### ISSUE TITLE
Feature Request: Image Hotspots

### ISSUE THREAD

**Issue by biben** [elementor/elementor#7282] opened 2019-03-03 19:36 UTC
## Prerequisites

- [X ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

I have Elementor Pro and what I am   missing is the function to add hotspots to an image. This function can be   found in the "ESSENTIAL ADDONS" plugin premiere version. It would   be great if you can add this in Elementor Pro version as well. Can you please   consider this in your upgrade work plan.
--

**What problem is your feature request going to solve? Please describe.**

It really would be a great feature having this in the paid version "Elementor Pro" instead of bying another plugin  for this feature. Could also be just that feature that more choose to buy the Pro-version of Elementor.

**Describe the solution you'd like**

I want this feature added in the Pro-version of Elementor

**Describe alternatives you've considered**

**Additional context**

**Comment by shilo-ey** [comment] 2019-03-04 16:07
Duplicate of #2768

**Closed by shilo-ey** 2019-03-04 16:07 UTC

**Comment by shilo-ey** [comment] 2021-06-08 12:19
This has been resolved in Elementor Pro v3.3.0

Feel free to update

Thanks!
