### ISSUE TITLE
Log-in widget

### ISSUE THREAD

**Issue by trevose** [elementor/elementor#10199] opened 2020-01-19 17:13 UTC
If a user enters an incorrect log-in I would like to be able to direct them to a website (non-private) page rather than to the standard wordpress log-in form

**Comment by bainternet** [comment] 2020-01-19 18:59
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.

**Comment by bainternet** [comment] 2020-01-19 18:59
Duplicate of #5355

**Closed by bainternet** 2020-01-19 18:59 UTC
