### ISSUE TITLE
Missing Sourcemap files

### ISSUE THREAD

**Issue by steve231293** [elementor/elementor#17311] opened 2021-12-28 03:56 UTC
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

Hello Elementor team,

Your plugin missing some soursemap files
![Screenshot at Dec 28 10-54-09](https://user-images.githubusercontent.com/7134267/147526295-55c84801-052e-4491-a561-29a5d48745a0.png)

Open Chrome Dev Tools then reload page.
This bug made WordPress Hooks run multi times

Please fix it

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by udidol** [comment] 2022-01-02 12:29
Hi @steve231293,
In what page did you encounter these warnings?

**Comment by steve231293** [comment] 2022-01-03 06:44
Hello @udidol,
You can see this issue on all pages built with Elementor.
Just please turn on Wordpress Debug in wp-config.php

```
define( 'WP_DEBUG', true );
define( 'SCRIPT_DEBUG', true );
```

**Comment by udidol** [comment] 2022-01-03 07:23
What version of Elementor/Pro are you using?

**Comment by steve231293** [comment] 2022-01-03 07:41
Hello @udidol 
I activated only Elementor ver 3.5.3

== Server Environment ==
	Operating System: Darwin
	Software: Apache/2.4.46 (Unix) mod_fastcgi/mod_fastcgi-SNAP-0910052141 PHP/7.2.34 OpenSSL/1.0.2u mod_wsgi/3.5 Python/2.7.13
	MySQL version: MySQL Community Server (GPL) v5.7.34
	PHP Version: 7.2.34
	PHP Max Input Vars: 1000
	PHP Max Post Size: 2048M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.8.2
	Site URL: http://dungnv.local/test/hello
	Home URL: http://dungnv.local/test/hello
	WP Multisite: No
	Max Upload Size: 2 GB
	Memory limit: 256M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: en-US
	Timezone: 0
	Admin Email: test@gmail.com
	Debug Mode: Active

== Theme ==
	Name: Hello Elementor
	Version: 2.4.2
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 3.5.3
		Author: Elementor.com


== Elementor Experiments ==
	Optimized DOM Output: Inactive
	Improved Asset Loading: Active
	Improved CSS Loading: Active
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Active by default
	Import Export Template Kit: Active by default
	Additional Custom Breakpoints: Active
	Hide native WordPress widgets from search results: Active by default
	Hello Theme Header & Footer: Inactive by default
	Landing Pages: Active by default
	Color Sampler: Active by default
	Favorite Widgets: Active by default
	Admin Top Bar: Active by default


== Log ==
	


== Elementor - Compatibility Tag ==

**Comment by udidol** [comment] 2022-01-04 07:17
Hey @steve231293 I'm sorry but I cannot reproduce these warnings.
If you could link to a live site where I can see this, that would help.

**Comment by steve231293** [comment] 2022-01-04 08:13
Hello @udidol 

Thanks for your reply. 
Please, could you confirm these:
**1: Your Dev-tool enable source map files?**

![Screenshot at Jan 04 14-32-50](https://user-images.githubusercontent.com/7134267/148024497-a092ae4c-6b81-4408-9fba-e7eeba0c2235.png)

**2: You added these code to wp-config.php**
```
define( 'WP_DEBUG', true );
define( 'SCRIPT_DEBUG', true );
```

This bug is hurting site performance so much because there are missing a lot of map files.
![Screenshot at Jan 04 15-12-07](https://user-images.githubusercontent.com/7134267/148028785-79ba0039-a7ca-48ca-b3ec-f16de05ff632.png)

Demo Site:
[https://test2.thememove.com/elementor-page/](https://test2.thememove.com/elementor-page/)

**Comment by udidol** [comment] 2022-01-04 08:50
Hi @steve231293,
Yes these settings are active.
I can see the issue in your demo site. I will pass this on to be taken care of.

Anyway, missing JS maps do not affect site performance.

**Comment by steve231293** [comment] 2022-01-04 08:56
@hi @udidol 
No, WordPress call all hooks when there is any 404 requests.
Number times re-call same as 404 requests

You can add this code to functions.php file to test:
```
function write_log( $log ) {
    if ( true === WP_DEBUG ) {
        if ( is_array( $log ) || is_object( $log ) ) {
            error_log( print_r( $log, true ) );
        } else {
            error_log( $log );
        }
    }
}

add_action('init', 'test_missing_map');

function test_missing_map() {
    write_log('total missing map file called');
}
```

Please Enable :
```
define( 'WP_DEBUG', true );
define( 'WP_DEBUG_LOG', true );
```

Then reload page and check log file.

**Comment by udidol** [comment] 2022-01-04 09:03
This happens asynchronously, so it doesn't affect load times.

**Comment by steve231293** [comment] 2022-01-04 09:06
Suppose, I have some heavy requests to server in WP Init Hook, This really hurting server side.

**Comment by udidol** [comment] 2022-01-04 09:12
The source map requests are sent by the browser, they are not being sent during the initial page load, so it doesn't affect page load times...

**Comment by steve231293** [comment] 2022-01-04 09:17
Okay, thank you for explaining.
Hope that you can fix bug in next version.

Thank you.

**Comment by arielk** [comment] 2022-08-26 14:59
I think this issue is already resolved so I'm closing issue for now. If the issue still exists, feel free to reopen.

**Closed by arielk** 2022-08-26 14:59 UTC
Labels: bug
