### ISSUE TITLE
🔗 🚀 Feature Request: Loop Builder - Add (Duplicate of #3140, Related to #20240)

### ISSUE THREAD

**Issue by cranstantinople** [elementor/elementor#20296] opened 2022-11-07 03:59 UTC
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

Post and Portfolio widgets have a lot of overlapping features but each is missing granular customization.

### Describe the solution you'd like

Loop building looks like it has the potential to replace both-- which I love.  I know it's a very early release but the ability to add a filter bar would get this a lot closer.

**Comment by black-eye** [comment] 2022-11-07 08:30
+1

**Comment by nicholaszein** [comment] 2022-11-09 14:27
Hello @cranstantinople!

Thank you for your submission! 🙏 

### 🔗 This issue is a Duplicate of #3140, and Related to #20240.

Which are on the same subject. 

For this reason, I'm closing this issue and 🔃 **Merging** it with the original, so we can have all the discussions in one location, and deal with it more efficiently.

Feel free to continue the conversation there. 😉 

### ✔️ Please, in the future, remember to check if there isn't an issue similar to yours already opened. 

Best regards,

Nick

**Closed by nicholaszein** 2022-11-09 14:27 UTC
Labels: request/enhancement, product/pro, component/loop-builder

**Comment by nicholaszein** [comment] 2023-08-02 01:16
Hello there!

We have great news! 🙌 

### 📢 We're happy to announce that this feature was released as the Taxonomy Filter widget for the Loop Builder with Elementor Pro v3.15.0! 🥳 

You can now place a standalone taxonomy filter widget anywhere on your layout and target one of the Loop Grid widgets on the page. You can also use multiple taxonomy filters.

You can learn more about this new feature here: https://elementor.com/help/taxonomy-filter-widget/

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
