### ISSUE TITLE
🔗 🐞 Bug Report: The save and back button is hidden in the Loop carousel widget. (Duplicate of #21316)

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#21328] opened 2023-02-14 11:17 UTC
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

In the Loop Carousel widget, the save and back button is displayed only for the first time. If we click the edit template button again, there will be no save and return button.

**tip** : There is an edit page button to go back, but the problem is that if we add the Loop Carousel at the bottom of the page, we have to scroll to the top of the page to access the edit page button, and that's not really cool.

**In the Loop Grid widget, this button is displayed well.**

### Steps to reproduce

https://user-images.githubusercontent.com/77163248/218720642-346a1092-700b-4c28-a64a-a365afbd1e49.mp4

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

[system-info-localhost-14-02-2023.txt](https://github.com/elementor/elementor/files/10731744/system-info-localhost-14-02-2023.txt)

**Comment by nicholaszein** [comment] 2023-02-16 13:09
Hello @79ho3ein!

Thank you for your submission! 🙏 

### 🔗 🐞 This issue is a Duplicate of #21316

Which is on the same subject. 

For this reason, I'm closing this thread and 🔃 **Merging** it with the original, so we can have all the discussions in one location, and deal with it more efficiently.

Feel free to continue the conversation there. 😉 

### 🔍 Please, in the future, remember to check if there isn't any thread similar to yours already opened. 

Best regards,

Nick

**Closed by nicholaszein** 2023-02-16 13:09 UTC
Labels: bug, type/design, component/loop-carousel

**Comment by nicholaszein** [comment] 2023-02-23 16:15
Hello there!

We have great news! 🙌 

### 📢 We're happy to announce that the issue you raised was resolved in Elementor Pro **v3.11.2**! 🥳 

✔️ Please feel free to check it out and update your plugin to the new version!

Cheers 🥂
