### ISSUE TITLE
🐞 Bug: Global Style settings don't work after updating Site Address with "Replace URL"

### ISSUE THREAD

**Issue by fleks** [elementor/elementor#14892] opened 2021-05-10 16:12 UTC
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

After changing the Wordpress Address/Site Address and replacing the URL via Elementor > Tools > Replace URL > Update Site Address the Global Settings for Colors, Fonts, Typography (...) doesn't work anymore at all, when Site Logo and/or Site Favicon is set with Elementor Site Settings > Site Identity.

## Steps to reproduce

Requirements: use of Global Styles &  Site Logo and/or Site Favicon is set with Elementor Site Settings > Site Identity.

Change Wordpress URL (with a different length than the old one!), update/replace URL with Elementor Tools, Regenerate CSS & check webpage's style

## Reason & Solution

The critical affected changes by the URL Replacement Tool happens in the `meta_value` of `meta_key = '_elementor_page_settings'` of Elementors "Default Kit" in the `wp_postmeta` database table. Here are only the string replaced without respect of the serialized saved `meta_value`-content of `meta_key = '_elementor_page_settings'`. Because of the difference of the length the content can't be read anymore, but no error appears.
After manually editing in the database the related length (`s:[length of URL]` ) of the URLs at 
`...;s:9:"site_logo";a:2:{s:3:"url";s:[length of URL]:"http://.../wp-content/uploads/....jpg";s:2:"id";i:39;}s:12:"site_favicon";a:2:{s:3:"url";s:[length of URL]:"http://.../wp-content/uploads/....png";s:2:"id";...` the Default Kit/Global Styles works fine again in the front-end after regenerating CSS.

**Solution**: Respect serialized saved values by replacing URL or better: store relative pathes in database

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Percona Server (GPL), Release '13', Revision '6f7822f' v8.0.22-13
	PHP Version: 7.4.13
	PHP Max Input Vars: 1500
	PHP Max Post Size: 32M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.7.1
	Site URL: http://wordpress.p587333.webspaceconfig.de // http://p587333.mittwaldserver.info
	Home URL: http://wordpress.p587333.webspaceconfig.de // http://p587333.mittwaldserver.info
	WP Multisite: No
	Max Upload Size: 32 MB
	Memory limit: 256M
	Permalink Structure: /%category%/%postname%/
	Language: de-DE
	Timezone: Europe/Berlin
	Debug Mode: Active

== Theme ==
	Name: Hello Elementor Child
	Version: 1.0.0
	Author: FH &
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.3.1
	Parent Theme Author: Elementor Team
```
</details>

**Comment by shilo-ey** [comment] 2021-06-13 15:29
Thanks.

Caused by: https://github.com/elementor/elementor/pull/13912

Will be reverted and released soon.

**Comment by d19dotca** [comment] 2021-06-16 15:54
Looks like it was released with core 3.2.5 today.

**Comment by shilo-ey** [comment] 2021-06-17 06:57
This issue has been resolved in Elementor v3.2.5

Feel free to update

Thanks!

**Closed** 2021-06-17 06:57 UTC
Labels: bug, status/merged

**Comment by euene** [comment] 2021-06-17 13:51
Looks like Elementor v3.2.5 was pulled from the WordPress repository today and the latest version is v3.2.4 now. What happened?

**Comment by shilo-ey** [comment] 2021-06-17 14:06
> Looks like Elementor v3.2.5 was pulled from the WordPress repository today and the latest version is v3.2.4 now. What happened?

Thank you @euene ,

This was caused by an issue with our latest dev releases.
We updated the latest stable tag in WP repository back to v3.2.5

Nice catch!
