### ISSUE TITLE
🔗 🚀 Feature Request: Custom shape divider + custom position (Duplicate of #2729) (Related to #20522)

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#19368] opened 2022-08-06 12:25 UTC
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

One of the most important features that elementor lacks is Custom shape divider. If I'm not mistaken, it was supposed to be added before. But it is not known what happened that did not happen. Anyway, I have suggestions for the development of shape divider, please check them if possible.

**1- Custom shape divider (svg, image)**
Using a custom shape divider is great. A [size & rotate control](https://prnt.sc/47EVg3yfwlgE) is essential for this feature.

**2- Custom position for Custom shape divider**
Currently, we can only display the shape divider at the top or bottom. This is a big limitation. We also need to be able to display it on the right or left.
**My suggestion is to remove [these two options](https://prnt.sc/UXx6ecHkXDcN).**  There will be no need for these two. If you add [such controls](https://prnt.sc/mca_XxOnSrUT) for shape divider. This will be super awesome and optimal.

**3- The possibility of using several shape dividers in each container**
I said in #2 that my suggestion is to remove the top and bottom options in the shape divider. But there is a much smarter solution instead : https://prnt.sc/fVtlxp1F9hVI
This solution has several advantages : 
A : It is much more useful
B : We can create several shape dividers in one container.
C : Everything will be organized, simple and very professional.

**details**
If we click on add item, [This section](https://prnt.sc/Y6zQhVKrnCW8) is displayed first. Here, the label option simply specifies the name of the shape divider. In the type option, we can specify the shape divider to be displayed in the form of the previous options. **or custom shape divider**.
Customization options in former shape dividers and custom shape dividers are somewhat different.

**So if we choose former shape dividers, we will have these options for customization :**
color - Width - Height - Invert - Bring to Front - opacity (new) - Position (up, down, left, right)

**But if we choose the type Custom shape divider, we will have these options for customization :**
color - Bring to Front - opacity (new) - size - rotate - [Custom position](https://prnt.sc/8vfKtXSvMxSj) & Entrance Animation.

I hope the explanations were useful. I also hope you put it on your roadmap.

thank you!

### Describe the solution you'd like

-

**Comment by rami-elementor** [comment] 2022-08-06 13:08
@79ho3ein Please start uploading images to GitHub issues. It's very hard to read you bug reports and open new windows to understand your bug reports.

**Comment by 79ho3ein** [comment] 2022-08-06 13:11
> @79ho3ein Please start uploading images to GitHub issues. It's very hard to read you bug reports and open new windows to understand your bug reports.

I apologize. I will definitely do it from now on.

**Comment by nicholaszein** [comment] 2022-11-27 10:15
Hello @79ho3ein!

Thank you for your submission! 🙏 

### 🔗 This issue is a Duplicate of #2729.

Which is on the same subject. 

For this reason, I'm closing this issue and 🔃 **Merging** it with the original, so we can have all the discussions in one location, and deal with it more efficiently.

Feel free to continue the conversation there. 😉

Best regards,

Nick

**Closed by nicholaszein** 2022-11-27 10:15 UTC
Labels: request/enhancement, type/developer-api, type/design, component/shape-divider

**Comment by nicholaszein** [comment] 2022-11-27 10:21
Related to #20522
