### ISSUE TITLE
Accordion with ACF

### ISSUE THREAD

**Issue by Yonimantin** [elementor/elementor#10201] opened 2020-01-19 18:30 UTC
Hello
Is there a way to integrate ACF pro (repeter) with the Elementor  accordion, I want to create dynamic content and not find the way to do it with existing tools.
Thanks

**Comment by bainternet** [comment] 2020-01-19 18:52
Thanks,

Please create GitHub issues only for bugs reports and feature requests. 
GitHub issues **ARE NOT FOR SUPPORT!**

- If you have questions or need general support, Please try:

* [Elementor Community](https://www.facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org 
* [Elementor Developers docs](https://developers.elementor.com/)

If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email for details.


thanks.

**Comment by bainternet** [comment] 2020-01-19 18:53
Duplicate of #5979

**Closed by bainternet** 2020-01-19 18:53 UTC

**Comment by Yonimantin** [comment] 2020-01-19 19:03
Hi Raz
The issue is for feature request (to enable to migrate ACF repeter with
Elementor accordion)


בתאריך יום א׳, 19 בינו׳ 2020, 20:53, מאת Raz Ohad ‏<notifications@github.com
