### ISSUE TITLE
Break Points 

### ISSUE THREAD

**Issue by KoshaK0** [elementor/elementor#9687] opened 2019-11-26 11:19 UTC
## Prerequisites

- [X ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Elementor have the option to style widgets for mobile devices by pressing the device icon next to option. I always was wondering why this is done per specific options only and not ALL of the options has the ability to be configured for other devices. This is also common mistake and question in Elementor Facebook Group, that people switching to mobile device view and just edit the widgets appearance in and when back to desktop it's also edited, simply case the options they have edited does not have the ability to be edited for mobile device. 

**Describe the solution you'd like**
So, the question is Why not make the different files for Desktop, Tablet, and Mobile, when you editing in one of the modes, the CSS written into the different CSS files, so EVERY options in the widget can be edited for different devices?  

**Describe alternatives you've considered**

**Additional context**

**Comment by Bovelett** [comment] 2019-11-30 11:06
Hey @KoshaK0 In this thread https://github.com/elementor/elementor/issues/2043 breakpoints are being actively discussed. Maybe you want to add your request there? Because that thread has the dev teams attention since there are so many respondents and has been  officially labeled as request / enhancement.

**Comment by arielk** [comment] 2020-05-01 14:46
Duplicate of #2043

**Closed by arielk** 2020-05-01 14:46 UTC
Labels: performance, responsive
