### ISSUE TITLE
 set custom image path

### ISSUE THREAD

**Issue by kbrothers** [elementor/elementor#8720] opened 2019-07-30 09:33 UTC
Hi
You have good products but ...

i have use abc.com domain and my image path is xyz.com/image.png

how can i set in abc.com without upload abc.com

at time we i do there are say choose image the i click there are say upload images or use your media file image

how can i have set custom image path like xyz.com/images.png

plz help me or guild me or tech me

**Comment by bainternet** [comment] 2019-07-30 09:39
Thanks for the feedback,
Please follow guidelines for opening a new [feature request](https://github.com/pojome/elementor/issues/new?template=Feature_request.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Description and examples.

**Comment by bainternet** [comment] 2019-07-30 09:39
Duplicate of #413

**Closed by bainternet** 2019-07-30 09:39 UTC

**Comment by kbrothers** [comment] 2019-07-30 10:23
Where i  see 

![image](https://user-images.githubusercontent.com/3642382/62121861-1cf9d980-b2e2-11e9-9bea-549608b9b5a6.png)

what i do for that see my ...
