### ISSUE TITLE
🔗 🚀 Feature Request: Restrict elements **in the editor** by role

### ISSUE THREAD

**Issue by doctorgrondo** [elementor/elementor#20332] opened 2022-11-09 01:58 UTC
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

Elementor's Role Manager functionality allows us to restrict which user roles have access to add/remove elements in the editor mode. However, this is all or nothing. There is no way to allow users access to a subset of elements. For example, if I want to give a user access just to add images, I can't just give them access to the images element, I must give them access to _all_ Elementor elements (or none at all).

### Describe the solution you'd like

**Please add more granular controls in the Role Manager**, specifically the ability to create subsets of elements (similar to the "favourites" subset) that can be accessed in the editor only by permitted user roles.

For example, I would like to create a subset of elements that includes the header, text and images elements and allow users with the Editor role access to elements in that subset, but none of the others.

### Describe alternatives you've considered

I haven't found any plug in or custom code to achieve this functionality. The only alternative is to allow access to all elements in the editor, however this exposes an unnecessary risk to site integrity.

### Additional context
![image](https://user-images.githubusercontent.com/3069068/200721609-484b9316-b50e-46aa-9113-d3d7cd43b1fc.png)

**Comment by doctorgrondo** [comment] 2022-11-10 05:05
Additionally, can we have the option to make the "Submissions" section available to other roles, such as Authors and Editors? I would like to let my users manage responses to various forms without them requiring to have the Administrator role.

**Comment by nicholaszein** [comment] 2022-11-14 06:35
Hello @doctorgrondo!

Thank you for your submission! 🙏 

### 🔗 This issue is a Duplicate of #1314

Which is on the same subject. 

For this reason, I'm closing this issue and 🔃 **Merging** it with the original, so we can have all the discussions in one location, and deal with it more efficiently.

Feel free to continue the conversation there. 😉 

### ✔️ Please, in the future, remember to check if there isn't an issue similar to yours already opened. 

Best regards,

Nick

**Closed by nicholaszein** 2022-11-14 06:35 UTC
Labels: request/enhancement, editor, status/merged, component/role-manager, type/workflow, solved, mod*, editor/widget-panel, widgets, product/3.19

**Comment by nicholaszein** [comment] 2024-04-12 05:15
Hello!

### 📢 We're happy to announce that the issue you raised was resolved in Elementor v3.18.0, and improved with Elementor Pro 3.19.0! 🥳 

You can now use the Element Manager to decide what widgets should appear in the Editor and your website, and with Elementor Pro you can decide who can use those widgets. To learn more check the [documentation in the Help Center](https://elementor.com/help/element-manager/).

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
