### ISSUE TITLE
✅ 🐞 Bug report: Hotspot widget - tooltip box width issue

### ISSUE THREAD

**Issue by twerkema** [elementor/elementor#18930] opened 2022-06-14 12:34 UTC
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Using Elementor 3.6.6 and Elementor Pro 3.7.1 with container experiment on. 

Changing width of tooltip box using widget Style > Box > Width doesn't work. Text continues to run wide with nowrap and I'm not able to override. Elementor's code is:
.e-hotspot__tooltip {white-space: var(--white-space,nowrap);

![Screen Shot 2022-06-14 at 8 31 11 AM](https://user-images.githubusercontent.com/41759677/173577652-af66e358-0924-404e-ad2c-361aec6417c3.jpg)
![Screen Shot 2022-06-14 at 8 29 29 AM](https://user-images.githubusercontent.com/41759677/173577665-aafcb560-66e6-4d24-bd38-76fc02a04f50.jpg)

### Steps to reproduce

1. Insert hotspot widget. 
2. Enter in relevant info. 
3. Adjust Width under Style settings. 
4. Nothing happens.

### Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [x] I can reproduce this bug consistently using the steps above.

### System Info

[System Info removed by moderation]

**Comment by About2git** [comment] 2022-09-22 09:02
I can confirm the Problem persists in Elementor Version 3.7.7 & Elementor Pro Version 3.7.7 and Container/Flexbox Experiment enabled…

**Comment by ipassas** [comment] 2022-10-03 16:19
Has anyone find any solution? Even with custom css.

**Comment by Andersonski** [comment] 2022-10-18 16:09
Same Problem still exists....

**Comment by joelinit1** [comment] 2022-10-26 13:46
The below CSS works for me, where width of the tooltip is obviously adjusted to your preference:

`.e-hotspot__tooltip {
    width: 30vw;
    white-space: var(--white-space,wrap);
}`

**Comment by anekdamian** [comment] 2022-11-02 21:33
Can confirm that @joelinit1's solution works! Thank you for this!

**Comment by yorkfrog** [comment] 2022-11-07 10:26
still present in 3.8.
Can confirm that @joelinit1's solution works in 3.8, thanks.
C.

**Comment by BlackBike** [comment] 2023-04-10 00:18
Thanks for the fix @joelinit1 👍

**Comment by bentographics** [comment] 2023-09-29 05:43
I have the same issue, tool tip box width can't be adjusted.
Please fix this as soon as possible, we'll need this for a client project.

Also, don't understand why people refer to Elementor 3.8. The current versions (29, Sept 2023) are the below, and it's still not working):
Elementor: 3.16.4 
Elementor Pro: 3.16.2

**Comment by phkoon** [comment] 2024-01-09 20:20
> Also, don't understand why people refer to Elementor 3.8.

If look at the previous comments' dates, they're from November 2022 and before...

**Comment by wschaefer1** [comment] 2024-01-29 21:27
It's now Jan 29, 2004 and the problem still goes on with Elementor 3.19. And joelinit1's answer worked! Thanks.

**Comment by nicholaszein** [comment] 2024-07-21 03:02
Hello everyone!

We have great news! 🙌 

### 📢 We're happy to announce that the issue you raised was resolved in Elementor Pro v3.23.0! 🥳 

You can now set a min and max width for the tooltip box.

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂

**Closed by nicholaszein** 2024-07-21 03:02 UTC
Labels: bug, type/responsive, product/pro, status/merged, type/layout, solved, mod*, widget/hotspot, product/3.23
