### ISSUE TITLE
⛔ Image Lazy Load functionality does not lazy load background images set on unconventional elements

### ISSUE THREAD

**Issue by jazir555** [elementor/elementor#27638] opened 2024-06-09 04:56 UTC
### Prerequisites

- [X] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [X] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

Lazy load functionality does not work on background images set on a spacer element. I can understand why as this is a weird unconventional implementation. The template kit "Growth Vibe" implements all of their background images via spacers in the advanced section.

The current implementation of lazy load misses multiple background images attached to spacers, which leaves a sizable amount of performance on the table. I cannot get them to lazy load even with perfmatters or flyingpress. It would be great if the lazyload functionality could be updated to support lazy loading images set as the background image in the advanced tab on spacer and other unconventional usage of image backgrounds in the advanced setting on all elements.

If necessary, I can provide access to the domain this is occurring on.

### Steps to reproduce

1. Set a background image on a spacer in the advanced section. Ideally multiple spacers (lets say 10), out of the viewport. Use separate images on each spacer element.
2. Enable the background image lazyloading experiment.
3. Multiple background images that should be lazyloaded as they are out of the viewport are still loaded on the initial page load

### Expected behavior

All images out of the viewport should be lazy loaded when both image lazy loading experiments are activated within the Elementor features section.

### Isolating the problem

- [X] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [ ] This bug happens with the Hello Elementor theme active.
- [X] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

<details>
<summary>Click to reveal</summary>

````txt


== Server Environment ==
	Operating System: Linux
	Software: LiteSpeed
	MySQL version: MariaDB Server v10.6.17
	PHP Version: 8.1.28
	PHP Memory Limit: 256M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 128M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.5.4
	WP Multisite: No
	Max Upload Size: 128 MB
	Memory limit: 1024M
	Max Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en_US
	Timezone: -8
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 3.0.2
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en-US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36

== Active Plugins ==
	Advanced Database Cleaner PRO
		Version: 3.2.8
		Author: Younes JFR.

	Asset CleanUp Pro: Page Speed Booster
		Version: 1.2.4.9
		Author: Gabe Livan

	Debloat
		Version: 1.2.8
		Author: asadkn

	Disable Bloat for WordPress &amp; WooCommerce
		Version: 3.4.8
		Author: Disable Bloat

	Disable Gutenberg
		Version: 3.1.1
		Author: Jeff Starr

	Docket Cache
		Version: 23.08.02
		Author: Nawawi Jamili

	Duplicate Page
		Version: 4.5.3
		Author: mndpsingh287

	Duplicator Pro
		Version: 4.5.16.3
		Author: Duplicator

	Elementor
		Version: 3.21.8
		Author: Elementor.com

	Elementor Pro
		Version: 3.21.3
		Author: Elementor.com

	Envato Elements
		Version: 2.0.13
		Author: Envato

	File Manager Advanced
		Version: 5.2.4
		Author: modalweb

	Flying Pages
		Version: 2.4.6
		Author: WP Speed Matters

	FlyingPress
		Version: 4.13.3
		Author: FlyingWeb

	Hide admin notices
		Version: 3.1.0
		Author: Rémi Leclercq

	HTTP Requests Manager
		Version: 1.3.1
		Author: veppa

	Minify HTML
		Version: 2.1.9
		Author: Tim Eckel

	Perfmatters
		Version: 2.3.0
		Author: forgemedia

	Post Type Switcher
		Version: 3.3.1
		Author: Triple J Software, Inc.

	Rank Math SEO with AI Best SEO Tools
		Version: 1.0.220
		Author: Rank Math

	Scalability Pro
		Version: 5.57
		Author: Dave Hilditch

	Show IDs by Echo
		Version: 1.1.3
		Author: Echo Plugins

	Stream
		Version: 4.0.0
		Author: XWP

	WPCode Lite
		Version: 2.1.12
		Author: WPCode

	WPO Tweaks &amp; Optimizations
		Version: 1.0.4
		Author: Fernando Tellado

	WP Tweaks
		Version: 2.3.4
		Author: Luiz Bills


== Must-Use Plugins ==
	Asset CleanUp Pro: Plugin Filtering
		Version: 1.0
		Author: Gabriel Livan


== Features ==
	Custom Fonts: 0
	Custom Icons: 0

== Integrations ==
	


== Elementor Experiments ==
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Active by default
	Additional Custom Breakpoints: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active by default
	Upgrade Swiper Library: Active by default
	Grid Container: Inactive
	Nested Elements Performance: Inactive by default
	Optimized Control Loading: Active
	Default to New Theme Builder: Active by default
	Hello Theme Header &amp; Footer: Inactive
	Elementor Home Screen: Active by default
	Editor Top Bar: Active
	Build with AI: Active by default
	Landing Pages: Inactive
	Nested Elements: Active
	Lazy Load Background Images: Active
	Pages Panel: Inactive by default
	Display Conditions: Inactive by default
	Form Submissions: Active by default
	Menu: Inactive by default
	Taxonomy Filter: Inactive by default


== Log ==
	
Log: showing 20 of 342024-03-15 22:14:09 [info] elementor::elementor_updater Started 
2024-03-15 22:14:09 [info] Elementor/Upgrades - _on_each_version Start  
2024-03-15 22:14:09 [info] Elementor/Upgrades - _on_each_version Finished 
2024-03-15 22:14:09 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.19.4',
  'to' => '3.20.0',
)]
2024-03-15 22:14:09 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.19.4',
  'to' => '3.20.0',
)]
2024-03-15 22:14:10 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.19.3',
  'to' => '3.20.0',
)]
2024-03-15 22:15:09 [info] elementor::elementor_updater Started 
2024-03-15 22:15:09 [info] Elementor/Upgrades - _on_each_version Start  
2024-03-15 22:15:09 [info] Elementor/Upgrades - _on_each_version Finished 
2024-03-15 22:15:09 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.20.0',
  'to' => '3.20.1',
)]
2024-04-15 13:57:27 [info] elementor::elementor_updater Started 
2024-04-15 13:57:27 [info] Elementor/Upgrades - _on_each_version Start  
2024-04-15 13:57:27 [info] Elementor/Upgrades - _on_each_version Finished 
2024-04-15 13:57:27 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.20.1',
  'to' => '3.21.0',
)]
2024-04-15 13:57:27 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.20.1',
  'to' => '3.21.0',
)]
2024-04-18 16:10:35 [info] elementor::elementor_updater Started 
2024-04-18 16:10:35 [info] Elementor/Upgrades - _on_each_version Start  
2024-04-18 16:10:35 [info] Elementor/Upgrades - _on_each_version Finished 
2024-04-18 16:10:35 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.21.0',
  'to' => '3.21.1',
)]
2024-04-18 16:10:35 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.21.0',
  'to' => '3.21.1',
)]

PHP: showing 8 of 8PHP: 2024-03-22 22:33:05 [warning X 9][../wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::179] Undefined array key &quot;editor_post_id&quot; [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-04-15 13:57:27 [warning X 1][../wp-content/plugins/elementor/core/files/manager.php::111] unlink(../wp-content/uploads/elementor/css/custom-widget-icon-box.min.css): No such file or directory [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-04-15 13:57:27 [warning X 1][../wp-content/plugins/elementor/core/files/manager.php::111] unlink(../wp-content/uploads/elementor/css/custom-widget-icon-list.min.css): No such file or directory [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-05-01 15:16:09 [warning X 11][../wp-content/plugins/elementor/includes/elements/container.php::1831] Undefined array key &quot;size&quot; [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-06-08 12:40:20 [warning X 2][../wp-content/plugins/elementor/includes/conditions.php::87] Undefined array key &quot;background_color&quot; [array (
  'trace' => '
#0: ../wp-content/plugins/elementor/includes/conditions.php(87): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: ../wp-content/plugins/elementor/includes/conditions.php(83): Elementor\Conditions :: check()
#2: ../wp-content/plugins/elementor/includes/base/controls-stack.php(1428): Elementor\Conditions :: check()
#3: ../wp-content/plugins/elementor/includes/base/controls-stack.php(1212): Elementor\Controls_Stack -> is_control_visible()
#4: ../wp-content/plugins/elementor/core/base/elements-iteration-actions/assets.php(22): Elementor\Controls_Stack -> get_active_settings()
',
)]
PHP: 2024-06-08 12:40:20 [warning X 2][../wp-content/plugins/elementor/includes/conditions.php::87] Undefined array key &quot;background_color_b&quot; [array (
  'trace' => '
#0: ../wp-content/plugins/elementor/includes/conditions.php(87): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: ../wp-content/plugins/elementor/includes/conditions.php(83): Elementor\Conditions :: check()
#2: ../wp-content/plugins/elementor/includes/base/controls-stack.php(1428): Elementor\Conditions :: check()
#3: ../wp-content/plugins/elementor/includes/base/controls-stack.php(1212): Elementor\Controls_Stack -> is_control_visible()
#4: ../wp-content/plugins/elementor/core/base/elements-iteration-actions/assets.php(22): Elementor\Controls_Stack -> get_active_settings()
',
)]
PHP: 2024-06-08 16:57:53 [warning X 12][../wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php::150] Undefined array key &quot;condition_type&quot; [array (
  'trace' => '
#0: ../wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(150): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_template_json_item()
#2: ../wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(120): class type array_map()
#3: ../wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(59): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_templates_json()
#4: ../wp-content/plugins/elementor/data/base/endpoint.php(158): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> get_items()
',
)]
PHP: 2024-06-08 17:12:55 [warning X 1][../wp-content/plugins/elementor/includes/conditions.php::87] Undefined array key &quot;background_color_b&quot; [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 1 of 1JS: 2024-05-01 23:25:04 [error X 2][../wp-includes/js/jquery/jquery.min.js:2:28760] Cannot read properties of undefined (reading &#039;value&#039;) 



== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatible
	Envato Elements: Incompatible

== Elementor Pro - Compatibility Tag ==
	
	Envato Elements: Incompatible

````

</details>

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by nicholaszein** [comment] 2024-09-02 00:11
Hello @jazir555!

Thank you for submitting your issue, and apologies for the delay in the response.

This is more of a Feature Request, not a bug. We consider a bug when there is an error in the code, or when a feature is not working as intended. However, in this case, the Lazy-Load Background Images feature is meant to work only with Containers, not any other element. So in your case, this is more of a missing feature, which should be submitted in the Feature Request Category, in Discussions.

As you can see in [this blog post](https://developers.elementor.com/elementor-3-21-developers-update/#:~:text=We%20should%20also%20note%20that%20the%20new%20experiment%20applies%20only%20to%20container%20background%20images%2C%20not%20to%20sections/columns.), Elementor will only lazy-load Background Images of Containers.

I'm closing this issue as not a bug.

Thank you for contributing!

Kind regards

**Closed by nicholaszein** 2024-09-02 00:11 UTC
Labels: type/performance, widget/spacer, mod*, component/lazy-load-bg-images, mod/r*
