### ISSUE TITLE
🐞 Bug report: Preview no longer launches a preview

### ISSUE THREAD

**Issue by sviteknology** [elementor/elementor#18366] opened 2022-04-05 22:18 UTC
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest development version of Elementor.

### Description

After activating Container/component experiment the preview (eye icon) no longer launches a preview nor updates the exisiting preview 

### Steps to reproduce

Make edits to items  (editing with elementor on cloud) choose update - no update to preview (browser window or tab) occurs

try clicking on preview icon (eye) - no update to preview (browser window or tab) occurs - if preview window is no already open, clicking on preview does not launch a preview window (browser window or tab)

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro) with development versions.
- [X] This bug happens with a vanilla WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: nginx/1.18.0
	MySQL version: (Google) v5.7.36
	PHP Version: 7.4.26
	PHP Memory Limit: 128M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 51M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.9.2
	Site URL: https://houseofwuli.com
	Home URL: https://houseofwuli.com
	WP Multisite: No
	Max Upload Size: 50 MB
	Memory limit: 512M
	Max Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: America/Chicago
	Admin Email: audra.sviteknology@gmail.com
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.5.0
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.60 Safari/537.36

== Active Plugins ==
	Activity Log
		Version: 2.8.3
		Author: Activity Log Team

	Classic Editor
		Version: 1.6.2
		Author: WordPress Contributors

	Duplicate Page
		Version: 4.4.8
		Author: mndpsingh287

	Elementor
		Version: 3.6.2
		Author: Elementor.com

	Elementor Pro
		Version: 3.6.4
		Author: Elementor.com

	Essential Addons for Elementor
		Version: 5.0.12
		Author: WPDeveloper

	SchedulePress (Formerly Known as WP Scheduled Posts)
		Version: 4.1.4
		Author: WPDeveloper

	WPForms Lite
		Version: 1.7.3
		Author: WPForms

== Must-Use Plugins ==
	Elementor Safe Mode
		Version: 1.0.0
		Author: Elementor.com

== Elements Usage ==
	
	archive : 1
		archive-posts : 1
		form : 1
		heading : 2
		posts : 1
		text-editor : 1
	footer : 3
		form : 2
		heading : 4
		image-box : 1
		media-carousel : 1
		sitemap : 1
		social-icons : 2
		text-editor : 4
		theme-site-logo : 1
	header : 3
		animated-headline : 1
		image : 1
		nav-menu : 2
		search-form : 1
		social-icons : 1
		theme-site-logo : 2
	popup : 2
		call-to-action : 1
		form : 2
		heading : 1
		spacer : 1
		text-editor : 2
	widget : 0
		animated-headline : 1
	wp-post : 10
		text-editor : 10
	wp-page : 3
		call-to-action : 1
		container : 2
		form : 2
		heading : 7
		icon-list : 1
		posts : 4
		spacer : 1
		text-editor : 5
	single-post : 4
		heading : 2
		post-info : 1
		post-navigation : 1
		posts : 1
		share-buttons : 1
		theme-post-content : 1
		theme-post-excerpt : 1
		theme-post-featured-image : 1
		theme-post-title : 1
	search-results : 1
		archive-posts : 1
		heading : 1
		text-editor : 1
	error-404 : 2
		button : 1
		heading : 4
		search-form : 1
		text-editor : 1

== Elementor Experiments ==
	Optimized DOM Output: Active by default
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Active by default
	Import Export Template Kit: Active
	Additional Custom Breakpoints: Active by default
	Hide native WordPress widgets from search results: Active by default
	: Inactive by default
	Flexbox Container: Active
	Default to New Theme Builder: Active by default
	Hello Theme Header & Footer: Inactive
	Landing Pages: Active by default
	Color Sampler: Active
	Favorite Widgets: Active by default
	Admin Top Bar: Active by default
	Page Transitions: Active by default
	Form Submissions: Active by default
	Scroll Snap: Inactive

== Log ==
	
PHP: showing 5 of 5PHP: 2022-03-28 16:54:56 [notice X 39][/mnt/customers-man/customers-el-3530151-24204-houseofwuli-wordpress-pvc-624029c8b23998001e77ba12/wp-content/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-04-01 12:23:13 [error X 8][/mnt/customers-man/customers-el-3530151-24204-houseofwuli-wordpress-pvc-624029c8b23998001e77ba12/wp-content/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::286] Uncaught Error: Call to a member function update_meta() on bool in /mnt/customers-man/customers-el-3530151-24204-houseofwuli-wordpress-pvc-624029c8b23998001e77ba12/wp-content/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:286
Stack trace:
#0 /mnt/customers-man/customers-el-3530151-24204-houseofwuli-wordpress-pvc-624029c8b23998001e77ba12/wp-content/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(167): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions()
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions()
#2 /mnt/customers-man/customers-el-3530151-24204-houseofwuli-wordpress-pvc-624029c8b23998001e77ba12/wp-content/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func()
#3 /mnt/customers-man/customers-el-3530151-24204-houseofwuli-wordpress-pvc-624029c8b23998001e77ba12/wp-content/wp-includes/class-wp-hook.php [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-04-01 14:13:16 [error X 1][/mnt/customers-man/customers-el-3530151-24204-houseofwuli-wordpress-pvc-624029c8b23998001e77ba12/wp-content/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::286] Uncaught Error: Call to a member function update_meta() on null in /mnt/customers-man/customers-el-3530151-24204-houseofwuli-wordpress-pvc-624029c8b23998001e77ba12/wp-content/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:286
Stack trace:
#0 /mnt/customers-man/customers-el-3530151-24204-houseofwuli-wordpress-pvc-624029c8b23998001e77ba12/wp-content/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(167): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions()
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions()
#2 /mnt/customers-man/customers-el-3530151-24204-houseofwuli-wordpress-pvc-624029c8b23998001e77ba12/wp-content/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func()
#3 /mnt/customers-man/customers-el-3530151-24204-houseofwuli-wordpress-pvc-624029c8b23998001e77ba12/wp-content/wp-includes/class-wp-hook.php [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-04-04 06:59:14 [notice X 1][/mnt/customers-man/customers-el-3530151-24204-houseofwuli-wordpress-pvc-624029c8b23998001e77ba12/wp-content/wp-content/plugins/elementor-pro/modules/query-control/module.php::737] Undefined index: filter_type [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-04-05 14:34:58 [error X 2][/mnt/customers-man/customers-el-3530151-24204-houseofwuli-wordpress-pvc-624029c8b23998001e77ba12/wp-content/wp-content/plugins/elementor/core/frontend/render-mode-manager.php::133] Uncaught Requests_Exception_HTTP_403: 403 Forbidden in /mnt/customers-man/customers-el-3530151-24204-houseofwuli-wordpress-pvc-624029c8b23998001e77ba12/wp-content/wp-content/plugins/elementor/core/frontend/render-mode-manager.php:133
Stack trace:
#0 /mnt/customers-man/customers-el-3530151-24204-houseofwuli-wordpress-pvc-624029c8b23998001e77ba12/wp-content/wp-content/plugins/elementor/core/frontend/render-mode-manager.php(151): Elementor\Core\Frontend\Render_Mode_Manager->add_current_actions()
#1 /mnt/customers-man/customers-el-3530151-24204-houseofwuli-wordpress-pvc-624029c8b23998001e77ba12/wp-content/wp-content/plugins/elementor/includes/frontend.php(192): Elementor\Core\Frontend\Render_Mode_Manager->__construct()
#2 /mnt/customers-man/customers-el-3530151-24204-houseofwuli-wordpress-pvc-624029c8b23998001e77ba12/wp-content/wp-includes/class-wp-hook.php(307): Elementor\Frontend->init_render_mode()
#3 /mnt/customers-man/customers-el-3530151-24204-houseofwuli-wordpress-pvc-624029c8b23998001e77ba12/wp-content/wp [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 5 of 5JS: 2022-04-01 17:21:03 [error X 3][https://houseofwuli.elementor.cloud/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.6.1:2:603704] elementorFrontend is not defined 
JS: 2022-04-01 21:36:12 [error X 16][https://houseofwuli.elementor.cloud/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.6.1:2:627961] Cannot read properties of undefined (reading \'settings\') 
JS: 2022-04-01 21:36:17 [error X 23][https://houseofwuli.elementor.cloud/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.6.1:2:631106] Cannot read properties of undefined (reading \'view\') 
JS: 2022-04-02 01:02:21 [error X 2][https://houseofwuli.elementor.cloud/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.6.1:2:515679] Cannot read properties of null (reading \'getBoundingClientRect\') 
JS: 2022-04-05 18:23:32 [error X 1][https://houseofwuli.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view58427\") has already been destroyed and cannot be used. 

Log: showing 6 of 62022-04-05 14:12:00 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.1',
  'to' => '3.6.2',
)]
2022-04-05 14:12:02 [info] elementor::elementor_updater Started 
2022-04-05 14:12:02 [info] Elementor/Upgrades - _on_each_version Start  
2022-04-05 14:12:02 [info] Elementor/Upgrades - _on_each_version Finished 
2022-04-05 14:12:02 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.1',
  'to' => '3.6.2',
)]
2022-04-05 14:12:03 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.1',
  'to' => '3.6.2',
)]

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatible
	Essential Addons for Elementor: Compatible

== Elementor Pro - Compatibility Tag ==
	
	Essential Addons for Elementor: Compatible

**Comment by rami-elementor** [comment] 2022-04-10 18:12
Duplicate of #18362

**Closed by rami-elementor** 2022-04-10 18:12 UTC
Labels: bug, product/developer-edition
