### ISSUE TITLE
🚀 Feature Request: Visibility logic for widgets, columns & sections AND make columns clickable

### ISSUE THREAD

**Issue by abbasdv** [elementor/elementor#18181] opened 2022-03-17 22:32 UTC
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

I would love to be able to hide/show different parts of my website based on some logic, especially if I want to hide parts from logged out users etc.

I'm using a plugin for this purpose but I feel like it should be something Elementor provides. Same thing with clickable columns, I'm using code for this purpose and once again I feel this should be a feature of Elementor.

### Describe the solution you'd like

Visibility logic for widgets, columns and sections. Display or do not display for logged in/logged out users, different roles etc.

Clickable columns. Making boxes of columns should be clickable.

**Comment by pauserratgutierrez** [comment] 2022-03-18 20:14
Conditional logic (#2638)
The new upcomming version adds the new containers which allows us to make sections and containers to be clickable.

**Comment by rami-elementor** [comment] 2022-03-20 10:52
Duplicate of #2638

**Closed by rami-elementor** 2022-03-20 10:52 UTC
Labels: request
