### ISSUE TITLE
With update 2.5.1 my Custom querys for posts are now broken

### ISSUE THREAD

**Issue by dvalledor** [elementor/elementor#7645] opened 2019-03-27 18:43 UTC
## Prerequisites

- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by dvalledor** [comment] 2019-03-27 18:45
"Fatal error: Can't use method return value in wright context in public_html/wp-content/plugins/elementor-pro/modules/query-control/classes/elementor-post-query.php on line 53

**Comment by tamelander** [comment] 2019-03-27 22:23
Elementor Pro 2.5.1. I had a query with manual search for two posts. The query rendered and included the Woocommerce cart and three other unwanted posts. I can confirm that update to 2.5.2. fixed the bug.

**Comment by Elementalel** [comment] 2019-03-28 07:38
Can confirm.

Custom Card Query is broken, as well as the global widget's image size. The latter looks good when editing but gets messed up irl. Please fix asap!

**Comment by Miheix** [comment] 2019-03-28 07:53
The bugg is still present.
Fatal error: Can not use method return value in write context in /web/wp-content/plugins/elementor-pro/modules/query-control/classes/elementor-post-query.php online 53

**Comment by Miheix** [comment] 2019-03-28 08:08
> 
> 
> The bugg is still present.
> Fatal error: Can not use method return value in write context in /web/wp-content/plugins/elementor-pro/modules/query-control/classes/elementor-post-query.php online 53

v. 2.5.2

**Comment by shilo-ey** [comment] 2019-03-28 08:43
@dvalledor @Miheix @Elementalel Please paste here your system info (including PHP version)

Thanks.

**Comment by shilo-ey** [comment] 2019-03-28 08:45
Duplicate of #7633

**Comment by shilo-ey** [comment] 2019-03-28 08:45
Please send us your system info including PHP version in the thread mentioned above.

**Closed by shilo-ey** 2019-03-28 08:45 UTC

**Comment by Elementalel** [comment] 2019-03-28 11:05
I was just able to update to 2.5.2 and it resolved my problem. thnx

**Comment by Kapitol** [comment] 2019-03-29 12:44
Fatal error: Can't use method return value in write context in /home/perfettephoto/speed.perfettephoto.com/wp/wp-content/plugins/elementor-pro/modules/query-control/classes/elementor-post-query.php on line 53

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MySQL Community Server (GPL) v5.6.41
	PHP Version: 5.4.35
	PHP Max Input Vars: 1000
	PHP Max Post Size: 200M
	GD Installed: Yes
	ZIP Installed: No
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.1.1
	Site URL: https://speed.perfettephoto.com/wp
	Home URL: https://speed.perfettephoto.com/wp
	WP Multisite: No
	Max Upload Size: 200 MB
	Memory limit: 256M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: en-US
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 1.2.0
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.0.3 Safari/605.1.15

== Active Plugins ==
	Elementor
		Version: 2.5.10
		Author: Elementor.com

	Elementor Pro
		Version: 2.5.2
		Author: Elementor.com


== Log ==
	: 
Log: showing 20 of 202019-03-25 20:19:16 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.0.7',
  'to' => '2.4.8',
)]
2019-03-27 02:43:16 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.5.9',
  'to' => '2.5.10',
)]
2019-03-27 02:55:52 [info] elementor-pro::elementor_pro_updater Started 
2019-03-27 02:55:52 [info] Elementor Pro/Upgrades - _v_2_5_0_form Start  
2019-03-27 02:55:52 [info] Elementor Pro/Upgrades - _v_2_5_0_form Finished 
2019-03-27 02:55:52 [info] Elementor Pro/Upgrades - _v_2_5_0_woocommerce_menu_cart Start  
2019-03-27 02:55:52 [info] Elementor Pro/Upgrades - _v_2_5_0_woocommerce_menu_cart Finished 
2019-03-27 02:55:52 [info] Elementor Pro/Upgrades - _v_2_5_0_posts Start  
2019-03-27 02:55:52 [info] Elementor Pro/Upgrades - _v_2_5_0_posts Finished 
2019-03-27 02:55:52 [info] Elementor Pro/Upgrades - _v_2_5_0_portfolio Start  
2019-03-27 02:55:52 [info] Elementor Pro/Upgrades - _v_2_5_0_portfolio Finished 
2019-03-27 02:55:52 [info] Elementor Pro/Upgrades - _v_2_5_0_products Start  
2019-03-27 02:55:52 [info] Elementor Pro/Upgrades - _v_2_5_0_products Finished 
2019-03-27 02:55:52 [info] Elementor Pro/Upgrades - _v_2_5_0_sitemap Start  
2019-03-27 02:55:52 [info] Elementor Pro/Upgrades - _v_2_5_0_sitemap Finished 
2019-03-27 02:55:52 [info] Elementor Pro/Upgrades - _v_2_5_0_popup_border_radius Start  
2019-03-27 02:55:52 [info] Elementor Pro/Upgrades - _v_2_5_0_popup_border_radius Finished 
2019-03-27 02:55:52 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.4.8',
  'to' => '2.5.1',
)]
2019-03-27 02:55:53 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.4.8',
  'to' => '2.5.1',
)]
2019-03-29 12:35:45 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.5.1',
  'to' => '2.5.2',
)]

PHP: showing 2 of 2PHP: 2019-03-27 03:01:25 [error X 17][/home/perfettephoto/speed.perfettephoto.com/wp/wp-content/plugins/elementor-pro/modules/query-control/classes/elementor-post-query.php::53] Can't use method return value in write context [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2019-03-29 12:39:59 [notice X 1][/home/perfettephoto/speed.perfettephoto.com/wp/wp-content/plugins/elementor/core/logger/items/base.php::101] Array to string conversion [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
