### ISSUE TITLE
🔗 🐞 Bug Report: Style Paste doesn't work when click on save (Duplicate of #20315)

### ISSUE THREAD

**Issue by gluexde** [elementor/elementor#20364] opened 2022-11-10 11:57 UTC
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Hi,

Elementor does not save the page after I copy and paste the style of one container to another. The save button stays green and the page does not refresh properly. The changes are not being committed.

### Steps to reproduce

1. Copy Style from one container
2. Paste it to another
3. Click save

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MariaDB Server v5.5.61-MariaDB-38.13
	PHP Version: 7.4.30
	PHP Memory Limit: 128M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 51M
	GD Installed: Yes
	ZIP Installed: No
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.1
	Site URL: https://gluex.de
	Home URL: https://gluex.de
	WP Multisite: No
	Max Upload Size: 50 MB
	Memory limit: 512M
	Max Memory limit: 512M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: de-DE
	Timezone: Europe/Berlin
	Admin Email: jonas.taubmann@gluex.de
	Debug Mode: Inactive

== Theme ==
	Name: Astra Child
	Version: 1.0.0
	Author: Brainstorm Force
	Child Theme: Yes
	Parent Theme Name: Astra
	Parent Theme Version: 3.9.4
	Parent Theme Author: Brainstorm Force

== User ==
	Role: administrator
	WP Profile lang: de_DE
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36

== Active Plugins ==
	AnyWhere Elementor Pro (Premium)
		Version: 2.25.4
		Author: WP Vibes

	Astra Pro
		Version: 3.9.3
		Author: Brainstorm Force

	Better Search Replace
		Version: 1.4.1
		Author: Delicious Brains

	Borlabs Cookie - Cookie Opt-in
		Version: 2.2.57
		Author: Borlabs GmbH

	Checkout Field Editor for WooCommerce (Pro)
		Version: 3.4.0
		Author: ThemeHigh

	Customizer for WooCommerce
		Version: 2.7.7
		Author: SkyVerge

	Disable & Remove Google Fonts
		Version: 1.4.6
		Author: Fonts Plugin

	Elementor
		Version: 3.8.0
		Author: Elementor.com

	Elementor Pro
		Version: 3.8.1
		Author: Elementor.com

	Email Customizer for WooCommerce (Pro)
		Version: 3.6.0
		Author: ThemeHigh

	Imagify
		Version: 2.0
		Author: Imagify - Optimize Images & Convert WebP

	Loco Translate
		Version: 2.6.3
		Author: Tim Whitlock

	Place Order Without Payment for WooCommerce
		Version: 2.2
		Author: Nitin Prakash

	Rank Math SEO
		Version: 1.0.101
		Author: Rank Math

	Rank Math SEO PRO
		Version: 3.0.23
		Author: Rank Math

	The Plus Addons for Elementor
		Version: 5.1.14
		Author: POSIMYTH

	The Plus Addons for Elementor - Pro
		Version: 5.1.3
		Author: POSIMYTH

	WooCommerce
		Version: 7.1.0
		Author: Automattic

	WooCommerce Product Add-ons
		Version: 5.0.0
		Author: WooCommerce

	Woocommerce Side Cart Premium
		Version: 3.1
		Author: XootiX

	wp-Typography
		Version: 5.8.1
		Author: Peter Putzer

	WP Rocket
		Version: 3.12.2.1
		Author: WP Media

== Elementor-Experimente ==
	Optimierte DOM Ausgabe: Standardmäßig aktiviert
	Verbessertes Laden von Assets: Standardmäßig aktiviert
	Verbessertes Laden von CSS: Standardmäßig aktiviert
	Inline-Schriftarten-Symbole: Standardmäßig deaktiviert
	Verbesserungen der Zugänglichkeit: Standardmäßig aktiviert
	Zusätzliche benutzerdefinierte Breakpoints: Standardmäßig aktiviert
	Import Export Website Kit: Standardmäßig aktiviert
	Native WordPress-Widgets aus den Suchergebnissen ausblenden: Standardmäßig aktiviert
	admin_menu_rearrangement: Standardmäßig deaktiviert
	Flexbox Container: Aktiv
	Default to New Theme Builder: Standardmäßig aktiviert
	Startseiten: Standardmäßig aktiviert
	Farbpalette: Standardmäßig aktiviert
	Bevorzugte Widgets: Standardmäßig aktiviert
	Admin Leiste: Standardmäßig aktiviert
	Page Transitions: Standardmäßig aktiviert
	Notes: Standardmäßig aktiviert
	Loop: Standardmäßig deaktiviert
	Form Submissions: Standardmäßig aktiviert
	Scroll Snap: Standardmäßig aktiviert

== Protokoll ==
	
Log: showing 20 of 352022-10-24 08:24:59 [info] Elementor/Upgrades - _on_each_version Finished 
2022-10-24 08:24:59 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.6',
  'to' => '3.7.8',
)]
2022-10-31 09:19:40 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.8',
  'to' => '3.8.0',
)]
2022-10-31 09:19:41 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.7',
  'to' => '3.8.0',
)]
2022-10-31 09:19:41 [info] elementor::elementor_updater Started 
2022-10-31 09:19:41 [info] Elementor/Upgrades - _on_each_version Start  
2022-10-31 09:19:41 [info] Elementor/Upgrades - _on_each_version Finished 
2022-10-31 09:19:41 [info] Elementor/Upgrades - _v_3_8_0_fix_php8_image_custom_size Start  
2022-10-31 09:19:41 [info] Elementor/Upgrades - _v_3_8_0_fix_php8_image_custom_size Finished 
2022-10-31 09:19:41 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.8',
  'to' => '3.8.0',
)]
2022-10-31 09:19:42 [info] elementor-pro::elementor_pro_updater Started 
2022-10-31 09:19:42 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-10-31 09:19:42 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-10-31 09:19:42 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.7',
  'to' => '3.8.0',
)]
2022-10-31 09:19:43 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.7',
  'to' => '3.8.0',
)]
2022-11-03 00:35:47 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'AnyWhere Elementor Pro',
  'from' => '2.25.3',
  'to' => '2.25.4',
)]
2022-11-10 12:48:37 [info] elementor-pro::elementor_pro_updater Started 
2022-11-10 12:48:37 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-11-10 12:48:37 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-11-10 12:48:37 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.8.0',
  'to' => '3.8.1',
)]

PHP: showing 5 of 5PHP: 2022-10-24 10:25:36 [notice X 11][/pages/14/9f/d0015976/home/htdocs/sites/gluexneu/wp-content/plugins/elementor-pro/modules/forms/classes/form-record.php::179] Undefined index: referrer [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-10-26 07:56:15 [error X 1][/pages/14/9f/d0015976/home/htdocs/sites/gluexneu/wp-content/plugins/elementor-pro/modules/woocommerce/widgets/cart.php::2637] Uncaught Error: Call to a member function get_cart_contents_count() on null in /pages/14/9f/d0015976/home/htdocs/sites/gluexneu/wp-content/plugins/elementor-pro/modules/woocommerce/widgets/cart.php:2637
Stack trace:
#0 /pages/14/9f/d0015976/home/htdocs/sites/gluexneu/wp-content/plugins/elementor/includes/base/controls-stack.php(2249): ElementorPro\Modules\Woocommerce\Widgets\Cart->render()
#1 /pages/14/9f/d0015976/home/htdocs/sites/gluexneu/wp-content/plugins/elementor/includes/base/widget-base.php(609): Elementor\Controls_Stack->render_by_mode()
#2 /pages/14/9f/d0015976/home/htdocs/sites/gluexneu/wp-content/plugins/elementor/includes/base/widget-base.php(750): Elementor\Widget_Base->render_content()
#3 /pages/14/9f/d0015976/home/htdocs/sites/gluexneu/wp-content/plugins/elementor/includes/base/element-base.php(447): Elementor\Widget_Base->print_content()
#4 /pages/14/9f/d0015976/home/htdocs/sites/gluexneu/wp-content/plugins/elementor/includes/base/element-base.php(787): Elementor\Element_Base->print_element() [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-11-03 00:37:22 [notice X 1][/pages/14/9f/d0015976/home/htdocs/sites/gluexneu/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-11-04 15:39:35 [notice X 23][/pages/14/9f/d0015976/home/htdocs/sites/gluexneu/wp-content/plugins/elementor-pro/modules/woocommerce/widgets/checkout.php::4130] Undefined index: coupon_section_display [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-11-08 18:32:45 [error X 1][/pages/14/9f/d0015976/home/htdocs/sites/gluexneu/wp-content/plugins/elementor-pro/modules/woocommerce/widgets/cart.php::2635] Uncaught Error: Call to a member function get_cart_contents_count() on null in /pages/14/9f/d0015976/home/htdocs/sites/gluexneu/wp-content/plugins/elementor-pro/modules/woocommerce/widgets/cart.php:2635
Stack trace:
#0 /pages/14/9f/d0015976/home/htdocs/sites/gluexneu/wp-content/plugins/elementor/includes/base/controls-stack.php(2266): ElementorPro\Modules\Woocommerce\Widgets\Cart->render()
#1 /pages/14/9f/d0015976/home/htdocs/sites/gluexneu/wp-content/plugins/elementor/includes/base/widget-base.php(609): Elementor\Controls_Stack->render_by_mode()
#2 /pages/14/9f/d0015976/home/htdocs/sites/gluexneu/wp-content/plugins/elementor/includes/base/widget-base.php(750): Elementor\Widget_Base->render_content()
#3 /pages/14/9f/d0015976/home/htdocs/sites/gluexneu/wp-content/plugins/elementor/includes/base/element-base.php(447): Elementor\Widget_Base->print_content()
#4 /pages/14/9f/d0015976/home/htdocs/sites/gluexneu/wp-content/plugins/elementor/includes/base/element-base.php(801): Elementor\Element_Base->print_element() [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 3 of 3JS: 2022-11-02 12:51:00 [error X 10][https://gluex.de/wp-admin/load-scripts.php?c=0&loadchunk_0=underscore,jquery-core,jquery-migrate,backbone,jquery-ui-core,jquery-ui-mouse,wp-api-request,regenerator-runtime,wp-polyfill,wp-&loadchunk_1=hooks&ver=6.1:4:51824] Cannot read properties of undefined (reading \'replace\') 
JS: 2022-11-02 23:37:32 [error X 1][https://gluex.de/wp-includes/js/dist/vendor/react-dom.min.js?ver=17.0.1:9:21077] Cannot read properties of null (reading \'getOptions\') 
JS: 2022-11-03 10:23:23 [error X 1][https://gluex.de/wp-content/plugins/elementor/assets/js/editor-modules.min.js?ver=3.8.0:2:18515] Cannot delete property \'ae_rule_type\' of # 

== Elementor - Compatibility Tag ==
	
	AnyWhere Elementor Pro (Premium): Kompatibel
	Elementor Pro: Unkompatibel
	The Plus Addons for Elementor: Kompatibel
	The Plus Addons for Elementor - Pro: Kompatibel

== Elementor Pro - Compatibility Tag ==
	
	AnyWhere Elementor Pro (Premium): Kompatibel
	The Plus Addons for Elementor: Kompatibel
	The Plus Addons for Elementor - Pro: Unkompatibel

**Comment by nicholaszein** [comment] 2022-11-14 06:31
Hello @gluexde!

Thank you for your submission! 🙏 

### 🔗 This issue is a Duplicate of #20315.

Which is on the same subject. 

Please check the answer in [this comment](https://github.com/elementor/elementor/issues/20315#issuecomment-1313112252) to understand why this is not an Elementor Bug.

### ✔️ Please, in the future, remember to check if there isn't an issue similar to yours already opened. 

Best regards,

Nick

**Closed by nicholaszein** 2022-11-14 06:31 UTC
Labels: bug, component/editor, type/workflow, type/content-management
