### ISSUE TITLE
⛔ 🐞 Bug Report: Elementor-created shop page defaults back to WooCommerce standard shop page after assigning it in the Settings. After the page is assigned, I’m unable to edit the page using Elementor

### ISSUE THREAD

**Issue by lizsanchez** [elementor/elementor#21421] opened 2023-02-22 04:04 UTC
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

When exactly did you first notice the problem? 
- I noticed this problem today when I finished modifying the Shop All page and navigated to the WooCommerce Settings to assign this page as a WooCommerce Shop Page

Have any updates been applied to your website recently?
- Updated the woocommerce templates that required an update

Have you changed themes or made design changes?
- No theme changes

Have you installed any new plugins?
- Yes, but I disabled and uninstalled it. (Royal Addons)

Can the issue be replicated on multiple devices?
- Yes, shop page shows incorrectly all devices

Is your problem happening in one browser or all of them?
- all of them

Do you see a specific error message? Take a screenshot.
- yes, when I attempt to edit the page after assigning it to WooCommerce I get the message: The Preview could not be loaded.

### Steps to reproduce

1. Created a Shop Page with Elementor
2. Navigate to the WooCommerce Settings to assign this page as a WooCommerce Shop Page
3. Navigate back to the page from the Pages menu
4. Click the Edit with Elementor link
5. Get an error The Preview Could Not Be Loaded
<img width="1393" alt="Screen Shot 2023-02-21 at 10 59 35 PM" src="https://user-images.githubusercontent.com/57504763/220518797-e13f501b-4ffa-44ec-aaa9-7fa1b5fe463d.png">
<img width="1299" alt="Screen Shot 2023-02-21 at 11 00 11 PM" src="https://user-images.githubusercontent.com/57504763/220518801-ff8d9985-b888-43ec-bc5b-b46bc04ec662.png">
<img width="587" alt="Screen Shot 2023-02-21 at 11 00 51 PM" src="https://user-images.githubusercontent.com/57504763/220518803-e31a3ada-b3dc-4b16-b5e3-3fa38db7a01c.png">

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently following the steps above.

### System Info

<details>
<summary>System Info</summary>

````txt
					
== Server Environment ==
	Operating System: Linux
	Software: LiteSpeed
	MySQL version: MariaDB Server v10.3.34
	PHP Version: 7.4.29
	PHP Memory Limit: 256M
	PHP Max Input Vars: 5000
	PHP Max Post Size: 1024M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.1.1
	Site URL: https://www.silkresse.com
	Home URL: https://www.silkresse.com
	WP Multisite: No
	Max Upload Size: 512 MB
	Memory limit: 40M
	Max Memory limit: 256M
	Permalink Structure: /blog/%postname%/
	Language: en-US
	Timezone: 0
	Admin Email: silkresse@gmail.com
	Debug Mode: Inactive

== Theme ==
	Name: Blocksy Child
	Version: 
	Author: Creative Themes
	Child Theme: Yes
	Parent Theme Name: Blocksy
	Parent Theme Version: 1.8.42
	Parent Theme Author: CreativeThemes

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36

== Active Plugins ==
	Advanced Product Fields for WooCommerce
		Version: 1.5.9
		Author: StudioWombat

	Blocksy Companion
		Version: 1.8.75
		Author: CreativeThemes

	CoDesigner
		Version: 3.9
		Author: Codexpert

	Elementor
		Version: 3.12.0-dev4
		Author: Elementor.com

	Elementor Beta (Developer Edition)
		Version: 1.1.1
		Author: Elementor.com

	ElementsKit Lite
		Version: 2.8.1
		Author: Wpmet

	Essential Addons for Elementor
		Version: 5.5.4
		Author: WPDeveloper

	Spotlight - Social Media Feeds
		Version: 1.4.4
		Author: RebelCode

	WooCommerce
		Version: 7.4.0
		Author: Automattic

	WPForms Lite
		Version: 1.8.0.1
		Author: WPForms


== Elementor Experiments ==
	Optimized DOM Output: Active by default
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Active by default
	Accessibility Improvements: Active by default
	Additional Custom Breakpoints: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active
	Upgrade Swiper Library: Active by default
	Editor V2: Inactive by default
	Landing Pages: Active by default
	Nested Elements: Active by default
	Lazy Load Background Images: Inactive by default
	Save as Default: Active by default


== Log ==
	
JS: showing 17 of 17JS: 2022-07-12 18:06:59 [error X 75][https://www.silkresse.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.6.7:3:475108] Cannot read properties of undefined (reading \'parent\') 
JS: 2022-07-16 15:21:36 [error X 28][https://www.silkresse.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.7.0-dev10:2:185947] Cannot read properties of undefined (reading \'data\') 
JS: 2022-07-20 16:33:37 [error X 6][https://www.silkresse.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.7.0-dev10:2:610510] Cannot read properties of null (reading \'getBoundingClientRect\') 
JS: 2022-08-12 21:59:03 [error X 8][https://www.silkresse.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.7.0-dev10:2:614960] Cannot read properties of undefined (reading \'toLowerCase\') 
JS: 2022-08-16 02:01:16 [error X 34][https://www.silkresse.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.7.0-dev10:2:615467] Cannot read properties of undefined (reading \'localized\') 
JS: 2022-09-12 01:10:55 [error X 1][https://www.silkresse.com/wp-content/plugins/elementor/assets/js/container-converter.min.js?ver=3.7.0-dev10:2:10719] elementor is not defined 
JS: 2022-11-09 01:26:51 [error X 13][https://www.silkresse.com/wp-admin/load-scripts.php?c=1&loadchunk_0=jquery-core,jquery-migrate,regenerator-runtime,wp-polyfill,underscore,shortcode,utils,backbone,wp-util,wp-backbone,media-models,&loadchunk_1=moxiejs,plupload,wp-plupload,jquery-ui-core,jquery-ui-mouse,jquery-ui-sortable&ver=6.1:2:51824] Cannot read properties of undefined (reading \'replace\') 
JS: 2022-11-09 02:35:21 [error X 36][https://www.silkresse.com/wp-content/plugins/elementor/assets/js/frontend.min.js?ver=3.10.0-dev1:2:32848] elementorFrontendConfig is not defined 
JS: 2022-11-09 03:20:43 [error X 2][https://www.silkresse.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.10.0-dev1:3:811312] Cannot convert undefined or null to object 
JS: 2022-11-17 22:00:07 [error X 4][https://www.silkresse.com/wp-content/plugins/elementor/assets/js/frontend.min.js?ver=3.10.0-dev1:2:32871] Can\'t find variable: elementorFrontendConfig 
JS: 2023-01-10 04:51:46 [error X 69][https://www.silkresse.com/wp-admin/load-scripts.php?c=1&loadchunk_0=jquery-core,jquery-migrate,regenerator-runtime,wp-polyfill,jquery-ui-core,jquery-ui-mouse,underscore,backbone,wp-api-request,wp-&loadchunk_1=hooks&ver=6.1.1:2:51824] Cannot read properties of undefined (reading 'replace') 
JS: 2023-01-11 15:19:35 [error X 1][https://www.silkresse.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.11.0-dev3:3:583495] Cannot read properties of null (reading 'id') 
JS: 2023-01-11 17:27:40 [error X 3][https://www.silkresse.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.11.0-dev3:3:782318] Cannot read properties of undefined (reading 'toLowerCase') 
JS: 2023-01-18 02:51:41 [error X 1][https://www.silkresse.com/wp-content/plugins/elementor/assets/js/web-cli.min.js?ver=3.11.0-dev3:3:105230] Routes: `library/templates` not found. 
JS: 2023-01-19 04:31:23 [error X 1][https://www.silkresse.com/wp-content/plugins/elementor/assets/js/web-cli.min.js?ver=3.11.0-dev3:3:105230] Routes: `library/blocks` not found. 
JS: 2023-01-19 04:31:26 [error X 1][https://www.silkresse.com/wp-content/plugins/elementor/assets/js/web-cli.min.js?ver=3.11.0-dev3:3:105230] Routes: `library/pages` not found. 
JS: 2023-02-20 16:19:44 [error X 14][https://www.silkresse.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.12.0-dev4:3:794636] Cannot read properties of undefined (reading 'localized') 

PHP: showing 5 of 5PHP: 2022-07-12 20:02:17 [notice X 120][/home/silkress/public_html/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] The $finder_category_name argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-07-12 20:05:38 [notice X 5][/home/silkress/public_html/wp-content/plugins/elementor/includes/widgets/traits/button-trait.php::553] Undefined index: icon [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-09-12 19:12:19 [notice X 1][/home/silkress/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-01-18 02:53:19 [notice X 2][/home/silkress/public_html/wp-content/plugins/elementor/core/page-assets/data-managers/font-icon-svg/font-awesome.php::50] Trying to access array offset on value of type null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-02-20 04:56:40 [notice X 21][/home/silkress/public_html/wp-content/plugins/elementor/includes/managers/image.php::108] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

Log: showing 20 of 202022-07-16 14:45:12 [info] elementor::elementor_updater Started 
2022-07-16 14:45:12 [info] Elementor/Upgrades - _on_each_version Start  
2022-07-16 14:45:12 [info] Elementor/Upgrades - _on_each_version Finished 
2022-07-16 14:45:12 [info] Elementor/Upgrades - _v_3_7_0_remove_old_elements_usage Start  
2022-07-16 14:45:12 [info] Elementor/Upgrades - _v_3_7_0_remove_old_elements_usage Finished 
2022-07-16 14:45:12 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.7',
  'to' => '3.7.0-dev10',
)]
2022-07-16 14:45:12 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.7',
  'to' => '3.7.0-dev10',
)]
2022-11-09 02:20:27 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.0-dev10',
  'to' => '3.10.0-dev1',
)]
2022-11-09 02:20:27 [info] elementor::elementor_updater Started 
2022-11-09 02:20:27 [info] Elementor/Upgrades - _on_each_version Start  
2022-11-09 02:20:27 [info] Elementor/Upgrades - _on_each_version Finished 
2022-11-09 02:20:27 [info] Elementor/Upgrades - _v_3_8_0_fix_php8_image_custom_size Start  
2022-11-09 02:20:27 [info] Elementor/Upgrades - _v_3_8_0_fix_php8_image_custom_size Finished 
2022-11-09 02:20:27 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.0-dev10',
  'to' => '3.10.0-dev1',
)]
2022-12-14 01:22:22 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.10.0-dev1',
  'to' => '3.11.0-dev1',
)]
2022-12-14 01:22:22 [info] elementor::elementor_updater Started 
2022-12-14 01:22:22 [info] Elementor/Upgrades - _on_each_version Start  
2022-12-14 01:22:22 [info] Elementor/Upgrades - _on_each_version Finished 
2022-12-14 01:22:22 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.10.0-dev1',
  'to' => '3.11.0-dev1',
)]
2022-12-14 01:22:23 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.10.0-dev1',
  'to' => '3.11.0-dev1',
)]



== Elementor - Compatibility Tag ==
	
	Essential Addons for Elementor: Incompatible
				

````
</details>

**Comment by doronwolf** [comment] 2023-02-22 09:51
when you assign a page to be the WC 'shop' page it stops acting as a standard page and starts acting as a **Products archive**, which makes it your theme product archive - this is the default WC behavior and not a bug.
simply use the theme builder to design a product archive and then assign it to the shop page - It should solve your issue

**Comment by lizsanchez** [comment] 2023-02-22 14:56
hi @doronwolf I was able to use the Elementor created shop page to be the WC shop last week. This change in behavior happened suddenly. How can I use the elementor created page as my WC shop page?

**Closed** 2023-02-23 18:16 UTC
Labels: bug, compatibility/3rd_party, product/pro, component/woocommerce, type/dynamic-content, type/templates
