### ISSUE TITLE
Elementor's page CSS files return 404 with Redis enabled on NGINX

### ISSUE THREAD

**Issue by lelas** [elementor/elementor#13299] opened 2020-12-14 13:58 UTC
## Description

With Redis enabled (running servers via Spinupwp), the layout is completely broken due to post-*.css files returning 404 errors. It's been like this for ages. We currently have tons of client sites that are a **lot** slower, because we have had to disable Redis.

## Steps to reproduce

Run Redis on a server with NGINX and a site with Elementor.

## Isolating the problem
- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x ] This bug happens with a default WordPress theme active.
- [x ] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
https://pastebin.com/vkXTsHDX
```
</details>

**Comment by KingYes** [comment] 2020-12-14 19:19
Hey @lelas 

We have compatible with Redis (and all object cache using WordPress).
Please try to use [Redis Object Cache](https://wordpress.org/plugins/redis-cache/).

Let me know if the problem is resolved.

**Comment by shilo-ey** [comment] 2020-12-21 17:03
Closing for lack of activity,

Feel free to reopen if the issue persists.

**Comment by vandijks** [comment] 2020-12-23 20:12
@shilo-ey @KingYes I am experiencing exactly the same issues @lelas I also use Delicious Brains' SpinupWP service and their plugin: https://en-gb.wordpress.org/plugins/spinupwp/ Can we please keep this topic open? I believe that SpinupWP staff have also tried to log this issue with the Elementor support team. I am happy to provide a clone of a staging server with exactly this issue or any other info.

**Comment by lelas** [comment] 2021-01-03 11:43
> Hey @lelas
> 
> We are fully compatible with Redis (and all object cache using WordPress).
> Please try to use [Redis Object Cache](https://wordpress.org/plugins/redis-cache/).
> 
> Let me know if the problem is resolved.

Hey @KingYes

AFAIK, SpinupWP is using that exact code base for their Redis implementation (Redis Object Cache, albeit implemented in their own plugin). And the problem persists.

[Here](https://trmmd.com/) is an example, where I haven't disabled Redis.

![image](https://user-images.githubusercontent.com/602131/103477624-9f7ca780-4db8-11eb-8bb6-a3aef08277b7.png)

For reference, see this [Github Issue](https://github.com/deliciousbrains/spinupwp-plugin/issues/43). There SpinupWP mentions that Elementor is aware of the issue and is working on a fix, but it doesn't seem like anyone is actively trying to fix this.

I, for one, would be very grateful if you'd look a bit into this.

Cheers, Lasse

**Comment by lelas** [comment] 2021-01-05 14:46
> Closing for lack of activity,
> 
> Feel free to reopen if the issue persists.

Mind reopening?

**Comment by tamal-sen** [comment] 2021-01-06 12:05
Thanks @lelas for opening this issue, I am facing the same. The only temporary solution is now is to disable Redis cache which is not ideal. Please fix it.

**Comment by gravnetic** [comment] 2021-01-06 16:04
I have this same issue on 48 website and have had to add a config exception of **define( 'WP_REDIS_DISABLED', true );** to prevent the stylesheet from returning a 404 after the nightly Elementor cron job.

**Recreate the issue:**
1. SpinupWP managed hosting / NGINX Config (cache enabled 1 day)
2. Install Standard WordPress + Elementor + Elementor Pro
3. Add custom page styles via Elementor to a page (EX:  Home)
4. View the website after the nightly Elementor cron runs and recreates the CSS file.
5. RESULT:   all layout styles will return 404 and the page will look terrible.

**Comment by kwdit** [comment] 2021-03-03 03:24
I'd like to also join the group of people frustrated with hundreds of sites breaking daily, with Elementor installed and Redis Object Cache active.

I can't help noticing that everyone seems to mention SpinupWP though.
Has anyone tested Elementor on a server with NGINX and Redis Object Cache, outside of a SpinupWP Setup?

**Comment by gravnetic** [comment] 2021-04-05 23:24
@kwdit @vandijks @lelas @tamal-sen this has been resolved for me, are you experiencing any issues at this time.  My experience was that every single night the css files were being rewritten, but the previous files reference persisted causing the site to load each morning with no styles.

**Comment by shilo-ey** [comment] 2021-04-07 15:01
Hey @lelas @tamal-sen , please try to change the `autoload` value of `elementor_active_kit` option to `no` and update here if it resolved the issue.

Thanks

**Comment by gravnetic** [comment] 2021-04-07 16:07
@shilo-ey I apologize, I read through all those tickets and see that you are talking with SpinupWP now.  What I do not know is where can I cahnge the autoload value.  I know what an elementor_active_kit.  Do I set this in the template, in a function, in master settings in Elementor?

**Comment by shilo-ey** [comment] 2021-04-07 17:10
> @shilo-ey I apologize, I read through all those tickets and see that you are talking with SpinupWP now. What I do not know is where can I cahnge the autoload value. I know what an elementor_active_kit. Do I set this in the template, in a function, in master settings in Elementor?

@gravnetic https://kinsta.com/knowledgebase/wp-options-autoloaded-data/#what-is-the-wp_options-table

**Comment by kwdit** [comment] 2021-04-08 03:18
@gravnetic My issue was the same as you'd described. Having received your comment, I removed the line below from wp-config.php on the effected sites.
define( 'WP_REDIS_DISABLED', true );
This was done yesterday and today the site still looks OK, so it appears fixed.

**Comment by heyfletch** [comment] 2021-05-20 13:03
@A5hleyRich @shilo-ey this fix seems to have stalled. It seems there is a [beta SpinupWP plugin ](https://github.com/deliciousbrains/spinupwp-plugin/issues/43#issuecomment-776084544)that does extra cache clearing, and a suggestion from Elementor about changing an autoload parameter. Does anyone know if either or both of these methods are fixing this issue? My Elementor websites are slower than they need to be on SpinupWP, and I'm awaiting an official fix.

**Comment by lelas** [comment] 2021-05-21 14:55
I enabled Redis again on a few sites (maintained through SpinupWP and all using Elementor Pro) a few days ago. So far no issues!

**Comment by heyfletch** [comment] 2021-05-21 15:53
> I enabled Redis again on a few sites (maintained through SpinupWP and all using Elementor Pro) a few days ago. So far no issues!

@lelas Did you use the beta spinupwp plugin or set the autoload to no?  Or just their default stuff?

**Comment by lelas** [comment] 2021-05-23 14:59
> @lelas Did you use the beta spinupwp plugin or set the autoload to no? Or just their default stuff?

None of that. Regular SpinupWP plugin. The servers are fully updated (OS/packages) + upgraded (SpinupWP) + latest Elementor releases (Elementor + Elementor Pro). Still no issues, but obviously not sure they'll come...

**Comment by shilo-ey** [comment] 2021-07-13 14:07
This issue has been resolved in Elementor v3.3.0.

From now on no new Kit will be generated on these cases.

Feel free to update

Thanks!

**Closed by shilo-ey** 2021-07-13 14:07 UTC
Labels: compatibility, status/merged

**Comment by webzunft** [comment] 2021-09-22 07:59
I believe that the change that was made here might conflict with another plugin using `ob_cache()` on setups that are not using SpinupWP. Unfortunately, this issue doesn’t link to the specific change that was made so I can’t investigate further. Could anyone please provide a link to that particular change?

**Comment by kwdit** [comment] 2021-09-23 03:28
It's my understanding that the change was made to the SpinupWP plugin and therefore shouldn't effect setups that are not using SpinupWP. Apologies if I'm wrong.

**Comment by jes-wd** [comment] 2022-12-16 09:26
I am experiencing this exact issue with v3.9.1. Disabling Redis immediately resolves it.

**Comment by RensTillmann** [comment] 2023-01-03 07:10
Same problem WP installation with Redis Object Cache plugin v2.2.2 + Redis server v4.0.9 + Elementor v3.9.2.

**Comment by only-sadeghi** [comment] 2023-02-17 18:07
Hi
I have the same problems in elementor 3.11.1 and elementor pro 3.11.1.
after updating to this version, wordpress kept showing me "Elementor Pro Data Updater" and "Elementor Data Updater" notification in the dashboard.
after disabling opcache, this problem still exists. how can i fix it?

**Comment by johan-windahl** [comment] 2023-02-23 10:16
> Hi I have the same problems in elementor 3.11.1 and elementor pro 3.11.1. after updating to this version, wordpress kept showing me "Elementor Pro Data Updater" and "Elementor Data Updater" notification in the dashboard. after disabling opcache, this problem still exists. how can i fix it?

Same here...

**Comment by axgalache** [comment] 2023-03-03 10:57
Experiencing this very same issue.
global.css in wp-content/uploads/elementor/css is not found when Elementor reloads/does his staff (dunno exactly)

One possible solution would be to tell redis to exclude the key/group which is storing this. I'm investigating which group/key name would be the one to exclude. If I find it I'll post here ;)

**Comment by torchsmith** [comment] 2023-05-15 16:27
@axgalache any updates?
