### ISSUE TITLE
[FEATURE REQUEST] Background Gradients + Responsive Controls

### ISSUE THREAD

**Issue by maurocarreraok** [elementor/elementor#17000] opened 2021-11-20 15:10 UTC
## Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Gradient Background Responsive Controls.

**Describe the solution you'd like**
There is no control for responsive background gradient ajustments. You need to use images made for each device instead of having just a quick setting for each breakpoint.

**Describe alternatives you've considered**
-

**Comment by acornavi** [comment] 2022-01-25 07:10
Background image responsive control is essential for a mobile page speed control. We need this control ASAP.

**Comment by OferBenda** [comment] 2022-05-17 11:17
Thanks @acornavi and @maurocarreraok!
We'll definitely look into this.

**Comment by arielk** [comment] 2022-09-12 17:12
Duplicate of https://github.com/elementor/elementor/issues/10247

**Closed by arielk** 2022-09-12 17:12 UTC
Labels: request/enhancement

**Comment by nicholaszein** [comment] 2024-04-12 05:10
Hello everyone!

### 📢 We're happy to announce that the issue you raised was resolved in Elementor v3.19.0! 🥳 

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
