### ISSUE TITLE
No option to Edit Widgets' Names

### ISSUE THREAD

**Issue by MB8862** [elementor/elementor#8211] opened 2019-05-28 10:32 UTC
Hi,

I recently did a change to my site and added Global Widgets. There were a few times when I needed to change a widget's name and there was no way to do so.
Instead, I had to create a new widget, delete the old one, and go over my site all over again and replace the widget in all the relevant pages. I have over 200 pages so this wasn't easy or productive, to say the least. 

I was very surprised to see that there's no option to edit widget's names, and I was also surprised to find other comments reporting the same problem.

Simply giving us an "edit" button to a widget's name would be beneficial to all your users, and would save us a great deal of time when maintaining our sites.

P.S. I have Elementor Pro and I love your product!

Please let me know if you think you'd be able to add this option for us in Elementor.

Thank you,
Michal

**Comment by bainternet** [comment] 2019-05-30 12:15
Thanks for the feedback,
Please follow guidelines for opening a new [feature request](https://github.com/pojome/elementor/issues/new?template=Feature_request.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Description and examples.

**Comment by bainternet** [comment] 2019-05-30 12:15
Duplicate of #1578

**Closed by bainternet** 2019-05-30 12:15 UTC
