### ISSUE TITLE
Sitemap Columns are not dividing single content sources into multiple columns

### ISSUE THREAD

**Issue by ricardoaraujo330** [elementor/elementor#28227] opened 2024-07-28 10:59 UTC
### Prerequisites

- [X] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [ ] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

Hi!
I'm using the sitemap widget. When I apply more than 1 column, it always show in one column anyway.

### Steps to reproduce

Drag and drop sitemap widget
select content to display
set columns >2 

### Expected behavior

I expected the menu list to break in two or 3 columns but instead it keeps one column anyway.
<img width="1460" alt="Screenshot at Jul 28 11-54-36" src="https://github.com/user-attachments/assets/89cbf1b3-c70e-4b39-ba70-2bbcb1331404">

### Isolating the problem

- [ ] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [X] This bug happens with the Hello Elementor theme active.
- [X] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

<details>
<summary>Click to reveal</summary>

````txt



== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.59 (Debian)
	MySQL version: mariadb.org binary distribution v10.4.34
	PHP Version: 7.4.33
	PHP Memory Limit: 4000M
	PHP Max Input Vars: 5000
	PHP Max Post Size: 128M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.6.1
	Site URL: https://floresnocais.pt
	Home URL: https://floresnocais.pt
	WP Multisite: No
	Max Upload Size: 128 MB
	Memory limit: 4000M
	Max Memory limit: 4000M
	Permalink Structure: /blog/%postname%/
	Language: pt_PT
	Timezone: Europe/Lisbon
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor Child
	Version: 2.0.0
	Author: Elementor Team
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 3.1.0
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: pt-PT
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36

== Active Plugins ==
	Admin Menu Editor Pro
		Version: 2.26.1
		Author: Janis Elsts

	AutomateWoo
		Version: 6.0.30
		Author: WooCommerce

	Chaty Pro
		Version: 3.2.6
		Author: Premio

	Converter for Media
		Version: 5.13.0
		Author: matt plugins - Optimize images by convert WebP & AVIF

	Elementor
		Version: 3.23.3
		Author: Elementor.com

	Elementor Pro
		Version: 3.23.1
		Author: Elementor.com

	Facebook for WooCommerce
		Version: 3.2.6
		Author: Facebook

	GTM4WP - A Google Tag Manager (GTM) plugin for WordPress
		Version: 1.20.2
		Author: Thomas Geiger

	Invoicing with InvoiceXpress for WooCommerce - Pro
		Version: 5.7
		Author: PT Woo Plugins (by Webdados)

	JetElements For Elementor
		Version: 2.6.19
		Author: Crocoblock

	JetEngine
		Version: 3.5.3
		Author: Crocoblock

	JetFormBuilder
		Version: 3.3.4.1
		Author: Crocoblock

	JetFormBuilder User Login Action
		Version: 2.0.4
		Author: Crocoblock

	JetProductGallery
		Version: 2.1.16
		Author: Crocoblock

	JetSmartFilters
		Version: 3.5.3
		Author: Crocoblock

	JetTabs For Elementor
		Version: 2.2.3
		Author: Crocoblock

	JetWooBuilder - Products Grid Load More
		Version: 1.2.0
		Author: Crocoblock

	JetWooBuilder For Elementor
		Version: 2.1.13
		Author: Crocoblock

	Mailchimp for WooCommerce
		Version: 4.2.1
		Author: Mailchimp

	MRW
		Version: 4.3.1
		Author: Webubi

	Multibanco, MB WAY, Credit card, Payshop and Cofidis Pay (IfthenPay) for WooCommerce
		Version: 9.4.3
		Author: PT Woo Plugins (by Webdados)

	Order Delivery Date Pro for WooCommerce
		Version: 11.0.0
		Author: Tyche Softwares

	Portuguese Postcodes for WooCommerce
		Version: 5.5
		Author: PT Woo Plugins (by Webdados)

	Refer a Friend for WooCommerce PREMIUM
		Version: 4.1.3
		Author: WPGens

	Stock Dependencies for WooCommerce
		Version: 1.6.2
		Author: Kevin McCall

	Variation Swatches for WooCommerce
		Version: 2.1.1
		Author: Emran Ahmed

	Variation Swatches for WooCommerce - Pro
		Version: 2.1.3
		Author: Emran Ahmed

	Weglot Translate
		Version: 4.2.7
		Author: Weglot Translate team

	WooCommerce
		Version: 9.1.4
		Author: Automattic

	WooCommerce Email Customizer
		Version: 3.33
		Author: cxThemes

	WooCommerce Google Product Feed
		Version: 11.0.11
		Author: Ademti Software Ltd.

	WooCommerce Sequential Order Numbers Pro
		Version: 1.21.3
		Author: SkyVerge

	WooCommerce Shipment Tracking
		Version: 2.5.0
		Author: WooCommerce

	WooCommerce Smart Coupons
		Version: 9.6.0
		Author: StoreApps

	WooCommerce Stripe Gateway
		Version: 8.5.2
		Author: WooCommerce

	WooCommerce Subscriptions
		Version: 6.5.0
		Author: WooCommerce

	WooCommerce Subscriptions Compatibility Addon
		Version: 1.5.0
		Author: Tyche Softwares

	WooCommerce Waitlist
		Version: 2.4.12
		Author: Neil Pie

	Woo Conditional Shipping and Payments
		Version: 1.15.11
		Author: Woo

	Woo Reviews for Google
		Version: 1.0
		Author: ICREATOR

	WP Mail SMTP Pro
		Version: 4.1.0
		Author: WP Mail SMTP

	WP Rocket
		Version: 3.16.2.1
		Author: WP Media

	YITH WooCommerce Bulk Product Editing Premium
		Version: 3.9.0
		Author: YITH

	YITH WooCommerce Product Add-ons &amp; Extra Options Premium
		Version: 4.15.0
		Author: YITH

	Yoast Duplicate Post
		Version: 4.5
		Author: Enrico Battocchi & Team Yoast

	Yoast SEO
		Version: 23.1
		Author: Team Yoast

	Yoast SEO Premium
		Version: 23.0
		Author: Team Yoast


== Must-Use Plugins ==
	WP STAGING Optimizer
		Version: 1.5.6
		Author: WP STAGING


== Features ==
	Custom Fonts: 2
	Custom Icons: 2

== Integrations ==
	
	google_maps: Active
	recaptcha: Active
	recaptcha_v3: Active
	woocommerce: Active


== Elementor Experiments ==
	Improved CSS Loading: Active
	Inline Font Icons: Active
	Additional Custom Breakpoints: Active
	Flexbox Container: Active
	Grid Container: Active
	Atualizar Swiper Library: Inactive
	Nested Elements Performance: Active by default
	Optimized Control Loading: Active
	Optimized Markup: Inactive by default
	Plugin Onboarding: Active by default
	Default to New Theme Builder: Active
	Header &amp; Footer: Active by default
	Elementor Home Screen: Active by default
	Editor Top Bar: Active
	Build with AI: Active
	Landing Pages: Active
	Nested Elements: Active
	Lazy Load Background Images: Active
	Pages Panel: Inactive by default
	Element Caching: Inactive by default
	Link In Bio: Inactive by default
	Floating Buttons: Inactive by default
	Elementor Editor Events: Inactive by default
	Display Conditions: Active
	Form Submissions: Inactive
	Menu: Active
	Taxonomy Filter: Active
	Search: Inactive by default


== Log ==
	
JS: showing 6 of 6JS: 2024-07-19 22:41:02 [error X 32][../wp-content/plugins/elementor/assets/js/frontend-modules.min.js?ver=3.23.1:2:17146] Cannot read properties of undefined (reading &#039;attributes&#039;) 
JS: 2024-07-21 13:49:08 [error X 3][../wp-content/plugins/elementor/assets/js/common-modules.min.js?ver=3.23.1:2:56144] Model.isValidChild() should be implemented, please provide &#039;isValidChild&#039; functionality. 
JS: 2024-07-22 15:01:38 [error X 1][../wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: &quot;view10936&quot;) has already been destroyed and cannot be used. 
JS: 2024-07-23 11:29:11 [error X 14][../wp-content/plugins/jetformbuilder/assets/js/frontend/main.js?ver=250b7174e5f50c1b4a7a:1:41134] Cannot read properties of undefined (reading &#039;getName&#039;) 
JS: 2024-07-23 14:34:59 [error X 1][../wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.23.1:3:54583] Cannot read properties of undefined (reading &#039;activate&#039;) 
JS: 2024-07-28 10:45:21 [error X 1][../wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: &quot;view20679&quot;) has already been destroyed and cannot be used. 

PHP: showing 20 of 25PHP: 2024-07-24 16:28:52 [warning X 1][../wp-content/plugins/elementor-pro/modules/forms/actions/email.php::352] unlink(../wp-content/uploads/elementor/forms/66a11db228021.pdf): No such file or directory [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-07-24 19:14:42 [warning X 1][../wp-content/plugins/elementor-pro/modules/forms/actions/email.php::352] unlink(../wp-content/uploads/elementor/forms/66a1448fd8b78.pdf): No such file or directory [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-07-24 22:06:58 [warning X 1][../wp-content/plugins/elementor-pro/modules/forms/actions/email.php::352] unlink(../wp-content/uploads/elementor/forms/66a16ceea11c7.pdf): No such file or directory [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-07-25 00:43:55 [warning X 1][../wp-content/plugins/elementor-pro/modules/forms/actions/email.php::352] unlink(../wp-content/uploads/elementor/forms/66a191b7ed796.pdf): No such file or directory [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-07-25 11:38:06 [warning X 1][../wp-content/plugins/elementor-pro/modules/forms/actions/email.php::352] unlink(../wp-content/uploads/elementor/forms/66a22b0c9d6db.pdf): No such file or directory [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-07-25 15:32:50 [warning X 1][../wp-content/plugins/elementor-pro/modules/forms/actions/email.php::352] unlink(../wp-content/uploads/elementor/forms/66a2620ec80ac.pdf): No such file or directory [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-07-25 20:19:00 [warning X 1][../wp-content/plugins/elementor-pro/modules/forms/actions/email.php::352] unlink(../wp-content/uploads/elementor/forms/66a2a522465bf.pdf): No such file or directory [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-07-26 06:44:44 [warning X 1][../wp-content/plugins/elementor-pro/modules/forms/actions/email.php::352] unlink(../wp-content/uploads/elementor/forms/66a337c857219.pdf): No such file or directory [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-07-26 11:06:11 [warning X 1][../wp-content/plugins/elementor-pro/modules/forms/actions/email.php::352] unlink(../wp-content/uploads/elementor/forms/66a3751127e71.pdf): No such file or directory [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-07-26 12:24:47 [error X 1][../wp-content/plugins/elementor-pro/modules/motion-fx/module.php::38] Uncaught Error: Class &#039;ElementorPro\Modules\MotionFX\Controls_Group&#039; not found in ../wp-content/plugins/elementor-pro/modules/motion-fx/module.php:38
Stack trace:
#0 ../wp-includes/class-wp-hook.php(324): ElementorPro\Modules\MotionFX\Module-&gt;register_controls_group()
#1 ../wp-includes/class-wp-hook.php(348): WP_Hook-&gt;apply_filters()
#2 ../wp-includes/plugin.php(517): WP_Hook-&gt;do_action()
#3 ../wp-content/plugins/elementor/includes/managers/controls.php(510): do_action()
#4 ../wp-content/plugins/elementor/includes/managers/controls.php(623): Elementor\Controls_Manager-&gt;register_controls()
#5 ../wp-content/plugins/elementor/includes/managers/controls.ph [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-07-26 12:26:04 [error X 1][../wp-content/plugins/elementor-pro/modules/theme-builder/widgets/post-content.php::15] Trait &#039;ElementorPro\Modules\Posts\Skins\Skin_Content_Base&#039; not found [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-07-26 12:26:07 [error X 1][../wp-content/plugins/elementor-pro/modules/forms/module.php::200] Uncaught Error: Class &#039;ElementorPro\Modules\Forms\Registrars\Form_Actions_Registrar&#039; not found in ../wp-content/plugins/elementor-pro/modules/forms/module.php:200
Stack trace:
#0 ../wp-content/plugins/elementor/core/base/module.php(85): ElementorPro\Modules\Forms\Module-&gt;__construct()
#1 ../wp-content/plugins/elementor-pro/core/modules-manager.php(97): Elementor\Core\Base\Module::instance()
#2 ../wp-content/plugins/elementor-pro/plugin.php(361): ElementorPro\Core\Modules_Manager-&gt;__construct()
#3 ../wp-includes/class-wp-hook.php(324): ElementorPro\Plugin-&gt;on_elementor_init()
#4 ../wp-includes/class-wp-hook.php(348): WP_Hook-&gt;apply_filters()
#5 ../wp-in [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-07-26 12:26:12 [error X 1][../wp-content/plugins/elementor-pro/modules/forms/registrars/form-actions-registrar.php::57] Uncaught Error: Class &#039;ElementorPro\Modules\Forms\Actions\Drip&#039; not found in ../wp-content/plugins/elementor-pro/modules/forms/registrars/form-actions-registrar.php:57
Stack trace:
#0 ../wp-includes/class-wp-hook.php(324): ElementorPro\Modules\Forms\Registrars\Form_Actions_Registrar-&gt;ElementorPro\Modules\Forms\Registrars\{closure}()
#1 ../wp-includes/class-wp-hook.php(348): WP_Hook-&gt;apply_filters()
#2 ../wp-includes/plugin.php(517): WP_Hook-&gt;do_action()
#3 ../wp-content/plugins/elementor-pro/modules/forms/registrars/form-actions-registrar.php(84): do_action()
#4 ../wp-content/plugins/elementor-pro/modules/forms/registrars/form-actions-registrar.php(42): ElementorPro\Modules\Forms\Registrars\Form_Actions [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-07-26 12:26:49 [error X 1][../wp-content/plugins/elementor/core/base/module.php::331] Uncaught Error: Class &#039;ElementorPro\Modules\Social\Widgets\Facebook_Comments&#039; not found in ../wp-content/plugins/elementor/core/base/module.php:331
Stack trace:
#0 ../wp-includes/class-wp-hook.php(324): Elementor\Core\Base\Module-&gt;init_widgets()
#1 ../wp-includes/class-wp-hook.php(348): WP_Hook-&gt;apply_filters()
#2 ../wp-includes/plugin.php(517): WP_Hook-&gt;do_action()
#3 ../wp-content/plugins/elementor/includes/managers/widgets.php(145): do_action()
#4 ../wp-content/plugins/elementor/includes/managers/widgets.php(344): Elementor\Widgets_Manager-&gt;init_widgets()
#5 ../wp-content/plugins/elementor/includes/elements/container.php(336): Elementor\Widgets_Mana [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-07-26 15:35:02 [warning X 1][../wp-content/plugins/elementor-pro/modules/forms/actions/email.php::352] unlink(../wp-content/uploads/elementor/forms/66a3b4136827d.pdf): No such file or directory [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-07-26 18:55:55 [warning X 1][../wp-content/plugins/elementor-pro/modules/forms/actions/email.php::352] unlink(../wp-content/uploads/elementor/forms/66a3e329a2b06.pdf): No such file or directory [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-07-26 19:56:07 [warning X 1][../wp-content/plugins/elementor-pro/modules/forms/actions/email.php::352] unlink(../wp-content/uploads/elementor/forms/66a3f142ef79e.pdf): No such file or directory [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-07-26 19:58:31 [notice X 2930][../wp-content/plugins/elementor/core/dynamic-tags/manager.php::73] Array to string conversion [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-07-26 21:14:22 [notice X 2][../wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php::150] Undefined index: condition_type [array (
  'trace' => '
#0: ../wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(150): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_template_json_item()
#2: ../wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(120): class type array_map()
#3: ../wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(59): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_templates_json()
#4: ../wp-content/plugins/elementor/data/base/endpoint.php(158): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> get_items()
',
)]
PHP: 2024-07-26 21:45:31 [notice X 2][../wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::182] Undefined index: editor_post_id [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

Log: showing 11 of 112024-07-26 12:24:10 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.23.1',
  'to' => '3.23.3',
)]
2024-07-26 12:24:12 [info] elementor::elementor_updater Started 
2024-07-26 12:24:12 [info] Elementor/Upgrades - _on_each_version Start  
2024-07-26 12:24:12 [info] Elementor/Upgrades - _on_each_version Finished 
2024-07-26 12:24:12 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.23.1',
  'to' => '3.23.3',
)]
2024-07-26 12:24:13 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.23.1',
  'to' => '3.23.3',
)]
2024-07-26 12:24:22 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.23.0',
  'to' => '3.23.1',
)]
2024-07-26 12:24:22 [info] elementor-pro::elementor_pro_updater Started 
2024-07-26 12:24:22 [info] Elementor Pro/Upgrades - _on_each_version Start  
2024-07-26 12:24:22 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2024-07-26 12:24:22 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.23.0',
  'to' => '3.23.1',
)]



== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatibility not specified
	JetElements For Elementor: Compatibility not specified
	JetTabs For Elementor: Compatibility not specified
	JetWooBuilder For Elementor: Compatibility not specified

== Elementor Pro - Compatibility Tag ==

````

</details>

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by nicholaszein** [comment] 2024-07-30 15:03
Hello @ricardoaraujo330!

Thank you for submitting your issue! 🙏 

Can you please clarify some points so we can understand your issue better?

1. Are you using Additional Breakpoints? If yes, which ones? Please, with the Elementor Editor open, go to the **`Site Settings`** > **`Layout`** > **`Breakpoints`** section, and take a Screenshot of all the items in that section just like the image below:
![image](https://github.com/user-attachments/assets/39043004-7edc-4632-9261-f315b0e12c80)
2. I see you have multiple active plugins on your site. As part of the Troubleshooting steps required for users to submit their issues, we ask that you isolate the problem by deactivating all plugins except Elementor and Elementor Pro, and test to see if the problem goes away. Especially when you have so many Elementor Addons on your site. Did you isolate the problem?

On our tests, the Sitemap widget is working as expected. We want to make sure this is not an issue cased by a 3rd-party addon.


https://github.com/user-attachments/assets/a52f798f-5a0b-45b9-95ae-f3c58041a94f



Please, provide the missing information so we can validate your issue!

Kind regards

**Comment by ricardoaraujo330** [comment] 2024-07-31 11:22
Hi @nicholaszein 
Thank you for your quick answer.

By seeing your video I think i understand the "problem".
It breaks into two columns only if you have two types of contents, in this case you have "pages" and "categories".
I'm working only with the "pages", so it doesn't distribute the content in two or more columns, instead, it shows an infinite list in a single column.

Answering your questions:
1. yes, i use all break points available in elementor.
2. i'll not deactivate all plugins except elementor and elementor pro since by your video it doesn't seem to be caused by a 3rd party plugin.

IF the "problem" is related to the number of content types, i would suggest the possibility to break content in more than one column inside each content type.

Thank you

**Comment by nicholaszein** [comment] 2024-08-05 15:34
Hello @ricardoaraujo330!

Thank you for clarifying your issue. I understand you expect to be able to break content from a single source into multiple columns. In the case of the Sitemap the number of columns applies to the different sources of content, and this is the intended behavior. Right now, to apply multiple columns to a single source of content, you'll need to use Custom CSS. Try the following:

```css

selector .elementor-sitemap-list {
    column-count: 2;
    column-width: 200px;
    column-gap: 3rem;
}

```

In the CSS above, you'll be applying the [CSS text column property](https://css-tricks.com/guide-responsive-friendly-css-columns/) to determine how many columns you'll want in the list. The first property **`column-count`** counts how many columns the list should have. The second property **`column-width`** determines the ideal column size. If it gets below that value, the text will fall back to a column quantity that fits the space available based on the column width, reducing the number of columns. The the last property **`column-gap`** determines the space between columns. Adjust the values to your liking.

I'm closing this issue as it's not a bug, and it's behaving as intended. We classify bugs as errors in the code, or features not behaving as they were intended to behave. In your case, you are expecting a behavior that wasn't intended. 

As for your suggestion, if you think this should be an Elementor feature, please submit a new [🚀 Feature Request](https://github.com/orgs/elementor/discussions/new?category=feature-request), and we will consider it in the future if there is enough demand (votes) from other users. We cannot track enhancement request from bug reports.

I hope you can understand.

Kind regards

**Closed by nicholaszein** 2024-08-05 15:34 UTC
Labels: product/pro, type/layout, widget/sitemap, mod*, widget/settings
