### ISSUE TITLE
Elementor is not working

### ISSUE THREAD

**Issue by Ashraf-Gazy** [elementor/elementor#7677] opened 2019-03-30 12:17 UTC
Hi Elementor group,
I would like to thank the elementor group because you have created such a good plugin. I am extremely happy to use this plugin. Your plugin is playing one of the most important roles on my website.
Now I am facing little difficulty to do anything or to create any new page or post using Elementor after updating new version of WordPress (V : 5.1.1).
Can you please help me to figure out the problem, why am i getting this kind of error?
Elementor is not allowing me to drag or drop the widgets, so I need your help.

Error: https://drive.google.com/open?id=14wUl3ckkSbZKQzoKqFGMSZWQyDL7SXvF
 
I am not able to figure out the error. I am facing this error from the past 2-3 days after updating the new version of WP 5.1.1.

**Comment by legion1978** [comment] 2019-03-30 16:05
ive seen this. thats an error500. dont know exactly where it comes from but i disabled 2 plugins: cache (WPSOL) and optimization (Clearfy) and then it loads fine. only one site presents this problem, even with the same plugins active. site hosted on dreamhost.

also, theres an issue when copying widgets from one page to another (same site) or using global widgets, the page wont save (error400).

**Comment by shilo-ey** [comment] 2019-03-31 06:38
Hi @Ashraf-Gazy 

This issue is most likely caused by JS conflict on your website.

Start by deactivating all other add-ons and plugins other than Elementor Core & Elementor Pro (if installed) - then proceed to edit and see if the issue has been resolved. You may need to switch to the default theme to rule out your theme as the cause of the conflict.

If the issue is resolved by following the above action the proceed to reactivate each plugin 1 at a time and checking the editor till you find the one causing the conflict.

If the above process does not resolve the issue then check on Memory Limit set for your site together with PHP version - the easiest way to do that is by going to Elementor > System Info & scanning through it. 

If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email for details.


Thanks.

**Closed by shilo-ey** 2019-03-31 06:38 UTC
