### ISSUE TITLE
⛔ When using a carousel (image carousel & media carousel), the margin left option of the column doesn't work.

### ISSUE THREAD

**Issue by Royb10** [elementor/elementor#9825] opened 2019-12-10 16:48 UTC
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

## Description

When using a carousel (image carousel & media carousel), the margin left option of the column doesn't work.

![elementor bug](https://user-images.githubusercontent.com/49725353/70548736-c055d780-1b7b-11ea-9a9b-db10edb76227.png)

## Steps to reproduce

1. Create 2 column section
2. Set Margin left on the columns
3. Check it works
4. Then, add a media / image carousel
5. The margin is not working

## Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a default WordPress theme active.
- [X] I can reproduce this bug consistently using the steps above.

## Environment

**[Moderation: Elementor System Info redacted]**

**Comment by nicholaszein** [comment] 2024-08-12 04:43
Hi @Royb10!

Thank you for submitting your issue, and apologies for the delay in responding to it! 🙏 

It's been a while since you posted this issue, and a lot has changed. When we tested your issue using the latest version of Elementor (v3.23.4), and Elementor Pro (v3.23.3), we couldn't reproduce it, even using the Container. In any attempt, the result was the same: With Containers the margin-left works as expected, and with Columns the margin-left works as expected as well.

![image](https://github.com/user-attachments/assets/4a74ffd2-53a0-4592-b332-a84313ecbae8)


Therefore we conclude this is not a bug anymore.

For this reason, I'm closing your issue.

If you think this is till a bug after testing with the latest versions of Elementor and Elementor Pro, please follow the guidelines for opening a new [🐞 Bug Report](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml), so we can help you better.

Kind regards

**Closed by nicholaszein** 2024-08-12 04:43 UTC
Labels: product/pro, component/swiper, type/layout, mod*, element/column*, widget/image-carousel*, widget/media-carousel*
