### ISSUE TITLE
Rotating Animated Headline not Responsive

### ISSUE THREAD

**Issue by KingsburyWeb** [elementor/elementor#9867] opened 2019-12-13 15:32 UTC
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

When creating an animated headline and setting it to "rotating", the headline does not go to the 2nd line if there's a long headline. This is especially a nuisance on mobile devices where the animated headline would be cut off completely.

## Steps to reproduce

Create a new animated headline and choose "rotating" as the style. In the rotating text field, the headline scrolls when a new line is inserted. If you type our a long headline, you'll notice it's not responsive..

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by rjobadder** [comment] 2020-02-24 03:02
Verify it is not working in v2.4.1

**Comment by illumepgh** [comment] 2020-02-24 04:14
I am having the same issue. Is there a fix for this?

**Comment by vfdugar** [comment] 2020-03-18 20:03
Same here. The 'before text' and 'after text' wraps the text in each element. Running with GeneratePress theme.

**Comment by ytchen1** [comment] 2020-03-19 23:00
having the same issue with version 2.8.5

**Comment by HussonT** [comment] 2020-05-01 18:15
Same issue with 2.9.1

**Comment by sotaspaso** [comment] 2020-05-07 21:28
Same issue here....

**Comment by BWhitehair** [comment] 2020-05-25 06:45
> Same issue here....
> 
> edit: the solution I'm using now
> show the Animated Headline only on desktop/tablet
> use a simple Heading for mobile

I'm having the same issues described here...and having a simple headline doesn't quite solve the problem because I don't have the choice then of rotating between my headlines, and it's important that all 3 of the options I have show up...

**Comment by luxpatrick** [comment] 2020-08-18 17:40
issue still not regarded by support team? 
same issue here

**Comment by BoBella** [comment] 2020-10-17 23:40
I found that if I put a <br> after the before text that fixed my issue.

**Comment by tannernelson26** [comment] 2020-11-17 06:11
Has this been resolved? I haven't found a fix for it...

**Comment by acgorecki** [comment] 2020-12-29 23:47
This is still an issue, but the below CSS prevents the words from disappearing entirely. It's not great, but better than the current state.
`.elementor-headline.elementor-headline-animation-type-typing.elementor-headline-letters{
    word-break: break-word;
}`

**Comment by DorShahar** [comment] 2021-03-03 16:25
Hi to all,
Thank you for taking the time and reporting this, and sorry for the delay. 

We recreated your process of work and it seems to work properly.

Please try:

- Deactivate all your plugins besides Elementor (and Elementor Pro). If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin.
- Change your WordPress theme to Hello Theme (or other default WordPress theme).
And see if the issue still persists.

If you have purchased Elementor Pro, you are entitled to personal support, please see your purchase email for details.

Thanks.

**Closed by DorShahar** 2021-03-03 16:25 UTC

**Comment by Ankita-3298** [comment] 2021-05-21 06:55
Hello everyone,
I faced same issue but I have solved this with jQuery
Try with this jQuery I'm pretty sure it's worked
jQuery( window ).scroll(function() {
  if(jQuery(".elementor-headline-dynamic-wrapper span:last-child").hasClass("elementor-headline-text-active")){
      jQuery(".elementor-headline-text-inactive").remove();
  }
});

**Comment by xdubx** [comment] 2022-02-03 22:28
The bug is still there. Some JS set the "elementor-headline-dynamic-wrapper elementor-headline-text-wrapper" container to big with width and the child spans too. 

Its funny in the preview from the page in elementor the editor window on selected widget the text breaks perfect. The scope set the correct width of the box.

**Comment by NikMaster777** [comment] 2022-03-10 04:55
У меня получилось решить проблему обновлением плагина Elementor с версии 3.5.4 до 3.5.6

**Comment by bikku33** [comment] 2022-04-25 11:23
I have tried all the codes and methods to solve this issue. But, Didn't found the solution yet. Could you please help me to solve it?

**Comment by Sidorov927** [comment] 2022-06-09 21:26
3.6.6, та же фигня

**Comment by FunkyCss** [comment] 2022-09-09 10:35
Still not working !

**Comment by AcclamationStudio** [comment] 2022-12-14 05:33
Just noting this is still an issue. The code below (as recommended by @acgorecki) did fix the overflow at least, thank you! Unfortunately, this bug makes the component almost unusable as the mobile experience is so poor. 

I would also add that the centering of the text seems to be faulty.  

`    .elementor-headline-text-active {word-break: break-word; }`

**Comment by joelgaribaygz** [comment] 2022-12-29 23:54
With the CSS code that @acgorecki and @AcclamationStudio  shared and complementing it with the alignment of the text, the responsive error was perfectly solved.

I share the one I use:
`@media only screen and (max-width: 768px) {
  .elementor-headline-text-active {
    word-break: break-word; 
    text-align: center;
}
}`

**Comment by ustk** [comment] 2023-10-28 14:38
After 4 years this issue is still here...
Could you please fix it for us?

**Comment by attollo1** [comment] 2023-11-01 23:21
This is super-low tech, embarrassingly so, but I added <br> to split up the text on lines that were too long. Works great for me.

**Comment by uncommonjoe** [comment] 2023-11-21 15:43
The issue is that Elementor is injecting `&nbsp;` instead of spaces. I discovered this by inspecting the page source.

I wrote this small script that will remove them. Go to Elementor > Custom Code > Add New, set location to <head> and paste this in:

`<script type="text/javascript">
	// Removes &nbsp; from Elementor Animated Headline making it responsive.
	jQuery(document).ready(function(){
		jQuery('.elementor-headline-dynamic-text').each(function(){
			var text = jQuery(this).html();
			text = text.replace(/&nbsp;/g, ' ');
			jQuery(this).html(text);
		});
});
</script>`

**Comment by MagneticArrow** [comment] 2025-02-18 19:04
Thanks @uncommonjoe - I added a bit at the end to center the roatating text:

`<script type="text/javascript">
	// Removes &nbsp; from Elementor Animated Headline making it responsive and centers the text.
	jQuery(document).ready(function(){
		jQuery('.elementor-headline-dynamic-text').each(function(){
			var text = jQuery(this).html();
			text = text.replace(/&nbsp;/g, ' ');
			jQuery(this).html(text);
			// Add a class to center the text
			jQuery(this).addClass('centered-text');
		});
	});
</script>

<style>
.centered-text {
	text-align: center;
	display: block;
}
</style>`
