### ISSUE TITLE
✅ ❌ 🐞 Unable to install elementor-pro via composer

### ISSUE THREAD

**Issue by mkachov** [elementor/elementor#28969] opened 2024-10-14 14:08 UTC
### Prerequisites

- [ ] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [ ] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

`Failed to download elementor/elementor-pro from dist: The "https://composer.elementor.com/download/3.24.4" file could not be downloaded (HTTP/2 500 )`

### Steps to reproduce

Trying to install elementor-pro via composer

### Expected behavior

Plugin is installed successfully

### Isolating the problem

- [X] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [ ] This bug happens with the Hello Elementor theme active.
- [ ] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

```txt
php 8.3
WordPress 6.6.2
```

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by mapsmarketing** [comment] 2024-10-15 04:32
Hi @mkachov 

There isn't a whole lot of information you provided. Did you check out the following page on how to install Elementor/Pro via Composer: https://developers.elementor.com/docs/cli/composer/

You may have not specified a license, etc.

**Comment by jamieburchell** [comment] 2024-10-15 08:28
Can also confirm it's broken

```
Loading composer repositories with package information
Updating dependencies
Lock file operations: 1 install, 0 updates, 0 removals
  - Locking elementor/elementor-pro (3.24.4)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Downloading elementor/elementor-pro (3.24.4)
  - Downloading elementor/elementor-pro (3.24.4)
  - Downloading elementor/elementor-pro (3.24.4)
  - Downloading elementor/elementor-pro (3.24.4)
    Failed to download elementor/elementor-pro from dist: The "https://composer.elementor.com/download/3.24.4" file could not be downloaded (HTTP/2 500 )
    Now trying to download from source
```

**Comment by jamieburchell** [comment] 2024-10-15 09:34
Might need to reach out to Pro Support in the absence of activity here

**Comment by jamieburchell** [comment] 2024-10-15 12:10
This is the response body from the 500 message btw

> Error 1101 Ray ID: 8d2fb23c89266aaf • 2024-10-15 12:08:44 UTC
> Worker threw exception
> What happened?
> You've requested a page on a website (composer.elementor.com) that is on the [Cloudflare](https://www.cloudflare.com/5xx-error-landing/) network. An unknown error occurred while rendering the page.

> What can I do?
> If you are the owner of this website:
> you should [login to Cloudflare](https://www.cloudflare.com/login?utm_source=error_100x) and check the error logs for composer.elementor.com.

> Cloudflare Ray ID: 8d2fb23c89266aaf • Your IP: Click to reveal x.x.x.x • Performance & security by [Cloudflare](https://www.cloudflare.com/5xx-error-landing)

**Comment by juhojama** [comment] 2024-10-16 09:08
Confirmed. None of the versions up from 3.24.0 are installable via Composer.

**Comment by lhall-amphibee** [comment] 2024-10-16 09:21
Same thing here, we can't update at the moment

**Comment by lhall-amphibee** [comment] 2024-10-16 09:34
@jamiemax is actually correct, all pipelines are now failing because of this

**Comment by jamieburchell** [comment] 2024-10-16 10:11
I just opened a ticket with technical support. If others could do the same, hopefully there will be a better chance of resolving this.

**Comment by jamiemax** [comment] 2024-10-16 10:30
@jamieburchell have done so - fingers crossed

**Comment by jamiemax** [comment] 2024-10-16 10:43
They are basically not interested, and are claiming this isn't supported functionality:

Hi there,

Thank you for contacting me again.

The documentation you have provided to us are related to the developer side - https://prnt.sc/PXR7PwapJJhT

This documentation is use only to extend Elementor core to create your own Addons. There you will find detailed documentation, handy code snippers and full code examples.

Please note that through this channel, we can only provide support for Elementor's existing features and do not provide support for custom code solutions, as it goes out of our [support scope](https://elementor.com/help/how-do-i-get-premium-support/#whatwesupport).

Currently, development/custom code queries (custom widgets and functions, Theme Child, custom code and CSS, BETA testing issues, compatibility issues, etc.) have to be directed to our [GitHub project](https://github.com/elementor/elementor/issues), where our developers will be able to assist. Kindly note that our GitHub project is not a support channel; therefore, the response times may vary. We appreciate your understanding.

To post on our GitHub Repository, follow this guide: [Contribution Guidelines](https://github.com/elementor/elementor/blob/master/.github/CONTRIBUTING.md).

I hope this helps. If I missed something, please reply if you have any further questions regarding this ticket and Elementor. I'd request that you open a new ticket for any other issue; this will allow us to give you more accurate support.

Kind Regards,
Milos Stojanovic

**Comment by Kilbourne** [comment] 2024-10-16 11:48
This feature was added on March '23 ( after 5 years it was requested!)
Then it was broke since October '23 until January '24.  
Please this time do not let pass 3months

**Comment by Kilbourne** [comment] 2024-10-16 11:50
@nicholaszein triaged it the last time #24046

**Comment by nicholaszein** [comment] 2024-10-16 12:23
Hello everyone,

thank you for raising this problem! It seems we had a malfunction in the network configuration that temporarily prevented direct access to our servers when trying to install the Elementor Pro via composer.

**✅ This issue has already been solved, and you can now try again.**

We apologize for the inconvenience this may have caused!

If you find this issue is still happening to you, please submit a new [Bug Report](https://elemn.to/gh-new-bug-report) and provide all the required information in the Bug Report form. This information is essential for validating issues, and are fundamental for a swift resolution.

As a gentle reminder, issues without the required information may be closed without resolution.

Kind regards

**Closed by nicholaszein** 2024-10-16 12:23 UTC
Labels: bug, product/pro, solved, integration/composer, mod/v*
