### ISSUE TITLE
Deactivate elements to make a faster web

### ISSUE THREAD

**Issue by mlmorenoguti** [elementor/elementor#11137] opened 2020-04-15 12:04 UTC
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Hello Elementors, actually you can't deactivate the elements you don't use in your web, so the css and js files are very heavy and you only use a low percentage of them.

**Describe the solution you'd like**
I think a possible solution would be to generate one css and/or one js file for each element and allow to deactivate the elements you don't use. Finally you can combine all the css and js in one file to reduce the number of requests to the server.

**Comment by shimsa** [comment] 2020-04-15 20:24
I am hoping, that Elementor team take their chance to create tool, that will automagically generate super speed websites. Of course only in case, that webdesigner know best practices. Seeing 15 MB site and no caching is very sad reality. And big unused CSS and JavaScript not helping.
Take a look for example at Elementor Sites of the Month in Google PageSpeed Insights or Lighthouse.
But even if you keep best practices and create simple page, this big CSS files degrading speed of the website and for us it is imposible to fix this.

But otherwise Elementor is super tool and in the future will be even better. Thanks for that. Just focus on things like that. New features may wait.

**Comment by black-eye** [comment] 2020-04-15 21:40
+1
This was mentioned in several other issues, mine included (https://github.com/elementor/elementor/issues/7530). Most of them were closed in favor of https://github.com/elementor/elementor/issues/1314 (although the goal of it is a a bit different).

But maybe, if we all will repeat it over and over again, Elementor will implement it one day. There's always a hope ...

**Comment by MichaelDarko** [comment] 2020-04-16 20:46
Page speed is an issue on websites built with Elementor. Even when you use the Hello theme and only Elementor plugin, it will still rate VERY badly on Google PageSpeed Insights.

I hope there is something Elementor can do about this. If you have a slow website, nobody will care how good it looks.

**Comment by arielk** [comment] 2020-05-01 14:36
Duplicate of #1314

**Closed** 2020-05-01 14:35 UTC
Labels: performance

**Comment by mlmorenoguti** [comment] 2020-05-04 10:32
The features are differents, #1314 talks about to lock some widgets based on user role, what i propose is to avoid loading css and scripts from unused widgets

**Comment by nicholaszein** [comment] 2024-01-05 21:19
Hey there everyone!

We have great news! 🙌 

### 📢 We're happy to announce that this feature was released with Elementor v3.18.0! 🥳 

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
