### ISSUE TITLE
🔗 🐞 LCP loading error (Duplicate of #25091)

### ISSUE THREAD

**Issue by aqueousdan** [elementor/elementor#25147] opened 2024-02-15 12:24 UTC
### Prerequisites

- [X] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [X] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

We have a new website and we are failing on core web vitals on mobile, it seems the page loads the desktop background initially before putting in the mobile hero image. Can this be altered?

Website url: https://www.aqueous-digital.co.uk

<img width="193" alt="Screenshot 2024-02-15 at 11 20 52" src="https://github.com/elementor/elementor/assets/160131833/ff4bd64b-8816-4316-b0ac-59ce838b82d4">

<img width="212" alt="Screenshot 2024-02-15 at 11 37 23" src="https://github.com/elementor/elementor/assets/160131833/a99a989f-f330-4ae9-9d49-33ad2cac4a5f">

<img width="1037" alt="Screenshot 2024-02-15 at 12 21 03" src="https://github.com/elementor/elementor/assets/160131833/8da83237-04bf-448f-b515-101c6919ae72">

<img width="129" alt="Screenshot 2024-02-15 at 12 17 54" src="https://github.com/elementor/elementor/assets/160131833/54f7ac91-8fc3-4531-9137-9b85f77df64d">

### Steps to reproduce

Simply run the core web vitals: https://pagespeed.web.dev/analysis/https-www-aqueous-digital-co-uk/0szq1hejvm?form_factor=mobile

### Expected behavior

Just load the mobile image and not the desktop version.

### Isolating the problem

- [ ] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [ ] This bug happens with the Hello Elementor theme active.
- [ ] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

<details>
<summary>Click to reveal</summary>

````txt

== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MySQL Community Server (GPL) v5.7.44
	PHP Version: 7.4.33
	PHP Memory Limit: 256M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 8M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.4.3
	Site URL: https://www.aqueous-digital.co.uk
	Home URL: https://www.aqueous-digital.co.uk
	WP Multisite: No
	Max Upload Size: 6 MB
	Memory limit: 40M
	Max Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en-GB
	Timezone: Europe/London
	Debug Mode: Inactive

== Theme ==
	Name: Aqueous Digital
	Version: 2.8.1.1694621909
	Author: Elementor Team
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 3.0.1
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: en_GB
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36

== Active Plugins ==
	ACF Content Analysis for Yoast SEO
		Version: 3.1
		Author: Thomas Kräftner, ViktorFroberg, marol87, pekz0r, angrycreative, Team Yoast

	Advanced Custom Fields PRO
		Version: 6.2.5
		Author: WP Engine

	Akismet Anti-spam: Spam Protection
		Version: 5.3.1
		Author: Automattic - Anti-spam Team

	Better Search Replace
		Version: 1.4.5
		Author: WP Engine

	Coming Soon Page, Maintenance Mode, Landing Pages &amp; WordPress Website Builder by SeedProd
		Version: 6.15.23
		Author: SeedProd

	Elementor
		Version: 3.19.2
		Author: Elementor.com

	Elementor Addon Elements
		Version: 1.12.12
		Author: WPVibes

	Elementor Pro
		Version: 3.19.2
		Author: Elementor.com

	EWWW Image Optimizer
		Version: 7.2.3
		Author: Exactly WWW

	Headers Security Advanced &amp; HSTS WP
		Version: 5.0.30
		Author: 🐙 Andrea Ferro

	InfiniteWP - Client
		Version: 1.12.5
		Author: Revmakx

	Link Whisper
		Version: 2.3.1
		Author: Link Whisper

	ManageWP - Worker
		Version: 4.9.19
		Author: GoDaddy

	Post Types Order
		Version: 2.1.4
		Author: Nsp Code

	Post Type Switcher
		Version: 3.2.2
		Author: Triple J Software, Inc.

	Really Simple SSL
		Version: 7.2.2
		Author: Really Simple Plugins

	Redirection
		Version: 5.4.2
		Author: John Godley

	Relevanssi
		Version: 4.22.0
		Author: Mikko Saari

	Shortcode in Menus
		Version: 3.5.1
		Author: Gagan Deep Singh

	Site Kit by Google
		Version: 1.119.0
		Author: Google

	The Plus Addons for Elementor
		Version: 5.3.5
		Author: POSIMYTH

	To Top
		Version: 2.5.3
		Author: Catch Plugins

	UpdraftPlus - Backup/Restore
		Version: 2.23.14.1
		Author: UpdraftPlus.Com, DavidAnderson

	Wordfence Security
		Version: 7.11.2
		Author: Wordfence

	WP Armour - Honeypot Anti Spam
		Version: 2.1.14
		Author: Dnesscarkey

	WP Custom Author URL
		Version: 1.0.5
		Author: Chris Allen

	WP Rocket
		Version: 3.15.9
		Author: WP Media

	WPS Hide Login
		Version: 1.9.13.2
		Author: WPServeur, NicolasKulka, wpformation

	Yoast Duplicate Post
		Version: 4.5
		Author: Enrico Battocchi & Team Yoast

	Yoast SEO
		Version: 22.0
		Author: Team Yoast


== Must-Use Plugins ==
	InfiniteWP - Client Loader
		Version: 1.0.1
		Author: Revmakx

	ManageWP - Worker Loader
		Version: 1.0.0
		Author: GoDaddy


== Elements Usage ==
	
	archive : 7
		archive-posts : 3
		button : 1
		call-to-action : 4
		container : 18
		heading : 9
		image : 4
		nav-menu : 5
		posts : 2
	container : 5
		button : 3
		call-to-action : 1
		container : 11
		heading : 4
		icon : 1
		image : 1
		text-editor : 2
		video : 1
	footer : 1
		container : 11
		heading : 9
		icon-list : 1
		image : 1
		image-carousel : 1
		nav-menu : 5
		social-icons : 2
		text-editor : 3
	header : 1
		button : 3
		container : 2
		nav-menu : 1
		theme-site-logo : 1
	page : 3
		container : 56
		google_maps : 3
		heading : 16
		nested-accordion : 5
		spacer : 1
		text-editor : 31
		video : 6
	popup : 1
		container : 1
		search-form : 1
	section : 2
		container : 4
		heading : 2
		image : 1
		shortcode : 1
		social-icons : 1
	wp-post : 4
		button : 4
		container : 91
		heading : 45
		image : 12
		posts : 7
		spacer : 9
		testimonial : 1
		text-editor : 57
		video : 2
	wp-page : 74
		button : 27
		call-to-action : 14
		container : 755
		divider : 39
		form : 2
		gallery : 1
		google_maps : 21
		heading : 228
		html : 2
		icon-box : 6
		icon-list : 1
		image : 33
		image-box : 41
		loop-grid : 3
		nested-accordion : 46
		nested-tabs : 1
		posts : 8
		shortcode : 2
		social-icons : 12
		spacer : 49
		text-editor : 435
		video : 56
	single-post : 4
		button : 1
		container : 18
		heading : 6
		image : 2
		post-info : 2
		posts : 2
		shortcode : 3
		social-icons : 2
		text-editor : 2
		theme-post-content : 2
		theme-post-title : 2
	search-results : 1
		archive-posts : 1
		container : 2
		search-form : 1
		theme-archive-title : 1
	loop-item : 3
		container : 5
		heading : 2
		image : 2
		text-editor : 3
		toggle : 1
		wts-modal-popup : 1
	error-404 : 1
		button : 1
		container : 2
		heading : 1
		image : 1
		lottie : 1
		text-editor : 1


== Settings ==
	
	cpt_support: post, page, e-landing-page, team, faq, article, testimonial, career, case-studies
	disable_color_schemes: yes
	disable_typography_schemes: yes
	allow_tracking: yes
	css_print_method: internal
	unfiltered_files_upload: 1
	font_display: swap
	meta_generator_tag: 1


== Features ==
	Custom Fonts: 0
	Custom Icons: 0

== Integrations ==
	
	recaptcha_v3: Active


== Elementor Experiments ==
	Improved asset loading: Active
	Improved CSS Loading: Active
	Inline Font Icons: Active
	Additional Custom Breakpoints: Active
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active
	Upgrade Swiper Library: Active
	Grid Container: Inactive
	Default to New Theme Builder: Active
	Hello Theme Header &amp; Footer: Active
	Editor Top Bar: Inactive
	Optimized Gutenberg Loading: Active
	Build with AI: Inactive
	Landing pages: Active
	Nested Elements: Active
	Lazy Load Background Images: Active
	Optimize Image Loading: Active
	Global Style Guide: Active
	Page Transitions: Inactive
	Notes: Inactive
	Display Conditions: Inactive by default
	Form Submissions: Active
	Scroll Snap: Inactive
	Menu: Inactive
	Taxonomy Filter: Active


== Log ==
	
PHP: showing 5 of 5PHP: 2024-01-23 10:35:48 [notice X 4][../wp-content/plugins/elementor-pro/modules/dynamic-tags/tags/post-featured-image.php::39] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-01-24 16:19:28 [notice X 4][../wp-content/plugins/elementor/core/page-assets/data-managers/font-icon-svg/font-awesome.php::50] Trying to access array offset on value of type null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-02-01 13:46:47 [notice X 7][../wp-content/plugins/elementor-pro/modules/query-control/module.php::386] Undefined index: display [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-02-07 13:20:45 [notice X 60][../wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php::150] Undefined index: condition_type [array (
  'trace' => '
#0: ../wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(150): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_template_json_item()
#2: ../wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(120): class type array_map()
#3: ../wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(59): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_templates_json()
#4: ../wp-content/plugins/elementor/data/base/endpoint.php(158): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> get_items()
',
)]
PHP: 2024-02-08 13:17:15 [error X 1][../wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::200] Uncaught Error: Class &#039;\ElementorPro\Modules\ThemeBuilder\Conditions\General&#039; not found in ../wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:200
Stack trace:
#0 ../wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(282): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager-&gt;register_condition(&#039;general&#039;)
#1 ../wp-includes/class-wp-hook.php(324): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager-&gt;register_conditions(&#039;&#039;)
#2 ../wp-includes/class-wp-hook.php(348): WP_Hook-&gt;apply_filters(NULL, Array)
#3 ../wp-includes/plugin.php(517): WP_Hook-&gt;do_action(Array)
#4 ../wp-settings.php(665): do_action(&#039;wp_loaded&#039;)
#5 ../wp-config.php(103): require_once(&#039;/home/aqueouswe...&#039;)
#6 /home/aqueouswebdesign/public_h [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 7 of 7JS: 2024-01-24 11:57:38 [error X 1][../wp-content/plugins/elementor/assets/js/web-cli.min.js?ver=3.18.3:3:82947] Data commands: `undefined` not found. 
JS: 2024-01-30 11:08:37 [error X 8][../wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.19.0:3:648162] Cannot read properties of undefined (reading &#039;isDesignable&#039;) 
JS: 2024-01-30 14:05:44 [error X 1][../wp-admin/post.php?post=6882&amp;action=elementor&amp;active-document=9093:6:39] Cannot read properties of undefined (reading &#039;needHelpUrl&#039;) 
JS: 2024-01-30 16:21:36 [error X 9][../wp-content/plugins/elementor-pro/assets/js/editor.min.js?ver=3.19.0:2:64496] Cannot convert undefined or null to object 
JS: 2024-02-01 15:43:28 [error X 5][../wp-content/plugins/elementor/assets/js/frontend-modules.min.js?ver=3.19.0:2:16868] Cannot read properties of undefined (reading &#039;data&#039;) 
JS: 2024-02-14 15:01:57 [error X 3][../wp-content/plugins/elementor-pro/assets/js/editor.min.js?ver=3.19.2:2:64496] can&#039;t convert undefined to object 
JS: 2024-02-14 15:02:39 [error X 4][../wp-content/plugins/elementor/assets/js/admin.min.js?ver=3.19.2:3:47917] c[0] is undefined 

Log: showing 20 of 302024-01-30 15:27:41 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.18.3',
  'to' => '3.19.0',
)]
2024-02-06 11:11:21 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.19.0',
  'to' => '3.19.1',
)]
2024-02-06 11:11:21 [info] elementor::elementor_updater Started 
2024-02-06 11:11:21 [info] Elementor/Upgrades - _on_each_version Start  
2024-02-06 11:11:23 [info] Elementor/Upgrades - _on_each_version Finished 
2024-02-06 11:11:23 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.19.0',
  'to' => '3.19.1',
)]
2024-02-07 12:26:37 [info] elementor-pro::elementor_pro_updater Started 
2024-02-07 12:26:37 [info] Elementor Pro/Upgrades - _on_each_version Start  
2024-02-07 12:26:37 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2024-02-07 12:26:37 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.19.0',
  'to' => '3.19.1',
)]
2024-02-07 12:26:39 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.19.0',
  'to' => '3.19.1',
)]
2024-02-08 13:16:59 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.19.1',
  'to' => '3.19.2',
)]
2024-02-08 13:17:00 [info] elementor::elementor_updater Started 
2024-02-08 13:17:00 [info] Elementor/Upgrades - _on_each_version Start  
2024-02-08 13:17:00 [info] Elementor/Upgrades - _on_each_version Finished 
2024-02-08 13:17:00 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.19.1',
  'to' => '3.19.2',
)]
2024-02-08 13:56:37 [info] elementor-pro::elementor_pro_updater Started 
2024-02-08 13:56:37 [info] Elementor Pro/Upgrades - _on_each_version Start  
2024-02-08 13:56:37 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2024-02-08 13:56:37 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.19.1',
  'to' => '3.19.2',
)]



== Elementor - Compatibility Tag ==
	
	Elementor Addon Elements: Compatibility not specified
	Elementor Pro: Compatibility not specified
	The Plus Addons for Elementor: Compatibility not specified

== Elementor Pro - Compatibility Tag ==

````

</details>

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by nicholaszein** [comment] 2024-02-15 23:02
Hello @aqueousdan!

Thank you for your submission! 🙏 

### 🔗 🐞 This issue is a Duplicate of #25091

Which is on the same subject. 

For this reason, I'm closing this thread and 🔃 **Merging** it with the original, so we can have all the discussions in one location, and deal with it more efficiently.

Feel free to continue the conversation there. 😉 

### 🔍 Please, in the future, remember to check if there isn't any thread similar to yours already opened. 

Kind regards

**Closed by nicholaszein** 2024-02-15 23:02 UTC
Labels: type/responsive, type/performance, type/seo, type/layout, control/group/background, mod*, duplicate
