### ISSUE TITLE
Allow Accordion to contain Elementor Blocks

### ISSUE THREAD

**Issue by Slapbox** [elementor/elementor#10162] opened 2020-01-15 23:29 UTC
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Better accordions, able to contain Elementor blocks.

**Describe the solution you'd like**
Accordions can contain other blocks, like a simple title block. I know styled headings is of course achievable in the text editor, but it's MUCH harder to implement or maintain than if Elementor allowed blocks inside of Accordions

**Describe alternatives you've considered**
Building a workaround myself :(

**Comment by bainternet** [comment] 2020-01-16 21:03
Thanks for the feedback,
Please follow guidelines for opening a new [feature request](https://github.com/pojome/elementor/issues/new?template=Feature_request.md), so we can help you better.
This report is missing key information: 

* Prerequisites.

**Comment by bainternet** [comment] 2020-01-16 21:03
Duplicate of #2587

**Closed by bainternet** 2020-01-16 21:03 UTC

**Comment by Slapbox** [comment] 2020-01-16 22:54
Thank you for noting a duplicate I failed to find. Please don't say that people who followed the issue template that they didn't though. It may seem like a small thing, but I searched through >150 issues to try to find a duplicate. Failing to find a needle in a haystack isn't not looking.

**Comment by nicholaszein** [comment] 2023-08-01 13:16
Hello there!

We have great news! 🙌 

### 📢 We're happy to announce that the new Nested Accordion widget was released with Elementor v3.15.0! 🥳 

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
