### ISSUE TITLE
BUG: Reverse Columns are not reversing based on custom breakpoints

### ISSUE THREAD

**Issue by Stilian1** [elementor/elementor#12925] opened 2020-10-25 23:54 UTC
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

As you know, custom breakpoints were not working since Elementor v3.0 and were fixed in Elementor v3.0.6 (see #12320). But there is still a leftover issue that needs to be fixed. Although custom breakpoints now work in general, they don't work with the Reverse Columns option in the Responsive settings tab of Sections. That means that although I have set custom breakpoints, the Reverse Columns feature follow the default breakpoints of Elementor and not my custom ones.
## Steps to reproduce
1. open and edit a page with Elementor
2. add a section with 2 columns and add an element inside each column
3. go to the Responsive tab of the section's settings and reverse the columns for tablet
4. open Site Settings and change the breakpoints from the default values, e.g 650px for mobile (instead of 768px)
5. update the page, view it live, and check if the columns are reversed at 768px or at 650px

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by digitallifementors** [comment] 2020-12-20 19:05
I just noticed this issue... have custom breakpoints set at 1299 and 800... in tablet design mode, the reverse column looks great... but in reality, anything above 1024 (and up to my 1299) is not adhering to my custom rules. Did you have any luck resolving this?

**Comment by Stilian1** [comment] 2020-12-20 20:03
> I just noticed this issue... have custom breakpoints set at 1299 and 800... in tablet design mode, the reverse column looks great... but in reality, anything above 1024 (and up to my 1299) is not adhering to my custom rules. Did you have any luck resolving this?

No luck. Still waiting for Elementor support to notice this issue. I ended up removing my custom breakpoints so the layout would work consistently at least...

**Comment by d2roth** [comment] 2020-12-22 19:39
I ran into this same issue and fixed it by adding the following CSS to the customizer. Note: 1150 is the custom tablet breakpoint I set in Elementor's Site Settings > Breakpoints > Tablet so change the max-width setting below to be 1px less than the Tablet setting selected.

```
@media (min-width:768px) and (max-width:1149px) {
  .elementor-reverse-tablet>.elementor-container>.elementor-row>:first-child {
    -webkit-box-ordinal-group:11;
    -ms-flex-order:10;
    order:10
  }
  .elementor-reverse-tablet>.elementor-container>.elementor-row>:nth-child(2) {
    -webkit-box-ordinal-group:10;
    -ms-flex-order:9;
    order:9
  }
  .elementor-reverse-tablet>.elementor-container>.elementor-row>:nth-child(3) {
    -webkit-box-ordinal-group:9;
    -ms-flex-order:8;
    order:8
  }
  .elementor-reverse-tablet>.elementor-container>.elementor-row>:nth-child(4) {
    -webkit-box-ordinal-group:8;
    -ms-flex-order:7;
    order:7
  }
  .elementor-reverse-tablet>.elementor-container>.elementor-row>:nth-child(5) {
    -webkit-box-ordinal-group:7;
    -ms-flex-order:6;
    order:6
  }
  .elementor-reverse-tablet>.elementor-container>.elementor-row>:nth-child(6) {
    -webkit-box-ordinal-group:6;
    -ms-flex-order:5;
    order:5
  }
  .elementor-reverse-tablet>.elementor-container>.elementor-row>:nth-child(7) {
    -webkit-box-ordinal-group:5;
    -ms-flex-order:4;
    order:4
  }
  .elementor-reverse-tablet>.elementor-container>.elementor-row>:nth-child(8) {
    -webkit-box-ordinal-group:4;
    -ms-flex-order:3;
    order:3
  }
  .elementor-reverse-tablet>.elementor-container>.elementor-row>:nth-child(9) {
    -webkit-box-ordinal-group:3;
    -ms-flex-order:2;
    order:2
  }
  .elementor-reverse-tablet>.elementor-container>.elementor-row>:nth-child(10) {
    -webkit-box-ordinal-group:2;
    -ms-flex-order:1;
    order:1
  }
}
```

**Comment by jonnymueller** [comment] 2021-05-06 08:40
+1

**Comment by edition-lachance** [comment] 2021-06-03 13:25
+1

**Comment by karizmaj** [comment] 2021-07-14 00:59
+1

**Comment by EricJammin** [comment] 2021-08-04 22:53
How is this still not fixed?

It's unreal how many bugs the Elementor team continues to push out.

**Comment by jonnymueller** [comment] 2021-08-18 14:05
How bout now?
Just got an email from elementor about breakpoint improvements.
Has anyone tested if this works now?

**Comment by spoongefeesh** [comment] 2021-08-24 08:03
+1

This has been happening for _ages_ now. Also nav menu dropdown mode doesn't kick in until 1024px (default breakpoint) after changing tablet to custom breakpoint.

**Comment by d19dotca** [comment] 2021-08-31 03:23
This bug really needs to be fixed. @shilo-ey - this hasn't even been triaged yet and it's been sitting since October 2020, nearly 11 months now.

**Comment by DorShahar** [comment] 2021-12-14 15:34
This issue has been added to Elementor Core v3.5.0

Feel free to update

Thanks!

**Closed by DorShahar** 2021-12-14 15:34 UTC
Labels: bug, status/merged

**Comment by m-seijo** [comment] 2021-12-18 23:04
I'm still able to reproduce the issue using Elementor v3.5.0

**Comment by vaidanshi-team** [comment] 2022-06-11 06:55
not seeing Reverse Column options in 3.6.6
