### ISSUE TITLE
Allow sum of column widths to be greater than 100% and then wrap columns

### ISSUE THREAD

**Issue by Stegosource** [elementor/elementor#2261] opened 2017-08-24 21:17 UTC
## Description

This is a feature request. Right now, Elementor allows you to edit the width of individual columns, but they can only total up to 100%. It would be nice to be able to add columns that can go greater than this, but have them wrap. 

For example, 50% 50% 50% 50%. This would produce 1 section with 4 columns within it, but 2 columns would be stacked above the other 2.

## Why the current version is not great

If I want to add a 3x4 grid of images (let's say a list of my client logos), I have to use 3 sections with 4 columns each. A bit more work, but not bad.

What if I want that page section to have a background color? I have to apply it to all 3 sections individually (or maybe wrap them in another section). Yeah, still not too bad, but more work nonetheless.
 
And if later I decide to move those images higher or lower on the page? Once again I have to move all 3 (or wrap them in another section).

But here's the real kicker. What if the order of my images matters, and I want to add another image anywhere except the end? That means I have to manually drag and drop image from one column to the next. This is a LOT of work potentially. 

## Why this proposal is great!

If custom column widths could add up to more than 100% and then wrap, all the issues above would be trivial to fix. Every column would exist inside 1 section, so they would share that sections background color, and if that 1 section is moved they all go. Most importantly, it allows a column to be dragged and dropped anywhere within the section, and the other columns will accommodate easily.

## Steps to reproduce

Add columns in Elementor. Edit widths of each column. They cannot go above a total of 100%.

**Comment by maxwellhibbert** [comment] 2017-09-09 20:54
This is a really great idea. Would make working with a grid so much better.

**Comment by Stegosource** [comment] 2017-09-09 23:26
Yeah thanks. I think so as well. Give it an upvote and hopefully they will move it up the list :)

**Comment by black-eye** [comment] 2018-01-17 03:36
Agreed, similar problem mentioned here: #2218

**Comment by tomas-eklund** [comment] 2018-10-10 08:59
+1

**Comment by jotcreative** [comment] 2019-12-20 17:13
+1

**Comment by arielk** [comment] 2020-09-01 19:59
Duplicate of #2218

**Closed by arielk** 2020-09-01 19:59 UTC
Labels: request/enhancement

**Comment by nicholaszein** [comment] 2022-11-16 05:17
Hello there!

We have great news! 🙌 

### 📢 We're happy to announce that you can use the <ins>stable</ins> version of the Flexbox Container released with Elementor **v3.8** to wrap as manny child containers as you want! 🥳 

✔️ Please feel free to check it out and update your plugin to the new version!

Cheers 🥂
