### ISSUE TITLE
🐞 Bug report: [23-Mar-2022 10:31:06 UTC] PHP Deprecated:  _register_controls est <strong>obsolète</strong> depuis la version 3.1.0 !

### ISSUE THREAD

**Issue by Lovecraft49** [elementor/elementor#18234] opened 2022-03-23 10:41 UTC
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Hello, 

I find this bug on my debug.log file since this morning. 

It happens every minute and disappear when Elementor is disabled.

![Uploading 
![ScreenShot612](https://user-images.githubusercontent.com/102222588/159680278-5a091e2b-992f-475e-83cc-dc0609275faf.jpg)
ScreenShot586.jpg…]()

### Steps to reproduce

I have not done anything special between yesterday and today. 

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

<html>
<body>

Operating System: | Linux |  
-- | -- | --
Software: | Apache/2.4.18 (Ubuntu) |  
MySQL version: | Ubuntu 16.04 v5.6.42-84.2 |  
PHP Version: | 7.4.10 |  
PHP Memory Limit: | 128M |  
PHP Max Input Vars: | 1000 |  
PHP Max Post Size: | 500M |  
GD Installed: | Yes |  
ZIP Installed: | No |  
Write Permissions: | All right |  
Elementor Library: | Connected

</body>
</html>

**Comment by udidol** [comment] 2022-03-23 11:03
@Lovecraft49
This is likely caused by a 3rd party plugin/theme.
You didn't share the full log of the error so we cannot tell you which 3rd party plugin/theme is causing this error.

**Comment by voicaandrei** [comment] 2022-03-23 12:22
```
wp-includes/functions.php:5316
Elementor\M\D\Deprecation->deprecated_function()
wp-content/plugins/elementor/includes/base/controls-stack.php:2278
Elementor\Controls_Stack->init_controls()
wp-content/plugins/elementor/includes/base/controls-stack.php:494
Elementor\Controls_Stack->get_stack()
wp-content/plugins/elementor/includes/base/widget-base.php:177
Elementor\Widget_Base->get_stack()
wp-content/plugins/elementor/includes/base/controls-stack.php:300
Elementor\Controls_Stack->get_controls()
wp-content/plugins/elementor/includes/base/controls-stack.php:2369
Elementor\Controls_Stack->sanitize_settings()
wp-content/plugins/elementor/includes/base/controls-stack.php:1105
Elementor\Controls_Stack->get_data()
wp-content/plugins/elementor/includes/base/controls-stack.php:2116
Elementor\Controls_Stack->get_init_settings()
wp-content/plugins/elementor/core/base/base-object.php:142
Elementor\C\B\Base_Object->ensure_settings()
wp-content/plugins/elementor/core/base/base-object.php:40
Elementor\C\B\Base_Object->get_settings()
wp-content/plugins/elementor/core/files/css/post.php:296
Elementor\C\F\C\Post->render_styles()
wp-content/plugins/elementor/core/files/css/post.php:226
Elementor\C\F\C\Post->add_controls_stack_style_rules()
wp-content/plugins/elementor/core/files/css/post.php:298
Elementor\C\F\C\Post->render_styles()
wp-content/plugins/elementor/core/files/css/post.php:226
Elementor\C\F\C\Post->add_controls_stack_style_rules()
wp-content/plugins/elementor/core/files/css/post.php:298
Elementor\C\F\C\Post->render_styles()
wp-content/plugins/elementor/core/files/css/post.php:178
Elementor\C\F\C\Post->render_css()
wp-content/plugins/elementor/core/files/css/base.php:632
Elementor\C\F\C\Base->parse_content()
wp-content/plugins/elementor/core/files/base.php:180
Elementor\C\F\Base->update_file()
wp-content/plugins/elementor/core/files/css/base.php:131
Elementor\C\F\C\Base->update()
wp-content/plugins/elementor/core/files/css/base.php:218
Elementor\C\F\C\Base->enqueue()
wp-content/plugins/elementor/core/files/css/post.php:201
Elementor\C\F\C\Post->enqueue()
wp-content/plugins/elementor/includes/frontend.php:639
Elementor\Frontend->enqueue_styles()
wp-includes/class-wp-hook.php:307
do_action('wp_enqueue_scripts')
wp-includes/script-loader.php:2105
wp_enqueue_scripts()
wp-includes/class-wp-hook.php:307
do_action('wp_head')
wp-includes/general-template.php:3042
wp_head()
```

I've got the same error and this is the stack trace that I get. On some environments, it also crash the rest api making page load/save imposible

**Comment by astbarc** [comment] 2022-03-23 12:37
Same problem here after updating to 3.6, 

I don't think is related to 3rd party plugin as it can see on debugger information.

**Comment by Lovecraft49** [comment] 2022-03-23 12:46
> @Lovecraft49 This is likely caused by a 3rd party plugin/theme. You didn't share the full log of the error so we cannot tell you which 3rd party plugin/theme is causing this error.

here is the last part of the error log : 
PHP Deprecated:  _register_controls est <strong>obsolète</strong> depuis la version 3.1.0 ! Utilisez Elementor\Controls_Stack::register_controls() à la place. in /var/www/clients/client13/web37/web/wp-includes/functions.php on line 5316

**Comment by udidol** [comment] 2022-03-23 13:17
@Lovecraft49 Deactivate all of your plugins except for Elementor and Elementor Pro, then activate them one by one and check if you get the error - That is how you will find the responsible extension.

**Comment by loorlab** [comment] 2022-03-24 20:35
+1

**Comment by steve340700** [comment] 2022-03-26 10:18
Hello,

I have the same error, even when disabling the plugins

https://www.entreprisedunet.fr/

PHP Deprecated:  _register_controls est <strong>obsolète</strong> depuis la version 3.1.0 ! Utilisez Elementor\Controls_Stack::register_controls() à la place. in /home/oilenergnh/wwwent/wp-includes/functions.php on line 5316

**Comment by rami-elementor** [comment] 2022-04-09 21:52
@Lovecraft49 @loorlab @steve340700 

One of the addons on your site is using deprecated code.

We don't have control over 3rd party plugins that don't remove outdated code.

See this dev doc explaining how to fix the issue: https://developers.elementor.com/docs/deprecations/simple-example/

**Comment by rami-elementor** [comment] 2022-04-13 23:27
@Lovecraft49 we don't have access to your site. 

Please follow @udidol instructions:

> Deactivate all of your plugins except for Elementor and Elementor Pro, then activate them one by one and check if you get the error - That is how you will find the responsible extension.

When you find the plugin causing the issue. Contact the plugin developer and ask him to check for deprecated code in his plugin and update it accordingly.

**Comment by rami-elementor** [comment] 2022-04-24 11:22
Hi @crstauf ,

The code you attached is a good example of our deprecation process. We support both the new `register_controls()` method and the old deprecated `_register_controls()` method. When using the old method in the [deprecation period](https://developers.elementor.com/docs/deprecations/#deprecation-period-example), the code notifies addon developers that they use deprecated methods and need to update their code.

How we do that? using this code that allows developers to debug their addons:

```php
Plugin::$instance->modules_manager->get_modules( 'dev-tools' )->deprecation->deprecated_function(
  '_register_controls',
  '3.1.0',
  __CLASS__ . '::register_controls()'
);
```

The `_register_controls()` method was renamed in **Elementor 3.1**, it means that in **Elementor 3.9** we will delete the old method.

When you understand our deprecation process, you see that Elementor is not causing this problem, the external addon is carousing the problem by using deprecated code. If the addon switch to the new method, you won't see this PHP notice anymore.

**Comment by rami-elementor** [comment] 2022-04-24 11:26
I should note that although the fix is simple, this is a familiar issue with addons #17580

**Comment by crstauf** [comment] 2022-04-24 12:44
@rami-elementor Yes, I understand your deprecation process, however, `init_controls()` is a protected function, which means that your own plugin calls it, not an add-on. Suggesting that it is an add-ons fault when `init_controls()` is protected is foolish.

Here's the full stack trace, and you'll see that the source of call is the `the_content` filter, which is used often within WordPress core, and means that it is not caused by an add-on:

<img width="1387" alt="2022-04-24T124109" src="https://user-images.githubusercontent.com/4573033/164977084-15330142-2016-4ca5-baaf-43b30b83ae19.png">

Please fix your own code, and stop blaming others.

**Comment by crstauf** [comment] 2022-04-24 14:53
Would it not make more sense to check if the new method exists and call that if it does?

**Comment by crstauf** [comment] 2022-04-30 13:44
@rami-elementor @udidol What version can we expect this to be fixed?

**Comment by crstauf** [comment] 2022-05-09 17:47
@rami-elementor @udidol It's not a great look to ignore your users.

What version can we expect this to be fixed?

**Comment by loorlab** [comment] 2022-05-10 03:56
> @rami-elementor @udidol It's not a great look to ignore your users.
> 
> What version can we expect this to be fixed?

 @danielkatz 🙏

**Comment by crstauf** [comment] 2022-05-27 22:57
:cry:

**Comment by nkireland** [comment] 2022-05-31 14:32
I'm now having this issue, too.

**Comment by crstauf** [comment] 2022-06-22 14:00
Two months later after being shown it's Elementor with the problem, and still no response. Wonderful.

**Comment by pippenet** [comment] 2022-06-24 07:27
Same problem and I can't find a solution either. I've tested a lot. I put the elementor and the pro on an empty new wordpress page, there is no other plugin on the page yet, the error is already there. :(

**Comment by udidol** [comment] 2022-06-26 08:27
@pippenet What theme are you using?

**Comment by pippenet** [comment] 2022-06-26 10:09
@udidol now Generatepress Pro, but I tried Astra and Ocean Wp pro. Nothing changed.

**Comment by udidol** [comment] 2022-06-26 11:15
@pippenet Try Hello Elementor. It is possible that Generatepress Pro, Astra and Ocean WP Pro have elementor integrations that are not up to date.

**Comment by crstauf** [comment] 2022-06-26 17:27
@udidol Are you kidding? I have showed you the error comes from within Elementor. Why ignore that?

**Comment by udidol** [comment] 2022-06-27 07:07
@crstauf
There are literally millions of websites running the latest versions of Elementor Core and Pro with no issue.
I invite you to contact Elementor's support, provide them with login details to a website of yours that is experiencing this issue, tell them that Udi referred you and that I asked your ticket to be forwarded to me, and I will look into your case.

**Comment by pippenet** [comment] 2022-06-27 12:22
@udidol I tried Hello Elementor theme, on a new site, added Elementor and Elementor pro. New site, no other plugins, but the error log alredy contains:  PHP: 2022-06-27 12:05:13 [notice X 2][/home/www/clients/client5384/web11633/web/wp-content/plugins/elementor/core/experiments/experiments-reporter.php::89] Undefined index: title [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

**Comment by udidol** [comment] 2022-06-27 12:40
@pippenet That is a different issue and has nothing to do with this one. And it should not affect your use of Elementor in any way

**Comment by pippenet** [comment] 2022-06-27 12:49
@udidol true, sorry, I deviated from the subject, I wandered over to install the new page and theme

**Comment by crstauf** [comment] 2022-06-27 20:59
@udidol I have provided you everything you need to understand that this issue is coming from your own plugin:
- https://github.com/elementor/elementor/issues/18234#issuecomment-1105908980
- https://github.com/elementor/elementor/issues/18234#issuecomment-1107834210

Why is this insufficient for you to look into and resolve?

Because you seem unwilling to accept the data I have provided you here, I will create a duplicate of the site I experienced the issue on, restore the deprecation notice, and disable as much as I can on the site for the issue to still be experienced.

**Closed** 2022-07-03 09:52 UTC
Labels: bug

**Comment by crstauf** [comment] 2022-07-03 18:08
> I see that you did not follow my basic instructions from the Github issue thread for debugging your issue, but you were very quick to complain.
> 
> That PHP notice is coming from a non-Elementor plugin called Sober Addons.
You should talk to them about their compatibility with newer versions of Elementor.
> 
> You can refer them to this doc: https://elementor.com/help/compatibility-tags/
which will help notify their users about which Elementor version they are compatible with, and will encourage them to check with each released version. 
> 
> You should also recommend to them to subscribe to Elementor's Developers newsletter which sends out e-mails about planned deprecations so 3rd party plugins could prepare properly.

Lol anything to get away from taking responsibility from your own plugin. Yes, the problem goes away if you disable Sober Addons plugin, but the deprecation notices come from protected methods in Elementor. Do you know what a protected method is, what it means?

My goodness: you pay for a product, you expect support. But nah, we ain't going to do that. Gross. 🤮

**Comment by crstauf** [comment] 2022-07-03 18:14
I suppose the only option left is for me to do the support work for you. How disappointing, that developers have to fight each other, rather than work together to solve problems.

**Comment by udidol** [comment] 2022-07-03 18:43
I will ignore your aggressive attitude and respond to you for the last
time, since I've given you the answer to your question.endeavors

Elementor has an organized and public deprecation process. The fact that
you decided to use an outdated plugin is on you, not on us. Elementor is an
open-source product so third parties use it as they please. You expect
Elementor to take responsibility for something that it didn't do, that's
your problem.

Best of luck in your future endeavors.

**Comment by crstauf** [comment] 2022-07-03 18:49
And there you have it! Completely ignore everything proven, and cast it off as the other person's problem. Glorious!

**Comment by crstauf** [comment] 2022-07-04 18:10
Okay, @udidol, I did your work for you, and here's what I figured out, and if I were a customer support agent for Elementor would've said, you know, to support my customers and prevent this from boiling up:

> The `Controls_Stack` class that is creating the deprecation notice is an abstract class, inherited by other classes. This means that a theme or plugin on your site is using is inheriting the `Controls_Stack` class and defining the `_register_controls()` method, which is now deprecated, rather than the `register_controls()` method. Please notify the plugin or theme author that they're using a deprecated method, and once fixed in a future version, the deprecation notice will go away.

The level of detail and instruction is sufficient to satisfy both non-technical and technical users. Sticking with "it's not our problem" over and over, is not helpful; providing even a little bit of detail would've resolved this months ago.
