### ISSUE TITLE
Video element - Youtube Autoplay is not working

### ISSUE THREAD

**Issue by pixar1942** [elementor/elementor#7728] opened 2019-04-04 03:54 UTC
I think the youtube update the way how they autoplay their videos in embed by adding this 
?autoplay=1 at the end of youtube url in iframe but if you try to add ?autoplay=1 in video element the autoplay still not working. 

Elementor - v2.5.11

![screen](https://user-images.githubusercontent.com/5967114/55528426-513eef80-568c-11e9-8c4a-55ef49190cf5.JPG)

**Comment by shilo-ey** [comment] 2019-04-04 06:34
Duplicate of #6916

**Closed by shilo-ey** 2019-04-04 06:34 UTC

**Comment by pixar1942** [comment] 2019-04-04 07:06
The duplicate thread didn't help I did a test page to show the youtube video autoplay is not working

http://safeatheights.pwd.net.au/test-page/

Same settings to the image I attached.


Thanks
