### ISSUE TITLE
🔗 Elementor Login Form - Redirecting to login page after wrong password or username (Duplicate of #5355)

### ISSUE THREAD

**Issue by DevrimOzsoy** [elementor/elementor#6119] opened 2018-11-10 17:23 UTC
## Prerequisites

- [ ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
If the user enters the wrong password, he’s redirected to Wordpress login page instead of the custom login page.

**Describe the solution you'd like**
Redirecting user to custom login page with an error message (Ex: Wrong username or password, please try again"). 

**Describe alternatives you've considered**
Workaround: custom code in my theme functions.php to redirect the user to another page

**Additional context**

**Comment by bainternet** [comment] 2018-11-11 07:59
Duplicate of #5355

**Closed by bainternet** 2018-11-11 07:59 UTC
Labels: product/pro, mod*, widget/pro/login-form, duplicate, mod/d*, mod/r*, mod/b*

**Comment by wilsonwc** [comment] 2019-03-11 04:14
For those looking for a solution to this, here is what I came up with:

Add this to your functions.php or code snippets plugin:
```php
//add hook to redirect the user back to the elementor login page if the login failed
add_action( 'wp_login_failed', 'elementor_form_login_fail' );
function elementor_form_login_fail( $username ) {
    $referrer = $_SERVER['HTTP_REFERER'];  // where did the post submission come from?
    // if there's a valid referrer, and it's not the default log-in screen
    if ( !empty($referrer) && !strstr($referrer,'wp-login') && !strstr($referrer,'wp-admin') ) {
        //redirect back to the referrer page, appending the login=failed parameter and removing any previous query strings
        //maybe could be smarter here and parse/rebuild the query strings from the referrer if they are important
        wp_redirect(preg_replace('/\?.*/', '', $referrer) . '/?login=failed' );
        exit;
    }
}
```
Then using the dynamicconditions plugin (https://wordpress.org/plugins/dynamicconditions/) you can configure a text/alert element above/below your form to only show up when "Request Parameter login is equal to failed" in the Advanced->Dynamic Conditions configuration on your widget (see attached image). Cheers!
<img width="271" alt="dynamic_configuration" src="https://user-images.githubusercontent.com/748496/54099964-9c156200-4381-11e9-83dc-e5b881e66cca.png">
