### ISSUE TITLE
🔗 🐞 Bug Report: Accordion Widget has hard coded "<a "href" causing Lighhouse and SEO issues (Duplicate of #14371)

### ISSUE THREAD

**Issue by sjb1963** [elementor/elementor#20477] opened 2022-11-21 20:56 UTC
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Using the accordion widget, the titles of the accordion items have a hard coded link ("<a></a>) in them. This is an error. These should NOT be links unless they are actually linked to a destination. Since there is no functionality that allows this, it's an error.

This causes Lighthouse to complain (correctly) that the links are not crawlable. This causes SEO issues as well.

### Steps to reproduce

Go to this page:
https://fhr.bwdsandbox.com/
Open the page, then go to Chrome Admin Tools. Choose Lighthouse and analyze the desktop version. At the end, choose the "SEO" button and review the "Uncrawlabe links" section and you will see each of the Accordion titles is listed there.

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

<html>
<body>
<div class="elementor-system-info-section elementor-system-info-server" style="outline: 0px; margin-bottom: 10px; color: rgb(60, 67, 74); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen-Sans, Ubuntu, Cantarell, &quot;Helvetica Neue&quot;, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(0, 0, 0); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">

Server Environment |   |  
-- | -- | --
Operating System: | Linux |  
Software: | nginx/1.21.4 |  
MySQL version: | mariadb.org binary distribution v10.5.18 |  
PHP Version: | 7.4.33 |  
PHP Memory Limit: | 256M |  
PHP Max Input Vars: | 1000 |  
PHP Max Post Size: | 256M |  
GD Installed: | Yes |  
ZIP Installed: | Yes |  
Write Permissions: | All right |  
Elementor Library: | Connected |  

</div>
</body>
</html>Server Environment		
Operating System:	Linux	
Software:	nginx/1.21.4	
MySQL version:	mariadb.org binary distribution v10.5.18	
PHP Version:	7.4.33	
PHP Memory Limit:	256M	
PHP Max Input Vars:	1000	
PHP Max Post Size:	256M	
GD Installed:	Yes	
ZIP Installed:	Yes	
Write Permissions:	All right	
Elementor Library:	Connected	
WordPress Environment		
Version:	6.1.1	
Site URL:	https://fhr.bwdsandbox.com	
Home URL:	https://fhr.bwdsandbox.com	
WP Multisite:	No	
Max Upload Size:	256 MB	
Memory limit:	1024M	
Max Memory limit:	1024M	
Permalink Structure:	/%category%/%postname%/	
Language:	en-US	
Timezone:	America/Chicago	
Admin Email:	steve.berry@berrywebdesigns.email	
Debug Mode:	Inactive	
Theme		
Name:	BuddyX Pro Child Theme	
Version:	1.0.0	
Author:	wbcomdesigns	
Child Theme:	Yes	
Parent Theme Name:	BuddyxPro	
Parent Theme Version:	3.9.3	
Parent Theme Author:	wbcomdesigns	
User		
Role:	administrator	
WP Profile lang:	en_US	
User Agent:	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36	
Active Plugins		
[Admin Menu Editor Pro](http://adminmenueditor.com/) - 2.18.1	By [Janis Elsts](http://w-shadow.com/)	
[Admin Tools Professional for WordPress](https://www.akeeba.com/) - 1.5.8	By [Akeeba Ltd](https://www.akeeba.com/)	
[Akeeba Backup Professional for WordPress](https://www.akeeba.com/) - 7.7.4	By [Akeeba Ltd](https://www.akeeba.com/)	
BWD-Branding	By [Berry Web Designs](https://berrywebdesigns.com/)	
BWD-Shortcodes	By [Berry Web Designs](https://berrywebdesigns.com/)	
[Classic Widgets](https://wordpress.org/plugins/classic-widgets/) - 0.3	By [WordPress Contributors](https://github.com/WordPress/classic-widgets/)	
[Designer Powerup for Elementor](https://designerpowerup.com/) - 2.2.8	By [Paras Shah](https://heyparas.com/)	
[Disable User Login](https://wordpress.org/plugins/disable-user-login) - 1.3.2	By [Saint Systems](https://www.saintsystems.com/)	
[DJ-Accessibility Pro](https://dj-extensions.com/yootheme/dj-accessibility) - 1.05	By [DJ-Extensions.com](https://dj-extensions.com/)	
[Doubly Pro](http://doubly.pro/) - 1.0.37	By Unlimited Elements	
[Duplicate Menu](https://github.com/jchristopher/duplicate-menu) - 0.2.2	By [Jonathan Christopher](https://jonchristopher.us/)	
[Elementor](https://elementor.com/?utm_source=wp-plugins&utm_campaign=plugin-uri&utm_medium=wp-dash) - 3.8.1	By [Elementor.com](https://elementor.com/?utm_source=wp-plugins&utm_campaign=author-uri&utm_medium=wp-dash)	
[Elementor Pro](https://go.elementor.com/wp-dash-wp-plugins-author-uri/) - 3.8.2	By [Elementor.com](https://go.elementor.com/wp-dash-wp-plugins-author-uri/)	
[ElementsKit Lite](https://products.wpmet.com/elementskit) - 2.7.4	By [Wpmet](https://wpmet.com/)	
[ElementsKit Pro](https://wpmet.com/plugin/elementskit) - 2.8.0	By [Wpmet](https://wpmet.com/)	
[Envira Gallery](http://enviragallery.com/) - 1.9.4.7	By [Envira Gallery Team](http://enviragallery.com/)	
[Envira Gallery - Tags Addon](http://enviragallery.com/) - 1.7.15	By [Envira Gallery Team](http://enviragallery.com/)	
[Fluent Forms](https://wpmanageninja.com/wp-fluent-form/) - 4.3.22	By [Contact Form - WPManageNinja LLC](https://fluentforms.com/)	
[Fluent Forms Pro Add On Pack](https://wpfluentforms.com/) - 4.3.21	By [Fluent Forms](https://wpfluentforms.com/)	
[FluentSMTP](https://fluentsmtp.com/) - 2.2.2	By [FluentSMTP & WPManageNinja Team](https://fluentsmtp.com/)	
[Happy Elementor Addons](https://happyaddons.com/) - 3.7.2	By [weDevs](https://happyaddons.com/)	
[Happy Elementor Addons Pro](https://happyaddons.com/) - 2.6.1	By [weDevs](https://happyaddons.com/)	
[Health Check & Troubleshooting](https://wordpress.org/plugins/health-check/) - 1.5.1	By [The WordPress.org community](https://wordpress.org/plugins/health-check/)	
[If Menu - Visibility control for menus](https://layered.store/plugins/if-menu) - 0.16.3	By [Layered](https://layered.store/)	
[Kirki Customizer Framework](https://kirki.org/) - 4.0.24	By [David Vongries](https://davidvongries.com/)	
[Max Mega Menu](https://www.megamenu.com/) - 3.0	By [megamenu.com](https://www.megamenu.com/)	
[Max Mega Menu - Pro Addon](https://www.megamenu.com/) - 2.2.7	By [megamenu.com](https://www.megamenu.com/)	
[Members](https://memberpress.com/plugins/members) - 3.2.2	By [MemberPress](https://memberpress.com/)	
Menu Item Duplicator - 1.0.2	By [Mathieu Hays](https://mathieuhays.co.uk/)	
[Move Addons Pro for Elementor](https://demo.moveaddons.com/) - 1.2.1	By [moveaddons](https://moveaddons.com/)	
[Pages with category and tag](https://dev.back2nature.jp/en/pages-with-category-and-tag/) - 0.9.0	By [YAHMAN](https://back2nature.jp/)	
[Plugin Groups](https://cramer.co.za/) - 2.0.6	By [David Cramer](https://cramer.co.za/)	
[Premium Addons for Elementor](https://premiumaddons.com/) - 4.9.38	By [Leap13](https://leap13.com/)	
[Premium Addons PRO](https://premiumaddons.com/) - 2.8.14	By [Leap13](https://leap13.com/)	
[Shortcode in Menus](https://wordpress.org/plugins/shortcode-in-menus/) - 3.5.1	By [Gagan Deep Singh](https://gagan0123.com/)	
[Simple History](http://simple-history.com/) - 3.3.1	By [Pär Thernström](http://simple-history.com/)	
[Smart Slider 3 Pro](https://smartslider3.com/) - 3.5.1.12	By [Nextend](https://smartslider3.com/)	
[The Plus Addons for Elementor](https://theplusaddons.com/) - 5.1.14	By [POSIMYTH](https://posimyth.com/)	
[The Plus Addons for Elementor - Pro](https://theplusaddons.com/) - 5.1.3	By [POSIMYTH](https://posimyth.com/)	
[Two Factor](https://wordpress.org/plugins/two-factor/) - 0.7.3	By [Plugin Contributors](https://github.com/wordpress/two-factor/graphs/contributors)	
[Unlimited Elements for Elementor (Premium)](http://unlimited-elements.com/) - 1.5.38	By [Unlimited Elements](http://unlimited-elements.com/)	
[W3 Total Cache](https://www.boldgrid.com/totalcache/) - 2.2.7	By [BoldGrid](https://www.boldgrid.com/)	
[Wbcom Essential](https://wbcomdesigns.com/) - 3.3.0	By [Wbcom Designs](https://wbcomdesigns.com/)	
[WordPress Importer](https://wordpress.org/plugins/wordpress-importer/) - 0.8	By [wordpressdotorg](https://wordpress.org/)	
[WordPress Toolbar Editor](https://adminmenueditor.com/) - 1.4.1	By [Janis Elsts](http://w-shadow.com/)	
[WP-Optimize - Clean, Compress, Cache](https://getwpo.com/) - 3.2.9	By [David Anderson, Ruhani Rabin, Team Updraft](https://updraftplus.com/)	
[WPCode Lite](https://www.wpcode.com/) - 2.0.4.1	By [WPCode](https://www.wpcode.com/)	
[WP Downgrade | Specific Core Version](https://www.reisetiger.net/) - 1.2.5	By [Reisetiger](https://www.reisetiger.net/)	
WPForce Logout - 1.5.0	By [Sanjeev Aryal](http://www.sanjeebaryal.com.np/)	
[WP Media folder](http://www.joomunited.com/) - 5.5.1	By [Joomunited](http://www.joomunited.com/)	
[WP Rollback](https://givewp.com/) - 1.7.2	By [GiveWP.com](https://givewp.com/)	
[WP Sitemap Page](http://tonyarchambeau.com/) - 1.9.2	By [Tony Archambeau](http://tonyarchambeau.com/)	
[WP User Avatars](https://wordpress.org/plugins/wp-user-avatars/) - 1.4.1	By [Triple J Software, Inc.](https://jjj.software/)	
[WP User Profiles](https://wordpress.org/plugins/wp-user-profiles/) - 2.6.2	By [Triple J Software, Inc.](https://jjj.software/)	
[Yoast SEO](https://yoa.st/1uj) - 19.10	By [Team Yoast](https://yoa.st/1uk)	
Must-Use Plugins		
Admin Tools for WordPress - 1.5.8	By [Akeeba Ltd](https://www.akeeba.com/)	
akeeba-backup-coreupdate.php		
Health Check Troubleshooting Mode - 1.7.2		
Joomunited WP Framework - 1.0.2	By [Joomunited](http://www.joomunited.com/)	
[Plugin Groups](https://cramer.co.za/) - 2.0.6	By [David Cramer](https://cramer.co.za/)	
Elementor Experiments		
Optimized DOM Output: 	Active
Improved Asset Loading: 	Active
Improved CSS Loading: 	Active
Inline Font Icons: 	Inactive
Accessibility Improvements: 	Active
Additional Custom Breakpoints: 	Active
Import Export Website Kit: 	Active
Hide native WordPress widgets from search results: 	Active
admin_menu_rearrangement: 	Inactive by default
Flexbox Container: 	Inactive
Default to New Theme Builder: 	Active by default
Landing Pages: 	Active
Color Sampler: 	Active
Favorite Widgets: 	Active
Admin Top Bar: 	Active
Page Transitions: 	Active by default
Notes: 	Inactive
Loop: 	Inactive by default
Form Submissions: 	Active by default
Scroll Snap: 	Active by default

**Comment by nicholaszein** [comment] 2022-11-22 04:12
Hello @sjb1963!

Thank you for your submission! 🙏 

### 🔗 This issue is a Duplicate of #14371

Which is on the same subject. 

For this reason, I'm closing this issue and 🔃 **Merging** it with the original, so we can have all the discussions in one location, and deal with it more efficiently.

Feel free to continue the conversation there. 😉 

### 🔍 Please, in the future, remember to check if there isn't an issue similar to yours already opened. 

Best regards,

Nick

**Closed by nicholaszein** 2022-11-22 04:12 UTC
Labels: type/seo, component/accordion

**Comment by nicholaszein** [comment] 2023-06-19 15:32
Hello!

We have great news! 🙌 

### 📢 We're happy to announce that the issue you raised was resolved in Elementor v3.14.0! 🥳 

Now Accordions are completely a11y compatible! 💪 

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
