### ISSUE TITLE
Breakpoints Not Working

### ISSUE THREAD

**Issue by actionTurtle** [elementor/elementor#13699] opened 2021-01-27 07:56 UTC
## Prerequisites

- [ x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ x ] The issue still exists against the latest stable version of Elementor.

## Description

Breakpoints are not working for tablet. 

I think that when the break point settings were moved in the last release or whatever... That there is some issues still... 

## Steps to reproduce

Elementor Pro 3.1
Wordpress 5.6

I updated elementor to see if the break points were fixed but no luck... 

Its a standard install... 

If I updat the break point values in the sites settings (new location) that the updated does not reflect in the mobile and tablet preview section... They stay locked to their default values...

I think the front end CSS is taking the break points from those values and not the ones set in the sites settings area

**Comment by DorShahar** [comment] 2021-01-27 08:31
Hi @actionTurtle
Thanks for reaching out.  
Did you updated to **Core v3.1.0** or are you a **beta tester for** **Pro v3.1.0**?
Also - could you share more info, like:

- Steps to reproduce
- System info
- Browser
- Console errors
- Video / Screenshots 

Waiting for your reply.
Thanks

**Comment by actionTurtle** [comment] 2021-01-27 08:38
Core 3.1.0

Steps to reproduce... Change the break point settings in site settings and see if they update for the mobile and tablet previews in elementor page section

System info...

Running Nginx with a standard Wp install...

Elementor 3.1.0 and Elementor pro 3.0.10

No 3rd party elementor add-ons

**Comment by DorShahar** [comment] 2021-01-27 12:03
Hi @actionTurtle 
I couldn't reproduce any issue.

Please share short videos or screenshots with the problem.

Thanks.

**Comment by redhotneo** [comment] 2021-01-28 13:45
Hi

I have the same issue with breakpoints but Elementor is no longer working. I changed the breakpoints in global settings and none of the changes to effect. But Elementor cannot operate now.

Error below using Elementor Pro 3.0.9 and 3.1 (same issue with all Elementor):

Error 500
There has been a critical error on this website.

Learn more about debugging in WordPress.

Uncaught RangeException: Max value for this device is out of range. in /chroot/home/ouyejnan/justcodes.co.za/html/wp-content/plugins/elementor_old/includes/stylesheet.php:300
Stack trace:
#0 /chroot/home/ouyejnan/justcodes.co.za/html/wp-content/plugins/elementor_old/includes/stylesheet.php(354): Elementor\Stylesheet->get_device_max_value('tablet')
#1 /chroot/home/ouyejnan/justcodes.co.za/html/wp-content/plugins/elementor_old/includes/stylesheet.php(385): Elementor\Stylesheet->hash_to_query(Array)
#2 [internal function]: Elementor\Stylesheet->Elementor\{closure}('max_tablet', 'max_mobile')
#3 /chroot/home/ouyejnan/justcodes.co.za/html/wp-content/plugins/elementor_old/includes/stylesheet.php(412): uksort(Array, Object(Closure))
#4 /chroot/home/ouyejnan/justcodes.co.za/html/wp-content/plugins/elementor_old/includes/stylesheet.php(149): Elementor\Stylesheet->add_query_hash('max_mobile')
#5 /chroot/home/ouyejnan/justcodes.co.za/html/wp-content/plugins/elementor_old/core/files/css/base.php(413): Elementor\Styleshee

**Comment by DorShahar** [comment] 2021-05-13 06:15
Hi. @redhotneo 
According to the stack trace, the problem in the plugin named "elementor_old". 
Elementor Core should be named "elementor" in `/wp-content/plugins/`  directory. 

Since there is no feedback from @actionTurtle who opened this issue, I'm closing it.
If the problem continues, you can open a new issue with video/screenshots and system info, or contact our support.

Thanks.

**Closed by DorShahar** 2021-05-13 06:15 UTC
Labels: status/needs feedback
