### ISSUE TITLE
Can't override {line-height: 1} with Site Settings > Typography

### ISSUE THREAD

**Issue by drawcard** [elementor/elementor#12979] opened 2020-11-02 02:16 UTC
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Steps to reproduce

Line heights cannot be overridden by Site Settings > Typography. I am adjusting the slider here:

![image](https://user-images.githubusercontent.com/1435638/97828227-64a5b700-1d16-11eb-9de1-1e3769e106e9.png)

However the line height is not changing here:

![image](https://user-images.githubusercontent.com/1435638/97828286-8bfc8400-1d16-11eb-98c1-d1e081e5d906.png)

It will however work if the "Global Typography" style line-height is adjusted:

![image](https://user-images.githubusercontent.com/1435638/97828625-8fdcd600-1d17-11eb-9c58-a6490fadf96d.png)

![image](https://user-images.githubusercontent.com/1435638/97828585-73409e00-1d17-11eb-80c3-a81b554484c8.png)

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by shilo-ey** [comment] 2020-11-02 06:57
Duplicate of #11453

**Closed by shilo-ey** 2020-11-02 06:57 UTC
