### ISSUE TITLE
🐞 Bug report: 3.7 release when Widget Space in columns is set to "0" it reverts to 20px default on live view

### ISSUE THREAD

**Issue by portrayaloflife** [elementor/elementor#19410] opened 2022-08-09 23:19 UTC
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

When widget space in columns is set to "0" it reverts to 20px default on live view but not in editor. All the spacing on our sites that had "0" set is now 20px. 

If I change it to a differen't number besides 0 it works, like 1, or 5, but when set to zero it shows 20px spacing after publishing but shows correctly within the editor. 

### Steps to reproduce

Add elements to a column, set column widget space to "0", save and view live page and you'll see it reverts to 20px.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: Flywheel/5.1.0
	MySQL version: (Google) v5.7.37
	PHP Version: 7.4.30
	PHP Memory Limit: 128M
	PHP Max Input Vars: 10000
	PHP Max Post Size: 300M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: There are some writing permissions issues with the following directories/files:
		 - WordPress root directory
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.0.1
	Site URL: https://splash.mysites.io
	Home URL: https://splash.mysites.io
	WP Multisite: No
	Max Upload Size: 300 MB
	Memory limit: 256M
	Max Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 0
	Admin Email: ben@apolloartistry.com
	Debug Mode: Inactive

== Theme ==
	Name: Apollox
	Version: 3.2.0
	Author: Apollo Artistry
	Child Theme: Yes
	Parent Theme Name: Astra
	Parent Theme Version: 3.9.1
	Parent Theme Author: Brainstorm Force

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36

== Active Plugins ==
	Astra Pro
		Version: 3.9.1
		Author: Brainstorm Force

	Elementor
		Version: 3.7.0
		Author: Elementor.com

	Elementor Pro
		Version: 3.7.3
		Author: Elementor.com

	JetElements For Elementor
		Version: 2.6.7
		Author: Crocoblock

	JetTricks
		Version: 1.4.2
		Author: Crocoblock

	Ultimate Addons for Elementor
		Version: 1.36.8
		Author: Brainstorm Force

== Elementor Experiments ==
	Optimized DOM Output: Inactive by default
	Improved Asset Loading: Inactive by default
	Improved CSS Loading: Inactive by default
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Inactive by default
	Additional Custom Breakpoints: Inactive by default
	Import Export Template Kit: Active by default
	Hide native WordPress widgets from search results: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Inactive by default
	Default to New Theme Builder: Active by default
	Landing Pages: Active by default
	Color Sampler: Active by default
	Favorite Widgets: Active by default
	Admin Top Bar: Inactive
	Page Transitions: Active by default
	Notes: Inactive
	Form Submissions: Active by default
	Scroll Snap: Inactive

== Log ==
	
Log: showing 20 of 422022-07-14 18:08:11 [info] Elementor/Upgrades - _on_each_version Start  
2022-07-14 18:08:11 [info] Elementor/Upgrades - _on_each_version Finished 
2022-07-14 18:08:11 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.4',
  'to' => '3.6.7',
)]
2022-07-14 18:08:12 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.6.5',
  'to' => '3.7.2',
)]
2022-07-14 18:08:23 [info] elementor-pro::elementor_pro_updater Started 
2022-07-14 18:08:23 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-07-14 18:08:23 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-07-14 18:08:23 [info] Elementor Pro/Upgrades - _v_3_7_2_woocommerce_rename_related_to_related_products Start  
2022-07-14 18:08:23 [info] Elementor Pro/Upgrades - _v_3_7_2_woocommerce_rename_related_to_related_products Finished 
2022-07-14 18:08:23 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.6.5',
  'to' => '3.7.2',
)]
2022-08-09 22:52:41 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.7',
  'to' => '3.7.0',
)]
2022-08-09 22:52:55 [info] elementor::elementor_updater Started 
2022-08-09 22:52:55 [info] Elementor/Upgrades - _on_each_version Start  
2022-08-09 22:52:55 [info] Elementor/Upgrades - _on_each_version Finished 
2022-08-09 22:52:55 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.7',
  'to' => '3.7.0',
)]
2022-08-09 23:08:16 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.2',
  'to' => '3.7.3',
)]
2022-08-09 23:10:38 [info] elementor-pro::elementor_pro_updater Started 
2022-08-09 23:10:38 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-08-09 23:10:38 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-08-09 23:10:38 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.2',
  'to' => '3.7.3',
)]

PHP: showing 1 of 1PHP: 2022-04-14 18:31:10 [notice X 3][/www/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] The $control_id argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatible
	JetElements For Elementor: Incompatible
	Ultimate Addons for Elementor: Incompatible

== Elementor Pro - Compatibility Tag ==
	
	JetElements For Elementor: Incompatible
	Ultimate Addons for Elementor: Compatible

**Comment by rami-elementor** [comment] 2022-08-10 07:04
Duplicate of #19393

**Closed by rami-elementor** 2022-08-10 07:04 UTC
Labels: bug

**Comment by shilo-ey** [comment] 2022-08-14 08:33
This issue has been resolved in Elementor v3.7.1

Feel free to update

Thanks!

**Comment by NAROLLES** [comment] 2022-08-14 10:24
The same problem is not solved by the latest version for those who use the flex container

**Comment by mkiii333** [comment] 2022-08-15 12:15
> The same problem is not solved by the latest version for those who use the flex container

+1 please fix it asap.

**Comment by mbaierl** [comment] 2022-08-16 10:20
The issue is not yet solved for Flexbox Containers. Still 10px padding.

**Comment by NAROLLES** [comment] 2022-08-16 11:03
> Le même problème n'est pas résolu par la dernière version pour ceux qui utilisent le conteneur flexible

Hello
The solution concerning padding for flex containers like the rest is in the new function implemented in the site settings. Go to layout settings.

Perhaps it was necessary to inform the community of this new function; It would have avoided a lot of inconvenience
Thanks

**Comment by m1ga** [comment] 2022-08-16 11:41
@NAROLLES to be fair it was in the release notes :wink: 
> Tweak: Added default padding values to Container Element
> Tweak: Added site-wide containers padding option to Site Settings

also it is still an experiment so stuff could change before release. That said: I saw the PR before hand and could change my theme before the release :smile:  And the devs responded in the beta thread to that change. 
Still not a fan of default paddings and that one is a bit difficult to find if you don't know about the site settings

**Comment by NAROLLES** [comment] 2022-08-16 12:22
Hello @m1ga 
Thanks for the details...
My point is not controversial, but not everyone is a developer. I look at the changeslog but an e-mail notice would be necessary if this can significantly change the look of a site.
I am not a beta tester but I agree to use the experiments.
I usually trust and have for a long time but sometimes there are bugs (pro and standard) and the communities of more experts than me on social networks are sometimes more worried than me....not to mention that the support does not was not able to answer me this simplicity. Thank you for your work...FYI I find that the flex design is much simpler....on the padding here is a suggestion from a non-expert.... we will have to find solutions in all the widget parameters for a adjustment which allows a real responsibility of a zoom screen at 25% to 100% as is the case above .... but it is less urgent. Thanks

**Comment by m1ga** [comment] 2022-08-16 12:25
@NAROLLES I totally understand you! I've opt-in to flexbox too and since I don't want my sites to break I follow the PRs but that's not mainstream and shouldn't be needed :smile: 

And yes: soooo much better and easier to work with. Hope they can focus on it a bit more to bring it out of the alpha status. I know there are many open features and everyone needs something else. But its already nice to work with it
