### ISSUE TITLE
[🧐 Evaluating] Unable to remove padding (or margin)

### ISSUE THREAD

**Issue by JakeQZ** [elementor/elementor#20369] opened 2022-11-11 02:32 UTC
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

After setting padding (or margin) for an element, it can't be cleared.

The default is blank, which means whatever default there is is not overridden.

But after setting a value, it can't be set back to blank.  It can only be set to a number.

The best hope for padding is to set it to `-1` (minus one), since that's an invalid value.  But that won't work for margins.

### Steps to reproduce

1. Set padding for an element.
2. Try to undo that.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MySQL Community Server - (GPL) v5.7.39
	PHP Version: 7.3.33
	PHP Memory Limit: 512M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 128M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.0.3
	Site URL: https://www.performancepads.co.uk/wordpress
	Home URL: https://www.performancepads.co.uk
	WP Multisite: No
	Max Upload Size: 128 MB
	Memory limit: 40M
	Max Memory limit: 512M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%
	Language: en-GB
	Timezone: Europe/London
	Admin Email: admin@performancepads.co.uk
	Debug Mode: Active

== Theme ==
	Name: Performance Movers
	Version: 1.4.0
	Author: QZ Design
	Child Theme: Yes
	Parent Theme Name: Expert Movers
	Parent Theme Version: 0.5.2
	Parent Theme Author: Luzuk

== User ==
	Role: administrator
	WP Profile lang: en_GB
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:106.0) Gecko/20100101 Firefox/106.0

== Active Plugins ==
	Akismet Anti-Spam
		Version: 5.0.1
		Author: Automattic

	All-in-One WP Migration
		Version: 7.67
		Author: ServMask

	Category Editor
		Version: 3.8.3
		Author: Kevin Heath

	Classic Editor
		Version: 1.6.2
		Author: WordPress Contributors

	Classic Widgets
		Version: 0.3
		Author: WordPress Contributors

	Elementor
		Version: 3.8.0
		Author: Elementor.com

	Elementor Header &amp; Footer Builder
		Version: 1.6.13
		Author: Brainstorm Force, Nikhil Chavan

	Formidable Forms
		Version: 5.5.3.1
		Author: Strategy11 Form Builder Team

	Head, Footer and Post Injections
		Version: 3.2.5
		Author: Stefano Lissa

	Menu Icons
		Version: 0.13.1
		Author: ThemeIsle

	Mobile Menu
		Version: 1.0.1
		Author: QZ Design

	Order Export &amp; Order Import for WooCommerce
		Version: 2.2.8
		Author: WebToffee

	Payment Plugins for Stripe WooCommerce
		Version: 3.3.31
		Author: Payment Plugins, support@paymentplugins.com

	Performance Pads
		Version: 1.0.1
		Author: QZ Design

	Product page shipping calculator for WooCommerce
		Version: 1.3.3
		Author: PI Websolution

	Simple Banner
		Version: 2.12.2
		Author: Ryan Petersen

	Trustpilot-reviews
		Version: 2.5.914
		Author: Trustpilot

	UpdraftPlus - Backup/Restore
		Version: 1.22.11
		Author: UpdraftPlus.Com, DavidAnderson

	Velvet Blues Update URLs
		Version: 3.2.10
		Author: VelvetBlues.com

	Widget Menuizer
		Version: 1.1.1
		Author: Cornershop Creative

	WooCommerce
		Version: 6.3.1
		Author: Automattic

	Woo Default Image
		Version: 0.1.2
		Author: QZ Design

	WOOF - WooCommerce Products Filter
		Version: 1.2.6.4
		Author: realmag777

	WP File Manager
		Version: 7.1.6
		Author: mndpsingh287

	WP Mail SMTP
		Version: 3.6.1
		Author: WPForms

	Yoast SEO
		Version: 19.10
		Author: Team Yoast

== Elementor Experiments ==
	Optimised DOM Output: Active by default
	Improved asset loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Inactive by default
	Accessibility improvements: Active by default
	Additional Custom Breakpoints: Active by default
	Import Export Website Kit: Active by default
	Hide native WordPress widgets from search results: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Inactive by default
	Landing pages: Active by default
	Color Sampler: Active by default
	Favorite Widgets: Active by default
	Admin Top Bar: Active by default

== Log ==
	
Log: showing 12 of 122022-07-06 11:35:19 [info] elementor::elementor_updater Started 
2022-07-06 11:35:19 [info] Elementor/Upgrades - _on_each_version Start  
2022-07-06 11:35:19 [info] Elementor/Upgrades - _on_each_version Finished 
2022-07-06 11:35:19 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.5.5',
  'to' => '3.6.7',
)]
2022-07-06 11:35:19 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.5.5',
  'to' => '3.6.7',
)]
2022-11-11 00:35:42 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.7',
  'to' => '3.8.0',
)]
2022-11-11 00:35:45 [info] elementor::elementor_updater Started 
2022-11-11 00:35:45 [info] Elementor/Upgrades - _on_each_version Start  
2022-11-11 00:35:45 [info] Elementor/Upgrades - _on_each_version Finished 
2022-11-11 00:35:45 [info] Elementor/Upgrades - _v_3_8_0_fix_php8_image_custom_size Start  
2022-11-11 00:35:45 [info] Elementor/Upgrades - _v_3_8_0_fix_php8_image_custom_size Finished 
2022-11-11 00:35:45 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.7',
  'to' => '3.8.0',
)]

JS: showing 3 of 3JS: 2022-07-06 10:57:25 [error X 4][https://ppads.qzdesign.co.uk/content/plugins/elementor/assets/js/editor.js?ver=3.6.7:52819:44] Cannot read properties of null (reading \&#039;getBoundingClientRect\&#039;) 
JS: 2022-07-06 10:57:29 [error X 2][https://ppads.qzdesign.co.uk/content/plugins/elementor/assets/js/editor.js?ver=3.6.7:16897:22] Cannot read properties of undefined (reading \&#039;html\&#039;) 
JS: 2022-11-11 00:42:09 [error X 1][https://www.performancepads.co.uk/content/plugins/elementor/assets/js/frontend.js?ver=3.8.0:2121:46] elementor.settings.page is undefined 

== Elementor - Compatibility Tag ==
	
	Elementor Header & Footer Builder: Compatibility not specified

**Comment by JakeQZ** [comment] 2022-11-11 02:37
Please see the attached image which illustrates the problem:

![elementor-padding-ui-issue](https://user-images.githubusercontent.com/15205088/201250525-de26ce7d-8426-46da-9572-d340aac0276b.png)

**Comment by qantumthemes** [comment] 2022-11-13 12:54
I can confirm. Previous version was working fine.
Since version 3.8.0 in general the padding of a column is not working anymore.
Padding of sections and padding of internal sections and columns is working.
Only the padding of a normal column is completely ignored.


**IMPORTANT:
this only happens if you disable the flexbox container**

https://capture.dropbox.com/5CKvvXp9NVh8YTWD



In the CSS there is no output for the padding.

Any value is ignored.

No other plugins enabled.

Steps to reproduce:
1. With Elementor 3.7 make a column with some padding
2. Upgrade to 3.8
3. Edit the page with Elementor: any new value will be ignored and there will be no padding out put anymore
https://capture.dropbox.com/qGy3Am7216s1GlbM

making a new page will not solve the issue.

**Comment by nicholaszein** [comment] 2022-11-14 08:33
Hello @JakeQZ! 

Thank you for submitting your issue! 🙏

If you click on the 🔗 "link values together" icon on the right, you can then remove the value added. See the video below:

https://user-images.githubusercontent.com/113993460/201611777-d6877915-6d9f-4d52-b5be-4c70de7c2ef8.mp4

For this reason, I'm closing this issue since this is not a bug, it's just how the interface works now. You can only remove values if you link the fields, otherwise, they will always show at least a zero.

Best regards

**Closed by nicholaszein** 2022-11-14 08:33 UTC

**Comment by nicholaszein** [comment] 2022-11-14 08:35
Hey @qantumthemes, 

would you be so kind to open a [new 🐞 Bug Report issue](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml), so we can help you better? 

We need to try to reproduce your issue and know about your system info. It seems what you're reporting is not the same thing as reported by @JakeQZ. 

Thank you very much! 🙏

**Comment by qantumthemes** [comment] 2022-11-14 08:35
Sure thanks

**Comment by qantumthemes** [comment] 2022-11-14 08:42
I saw an update 3.8.1 when trying to record the issue.
The new version appears to solve the problem.
Thanks for the quick fix!

**Comment by JakeQZ** [comment] 2022-11-14 13:02
> For this reason, I'm closing this issue since this is not a bug, it's just how the interface works now. You can only remove values if you link the fields, otherwise, they will always show at least a zero.

I'd say this is a bug.  As things stand, it is not possible to specify some but not all padding or margin values, whilst having the others inherit the default from the theme.

**Comment by nicholaszein** [comment] 2022-11-30 10:33
Hello @JakeQZ,

this is not a bug, but I understand what you are saying. We are working on some new features that will help you accomplish what you are describing. Stay tuned! 😉
