### ISSUE TITLE
Version 3.4.1 woocommerce Product Widget

### ISSUE THREAD

**Issue by nickdgreen** [elementor/elementor#16067] opened 2021-08-19 13:23 UTC
Updating to version 3.4.1 the Product Widget grid formatting broke. A row of three items was no longer spaced at approx 33% but were three very thin items. Rolling back to the previous version did not rectify the problem. I re-added the Product Widget and the formatting on the backend appeared to have been rectified but it was still broken on the front end. I have temporarily patched the front end by adding the following CSS:
`.elementor-products-grid ul.products li.product {
    width: auto !important;
    padding: 0 !important;
    margin: 0 !important;
    float: none !important;
}`
The items are not formatted completely correctly but they are readable.
![what the items should look like and how they are on the back end](https://user-images.githubusercontent.com/22448787/130076088-671f2c8a-3828-417d-b7d3-01b3ba5ea655.png)
![what the items look like on the front end](https://user-images.githubusercontent.com/22448787/130076107-3d7ce8a0-cb65-4cfa-81da-061bedf0153c.png)
[system-info-floatsation.com-19-08-2021.txt](https://github.com/elementor/elementor/files/7014647/system-info-floatsation.com-19-08-2021.txt)

**Comment by DCMadmin** [comment] 2021-08-19 14:53
same issue here. its the pro plugin  3.3.5 ok, fault apparant in Version 3.3.6 & Version 3.3.7 Elementor Pro

**Comment by Mateussgp07** [comment] 2021-08-20 22:57
Também estou com esse problema e tá me prejudicando demais nas minhas vendas!

**Comment by Mateussgp07** [comment] 2021-08-20 23:02
O CSS que esse para passou me ajudou!

**Comment by shilo-ey** [comment] 2021-08-22 05:52
Duplicate of #16001

**Comment by shilo-ey** [comment] 2021-08-22 05:52
I merged this issue with #16001, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!

**Closed by shilo-ey** 2021-08-22 05:52 UTC
