### ISSUE TITLE
🔗 🚀 Feature Request: Allow alternate & custom button styles in site settings (Duplicate of #19098)

### ISSUE THREAD

**Issue by joshnajera** [elementor/elementor#19980] opened 2022-10-03 22:30 UTC
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

Allows the user to defined button styles to swap between depending on the color scheme of the section.  

Example:
A user could create:
- a base style
- alternate style
- inverted style
- etc.

Then in Elementor the user could select the style that best suits the section's colors. This would allow for better control and easier management of a sites color scheme in a more modular fashion.

### Describe the solution you'd like

Similar to font "Global Fonts" section where you can add custom style, allow buttons various button styles to be saved.

### Describe alternatives you've considered

I can do this by setting all button style manually everywhere it varies from the default theme.

### Additional context

It would reduce the repetative nature of manually updating different button styles depending on the context of their section's color scheme.

**Comment by nicholaszein** [comment] 2022-11-14 03:04
Hello @joshnajera 

Thank you for your submission! 🙏 

### 🔗 This issue is a Duplicate of #19098

Which is on the same subject. 

For this reason, I'm closing this issue and 🔃 **Merging** it with the original, so we can have all the discussions in one location, and deal with it more efficiently.

Feel free to continue the conversation there. 😉 

### ✔️ Please, in the future, remember to check if there isn't an issue similar to yours already opened. 

Best regards,

Nick

**Closed by nicholaszein** 2022-11-14 03:04 UTC
Labels: request/enhancement, type/global-style, component/button
