### ISSUE TITLE
⛔ 🔗 "Equal Height" Option Not Working on Loop Carousel and Loop Grid Widgets (Duplicate of #21164)

### ISSUE THREAD

**Issue by modegraffiti99** [elementor/elementor#29240] opened 2024-11-10 19:18 UTC
### Prerequisites

- [ ] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [ ] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

Description: I'm experiencing an issue where the "Equal Height" option does not function correctly in the Loop Carousel and Loop Grid widgets on my site. Despite enabling "Equal Height," the elements within the loop do not align to the same height as expected. I’ve tried several solutions found online, including custom CSS adjustments, but none have resolved the issue.

Site link: [www.ducicontemporanea.it/shop](url)

Any guidance or suggestions on how to address this would be greatly appreciated!

### Steps to reproduce

1. Enable "Equal Height" on Loop Carousel/Loop Grid widgets.
2. Observe that the elements do not align to the same height.
3. Additional Information:

### Expected behavior

When the "Equal Height" option is enabled in the Loop Carousel or Loop Grid widgets, all items within the loop should adjust to have the same height. This would create a uniform, aligned appearance for the widget's content, regardless of differences in content length or image dimensions.

Currently, despite enabling this option, items are not aligning to a consistent height, which disrupts the layout's visual balance.

### Isolating the problem

- [ ] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [ ] This bug happens with the Hello Elementor theme active.
- [X] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

<details>
<summary>Click to reveal</summary>

````txt


== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MariaDB Server v10.6.16
	PHP Version: 8.0.30
	PHP Memory Limit: 1G
	PHP Max Input Vars: 8000
	PHP Max Post Size: 128M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.6.2
	Site URL: https://www.ducicontemporanea.it
	Home URL: https://www.ducicontemporanea.it
	WP Multisite: No
	Max Upload Size: 128 MB
	Memory limit: 40M
	Max Memory limit: 1G
	Permalink Structure: /%postname%/
	Language: it_IT
	Timezone: Europe/Rome
	Debug Mode: Inactive

== Theme ==
	Name: SKT White Pro
	Version: pro5.0
	Author: SKT Themes
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: it-IT
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36

== Active Plugins ==
	Code Snippets
		Version: 3.6.5.1
		Author: Code Snippets Pro

	Complianz | GDPR/CCPA Cookie Consent
		Version: 7.1.4
		Author: Really Simple Plugins

	Contact Form 7
		Version: 6.0
		Author: Takayuki Miyoshi

	Contact Form 7 Widget For Elementor Page Builder & Gutenberg Blocks
		Version: 1.2.1
		Author: HT Plugins

	Elementor
		Version: 3.25.4
		Author: Elementor.com

	Elementor Pro
		Version: 3.15.0
		Author: Elementor.com

	Extensions For CF7
		Version: 3.1.7
		Author: HasThemes

	GTranslate
		Version: 3.0.7
		Author: Translate AI Multilingual Solutions

	Plugins Garbage Collector (Database Cleanup) Old!
		Version: 0.14
		Author: Vladimir Garagulya

	Post Type Switcher
		Version: 3.3.1
		Author: Triple J Software, Inc.

	ShopEngine
		Version: 4.7.2
		Author: Wpmet

	SKT Templates
		Version: 6.19
		Author: SKT Themes

	SumUp Payment Gateway For WooCommerce
		Version: 2.6.5
		Author: SumUp

	W3 Total Cache
		Version: 2.7.7
		Author: BoldGrid

	WooCommerce
		Version: 9.3.3
		Author: Automattic

	WooPayments
		Version: 8.4.0
		Author: WooCommerce

	WordPress Importer
		Version: 0.8.3
		Author: wordpressdotorg

	WPvivid Backup Plugin
		Version: 0.9.107
		Author: WPvivid Team

	YITH WooCommerce Product Gallery & Image Zoom
		Version: 2.37.0
		Author: YITH

	Yoast Duplicate Post
		Version: 4.5
		Author: Enrico Battocchi & Team Yoast

	Yoast SEO
		Version: 23.8
		Author: Team Yoast


== Must-Use Plugins ==
	Elementor Safe Mode
		Version: 1.0.0
		Author: Elementor.com


== Features ==
	Custom Fonts: 0
	Custom Icons: 1

== Integrations ==
	
	woocommerce: Active


== Esperimenti Elementor ==
	Caricamento CSS migliorato: Inattivo per impostazione predefinita
	Icone dei font in linea: Inattivo per impostazione predefinita
	Punti di interruzione aggiuntivi: Attivo per impostazione predefinita
	Contenitore: Attiva
	Aggiorna la libreria Swiper: Attivo per impostazione predefinita
	Nested Elements Performance: Attivo per impostazione predefinita
	Optimized Control Loading: Attivo per impostazione predefinita
	Markup ottimizzato: Inattivo per impostazione predefinita
	Conditionally load Swiper CSS files: Inattivo per impostazione predefinita
	Plugin Onboarding: Attivo per impostazione predefinita
	CSS Smooth Scroll: Attivo per impostazione predefinita
	Default to New Theme Builder: Attivo per impostazione predefinita
	Schermata home di Elementor: Attivo per impostazione predefinita
	Landing Page: Attivo per impostazione predefinita
	Elementi annidati: Attiva
	Barra unificata degli strumenti dell'editor: Attivo per impostazione predefinita
	Pannello pagine: Inattivo per impostazione predefinita
	Cache degli elementi: Inattivo per impostazione predefinita
	Link In Bio: Attivo per impostazione predefinita
	Floating Buttons: Attivo per impostazione predefinita
	Elementor Editor Events: Inattivo per impostazione predefinita
	Atomic Widgets: Inattivo per impostazione predefinita
	Launchpad Checklist: Inattivo per impostazione predefinita
	Page Transitions: Attivo per impostazione predefinita
	Notes: Attivo per impostazione predefinita
	Loop: Attivo per impostazione predefinita
	Form Submissions: Attivo per impostazione predefinita
	Scroll Snap: Attivo per impostazione predefinita
	Menu: Attiva
	Taxonomy Filter: Inattivo per impostazione predefinita


== Registro ==
	
JS: showing 14 of 14JS: 2024-09-15 12:33:29 [error X 1][../wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.24.2:3:778299] Cannot read properties of null (reading '$element') 
JS: 2024-09-15 15:09:01 [error X 1][../wp-content/plugins/elementor/assets/js/editor-modules.min.js?ver=3.24.2:3:14298] An invalid argument supplied as multiple control value [array (
  'category' => 'InvalidElementData',
  'tag' => 'Element `wpr-grid` got as `content_width` value. Expected array or object.',
)]
JS: 2024-09-15 19:48:43 [error X 13][../wp-includes/js/jquery/jquery.min.js?ver=3.7.1:2:28760] Cannot read properties of undefined (reading 'value') 
JS: 2024-09-15 20:01:58 [error X 17][../wp-includes/js/dist/vendor/react-dom.min.js?ver=18.3.1:2:37261] Cannot read properties of null (reading 'getOptions') 
JS: 2024-09-16 15:35:03 [error X 11][../wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.24.2:3:816444] Cannot read properties of undefined (reading 'get') 
JS: 2024-11-05 14:19:02 [error X 60][../wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.24.7:3:837409] Cannot read properties of undefined (reading 'localized') 
JS: 2024-11-06 17:56:50 [error X 3][../wp-content/plugins/elementor-pro/assets/js/editor.min.js?ver=3.15.0:2:64105] Cannot convert undefined or null to object 
JS: 2024-11-07 11:52:43 [error X 4][../wp-content/plugins/elementor/assets/js/common.min.js?ver=3.25.4:3:97101] Cannot read properties of undefined (reading 'toLowerCase') 
JS: 2024-11-07 16:45:39 [error X 5][../wp-content/plugins/elementor/assets/js/d91e4d7f57d57af2aab9.bundle.min.js:2:7789] Cannot read properties of null (reading 'dataset') 
JS: 2024-11-07 18:10:27 [error X 1][../wp-content/plugins/elementor-pro/assets/js/editor.min.js?ver=3.15.0:2:116911] Cannot read properties of null (reading 'config') 
JS: 2024-11-07 19:13:17 [error X 1][../wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.25.4:3:1274664] Cannot read properties of null (reading 'getBoundingClientRect') 
JS: 2024-11-07 19:19:38 [error X 11][../wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.25.4:3:330206] Cannot read properties of undefined (reading 'id') 
JS: 2024-11-09 17:03:04 [error X 18][../wp-content/plugins/elementor/assets/js/frontend-modules.min.js?ver=3.25.4:2:12921] Cannot read properties of undefined (reading 'attributes') 
JS: 2024-11-10 11:40:51 [error X 2][../wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.25.4:3:715501] this.model.isValidChild is not a function 

Log: showing 20 of 212024-09-20 08:23:32 [info] elementor::elementor_updater Started 
2024-09-20 08:23:32 [info] Elementor/Upgrades - _on_each_version Start  
2024-09-20 08:23:32 [info] Elementor/Upgrades - _on_each_version Finished 
2024-09-20 08:23:33 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.24.2',
  'to' => '3.24.3',
)]
2024-09-20 08:23:35 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.24.2',
  'to' => '3.24.3',
)]
2024-10-07 16:27:28 [info] elementor::elementor_updater Started 
2024-10-07 16:27:28 [info] Elementor/Upgrades - _on_each_version Start  
2024-10-07 16:27:28 [info] Elementor/Upgrades - _on_each_version Finished 
2024-10-07 16:27:28 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.24.3',
  'to' => '3.24.5',
)]
2024-10-25 12:06:54 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.24.5',
  'to' => '3.24.7',
)]
2024-10-25 12:06:55 [info] elementor::elementor_updater Started 
2024-10-25 12:06:55 [info] Elementor/Upgrades - _on_each_version Start  
2024-10-25 12:06:55 [info] Elementor/Upgrades - _on_each_version Finished 
2024-10-25 12:06:55 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.24.5',
  'to' => '3.24.7',
)]
2024-11-07 12:12:06 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.24.7',
  'to' => '3.25.4',
)]
2024-11-07 12:12:09 [info] elementor::elementor_updater Started 
2024-11-07 12:12:09 [info] Elementor/Upgrades - _on_each_version Start  
2024-11-07 12:12:10 [info] Elementor/Upgrades - _on_each_version Finished 
2024-11-07 12:12:10 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.24.7',
  'to' => '3.25.4',
)]
2024-11-07 12:12:13 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.24.7',
  'to' => '3.25.4',
)]

PHP: showing 7 of 7PHP: 2024-10-08 15:06:14 [warning X 13][../wp-content/plugins/elementor/modules/history/revisions-manager.php::363] Undefined array key "editor_post_id" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-11-06 12:21:05 [error X 5][../wp-content/plugins/elementor/core/frontend/render-mode-manager.php::136] Uncaught WpOrg\Requests\Exception\Http\Status403: 403 Forbidden in ../wp-content/plugins/elementor/core/frontend/render-mode-manager.php:136
Stack trace:
#0 ../wp-content/plugins/elementor/core/frontend/render-mode-manager.php(157): Elementor\Core\Frontend\Render_Mode_Manager->add_current_actions()
#1 ../wp-content/plugins/elementor/includes/frontend.php(212): Elementor\Core\Frontend\Render_Mode_Manager->__construct()
#2 ../wp-includes/class-wp-hook.php(324): Elementor\Frontend->init_render_mode()
#3 ../wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters()
#4 ../wp-includes/plugin.php(517): WP_Hook->do_action()
#5 ../wp-includes/template-loader.php(13): do_action()
#6 ../wp-blog-header.php(19): require_once('/home/bqhjztwa/...')
#7 ../index.php(17): require('/home/bqhjztwa/...')
#8 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-11-06 20:52:08 [warning X 36][../wp-content/plugins/elementor-pro/modules/theme-builder/widgets/site-logo.php::192] Undefined array key "options" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-11-07 10:01:37 [warning X 2][../wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php::150] Undefined array key "condition_type" [array (
  'trace' => '
#0: ../wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(150): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: ../wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(84): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_template_json_item()
#2: ../wp-content/plugins/elementor/data/base/endpoint.php(166): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> update_item()
#3: ../wp-content/plugins/elementor/data/base/endpoint.php(307): Elementor\Data\Base\Endpoint -> base_callback()
#4: ../wp-includes/rest-api/class-wp-rest-server.php(1230): Elementor\Data\Base\Endpoint -> Elementor\Data\Base\{closure}()
',
)]
PHP: 2024-11-07 10:09:46 [warning X 77][../wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php::150] Undefined array key "condition_type" [array (
  'trace' => '
#0: ../wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(150): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_template_json_item()
#2: ../wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(120): class type array_map()
#3: ../wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(59): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_templates_json()
#4: ../wp-content/plugins/elementor/data/base/endpoint.php(158): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> get_items()
',
)]
PHP: 2024-11-09 11:25:15 [warning X 9][../wp-content/plugins/elementor/includes/managers/image.php::113] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-11-09 16:47:50 [error X 2][../wp-content/plugins/elementor-pro/modules/woocommerce/module.php::1519] Uncaught TypeError: Unsupported operand types: string / int in ../wp-content/plugins/elementor-pro/modules/woocommerce/module.php:1519
Stack trace:
#0 ../wp-content/plugins/elementor-pro/modules/woocommerce/module.php(1481): ElementorPro\Modules\Woocommerce\Module->adjust_setting_for_product_renderer()
#1 ../wp-content/plugins/elementor-pro/modules/woocommerce/module.php(1471): ElementorPro\Modules\Woocommerce\Module->parse_loop_query_args()
#2 ../wp-content/plugins/elementor-pro/modules/woocommerce/module.php(1422): ElementorPro\Modules\Woocommerce\Module->loop_query()
#3 ../wp-includes/class-wp-hook.php(324): ElementorPro\Modules\Woocommerce\Module->ElementorPro\Modules\Woocommerce\{closure}()
#4 ../wp-includes/plugin.php(205): WP_Hook->apply_filters()
#5 ../wp-content/plugins/elementor-pro/modules/query-control/classes/elementor-post-query.php(147): apply_filters()
#6 ../wp-content/plugins/elementor-pro/modules/query-control/classes/elementor-post-query.php(49): ElementorPro\Modules\QueryControl\Classes\Elementor_Post_Query->get_query_args()
#7 ../wp-content/plugins/elementor-pro/modules/query-control/module.php(959): ElementorPro\Modules\QueryControl\Classes\Elementor_Post_Query->get_query()
#8 ../wp-content/plugins/elementor-pro/modules/posts/widgets/posts.php(72): ElementorPro\Modules\QueryControl\Module->get_query()
#9 ../wp-content/plugins/elementor-pro/modules/loop-builder/widgets/base.php(57): ElementorPro\Modules\Posts\Widgets\Posts->query_posts()
#10 ../wp-content/plugins/elementor-pro/modules/posts/skins/skin-base.php(856): ElementorPro\Modules\LoopBuilder\Widgets\Base->query_posts()
#11 ../wp-content/plugins/elementor-pro/modules/loop-builder/skins/skin-loop-base.php(89): ElementorPro\Modules\Posts\Skins\Skin_Base->render()
#12 ../wp-content/plugins/elementor-pro/modules/woocommerce/skins/skin-loop-product.php(36): ElementorPro\Modules\LoopBuilder\Skins\Skin_Loop_Base->render()
#13 ../wp-content/plugins/elementor/includes/base/skin-base.php(79): ElementorPro\Modules\WooCommerce\Skins\Skin_Loop_Product->render()
#14 ../wp-content/plugins/elementor/includes/base/widget-base.php(633): Elementor\Skin_Base->render_by_mode()
#15 ../wp-content/plugins/elementor/core/base/document.php(387): Elementor\Widget_Base->render_content()
#16 ../wp-content/plugins/elementor/includes/managers/widgets.php(461): Elementor\Core\Base\Document->render_element()
#17 [internal function]: Elementor\Widgets_Manager->ajax_render_widget()
#18 ../wp-content/plugins/elementor/core/common/modules/ajax/module.php(176): call_user_func()
#19 ../wp-includes/class-wp-hook.php(324): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request()
#20 ../wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters()
#21 ../wp-includes/plugin.php(517): WP_Hook->do_action()
#22 ../wp-admin/admin-ajax.php(192): do_action()
#23 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]



== Elementor - Compatibility Tag ==
	
	Contact Form 7 Widget For Elementor Page Builder & Gutenberg Blocks: Compatibilità non specificata
	Elementor Pro: Compatibilità non specificata

== Elementor Pro - Compatibility Tag ==

````

</details>

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by nicholaszein** [comment] 2024-11-18 20:37
Hello @modegraffiti99!

Thank you for reaching out! 🙏 

When I visit your site, all items on both the Loop Grid and Loop Carousel widgets are on the same height. I don't see any item with different heights. Moreover, when I inspect the code, I can see the **`Equal Height`** being correctly applied in all instances of these widgets. This means that if you are not seeing this, you need to purge your browser cache.

This is also a duplicate of #21164, which is on the same subject and was already covered multiple times in here. Usually, the problem is on how you build the Loop Item layout. If you nest multiple containers, for example, then the effect will not apply as you expect, although it will even then be applied.

### 🔍 Please, in the future, remember to check if there isn't any thread similar to yours already opened. 

Make sure to [always troubleshoot](https://elemn.to/help-troubleshooting) your issues before opening a bug report. 

Kind regards

**Closed by nicholaszein** 2024-11-18 20:37 UTC
Labels: product/pro, type/layout, widget/loop-builder, mod*, compatibility/cache, theme-builder/loop-item-template, duplicate, mod/x*, mod/i*
