### ISSUE TITLE
Share Buttons Not Opening Share Dialog Box After Latest Updates

### ISSUE THREAD

**Issue by Worldwebscapes** [elementor/elementor#9920] opened 2019-12-18 15:24 UTC
## Prerequisites

- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ x] The issue still exists against the latest stable version of Elementor.

## Description

I have updated to EPro 2.8 and E Free 2.8.2.
Share Buttons do not open the share dialog box. There is an "a" class and linked but no box. I am running no-cache or other minify plugins. 

## Steps to reproduce
I tried this on multiple pages on the test site. Other sites that have not been updated function properly.

Place a Share Buttons widget on to a page and attempt to share it with social media link.

## Isolating the problem

- [X ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ X] This bug happens with a default WordPress theme active.
- [ X] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MariaDB Server v10.3.21
	PHP Version: 7.3.12
	PHP Max Input Vars: 1000
	PHP Max Post Size: 2000M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.3.1

	WP Multisite: No
	Max Upload Size: 2 GB
	Memory limit: 512M
	Permalink Structure: /%postname%/
	Language: en
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.2.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 2.8.2
		Author: Elementor.com

	Elementor Pro
		Version: 2.8.0
		Author: Elementor.com


== Must-Use Plugins ==
	installatron_hide_status_test.php
		Version: 
		Author: 



</details>

**Comment by regentmg** [comment] 2019-12-18 17:13
Same here!

		
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Percona Server (GPL), Release 84.0, Revision 47234b3 v5.6.40-84.0
	PHP Version: 7.1.33
	PHP Max Input Vars: 3000
	PHP Max Post Size: 128M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.3.1
	Site URL: http://thecatholicdads.com
	Home URL: http://thecatholicdads.com
	WP Multisite: No
	Max Upload Size: 128 MB
	Memory limit: 768M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: America/New_York
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor Child
	Version: 1.0.1
	Author: Elementor Team
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.2.1
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_2) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.4 Safari/605.1.15

== Active Plugins ==
	Disqus for WordPress
		Version: 3.0.17
		Author: Disqus

	Elementor
		Version: 2.8.2
		Author: Elementor.com

	Elementor Pro
		Version: 2.8.0
		Author: Elementor.com

	SG Optimizer
		Version: 5.3.10
		Author: SiteGround


== Elements Usage ==
	
	archive : 2
		archive-posts : 1
		heading : 2
		posts : 1
	footer : 1
		form : 2
		heading : 3
		text-editor : 2
	header : 1
		icon-list : 2
		nav-menu : 1
		search-form : 1
		theme-site-logo : 3
	popup : 2
		icon-list : 1
	single : 2
		author-box : 1
		heading : 2
		post-comments : 1
		post-info : 1
		posts : 1
		share-buttons : 1
		theme-page-title : 1
		theme-post-content : 1
		theme-post-title : 1
	wp-page : 3
		blockquote : 1
		heading : -2
		spacer : 3
		tabs : 1
		text-editor : 3


== Log ==
	
JS: showing 5 of 5JS: 2019-12-01 15:25:52 [error X 1][http://thecatholicdads.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.7.5:7:33305] Invalid argument. 
JS: 2019-12-06 15:53:45 [error X 6][http://thecatholicdads.com/wp-content/plugins/elementor-pro/assets/js/frontend.min.js?ver=2.7.3:2:24481] Cannot read property \'size\' of undefined 
JS: 2019-12-07 02:55:06 [error X 1][http://thecatholicdads.com/wp-content/plugins/elementor-pro/assets/js/frontend.min.js?ver=2.7.3:2:24480] undefined is not an object (evaluating \'t.entrance_animation_duration.size\') 
JS: 2019-12-10 14:37:03 [error X 15][http://thecatholicdads.com/wp-content/plugins/elementor/assets/js/editor-modules.min.js?ver=2.8.0:2:48076] n.attributes[e.name].each is not a function 
JS: 2019-12-10 14:37:14 [error X 6][http://thecatholicdads.com/wp-content/plugins/elementor/assets/js/editor-modules.min.js?ver=2.8.0:2:34953] id invalid type: string. 

PHP: showing 4 of 4PHP: 2019-12-04 15:33:20 [notice X 2][/home/regentme/public_html/thecatholicdads.com/wp-content/plugins/elementor-pro/modules/posts/widgets/posts.php::31] Undefined index: posts_post_type [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2019-12-06 12:16:12 [notice X 9][/home/regentme/public_html/thecatholicdads.com/wp-content/plugins/elementor-pro/modules/query-control/module.php::360] Undefined index: q [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2019-12-12 16:00:19 [notice X 163][/home/regentme/public_html/thecatholicdads.com/wp-content/plugins/elementor/core/dynamic-tags/tag.php::45] Undefined index: after [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2019-12-13 08:41:30 [notice X 2][/home/regentme/public_html/thecatholicdads.com/wp-content/plugins/elementor-pro/modules/posts/skins/skin-content-base.php::204] Trying to get property of non-object [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

Log: showing 5 of 52019-12-08 14:21:27 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.7.5',
  'to' => '2.7.6',
)]
2019-12-10 09:16:32 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.7.6',
  'to' => '2.8.0',
)]
2019-12-12 15:59:30 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.8.0',
  'to' => '2.8.1',
)]
2019-12-17 10:16:02 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.8.1',
  'to' => '2.8.2',
)]
2019-12-18 11:53:33 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.7.3',
  'to' => '2.8.0',
)]

**Comment by shilo-ey** [comment] 2019-12-18 18:08
This issue has been resolved in Elementor Pro v2.8.1

Feel free to update

Thanks!

**Closed by shilo-ey** 2019-12-18 18:08 UTC
Labels: bug, status/merged

**Comment by pepitos79** [comment] 2020-03-03 10:24
Hi,
When i put share button in a Elementor model that i use for news in my blog, share button doesn't work
Can you explain to me why ?

Thx

**Comment by catherinewiltshire** [comment] 2020-03-11 14:35
> Hi,
> When i put share button in a Elementor model that i use for news in my blog, share button doesn't work
> Can you explain to me why ?
> 
> Thx

I'm having the same problem, share buttons work on regular pages but not where I have them on single post templates - which is the only place I have them active on my site!

I have also tried adding the share widget directly into the post on editing with elementor and this doesn't work either.

I have updated to the latest version of elementor free and pro.

**Comment by saranghills** [comment] 2020-03-27 06:18
I am having the same issue. Elementor and Pro latest version. TwentyTwenty theme latest version. Share button not working on single template.

**Comment by gabscoll** [comment] 2020-04-01 11:15
I'm having this problem right now, on a single post template. I have latest version of Elementor Pro and I'm using Theme Builder with Elementor's Hello theme.

**Comment by pcodina** [comment] 2020-05-07 10:38
Hi,
Me too, the same problem. Share buttons not working on templates.

**Comment by ste70** [comment] 2020-05-21 07:08
Same Problem

**Comment by Bartosz1985** [comment] 2020-05-22 19:37
Any idea how to fix this ?

**Comment by JOTAI** [comment] 2020-05-27 03:24
I have the same problem, Elementor Pro 2.9.5 and the share button doesn't work, only works to facebook.

**Comment by n4l5u0r** [comment] 2020-07-09 10:00
Guys any resolution on the issue some day?

**Comment by wpdkg** [comment] 2020-08-18 13:35
Wondering if anyone was aware of a fix for this yet?

elementor share buttons not working on single product templates

**Comment by n4l5u0r** [comment] 2020-08-18 13:54
> Guys any resolution on the issue some day?

Ok solved the issue on my side. Looks like the Elementor does not manage the "%" symbol present in the excerpt and crash. Just removed the symbol and it works perfectly now.
Still remains a workaround

**Comment by shaulhadarn** [comment] 2020-08-24 14:23
Hi, I can't use the share buttons at all on the post template, but i can't find where to remove the "%" sign, how did you do this?

**Comment by Ineedhelpguys** [comment] 2020-08-27 18:14
> > Guys any resolution on the issue some day?
> 
> Ok solved the issue on my side. Looks like the Elementor does not manage the "%" symbol present in the excerpt and crash. Just removed the symbol and it works perfectly now.
> Still remains a workaround

Same question. How do you remove the %? I'm having the same issue.

**Comment by Ineedhelpguys** [comment] 2020-08-31 21:31
I know this issue was initially posted before WordPress 5.5, but I rolled back to the previous version, 5.4.2, and it's working again.

Maybe that will help someone who comes across this.

**Comment by uttam-laila** [comment] 2020-09-14 09:28
I'm using wordpress version 5.5.1, Elementor - 3.0.7, Elementor Pro - 3.0.4. Still I have the same problem, only facebook share is working and all other share buttons just open a blank popup.

**Comment by orlandotrejo** [comment] 2020-09-17 05:55
Same issue here: WP 5.5.1, Elementor 3.0.8, Elementor Pro 3.0.4 . Maybe a rollback to a previous Elementor version?

**Comment by yewzy** [comment] 2020-09-27 11:38
I'm having the same issue, with only Facebook share working. Whatsapp share opens a blank window. Wechat & Weibo have no reactions whatsoever. 

From the chrome console:

_When Weibo & Wechat Icon is clicked:_
> Uncaught TypeError: Cannot read property 'replace' of undefined
>     at Function.ShareLink.getNetworkLink (share-link.min.js?ver=3.0.10:1)
>     at h (share-link.min.js?ver=3.0.10:1)
>     at HTMLDivElement.<anonymous> (share-link.min.js?ver=3.0.10:1)
>     at HTMLDivElement.dispatch (jquery.js:3)
>     at HTMLDivElement.r.handle (jquery.js:3)

_When Whatsapp Icon is clicked:_
> share-link.min.js?ver=3.0.10:1 [Deprecation] Resource requests whose URLs contained both removed whitespace (`\n`, `\r`, `\t`) characters and less-than characters (`<`) are blocked. Please remove newlines and encode less-than characters from places like element attribute values in order to load these resources. See https://www.chromestatus.com/feature/5735596811091968 for more details.

**Comment by orlandotrejo** [comment] 2020-09-30 15:15
I finally got to correct the issue, and I discovered it was caused by some theme modifications I did without following the WordPress conventions and good practices.

What you can try to do is to install your theme again and start from scratch. All Elementor widgets and features were working.

What I did at the end was to use the Elementor Hello Theme which comes significantly less bloated, and build your entire site with Elementor.

I my case this had the additional advantage that I can fine tune the theme for mobile and tablet, something I was doing manually with my old limited theme.

**Comment by artneo7** [comment] 2020-12-14 20:13
Thanks @orlandotrejo! I changed parent theme from twentyseventeen to hello-theme and it fixed this issue.

**Comment by Andy-Fontana** [comment] 2021-01-15 14:56
@orlandotrejo In my case I was already using Elementor Hello Theme and I still have the problem. If anyone finds a solution I would really appreciate it. :)

**Comment by pepitos79** [comment] 2021-01-15 15:16
> I finally got to correct the issue, and I discovered it was caused by some theme modifications I did without following the WordPress conventions and good practices.
> 
> What you can try to do is to install your theme again and start from scratch. All Elementor widgets and features were working.
> 
> What I did at the end was to use the Elementor Hello Theme which comes significantly less bloated, and build your entire site with Elementor.
> 
> I my case this had the additional advantage that I can fine tune the theme for mobile and tablet, something I was doing manually with my old limited theme.

Thx Dude
I changed the theme for Hell and that solved my problem

**Comment by aliboy08** [comment] 2023-02-23 02:47
Issue: share buttons other than facebook are not working
https://prnt.sc/Ca5i6UO7CmaZ

seems like this is because of the html tags on the excerpt / description

If you check the codes at /plugins/elementor-pro/assets/js/share-buttons
https://prnt.sc/5GJLr7N8-WaL
You'll see it gets the data from elementorFrontend.config.post

the excerpt includes html markup
https://prnt.sc/amPO3srmSgW3

you can run a script to remove the html tags from the excerpt, then reassign it
e.g: 
// remove html tags
var cleanedExcerpt = elementorFrontend.config.post.excerpt.replace(/<\/?[^>]+(>|$)/g, ""); 

// re-assign the cleaned excerpt
elementorFrontend.config.post.excerpt = cleanedExcerpt;

https://prnt.sc/YgKKfNhWv8lm

Another possible fix for this might be to clean the excerpt on php before it is assigned to elementorFrontend.config.post.excerpt (have not found where this is set yet, or if there are filters available for this)
