### ISSUE TITLE
Elementor ( Button ) element is showing big in editor ( 3.0 & 3.0.1 )

### ISSUE THREAD

**Issue by torpix** [elementor/elementor#12235] opened 2020-08-25 20:55 UTC
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

## Description

In the backend elementor page editor, the button element is a bit bigger, but on the front end it is the correct size.

It was working fine before the 3.0 update.

I've (de)activated plugins 1 by 1 and the issue still there.

## Isolating the problem
- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [ ] I can reproduce this bug consistently using the steps above.

## Environment

WP: 5.5
PHP: 7.4.8
MariaDB: 10.3.23
Theme: Astra (2.5.4)

Elementor: 3.0.1
Elementor Pro: 3.0.0

**Comment by BAtiyat** [comment] 2020-08-26 12:34
Same issue
Following...

**Comment by torpix** [comment] 2020-08-27 17:52
Still an issue in Elementor 3.0.3.

**Comment by BAtiyat** [comment] 2020-08-27 17:55
There are lots of issues mentioned in #12224

**Comment by shilo-ey** [comment] 2020-08-28 08:57
We should release a patch for this issue soon, it is caused by inconsistent parameters printing on the Editor, and we resolved this issue in the following PRs: #12293 , #12290 

Thanks

**Comment by shilo-ey** [comment] 2020-08-30 15:49
This issue has been resolved in Elementor v3.0.4

Feel free to update

Thanks!

**Closed by shilo-ey** 2020-08-30 15:49 UTC
Labels: bug, status/merged
