### ISSUE TITLE
Replace hamburger menu with "Menu" text

### ISSUE THREAD

**Issue by besweeet** [elementor/elementor#11270] opened 2020-05-01 15:39 UTC
## Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
The three-lined hamburger menu isn't obvious to everyone as to what it does, so an alternative where it's simply "Menu" in text (or something that's customizable) would be ideal.

**Comment by arielk** [comment] 2020-05-03 07:31
Duplicate of #9205

**Closed by arielk** 2020-05-03 07:31 UTC
