### ISSUE TITLE
Image Carousel widget freezes with ‘author’ level user

### ISSUE THREAD

**Issue by eefee-github** [elementor/elementor#14675] opened 2021-04-24 06:51 UTC
## Prerequisites

- [ X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ X] The issue still exists against the latest stable version of Elementor (v.3.2.1)

## Description

Using Elementor, when an ‘author’ level user creates or edits an ‘image carousel’ widget, the carousel displays as frozen on the page. The images do not auto-play, and one cannot select either the dots or arrows to navigate to other images.

This does not happen when using either ‘editor’ or ‘administrator’ level users (the carousel displays and behaves as expected).

The only way to fix this issue is to edit (with Elementor) the page, and delete and re-create the carousel, re-selecting all the images and setting the display order. Editing a frozen carousel with a higher-level user, e.g. adding or deleting images (as applicable), has no effect on the frozen behaviour.

A workaround is to change the ‘author’ users to ‘editor’ level until the bug is fixed, but would prefer a clean solution.  

## Steps to reproduce

When logged in as an 'author' level user, create or edit an 'image carousel' - select images, change the display order, remove images - and publish the page.  

The carousel appears frozen - i.e. the images do not auto-play, and selecting the navigation arrows or dots to display other images has no affect.  

When logged in as an 'editor' or 'administrator' user, trying to edit a frozen image carousel has no affect on the carousel - it remains frozen.  The (non-author) user has to re-create the carousel from scratch.  

Creating a (new) or editing a (non-frozen) image carousel as an editor or administrator user works as expected - the published carousel auto-plays, and one can select other images in the carousel using the navigation arrows or dots.       

## Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro). [note: cannot deactivate the SSL plug-ins, as I don't want to have to manage/troubleshoot not having SSL active on a site that forces https]  
- [ ] This bug happens with a default WordPress theme active.
- [X] I can reproduce this bug consistently using the steps above.

Isolating: the carousel behaviour is completely as expected (documented) for user levels 'editor' and 'administrator' - the freezing described above only happens for 'author' role (I have not tried 'contributor', but this is not relevant for our website).

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MariaDB Server v5.7.33
	PHP Version: 7.3.27
	PHP Max Input Vars: 1000
	PHP Max Post Size: 8M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.7.1
	Site URL: https://ealingfoe.org.uk
	Home URL: https://ealingfoe.org.uk
	WP Multisite: No
	Max Upload Size: 2 MB
	Memory limit: 300M
	Permalink Structure: /%postname%/
	Language: en-GB
	Timezone: Europe/London
	Debug Mode: Inactive

== Theme ==
	Name: Astra
	Version: 3.3.2
	Author: Brainstorm Force
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_GB
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:87.0) Gecko/20100101 Firefox/87.0

== Active Plugins ==
	Elementor
		Version: 3.2.1
		Author: Elementor.com

	Elementor - Header, Footer & Blocks
		Version: 1.5.9
		Author: Brainstorm Force, Nikhil Chavan

	Google Analytics for WordPress by MonsterInsights
		Version: 7.17.0
		Author: MonsterInsights

	Loginizer
		Version: 1.6.6
		Author: Softaculous

	Premium Addons for Elementor
		Version: 4.3.1
		Author: Leap13

	Really Simple SSL
		Version: 4.0.14
		Author: Really Simple Plugins

	SSL Zen - Free SSL Certificate & HTTPS Redirect for WordPress
		Version: 3.1.7
		Author: SSL Zen

	Starter Templates
		Version: 2.6.2
		Author: Brainstorm Force

	WordPress Importer
		Version: 0.7
		Author: wordpressdotorg

	WPForms Lite
		Version: 1.6.6
		Author: WPForms

	WP Google Analytics Events
		Version: 2.6.0
		Author: PineWise

== Must-Use Plugins ==
	Elementor Safe Mode
		Version: 1.0.0
		Author: Elementor.com

== Elementor - Compatibility Tag ==
	
	Elementor - Header, Footer & Blocks: compatible
	Premium Addons for Elementor: compatible

== Elements Usage ==
	
	page : 6
		button : 4
		heading : 2
		image : 24
		image-carousel : 1
		spacer : -14
		text-editor : 52
	section : 113
		button : 4
		heading : 9
		image : 5
		image-box : 1
		image-carousel : 1
		spacer : 3
		text-editor : 14
		video : 5
	wp-post : 41
		button : 20
		copyright : 1
		heading : 45
		image : 30
		image-carousel : 3
		navigation-menu : 7
		retina : 4
		social-icons : 3
		spacer : 25
		text-editor : 80
		video : 15
	wp-page : 28
		button : 2
		divider : 1
		heading : -75
		icon-list : 1
		image : -28
		image-box : 3
		image-carousel : 1
		premium-addon-blog : 3
		spacer : 1
		text-editor : 89
		video : -3

== Log ==
	
PHP: showing 7 of 7PHP: 2020-10-23 19:35:54 [notice X 1][/home/ealingfo/refresh.ealingfoe.org.uk/wp-content/plugins/elementor/includes/template-library/sources/local.php::697] ob_end_clean(): failed to delete buffer. No buffer to delete [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-11-04 22:00:58 [error X 5][/home/ealingfo/refresh.ealingfoe.org.uk/wp-content/plugins/elementor/core/common/modules/ajax/module.php::265] Allowed memory size of 41943040 bytes exhausted (tried to allocate 3688168 bytes) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-11-08 12:12:11 [error X 28][/home/ealingfo/refresh.ealingfoe.org.uk/wp-content/plugins/elementor/core/common/modules/ajax/module.php::265] Allowed memory size of 41943040 bytes exhausted (tried to allocate 3688488 bytes) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-11-10 14:35:49 [error X 2][/home/ealingfo/refresh.ealingfoe.org.uk/wp-content/plugins/elementor/core/common/modules/ajax/module.php::265] Allowed memory size of 41943040 bytes exhausted (tried to allocate 3684392 bytes) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-11-10 14:51:18 [error X 1][/home/ealingfo/refresh.ealingfoe.org.uk/wp-content/plugins/elementor/core/common/modules/ajax/module.php::265] Allowed memory size of 41943040 bytes exhausted (tried to allocate 3688512 bytes) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-11-24 14:30:14 [error X 3][/home/ealingfo/refresh.ealingfoe.org.uk/wp-content/plugins/elementor/core/common/modules/ajax/module.php::265] Allowed memory size of 41943040 bytes exhausted (tried to allocate 3289288 bytes) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-11-27 12:50:55 [notice X 3][/home/ealingfo/refresh.ealingfoe.org.uk/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

Log: showing 15 of 152020-11-04 16:39:47 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.12',
  'to' => '3.0.13',
)]
2020-11-25 16:40:39 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.13',
  'to' => '3.0.14',
)]
2020-12-21 16:09:42 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.14',
  'to' => '3.0.15',
)]
2021-01-07 04:44:58 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.15',
  'to' => '3.0.16',
)]
2021-01-26 16:09:39 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.16',
  'to' => '3.1.0',
)]
2021-02-01 04:20:30 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.1.0',
  'to' => '3.1.1',
)]
2021-03-03 04:20:55 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.1.1',
  'to' => '3.1.2',
)]
2021-03-04 04:34:40 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.1.2',
  'to' => '3.1.3',
)]
2021-03-10 13:53:26 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.1.3',
  'to' => '3.1.4',
)]
2021-04-22 16:39:53 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.1.4',
  'to' => '3.2.1',
)]
2021-04-22 16:39:53 [info] elementor::elementor_updater Started 
2021-04-22 16:39:53 [info] Elementor/Upgrades - _v_3_2_0_migrate_breakpoints_to_new_system Start  
2021-04-22 16:39:53 [info] Elementor/Upgrades - _v_3_2_0_migrate_breakpoints_to_new_system Finished 
2021-04-22 16:39:53 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.1.4',
  'to' => '3.2.1',
)]
2021-04-22 16:39:55 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.1.4',
  'to' => '3.2.1',
)]

JS: showing 14 of 14JS: 2020-11-11 16:43:59 [error X 1][https://refresh.ealingfoe.org.uk/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.0.13:2:467592] t.ui.form is undefined 
JS: 2020-11-11 16:44:33 [error X 1][https://refresh.ealingfoe.org.uk/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.0.13:2:474266] elementorFrontend.elements.window.jQuery is not a function 
JS: 2020-11-11 16:44:33 [error X 1][https://refresh.ealingfoe.org.uk/wp-content/plugins/elementor/assets/js/frontend.min.js?ver=3.0.13:2:0]  
JS: 2020-11-28 18:22:26 [error X 1][https://refresh.ealingfoe.org.uk/wp-admin/load-scripts.php?c=1&loadchunk_0=underscore,shortcode,utils,jquery-core,backbone,wp-util,wp-backbone,media-models,moxiejs,plupload,wp-plupload,jquery-ui-core,jqu&loadchunk_1=ery-ui-widget,jquery-ui-mouse,jquery-ui-sortable&ver=5.5.3:8:24992] Permission denied to access property \"nodeType\" 
JS: 2020-11-28 19:32:25 [error X 4][https://refresh.ealingfoe.org.uk/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.0.14:2:0] Permission denied to access property \"reload\" on cross-origin object 
JS: 2020-11-29 10:08:37 [error X 2][https://refresh.ealingfoe.org.uk/wp-admin/load-scripts.php?c=1&loadchunk_0=underscore,shortcode,utils,jquery-core,backbone,wp-util,wp-backbone,media-models,moxiejs,plupload,wp-plupload,jquery-ui-core,jqu&loadchunk_1=ery-ui-widget,jquery-ui-mouse,jquery-ui-sortable&ver=5.5.3:8:0] Permission denied to access property \"addEventListener\" on cross-origin object 
JS: 2020-12-09 13:30:44 [error X 1][https://refresh.ealingfoe.org.uk/wp-content/plugins/premium-addons-for-elementor/assets/frontend/min-js/premium-addons.min.js?ver=4.0.9:1:2648] t is undefined 
JS: 2020-12-11 12:10:40 [error X 1][https://refresh.ealingfoe.org.uk/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.0.14:2:332655] elementorFrontend is not defined 
JS: 2020-12-13 14:29:45 [error X 1][https://refresh.ealingfoe.org.uk/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.0.14:2:230494] Blocked a frame with origin \"https://refresh.ealingfoe.org.uk\" from accessing a cross-origin frame. 
JS: 2020-12-13 20:09:43 [error X 2][https://refresh.ealingfoe.org.uk/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.0.14:2:377073] this.ui.title is undefined 
JS: 2020-12-17 11:10:02 [error X 42][https://refresh.ealingfoe.org.uk/wp-content/plugins/elementor/assets/lib/pickr/pickr.min.js?ver=1.5.0:2:19643] this.getColorRepresentation() is null 
JS: 2021-01-06 21:38:30 [error X 1][https://ealingfoe.org.uk/wp-content/plugins/elementor/assets/lib/inline-editor/js/inline-editor.min.js?ver=3.0.15:1:3190] Object.values is not a function 
JS: 2021-01-25 21:55:26 [error X 1][https://ealingfoe.org.uk/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.0.16:2:479520] this.view.container is undefined 
JS: 2021-01-31 17:11:32 [error X 3][https://ealingfoe.org.uk/wp-content/plugins/elementor/assets/js/frontend-modules.min.js?ver=3.1.0:2:36742] elementorFrontend.config.elements is undefined 

</details>

**Comment by shilo-ey** [comment] 2021-04-25 09:09
Hey @eefee-github 

We do have an issue with carousels but not related to the user role.

Please see here and let me know if it the same as you experience.
#14663

Thanks

**Comment by shilo-ey** [comment] 2021-04-26 12:17
This issue has been resolved in Elementor v3.2.2

Duplicate of #14642

Feel free to update

Thanks!

**Closed by shilo-ey** 2021-04-26 12:17 UTC
Labels: status/merged, status/needs feedback

**Comment by eefee-github** [comment] 2021-05-15 09:56
Hi, I have checked this again with the latest Elementor version 3.2.3 and experience the same issue as initially reported.  

Compare
https://ealingfoe.org.uk/test-carousel-post-v3-2-3-editor/ - the carousel flows normally
https://ealingfoe.org.uk/test-carousel-post-v3-2-3-author/ - the carousel is frozen, as described

The issue was suggested as relating to this (now closed) ticket but it has not resolved the underlying issue  
https://github.com/elementor/elementor/issues/14663

**Comment by eefee-github** [comment] 2021-06-07 10:48
I have created a new ticket #15008, and would appreciate a response on either this original or the later ticket please.  
Thanks
