### ISSUE TITLE
🔗 ⛔ 🧩 🐞 Bug Report: Elementor Pro =< 3.12.1: GravityForms doesn't work inside Elementor popups (Duplicate of #7245)

### ISSUE THREAD

**Issue by mateitudor** [elementor/elementor#21977] opened 2023-04-08 23:49 UTC
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Reopening this bug since it was wrongfully marked as closed: https://github.com/elementor/elementor/issues/7245

**When adding a GravityForms widget inside an Elementor popup:**

> Forms that use conditional logic don't appear to load at all;
> Datepicker does not show;
> AJAX doesn't work.

Works the same with a shortcode instead of a widget.

My code, inspired by @nicomollet, kind of works, but it's hacky. It should work well out of the box.

```
<script>
(function ($) {
    function enqueueGravityFormsScripts() {
        $.ajax({
            url: "/wp-content/plugins/gravityforms/js/gravityforms.min.js",
            dataType: "script",
            cache: true
        }).done(function() {
            $.ajax({
                url: "/wp-content/plugins/gravityforms/js/datepicker.min.js",
                dataType: "script",
                cache: true
            });
        });
    }

    function enqueueGravityFormsStyles() {
        $('head').append($('<link>', {
            rel: 'stylesheet',
            type: 'text/css',
            href: "/wp-content/plugins/gravityforms/css/dist/theme.css"
        }));
    }

    $(document).on("elementor/popup/show", function (event, popupId, popup) {
        enqueueGravityFormsStyles();
        enqueueGravityFormsScripts();

        var gformWrapper = $(".gform_wrapper", popup.$element);
        if (!gformWrapper) {
            return;
        }
        var gformId = gformWrapper.get(0).id.replace(/^gform_wrapper_/, "");
        if (!gformId) {
            return;
        }
        var date = new Date(), y = date.getFullYear(), m = date.getMonth();
        var fSDate = new Date(y, m, 0);
        var fEDate = new Date(y, m + 12, 0);
        
        // Trigger gform_post_render event after the form has been loaded
        gformInitSpinner(gformId);
        gform.get("form_" + gformId).getPageNumber();
        $(document).trigger("gform_post_render", [gformId, 1]);
        
        $(document).on("gform_post_render", function (event, formId, currentPage) {
            $("#ui-datepicker-div").addClass("gform-theme-datepicker");
            $(".datepicker").datepicker({
                changeYear: true,
                changeMonth: true,
                showOtherMonths: true,
                yearRange: '-100:+20',
                dateFormat: 'yy-mm-dd',
                defaultDate: +0,
                minDate: fSDate,
                maxDate: fEDate
            });
        });
    });
})(window.jQuery);
</script>
<style> body div#ui-datepicker-div[style]{ z-index: 99999999!important; } </style>
```

Thank you in advance for all the work you do and your commitment to making quality code.

### Steps to reproduce

① Create a form using the GravityForms plugin;
② Make sure you add a date field;
③ Extra: add a phone field using GravityPerks Advanced Phone Field — it adds a dropdown country selector which doesn't load inside an Elementor popup;
④ Make an Elementor popup and add the form using either a widget or a shortcode;
⑤ Load the form by pressing a button;

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

<details>
<summary>System Info</summary>

````txt


					
== Server Environment ==
	Operating System: Linux
	Software: LiteSpeed
	MySQL version: MySQL Community Server (GPL) v5.7.41
	PHP Version: 8.1.16
	PHP Memory Limit: 2G
	PHP Max Input Vars: 15000
	PHP Max Post Size: 512M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.2
	Site URL: https://rukaizakaya.ro
	Home URL: https://rukaizakaya.ro
	WP Multisite: No
	Max Upload Size: 512 MB
	Memory limit: 40M
	Max Memory limit: 2G
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: Europe/Bucharest
	Admin Email: [REDACTED]
	Debug Mode: Inactive

== Theme ==
	Name: Ruka Izakaya
	Version: 1.0.1
	Author: Tudor Matei
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.7.1
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.5 Safari/605.1.15

== Active Plugins ==
	Change wp-admin login
		Version: 1.1.3
		Author: wpexpertsio

	Elementor
		Version: 3.13.0-dev2
		Author: Elementor.com

	Elementor Pro
		Version: 3.12.1
		Author: Elementor.com

	Email Address Encoder
		Version: 1.0.22
		Author: Till Krüss

	EmbedPress
		Version: 3.6.8
		Author: WPDeveloper

	GP Advanced Phone Field
		Version: 1.0.13
		Author: Gravity Wiz

	GP Limit Dates
		Version: 1.1.21
		Author: Gravity Wiz

	Gravity Forms
		Version: 2.7.3
		Author: Gravity Forms

	Gravity Perks
		Version: 2.2.9
		Author: Gravity Wiz

	Meta pixel for WordPress
		Version: 3.0.9
		Author: Facebook

	PixelYourSite
		Version: 9.3.5
		Author: PixelYourSite

	WP Crontrol
		Version: 1.15.2
		Author: John Blackbourn & crontributors

	WP Mail SMTP
		Version: 3.7.0
		Author: WPForms

	Yoast SEO
		Version: 20.4
		Author: Team Yoast

	Yoast SEO Premium
		Version: 20.4
		Author: Team Yoast


== Must-Use Plugins ==
	Local WP Live Link Helper
		Version: 2.0
		Author: Flywheel


== Elements Usage ==
	
	container : 0
		container : 7
		icon-list : 1
		image : 2
		social-icons : 1
		text-editor : 1
	page : 2
		button : 7
		container : 56
		gallery : 2
		heading : 29
		icon : 6
		image : 6
		nav-menu : 2
		text-editor : 14
	popup : 2
		container : 1
		html : 1
		shortcode : 1
	wp-page : 8
		button : 13
		container : 91
		gallery : 1
		heading : 46
		icon : 10
		image : 6
		nav-menu : 1
		qi_addons_for_elementor_premium_gravity_forms : 1
		text-editor : 20


== Settings ==
	
	cpt_support: post, page
	disable_color_schemes: yes
	disable_typography_schemes: yes
	allow_tracking: yes
	unfiltered_files_upload: 1


== Features ==
	Custom Fonts: 0
	Custom Icons: 0

== Integrations ==
	


== Elementor Experiments ==
	Optimized DOM Output: Active
	Improved Asset Loading: Active
	Improved CSS Loading: Active
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Active
	Additional Custom Breakpoints: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active
	Upgrade Swiper Library: Active
	Container Grid: Inactive by default
	Default to New Theme Builder: Active by default
	Hello Theme Header & Footer: Inactive
	Editor Top Bar: Active
	Landing Pages: Inactive
	Nested Elements: Active
	Lazy Load Background Images: Active
	Page Transitions: Active by default
	Notes: Inactive
	Loop: Active
	Form Submissions: Inactive
	Scroll Snap: Active by default
	Menu: Active


== Log ==
	
Log: showing 20 of 322023-03-27 18:18:33 [info] elementor-pro::elementor_pro_updater Started 
2023-03-27 18:18:33 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-03-27 18:18:33 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-03-27 18:18:33 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.10.1',
  'to' => '3.11.7',
)]
2023-03-27 18:18:33 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.10.1',
  'to' => '3.11.7',
)]
2023-04-08 18:52:25 [info] elementor-pro::elementor_pro_updater Started 
2023-04-08 18:52:25 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-04-08 18:52:25 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-04-08 18:52:25 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.11.7',
  'to' => '3.12.1',
)]
2023-04-08 18:52:25 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.11.5',
  'to' => '3.12.1',
)]
2023-04-08 18:52:26 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.11.7',
  'to' => '3.12.1',
)]
2023-04-08 18:52:26 [info] elementor::elementor_updater Started 
2023-04-08 18:52:26 [info] Elementor/Upgrades - _on_each_version Start  
2023-04-08 18:52:26 [info] Elementor/Upgrades - _on_each_version Finished 
2023-04-08 18:52:26 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.11.5',
  'to' => '3.12.1',
)]
2023-04-08 18:52:27 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.11.5',
  'to' => '3.12.1',
)]
2023-04-08 19:50:10 [info] elementor::elementor_updater Started 
2023-04-08 19:50:10 [info] Elementor/Upgrades - _on_each_version Start  
2023-04-08 19:50:10 [info] Elementor/Upgrades - _on_each_version Finished 
2023-04-08 19:50:10 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.12.1',
  'to' => '3.13.0-dev2',
)]

PHP: showing 5 of 5PHP: 2023-03-27 18:30:05 [notice X 9142][../wp-content/plugins/elementor-pro/modules/loop-builder/module.php::200] strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-03-27 19:25:39 [notice X 3024][../wp-content/plugins/elementor-pro/modules/custom-css/module.php::76] trim(): Passing null to parameter #1 ($string) of type string is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-03-29 06:50:42 [notice X 10][../wp-content/plugins/elementor-pro/modules/custom-css/module.php::76] trim(): Passing null to parameter #1 ($string) of type string is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: ../wp-content/plugins/elementor-pro/modules/custom-css/module.php(76): class type trim()
#2: ../wp-includes/class-wp-hook.php(308): ElementorPro\Modules\CustomCss\Module -> add_page_settings_css()
#3: ../wp-includes/class-wp-hook.php(332): WP_Hook -> apply_filters()
#4: ../wp-includes/plugin.php(517): WP_Hook -> do_action()
',
)]
PHP: 2023-04-09 01:00:20 [warning X 1][../wp-content/plugins/elementor/app/modules/import-export/module.php::696] Attempt to read property "label" on null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-04-09 01:00:21 [warning X 1][../wp-content/plugins/elementor/core/common/modules/ajax/module.php::175] Undefined array key "data" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 5 of 5JS: 2023-04-08 21:35:51 [error X 1][https://rukaizakaya.ro/wp-includes/js/jquery/jquery.min.js?ver=3.6.3:2:31830] e.dispatchEvent is not a function. (In 'e.dispatchEvent(new CustomEvent(t,{detail:n}))', 'e.dispatchEvent' is undefined) 
JS: 2023-04-08 23:09:35 [error X 1][https://rukaizakaya.ro/ruka-izakaya-japanese-restaurant-2/:702:29] Can't find variable: wp_enqueue_style 
JS: 2023-04-08 23:10:14 [error X 1][https://rukaizakaya.ro/ruka-izakaya-japanese-restaurant-2/:703:35] gform.get_base_url is not a function. (In 'gform.get_base_url()', 'gform.get_base_url' is undefined) 
JS: 2023-04-08 23:19:42 [error X 9][https://rukaizakaya.ro/ruka-izakaya-japanese-restaurant-2/:742:18] gform.get is not a function. (In 'gform.get("form_" + gformId)', 'gform.get' is undefined) 
JS: 2023-04-08 23:20:19 [error X 1][https://rukaizakaya.ro/ruka-izakaya-japanese-restaurant-2/:709:34] Can't find variable: enqueueGravityFormsStyles




== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatibility not specified

== Elementor Pro - Compatibility Tag ==
	

				

````

</details>

**Comment by nicholaszein** [comment] 2023-07-29 22:35
Hello @mateitudor!

Thank you for your feedback! 🙏 

### ⛔ After reviewing your report we concluded this is not a bug caused by Elementor. The feature you're referring to is not yet supported.

Elementor currently does not provide any integration with Gravity Forms, including loading GF scripts on Popups. 

For performance reasons, Elementor Popups load content, scripts, and styles dynamically not on page load. Gravity Forms scripts need to see the form on the page to trigger their actions. This needs to be something that the developers of the plugin need to account for.

However, you can either use the solution you provided [here](https://github.com/elementor/elementor/issues/7245#issuecomment-1500990456) or use a 3rd-party Elementor add-on that has Gravity Forms integration. Usually, they implement the necessary script to ensure the forms from GF work on Popups.

There are no plans to change the Popup API or add integration to Gravity Forms on Elementor Popups for the time being.

If you think this should be an Elementor feature, please submit a new [🚀 Feature Request](https://github.com/orgs/elementor/discussions/new?category=feature-request), and we will consider it in the future if there is enough demand (votes) from other users.

### 🔗 🐞 This issue is a Duplicate of #7245 

Which is on the same subject. 

Kind regards

**Closed by nicholaszein** 2023-07-29 22:35 UTC
Labels: compatibility/3rd_party, product/pro, component/popup, mod*
