### ISSUE TITLE
🔗 Image Carousel Widget - image size selection won't produce HTML Width, Height etc Attributes - Lighthouse "Image elements do not have explicit width and height" Error (Duplicate of #11348)

### ISSUE THREAD

**Issue by ghost** [elementor/elementor#15654] opened 2021-07-14 22:13 UTC
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

i inserted 5 some pictures in Image Carousel Widget, selected a pre-defined/custom size, then hit publish. (i chose Medium 300 x 300 size)
but when i checked the HTML there was no HTML attributes for < img >like Height, Width, Lazy-Load, srcset etc.
and i even checked it with lighthouse rules. and faced the " Image elements do not have explicit width and height " error

it'll be produced something like : (website link is replaced with "YYY")

```
< div class="swiper-slide" data-swiper-slide-index="0" style="width: 147.5px;">
      < figure class="swiper-slide-inner" >
            < img class="swiper-slide-image" src="YYY" alt="15" >
      < /figure>
</div>
```

instead it must be like : (website link is replaced with "YYY")

```
< div class="swiper-slide" data-swiper-slide-index="0" style="width: 147.5px;">
      < figure class="swiper-slide-inner" >
            < img class="swiper-slide-image" src="YYY" height="300px" width="500px" srcset=" ... " loading="lazy" alt="15">
      </ figure>
</ div>
```

## Steps to reproduce

1 - install Wordpress
2 - install Elementor
3 - create a new page/post
4 - add an Image Carousel with any Pre-defined/Custom Size.
5 - publish the page/post
6 - check the < img > property in HTML. no width and height attribute, no lazy loading (lazy loading is very important, please implement it), no srcset etc.
9 - with Chrome, hit F12 key on keyboard, go to Lighthouse, and click on "Generate Report" button to see "Image elements do not have explicit width and height" error for the Custom Sized Image.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MariaDB Server v10.4.17
	PHP Version: 7.2.34
	PHP Max Input Vars: 1000
	PHP Max Post Size: 256M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.7.2
	Site URL: YYY
	Home URL: YYY
	WP Multisite: No
	Max Upload Size: 256 MB
	Memory limit: 1024M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: Twenty Twenty-One
	Version: 1.3
	Author: the WordPress team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 3.3.0
		Author: Elementor.com


== Elementor - Compatibility Tag ==
	


== Elements Usage ==
	
	wp-page : 1
		image-carousel : 1


== Log ==
	

				
```
</details>

**Comment by SteveKinzey** [comment] 2021-07-15 04:13
You need to add some custom CSS. To do this you can follow these steps.

1. Scroll to the bottom of the column and open the Custom CSS accordion as shown: https://prnt.sc/1bayxnv
2. The class for the carousel images is swiper-slide-image
3. Using that class enter in the CSS for width 300px and height 300px:  https://prnt.sc/1bb1u4b

And you will have assigned the width and height attributes to your images.

**Comment by masoudahmadpour** [comment] 2021-07-15 06:00
@SteveKinzey Thanks for workaround and the explanations. Actually i've done the same thing.
However while this workaround will work, Elementor should consider adding these HTML attributes to the <img > tag.
Firstly because what will be the use of " Image Size " selection anyway?
And besides, if you look at other image widgets in Elementor, some of them already have this.
So i think they might forgot to do it for this widget.

**Comment by bluantinoo** [comment] 2021-12-14 15:49
Can we consider this a duplicate of https://github.com/elementor/elementor/issues/11348 ?

**Comment by rami-elementor** [comment] 2022-02-21 21:26
Duplicate of #11348

**Closed by rami-elementor** 2022-02-21 21:26 UTC
Labels: component/swiper, type/performance, type/seo, mod*, widget/image-carousel*, duplicate

**Comment by puregraphx** [comment] 2022-04-26 11:05
My view is that adding the css rules does not impact GPSI score as Google expects the width/height to be added to the <img> tag as attributes like class, alt, ...

**Comment by NWTrailers** [comment] 2023-08-10 18:49
Agreed, the workaround is not acceptable from GPSI's perspective. The image needs explicit width/height, not from css.

**Comment by alexiserodriguez** [comment] 2023-09-27 23:27
Hi! Any update on this issue? Still happens

**Comment by blockmonkey** [comment] 2023-10-02 22:59
+1 - any chance this is being worked on?

**Comment by vaccinemedia** [comment] 2023-10-23 21:52
I'm getting "Image elements do not have explicit width and height" on the Post Info widget when showing the avatar of thr author.
