### ISSUE TITLE
✔️ 🐞 Bug report: Flexbox Container, weird behaviour when nested and Boxed content

### ISSUE THREAD

**Issue by hogash** [elementor/elementor#19616] opened 2022-08-25 21:47 UTC
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

When adjusting width inside a nested Container, in Boxed content width mode, the behaviour is odd. Recorded a quick video: https://d.pr/v/0pqc1c .

Seems to be tied with the container's padding.

### Steps to reproduce

Nest a Container inside another Container, duplicate the nested container and add any element inside. Set the nested container's content width to Boxed and adjust the width. A side padding is increasing and decreasing while adjusting the content width.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by nicholaszein** [comment] 2022-11-16 04:46
Hello there @hogash!

We have great news! 🙌 

### 📢 We're happy to announce that the issue you raised was resolved in Elementor **v3.8**! 🥳 

Part of what you reported is how CSS Flexbox behaves by default. If you change flex-grow and flex-shrink, it will try to fill the space of the entire container if it can to fit its contents, including padding. This is the expected behavior. But as you pointed out, the way we were implementing the boxed content was by using some calculations to add padding to the boxed container. Since version 3.8 boxed containers now have an inner-wrapper to apply the boxed state, so the padding that was being added does not influence the size of the container anymore when it's being nested.

✔️ Please feel free to check it out and update your plugin to the new version!

Cheers 🥂

**Closed by nicholaszein** 2022-11-16 04:46 UTC
Labels: bug, component/container, 🚀 shipped
