### ISSUE TITLE
✔️ 🐞 Bug Report: Sticky Container's z-index overrides the Container's z-index control's value

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#20227] opened 2022-11-02 10:30 UTC
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

In the container, there are still two bugs in z-index.

1- **We cannot use z-index to determine which container is on top of another container.**

https://user-images.githubusercontent.com/77163248/199465416-e104bbe7-d80b-4229-a63c-c74b081881b7.mp4

As you can see in the video above, for the yellow container, I set the z-index to 999 so that it is above the white container. But z-index doesn't work for that at all. **But if we include the z-index in the custom css section of the container, it works fine.**

2- **If we have a container in sticky mode, after scrolling, the container handles and also the blue border of the container will be placed on the sticky container.**

https://user-images.githubusercontent.com/77163248/199466235-9a4aaaf5-f956-4002-9ea6-f545a9b5a3fa.mp4

### Steps to reproduce

**BUG 1**

- Create two containers in sticky mode.
- After scrolling, a container is placed higher.
- Using the z-index, try to determine which container should be placed at the top.

Will not work.

**BUG 2**

If you have a sticky container, it will be visible on the lower container handles after scrolling.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

[system-info-localhost-01-11-2022.txt](https://github.com/elementor/elementor/files/9919373/system-info-localhost-01-11-2022.txt)

**Comment by nicholaszein** [comment] 2022-11-02 17:03
Hello @79ho3ein! 

Thank you for your detailed description and steps to reproduce! 🙏 

I was able to reproduce the **first bug** consistently and have already detected the issue. 

As for your second "bug", I can confirm this is not a bug and is working as expected since the selected container should always show the editor overlay and handles to be easily selected. Modifying this behavior could affect other cases, like when we had a sticky header and couldn't see the topmost container's handles. I think you were the one to report this as an issue. So now we make sure the handles are always visible by increasing their z-index. This doesn't affect any other functionality or front-end rendering, so it's a good compromise.

I'll be forwarding this to the team to see if we can fix the first issue.

Best regards

**Comment by 79ho3ein** [comment] 2022-11-02 17:30
Hi @nicholaszein.

The first problem, will it be fixed in version 3.8?

But about the second bug, isn't this an abnormal behavior? In the section (before container), everything was working fine. But it behaves like this in the container. I know it doesn't cause any problems in the front end, but it makes a very bad UI in the editor. I hope there is a solution for it.

**Comment by nicholaszein** [comment] 2022-11-07 18:00
Hey @79ho3ein!

We have great news! 🙌 

### 📢 We're happy to announce that the issue you raised was resolved in Elementor Pro **v3.8.1**! 🥳 

✔️ Please feel free to check it out and update your plugin to the new version!

As for the second issue, we are not planning to change this behavior for the time being. We might revisit it in the future, but for now, this is not affecting the editor's usability. Thanks for raising the concern though, and thanks for finding the z-index bug!

Cheers 🥂

**Closed by nicholaszein** 2022-11-07 18:00 UTC
Labels: bug, component/container, component/sticky

**Comment by nicholaszein** [comment] 2022-11-29 20:40
Hello all, I'm just passing by to say the remaining issue with the [z-index has been fixed](https://github.com/elementor/elementor/discussions/20328#discussioncomment-4158614) in the v3.9-Beta2. 🙌 

Kind regards
