### ISSUE TITLE
🔗 🚀 Feature Request: Advanced Conditions for Pop-Ups (Duplicate of #6899)

### ISSUE THREAD

**Issue by cranstantinople** [elementor/elementor#20885] opened 2022-12-30 02:29 UTC
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

I'm trying to allow clients to easily schedule pop-ups for things such as holiday hours or ad campaigns but there are no scheduling options for Pop-Ups.

### Describe the solution you'd like

Ideally I would like trigger that shows a popup if a Post query returns results (i.e.  Post [Type] with [Category] is [Published], trigger popup).  I've purchased Essential Addons Agency which allows me to Publish/Unpublish posts on specific dates.  With this feature for Elementor popups, I would be able to create a Custom Post Type called "Popup Notices" and users could schedule those posts meeting the conditions-- triggering the popup.

Even the ability to schedule or end pop-ups directly as a trigger would be helpful.

### Describe alternatives you've considered

 I've purchased Essential Addons Agency which allows me to Publish/Unpublish posts on specific dates and tried using their "Display Conditions" features but with no luck on popups.

**Comment by cranstantinople** [comment] 2022-12-30 02:33
Even better would be a more universal "Conditions" feature for Elementor that would allow for { If {Conditions}, [Trigger/Hide/Show] Elements with [Class/ID] }

**Comment by nicholaszein** [comment] 2023-01-27 16:12
Hello @cranstantinople!

Thank you for your submission! 🙏 

### 🔗 This issue is a Duplicate of #6899

Which is on the same subject. 

For this reason, I'm closing this issue and 🔃 **Merging** it with the original, so we can have all the discussions in one location, and deal with it more efficiently.

We are also beta-testing our new [Popup Advanced Rule for Date and Time range](https://github.com/elementor/elementor/discussions/21125), which covers part of what you're asking. Try the new beta version and let us know if it helps to manage popups better.

Feel free to continue the conversation there. 😉 

Best regards,

Nick

**Closed by nicholaszein** 2023-01-27 16:12 UTC
Labels: request/enhancement, product/pro, component/popup, product/beta3.11
