### ISSUE TITLE
✅ 🐞 Bug Report: Loop Carousel links only work after clicking on Navigation Arrows when inside a Mega Menu (Related to #23039) - [ED-11434]

### ISSUE THREAD

**Issue by mateitudor** [elementor/elementor#23705] opened 2023-09-07 17:10 UTC
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

It's kind of hard to explain but if you have a loop carousel inside an Elementor Menu widget, in the dropdown, the loop items only become clickable if you press the left or right arrows.

### Steps to reproduce

1) Create an Elementor Menu widget
2) add a loop carousel in one of the menu items
3) In the front-end, hover over the menu item with the dropdown
4) then hover over any of the loop items
5) there is no hover state or pointer event connected to the loop item
6) click the prev/next arrows or flick to scroll → loop items become clickable

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

<details>
<summary>Click to reveal</summary>

````txt


					
== Server Environment ==
	Operating System: Darwin
	Software: nginx/1.16.0
	MySQL version: MySQL Community Server - GPL v8.0.16
	PHP Version: 8.1.9
	PHP Memory Limit: 256M
	PHP Max Input Vars: 4000
	PHP Max Post Size: 1000M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.3.1
	Site URL: https://washlinks.local
	Home URL: https://washlinks.local
	WP Multisite: No
	Max Upload Size: 300 MB
	Memory limit: 40M
	Max Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: America/Toronto
	Debug Mode: Inactive

== Theme ==
	Name: Washlinks
	Version: 0.0.6
	Author: Matei Tudor
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.8.1
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Safari/605.1.15

== Active Plugins ==
	All-in-One WP Migration
		Version: 7.78
		Author: ServMask

	All-in-One WP Migration Unlimited Extension
		Version: 2.53
		Author: ServMask

	Custom Post Type Permalinks
		Version: 3.5.2
		Author: Toro_Unit

	Elementor
		Version: 3.16.0-dev4
		Author: Elementor.com

	Elementor Beta (Developer Edition)
		Version: 1.1.1
		Author: Elementor.com

	Elementor Pro
		Version: 3.16.0-beta4
		Author: Elementor.com

	GP Multi-page Navigation
		Version: 1.2.3
		Author: Gravity Wiz

	GP Page Transitions
		Version: 1.0.22
		Author: Gravity Wiz

	GP Populate Anything
		Version: 2.0.12
		Author: Gravity Wiz

	Gravity Forms
		Version: 2.7.13
		Author: Gravity Forms

	Gravity Forms Auto Formatter
		Version: 2.7.1
		Author: Plugin Owl

	Gravity Perks
		Version: 2.3.4
		Author: Gravity Wiz

	JetEngine
		Version: 3.2.4
		Author: Crocoblock

	JetEngine - Custom visibility conditions
		Version: 1.1.2
		Author: Crocoblock

	Nested Pages
		Version: 3.2.4
		Author: Kyle Phillips

	Rank Math SEO
		Version: 1.0.201.1
		Author: Rank Math

	Rank Math SEO PRO
		Version: 3.0.44
		Author: Rank Math

	Reveal Post Data
		Version: 0.1.0
		Author: Ross Morsali

	Unsplash
		Version: 1.0.1
		Author: Unsplash


== Features ==
	Custom Fonts: 0
	Custom Icons: 0

== Integrations ==
	


== Elementor Experiments ==
	Optimized DOM Output: Active
	Improved Asset Loading: Active
	Improved CSS Loading: Active
	Inline Font Icons: Active
	Additional Custom Breakpoints: Active
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active
	Upgrade Swiper Library: Active
	Grid Container: Active
	Default to New Theme Builder: Inactive
	Hello Theme Header & Footer: Inactive
	Editor Top Bar: Active
	Landing Pages: Inactive
	Nested Elements: Active
	Lazy Load Background Images: Inactive
	Pages Panel: Inactive by default
	Global Style Guide: Active
	Page Transitions: Inactive
	Notes: Inactive
	Form Submissions: Active
	Scroll Snap: Active
	Menu: Active
	Taxonomy Filter: Active


== Log ==
	
PHP: showing 20 of 24PHP: 2023-09-04 12:57:13 [warning X 1][../wp-content/plugins/elementor/app/modules/import-export/module.php::753] Attempt to read property "label" on null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-09-04 12:57:13 [warning X 1][../wp-content/plugins/elementor/core/common/modules/ajax/module.php::175] Undefined array key "data" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-09-04 12:57:13 [warning X 15][../wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php::150] Undefined array key "condition_type" [array (
  'trace' => '
#0: ../wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(150): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_template_json_item()
#2: ../wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(120): class type array_map()
#3: ../wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(59): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_templates_json()
#4: ../wp-content/plugins/elementor/data/base/endpoint.php(158): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> get_items()
',
)]
PHP: 2023-09-04 13:03:36 [warning X 1][../wp-content/plugins/elementor/core/files/file-types/svg.php::234] simplexml_load_file(): I/O warning : failed to load external entity "https://washlinks.local/wp-content/uploads/2023/05/washlinks-icon-soaps_chemicals-color.svg" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-09-04 13:03:36 [warning X 1][../wp-content/plugins/elementor/core/files/file-types/svg.php::234] simplexml_load_file(): I/O warning : failed to load external entity "https://washlinks.local/wp-content/uploads/2023/05/washlinks-icon-soaps_chemicals-duotone.svg" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-09-04 13:03:36 [warning X 1][../wp-content/plugins/elementor/core/files/file-types/svg.php::234] simplexml_load_file(): I/O warning : failed to load external entity "https://washlinks.local/wp-content/uploads/2023/05/washlinks-icon-soaps_chemicals-mono_dark.svg" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-09-04 13:03:36 [warning X 1][../wp-content/plugins/elementor/core/files/file-types/svg.php::234] simplexml_load_file(): I/O warning : failed to load external entity "https://washlinks.local/wp-content/uploads/2023/05/washlinks-icon-soaps_chemicals-mono_light.svg" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-09-04 13:15:16 [warning X 1][../wp-content/plugins/elementor/core/files/file-types/svg.php::234] simplexml_load_file(): I/O warning : failed to load external entity "https://washlinks.local/wp-content/uploads/2023/05/washlinks-icon-soaps_chemicals-color-1.svg" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-09-04 13:15:17 [warning X 1][../wp-content/plugins/elementor/core/files/file-types/svg.php::234] simplexml_load_file(): I/O warning : failed to load external entity "https://washlinks.local/wp-content/uploads/2023/05/washlinks-icon-soaps_chemicals-duotone-1.svg" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-09-04 13:15:17 [warning X 1][../wp-content/plugins/elementor/core/files/file-types/svg.php::234] simplexml_load_file(): I/O warning : failed to load external entity "https://washlinks.local/wp-content/uploads/2023/05/washlinks-icon-soaps_chemicals-mono_dark-1.svg" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-09-04 13:15:17 [warning X 1][../wp-content/plugins/elementor/core/files/file-types/svg.php::234] simplexml_load_file(): I/O warning : failed to load external entity "https://washlinks.local/wp-content/uploads/2023/05/washlinks-icon-soaps_chemicals-mono_light-1.svg" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-09-04 13:15:41 [warning X 1][../wp-content/plugins/elementor/core/files/file-types/svg.php::234] simplexml_load_file(): I/O warning : failed to load external entity "https://washlinks.local/wp-content/uploads/2023/05/washlinks-icon-precise_cost_controls-color.svg" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-09-04 13:15:42 [warning X 1][../wp-content/plugins/elementor/core/files/file-types/svg.php::234] simplexml_load_file(): I/O warning : failed to load external entity "https://washlinks.local/wp-content/uploads/2023/05/washlinks-icon-precise_cost_controls-duotone.svg" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-09-04 13:15:42 [warning X 1][../wp-content/plugins/elementor/core/files/file-types/svg.php::234] simplexml_load_file(): I/O warning : failed to load external entity "https://washlinks.local/wp-content/uploads/2023/05/washlinks-icon-precise_cost_controls-mono_dark.svg" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-09-04 13:15:42 [warning X 1][../wp-content/plugins/elementor/core/files/file-types/svg.php::234] simplexml_load_file(): I/O warning : failed to load external entity "https://washlinks.local/wp-content/uploads/2023/05/washlinks-icon-precise_cost_controls-mono_light.svg" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-09-04 13:21:47 [warning X 1][../wp-content/plugins/elementor/core/files/file-types/svg.php::234] simplexml_load_file(): I/O warning : failed to load external entity "https://washlinks.local/wp-content/uploads/2023/05/washlinks-icon-chemical_safety-color.svg" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-09-04 13:21:47 [warning X 1][../wp-content/plugins/elementor/core/files/file-types/svg.php::234] simplexml_load_file(): I/O warning : failed to load external entity "https://washlinks.local/wp-content/uploads/2023/05/washlinks-icon-chemical_safety-dark.svg" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-09-04 13:21:47 [warning X 1][../wp-content/plugins/elementor/core/files/file-types/svg.php::234] simplexml_load_file(): I/O warning : failed to load external entity "https://washlinks.local/wp-content/uploads/2023/05/washlinks-icon-chemical_safety-duotone.svg" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-09-04 13:21:47 [warning X 1][../wp-content/plugins/elementor/core/files/file-types/svg.php::234] simplexml_load_file(): I/O warning : failed to load external entity "https://washlinks.local/wp-content/uploads/2023/05/washlinks-icon-chemical_safety-mono_light.svg" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-09-06 14:30:01 [warning X 1][../wp-content/plugins/elementor/core/files/file-types/svg.php::234] simplexml_load_file(): I/O warning : failed to load external entity "https://washlinks.local/wp-content/uploads/2023/05/icon-canada_leaf-gray.svg" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 5 of 5JS: 2023-09-04 15:48:16 [error X 12][https://washlinks.local/wp-admin/load-scripts.php?c=1&loadchunk_0=jquery-core,jquery-migrate,utils,wp-polyfill-inert,regenerator-runtime,wp-polyfill,wp-hooks&ver=6.3.1:2:28729] undefined is not an object (evaluating 'l[0].value') 
JS: 2023-09-04 15:49:42 [error X 2][https://washlinks.local/wp-content/plugins/elementor/assets/js/4fdaa70e951ad90db2f2.bundle.min.js:2:7739] null is not an object (evaluating 'elementor.documents.currentDocument.id') 
JS: 2023-09-04 15:49:44 [error X 1][https://washlinks.local/wp-content/plugins/elementor/assets/js/4fdaa70e951ad90db2f2.bundle.min.js:2:7997] undefined is not an object (evaluating 's.view') 
JS: 2023-09-06 18:17:37 [error X 5][https://washlinks.local/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.16.0-dev3:3:803958] undefined is not an object (evaluating 'this.store.find((function(T){return T.original===C})).localized') 
JS: 2023-09-06 18:30:53 [error X 2][https://washlinks.local/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.16.0-dev3:3:54033] undefined is not an object (evaluating '$.activate') 

Log: showing 14 of 142023-09-07 13:03:53 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.16.0-dev3',
  'to' => '3.16.0-dev4',
)]
2023-09-07 13:03:53 [info] elementor::elementor_updater Started 
2023-09-07 13:03:53 [info] Elementor/Upgrades - _on_each_version Start  
2023-09-07 13:03:53 [info] Elementor/Upgrades - _on_each_version Finished 
2023-09-07 13:03:53 [info] Elementor/Upgrades - _v_3_16_0_container_updates Start  
2023-09-07 13:03:54 [info] Elementor/Upgrades - _v_3_16_0_container_updates Finished 
2023-09-07 13:03:54 [info] Elementor/Upgrades - _v_3_17_0_site_settings_updates Start  
2023-09-07 13:03:54 [info] Elementor/Upgrades - _v_3_17_0_site_settings_updates Finished 
2023-09-07 13:03:54 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.16.0-dev3',
  'to' => '3.16.0-dev4',
)]
2023-09-07 13:04:38 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.16.0-beta3',
  'to' => '3.16.0-beta4',
)]
2023-09-07 13:04:38 [info] elementor-pro::elementor_pro_updater Started 
2023-09-07 13:04:38 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-09-07 13:04:38 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-09-07 13:04:38 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.16.0-beta3',
  'to' => '3.16.0-beta4',
)]



== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatible

== Elementor Pro - Compatibility Tag ==
	

				

````

</details>

**Comment by nicholaszein** [comment] 2023-09-08 16:04
Hello @mateitudor! 

Thank you for submitting your issue! 🙏 

Please allow us some time to investigate it, and get back to you with our findings. 🧐 

Best regards

**Comment by IgnorePT** [comment] 2023-09-10 15:36
Is not only in Mega Menu, currently the issue is the same on a normal container.

**Comment by midihead7** [comment] 2023-09-14 17:46
I am experiencing the same exact issue. The issue doesn't happen for me on Elementor 3.16.0 and Elementor Pro 3.16.0 but DOES happen once I update to any higher version of either plugin.

**Comment by mateitudor** [comment] 2023-09-20 07:38
Notice how they reference closed tickets... they close them before they test anything. So silly.

**Comment by midihead7** [comment] 2023-10-01 16:24
@nicholaszein When do you expect that this bug will be fixed? Thank you.

**Comment by nicholaszein** [comment] 2023-10-01 20:00
A fix fo this issue has been introduced in version 3.17-beta1. I would love to know your feedback about it.

**Comment by shad0wlan** [comment] 2023-10-04 19:59
Hello, i had this problem too. I use elementor pro with hello theme. My issue was:
Using tabs widget, inside every tab i had a loop carousel with custom product loop item using cta widget.
First tab loop item links was working (hovering animations and link)
The other loop items in the other tabs wasnt reacting at all (no hover animations and no link) till the slider moves to the next slides. After this they worked. This issue was happening in every tab except the first.

With the update to 3.17-beta1 the issue was fixed.

However i noticed an issue that was happening the last month and i didnt create any ticket.
When the Lazy Load Background Images setting is enabled, when i use a loop carousel or loop grid, when i load more elements (using load more button or other modes), the background images of the next items arent loading.

**Comment by midihead7** [comment] 2023-10-04 23:46
@nicholaszein Elementor Pro 3.17-beta1 appears to fix the issue for me on a staging copy of my site however this doesn't yet help those who don't want to install the beta version on their live production sites (Elementor Support specifically discourages installing betas on production sites). What is a realistic estimate of when Elementor Pro 3.17 stable will be released?

**Comment by yyc-food-blog** [comment] 2023-12-26 20:04
Did the fix in the beta go to the live version yet? I'm having this problem with clickable links in a simple carousel.

**Comment by steveindzine** [comment] 2024-01-04 16:04
I am having similar problems with a carousel where the [Emage Hover Image](https://codecanyon.net/item/emage-image-hover-effects-for-elementor-page-builder/22563091) doesn't work correctly until the loop carousel is paged. If I use the standard carousel with the widget none of them work correctly until you get to the duplicated carousel items.

**Comment by nicholaszein** [comment] 2024-01-05 18:36
Hello everyone!

@shad0wlan, and @midihead7, thank you for confirming the issue has been solved, and I apologize for the delay. 🙏 

### 📢 We're happy to announce that the issue you raised was resolved in Elementor 3.17.0! 🥳 

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂

**Closed by nicholaszein** 2024-01-05 18:36 UTC
Labels: bug, type/ui-ux, product/pro, status/merged, ✅ solved, component/nested/menu, mod*, component/nested/carousel

**Comment by nicholaszein** [comment] 2024-01-05 18:39
Hi, @yucheng91.

The `inert` attribute issue is still under investigation. Please refer to this issue to follow its resolution: #23039

Currently, there is no ETA on a fix for this issue.

Kind regards

**Comment by nicholaszein** [comment] 2024-01-05 18:41
Hi @yyc-food-blog,

This issue was related to the Loop Carousel widget inside a Mega Menu. It does not correlate to other carousel widgets.

If after troubleshooting your issue, and isolating the problem, you are certain there is a problem in the code, please submit a new [🐞 Bug Report](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml), so we can help you better.

Kind regards

**Comment by nicholaszein** [comment] 2024-01-05 18:43
Hello @steveindzine.

### ⛔ 🧩 Please note that while we do welcome bug reports, we can't provide support for 3rd-party add-ons/extensions.

If your issue is specifically happening only when you're using a feature from a 3rd-party software, or only when the 3rd-party software is active, you'll need to contact the support for that specific software or its developers.

Regards
