### ISSUE TITLE
🔗 🚀 Feature Request: Custom values ​​for Transition Duration controls (Duplicate of #20997)

### ISSUE THREAD

**Issue by Michaelgimii** [elementor/elementor#21012] opened 2023-01-14 10:43 UTC
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

Hi elementor team.

In version 3.10, some fields were improved and the possibility of using calc and clamp values ​​was added. So it would be great if you improve the Transition Duration controls.

### Describe the solution you'd like

If you add the ability to write text to the Transition Duration controls, we can have more complete control over it. **For example, we can write :** transform 0.3s ease-in or ...

**Comment by nicholaszein** [comment] 2024-03-10 04:51
Hello @Michaelgimii! It seems this issue was a duplicate of another one of yours. For the sake of completion, I'm reproducing my comment again:

> This feature was added to almost all transition durations from various widgets in version 3.19.0, and improved in version 3.20.0.
> 
> You can now choose the units for transition duration, including setting custom ones! 
> 
> ✅ Feel free to check it out and update your plugin to the new version!
> 
> > _Check the changelog for more information:_
> > [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)
> 
Cheers 🥂

**Closed by nicholaszein** 2024-03-10 04:51 UTC
Labels: request/enhancement, status/merged, component/transitions-preloaders, type/animations, solved, solved-by/custom-units, duplicate
