### ISSUE TITLE
Change hour format to 24h

### ISSUE THREAD

**Issue by PVTD** [elementor/elementor#9582] opened 2019-11-15 09:12 UTC
[x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
[x] The issue still exists against the latest stable version of Elementor.
In europe we mostly use the 24h format, especially older people do not know how to work with AM/PM.
Is there a way to activate that this in the **Forms** block?

Also the popup location is a bit weird, but not a concern for right now :)
https://i.imgur.com/dHWSsjW.png

Info:
WP General settings set to H:i
Elementor Pro Version 2.7.3
Elementor Version 2.7.5
Using the **Forms** in popup mode.

TY, PV

**Comment by bainternet** [comment] 2019-11-16 22:23
Duplicate of #6610

**Closed by bainternet** 2019-11-16 22:23 UTC
