### ISSUE TITLE
✅ 🐞 Bug Report: Elementor Pro Gallery Lightbox Still Showing After Disabling Lightbox From The Site Settings - [ED-10590]

### ISSUE THREAD

**Issue by AbdoSarmini** [elementor/elementor#19871] opened 2022-09-20 18:09 UTC
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Elementor Pro Gallery lightbox is still showing after disabling the global lightbox option from the global settings. This problem happens only when the link option is set to media file. And I can't turn off the link option because I am using another lightbox plugin. So now I am seeing 2 lightboxes on top of each other.

### Steps to reproduce

1. Disable the "Image Lightbox" option from the global site settings.
2. Add Gallery block (Pro version).
3. Add some images and set the link to media file.
4. Now click on any image and the lightbox will show up.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

.

**Comment by rami-elementor** [comment] 2022-09-21 09:36
Hi @AbdoSarmini ,

Good catch. I confirm. The bug recreated with the "Gallery" widget.

**Site settings:**

![lb1](https://user-images.githubusercontent.com/92088692/191470566-f07bb443-49c7-4926-8cb3-1f02809fa7d8.png)

**Gallery widget:**

![lb2](https://user-images.githubusercontent.com/92088692/191470577-a20eac2a-df4c-4bdf-91af-1269270700ea.png)

**Basic gallery widget:**

![lb3](https://user-images.githubusercontent.com/92088692/191470585-8c419acc-2244-4e87-8667-1e58a8735f44.png)

**Comment by black-eye** [comment] 2022-09-21 09:45
The issue is there lurking since the introduction of the Gallery Pro and new lightbox - https://github.com/elementor/elementor/issues/11193. But I thought it was resolved. Apparently not completely...

**Comment by AbdoSarmini** [comment] 2022-09-22 11:47
> The issue is there lurking since the introduction of the Gallery Pro and new lightbox - #11193. But I thought it was resolved. Apparently not completely...

It's been 2 years and I don't think it is a hard thing to fix. Strange.

**Comment by AbdoSarmini** [comment] 2022-09-22 11:48
@rami-elementor Are you working with Elementor? If yes, do you know when it will be fixed? It's been 2 years.

**Comment by AbdoSarmini** [comment] 2022-09-23 22:35
Guys, I just figured out a solution to disable the Elementor lightbox completely from all the site. 
Just go to the Elementor site settings then to Custom CSS option and add this CSS code:
`.elementor-lightbox{
    display: none !important;
}`

**Comment by black-eye** [comment] 2022-11-05 18:04
Confirming the issue is still there. It just wasn't visible, because the Elementor lightbox was hiding behind the one I use. Please, please, fix this.

@AbdoSarmini Using `.elementor-lightbox{ display: none !important; }` is a "solution" that hides ALL the Elementor's lightboxes. For instance, the lightboxes for the videos.

**Comment by black-eye** [comment] 2023-04-26 20:55
Any news on this one? Elementor 3.12.2 & 3.12.3 (PRO) and the problem is still there.
@rami-elementor, @nicholaszein?

**Comment by nicholaszein** [comment] 2023-06-19 16:28
Hello there!

We have great news! 🙌 

### 📢 We're happy to announce that the issue you raised was resolved in Elementor Pro v3.14.0! 🥳 

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂

**Closed by nicholaszein** 2023-06-19 16:28 UTC
Labels: bug, product/pro, component/lightbox, status/merged, type/performance, component/site-settings, 🚀 shipped
