### ISSUE TITLE
wp-admin/edit.php pages for Posts and Pages show HTML source instead of HTML/CSS rendering

### ISSUE THREAD

**Issue by MikevHoenselaar** [elementor/elementor#12209] opened 2020-08-24 19:09 UTC
#12196  Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

## Description

I updated to 3.0.0 through the WordPress repository.
After updating I can't access My Posts and Pages in the backend anymore.
/wp-admin/edit.php?post_type=page and /wp-admin/edit.php?post_type=page give me raw HTML output of the complete page.

I deactivated Elementor and it is working again. When I active Elementor again the same bug is happening.

## Steps to reproduce

*) Update Elementor through WP repo to 3.0.0
*) Visit the Posts or Pages admin page
*) WIth either WooCommerce or Yoast SEO Premium active as plugins
*) This occured AFTER updating to Elementor 3.0.0

*) I deactivated WooCommerce, (Yoast SEO is active, Elementor is active) page was showing, when activating WooCommerce, same bug, but it looks like the loop is broken, since it only shows one post. When Deactivating Elementor, it shows all posts and pages again.

*) I deactivated Yoast SEO Premium (WooCommerce is active, Elementor is active), admin page was showing again, when activated Yoast, same bug. I see all posts and pages on the admin page

It looks like it has something to do with plugins tapping into the loop on those pages or something.
I also read in one of the bug reports here it taps into action/filters twice.
That could be a thing as well.

## Isolating the problem
- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a default WordPress theme active.
- [X] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
					
== Server Environment ==
	Operating System: Linux
	Software: nginx/1.15.8
	MySQL version: MySQL Community Server (GPL) v5.6.44
	PHP Version: 7.4.1
	PHP Max Input Vars: 3000
	PHP Max Post Size: 64M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.5
	Site URL: https://fitbox.nl
	Home URL: https://fitbox.nl
	WP Multisite: No
	Max Upload Size: 64 MB
	Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: nl
	Timezone: 2
	Debug Mode: Inactive

== Theme ==
	Name: Flone Child Theme
	Version: 1.0
	Author: codecarnival
	Child Theme: Yes
	Parent Theme Name: Flone
	Parent Theme Version: 2.0.4
	Parent Theme Author: codecarnival

== User ==
	Role: administrator
	WP Profile lang: nl_NL
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36

== Active Plugins ==
	Autoptimize
		Version: 2.7.7
		Author: Frank Goossens (futtta)

	CMB2
		Version: 2.7.0
		Author: CMB2 team

	CMB2 Field Type: Attached Posts
		Version: 1.2.7
		Author: WebDevStudios

	Compress JPEG & PNG images
		Version: 3.2.1
		Author: TinyPNG

	Elementor
		Version: 3.0.0
		Author: Elementor.com

	Fitbox Category plugin for Elementor
		Version: 0.0.1
		Author: Mike van Hoenselaar

	Fitbox plugin for Global Custom blocks Elementor
		Version: 0.0.1
		Author: Mike van Hoenselaar

	Fitbox plugin for Header on category pages Elementor
		Version: 0.0.1
		Author: Mike van Hoenselaar

	Flone Core
		Version: 2.0.2
		Author: codecarnival

	Gravity Forms
		Version: 2.4.20
		Author: Gravity Forms

	Gravity Forms Mailchimp Add-On
		Version: 4.7
		Author: Gravity Forms

	Hide from Search
		Version: 1.1.1
		Author: Micah Wood

	Jetpack by WordPress.com
		Version: 8.8.2
		Author: Automattic

	Mollie Payments for WooCommerce
		Version: 5.8.2
		Author: Mollie

	Redirection
		Version: 4.8
		Author: John Godley

	Redux Lite
		Version: 4.1.15
		Author: Redux.io + Dovy Paukstys

	Warpdrive
		Version: 2.10.2
		Author: Savvii <support@savvii.com>

	WebP Express
		Version: 0.17.5
		Author: Bjørn Rosell

	WooCommerce
		Version: 4.4.1
		Author: Automattic

	WooCommerce Google Analytics Integration
		Version: 1.4.23
		Author: WooCommerce

	WooCommerce Product Bundles
		Version: 6.3.3
		Author: SomewhereWarm

	WooCommerce Product Search
		Version: 3.0.0
		Author: itthinx

	WooCommerce Services
		Version: 1.24.1
		Author: Automattic

	WooLentor - WooCommerce Elementor Addons + Builder
		Version: 1.6.8
		Author: HasThemes

	WooLentor Pro
		Version: 1.4.8
		Author: HasThemes

	WordPress Zero Spam
		Version: 4.9.13
		Author: Ben Marshall

	YITH WooCommerce Wishlist
		Version: 3.0.13
		Author: YITH

	Yoast SEO Premium
		Version: 14.8
		Author: Team Yoast

== Elements Usage ==
	
	page : 38
		button : 18
		fb-cat : 1
		fb-conversion : 1
		fb-custom : 2
		fb-header : 1
		fb-highlight : 1
		flone_Masonary_Products : 1
		flone_banner : 91
		flone_blog : 14
		flone_brands : 5
		flone_countdown : 15
		flone_counter : 4
		flone_icon_with_info : 3
		flone_instagram : 2
		flone_map : 1
		flone_newsletter : 18
		flone_product_categories : 4
		flone_products : 5
		flone_section_title : 2
		flone_service : 27
		flone_slider : 29
		flone_tabbed_products : 27
		flone_tabbed_products_2 : 5
		flone_team : 4
		flone_testimonial : 12
		flone_welcome_content : 3
		heading : 141
		icon-box : 4
		icon-list : 1
		image : 15
		image-box : 4
		shortcode : 1
		social-icons : 1
		text-editor : 21
	section : 2
		flone_banner : 2
		flone_slider : 1
		heading : 1
		text-editor : 1
	wp-post : 0
		button : 3
		flone_banner : 2
		flone_blog : 1
		flone_counter : 3
		flone_icon_with_info : 4
		flone_product_categories : 1
		flone_section_title : 1
		flone_service : 7
		flone_slider : 1
		flone_team : 5
		google_maps : 1
		heading : 6
		shortcode : 3
		star-rating : 1
		text-editor : 9
	wp-page : 8
		fb-cat : 1
		text-editor : 2

== Log ==
	
Log: showing 17 of 172020-05-25 11:43:40 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.9.8',
  'to' => '2.9.9',
)]
2020-06-04 10:35:11 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.9.9',
  'to' => '2.9.11',
)]
2020-07-16 01:52:27 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.9.11',
  'to' => '2.9.13',
)]
2020-07-22 11:48:38 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.9.13',
  'to' => '2.9.14',
)]
2020-08-24 20:15:30 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '2.9.14',
  'to' => '3.0.0',
)]
2020-08-24 20:15:31 [info] elementor::elementor_updater Started 
2020-08-24 20:15:31 [info] Elementor/Upgrades - _v_3_0_0_move_general_settings_to_kit Start  
2020-08-24 20:15:31 [info] Elementor/Upgrades - _v_3_0_0_move_general_settings_to_kit Finished 
2020-08-24 20:15:31 [info] Elementor/Upgrades - _v_3_0_0_move_default_colors_to_kit Start  
2020-08-24 20:15:31 [notice] System colors are disabled. nothing to do. 
2020-08-24 20:15:31 [info] Elementor/Upgrades - _v_3_0_0_move_default_colors_to_kit Finished 
2020-08-24 20:15:31 [info] Elementor/Upgrades - _v_3_0_0_move_saved_colors_to_kit Start  
2020-08-24 20:15:31 [info] Elementor/Upgrades - _v_3_0_0_move_saved_colors_to_kit Finished 
2020-08-24 20:15:31 [info] Elementor/Upgrades - _v_3_0_0_move_default_typography_to_kit Start  
2020-08-24 20:15:31 [notice] System typography is disabled. nothing to do. 
2020-08-24 20:15:31 [info] Elementor/Upgrades - _v_3_0_0_move_default_typography_to_kit Finished 
2020-08-24 20:15:31 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.9.14',
  'to' => '3.0.0',
)]
</details>

**Comment by kukkakeppi** [comment] 2020-08-25 07:05
Hi!

I have exactly same issue here.

Post types that are made with CPT UI (+Pages) are only displaying HTML. Weird part is that custom categories are still shown correctly.

Deactivating Elementor or Rollback to 2.9.9. helps.

<img width="1675" alt="Näyttökuva 2020-8-25 kello 9 39 57" src="https://user-images.githubusercontent.com/41680593/91142865-3d00f580-e6ba-11ea-9686-ec79ca598ffe.png">

**Comment by kukkakeppi** [comment] 2020-08-25 08:01
@MikevHoenselaar 

I'll try to translate our hosting companys reply for this:

In our (my / MySpeaker.fi) case, the issue was caused by Yoast SEO Premium plugin, which caused wp-admin edit page to return false header-information (application/json) and therefore it only displays HTML.

They recommend us to rollback to 2.9.14 (latest stable version) and wait until they release newer version of 3.0, in which they hopefully do not have so many issues with other plugins.

**Comment by MikevHoenselaar** [comment] 2020-08-25 08:38
But is the problem with SEO Premium or Elementor? :)

**Comment by kukkakeppi** [comment] 2020-08-25 09:20
This I do not know unfortunately :(

**Comment by shilo-ey** [comment] 2020-08-25 12:16
I merged this issue with #12219, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!

**Closed by shilo-ey** 2020-08-25 12:16 UTC
