### ISSUE TITLE
⛔ 🐞 Bug Report: menu cart bug in sticky header and popup

### ISSUE THREAD

**Issue by Michaelgimii** [elementor/elementor#22285] opened 2023-05-02 11:30 UTC
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Hi

I want to create a bottom navigation for mobile users using two different methods.

![A](https://user-images.githubusercontent.com/88034902/235649710-caa130be-c044-4c33-9b6c-075704435544.jpg)

1- Create bottom navigation in the footer
2- Create bottom navigation in popup

In both of the above solutions, we will encounter an annoying bug. The problem is when we open the menu cart, the bottom navigation is placed on the menu cart. See the image below.

![B](https://user-images.githubusercontent.com/88034902/235650460-5147f1fe-78f7-49a5-be65-60c95a4f6e5f.jpg)

### Steps to reproduce

For both of the above solutions, I will describe the reproduction steps separately because they are slightly different. But the bug is similar.

**A : Create bottom navigation in the footer**

1- First, create a header and place the menu cart widget in it. To better understand the bug, be sure to consider a box shadow for the header container.

2- Now create a footer and add a container in it (bottom navigation) and add a desired widget in it. In the motion effect tab of this container, enable Sticky and set it to the bottom.

3- Check out the frontend here. When you open the menu cart, there is no problem. The main problem is in the next step.

4- Now go back to the header we created in step 1 and enable sticky for the header container (sticky top). After enabling sticky for the header container, visit the frontend and check the result. 

**When the menu cart is opened, the bottom navigation that we created in the footer is placed on the menu cart. Actually, activating the sticky mode in the header caused this bug.**

**B : Create bottom navigation in popup**

1- First, create a header and place the menu cart widget in it. To better understand the bug, be sure to consider a box shadow for the header container.

2- Create a popup for bottom navigation and place it at the bottom of the page and make the necessary settings for it.

3- Go to frontend and check the result. When the menu cart is opened, the bottom navigation(popup) that we created in the footer is placed on the menu cart. **What is different here from the previous solution is that it doesn't matter if the header is in sticky mode or not. In any case, this bug occurs.**

I hope you will be successful in reproducing this bug and fix it❤

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

<details>
<summary>System Info</summary>

== Server Environment ==
Operating System: WINNT
Software: Apache/2.4.38 (Win32) OpenSSL/1.1.1a PHP/7.3.2
MySQL version: mariadb.org binary distribution v5.6.42-84.2
PHP Version: 7.3.2
PHP Memory Limit: 128M
PHP Max Input Vars: 1000
PHP Max Post Size: 64M
GD Installed: Yes
ZIP Installed: Yes
Write Permissions: All right
Elementor Library: Connected

== WordPress Environment ==
Version: 6.1.1
Site URL: [http://localhost:80/elementor](http://localhost/elementor)
Home URL: [http://localhost:80/elementor](http://localhost/elementor)
WP Multisite: No
Max Upload Size: 64 MB
Memory limit: 40M
Max Memory limit: 256M
Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
Language: en-US
Timezone: Europe/berlin
Admin Email: [Michaelgimii@gmail.com](mailto:Michaelgimii@gmail.com)
Debug Mode: Inactive

== Theme ==
Name: Hello Elementor
Version: 2.7.1
Author: Elementor Team
Child Theme: No

== User ==
Role: administrator
WP Profile lang: en_US
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36

== Active Plugins ==
Elementor
Version: 3.12.0
Author: Elementor.com

Elementor Pro
Version: 3.12.0
Author: Elementor.com

WooCommerce
Version: 7.5.0
Author: Automattic
== Features ==
Custom Fonts: 0
Custom Icons: 0

== Integrations ==

woocommerce: Active

== Elementor Experiments ==
Optimized DOM Output: Active
Improved Asset Loading: Active
Improved CSS Loading: Active
Inline Font Icons: Inactive
Accessibility Improvements: Inactive
Additional Custom Breakpoints: Inactive
admin_menu_rearrangement: Inactive by default
Flexbox Container: Active
Upgrade Swiper Library: Active
Default to New Theme Builder: Inactive
Hello Theme Header & Footer: Inactive
Editor Top Bar: Active
Landing Pages: Inactive
Nested Elements: Active
Lazy Load Background Images: Inactive by default
Page Transitions: Inactive
Notes: Inactive
Loop: Active
Scroll Snap: Inactive
Menu: Active

== Log ==

Log: showing 20 of 322023-02-27 01:30:44 [info] elementor::elementor_updater Started
2023-02-27 01:30:44 [info] Elementor/Upgrades - _on_each_version Start
2023-02-27 01:30:44 [info] Elementor/Upgrades - _on_each_version Finished
2023-02-27 01:30:44 [info] Elementor data updater process has been completed. [array (
'plugin' => 'Elementor',
'from' => '3.11.1',
'to' => '3.11.2',
)]
2023-03-20 01:11:35 [info] Elementor data updater process has been queued. [array (
'plugin' => 'Elementor',
'from' => '3.11.2',
'to' => '3.11.5',
)]
2023-03-20 01:11:36 [info] Elementor data updater process has been queued. [array (
'plugin' => 'Elementor Pro',
'from' => '3.11.2',
'to' => '3.11.6',
)]
2023-03-20 01:11:36 [info] elementor-pro::elementor_pro_updater Started
2023-03-20 01:11:36 [info] Elementor/Upgrades - _on_each_version Start
2023-03-20 01:11:36 [info] Elementor Pro/Upgrades - _on_each_version Start
2023-03-20 01:11:36 [info] Elementor Pro/Upgrades - _on_each_version Finished
2023-03-20 01:11:36 [info] Elementor data updater process has been completed. [array (
'plugin' => 'Elementor Pro',
'from' => '3.11.2',
'to' => '3.11.6',
)]
2023-03-29 11:53:48 [info] Elementor data updater process has been queued. [array (
'plugin' => 'Elementor',
'from' => '3.11.5',
'to' => '3.12.0',
)]
2023-03-29 11:53:48 [info] elementor::elementor_updater Started
2023-03-29 11:53:48 [info] Elementor/Upgrades - _on_each_version Start
2023-03-29 11:53:48 [info] Elementor/Upgrades - _on_each_version Finished
2023-03-29 11:53:48 [info] Elementor data updater process has been completed. [array (
'plugin' => 'Elementor',
'from' => '3.11.5',
'to' => '3.12.0',
)]
2023-03-29 14:37:27 [info] Elementor data updater process has been queued. [array (
'plugin' => 'Elementor Pro',
'from' => '3.11.6',
'to' => '3.12.0',
)]
2023-03-29 14:37:27 [info] Elementor Pro/Upgrades - _on_each_version Start
2023-03-29 14:37:27 [info] Elementor Pro/Upgrades - _on_each_version Finished
2023-03-29 14:37:27 [info] Elementor data updater process has been completed. [array (
'plugin' => 'Elementor Pro',
'from' => '3.11.6',
'to' => '3.12.0',
)]

PHP: showing 4 of 4PHP: 2023-03-02 02:31:28 [error X 1][C:\xampp\htdocs\elementor\wp-content\plugins\elementor-pro\modules\theme-builder\classes\conditions-manager.php::295] Uncaught Error: Call to a member function update_meta() on bool in C:\xampp\htdocs\elementor\wp-content\plugins\elementor-pro\modules\theme-builder\classes\conditions-manager.php:295
Stack trace:
#0 C:\xampp\htdocs\elementor\wp-content\plugins\elementor-pro\modules\theme-builder\classes\conditions-manager.php(168): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions(NULL, Array)
https://github.com/elementor/elementor/pull/1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
https://github.com/elementor/elementor/pull/2 C:\xampp\htdocs\elementor\wp-content\plugins\elementor\core\common\modules\ajax\module.php(175): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
https://github.com/elementor/elementor/pull/3 C:\xampp\htdocs\elementor\wp-includes\class-wp-hook.php(308): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
https://github.com/elementor/elementor/pull/4 C:\xampp\htdocs\elementor\wp-includes\class-wp-hook.php(332): WP_Hook->apply_filters('', Array)
https://github.com/elementor/elementor/pull/5 C:\xampp\htdocs\elemen [array (
'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-03-11 14:20:00 [error X 4][C:\xampp\htdocs\elementor\wp-content\plugins\elementor\modules\safe-mode\module.php::11] Maximum execution time of 30 seconds exceeded [array (
'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-03-17 21:02:19 [notice X 1][C:\xampp\htdocs\elementor\wp-content\plugins\elementor-pro\modules\theme-builder\classes\conditions-manager.php::168] Undefined index: editor_post_id [array (
'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-03-29 14:38:36 [notice X 3][C:\xampp\htdocs\elementor\wp-content\plugins\elementor\core\common\modules\ajax\module.php::175] Undefined index: data [array (
'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 6 of 6JS: 2023-03-03 20:14:54 [error X 2][http://localhost:80/elementor/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.11.2:3:719506] Cannot read properties of undefined (reading 'widgets_settings')
JS: 2023-03-04 12:28:29 [error X 10][http://localhost:80/elementor/wp-admin/load-scripts.php?c=1&loadchunk_0=underscore,jquery-core,jquery-migrate,backbone,jquery-ui-core,jquery-ui-mouse,wp-api-request,regenerator-runtime,wp-polyfill,wp-&loadchunk_1=hooks&ver=6.1.1:4:51824] Cannot read properties of undefined (reading 'replace')
JS: 2023-03-09 11:53:29 [error X 3][http://localhost:80/elementor/wp-content/plugins/elementor/assets/js/editor-modules.min.js?ver=3.11.2:2:14150] An invalid argument supplied as multiple control value [array (
'category' => 'InvalidElementData',
'tag' => 'Element undefined got as icon value. Expected array or object.',
)]
JS: 2023-03-19 21:43:38 [error X 2][http://localhost:80/elementor/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.11.5:3:1087291] Cannot read properties of null (reading 'getBoundingClientRect')
JS: 2023-03-29 10:08:23 [error X 2][http://localhost:80/elementor/wp-content/plugins/elementor-pro/assets/js/editor.min.js?ver=3.12.0:2:63837] Cannot read properties of undefined (reading 'createTemplate')
JS: 2023-03-29 10:27:09 [error X 40][http://localhost:80/elementor/wp-content/plugins/elementor/assets/js/df16c9d56464dd4f0800.bundle.min.js:2:7826] Cannot read properties of null (reading 'dataset')

== Elementor - Compatibility Tag ==

Elementor Pro: Incompatible
== Elementor Pro - Compatibility Tag ==

</details>

**Comment by nicholaszein** [comment] 2023-05-02 14:09
Hi @Michaelgimii,

Thank you for reaching out! 🙏 

### Please don't forget: 
- ☝️ **One Issue Per Thread:** If you are experiencing more than one bug, submit only **<ins>ONE ISSUE PER THREAD</ins>**, so we can properly track them and reference them without any confusion.

## ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
- **Issue A:** You forgot to define a `z-index` for the containers of both Header and Footer navigations. Keep in mind that `z-index` follows the cascade. Meaning that the elements at the end of the document have a higher `z-index` than the elements at the beginning of a document. If you don't specify a higher `z-index` for your header container, the footer container will appear above it and any element from inside of it, including in this case the Menu Cart widget content.
- **Issue B:** The same as issue **A**. Popups are rendered at the end of the document, right before the closing `</body>` tag. This means they have a higher `z-index` in relation to everything else. But there is a catch here, and I understand why you thought this was a bug. Popups by default receive a `z-index` of **`9999`**. This is on purpose, so they can always be on top of everything. 

### ✅ What you can do to solve your issue:
- **Issue A:** Check the video below:

https://user-images.githubusercontent.com/113993460/235689457-384a5f74-3785-4e7e-95c6-8e833337d87f.mp4

----
- **Issue B:** If you wish your Menu Cart to appear above Popups, please give to its **<ins>parent container</ins>** a `z-index` of **`10000`** or higher.


#### ℹ️ Just FYI, Sticky Containers receive a default `z-index` of `99`.

### 👍 For now, that's all we can help with. 

### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for support.

❔ If you have questions, or need guidance, help, or general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) The main Facebook group where all kinds of users come together to help each other.
- [Elementor Academy](https://elementor.com/academy) Learn everything you need to know about using Elementor.
- [Elementor Developers Documentation](https://developers.elementor.com/) Learn everything about our Developer-API.
- [Free Support Forum](https://wordpress.org/support/plugin/elementor) Get help on WordPress.org.

💎 If you have an active [Elementor Pro](https://elementor.com/pro) license you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Kind regards

**Closed by nicholaszein** 2023-05-02 14:09 UTC
Labels: bug, product/pro, component/woocommerce, component/popup, component/container, component/sticky, component/menu-cart
