### ISSUE TITLE
✔️ 🔗 🐞 Bug Report: Update button disabled after Copy and Paste Style (Duplicate of #19895) (Related to #20315, #20364, #20470) (ED-8548)

### ISSUE THREAD

**Issue by T-Mac31** [elementor/elementor#20637] opened 2022-12-07 05:41 UTC
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Aftre doing a copy and Paste Style, the Update button no longer works.

Uploading Elementor _ Clever Logger Versus AQ Box - Google Chrome 2022-12-07 15-59-13.mp4…

[system-info-cleverlogger.com-07-12-2022.txt](https://github.com/elementor/elementor/files/10173098/system-info-cleverlogger.com-07-12-2022.txt)

### Steps to reproduce

Update button works as normal

Copy any element

Go to another element and Paste Style

Update button no longer performs update

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

== Server Environment ==
	Operating System: Linux
	Software: LiteSpeed
	MySQL version: MariaDB Server v10.3.37
	PHP Version: 8.1.12
	PHP Memory Limit: 256M
	PHP Max Input Vars: 3000
	PHP Max Post Size: 128M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.1.1
	Site URL: https://cleverlogger.com
	Home URL: https://cleverlogger.com
	WP Multisite: No
	Max Upload Size: 128 MB
	Memory limit: 640M
	Max Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en-AU
	Timezone: Australia/Sydney
	Admin Email: web@onsolution.com.au
	Debug Mode: Inactive

== Theme ==
	Name: CleverLogger (Hello)
	Version: 1.0.1
	Author: Elementor Team
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.6.1
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: en_AU
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36

== Active Plugins ==
	Abandoned Cart Pro for WooCommerce
		Version: 8.22.1
		Author: Tyche Softwares

	Broken Link Checker
		Version: 1.11.21
		Author: WPMU DEV

	Cloudflare
		Version: 4.11.0
		Author: Cloudflare, Inc.

	Crocoblock Wizard
		Version: 1.1.0
		Author: Crocoblock

	Disable Emojis (GDPR friendly)
		Version: 1.7.4
		Author: Ryan Hellyer

	Elementor
		Version: 3.9.0
		Author: Elementor.com

	Elementor Pro
		Version: 3.9.0
		Author: Elementor.com

	Essential Addons for Elementor
		Version: 5.5.0
		Author: WPDeveloper

	Essential Addons for Elementor - Pro
		Version: 5.4.2
		Author: WPDeveloper

	Happy Elementor Addons
		Version: 3.7.2
		Author: weDevs

	Happy Elementor Addons Pro
		Version: 2.6.1
		Author: weDevs

	JetMenu
		Version: 2.2.4
		Author: Crocoblock

	JetSearch
		Version: 3.0.3
		Author: Crocoblock

	JSON Basic Authentication
		Version: 0.1
		Author: WordPress API Team

	MainWP Child
		Version: 4.3.0.1
		Author: MainWP

	Premium Addons for Elementor
		Version: 4.9.41
		Author: Leap13

	Premium Addons PRO
		Version: 2.8.17
		Author: Leap13

	Rank Math SEO
		Version: 1.0.103.1
		Author: Rank Math

	Rank Math SEO PRO
		Version: 3.0.25
		Author: Rank Math

	Super Browser Detector
		Version: 1.1
		Author: Louis Fico

	Super Forms - Drag &amp; Drop Form Builder
		Version: 6.3.312
		Author: feeling4design

	WooCommerce
		Version: 7.1.0
		Author: Automattic

	WooCommerce Conversion Tracking
		Version: 2.0.10
		Author: weDevs

	WooCommerce Dynamic Pricing &amp; Discounts
		Version: 2.4.5
		Author: RightPress

	WooCommerce MYOB Integration (OnSolution Customised)
		Version: 1.5-custom2
		Author: WooCommerce / OnSolution

	WooCommerce Price Based on Country (Basic)
		Version: 2.2.9
		Author: Oscar Gare

	WooCommerce Price Based on Country Pro Add-on
		Version: 2.22.4
		Author: Oscar Gare

	WooCommerce Stripe Gateway
		Version: 7.0.1
		Author: WooCommerce

	Wordfence Security
		Version: 7.8.0
		Author: Wordfence

	WPCode Lite
		Version: 2.0.4.4
		Author: WPCode

	WP Mail SMTP
		Version: 3.6.1
		Author: WPForms

	Yotpo Reviews for WooCommerce
		Version: 2.0.4
		Author: Paul Glushak (hxii)

== Elementor Experiments ==
	Optimized DOM Output: Active
	Improved Asset Loading: Active
	Improved CSS Loading: Active
	Inline Font Icons: Active
	Accessibility Improvements: Inactive by default
	Additional Custom Breakpoints: Inactive by default
	Import Export Website Kit: Active by default
	Hide native WordPress widgets from search results: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Inactive by default
	Default to New Theme Builder: Active by default
	Hello Theme Header & Footer: Inactive by default
	Landing Pages: Active by default
	Color Sampler: Active by default
	Favorite Widgets: Active by default
	Admin Top Bar: Active by default
	Lazy Load Background Images: Inactive by default
	Save as Default: Active by default
	Page Transitions: Active by default
	Notes: Active by default
	Loop: Inactive by default
	Form Submissions: Active by default
	Scroll Snap: Active by default

== Log ==
	
JS: showing 7 of 7JS: 2022-10-30 23:42:53 [error X 2][https://cleverlogger.com/wp-content/plugins/elementor/assets/js/editor-modules.min.js?ver=3.8.0:2:18481] property \&quot;_ha_condition_key\&quot; is non-configurable and can\&#039;t be deleted 
JS: 2022-10-30 23:46:08 [error X 6][https://cleverlogger.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.8.0:3:367744] B[0] is undefined 
JS: 2022-11-08 04:55:39 [error X 2][https://cleverlogger.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.8.0:3:768952] Cannot read properties of undefined (reading \&#039;toLowerCase\&#039;) 
JS: 2022-11-09 22:11:58 [error X 11][https://cleverlogger.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.8.0:3:367749] Cannot read properties of undefined (reading \&#039;controls\&#039;) 
JS: 2022-11-15 02:30:26 [error X 5][https://cleverlogger.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.8.1:3:1061530] Cannot read properties of null (reading \&#039;getBoundingClientRect\&#039;) 
JS: 2022-11-21 00:04:30 [error X 3][https://cleverlogger.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:768] Cannot read properties of null (reading \&#039;cid\&#039;) 
JS: 2022-11-24 22:43:57 [error X 2][https://cleverlogger.com/wp-admin/load-scripts.php?c=1&loadchunk_0=regenerator-runtime,wp-polyfill,wp-hooks,jquery-core,jquery-migrate,utils,moxiejs,plupload&ver=1b10ac1e283fee1c1bb1ed093e5a4728:6:31703] elementor_new_template_form_controls is not defined 

Log: showing 20 of 282022-11-14 12:35:26 [info] Elementor/Upgrades - _on_each_version Finished 
2022-11-14 12:35:26 [info] Elementor/Upgrades - _v_3_8_0_fix_php8_image_custom_size Start  
2022-11-14 12:35:26 [info] Elementor/Upgrades - _v_3_8_0_fix_php8_image_custom_size Finished 
2022-11-14 12:35:26 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.8.0',
  'to' => '3.8.1',
)]
2022-11-22 11:58:15 [info] elementor-pro::elementor_pro_updater Started 
2022-11-22 11:58:15 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-11-22 11:58:15 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-11-22 11:58:15 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.8.1',
  'to' => '3.8.2',
)]
2022-12-07 10:01:47 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.8.1',
  'to' => '3.9.0',
)]
2022-12-07 10:01:48 [info] elementor::elementor_updater Started 
2022-12-07 10:01:48 [info] Elementor/Upgrades - _on_each_version Start  
2022-12-07 10:01:48 [info] Elementor/Upgrades - _on_each_version Finished 
2022-12-07 10:01:48 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.8.1',
  'to' => '3.9.0',
)]
2022-12-07 10:01:49 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.8.2',
  'to' => '3.9.0',
)]
2022-12-07 10:01:50 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.8.1',
  'to' => '3.9.0',
)]
2022-12-07 10:01:51 [info] elementor-pro::elementor_pro_updater Started 
2022-12-07 10:01:51 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-12-07 10:01:51 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-12-07 10:01:51 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.8.2',
  'to' => '3.9.0',
)]
2022-12-07 10:01:53 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.8.2',
  'to' => '3.9.0',
)]

PHP: showing 7 of 7PHP: 2022-11-08 10:51:39 [warning X 9675][/home/web5onso/cleverlogger.com/wp-content/plugins/elementor-pro/modules/nav-menu/widgets/nav-menu.php::1482] Trying to access array offset on value of type null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-11-08 10:54:24 [notice X 196][/home/web5onso/cleverlogger.com/wp-content/plugins/elementor-pro/modules/woocommerce/module.php::553] parse_str(): Passing null to parameter #1 ($string) of type string is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-11-11 17:56:35 [notice X 29][/home/web5onso/cleverlogger.com/wp-content/plugins/elementor-pro/modules/custom-css/module.php::76] trim(): Passing null to parameter #1 ($string) of type string is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /home/web5onso/cleverlogger.com/wp-content/plugins/elementor-pro/modules/custom-css/module.php(76): class type trim()
#2: /home/web5onso/cleverlogger.com/wp-includes/class-wp-hook.php(308): ElementorPro\Modules\CustomCss\Module -> add_page_settings_css()
#3: /home/web5onso/cleverlogger.com/wp-includes/class-wp-hook.php(332): WP_Hook -> apply_filters()
#4: /home/web5onso/cleverlogger.com/wp-includes/plugin.php(517): WP_Hook -> do_action()
',
)]
PHP: 2022-11-14 12:40:20 [notice X 25][/home/web5onso/cleverlogger.com/wp-content/plugins/elementor-pro/core/database/model-base.php::135] Return type of ElementorPro\Core\Database\Model_Base::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-11-15 10:21:10 [notice X 70][/home/web5onso/cleverlogger.com/wp-content/plugins/elementor-pro/core/utils/collection.php::75] Return type of ElementorPro\Core\Utils\Collection::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-11-25 09:51:51 [notice X 63][/home/web5onso/cleverlogger.com/wp-content/plugins/elementor-pro/modules/custom-css/module.php::76] trim(): Passing null to parameter #1 ($string) of type string is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-12-07 10:06:11 [notice X 127][/home/web5onso/cleverlogger.com/wp-content/plugins/elementor-pro/core/database/model-base.php::135] Return type of ElementorPro\Core\Database\Model_Base::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice [array (
  'trace' => '
#0: /home/web5onso/cleverlogger.com/wp-content/plugins/elementor-pro/core/database/model-base.php(10): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /home/web5onso/cleverlogger.com/wp-content/plugins/elementor-pro/plugin.php(154): class type include()array (
  0 => '/home/web5onso/cleverlogger.com/wp-content/plugins/elementor-pro/core/database/model-base.php',
)
#2: /home/web5onso/cleverlogger.com/wp-content/plugins/elementor-pro/modules/notes/database/models/note.php(18): ElementorPro\Plugin -> autoload()
#3: /home/web5onso/cleverlogger.com/wp-content/plugins/elementor-pro/plugin.php(154): class type include()array (
  0 => '/home/web5onso/cleverlogger.com/wp-content/plugins/elementor-pro/modules/notes/database/models/note.php',
)
#4: /home/web5onso/cleverlogger.com/wp-content/plugins/elementor-pro/modules/notes/data/controller.php(243): ElementorPro\Plugin -> autoload()
',
)]

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Incompatible
	Essential Addons for Elementor: Incompatible
	Essential Addons for Elementor - Pro: Incompatible
	Happy Elementor Addons: Incompatible
	Happy Elementor Addons Pro: Incompatible
	Premium Addons for Elementor: Incompatible
	Premium Addons PRO: Incompatible

== Elementor Pro - Compatibility Tag ==
	
	Essential Addons for Elementor: Incompatible
	Essential Addons for Elementor - Pro: Incompatible
	Happy Elementor Addons: Incompatible
	Happy Elementor Addons Pro: Incompatible
	Premium Addons for Elementor: Incompatible
	Premium Addons PRO: Incompatible

**Comment by nicholaszein** [comment] 2022-12-07 11:22
Hello @T-Mac31!

Thank you for your submission! 🙏 

### 🔗 This issue is a Duplicate of #19895

Which is on the same subject. 

Feel free to continue the conversation there. 😉 

### ✔️ Please, in the future, remember to check if there isn't an issue similar to yours already opened. 

Best regards,

Nick

**Comment by nicholaszein** [comment] 2022-12-15 18:25
Hello there @T-Mac31!

We have great news! 🙌 

### 📢 We're happy to announce that the issue you raised was resolved in Elementor **v3.9.1**! 🥳 

✔️ Feel free to check it out and update your plugin to the new version!

Cheers 🥂

**Closed by nicholaszein** 2022-12-15 18:25 UTC
Labels: bug, type/developer-api, component/editor
