### ISSUE TITLE
add ability to create custom product loop 

### ISSUE THREAD

**Issue by promocot** [elementor/elementor#12051] opened 2020-08-06 17:37 UTC
Like in Elementor Custom Skin, but in product grid the ability to customize various animations for the button when hovering over the product, such a solution is available in crockoblock

**Comment by shilo-ey** [comment] 2020-08-06 17:38
duplicate of #4440

**Closed by shilo-ey** 2020-08-06 17:38 UTC

**Comment by promocot** [comment] 2020-08-06 17:41
> duplicate of #4440

not, my solution differ

**Comment by nicholaszein** [comment] 2023-08-01 20:54
Hello there!

We have great news! 🙌 

### 📢 We're happy to announce the new Loop Builder released with Elementor Pro v3.8.0! 🥳 

With the new Loop Grid widget, you can customize your post listings with custom templates! 💪 
Drag & Drop widgets to create complex designs, fine-tune your Loop Grid layout, add alternate templates, and much more!

This is just the first phase. More customization is coming!

Check out the article here: https://elementor.com/help/loop-grid/

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
