### ISSUE TITLE
🚀 Feature Request: Multiple Site Settings

### ISSUE THREAD

**Issue by AndreasH08** [elementor/elementor#18468] opened 2022-04-20 09:49 UTC
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

Less custom CSS

### Describe the solution you'd like

An option to be able to choose between different site settings on a per-page level, that way you can have to choose multiple standard max-width, multiple global fonts, colors, and other such things.

### Describe alternatives you've considered

A ton of custom CSS, that I'll need to keep track off :/

### Additional context

I'm asking for this because the website has some old standards that we're phasing out, but until we've stopped using them completely we can't remove them from the site settings, so having the option to simply create an additional one, would make my life a lot easier :D

**Comment by pauserratgutierrez** [comment] 2022-04-25 09:29
#17670

**Comment by rami-elementor** [comment] 2022-04-25 09:46
Duplicate of #17670

**Closed by rami-elementor** 2022-04-25 09:46 UTC
Labels: request/feature, component/site-settings, type/site-settings
