### ISSUE TITLE
✔️ 🔗 🚀 Feature Request: Google Fonts GDPR - Automatic font download and swap (Related to #17913, #19071)

### ISSUE THREAD

**Issue by Henry00IS** [elementor/elementor#20312] opened 2022-11-07 12:48 UTC
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

I built and maintain several customer websites, they use a lot of templates and Google Fonts. Unfortunately they are all getting into law suits because the Google Fonts are loaded from the google server. The lawsuit claims that a victim got their IP address leaked. I noticed this problem has been mentioned here and there on GitHub already.

### Describe the solution you'd like

It would be nice if Elementor simply had a font cache. When it outputs a template or page and the cache doesn't recognize a font that it uses, it downloads the font from the Google server and then hosts it locally. The user doesn't even have to be aware of this swap- or it could be a setting. Either way, because it then uses the downloaded google font and hosts it directly, that would instantly solve the problem. If done elegantly you can make almost every website using Elementor GDPR compliant in a single update.

My first thought was that the Google Font Loading Method "Swap" was this feature already. But unfortunately that is not the case.

### Describe alternatives you've considered

It can be solved by adding a custom font, but then I have to go in all of the websites I ever built, all of the templates, and hope that I find all of the places where I used google fonts. This will take me ages.

**Comment by nicholaszein** [comment] 2022-11-14 04:59
Hello @Henry00IS!

Thank you for your submission! 🙏 

### 🔗 This issue is a Duplicate of #17913 and #19071.

Which is on the same subject. 

For this reason, I'm closing this issue and 🔃 **Merging** it with the original, so we can have all the discussions in one location, and deal with it more efficiently.

Feel free to continue the conversation there. 😉 

### ✔️ Please, in the future, remember to check if there isn't an issue similar to yours already opened. 

Best regards,

Nick

**Comment by nicholaszein** [comment] 2023-01-11 16:17
Hello there!

We have great news! 🙌 

### 📢 We're happy to announce that this request was partially solved with the release of Elementor **v3.10**! 🥳 

You can now completely disable Google Fonts from within your Dashboard > Elementor > Settings > Advanced page, as explained [here](https://developers.elementor.com/elementor-3-10-beta/).

For the time being, we have no plans to download Google Fonts and store them locally. If you need that functionality you can use one of the many performance optimization plugins that have this feature built-in, or use the [free OMGF plugin](https://wordpress.org/plugins/host-webfonts-local/).

✔️ Please feel free to check it out and update your plugin to the new version!

Cheers 🥂

**Closed by nicholaszein** 2023-01-11 16:17 UTC
Labels: request/integration, type/performance, component/custom-fonts, type/privacy
