### ISSUE TITLE
Elementor Custom Color

### ISSUE THREAD

**Issue by ssavir** [elementor/elementor#9519] opened 2019-11-07 09:12 UTC
- Before opening a new sheet, please look for duplicate issues to prevent a duplicate feature request from opening. If an existing application is already open, please leave a comment. ->

## early conditions
<! - Completed items for marks with [x] ->

- [X] I searched for similar feature requests on both open and closed tickets and could not find duplicates.
- [X] The feature is still missing in the latest stable version of Elementor (Elementor Pro.)

** What problem does your feature request resolve? Please describe. **

My problem would be to solve the problem of designers and other web builders, the ability to use dynamic ACF fields to select and determine color similar to image background

** Describe the solution you want **
The solution is simple and clear to solve problems for web designers and builders who can build a UI for the site owner and can without affecting the element design color and not spoil the design of the page.

** Describe alternatives you considered **
I have no idea to solve this, it would be of great help if you could add it to the Elementor

** Additional context **

Hi champions,

Asking where possible to set a background / font color ... because the selection is dynamic and that the color value can be read from the ACF field similar to a photo or background selection.

Thanks

**Comment by bainternet** [comment] 2019-11-09 18:08
Duplicate of #6485

**Comment by bainternet** [comment] 2019-11-09 18:08
Thanks for the feedback,
Please follow guidelines for opening a new [feature request](https://github.com/pojome/elementor/issues/new?template=Feature_request.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Description and examples.

**Closed by bainternet** 2019-11-09 18:08 UTC
