### ISSUE TITLE
Forms arrive blank

### ISSUE THREAD

**Issue by alonep1** [elementor/elementor#7651] opened 2019-03-28 09:52 UTC
## Prerequisites

- [ x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x ] The issue still exists against the latest stable version of Elementor.

## Description
elemntor forms sends a blank form (both to mail and database), tried deactivating all plugins except ele and elepro and still didnt manage to get it to work, had to downgrade epro to version 2.4.8

## Steps to reproduce

upgrade elementor to the latest version

## Isolating the problem

- [x ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ x] This bug happens with a default WordPress theme active.
- [x ] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
					
== Server Environment ==
	Operating System: Linux
	Software: LiteSpeed
	MySQL version: MariaDB Server v5.6.42-84.2
	PHP Version: 7.0.33
	PHP Max Input Vars: 10240
	PHP Max Post Size: 24M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.1.1
	Site URL: https://www.avitauber.com
	Home URL: https://www.avitauber.com
	WP Multisite: No
	Max Upload Size: 24 MB
	Memory limit: 512M
	Permalink Structure: /%postname%/
	Language: he-IL
	Timezone: Asia/Jerusalem
	Debug Mode: Inactive

== Theme ==
	Name: OceanWP
	Version: 1.6.4
	Author: Nick
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: he_IL
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36

== Active Plugins ==
	Click to Chat for WhatsApp
		Version: 1.6
		Author: HoliThemes

	Contact Form DB
		Version: 2.10.32
		Author: Michael Simpson

	Duplicate Post
		Version: 3.2.2
		Author: Enrico Battocchi

	Elementor
		Version: 2.5.10
		Author: Elementor.com

	Elementor Addon Elements
		Version: 1.4
		Author: WebTechStreet

	Elementor Pro
		Version: 2.4.8
		Author: Elementor.com

	Insert Headers and Footers
		Version: 1.4.3
		Author: WPBeginner

	ManageWP - Worker
		Version: 4.7.7
		Author: GoDaddy

	Ocean Extra
		Version: 1.5.3
		Author: OceanWP

	TinyMCE Advanced
		Version: 5.1.0
		Author: Andrew Ozz

	WeSafe by uPress
		Version: 1.7.2
		Author: uPress

	Yoast SEO
		Version: 10.0.1
		Author: Team Yoast


== Must-Use Plugins ==
	ManageWP - Worker Loader
		Version: 
		Author: GoDaddy


== Log ==
	: 
Log: showing 20 of 222019-01-22 08:06:55 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'אלמנטור פרו',
  'from' => '2.3.1',
  'to' => '2.4.0',
)]
2019-01-28 14:47:24 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'אלמנטור',
  'from' => '2.4.3',
  'to' => '2.4.4',
)]
2019-01-31 15:28:24 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'אלמנטור',
  'from' => '2.4.4',
  'to' => '2.4.5',
)]
2019-02-11 17:58:42 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'אלמנטור',
  'from' => '2.4.5',
  'to' => '2.4.6',
)]
2019-02-11 18:00:12 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'אלמנטור פרו',
  'from' => '2.4.0',
  'to' => '2.4.4',
)]
2019-02-20 08:08:48 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'אלמנטור',
  'from' => '2.4.6',
  'to' => '2.4.7',
)]
2019-02-24 10:08:55 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'אלמנטור פרו',
  'from' => '2.4.4',
  'to' => '2.4.5',
)]
2019-03-04 15:43:55 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'אלמנטור',
  'from' => '2.4.7',
  'to' => '2.5.0',
)]
2019-03-05 08:19:35 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'אלמנטור',
  'from' => '2.5.0',
  'to' => '2.5.1',
)]
2019-03-05 08:19:45 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'אלמנטור פרו',
  'from' => '2.4.5',
  'to' => '2.4.6',
)]
2019-03-06 12:02:40 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'אלמנטור',
  'from' => '2.5.1',
  'to' => '2.5.2',
)]
2019-03-07 13:07:09 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'אלמנטור',
  'from' => '2.5.2',
  'to' => '2.5.3',
)]
2019-03-10 09:36:42 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'אלמנטור פרו',
  'from' => '2.4.6',
  'to' => '2.4.7',
)]
2019-03-11 12:17:23 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'אלמנטור',
  'from' => '2.5.3',
  'to' => '2.5.4',
)]
2019-03-12 08:39:27 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'אלמנטור',
  'from' => '2.5.4',
  'to' => '2.5.5',
)]
2019-03-12 15:07:31 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'אלמנטור פרו',
  'from' => '2.4.7',
  'to' => '2.4.8',
)]
2019-03-17 09:57:40 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'אלמנטור',
  'from' => '2.5.5',
  'to' => '2.5.8',
)]
2019-03-19 11:11:53 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'אלמנטור',
  'from' => '2.5.8',
  'to' => '2.5.9',
)]
2019-03-28 09:46:58 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'אלמנטור',
  'from' => '2.5.9',
  'to' => '2.5.10',
)]
2019-03-28 11:33:28 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'אלמנטור פרו',
  'from' => '2.4.8',
  'to' => '2.5.2',
)]

JS: showing 1 of 1JS: 2019-01-22 08:03:28 [error X 3][https://www.avitauber.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.4.3:2:65076] ‏‏הארגומנט אינו חוקי. 

PHP: showing 1 of 1PHP: 2019-03-07 13:07:20 [notice X 9][/home/avitauber/public_html/wp-content/plugins/elementor/includes/base/controls-stack.php::714] Undefined index: type [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]


				
```
</details>

**Comment by shilo-ey** [comment] 2019-03-28 10:47
Hi @alonep1 

We can't reproduce your issue.

Please contact our support at support @elementor.com for guidance in resolving this issue and mention that you were directed by me and reference this issue.

thanks.

**Comment by shilo-ey** [comment] 2019-03-28 11:44
Hi @alonep1 

After reviewing this issue again, we have found that this issue might be caused by missing ID in the form fields.

Can you please verify that for us?

Thanks

**Comment by alonep1** [comment] 2019-03-28 11:53
@shilo-ey 
Seems like that was the issue, For some reason then the new version of elepro is deleting the forms id

**Comment by zorca** [comment] 2019-03-28 12:25
I confirm this bug in Pro 2.5.1

**Comment by mihdan** [comment] 2019-03-28 12:32
I confirm this bug in Pro 2.5.1.

**Comment by shilo-ey** [comment] 2019-03-28 12:40
Thanks for reporting.

We will address this issue soon and release a patch.

Please follow this thread for updates.

Thanks!

**Comment by thimfy** [comment] 2019-03-30 07:48
Do not purchase elementor or any item from creator of it, no support nothing just kind of shit only.

**Comment by zorca** [comment] 2019-03-30 08:07
> 
> 
> Do not purchase elementor or any item from creator of it, no support nothing just kind of shit only.

Very toxic remark from a newly created fake account.

**Comment by thimfy** [comment] 2019-03-30 09:13
Did you know about fontawesome issue on elementor and how they are doing about it, i have purchased pro and now this is what i am getting and same all.

**Comment by alonep1** [comment] 2019-03-31 10:31
@shilo-ey any update?
this is a major bug with alot of my costumers websites

**Comment by shilo-ey** [comment] 2019-03-31 14:37
This issue has been fixed in Elementor Pro v2.5.3

Feel free to update!

**Closed by shilo-ey** 2019-03-31 14:37 UTC
Labels: bug, status/merged

**Comment by knireis** [comment] 2019-04-01 09:10
I am on 2.5.3, but this issue still persists

**Comment by shilo-ey** [comment] 2019-04-01 09:35
@knireis 

Please contact our support at support @elementor.com for guidance in resolving this issue and **mention that you were directed by me and reference this issue.**

When you contact the support please provide as many details as possible (including credentials for logging in to your environment, pages that are affected and description of the desired behavior)

Thanks.

**Comment by Talco100** [comment] 2019-04-07 05:01
Same problem here, everything is updated.
Please help :-|

**Comment by bertoUK** [comment] 2019-05-11 20:15
Has this been fixed as emails were still coming through blank despite upgrading. Works now that I have manually added ids to the form fields.

**Comment by anniemnz** [comment] 2019-05-19 21:10
What are the manual id's that you added to the form?

**Comment by bertoUK** [comment] 2019-05-19 21:33
You can add any ID you want but best to use the field name as a reference.

**Comment by Oddlaw** [comment] 2019-06-19 08:22
To bad I have the same problem. Used a standard elementor mail form but, when sent all the fields are empty. Using version 2.5.1.6. After downgrading to 2.4.7 the email form is sent successful with all the information in the fields.

**Comment by oferkeidar** [comment] 2019-06-26 15:01
I'm having the same problem.
I tried adding IDs to the form fields and also tried to use the fields' specific shortcodes instead of [all-fields].
Elementor 2.5.16 // Elemntor Pro 2.5.9

**Comment by ouzdohan** [comment] 2019-07-03 06:03
Using latest WP and Elementor pro as of today.

Once in a while when Wordpress updates I get this problem (blank forms) on some of the sites I've developed. It makes you look bad in your clients eyes. It's bad for business too - time wasted to fix the problem.

I've decided that I don't want to depend on Elementor for forms, simply unreliable. 

Now (and will do for all projects) using Ninja Forms to do the job. If you decide on Ninja you might want to add some css to customize it. 
A bit Upset.

**Comment by samacker77** [comment] 2019-07-17 19:36
The bug is still there.

**Comment by DiXeRpl** [comment] 2019-08-16 08:46
Mine situation is Elementor 2.6.8 and Elementor Pro 2.6.2, Wordpress 5.2.2.
The same issue with blank forms in email message after submit button on webpage.
 
@samacker77 
Thanks a lot!  Yours solution works great and is 100% what I needed.

**Comment by shwnhll** [comment] 2021-06-14 01:09
I know this is closed, but this same problem happened recently on my site. The same fix @samacker77 had works still. 

My question - is there a way to view these messages although the information is blank in email and inside of the "submissions" tab of Elementor?
