### ISSUE TITLE
✅ 🔗 🐞 Image Carousel Not Showing Image Captions or Descriptions (Duplicate of #28946)

### ISSUE THREAD

**Issue by LeadingEdges** [elementor/elementor#29001] opened 2024-10-16 15:20 UTC
### Prerequisites

- [X] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [X] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

After updating from 3.24.3 to 3.24.4, the image captions disappeared, as the caption code was absent from all of my image carousels. I tried switching to the image description, but it did not display either. NOTE: The image caption IS shown when logged in as an admin.  I had to roll back the Pro version to 3.24.3 and the base version to 3.24.6 to get the captions to display. 

### Steps to reproduce

1. Use pro version 3.24.3 and base version 3.24.6
2. insert code into an image's caption field. IE   
```html
<div class="my-div-class">
        <h1>My Title Here</h1>
        <p>My subtitle here</p>
        <a href="mywebsite,.com"> Learn More</a>
    </div>
```
3. Set the Image Carousel Caption field to "Caption."
4. Update to pro version 3.24.4 and the base version to 3.24.7; neither the caption nor its code is present. 

### Expected behavior

The expected behavior is for the image caption to be displayed. 

### Isolating the problem

- [ ] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [ ] This bug happens with the Hello Elementor theme active.
- [X] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

<details>
<summary>Click to reveal</summary>

````txt


== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MySQL Community Server - GPL v8.0.40
	PHP Version: 7.4.33
	PHP Memory Limit: -1
	PHP Max Input Vars: 1000
	PHP Max Post Size: 35M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.6.1
	Site URL: https://www.yourcnb.com
	Home URL: https://www.yourcnb.com
	WP Multisite: No
	Max Upload Size: 32 MB
	Memory limit: -1
	Max Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en_US
	Timezone: America/Chicago
	Debug Mode: Inactive

== Theme ==
	Name: Astra Child
	Version: 4.4.1.1699518067
	Author: Brainstorm Force
	Child Theme: Yes
	Parent Theme Name: Astra
	Parent Theme Version: 4.8.0
	Parent Theme Author: Brainstorm Force

== User ==
	Role: administrator
	WP Profile lang: en-US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36

== Active Plugins ==
	Admin Menu Editor Pro
		Version: 2.26.1
		Author: Janis Elsts

	Advanced Custom Fields PRO
		Version: 6.3.9
		Author: WP Engine

	Breadcrumb
		Version: 1.5.46
		Author: PickPlugins

	CatFolders Pro - WP Media Folders
		Version: 2.4.6
		Author: CatFolders

	Child Theme Configurator
		Version: 2.6.6
		Author: Lilaea Media

	Classic Editor
		Version: 1.6.5
		Author: WordPress Contributors

	Contact Form 7
		Version: 5.9.8
		Author: Takayuki Miyoshi

	CookieYes | GDPR Cookie Consent
		Version: 3.2.7
		Author: CookieYes

	Copy &amp; Delete Posts
		Version: 1.4.9
		Author: Inisev

	Custom Fonts
		Version: 2.1.7
		Author: Brainstorm Force

	Elementor
		Version: 3.24.5
		Author: Elementor.com

	Elementor Pro
		Version: 3.24.3
		Author: Elementor.com

	Font Awesome
		Version: 4.5.0
		Author: Font Awesome

	Formidable Forms
		Version: 6.15
		Author: Strategy11 Form Builder Team

	Formidable Forms Pro
		Version: 6.15.1
		Author: Strategy11

	Formidable PDFs
		Version: 2.0.4
		Author: Strategy11

	Max Mega Menu
		Version: 3.3.2
		Author: megamenu.com

	Popup Maker
		Version: 1.20.2
		Author: Popup Maker

	Post Grid Elementor Addon
		Version: 2.0.18
		Author: WP Hait

	Post Grid Gutenberg Blocks
		Version: 2.2.96
		Author: PickPlugins

	Redirection
		Version: 5.5.0
		Author: John Godley

	Simple Custom CSS and JS
		Version: 3.48
		Author: SilkyPress.com

	SVG Support
		Version: 2.5.8
		Author: Benbodhi

	Web Accessibility by accessiBe
		Version: 1.19
		Author: accessiBe

	WPCode Lite
		Version: 2.2.2
		Author: WPCode

	WP Mail SMTP Pro
		Version: 4.1.1
		Author: WP Mail SMTP

	Yoast SEO
		Version: 23.6
		Author: Team Yoast

	YouTube WordPress Plugin by Embed Plus
		Version: 14.2.1.2
		Author: Embed Plus YouTube Plugin Team


== Elements Usage ==
	
	container : 12
		accordion : 1
		button : 15
		container : 23
		divider : 1
		heading : 16
		icon : 3
		image : 11
		shortcode : 1
		text-editor : 14
	page : 71
		button : 135
		container : 455
		counter : 6
		divider : 62
		heading : 155
		html : 16
		icon : 13
		icon-list : 6
		image : 75
		image-box : 45
		image-carousel : 38
		progress : 6
		shortcode : 44
		spacer : 20
		text-editor : 283
		video : 13
	section : 3
		container : 10
		heading : 4
		html : 4
	wp-post : 2
		button : 6
		container : 20
		divider : 2
		heading : 6
		html : 1
		icon : 2
		icon-list : 1
		image : 4
		image-carousel : 4
		text-editor : 5
	wp-page : 46
		button : 19
		container : 271
		counter : 3
		divider : 44
		heading : 94
		html : 13
		icon : 7
		icon-box : 2
		icon-list : 8
		image : 69
		image-carousel : 6
		nested-accordion : 1
		progress : 3
		shortcode : 43
		spacer : 4
		text-editor : 168
		video : 6


== Settings ==
	
	cpt_support: post, page, e-landing-page, articles___insights, business_banking, cnb_news, financial-education, i_want_to, location, mortgages, personal_banking_, resource-toolbox, the_power_of_local, wealth_management, our_teams, post_grid_template
	allow_tracking: yes
	unfiltered_files_upload: 1
	font_display: swap


== Features ==
	Custom Fonts: 0
	Custom Icons: 0

== Integrations ==
	


== Elementor Experiments ==
	Improved CSS Loading: Inactive by default
	Inline Font Icons: Active
	Additional Custom Breakpoints: Active
	Flexbox Container: Active
	Grid Container: Active
	Upgrade Swiper Library: Active
	Nested Elements Performance: Active by default
	Optimized Control Loading: Inactive
	Optimized Markup: Inactive by default
	Conditionally load Swiper CSS files: Inactive by default
	Plugin Onboarding: Active by default
	Default to New Theme Builder: Active
	Elementor Home Screen: Active by default
	Build with AI: Active
	Landing Pages: Active
	Launchpad Checklist: Inactive by default
	Nested Elements: Active
	Editor Top Bar: Inactive by default
	Element Caching: Inactive
	Link In Bio: Active by default
	Floating Buttons: Active by default
	Elementor Editor Events: Inactive by default
	Atomic Widgets: Inactive by default
	Display Conditions: Active by default
	Form Submissions: Active
	Menu: Active


== Log ==
	
Log: showing 20 of 372024-09-19 15:08:41 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.23.4',
  'to' => '3.24.3',
)]
2024-10-02 15:52:04 [info] elementor::elementor_updater Started 
2024-10-02 15:52:04 [info] Elementor/Upgrades - _on_each_version Start  
2024-10-02 15:52:05 [info] Elementor/Upgrades - _on_each_version Finished 
2024-10-02 15:52:05 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.24.3',
  'to' => '3.24.4',
)]
2024-10-08 01:50:26 [info] elementor::elementor_updater Started 
2024-10-08 01:50:26 [info] Elementor/Upgrades - _on_each_version Start  
2024-10-08 01:50:27 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.24.4',
  'to' => '3.24.5',
)]
2024-10-08 01:50:29 [info] Elementor/Upgrades - _on_each_version Finished 
2024-10-08 01:50:29 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.24.4',
  'to' => '3.24.5',
)]
2024-10-08 01:50:30 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.24.4',
  'to' => '3.24.5',
)]
2024-10-16 09:12:43 [info] elementor::elementor_updater Started 
2024-10-16 09:12:43 [info] Elementor/Upgrades - _on_each_version Start  
2024-10-16 09:12:44 [info] Elementor/Upgrades - _on_each_version Finished 
2024-10-16 09:12:44 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.24.5',
  'to' => '3.24.7',
)]
2024-10-16 09:24:32 [info] elementor-pro::elementor_pro_updater Started 
2024-10-16 09:24:32 [info] Elementor Pro/Upgrades - _on_each_version Start  
2024-10-16 09:24:32 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2024-10-16 09:24:32 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.23.3',
  'to' => '3.24.4',
)]
2024-10-16 09:24:32 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.23.3',
  'to' => '3.24.4',
)]

PHP: showing 4 of 4PHP: 2024-06-17 03:19:18 [error X 3][../wp-content/plugins/elementor/data/v2/base/controller.php::227] Uncaught Elementor\Data\V2\Base\Exceptions\WP_Error_Exception: Method &#039;WP_REST_Controller::get_item_permissions_check&#039; not implemented. Must be overridden in subclass. in ../wp-content/plugins/elementor/data/v2/base/controller.php:227
Stack trace:
#0 ../wp-content/plugins/elementor/data/v2/base/base-route.php(105): Elementor\Data\V2\Base\Controller-&gt;get_permission_callback(Object(WP_REST_Request))
#1 ../wp-content/plugins/elementor/data/v2/base/base-route.php(242): Elementor\Data\V2\Base\Base_Route-&gt;get_permission_callback(Object(WP_REST_Request))
#2 ../wp-includes/rest-api/class-wp-rest-server.php(1197): Elementor\Data\V2\Base\Base_Route-&gt;Elementor\Data\V2\Base\{closure}(Object(WP_REST_Request))
#3 ../wp-includes/rest-api/class-wp-rest-server.php(1063): WP_REST_Server-&gt;respond_to_request(Object(WP_REST_Request), &#039;/elementor/v1/f...&#039;, Array, NULL)
#4 /home/wpdevyourcnb/pu [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-10-16 09:24:32 [warning X 1][../wp-content/plugins/elementor/core/files/manager.php::113] unlink(../wp-content/uploads/elementor/css/custom-pro-widget-video-playlist.min.css): No such file or directory [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-10-16 09:24:35 [warning X 1][../wp-content/plugins/elementor/core/files/manager.php::113] unlink(../wp-content/uploads/elementor/css/post-9068.css): No such file or directory [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-10-16 10:01:35 [notice X 1][../wp-content/plugins/elementor/core/page-assets/data-managers/font-icon-svg/font-awesome.php::50] Trying to access array offset on value of type null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 2 of 2JS: 2024-07-23 16:06:19 [error X 6][../wp-content/plugins/elementor/assets/js/frontend-modules.min.js?ver=3.21.8:2:10586] Cannot read properties of undefined (reading &#039;autoplay&#039;) 
JS: 2024-09-18 19:01:21 [error X 4][../wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.23.4:3:663451] Cannot read properties of undefined (reading &#039;isDesignable&#039;) 



== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatibility not specified
	Post Grid Elementor Addon: Compatibility not specified

== Elementor Pro - Compatibility Tag ==

````

</details>

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by BouquetAntoine** [comment] 2024-10-16 21:12
Duplicate of https://github.com/elementor/elementor/issues/28946

**Closed** 2024-10-29 18:48 UTC
Labels: bug, status/merged, type/content-management, solved, mod*, widget/image-carousel*, duplicate
