### ISSUE TITLE
🐞 Bug report: Typo in Elementor (free) plugin prompt to install Elementor Pro plugin

### ISSUE THREAD

**Issue by deepwaterpixel** [elementor/elementor#19104] opened 2022-07-07 01:52 UTC
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

When I am prompted to install Elementor Pro on the free version of the plugin, there is a typo:

>Import **you** Elementor Pro plugin file

Should be:

>Import _your_ Elementor Pro plugin file

### Steps to reproduce

1. Install Elementor free
2. During the install process, click the "I already have Elementor Pro" option
3. See the popup window with typo, as shown below
![Screen Shot 2022-07-06 at 8 48 37 PM](https://user-images.githubusercontent.com/54284392/177673089-e76bddc3-8dc1-4b36-ba94-e3475401ef92.png)

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

Not Relevant

**Comment by rami-elementor** [comment] 2022-07-11 06:59
Hi @deepwaterpixel ,

Thank you for your feedback. We’re happy to say that the issue is resolved in Elementor 3.7.0

Regards,

**Comment by shilo-ey** [comment] 2022-08-08 08:31
Hey,

This issue has been resolved in Elementor v3.7.0

Feel free to update

Thanks!

**Closed by shilo-ey** 2022-08-08 08:31 UTC
Labels: bug, status/merged
