### ISSUE TITLE
issue with resizing page at 767px

### ISSUE THREAD

**Issue by wizard2000** [elementor/elementor#12413] opened 2020-09-04 14:35 UTC
hi everyone 
i've a problem which is:
when i resize my browser to 767px width, responsiveness all my columns is gone (for example columns i hide them in tablet mode is shown width of width of sections change  and many other things )
i've notice that in inspect mode of my chrome at that exact pixel, one attribute "data-elementor-device-mode" in body tag is set to "none" in other pixels  everything is fine ant that attribute changes to  desktop, tablet and mobile but in 767 pixel width 
i changed breakpoints in setting but nothing happens
i used elementor v3.0.1 pro

**Comment by wizard2000** [comment] 2020-09-04 19:52
![my issue](https://user-images.githubusercontent.com/41239997/92280059-dd061c80-ef0d-11ea-9ed2-1f306a5007bc.png)

**Comment by arielk** [comment] 2020-09-06 09:47
Duplicate of https://github.com/elementor/elementor/issues/12320

**Closed by arielk** 2020-09-06 09:47 UTC
