### ISSUE TITLE
In Safari when both Scrolling Effects and Mouse Effects are enabled on an element, a "RangeError: Maximum call stack size exceeded." error is thrown.

### ISSUE THREAD

**Issue by JordanaHarrison** [elementor/elementor#9115] opened 2019-09-17 19:56 UTC
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

When any Scrolling Effect AND Mouse Effect is enabled on a single element, Safari will throw a "RangeError: Maximum call stack size exceeded." error in jquery on load and on window resize. This prevents any events from firing after the element on the page, but any event before the element still functions. 

## Steps to reproduce

1. In a new Elementor page, add an element with an event (like a toggle).
2. Underneath, add another element like an image and apply 2 motion effects to it. I applied Scrolling Effects with Vertical Scroll (defaults), and Mouse Effects with Mouse Track (default).
3. Underneath this element, add another toggle element.

Everything will work in other browsers, except for in Desktop Safari (tested in Version 12.1.1). In Safari, the console will show the error. Additionally the toggle above the motion element will function, but the one under it will not.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
					
== Server Environment ==
	Operating System: Linux
	Software: nginx/1.15.8
	MySQL version: Source distribution v5.6.40
	PHP Version: 7.2.16-1+ubuntu16.04.1+deb.sury.org+1
	PHP Max Input Vars: 1000
	PHP Max Post Size: 32M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.2.3
	Site URL: https://canfar2019.dev.artscience.ca
	Home URL: https://canfar2019.dev.artscience.ca
	WP Multisite: No
	Max Upload Size: 32 MB
	Memory limit: 512M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: America/Toronto
	Debug Mode: Active

== Theme ==
	Name: Showcase Pro
	Version: 2.5
	Author: Bloom
	Child Theme: Yes
	Parent Theme Name: Genesis
	Parent Theme Version: 3.0.3
	Parent Theme Author: StudioPress

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36

== Active Plugins ==
	Classic Editor
		Version: 1.5
		Author: WordPress Contributors

	Contact Form 7
		Version: 5.1.4
		Author: Takayuki Miyoshi

	Elementor
		Version: 2.7.2
		Author: Elementor.com

	Elementor Extras
		Version: 2.2.3
		Author: Namogo

	Envira Gallery Lite
		Version: 1.6.8
		Author: Envira Gallery Team

	Flow-Flow
		Version: 4.1.17
		Author: Looks Awesome

	MapSVG Lite
		Version: 4.2.3.1
		Author: Roman S. Stepanov

	Post Types Order
		Version: 1.9.4.1
		Author: Nsp Code

	Quick Alt Editor
		Version: 1.0.2
		Author: Arsmoon

	Redirection
		Version: 4.3.3
		Author: John Godley

	Regenerate Thumbnails
		Version: 3.1.1
		Author: Alex Mills (Viper007Bond)

	Responsive Mobile-Friendly Tooltip
		Version: 1.6.6
		Author: ItayXD

	Scroll Triggered Box
		Version: 2.3
		Author: Dreamgrow Digital

	Smush
		Version: 3.2.4
		Author: WPMU DEV

	Text Hover
		Version: 3.8
		Author: Scott Reilly

	Timeline Express
		Version: 1.8.0
		Author: Code Parrots

	Timeline Express - No Icons Add-On
		Version: 1.2.0
		Author: Code Parrots

	Visualizer: Tables and Charts Manager for WordPress
		Version: 3.3.0
		Author: Themeisle

	WooCommerce
		Version: 3.6.5
		Author: Automattic

	WooCommerce Admin
		Version: 0.16.0
		Author: WooCommerce

	WooCommerce Google Analytics Integration
		Version: 1.4.11
		Author: WooCommerce

	WooCommerce Hear About Us
		Version: 1.5.2
		Author: SiteOptimo

	WooCommerce Multilingual
		Version: 4.6.7
		Author: OnTheGoSystems

	WooCommerce Remove Product Sorting
		Version: 1.2.0
		Author: SkyVerge

	WPFront Scroll Top
		Version: 2.0.2
		Author: Syam Mohan

	WPML Media
		Version: 2.5.3
		Author: OnTheGoSystems

	WPML Multilingual CMS
		Version: 4.2.8
		Author: OnTheGoSystems

	WPML String Translation
		Version: 2.10.6
		Author: OnTheGoSystems

	WPML Translation Management
		Version: 2.8.7
		Author: OnTheGoSystems

	Yoast SEO
		Version: 12.0
		Author: Team Yoast

	Yoast SEO Multilingual
		Version: 1.0.1
		Author: OnTheGoSystems


== Must-Use Plugins ==
	Art & Science MU Plugin Loader
		Version: 1.2
		Author: Tom Auger, Art & Science Experience Design

== Elements Usage ==
	
	page
		blockquote : 2
		button : 15
		call-to-action : 2
		circle-progress : 15
		counter : 12
		ee-scroll-indicator : 6
		ee-switcher : 5
		flip-box : 59
		heading : 64
		html : 175
		icon-box : 3
		image : 213
		image-box : 5
		media-carousel : 1
		share-buttons : 1
		shortcode : 2
		slides : 3
		spacer : 2
		testimonial-carousel : 1
		text-editor : 323
		toggle : 3
		unfold : 31
		video : 13
		woocommerce-products : 1
		wp-widget-ff_widget : 3
	section
		accordion : 1
		animated-headline : 2
		blockquote : 1
		button : 1
		counter : 4
		divider : 3
		ee-switcher : 2
		flip-box : 19
		global : 6
		heading : 8
		html : 30
		icon-box : 1
		image : 7
		image-box : 2
		media-carousel : 1
		menu-anchor : 1
		nav-menu : 1
		share-buttons : 4
		spacer : 1
		tabs : 2
		testimonial-carousel : 1
		text-editor : 25
		toggle : 4
		unfold : 3
	wp-post
		accordion : 1
		animated-headline : 6
		blockquote : 40
		button : 8
		call-to-action : 2
		circle-progress : 5
		counter : 8
		divider : 3
		ee-offcanvas : 1
		ee-scroll-indicator : 1
		ee-switcher : 4
		flip-box : 63
		global : 9
		google_maps : 1
		heading : 159
		html : 122
		icon : 3
		icon-box : 7
		image : 112
		image-box : 35
		image-gallery : 1
		media-carousel : 5
		posts : 1
		progress : 7
		share-buttons : 12
		shortcode : 2
		slides : 5
		spacer : 13
		testimonial-carousel : 1
		text-editor : 223
		toggle : 8
		unfold : 13
		video : 11
		wp-widget-ff_widget : 1
		wp-widget-media_video : 6
	wp-page
		image : 3
		text-editor : 3
		unfold : 3	
```
</details>

**Comment by shilo-ey** [comment] 2019-09-18 07:31
Duplicate of #7824

Try using different jQuery version (not the native one)

Thanks!

**Closed by shilo-ey** 2019-09-18 07:31 UTC

**Comment by JordanaHarrison** [comment] 2019-09-18 12:09
I saw the other thread that recommended that and tried it before submitting this bug. I still had the same issue. Is there a particular version that is known to work?

**Comment by joelnewcomer** [comment] 2020-08-14 15:46
@JordanaHarrison If you install this plugin, it should fix the issue for you: https://wordpress.org/plugins/jquery-updater/
