### ISSUE TITLE
Max columns in row

### ISSUE THREAD

**Issue by Zegklitz** [elementor/elementor#11248] opened 2020-04-28 08:55 UTC
Hello,

would it be possible to i nncrease max amount of columns in row from 10 to 12? When I want to have some grid of blocks looking good on PC, tablet and mobile it would help.
Eg. I want to have two rows with 12 colums each. On PC I want to have 4 columns in line (matrice 3*4). On tablet I want to have 3 columns in every line (matrice 4*3), but I can not do this now. In the last line on tablet I will miss one column on the end of row, if I set 8 columns on row.

Best regards,
Martin Žegklitz

**Comment by black-eye** [comment] 2020-04-28 13:42
Hi, @Zegklitz, welcome to the club ;)
https://github.com/elementor/elementor/issues/2218

**Comment by 3rinyes** [comment] 2020-04-29 08:48
This +1

**Comment by arielk** [comment] 2020-05-01 14:03
Duplicate of #2218

**Closed by arielk** 2020-05-01 14:03 UTC

**Comment by nicholaszein** [comment] 2022-11-16 05:24
This issue has been solved by the **stable** Flexbox Container experiment introduced with Elementor v**3.8**! 🥳
