### ISSUE TITLE
The gradient does not work with a dynamic ACF-Color-Field (Advanced Custom Field)

### ISSUE THREAD

**Issue by flo-glass** [elementor/elementor#12140] opened 2020-08-17 15:49 UTC
## Prerequisites

- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [ ] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by flo-glass** [comment] 2020-08-17 15:54
Steps to reproduce: 

1. Assign a ACF-Color field (jQuery) to all pages.
2. Add a new site and assign a color to from the ACF-field to that site. 
3. Edit this site with Elementor
4. Add a new element and edit the background.
5. Add a gradient to that background and assign the dynamic ACF-Color to one of the two available colors from the gradient.

**Comment by arielk** [comment] 2022-09-12 17:22
Duplicate of https://github.com/elementor/elementor/issues/10885

**Closed by arielk** 2022-09-12 17:22 UTC
Labels: bug, component/acf
