### ISSUE TITLE
🐞 Bug report: elementor icons - extra line height (Duplicate of #16511)

### ISSUE THREAD

**Issue by Michaelgimii** [elementor/elementor#17987] opened 2022-02-25 15:09 UTC
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

If you add an icon to the elementor, (it does not matter where. Button, icon alone or ...) the icon is not exactly in the center. It is such that the distance at the bottom is greater than at the top.
So the icons will never be in the center. This is really annoying. But if you look closely at other wordpress theme like Woodmart, the icons are right in the center. All icons in elementor have line height by default. So this is problematic. Please check this issue
Very small but very important

### Steps to reproduce

Use only the icon. What an icon widget, what In button. But to better understand the problem, add the icon widget and then increase the icon size. It is clear that the icon is not exactly in the center. https://prnt.sc/n-V0qpEquxJe

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

-

**Comment by rami-elementor** [comment] 2022-04-30 17:34
Duplicate of #16511

**Closed by rami-elementor** 2022-04-30 17:34 UTC
Labels: bug, component/icons, type/design
