### ISSUE TITLE
Customization of login pages

### ISSUE THREAD

**Issue by RicardoBenito** [elementor/elementor#10437] opened 2020-02-06 11:24 UTC
The login widget is very good, but unfortunately I consider it incomplete, since this design should be maintained for password recovery options in all its phases, as well as registration. And so depend on third party plugins. Likewise, add registration and login option with social media profiles.

Finally I want to add, that for two years I have been migrating all my work to Elementor.

**Comment by arielk** [comment] 2020-06-20 19:30
Duplicate of https://github.com/elementor/elementor/issues/8222

**Closed by arielk** 2020-06-20 19:30 UTC
Labels: request/enhancement
