### ISSUE TITLE
Mobile Menu Rendering Bug

### ISSUE THREAD

**Issue by mcrowell** [elementor/elementor#8460] opened 2019-07-01 17:40 UTC
## Prerequisites

- [X ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X ] The issue still exists against the latest stable version of Elementor.

## Description

I'm noticing a bug on the new Pro 2.5.10 version. It's not rendering the active mobile hamburger icon at all.

## Steps to reproduce

When you click on the mobile menu icon it doesn't render the active icon. ( X icon )

## Isolating the problem
- [X ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a default WordPress theme active.
- [X ] I can reproduce this bug consistently using the steps above.

## Environment

== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MySQL Community Server (GPL) v5.7.26
	PHP Version: 7.3.6
	PHP Max Input Vars: 5000
	PHP Max Post Size: 200M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.2.2
	Site URL: https://wickydemo.com/testing
	Home URL: https://wickydemo.com/testing
	WP Multisite: No
	Max Upload Size: 200 MB
	Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: America/New_York
	Debug Mode: Inactive

== Theme ==
	Name: Twenty Nineteen
	Version: 1.4
	Author: the WordPress team
	Child Theme: No

![hamburger menu](https://user-images.githubusercontent.com/7768009/60456004-ff175700-9c05-11e9-89ea-5846099a478a.jpg)

**Comment by borgwald** [comment] 2019-07-01 19:31
I can confirm this bug. Updated to Version Elementor Pro v2.5.10 and can't see closed Hamburger Menu Icon since then.

**Comment by shilo-ey** [comment] 2019-07-02 09:53
Thanks for reporting.

This issue will be fixed soon.

Follow this thread for updates.

**Comment by shilo-ey** [comment] 2019-07-03 06:37
This issue has been resolved in Elementor Pro v2.5.11

Feel free to update

Thanks!

**Closed by shilo-ey** 2019-07-03 06:37 UTC
Labels: component/nav-menu, pro, status/merged
