### ISSUE TITLE
[Feature Request] PRESETS for widgets and more!

### ISSUE THREAD

**Issue by fabianenzensperger** [elementor/elementor#11865] opened 2020-07-14 10:43 UTC
- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

That would be something I really want since using Elementor. Presets to uniformly style my widgets such as buttons, icons, etc. without having to go into every single element when I make changes. And no, theme styles is far from it and would not be the answer. There you should only be able to set the defaults. PRESETS would be a game changer!

So that you understand better what I mean, just watch this recently released video [(https://youtu.be/I2VqPBfMA5Y)](url) from Divi. Really awesome! Something like that would be very important in the course of global settings and in general global work in Elementor!

Please leave me your opinion.

<img width="1680" alt="Bildschirmfoto 2020-07-14 um 12 42 54" src="https://user-images.githubusercontent.com/57997262/87416846-96600a00-c5cf-11ea-8cc6-8a514a940aad.png">

**Comment by beziehungsweise** [comment] 2020-07-15 08:00
Extremely important feature, see this facebook post:

https://www.facebook.com/groups/Elementors/?post_id=2910760729049694&comment_id=2911640605628373&reply_comment_id=2911820982277002&notif_id=1594753889754786&notif_t=group_comment_mention&ref=notif

**Comment by ewokee** [comment] 2020-07-15 08:02
+1 
big need! would love to see this feature :)

**Comment by medvedbne** [comment] 2020-07-15 08:16
+1

**Comment by fabianenzensperger** [comment] 2020-07-15 09:49
Can anyone tell me how to label this feature request? On the Macbook, I don't have a checkbox in the issue overview to the left of the icon to select it and then label it. Thanks for help!

**Comment by fabianenzensperger** [comment] 2020-07-15 09:51
Oh, and Presets are NOT "Global Widgets". These are mostly bullshit!

**Comment by fabianenzensperger** [comment] 2020-07-15 09:52
> +1
> big need! would love to see this feature :)

Yes!! So valuable.

**Comment by fabianenzensperger** [comment] 2020-07-15 09:54
> +1
> Extremely important feature, see this facebook post:
> 
> https://www.facebook.com/groups/Elementors/?post_id=2910760729049694&comment_id=2911640605628373&reply_comment_id=2911820982277002&notif_id=1594753889754786&notif_t=group_comment_mention&ref=notif

Jep, this is my FB Post with a link to my feature request and in this facebook post there are unfortunately a lot of unknowing and not aware of the meaning of what I mean.

**Comment by beziehungsweise** [comment] 2020-07-15 09:58
> > +1
> > Extremely important feature, see this facebook post:
> > https://www.facebook.com/groups/Elementors/?post_id=2910760729049694&comment_id=2911640605628373&reply_comment_id=2911820982277002&notif_id=1594753889754786&notif_t=group_comment_mention&ref=notif
> 
> Jep, this is my FB Post with a link to my feature request and in this facebook post there are unfortunately a lot of unknowing and not aware of the meaning of what I mean.

=> Yes, you are completely right. People are comparing this with global widgets ... !!!

**Comment by MichaelDarko** [comment] 2020-07-17 11:01
+1 

This should be a big part of Elementor's focus on "design systems".

**Comment by fabianenzensperger** [comment] 2020-07-17 17:07
> +1
> 
> This should be a big part of Elementor's focus on "design systems".

Absolutely essential!

**Comment by arielk** [comment] 2020-07-22 16:49
Duplicate of #965

**Closed** 2020-07-22 16:49 UTC

**Comment by fabianenzensperger** [comment] 2020-08-28 14:40
> Duplicate of #965

Ok a duplicate, but so much wanted!
