### ISSUE TITLE
🔗 🚀 Feature Request: Custom post type for form submissions (Duplicate of #1686)

### ISSUE THREAD

**Issue by mrtolix** [elementor/elementor#6505] opened 2018-12-19 20:35 UTC
Would be great if Elementor could have a custom post type with all form submissions

**Comment by bainternet** [comment] 2018-12-20 08:54
Duplicate of #1686

**Comment by bainternet** [comment] 2018-12-20 08:55
@mrtolix 

Thanks for the suggestion, next time, please follow guidelines for opening a new [feature request](https://github.com/pojome/elementor/issues/new?template=Feature_request.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Description and examples.

**Closed by bainternet** 2018-12-20 08:55 UTC
