### ISSUE TITLE
🔗 🚀 Feature Request: Ability to save editor changes using ctrl+s / cmd+s. (Duplicate of #20283)

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#20459] opened 2022-11-20 11:54 UTC
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

Hi elementor team!

It would be great if you could add the ability to save editor changes using ctrl+s. Currently using ctrl+s we can only save changes to history and that doesn't look cool. But it would be great if we could save and publish changes using it.

### Describe the solution you'd like

Save and publish changes using ctrl+s

**Comment by mbaierl** [comment] 2022-11-21 11:32
Actually even more important: if a page / post is not published, cmd+s should NOT publish it.

**Comment by nicholaszein** [comment] 2022-11-22 03:25
Hello @79ho3ein!

Thank you for your submission! 🙏 

### 🔗 This issue is a Duplicate of #20283.

Which is on the same subject. 

As @mbaierl correctly pointed out above, the `ctrl/cmd+s` keyboard shortcut only saves the history to avoid inadvertently publishing the document. There is no plan to change this behavior for the time being.

We will, of course, keep this suggestion in mind and consider adding it if there is significant demand in the future. 

### 🔍 Please, in the future, remember to check if there isn't an issue similar to yours already opened. 

Best regards,

Nick

**Closed by nicholaszein** 2022-11-22 03:25 UTC
Labels: request/enhancement, component/editor, type/workflow
