### ISSUE TITLE
✅ 🐞 Bug Report: Custom Breakpoints + Single templates – Custom breakpoints do not work while using a single post/page template.

### ISSUE THREAD

**Issue by Specialistinwebsites** [elementor/elementor#16819] opened 2021-11-05 12:46 UTC
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description
When using custom breakpoints for elements on posts/pages edited with Elementor, this does not work on the frontend while a single template is being applied. The CSS for the default desktop breakpoint in the inline styling (added while using the Post Content widget) overrides the post’s stylesheet with the expected custom breakpoint CSS.

## Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.

**Comment by Northwest-Studio** [comment] 2021-11-22 12:20
I have this issue too - it seems to be a bug. I am currently working with support on it and they have access to my site but hope it gets identified as a bug and fixed soon! My report: https://github.com/elementor/elementor/issues/16940

**Comment by twerkema** [comment] 2021-11-22 12:49
Similar issue with a footer template. I've posted on another thread and saw someone with a similar issue in the Elementor Community. Could be an issue between templates and custom breakpoints. Non-templates seem to work ok for me. Keep us posted and hope they figure it out.

**Comment by twerkema** [comment] 2021-12-06 21:04
Started a new site and similar issues. I created a loop template using ACF fields. With Custom Breakpoints enabled my font sizes set in the Elementor widget for tablet and mobile are ignored and the desktop font settings are applied. With Custom Breakpoints disabled the font sizes appear correctly.

**Comment by jdgranja** [comment] 2022-01-04 10:43
Same here.

**Comment by Swervedriver** [comment] 2022-03-03 08:26
Same here. Problem still exists with Elementor Version 3.5.6 and Elementor Pro 3.6.3

**Comment by web-center** [comment] 2022-03-16 10:53
I'm experiencing this issue only when working with translated single page templates (WPML).
Elementor "Regenerate CSS" works fine for me if I have no translations. Maybe you can try changing the CSS-output from external which is default to inline (Elementor>Settings>Advanced) and back again + regenerate CSS, as suggested by Elementor.

But at the time I create a translation for example of a custom 404 error page template with custom breakpoints active actually the style settings for the different breakpoints don't get applied on the frontend (desktop settings are inherited). As a workaround at this time I'm working with dynamic styling (for example font sizes set by VW).

But this issue should be solved.

**Comment by FelixBehr** [comment] 2022-03-18 09:10
Any idea when this will be fixed? Custom Breakpoints is a huge deal it seems

**Comment by FelixBehr** [comment] 2022-03-25 09:39
Well...i think i've found the solution by pure accident. 

Take a look at your used template for the specific page. If this is set to "Theme", set it to "Elementor Canvas" or "Elementor Full Width".

At least for me this resolved the problem.

**Comment by BaronVonDerpsalot** [comment] 2022-04-07 20:10
+1 Except I'm not getting any relief by changing the template to Canvas or full width.

**Comment by MichaelDarko** [comment] 2022-04-20 04:32
My experience is this:

- If I turn on the custom breakpoints experiment (even without adding any custom breakpoints) I can't use any advanced positioning on mobile / tablet. It works fine in the editor, but the responsive styles do not load on the front-end.

- This happens in header/footer templates. Maybe in other templates as well, not sure.

- Regenerating CSS fixes this. Make any change to the template and the problem comes back.

- Turn off the custom breakpoints experiment and the responsive styles load correctly.

The exact problem is nicely explained by other user here: #16940

This makes the custom breakpoints feature unusable because I can't have it turned on. 

This was raised 6 months ago and during the beta testing!

What's the point of releasing new features if you release them buggy and provide no fix in 6 months?

**Comment by david-strejc** [comment] 2022-04-26 07:27
+1 Also same here. Same behaviour.

**Comment by satomiao** [comment] 2022-04-30 17:35
+1

**Comment by GiuMagnani** [comment] 2022-06-24 08:31
+1, any update on this? is there any workaround apart from regenerating the css?

**Comment by aliboy08** [comment] 2022-08-09 14:22
did some testing in the core codes
on /plugins/elementor/core/files/css/base.php method/function = parse_content

the $initial_responsive_controls_duplication_mode is set to = "off"
changing this to "on" seems to work on my case

https://prnt.sc/Mx4r5JwdeRgc

upon checking checking the code /plugins/elementor/core/breakpoints/manager.php 
description/comment says "When generating Post CSS, the mode is set to 'on'. When generating Dynamic CSS, the mode is set to 'dynamic'."
https://prnt.sc/-1BiEnTs2Wyw

Seems like this should be set to "on" 
but it is currently set to "off" for post

https://prnt.sc/EIVCAEN248Nm

I don't understand exactly how this responsive_control_duplication_mode works, did not reach that far yet.

This is just for testing, I know you should not edit plugin files.

**Comment by ConsultMePL** [comment] 2022-10-23 12:19
It's been a year and the issue is still not fixed.

I'm using JetEngine from Croco and load a listing from a single template. The changes are visible in the editor, but not on the frontend. Regenerating CSS doesn't help. I can't make a workaround with a custom css, as what I do is setting the number of columns based on the breakpoint.

**Comment by MERZAK-X** [comment] 2022-10-29 14:52
I faced this issue with many themes footers; changing the breakpoints (+ and -1 then save, just to refresh) fixes it for single lang sites, it's more painful with multi-lang (polylang) sites after fixing one footer in a lang the other glitches.
Reupdating the footers and regenerating CSS from Elementor dashboard does the trick sometimes.

**Comment by frussane** [comment] 2022-10-31 18:30
+1

**Comment by badwulfx** [comment] 2022-11-01 14:49
The same issue exists for me.

**Comment by manuel-will** [comment] 2022-11-25 00:34
This issue still persists.

**Comment by asiaryckobozenska** [comment] 2022-12-06 16:09
Me and my team encountered the same issue in the last two weeks, while working on a projects with multiple added breakpoints (apart from the usual three, there are also a Widescreen, a Laptop, a Tablet Extra and a Mobile Extra). This bug is already one year old, so I hope it will get attention.

**Comment by Anders-Graitor** [comment] 2023-01-06 08:45
+1 big time,

**Comment by Anders-Graitor** [comment] 2023-01-06 08:53
> +1
> 
> I've managed to put some code in functions.php that might help (a workaround):
> 
> ```
> add_action('elementor/editor/after_save', 'qcwp_regenerate_css');
> function qcwp_regenerate_css(){
>     // Make sure that Elementor loaded and the hook fired
>     if ( did_action( 'elementor/loaded' ) ) {
>         // Automatically purge and regenerate the Elementor CSS cache
>         \Elementor\Plugin::instance()->files_manager->clear_cache();
>         \Elementor\Plugin::instance()->posts_css_manager->clear_cache();
>     }
> }
> ```
> 
> This forces Elementor to clear it's cache and regenerate everytime a post/page/layout is saved on the editor

is it possible to make it do it even if you didn't update or edit a page? but force each user that enter a site to make it regenerate because that's also one of the big issues with this bug.

**Comment by Nevaah** [comment] 2023-02-07 16:25
I bet on custom breakpoints working for my current project. I abandoned them march 2022 because of this issue, it always popped up on sites I worked on, but it was in BETA so I took my licks. After it's now out of BETA I bet on this to provide QHD res a better experience. 3 months into dev and just finishing up frontend I find out this hasn't been fixed. It's been an open and well known bug for 15 months and they just took it out of BETA. 

I have had to turn off this option and of course everything at least works now. But honestly, shame on Elementor devs for this. Considering switching to Bricks after being a Pro subscriber for 3 years.

**Comment by annitacaniglia** [comment] 2023-03-17 00:31
Any news on this issue? I'm still unable to work with custom breakpoints and it's been a year and a half since it was reported!

**Comment by Azenocx752** [comment] 2023-03-31 10:44
Same issue with elementor 3.11.5 and elementor pro 3.11.7. HELP

**Comment by Nevaah** [comment] 2023-03-31 12:05
I tried getting Elementor Support to recognize that this issue exists. THEY DO NOT BELIEVE THERE IS AN ISSUE. This is not being worked on, support says it can only be conflicting plugin and so this does not appear to ever be fixed. This is one of the reasons I'm now looking into Bricks. I'm very sorry for the new people who find out the hard way that this exists still, but there is no permanent fix.

**Comment by black-eye** [comment] 2023-03-31 12:24
> I tried getting Elementor Support to recognize that this issue exists. THEY DO NOT BELIEVE THERE IS AN ISSUE. This is not being worked on, support says it can only be conflicting plugin and so this does not appear to ever be fixed. This is one of the reasons I'm now looking into Bricks. I'm very sorry for the new people who find out the hard way that this exists still, but there is no permanent fix.

I think this problem is similar or identical to https://github.com/elementor/elementor/issues/19394#issuecomment-1488039832. Fix might be coming soon, but it was promised to come before 3.12 which sets Custom Breakpoints by default. The promise was not kept.

I simply don't get it - the problem was known, the issue is hard to spot and debug, it will cause trouble to thusands of users (without them even noticing it), but it was still published... So sad...

**Comment by Nevaah** [comment] 2023-03-31 20:53
> I think this problem is similar or identical to [#19394 (comment)](https://github.com/elementor/elementor/issues/19394#issuecomment-1488039832). Fix might be coming soon, but it was promised to come before 3.12 which sets Custom Breakpoints by default. The promise was not kept.
> 
> I simply don't get it - the problem was known, the issue is hard to spot and debug, it will cause trouble to thusands of users (without them even noticing it), but it was still published... So sad...

I really do hope this is true and that they will eventually fix it. I was absolute furious with the support just directing me to disable all plugins and see what that does, since they KNOW the issue exists. They obviously know or maybe even knew there was a bug in the feature they took out of beta. 

Anyways, I completely agree with you here. It's a terrible black spot on the team behind Elementor, that they try to sweep this under the rug and just hope people don't notice what's actually going on. Their response should have been: "We are aware of this issue and working on a fix". Instead I got the whole "Weeeeell, this might be someone else's fault, or maybe even yours? Do a ton of debugging yourself before we actually tell you, we cannot help you at this time". Again, this is shameful behavior.

**Comment by Irinel123** [comment] 2023-04-04 11:10
> Same here. Should be fixed ASAP.

+ 1

I have the same problem for blog/category template

**Comment by lensbreak** [comment] 2023-04-04 17:39
+1

**Comment by TomRaraAvis** [comment] 2023-04-05 16:03
+1

**Comment by frussane** [comment] 2023-04-13 17:35
> > +1
> > I've managed to put some code in functions.php that might help (a workaround):
> > ```
> > add_action('elementor/editor/after_save', 'qcwp_regenerate_css');
> > function qcwp_regenerate_css(){
> >     // Make sure that Elementor loaded and the hook fired
> >     if ( did_action( 'elementor/loaded' ) ) {
> >         // Automatically purge and regenerate the Elementor CSS cache
> >         \Elementor\Plugin::instance()->files_manager->clear_cache();
> >         \Elementor\Plugin::instance()->posts_css_manager->clear_cache();
> >     }
> > }
> > ```
> > 
> > This forces Elementor to clear it's cache and regenerate everytime a post/page/layout is saved on the editor
> 
> is it possible to make it do it even if you didn't update or edit a page? but force each user that enter a site to make it regenerate because that's also one of the big issues with this bug.

@Anders-Graitor You could, by hooking it to 'init' instead of 'elementor/editor/after_save' although depending on your server and how many templates you have got, I wouldn't recommend it as it could bring some performance issues! Also if you're using a cache plugin, you'd have to clean the cache everytime, or simply turn it off.

Also, just trying yo bump this issue, it needs to be solved! This is a great feature I use in a lot of websites, but it's f#cked up having clients calling randomly because the websites layout is broken...

**Comment by Nevaah** [comment] 2023-05-25 17:54
Bought a year subscription for Breakdance builder now. Don't know if it's going to work out, but the absolute disregard for making existing functions work and be updated is a clear sign that they are banking on only attracting new subscribers and just hoping people don't cancel. My completed sites will not need updates, hope I am ready for full transition to new builder before next year billing. Been Pro subscriber for 4 years but waiting 2 years for a dev to fix a feature puts the writing on the wall. 

"but but but AI!!!" - I'm done

**Comment by Anders-Graitor** [comment] 2023-05-25 17:56
Have a week left, not sure if I keeps it. Just the nightmare of migrating
to a new builder 🙄🫡

tor. 25. maj 2023 19.54 skrev Nevaah ***@***.***>:

**Comment by sermalefico** [comment] 2023-05-31 09:33
BIG BUG

**Comment by duongancol** [comment] 2023-06-21 04:28
Hm, I don't know why they keep following a fancy feature like AI instead of fixing this important bug.

**Comment by Anders-Graitor** [comment] 2023-06-21 05:48
> Hm, I don't know why they keep following a fancy feature like AI instead of fixing this important bug.

2000% agree. Had to go with webflow for 2 new projects. this bug just kills me and my time and projects.

**Comment by Nevaah** [comment] 2023-06-21 23:07
According to changelog for latest version 3.14.0 this has been fixed. I have not verified it yet as I'm not going back to old projects to test it out. And I've started building my first sites with Breakdance now any ways. Just thought it to be proper bringing up that they after 2 years finally saw fit to at least address the bug. 

> Fix: Responsive settings for templates don’t work as expected when Additional Custom Breakpoints feature is active ([#16819](https://github.com/elementor/elementor/issues/16819), [#19394](https://github.com/elementor/elementor/issues/19394))

**Comment by sermalefico** [comment] 2023-06-29 14:29
this is no fixed

**Comment by nicholaszein** [comment] 2023-08-01 22:45
Hello everyone!
We have great news! 🙌 

### 📢 We're happy to announce that the issue you raised was resolved in Elementor Core v.3.15.0! 🥳 

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂

**Closed by nicholaszein** 2023-08-01 22:45 UTC
Labels: bug, type/responsive, product/pro, component/theme-builder, status/merged, component/document, type/design, type/templates, 🚀 shipped, component/theme-builder/single-template
