### ISSUE TITLE
Dynamic ACF fields - in loop list and single templates.

### ISSUE THREAD

**Issue by bispawel** [elementor/elementor#8762] opened 2019-08-03 10:11 UTC
Hi,
- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

I would like to create a list of posts not only with the title date information about tags, comments, but also with unusual fields from ACF.
Currently, you can create a "loop" or "archive" template, but use only standard
 "Wordrpess" fields.

Additionally, it is not possible to display dynamic "ACF Field" information, for example from the "taxonomy" fields, also for "single" templates.

Is it possible to add these options? Or how can I do it myself?

best regards
Paweł Biskupski

**Comment by shilo-ey** [comment] 2019-08-04 06:22
Duplicate of #4440

**Closed by shilo-ey** 2019-08-04 06:22 UTC

**Comment by nicholaszein** [comment] 2023-08-01 19:39
Hello there!

We have great news! 🙌 

### 📢 We're happy to announce the new Loop Builder released with Elementor Pro v3.8.0! 🥳 

With the new Loop Grid widget, you can customize your post listings with custom templates! 💪 
Drag & Drop widgets to create complex designs, fine-tune your Loop Grid layout, add alternate templates, and much more!

This is just the first phase. More customization is coming!

Check out the article here: https://elementor.com/help/loop-grid/

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
