### ISSUE TITLE
Background Videos as Slideshow

### ISSUE THREAD

**Issue by badcat** [elementor/elementor#9361] opened 2019-10-17 15:46 UTC
I've added 3 short, self-hosted mpg videos (yup, I did it) into the background as a Slideshow type.  This works well in Safari and Mobile Safari - but no other browsers, of course.   

Any chance this could be made to work in Chrome, Firefox, Edge etc?  thanks.

**Comment by shilo-ey** [comment] 2019-11-14 07:07
Duplicate of #5812

**Closed by shilo-ey** 2019-11-14 07:07 UTC
