### ISSUE TITLE
⛔ Image carousel unfinished dynamic content feature

### ISSUE THREAD

**Issue by com2** [elementor/elementor#13160] opened 2020-11-25 12:06 UTC
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

The image field allows to select dynamic content, but then does not:

- provide the option for dynamic URL
- show dynamic content at all. 
- allow to filter product or post categories or tags

The dynamic image feature is therefore broken leading to high hopes that end up in disappointment. 

## Steps to reproduce

- Have at least some Products with images active. 
- Edit the home page with Elementor
- Drag the Image Carousel widget to a section in the page, that is in default page lay-out mode. 
- Click the Dynamic tags symbol that appears to the right of "No images selected"
- Choose Product Gallery
- Verify the unexpected behaviour that no preview images appear
- Saved and displaying the front page logged out administrator with my browser inspector I see the an empty  elementor-widge-wrap inside the elementor-section where a dragged the widget. 
- Verify the unexpected behaviour that no other dynamic options appear anywhere else in the settings (Link URL, Image caption etc expected behaviour). 

## Isolating the problem

- [x] This bug happens with WooCommerce (to provide the product images), Elementor and Elementor Pro plugins active.
- [x] This bug happens with Elementor's recommended minimal Hello theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>Click to reveal</summary>

````txt


== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.25 (Debian)
	MySQL version: MySQL Community Server (GPL) v5.7.29
	PHP Version: 7.3.24
	PHP Max Input Vars: 10000
	PHP Max Post Size: 100M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.5.3
	Site URL: https://fotowp.lndo.site
	Home URL: https://fotowp.lndo.site
	WP Multisite: No
	Max Upload Size: 100 MB
	Memory limit: 1G
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: en-US
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.3.0
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:83.0) Gecko/20100101 Firefox/83.0

== Active Plugins ==
	Elementor
		Version: 3.0.13
		Author: Elementor.com

	Elementor Pro
		Version: 3.0.6
		Author: Elementor.com

	WooCommerce
		Version: 4.7.1
		Author: Automattic


== Must-Use Plugins ==
	Health Check Troubleshooting Mode
		Version: 1.7.2
		Author: 


== Elements Usage ==
	
	section : 1
		heading : 1
		image : 1
	wp-page : 1
		image-carousel : 1
		slides : 1
	product-archive : 1
		woocommerce-products : 1
		woofilters : 1


== Log ==
	
JS: showing 1 of 1JS: 2020-09-30 14:58:18 [error X 2][../wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.0.10:2:332391] elementorFrontend is not defined 

Log: showing 3 of 32020-10-01 17:58:39 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.10',
  'to' => '3.0.11',
)]
2020-10-21 08:39:22 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.11',
  'to' => '3.0.12',
)]
2020-11-05 08:43:52 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.12',
  'to' => '3.0.13',
)]

````

</details>

**Comment by nicholaszein** [comment] 2024-08-12 03:57
Hello @com2!

Thank you for reaching out and apologies for the delay in responding you. 🙏 

As we work to organize GitHub Issues and migrate Feature Requests to their new home in Discussions, we identified that your issue is more of a Feature Request, and not a bug. 

The Image Carousel is intended to be used to display a Gallery of images only, related to the current document you are editing. It is not intended to show a gallery of other content, or from another source that isn't the current document, be it a product, a page, or any Post Type. This includes using Dynamic Tags to show images. It was never intended to show images from other documents.

If you wish to display a slideshow of images from other sources, we recommend using the new Loop Carousel widget instead.

Therefore we are closing this issue as it's not a bug.

If you think this should be an Elementor feature, please submit a new [🚀 Feature Request](https://github.com/orgs/elementor/discussions/new?category=feature-request), and we will consider it in the future if there is enough demand (votes) from other users.

Kind regards

**Closed by nicholaszein** 2024-08-12 03:57 UTC
Labels: product/pro, component/swiper, component/dynamic-tag, integration/woocommerce, type/dynamic-content, solved-by/loop-builder, mod*, widget/image-carousel*
