### ISSUE TITLE
⛔ Terms in the Post Info widget do not appear vertically aligned with the rest of the Post Info items

### ISSUE THREAD

**Issue by JuliaArr** [elementor/elementor#10825] opened 2020-03-11 15:02 UTC
Hi, there is an issue with displaying Terms type of post meta data: https://www.screencast.com/t/vIyDHaFW8Q as it is not displayed in line with the other data.

**Comment by nicholaszein** [comment] 2024-04-28 06:22
Hello @JuliaArr,

Thank you for reaching out! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
We tested with multiple different icons, and with different configurations and all items appear correctly.

### ✅ What you can do to solve your issue:
- Your issue most likely has been fixed since you posted your issue.

As we work to improve and organize GitHub issues, we are gradually closing older issues that aren't relevant anymore.

We apologize for the inconvenience this may have caused you. We appreciate your patience and understanding.

### 👍 For now, that's all we can help with. 

Kind regards

**Closed by nicholaszein** 2024-04-28 06:22 UTC
Labels: product/pro, type/layout, mod*, widget/post-info
