### ISSUE TITLE
⛔ Cannot Discard new Revisions in the History panel if changes are made to the document and the document is not Updated

### ISSUE THREAD

**Issue by Roy-Orbison** [elementor/elementor#28658] opened 2024-09-10 02:34 UTC
### Prerequisites

- [X] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [X] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

I cannot discard autosaves. The page/post update button stays pink showing pending changes even though I do not wish to make any.

### Steps to reproduce

1. Open an existing page/post in Elementor's editor
2. Change something simple, then back again so the document is effectively unchanged, e.g. toggle Hide Title on & off, or vice versa. The post's update button should now be highlighted.
3. Click the History panel button.
4. In the Actions tab of the History panel, click on the bottom (Editing Started) item. The Update button remains highlighted.
5. Click the Revisions tab of the History panel.
6. The top item should be an Autosave of the "change". Select it.
7. Try to click the Discard button.

### Actual behaviour
The Discard button is either disabled, or if clickable it does nothing. The Update button remains highlighted, even after reloading the page.

I have to manually delete the autosaved post (and its metadata) from the database to make it go away.

### Expected behavior

* The autosave should be discarded
* The Update button should no longer be highlighted
* One should be able to cancel any pending changes to a document without the UI implying that there is unfinished work. This is especially important if another author could come along and assume pending changes need saving when they should in fact be discarded.

### Isolating the problem

- [X] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [X] This bug happens with the Hello Elementor theme active.
- [X] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

<details>
<summary>Click to reveal</summary>

````txt


== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: v10.3
	PHP Version: 8.3.10
	PHP Memory Limit: 256M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 8M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.3.5
	Site URL: https://redacted.example
	Home URL: https://redacted.example
	WP Multisite: No
	Max Upload Size: 2 MB
	Memory limit: 40M
	Max Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en_US
	Timezone: UTC
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 3.1.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en-US
	User Agent: Mozilla/5.0

== Active Plugins ==
	Elementor
		Version: 3.23.4
		Author: Elementor.com

	Elementor Pro
		Version: 3.23.3
		Author: Elementor.com


== Must-Use Plugins ==

== Elements Usage ==
	
	archive : 1
		archive-posts : 1
		container : 4
		heading : 1
	container : 9
		button : 1
		call-to-action : 1
		container : 31
		form : 1
		heading : 8
		html : 1
		image : 5
		image-box : 7
		image-carousel : 1
		posts : 1
		reviews : 1
		text-editor : 2
		toggle : 1
	footer : 3
		container : 8
		heading : 6
		image : 4
		nav-menu : 2
		posts : 1
		social-icons : 1
		text-editor : 7
	header : 3
		button : 1
		container : 7
		heading : 1
		icon-list : 1
		image : 2
		nav-menu : 2
		theme-site-logo : 2
	page : 6
		accordion : 2
		button : 12
		call-to-action : 2
		container : 125
		divider : 2
		heading : 37
		html : 4
		image : 19
		image-box : 24
		image-carousel : 4
		posts : 4
		text-editor : 27
		toggle : 4
		video : 6
	popup : 3
		form : 2
		heading : 2
		text-editor : 2
	widget : 0
		form : 2
	wp-page : 10
		button : 8
		call-to-action : 2
		container : 118
		divider : 2
		form : 3
		google_maps : 1
		heading : 36
		html : 1
		icon-box : 4
		image : 19
		image-box : 27
		image-carousel : 2
		posts : 3
		reviews : 3
		text-editor : 26
		toggle : 4
		video : 4
	single-post : 2
		container : 14
		form : 2
		heading : 6
		post-info : 2
		post-navigation : 2
		posts : 2
		share-buttons : 2
		theme-post-content : 2
		theme-post-featured-image : 2
		theme-post-title : 2
	error-404 : 1
		button : 1
		container : 2
		heading : 1
		text-editor : 1


== Settings ==
	
	cpt_support: post, page
	allow_tracking: yes
	editor_break_lines: 1
	unfiltered_files_upload: 1
	meta_generator_tag: 1


== Features ==
	Custom Fonts: 1
	Custom Icons: 0

== Integrations ==
	
	google_maps: Active
	recaptcha_v3: Active


== Elementor Experiments ==
	Improved CSS Loading: Active by default
	Inline Font Icons: Inactive
	Additional Custom Breakpoints: Active by default
	Flexbox Container: Active
	Grid Container: Active by default
	Upgrade Swiper Library: Active
	Nested Elements Performance: Active by default
	Optimized Control Loading: Inactive by default
	Optimized Markup: Inactive by default
	Plugin Onboarding: Active by default
	Default to New Theme Builder: Active by default
	Header &amp; Footer: Active by default
	Elementor Home Screen: Active by default
	Editor Top Bar: Inactive by default
	Build with AI: Active by default
	Landing Pages: Active by default
	Nested Elements: Inactive by default
	Lazy Load Background Images: Active
	Element Caching: Inactive by default
	Link In Bio: Inactive by default
	Floating Buttons: Inactive by default
	Elementor Editor Events: Inactive by default
	Display Conditions: Active by default
	Form Submissions: Active by default
	Menu: Inactive
	Taxonomy Filter: Active by default
	Search: Inactive by default


== Log ==
	
Log: showing 20 of 382024-07-17 18:12:20 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.22.1',
  'to' => '3.23.0',
)]
2024-07-17 18:12:20 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.22.1',
  'to' => '3.23.0',
)]
2024-08-01 20:29:31 [info] elementor-pro::elementor_pro_updater Started 
2024-08-01 20:29:31 [info] Elementor Pro/Upgrades - _on_each_version Start  
2024-08-01 20:29:31 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2024-08-01 20:29:31 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.23.0',
  'to' => '3.23.2',
)]
2024-08-01 20:29:31 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.23.0',
  'to' => '3.23.2',
)]
2024-08-05 15:25:22 [info] elementor::elementor_updater Started 
2024-08-05 15:25:22 [info] Elementor/Upgrades - _on_each_version Start  
2024-08-05 15:25:23 [info] Elementor/Upgrades - _on_each_version Finished 
2024-08-05 15:25:23 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.22.3',
  'to' => '3.23.3',
)]
2024-08-06 15:38:41 [info] elementor-pro::elementor_pro_updater Started 
2024-08-06 15:38:41 [info] Elementor Pro/Upgrades - _on_each_version Start  
2024-08-06 15:38:41 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2024-08-06 15:38:41 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.23.2',
  'to' => '3.23.3',
)]
2024-08-06 15:38:41 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.23.3',
  'to' => '3.23.4',
)]
2024-08-06 15:38:42 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.23.2',
  'to' => '3.23.3',
)]
2024-08-06 15:38:42 [info] Elementor/Upgrades - _on_each_version Start  
2024-08-06 15:38:43 [info] Elementor/Upgrades - _on_each_version Finished 
2024-08-06 15:38:43 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.23.3',
  'to' => '3.23.4',
)]

JS: showing 3 of 3JS: 2023-12-20 04:40:52 [error X 1][../wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.17.1:3:601323] can&#039;t access property &quot;id&quot;, elementor.documents.getCurrent() is null 
JS: 2024-08-27 01:29:59 [error X 1][../wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.23.4:3:663431] this.view.container is undefined 
JS: 2024-09-10 01:28:15 [error X 8][../wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.23.4:3:663431] can&#039;t access property &quot;isDesignable&quot;, this.view.container is undefined 

PHP: showing 1 of 1PHP: 2024-08-27 14:00:08 [warning X 4][../wp-content/plugins/elementor/includes/managers/image.php::113] Trying to access array offset on false [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]



== Elementor - Compatibility Tag ==
	
	Elementor form submission access: Compatibility not specified
	Elementor Pro: Compatibility not specified

== Elementor Pro - Compatibility Tag ==

````

</details>

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by nicholaszein** [comment] 2024-09-11 23:33
Hello @Roy-Orbison!

Thank you for reaching out! 🙏 

### ⛔ After reviewing your issue and following your steps, we concluded this is not a bug caused by Elementor. It's the intended behavior.

It seems you are missing some key information about this feature, and how it's intended to work. Please, allow me to explain:

The History panel is based on the default WordPress Post Revision mechanism. In fact it's only an overlay of the underlying feature. The only difference is that Elementor includes another level of interaction called Actions, which records all your actions during the session you have Elementor open. This allows you to revert your steps in a granular way without needing to restore post revisions. I believe you understand this functionality. However, there is one information you're missing:

Once you've made any changes to a document, even if you revert your Actions back, you are required to save the document again. This is not an arbitrary decision, but a safe mechanism from WordPress (not Elementor) that prevents potential loss of data in case something goes wrong. It's just how WordPress works. Once a Post Revision is generated (it happens every 60 seconds), you still need to save the document, even if you revert to another revision. In the same logical line, revisions can only be discarded if you Update the document as well. Because WordPress needs to save the last revision, which is stored in your browser to, again, prevent loss of data.

So to summarize. When a change is made to a document, you need to Update it. If you don't want to update it with that change, you can revert back your Actions and then Update. You still need to update it regardless. If you don't update, next time you open the document it will indicate you have a more recent revision and ask you if you want to restore it.

As for discarding or applying a revision, it can only be done once the document is saved. 

I hope this explanation makes sense.

Here's also a video showing these mechanisms at work:

https://github.com/user-attachments/assets/7d9d0ee5-2f3b-49d1-9890-bfdf64904824



I am closing this issue as it is not a bug, and we have no intention to change Core WordPress functionality as this could cause loads of conflicts with other plugins that depend on this functionality.

Kind regards

**Closed by nicholaszein** 2024-09-11 23:33 UTC
Labels: type/ui-ux, editor, type/workflow, editor/history-revisions, mod*
