### ISSUE TITLE
🔗 🐞 Display Conditions dynamic tags are limited - can't see more than 58 (Duplicate of #25418)

### ISSUE THREAD

**Issue by JennyPower** [elementor/elementor#25444] opened 2024-03-15 03:41 UTC
### Prerequisites

- [X] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [X] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

When setting a dynamic condition for a dynamic tag, the dropdown list of dynamic tags is limited to the first 58 (or so). I'm working on a large site with Woo and Event Calendar so lots of random custom fields. The dynamic tags are in alphabetical order, so it gets to 'E' and then stops - can't scroll any further.
Works fine for any dynamic fields that I can see.

### Steps to reproduce

1. Add an ACF field
2. Go to Advanced, Dynamic Conditions
3. Select Add Condition
4. Choose Dynamic Tags
5. Try to choose a dynamic tag name that is number 60th in the dropdown list

### Expected behavior

All dynamic tags should be visible or at least the ones used on the page

### Isolating the problem

- [X] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [X] This bug happens with the Hello Elementor theme active.
- [X] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

<details>
<summary>Click to reveal</summary>

````txt

== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MariaDB Server v10.3.39
	PHP Version: 8.0.30
	PHP Memory Limit: 512M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 256M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.4.3
	Site URL: ###################
	Home URL: ###################
	WP Multisite: No
	Max Upload Size: 256 MB
	Memory limit: 512M
	Max Memory limit: 512M
	Permalink Structure: /updates/%postname%/
	Language: en_AU
	Timezone: Australia/Sydney
	Debug Mode: Inactive

== Theme ==
	Name: ###########custom sub theme
	Version: 
	Author: #####
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 3.0.1
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: en-AU
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36

== Active Plugins ==
	Advanced Custom Fields PRO
		Version: 6.2.7
		Author: WP Engine

	All in One SEO
		Version: 4.4.1
		Author: All in One SEO Team

	Anti-Spam by CleanTalk
		Version: 6.29
		Author: СleanTalk - Anti-Spam Protection <welcome@cleantalk.org>

	Duplicator Pro
		Version: 4.5.15.1
		Author: Duplicator

	Elementor
		Version: 3.20.1
		Author: Elementor.com

	Elementor Pro
		Version: 3.20.0
		Author: Elementor.com

	Gravity Forms
		Version: 2.8.5
		Author: Gravity Forms

	Gravity Forms Power Automate Add-On
		Version: 1.5.0
		Author: Reenhanced LLC

	Imagify
		Version: 2.1.3.1
		Author: Imagify – Optimize Images & Convert WebP

	ManageWP - Worker
		Version: 4.9.19
		Author: GoDaddy

	Real3D Flipbook
		Version: 3.36
		Author: creativeinteractivemedia

	Redirection
		Version: 5.4.2
		Author: John Godley

	Simple History
		Version: 4.12.0
		Author: Pär Thernström

	The Events Calendar
		Version: 6.3.4
		Author: The Events Calendar

	The Events Calendar: Filter Bar
		Version: 5.5.3
		Author: The Events Calendar

	The Events Calendar Pro
		Version: 6.3.1.1
		Author: The Events Calendar

	Unlimited Elements for Elementor (Premium)
		Version: 1.5.99
		Author: Unlimited Elements

	Customisations
		Version: 0.1
		Author: #######

	WooCommerce
		Version: 8.6.1
		Author: Automattic

	WooCommerce Customer/Order/Coupon Export
		Version: 5.5.0
		Author: SkyVerge

	WooCommerce Stripe Gateway
		Version: 8.0.1
		Author: WooCommerce

	WooCommerce Weight Based Shipping
		Version: 5.7.1
		Author: weightbasedshipping.com

	Wordfence Security
		Version: 7.11.4
		Author: Wordfence

	WPForms
		Version: 1.8.6.3
		Author: WPForms


== Must-Use Plugins ==
	ManageWP - Worker Loader
		Version: 1.0.0
		Author: GoDaddy


== Features ==
	Custom Fonts: 1
	Custom Icons: 0

== Integrations ==
	
	woocommerce: Active


== Elementor Experiments ==
	Improved Asset Loading: Active
	Improved CSS Loading: Active
	Inline Font Icons: Active
	Additional Custom Breakpoints: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active
	Upgrade Swiper Library: Active by default
	Grid Container: Active
	Default to New Theme Builder: Active by default
	Hello Theme Header &amp; Footer: Inactive by default
	Editor Top Bar: Inactive by default
	Optimized Gutenberg Loading: Active by default
	Build with AI: Inactive
	Landing Pages: Inactive
	Nested Elements: Active
	Lazy Load Background Images: Active
	Optimize Image Loading: Active by default
	Notes: Inactive
	Display Conditions: Active
	Form Submissions: Inactive
	Menu: Inactive by default
	Taxonomy Filter: Active


== Log ==
	
Log: showing 20 of 272024-01-08 09:50:57 [info] Elementor/Upgrades - _on_each_version Finished 
2024-01-08 09:50:57 [info] Elementor/Upgrades - _on_each_version Start  
2024-01-08 09:50:58 [info] Elementor/Upgrades - _on_each_version Finished 
2024-01-08 09:50:58 [info] Elementor/Upgrades - _on_each_version Start  
2024-01-08 09:50:58 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.17.3',
  'to' => '3.18.3',
)]
2024-01-08 09:50:59 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.17.3',
  'to' => '3.18.3',
)]
2024-03-13 14:10:30 [info] elementor::elementor_updater Started 
2024-03-13 14:10:30 [info] Elementor/Upgrades - _on_each_version Start  
2024-03-13 14:10:31 [info] Elementor/Upgrades - _on_each_version Finished 
2024-03-13 14:10:31 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.18.3',
  'to' => '3.20.0',
)]
2024-03-15 10:43:46 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.20.0',
  'to' => '3.20.1',
)]
2024-03-15 10:43:47 [info] elementor::elementor_updater Started 
2024-03-15 10:43:47 [info] Elementor/Upgrades - _on_each_version Start  
2024-03-15 10:43:47 [info] Elementor/Upgrades - _on_each_version Finished 
2024-03-15 10:43:47 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.20.0',
  'to' => '3.20.1',
)]
2024-03-15 10:43:49 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.20.0',
  'to' => '3.20.1',
)]
2024-03-15 11:05:45 [info] elementor-pro::elementor_pro_updater Started 
2024-03-15 11:05:45 [info] Elementor Pro/Upgrades - _on_each_version Start  
2024-03-15 11:05:45 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2024-03-15 11:05:45 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.13.2',
  'to' => '3.20.0',
)]

PHP: showing 8 of 8PHP: 2024-01-22 20:36:29 [warning X 423][../wp-content/plugins/elementor-pro/modules/woocommerce/widgets/cart.php::2383] Undefined array key &quot;section_coupon_display&quot; [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-02-13 13:21:42 [warning X 30][../wp-content/plugins/elementor-pro/modules/posts/skins/skin-content-base.php::265] Attempt to read property &quot;ID&quot; on null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-03-07 01:02:32 [error X 1][../wp-content/plugins/elementor/core/admin/menu/admin-menu-manager.php::8] Maximum execution time of 30 seconds exceeded [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-03-13 14:00:58 [warning X 1][../wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php::150] Undefined array key &quot;condition_type&quot; [array (
  'trace' => '
#0: ../wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(150): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_template_json_item()
#2: ../wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(120): class type array_map()
#3: ../wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(69): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_templates_json()
#4: ../wp-content/plugins/elementor/data/base/endpoint.php(162): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> create_items()
',
)]
PHP: 2024-03-13 14:01:18 [warning X 1][../wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php::150] Undefined array key &quot;condition_type&quot; [array (
  'trace' => '
#0: ../wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(150): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: ../wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(84): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_template_json_item()
#2: ../wp-content/plugins/elementor/data/base/endpoint.php(166): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> update_item()
#3: ../wp-content/plugins/elementor/data/base/endpoint.php(307): Elementor\Data\Base\Endpoint -> base_callback()
#4: /home/####/public_html/wp-includes/rest-api/class-wp-rest-server.php(1193): Elementor\Data\Base\Endpoint -> Elementor\Data\Base\{closure}()
',
)]
PHP: 2024-03-13 14:04:00 [warning X 3][../wp-content/plugins/elementor/includes/elements/container.php::1849] Undefined array key &quot;size&quot; [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-03-15 11:43:48 [warning X 1][../wp-content/plugins/elementor/modules/history/revisions-manager.php::363] Undefined array key &quot;editor_post_id&quot; [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-03-15 12:51:40 [warning X 2][../wp-content/plugins/elementor-pro/modules/dynamic-tags/acf/tags/acf-text.php::33] Undefined array key 1 [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 7 of 7JS: 2024-02-13 02:36:20 [error X 5][../wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.18.3:3:954453] Cannot read properties of undefined (reading &#039;settings&#039;) 
JS: 2024-02-13 03:16:07 [error X 1][..#/wp-content/plugins/elementor/assets/js/web-cli.min.js?ver=3.18.3:3:72628] Commands: `panel/global/open` not found. 
JS: 2024-02-16 00:15:42 [error X 4][../wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.18.3:3:806339] Cannot read properties of undefined (reading &#039;toLowerCase&#039;) 
JS: 2024-02-27 04:01:07 [error X 5][../wp-content/plugins/elementor/assets/js/common-modules.min.js?ver=3.18.3:2:56156] Model.isValidChild() should be implemented, please provide &#039;isValidChild&#039; functionality. 
JS: 2024-03-06 06:22:48 [error X 11][../wp-admin/load-scripts.php?c=0&amp;loadchunk_0=wp-polyfill-inert,regenerator-runtime,wp-polyfill,wp-hooks,jquery-core,jquery-migrate,utils&amp;ver=c97e7fbc6ca5b7f702a54caa5b437f9d:7:28760] Cannot read properties of undefined (reading &#039;value&#039;) 
JS: 2024-03-13 03:14:50 [error X 1][../wp-content/plugins/unlimited-elements-for-elementor-premium/provider/core/plugins/unlimited_elements/elementor/assets/uc_editor_admin.js?ver=1.5.99:685:17] Cannot read properties of null (reading &#039;replace&#039;) 
JS: 2024-03-13 03:52:43 [error X 1][../wp-includes/js/dist/vendor/react-dom.min.js?ver=18.2.0:10:23755] Cannot read properties of null (reading &#039;getOptions&#039;) 



== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatibility not specified
	Unlimited Elements for Elementor (Premium): Compatibility not specified

== Elementor Pro - Compatibility Tag ==

````

</details>

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by vladninja** [comment] 2024-03-21 16:26
Same problem

**Comment by nicholaszein** [comment] 2024-03-25 20:48
Hello @JennyPower!

Thank you for your submission! 🙏 

### 🔗 🐞 This issue is a Duplicate of #25418 

Which is on the same subject. 

For this reason, I'm closing this thread and 🔃 **Merging** it with the original, so we can have all the discussions in one location, and deal with it more efficiently.

Feel free to continue the conversation there. 😉 

### 🔍 Please, in the future, remember to check if there isn't any thread similar to yours already opened. 

Kind regards

**Closed by nicholaszein** 2024-03-25 20:48 UTC
Labels: product/pro, component/dynamic-tag, mod*, duplicate, widget/settings/display-conditions
