### ISSUE TITLE
🔗 🚀 Feature Request: reset style button for all controller in editor. (Duplicate of #19140)

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#20542] opened 2022-11-27 10:22 UTC
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

Hi elementor team.

If I'm not mistaken, I posted a similar request for this before, but I couldn't find it, so I'm posting it again since I think it's an important request...

Currently, there is no option to reset an option like box shadow. If we want to reset a control like box shadow or border, we have to right click on the widget/container/section and then select reset style option. This is not a logical way. Because it resets all settings.

### Describe the solution you'd like

It would be great if you could display a small button for each control like in the image below. This button is not displayed by default. But if we activate a control like board or box shadow, it will be displayed. By clicking the button, the desired control settings (such as box shadow) will be reset and return to the initial state.

![reset style](https://user-images.githubusercontent.com/77163248/204130169-4806a077-d00e-4f6c-8e84-94fb71efdf5d.png)

This will be a very useful feature in Elementor. Currently, the bricks page builder uses this feature. I hope we will see this feature in Elementor as well.

thank you

**Comment by nicholaszein** [comment] 2022-11-27 11:17
Hello @79ho3ein!

Thank you for your submission! 🙏 

### 🔗 This issue is a Duplicate of #19140.

Which was created by you, and is on the same subject. 

For this reason, I'm closing this issue and 🔃 **Merging** it with the original, so we can have all the discussions in one location, and deal with it more efficiently.

Feel free to continue the conversation there. 😉 

## ⛔ Please, in the future, avoid creating duplicate issues. 
Although some issues do not receive any answers, they are still being tracked by Elementor. Creating duplicates only wastes your time. If you need to add something new, update your original issue instead. 

We appreciate it! 👊 😉

**Closed by nicholaszein** 2022-11-27 11:17 UTC
Labels: request/feature, type/ui/ux, component/editor
