### ISSUE TITLE
❌ 🔗 🐞 Bug Report: Mega Menu - Active Mode Color Not Working (Duplicate of #22391)

### ISSUE THREAD

**Issue by lensbreak** [elementor/elementor#23366] opened 2023-08-09 12:45 UTC
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

When hovering the megamenu item, its color changes (active mode). But if we place the mouse on the megamenu content, the color of the megamenu item returns to the default color (that should not be). While the active color should still be displayed so that it is clear which menu item the megamenu content belongs to. 

### Steps to reproduce

https://user-images.githubusercontent.com/88034902/237227412-75d4a19f-5474-4d5b-880a-9ddf677a6bbf.mp4

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

<details>
<summary>Click to reveal</summary>

````txt


== Server Environment ==
	Operating System: Linux
	Software: LiteSpeed
	MySQL version: MySQL Community Server - (GPL) v5.7.41
	PHP Version: 8.1.17
	PHP Memory Limit: 512M
	PHP Max Input Vars: 5000
	PHP Max Post Size: 80M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.3
	Site URL: 
	Home URL: 
	WP Multisite: No
	Max Upload Size: 80 MB
	Memory limit: 40M
	Max Memory limit: 512M
	Permalink Structure: /%postname%/
	Language: de-CH
	Timezone: Europe/Zurich
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor Child
	Version: 1.0.1
	Author: Elementor Team
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.8.1
	Parent Theme Author: Elementor Team

== Active Plugins ==
	Elementor
		Version: 3.15.2
		Author: Elementor.com

	Elementor Pro
		Version: 3.15.1
		Author: Elementor.com

== Features ==
	Custom Fonts: 0
	Custom Icons: 0

== Elementor Experiments ==
	Optimized DOM Output: Active by default
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Inactive by default
	Additional Custom Breakpoints: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active
	Upgrade Swiper Library: Active
	Grid Container: Active
	Default to New Theme Builder: Active by default
	Hello Theme Header & Footer: Active by default
	Editor Top Bar: Active
	Landing Pages: Active by default
	Nested Elements: Active
	Lazy Load Background Images: Inactive by default
	Global Style Guide: Inactive by default
	Page Transitions: Active by default
	Notes: Inactive
	Loop: Active by default
	Form Submissions: Active by default
	Scroll Snap: Active by default
	Menu: Active
	Taxonomy Filter: Active


````

</details>

**Comment by nicholaszein** [comment] 2023-08-09 21:13
Hi, @lensbreak ,

Thank you for reaching out! 🙏 

### ⛔ After reviewing your report we concluded this is not a bug caused by Elementor. The feature you're referring to is not yet supported.

As explained [here](https://github.com/orgs/elementor/discussions/22426#discussioncomment-6684659), this is not for what the **`Active`** state of the Menu Item Styles is supposed to do. It relates to the Currently Active Page, or Currently Active Section (for anchor points). It should appear if you visit a link or anchor point that the menu item is linked to, not to convey when a Menu Item Content is Open.

If you think this should be an Elementor feature, please cast your ⬆️ **Upvote** in #22426 and we will consider it in the future if there is enough demand (votes) from other users.

----

### 🔗 🐞 This issue is a Duplicate of #22391

Which is on the same subject. 

### 🔍 Please, in the future, remember to check if there isn't any thread similar to yours already opened. 

----

We appreciate your involvement in our community. For efficient troubleshooting, please remember to include the <br />**<ins>FULL, and essential</ins> [System Info](https://elementor.com/help/hare-my-system-info/)** with each issue reported. We'll need it to help you effectively. 

#### ⚠️ As a gentle reminder, issues without it may need to be closed without troubleshooting. Providing this information upfront aligns with our guidelines, saves time, and ensures swift resolution. Thank you for understanding.

Kind regards

**Closed by nicholaszein** 2023-08-09 21:13 UTC
Labels: type/ui/ux, product/pro, component/design, component/tabs, component/nested/menu, mod*
