### ISSUE TITLE
🔗 🚀 Feature Request: popup scheduling (Duplicate of #6899)

### ISSUE THREAD

**Issue by Wisefocus** [elementor/elementor#9988] opened 2019-12-25 02:54 UTC
Could a schedule setting be added to popup that works something like scheduling WP posts?

Until this feature is added, is there a work-around for setting a schedule for a popup to start and stop?

**Comment by shilo-ey** [comment] 2019-12-25 11:20
I merged this issue with #6899, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!

**Closed by shilo-ey** 2019-12-25 11:20 UTC
Labels: request/enhancement, product/pro, component/popup, product/beta3.11

**Comment by nicholaszein** [comment] 2023-01-27 16:09
Hello @steve-manes!

Thank you for your submission! 🙏 

### 🔗 This issue is a Duplicate of #6899

Which is on the same subject. 

For this reason, I'm closing this issue and 🔃 **Merging** it with the original, so we can have all the discussions in one location, and deal with it more efficiently.

We are also beta-testing our new [Popup Advanced Rule for Date and Time range](https://github.com/elementor/elementor/discussions/21125), which covers part of what you're asking. Try the new beta version and let us know if it helps to manage popups better.

Feel free to continue the conversation there. 😉 

Best regards,

Nick
