### ISSUE TITLE
✅ 📚 🐞 Bug Report: Popover On Page Settings won't work as expected

### ISSUE THREAD

**Issue by meceware** [elementor/elementor#22936] opened 2023-06-29 19:01 UTC
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Hi,

Starting from v3.14.0, the popovers with the plugin don't work on page settings, however they work on the element settings. 

After some investigation, in `editor.js` file `onPopoverToggleClick` function, I noticed that if popover is not visible, it reroutes to the main element for some reason. When I change it as shown, it started working back again. This feature was working without problem until 3.13.4, but broken after 3.14.0.

![image](https://github.com/elementor/elementor/assets/16402717/6f554455-6dfb-4536-88a7-328cbb0df25b)

Thank you for your help,

### Steps to reproduce

- Please activate the test plugin attached.

[test_plugin.zip](https://github.com/elementor/elementor/files/11909552/test_plugin.zip)

- Create a new test page and go to page settings. 
- Go to `Test Tab` and click on the pen popover pen icon for `Test Option Tab`.

![image](https://github.com/elementor/elementor/assets/16402717/a9ad1774-d320-43c9-82dd-5e44a4a0defb)

- Verify that the popover does not activate.

- Change the `editor.min.js` as expained in the description.

- Check again the same page and verify that popover activates.

### Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [x] I can reproduce this bug consistently following the steps above.

### System Info

Any page, as this is related to JS.

[system-info-localhost-05-07-2023.txt](https://github.com/elementor/elementor/files/11959862/system-info-localhost-05-07-2023.txt)

**Comment by nicholaszein** [comment] 2023-07-05 14:08
Hello @meceware, 

Thank you for submitting your report! 🙏 

### ❌ While reviewing your report, we noticed it was missing some key pieces of information:

- 💾 **System info:** Please include the System Info report as outlined in our [guidelines](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml). 
   - Get your System Info from your WordPress `Dashboard` > `Elementor` > `System info` [learn how to copy it here](https://elementor.com/help/hare-my-system-info/). We can't accept issues without it.

We appreciate your involvement in our community. For efficient troubleshooting, please remember to include the essential **<ins>System Info</ins>** with each issue reported. We'll need it to help you effectively. 

⚠️ As a gentle reminder, issues without it may need to be closed without troubleshooting. Providing this information upfront aligns with our guidelines, saves time, and ensures swift resolution. Thank you for understanding.

### 🧐 Please provide the missing information above so we can troubleshoot your issue faster and better.

Best regards

**Comment by meceware** [comment] 2023-07-05 16:01
Hi,

This is a JS issue so I didn't think the system info would be necessary so, please find the system information attached below.

[system-info-localhost-05-07-2023.txt](https://github.com/elementor/elementor/files/11959862/system-info-localhost-05-07-2023.txt)

**Comment by meceware** [comment] 2023-07-07 14:11
Another side note, the same issue (routing to the top) happens when putting a color selector on page settings. When a color selector option is added to page settings, the clicking on the color makes a jump to the top instead of showing the color.

**Comment by choijun** [comment] 2023-07-12 15:17
Hi @meceware 
I found the similar issue https://github.com/elementor/elementor/issues/22867 - and I think the cause of these two problems is the same

**Comment by meceware** [comment] 2023-07-12 15:45
Yes, that looks about right, the code update I mentioned above is the reason this is happening, the color picker as well. When I fix that on the unminified `editor.js` file, color pickers and popovers start working.

**Comment by choijun** [comment] 2023-07-26 09:31
Hi @nicholaszein 

It's been a month, this problem can be solved on the next version (3.15) ?

**Comment by meceware** [comment] 2023-07-26 19:19
Hey @choijun, you are right, that's exactly the issue.

**Comment by nicholaszein** [comment] 2023-08-02 00:52
Hello there!

We have great news! 🙌 

### 📢 We're happy to announce that the issue you raised was resolved in Elementor Core v.3.15.0! 🥳 

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂

**Closed by nicholaszein** 2023-08-02 00:52 UTC
Labels: bug, compatibility/3rd_party, type/developer-api, status/merged, 🚀 shipped, component/document-settings, mod*, component/control/popover-toggle
