### ISSUE TITLE
Global Colors don't work after editing in responsive mode

### ISSUE THREAD

**Issue by zocoloco** [elementor/elementor#12181] opened 2020-08-21 23:42 UTC
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

Global Colors don't work after editing in responsive mode.

## Steps to reproduce

- Set your global colors
- Style your template using global colors
- Confirm everything works on the desktop and all colors are correct
- Switch to editing in responsive mobile mode.
- Check on mobile device
- Global colors aren't displaying
- Clear cache and check on desktop
- Colors stop displaying on desktop

WORKAROUND:
- reset all colors again ;-(

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Source distribution v5.7.26-29
	PHP Version: 7.3.20
	PHP Max Input Vars: 3000
	PHP Max Post Size: 128M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.5
	WP Multisite: No
	Max Upload Size: 128 MB
	Memory limit: 768M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: America/New_York
	Debug Mode: Inactive

**Comment by zocoloco** [comment] 2020-10-03 19:21
Still not working

**Comment by lior-sh** [comment] 2020-10-04 11:34
Hi @zocoloco,

Thanks for reporting, we couldn't reproduce the issue.
Please contact our support at support@elementor.com for guidance in resolving this issue and mention that you were directed by me and reference this issue.
Thanks.

**Closed by lior-sh** 2020-10-04 11:34 UTC

**Comment by zocoloco** [comment] 2020-10-07 04:15
Why are you so quick to close an issue that multiple people have had? Maybe you're not trying hard enough to figure it out?

 I've narrowed it down. It happens in Safari browser Mac. When I work in Chrome (or Brave)...it works fine. Then I open it in Safari - and it looses all the global colors and settings. Poof.

**Comment by fabianenzensperger** [comment] 2020-10-07 12:27
> Why are you so quick to close an issue that multiple people have had? Maybe you're not trying hard enough to figure it out?
> 
> I've narrowed it down. It happens in Safari browser Mac. When I work in Chrome (or Brave)...it works fine. Then I open it in Safari - and it looses all the global colors and settings. Poof.

Because it solved? I don't have this problem anymore.
