### ISSUE TITLE
⛔ Inner sections are no longer available in the widget panel when the Container Experiment is active

### ISSUE THREAD

**Issue by ValentinGratz** [elementor/elementor#18511] opened 2022-04-27 07:19 UTC
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

In the free version of elementor dev I no longer find the inner section module.

### Describe the solution you'd like

put back the inner section module

**Comment by nicholaszein** [comment] 2024-07-28 02:56
Hello @ValentinGratz!

Thank you for reaching out. It's been a while, and we apologize for the delay. 🙏 

It seems that the issue you reported was because you were using the Elementor Developer Edition plugin, which had, at the time, the new Flexbox Containers active by default.

Since so much time has passed, and the Container is now active by default on all new installations without the Developer Edition, we are closing this issue as not a bug.

We recommend not using the Developer Edition plugin on production websites. This plugin is intended to be used by developers who want to test their plugins against the latest Elementor features.

Kind regards

**Closed by nicholaszein** 2024-07-28 02:56 UTC
Labels: product/dev-edition, element/container, mod*
