### ISSUE TITLE
Buttons and Icons are not editable

### ISSUE THREAD

**Issue by TimSgr** [elementor/elementor#13064] opened 2020-11-13 12:20 UTC
## Prerequisites

- [ x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ x] The issue still exists against the latest stable version of Elementor.

## Description

the issue appears if I try to edit buttons or icons on my local website using docker compose. I installed and activated elementor and elementor pro and as soon as I try to edit the buttons or icons i have a blank/grey screen on the right side where there should be the edit options like choose a custom icon. On the live website everything is working fine.
If i open my browser console i get the following error: 

common.min.js?ver=3.0.13:2 TypeError: r.getKey is not a function
    at _default.initIconType (editor.min.js?ver=3.0.13:2)
    at editor.min.js?ver=3.0.13:2
    at Array.forEach (<anonymous>)
    at _default.loadIconLibraries (editor.min.js?ver=3.0.13:2)
    at ControlIconsView.onRender (editor.min.js?ver=3.0.13:2)
    at Object._triggerMethod (backbone.marionette.min.js?ver=2.4.5:22)
    at ControlIconsView.triggerMethod (backbone.marionette.min.js?ver=2.4.5:22)
    at ControlIconsView.render (backbone.marionette.min.js?ver=2.4.5:23)
    at i.renderChildView (backbone.marionette.min.js?ver=2.4.5:22)
    at i._addChildView (backbone.marionette.min.js?ver=2.4.5:22)

## Steps to reproduce
If I start a local wordpress enviroment and install the elementor and elementor pro plugin as soon as I add an button I am unable to edit it.

## Isolating the problem

- [x ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x ] This bug happens with a default WordPress theme active.
- [x ] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>

					
== Server Environment ==
	Operating System: Linux
	Software: nginx/1.17.8
	MySQL version: MySQL Community Server - GPL v8.0.21
	PHP Version: 7.4.2
	PHP Max Input Vars: 1000
	PHP Max Post Size: 1024M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.5.3
	Site URL: https://stackfuel.local
	Home URL: https://stackfuel.local
	WP Multisite: No
	Max Upload Size: 1 GB
	Memory limit: 1024M
	Permalink Structure: Plain
	Language: de-DE
	Timezone: Europe/Berlin
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.3.0
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: de_DE
	User Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.102 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 3.0.13
		Author: Elementor.com

	Elementor Pro
		Version: 3.0.6
		Author: Elementor.com

== Elements Usage ==
	
	header : 2
		button : 1
		image : 1
		nav-menu : 1
		text-editor : 1
	page : 6
		author-box : 1
		button : 6
		counter : 6
		heading : 49
		html : 3
		icon-list : 3
		image : 20
		nav-menu : 4
		post-info : 1
		posts : 2
		social-icons : 6
		spacer : 10
		testimonial : 3
		text-editor : 49
		theme-post-title : 2
	section : 2
		button : 2
		image : 2
		nav-menu : 2
		text-editor : 2
	wp-post : 5
		button : 8
		counter : 9
		heading : 47
		image : 15
		nav-menu : 4
		social-icons : 4
		spacer : 8
		testimonial : 4
		text-editor : 46
		theme-post-title : 3
	wp-page : 4
		button : 3
		counter : 3
		heading : 30
		icon : 2
		image : 19
		nav-menu : 2
		posts : 1
		search-form : 1
		social-icons : 3
		spacer : 6
		testimonial : 2
		text-editor : 37
		theme-post-title : 1
	single-post : 1
		button : 2
		counter : 3
		heading : 12
		image : 4
		nav-menu : 1
		social-icons : 1
		spacer : 2
		testimonial : 1
		text-editor : 11
		theme-post-content : 1
		theme-post-title : 1

== Log ==
	
PHP: showing 2 of 2PHP: 2020-11-03 15:19:09 [notice X 2][/var/www/html/web/wp-content/plugins/elementor/includes/managers/image.php::86] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-11-03 15:43:27 [notice X 5][/var/www/html/web/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 6 of 6JS: 2020-11-04 14:24:45 [error X 1][https://stackfuel.local/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view46740\") has already been destroyed and cannot be used. 
JS: 2020-11-04 14:24:45 [error X 1][https://stackfuel.local/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view50244\") has already been destroyed and cannot be used. 
JS: 2020-11-04 14:25:06 [error X 1][https://stackfuel.local/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view56097\") has already been destroyed and cannot be used. 
JS: 2020-11-04 14:25:06 [error X 1][https://stackfuel.local/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view56165\") has already been destroyed and cannot be used. 
JS: 2020-11-04 14:25:06 [error X 1][https://stackfuel.local/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view44784\") has already been destroyed and cannot be used. 
JS: 2020-11-10 12:43:31 [error X 3][https://stackfuel.local/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.0.12:2:474643] Cannot read property \'document\' of undefined 

Log: showing 2 of 22020-11-11 10:14:31 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.12',
  'to' => '3.0.13',
)]
2020-11-11 10:14:37 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.0.5',
  'to' => '3.0.6',
)]

				

</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by Aviad-Herman** [comment] 2020-11-15 09:18
Hi @TimSgr,

In order to pinpoint the origin of this bug we would have to see screenshots, dive deep into your local setup. and in general this could take a while. There is a very high chance this bug is caused by your local setup with docker compose.

May I suggest something first?

Depending on your needs, you might find the following software useful: [Local by Flywheel](https://localwp.com)
I personally use it and it works like a charm, very intuitive and easy.

If you are looking for more alternatives, check out this [blogpost](https://elementor.com/blog/wordpress-staging-site/) on more ways to build a staging site.

I'm going to close this issue but if you are still having trouble please reply and mention me to reopen it.

Thanks @TimSgr,

**Closed by Aviad-Herman** 2020-11-15 09:18 UTC

**Comment by kos2reus** [comment] 2021-06-09 10:23
This problem is not solved
the problem is still.

common.min.js?ver=3.2.4:2 TypeError: r.getKey is not a function
    at _default.initIconType (editor.min.js?ver=3.2.4:2)
    at editor.min.js?ver=3.2.4:2
    at Array.forEach (<anonymous>)
    at _default.loadIconLibraries (editor.min.js?ver=3.2.4:2)
    at ControlIconsView.onRender (editor.min.js?ver=3.2.4:2)
    at Object._triggerMethod (backbone.marionette.min.js?ver=2.4.5.e1:24)
    at ControlIconsView.triggerMethod (backbone.marionette.min.js?ver=2.4.5.e1:24)
    at ControlIconsView.render (backbone.marionette.min.js?ver=2.4.5.e1:25)
    at n.renderChildView (backbone.marionette.min.js?ver=2.4.5.e1:24)
    at n._addChildView (backbone.marionette.min.js?ver=2.4.5.e1:24)

**Comment by TimSgr** [comment] 2021-06-09 10:39
Hey! 
I found a solution for my problem: you need to clear your cache and/or delete your cookies if you can edit the buttons in elementor. This is still a huge and annoying problem because you waste much more time if you need to delete your cookies every 5min and relog every time again. I dont know if the problem is caused by a memory issue, so that elementor cant handle widgets with icons like icon boxes or buttons if you have a complex page or something.

**Comment by kos2reus** [comment] 2021-06-09 10:43
Hey!
thanks for answering
I have already realized that it is some problem with the browser cache, but it happens the same with safari ... I have realized because when I try it by opening a new incognito window in the first edition it does not happen, then in the second it does. ...

it's surprising that no one else complains about this or that Elementor fixes it

**Comment by TimSgr** [comment] 2023-06-01 10:45
Totally forgot about this until now!

i also opened a reddit thread about my issue but nothing seems to resolve the issue for me. 

I increased my memory limit, tried different themes and more... but nothing seems to help.

https://www.reddit.com/r/elementor/comments/11f85ac/problem_with_editing_widgets/

**Comment by TimSgr** [comment] 2023-06-10 23:47
My problem got resolved by deleting my custom icon set. It seems one icon had an invalid format or something. After deleting the icons I was able to edit the buttons and icon boxes. 

Thanks for the input
