### ISSUE TITLE
Option to add another breakpoint for responsive view

### ISSUE THREAD

**Issue by kneops** [elementor/elementor#8744] opened 2019-08-01 09:15 UTC
Especially with columns I find myself regularly needing a fourth breakpoint, so perhaps it could be an option to add an extra breakpoint.

Example: I recently had a four column layout with sections. It was a team members page. Breakpoint for mobile was 768 which in general is okay. I manually changed the width of the columns to become 50% width for tablets and mobiles (768) because the default behavour would have made the columns already 100% width at 768 pixels and that would show the images too big. But on smaller mobile screens 50% width would make the images and text too narrow, so starting from about 480 pixels a 100% width of the columns would be perfect, but I can't do that, except by manually adding custom css queries for that page and those columns.

Adding an optional extra breakpoint would be very helpful in these cases.

**Comment by shilo-ey** [comment] 2019-08-01 09:27
Duplicate of #2043

**Closed by shilo-ey** 2019-08-01 09:27 UTC
