### ISSUE TITLE
🔗 ⛔ 🐞 Bug Report: After updating I can't see the styles of my Mega Menu (Duplicate of #23790) - [ED-12212]

### ISSUE THREAD

**Issue by WastonW** [elementor/elementor#23813] opened 2023-09-15 11:04 UTC
### Prerequisites

- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest stable version of Elementor.

### Description

I use mega menu as the official said but the final appearance is like this.

the background
![mega menu](https://github.com/elementor/elementor/assets/76507552/ce1e0dd2-265b-4bd9-9645-de2f6e92a1bb)
 setting is right and has not changed anything.

Final appearance：
![elementor](https://github.com/elementor/elementor/assets/76507552/9fd8fec2-5633-4672-8cd8-77bf09a2d164)

I have tried clearing the cache and also clearing the elementor and also updated the version but still not solved.
Do you know how to solve it？

### Steps to reproduce

1. I use the mega menu as the official said. this is my first time trying it.
2. whatever I test， the mega menu appearance like this：
![elementor](https://github.com/elementor/elementor/assets/76507552/2113f788-cc8d-480a-a4ea-c412eaf25643)

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently following the steps above.

### System Info

<details>
<summary>Click to reveal</summary>

````txt



== Server Environment ==
	Operating System: Linux
	Software: LiteSpeed
	MySQL version: MySQL Community Server - GPL v8.0.34
	PHP Version: 8.1.22
	PHP Memory Limit: 256M
	PHP Max Input Vars: 10000
	PHP Max Post Size: 256M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.3.1
	Site URL: https://zchyoga.com
	Home URL: https://zchyoga.com
	WP Multisite: No
	Max Upload Size: 256 MB
	Memory limit: 40M
	Max Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.8.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36

== Active Plugins ==
	Akismet Anti-spam: Spam Protection
		Version: 5.3
		Author: Automattic - Anti-spam Team

	All In One WP Security
		Version: 5.2.4
		Author: All In One WP Security & Firewall Team

	Child Theme Wizard
		Version: 1.4
		Author: Jay Versluis

	Database for WPforms
		Version: 1.0.4
		Author: wpdebuglog

	Elementor
		Version: 3.16.3
		Author: Elementor.com

	Elementor Pro
		Version: 3.16.1
		Author: Elementor.com

	Essential Addons for Elementor
		Version: 5.8.9
		Author: WPDeveloper

	Essential Addons for Elementor - Pro
		Version: 5.6.1
		Author: WPDeveloper

	Imagify
		Version: 2.1.1
		Author: Imagify – Optimize Images & Convert WebP

	SEOPress
		Version: 6.9.1
		Author: The SEO Guys at SEOPress

	SEOPress PRO
		Version: 6.9
		Author: The SEO Guys at SEOPress

	Temporary Login Without Password
		Version: 1.8.2
		Author: StoreApps

	WPForms Lite
		Version: 1.8.3.1
		Author: WPForms

	WP Rocket
		Version: 3.15.0.1
		Author: WP Media


== Elements Usage ==
	
	container : 0
		button : 1
		container : 1
		heading : 3
		text-editor : 2
		wpforms : 1
	wp-page : 10
		button : 37
		divider : 28
		eael-adv-accordion : 1
		heading : 124
		image : 49
		image-carousel : 7
		spacer : 43
		tabs : 9
		text-editor : 101
		toggle : 7
		wpforms : 2


== Settings ==
	
	cpt_support: post, page
	disable_color_schemes: yes
	disable_typography_schemes: yes
	allow_tracking: yes
	unfiltered_files_upload: 1
	font_display: swap


== Features ==
	Custom Fonts: 0
	Custom Icons: 0

== Integrations ==
	


== Elementor Experiments ==
	Optimized DOM Output: Active
	Improved Asset Loading: Active
	Improved CSS Loading: Active
	Inline Font Icons: Active
	Additional Custom Breakpoints: Active
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active
	Upgrade Swiper Library: Active
	Grid Container: Active
	Default to New Theme Builder: Active
	Hello Theme Header &amp; Footer: Active
	Editor Top Bar: Active
	Landing Pages: Active
	Nested Elements: Active
	Lazy Load Background Images: Active
	Pages Panel: Inactive by default
	Global Style Guide: Active
	Page Transitions: Active
	Notes: Active
	Form Submissions: Active
	Scroll Snap: Active
	Menu: Active
	Taxonomy Filter: Active


== Log ==
	
JS: showing 9 of 9JS: 2023-07-21 10:28:36 [error X 45][https://zchyoga.com/wp-admin/load-scripts.php?c=1&amp;loadchunk_0=jquery-core,jquery-migrate,utils,wp-polyfill-inert,regenerator-runtime,wp-polyfill,wp-hooks&amp;ver=6.2.2:2:31823] Cannot read properties of undefined (reading &#039;value&#039;) 
JS: 2023-07-23 09:07:37 [error X 1][https://zchyoga.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.14.1:3:923837] elementorFrontend is not defined 
JS: 2023-08-01 08:17:51 [error X 1][https://zchyoga.com/wp-content/plugins/elementor/assets/js/web-cli.min.js?ver=3.14.1:3:107466] Routes: `panel/editor/settings` not found. 
JS: 2023-08-07 11:08:37 [error X 2][https://zchyoga.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.14.1:3:932267] Cannot read properties of undefined (reading &#039;route&#039;) 
JS: 2023-08-09 09:18:07 [error X 1][https://zchyoga.com/wp-content/plugins/elementor-pro/assets/js/editor.min.js?ver=3.14.1:2:64049] Cannot read properties of undefined (reading &#039;createTemplate&#039;) 
JS: 2023-08-09 09:43:39 [error X 7][https://zchyoga.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.14.1:3:310560] Cannot read properties of undefined (reading &#039;id&#039;) 
JS: 2023-08-10 07:04:25 [error X 1][https://zchyoga.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.14.1:3:807522] Cannot read properties of undefined (reading &#039;localized&#039;) 
JS: 2023-09-13 11:00:24 [error X 69][https://zchyoga.com/wp-content/plugins/elementor/assets/js/4fdaa70e951ad90db2f2.bundle.min.js:2:7786] Cannot read properties of null (reading &#039;dataset&#039;) 
JS: 2023-09-15 09:08:13 [error X 1][https://zchyoga.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: &quot;view88&quot;) has already been destroyed and cannot be used. 

PHP: showing 5 of 5PHP: 2023-07-24 09:33:02 [warning X 3][../wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::171] Undefined array key &quot;editor_post_id&quot; [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-09-13 10:59:05 [notice X 59][../wp-content/plugins/elementor/includes/base/controls-stack.php::228] hexdec(): Passing null to parameter #1 ($hex_string) of type string is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-09-13 11:02:59 [warning X 42][../wp-content/plugins/elementor/core/common/modules/ajax/module.php::175] Undefined array key &quot;data&quot; [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-09-15 07:21:16 [warning X 12][../wp-content/plugins/elementor/app/modules/import-export/module.php::753] Attempt to read property &quot;label&quot; on null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-09-15 09:17:36 [warning X 33][../wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php::150] Undefined array key &quot;condition_type&quot; [array (
  'trace' => '
#0: ../wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(150): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_template_json_item()
#2: ../wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(120): class type array_map()
#3: ../wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(59): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_templates_json()
#4: ../wp-content/plugins/elementor/data/base/endpoint.php(158): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> get_items()
',
)]

Log: showing 20 of 282023-09-13 10:49:57 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.15.1',
  'to' => '3.16.0',
)]
2023-09-13 10:49:57 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.15.1',
  'to' => '3.16.0',
)]
2023-09-14 10:58:31 [info] elementor::elementor_updater Started 
2023-09-14 10:58:31 [info] Elementor/Upgrades - _on_each_version Start  
2023-09-14 10:58:32 [info] Elementor/Upgrades - _on_each_version Finished 
2023-09-14 10:58:32 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.14.1',
  'to' => '3.16.2',
)]
2023-09-14 10:58:33 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.14.1',
  'to' => '3.16.2',
)]
2023-09-15 09:09:08 [info] elementor::elementor_updater Started 
2023-09-15 09:09:08 [info] Elementor/Upgrades - _on_each_version Start  
2023-09-15 09:09:08 [info] Elementor/Upgrades - _on_each_version Finished 
2023-09-15 09:09:08 [info] Elementor/Upgrades - _v_3_16_0_container_updates Start  
2023-09-15 09:09:09 [info] Elementor/Upgrades - _v_3_16_0_container_updates Finished 
2023-09-15 09:09:09 [info] Elementor/Upgrades - _v_3_17_0_site_settings_updates Start  
2023-09-15 09:09:09 [info] Elementor/Upgrades - _v_3_17_0_site_settings_updates Finished 
2023-09-15 09:09:09 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.16.2',
  'to' => '3.16.3',
)]
2023-09-15 09:16:58 [info] elementor-pro::elementor_pro_updater Started 
2023-09-15 09:16:58 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-09-15 09:16:58 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-09-15 09:16:58 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.16.0',
  'to' => '3.16.1',
)]
2023-09-15 09:16:58 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.16.0',
  'to' => '3.16.1',
)]



== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatible
	Essential Addons for Elementor: Compatible
	Essential Addons for Elementor - Pro: Compatible

== Elementor Pro - Compatibility Tag ==
	
	Essential Addons for Elementor: Compatible
	Essential Addons for Elementor - Pro: Compatible


````

</details>

**Comment by tobias992** [comment] 2023-09-15 13:17
Please try to disable "Improves CSS Loading" in settings. Looks similar like my problem:
https://github.com/elementor/elementor/issues/23790

**Comment by WastonW** [comment] 2023-09-15 13:32
> like

Thank you solved.

**Comment by tobias992** [comment] 2023-09-15 13:36
After Elementor fixed the bug... now it's just a workaround.

**Comment by mllemata** [comment] 2023-09-15 13:41
after update to 3.16.3 and pro to 3.16.1 it breaks the mega Menu widget styles

https://bluemed.monteweby.sk/

**Comment by nicholaszein** [comment] 2023-09-17 12:51
Hello @WastonW,

Thank you for reaching out! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
This issue was already solved. Your issue is likely caused by cache.

### ✅ What you can do to solve your issue:

1. ⚠️ **Make a Backup** of your website before proceeding, and if possible do it in a staging environment!

2. 🔬 **Isolate the problem:** Deactivate all of your plugins (except Elementor/Pro), and temporarily change your WordPress theme to [Hello theme](https://wordpress.org/themes/hello-elementor/). If this solves the problem, gradually activate your plugins and theme one by one, until you spot the conflicting plugin or theme.

3. 🗑️ **Clear the cache:** Clear all levels of cache, including but not limited to **Server cache**, **WordPress (optimization plugin) cache**, **CDN cache**, and **Browser cache**. Also, try visiting the front page of your website in **incognito/private** mode.
   - Check with your hosting provider if they employ server cache. If they do, please purge and temporarily deactivate the cache during the update process.
   - After updating, clear all levels of cache, especially the browser cache.

4. In your WordPress **`Dashboard`** > **`Elementor`** > **`Settings`** > **`Features`** page make sure the **`Improved CSS Loading`** experimental feature is **`Deactivated`**.

5. Go to your WordPress **`Dashboard`** > **`Elementor`** > **`Tools`** > **`General`** page and click to **`Regenerate CSS & Data`**, then clear all levels of cache again.

### 🛟 If after performing the steps above you are still experiencing issues with the Menu widget, please contact Elementor support.

### 👍 For now, that's all we can help with. 

----

### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for support.

❔ If you have questions, or need guidance, help, or general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) The main Facebook group where all kinds of users come together to help each other.
- [Elementor Academy](https://elementor.com/academy) Learn everything you need to know about using Elementor.
- [Elementor Developers Documentation](https://developers.elementor.com/) Learn everything about our Developer-API.
- [Free Support Forum](https://wordpress.org/support/plugin/elementor) Get help on WordPress.org.

💎 If you have an active [Elementor Pro](https://elementor.com/pro) license you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

----

### 🔗 🐞 This issue is a Duplicate of #23790 

### 🔍 Please, in the future, remember to check if there isn't any thread similar to yours already opened. 

Kind regards

**Closed by nicholaszein** 2023-09-17 12:51 UTC
Labels: product/pro, type/performance, type/styles, type/experiment, component/nested/menu, mod*, compatibility/cache
