### ISSUE TITLE
✔️ 🚀 Feature Request: Default Container Padding - User-Defined

### ISSUE THREAD

**Issue by IMTanuki** [elementor/elementor#19687] opened 2022-09-02 14:59 UTC
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

1. Setting a fixed default padding for all containers in 3.7.x severely limits the flexibility (no pun intended) when designing nested containers - each additional container level distorts the position of elements in those containers (or any child containers). In many cases, the original 0px default padding is preferred.

2. Right now, the default padding is not even displayed in each added container, so it's not even obvious what the actual padding value is.

### Describe the solution you'd like

1. Pls add a user-defined default container padding, similar to the user-defined element gap in the element kit template, so developers can control the impact of adding nested containers.

2. Pls ensure that the default container padding (whatever it is) is clearly displayed in each container that is added in a page, post or template.

### Describe alternatives you've considered

The only workaround is to create templates with empty container hierarchies, where the container padding has been overridden.

### Additional context

Just out of curiosity, what was the rationale for setting the default container padding?

**Comment by Michaelgimii** [comment] 2022-09-02 16:24
hi @IMTanuki , I think the default padding is a useful feature. Because it prevents elements from sticking to the edge of the mobile phone. It also makes nested containers much easier to access.
Alternatively, if you don't agree with this feature, you can easily set it to 0 : https://prnt.sc/0NjpFYdyJ4kk

**Comment by perks98** [comment] 2022-09-02 17:26
I agree, I would prefer the default padding to be 0px and have an option to get globally the first container padding then the children of the first container separate, as we can use flex gap now for child default padding in most of my cases are not needed for spacing while the parent will always need padding. Just my opinion as everyone has their own workflow.

**Comment by Michaelgimii** [comment] 2022-09-02 17:52
hi @perks98 , If the default padding is 0, how do you prevent the content inside the container from sticking to the mobile border? Is there a solution for that? I think this is an important issue. Am I wrong?

**Comment by perks98** [comment] 2022-09-02 21:06
Hi @Michaelgimii, @IMTanuki sounded like a request around controlling global container padding or at least more options around padding control that isn’t one size fits all. My response in terms of doing pixel perfect designs is that you mostly for simple sections only need to set the padding of the parent container then the nested widgets and containers can rely on flex gap rather than padding (depending on the design), this ensures your content uses the full content area that align to other sections. Setting default padding to all containers including nested ones will make the content area more narrow as you nest containers.

They added default padding globally under the site settings under the layout tab (I think that is where it is still) due to current columns having a default of 10px and so that nested containers are easier to edit in the editor or else using 0px padding currently makes them overlap.

**Comment by IMTanuki** [comment] 2022-09-03 00:50
@Michaelgimii - sorry, I just read the release notes and it didn't mention the global settings were enhanced to allow the designer to set the default padding. I just found it under layout - @perks98 , thx for pointing this out.

FWIW, I think  it's preferable to start with a default of 0 so that containers can be freely nested without progressively shrinking available real estate, which is what was happening to me until I noticed the padding. 

What really threw me off is that the padding is not explicitly shown in each instance of a container, so it looks like it's null.

But to your point, obviously at some level left and right padding are needed for mobile form factors. 

Thx both for your feedback - glad I can now set the default...

**Comment by barttermorshuizen** [comment] 2022-11-11 06:00
+1. the padding setting is kinda useless as it is also applied to all nested containers. 
I think that for nested child containers a general setting is much less needed. 
If the padding setting would only be applied on the outermost container, most use cases (differences padding mobile vs desktop etc.) would be fullfilled.

**Comment by barttermorshuizen** [comment] 2022-11-12 05:51
yeah, when the padding in the layout settings is left empty, a default padding of 10px is applied to all containers.
when a padding setting is entered, that setting is applied to all containers, nested or not (which is what the problem is).

when you enter a padding on a container, that setting - fortunately - overrides the layout setting.

I now fixed it with setting a class 'layout-fix' on the outermost container and some CSS:

.layout-fix.e-con>.e-con-inner{
    --padding-top: 40px;
    --padding-bottom: 40px;
}

body[data-elementor-device-mode=mobile] .layout-fix.e-con>.e-con-inner
{
    --padding-top: 20px;
    --padding-bottom: 20px;
    --padding-left: 20px;
    --padding-right: 20px;
}

Obviously, the current layout setting is kinda useless when applied nested - users need to override the nested containers all the time, which defeats the purpose of such a setting :-)

**Comment by nicholaszein** [comment] 2022-11-16 04:33
Hello everybody!

### 📢 We're happy to announce that you can now set a default padding in the Site Settings > Layout section with the latest version of Elementor (**v3.8**)! 🥳 

✔️ Please feel free to check it out and update your plugin to the new version!

Cheers 🥂

**Closed by nicholaszein** 2022-11-16 04:33 UTC
Labels: request/enhancement, component/container, type/global-style, 🚀 shipped

**Comment by barttermorshuizen** [comment] 2022-11-21 23:36
Hi @nicholaszein ,

I just verified and it is not working on version 3.8.1

Please create some nested containers with text in it.
change the layout setting and you'll see it is applied on everything - not just the outer containers.\

Please reopen.

Thanks, Bart

**Comment by IMTanuki** [comment] 2022-11-22 05:07
@barttermorshuizen 
I kind of lucked out - bc I was running into so many problems w/ container default values (not just padding and margin), I actually manually updated every container in any hierarchy. A lot of work, but it looks like I ducked a bullet.

**Comment by nicholaszein** [comment] 2022-11-23 17:40
> Please create some nested containers with text in it. change the layout setting and you'll see it is applied on everything - not just the outer containers.\

Hello @barttermorshuizen, this request was to add a default padding for all containers, not just the parent-most container. We have no plans to change this for the time being. It would be very confusing for users if this was only applied to parent containers, and wouldn't solve the issues this request was trying to solve.

Best regards

**Comment by IMTanuki** [comment] 2022-11-23 18:11
@nicholaszein @barttermorshuizen 
Nicholas - you don;t seem to understand what Bart is saying. There is a HUGE difference between default padding that gets applied to every new container and having padding settings for a high-level container cascade down to every child container. A huge difference...

**Comment by nicholaszein** [comment] 2022-11-23 18:28
@IMTanuki actually I do understand the difference very well. I see the value of what @barttermorshuizen is requesting.

But this specific issue was requesting global padding settings for all containers. Which is what it was delivered. 

If you or @barttermorshuizen wish to submit a new request, you can do so by filling out [this form](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=feature_request.yml), your feedback is very welcome! 

But we need to separate things, otherwise, we can't track these issues.

I can't promise though that this feature will be considered for the time being.

**Comment by nicholaszein** [comment] 2022-11-23 18:40
@barttermorshuizen,

you can set responsive values for the `Site Settings > Layout > Container Padding` control. These will always apply to all containers unless you specify them otherwise.

![image](https://user-images.githubusercontent.com/113993460/203621853-504b16c3-81b3-4bba-a7b7-582c3f7c5c8d.png)

Here's something you can use globally if you wish to set different padding for parent containers:

````css

.elementor[data-elementor-type] > .e-con {
     padding: 1.25rem;
}
````

You can add whichever value you'd like. This will only affect parent containers inside any document.

**Comment by IMTanuki** [comment] 2022-11-23 20:55
If this is the delivered solution, then the best use of it would be to set the default LR padding to 0px, then manually set the outermost container to whatever device-specific value.

Not sure we've moved the ball here, but if we can set the default to 0 instead sth hard-coded, that's better than nothing.

**Comment by nicholaszein** [comment] 2022-11-29 23:36
@IMTanuki,

when you use Elementor, it wraps all the design inside a `.elementor` tag. If you use containers, they will be the direct child of this tag and will be the parents of any element or container inside them. So if you want, you can use custom CSS to target all these "parent" containers as I shared above using the [Child Combinator](https://developer.mozilla.org/en-US/docs/Web/CSS/Child_combinator) rule.
