### ISSUE TITLE
✅ ⛔ 🧩 Editor is not updating or saving changes (caused by Rank Math)

### ISSUE THREAD

**Issue by Muhammadak47** [elementor/elementor#27401] opened 2024-05-21 04:34 UTC
### Prerequisites

- [X] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [ ] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

Elementor page is not updating when making changes to an existing page. The Update button stays pink, despite the save function aying - saved at timestamp.
In order to save any changes, we have to exit elementor and save it using autosave in wp dashboard. 

<img width="1505" alt="Screenshot 2024-05-21 at 05 26 17" src="https://github.com/elementor/elementor/assets/123341245/9efc4ea1-6365-4096-8523-0cbe83980097">

The is the news website i'm referring to and teh exact page i've added the screenshot to.
[https://wtxnews.com/uk/](url)

### Steps to reproduce

1. Open elementor editor page 
2. make a change
3. Try to save

### Expected behavior

1 it will attempt to save and will stay pink
2. when you log out - the browser will tell you changes have not be saved are you sure you want to exit.
3. save in wp dashboard

### Isolating the problem

- [ ] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [ ] This bug happens with the Hello Elementor theme active.
- [X] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

<details>
<summary>Click to reveal</summary>

````txt

== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Ubuntu 22.04 v10.6.16
	PHP Version: 8.2.19
	PHP Memory Limit: 1024M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 16M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.5.3
	Site URL: https://wtxnews.com
	Home URL: https://wtxnews.com
	WP Multisite: No
	Max Upload Size: 16 MB
	Memory limit: 40M
	Max Memory limit: 1024M
	Permalink Structure: /%postname%/
	Language: en_GB
	Timezone: Europe/London
	Debug Mode: Inactive

== Theme ==
	Name: SmartMag
	Version: 10.0.0
	Author: ThemeSphere
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en-US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36

== Active Plugins ==
	10Web Booster
		Version: 2.27.4
		Author: 10Web - Website speed optimization team

	Ads.txt Manager
		Version: 1.4.3
		Author: 10up

	Akismet Anti-spam: Spam Protection
		Version: 5.3.2
		Author: Automattic - Anti-spam Team

	Asset CleanUp Pro: Page Speed Booster
		Version: 1.2.2.0
		Author: Gabe Livan

	Elementor
		Version: 3.21.5
		Author: Elementor.com

	Elementor Pro
		Version: 3.21.2
		Author: Elementor.com

	Featured Image from URL (FIFU)
		Version: 4.7.6
		Author: fifu.app

	FluentCRM - Marketing Automation For WordPress
		Version: 2.8.45
		Author: WP Email Newsletter Team - FluentCRM

	FluentSMTP
		Version: 2.2.73
		Author: FluentSMTP & WPManageNinja Team

	FS Poster
		Version: 6.5.8
		Author: FS-Code

	MemberPress Basic
		Version: 1.11.29
		Author: Caseproof, LLC

	Rank Math SEO PRO
		Version: 3.0.62
		Author: Rank Math

	Rank Math SEO with AI Best SEO Tools
		Version: 1.0.219
		Author: Rank Math

	Regenerate Thumbnails
		Version: 3.1.6
		Author: Alex Mills (Viper007Bond)

	SmartMag Core
		Version: 1.4.8
		Author: ThemeSphere

	Sphere Core
		Version: 1.6.7
		Author: ThemeSphere

	WordPress Automatic Plugin
		Version: 3.94.0
		Author: ValvePress


== Must-Use Plugins ==
	Asset CleanUp Pro: Plugin Filtering
		Version: 1.0
		Author: Gabriel Livan


== Features ==
	Custom Fonts: 4
	Custom Icons: 0

== Integrations ==
	
	facebook_sdk: Active


== Elementor Experiments ==
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active
	Inline Font Icons: Active
	Additional Custom Breakpoints: Active
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active
	Upgrade Swiper Library: Active by default
	Grid Container: Active
	Nested Elements Performance: Inactive by default
	Optimized Control Loading: Inactive by default
	Default to New Theme Builder: Inactive
	Elementor Home Screen: Active by default
	Editor Top Bar: Inactive
	Build with AI: Inactive
	Landing Pages: Active
	Nested Elements: Inactive
	Lazy Load Background Images: Inactive
	Display Conditions: Inactive by default
	Form Submissions: Active
	Menu: Inactive by default
	Taxonomy Filter: Active


== Log ==
	
Log: showing 20 of 212024-04-25 16:08:31 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.21.2',
  'to' => '3.21.3',
)]
2024-04-26 05:15:39 [info] elementor-pro::elementor_pro_updater Started 
2024-04-26 05:15:39 [info] Elementor Pro/Upgrades - _on_each_version Start  
2024-04-26 05:15:39 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2024-04-26 05:15:39 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.21.0',
  'to' => '3.21.1',
)]
2024-04-26 05:15:39 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.21.0',
  'to' => '3.21.1',
)]
2024-04-26 05:15:40 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.21.0',
  'to' => '3.21.1',
)]
2024-05-01 14:36:23 [info] elementor::elementor_updater Started 
2024-05-01 14:36:23 [info] Elementor/Upgrades - _on_each_version Start  
2024-05-01 14:36:23 [info] Elementor/Upgrades - _on_each_version Finished 
2024-05-01 14:36:23 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.21.3',
  'to' => '3.21.4',
)]
2024-05-01 14:36:25 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.21.3',
  'to' => '3.21.4',
)]
2024-05-01 14:36:28 [info] elementor-pro::elementor_pro_updater Started 
2024-05-01 14:36:28 [info] Elementor Pro/Upgrades - _on_each_version Start  
2024-05-01 14:36:28 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2024-05-01 14:36:28 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.21.1',
  'to' => '3.21.2',
)]
2024-05-08 16:30:03 [info] elementor::elementor_updater Started 
2024-05-08 16:30:03 [info] Elementor/Upgrades - _on_each_version Start  
2024-05-08 16:30:03 [info] Elementor/Upgrades - _on_each_version Finished 
2024-05-08 16:30:03 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.21.4',
  'to' => '3.21.5',
)]

PHP: showing 7 of 7PHP: 2024-04-27 02:12:45 [warning X 5][../wp-content/plugins/elementor/includes/widgets/image-carousel.php::1045] Attempt to read property &quot;post_title&quot; on null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-05-01 14:54:10 [warning X 10][../wp-content/plugins/elementor/core/page-assets/data-managers/font-icon-svg/font-awesome.php::50] Trying to access array offset on value of type null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-05-05 19:01:34 [warning X 2][../wp-content/plugins/elementor/modules/history/revisions-manager.php::363] Undefined array key &quot;editor_post_id&quot; [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-05-05 19:25:23 [warning X 9][../wp-content/plugins/elementor/includes/base/controls-stack.php::1477] Undefined array key &quot;_flex_size_tablet&quot; [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-05-09 15:20:19 [warning X 23][../wp-content/plugins/elementor/core/logger/items/js.php::17] Undefined array key &quot;url&quot; [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-05-10 14:34:51 [warning X 132][../wp-content/plugins/elementor/includes/db.php::267] foreach() argument must be of type array|object, string given [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-05-12 12:39:11 [warning X 1][../wp-content/plugins/elementor/includes/widgets/image-carousel.php::1045] Attempt to read property &quot;post_title&quot; on null [array (
  'trace' => '
#0: ../wp-content/plugins/elementor/includes/widgets/image-carousel.php(1045): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: ../wp-content/plugins/elementor/includes/widgets/image-carousel.php(903): Elementor\Widget_Image_Carousel -> get_image_caption()
#2: ../wp-content/plugins/elementor/includes/base/controls-stack.php(2315): Elementor\Widget_Image_Carousel -> render()
#3: ../wp-content/plugins/elementor/includes/base/widget-base.php(634): Elementor\Controls_Stack -> render_by_mode()
#4: ../wp-content/plugins/elementor/includes/base/widget-base.php(775): Elementor\Widget_Base -> render_content()
',
)]

JS: showing 14 of 14JS: 2024-04-29 05:17:38 [error X 6][../wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.21.3:3:821594] Cannot read properties of undefined (reading &#039;localized&#039;) 
JS: 2024-05-02 09:28:00 [error X 11][../wp-content/plugins/elementor/assets/js/frontend-modules.min.js?ver=3.21.4:2:16853] Cannot read properties of undefined (reading &#039;attributes&#039;) 
JS: 2024-05-04 01:33:30 [error X 1][../wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.21.4:3:326165] Cannot read properties of undefined (reading &#039;id&#039;) 
JS: 2024-05-05 18:05:53 [error X 1][../wp-content/plugins/elementor/assets/js/frontend-modules.min.js?ver=3.21.4:2:10586] Cannot read properties of undefined (reading &#039;autoplay&#039;) 
JS: 2024-05-05 18:09:40 [error X 16][../wp-admin/load-scripts.php?c=0&amp;loadchunk_0=jquery-core,jquery-migrate,utils,wp-polyfill-inert,regenerator-runtime,wp-polyfill,wp-hooks&amp;ver=6.5.2:2:28760] Cannot read properties of undefined (reading &#039;value&#039;) 
JS: 2024-05-05 19:38:27 [error X 1][../wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.21.4:3:1161578] Cannot read properties of null (reading &#039;getBoundingClientRect&#039;) 
JS: 2024-05-09 14:12:05 [error X 1][../wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.21.5:3:821087] Cannot read properties of undefined (reading &#039;toLowerCase&#039;) 
JS: 2024-05-09 14:19:50 [error X 8903][../wp-content/plugins/elementor/assets/lib/pickr/pickr.min.js?ver=1.5.0:2:14799] Cannot read properties of null (reading &#039;clone&#039;) 
JS: 2024-05-09 14:19:51 [error X 166][../wp-content/plugins/elementor/assets/lib/pickr/pickr.min.js?ver=1.5.0:2:19552] Cannot read properties of null (reading &#039;changestop&#039;) 
JS: 2024-05-10 01:17:00 [error X 4][../wp-content/plugins/elementor/assets/js/editor-modules.min.js?ver=3.21.5:3:14246] An invalid argument supplied as multiple control value [array (
  'category' => 'InvalidElementData',
  'tag' => 'Element `smartmag-highlights` got as `css_excerpt_lines` value. Expected array or object.',
)]
JS: 2024-05-10 12:22:54 [error X 8][../wp-content/plugins/tenweb-speed-optimizer/assets/js/two_elementor_editor.js?ver=2.27.4:34:57] Cannot read properties of undefined (reading &#039;background_image&#039;) 
JS: 2024-05-10 13:22:32 [error X 1][../wp-content/plugins/elementor-pro/assets/js/editor.min.js?ver=3.21.2:2:65733] Cannot read properties of undefined (reading &#039;createTemplate&#039;) 
JS: 2024-05-10 13:30:35 [error X 14][../wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.21.5:3:638920] Cannot read properties of undefined (reading &#039;split&#039;) 
JS: 2024-05-14 11:00:42 [error X 2][../wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.21.5:3:683613] elementorFrontend.elements.window.jQuery is not a function 



== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatibility not specified

== Elementor Pro - Compatibility Tag ==

````

</details>

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by nicholaszein** [comment] 2024-05-21 13:44
Hi @Muhammadak47.

This is a known issue caused by Rank Math. Please reach out to Rank Math support.

**Comment by mocana** [comment] 2024-05-29 21:50
Looks like Rank Math is releasing a fix soon, it's in Beta now:

https://rankmath.com/changelog/beta/?_gl=1*1dq8gda*_ga*Mzk0NTA2NjUyLjE3MTIyMDA3NzQ.*_ga_WTF2SQ5LGQ*MTcxNzAxODgxMy40LjEuMTcxNzAxODgxNi41Ny4wLjA.

**Comment by Muhammadak47** [comment] 2024-05-30 10:00
Hi Thank you Mocana, for the update.

Rank Math really are awful and have such a heavy plugin, I think its time to delete it.

**Comment by Muhammadak47** [comment] 2024-05-30 10:05
Maintaining speed on the website with some of these plugins was a real mistake.

Even elementor and Fluent crm and memberpress is full of problems. Should have just built in a simpler way.
It is a vicious circle, you fix one problem and then another one pops up.

One of these plugins goes around in and just drains my resources on the vps [https://wtxnews.com/](url) on this site, eating my system memory and cpu usage to a 100%.

But thanks for your help

**Comment by cKellyDesign** [comment] 2024-07-02 18:47
I don't have Rank Math but I'm experiencing this issue on `v3.22.3`, changes don't get saved and pages are not updated. Strangely, after refreshing the Elementor editor and clicking on a previously updated element in Elementor, the element changes to reflect what I've done, it just won't publish it.

Note: `v3.22.2` produced 500 errors when clicking Update, I'm going to try rolling back to prior versions that actually worked so my client can update their site.

**Comment by nicholaszein** [comment] 2024-07-13 23:17
@cKellyDesign, this is not the same issue, and it's definitely not caused by Elementor. Most likely you have a problem with cache.

You need to troubleshoot your issue by isolating the problem:

1. On a staging website, deactivate all plugins except Elementor and Elementor Pro.
2. Switch your theme to the Hello Elementor theme.
3. Purge, clear, and deactivate all levels of cache, including server, site, cdn, and browser cache (whichever you have on your site).
4. Test on a private/incognito browser.

If after following these steps the problem still persist, reach out to Elementor support.

**Comment by nicholaszein** [comment] 2024-07-13 23:17
This issue was resolved by Rank Math.

Make sure you have the latest version installed.

**Closed by nicholaszein** 2024-07-13 23:17 UTC
Labels: compatibility/3rd-party, editor, solved, mod*
