### ISSUE TITLE
Language files are incomplete since Update to Elementor 3.1.1 an 3.0.10 Pro

### ISSUE THREAD

**Issue by dbfischer** [elementor/elementor#13934] opened 2021-02-16 18:54 UTC
The issue persists.

I just updated another WordPress installation. I have the Pro Expert license and over 20 websites with Elementor Pro on several providers and it's everywhere.

As you can see in German screenshot: "Alle Übersetzungen sind auf dem neuesten Stand." which means "All translations are up to date."
![Screenshot_2021-02-16 WordPress-Aktualisierungen ‹ Maxi-Mode — WordPress](https://user-images.githubusercontent.com/15387379/108107649-cef92200-708f-11eb-9509-24746f73c8ca.png)

see #13910

Since the update to 3.1.1 and 3.0.10 Pro, the translation for German is no longer complete.
I have noticed this on several installations.
For example, the "Save" button is now called "Update".
The settings menu is completely in English instead of German as before.
The same applies to some context menus (right mouse button).
![Screenshot_2021-02-15 Elementor Neuanlage](https://user-images.githubusercontent.com/15387379/108107994-4af36a00-7090-11eb-86f5-657ed06f4a93.png)

**Comment by dbfischer** [comment] 2021-02-17 13:18
Solved with the new version Elementor Pro 3.1.0
Thank you!

**Comment by shilo-ey** [comment] 2021-02-17 13:23
Thanks for updating!

**Comment by dbfischer** [comment] 2021-03-16 09:29
Unfortunately the issue persists in existing installations.
Only in new installations the translations are complete.
In existing installations, elementor-de_DE-*.json files are missing in the language folder /wp-content/languages/plugins.

**Comment by shilo-ey** [comment] 2021-03-16 09:44
Please try to re-install Elementor Pro v3.1.1

**Comment by dbfischer** [comment] 2021-03-16 10:58
When doing this I get a after a short message a white page on URL */wp-admin/admin-post.php?action=elementor_pro_rollback&version=3.1.1&_wpnonce=db6e408830
Going back to dashboard Plugins the Elementor Pro is deactivated. When I activate it, the translation is still incomplete.

**Comment by frdagostino** [comment] 2021-04-01 15:13
I have the same issue as the op (only with Italian instead of German as a language)
It's a wild guess but it looks like the basics function of the free version are correctly translated while the Elementor Pro widgets and funcionalities are not. 

I tried to reinstall Elementor Pro but nothing has changed. I also checked my wordpress installation and the only language files there are the Italian ones.

![Immagine 2021-04-01 143305](https://user-images.githubusercontent.com/22613261/113315375-816a0900-930d-11eb-9160-bd6d66de0582.jpg)

**Comment by frdagostino** [comment] 2021-04-09 11:34
I got back on this issue from the support of Elementor. They're aware of the issue. 
In the meantime you can fix it manually by uploading via FTP the files elementor-pro-it_IT.mo and .po (or de_DE, etc. based on your language) to the folder "wp-content/languages/plugins".

I grabbed mine from another website I had and the fix worked (remains to see what will happen in the next update though).
If somebody needs the italian translations, I can share them.

**Comment by shilo-ey** [comment] 2021-06-29 08:37
@frdagostino @dbfischer Are you still experiencing this issue?

When heading to your WP dashboard > Updates - can you see an update notice there? 
If you try to update it - does it updates correctly?

Thanks

**Comment by shilo-ey** [comment] 2021-06-30 06:10
Update - we are still investigating this issue, thank your for sharing the credentials, it got us one step closer to solving this issue.

Will update soon once the issue is resolved.

**Comment by shilo-ey** [comment] 2021-07-01 08:41
Hey all, the issue is mostly resolved.

Please update here if you still encounter issues.

Keeping this issue open for now.

Thanks!

**Comment by shilo-ey** [comment] 2021-07-27 14:48
This issue has been resolved in our latest versions

Feel free to update

Thanks!

**Closed by shilo-ey** 2021-07-27 14:48 UTC
Labels: status/merged, type/internationalization
