### ISSUE TITLE
Coloured Underline Issue 

### ISSUE THREAD

**Issue by sunra67** [elementor/elementor#13159] opened 2020-11-25 11:37 UTC
Hi there I am trying to change the colour of my underlines site-wide. 

I have followed the information here: https://github.com/elementor/elementor/issues/7553

However this CSS does not work, when placed in the header additional CSS it tells me that the 'text-decoration-color' is unknown property. 

When the CSS is placed in the site CSS, nothing happens 

How can i change the underline color ?

**Comment by DorShahar** [comment] 2020-11-29 14:40
Hi @sunra67 ,
If you are using Internet Explorer, then [this CSS attribute](https://developer.mozilla.org/en-US/docs/Web/CSS/text-decoration-color) is not compatible. 

Please share a screenshot of the CSS in dev-tools and console in order to understand the issue.

**Comment by sunra67** [comment] 2020-11-29 14:49
Hi there, 

I am using chrome. Unsure what you mean by  dev-tools and console. I have put the CSS into the additional CSS within my 'hello elementor' wordpress theme as shown:

![Screenshot 2020-11-29 at 14 47 34](https://user-images.githubusercontent.com/75020888/100545088-fdfeb500-3251-11eb-8e0f-041ce0195b29.png)

**Comment by DorShahar** [comment] 2020-11-30 07:15
I'm not sure why you get an error.
I couldn't reproduce on chorme. 

To open the [dev-tools ](https://developers.google.com/web/tools/chrome-devtools)- if you are in the editor, right-click + CMD and click inspect, else - just right click and choose inspect. you could see if you have errors in the console which could help you diagnose and see the DOM in order to target classes. 

Try to see what is happing with `!important` , and try to use [text-decoration](https://developer.mozilla.org/en-US/docs/Web/CSS/text-decoration).

Since GitHub is not for support, I'm closing the issue.
If you still have trouble - contact our [support](https://elementor.com/support/) team.

Good luck

**Closed by DorShahar** 2020-11-30 07:15 UTC
Labels: status/needs feedback
