### ISSUE TITLE
Elementor Forms

### ISSUE THREAD

**Issue by dendun0318** [elementor/elementor#11614] opened 2020-06-13 11:03 UTC
It would be nice feature to add to Elementor Pro for forms to know how many people filled out forms and capture their email addresses and other information related to form.

Thanks,
Dennis

## Prerequisites

- [ ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by shilo-ey** [comment] 2020-06-14 09:33
Duplicate of #1686

**Closed by shilo-ey** 2020-06-14 09:33 UTC
