### ISSUE TITLE
Elementor Accordeon

### ISSUE THREAD

**Issue by Arisvelperbroek** [elementor/elementor#14456] opened 2021-04-06 19:39 UTC
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest development version of Elementor.

## Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro) with development versions.
- [ ] This bug happens with a vanilla WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by d19dotca** [comment] 2021-04-06 22:45
Seems this is a duplicate of the one filed immediately afterwards (#14457) just a slightly different title and extra details in the other one. This one should be closed if it's supposed to be the same.

**Closed** 2021-04-07 06:19 UTC
