### ISSUE TITLE
⛔ 🛟 Support Request: Problem with free Elementor Image Carousel Arrow Navigation. 

### ISSUE THREAD

**Issue by PowerUser1234** [elementor/elementor#19113] opened 2022-07-08 07:49 UTC
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

I am running **Windows 10 64 bit Home Edition**. My defalt web browser is **Firefox 64 bit v 102.0.1**. I have been using the presently installed and updated **free Elementor version 3.6.7** page builder on a topic page area for my website.
I installed the **Windows XAMPP framework** from the following file name:

**xampp-windows-x64-7.4.27-2-VC15-installer.exe**

and installed and updated to WordPress version 6 from the following file:

**wordpress-5.9.2.zip**

I have updated that WordPress installation so that I am now currently running

**WordPress 6.0**

I installed and got started using WordPress using the following online tutorial:

[https://www.wpbeginner.com/.../how-to-create-a-local.../](https://www.wpbeginner.com/.../how-to-create-a-local.../?fbclid=IwAR1ifF-Xw4Pl3yeUMh4BdcW8-cQN1OJGNsUBdrf-4cIspThOOTO3BclxBlA)

From there I have added and upgraded WordPress itself and the plugins as asked, from which point I have had no problems.
On my Dinosaur Fossils page, I have used the horizontal Image Carousel widget. I can pull the carousel left and right by grasping anywhere on one of the three visible images, but the left and right arrows themselves don't always, consistently, scroll the carousel one image in their particular direction by clicking on one of them.

Is there something simple to be done to get the left and right arrows behaving as expected on my Dinosaur Fossils page?
If the answer is just a simple Javascript or css correction, perhaps this should be submitted to the people who do the free plugin that supplies this Carousel widget?

If more information exchange is needed, please email me at **[Redacted by moderation]!**

![dino-fossils-error](https://user-images.githubusercontent.com/33169528/177943344-a9a344c2-7a9f-479f-9787-ddf5568f7bb2.png)

### Steps to reproduce

Is occuring by default placement, or in my instance of the webpage.  I cannot get the arrows to behave consistently,
crisply, or at all.

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently using the steps above.

### System Info

<details>
<summary>Click to reveal</summary>

````txt




== Server Environment ==
	Operating System: WINNT
	Software: Apache/2.4.52 (Win64) OpenSSL/1.1.1m PHP/7.4.27
	MySQL version: mariadb.org binary distribution v10.4.22
	PHP Version: 7.4.27
	PHP Memory Limit: 512M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 40M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.0
	Site URL: https://localhost:4443/wordpress
	Home URL: https://localhost:4443/wordpress
	WP Multisite: No
	Max Upload Size: 1 GB
	Memory limit: 40M
	Max Memory limit: 512M
	Permalink Structure: /%postname%/
	Language: en-AU
	Timezone: 9.5
	Debug Mode: Inactive

== Theme ==
	Name: Twenty Twenty-One
	Version: 1.6
	Author: the WordPress team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_AU
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:102.0) Gecko/20100101 Firefox/102.0

== Active Plugins ==
	Big File Uploads
		Version: 2.0.3
		Author: Infinite Uploads

	Change Admin Email Setting Without Outbound Email
		Version: 3.1
		Author: John Dee

	Download Plugin
		Version: 2.0.4
		Author: metagauss

	Elementor
		Version: 3.6.7
		Author: Elementor.com

	Essential Addons for Elementor
		Version: 5.1.8
		Author: WPDeveloper

	FileBird Lite
		Version: 5.0.1
		Author: Ninja Team

	Ninja Forms
		Version: 3.6.12
		Author: Saturday Drive

	Remove &quot;Powered by Wordpress&quot;
		Version: 1.4.6
		Author: Webd Ltd

	Responsive Pagination
		Version: 1.4.1
		Author: Bagus Sasikirono

	Shape Dividers Plus
		Version: 1.2.2
		Author: Marcus Burnette

	Wicked Folders
		Version: 2.18.14
		Author: Wicked Plugins

	WPvivid Backup Plugin
		Version: 0.9.74
		Author: WPvivid Team


== Elementor Experiments ==
	Optimized DOM Output: Inactive
	Improved Asset Loading: Inactive
	Improved CSS Loading: Inactive
	Inline Font Icons: Inactive
	Accessibility Improvements: Inactive
	Import Export Template Kit: Inactive
	Additional Custom Breakpoints: Inactive
	Hide native WordPress widgets from search results: Inactive
	: Inactive by default
	Flexbox Container: Inactive
	Landing Pages: Inactive
	Color Sampler: Inactive
	Favorite Widgets: Inactive
	Admin Top Bar: Inactive


== Log ==
	
PHP: showing 4 of 4PHP: 2022-03-15 18:42:45 [notice X 1564][../wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] The $finder_category_name argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-03-26 12:16:18 [notice X 6470][..\wp-content\plugins\elementor\modules\dev-tools\deprecation.php::301] The $control_id argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-03-26 13:18:40 [notice X 6][..\wp-content\plugins\elementor\includes\managers\image.php::87] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-05-25 15:09:35 [notice X 3][..\wp-content\plugins\elementor\core\experiments\experiments-reporter.php::89] Undefined index: title [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

Log: showing 20 of 302022-04-14 14:58:42 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.2',
  'to' => '3.6.4',
)]
2022-04-14 14:58:43 [info] elementor::elementor_updater Started 
2022-04-14 14:58:43 [info] Elementor/Upgrades - _on_each_version Start  
2022-04-14 14:58:43 [info] Elementor/Upgrades - _on_each_version Finished 
2022-04-14 14:58:43 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.2',
  'to' => '3.6.4',
)]
2022-04-30 14:46:17 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.4',
  'to' => '3.6.5',
)]
2022-04-30 14:46:18 [info] elementor::elementor_updater Started 
2022-04-30 14:46:18 [info] Elementor/Upgrades - _on_each_version Start  
2022-04-30 14:46:18 [info] Elementor/Upgrades - _on_each_version Finished 
2022-04-30 14:46:18 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.4',
  'to' => '3.6.5',
)]
2022-06-10 13:35:27 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.5',
  'to' => '3.6.6',
)]
2022-06-10 13:35:28 [info] elementor::elementor_updater Started 
2022-06-10 13:35:28 [info] Elementor/Upgrades - _on_each_version Start  
2022-06-10 13:35:28 [info] Elementor/Upgrades - _on_each_version Finished 
2022-06-10 13:35:28 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.5',
  'to' => '3.6.6',
)]
2022-06-10 13:35:30 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.5',
  'to' => '3.6.6',
)]
2022-07-04 15:13:09 [info] elementor::elementor_updater Started 
2022-07-04 15:13:09 [info] Elementor/Upgrades - _on_each_version Start  
2022-07-04 15:13:09 [info] Elementor/Upgrades - _on_each_version Finished 
2022-07-04 15:13:09 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.6',
  'to' => '3.6.7',
)]

JS: showing 6 of 6JS: 2022-03-26 03:40:17 [error X 3][../wp-content/plugins/elementor/assets/js/editor-modules.min.js?ver=3.6.1:2:20179] An invalid argument supplied as multiple control value [array (
  'category' => 'InvalidElementData',
  'tag' => 'Element `undefined` got as `ma_el_image_gallery_link_one_url` value. Expected array or object.',
)]
JS: 2022-03-26 03:40:17 [error X 3][../wp-content/plugins/elementor/assets/js/editor-modules.min.js?ver=3.6.1:2:20179] An invalid argument supplied as multiple control value [array (
  'category' => 'InvalidElementData',
  'tag' => 'Element `undefined` got as `ma_el_image_gallery_link_two_url` value. Expected array or object.',
)]
JS: 2022-03-31 08:30:53 [error X 1][../wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.6.1:2:363181] this.container is undefined 
JS: 2022-04-05 07:08:06 [error X 1][../wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.6.1:2:338291] this.config.document is undefined 
JS: 2022-04-05 08:40:51 [error X 1][../wp-content/plugins/premium-addons-for-elementor/assets/editor/js/premium-cross-cp.js?ver=4.9.4:13:21] b is null 
JS: 2022-04-07 05:42:15 [error X 6][../wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.6.2:2:0] Permission denied to access property \&quot;elementorFrontend\&quot; on cross-origin object 



== Elementor - Compatibility Tag ==
	
	Essential Addons for Elementor: Compatibility not specified

````

</details>

**Comment by PowerUser1234** [comment] 2022-07-09 02:20
Instead of someone just marking this as a bug or closing this, when seen and read, can someone please reply indicating whether and how this problem can be fixed?  It is an immediate issue for a current web page project.

**Comment by m1ga** [comment] 2022-07-09 09:16
![Screenshot_20220709_111117](https://user-images.githubusercontent.com/4334997/178099516-3caa6f78-191a-499f-9bd9-91510a9d6d17.png)
that was done automatically since you've created a bug issue :wink: Also: there are over 3k issues and most of them don't have or get a reply. So you'll have to be patient or try to use the Facebook group for such questions (since it looks like an implementation issue and not an Elementor bug).

about the image carousel: works fine when I just drag it into a new page and add some images. Do you have any other custom styles or try to disable other plugins that might override stuff (e.g. `Essential Addons for Elementor`). Just Elementor (with non Elementor plugins like caching, backup,...) works fine and I can click on the arrow in both directions with no issues.

**Comment by PowerUser1234** [comment] 2022-07-09 09:26
Dear Michael,

I do have the 'Essential Addons for Elementor' plugin activated,
but I need it on for another feature on another page, so I don't have the option
to disable or uninstall it.

I have posted on the Facebook group, inside the Global Elementor Community
group, which has allowed me to become an active member.

I can't seem to get them to give me an active reply there.  Are you able to
nudge a few people over there for me, to look at my Posts, under my name

Zachary Mitchell

 at

https://www.facebook.com/groups/Elementors/permalink/5002073546585058/

and

https://www.facebook.com/groups/Elementors/


please?

Yours Sincerely,

Zachary Mitchell.

Z.M.
________________________________

**Comment by m1ga** [comment] 2022-07-09 09:32
> I do have the 'Essential Addons for Elementor' plugin activated, but I need it on for another feature on another page, so I don't have the option to disable or uninstall it.

ok, just saw it in the list above. 

> I have posted on the Facebook group,

I'm not in the group and won't join it.


Is it possible to access that page on a webserver? All I can say is that it is working fine here in a blank WP with Elementor and Firefox

https://user-images.githubusercontent.com/4334997/178100130-729efd40-6feb-4f53-ab75-425922620750.mp4

**Comment by PowerUser1234** [comment] 2022-07-09 10:27
Dear Michael,

The trick is, that my website is not on the internet, it is only local, precisely
because it is not finished and still contains bugs and things.

I use the free version of the WPVivid to back up my web page.  I also use WeTransfer
to set up large file transfers across the internet.

Do you have enough bandwidth on your internet, and the ability to install a fresh web page setup
on your copy of WordPress via WPVivid and its zip archives, to just look and edit how I have things,
and reply to me showing me what you have done to fix it?

I use WeTransfer to do this at the moment.  I can also send you the username and password login
you will need for WordPress to login to my web page.  Are you prepared to just take a files archive
internet transfer, install my web page over there, and work to fix my problem?

Yours Sincerely,

Zachary Mitchell.

Z.M.
________________________________

**Comment by m1ga** [comment] 2022-07-09 10:33
upload it to wetransfer and I'll have a quick look. Don't need a username or password, I can add my own to a local instance

**Comment by PowerUser1234** [comment] 2022-07-09 12:07
Dear Michael,

I need a better email for yourself other than just

***@***.***

What email address can I use with WeTransfer?

Zachary.
________________________________

**Comment by m1ga** [comment] 2022-07-09 12:09
I've send you an email. But normally you can just upload a file and just add the link here, without knowing my mail (which is available at my homepage if you click on my profile)

**Comment by PowerUser1234** [comment] 2022-07-09 12:15
Dear Michael,

The WeTransfer email and uploading is on the way.

Zachary Mitchell.
________________________________

**Comment by m1ga** [comment] 2022-07-09 13:34
sorry, don't have any idea what is wrong. But if you just place a new image carousel in your page it works right away:
https://user-images.githubusercontent.com/4334997/178107862-4698d146-22d3-4588-a58b-4d1f03516aee.mp4

So its one of your configurations you've did. Just add it again and you are done.

Also for the next time: please remove the add-ons that aren't used. They are all in the backup and blow up the size without a reason. There was even a 200mb zip with a static file backup include :shrug:

**Comment by nicholaszein** [comment] 2024-08-12 05:23
Hello @PowerUser1234,

Thanks for contacting us, and apologies for the delay in the response! 🙏 

We are currently working hard to make sure every issue on GitHub receives an answer, and we aim to make a faster response in the future, but there are plenty issues, and it's taking longer than expected. We apologize for any inconvenience this may have caused you.

While reading your issue, and checking the conversation you had with @m1ga (thanks Michael, you rock! 💪), and after testing ourselves, we cannot reproduce your issue. Since you posted this a while ago, we can only speculate that it was likely an issue with the settings you've chosen for this particular instance of the Image Carousel widget, or likely a conflict with another plugin. I hope you were able to follow @m1ga's suggestions and create a new Image Carousel, and therefore solving your issue.

👉 Please remember to check the [Help Center](https://elementor.com/help) or contact [Elementor Support](https://elementor.com/contact) before submitting an issue. It usually is very helpful and can solve many of the common issues you may experiment. One example is this article: https://elementor.com/help/changes-dont-appear-online/

❔ If you have questions, or need guidance, help, or general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) The main Facebook group where all kinds of users come together to help each other.
- [Elementor Academy](https://elementor.com/academy) Learn everything you need to know about using Elementor.
- [Elementor Developers Documentation](https://developers.elementor.com/) Learn everything about our Developer-API.
- [Free Support Forum](https://wordpress.org/support/plugin/elementor) Get help on WordPress.org.

💎 If you have an active [Elementor Pro](https://elementor.com/pro) license you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

### ⚠️ As a gentle reminder, **🛟 Support Request issues** may need to be closed without troubleshooting. 
Remember to always follow our **[🐞 Bug Report Guidelines](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&projects=&template=bug.yml)** to save time and ensure smooth troubleshooting.

I am closing this issue as it's not a bug. Thank you for understanding! 🙏 

Kind regards

**Closed by nicholaszein** 2024-08-12 05:23 UTC
Labels: type/ui-ux, component/swiper, type/layout, mod*, widget/image-carousel*, request/support
