### ISSUE TITLE
Linkedin option is not working in social buttons widget

### ISSUE THREAD

**Issue by jainnidhi** [elementor/elementor#10098] opened 2020-01-09 07:09 UTC
Hello team,

Linkedin URL is not working in social buttons widget. It's showing the message 

> I's not you. It's us. Give it another try, please. Try again

Can you please help me out?

**Comment by ideasandpixels** [comment] 2020-03-17 22:25
I'm having the same issue. All of my share buttons work except for LinkedIn. It says: 

> Invalid HTTP Request
Could not process this client request HTTP method request for URL. Please double-check the URL (address) you used, or contact us if you feel you have reached this page in error.

**Comment by shilo-ey** [comment] 2020-03-25 12:06
This issue has been resolved in Elementor v2.9.7
Feel free to update

Thanks!

**Closed by shilo-ey** 2020-03-25 12:06 UTC
Labels: bug, status/merged

**Comment by DouglasTTG** [comment] 2023-08-08 13:38
![image](https://github.com/elementor/elementor/assets/141744546/60f521f3-d3bc-472f-b6e5-ada4bffd061f)
The problem is still happening

**Comment by kuruvi008** [comment] 2024-09-16 06:06
> I'm having the same issue. All of my share buttons work except for LinkedIn. It says:
> 
> > Invalid HTTP Request
> > Could not process this client request HTTP method request for URL. Please double-check the URL (address) you used, or contact us if you feel you have reached this page in error.

I faced the same issue with the LinkedIn share button not working on my site. All other buttons are fine, but LinkedIn doesn’t seem to function. Is there a solution for this problem now?
