### ISSUE TITLE
⛔ 🔗 🐞 Bug Report: Style Guide preview not changing when using clamp function (Duplicate of #22831)

### ISSUE THREAD

**Issue by timovantwout** [elementor/elementor#23499] opened 2023-08-21 13:02 UTC
### Prerequisites

- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

When I use the Elementor website settings and go to global fonts and create a new font and use the clamp function the preview won't update. But when I use pixels it does work.

### Steps to reproduce

1) Site settings
2) Global fonts
3) Add new style
4) Add clamp, example: "clamp(3rem, 2.5385rem + 2.0513vw, 4rem)"
5) Style guide preview wont update

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

<details>
<summary>Click to reveal</summary>

````txt



== Server Environment ==
	Operating System: Linux
	Software: Apache/2
	MySQL version: MariaDB Server v10.6.11
	PHP Version: 8.1.15
	PHP Memory Limit: 2048M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 256M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.3
	Site URL: https://karah.omitdesign.nl
	Home URL: https://karah.omitdesign.nl
	WP Multisite: No
	Max Upload Size: 256 MB
	Memory limit: 40M
	Max Memory limit: 2048M
	Permalink Structure: /blog/%postname%/
	Language: nl-NL
	Timezone: Europe/Amsterdam
	Debug Mode: Inactive

== Theme ==
	Name: Omit Design Child Thema
	Version: 1.0.1
	Author: Elementor Team
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.8.1
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: nl_NL
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36 Edg/115.0.1901.203

== Active Plugins ==
	Elementor
		Version: 3.15.3
		Author: Elementor.com

	Elementor Pro
		Version: 3.15.1
		Author: Elementor.com

	Limit Login Attempts Reloaded
		Version: 2.25.22
		Author: Limit Login Attempts Reloaded

	WPForms
		Version: 1.7.8
		Author: WPForms

	WP Rocket
		Version: 3.14.4.2
		Author: WP Media


== Must-Use Plugins ==
	WordPress automation by Installatron
		Version: 
		Author: 


== Gebruik van elementen ==
	


== Instellingen ==
	
	cpt_support: post, page
	allow_tracking: yes
	font_display: swap


== Features ==
	Custom Fonts: 0
	Custom Icons: 0

== Integrations ==
	


== Elementor experimenten ==
	Geoptimaliseerde DOM-uitvoer: Standaard actief
	Verbeterd laden van assets: Standaard actief
	Verbeterd laden van CSS: Standaard actief
	Pictogrammen inline lettertype: Standaard inactief
	Extra aangepaste onderbrekingspunten: Standaard actief
	admin_menu_rearrangement: Standaard inactief
	Flexbox container: Actief
	Upgrade Swiper bibliotheek: Standaard actief
	Raster container: Actief
	Default to New Theme Builder: Standaard actief
	Hello Theme header &amp; footer: Standaard actief
	Editor top balk: Standaard inactief
	Landingspagina&#039;s: Standaard actief
	Geneste elementen: Actief
	Lazy-load achtergrondafbeeldingen: Standaard inactief
	Globale stijlgids: Standaard actief
	Page Transitions: Standaard actief
	Notes: Standaard actief
	Loop: Standaard actief
	Form Submissions: Standaard actief
	Scroll Snap: Standaard actief
	Menu: Standaard inactief
	Taxonomy Filter: Standaard inactief


== Log ==
	
PHP: showing 1 of 1PHP: 2023-08-14 10:40:59 [notice X 1][/../wp-content/plugins/elementor/core/upgrade/manager.php::63] version_compare(): Passing null to parameter #1 ($version1) of type string is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

Log: showing 10 of 102023-08-21 14:11:18 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.15.2',
  'to' => '3.15.3',
)]
2023-08-21 14:11:24 [info] elementor::elementor_updater Started 
2023-08-21 14:11:24 [info] Elementor/Upgrades - _on_each_version Start  
2023-08-21 14:11:25 [info] Elementor/Upgrades - _on_each_version Finished 
2023-08-21 14:11:25 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.15.2',
  'to' => '3.15.3',
)]
2023-08-21 14:49:35 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.14.1',
  'to' => '3.15.1',
)]
2023-08-21 14:49:35 [info] elementor-pro::elementor_pro_updater Started 
2023-08-21 14:49:35 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-08-21 14:49:35 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-08-21 14:49:35 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.14.1',
  'to' => '3.15.1',
)]



== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatibel

== Elementor Pro - Compatibility Tag ==
	



````

</details>

**Comment by nicholaszein** [comment] 2023-08-22 00:51
Hello @timovantwout!

Thank you for your submission! 🙏 

### 🔗 🐞 This issue is a Duplicate of #22831

Which is on the same subject. 

For this reason, I'm closing this thread and 🔃 **Merging** it with the original, so we can have all the discussions in one location, and deal with it more efficiently.

Feel free to continue the conversation there. 😉 

### 🔍 Please, in the future, remember to check if there isn't any thread similar to yours already opened. 

Kind regards

**Closed by nicholaszein** 2023-08-22 00:51 UTC
Labels: component/control/typography, type/global-style, mod*, component/site-settings/style-guide, component/controls/custom-units
