### ISSUE TITLE
⛔ 🔗 Sections are not hidden by default in Elementor 3.25+ (Duplicate of #29148)

### ISSUE THREAD

**Issue by KuguKot** [elementor/elementor#29369] opened 2024-11-23 01:38 UTC
### Prerequisites

- [X] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [X] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

In Elementor version 3.24.7, the functionality for mobile sections worked as expected. Sections were initially hidden by default, and clicking a button (.showme) would toggle their visibility.

Starting from Elementor version 3.25.0, this functionality has been broken. On mobile, sections are now visible by default upon first page load, even though they are supposed to be hidden.

This issue persists across all versions from 3.25.0 to 3.25.9.

### Steps to reproduce

1.Use the following custom code to add a button for toggling section visibility:

```html
<script>
document.addEventListener('DOMContentLoaded', function() {
    jQuery(function($){
        $('.showme').click(function(){
            $(this).closest('.elementor-section').next().slideToggle();
            $(this).toggleClass('opened');
        });
        $('.closebutton').click(function(){
            $(this).closest('.elementor-section').prev().find('.showme').click();
        });
    });
});
</script>
<style>
.showme a , .showme i , .showme img, .closebutton a, .closebutton i, .closebutton img {
    cursor: pointer;
    -webkit-transition: transform 0.34s ease;
    transition : transform 0.34s ease;
}
.opened i , .opened img , .opened svg {
    transform: rotate(90deg);
}
</style>
```
2. On mobile, ensure the `.showme` button is present and correctly linked to a collapsible section.
3. Load the page in Elementor version 3.24.7 and verify:
-The section is hidden by default.
-Clicking the .showme button toggles the section's visibility.
4.Update Elementor to 3.25.0 or higher.
5.Reload the page and observe:
-The section is visible by default when it should be hidden.

### Expected behavior

The section should be hidden by default on mobile and only displayed when the .showme button is clicked.

### Isolating the problem

- [ ] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [ ] This bug happens with the Hello Elementor theme active.
- [ ] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

<details>
<summary>Click to reveal</summary>

````txt

== Server Environment ==
	Operating System: Linux
	Software: LiteSpeed
	MySQL version: MariaDB Server v10.4.27
	PHP Version: 8.0.30
	PHP Memory Limit: 1024M
	PHP Max Input Vars: 10000
	PHP Max Post Size: 512M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.7.1
	
	WP Multisite: No
	Max Upload Size: 512 MB
	Memory limit: 40M
	Max Memory limit: 1024M
	Permalink Structure: /%postname%/
	Language: pl_PL
	Timezone: Europe/Warsaw
	Debug Mode: Inactive

== Theme ==
	Name: (GeneratePress)
	Version: 
	Author: 
	Child Theme: Yes
	Parent Theme Name: GeneratePress
	Parent Theme Version: 3.5.1
	Parent Theme Author: Tom Usborne

== User ==
	Role: administrator
	WP Profile lang: pl-PL
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36

== Active Plugins ==
	Analytics Insights
		Version: 6.3.8
		Author: DeConf

	BEAR – Bulk Editor and Products Manager Professional for WooCommerce
		Version: 2.1.4.4
		Author: realmag777

	Ceneo Zaufane Opinie
		Version: 1.4.6
		Author: WP Desk

	Code Snippets
		Version: 3.6.5.1
		Author: Code Snippets Pro

	Conditional Shipping for WooCommerce
		Version: 3.1.3
		Author: Lauri Karisola / WP Trio

	Elementor
		Version: 3.24.7
		Author: Elementor.com

	Elementor Pro
		Version: 3.24.4
		Author: Elementor.com

	Flexible Shipping
		Version: 5.0.3
		Author: Octolize

	Flexible Shipping PRO
		Version: 2.19.1
		Author: Octolize

	JetMenu
		Version: 2.4.5
		Author: Crocoblock

	JetSmartFilters
		Version: 3.5.7.1
		Author: Crocoblock

	Kadence WooCommerce Email Designer
		Version: 1.5.13
		Author: Kadence WP

	Modern Image Formats
		Version: 2.3.0
		Author: WordPress Performance Team

	Pay by paynow.pl
		Version: 2.5.7
		Author: mElements S.A.

	Perfmatters
		Version: 2.3.4
		Author: forgemedia

	Post SMTP
		Version: 2.9.11
		Author: Post SMTP

	Query Monitor
		Version: 3.16.4
		Author: John Blackbourn

	Redis Object Cache
		Version: 2.5.4
		Author: Till Krüss

	Schema Pro
		Version: 2.7.23
		Author: Brainstorm Force

	UpdraftPlus - Backup/Restore
		Version: 2.24.11.26
		Author: TeamUpdraft, DavidAnderson

	WooCommerce
		Version: 9.4.2
		Author: Automattic

	WooCommerce Allegro
		Version: 5.2.4
		Author: WP Desk

	WooCommerce Google Merchant XML
		Version: 1.9.14
		Author: WP Desk

	WooCommerce InPost
		Version: 4.6.3
		Author: WP Desk

	WooCommerce Przelewy24 Payment Gateway
		Version: 1.0.27
		Author: Przelewy24 Sp. z o.o.

	WP Rocket
		Version: 3.16.4
		Author: WP Media

	YITH WooCommerce Badge Management Premium
		Version: 3.4.0
		Author: YITH

	YITH WooCommerce Checkout Manager
		Version: 1.36.0
		Author: YITH

	Yoast SEO
		Version: 23.7
		Author: Team Yoast

	Yoast SEO Premium
		Version: 23.7
		Author: Team Yoast


== Must-Use Plugins ==
	Health Check Troubleshooting Mode
		Version: 1.9.1
		Author: 


== Składniki oferty ==
	Custom Fonts: 2
	Custom Icons: 0

== Integracje ==
	
	recaptcha_v3: Aktywny
	woocommerce: Aktywny


== Eksperymenty z Elementorem ==
	Poprawione ładowanie CSS: Domyślnie nieaktywne
	Czcionka ikon: Włączono
	Dodatkowe niestandardowe punkty zmiany: Włączono
	Flexbox Container: Włączono
	Kontener siatki: Domyślnie aktywne
	Upgrade Swiper Library: Włączono
	Nested Elements Performance: Domyślnie aktywne
	Optimized Control Loading: Włączono
	Optimized Markup: Włączono
	Conditionally load Swiper CSS files: Domyślnie nieaktywne
	Plugin Onboarding: Domyślnie aktywne
	Default to New Theme Builder: Włączono
	Elementor Home Screen: Domyślnie aktywne
	Build with AI: Domyślnie aktywne
	Strony docelowe: Włączono
	Launchpad Checklist: Domyślnie nieaktywne
	Elementy zagnieżdżone: Nieaktywne
	Editor Top Bar: Włączono
	Pages Panel: Domyślnie nieaktywne
	Element Caching: Włączono
	Link In Bio: Domyślnie aktywne
	Floating Buttons: Domyślnie aktywne
	Elementor Editor Events: Domyślnie nieaktywne
	Atomic Widgets: Domyślnie nieaktywne
	Wyświetl warunki: Domyślnie aktywne
	Form Submissions: Włączono
	Menu: Nieaktywne


== Elementor - Compatibility Tag ==
	
	Elementor Pro: Kompatybilność nieokreślona

== Elementor Pro - Compatibility Tag ==

````

</details>

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by nicholaszein** [comment] 2024-11-27 22:07
Hello @KuguKot,

Thank you for reaching out! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
In version 3.4.0, released way back in August 2021, we released the new Additional Custom Breakpoints feature, aimed to allow users to use additional breakpoints on their websites. This was a long requested feature, and welcomed by the users.

At the time, [we explained](https://developers.elementor.com/additional-custom-breakpoints-technical-details-and-gotchas/) that we were deprecating the `.elementor-hidden-phone` class used to hide elements in mobile devices and replace it with the more appropriate `.elementor-hidden-mobile` class.

We recommended to everyone using those classes to replace them with the new ones, including addons and 3rd-party plugins.

We also set a [deprecation notice](https://developers.elementor.com/docs/deprecations/) that this class would be removed within the next 8 minor versions of Elementor.

Since then, we released 26 minor versions, and we finally removed this class.

### ✅ What you can do to solve your issue:
- Go to the affected Sections and perform an "off-and-on-again" switch to the **`Hide on Mobile`** option in the Sections' Settings > Advanced tab > Responsive section, to force your sections to update to the new class.
- Alternatively add the following Custom CSS to your Elementor Site Settings, or Customizer:
```css
@media (max-width: 767px) {
    .elementor-hidden-phone {
        display: none;
    }
}
```

### 🔗 🐞 This issue is a Duplicate of #29148

Which is on the same subject. 

🔍 Please, in the future, remember to check if there isn't any thread similar to yours already opened. 

### ⛔ 🧩 Note that while we do welcome bug reports, we can't provide support for custom code such as the script you are using.

I hope this helps.

Kind regards

**Closed by nicholaszein** 2024-11-27 22:07 UTC
Labels: type/responsive, type/styles, mod*, element/section*, widget/settings, compatibility/cache, duplicate
