### ISSUE TITLE
🔗 🐞 Bug Report: Inline Font Icons experiment breaks the Menu Cart icon (Duplicate of #17692)

### ISSUE THREAD

**Issue by Tractorist4romUssr** [elementor/elementor#20581] opened 2022-12-01 00:04 UTC
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Shop icon is not load when svg experiment is on.
More info below.
Thank you

### Steps to reproduce

1. Experiment official page

[elementor.com/help/inline-font-awesome/](https://elementor.com/help/inline-font-awesome/?utm_source=experiments&utm_medium=wp-dash&utm_campaign=learn)

2. Activate experiment
![Screenshot_121](https://user-images.githubusercontent.com/44454639/204931817-4a634525-ea33-4e33-94ab-f0718d975a11.png)

3. Add element of cart widget on page

![Screenshot_124](https://user-images.githubusercontent.com/44454639/204932045-38437dc1-f048-4574-b939-cd5440a0eb3f.png)

4. Watch it

![Screenshot_122](https://user-images.githubusercontent.com/44454639/204931812-9ab235e5-018d-484a-b0a2-2284ef46cef4.png)

5. Deactivate experiment
6. Reload page
7. Watch it

![Screenshot_123](https://user-images.githubusercontent.com/44454639/204932248-560ef0c0-b0d2-49c2-92ff-03d6e4503574.png)

8. anjoy

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.41 (Ubuntu)
	MySQL version: (Ubuntu) v8.0.31
	PHP Version: 7.4.3
	PHP Memory Limit: 128M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 200M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.1.1
	Site URL: https://test2.test
	Home URL: https://test2.test
	WP Multisite: Yes
	Max Upload Size: 125 MB
	Memory limit: 64M
	Max Memory limit: 256M
	Permalink Structure: /%category%/%postname%/
	Language: en-US
	Timezone: 3
	Admin Email: webmaster@test2.test
	Debug Mode: Inactive

== Theme ==
	Name: media
	Version: 1.0.0
	Author: Brainstorm Force
	Child Theme: Yes
	Parent Theme Name: Astra
	Parent Theme Version: 3.7.9
	Parent Theme Author: Brainstorm Force

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:107.0) Gecko/20100101 Firefox/107.0

== Active Plugins ==
	Akismet Anti-Spam
		Version: 4.2.2
		Author: Automattic

	All In One WP Security
		Version: 5.1.1
		Author: All In One WP Security & Firewall Team

	Astra Pro
		Version: 3.6.6
		Author: Brainstorm Force

	Checkout Field Editor for WooCommerce
		Version: 1.8.0
		Author: ThemeHigh

	Elementor
		Version: 3.8.1
		Author: Elementor.com

	Elementor Pro
		Version: 3.8.2
		Author: Elementor.com

	Gravity Forms
		Version: 2.6.8.1
		Author: Gravity Forms

	Gravity Forms User Registration Add-On
		Version: 5.0
		Author: Gravity Forms

	Insert Giphy Block
		Version: 0.1.0
		Author: donMhico

	Nav Menu Roles
		Version: 2.1.0
		Author: Kathy Darling

	Robokassa WooCommerce
		Version: 1.4.1
		Author: Robokassa

	WooCommerce
		Version: 7.1.0
		Author: Automattic

	Woocommerce Advanced Bulk Edit
		Version: 4.3.6
		Author: George Iron

	WOOF - WooCommerce Products Filter
		Version: 3.3.0
		Author: realmag777

	WP All Import - WooCommerce Import Add-On Pro
		Version: 3.3.0
		Author: Soflyy

	WP All Import Pro
		Version: 4.7.1
		Author: Soflyy

	WP Translitera
		Version: p1.2.5
		Author: Evgen Yurchenko

	Yoast SEO Premium
		Version: 12.1
		Author: Team Yoast

== Network Plugins ==
	License Manager for WooCommerce (Free)
		Version: 2.2.8
		Author: LicenseManager

== Elements Usage ==
	
	archive : 1
		archive-posts : 1
		search-form : 1
	footer : 2
		heading : 5
		image : 2
		nav-menu : 3
		social-icons : 1
		text-editor : 2
		theme-site-logo : 1
	header : 4
		icon : 1
		icon-list : 1
		nav-menu : 1
		theme-site-logo : 2
		woocommerce-menu-cart : 1
	page : 5
		divider : 1
		heading : 6
		html : 1
		icon-box : 6
		image : 1
		social-icons : 1
		text-editor : 2
	product : 2
		woocommerce-breadcrumb : 1
		woocommerce-product-add-to-cart : 1
		woocommerce-product-data-tabs : 1
		woocommerce-product-images : 1
		woocommerce-product-meta : 1
		woocommerce-product-price : 1
		woocommerce-product-rating : 1
		woocommerce-product-short-description : 1
		woocommerce-product-title : 1
	section : 14
		divider : 2
		heading : 11
		html : 3
		icon-list : 1
		image : 1
		image-carousel : 1
		search-form : 1
		text-editor : 1
		wc-archive-products : 1
	widget : 0
		woocommerce-menu-cart : 3
	wp-post : 
		button : 10
		heading : 17
		html : 2
		icon : 3
		social-icons : 1
		text-editor : 6
	wp-page : 18
		button : 2
		call-to-action : 1
		heading : 11
		html : 3
		icon : 2
		image : 8
		login : 1
		posts : 1
		search-form : 1
		shortcode : 2
		text-editor : 8
	product-archive : 1
		divider : 1
		heading : 8
		html : 1
		icon-box : 12
		social-icons : 1
		text-editor : 2
		wc-archive-products : 1
	error-404 : 1
		heading : 3
		nav-menu : 1

== Elementor Experiments ==
	Optimized DOM Output: Active
	Improved Asset Loading: Active
	Improved CSS Loading: Active
	Inline Font Icons: Inactive
	Accessibility Improvements: Active
	Additional Custom Breakpoints: Active
	Import Export Website Kit: Active
	Hide native WordPress widgets from search results: Active
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active
	Default to New Theme Builder: Active
	Landing Pages: Active
	Color Sampler: Active
	Favorite Widgets: Active
	Admin Top Bar: Active
	Page Transitions: Active
	Notes: Active
	Loop: Active
	Form Submissions: Active
	Scroll Snap: Active

== Log ==
	
Log: showing 20 of 242022-01-23 23:32:03 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.5.3',
  'to' => '3.5.4',
)]
2022-03-21 00:35:58 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.5.4',
  'to' => '3.5.6',
)]
2022-03-21 00:35:58 [info] elementor::elementor_updater Started 
2022-03-21 00:35:58 [info] Elementor/Upgrades - _on_each_version Start  
2022-03-21 00:36:01 [info] Elementor/Upgrades - _on_each_version Finished 
2022-03-21 00:36:01 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.5.4',
  'to' => '3.5.6',
)]
2022-12-01 02:12:31 [info] elementor-pro::elementor_pro_updater Started 
2022-12-01 02:12:31 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-12-01 02:12:31 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-12-01 02:12:32 [info] Elementor Pro/Upgrades - _v_3_7_2_woocommerce_rename_related_to_related_products Start  
2022-12-01 02:12:32 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.5.6',
  'to' => '3.8.1',
)]
2022-12-01 02:12:32 [info] Elementor Pro/Upgrades - _v_3_7_2_woocommerce_rename_related_to_related_products Finished 
2022-12-01 02:12:32 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.6.4',
  'to' => '3.8.2',
)]
2022-12-01 02:12:32 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.6.4',
  'to' => '3.8.2',
)]
2022-12-01 02:12:32 [info] elementor::elementor_updater Started 
2022-12-01 02:12:32 [info] Elementor/Upgrades - _on_each_version Start  
2022-12-01 02:12:33 [info] Elementor/Upgrades - _on_each_version Finished 
2022-12-01 02:12:33 [info] Elementor/Upgrades - _v_3_8_0_fix_php8_image_custom_size Start  
2022-12-01 02:12:33 [info] Elementor/Upgrades - _v_3_8_0_fix_php8_image_custom_size Finished 
2022-12-01 02:12:33 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.5.6',
  'to' => '3.8.1',
)]

PHP: showing 13 of 13PHP: 2022-01-23 23:19:23 [error X 1][/var/www/www-root/data/www/test2.test/wp-content/plugins/elementor/core/page-assets/loader.php::104] Uncaught Error: Call to undefined function Elementor\Core\Page_Assets\wp_register_style() in /var/www/www-root/data/www/test2.test/wp-content/plugins/elementor/core/page-assets/loader.php:104
Stack trace:
#0 /var/www/www-root/data/www/test2.test/wp-content/plugins/elementor/core/page-assets/loader.php(113): Elementor\Core\Page_Assets\Loader->register_assets()
#1 /var/www/www-root/data/www/test2.test/wp-content/plugins/elementor/includes/plugin.php(726): Elementor\Core\Page_Assets\Loader->__construct()
#2 /var/www/www-root/data/www/test2.test/wp-content/plugins/elementor/includes/plugin.php(636): Elementor\Plugin->init_components()
#3 /var/www/www-root/data/www/test2.test/wp-includes/class-wp-hook.php(303): Elementor\Plugin->init()
#4 /var/www/www-root/data/www/test2.test/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters()
#5 /var/www/www-root/data/www/test2.test/wp-includes/plugin.php(470): WP_Hook->do_action()
#6 /var/www/www-root/data/www/mediaservic [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-02-05 01:58:46 [error X 2][/var/www/www-root/data/www/test2.test/wp-content/plugins/elementor/core/common/modules/ajax/module.php::265] Allowed memory size of 134217728 bytes exhausted (tried to allocate 21702072 bytes) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-02-05 01:59:53 [error X 1][/var/www/www-root/data/www/test2.test/wp-content/plugins/elementor/core/common/modules/ajax/module.php::265] Allowed memory size of 134217728 bytes exhausted (tried to allocate 20569616 bytes) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-03-21 00:34:12 [notice X 622][/var/www/www-root/data/www/test2.test/wp-content/plugins/elementor-pro/license/updater.php::84] Undefined index: new_version [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-03-21 23:00:50 [notice X 85][/var/www/www-root/data/www/test2.test/wp-content/plugins/elementor/core/app/modules/import-export/module.php::91] Trying to get property 'label' of non-object [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-03-21 23:50:55 [error X 2][/var/www/www-root/data/www/test2.test/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::286] Uncaught Error: Call to a member function update_meta() on bool in /var/www/www-root/data/www/test2.test/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:286
Stack trace:
#0 /var/www/www-root/data/www/test2.test/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(167): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions()
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions()
#2 /var/www/www-root/data/www/test2.test/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func()
#3 /var/www/www-root/data/www/test2.test/wp-includes/class-wp-hook.php(307): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request()
#4 /var/www/www-root/data/www/test2.test/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters()
#5 /var/www/www-root/data/www/test2.test/wp-includes/plugin.php( [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-03-23 04:57:59 [notice X 2][/var/www/www-root/data/www/test2.test/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::167] Undefined index: editor_post_id [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-03-26 08:57:00 [notice X 4][/var/www/www-root/data/www/test2.test/wp-content/plugins/elementor-pro/modules/query-control/module.php::748] Trying to get property 'name' of non-object [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-03-26 08:57:23 [notice X 1][/var/www/www-root/data/www/test2.test/wp-content/plugins/elementor-pro/modules/query-control/classes/elementor-post-query.php::229] Undefined property: WP_Error::$taxonomy [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-03-28 15:50:48 [error X 20][/var/www/www-root/data/www/test2.test/wp-content/plugins/elementor-pro/modules/screenshots/module.php::206] Uncaught Requests_Exception_HTTP_403: 403 Forbidden in /var/www/www-root/data/www/test2.test/wp-content/plugins/elementor-pro/modules/screenshots/module.php:206
Stack trace:
#0 /var/www/www-root/data/www/test2.test/wp-content/plugins/elementor-pro/modules/screenshots/module.php(226): ElementorPro\Modules\Screenshots\Module->is_screenshot_proxy_mode()
#1 /var/www/www-root/data/www/test2.test/wp-content/plugins/elementor/core/base/module.php(85): ElementorPro\Modules\Screenshots\Module->__construct()
#2 /var/www/www-root/data/www/test2.test/wp-content/plugins/elementor-pro/core/modules-manager.php(84): Elementor\Core\Base\Module::instance()
#3 /var/www/www-root/data/www/test2.test/wp-content/plugins/elementor-pro/plugin.php(327): ElementorPro\Core\Modules_Manager->__construct()
#4 /var/www/www-root/data/www/test2.test/wp-includes/class-wp-hook.php(307): ElementorPro\Plugin->on_elementor_init()
#5 /var/www/www-root/data/www/test2.test/wp-includes/class-wp-hook.php [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-11-30 06:57:22 [notice X 1][/var/www/www-root/data/www/test2.test/wp-content/plugins/elementor/includes/template-library/classes/class-import-images.php::186] Undefined index: url [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-12-01 02:29:42 [notice X 1][/var/www/www-root/data/www/test2.test/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-12-01 02:36:10 [notice X 2][/var/www/www-root/data/www/test2.test/wp-content/plugins/elementor/modules/usage/module.php::79] Undefined index: publish [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 5 of 5JS: 2022-03-20 20:47:19 [error X 2][https://test2.test/wp-admin/load-scripts.php?c=0&loadchunk_0=jquery-core,jquery-migrate,underscore,backbone,shortcode,utils,wp-util,wp-backbone,media-models,moxiejs,plupload,wp-plupload,jqu&loadchunk_1=ery-ui-core,jquery-ui-mouse,jquery-ui-sortable&ver=5.9.2 line 8 > Function:9:8] settings.link is undefined 
JS: 2022-09-29 20:09:56 [error X 1][https://test2.test/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.5.6:2:349860] elementor.documents.getCurrent() is null 
JS: 2022-10-30 21:55:47 [error X 2][https://test2.test/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.5.6:2:453888] T is null 
JS: 2022-10-30 21:59:56 [error X 3][https://test2.test/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.5.6:2:349044] elementorFrontend.elements.window.jQuery is not a function 
JS: 2022-10-30 21:59:56 [error X 13][https://test2.test/wp-includes/js/mediaelement/mediaelement-and-player.min.js?ver=4.2.16:12:0]  

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatibility not specified

== Elementor Pro - Compatibility Tag ==

**Comment by nicholaszein** [comment] 2022-12-01 12:29
Hello @Tractorist4romUssr!

Thank you for your submission! 🙏 

### 🔗 This issue is a Duplicate of #17692

Which is on the same subject. 

For this reason, I'm closing this issue and 🔃 **Merging** it with the original, so we can have all the discussions in one location, and deal with it more efficiently.

Feel free to continue the conversation there. 😉 

### 🔍 Please, in the future, remember to check if there isn't an issue similar to yours already opened. 

Best regards,

Nick

**Closed by nicholaszein** 2022-12-01 12:29 UTC
Labels: bug, product/pro, component/woocommerce, component/icons, type/experiment
