### ISSUE TITLE
✅ 🐞 Bug Report: Equal height does not work in the loop grid widget if Optimized DOM Output is disabled.

### ISSUE THREAD

**Issue by Michaelgimii** [elementor/elementor#21275] opened 2023-02-09 12:23 UTC
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Hi

As mentioned in the title, if the Optimized DOM Output option is disabled in the settings, the Equal height option will not work in the loop grid widget.

### Steps to reproduce

1- First, make sure Optimized DOM Output is enabled.
2- In the editor, add the loop grid widget and activate the Equal Height option. Rest assured that everything is going according to plan.
3- Now enable the Optimized DOM Output option.
4- Add the loop grid widget again in the editor or view the same widget that you created in step 2.

If you turn on the Equal height option, it will not work.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

[system-info-domain.com-30-01-2023.txt](https://github.com/elementor/elementor/files/10697020/system-info-domain.com-30-01-2023.txt)

**Comment by nicholaszein** [comment] 2023-02-09 19:11
Hello @Michaelgimii,

Thank you for reaching out! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
This is the expected behavior since the equal heights option relies on the content to have fewer DOM elements. When it is not enabled, the calculation can't be made. Since the Optimized DOM Output is a **stable** experiment and is active by default, there is no reason why one should deactivate it, since it's a significant performance improvement.

However, I understand why one would deactivate it.

Since this is really not a bug, I will be closing the issue, but I will discuss it internally to see if we can make the Optimized DOM Output experiment something required for the use of the Loop Builder and Containers going forward.

It's worth mentioning that the experiment in question is only an experiment for backward compatibility (for sites that haven't yet updated their templates). In reality, it should be considered part of the builder, and no one should be deactivating it after activating it. This is what the builder structure will be going forward.

### 👍 For now, that's all we can help with. 

Kind regards

**Closed by nicholaszein** 2023-02-09 19:11 UTC
Labels: status/merged, type/performance, type/layout, widget/loop-builder, solved, type/experiment, mod*

**Comment by nicholaszein** [comment] 2024-03-08 22:14
Hi @Michaelgimii.

As of version 3.19 the `Optimize DOM output` experimental feature was merged into Core, and is now the default and only option for the DOM output. This change was made so we can continue reducing the DOM size from now forward, and we have no plans to remove it.

From our tests using the latest version of Elementor with Sections and Columns, with the merged `Optimize DOM output` experiment active, we see no problem with padding on columns. If you use custom CSS, make sure you follow the instructions in [this article](https://elementor.com/help/what-is-the-optimized-dom/) to adjust it to make it work with the current version.

It's important to emphasize that this experiment was introduced back in 2020, in version 3.0, and was always meant to be merged to Core. We gave our users the option to migrate to the new output on their time, and now, 4 years later, it's time to move forward. With these changes now being part of Core, we can focus on improving the DOM output further, and making Elementor load faster. We hope you can understand.

Kind regards
