### ISSUE TITLE
Mega Menu

### ISSUE THREAD

**Issue by SusanTapper** [elementor/elementor#11760] opened 2020-06-30 01:52 UTC
## Prerequisites

- [ ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by arielk** [comment] 2020-08-07 13:23
Duplicate of https://github.com/elementor/elementor/issues/3275

**Closed by arielk** 2020-08-07 13:23 UTC
Labels: component/nav-menu

**Comment by nicholaszein** [comment] 2023-08-01 17:26
Hello there!

We have great news! 🙌 

### 📢 We're happy to announce the new Menu widget released with Elementor Pro v3.12.0! 🥳 

With the new (nested) Menu widget, you can customize your menus better than ever! 💪 
Drag & Drop widgets to create complex Mega Menus, fine-tune your menu designs, add relevant information, and much more!

This is just the first phase. More customization is coming!

Check out the article here: https://elementor.com/help/the-menu-widget/

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
