### ISSUE TITLE
⛔ Background-repeat option is Missing for the Background Slideshow

### ISSUE THREAD

**Issue by allbut0ne** [elementor/elementor#28663] opened 2024-09-10 12:02 UTC
### Prerequisites

- [ ] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [ ] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

Container > Background Type > Slideshow:
The menu for "repeat / no-repeat" is missing! Therefore all slides are repeated endlessly if you set your slideshow to "contain".

### Steps to reproduce

Set the Container > Background Type > Slideshow.

### Expected behavior

A no-repeat function is needed as it is available for images 

### Isolating the problem

- [ ] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [X] This bug happens with the Hello Elementor theme active.
- [X] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

<details>
<summary>Click to reveal</summary>

````txt


== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Percona Server (GPL), Release '16', Revision '3d64165' v8.0.26-16
	PHP Version: 8.1.20
	PHP Memory Limit: 512M
	PHP Max Input Vars: 8192
	PHP Max Post Size: 64M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.5.5
	Site URL: https://aem24.andre-morre.de
	Home URL: https://aem24.andre-morre.de
	WP Multisite: No
	Max Upload Size: 64 MB
	Memory limit: 40M
	Max Memory limit: 512M
	Permalink Structure: /%postname%/
	Language: de_DE
	Timezone: Europe/Berlin
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor Child
	Version: 1.0.1
	Author: Elementor Team
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 3.1.1
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: en-US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36

== Active Plugins ==
	Admin and Site Enhancements (ASE)
		Version: 7.2.1
		Author: wpase.com

	Admin Menu Editor
		Version: 1.12.4
		Author: Janis Elsts

	Advanced Editor Tools
		Version: 5.9.2
		Author: Automattic

	Branda
		Version: 3.4.19
		Author: WPMU DEV

	Classic Editor
		Version: 1.6.4
		Author: WordPress Contributors

	Crocoblock Wizard
		Version: 1.2.12
		Author: Crocoblock

	Dashboard Widgets Suite
		Version: 3.4.6
		Author: Jeff Starr

	Duplicate Post Page Menu & Custom Post Type
		Version: 2.4.1
		Author: Inqsys Technology

	Duplicator Pro
		Version: 4.5.19
		Author: Duplicator

	Elementor
		Version: 3.23.4
		Author: Elementor.com

	Elementor Pro
		Version: 3.23.3
		Author: Elementor.com

	Fluent Snippets
		Version: 10.34
		Author: Fluent Snippets

	JetBlog For Elementor
		Version: 2.4.0
		Author: Crocoblock

	JetElements For Elementor
		Version: 2.6.20
		Author: Crocoblock

	JetEngine
		Version: 3.5.3
		Author: Crocoblock

	JetTricks
		Version: 1.4.9
		Author: Crocoblock

	Local Google Fonts
		Version: 0.22.0
		Author: EverPress

	Simple History
		Version: 4.17.0
		Author: Pär Thernström

	Simple Post Notes
		Version: 1.7.8
		Author: BracketSpace

	WordPress Importer
		Version: 0.8.2
		Author: wordpressdotorg

	WP-Optimize - Clean, Compress, Cache
		Version: 3.4.2
		Author: David Anderson, Ruhani Rabin, Team Updraft


== Elements Usage ==
	
	container : 7
		button : 4
		container : 10
		heading : 8
		image : 4
	footer : 3
		button : 5
		container : 6
		heading : 3
		icon-box : 2
		image : 1
		nav-menu : 1
		text-editor : 4
	header : 3
		container : 4
		image : 2
		nav-menu : 2
	page : 6
		button : 1
		container : 1
		heading : 2
	popup : 6
		button : 5
		container : 8
		heading : 3
		html : 1
		icon : 1
		text-editor : 4
	wp-post : 0
		button : 2
		container : 292
		gallery : 5
		heading : 83
		html : 1
		icon-list : 1
		image : 10
		jet-bar-chart : 1
		jet-circle-progress : 4
		shortcode : 58
		text-editor : 73
		video : 1
	wp-page : 18
		button : 2
		call-to-action : 15
		container : 207
		counter : 1
		divider : 16
		heading : 167
		html : 10
		icon : 11
		image : 10
		image-carousel : 4
		jet-image-comparison : 1
		jet-slider : 3
		loop-grid : 2
		nested-carousel : 4
		nested-tabs : 1
		shortcode : 5
		taxonomy-filter : 2
		testimonial-carousel : 3
		text-editor : 49
	single-post : 1
		button : 4
		container : 11
		heading : 2
		post-comments : 1
		posts : 1
		text-editor : 1
		theme-post-content : 1
		theme-post-title : 1
	single-page : 9
		button : 2
		container : 34
		divider : 12
		heading : 28
		jet-listing-dynamic-terms : 4
		text-editor : 4
	loop-item : 6
		container : 24
		heading : 10
		image : 1
		jet-listing-grid : 5
		text-editor : 1
	jet-listing-items : 0
		container : 1
		heading : 1


== Settings ==
	
	cpt_support: post, page, projekte
	allow_tracking: yes
	unfiltered_files_upload: 1
	disabled_elements: stripe-button, paypal-button, video-playlist, code-highlight, facebook-page, facebook-embed, facebook-comments, facebook-button, table-of-contents, price-table, price-list, wp-widget-custom_html, wp-widget-tag_cloud, wp-widget-rss, wp-widget-recent-comments, wp-widget-recent-posts, wp-widget-search, wp-widget-meta, wp-widget-media_audio, wp-widget-calendar, audio, alert, social-icons, testimonial, google_maps, inner-section


== Features ==
	Custom Fonts: 0
	Custom Icons: 0

== Integrations ==
	


== Elementor Experiments ==
	Improved CSS Loading: Inactive by default
	Inline Font Icons: Active
	Additional Custom Breakpoints: Active by default
	Flexbox Container: Active
	Grid Container: Active
	Upgrade Swiper Library: Active by default
	Nested Elements Performance: Active by default
	Optimized Control Loading: Inactive by default
	Optimized Markup: Inactive by default
	Plugin Onboarding: Active by default
	Default to New Theme Builder: Inactive
	Header & Footer: Inactive
	Elementor Home Screen: Active by default
	Editor Top Bar: Active
	Build with AI: Active by default
	Landing Pages: Inactive
	Nested Elements: Active
	Lazy Load Background Images: Active by default
	Pages Panel: Inactive by default
	Element Caching: Inactive by default
	Link In Bio: Inactive by default
	Floating Buttons: Active
	Elementor Editor Events: Inactive by default
	Display Conditions: Active
	Form Submissions: Active by default
	Menu: Active
	Taxonomy Filter: Active
	Search: Inactive by default


== Log ==
	
Log: showing 2 of 22024-08-05 23:49:48 [info] Elementor/Upgrades - _on_each_version Finished 
2024-08-05 23:49:48 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.23.3',
  'to' => '3.23.4',
)]

PHP: showing 4 of 4PHP: 2024-08-05 23:49:59 [notice X 448][../wp-content/plugins/elementor/includes/base/controls-stack.php::229] hexdec(): Passing null to parameter #1 ($hex_string) of type string is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-08-27 19:37:06 [warning X 1][../wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::182] Undefined array key "editor_post_id" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-08-28 11:12:01 [warning X 388][../wp-content/plugins/elementor-pro/modules/loop-filter/query/taxonomy-manager.php::150] Undefined array key "logicalJoin" [array (
  'trace' => '
#0: ../wp-content/plugins/elementor-pro/modules/loop-filter/query/taxonomy-manager.php(150): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: ../wp-content/plugins/elementor-pro/modules/loop-filter/query/taxonomy-query-builder.php(33): ElementorPro\Modules\LoopFilter\Query\Taxonomy_Manager -> get_hierarchy_of_selected_terms()
#2: ../wp-content/plugins/elementor-pro/modules/loop-filter/module.php(124): ElementorPro\Modules\LoopFilter\Query\Taxonomy_Query_Builder -> get_merged_queries()
#3: ../wp-includes/class-wp-hook.php(324): ElementorPro\Modules\LoopFilter\Module -> filter_loop_query()
#4: ../wp-includes/plugin.php(205): WP_Hook -> apply_filters()
',
)]
PHP: 2024-09-10 11:11:21 [warning X 10][../wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php::150] Undefined array key "condition_type" [array (
  'trace' => '
#0: ../wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(150): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_template_json_item()
#2: ../wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(120): class type array_map()
#3: ../wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(59): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_templates_json()
#4: ../wp-content/plugins/elementor/data/base/endpoint.php(158): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> get_items()
',
)]

JS: showing 20 of 36JS: 2024-08-31 10:23:59 [error X 7][../wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: "view177") has already been destroyed and cannot be used. 
JS: 2024-08-31 16:24:21 [error X 1][../wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: "view70142") has already been destroyed and cannot be used. 
JS: 2024-08-31 21:18:04 [error X 7][../wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: "view92") has already been destroyed and cannot be used. 
JS: 2024-09-01 10:15:26 [error X 1][../wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: "view9733") has already been destroyed and cannot be used. 
JS: 2024-09-01 10:44:18 [error X 2][../wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: "view124") has already been destroyed and cannot be used. 
JS: 2024-09-01 15:28:42 [error X 5][../wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: "view130") has already been destroyed and cannot be used. 
JS: 2024-09-01 15:28:42 [error X 2][../wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: "view166") has already been destroyed and cannot be used. 
JS: 2024-09-01 18:28:15 [error X 2][../wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: "view168") has already been destroyed and cannot be used. 
JS: 2024-09-01 18:28:36 [error X 4][../wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.23.4:3:663451] Cannot read properties of undefined (reading 'isDesignable') 
JS: 2024-09-01 18:52:00 [error X 1][../wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: "view152") has already been destroyed and cannot be used. 
JS: 2024-09-01 20:20:44 [error X 6][../wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: "view80") has already been destroyed and cannot be used. 
JS: 2024-09-01 20:20:44 [error X 6][../wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: "view118") has already been destroyed and cannot be used. 
JS: 2024-09-01 20:20:44 [error X 1][../wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: "view147") has already been destroyed and cannot be used. 
JS: 2024-09-01 20:37:19 [error X 5][../wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: "view149") has already been destroyed and cannot be used. 
JS: 2024-09-10 08:51:32 [error X 1][../wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: "view8709") has already been destroyed and cannot be used. 
JS: 2024-09-10 08:51:32 [error X 1][../wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: "view8735") has already been destroyed and cannot be used. 
JS: 2024-09-10 08:51:32 [error X 1][../wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: "view8766") has already been destroyed and cannot be used. 
JS: 2024-09-10 08:58:16 [error X 1][../wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: "view1122") has already been destroyed and cannot be used. 
JS: 2024-09-10 08:58:16 [error X 1][../wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: "view1148") has already been destroyed and cannot be used. 
JS: 2024-09-10 08:58:16 [error X 1][../wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: "view1179") has already been destroyed and cannot be used. 



== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatible
	JetBlog For Elementor: Incompatible
	JetElements For Elementor: Incompatible

== Elementor Pro - Compatibility Tag ==
	
	JetBlog For Elementor: Incompatible
	JetElements For Elementor: Incompatible

````

</details>

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

![Bildschirmfoto 2024-09-10 um 13 44 32](https://github.com/user-attachments/assets/98b1cd83-4540-4b6e-9030-d1d1469ad649)

**Comment by nicholaszein** [comment] 2024-09-11 23:05
Hi, @allbut0ne,

Thank you for reaching out! 🙏 

### ⛔ 🚀 This is more of a Feature Request, not a bug. The feature you're referring to is not yet supported.

The Background Slideshow option never had the Background-repeat setting. If a feature is missing, you should open a new Feature Request, so other users can vote and we can consider implementing it.

**I am closing this issue as it's not a bug.**

If you think this should be an Elementor feature, please submit a new [🚀 Feature Request](https://github.com/orgs/elementor/discussions/new?category=feature-request), and we will consider it in the future if there is enough demand (votes) from other users.

Kind regards

**Closed by nicholaszein** 2024-09-11 23:05 UTC
Labels: product/pro, component/swiper, type/styles, type/layout, control/group/background, mod*, widget/settings, mod/r*, mod/i*
