### ISSUE TITLE
🐞 Bug report: Counter widget no longer shows the dynamic content button for starting and ending numbers 

### ISSUE THREAD

**Issue by khag7** [elementor/elementor#19386] opened 2022-08-08 15:30 UTC
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

When I try to use a Counter widget I can enter a starting number and ending number, but there is no longer a button next to the input box that allows me to use dynamic content for that value.

![image](https://user-images.githubusercontent.com/1531746/183455026-21cca782-e28c-4956-8c4b-9fa2b6b192cb.png)

### Steps to reproduce

Fresh install of WP
Install latest version of Elementor (3.7.0)
Create new page, edit with Elementor
Add a Counter widget block
Observe lack of dynamic content button to the right of the "Starting Number" and "Ending Number" inputs

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: WINNT
	Software: nginx/1.16.0
	MySQL version: MySQL Community Server - GPL v8.0.16
	PHP Version: 7.3.5
	PHP Memory Limit: 256M
	PHP Max Input Vars: 4000
	PHP Max Post Size: 1000M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.0.1
	Site URL: Redacted
	Home URL: Redacted
	WP Multisite: No
	Max Upload Size: 300 MB
	Memory limit: 40M
	Max Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 0
	Admin Email: Redacted
	Debug Mode: Inactive

== Theme ==
	Name: Twenty Nineteen
	Version: 2.3
	Author: the WordPress team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 3.7.0
		Author: Elementor.com

== Elementor Experiments ==
	Optimized DOM Output: Active by default
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Active by default
	Additional Custom Breakpoints: Active by default
	Import Export Template Kit: Active by default
	Hide native WordPress widgets from search results: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Inactive by default
	Landing Pages: Active by default
	Color Sampler: Active by default
	Favorite Widgets: Active by default
	Admin Top Bar: Active by default

== Log ==
	

== Elementor - Compatibility Tag ==

**Comment by shilo-ey** [comment] 2022-08-14 08:33
This issue has been resolved in Elementor v3.7.1

Feel free to update

Thanks!

**Closed by shilo-ey** 2022-08-14 08:33 UTC
Labels: bug, component/counter

**Comment by NAROLLES** [comment] 2022-08-14 10:25
The same problem is not solved by the latest version for those who use the flex container

**Comment by mbaierl** [comment] 2022-08-16 10:21
The issue is not yet solved for Flexbox Containers. Still 10px padding.

**Comment by NAROLLES** [comment] 2022-08-16 11:04
> The same problem is not solved by the latest version for those who use the flex container

Hello
The solution concerning padding for flex containers like the rest is in the new function implemented in the site settings. Go to layout settings.

Perhaps it was necessary to inform the community of this new function; It would have avoided a lot of inconvenience
Thanks
