### ISSUE TITLE
🐞 Bug report: Nav Menu is not working on older versions of IOS

### ISSUE THREAD

**Issue by jannelliee** [elementor/elementor#19580] opened 2022-08-24 02:04 UTC
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

The navigation is not working on older IOS versions such as iPhone 6 and iPhone 7. When the hamburger menu is clicked, the dropdown is not showing. It seems like the script is not working properly on these versions of iPhones?

We use the edit nav widget from the elementor itself. 

### Steps to reproduce

Open website on iphone 6 or iphone 7. These are the devices we currently tested.
Open the hamburger menu and see if the dropdown menu shows.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: LiteSpeed
	MySQL version: MySQL Community Server - (GPL) v5.7.38
	PHP Version: 7.4.30
	PHP Memory Limit: 512M
	PHP Max Input Vars: 20000
	PHP Max Post Size: 512M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.0.1
	Site URL: https://foxandlee.com.au
	Home URL: https://foxandlee.com.au
	WP Multisite: No
	Max Upload Size: 512 MB
	Memory limit: 40M
	Max Memory limit: 512M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: Australia/Melbourne
	Admin Email: david@foxandlee.com.au
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor Child
	Version: 2.5.0
	Author: Elementor Team
	Child Theme: Yes

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36

== Active Plugins ==
	Advanced Custom Fields PRO
		Version: 5.12.3
		Author: Delicious Brains

	Akismet Anti-Spam
		Version: 5.0
		Author: Automattic

	Asset CleanUp: Page Speed Booster
		Version: 1.3.8.5
		Author: Gabe Livan

	Better Search Replace
		Version: 1.4.1
		Author: Delicious Brains

	Classic Editor
		Version: 1.6.2
		Author: WordPress Contributors

	Ele Custom Skin
		Version: 3.1.6
		Author: Dudaster.com

	Elementor
		Version: 3.7.2
		Author: Elementor.com

	Elementor Pro
		Version: 3.7.3
		Author: Elementor.com

	FacetWP
		Version: 4.0.6
		Author: FacetWP, LLC

	FacetWP - Flyout menu
		Version: 0.8.1
		Author: FacetWP, LLC

	FacetWP - Monthly
		Version: 2.0.1
		Author: Clément Boirie

	Gravity Forms
		Version: 2.6.5
		Author: Gravity Forms

	Gravity Forms Akismet Add-On
		Version: 1.0
		Author: Gravity Forms

	Gravity Forms Signature Add-On
		Version: 4.3
		Author: Gravity Forms

	iThemes Security
		Version: 8.1.2
		Author: iThemes

	ManageWP - Worker
		Version: 4.9.14
		Author: GoDaddy

	Page Generator Pro
		Version: 3.8.6
		Author: WP Zinc

	Perfect Images (Retina, Thumbnails, Replace)
		Version: 6.2.9
		Author: Jordy Meow

	Post Types Order
		Version: 1.9.9.1
		Author: Nsp Code

	Redirection
		Version: 5.3.2
		Author: John Godley

	ShortPixel Image Optimizer
		Version: 5.0.8
		Author: ShortPixel

	Site Kit by Google
		Version: 1.81.0
		Author: Google

	Super Page Cache for Cloudflare
		Version: 4.6.1
		Author: Optimole

	SVG Support
		Version: 2.4.2
		Author: Benbodhi

	WP Rocket
		Version: 3.11.5
		Author: WP Media

	Yoast Duplicate Post
		Version: 4.5
		Author: Enrico Battocchi & Team Yoast

	Yoast SEO
		Version: 19.5.1
		Author: Team Yoast

	Yoast SEO Premium
		Version: 19.1
		Author: Team Yoast

== Must-Use Plugins ==
	ManageWP - Worker Loader
		Version: 1.0.0
		Author: GoDaddy

	Page Generator Pro: Performance Addon
		Version: 2.9.3
		Author: WP Zinc

	WP Rocket | Disable Page Caching
		Version: 
		Author: Saumya Majumder & WP Rocket Support Team

== Elementor Experiments ==
	Optimized DOM Output: Active
	Improved Asset Loading: Active
	Improved CSS Loading: Inactive by default
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Inactive by default
	Additional Custom Breakpoints: Active
	Import Export Template Kit: Active by default
	Hide native WordPress widgets from search results: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Inactive by default
	Default to New Theme Builder: Active by default
	Hello Theme Header & Footer: Inactive by default
	Landing Pages: Active by default
	Color Sampler: Active by default
	Favorite Widgets: Active by default
	Admin Top Bar: Active by default
	Page Transitions: Active by default
	Notes: Active by default
	Form Submissions: Active by default
	Scroll Snap: Active by default

== Log ==
	
PHP: showing 8 of 8PHP: 2022-06-01 11:53:17 [notice X 54][/home/webproof6/public_html/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] The $control_id argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /home/webproof6/public_html/wp-content/plugins/elementor/modules/dev-tools/deprecation.php(301): class type trigger_error()
#2: /home/webproof6/public_html/wp-content/plugins/elementor/includes/managers/controls.php(523): Elementor\Modules\DevTools\Deprecation -> deprecated_argument()
#3: /home/webproof6/public_html/wp-content/plugins/elementor/includes/managers/controls.php(501): Elementor\Controls_Manager -> register()
#4: /home/webproof6/public_html/wp-content/plugins/page-generator-pro/includes/global/integrations/elementor.php(160): Elementor\Controls_Manager -> register_control()
',
)]
PHP: 2022-06-03 14:38:08 [notice X 4][/home/webproof6/public_html/wp-content/plugins/elementor-pro/modules/posts/skins/skin-content-base.php::264] Trying to get property 'ID' of non-object [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-06-08 12:41:13 [notice X 194][/home/foxandle/public_html/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] The $control_id argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /home/foxandle/public_html/wp-content/plugins/elementor/modules/dev-tools/deprecation.php(301): class type trigger_error()
#2: /home/foxandle/public_html/wp-content/plugins/elementor/includes/managers/controls.php(523): Elementor\Modules\DevTools\Deprecation -> deprecated_argument()
#3: /home/foxandle/public_html/wp-content/plugins/elementor/includes/managers/controls.php(501): Elementor\Controls_Manager -> register()
#4: /home/foxandle/public_html/wp-content/plugins/page-generator-pro/includes/global/integrations/elementor.php(160): Elementor\Controls_Manager -> register_control()
',
)]
PHP: 2022-06-30 15:00:44 [notice X 3][/home/foxandle/public_html/wp-content/plugins/elementor/includes/managers/image.php::87] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-07-23 05:27:07 [notice X 89][/home/foxandle/public_html/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] The $control_id argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /home/foxandle/public_html/wp-content/plugins/elementor/modules/dev-tools/deprecation.php(301): class type trigger_error()
#2: /home/foxandle/public_html/wp-content/plugins/elementor/includes/managers/controls.php(523): Elementor\Modules\DevTools\Deprecation -> deprecated_argument()
#3: /home/foxandle/public_html/wp-content/plugins/elementor/includes/managers/controls.php(501): Elementor\Controls_Manager -> register()
#4: /home/foxandle/public_html/wp-content/plugins/page-generator-pro/includes/global/integrations/elementor.php(163): Elementor\Controls_Manager -> register_control()
',
)]
PHP: 2022-08-09 11:21:05 [notice X 4][/home/foxandle/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-08-09 11:22:04 [notice X 397][/home/foxandle/public_html/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] The $control_id argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-08-18 11:33:33 [notice X 34][/home/foxandle/public_html/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::304] The $control_id argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /home/foxandle/public_html/wp-content/plugins/elementor/modules/dev-tools/deprecation.php(304): class type trigger_error()
#2: /home/foxandle/public_html/wp-content/plugins/elementor/includes/managers/controls.php(523): Elementor\Modules\DevTools\Deprecation -> deprecated_argument()
#3: /home/foxandle/public_html/wp-content/plugins/elementor/includes/managers/controls.php(501): Elementor\Controls_Manager -> register()
#4: /home/foxandle/public_html/wp-content/plugins/page-generator-pro/includes/global/integrations/elementor.php(163): Elementor\Controls_Manager -> register_control()
',
)]

Log: showing 20 of 332022-06-17 13:11:58 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.1',
  'to' => '3.7.2',
)]
2022-08-09 11:19:05 [info] elementor::elementor_updater Started 
2022-08-09 11:19:05 [info] Elementor/Upgrades - _on_each_version Start  
2022-08-09 11:19:05 [info] Elementor/Upgrades - _on_each_version Finished 
2022-08-09 11:19:05 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.6',
  'to' => '3.6.7',
)]
2022-08-18 09:56:00 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.7',
  'to' => '3.7.1',
)]
2022-08-18 09:57:18 [info] elementor::elementor_updater Started 
2022-08-18 09:57:18 [info] Elementor/Upgrades - _on_each_version Start  
2022-08-18 09:57:18 [info] Elementor/Upgrades - _on_each_version Finished 
2022-08-18 09:57:18 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.7',
  'to' => '3.7.1',
)]
2022-08-18 10:05:12 [info] elementor-pro::elementor_pro_updater Started 
2022-08-18 10:05:12 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-08-18 10:05:12 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-08-18 10:05:12 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.2',
  'to' => '3.7.3',
)]
2022-08-18 10:05:12 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.2',
  'to' => '3.7.3',
)]
2022-08-22 14:01:03 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.1',
  'to' => '3.7.2',
)]
2022-08-22 14:01:04 [info] elementor::elementor_updater Started 
2022-08-22 14:01:04 [info] Elementor/Upgrades - _on_each_version Start  
2022-08-22 14:01:04 [info] Elementor/Upgrades - _on_each_version Finished 
2022-08-22 14:01:04 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.1',
  'to' => '3.7.2',
)]

JS: showing 1 of 1JS: 2022-08-19 00:17:46 [error X 1][https://foxandlee.com.au/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.7.1:3:1060434] Cannot read properties of null (reading \'getBoundingClientRect\') 

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatibility not specified

== Elementor Pro - Compatibility Tag ==

**Comment by programmin1** [comment] 2022-08-31 20:00
Probably a duplicate of https://github.com/elementor/elementor/issues/19076 ?

**Comment by rami-elementor** [comment] 2022-09-04 08:28
Duplicate of #19076

**Closed by rami-elementor** 2022-09-04 08:28 UTC
Labels: bug
