### ISSUE TITLE
🔗 🚀 Feature Request: Elementor Pro - add filter bar like Portfolio to Post Archive Widget (Duplicate of #3140)

### ISSUE THREAD

**Issue by lgsween** [elementor/elementor#11780] opened 2020-07-02 15:59 UTC
I saw similar request on previous occasion but cannot find it now. First time on Git Hub and it is confusing. So...

Elementor Pro has a filter bar in the Portfolio options. It is NOT available for the Posts/Post Archive Widgets. 

I do a lot of work with companies that produce a lot of products, articles, news, publications, presentations, etc. and the filter is a great tool. I have been using Content Views Pro, which I like a lot. It has the filter bar and I use it quite often. (It also doesn't bounce to top of the page like some of the Elementor items do when you sort or refresh.)

Reasons I would prefer to have the filter bar in Elementor are 1) always better to have fewer software products on a site; 2) less confusing for any clients that would edit their own site after launch; 3) the responsive controls in Elementor are superior, requiring less coding; 4) many of the other options are quite good also (such as customization of Read More text).

I am primarily a designer, so I do some CSS and some HTML, but not really PHP or JS. Someone said they were able to clone the filter bar function from the Portfolio to the Post/Post Archive Widget. I can't do that myself. This seems like it ought to be an easy update for you. 

Why is this NOT a standard feature for the posts? Giving visitors the ability to sort through large quantities of information in a clear and logical way is a key feature to keep them coming back to a site as a great resource.

I may try some of the filter plugins listed on your site, but I am trying to cut down on the number of software products on the site, not keep adding them.

Thanks,

Linda S

**Comment by ex-avenger** [comment] 2020-07-02 17:41
+1 It would be good if you can add a drop down filter to Post Archive by using taxonomiesl.

**Comment by black-eye** [comment] 2020-07-02 20:23
@lgsween, welcome to the club! ;) 

This is the original request: #3140 
- 2 years and 6 months old
- 110 comments
- 76 participants
- 0 reactions from the dev team. 

This is how Elementor team treats the users' feedback in a nutshell. This is the reality vs PR proclamations.

Nevertheless, no big deal for me anymore since the time I've bought lifetime licence of [Extras for Elementor](https://shop.namogo.com/product/extras-elementor/). Their [post widget](https://shop.namogo.com/elementor-extras/widgets/posts/) is much more powerful than Elementor's, which is, to be honest, basicaly usesless anyway.

**Comment by fabianenzensperger** [comment] 2020-07-06 16:23
> @lgsween, welcome to the club! ;)
> 
> This is the original request: #3140
> 
> * 2 years and 6 months old
> * 110 comments
> * 76 participants
> * 0 reactions from the dev team.
> 
> This is how Elementor team treats the users' feedback in a nutshell. This is the reality vs PR proclamations.
> 
> Nevertheless, no big deal for me anymore since the time I've bought lifetime licence of [Extras for Elementor](https://shop.namogo.com/product/extras-elementor/). Their [post widget](https://shop.namogo.com/elementor-extras/widgets/posts/) is much more powerful than Elementor's, which is, to be honest, basicaly usesless anyway.

It's a shame from Elementor!

I also use the tool you mentioned. I would like to take that from Elementor, unfortunately I am forced to do so because I use more functions. **Sometimes Elementor isn't PRO**.

**Comment by nashmiweb** [comment] 2020-07-15 08:05
+1

**Comment by fabianenzensperger** [comment] 2020-07-15 09:49
Can anyone tell me how to label this feature request? On the Macbook, I don't have a checkbox in the issue overview to the left of the icon to select it and then label it. Thanks for help!

**Comment by EmerKelly** [comment] 2022-03-26 21:23
+1

**Comment by nicholaszein** [comment] 2022-11-09 14:41
Hey there!

Thank you for your submission! 🙏 

### 🔗 This issue is a Duplicate of #3140

Which is on the same subject. 

As @bainternet said, this issue has been 🔃 **Merged** with the original, so we can have all the discussions in one location, and deal with it more efficiently.

Feel free to continue the conversation there. 😉 

Best regards,

Nick

**Closed by nicholaszein** 2022-11-09 14:41 UTC
Labels: request/enhancement, product/pro, component/posts
