### ISSUE TITLE
Icons Font Display Swap

### ISSUE THREAD

**Issue by jonathansoltero** [elementor/elementor#10095] opened 2020-01-08 22:18 UTC
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
PageSpeed Insights "Ensure text remains visible during webfont load" Fonts being loaded by Elementor such as the icons are causing a 1-second delay in load time.

I am not referring to custom fonts from Elementer Pro, I am referring to the bundled icons/fonts with Elementor, paths such as:

```
/elem/assets/lib/font-awesome/webfonts/fa-solid-900.woff2
/elem/assets/lib/eicons/fonts/eicons.woff2?5.5.0
```

**Describe the solution you'd like**
Adding `font-display: swap;` 

Update: Font Awesome did this themselves, just update to the latest version 5.15

**Describe alternatives you've considered**
I have added the code in myself but they were removed after the update. I don't want to keep manually adding the font display.

**Additional context**

**Comment by EdwardBlack** [comment] 2020-01-19 15:10
+1 for that Issue.

Even though you don't reference the custom uploaded fonts, there should also be an option to select what font-display-attribute you want to use in the interface.

**Comment by stannvanheusden** [comment] 2020-01-21 09:06
I second this. Not only for internal fonts: also for Google Fonts, TypeKit etc.

**Comment by jdub850000** [comment] 2020-02-25 14:06
Thirded!

**Comment by dineshmistry** [comment] 2020-03-26 15:34
Fourth!

**Comment by draconnia** [comment] 2020-07-15 09:28
On the one hand  **Lighthouse**  tells us to use  `font-display: swap` and delays the load
On the other hand, we are told that  `font-display: swap` is not ideal for an icon font, because there's no benefit in showing the character in a fallback typeface.
What can we do?

**Comment by visrey** [comment] 2020-10-05 21:42
I think this issue is fixed in the latest release of font awesome refer the ticket
 
https://github.com/FortAwesome/Font-Awesome/issues/16077

Upgrading the font-awesome version should fix the issue.

**Comment by jonathansoltero** [comment] 2020-10-29 03:41
> I think this issue is fixed in the latest release of font awesome refer the ticket
> 
> [FortAwesome/Font-Awesome#16077](https://github.com/FortAwesome/Font-Awesome/issues/16077)
> 
> Upgrading the font-awesome version to 5.13 should fix the issue.

What version is Elementor on now?

**Comment by jonathansoltero** [comment] 2020-10-29 03:56
Can we also consider adding <link rel=preload>

**Comment by visrey** [comment] 2020-10-30 14:24
![Screenshot 2020-10-30 at 7 54 02 PM](https://user-images.githubusercontent.com/12045221/97716484-aaca0300-1ae9-11eb-90cd-547953a5bfec.png)

I have replaced the copies locally in my wordpress and it worked 👍

**Comment by shaneonabike** [comment] 2020-11-09 19:44
Also there is already a hook for this so we simply need to append `display=swap` or whatever setting we wish and Google creates the appropriate css. I attempted to override the existing stylesheet but it seems to never make it in the enqueue even when I set my priority super low :/

Please this would be a super easy change to hook into your existing filter created for local fonts.

**Comment by visrey** [comment] 2020-11-15 08:28
It won't work the way you think display=swap won't work for font-awesome.
Understand the issue with font-awesome before suggesting the solution.
Actual issue and solution can be found in the issue created at font-awesome
https://github.com/FortAwesome/Font-Awesome/issues/16077

**Comment by shaneonabike** [comment] 2020-11-16 12:55
I saw that there were other comments relating to this being added for Google fonts too so that's why I added my comment. Maybe could I suggest you change the ticket title so that it's more clear that it relates to icons? Or just Font Awesome. Cause really it's not solved and the title implies more of a global (applies to all not covered) approach?

**Comment by jonathansoltero** [comment] 2020-11-16 19:33
> I saw that there were other comments relating to this being added for Google fonts too so that's why I added my comment. Maybe could I suggest you change the ticket title so that it's more clear that it relates to icons? Or just Font Awesome. Cause really it's not solved and the title implies more of a global (applies to all not covered) approach?

There I have added Icons to the title, like visrey said, Font Awesome has already done the updates to make lighthouse happy, Elementor just needs to stay up to date, Font Awesome resolved this in March.

**Comment by shilo-ey** [comment] 2021-03-21 14:45
This feature has been released in Elementor v3.1.

Please feel free to update

**Closed by shilo-ey** 2021-03-21 14:45 UTC
Labels: request/enhancement, type/performance

**Comment by joshcummingsdesign** [comment] 2021-04-15 23:39
This issue still exists for `assets/fonts/eicons.woff2?5.11.0`. Confirmed that adding `font-display: swap` resolves the `Ensure text remains visible during webfont load` issue in Lighthouse. Happy to make a PR if this is a valid solution.

**Comment by pavosdijital** [comment] 2021-05-06 13:12
> This issue still exists for Elementor icons.
> 
> Running Lighthouse shows the following:
> 
> ```
> Ensure text remains visible during webfont load
> ../fonts/eicons.woff2?5.11.0
> ```
> 
> Confirmed that adding `font-display: swap` to the `@font-face` rule in `elementor-icons.css` resolves the issue. Happy to make a PR if this is a valid solution.

Can you please write the code exactly how it should be so I can add to my website. I am not very familiar with coding so your help is most appreciated. thank you

**Comment by berkmh** [comment] 2021-05-06 15:32
> > This issue still exists for Elementor icons.
> > Running Lighthouse shows the following:
> > ```
> > Ensure text remains visible during webfont load
> > ../fonts/eicons.woff2?5.11.0
> > ```
> > 
> > 
> > Confirmed that adding `font-display: swap` to the `@font-face` rule in `elementor-icons.css` resolves the issue. Happy to make a PR if this is a valid solution.
> 
> Can you please write the code exactly how it should be so I can add to my website. I am not very familiar with coding so your help is most appreciated. thank you

+ 1

**Comment by JennyPower** [comment] 2021-05-11 09:56
Confirmed still an issue

**Comment by Holland1** [comment] 2021-05-18 19:54
Indeed, still an issue. Hope this will be fixed soon

**Comment by joshcummingsdesign** [comment] 2021-05-19 22:06
I created #15014 to resolve this issue.

**Comment by jkplkjm** [comment] 2021-06-03 23:27
> I created #15014 to resolve this issue.

I tried this directly modifying the css and .min.css files under wp-content/plugins/elementor/assets/lib/eicons/css/  however, it didn't work. I'm not entirely sure why, but my browser is requesting the .woff2 icons with query parameter ?5.10.0 instead of ?5.11.0, and it doesn't work even when adding the new urls.

**Comment by yerba69** [comment] 2021-06-11 15:31
> > I created #15014 to resolve this issue.
> 
> I tried this directly modifying the css and .min.css files under wp-content/plugins/elementor/assets/lib/eicons/css/ however, it didn't work. I'm not entirely sure why, but my browser is requesting the .woff2 icons with query parameter ?5.10.0 instead of ?5.11.0, and it doesn't work even when adding the new urls.

I'm having the same issue on my end.

**Comment by jonathansoltero** [comment] 2021-06-13 21:42
> > I created #15014 to resolve this issue.
> 
> I tried this directly modifying the css and .min.css files under wp-content/plugins/elementor/assets/lib/eicons/css/ however, it didn't work. I'm not entirely sure why, but my browser is requesting the .woff2 icons with query parameter ?5.10.0 instead of ?5.11.0, and it doesn't work even when adding the new URLs.

               Yeah same here, it seems to only show up for mobile

**Comment by jonathansoltero** [comment] 2021-06-22 19:05
Nevermind it looks like it's also affecting desktop

**Comment by StiefTschobbs** [comment] 2021-06-25 08:46
It affects desktop and mobile for my website.. all changes on the .css & min.css do not change anything.. so how could we tackle that issue?

**Comment by Hynek-O** [comment] 2021-07-07 10:28
Confirmed still an issue.

**Comment by oliveandlake** [comment] 2021-09-03 14:00
Yes, also still getting this error. Seems to be no way to remove eicons.

**Comment by shilo-ey** [comment] 2021-09-05 05:57
We are planning on releasing a new e-icons loading method that will eliminate this issue (inline SVG)

Thanks

**Comment by rafaviana** [comment] 2021-09-09 10:09
> We are planning on releasing a new e-icons loading method that will eliminate this issue (inline SVG)
> 
> Thanks

Great news! Looking for it 😉

**Comment by EXECdesign** [comment] 2021-11-12 07:39
https://github.com/elementor/elementor/pull/15897
Still the same issues in EP 3.5.1: eicons.woff2?5.10.0 gets loaded, Google Lighthouse test fails.

**Comment by llavillaccama** [comment] 2021-11-24 14:27
Same problem someone managed to fix it

**Comment by alibori** [comment] 2021-12-03 14:15
Hello!
Same problem with eicons on Page Speed Insights.

**Comment by jonathansoltero** [comment] 2021-12-09 07:12
Yeah still not fixed.

**Comment by yerba69** [comment] 2021-12-16 17:49
Issue looks to be resolved in the most recent version of Elementor 😎

**Comment by Salimoh** [comment] 2021-12-18 16:29
Does anybody else have problem with the cart icon after this update?
 Cart icon no longer show in [my client website](iranbatri.com)

**Comment by yerba69** [comment] 2021-12-18 17:20
Just noticed that as well…..

>

**Comment by EXECdesign** [comment] 2021-12-20 08:25
This is what I get by testing Elementor 3.5.0:
![wp582-ep352-ep350-php80](https://user-images.githubusercontent.com/40740207/146735311-3e0e7704-e7ce-4f2f-9f03-f2142dd5c394.png)

It's a very slim site with WP 5.8.2 and EP 3.5.2 running with PHP 8.0.13.
After rollback to Elementor 3.4.8 everything works fine again instantly.

What can be so difficult regarding those Eicons that there's another trouble about it update after update?

**Comment by tamal-sen** [comment] 2022-04-07 14:51
Hope the fix will be implemented soon. I have tried the Inline SVG method which is currently in alpha stage. That messed up my fonts so I had to revert.

**Comment by asfo** [comment] 2023-06-17 23:45
So, this was closed but not fixed? I mean I'm posting this on June 17, 2023 and the issue is still there ...any workaround here?

**Comment by JanWebofka** [comment] 2023-10-09 21:35
Hello,

/wp-content/plugins/elementor/assets/lib/eicons/fonts/eicons.woff2?5.23.0

still issue.
