### ISSUE TITLE
⛔ TOC in Popup always shows "No headings were found on this page." message if no container is selected

### ISSUE THREAD

**Issue by jomawie** [elementor/elementor#11301] opened 2020-05-05 16:34 UTC
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

I'm using an Elementor-popup with the TOC Widget inside. The popup itself works fine but since the last version of Elementor (2.9.8 / 2.9.3 pro) the TOC widget always shows the "No headings were found on this page." message. It worked fine with previous versions of Elementor. 
## Steps to reproduce

- Popup created (Templates > Popup)
- Placed Social Sharing Widget & TOC Widget inside the popup
- Trigger popup with a button that is placed in the previously created single template for blog posts

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: (Ubuntu) v5.7.28
	PHP Version: 7.2.24-nmm1
	PHP Max Input Vars: 3000
	PHP Max Post Size: 200M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.4.1
	WP Multisite: No
	Max Upload Size: 200 MB
	Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: de-DE
	Timezone: Europe/Berlin
	Debug Mode: Inactive

== Theme ==
	Name: 
	Version: 
	Author: 
	Child Theme: Yes

== User ==
	Role: administrator
	WP Profile lang: de_DE
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36

== Active Plugins ==
	Borlabs Cookie - Cookie Opt-in
		Version: 2.1.15
		Author: Benjamin A. Bornschein, Borlabs

	Code Snippets
		Version: 2.14.0
		Author: Code Snippets Pro

	Coming Soon Page, Under Construction & Maintenance Mode by SeedProd
		Version: 5.1.0
		Author: SeedProd

	Custom Post Type UI
		Version: 1.7.4
		Author: WebDevStudios

	Elementor
		Version: 2.9.8
		Author: Elementor.com

	Elementor Pro
		Version: 2.9.3
		Author: Elementor.com

	Full Screen Menu for Elementor
		Version: 1.0.3
		Author: Solitweb

	Image optimization service by Optimole
		Version: 2.3.1
		Author: Optimole

	Insert Headers and Footers
		Version: 1.4.5
		Author: WPBeginner

	JetElements For Elementor
		Version: 2.2.14
		Author: Crocoblock

	JetTricks
		Version: 1.2.8
		Author: Crocoblock

	Livemesh Addons for Elementor
		Version: 2.9.9
		Author: Livemesh

	Post Type Switcher
		Version: 3.2.0
		Author: John James Jacoby

	PowerPack Lite for Elementor
		Version: 1.2.9.3
		Author: IdeaBox Creations

	Rank Math SEO
		Version: 1.0.42.3
		Author: Rank Math

	Really Simple SSL
		Version: 3.3.1
		Author: Rogier Lankhorst, Mark Wolters

	SVG Support
		Version: 2.3.18
		Author: Benbodhi

	Unlimited Elements for Elementor
		Version: 1.4.33
		Author: Unlimited Elements

	WP Rocket
		Version: 3.5.4
		Author: WP Media

== Elements Usage ==
	
	archive : 3
		heading : 1
		lae-portfolio : 1
		text-editor : 1
	footer : 1
		form : 1
		heading : 2
		text-editor : 5
	header : 7
		icon : 2
	page : 18
		button : 1
		heading : 3
		image : 7
		post-navigation : 1
		text-editor : 2
	popup : 2
		heading : 1
		html : 2
		nav-menu : 1
		share-buttons : 1
		table-of-contents : 1
	single : 7
		button : 3
		counter : 1
		heading : 2
		image : 1
		theme-post-content : 1
	wp-post : 5
		divider : 1
		gallery : 10
		heading : 20
		html : 1
		image : 65
		post-navigation : 20
		price-table : 2
		text-editor : 37
		toggle : 1
	wp-page : 11
		button : 4
		call-to-action : 1
		heading : 29
		html : 2
		icon : 4
		image : 12
		jet-unfold : 18
		portfolio : 1
		text-editor : 24

				
</details>

**Comment by chungtinghsiao** [comment] 2020-06-11 08:07
Same issue here after I upgraded to the newer version of Elementor Pro (v2.10.0 currently).

**Comment by mhr88** [comment] 2022-12-21 09:49
Been 2 years and still open. Anyone fixed this issue? I have the same problem now. 
Using version 3.9.1.

**Comment by Duuble-U** [comment] 2023-11-02 16:15
+1
It's a detail but, yes it's not smart for user experience.
I often use this tool so I hope it will be fixed.

**Comment by samuelmente** [comment] 2024-02-12 20:33
I also ran into this issue today. Are there any workarounds?

**Comment by nicholaszein** [comment] 2024-11-22 21:41
Hi everyone!

Thank you for reaching out, and for being so patient! 🙏 

We are in the process or organizing our GitHub repository, and it's time to talk about this issue.

To make the **Table of Contents** widget to work inside a Popup, you need to specify a **`Container`** in which your Headings are going to be located. You can do it by adding a CSS ID or Class to the container where the content is, and reference it in the ToC widget. This way the widget knows where to look. Otherwise it won't show anything, as Popups are loaded Dynamically after the page has already loaded, making the ToC widget to try to look for content inside the Popup, not in the page.

Alternatively, you can use the new Off-Canvas widget inside the page have the same effect.

In the video below you can see both examples in action:

https://github.com/user-attachments/assets/666e1eeb-27bf-4489-8cef-cd69008e61c1

Since this is working as expected, we consider this issue not a bug, therefore we are closing it!

Thank you for sharing your feedback!

Kind regards

**Closed by nicholaszein** 2024-11-22 21:41 UTC
Labels: popups, widget/table-of-contents, solved-by/nested, mod*
