### ISSUE TITLE
⛔ 📎 🧩 🐞 Bug Report: Elementor Pro - Mini cart - widget_shopping_cart_content showing empty data (Duplicate of #22789) 

### ISSUE THREAD

**Issue by webtories** [elementor/elementor#22800] opened 2023-06-17 10:16 UTC
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Dear Elementor Team,
I saw the closest issue https://github.com/elementor/elementor/issues/21836 and I try ti open new issue, because still not working for my websites.

Problem is that MENU CART widget not showing product items in cart, if the products are in carts, see:

![image](https://github.com/elementor/elementor/assets/135512952/bbb6f7a0-c91f-4edb-8147-1d39d3772d2f)

You can use it at test website https://chktpcom.webtories.cz/

### Steps to reproduce

1. Follow for example https://chktpcom.webtories.cz/produkt/camo-panske-funkcni-triko/
2. Added variant into cart
3. Hover the cart ikon ==> mini cart is still empty

I looked the problem and I found this method render_menu_cart:

`
	/**
	 * Render Menu Cart
	 *
	 * The `widget_shopping_cart_content` div will be populated by woocommerce js.
	 *
	 * When in the editor we populate this on page load as we can't rely on the woocoommerce js to re-add the fragments
	 * each time a widget us re-rendered.
	 */
	public static function render_menu_cart( $settings ) {
		if ( null === WC()->cart ) {
			return;
		}

		$widget_cart_is_hidden = apply_filters( 'woocommerce_widget_cart_is_hidden', false );
		$is_edit_mode = Plugin::elementor()->editor->is_edit_mode();
		?>
		<div class="elementor-menu-cart__wrapper">
			<?php if ( ! $widget_cart_is_hidden ) : ?>
				<div class="elementor-menu-cart__toggle_wrapper">
					<div class="elementor-menu-cart__container elementor-lightbox" aria-hidden="true">
						<div class="elementor-menu-cart__main" aria-hidden="true">
							<?php self::render_menu_cart_close_button( $settings ); ?>
							<div class="widget_shopping_cart_content">
								<?php if ( $is_edit_mode ) {
                                   // error_log(print_r("Calling woocommerce_mini_cart - custom log ==> Silence is gold, isnt it ?!!!!", true));
									woocommerce_mini_cart();
								} ?>
							</div>
						</div>
					</div>
					<?php self::render_menu_cart_toggle_button( $settings ); ?>
				</div>
			<?php endif; ?>
		</div> 
		<?php
	}
`

If i changed the condition for if ( $is_edit_mode ) to  if ( **!** $is_edit_mode ) mini cart is rendered. For me is the HOT fix, but I need to system plugin support from us.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Source distribution v5.6.46-86.2
	PHP Version: 7.4.33
	PHP Memory Limit: 512M
	PHP Max Input Vars: 10000
	PHP Max Post Size: 256M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.2.2
	Site URL: https://chktpcom.webtories.cz
	Home URL: https://chktpcom.webtories.cz
	WP Multisite: No
	Max Upload Size: 256 MB
	Memory limit: 512M
	Max Memory limit: 512M
	Permalink Structure: /%postname%/
	Language: cs
	Timezone: Europe/Prague
	Admin Email: zbynek.simek@outlook.com
	Debug Mode: Active

== Theme ==
	Name: the7dtchild
	Version: 1.0.0
	Author: Dream-Theme
	Child Theme: Yes
	Parent Theme Name: The7
	Parent Theme Version: 11.2.2
	Parent Theme Author: Dream-Theme

== User ==
	Role: administrator
	WP Profile lang: cs_CZ
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36

== Active Plugins ==
	Advanced Order Export For WooCommerce
		Version: 3.4.0
		Author: AlgolPlus

	Booster for WooCommerce
		Version: 6.0.6
		Author: Pluggabl LLC

	Choketopus Email Flow
		Version: 2.0.0
		Author: Webtories s.r.o

	Elementor
		Version: 3.13.4
		Author: Elementor.com

	Elementor Pro
		Version: 3.13.2
		Author: Elementor.com

	GTM4WP
		Version: 1.16.2
		Author: Thomas Geiger

	Maintenance
		Version: 4.07
		Author: WebFactory Ltd

	PDF Invoices &amp; Packing Slips for WooCommerce
		Version: 3.5.5
		Author: WP Overnight

	Product Size Chart for Woocommerce
		Version: 1.1.3
		Author: Ciobanu George

	The7 Elements
		Version: 2.7.1
		Author: Dream-Theme

	Toret EET
		Version: 2.7
		Author: toret.cz

	WooCommerce
		Version: 7.8.0
		Author: Automattic

	WooCommerce Advanced Bulk Edit
		Version: 5.0
		Author: George Iron

	Woo Fio
		Version: 1.3
		Author: Woo

	Woo GoPay Inline
		Version: 1.6.1
		Author: Woo

	Woo Zásilkovna
		Version: 2.7.5
		Author: WM

	Wordfence Security
		Version: 7.9.3
		Author: Wordfence

	WPML Multilingual CMS
		Version: 4.5.14
		Author: OnTheGoSystems

	WPML String Translation
		Version: 3.2.3
		Author: OnTheGoSystems

	Yoast SEO
		Version: 20.9
		Author: Team Yoast

== Použitím Elements ==
	
	footer : 4
		divider : 1
		form : 1
		heading : 3
		icon-list : 1
		image : 1
		spacer : 1
		the7_button_widget : 9
	header : 2
		divider : 1
		html : 1
		icon : 2
		image : 1
		nav-menu : 1
		search-form : 1
		social-icons : 1
		spacer : 2
		text-editor : 1
		woocommerce-menu-cart : 1
	page : 1
		heading : 1
		html : 2
		text-editor : 3
	product : 1
		divider : 1
		heading : 1
		image : 1
		the7-woocommerce-product-images : 1
		woocommerce-breadcrumb : 1
		woocommerce-product-add-to-cart : 1
		woocommerce-product-data-tabs : 1
		woocommerce-product-price : 1
		woocommerce-product-rating : 1
		woocommerce-product-short-description : 1
		woocommerce-product-title : 1
		woocommerce-product-upsell : 1
	wp-post : 9
		heading : 5
		html : 8
		image : 2
		spacer : 5
		text-editor : 23
		video : 2
	wp-page : 23
		button : 68
		countdown : 1
		divider : 94
		form : 2
		heading : 142
		hotspot : 4
		html : 1
		icon-box : 8
		image : 121
		media-carousel : 2
		nav-menu : 1
		slides : 1
		social-icons : 2
		spacer : 47
		text-editor : 52
		theme-site-logo : 1
		video : 5
	search-results : 1
		archive-posts : 1
		divider : 1
		theme-archive-title : 1
	product-archive : 5
		wc-archive-products : 1

== Nastavení ==
	
	cpt_support: post, page
	allow_tracking: yes
	css_print_method: internal
	load_fa4_shim: yes

== Features ==
	Custom Fonts: 0
	Custom Icons: 0

== Integrations ==
	
	woocommerce: Active

== Experimenty Elementoru ==
	Optimalizováno DOM Output: Ve výchozím stavu neaktivní
	Vylepšené načítání assetů: Ve výchozím stavu neaktivní
	Vylepšené načítání CSS: Ve výchozím stavu neaktivní
	Inline Font Icons: Ve výchozím stavu neaktivní
	Vylepšení přístupnosti: Ve výchozím stavu aktivní
	Dodatečné vlastní body zalomení: Aktivní
	admin_menu_rearrangement: Ve výchozím stavu neaktivní
	Flexbox kontejner: Ve výchozím stavu neaktivní
	Aktualizujte knihovnu Swiper: Ve výchozím stavu neaktivní
	Grid Container: Ve výchozím stavu neaktivní
	Default to New Theme Builder: Ve výchozím stavu aktivní
	Horní lišta editoru: Ve výchozím stavu neaktivní
	Vstupní stránky (Landing page): Ve výchozím stavu aktivní
	Vložené prvky: Ve výchozím stavu neaktivní
	Líné načítání obrázků na pozadí: Ve výchozím stavu neaktivní
	Page Transitions: Ve výchozím stavu aktivní
	Notes: Ve výchozím stavu aktivní
	Loop: Ve výchozím stavu aktivní
	Form Submissions: Ve výchozím stavu aktivní
	Scroll Snap: Ve výchozím stavu aktivní
	Menu: Ve výchozím stavu neaktivní

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Není specifikována kompatibilita

== Elementor Pro - Compatibility Tag ==

**Comment by SilverFoxA** [comment] 2023-06-17 11:42
@nicholaszein Unfortunately, the issue has not been fixed and we are still getting this error #21836 

It's a fresh setup, with just elementor pro and woocommerce. Let me know if any other details required to debug this case.

![Screenshot 2023-06-17 at 5 08 42 PM](https://github.com/elementor/elementor/assets/6983070/4908eef0-aca7-45d8-883a-58fbe3477d07)
![Screenshot 2023-06-17 at 5 08 29 PM](https://github.com/elementor/elementor/assets/6983070/53327697-6951-4cf6-b0b1-2f50e6fab929)
![Screenshot 2023-06-17 at 5 08 21 PM](https://github.com/elementor/elementor/assets/6983070/db4d88d1-0c90-4ba7-b8a2-c2bf50927894)

**Comment by bloodcult** [comment] 2023-06-17 12:24
I also have this bug. Only Elementor/Elementor Pro installed with the Hello theme.

**Comment by nicholaszein** [comment] 2023-06-17 13:04
Hello guys...

### 🔗 🐞 This issue is a Duplicate of #22789 

Which is on the same subject. 

For this reason, I'm closing this thread and 🔃 **Merging** it with the original, so we can have all the discussions in one location, and deal with it more efficiently.

Feel free to continue the conversation there. 😉 

# 🔍 Please, in the future, remember to check if there isn't any thread similar to yours already opened...

Kind regards

**Closed** 2023-06-17 13:05 UTC
Labels: compatibility/3rd_party, product/pro, component/woocommerce, component/wc/menu-cart, mod*

**Comment by nicholaszein** [comment] 2023-06-19 13:53
Hello there!

We have great news! 🙌 

### 📢 We're happy to announce that the issue you raised was resolved in Elementor v3.14.0! 🥳 

You can learn more about the fix [here](https://github.com/elementor/elementor/issues/22789#issuecomment-1597226893).

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
