### ISSUE TITLE
🔗 🚀 Feature Request: Build form with any Cf by ACF PRO to submitt post (Duplicate of #1686)

### ISSUE THREAD

**Issue by mariobarretta** [elementor/elementor#6828] opened 2019-01-22 06:28 UTC
I’m an Elementor Pro User and i'd need to can build a form that integrate all the CF created by ACF PRO.

Actually there is not this feature and i'm very frustrated for tht missing.

I would like to use Elementor and to do an advanced step on the web site design using the power of Elementor + ACF Pro to  creating directory sites and Events and Books and many other sites with custom fields managed on a form accessed from external user that can publish on my site.

I see that team develop a lot of new features but, for now, no any attention to USP ( User Submitted Post )  and i hope to can finally and totally use your page builder .

Thank you very much for attention and any feedback form you

**Comment by bainternet** [comment] 2019-01-22 09:41
Thanks for the feedback,
Please follow guidelines for opening a new [feature request](https://github.com/pojome/elementor/issues/new?template=Feature_request.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Description and examples.

**Comment by bainternet** [comment] 2019-01-22 09:41
Duplicate of #1686

**Closed by bainternet** 2019-01-22 09:41 UTC
Labels: request/enhancement, product/pro, component/forms, component/forms/actions, request/integration

**Comment by mariobarretta** [comment] 2019-01-23 09:19
@bainternet i'm sorry but i've respected the prerequisites and i've describved the case.
What more i've to do to can receive a feedback about this important request that a lot of users are asking from several time? 
Thank You
