### ISSUE TITLE
🔗 🐞 Bug Report: Elementor tabs not scrolling to the top of each tab on mobile in some cases (Duplicate of #21288)

### ISSUE THREAD

**Issue by monica1995pk** [elementor/elementor#21294] opened 2023-02-12 09:49 UTC
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

The Nested Tabs feature works correctly on the desktop version. However, on the mobile breakpoint, if the tab content is larger than the viewport height, selecting the tab title adjacent to the active tab results in the active tab to open upwards and showing only the bottom of the tab content. This issue does not occur when any other tab title, except the adjacent tab title, is selected.
![WhatsApp Image 2023-02-09 at 11 21 53](https://user-images.githubusercontent.com/125185540/218303886-a2eec0be-c816-4ccb-86ee-bce8506546af.jpg)

### Steps to reproduce

Activate the nested tab and the container feature.
In the elementor edit screen, add a tabs element into a new container
Add a gallery widget containing about 10 images into the first tab content area
Add other widgets to the other tabs
View the page on a mobile phone
Click on the tab title directly below the currently active tab and observe the result.
Click on a tab title that is 2 or more steps away from the active tab title and observe the different result

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently following the steps above.

### System Info

== Server Environment ==
Operating System: Linux
Software: LiteSpeed
MySQL version: MariaDB Server v10.5.17
PHP Version: 8.0.24
PHP Memory Limit: 2048M
PHP Max Input Vars: 5000
PHP Max Post Size: 2048M
GD Installed: Yes
ZIP Installed: Yes
Write Permissions: All right
Elementor Library: Connected

**Comment by nicholaszein** [comment] 2023-02-14 13:50
Hello @monica1995pk! 

Thank you for submitting your issue! 🙏 

Please allow us some time to investigate it, and get back to you with our findings. 🧐 

Best regards

**Comment by nicholaszein** [comment] 2023-02-14 13:53
Hi @monica1995pk!

### 🔗 🐞 This issue is a Duplicate of #21288

Which is on the same subject. 

For this reason, I'm closing this thread and 🔃 **Merging** it with the original, so we can have all the discussions in one location, and deal with it more efficiently.

Feel free to continue the conversation there. 😉 
Best regards,

Nick

**Closed by nicholaszein** 2023-02-14 13:53 UTC
Labels: bug, type/layout, component/tabs
