### ISSUE TITLE
YouTube videos don't show up

### ISSUE THREAD

**Issue by dpanaget** [elementor/elementor#14504] opened 2021-04-09 13:36 UTC
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

After upgrading Elementor plugin to version 3.1.4, YouTube videos don't show up anymore, both in front-end and in back-end.
In front-end, instead of a YouTube video, a blank area is displayed.
Same behavior in back-end: the video is not displayed and a blank zone appears instead.

When I try Vimeo or Dailymotion videos, I experience no problem at all.
Everything works as expected, both in front-end and in back-end.

Here is below the part of code that tried to render the video in front-end.

`<div class="elementor-element elementor-element-825ac2c elementor-aspect-ratio-169 elementor-widget elementor-widget-video" data-id="825ac2c" data-element_type="widget" data-settings="{&quot;youtube_url&quot;:&quot;https:\/\/www.youtube.com\/embed\/Yqsg5UYCwKY&quot;,&quot;lazy_load&quot;:&quot;yes&quot;,&quot;video_type&quot;:&quot;youtube&quot;,&quot;aspect_ratio&quot;:&quot;169&quot;}" data-widget_type="video.default">
				<div class="elementor-widget-container">
					<div class="elementor-aspect-ratio-169 elementor-wrapper elementor-fit-aspect-ratio elementor-open-inline">
			<div class="elementor-video"></div>		</div>
				</div>
				</div>`

## Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [ ] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->

### wp-core ###

version: 5.7
site_language: fr_FR
user_language: fr_FR
timezone: Europe/Paris
https_status: true
multisite: true

### wp-plugins-active ###
Elementor: version: 3.1.4, author: Elementor.com
Elementor Pro: version: 3.2.1, author: Elementor.com

### wp-server ###

server_architecture: Linux 4.9.0-15-amd64 x86_64
httpd_software: Apache/2.4.38 (Debian)
php_version: 7.4.16 64bit
php_sapi: apache2handler
max_input_variables: 1000
time_limit: 30
memory_limit: 128M
admin_memory_limit: 256M
max_input_time: -1
upload_max_filesize: 512M
php_post_max_size: 512M
curl_version: 7.64.0 OpenSSL/1.1.1d
suhosin: false
imagick_availability: false
pretty_permalinks: true
htaccess_extra_rules: true

### wp-database ###

extension: mysqli
server_version: 10.1.48-MariaDB-0+deb9u2
client_version: mysqlnd 7.4.16

### wp-filesystem ###

wordpress: not writable
wp-content: not writable
uploads: writable
plugins: not writable
themes: not writable
mu-plugins: not writable

</details>

**Comment by Mitchy25** [comment] 2021-04-10 00:31
Duplicate of #14135

**Comment by danygit** [comment] 2021-04-12 14:29
@Mitchy25 is not the same problem. In our case, we have a container of the video but not the video.
See : https://wordpress.org/support/topic/videos-no-longer-working-after-updating-elementor/

**Comment by danygit** [comment] 2021-04-22 14:38
Up ? Can you help us ?

**Comment by addMitt** [comment] 2021-04-26 16:50
Not sure which Issue I should post this in exactly, so I'll do both:

I believe I'm having this issue, albeit with some slightly different errors.

With no caching plugins or anything enabled, it seems like when a widget requires a JavaScript file to work, that file does not get included when viewing the page (unless you are, strangely, logged in to the backend as an administrator).

The YouTube part of the DOM element never shows up:

```
<div class="elementor-element elementor-element-cf4b777 elementor-aspect-ratio-169 elementor-widget elementor-widget-video" data-id="cf4b777" data-element_type="widget" data-settings="{&quot;youtube_url&quot;:&quot;https:\/\/www.youtube.com\/watch?v=wOwy_4RPkoo&quot;,&quot;video_type&quot;:&quot;youtube&quot;,&quot;controls&quot;:&quot;yes&quot;,&quot;aspect_ratio&quot;:&quot;169&quot;}" data-widget_type="video.default">
  <div class="elementor-widget-container">
    <div class="elementor-wrapper elementor-fit-aspect-ratio elementor-open-inline">
      <div class="elementor-video"></div>
    </div>
  </div>
</div>
```

The console reports an error related to a variable it requires not being defined (because the JavaScript file didn't load for it)

> Uncaught ReferenceError: elementorModules is not defined

And by comparing when logged in to the admin panel, I found that this is the file that is not being loaded:

> /wp/wp-content/plugins/elementor/assets/js/video.2be65474f4a78954309a.bundle.min.js

~~This does however, happen for any video site included with the Video widget (as the JavaScript for the entire widget is not being loaded).~~ Just kidding, I tested wrong. It appears that Vimeo and DailyMotion both work fine. Only YouTube is having this problem. I've tested with our own videos, and the sample video.

Tested with Elementor 3.2.2 and Elementor Pro 3.2.1.

**Comment by Aviad-Herman** [comment] 2021-06-15 21:41
Hi,
Does this issue still occur on the latest versions of Elementor?

We need more info to replicate the issue.
Please add exact steps to reproduce (or preferably a short video, Loom is a great tool for this.)
We need as much details as possible, such as what permissions (admin?) the user who is trying to edit the page has, are any elementor experiments on? does the bug happen when all plugins except Elementor are deactivated? Does the bug happen with Elementor Hello theme activated?

**Closed** 2021-06-16 18:00 UTC
Labels: status/needs feedback

**Comment by addMitt** [comment] 2021-06-16 18:18
Sorry, this ended up being an issue with our Magento 2 integration. I was unaware it was responsible for injecting dependencies for Elementor and was causing issues.
