### ISSUE TITLE
🐞 Bug report: PHP 8.1 - Widget Skins don't work anymore

### ISSUE THREAD

**Issue by hogash** [elementor/elementor#17885] opened 2022-02-19 08:27 UTC
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

When using for example the Posts element, there are no options inside the Layout controls section.

Video recording https://d.pr/v/4vKKcK .

The problem seem to happen on any element that has Skins registered inside. For some reason the "_skin" key is no longer working causing the conditioned controls to vanish completly.

### Steps to reproduce

Use Posts element.

Look inside the error log for the error `PHP Warning:  Undefined array key "_skin" in /../wp-content/plugins/elementor/includes/conditions.php on line 87` (as well as other deprecated ones)

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Source distribution v5.7.32-35
	PHP Version: 8.1.3
	PHP Max Input Vars: 3000
	PHP Max Post Size: 256M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.9
	WP Multisite: Yes
	Max Upload Size: 1 MB
	Memory limit: 768M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 0
	Debug Mode: Active

== Elementor Experiments ==
	Optimized DOM Output: Active by default
	Improved Asset Loading: Active by default
	Improved CSS Loading: Inactive by default
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Active by default
	Import Export Template Kit: Active by default
	Additional Custom Breakpoints: Inactive by default
	Hide native WordPress widgets from search results: Active by default
	Default to New Theme Builder: Active by default
	Landing Pages: Active by default
	Color Sampler: Active by default
	Favorite Widgets: Active by default
	Admin Top Bar: Active by default
	Page Transitions: Active by default
	Form Submissions: Active by default
	Scroll Snap: Active by default

**Comment by squadcar** [comment] 2022-02-21 00:21
Similar issue found via Premium Addons new Woocommerce Products widget. Trying to use the widget with php8.1 throws the same error: `Warning: Undefined array key “_skin” in /../wp/wp-content/plugins/elementor/includes/conditions.php
on line 87`

**Comment by euene** [comment] 2022-02-24 08:39
I can also reproduce this issue on PHP 8.1.
@shilo-ey @rami-elementor

**Comment by shilo-ey** [comment] 2022-02-24 09:03
@euene Yes, it's supposed to be fixed soon. 

Thanks for reporting.

**Comment by encreinformatique** [comment] 2022-03-22 17:37
I do have those issues as well with Elementor and PHP 8.1. Downgrading to PHP 7.4 is not a valid solution. [PHP 8.0 has been released in November 2020](https://www.php.net/supported-versions.php) and the boost in performance is substantial.

**Comment by rami-elementor** [comment] 2022-03-30 12:18
@encreinformatique You are right, downgrading to PHP 7.4 is not a valid solution but it should help you solve the issue on your site.

You should also know that even WordPress doesn't fully support **PHP 8.0** ([Source](https://make.wordpress.org/core/handbook/references/php-compatibility-and-wordpress-versions/)), and this bug refers to **PHP 8.1**

**Comment by euene** [comment] 2022-03-30 12:28
> You should also know that even WordPress doesn't fully support **PHP 8.0** ([Source](https://make.wordpress.org/core/handbook/references/php-compatibility-and-wordpress-versions/)), and this bug refers to **PHP 8.1**

Actually, WordPress core is completely **functional** on both PHP 8.0 and 8.1 and there are **no visible or functional regressions** when compared to PHP 7.x.

Here's an excerpt from the official [WordPress core blog](https://make.wordpress.org/core/2022/01/10/wordpress-5-9-and-php-8-0-8-1/):

> WordPress is not fully compatible with PHP 8.0 or 8.1. All remaining known PHP 8.1 issues **are deprecation notices**.

> **Please note, a deprecation notice is not an error**, but rather an indicator of where additional work is needed for compatibility before PHP 9 (i.e. when the notices become fatal errors). With a deprecation notice, the PHP code will continue to work and nothing is broken.

This means that while WordPress doesn't have official stable compatibility with PHP 8/8.1 - the only remaining "issues" are some warnings that will potentially be output in the server's error_log. That's all. On the actual WordPress website, everything functions normally.

There's a difference between the state of WordPress core's PHP 8/8.1 compatibility (warnings only) and the state of Elementor's PHP 8/8.1 PHP 8/8.1 compatibility (actual functional/visible regressions) which is the topic of this issue and other PHP 8/8.1 Elementor issues here on GitHub.

**Comment by encreinformatique** [comment] 2022-03-30 13:29
I totally agree, deprecations are pretty common. They are not a problem if they are dealt with prior to the removal of those functions. This typically happens on a major version change.

@rami-elementor while downgrading to 7.4 would be a solution, it means that potential performance boost would be lost for just one plugin.
On a side note I am quite surprised that multiple wordpress plugins (not specific to Elementor) still have problems with PHP 8.0. (released 18 months ago). I am not familiar enough with SVN to propose changes on those.

**Comment by arielk** [comment] 2022-10-17 18:55
I'm closing an issue due to inactivity. If the problem still exists, feel free to reopen the issue or contact our support through your account. 

Thanks!

**Closed by arielk** 2022-10-17 18:55 UTC
Labels: bug, status/merged
