### ISSUE TITLE
⛔ 🔗🐞 Bug Report: add_filter( 'elementor_pro/forms/csv_export_headers', 'my_f', 10,2) is NOT triggered/working (Duplicate of #17775)

### ISSUE THREAD

**Issue by Mulli** [elementor/elementor#20923] opened 2023-01-05 02:17 UTC
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description
LAST MINUTE EDIT: The code is from chatGPT - after searching the source code, there is no such hook....
ISSUE SHOULD BE FEATURE REQUEST
The following is not working:
```
function custom_form_field_headers( $headers, $form_id ) {
  // Replace the form field labels with the form field IDs
  foreach ( $headers as $key => $header ) {
    $field_id = 'testing_' . $key; // get_form_field_id_by_label( $header, $form_id );
    if ( $field_id ) {
      $headers[ $key ] = $field_id;
    }
  }
  error_log('elementor_pro/forms/csv_export_headers form id='. $form_id . '   headers='. $headers); // for debug purposes
  return $headers;
}
add_filter( 'elementor_pro/forms/csv_export_headers', 'custom_form_field_headers', 10, 2 );
```

### Steps to reproduce

1. Add the code above to functions.php
2. Export form leads to csv
3. The CSV file does not have the expected headers
4. Debug.log does NOT contain the error message

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

<details>
<summary>System Info</summary>

````txt

					
== Server Environment ==
	Operating System: Linux
	Software: LiteSpeed
	MySQL version: MariaDB Server v10.3.37
	PHP Version: 7.4.33
	PHP Memory Limit: 512M
	PHP Max Input Vars: 20560
	PHP Max Post Size: 24M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.1.1
	Site URL: https://forms.plev.today
	Home URL: https://forms.plev.today
	WP Multisite: No
	Max Upload Size: 24 MB
	Memory limit: 1024M
	Max Memory limit: 1024M
	Permalink Structure: /%postname%/
	Language: he-IL
	Timezone: Asia/Jerusalem
	Admin Email: mulli@site2goal.co.il
	Debug Mode: Active

== Theme ==
	Name: Hello Elementor Child
	Version: 1.0.1
	Author: Elementor Team
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.6.1
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: he_IL
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36

== Active Plugins ==
	Advanced Custom Fields
		Version: 6.0.6
		Author: WP Engine

	Classic Editor
		Version: 1.6.2
		Author: WordPress Contributors

	Disable Password Reset
		Version: 1.0
		Author: WPBeginner

	Duplicate Page
		Version: 4.5
		Author: mndpsingh287

	Elementor
		Version: 3.9.2
		Author: Elementor.com

	Elementor Pro
		Version: 3.9.2
		Author: Elementor.com

	LTR <=> RTL Admin content
		Version: 0.6.2
		Author: Ronny Sherer

	WPCode Lite
		Version: 2.0.5
		Author: WPCode

	WPS Hide Login
		Version: 1.9.6
		Author: WPServeur, NicolasKulka, wpformation


== הניסויים של אלמנטור ==
	פלט DOM שעבר אופטימיזציה: פעיל
	טעינת נכסים משופרת: פעיל
	טעינת CSS משופרת: פעיל
	Inline Font Icons: לא פעיל
	שיפורי נגישות: פעיל
	Additional Custom Breakpoints: פעיל
	ייבא קיט אתר אינטרנט: פעיל כברירת מחדל
	Hide native WordPress widgets from search results: פעיל כברירת מחדל
	admin_menu_rearrangement: לא פעיל כברירת מחדל
	פלקסבוקס קונטיינר: לא פעיל
	ברירת מחדל לממשק החדש של בונה התבנית: פעיל כברירת מחדל
	עיצוב כותרת עליונה ותחתונה: לא פעיל כברירת מחדל
	דפי נחיתה: פעיל כברירת מחדל
	דוגם צבע: פעיל כברירת מחדל
	וידג׳טים מעודפים: פעיל כברירת מחדל
	סרגל אדמין עליון: פעיל כברירת מחדל
	טעינה עצלה של תמונות רקע: לא פעיל כברירת מחדל
	שמור כברירת מחדל: פעיל כברירת מחדל
	מעבר עמוד: פעיל
	Notes: פעיל כברירת מחדל
	לולאה: לא פעיל כברירת מחדל
	לידים: פעיל
	קפיצת גלילה: פעיל כברירת מחדל


== יומן שינויים ==
	
Log: showing 20 of 422022-12-19 10:52:05 [info] אלמנטור/Upgrades - _on_each_version Start  
2022-12-19 10:52:06 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'אלמנטור',
  'from' => '3.8.1',
  'to' => '3.9.1',
)]
2022-12-19 10:52:06 [info] אלמנטור/Upgrades - _on_each_version Finished 
2022-12-19 10:52:06 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'אלמנטור',
  'from' => '3.8.1',
  'to' => '3.9.1',
)]
2022-12-19 10:52:36 [info] elementor-pro::elementor_pro_updater Started 
2022-12-19 10:52:36 [info] אלמנטור פרו/Upgrades - _on_each_version Start  
2022-12-19 10:52:36 [info] אלמנטור פרו/Upgrades - _on_each_version Finished 
2022-12-19 10:52:36 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'אלמנטור פרו',
  'from' => '3.7.5',
  'to' => '3.9.1',
)]
2022-12-19 10:52:36 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'אלמנטור פרו',
  'from' => '3.7.5',
  'to' => '3.9.1',
)]
2022-12-31 16:20:05 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Dynamic.ooo - Dynamic Content for Elementor',
  'from' => '2.8.1',
  'to' => '2.8.3',
)]
2022-12-31 16:20:11 [info] elementor::elementor_updater Started 
2022-12-31 16:20:11 [info] אלמנטור/Upgrades - _on_each_version Start  
2022-12-31 16:20:12 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'אלמנטור',
  'from' => '3.9.1',
  'to' => '3.9.2',
)]
2022-12-31 16:20:12 [info] אלמנטור/Upgrades - _on_each_version Finished 
2022-12-31 16:20:12 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'אלמנטור',
  'from' => '3.9.1',
  'to' => '3.9.2',
)]
2023-01-01 05:01:15 [info] elementor-pro::elementor_pro_updater Started 
2023-01-01 05:01:15 [info] אלמנטור פרו/Upgrades - _on_each_version Start  
2023-01-01 05:01:15 [info] אלמנטור פרו/Upgrades - _on_each_version Finished 
2023-01-01 05:01:15 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'אלמנטור פרו',
  'from' => '3.9.1',
  'to' => '3.9.2',
)]
2023-01-01 05:01:15 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'אלמנטור פרו',
  'from' => '3.9.1',
  'to' => '3.9.2',
)]

PHP: showing 1 of 1PHP: 2022-10-28 14:36:15 [notice X 2][/home/hila/forms.plev.today/wp-content/plugins/elementor/includes/template-library/sources/local.php::720] ob_end_clean(): failed to delete buffer. No buffer to delete [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]



== אלמנטור - Compatibility Tag ==
	
	Elementor Pro: לא תואם

== אלמנטור פרו - Compatibility Tag ==
	


````
</details>

**Comment by nicholaszein** [comment] 2023-01-30 15:31
Hello @Mulli,

Thank you for reaching out! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
* As you discovered yourself, this hook is not supported.
* This issue is a duplicate of #17775 

### ✅ What you can do to solve your issue:
* Please **<ins>ALWAYS</ins>** check the official Developers Documentation before using any hook you find on the internet.

For now, that's all we can help with. If you think this is still an issue caused by Elementor, please feel free to open a [new issue report](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml) and provide us with the most information you can possibly get by following our guidelines:

* Please create GitHub issues **only for Elementor bugs**. GitHub issues ARE NOT FOR SUPPORT or for issues with 3rd party plugins.
* To **avoid duplicates**, please search this repository for similar issues before submitting your own.
* If the issue can't be recreated on other sites, it's not an Elementor bug. In that case, **use the support links below before submitting your issue here**.
* Make sure you are using the most **updated versions** of Elementor, WordPress & your theme.
* Deactivate all of your plugins. If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin, and then **contact the 3rd party plugin developer**.
* Make sure to **provide a detailed description** of your issue.
* Make sure to **provide detailed steps to replicate** your issue.
* Make sure the issue occurs with **only Elementor** (and Elementor Pro) plugin(s) active.
* Make sure the issue happens with a **blank theme** active ([Hello Elementor](https://wordpress.org/themes/hello-elementor/)).
* Make sure to **provide a copy of your _Elementor > System Info_**. Download the `.txt` file and drag it inside the "System Info" field when submitting a new bug report.

### ⚠️ Please Note that GitHub issues are reserved for 🐞**Bug Reports**, and should not be used for support.

❔ If you have questions or need general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) on Facebook
- [Elementor Help Center](https://docs.elementor.com)
- [Support Forum](https://wordpress.org/support/plugin/elementor) on WordPress.org 
- [Elementor Developers Documentation](https://developers.elementor.com/)

💎 If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Kind regards

**Closed by nicholaszein** 2023-01-30 15:31 UTC
Labels: bug, type/developer-api, product/pro, component/submissions
