### ISSUE TITLE
Elementor enqueues all scripts used on a site, not just those required by a page

### ISSUE THREAD

**Issue by yourpropertyexpert** [elementor/elementor#11292] opened 2020-05-04 10:14 UTC
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

On sites that include a large number of widgets, all the scripts for every widget are enqueued at pageload, not just those required for the widgets that happen to be on that page.

**Describe the solution you'd like**

Instead of the code enqueuing every script, there should be a mechanism to only enqueue the scripts that are actually used on the page.

**Describe alternatives you've considered**

**Additional context**

**Comment by shilo-ey** [comment] 2020-05-04 10:23
duplicate of #8572

**Closed by shilo-ey** 2020-05-04 10:23 UTC

**Comment by yourpropertyexpert** [comment] 2020-05-04 10:53
No. It wasn't a duplicate.

I've created a new issue explaining why they are different.
