### ISSUE TITLE
Conflict with FastSpring WP plugin

### ISSUE THREAD

**Issue by blakmarkit** [elementor/elementor#7093] opened 2019-02-16 00:45 UTC
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

With Elementor and FastSpring installed on WordPress, loading the Elementor page builder gets stuck perpetually with the page mostly loaded, with the Elementor sidebar, but with a spinning icon and overlay on the page that is loaded into the editor. Not able to add any page elements from the sidebar. Appears to be a javascript conflict between the two plugins. Removing other plugins doesn't help. It is definitely a conflict between these two. As soon as I uninstall FastSpring, Elementor works correctly. 

Out of curiosity, disabled Elementor and installed Beaver Builder, and no issues loading pages into their editor. 

This is a breaking issue for us. 

Using Elementor Hello theme, WP 5.0.3, latest Elementor and Elementor Pro, latest FastSpring plugin

## Steps to reproduce

Install and activate Elementor/Pro and FastSpring WordPress Plugin. Possibly need to setup popup storefront details within FastSpring plugin? But might not need to do that. 

https://wordpress.org/plugins/fastspring/

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Percona Server (GPL), Release '27', Revision 'bd42700' v5.7.24-27
	PHP Version: 7.0.33-1+ubuntu18.04.1+deb.sury.org+1
	PHP Max Input Vars: 1000
	PHP Max Post Size: 100M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.0.3
	Site URL: https://dclaydev.wpengine.com
	Home URL: http://dclaydev.wpengine.com
	WP Multisite: No
	Max Upload Size: 50 MB
	Memory limit: 40M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: America/Chicago
	Debug Mode: Inactive

== Theme ==
	Name: Elementor Hello Theme
	Version: 1.1.0
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:65.0) Gecko/20100101 Firefox/65.0

== Active Plugins ==
	Beaver Builder Plugin (Lite Version)
		Version: 2.2.0.6
		Author: The Beaver Builder Team

	Classic Editor
		Version: 1.4
		Author: WordPress Contributors

	Coming Soon Page & Maintenance Mode by SeedProd
		Version: 5.0.23
		Author: SeedProd

	Elementor
		Version: 2.4.6
		Author: Elementor.com

	Elementor Pro
		Version: 2.4.4
		Author: Elementor.com

	FastSpring
		Version: 1.8.5
		Author: FastSpring WordPress Team

	FileBird Lite
		Version: 1.7
		Author: Ninja Team

	Login by Auth0
		Version: 3.9.0
		Author: Auth0

	Peter's Blog URL Shortcodes
		Version: 0.4
		Author: Peter Keung

	PowerPack Lite for Beaver Builder
		Version: 1.2.3.1
		Author: Beaver Addons

	Ultimate Addons for Beaver Builder - Lite
		Version: 1.2.4
		Author: Brainstorm Force

	WPForms Lite
		Version: 1.5.1
		Author: WPForms

== Must-Use Plugins ==
	Force Strong Passwords - WPE Edition
		Version: 1.6.4
		Author: Jason Cosper

	Stop long comments
		Version: 0.0.4
		Author: WPEngine

	WP Engine System
		Version: 3.2.1
		Author: WP Engine

== Log ==
	: 
Log: showing 3 of 32019-01-30 23:13:54 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.4.4',
  'to' => '2.4.5',
)]
2019-02-11 15:12:30 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Page Builder',
  'from' => '2.4.5',
  'to' => '2.4.6',
)]
2019-02-11 15:12:30 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.4.3',
  'to' => '2.4.4',
)]

JS: showing 7 of 7JS: 2019-02-01 03:27:49 [error X 1][https://dclaydev.wpengine.com/wp-includes/js/jquery/jquery.js?ver=1.12.4 line 2 > eval:6:9] MasterSlider is not defined 
JS: 2019-02-01 07:05:11 [error X 10][https://dclaydev.wpengine.com/wp-admin/js/editor.min.js?ver=5.0.3:1:681] j is undefined 
JS: 2019-02-01 07:05:11 [error X 10][https://dclaydev.wpengine.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.4.5:2:209372] e.editor is null 
JS: 2019-02-01 07:47:12 [error X 1][https://dclaydev.wpengine.com/wp-content/plugins/elementor/assets/lib/slick/slick.min.js?ver=1.8.1:1:19325] e.$slides is null 
JS: 2019-02-03 11:13:47 [error X 1][https://dclaydev.wpengine.com/wp-content/plugins/elementor/assets/js/editor-modules.js?ver=2.4.5:671:36] An invalid argument supplied as multiple control value [array (
  'category' => 'InvalidElementData',
  'tag' => 'Element `undefined` got <#> as `gridimage_btnlink` value. Expected array or object.',
)]
JS: 2019-02-04 22:12:55 [error X 9][https://dclaydev.wpengine.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.4.5:2:41267] e.elements is undefined 
JS: 2019-02-05 01:39:13 [error X 4][https://dclaydev.wpengine.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.4.5:2:74603] setting getter-only property \"type\" 

				
</details>

**Comment by blakmarkit** [comment] 2019-02-16 05:19
Additional information:

I've discovered that by using the browser Developer Tools to remove the fastspringgrid-css stylesheet that the FastSpring plugin uses from within the iframe that Elementor generates when loading a page for editing, I am able to utilize the editor.

**Comment by bdthemes** [comment] 2019-02-16 17:49
me too 😟

**Comment by James7503** [comment] 2019-02-16 20:42
I cannot edit the home page of my website with elementor. Once it is loaded the page goes white. Any thought on what the problem could be?

**Comment by shilo-ey** [comment] 2019-02-17 10:09
Hi @blakmarkit 

I Cannot see a way we can control this conflict, hence it's resolving from CSS rules "taking over" Elementor editor.

Try contacting the plugin authors and ask them to fix this.

Thanks.

**Closed by shilo-ey** 2019-02-17 10:09 UTC

**Comment by James7503** [comment] 2019-02-17 12:31
Can you recommend the best way to contact authors. To resolve the issue.

**Comment by shilo-ey** [comment] 2019-02-17 12:36
https://wordpress.org/support/plugin/fastspring/
or
https://fastspring.com/contact/

**Comment by James7503** [comment] 2019-02-17 13:23
Thanks

**Comment by blakmarkit** [comment] 2019-02-18 18:51
@shilo-ey 

I have previously contacted FastSpring, as well, and they also punted. It's more than a bit frustrating to go to both plugin developers and have both point at the other one. Is there anything you could do to take a look at the situation to test? I've spent a lot of time tracking down the source of this issue, only to be told, effectively, "too bad, not my problem," twice. It's disheartening to see the case closed so immediately without resolution. 

Is there anything you can do to work with their developers? Is there anything you can test? Is it possible to automatically remove the offending stylesheet programatically in Elementor's editor iframe? The fact that it's in an iframe seems to make it very difficult for me to figure out a way to have a plugin *not* load in a particular area of the site. I need to find a way to make this work.

**Comment by shilo-ey** [comment] 2019-02-20 10:00
@blakmarkit 

Hi, 

The 3rd party plugin **is** the cause of the issue you're describing.
This issue was closed because it is not under our control.

If their developers would need some assistance, we will be glad to help.

Thanks.
