### ISSUE TITLE
⛔ 🐞 Bug report: Buttons in containers are shown outside of container and are multiplied

### ISSUE THREAD

**Issue by bodhi1970** [elementor/elementor#18336] opened 2022-04-02 12:55 UTC
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest development version of Elementor.

### Description

I am working on a new page where I installed Dev version and activated Flex Box Container.
When I have a button in a container then this is shown outside of the container and 2 or 3 timers.
I added other widgets and it is fine, this appears only with buttons, also vanilla buttons not just the one I customized.
All looks good in the Elementor preview but as soon as I publish it looks weird.
I checked on Firefox and Chrome and both show same result.
<img width="1135" alt="Screenshot 2022-04-02 at 10 27 29" src="https://user-images.githubusercontent.com/5292941/161384240-0b12f2c8-f200-478d-9fe5-5c5eecfa001c.png">
<img width="916" alt="Screenshot 2022-04-02 at 10 27 45" src="https://user-images.githubusercontent.com/5292941/161384242-6c5b81ea-43d0-4ec1-8c8d-0913957d7558.png">
<img width="995" alt="Screenshot 2022-04-02 at 12 42 05" src="https://user-images.githubusercontent.com/5292941/161384243-c0102a06-46e4-4817-8252-1311a2fa5e89.png">
.

### Code from Inspector ###

```
<section class="elementor-element elementor-element-ba0c4ca e-container--column e-container" data-id="ba0c4ca" data-element_type="container" data-settings="{&quot;background_background&quot;:&quot;classic&quot;}">		<a class="elementor-element elementor-element-da666ae e-container--column e-container" data-id="da666ae" data-element_type="container" data-settings="{&quot;background_background&quot;:&quot;classic&quot;}" href="https://relationalspaces.dk/consulting/services/">				<div class="elementor-element elementor-element-e041b23 elementor-widget elementor-widget-heading" data-id="e041b23" data-element_type="widget" data-widget_type="heading.default">
				<div class="elementor-widget-container">
			<style>/*! elementor - v3.5.6 - 17-03-2022 */
.elementor-heading-title{padding:0;margin:0;line-height:1}.elementor-widget-heading .elementor-heading-title[class*=elementor-size-]>a{color:inherit;font-size:inherit;line-height:inherit}.elementor-widget-heading .elementor-heading-title.elementor-size-small{font-size:15px}.elementor-widget-heading .elementor-heading-title.elementor-size-medium{font-size:19px}.elementor-widget-heading .elementor-heading-title.elementor-size-large{font-size:29px}.elementor-widget-heading .elementor-heading-title.elementor-size-xl{font-size:39px}.elementor-widget-heading .elementor-heading-title.elementor-size-xxl{font-size:59px}</style><h4 class="elementor-heading-title elementor-size-default">We create thriving workplaces</h4>		</div>
				</div>
				<div class="elementor-element elementor-element-a8dfc6d elementor-widget elementor-widget-text-editor" data-id="a8dfc6d" data-element_type="widget" data-widget_type="text-editor.default">
				<div class="elementor-widget-container">
							<p>It is our experience that many organizations struggle because people fail to <strong>listen</strong> to each other, don’t <strong>feel safe</strong> enough to share their doubts and insecurities or don’t know how to <strong>handle conflicts</strong>.</p>						</div>
				</div>
				</a><div class="elementor-element elementor-element-5fff071 box-button elementor-widget elementor-widget-button" data-id="5fff071" data-element_type="widget" data-widget_type="button.default"><a class="elementor-element elementor-element-da666ae e-container--column e-container" data-id="da666ae" data-element_type="container" data-settings="{&quot;background_background&quot;:&quot;classic&quot;}" href="https://relationalspaces.dk/consulting/services/">
				</a><div class="elementor-widget-container"><a class="elementor-element elementor-element-da666ae e-container--column e-container" data-id="da666ae" data-element_type="container" data-settings="{&quot;background_background&quot;:&quot;classic&quot;}" href="https://relationalspaces.dk/consulting/services/">
					</a><div class="elementor-button-wrapper"><a class="elementor-element elementor-element-da666ae e-container--column e-container" data-id="da666ae" data-element_type="container" data-settings="{&quot;background_background&quot;:&quot;classic&quot;}" href="https://relationalspaces.dk/consulting/services/">
			</a><a href="https://relationalspaces.dk/consulting/services/" class="elementor-button-link elementor-button elementor-size-md elementor-animation-shrink" role="button">
						<span class="elementor-button-content-wrapper">
							<span class="elementor-button-icon elementor-align-icon-right">
				<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" id="Ebene_1" x="0px" y="0px" width="64px" height="64px" viewBox="0 0 64 64" xml:space="preserve"><g>	<path d="M28.373,13.546c-0.803-0.758-2.068-0.722-2.827,0.081c-0.758,0.803-0.722,2.069,0.081,2.827L42.087,32l-16.46,15.546  c-0.803,0.758-0.839,2.024-0.081,2.827C25.939,50.79,26.469,51,27,51c0.493,0,0.986-0.181,1.373-0.546l18-17  C46.773,33.076,47,32.55,47,32s-0.227-1.076-0.627-1.454L28.373,13.546z"></path>	<path d="M32,0C23.453,0,15.417,3.329,9.374,9.373C3.329,15.417,0,23.453,0,32s3.33,16.583,9.374,22.626  C15.417,60.671,23.453,64,32,64s16.583-3.329,22.626-9.373C60.671,48.583,64,40.547,64,32s-3.33-16.583-9.374-22.626  C48.583,3.329,40.547,0,32,0z M51.797,51.798C46.509,57.087,39.479,60,32,60s-14.509-2.913-19.798-8.202C6.913,46.51,4,39.479,4,32  s2.913-14.51,8.203-19.798C17.491,6.913,24.521,4,32,4s14.509,2.913,19.798,8.202C57.087,17.49,60,24.521,60,32  S57.087,46.51,51.797,51.798z"></path></g></svg>			</span>
						<span class="elementor-button-text">See our services</span>
		</span>
					</a>
		</div>
				</div>
				</div>
		</section>

```

### Steps to reproduce

Create a container within a container, add Heading, Text editor and a button below.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro) with development versions.
- [X] This bug happens with a vanilla WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: mariadb.org binary distribution v10.3.34
	PHP Version: 7.4.28
	PHP Memory Limit: 1073741824
	PHP Max Input Vars: 5000
	PHP Max Post Size: 256M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.9.2
	Site URL: https://relationalspaces.dk/consulting
	Home URL: https://relationalspaces.dk/consulting
	WP Multisite: No
	Max Upload Size: 256 MB
	Memory limit: 40M
	Max Memory limit: 1073741824
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 0
	Admin Email: heinz@relationalspaces.dk
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.5.0
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:98.0) Gecko/20100101 Firefox/98.0

== Active Plugins ==
	Classic Editor
		Version: 1.6.2
		Author: WordPress Contributors

	Ele Custom Skin
		Version: 3.1.5
		Author: Dudaster.com

	Ele Custom Skin Pro
		Version: 3.2.3
		Author: Dudaster.com

	Elementor
		Version: 3.7.0-dev2
		Author: Elementor.com

	Elementor Beta (Developer Edition)
		Version: 1.1.1
		Author: Elementor.com

	Elementor Pro
		Version: 3.7.0-dev38
		Author: Elementor.com

	Pods - Custom Content Types and Fields
		Version: 2.8.10
		Author: Pods Framework Team

	Unlimited Elements for Elementor
		Version: 1.5.9
		Author: Unlimited Elements

	Wordfence Security
		Version: 7.5.9
		Author: Wordfence

== Elementor Experiments ==
	Optimized DOM Output: Active by default
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Active by default
	Import Export Template Kit: Active by default
	Additional Custom Breakpoints: Active by default
	Hide native WordPress widgets from search results: Active by default
	: Inactive by default
	Flexbox Container: Active
	Default to New Theme Builder: Active by default
	Hello Theme Header & Footer: Active by default
	Landing Pages: Active by default
	Color Sampler: Active by default
	Favorite Widgets: Active by default
	Admin Top Bar: Active by default
	Page Transitions: Active by default
	Notes: Inactive by default
	Form Submissions: Active by default
	Scroll Snap: Active by default

== Log ==
	
Log: showing 20 of 332022-03-23 20:04:21 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.0',
  'to' => '3.6.1',
)]
2022-03-23 20:04:23 [info] elementor::elementor_updater Started 
2022-03-23 20:04:23 [info] Elementor/Upgrades - _on_each_version Start  
2022-03-23 20:04:23 [info] Elementor/Upgrades - _on_each_version Finished 
2022-03-23 20:04:23 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.0',
  'to' => '3.6.1',
)]
2022-03-31 15:12:26 [info] elementor::elementor_updater Started 
2022-03-31 15:12:26 [info] Elementor/Upgrades - _on_each_version Start  
2022-03-31 15:12:26 [info] Elementor/Upgrades - _on_each_version Finished 
2022-03-31 15:12:26 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.1',
  'to' => '3.7.0-dev2',
)]
2022-03-31 15:12:26 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.1',
  'to' => '3.7.0-dev2',
)]
2022-03-31 15:14:37 [info] elementor-pro::elementor_pro_updater Started 
2022-03-31 15:14:37 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-03-31 15:14:37 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-03-31 15:14:37 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.6.4',
  'to' => '3.7.0-dev37',
)]
2022-03-31 15:14:37 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.6.4',
  'to' => '3.7.0-dev37',
)]
2022-04-01 15:48:18 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.0-dev37',
  'to' => '3.7.0-dev38',
)]
2022-04-01 15:48:20 [info] elementor-pro::elementor_pro_updater Started 
2022-04-01 15:48:20 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-04-01 15:48:20 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-04-01 15:48:20 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.0-dev37',
  'to' => '3.7.0-dev38',
)]

JS: showing 6 of 6JS: 2022-03-18 08:21:50 [error X 148][https://relationalspaces.dk/consulting/wp-content/plugins/elementor/assets/js/frontend-modules.min.js?ver=3.5.6:2:5057] Cannot read properties of undefined (reading \'data\') 
JS: 2022-03-22 15:49:42 [error X 4][https://relationalspaces.dk/consulting/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.5.6:2:349044] elementorFrontend.elements.window.jQuery is not a function 
JS: 2022-03-30 14:09:12 [error X 2][https://relationalspaces.dk/consulting/wp-content/plugins/elementor/assets/js/frontend-modules.min.js?ver=3.6.1:2:5069] Cannot read properties of undefined (reading \'attributes\') 
JS: 2022-03-30 14:25:19 [error X 12][https://relationalspaces.dk/consulting/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.6.1:2:243865] quicktags is not defined 
JS: 2022-03-31 15:27:02 [error X 33][https://relationalspaces.dk/consulting/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.7.0-dev2:2:248360] QTags is not defined 
JS: 2022-03-31 21:40:46 [error X 3][https://relationalspaces.dk/consulting/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.7.0-dev2:2:448397] Cannot read properties of undefined (reading \'isActive\') 

PHP: showing 4 of 4PHP: 2022-03-23 10:10:49 [notice X 16][/customers/6/a/3/relationalspaces.dk/httpd.www/consulting/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] The $control_id argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-03-23 10:11:05 [notice X 4][/customers/6/a/3/relationalspaces.dk/httpd.www/consulting/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] The $control_id argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /customers/6/a/3/relationalspaces.dk/httpd.www/consulting/wp-content/plugins/elementor/modules/dev-tools/deprecation.php(301): class type trigger_error()
#2: /customers/6/a/3/relationalspaces.dk/httpd.www/consulting/wp-content/plugins/elementor/includes/managers/controls.php(523): Elementor\Modules\DevTools\Deprecation -> deprecated_argument()
#3: /customers/6/a/3/relationalspaces.dk/httpd.www/consulting/wp-content/plugins/elementor/includes/managers/controls.php(501): Elementor\Controls_Manager -> register()
#4: /customers/6/a/3/relationalspaces.dk/httpd.www/consulting/wp-content/plugins/unlimited-elements-for-elementor/provider/core/plugins/unlimited_elements/elementor/elementor_integrate.class.php(404): Elementor\Controls_Manager -> register_control()
',
)]
PHP: 2022-03-31 15:17:45 [error X 2][/customers/6/a/3/relationalspaces.dk/httpd.www/consulting/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::286] Uncaught Error: Call to a member function update_meta() on null in /customers/6/a/3/relationalspaces.dk/httpd.www/consulting/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:286
Stack trace:
#0 /customers/6/a/3/relationalspaces.dk/httpd.www/consulting/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(167): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions(6, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /customers/6/a/3/relationalspaces.dk/httpd.www/consulting/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /customers/6/a/3/relationalspaces.dk/httpd.www/consulting/wp-includes/class-wp-hook.php(307): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('') [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-04-02 11:43:21 [notice X 1][/customers/6/a/3/relationalspaces.dk/httpd.www/consulting/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatibility not specified
	Unlimited Elements for Elementor: Compatibility not specified

== Elementor Pro - Compatibility Tag ==

**Comment by shilo-ey** [comment] 2022-04-03 06:04
Hi @bodhi1970 

Thank you for sharing this. 

Can you please export and share the `json` template file of your affected structure?

Thanks

**Comment by bodhi1970** [comment] 2022-04-03 10:47
Hi, here is the JSON from the container with the widgets inside.
[elementor-1210-2022-04-03.json.zip](https://github.com/elementor/elementor/files/8404298/elementor-1210-2022-04-03.json.zip)

**Comment by bodhi1970** [comment] 2022-04-03 10:51
Here is the same container with a vanilla button inside
[elementor-1216-2022-04-03.json.zip](https://github.com/elementor/elementor/files/8404306/elementor-1216-2022-04-03.json.zip)
.

**Comment by bodhi1970** [comment] 2022-04-03 14:13
I found out the whole thing does react differently as soon the container where a button is in has a HTML Tag a with a link.
I want to make the whole box clickable but than I probably need to take away the link for the button.

**Comment by nicholaszein** [comment] 2022-11-17 17:41
Hello @bodhi1970!

Is this still an issue with the latest version of Elementor (v3.8)?

**Comment by bodhi1970** [comment] 2022-11-18 11:44
We closed the business and I havn't continued to develop that website. Can't check

**Comment by nicholaszein** [comment] 2022-11-22 04:23
Thank you for the feedback @bodhi1970!

I tried to reproduce your issue but haven't been successful. It seems this is not an issue anymore, or it was related specifically to your case.

I am closing this issue as "can't reproduce".

If you happen to experience this issue again, please feel free to open a new issue!

Kind regards

**Closed by nicholaszein** 2022-11-22 04:23 UTC
Labels: product/dev-edition, component/container
