### ISSUE TITLE
🚀 Feature Request: tooltip New feature for All widgets (Duplicate of #16415, #11302, #5512)

### ISSUE THREAD

**Issue by Joliamendi** [elementor/elementor#18720] opened 2022-05-23 17:07 UTC
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

I really do not know if elementor has ever thought about this feature or not. But it would be great if you could add tooltip feature.
Watch the video below:

https://user-images.githubusercontent.com/103376243/169870879-d113f808-ad9b-4cb4-ab51-317f15063525.mp4

This feature is implemented in the simplest and most complete way possible in the elementor extras plugin. It also has complete settings and customization that leaves no room for flaws. Finally I hope you add this feature to elementor. It is really necessary.
**This feature will be available in the Advanced tab**

Finally, I had a suggestion for this feature, which is not currently implemented in the elementor exteras plugin ...
If you add this feature, it's best to extend it so that we can create multiple tooltips for a widget. Creating multiple tooltips will be very useful for the nav menu widget. If we want to have [such a thing](https://prnt.sc/Q9987uk3HLMN).

### Describe the solution you'd like

tooltip for All widgets

**Comment by 79ho3ein** [comment] 2022-06-02 15:01
#16415

**Comment by nicholaszein** [comment] 2022-10-24 18:01
Duplicate of #16415, #11302, #5512...

Continue the conversation on #16415.

Thanks 🙏

**Closed by nicholaszein** 2022-10-24 18:01 UTC
Labels: request/feature
