### ISSUE TITLE
Gradient colors for texts.

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#17551] opened 2022-01-23 17:37 UTC
- [ ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

It would be great if  add gradient color to the texts. For now, we can only consider simple colors for texts. Adding this feature can be great.
This feature is also already present in some elementor add-ons : https://prnt.sc/26i4udc

thank you

**Comment by perks98** [comment] 2022-01-24 09:13
+1

**Comment by rodolphebertozzo** [comment] 2022-01-26 11:15
+1

**Comment by paauserrat** [comment] 2022-01-26 22:58
Animated gradient too

**Comment by rami-elementor** [comment] 2022-03-10 12:49
Nice feature! You can do that with Custom CSS, see this tutorial: https://fossheim.io/writing/posts/css-text-gradient/

**Comment by arielk** [comment] 2022-09-12 08:59
Duplicate of: https://github.com/elementor/elementor/issues/4676

**Closed by arielk** 2022-09-12 08:59 UTC
Labels: request/enhancement
