### ISSUE TITLE
✅ 🐞 Bug Report: Container widget spacing not applied in editor

### ISSUE THREAD

**Issue by mapsmarketing** [elementor/elementor#20023] opened 2022-10-12 01:47 UTC
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

The following CSS code is applied by Elementor when in frontend:

```
.elementor-element {
    --widgets-spacing: 80px;
}
```

This code creates spacing between widgets by `80px`. However, the spacing is not applied when in editor view which means what-you-see-is-not-what-you-get.

![image](https://user-images.githubusercontent.com/79551469/195228945-7eccbaee-96b0-4684-92d2-2a25d9de9804.png)

### Steps to reproduce

1) Create a new page
2) Go to Edit with Elementor
3) Go to Site Settings > Layout
4) Edit `Gap between elements (px)` and set it `80px` 
5) Save Site Settings
6) Back to edit page
7) Create 3 or more `containers` and add a few widgets in each
8) Compare 'editor' view with `frontend` view

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

<details>
<summary>Click to reveal</summary>

````txt


					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MySQL Community Server (GPL) v5.7.40
	PHP Version: 7.4.32
	PHP Memory Limit: 256M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 64M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.0.2
	Site URL: 
	Home URL: 
	WP Multisite: No
	Max Upload Size: 64 MB
	Memory limit: 40M
	Max Memory limit: 512M
	Permalink Structure: /%postname%/
	Language: en-AU
	Timezone: Australia/Melbourne
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor Child
	Version: 2.4.1
	Author: Elementor Team
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.6.1
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: en_AU
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36

== Active Plugins ==
	Admin Columns Pro
		Version: 4.2.9
		Author: Admin Columns

	Admin Columns Pro - Advanced Custom Fields (ACF)
		Version: 2.2.3
		Author: Admin Columns

	Advanced Custom Fields PRO
		Version: 6.0.2
		Author: WP Engine

	Advanced Editor Tools (previously TinyMCE Advanced)
		Version: 5.6.0
		Author: Automattic

	Advanced Sidebar Menu
		Version: 9.0.2
		Author: OnPoint Plugins

	All-in-One Event Calendar by Time.ly
		Version: 3.0.0
		Author: Time.ly Network Inc.

	BackupBuddy
		Version: 8.7.4.1
		Author: iThemes

	Better Search Replace
		Version: 1.4.1
		Author: Delicious Brains

	Classic Editor
		Version: 1.6.2
		Author: WordPress Contributors

	Elementor
		Version: 3.7.8
		Author: Elementor.com

	Elementor Pro
		Version: 3.7.7
		Author: Elementor.com

	ElementsKit Lite
		Version: 2.7.2
		Author: Wpmet

	Essential Addons for Elementor
		Version: 5.3.2
		Author: WPDeveloper

	Gravity Forms
		Version: 2.6.7
		Author: Gravity Forms

	GTranslate
		Version: 2.9.13
		Author: Translate AI Multilingual Solutions

	InfiniteWP - Client
		Version: 1.9.9
		Author: Revmakx

	MailPoet
		Version: 3.100.1
		Author: MailPoet

	One Click Accessibility
		Version: 2.0.3
		Author: One Click Accessibility

	Prime Slider
		Version: 3.1.1
		Author: BdThemes

	Regenerate Thumbnails
		Version: 3.1.5
		Author: Alex Mills (Viper007Bond)

	Revision Control
		Version: 2.3.2
		Author: Dion Hulse

	Simple Custom Post Order
		Version: 2.5.6
		Author: Colorlib

	Sticky Header Effects for Elementor
		Version: 1.5.3
		Author: Rwattner

	Video User Manuals
		Version: 2.5.12
		Author: Video User Manuals Pty Ltd

	WCAG 2.0 form fields for Gravity Forms
		Version: 1.7.2
		Author: Adrian Gordon

	White Label CMS
		Version: 2.3
		Author: www.videousermanuals.com

	WP Rollback
		Version: 1.7.2
		Author: GiveWP.com

	Yoast SEO
		Version: 19.7.2
		Author: Team Yoast


== Must-Use Plugins ==
	InfiniteWP - Client Loader
		Version: 1.0.1
		Author: Revmakx


== Elementor Experiments ==
	Optimized DOM Output: Inactive by default
	Improved Asset Loading: Inactive by default
	Improved CSS Loading: Inactive by default
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Inactive by default
	Additional Custom Breakpoints: Active
	Import Export Template Kit: Active by default
	Hide native WordPress widgets from search results: Inactive
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active
	Default to New Theme Builder: Inactive
	Hello Theme Header & Footer: Inactive by default
	Landing Pages: Active by default
	Color Sampler: Active by default
	Favorite Widgets: Active by default
	Admin Top Bar: Active by default
	Page Transitions: Active by default
	Notes: Inactive
	Form Submissions: Inactive
	Scroll Snap: Active by default


== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatibility not specified
	Essential Addons for Elementor: Compatibility not specified
	MAPS Elementor: Compatibility not specified
	Sticky Header Effects for Elementor: Compatibility not specified

== Elementor Pro - Compatibility Tag ==

````

</details>

**Comment by nicholaszein** [comment] 2022-10-12 22:13
Hey @mapsmarketing!

Thank you for submitting your issue! 🙏 

Before we continue, please clarify if your issue only happens with Elementor v3.8 and Elementor Pro v3.8 installed, running with only Hello Elementor as your theme. You marked saying this issue only happens with Elementor active, but your **System Info** points out that you have multiple Elementor add-ons installed, not to mention some of them do not have compatibility with the latest version of Elementor.

⚠️ This report is missing key information: 

* **Isolating the problem**: Please make sure you have properly isolated the problem in a staging environment, and that you can consistently reproduce this issue using the Latest Elementor Beta versions (v3.8-Beta4).

👉 Please follow the guidelines for opening a [new issue report](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml), so we can help you better.

Best regards,

Nick

**Comment by mapsmarketing** [comment] 2022-10-12 22:25
Hi @nicholaszein 

Have tested by disabling all plugins with the exception of Elementor (v3.7.8) + Elementor Pro (v3.7.7), which are the latest possible, and Hello Theme. The resulting issue was the same.

Do you require any further information?

Thank you

**Comment by nicholaszein** [comment] 2022-10-12 23:37
Hello @mapsmarketing.

Thanks for confirming this. Since the new beta v3.8, a lot of improvements have been made to the Container, and some of them might have fixed the issues you're reporting. But I myself haven't experienced this issue for quite some time.

Please allow me some time to check this and get back to you with my findings. 🙏

**Comment by mapsmarketing** [comment] 2022-10-12 23:44
No dramas at all @nicholaszein 

I've temporary fixed it by adding the following CSS to the wrapping element:

```
.elementor-element-788dd3c {
    gap: 0;
}
```

It's easier to wait for the v3.8 release and I'll test again, so no stress.

Thank you again for your reply.

**Comment by nicholaszein** [comment] 2022-10-24 22:52
Hello @mapsmarketing,

I just made some tests and I can confirm this issue has been solved in v3.8, which is due to launch soon.

I'll update you when 3.8 is launched!

Cheers 🥂

**Comment by mapsmarketing** [comment] 2022-10-24 22:54
Too easy @nicholaszein

Sincerely appreciate you letting me know mate

**Comment by nicholaszein** [comment] 2022-11-16 06:07
Hey @mapsmarketing!

This issue was resolved in Elementor **v3.8**! 🥳 

✔️ Feel free to update to the latest version!

🥂 Cheers!

**Comment by mapsmarketing** [comment] 2022-11-16 06:14
Legend! Thank you very much @nicholaszein

**Comment by mapsmarketing** [comment] 2022-11-22 22:49
Hi @nicholaszein 

It doesn't look like it has been fixed (please see attached screenshot).

Thank you

![image](https://user-images.githubusercontent.com/79551469/203437027-e0411b0c-e376-4021-90dc-165f267b9ddb.png)

**Comment by nicholaszein** [comment] 2022-11-29 23:27
Hello @mapsmarketing! 

Thank you for your feedback! 🙏 

Please allow me some time to investigate it, and get back to you with my findings. 🧐 

Best regards

**Comment by nicholaszein** [comment] 2023-09-24 17:40
Hey @mapsmarketing!

We have great news! 🙌 

### 📢 We're happy to announce that the issue you raised was finally completely resolved in Elementor v.3.16! 🥳 

The `--widgets-spacing` logical property correctly applies both in the backend and in the frontend!

![image](https://github.com/elementor/elementor/assets/113993460/443e79b5-0628-4725-afd7-5eb97d953269)


✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂

**Closed by nicholaszein** 2023-09-24 17:40 UTC
Labels: bug, type/layout, component/container, solved_by_container, mod*, product/3.16
