### ISSUE TITLE
🔗 🚀 Feature Request: Media Carousel - Provide a way to add Dynamic Galleries with custom fields (Duplicate of #20306)

### ISSUE THREAD

**Issue by carterwe** [elementor/elementor#20351] opened 2022-11-09 17:35 UTC
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

No option to choose Dynamic Slides and specify the ACF Gallery field on the Elementor Pro Media Carousel.  

### Describe the solution you'd like

Need to be able to choose Dynamic Slides and specify the ACF Gallery field on the Elementor Pro Media Carousel.  

### Describe alternatives you've considered

Other plugins have this option but they are buggy and problematic - not having the robustness of Elementor Solutions!

### Additional context

This has been requested by many people on many forums going on four years now.  See specifically the multiple requests on comments to this fine article by Ben Pines. https://elementor.com/blog/introducing-media-carousel/

**Comment by nicholaszein** [comment] 2022-11-14 02:49
Hello @carterwe!

Thank you for your submission! 🙏 

### 🔗 This issue is a Duplicate of #20306

Which is on the same subject. 

For this reason, I'm closing this issue and 🔃 **Merging** it with the original, so we can have all the discussions in one location, and deal with it more efficiently.

Feel free to continue the conversation there. 😉 

### ✔️ Please, in the future, remember to check if there isn't an issue similar to yours already opened. 

Best regards,

Nick

**Closed by nicholaszein** 2022-11-14 02:49 UTC
Labels: request/enhancement, product/pro, component/carousel, component/dynamic-tag, type/dynamic-content
