### ISSUE TITLE
✅ 🔗 🔣 🐞 Bug Report: The translation for the "Publish" button is truncated in German (Related to #19585)

### ISSUE THREAD

**Issue by LukasSchuetter** [elementor/elementor#22472] opened 2023-05-17 14:50 UTC
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

In the new top bar, the text of the "Publish" button (in German it is called "Veröffentlichen") is truncated on the left and right due to the length of the text. See the screenshot https://ibb.co/zP5LdTW.

### Steps to reproduce

1) On every page in the backend

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently following the steps above.

### System Info

<details>
<summary>System Info</summary>

````txt



== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MariaDB Server v10.3.39
	PHP Version: 8.1.19
	PHP Memory Limit: 128M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 32M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.2.1
	Site URL: https://www.camping-almen.at
	Home URL: https://www.camping-almen.at
	WP Multisite: No
	Max Upload Size: 16 MB
	Memory limit: 40M
	Max Memory limit: 512M
	Permalink Structure: /%postname%/
	Language: de-DE
	Timezone: 0
	Admin Email: admin@doppelpack.com
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor Child
	Version: 2.0.0
	Author: Elementor Team
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.7.1
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: de_DE
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36

== Active Plugins ==
	Advanced Custom Fields PRO
		Version: 6.1.6
		Author: WP Engine

	Borlabs Cookie - Cookie Opt-in
		Version: 2.2.63
		Author: Borlabs GmbH

	DP Blocks
		Version: 4.0.9
		Author: Timon Scheibner | Doppelpack Werbeagentur

	DP Lightbox
		Version: 1.0.0
		Author: Timon Scheibner | Doppelpack Werbeagentur

	Elementor
		Version: 3.13.2
		Author: Elementor.com

	Elementor Pro
		Version: 3.13.1
		Author: Elementor.com

	Formidable Forms
		Version: 6.3
		Author: Strategy11 Form Builder Team

	Formidable Forms Pro
		Version: 6.3
		Author: Strategy11

	iThemes Security Pro
		Version: 7.3.4
		Author: iThemes

	Rank Math SEO
		Version: 1.0.114
		Author: Rank Math

	Rank Math SEO PRO
		Version: 3.0.32
		Author: Rank Math


== Elemente Verwendung ==
	


== Einstellungen ==
	
	cpt_support: post, page
	allow_tracking: yes
	font_display: swap


== Features ==
	Custom Fonts: 0
	Custom Icons: 0

== Integrations ==
	


== Elementor-Experimente ==
	Optimierte DOM Ausgabe: Aktiv
	Verbessertes Laden von Assets: Aktiv
	Verbessertes Laden von CSS: Aktiv
	Inline-Schriftarten-Symbole: Aktiv
	Verbesserungen der Zugänglichkeit: Aktiv
	Zusätzliche benutzerdefinierte Breakpoints: Standardmäßig aktiviert
	admin_menu_rearrangement: Standardmäßig deaktiviert
	Flexbox Container: Aktiv
	Upgrade Swiper Library: Aktiv
	Grid Container: Aktiv
	Default to New Theme Builder: Standardmäßig aktiviert
	Hello Theme Header &amp; Footer: Aktiv
	Editor Top Bar: Aktiv
	Startseiten: Aktiv
	Nested Elements: Aktiv
	Lazy Load Background Images: Aktiv
	Page Transitions: Standardmäßig aktiviert
	Notes: Standardmäßig aktiviert
	Loop: Standardmäßig aktiviert
	Form Submissions: Standardmäßig aktiviert
	Scroll Snap: Standardmäßig aktiviert
	Menu: Standardmäßig deaktiviert


== Protokoll ==
	
PHP: showing 1 of 1PHP: 2023-05-17 11:27:42 [notice X 1][/var/www/vhosts/camping-almen.at/httpdocs/wp-content/plugins/elementor/core/upgrade/manager.php::63] version_compare(): Passing null to parameter #1 ($version1) of type string is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]



== Elementor - Compatibility Tag ==
	
	Elementor Pro: Die Kompatibilität ist nicht angegeben

== Elementor Pro - Compatibility Tag ==
	


````

</details>

**Comment by m1ga** [comment] 2023-05-17 22:02
The same for the old/current button. Tried to change it already https://github.com/elementor/elementor/issues/19585#issuecomment-1225691209 and the Elementor team saw and replied in that thread but nothing changed so far.

**Comment by nicholaszein** [comment] 2023-05-18 19:25
Hello @LukasSchuetter!

Thank you for your submission! 🙏 

### 🔗 🐞 This issue is a Duplicate of #19585 

Which is on the same subject. 

For this reason, I'm closing this thread and 🔃 **Merging** it with the original, so we can have all the discussions in one location, and deal with it more efficiently.

Feel free to continue the conversation there. 😉 

### 🔍 Please, in the future, remember to check if there isn't any thread similar to yours already opened. 

Best regards,

Nick

**Comment by nicholaszein** [comment] 2023-08-02 00:53
Hello there!

We have great news! 🙌 

### 📢 We're happy to announce that the issue you raised was resolved in Elementor Core v.3.15.0! 🥳 

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂

**Closed by nicholaszein** 2023-08-02 00:53 UTC
Labels: bug, type/ui/ux, component/editor, status/merged, type/internationalization, 🚀 shipped, component/editor/top-bar, mod*, product/3.15
