### ISSUE TITLE
Elementor Pro Forms MailChimp Conditional Opt-in Field

### ISSUE THREAD

**Issue by gamertan** [elementor/elementor#10038] opened 2020-01-01 22:16 UTC
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

I'm looking for a way to stay in compliance with local requirements for newsletter subscriptions "opt-ins". I have a number of contact forms / estimate forms that I'd like to add a "sign up for our newsletter" checkbox to, then conditionally complete the "MailChimp" action based on the value returned by the user for that field.

**Describe the solution you'd like**

I would love to see an option to select the "opt-in" field in a form with a "true/false" value for newsletter sign up in the MailChimp action. Similar to how you can select the "reply-to" email field value, I'd love to see a select referring to a field used as an "opt-in" condition. 

**Describe alternatives you've considered**

I've alternatively considered adding in separate "newsletter sign up" forms to landing pages, but it's unlikely that a user will take the time to fill out two forms than just a single form submission through something like a "request a quote" or "contact us" form. Additionally, if we're redirecting to a "thank you" page, we're "worst case" asking them to fill out a second form, hoping that they complete the action. These just aren't sufficient considering there are other "form plugins" that allow for this type of functionality.

**Additional context**

This is critical for a number of my clients marketing efforts. The need for this feature is compounded by the fact that MailChimp now has a "website builder" that a number of my clients are pushing me to investigate for their marketing efforts. I would hate to see a "landing page" created outside Elementor, as it's just so good at achieving everything else I'm looking for in one. 

Additionally, there are a number of actions that could use some conditional love. I could see the need for a conditional "second email", "slack", "webhook" or even conditional "redirect" happening. Just a thought!

**Comment by Maxxeen** [comment] 2020-01-07 16:20
I agree.  I've spent a few days trying to figure out how to implement a simple opt-in to existing contact forms.  It seems crazy that this feature, which is so common on other websites, is so hard to implement within Elementor.

**Comment by shilo-ey** [comment] 2020-03-02 17:34
Duplicate of #2638

**Closed by shilo-ey** 2020-03-02 17:34 UTC
Labels: mod*

**Comment by scottybo** [comment] 2020-05-21 16:20
@shilo-ey this isn't a duplicate of #2638 - it's similar, but not a duplicate.

What is being suggested is that the 'Action after submit' options can be executed on a condition laid out in the form.

**Comment by captaincoo1** [comment] 2020-08-07 15:38
I am looking for MailChimp conditional opt-in too.

**Comment by robmaric** [comment] 2020-09-13 00:28
I find the absence of this option mind-boggling. What do I do now? Re-do the whole form in CF7? Please add this small, but important feature in.

**Comment by scottybo** [comment] 2020-09-13 06:52
I think we might develop a plugin for this, something like 'Conditional actions after submit' - it's something every client asks for (I.e. A newsletter opt-in checkbox on every contact form)

**Comment by synio-wesley** [comment] 2021-03-12 12:30
I needed this functionality too. I couldn't (quickly) find usable hooks in Elementor, so I ended up simply filtering the pre_http_request to 'api.mailchimp.com' and short-circuiting it when an opt-in field hasn't been checked.

It works as follows:
* Add an acceptance checkbox with **required set to false** and **set the id to something custom**
* Add a hidden field with id **newsletter_optin_field** and **set the value to the custom id** of the opt-in acceptance checkbox

Now, when the code runs, it checks whether this hidden field exists, and if so, it checks whether the acceptance checkbox has been ticked or not. If it hasn't been ticked, the HTTP request is short-circuited. Elementor only really cares about the '200 OK' response so everything still works, but the Mailchimp call is not happening anymore when the box is not ticked.

Maybe not the cleanest solution, but it works, and might be useful as a workaround until this is supported in an official way.

```
// Mailchimp opt-in checkbox for Elementor Form
add_filter('pre_http_request', function ($preempt, $parsed_args, $url) {
    // Only run this code when an Elementor Pro form has been submitted
    if (!isset($_POST['action']) || $_POST['action'] != 'elementor_pro_forms_send_form') {
        return $preempt;
    }

    // Only run this when trying to contact the Mailchimp API
    if (strpos($url, 'api.mailchimp.com') !== false) {
        $form_fields = $_POST['form_fields'] ?? [];

        if (!is_array($form_fields) || empty($form_fields)) {
            return $preempt;
        }

        // Check if there is an opt-in field defined (hidden field)
        if (array_key_exists('newsletter_optin_field', $form_fields)) {
            $optin_field = $form_fields['newsletter_optin_field'];

            // Check if the user hasn't opted in (hasn't ticked the box)
            if (!array_key_exists($optin_field, $form_fields)) {
                // Short-circuit Mailchimp API call
                return [
                    'headers' => '',
                    'body' => '{"simulation":true}',
                    'response' => [
                        'code' => '200',
                        'message' => 'OK',
                    ],
                    'cookies' => '',
                    'filename' => '',
                ];
            }
        }
    }

    return $preempt;
}, 10, 3);
```

**Comment by pgm-nicolascnudde** [comment] 2021-03-23 21:39
> I needed this functionality too. I couldn't (quickly) find usable hooks in Elementor, so I ended up simply filtering the pre_http_request to 'api.mailchimp.com' and short-circuiting it when an opt-in field hasn't been checked.
> 
> It works as follows:
> 
>     * Add an acceptance checkbox with **required set to false** and **set the id to something custom**
> 
>     * Add a hidden field with id **newsletter_optin_field** and **set the value to the custom id** of the opt-in acceptance checkbox
> 
> 
> Now, when the code runs, it checks whether this hidden field exists, and if so, it checks whether the acceptance checkbox has been ticked or not. If it hasn't been ticked, the HTTP request is short-circuited. Elementor only really cares about the '200 OK' response so everything still works, but the Mailchimp call is not happening anymore when the box is not ticked.
> 
> Maybe not the cleanest solution, but it works, and might be useful as a workaround until this is supported in an official way.
> 
> ```
> // Mailchimp opt-in checkbox for Elementor Form
> add_filter('pre_http_request', function ($preempt, $parsed_args, $url) {
>     // Only run this code when an Elementor Pro form has been submitted
>     if (!isset($_POST['action']) || $_POST['action'] != 'elementor_pro_forms_send_form') {
>         return $preempt;
>     }
> 
>     // Only run this when trying to contact the Mailchimp API
>     if (strpos($url, 'api.mailchimp.com') !== false) {
>         $form_fields = $_POST['form_fields'] ?? [];
> 
>         if (!is_array($form_fields) || empty($form_fields)) {
>             return $preempt;
>         }
> 
>         // Check if there is an opt-in field defined (hidden field)
>         if (array_key_exists('newsletter_optin_field', $form_fields)) {
>             $optin_field = $form_fields['newsletter_optin_field'];
> 
>             // Check if the user hasn't opted in (hasn't ticked the box)
>             if (!array_key_exists($optin_field, $form_fields)) {
>                 // Short-circuit Mailchimp API call
>                 return [
>                     'headers' => '',
>                     'body' => '{"simulation":true}',
>                     'response' => [
>                         'code' => '200',
>                         'message' => 'OK',
>                     ],
>                     'cookies' => '',
>                     'filename' => '',
>                 ];
>             }
>         }
>     }
> 
>     return $preempt;
> }, 10, 3);
> ```

I don't have much experience with hooks. Could you tell me where exactly I have to put this?

**Comment by synio-wesley** [comment] 2021-03-23 22:23
> I don't have much experience with hooks. Could you tell me where exactly I have to put this?

You could [create a simple plugin](https://developer.wordpress.org/plugins/plugin-basics/) for this, or maybe paste it in `functions.php` if you are using a [custom child theme](https://developer.wordpress.org/themes/advanced-topics/child-themes/).

**Comment by pgm-nicolascnudde** [comment] 2021-03-23 22:59
> > I don't have much experience with hooks. Could you tell me where exactly I have to put this?
> 
> You could [create a simple plugin](https://developer.wordpress.org/plugins/plugin-basics/) for this, or maybe paste it in `functions.php` if you are using a [custom child theme](https://developer.wordpress.org/themes/advanced-topics/child-themes/).

Was able to put it in the functions.php and seems to be working fine, thx!

**Comment by davidamarek** [comment] 2021-03-28 06:30
+1

**Comment by alexmuu** [comment] 2021-05-11 12:05
> I needed this functionality too. I couldn't (quickly) find usable hooks in Elementor, so I ended up simply filtering the pre_http_request to 'api.mailchimp.com' and short-circuiting it when an opt-in field hasn't been checked.
> 
> It works as follows:
> 
> * Add an acceptance checkbox with **required set to false** and **set the id to something custom**
> * Add a hidden field with id **newsletter_optin_field** and **set the value to the custom id** of the opt-in acceptance checkbox
> 
> Now, when the code runs, it checks whether this hidden field exists, and if so, it checks whether the acceptance checkbox has been ticked or not. If it hasn't been ticked, the HTTP request is short-circuited. Elementor only really cares about the '200 OK' response so everything still works, but the Mailchimp call is not happening anymore when the box is not ticked.
> 
> Maybe not the cleanest solution, but it works, and might be useful as a workaround until this is supported in an official way.
> 
> ```
> // Mailchimp opt-in checkbox for Elementor Form
> add_filter('pre_http_request', function ($preempt, $parsed_args, $url) {
>     // Only run this code when an Elementor Pro form has been submitted
>     if (!isset($_POST['action']) || $_POST['action'] != 'elementor_pro_forms_send_form') {
>         return $preempt;
>     }
> 
>     // Only run this when trying to contact the Mailchimp API
>     if (strpos($url, 'api.mailchimp.com') !== false) {
>         $form_fields = $_POST['form_fields'] ?? [];
> 
>         if (!is_array($form_fields) || empty($form_fields)) {
>             return $preempt;
>         }
> 
>         // Check if there is an opt-in field defined (hidden field)
>         if (array_key_exists('newsletter_optin_field', $form_fields)) {
>             $optin_field = $form_fields['newsletter_optin_field'];
> 
>             // Check if the user hasn't opted in (hasn't ticked the box)
>             if (!array_key_exists($optin_field, $form_fields)) {
>                 // Short-circuit Mailchimp API call
>                 return [
>                     'headers' => '',
>                     'body' => '{"simulation":true}',
>                     'response' => [
>                         'code' => '200',
>                         'message' => 'OK',
>                     ],
>                     'cookies' => '',
>                     'filename' => '',
>                 ];
>             }
>         }
>     }
> 
>     return $preempt;
> }, 10, 3);
> ```

Hi there,

how would you set up the hidden field with the dynamic value?

I've created a hidden field in elementor and pasted the shortcode of the acceptance field into the default value of the hidden field.
I guess the default value won't be updated with the acceptance field though, will it?

Thank you in advance!

**Comment by synio-wesley** [comment] 2021-05-11 12:10
> how would you set up the hidden field with the dynamic value?
> 
> I've created a hidden field in elementor and pasted the shortcode of the acceptance field into the default value of the hidden field.
> I guess the default value won't be updated with the acceptance field though, will it?

With my code, you should just paste the identifier of the checkbox/acceptance field. Not the full shortcode.

Also make sure that the identifier for the hidden field is 'newsletter_optin_field'.

**Comment by alexmuu** [comment] 2021-05-11 12:21
> > how would you set up the hidden field with the dynamic value?
> > I've created a hidden field in elementor and pasted the shortcode of the acceptance field into the default value of the hidden field.
> > I guess the default value won't be updated with the acceptance field though, will it?
> 
> With my code, you should just paste the identifier of the checkbox/acceptance field. Not the full shortcode.
> 
> Also make sure that the identifier for the hidden field is 'newsletter_optin_field'.

Okay, seems easy enough.
How does the code get the value from the acceptance field though?

Thanks!

**Comment by synio-wesley** [comment] 2021-05-11 13:24
> Okay, seems easy enough.
> How does the code get the value from the acceptance field though?

The acceptance/checkbox field is either ticked/checked or not ticked/checked.

I'm checking if it has or has not been ticked/checked here using `array_key_exists($optin_field, $form_fields)` in my code snippet.

**Comment by alexmuu** [comment] 2021-05-12 07:56
> > Okay, seems easy enough.
> > How does the code get the value from the acceptance field though?
> 
> The acceptance/checkbox field is either ticked/checked or not ticked/checked.
> 
> I'm checking if it has or has not been ticked/checked here using `array_key_exists($optin_field, $form_fields)` in my code snippet.

Alright, thank you for your explanation!

**Comment by fontaholic** [comment] 2021-07-12 20:06
i get this error when i add your code and submit a test....
`MailChimp HTTP 400 - The resource submitted could not be validated. For field-specific details, see the 'errors' array.
This Message is not visible for site visitors.`

**Comment by Mathieu2HB** [comment] 2021-11-13 21:25
Thanks a lot @synio-wesley ! This works great, except that I get an error message when validating the form (even if it's sending the message correctly). As if the form "validation message" was happening separately from the actual process.
Any idea how to address this? Thanks

**Comment by windkracht20-nl** [comment] 2021-12-23 21:23
> Thanks a lot @synio-wesley ! This works great, except that I get an error message: "_An error occurred. MailChimp HTTP 200 - This Message is not visible for site visitors."_ when validating the form (even if it's sending the message correctly). As if the form "validation message" was happening separately from the actual process. Any idea how to address this? Thanks
> 
> If it can help, I also have this log error: .../plugins/elementor-pro/modules/forms/actions/mailchimp.php::258] Undefined array key "email_address" [array ( 'trace' => '

I'm getting the same error message. Were you able to solve the issue?

**Comment by zanga7** [comment] 2022-01-10 04:42
I have the same error message. If I use in incognito, it just gives the default error message "An error occurred." but still collects the message. In the email log, it says "Mailchimp. HTTP 200 -" which is fine. But we dont want to say to users there was an error. Any ideals on how to resolve here?

**Comment by zanga7** [comment] 2022-01-10 04:56
@windkracht20-nl  @Mathieu2HB @synio-wesley 
Did you guys get anywhere with this error?

**Comment by synio-wesley** [comment] 2022-01-14 16:17
> @windkracht20-nl @Mathieu2HB @synio-wesley Did you guys get anywhere with this error?

I cannot reproduce this. If you want me to investigate, I need a way to reproduce this. Easiest would be if you can give me temporary access through SSH, or if you can set up a temporary server where the issue is, or if you can prepare a Docker image with the issue so I can debug it locally.

Maybe I can also reproduce it if you give me your exact WP + Elementor versions + full form configuration.

**Comment by windkracht20-nl** [comment] 2022-01-16 12:49
Hi, thanks for reaching out. It looks like it's indeed related to some version number of WP/Elementor. We update to the latest versions of both and now it's working fine. Unfortunately I don't know the exact version numbers of both where the issue did occur. But at least it's good to know it's working great now! Many thanks for your work!

**Comment by zorrobiwan** [comment] 2022-03-09 15:46
Would be great if this could be implemented in Elementor in any way :)

**Comment by genuino2** [comment] 2022-05-24 12:42
> > @windkracht20-nl @Mathieu2HB @synio-wesley Did you guys get anywhere with this error?
> 
> I cannot reproduce this. If you want me to investigate, I need a way to reproduce this. Easiest would be if you can give me temporary access through SSH, or if you can set up a temporary server where the issue is, or if you can prepare a Docker image with the issue so I can debug it locally.
> 
> Maybe I can also reproduce it if you give me your exact WP + Elementor versions + full form configuration.

same to me,:
An error occurred. MailChimp HTTP 200 - This Message is not visible for site visitors.

If you need i could give access to check. I've the latest version of Elementor Pro and Wordpress.

**Comment by synio-wesley** [comment] 2022-05-24 14:18
I debugged this issue on @genuino2 his site.

Apparently, my code is not taking into account the possibility that you might want to add tags to Mailchimp. But we're always mocking status code `200` (`OK`) for the `pre_http_request` when we're simulating the request instead of actually executing it. However, the Mailchimp action code expects code `204` (`No content`) when adding tags. So we need to simulate this code when needed.

The fix is simply to check the end of the URL. If it ends with `/tags` then we use code `204` instead of `200`.

Updated code here:

```php
// Mailchimp opt-in checkbox for Elementor Form
// Version 2.0 - This one also works when you use Mailchimp tags
add_filter('pre_http_request', function($preempt, $parsed_args, $url) {
    // Only run this code when an Elementor Pro form has been submitted
    if (!isset($_POST['action']) || $_POST['action'] != 'elementor_pro_forms_send_form') {
        return $preempt;
    }

    // Only run this when trying to contact the Mailchimp API
    if (strpos($url, 'api.mailchimp.com') !== false) {
        $form_fields = $_POST['form_fields'] ?? [];

        if (!is_array($form_fields) || empty($form_fields)) {
            return $preempt;
        }

        // Check if there is an opt-in field defined (hidden field)
        if (array_key_exists('newsletter_optin_field', $form_fields)) {
            $optin_field = $form_fields['newsletter_optin_field'];

            // Check if the user hasn't opted in (hasn't ticked the box)
            if (!array_key_exists($optin_field, $form_fields)) {
                // Short-circuit Mailchimp API call
                return [
                    'headers' => '',
                    'body' => '{"simulation":true}',
                    'response' => [
                        'code' => substr($url, -5) === '/tags' ? 204 : 200,
                        'message' => 'OK',
                    ],
                    'cookies' => '',
                    'filename' => '',
                ];
            }
        }
    }

    return $preempt;
}, 10, 3);
```

**Comment by uniqwork** [comment] 2022-05-31 20:08
Just made an account to thank you @synio-wesley.
Thank you sooo much! Been looking for this stuff for a long time and never found a solution. This worked like a charm, thanks so much

They should implement this asap!
Could you also adapt this code into like checkbox 1 = audience 1 in mailchimp and checkbox 2 = audience 2?
Just as an idea :)

cheers!
Phil

**Comment by genuino2** [comment] 2022-06-01 05:38
Imo two different audiences is not easy to develop and is not the best way
to use mailchimp. Use the same audience with tag or segment, like mailchimp
guidelines suggest:

"As a best practice, we recommend you maintain only one primary audience in
Mailchimp, and use tags and segments to organize and target your contacts."
Source: https://mailchimp.com/en/help/create-audience/

Il giorno mar 31 mag 2022 alle ore 22:08 uniqwork GmbH <
***@***.***> ha scritto:

**Comment by donolsch** [comment] 2022-06-03 13:00
> I debugged this issue on @genuino2 his site.
> 
> Apparently, my code is not taking into account the possibility that you might want to add tags to Mailchimp. But we're always mocking status code `200` (`OK`) for the `pre_http_request` when we're simulating the request instead of actually executing it. However, the Mailchimp action code expects code `204` (`No content`) when adding tags. So we need to simulate this code when needed.
> 
> The fix is simply to check the end of the URL. If it ends with `/tags` then we use code `204` instead of `200`.
> 
> This is the only line that we changed from the original workaround code: ` 'code' => substr($url, -5) === '/tags' ? 204 : 200,` instead of `'code' => '200',`
> 
> Updated code here:
> 
> ```
> // Mailchimp opt-in checkbox for Elementor Form
> // Version 2.0 - This one also works when you use Mailchimp tags
> add_filter('pre_http_request', function($preempt, $parsed_args, $url) {
>     // Only run this code when an Elementor Pro form has been submitted
>     if (!isset($_POST['action']) || $_POST['action'] != 'elementor_pro_forms_send_form') {
>         return $preempt;
>     }
> 
>     // Only run this when trying to contact the Mailchimp API
>     if (strpos($url, 'api.mailchimp.com') !== false) {
>         $form_fields = $_POST['form_fields'] ?? [];
> 
>         if (!is_array($form_fields) || empty($form_fields)) {
>             return $preempt;
>         }
> 
>         // Check if there is an opt-in field defined (hidden field)
>         if (array_key_exists('newsletter_optin_field', $form_fields)) {
>             $optin_field = $form_fields['newsletter_optin_field'];
> 
>             // Check if the user hasn't opted in (hasn't ticked the box)
>             if (!array_key_exists($optin_field, $form_fields)) {
>                 // Short-circuit Mailchimp API call
>                 return [
>                     'headers' => '',
>                     'body' => '{"simulation":true}',
>                     'response' => [
>                         'code' => substr($url, -5) === '/tags' ? 204 : 200,
>                         'message' => 'OK',
>                     ],
>                     'cookies' => '',
>                     'filename' => '',
>                 ];
>             }
>         }
>     }
> 
>     return $preempt;
> }, 10, 3);
> ```

Amazing! Works like a charm! Thank you.
Pretty sad that this is not a native Elementor forms feature though.

**Comment by uniqwork** [comment] 2022-06-03 21:47
> 

Interesting! Thanks for explaining.
But how do we say the code please set Tag A and Tag B (...n) while filling out the form.
Of course you can say in elementor action after submit, but then again, its not dynamic or an if condition for more than 1 tag

**Comment by 0merSharon** [comment] 2022-06-06 12:21
I had to improve this perfect solution,
Now we can use default checkbox/acceptance type of field without the hidden one, also we are not limited to one id per page.

Just use an id that start with "mailchimp_accept_" for the checkbox/acceptance.
Examples: "mailchimp_accept_popup" / "mailchimp_accept_footer"


```
// Mailchimp opt-in checkbox for Elementor Form
// Version 2.0 - This one also works when you use Mailchimp tags
add_filter('pre_http_request', function($preempt, $parsed_args, $url) {
    // Only run this code when an Elementor Pro form has been submitted
    if (!isset($_POST['action']) || $_POST['action'] != 'elementor_pro_forms_send_form') {
        return $preempt;
    }

    // Only run this when trying to contact the Mailchimp API
    if (strpos($url, 'api.mailchimp.com') !== false) {
        $form_fields = $_POST['form_fields'] ?? [];

        if (!is_array($form_fields) || empty($form_fields)) {
            return $preempt;
        }
        
        // Check if there is an opt-in field defined that start with mailchimp_accept
        $ID = "";
        foreach(array_keys($form_fields) as $formKey)
        {
            if(strpos($formKey, "mailchimp_accept") !== false)
                $ID = $formKey;
        }

        // If not found any key means not approved
        if (empty($ID)) {
            // Short-circuit Mailchimp API call
            return [
                'headers' => '',
                'body' => '{"simulation":true}',
                'response' => [
                    'code' => substr($url, -5) === '/tags' ? 204 : 200,
                    'message' => 'OK',
                ],
                'cookies' => '',
                'filename' => '',
            ];
        }
    }

    return $preempt;
}, PHP_INT_MAX, 3);
```


Hope that it will help some of you

**Comment by Yarin-Shitrit** [comment] 2022-07-27 08:37
> 
Fantastic solution, easy to implement and works great.
Thank you !

**Comment by synio-wesley** [comment] 2022-11-17 09:31
I talked to the Global Community Manager of Elementor in September 2022 at Wordcamp Netherlands. I briefly discussed this issue and my workaround and asked if they could make it native functionality. They told me to send them a mail or message on WhatsApp, so I did both. After a few days I got a reply that they would put a new recruit on this issue. But I haven't heard back yet. 2 months have passed now. I just asked for another status update but I'm still awaiting feedback.

**Comment by synio-wesley** [comment] 2022-11-18 12:39
UPDATE: I got a reply from the Global Community Manager. He says that the new recruit began working at a later time than expected and that he forgot to mention the Github issues to him because of that.

He asked me to tag him and his colleague. So that's what I will do now. Hopefully Elementor Pro will soon be able to add a conditional opt-in field for MailChimp forms (and maybe other forms as well) as it is a highly requested feature and one that would be very welcome for everyone using Elementor with the Forms module.

@nicholaszein @VerdiH Thanks for looking into this for us! I briefly looked into the code before and I could create a pull request to fix this if you want. If you promise to accept a (good) pull request for this feature, then I will take a stab at implementing this missing functionality. [Right now I created a workaround but it's a very ugly hack.](#issuecomment-1135990334)

**Comment by nicholaszein** [comment] 2022-12-28 05:52
Hello everyone, this is Nick, the "new recruit guy"! 👋

I wanted to give you an update on this feature request.

First of all, thank you for your patience! 🙏 

I know you have been waiting for an update on this request, and I understand the frustration of not having the option to conditionally execute actions after the user submits for things like adding the user to a Mailchimp list.

That being said, we have no plans to implement this feature request for the time being. There are other broader requests like adding conditions to forms (which could or not include conditions to actions after submission) that are being considered, and when we decide to implement them, we will let everyone know.

I hope you can understand.

Kind regards

**Comment by synio-wesley** [comment] 2023-01-05 22:12
@nicholaszein If I were to create a pull request to add this missing functionality in a clean way, would it get accepted? I would take the time to implement it in a clean way. But not if there's no chance of it getting accepted. (I have a lot of real work to do as well.)

**Comment by markosansa** [comment] 2023-02-14 00:24
Hello, 
Any update on this topic? Is it still considered a not relevant functionality to be included?

**Comment by nicholaszein** [comment] 2023-05-24 21:58
Hey @synio-wesley,

apologies for the delay. Surely we would consider it if you take it up to submit a PR! 💪 😉

**Comment by abbasdv** [comment] 2023-06-05 14:49
When will this be added?

**Comment by synio-wesley** [comment] 2023-06-16 10:07
@nicholaszein There is no git repo for the Pro plugin that I can access. How should I create the PR?

**Comment by synio-wesley** [comment] 2023-06-29 23:51
@nicholaszein Or should I send a patch file? Or maybe you can invite me to your internal Git repo? I don't know what would be possible? I'd like to help you out with a few features that are bothering me. But only Elementor free is available publicly on GitHub. And I'd like to submit a PR for Elementor Pro.

**Comment by nicholaszein** [comment] 2023-07-18 00:14
@synio-wesley,

sorry for the delay in the response. I've been talking with the team, and we've considered opening contributions for Elementor Pro, but ultimately we decided against it for reasons I can't disclose. I'm really sorry for giving you the hope it would be possible. It was a mistake and I apologize.

You could, however, create an add-on for the forms widget with a different `Action` for the Mailchimp integration that includes the functionality you are requesting. You can follow the documentation to create your own add-on [here](https://developers.elementor.com/docs/getting-started/first-addon/), and you can use one of the available hooks [here](https://developers.elementor.com/docs/hooks/forms/#action-after-email-sent-successfully).

I hope this helps.

Kind regards
