### ISSUE TITLE
🔗 🚀 Feature Request: Custom control for connecting query to any widget containing a repeater (duplicate of #20201, Related to #19405)

### ISSUE THREAD

**Issue by elasticeye** [elementor/elementor#20761] opened 2022-12-15 12:13 UTC
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

Custom control for connecting query to any widget containing a repeater. 
Probably will work best for widgets where content is added with a repeater – Slider, Timeline, Testimonials, Tabs, etc.

### Describe the solution you'd like

Connect a loop query to a (repeater) widget, not just to a normal post.

### Describe alternatives you've considered

https://github.com/Crocoblock/suggestions/issues/6181

**Comment by nicholaszein** [comment] 2023-01-03 04:41
Hello @elasticeye!

Thank you for your submission! 🙏 

### 🔗 This issue is a Duplicate of #20201 and Related to #19405.

Which are on the same subject. 

For this reason, I'm closing this issue and 🔃 **Merging** it with the original, so we can have all the discussions in one location, and deal with it more efficiently.

Feel free to continue the conversation there. 😉 

### ✔️ Please, in the future, remember to check if there isn't an issue similar to yours already opened. 

Best regards,

Nick

**Closed by nicholaszein** 2023-01-03 04:41 UTC
Labels: request/feature, component/carousel, solved_by_loop, component/loop-builder
