### ISSUE TITLE
⌛ 🧩 Anchor Links and Lightbox images don't work after updating Elementor to version 3.23 when using Elementor addons

### ISSUE THREAD

**Issue by pg-los** [elementor/elementor#28065] opened 2024-07-15 12:24 UTC
### Prerequisites

- [X] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [ ] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

- I can't get images that are set to lightbox to actually launch lightbox
- I can't get anchor links to sections in the same page to work

The issue appears evident in my page https://lexiconofimpacts.com/coastal-restoration/impact-areas/ (password: adb) and when you click on any of the images in the page they won't launch on lightbox.
Furthermore, if you click on any of the anchor links in the hero section, the page won't scroll to the relative anchor point.

This is a problem that appears in the console, and I am attaching a screenshot)
![Screenshot 2024-07-15 at 13 15 35](https://github.com/user-attachments/assets/78a4cab7-725e-4928-8c41-a174efe336ad)

The issue is site-wise. Please can we find a solution as this is very frustrating.

P.S.: I have tried to clear any server-side and browser caches, and the error is still there. I have tried to de-activate plugins one by one, and the issue seems to still be there. I have contacted Elementor help and no solution was provided. please help!

### Steps to reproduce

1. go to https://lexiconofimpacts.com/coastal-restoration/impact-areas/
2. insert password: adb
3. click on any of the elements in the list of chapters in the hero section and notice how the links won't work
4. click on any of the images attached under the hero section and notice how none of them open up in lightbox
![Screenshot 2024-07-10 at 12 03 23](https://github.com/user-attachments/assets/83ca0c09-b4e5-43d7-aff3-6e2ec881707e)
<img width="2307" alt="Screenshot 2024-07-15 at 13 19 24" src="https://github.com/user-attachments/assets/2ee92828-a2f7-43db-9d5e-032a2df82bf9">

### Expected behavior

1. clicking on any of the elements in the list of chapters in the hero section should make the page scroll to the relative section of the page
2.  clicking on any of the images attached under the hero section should make them open up in lightbox

### Isolating the problem

- [ ] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [X] This bug happens with the Hello Elementor theme active.
- [X] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

<details>
<summary>Click to reveal</summary>

````txt

== Server Environment ==
	Operating System: Linux
	Software: nginx/1.25.5
	MySQL version: mariadb.org binary distribution v10.11.8-MariaDB-ubu2004
	PHP Version: 8.1.29
	PHP Memory Limit: 256M
	PHP Max Input Vars: 10000
	PHP Max Post Size: 128M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.5.5
	Site URL: https://lexiconofimpacts.com
	Home URL: https://lexiconofimpacts.com
	WP Multisite: No
	Max Upload Size: 128 MB
	Memory limit: 40M
	Max Memory limit: 256M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: en_US
	Timezone: America/Los_Angeles
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor Child
	Version: 2.0.0
	Author: Elementor Team
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 3.1.0
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: en-US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36

== Active Plugins ==
	ACF Content Analysis for Yoast SEO
		Version: 3.1
		Author: Thomas Kräftner, ViktorFroberg, marol87, pekz0r, angrycreative, Team Yoast

	Advanced Custom Fields PRO
		Version: 6.3.1.2
		Author: WP Engine

	Akismet Anti-spam: Spam Protection
		Version: 5.3.3
		Author: Automattic - Anti-spam Team

	AnyWhere Elementor Pro (Premium)
		Version: 2.27
		Author: WP Vibes

	Elementor
		Version: 3.23.0
		Author: Elementor.com

	Elementor ACF Group Tag Extension
		Version: 0.1
		Author: Umair Ahmed

	Elementor Pro
		Version: 3.23.0
		Author: Elementor.com

	Extras for Elementor
		Version: 2.2.52
		Author: Namogo

	Image Map Pro v6
		Version: 6.0.20
		Author: Webcraft Plugins Ltd.

	JetTabs For Elementor
		Version: 2.1.14
		Author: Crocoblock

	Login Designer
		Version: 1.6.4
		Author: LoginDesigner

	Password Protected
		Version: 2.7.2
		Author: Password Protected

	SVG Support
		Version: 2.5.5
		Author: Benbodhi

	Temporary Login
		Version: 1.2.0
		Author: Elementor.com

	WordPress Importer
		Version: 0.8.2
		Author: wordpressdotorg

	Yoast Duplicate Post
		Version: 4.5
		Author: Enrico Battocchi & Team Yoast

	Yoast SEO
		Version: 23.0
		Author: Team Yoast


== Must-Use Plugins ==
	Kinsta Must-use Plugins
		Version: 3.1.1
		Author: Kinsta Team


== Features ==
	Custom Fonts: 1
	Custom Icons: 0

== Integrations ==
	


== Elementor Experiments ==
	Improved CSS Loading: Active
	Inline Font Icons: Active
	Additional Custom Breakpoints: Active
	Flexbox Container: Active
	Grid Container: Active
	Upgrade Swiper Library: Active
	Nested Elements Performance: Active by default
	Optimized Control Loading: Inactive
	Optimized Markup: Inactive by default
	Plugin Onboarding: Active by default
	Default to New Theme Builder: Active
	Header & Footer: Inactive
	Elementor Home Screen: Active by default
	Editor Top Bar: Inactive
	Build with AI: Inactive
	Landing Pages: Active
	Nested Elements: Active
	Lazy Load Background Images: Active
	Element Caching: Inactive
	Link In Bio: Inactive by default
	Floating Buttons: Inactive by default
	Elementor Editor Events: Inactive by default
	Display Conditions: Inactive
	Form Submissions: Active
	Menu: Inactive
	Taxonomy Filter: Active
	Search: Active


== Log ==
	
PHP: showing 8 of 8PHP: 2024-06-19 05:36:54 [notice X 13][../wp-content/plugins/elementor-extras/modules/display-conditions/conditions/shortcode.php::99] Optional parameter $name declared before required parameter $value is implicitly treated as a required parameter [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-06-19 05:56:14 [warning X 91][../wp-content/plugins/elementor/includes/base/controls-stack.php::695] Undefined array key -1 [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-06-19 10:33:30 [notice X 1][../wp-content/plugins/elementor-extras/modules/search/widgets/search-form.php::186] trim(): Passing null to parameter #1 ($string) of type string is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-06-26 03:41:22 [notice X 2][../wp-content/plugins/elementor-extras/modules/breadcrumbs/widgets/breadcrumbs.php::1215] Optional parameter $post declared before required parameter $query is implicitly treated as a required parameter [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-06-27 16:16:20 [warning X 2][../wp-content/plugins/elementor/includes/managers/image.php::113] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-06-28 05:34:05 [error X 2][../wp-content/plugins/elementor/includes/base/widget-base.php::198] Allowed memory size of 268435456 bytes exhausted (tried to allocate 20480 bytes) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-06-28 05:35:21 [error X 1][../wp-content/plugins/elementor/includes/base/controls-stack.php::2231] Allowed memory size of 268435456 bytes exhausted (tried to allocate 40960 bytes) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-07-15 03:47:17 [warning X 4][../wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php::150] Undefined array key "condition_type" [array (
  'trace' => '
#0: ../wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(150): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_template_json_item()
#2: ../wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(120): class type array_map()
#3: ../wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(59): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_templates_json()
#4: ../wp-content/plugins/elementor/data/base/endpoint.php(158): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> get_items()
',
)]

Log: showing 20 of 252024-07-01 04:14:13 [info] elementor::elementor_updater Started 
2024-07-01 04:14:13 [info] Elementor/Upgrades - _on_each_version Start  
2024-07-01 04:14:13 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.22.2',
  'to' => '3.22.3',
)]
2024-07-01 04:14:14 [info] Elementor/Upgrades - _on_each_version Finished 
2024-07-01 04:14:14 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.22.2',
  'to' => '3.22.3',
)]
2024-07-01 04:15:32 [info] elementor-pro::elementor_pro_updater Started 
2024-07-01 04:15:32 [info] Elementor Pro/Upgrades - _on_each_version Start  
2024-07-01 04:15:32 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2024-07-01 04:15:32 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.22.0',
  'to' => '3.22.1',
)]
2024-07-01 04:15:32 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.22.0',
  'to' => '3.22.1',
)]
2024-07-15 03:32:34 [info] elementor::elementor_updater Started 
2024-07-15 03:32:34 [info] Elementor/Upgrades - _on_each_version Start  
2024-07-15 03:32:34 [info] Elementor/Upgrades - _on_each_version Finished 
2024-07-15 03:32:34 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.22.3',
  'to' => '3.23.0',
)]
2024-07-15 03:32:34 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.22.3',
  'to' => '3.23.0',
)]
2024-07-15 03:33:31 [info] elementor-pro::elementor_pro_updater Started 
2024-07-15 03:33:31 [info] Elementor Pro/Upgrades - _on_each_version Start  
2024-07-15 03:33:31 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2024-07-15 03:33:31 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.22.1',
  'to' => '3.23.0',
)]
2024-07-15 03:33:31 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.22.1',
  'to' => '3.23.0',
)]

JS: showing 9 of 9JS: 2024-06-27 15:48:58 [error X 1][../wp-content/plugins/jet-tabs/assets/js/jet-tabs-frontend.min.js?ver=2.1.14:1:6413] t.ajax is not a function 
JS: 2024-06-27 16:18:15 [error X 1][../wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: "view237793") has already been destroyed and cannot be used. 
JS: 2024-06-27 23:18:41 [error X 1][../wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.22.2:3:825128] Cannot read properties of undefined (reading 'toLowerCase') 
JS: 2024-06-27 23:54:58 [error X 1][../wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: "view4919") has already been destroyed and cannot be used. 
JS: 2024-06-27 23:54:58 [error X 1][../wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: "view4956") has already been destroyed and cannot be used. 
JS: 2024-06-27 23:54:58 [error X 1][../wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: "view4993") has already been destroyed and cannot be used. 
JS: 2024-06-28 12:35:18 [error X 1][../wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.22.2:3:634940] Cannot read properties of undefined (reading 'isEditable') 
JS: 2024-07-01 16:49:47 [error X 3][../wp-content/plugins/elementor/assets/js/frontend-modules.min.js?ver=3.22.3:2:16898] Cannot read properties of undefined (reading 'attributes') 
JS: 2024-07-15 10:49:23 [error X 1][../wp-includes/js/jquery/jquery.min.js?ver=3.7.1:2:28760] Cannot read properties of undefined (reading 'value') 



== Elementor - Compatibility Tag ==
	
	AnyWhere Elementor Pro (Premium): Compatibility not specified
	Elementor ACF Group Tag Extension: Compatibility not specified
	Elementor Pro: Compatibility not specified
	Extras for Elementor: Compatibility not specified
	JetTabs For Elementor: Compatibility not specified

== Elementor Pro - Compatibility Tag ==
````

</details>

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by nicholaszein** [comment] 2024-07-15 15:13
Hello @pg-los! 

Thank you for submitting your issue! 🙏 

Please allow us some time to investigate it, and get back to you with our findings. 🧐 

Best regards

**Comment by nicholaszein** [comment] 2024-07-15 15:50
Hi @pg-los!

After testing on a website with just Elementor v3.23.0, and Elementor Pro v3.23.0, we could not reproduce your issue. I see you have a number of Elementor add-ons installed that may be conflicting with the latest version of Elementor.

As requested in the Bug Report form, to isolate the problem, on a staging site, try to deactivate all plugins, except Elementor and Elementor Pro, and see if the problem goes away. It's most likely one of your other plugins is causing the problem you're experiencing.

Here is a video of me testing both Anchor Links and Lightbox features:

https://github.com/user-attachments/assets/b4fcdd33-5096-45bb-8f72-6cd73a5e4340

As you can see, anchors are working fine, and images correctly open on a lightbox.

Please, troubleshoot your issue by isolating possible plugin conflicts, clear and purge all levels of cache, and let me know if after following these steps you can use those features again.

Kind regards

**Comment by pg-los** [comment] 2024-07-15 15:59
Hi @nicholaszein I have tried to deactivate plugins one by one and it seems that at least the lighbox functionality is restored after I deactivate AnyWhere Elementor Pro (Premium). I need that plugin, so I contacted their support and all I was told was that they couldn't replicate the error by deactivating that plugin. I am at a loss for solutions. please help!

**Comment by nicholaszein** [comment] 2024-07-15 16:17
Hi @pg-los,

I completely understand your frustration, however, we cannot provide support for 3rd-party addons. We publish a beta program that runs for at least 3 weeks, were 3rd-party developers have a chance to not only test their add-ons with the new version, but also report on conflicts and suggest solutions. We also send a newsletter to all developers, and reach out directly to those who have joined our Partnership program. We communicate and give time for everyone to make sure their plugins are compatible.

From your own System Info, see the Compatibility Tag section:

```
== Elementor - Compatibility Tag ==
	
	AnyWhere Elementor Pro (Premium): Compatibility not specified
	Elementor ACF Group Tag Extension: Compatibility not specified
	Elementor Pro: Compatibility not specified
	Extras for Elementor: Compatibility not specified
	JetTabs For Elementor: Compatibility not specified

== Elementor Pro - Compatibility Tag ==
```
None of the addons you use specify any compatibility with the versions of Elementor and Elementor Pro you have installed.

What I can suggest to you is to **Rollback Elementor and Elementor Pro to versions 3.22.3, and 3.22.1 (respectively)**, and wait for your Addons to release compatible versions. You can learn more about how to proceed with the Rollback in [this article](https://elementor.com/help/rolling-back-to-a-previous-version-of-elementor/).

That being said, I consider this is not a bug caused by Elementor, therefore I'm closing this issue.

❔ If you have questions, or need guidance, help, or general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) The main Facebook group where all kinds of users come together to help each other.
- [Elementor Academy](https://elementor.com/academy) Learn everything you need to know about using Elementor.
- [Elementor Developers Documentation](https://developers.elementor.com/) Learn everything about our Developer-API.
- [Free Support Forum](https://wordpress.org/support/plugin/elementor) Get help on WordPress.org.

💎 If you have an active [Elementor Pro](https://elementor.com/pro) license you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Kind regards

**Closed by nicholaszein** 2024-07-15 16:17 UTC
Labels: compatibility/3rd-party, status/needs-feedback, component/lightbox, component/code, compatibility/assets, document/assets, product/3.23
