### ISSUE TITLE
User Profile Language not considered by Elementor

### ISSUE THREAD

**Issue by MM-WPS** [elementor/elementor#5148] opened 2018-07-20 20:47 UTC
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

Website is set to default language "Catalan"
Administrator is set to "English UK"

All commands of Elementor appear in Catalan instead of English
WP admin interface remains in English as it should be

## Steps to reproduce

Same happens with any language, Elementor takes the website language instead of the user language

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: 10.1.31
	PHP Version: 5.6.36
	PHP Max Input Vars: 1000
	PHP Max Post Size: 32M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 4.9.7
	Site URL: https://3d-webservice.com
	Home URL: https://3d-webservice.com
	WP Multisite: No
	Max Upload Size: 32 MB
	Memory limit: 40M
	Permalink Structure: /%postname%/
	Language: en-GB
	Timezone: Europe/Madrid
	Debug Mode: Inactive

== Theme ==
	Name: OceanWP
	Version: 1.5.20
	Author: Nick
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: ca
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.1.2 Safari/605.1.15

== Active Plugins ==
	All-in-One WP Migration
		Version: 6.72
		Author: ServMask

	Block Bad Queries (BBQ)
		Version: 20180511
		Author: Jeff Starr

	Bookeo
		Version: 1.4
		Author: Bookeo

	Direct Mail Subscribe Form
		Version: 1.3.6
		Author: e3 Software

	Duplicate Page
		Version: 2.6
		Author: mndpsingh287

	Elementor
		Version: 2.1.4
		Author: Elementor.com

	Folders
		Version: 1.3.7
		Author: Steve North, Aaron Taylor (6-2 Design), Richard Green

	Google Analytics Dashboard for WP (GADWP)
		Version: 5.3.5
		Author: ExactMetrics

	Limit Login Attempts Reloaded
		Version: 2.7.1
		Author: wpchefgadget

	Ocean Demo Import
		Version: 1.0.9
		Author: OceanWP

	Ocean Extra
		Version: 1.4.18
		Author: OceanWP

	Polylang
		Version: 2.3.8
		Author: Frédéric Demarle

	SecuPress Free — WordPress Security
		Version: 1.4.5.1
		Author: SecuPress

	SF Move Login
		Version: 2.5.3
		Author: Grégory Viguier

	Sticky Menu (or Anything!) on Scroll
		Version: 2.1.1
		Author: Mark Senff

	Yoast SEO
		Version: 7.8
		Author: Team Yoast


== Must-Use Plugins ==
	SecuPress COOKIEHASH
		Version: 1.0
		Author: 

	SecuPress Salt Keys
		Version: 1.0.1
		Author: 


== Debug ==
	Errors: 
		TypeError: undefined is not an object (evaluating 'i.attributes')
			at https://3d-webservice.com/wp-content/plugins/elementor/assets/js/frontend.min.js?ver=2.1.3 - 2:7459
			2018-07-18 12:52 +00:00

		TypeError: undefined is not an object (evaluating 'n.ui.form.html')
			at https://3d-webservice.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.1.2 - 2:80016
			2018-07-09 18:17 +00:00
			x 2 times

		TypeError: undefined is not a function (near '...t.imagesLoaded...')
			at https://3d-webservice.com/wp-content/themes/oceanwp/assets/js/main.min.js?ver=1.5.18 - 1:120374
			2018-07-08 00:56 +00:00
			x 17 times

		TypeError: undefined is not an object (evaluating 'this._parent.errors')
			at https://3d-webservice.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.1.1 - 2:138432
			2018-07-07 18:50 +00:00
			x 2 times

				
</details>

**Comment by Jaska** [comment] 2018-10-04 08:44
A solution from a related issue https://github.com/pojome/elementor/issues/4686#issuecomment-412304458

    function bleye_unload_textdomain_elementor() {
    	unload_textdomain( 'elementor' );
    	unload_textdomain( 'elementor-pro' );
    }  // end function
    add_action( 'init', 'bleye_unload_textdomain_elementor', 100 );

I wished I've known about this 2 weeks ago 😂

**Comment by yasharhv** [comment] 2018-10-11 09:40
> A solution from a related issue [#4686 (comment)](https://github.com/pojome/elementor/issues/4686#issuecomment-412304458)
> 
> ```
> function bleye_unload_textdomain_elementor() {
> 	unload_textdomain( 'elementor' );
> 	unload_textdomain( 'elementor-pro' );
> }  // end function
> add_action( 'init', 'bleye_unload_textdomain_elementor', 100 );
> ```
> I wished I've known about this 2 weeks ago 😂

+1
I suggest using is_admin tag to keep translated texts of elements on front-end:
```
add_action( 'init', 'unload_textdomain_elementor', 100 );
function unload_textdomain_elementor() {
	if (is_admin()) {
		unload_textdomain( 'elementor' );
		unload_textdomain( 'elementor-pro' );
	}
}
```
But this is just a temporary and not a bug-free solution.
We want to see Elementor's default labels and  admin side texts in English but I personally prefer to see content of elements in the language in which front-end users will see them, while editing and designing the page.

**Comment by Applepiee** [comment] 2018-11-12 01:47
Hello,
Any update on this?

**Comment by black-eye** [comment] 2018-11-27 23:02
+1

**Comment by MarcusCaeruleus** [comment] 2018-12-11 03:43
+1 This is a nightmare of a problem and massively slowing down development of a multilanguage site I am working on. Please help!

**Comment by lirdis** [comment] 2019-01-08 15:50
+1 PLEASE !!

**Comment by Applepiee** [comment] 2019-01-18 09:17
Elementor team,
Please.

**Comment by servitiumpl** [comment] 2019-01-23 21:57
+1

**Comment by abclution** [comment] 2019-02-02 16:16
Yup, another +1 here. 

User setting options for Elementor language interface  needed. Thank you.

**Comment by m2sahin** [comment] 2019-02-07 09:04
+1

**Comment by pandusen** [comment] 2019-02-14 13:36
+1

**Comment by trouni** [comment] 2019-03-06 03:30
+1

**Comment by numanzahid** [comment] 2019-03-06 12:54
+1
elementor should respect user language in editor.

**Comment by galwpsite** [comment] 2019-03-11 01:06
+1 it just makes sense

**Comment by zeinnicholas** [comment] 2019-03-11 01:08
+1 https://github.com/elementor/elementor/issues/3623

**Comment by davideassis** [comment] 2019-03-11 01:24
+1 Or adopt the User Language or offer an option to Force English everywhere.

**Comment by touchestudio** [comment] 2019-03-11 13:18
Please fix. It's mind boggling. 😁

**Comment by KristianEp** [comment] 2019-03-23 14:12
Elementor sitebuilder UI should respect the WordPress user profile language setting for the menus, properties descriptions and options. Contents of the text boxes where user can type in, should stay original.

**Comment by Hauki75** [comment] 2019-03-26 15:57
+1

**Comment by johnreed** [comment] 2019-04-05 14:39
+1 any update on this issue?

**Comment by anderscarlen** [comment] 2019-04-12 10:36
+1

**Comment by stefanico** [comment] 2019-04-18 20:32
#majorpain ... same here
Some peeps have used this plugin from @deckerweb that unloads elementor text domain, but didn't work for me :(
https://toolbarextras.com/

...Please?

**Comment by deckerweb** [comment] 2019-04-18 20:41
> #majorpain ... same here
> Some peeps have used this plugin from @deckerweb that unloads elementor text domain, but didn't work for me :(
> https://toolbarextras.com/

I know a lot of users using my plugin successfully to date for just doing this.
But environements can be very different - and also settings and maybe other plugins/ filters are interfering...!

@stefanico Could you please give me feedback about your install so maybe I can make it work with my plugin?
What's your goal? -- You will have Elementor in English, right? -- Or in another language?
Questions:
- What language is set in WordPress general settings for you?
- What language is set in your user profile?
- And, are administrator role, or different role (if so, which one)?

Best would be to contact me on facebook, also "deckerweb" there - to not go too much beyond this ticket.

**Comment by fthiesen** [comment] 2019-05-16 18:26
Please fix this. It's a nightmare to have Elementor in a language you don't know. I don't understand what's taking so long, how hard is it to have this fixed? Simply respect the user language like ALL other wp plugins. Such a great product and such a huge language issue. :(

**Comment by fthiesen** [comment] 2019-05-16 18:32
> A solution from a related issue [#4686 (comment)](https://github.com/elementor/elementor/issues/4686#issuecomment-412304458)
> 
> ```
> function bleye_unload_textdomain_elementor() {
> 	unload_textdomain( 'elementor' );
> 	unload_textdomain( 'elementor-pro' );
> }  // end function
> add_action( 'init', 'bleye_unload_textdomain_elementor', 100 );
> ```
> 
> I wished I've known about this 2 weeks ago 😂

thanks so much for this!! life savior

**Comment by MM-WPS** [comment] 2019-05-16 18:59
I raised the issue again at Elementor 
This is their respons:

This is more of a WordPress/Polylang issue than Elementor.

Elementor obeys the language configuration of WordPress, however, as Polylang interfers in this setting, there may happen this kind of issues.

In order to maintain the backend language only in english, you'd need to enforce this with a third-party plugin or a custom code solution (if there may exist one).

At the moment we do not recommend nor provide support for third-party software (plugins/themes) nor custom code, as this goes out of our support scope.



Manuel


Le 16 mai 2019 à 20:26, fthiesen <notifications@github.com> a écrit :

Please fix this. It's a nightmare to have Elementor in a language you don't know. I don't understand what's taking so long, how hard is it to have this fixed? Simply respect the user language like ALL other wp plugins. Such a great product and such a huge language issue. :(

**Comment by fthiesen** [comment] 2019-05-16 19:02
> I raised the issue again at Elementor This is their respons: This is more of a WordPress/Polylang issue than Elementor. Elementor obeys the language configuration of WordPress, however, as Polylang interfers in this setting, there may happen this kind of issues. In order to maintain the backend language only in english, you'd need to enforce this with a third-party plugin or a custom code solution (if there may exist one). At the moment we do not recommend nor provide support for third-party software (plugins/themes) nor custom code, as this goes out of our support scope. Manuel Le 16 mai 2019 à 20:26, fthiesen <notifications@github.com> a écrit : Please fix this. It's a nightmare to have Elementor in a language you don't know. I don't understand what's taking so long, how hard is it to have this fixed? Simply respect the user language like ALL other wp plugins. Such a great product and such a huge language issue. :( — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

I don't know what exactly is your issue, but the issue in the thread has nothing to do with Polylang. I don't use Polylang and my Elementor still shows in the Site Language instead of the User Language.

**Comment by MM-WPS** [comment] 2019-05-16 19:03
Thanks for that !

Where to insert this code ?
Sorry for stupid question but I do not code :(

Manuel 

Le 16 mai 2019 à 20:32, fthiesen <notifications@github.com> a écrit :

A solution from a related issue #4686 (comment)

function bleye_unload_textdomain_elementor() {
	unload_textdomain( 'elementor' );
	unload_textdomain( 'elementor-pro' );
}  // end function
add_action( 'init', 'bleye_unload_textdomain_elementor', 100 );
I wished I've known about this 2 weeks ago 😂

thanks so much for this!! life savior

**Comment by fthiesen** [comment] 2019-05-16 19:24
> Thanks for that ! Where to insert this code ? Sorry for stupid question but I do not code :( Manuel Le 16 mai 2019 à 20:32, fthiesen <notifications@github.com> a écrit : A solution from a related issue #4686 (comment) function bleye_unload_textdomain_elementor() { unload_textdomain( 'elementor' ); unload_textdomain( 'elementor-pro' ); } // end function add_action( 'init', 'bleye_unload_textdomain_elementor', 100 ); I wished I've known about this 2 weeks ago 😂 thanks so much for this!! life savior — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

Hi I used a plugin called Code Snippets.

**Comment by matteo-greco** [comment] 2019-05-17 08:33
Hi! In case you have to support multiple languages and you want to reset Elementor's language only for users using the en_US locale, I took a spin at the solution contributed by @yaaashaaar 

```php
function mg_unload_textdomain_elementor() {
	if ( is_admin() ) {
		$user_locale = get_user_meta( get_current_user_id(), 'locale', true );
		if ( 'en_US' === $user_locale ) {
			unload_textdomain( 'elementor' );
			unload_textdomain( 'elementor-pro' );
		}
	}
}
add_action( 'init', 'mg_unload_textdomain_elementor', 100 );
```

HTH

**Comment by dwph** [comment] 2019-07-23 18:55
> I raised the issue again at Elementor This is their respons: This is more of a WordPress/Polylang issue than Elementor.

Of course it's an Elementor issue and not WordPress. Other theme builders like Divi respect the user language. WordPress implemented that function for a reason. It's Elementor who decided to implement this extremely user unfriendly enforcment to use the site language for ALL users with different languages.

Please this is 2019 not 2009. I am paying for Elementor Pro, so Elementor, please this problem. Yes it's a problem.

**Comment by madbradj** [comment] 2019-08-15 06:15
By the way, there is plugin by @deckerweb , called Toolbar Extras, ITS A LIFESAVER for this problem. It only runs on the backend and does not affect the front end. You can disable the translation of the backend using Toolbar Extras. This also disabled Elementor's translation, so you can work in your default language.

**Comment by ElectricFeet** [comment] 2019-08-15 16:51
This is not an issue with Polylang, or WPML, or any other plugin (nor with WordPress itself), it's squarely an Elementor bug (it happens with _only_ Elementor active).

- It renders Elementor pretty much unusable on multilingual sites that have users with different mother-tongues.
- It doesn't respect the design of WordPress.

Specifically, to get the user-interface language, Elementor queries the site's locale rather than the user's locale. This is simply a mistake.

Why is this so hard to change? The code simply needs to query the user's locale, not the site's locale. I don't get why this is not a quick fix. It certainly shouldn't take a year. It's a low impact change, too: For users _without_ multilingual sites (where sitelang=userlang), they will see no difference at all once a fix is implemented. For users _with_ multilingual sites (where sitelang!=userlang), it's a lifesaver.  

It's a bug, pure and simple. Not a design choice, not an opinion, not a request/enhancement. It's a bug that needs fixing.

In a world where sites are increasingly in more than one language, I can't see why Elementor is dragging its feet for so long on fixing this.

( More detail on why WordPress introduced user locales in WP 4.7 [here](https://make.wordpress.org/core/2016/11/07/user-admin-languages-and-locale-switching-in-4-7/) and [here](https://wptavern.com/wordpress-4-7-to-introduce-user-specific-language-setting-for-the-admin).)

**Comment by MarcusCaeruleus** [comment] 2019-08-16 07:36
@ElectricFeet Yes, Yes, Yes!! +1 !!!!

**Comment by ucheng** [comment] 2019-09-10 09:04
This issue was raised one year ago, but is still unfixed...

**Comment by numanzahid** [comment] 2019-09-10 19:26
Please we need this please.

**Comment by fthiesen** [comment] 2019-09-10 19:47
Yep, it's unbelievable how they are ignoring this issue for so long.

**Comment by dasigna** [comment] 2019-09-23 15:08
just my 2cents on this:

would be an **really** good idea to have this for elementor!
the problem i am actually facing is: the translations sometimes are that poor (or even wrong) that youre completely mislead for funtions or options.
so i tried to change the language to get behind some things... with the disadvantage that the frontend always is in the wrong language - which is completely disturbing.

yes - one could dig into the translations and change (or complete) them, but this is time consuming and cant be done quick to get it right :/
did this already and will do it again. but thats not done in a few minutes and sadly even if you change some strings for better understanding sometimes someone changes it back for renewal of confusion which is frustrating ...

so easily changing the language for the editor would be a great help for quick resolving things.
AND:
theres the possibility that sometimes theres a native speaker of another language for whom it might be better to use his set editor laguage too ...

**Comment by zimmiel** [comment] 2019-09-26 18:48
+1

**Comment by MichaelDarko** [comment] 2019-10-15 04:00
How Elementor handles languages is crazy and causes so many problems for so many users. 

- Translation fo my language is complete garbage. One third is translated confusingly, 1 third is translated wrongly and 1 third is not translated at all. (Absolute nightmare to use.)

- Elementor doesn't allow you to switch to the default English interface.

- Changing user's locale to English should solve this, but doesn't.

Imagine buying professional software and being forced to use interface where nothing makes sense.

Some translations are really bad and can't be used, some people just prefer to use English interface, some teams are multi-lingual. MANY people need Elementor to respect their user locale for many reasons.

This is not a feature request, this is an absolute necessity that should be there form the beginning! This problem shouldn't exist after 3 years of developement and more than a year since it has been raised.

Elementor is paid product and after 3 years of paying for the Expert license i'm still forced to use interface that's barely usable.

Whatever fancy feature you're working on right know, is not more important that this fundamental problem.

**Comment by stefanico** [comment] 2019-10-15 06:14
@MichaelDarko ... well put ... but after all this time I think the Elementor team seems to be more motivated by fancy swooshy (often overdone) effects. The Interface and concept is very clever but the Multilingual community doesn't seem to weight over the flashy content.
Ticket open ...Jul 20, 2018 .... no one assigned ... sigh

**Comment by dwph** [comment] 2019-10-15 08:47
Submit a tickets. Shout this on social media. Rewview the product.

Elementor has to listen at some pont,

**Comment by anderscarlen** [comment] 2019-10-15 08:56
Agreed.

**Comment by PPjev** [comment] 2019-10-26 20:39
+1 this is will be helpful

**Comment by dwph** [comment] 2019-11-14 10:30
Elementor is not even responding to this problem. I thought this was the place to report problems.

**Comment by princesshorsepower** [comment] 2019-12-11 00:57
The workaround is ok. But this should be fixed in Elementor.
**The Elementor Backend should speak the Users language.** :vulcan_salute:

**Comment by fafchook** [comment] 2020-01-16 11:00
+1

**Comment by busymick** [comment] 2020-02-13 16:09
+1

**Comment by webschmitt** [comment] 2020-02-28 17:15
I was translating a German website to Arabic, that was sheer horror, Elementor was shown the complete UI in Arabic and so it was unusable for me.

For German Developers or from other countries I made a tiny work around using the script above, thanks for this. Replace 'de_DE' with your country code and Elementor will be shown in your language by editing native pages or in English only (Elementors native language) by editing (translate) other languages. I think, English is ok for the most of us. For me it works.

add_action( 'init', 'ws_unload_textdomain_elementor', 100 );
function ws_unload_textdomain_elementor() {
	if ( is_admin() ) {
		if ( 'de_DE' !== get_locale()) {
			unload_textdomain( 'elementor' );
			unload_textdomain( 'elementor-pro' );
		}
	}
}

I think it's very important that a user can operate a user interface in their native language, that's definitely the admin language. Hopefully Elementor will fix that soon.

**Comment by crazypsycho** [comment] 2020-03-25 10:55
I think the problem is, that elementor overrides the user_locale. So it also effects other plugins showing in the elementor-editor (like extra-toolbars).
I fixed it with this snippet:
```php
        add_action( 'set_current_user', function() {
            global $current_user;
            $userLocale = get_user_meta( get_current_user_id(), 'locale', true );
            $current_user->locale = $userLocale;
        }, 11 );
```

The issue comes from plugins/elementor/includes/compatibility.php (Line 270-275)
Seems it should fix some problems with polylang. But this method is also called if no polylang is installed.

**Comment by marcusssss** [comment] 2020-04-29 12:06
+1 please fix it

**Comment by erfan-ilyas** [comment] 2020-06-12 10:34
Please fix this bug.

**Comment by dogstar10** [comment] 2020-06-14 11:57
Please fix

**Comment by jchwenger** [comment] 2020-06-19 14:01
Yes please.

**Comment by srpotman72** [comment] 2020-06-21 10:09
Was also registered in https://github.com/elementor/elementor/issues/9356
**What problem is your feature request going to solve?
WordPress is showing it's menu in the language as per following:

(WP Dashboard - Settings - General - ) Site language
(WP Dashboard - right up in screen hover over user-id - Edit my profile - ) Language
The second is dominant.
Elementor is showing its menu (and Widget names) in the "Site language". This way we get to administer the site in 2 languages, one we don't master (the "Site language" is for the visitors of the site).

Describe the solution you'd like
Request to follow the same logic as WordPress, so Elementor is showing their options also based on 1) the Site language but if different 2) Language (in the user profile), with the second dominant

**Describe alternatives you've considered
Learning each language my customers want to target :-)**

Additional context
Thanks! I hope this is easy to implement. A happy PRO-user

**Comment by erfan-ilyas** [comment] 2020-06-21 10:49
> I think the problem is, that elementor overrides the user_locale. So it also effects other plugins showing in the elementor-editor (like extra-toolbars).
> I fixed it with this snippet:
> 
> ```
>         add_action( 'set_current_user', function() {
>             global $current_user;
>             $userLocale = get_user_meta( get_current_user_id(), 'locale', true );
>             $current_user->locale = $userLocale;
>         }, 11 );
> ```
> 
> The issue comes from plugins/elementor/includes/compatibility.php (Line 270-275)
> Seems it should fix some problems with polylang. But this method is also called if no polylang is installed.

I have tried all the solutions, I am not using any translation plugin like WPML or Polylan.

This is only solution that worked for me thanks to @crazypsycho 

Add this code to your functions.php or mu-plugins

```PHP
add_action( 'set_current_user', function() {
	global $current_user;
	$userLocale = get_user_meta( get_current_user_id(), 'locale', true );
	$current_user->locale = $userLocale;
}, 11 );
`

Note that I have increased the order priority to 11 as 10th order is Elementors default.

**Comment by dannygrio** [comment] 2020-09-26 02:47
I guess elementor is not going to look at this! I really would like a solution. I normally change the website language to English so I can use elementor in English, however this is a workaround. I always have to mov the website back to its original language since elementor won't respect user language.

**Comment by wwdes** [comment] 2020-11-03 08:09
Please fix this.

**Comment by busymick** [comment] 2020-11-05 09:38
Elementor support please fix this! Elementor should respect user language instead of site language..

**Comment by daniilicic** [comment] 2020-11-28 09:06
+1

**Comment by ancient2** [comment] 2020-12-14 12:48
an easy workaround to always work elementor in english
use toolbarextras plugin and check the checkbox **to unload any translations for Elementor and Elementor Pro**
https://toolbarextras.com/docs/unload-elementor-translations/

**Comment by dsecareanu** [comment] 2021-01-06 10:32
+1 - I'm having the same issues building websites in various languages and being unable to work in Elementor in English, often times when switching the admin language to check content in a certain language I have to guess Elementor elements to be able to navigate through the interface. Please fix this. Thanks!

**Comment by AmirHosseinKarimi** [comment] 2021-02-03 11:56
Looks like its fundamental problem, After 3 years they did not answered!
So this mean they do not want or can not fix this problem!

**Comment by ElectricFeet** [comment] 2021-02-03 13:01
> Looks like its fundamental problem, After 3 years they did not answered!
> So this mean they do not want or can not fix this problem!

@AmirHosseinKarimi That’s what’s really irritating about this bug; it should be pretty easy to fix — just use the user’s locale, not the WordPress locale. 

I stopped using Elementor as a direct consequence of their unwillingness to fix this bug. Gutenberg (in the WordPress core) has improved a lot in the last few years and I see no need to be dependent on Elementor. 

I might have stayed, if they had explained _why_ they weren’t fixing it, but just ignoring it like this is not helpful.

**Comment by numanzahid** [comment] 2021-02-05 14:52
Their ignorance forcing me to switch to some alternate page builder.
@ElectricFeet 
Can you please share some learning resources for Gutenberg to use it at its full potential, and make beautiful designs.

**Comment by dasigna** [comment] 2021-02-05 18:31
another tiny litte thing with big annoyance...

**Comment by bitfur** [comment] 2021-02-13 21:09
Wish I knew this stuff before buying pro...

**Comment by dogstar10** [comment] 2021-02-14 07:41
i found a really good solution.... 
uninstalled Elementor and moved to Oxygen Builder...
problem solved :)

**Comment by numanzahid** [comment] 2021-02-14 10:30
> i found a really good solution....
> uninstalled Elementor and moved to Oxygen Builder...
> problem solved :)

+1 for Oxygen Builder. Complete control over the output and very good page speed.

**Comment by mariusz-ah** [comment] 2021-02-15 11:45
> Looks like its fundamental problem, After 3 years they did not answered!
> So this mean they do not want or can not fix this problem!

I won't expect them to change anything in that matter

**Comment by PPjev** [comment] 2021-03-05 08:26
You can remove PO translations specifically for elementor front end, and it will show you in english. Works for me.

**Comment by srpotman72** [comment] 2021-03-05 12:35
> You can remove PO translations specifically for elementor front end, and it will show you in english. Works for me.

Do you have some instructions on how we can do this? Where and what exactly to remove?
Thanks!

**Comment by PPjev** [comment] 2021-03-05 12:42
wp-content>languages>plugins  there you will see something like elementor-pro-EE... just remove all translations related to elementor and elementor-pro.

**Comment by srpotman72** [comment] 2021-03-05 13:39
I tried it but it doesn't work.
I removed all elementorXXXX.po files. When I go to WP Dashboard - Pages - Edit with Elementor - the widgets are still in: (WP Dashboard - Settings - General - ) Site language.
If it would work, it would need to be tested if updates of Elementor doesn't add the elementorXXXX.po files. Else it's not a sustainable solution.

**Comment by Ruzgfpegk** [comment] 2021-03-06 05:10
.po files are "work files" for translators.
It's the .mo files (compiled .po files) that are used by PHP/WordPress and that should be deleted.

Updates would recreate all of those files each time.

**Comment by iker87** [comment] 2021-06-05 13:46
When will we get an official solution?

**Comment by gina0868** [comment] 2021-06-17 09:40
Very frustrating!!! Please fix this...

**Comment by eminozturk58** [comment] 2021-08-30 12:14
+1 ....

It's 2021. Elementor please find a solution to this problem now.

**Comment by marowi85** [comment] 2021-09-09 13:07
+1

Three years later and still an issue...

**Comment by daniilicic** [comment] 2021-09-23 07:03
C'mon guys, it's been three years. 

Instead of working on new, shiny, fancy features no professional user needs, try fixing the core issues.

**Comment by trofimartya** [comment] 2021-10-13 08:54
+1

**Comment by Mjasotrboob** [comment] 2021-10-16 21:23
> 
> 
> C'mon guys, it's been three years.
> 
> Instead of working on new, shiny, fancy features no professional user needs, try fixing the core issues.

So true bro, literally made it impossible...

**Comment by lelas** [comment] 2021-12-08 14:51
This sort of ignorance from Elementor is also why we won't renew our agency license (after 4 years).

Incredible that the team doesn't get that developers and designers can work with clients with websites in languages said developers and designers don't speak/read (well enough)...

Have you heard about this rare phenomenon called "remote work", @shilo-ey? It's quite revolutionary. Companies can hire freelancers and companies residing in OTHER countries than their own! Shocker, eh?

**Comment by dannygrio** [comment] 2021-12-08 17:21
This is from 2018 and elementor not even replied here to say why or why not. Nothing!!

**Comment by Vossha** [comment] 2022-03-09 22:59
> I merged this issue with #5148, which is on the same subject so we could deal with it more efficiently. Please feel free to continue the conversation there.
> 
> **We are working on introducing this feature**. please follow the original thread for further updates.
> 
> Thanks for your feedback!
See: https://github.com/elementor/elementor/issues/17732#issuecomment-1032843640

@shilo-ey I hope it's oke to quote your answer from another thread in this thread so people know Elementor is working on it 🥳🥳

**Comment by Vossha** [comment] 2022-03-09 23:16
In case this is informative, my use case in why I would love Elementor to change language based on user account selected language:

I'm working on a website where we work with 3 different languages.

- The website itself is in French and English
- The business is located in France and thus the site language is French (<html lang="fr-FR">).
- Communication between clients and me is in Dutch.
- Both of my clients have different language preferences. One prefers NL, one prefers FR (I prefer English).

I wanted to setup our user accounts today, got confused and ended up in this thread (:

**Comment by raduberar** [comment] 2022-04-01 16:04
+1!
The site needs to be in a local language for SEO.
But for people that learned to use Elementor in english, I can confirm that it not a good experience.

**Comment by daniilicic** [comment] 2022-04-22 04:29
2022, four years after the issue has been brought up, 90 comments, a lot of agitated users - and what do we get from support - nada. Not a single response from the team.

Time to really think about changing our toolset.

**Comment by v3ctordesign** [comment] 2022-05-30 18:59
About a year ago I came across this problem, i was wondering if it still is... Cmon elementor, not to be toxic but shame on you. Can't wait to migrate from Elemenotr Pro to Oxygen.

**Comment by lllopo** [comment] 2022-06-01 07:29
+1

**Comment by black-eye** [comment] 2022-06-15 12:11
Oh my, schedulled for 3.7.0? I hope so.

And @shilo-ey, when you'll be working on it, please consider adding an option to have Elementor in English regardless the profile or web language. I find the Elementor translation rather terrible, I would even say usesless (e.g. meaningless translations for CSS terms). My language is Czech, but from the other comments here on GitHub I would guess, it's not the only problematic translation.

Thanks

**Comment by gilad905** [comment] 2022-06-16 10:53
> > A solution from a related issue [#4686 (comment)](https://github.com/pojome/elementor/issues/4686#issuecomment-412304458)
> > ```
> > function bleye_unload_textdomain_elementor() {
> > 	unload_textdomain( 'elementor' );
> > 	unload_textdomain( 'elementor-pro' );
> > }  // end function
> > add_action( 'init', 'bleye_unload_textdomain_elementor', 100 );
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I wished I've known about this 2 weeks ago 😂
> 
> +1 I suggest using is_admin tag to keep translated texts of elements on front-end:
> 
> ```
> add_action( 'init', 'unload_textdomain_elementor', 100 );
> function unload_textdomain_elementor() {
> 	if (is_admin()) {
> 		unload_textdomain( 'elementor' );
> 		unload_textdomain( 'elementor-pro' );
> 	}
> }
> ```
> 
> But this is just a temporary and not a bug-free solution. We want to see Elementor's default labels and admin side texts in English but I personally prefer to see content of elements in the language in which front-end users will see them, while editing and designing the page.

This works great but for some reason it only changes language for the UI panel content, not the panel header (where it says e.g "Edit Section").
Any ideas for a solution for the header as well?
Thanks

**Comment by lllopo** [comment] 2022-06-16 10:55
@gilad905 [here](https://github.com/elementor/elementor/issues/5148#issuecomment-1143216409)

**Comment by shilo-ey** [comment] 2022-08-08 08:27
This feature has been implemented in Elementor v3.7.0

Feel free to update

Thanks!

**Closed by shilo-ey** 2022-08-08 08:27 UTC
Labels: request/enhancement, type/internationalization

**Comment by srpotman72** [comment] 2022-08-08 15:08
oh so good to give some pointers on how the solution looks like... Where can we go in the menu?

**Comment by draganche77** [comment] 2022-08-09 12:02
And where we can change Elementor language?

Thanks

**Comment by PPjev** [comment] 2022-08-09 12:15
You just change it in user settings. Language field.
<img width="526" alt="Screenshot 2022-08-09 at 15 14 55" src="https://user-images.githubusercontent.com/1798276/183644493-3880d4fc-211b-49d7-b774-f159a3c0341a.png">

**Comment by draganche77** [comment] 2022-08-11 16:45
Yes I now that, but it is a language of Wordpress. My clients want WP in their language and I want Elementor on English. Isn't that the point of this one feature?

**Comment by PPjev** [comment] 2022-08-11 16:56
The thing I am referring, is language of admin panel, not pages language. It is unique to each user.

**Comment by shayr1** [comment] 2023-09-19 10:37
This is still a problem in v3.16.3. It also seems that the problem is related to Elementor and not Elementor Pro. Even on plugin page, the name of the plugin uses the translation of the site language, but if the plugin is deactivated, the name reverts to English (As in, user language.).
For reference, my site is Hebrew and I much prefer Elementor menus to be in English. It seems that menus relating to Elementor Pro _are_ in English, but menus relating to Elementor Core are in Hebrew, like the website language.
