### ISSUE TITLE
HOWTO and FAQ schema Widgets

### ISSUE THREAD

**Issue by pgsekula** [elementor/elementor#12735] opened 2020-10-03 18:23 UTC
hi,

Is there a chance you will make HOWTO and FAQ schema Widgets?
So there is no need to install and pay for any external plugins.
This will help a lot with Google Search.

Thank you for your information
Shamack 

## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by CodeBradley** [comment] 2020-10-03 22:35
This is actually something I was attempting to do yesterday and don't mind sharing the code, but when I upload this code as a plugin the Javascript breaks. As soon as I determine the cause and resolve it ill share the plugin files.

https://github.com/elementor/elementor/issues/12732

**Comment by DorShahar** [comment] 2020-12-24 15:53
Merged issue

I merged this issue with  #9237, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.
Thanks for your feedback!

**Closed by DorShahar** 2020-12-24 15:53 UTC
