### ISSUE TITLE
🔗 🚀 Feature Request: Google Map multiple pins (Duplicate of #1319)

### ISSUE THREAD

**Issue by AurelienWebnation** [elementor/elementor#9251] opened 2019-10-04 06:45 UTC
Add multiple pins on the google map plugin, if we need to enter multiple addresses.

**Comment by sunawang** [comment] 2020-01-29 08:57
The native Google Maps widget of Elementor doesn't support multiple pins. You can use [Essential Addons](https://www.wppagebuilders.com/essential-addons-review/) if you need to create a map with multiple pins

**Comment by d19dotca** [comment] 2021-06-28 03:52
Yes, this would be great! Bricks builder does this very well actually too, hopefully Elementor can take note of that.

**Comment by 79ho3ein** [comment] 2021-07-11 22:38
+1

**Comment by MichaelDarko** [comment] 2022-03-03 14:00
Current widget is too limiting. We need to add multiple locations quite often. Adding this feature would not be that hard and it would make the widget way more powerful.

**Comment by nicholaszein** [comment] 2022-11-27 07:03
Hello! 🙂 

Thank you for your submission! 🙏 

### 🔗 This issue is a Duplicate of #1319.

Which is on the same subject. 

For this reason, I'm closing this issue and 🔃 **Merging** it with the original, so we can have all the discussions in one location, and deal with it more efficiently.

Feel free to continue the conversation there. 😉

**Closed by nicholaszein** 2022-11-27 07:03 UTC
Labels: request/enhancement, component/maps
