### ISSUE TITLE
🔗 🐞 Bug Report: Can't Edit Facelift Publish Settings (Duplicate of #21862)

### ISSUE THREAD

**Issue by nickdgreen** [elementor/elementor#21942] opened 2023-04-05 11:42 UTC
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

When creating a popup on completion of the design clicking on "Publish" causes the Publish Settings Window to open allowing the setting of Conditions, Triggers, and Advanced Rules. Once the popup has been published if it is opened and the content changed, for example, the "publish button" becomes active but when clicked the popup is just updated and no opportunity is given to edit the publish settings. The only workaround I have found is to use the gear wheel icon for popup settings and under 'general settings' change the status to draft. This activates the publish button and when clicked the publish setting window is displayed.

From comments on facebook this is being experienced by other users.

### Steps to reproduce

1) Create a new popup
2) Publish it and configure the Publish Settings (Conditions, Triggers, and Advanced Rules)
3) Exit the popup to the menu
4) Select the popup "Edit with Elementor"
5) There appears to be no control on the screen that I can find that allows you to directly edit the "publish settings" 
6)  Edit content and click on publish (publish settings window not displayed)

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

<details>
<summary>System Info</summary>

````txt


					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Percona Server (GPL), Release 23, Revision 500fcf5 v5.7.23-23
	PHP Version: 8.1.17
	PHP Memory Limit: 512M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 516M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.2
	Site URL: https://elementary.websitesdesigned4u.com
	Home URL: https://elementary.websitesdesigned4u.com
	WP Multisite: No
	Max Upload Size: 512 MB
	Memory limit: 768M
	Max Memory limit: 512M
	Permalink Structure: /%postname%/
	Language: en-GB
	Timezone: Europe/London
	Admin Email: [REDACTED]
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor Child
	Version: 2.3.0.1607241787
	Author: Elementor Team
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.7.1
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: en_GB
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36

== Active Plugins ==
	Code Snippets
		Version: 3.3.0
		Author: Code Snippets Pro

	Complianz | GDPR/CCPA Cookie Consent
		Version: 6.4.3
		Author: Really Simple Plugins

	Elementor
		Version: 3.12.1
		Author: Elementor.com

	Elementor Pro
		Version: 3.12.1
		Author: Elementor.com

	iThemes Security
		Version: 8.1.5
		Author: iThemes

	ManageWP - Worker
		Version: 4.9.17
		Author: GoDaddy

	PhastPress
		Version: 2.12
		Author: Albert Peschar

	Pods - Custom Content Types and Fields
		Version: 2.9.13
		Author: Pods Framework Team

	Rank Math SEO
		Version: 1.0.110.2
		Author: Rank Math

	Rank Math SEO PRO
		Version: 3.0.32.1
		Author: Rank Math

	Really Simple SSL
		Version: 6.2.3
		Author: Really Simple Plugins

	UpdraftPlus - Backup/Restore
		Version: 1.23.3
		Author: UpdraftPlus.Com, DavidAnderson

	WhatsApp Chat by NinjaTeam
		Version: 3.3.1
		Author: NinjaTeam

	WP Meteor
		Version: 3.1.9
		Author: Aleksandr Guidrevitch


== Must-Use Plugins ==
	Endurance Page Cache
		Version: 2.2
		Author: Mike Hansen

	ManageWP - Worker Loader
		Version: 1.0.0
		Author: GoDaddy


== Elements Usage ==
	
	archive : 2
		container : 1
		loop-grid : 1
	container : 3
		button : 1
		container : 6
		heading : 1
		html : 2
		icon-box : 1
		image : 2
		text-editor : 2
	footer : 2
		text-editor : 1
	header : 1
		image : 1
		nav-menu : 1
	page : 3
		container : 16
		heading : 4
		image-box : 4
		text-editor : 5
	popup : 2
		button : 1
		container : 2
		heading : 2
		icon : 1
		image : 1
		shortcode : 1
		text-editor : 1
	section : 2
		button : 5
		call-to-action : 3
		html : 1
	widget : 0
		icon : 1
	wp-post : 2
		text-editor : 1
		wp-widget-pods_widget_field : 1
	wp-page : 6
		button : 8
		container : 12
		countdown : 1
		form : 1
		heading : 3
		image : 1
		image-box : 1
		image-carousel : 1
		shortcode : 2
		social-icons : 1
		text-editor : 2
	loop-item : 2
		call-to-action : 1
		container : 2
		heading : 2
		post-info : 1
		theme-post-excerpt : 1
		theme-post-featured-image : 1
		theme-post-title : 2
		wp-widget-pods_widget_field : 1


== Settings ==
	
	cpt_support: post, page
	allow_tracking: yes
	unfiltered_files_upload: 1
	load_fa4_shim: yes


== Features ==
	Custom Fonts: 1
	Custom Icons: 0

== Integrations ==
	


== Elementor Experiments ==
	Optimised DOM Output: Active
	Improved asset loading: Active
	Improved CSS Loading: Active
	Inline Font Icons: Active
	Accessibility improvements: Active
	Additional Custom Breakpoints: Active
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active
	Upgrade Swiper Library: Active
	Default to New Theme Builder: Active by default
	Hello Theme Header & Footer: Inactive by default
	Editor Top Bar: Active
	Landing pages: Active by default
	Nested Elements: Active
	Lazy Load Background Images: Inactive by default
	Page Transitions: Active by default
	Notes: Active by default
	Loop: Active
	Form Submissions: Active by default
	Scroll Snap: Active by default
	Menu: Active


== Log ==
	
Log: showing 20 of 372023-03-27 16:09:02 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.12.0-beta2',
  'to' => '3.12.0-beta3',
)]
2023-03-29 10:53:47 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.12.0-beta3',
  'to' => '3.12.0',
)]
2023-03-29 11:06:53 [info] elementor::elementor_updater Started 
2023-03-29 11:06:53 [info] Elementor/Upgrades - _on_each_version Start  
2023-03-29 11:06:54 [info] Elementor/Upgrades - _on_each_version Finished 
2023-03-29 11:06:54 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.12.0-beta3',
  'to' => '3.12.0',
)]
2023-03-29 11:09:28 [info] elementor-pro::elementor_pro_updater Started 
2023-03-29 11:09:28 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-03-29 11:09:28 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-03-29 11:09:28 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.12.0-beta3',
  'to' => '3.12.0',
)]
2023-03-29 11:09:29 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.12.0-beta3',
  'to' => '3.12.0',
)]
2023-04-03 16:43:47 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.12.0',
  'to' => '3.12.1',
)]
2023-04-03 16:44:20 [info] elementor::elementor_updater Started 
2023-04-03 16:44:20 [info] Elementor/Upgrades - _on_each_version Start  
2023-04-03 16:44:20 [info] Elementor/Upgrades - _on_each_version Finished 
2023-04-03 16:44:20 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.12.0',
  'to' => '3.12.1',
)]
2023-04-04 17:49:24 [info] elementor-pro::elementor_pro_updater Started 
2023-04-04 17:49:24 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-04-04 17:49:24 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-04-04 17:49:24 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.12.0',
  'to' => '3.12.1',
)]

PHP: showing 5 of 5PHP: 2023-03-27 21:13:34 [notice X 6][/home2/website1/public_html/elementary/wp-content/plugins/elementor-pro/modules/loop-builder/module.php::204] strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /home2/website1/public_html/elementary/wp-content/plugins/elementor-pro/modules/loop-builder/module.php(204): class type strpos()
#2: /home2/website1/public_html/elementary/wp-content/plugins/elementor-pro/modules/loop-builder/module.php(216): ElementorPro\Modules\LoopBuilder\Module -> is_editing_existing_loop_item()
#3: /home2/website1/public_html/elementary/wp-content/plugins/elementor-pro/modules/loop-builder/module.php(60): ElementorPro\Modules\LoopBuilder\Module -> is_loop_theme_builder()
#4: /home2/website1/public_html/elementary/wp-content/plugins/elementor-pro/modules/loop-builder/documents/loop.php(406): ElementorPro\Modules\LoopBuilder\Module -> __construct()
',
)]
PHP: 2023-03-27 21:13:34 [notice X 6][/home2/website1/public_html/elementary/wp-content/plugins/elementor-pro/modules/loop-builder/module.php::204] strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /home2/website1/public_html/elementary/wp-content/plugins/elementor-pro/modules/loop-builder/module.php(204): class type strpos()
#2: /home2/website1/public_html/elementary/wp-content/plugins/elementor-pro/modules/loop-builder/module.php(216): ElementorPro\Modules\LoopBuilder\Module -> is_editing_existing_loop_item()
#3: /home2/website1/public_html/elementary/wp-content/plugins/elementor-pro/modules/loop-builder/module.php(60): ElementorPro\Modules\LoopBuilder\Module -> is_loop_theme_builder()
#4: /home2/website1/public_html/elementary/wp-content/plugins/elementor-pro/modules/loop-builder/documents/loop.php(328): ElementorPro\Modules\LoopBuilder\Module -> __construct()
',
)]
PHP: 2023-04-04 17:49:25 [notice X 253][/home2/website1/public_html/elementary/wp-content/plugins/elementor-pro/modules/loop-builder/module.php::204] strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-04-05 12:16:01 [warning X 1][/home2/website1/public_html/elementary/wp-content/plugins/elementor/core/common/modules/ajax/module.php::175] Undefined array key "data" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-04-05 12:16:01 [warning X 2][/home2/website1/public_html/elementary/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php::150] Undefined array key "condition_type" [array (
  'trace' => '
#0: /home2/website1/public_html/elementary/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(150): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_template_json_item()
#2: /home2/website1/public_html/elementary/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(120): class type array_map()
#3: /home2/website1/public_html/elementary/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(59): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_templates_json()
#4: /home2/website1/public_html/elementary/wp-content/plugins/elementor/data/base/endpoint.php(158): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> get_items()
',
)]



== Elementor - Compatibility Tag ==
	
	Elementor Pro: Incompatible

== Elementor Pro - Compatibility Tag ==
	

				

````

</details>

**Comment by loucasl** [comment] 2023-04-05 13:37
You have the new top bar feature active (currently in the alpha development stage) which doesn't have support for display conditions yet

Deactivate that and you'll be able to access those again

**Comment by nicholaszein** [comment] 2023-05-28 04:12
Hello @nickdgreen,

Thank you for your submission! 🙏 

### 🔗 🐞 This issue is a Duplicate of #21862

Which is on the same subject. 

For this reason, I'm closing this thread and 🔃 **Merging** it with the original, so we can have all the discussions in one location, and deal with it more efficiently.

Feel free to continue the conversation there. 😉 

### 🔍 Please, in the future, remember to check if there isn't any thread similar to yours already opened. 

Best regards,

Nick

**Closed by nicholaszein** 2023-05-28 04:12 UTC
Labels: bug, type/ui/ux, component/popup, type/workflow, component/top-bar
