### ISSUE TITLE
Save Your Page to Library bug

### ISSUE THREAD

**Issue by borayeris** [elementor/elementor#13273] opened 2020-12-09 22:01 UTC
## Prerequisites

- [ x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ x ] The issue still exists against the latest stable version of Elementor.

## Description

00:46:33.918 Uncaught 
{…}
​
fileName: "https://domain.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5"
​
lineNumber: 22
​
message: "An \"el\" undefined must exist in DOM"
​
name: "Error"
​
stack: ""
​
<prototype>: Object { urlRoot: "http://marionettejs.com/docs/v2.4.5/", constructor: constructor(a, b), captureStackTrace: captureStackTrace(), … }
backbone.marionette.min.js:22

## Steps to reproduce

When I try to save a page to library which edited by Elementor stucks.

## Isolating the problem

- [ x ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ x ] This bug happens with a default WordPress theme active.
- [ x ] I can reproduce this bug consistently using the steps above.

## Environment
Wordpress 5.6
Latest Elementor

**Comment by shilo-ey** [comment] 2020-12-10 13:22
Thanks for reporting.

We will address this issue soon and release a patch.

Please follow this thread for updates.

Thanks!

**Comment by Abstract-Mindfreak** [comment] 2020-12-11 00:00
Hello ! I have the same problem. Elementor Pro and Elementor active, Hello Theme and Hello Child theme active. 
message: "An "el" undefined must exist in DOM"

**Comment by VenkmanNL** [comment] 2020-12-11 10:56
I get the same message when trying to edit a Ninja Forms field, making it impossible to edit anything in Ninja Forms. Using latest Elementor + Pro with wp 5.6.

**Comment by Worldwebscapes** [comment] 2020-12-11 23:28
Same here. Can replicate with only E/Pro activated and Twenty Twenty-One theme active.

**Comment by dagostinelli** [comment] 2020-12-13 00:48
I can replicate this as well.  

1. Create a "Single"
2. Save it

Check the JScript console

```
Object { fileName: "https://omitted.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5", lineNumber: 22, name: "Error", message: "An \"el\" undefined must exist in DOM", stack: "" }
```

**Comment by dmquin** [comment] 2020-12-13 04:51
Same problem WP 5.6 and latest Elementor and Elementor Pro versions

**Comment by divemasterza** [comment] 2020-12-13 07:50
+1 on this issue. Exactly the same as reported by others. Hopefully, the patch, hotfix, will be released soon.

**Comment by shilo-ey** [comment] 2020-12-13 14:30
We are currently working on a fix.

This issue origins from the upgrade of jQuery version build in WP 5.6

To avoid this issue for the meanwhile please use the following plugin:
https://wordpress.org/plugins/enable-jquery-migrate-helper/

A patch will release in the upcoming days.

Thanks

**Comment by karolgrudzinski** [comment] 2020-12-14 23:18
Installing that plugin doesn't fix the issue.

**Comment by AristidisKoutounidis** [comment] 2020-12-15 12:55
Downgrading WP-Core to 5.5.3 solved it for me.
I used "WP Downgrade | Specific Core Version"
https://de.wordpress.org/plugins/wp-downgrade/

**Comment by karolgrudzinski** [comment] 2020-12-15 13:56
> Downgrading WP-Core to 5.5.3 solved it for me.
> I used "WP Downgrade | Specific Core Version"
> https://de.wordpress.org/plugins/wp-downgrade/

I downgraded Wordpress and Elementor now shows dozens of saved templates that I tried to save since yesterday. So it looks that they were saved despite broken library.

**Comment by derKh4N** [comment] 2020-12-16 16:58
Same issue here! Circle of do nothing but still doing! 🤪

**Comment by Aviad-Herman** [comment] 2020-12-17 14:30
Hi guys, I'm merging this with issue #13297 which includes more cases of this bug. You can follow it for updates.

We are currently working to solve this issue which is caused by WP 5.6 upgrading JQuery version from 1.x to 3.x.

As a quickfix until we get a patch up and running you can either:
- Downgrade to WP 5.5.3 (for example using https://de.wordpress.org/plugins/wp-downgrade/)
- Use https://wordpress.org/plugins/enable-jquery-migrate-helper/

**Closed by Aviad-Herman** 2020-12-17 14:30 UTC
Labels: bug, compatibility
