### ISSUE TITLE
🔗 🐞 Bug Report: Excerpt Widget is not working in Container / Elementer Pro Dev Edition (Duplicate of #20256)

### ISSUE THREAD

**Issue by asiz007** [elementor/elementor#21715] opened 2023-03-21 08:30 UTC
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

In Loop using the Excerpt widget to show the excerpt is shown blank. Does not extract excerpt automatically from Content unless custom excerpt is written in post.

### Steps to reproduce

Create a loop
Add Featured Image, title and so on
Add Excerpt via Excerpt widget or add it dynamically using dynamic content on text or html
No Excerpt is shown. 

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

<html>
<body>
<div class="elementor-system-info-section elementor-system-info-server" style="outline: 0px; margin-bottom: 10px; color: rgb(60, 67, 74); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen-Sans, Ubuntu, Cantarell, &quot;Helvetica Neue&quot;, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(240, 240, 241); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">

Server Environment |   |  
-- | -- | --
Operating System: | Linux |  
Software: | Apache |  
MySQL version: | MariaDB Server v10.4.27 |  
PHP Version: | 8.2.4 |  
PHP Memory Limit: | 128M |  
PHP Max Input Vars: | 2500 |  
PHP Max Post Size: | 128M |  
GD Installed: | Yes |  
ZIP Installed: | Yes |  
Write Permissions: | All right |  
Elementor Library: | Connected |  

</div>
</body>
</html>Server Environment		
Operating System:	Linux	
Software:	Apache	
MySQL version:	MariaDB Server v10.4.27	
PHP Version:	8.2.4	
PHP Memory Limit:	128M	
PHP Max Input Vars:	2500	
PHP Max Post Size:	128M	
GD Installed:	Yes	
ZIP Installed:	Yes	
Write Permissions:	All right	
Elementor Library:	Connected	
WordPress Environment		
Version:	6.1.1	
Site URL:	https://greenview.com.np	
Home URL:	https://greenview.com.np	
WP Multisite:	No	
Max Upload Size:	128 MB	
Memory limit:	40M	
Max Memory limit:	256M	
Permalink Structure:	/news/%post_id%	
Language:	en-US	
Timezone:	Asia/Kathmandu	
Admin Email:	asmitacewon@gmail.com	
Debug Mode:	Inactive	
Theme		
Name:	Hello Elementor	
Version:	2.6.1	
Author:	Elementor Team	
Child Theme:	No	If you want to modify the source code of your theme, we recommend using a [child theme](https://go.elementor.com/wordpress-child-themes/).
User		
Role:	administrator	
WP Profile lang:	en_US	
User Agent:	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36	
Active Plugins		
[Elementor](https://elementor.com/?utm_source=wp-plugins&utm_campaign=plugin-uri&utm_medium=wp-dash) - 3.13.0-dev2	By [Elementor.com](https://elementor.com/?utm_source=wp-plugins&utm_campaign=author-uri&utm_medium=wp-dash)	
[Elementor Beta (Developer Edition)](https://elementor.com/) - 1.1.1	By [Elementor.com](https://elementor.com/?utm_source=wp-plugins&utm_campaign=dev-author-uri&utm_medium=wp-dash)	
[Elementor Pro](https://go.elementor.com/wp-dash-wp-plugins-author-uri/) - 3.11.6	By [Elementor.com](https://go.elementor.com/wp-dash-wp-plugins-author-uri/)	
[JetBlog For Elementor](https://crocoblock.com/plugins/jetblog/) - 2.3.1	By [Crocoblock](https://crocoblock.com/)	
[JetEngine](https://crocoblock.com/plugins/jetengine/) - 3.1.3.1	By [Crocoblock](https://crocoblock.com/)	
[Nepali Date Converter](https://www.addonspress.com/wordpress-plugins/nepali-date-converter/) - 2.0.5	By [addonspress](https://www.addonspress.com/)

**Comment by nicholaszein** [comment] 2023-04-18 04:01
Hello!

Thank you for your submission! 🙏 

### 🔗 🐞 This issue is a Duplicate of #20256

Which is on the same subject. 

For this reason, I'm closing this thread and 🔃 **Merging** it with the original, so we can have all the discussions in one location, and deal with it more efficiently.

Feel free to continue the conversation there. 😉 

### 🔍 Please, in the future, remember to check if there isn't any thread similar to yours already opened. 

Best regards,

Nick

**Closed by nicholaszein** 2023-04-18 04:01 UTC
Labels: bug, product/pro, component/dynamic-tag, type/dynamic-content, product/beta-3.13

**Comment by nicholaszein** [comment] 2023-04-20 17:38
Hello, @asiz007!

We are happy to announce that this new feature is now live in the latest v3.13-Beta release!

We would love to see you try this new feature and give your feedback in the [Beta Announcement](https://github.com/orgs/elementor/discussions/22119)! 💪

Please try it out and let us know!

https://github.com/orgs/elementor/discussions/22119

Kind regards

**Comment by nicholaszein** [comment] 2023-05-08 20:47
Hello there @asiz007!

We have great news! 🙌 

### 📢 We're happy to announce that the issue you raised was resolved in Elementor Pro **v3.13.0**! 🥳 

✅ Feel free to check it out and update your plugin to the new version!

Cheers 🥂
