### ISSUE TITLE
🚀 ACF Repeater Field Support

### ISSUE THREAD

**Issue by ayoubkhan558** [elementor/elementor#19477] opened 2022-08-15 07:58 UTC
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

I need ACF Repeater Field Support for elementor

### Describe the solution you'd like

I need ACF Repeater Field Support for elementor

### Describe alternatives you've considered

I need ACF Repeater Field Support for elementor.

### Additional context

I need ACF Repeater Field Support for elementor .

**Comment by nreljed** [comment] 2022-08-15 14:08
thank you for putting this request in the list.

to add other interesting elements on how I solved this problem (unfortunately for the moment with a 3rd plugin) and I unlocked the sesame to access my acf repeater and flexibe also (don't forget that too)

anywhere elementor pro

![Capture d’écran 2022-08-15 150256](https://user-images.githubusercontent.com/82481592/184650958-9bb84455-fc13-4a3e-aec2-607f952a5668.png)


the solution is very simple is to improve the dynamic tags for ACF and list them all

**Comment by hitsgee** [comment] 2022-08-16 06:53
Dynamic Content For Elementor also has a widget for this that works well :)

**Comment by arielk** [comment] 2022-08-24 11:37
Duplicate of #5979

**Closed by arielk** 2022-08-24 11:37 UTC
Labels: compatibility, request, component/acf

**Comment by never-failing** [comment] 2022-10-01 17:40
Я протестировал многие способы, такие как Dynamic Content For Elementor или AnyWhere Elementor или Piotnet Addons For Elementor Pro. Во многих случаях они не понимают многоуровневую задачу, такие как гибкое содержание + повторитель + повторитель или повторитель + повторитель + повторитель. Очень печально что на сегодняшний день я так и не нашел решение. Очевидно что разработчики этих плагинов не тестируют всевозможные сценарии, или им это не под силу.

I have tested many ways like Dynamic Content For Elementor or AnyWhere Elementor or Piotnet Addons For Elementor Pro. In many cases, they don't understand the layered challenge, such as flexible content + repeater + repeater or repeater + repeater + repeater. It is very sad that today I have not found a solution. It is obvious that the developers of these plugins do not test all kinds of scenarios, or they cannot do it.
