### ISSUE TITLE
🚀 Feature Request: Background clip transparent. New Text option

### ISSUE THREAD

**Issue by pauserratgutierrez** [elementor/elementor#17737] opened 2022-02-07 17:48 UTC
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

There's no widget to display transparent text masked with a photo or video behind.

![Screenshot_2022-02-07-18-54-23-730_com.android.chrome.jpg](https://user-images.githubusercontent.com/73240206/152844849-4099405a-0c8b-416e-bf64-50f360ad8e4f.jpg)

### Describe the solution you'd like

Adding an option to switch text mask on and off and allowing us to display anything behind. Maybe a new widget is better, I don't know.

But this will allow us to use the normal text options creating a new effect.

Reference: https://codepen.io/pierrinho/pen/NEYmLO
CSS: `background-clip: text;
-webkit-background-clip: text;
color: transparent;`

### Describe alternatives you've considered

Custom CSS code or additional plugins

**Comment by 79ho3ein** [comment] 2022-02-07 22:55
+1
In addition to the gradient color, the ability to display an image in the text can also be excellent and useful.

**Comment by arielk** [comment] 2022-09-12 08:58
Duplicate of https://github.com/elementor/elementor/issues/4676

**Closed by arielk** 2022-09-12 08:58 UTC
Labels: request/enhancement
