### ISSUE TITLE
⛔ 📚 ❓ API Question: Elementor Pro Form Field custom attribute value is not fetching correctly 

### ISSUE THREAD

**Issue by IMalikHussain** [elementor/elementor#22532] opened 2023-05-23 18:11 UTC
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

some one check the code i am unable to fetch the value of attribute in form field advance tab to compare in IF statement

```

if ( $selected_option === 'vehicle' ) {
        $vehicleFields[] = [$field_name => $field_value];}
		elseif ( $selected_option === 'customer' ) {
        $customerFields[] = [$field_name => $field_value];} 
		elseif ( $selected_option === 'vendor' ) {
        $vendorFields[] = [$field_name => $field_value];}

```

//////////////////////////////////////////////CODE////////////////////////////////////////////

```php

global $selected_option;
class Elementor_Forms_Patterns_Validation {
   // public $selected_option;
    public $allowed_fields = [
        'text',
        'email',
        'textarea',
    ];

    public function __construct() {
        add_filter( 'elementor_pro/forms/render/item', [ $this, 'maybe_add_attribute' ], 10, 3 );
        add_action( 'elementor/element/form/section_form_fields/before_section_end', [ $this, 'add_attribute_field_control' ], 100, 2 );
    }

    public function add_attribute_field_control( $element, $args ) {
        $elementor = \Elementor\Plugin::instance();
        $control_data = $elementor->controls_manager->get_control_from_stack( $element->get_name(), 'form_fields' );

        if ( is_wp_error( $control_data ) ) {
            return;
        }

        $tmp = new \Elementor\Repeater();
        $tmp->add_control(
            'field_attribute',
            [
                'label' => 'Attribute',
                'inner_tab' => 'form_fields_advanced_tab',
                'tab' => 'content',
                'tabs_wrapper' => 'form_fields_tabs',
                'type' => 'select',
                'options' => [
                    '' => 'None',
                    'vehicle' => 'vehicle',
                    'customer' => 'customer',
                    'vendor' => 'vendor',
                ],
                'conditions' => [
                    'terms' => [
                        [
                            'name' => 'field_type',
                            'operator' => 'in',
                            'value' => $this->allowed_fields,
                        ],
                    ],
                ],
            ]
        );

        $attribute_field = $tmp->get_controls();
        $attribute_field = $attribute_field['field_attribute'];

        $new_order = [];
        foreach ( $control_data['fields'] as $field_key => $field ) {
            if ( 'custom_id' === $field['name'] ) {
                $new_order['field_attribute'] = $attribute_field;
            }
            $new_order[ $field_key ] = $field;
        }
        $control_data['fields'] = $new_order;

        $element->update_control( 'form_fields', $control_data );
    }
		//echo 'Selected attribute value: ';
				//print_r($selected_options);
		  public function maybe_add_attribute( $field, $field_index, $form_widget ) {
        if ( isset( $field['field_attribute'] ) && in_array( $field['field_type'], $this->allowed_fields ) ) {
            $attribute = $field['field_attribute'];
            if ( ! empty( $attribute ) ) {
                $form_widget->add_render_attribute( 'input' . $field_index, 'data-attribute', $attribute );
                // Set the selected option to the global variable
                global $selected_option;
				$selected_option=array();
                $selected_option[] = $attribute;
            }
        }
        return $field;
    }
}

// Convert Elementor form data to ADF format and send email
add_action( 'elementor_pro/forms/new_record', function( $record, $handler ) {
    // Get form data and form name
    $data = $record->get_formatted_data();
    $form_id = $record->get_form_settings( 'form_id' );
    $form_name = $record->get_form_settings( 'form_name' );
    
	
	// Create ADF data array dynamically
    $adf_data = array();
    foreach ( $data as $field_name => $field_value ) {
        // Replace any space in field name with underscore
        $field_name = str_replace( ' ', '_', $field_name );
        $adf_data[ $field_name ] = $field_value;
    }

    // Generate ADF XML
    $xml = new DOMDocument( "1.0", "UTF-8" );
    $adf = $xml->createElement( "adf" );
    $prospect = $xml->createElement( "prospect" );

    // Add request date to prospect
    $requestdate = $xml->createElement( "requestdate", date( 'c' ) );
    $prospect->appendChild( $requestdate );
  

    global $selected_option;

    $vehicleFields = [];
    $customerFields = [];
    $vendorFields = [];
	
    //if ( ! empty( $selected_options ) ) 
	//{
    	if ( $selected_option === 'vehicle' ) 
		{
        $vehicleFields[] = [$field_name => $field_value];
   		} 
		
		elseif ( $selected_option === 'customer' ) 
		{
        $customerFields[] = [$field_name => $field_value];
   		} 
		
		elseif ( $selected_option === 'vendor' ) 
		{
        $vendorFields[] = [$field_name => $field_value];
    	}

	//}
// Add vehicle data to prospect
if ( ! empty( $vehicleFields ) ) {
    $vehicle = $xml->createElement( "vehicle" );
    foreach ( $vehicleFields as $field ) {
        foreach ( $field as $field_name => $field_value ) {
            $fieldElement = $xml->createElement( $field_name, $field_value );
            $vehicle->appendChild( $fieldElement );
        }
    }
    $prospect->appendChild( $vehicle );
}
// Add customer data to prospect
if ( ! empty( $customerFields ) ) {
    $customer = $xml->createElement( "customer" );
    $contact = $xml->createElement( "contact" );
    foreach ( $customerFields as $field ) {
        foreach ( $field as $field_name => $field_value ) {
            $fieldElement = $xml->createElement( $field_name, $field_value );
            $contact->appendChild( $fieldElement );
        }
    }
    $customer->appendChild( $contact );
    $prospect->appendChild( $customer );
}

// Add vendor data to prospect
if ( ! empty( $vendorFields ) ) {
    $vendor = $xml->createElement( "vendor" );
    $contact = $xml->createElement( "contact" );
    foreach ( $vendorFields as $field ) {
        foreach ( $field as $field_name => $field_value ) {
            $fieldElement = $xml->createElement( $field_name, $field_value );
            $contact->appendChild( $fieldElement );
        }
    }
    $vendor->appendChild( $contact );
    $prospect->appendChild( $vendor );
}

    $adf->appendChild( $prospect );
    $xml->appendChild( $adf );

    // Format ADF XML for readability
    $xml->formatOutput = true;
    $adf_xml = $xml->saveXML();

    // Send email with ADF XML in body
    $to = array( 'example@mail.com')
    $subject = 'Subject ';
    $headers = array(
        'Content-Type: text/plain; charset=UTF-8',
        'From: From <email@example.com>
    );
    wp_mail( $to, $subject, $adf_xml, $headers );
}, 10, 2 );

new Elementor_Forms_Patterns_Validation();

```

### Steps to reproduce

For Example
i want that if Model is selected as Vehicle
i want that if Name is selected as customer
i want that if Phone is selected as Vedor

```
<img width="410" alt="Screenshot 2023-05-23 at 11 15 10 PM" src="https://github.com/elementor/elementor/assets/134432534/7a65a093-104e-4828-ae16-591a24777db3">

<?ADF VERSION "1.0"?>
<?XML VERSION “1.0”?>
<adf>
<prospect>
<requestdate>2000-03-30T15:30:20-08:00</requestdate>
     <vehicle>
        <model>Blazer</model>
    </vehicle>
    <customer>
       <contact>
            <name part="full">John Doe</name>
        </contact>
     </customer>
      <vendor>
         <contact>
            <phone>393-999-3922</phone>
         </contact>
         </vendor>
 </prospect>
</adf> 

```
Output something like this

But i am getting this output please let me know where is the problem, if someone can fix it.

```
<?ADF VERSION "1.0"?>
<?XML VERSION “1.0”?>
<adf>
<prospect>
<requestdate>2000-03-30T15:30:20-08:00</requestdate>
      <vendor>
         <contact>
            <phone>393-999-3922</phone>
         </contact>
         </vendor>
 </prospect>
</adf> 
```

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently following the steps above.

### System Info

<details>
<summary>System Info</summary>

````txt



== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MariaDB Server v10.4.26
	PHP Version: 7.3.33
	PHP Memory Limit: 128M
	PHP Max Input Vars: 2500
	PHP Max Post Size: 128M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.2.2
	
	WP Multisite: No
	Max Upload Size: 128 MB
	Memory limit: 40M
	Max Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 0
	
	Debug Mode: Inactive



== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.3 Safari/605.1.15

== Active Plugins ==
	Bunyad Demo Import
		Version: 2.6.2
		Author: ThemeSphere & ProteusThemes

	Code Snippets
		Version: 3.3.0
		Author: Code Snippets Pro

	Custom Elementor Form Widget
		Version: 1.0
		Author: Your Name

	Elementor
		Version: 3.6.6
		Author: Elementor.com

	Elementor Pro
		Version: 3.7.2
		Author: Elementor.com

	Regenerate Thumbnails
		Version: 3.1.5
		Author: Alex Mills (Viper007Bond)

	SmartMag Core
		Version: 1.3.1
		Author: ThemeSphere

	Sphere Core
		Version: 1.5.1
		Author: ThemeSphere

	Yoast SEO
		Version: 18.9
		Author: Team Yoast

	Yoast SEO Premium
		Version: 18.5
		Author: Team Yoast


== Must-Use Plugins ==
	StackCache
		Version: 
		Author: Stack CP


== Elementor Experiments ==
	Optimized DOM Output: Active
	Improved Asset Loading: Active
	Improved CSS Loading: Active by default
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Active by default
	Import Export Template Kit: Active by default
	Additional Custom Breakpoints: Active by default
	Hide native WordPress widgets from search results: Active by default
	: Inactive by default
	Flexbox Container: Inactive by default
	Default to New Theme Builder: Active by default
	Landing Pages: Active by default
	Color Sampler: Active by default
	Favorite Widgets: Active by default
	Admin Top Bar: Active by default
	Page Transitions: Active by default
	Notes: Active by default
	Form Submissions: Active by default
	Scroll Snap: Active by default



````

</details>

**Comment by nicholaszein** [comment] 2023-05-24 18:15
Hello, @IMalikHussain,

Thank you for reaching out! 🙏 

### ⛔ After reviewing your report we concluded this is not a bug caused by Elementor. The feature you're referring to is not yet supported.

We can't provide review support for extensive custom code like yours. Please refer to the documentation to learn how to hook into Elementor Forms and use only the methods available in our documentation. Anything different from what is shared there is out of scope.

https://developers.elementor.com/docs/hooks/forms/

Kind regards

**Closed by nicholaszein** 2023-05-24 18:15 UTC
Labels: type/developer-api, component/forms, component/forms/actions, mod*
