### ISSUE TITLE
Unnecessary call https://my.elementor.com/api/v1/info/

### ISSUE THREAD

**Issue by gralance** [elementor/elementor#14801] opened 2021-05-03 17:39 UTC
Every time I switch to a new page in the wp-admin
Elementor always calls the https://my.elementor.com/api/v1/info/ every time.
It takes 1.5 to 4.5 seconds to wait for the API, which slows down the response time painfully.
Please reduce the frequency of calling https://my.elementor.com/api/v1/info/
which saves tons of time to users!

**Comment by shilo-ey** [comment] 2021-05-04 16:15
Hi @gralance 

We can't reproduce the issue you are referring to. Please make sure your database is properly set and no errors occur.

If the issue persists, please contact our support at support @elementor.com for guidance in resolving this issue and mention that you were directed by me and reference this issue.

Thanks.

**Comment by DorShahar** [comment] 2021-05-12 14:52
Closing for lack of activity,
Feel free to reopen if the issue persists.

**Closed by DorShahar** 2021-05-12 14:52 UTC
Labels: status/needs feedback
