### ISSUE TITLE
🐞 Bug report: Import template fail while in editing mode. OK on admin page.

### ISSUE THREAD

**Issue by Mulli** [elementor/elementor#18037] opened 2022-03-01 17:23 UTC
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

When I open Elementor editor with a new page
AND try to import a template - it fails with message "Error Occurred".

When I go to admin panel: Elementor > Templates > Import
It works fine on the same file.

### Steps to reproduce

1. Export a temple
2. Open Elementor editor with a new page
3. Import a template - on an empty new page
4. BOOM. it fails with message "Error Occurred".

Go to admin panel:
Elementor > Templates > Import > select the same file as before
It works fine.

WORKAROUND: (bypass the issue)
Go Back to Elementor editor and insert the template. 

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: WINNT
	Software: Apache/2.4.43 (Win32)
	MySQL version: MySQL Community Server - GPL v8.0.16
	PHP Version: 8.0.0
	PHP Max Input Vars: 4000
	PHP Max Post Size: 1000M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.9.1
	Site URL: https://plnext2.local
	Home URL: https://plnext2.local
	WP Multisite: No
	Max Upload Size: 300 MB
	Memory limit: 512M
	Permalink Structure: /%postname%/
	Language: he-IL
	Timezone: Asia/Jerusalem
	Admin Email: mulli@site2goal.co.il
	Debug Mode: Active

== Theme ==
	Name: Mbo Digmatec
	Version: 1.0.1
	Author: Elementor Team
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.5.0
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: he_IL
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36

== Active Plugins ==
	ACF: Mbo Compute
		Version: 1.0.0
		Author: Mulli Bahr

	ACF to REST API
		Version: 3.3.2
		Author: Aires Gonçalves

	Activity Log
		Version: 2.8.2
		Author: Activity Log Team

	Advanced Custom Fields PRO
		Version: 5.12
		Author: Delicious Brains

	Classic Editor
		Version: 1.6.2
		Author: WordPress Contributors

	Custom Post Type UI
		Version: 1.10.2
		Author: WebDevStudios

	DigmaTec MBO - Management By Objectives
		Version: 1.0.0
		Author: Mulli

	Duplicate Page
		Version: 4.4.8
		Author: mndpsingh287

	Easy WP SMTP
		Version: 1.4.7
		Author: wpecommerce, alexanderfoxc

	Elementor
		Version: 3.5.6
		Author: Elementor.com

	Elementor Pro
		Version: 3.6.2
		Author: Elementor.com

	Graphina - Elementor Charts and Graphs
		Version: 1.6.8
		Author: Iqonic Design

	GraphinaPro – Elementor Dynamic Charts & Datatable
		Version: 1.2.8
		Author: Iqonic Design

	JWT Authentication for WP-API, DigmaTec version
		Version: 1.2.7 - Mulli's
		Author: Mulli Bahr fixes (Orig: Enrique Chavez, https://enriquechavez.co)

	LTR <=> RTL Admin content
		Version: 0.5.7
		Author: Ronny Sherer

	PDF Generator Addon for Elementor Page Builder
		Version: 1.6.1
		Author: RedefiningTheWeb

	Plev admin page
		Version: 1.0.0
		Author: Mulli Bahr

	whatwedo ACF Cleaner
		Version: 1.0.0
		Author: whatwedo

	WP-Optimize - Clean, Compress, Cache
		Version: 3.2.2
		Author: David Anderson, Ruhani Rabin, Team Updraft

	WP Crontrol
		Version: 1.12.0
		Author: John Blackbourn & crontributors

== Must-Use Plugins ==
	Elementor Safe Mode
		Version: 1.0.0
		Author: Elementor.com

== Elementor Experiments ==
	פלט DOM שעבר אופטימיזציה: לא פעיל כברירת מחדל
	טעינת נכסים משופרת: לא פעיל כברירת מחדל
	Improved CSS Loading: לא פעיל כברירת מחדל
	Inline Font Icons: לא פעיל כברירת מחדל
	שיפורי נגישות: לא פעיל כברירת מחדל
	Import Export Template Kit: פעיל כברירת מחדל
	Additional Custom Breakpoints: לא פעיל כברירת מחדל
	Hide native WordPress widgets from search results: פעיל כברירת מחדל
	Default to New Theme Builder: פעיל כברירת מחדל
	Hello Theme Header & Footer: לא פעיל כברירת מחדל
	דפי נחיתה: פעיל כברירת מחדל
	דוגם צבע: פעיל כברירת מחדל
	וידג׳טים מעודפים: פעיל כברירת מחדל
	באר עליון אדמין: פעיל כברירת מחדל
	מעבר עמוד: פעיל כברירת מחדל
	לידים: פעיל כברירת מחדל
	Scroll Snap: פעיל כברירת מחדל

== יומן שינויים ==
	
Log: showing 20 of 312022-02-01 05:40:15 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'אלמנטור פרו',
  'from' => '3.5.2',
  'to' => '3.6.0',
)]
2022-02-06 00:07:04 [info] elementor::elementor_updater Started 
2022-02-06 00:07:04 [info] אלמנטור/Upgrades - _on_each_version Start  
2022-02-06 00:07:05 [info] אלמנטור/Upgrades - _on_each_version Finished 
2022-02-06 00:07:05 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'אלמנטור',
  'from' => '3.5.4',
  'to' => '3.5.5',
)]
2022-02-10 02:44:01 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'אלמנטור פרו',
  'from' => '3.6.0',
  'to' => '3.6.1',
)]
2022-02-10 02:44:05 [info] elementor-pro::elementor_pro_updater Started 
2022-02-10 02:44:05 [info] אלמנטור פרו/Upgrades - _on_each_version Start  
2022-02-10 02:44:05 [info] אלמנטור פרו/Upgrades - _on_each_version Finished 
2022-02-10 02:44:05 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'אלמנטור פרו',
  'from' => '3.6.0',
  'to' => '3.6.1',
)]
2022-02-15 09:28:14 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'אלמנטור פרו',
  'from' => '3.6.1',
  'to' => '3.6.2',
)]
2022-02-15 09:28:20 [info] elementor-pro::elementor_pro_updater Started 
2022-02-15 09:28:20 [info] אלמנטור פרו/Upgrades - _on_each_version Start  
2022-02-15 09:28:20 [info] אלמנטור פרו/Upgrades - _on_each_version Finished 
2022-02-15 09:28:20 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'אלמנטור פרו',
  'from' => '3.6.1',
  'to' => '3.6.2',
)]
2022-03-01 18:57:59 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'אלמנטור',
  'from' => '3.5.5',
  'to' => '3.5.6',
)]
2022-03-01 18:58:05 [info] elementor::elementor_updater Started 
2022-03-01 18:58:06 [info] אלמנטור/Upgrades - _on_each_version Start  
2022-03-01 18:58:06 [info] אלמנטור/Upgrades - _on_each_version Finished 
2022-03-01 18:58:06 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'אלמנטור',
  'from' => '3.5.5',
  'to' => '3.5.6',
)]

PHP: showing 7 of 7PHP: 2022-01-03 09:55:03 [notice X 14][/home/hila/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-01-16 17:57:46 [notice X 2][/home/hila/public_html/wp-content/plugins/elementor/includes/template-library/sources/local.php::712] ob_end_clean(): failed to delete buffer. No buffer to delete [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-01-17 02:31:07 [notice X 1][/home/hila/public_html/wp-content/plugins/elementor-pro/modules/query-control/module.php::740] Trying to get property 'name' of non-object [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-01-22 10:16:45 [notice X 1][/home/hila/public_html/wp-content/plugins/elementor-pro/modules/dynamic-tags/acf/tags/acf-text.php::33] Undefined offset: 1 [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-01-28 13:21:36 [warning X 16][C:\Users\Lenovo\Local Sites\plnext2\app\public\wp-content\plugins\elementor\core\common\modules\ajax\module.php::171] Undefined array key "data" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-01-28 16:11:32 [warning X 186][C:\Users\Lenovo\Local Sites\plnext2\app\public\wp-content\plugins\elementor-pro\modules\dynamic-tags\acf\tags\acf-text.php::33] Undefined array key 1 [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-02-17 04:48:04 [error X 3][C:\Users\Lenovo\Local Sites\plnext2\app\public\wp-content\plugins\elementor\includes\template-library\manager.php::457] Uncaught Error: Cannot use object of type WP_Error as array in C:\Users\Lenovo\Local Sites\plnext2\app\public\wp-content\plugins\elementor\includes\template-library\manager.php:457
Stack trace:
#0 [internal function]: Elementor\TemplateLibrary\Manager->import_template(Array)
#1 C:\Users\Lenovo\Local Sites\plnext2\app\public\wp-content\plugins\elementor\includes\template-library\manager.php(550): call_user_func(Array, Array)
#2 C:\Users\Lenovo\Local Sites\plnext2\app\public\wp-content\plugins\elementor\includes\template-library\manager.php(582): Elementor\TemplateLibrary\Manager->handle_ajax_request('import_template', Array)
#3 [internal function]: Elementor\TemplateLibrary\Manager->Elementor\TemplateLibrary\{closure}(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#4 C:\Users\Lenovo\Local Sites\plnext2\app\public\wp-content\plugins\elementor\core\common\modules\ajax\module.php(171): call_user_func(Object(Closure), Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#5 C:\Users\Lenovo\Local Sites\plnext2\app\public\wp-includes\class-wp-hook.php(307): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#6 C:\Users\Lenovo\Local Sites\plnext2\app\public\wp-includes\class-wp-hook.php(331): WP_Hook->apply_filters('', Array)
#7 C:\Users\Lenovo\Local Sites\plnext2\app\public\wp-includes\plugin.php(474): WP_Hook->do_action(Array)
#8 C:\Users\Lenovo\Local Sites\plnext2\app\public\wp-admin\admin-ajax.php(187): do_action('wp_ajax_element...')
#9 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 4 of 4JS: 2022-01-24 10:10:37 [error X 5][https://plev.today/wp-content/plugins/elementor/assets/js/editor.js?ver=3.5.4:30233:44] Cannot read properties of null (reading \'getBoundingClientRect\') 
JS: 2022-02-13 14:11:12 [error X 1][https://plnext2.local/wp-content/plugins/elementor-pro/assets/js/editor.js?ver=3.6.1:8340:51] Cannot read properties of undefined (reading \'settings\') 
JS: 2022-02-17 02:46:59 [error X 1][https://plnext2.local/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.js?ver=2.4.5.e1:1813:9] View (cid: \"view108\") has already been destroyed and cannot be used. 
JS: 2022-02-19 07:46:32 [error X 2][https://plnext2.local/wp-content/plugins/elementor/assets/js/common.js?ver=3.5.5:21109:29] Cannot read properties of undefined (reading \'global\') 

== אלמנטור - Compatibility Tag ==
	
	Elementor Pro: תואם
	Graphina - Elementor Charts and Graphs: תואם
	GraphinaPro – Elementor Dynamic Charts & Datatable: תאימות לא הוגדרה
	PDF Generator Addon for Elementor Page Builder: תואם

== אלמנטור פרו - Compatibility Tag ==
	
	Graphina - Elementor Charts and Graphs: לא תואם

**Comment by MichaelDarko** [comment] 2022-03-01 21:53
Other people including me have been experiencing the same bug.

#17490

**Comment by rami-elementor** [comment] 2022-03-08 10:58
Duplicate of #17490

**Closed by rami-elementor** 2022-03-08 10:58 UTC
Labels: bug
