### ISSUE TITLE
⛔ List items don't show when using Text Editor > Dynamic Content > Post Excerpt > Apply to Post Content

### ISSUE THREAD

**Issue by portrayaloflife** [elementor/elementor#29475] opened 2024-12-02 20:40 UTC
### Prerequisites

- [X] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [ ] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

Creating a page template we wanted to pull lists to style from the pages content through dynamic content in a text editor widget. But lists do not show.

### Steps to reproduce

1. Create a bulleted list on a page
2. Create a Single Page template for that page
3. Add a text editor widget to dynamically pull the page content
4. see the list not showing

### Expected behavior

That the bulleted list shows

### Isolating the problem

- [ ] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [X] This bug happens with the Hello Elementor theme active.
- [X] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

<details>
<summary>Click to reveal</summary>

```txt

== Server Environment ==
	Operating System: Linux
	Software: Flywheel/5.1.0
	MySQL version: (Google) v5.7.44
	PHP Version: 8.2.25
	PHP Memory Limit: 256M
	PHP Max Input Vars: 10000
	PHP Max Post Size: 900M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.6.2
	Site URL: -
	Home URL: -
	WP Multisite: No
	Max Upload Size: 900 MB
	Memory limit: 256M
	Max Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en_US
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 3.1.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en-US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 3.25.10
		Author: Elementor.com

	Elementor Pro
		Version: 3.25.4
		Author: Elementor.com

	JetElements For Elementor
		Version: 2.7.1.1
		Author: Crocoblock

	Temporary Login
		Version: 1.3.0
		Author: Elementor.com


== Features ==
	Custom Fonts: 0
	Custom Icons: 0

== Integrations ==
	


== Elementor Experiments ==
	Improved CSS Loading: Inactive by default
	Inline Font Icons: Inactive by default
	Additional Custom Breakpoints: Active by default
	Container: Active
	Upgrade Swiper Library: Active by default
	Nested Elements Performance: Active by default
	Optimized Control Loading: Active by default
	Optimized Markup: Inactive by default
	Conditionally load Swiper CSS files: Inactive by default
	Plugin Onboarding: Active by default
	CSS Smooth Scroll: Active by default
	Default to New Theme Builder: Active by default
	Header & Footer: Active by default
	Elementor Home Screen: Active by default
	Landing Pages: Active by default
	Nested Elements: Active
	Editor Top Bar: Active by default
	Pages Panel: Inactive by default
	Element Caching: Inactive by default
	Link In Bio: Active by default
	Floating Buttons: Active by default
	Elementor Editor Events: Inactive by default
	Atomic Widgets: Inactive by default
	Launchpad Checklist: Inactive by default
	Menu: Inactive by default


== Log ==
	
[redacted by moderation] 


== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatible
	JetElements For Elementor: Incompatible

== Elementor Pro - Compatibility Tag ==
	
	JetElements For Elementor: Incompatible


```
</details>

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by nicholaszein** [comment] 2024-12-03 16:56
Hi @portrayaloflife!

Can you please elaborate on what dynamic tag you used to pull the lists?

The text editor widget is not meant to be used for this kind of purpose (assuming you used it to show the post excerpt). By default, pulling the excerpt from the content of a document will remove any markup and style. This is the intended behavior.

If you are pulling the content using this method, you should instead use the Post Content widget.

Please clarify which dynamic tag you are using, and how.

Kind regards

**Comment by portrayaloflife** [comment] 2024-12-03 17:30
Hey Nick!

Screenshots below. Makes sense. We were trying to do it through the text widget so we can utilize the custom columns, but just ended up using straight CSS instead. But as you'll see, list items are excluded. Though like you said that may be by design. 

<img width="1266" alt="image" src="https://github.com/user-attachments/assets/4b82a6aa-3017-45eb-93e9-b98914de82d1">
<img width="1335" alt="image" src="https://github.com/user-attachments/assets/70dfc11e-acf2-41ab-98cf-3e259cc74237">
<img width="611" alt="image" src="https://github.com/user-attachments/assets/4191ce0d-6da4-4bb7-8560-30a2e94a1f94">

**Comment by neylwalecki** [comment] 2024-12-15 22:24
@portrayaloflife the basic theme.json config would resolve this formating issue.
https://developer.wordpress.org/themes/global-settings-and-styles/
https://codewp.ai/tool/theme-json/

**Comment by nicholaszein** [comment] 2024-12-24 18:35
Hi @portrayaloflife!

I'm closing this issue as it is not a bug. The Post Excerpt Dynamic tag sanitizes the text intentionally, and we are not going to change this due to user demand.

Kind regards

**Closed by nicholaszein** 2024-12-24 18:35 UTC
Labels: product/pro, component/dynamic-tag, type/dynamic-content, mod*, theme-builder/single-template, widget/text-editor
