### ISSUE TITLE
⛔ Sticky Active class added to sticky elements does not take in consideration the value for the Offset on sticky elements

### ISSUE THREAD

**Issue by SirLouen** [elementor/elementor#25801] opened 2024-04-21 13:59 UTC
### Prerequisites

- [X] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [X] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

This issue is exactly the same as this one:
https://github.com/elementor/elementor/issues/5422

But it was closed without a real solution

Fortunately another user provided a perfect solution for this here, that could be implemented to sort this problem:
https://github.com/elementor/elementor/issues/5422#issuecomment-1259675321

### Steps to reproduce

1. Add a header
2. Put in the header the Motions Effect -> Sticky Top
3. Set a Effects Offset for example of 150
4. Scroll down 150 px to see it doesnt work

### Expected behavior

After scrolling down the desired px (in the example 150px) the effect should trigger.

### Isolating the problem

- [X] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [X] This bug happens with the Hello Elementor theme active.
- [X] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

<details>
<summary>Click to reveal</summary>

````txt

== Server Environment ==
	Operating System: Linux
	Software: nginx/1.24.0
	MySQL version: MariaDB Server v10.5.23
	PHP Version: 8.2.17
	PHP Memory Limit: 256M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 8M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.5.2
	Site URL: http://elementorbug.mcamargo.es
	Home URL: http://elementorbug.mcamargo.es
	WP Multisite: No
	Max Upload Size: 8 MB
	Memory limit: 40M
	Max Memory limit: 256M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: en_US
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 3.0.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en-US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 3.21.0
		Author: Elementor.com

	Elementor Pro
		Version: 3.21.0
		Author: Elementor.com


== Features ==
	Custom Fonts: 0
	Custom Icons: 0

== Integrations ==
	


== Elementor Experiments ==
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Active by default
	Additional Custom Breakpoints: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active by default
	Upgrade Swiper Library: Active by default
	Grid Container: Active by default
	Nested Elements Performance: Inactive by default
	Optimized Control Loading: Inactive by default
	Default to New Theme Builder: Active by default
	Hello Theme Header & Footer: Active by default
	Elementor Home Screen: Active by default
	Editor Top Bar: Inactive by default
	Build with AI: Active by default
	Landing Pages: Active by default
	Nested Elements: Inactive by default
	Lazy Load Background Images: Inactive by default
	Display Conditions: Active by default
	Form Submissions: Active by default
	Menu: Inactive by default
	Taxonomy Filter: Active by default


== Log ==
	
Log: showing 5 of 52024-04-15 16:02:56 [info] elementor::elementor_updater Started 
2024-04-15 16:02:56 [info] Elementor/Upgrades - _on_each_version Start  
2024-04-15 16:02:56 [info] Elementor/Upgrades - _on_each_version Finished 
2024-04-15 16:02:56 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.20.4',
  'to' => '3.21.0',
)]
2024-04-15 16:02:56 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.20.4',
  'to' => '3.21.0',
)]

PHP: showing 1 of 1PHP: 2024-04-15 16:16:44 [notice X 2][../wp-content/plugins/elementor-pro/modules/screenshots/module.php::33] Function utf8_decode() is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]



== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatible

== Elementor Pro - Compatibility Tag ==

````

</details>

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by nicholaszein** [comment] 2024-05-16 20:49
Hi, @SirLouen,

Thank you for reaching out! 🙏 

### ⛔ After reviewing your report we concluded this is not a bug caused by Elementor. The feature you're referring to is not yet supported.

I think you are mixing different things. Let me explain:

1. The Elementor Pro Sticky motion effect is supposed to activate the sticky element **<ins>every time the sticky element touches the top of the viewport</ins>**. This is by design, and intended behavior. When it reaches the top, the `.elementor-sticky--active` class is added to the sticky element, and it immediately becomes sticky. If the sticky element is already touching the top of the viewport, then it will automatically be active and the class will be added to the element.

2. The **`Offset`** option, defines the distance from the top of the viewport from which the element will become sticky (and maintain the distance), and is activated too when that value is reached, and the `.elementor-sticky--active` class will be added to the sticky element. So in your example, a sticky element that has an offset of `150px`, and is at or below `150px` of distance from the top of the viewport, will automatically become active. Which means that if the distance of the sticky element from the top of the viewport is below `150px`, it will become active immediately.

2. The **`Effects Offset`** setting defines when the `.elementor-sticky--effects` class is added to the element, and is not intended to be used to define when a sticky element will be activated, or stick to the top, but rather when the effects will be applied after you've scrolled a certain amount of pixels _AFTER_ the sticky element becomes active. So, in your example, if the sticky element is active, and you have scrolled the number of pixels defined in the **`Effects Offset`** _AFTER_ the sticky element has become sticky, _THEN_ the effects will be applied.

To simplify:

1. A sticky element becomes active when it reaches the top of the viewport including the distance defined in the **`Offset`** setting.
2. A sticky element applies your effects based on the distance you have scrolled in pixels defined in the **`Effects Offset`** setting _AFTER_ the element becomes sticky.

Maybe the video below can illustrate it better:


https://github.com/elementor/elementor/assets/113993460/f70946c7-9007-474b-aee6-05603d80e1b5

I hope this clarifies how it works, and that you understand nothing is broken. This is the expected behavior for the Sticky Motion Effect.

However, if you think this effect should be changed, please submit a new [🚀 Feature Request](https://github.com/orgs/elementor/discussions/new?category=feature-request), explaining how you would want it to behave, and we will consider it in the future if there is enough demand (votes) from other users.

For now, I'm closing this issue as it is not a bug.

Kind regards

**Closed by nicholaszein** 2024-05-16 20:49 UTC
Labels: product/pro, type/layout, widget/motion-effects/sticky, mod*, widget/settings
