### ISSUE TITLE
acf color picker not working with portfolio widget

### ISSUE THREAD

**Issue by yossab** [elementor/elementor#11646] opened 2020-06-16 14:24 UTC
I use color picker(acf) with portfolio widget.
but lt is not working 
plz help me.... T.T

**Comment by lior-sh** [comment] 2020-06-16 15:32
Hi @yossab,

Thanks for reporting, we couldn't reproduce the issue.
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information:
* Prerequisites.
* **Steps to replicate**.
* Isolating the problem.
* **System info**.
* One issue per thread
Without it, we simply can't help.
Thanks.

**Comment by lior-sh** [comment] 2020-06-17 12:06
Duplicate of #11655

**Closed by lior-sh** 2020-06-17 12:06 UTC
Labels: status/needs feedback
