### ISSUE TITLE
Image Object-Fit control for non-desktop responsive modes

### ISSUE THREAD

**Issue by Bot12313** [elementor/elementor#13799] opened 2021-02-04 01:17 UTC
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

## Description

For Image widget "Object-fit" control doesn't show when editing image properties for mobile/tablet device/

## Steps to reproduce

1. Create new page
2. Edit it with Elementor
3. Insert image (placeholder's fine)
4. Switch to _mobile_ responsive mode
5. Image -> Style -> Set any **Height** value
6. Switch back to _desktop_ responsive mode
7. Change height again
8. You will see the "Object Fit" control field
9. Switch to the mobile version again

## Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a default WordPress theme active.
- [X] I can reproduce this bug consistently using the steps above.

## Environment

[system-info-web.local-04-02-2021.txt](https://github.com/elementor/elementor/files/5922526/system-info-web.local-04-02-2021.txt)

**Comment by DorShahar** [comment] 2021-02-04 07:33
Hi @Bot12313 
I couldn't reproduce the problem: Object fit loads for all the platforms according to your steps. 

I noticed that you are using the Twenty Twenty-One theme. In the release of Elementor core v3.1.0 we noticed problems that came from the theme, so there is a slight chance that it is related . 

If the problem still happens - please add a short video. 

Thanks

**Comment by Bot12313** [comment] 2021-02-04 11:15
### Reproducing
Changed theme to "Twenty Nineteen", reproduced steps with additional comments.
https://youtu.be/_ubJaiO_fKk

### Source of problem
As I can see from this code snippet, responsive control depends only on desktop related fields (and it works fine accordingly to this), but this is not how it should be, is it?
https://github.com/elementor/elementor/blob/2b10906817663259f8a55753c0edf23e86fb8799/includes/widgets/image.php#L352-L373

**Comment by DorShahar** [comment] 2021-02-07 07:52
Hi @Bot12313 

Thanks for the video.
I was able to reproduce. This a bug in our conditions system (as you noticed)
I can't tell when it will be fixed.

I will come back with an answer when I have more details. 

Thanks.

**Comment by rami-elementor** [comment] 2022-09-22 13:14
Tested with 3.7.6, looks like it was already fixed.

Closing the issue. If happens again, please open a new issue.

**Closed by rami-elementor** 2022-09-22 13:14 UTC
Labels: bug, type/responsive
