### ISSUE TITLE
The Elementor limitation for only 1 Style Kit and 1 Global Button Style. STOP!

### ISSUE THREAD

**Issue by sgripen** [elementor/elementor#17087] opened 2021-12-01 16:36 UTC
Everything is beautiful, but the workflow needs to be more productive when working with global style overrides, starting with Style Kit definitions. Please assign a real role to the Settings > Styles tab, create a Style Kits selector and you will already be revolutionizing the limited way that element forces us to lock in our styles.

For example, this would give us the freedom to quickly switch to a dark version of the site, or an alternate styles version, obviously keeping the content. Perhaps, for this to work correctly in color kits alternation, you would have to add some more system color fields and they cannot be deleted, look at default colors as it works in bootstrap. This would work perfectly with a "**Dark mode**" widget for use on the front end, the configuration would be based on the predefined style kits. It's the fastest and most versatile way for you to add a new feature, already with the existing functions. We could create Style Kits for every festive season of the year.

Now speaking of buttons, element leaves a lot to be desired regarding the lack of active resource styling. The color definition for the buttons should work separately from the pattern formatting. This is so we can add the global and quickly selectable styles for Primary, Secondary, Default etc patterns. These are minimal settings and necessary to improve the workflow with Elementor.

**Comment by shilo-ey** [comment] 2021-12-01 16:41
Please edit your heading according to the guidelines.

Thanks for the feedback,
Please follow guidelines for opening a new [feature request](https://github.com/pojome/elementor/issues/new?template=Feature_request.md), so we can help you better.

Thanks.

**Comment by gitgripp** [comment] 2021-12-01 16:51
> 
Edited! The intention was to draw attention to the problem as also seen here:
As was also discussed here https://www.reddit.com/r/elementor/comments/kdc6hs/do_not_delete_the_theme_builder_default_kit/

**Comment by paauserrat** [comment] 2022-02-01 20:44
#17670

**Comment by arielk** [comment] 2022-09-12 19:44
Duplicate of https://github.com/elementor/elementor/issues/17670

**Closed by arielk** 2022-09-12 19:44 UTC
Labels: request/feature, component/site-settings
