### ISSUE TITLE
🔗 🐞 Bug Report: The pointer-events don't work on Image Carousel with the Fade effect (Duplicate of #22927)

### ISSUE THREAD

**Issue by titibleh** [elementor/elementor#23393] opened 2023-08-12 17:56 UTC
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

There is an issue with the Image Carousel widget. If you choose the "Fade" effect, the `pointer-event: auto;` doesn't work for the active swiper. For this reason, you cannot select the text and all links are disabled like media files (lightbox), custom URL, caption, title or description (annoying if you add a link), etc. See the additional information below the screenshot for more details.

![image-carousel-fade-pointer-event-none](https://github.com/elementor/elementor/assets/142108952/f6cf6558-6cf0-4f75-ab25-388b92bededd)

**Additionnal information:**
- If you choose the "Slide" effect all works like a charm.
- If you select "**Infinite Loop:** Yes" the issue is for all slides but if you select "**Infinite Loop:** No"  the issue is for all slides except the first one.
- Same issue with SwiperJS lib v. 5.36 and 8.45.
- The issue didn't exist with Elementor v. 3.11.5 and lower. The issue exists with Elementor v.3.15.1 and above. All between versions haven't been tested so we don't know from which version the issue appeared.

### Steps to reproduce

1) Select Image Carousel widget
2) Add 2 or more images with caption, title and description `<a href="#">Link</a>`
3) Select "**Caption:** title, caption or description" _(same result)_
4) Select "**Link to:** Custom URL" and write `#`*
5) Choose "**Infinite Loop:** Yes**"
6) Choose "**Effect:** Fade"
7) Publish and see that all pointer-events are disabled.

*You can choose "**Link to:** Media" and the result will be that lightbox doesn't work.
**You can choose "**Infinite Loop:** No" and the result will be that all pointer-events are disable except on the first slide.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

<details>
<summary>Click to reveal</summary>

````txt


					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MariaDB Server v10.6.14
	PHP Version: 8.0.29
	PHP Memory Limit: 512M
	PHP Max Input Vars: 250000
	PHP Max Post Size: 512M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.2.2
	Site URL: CONFIDENTIAL
	Home URL: CONFIDENTIAL
	WP Multisite: No
	Max Upload Size: 512 Mo
	Memory limit: 40M
	Max Memory limit: 512M
	Permalink Structure: /%category%/%postname%
	Language: fr-FR
	Timezone: Europe/Paris
	Admin Email: CONFIDENTIAL
	Debug Mode: Active

== Theme ==
	Name: Hello Elementor
	Version: 2.8.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: fr_FR
	User Agent: Mozilla/5.0 (X11; CrOS x86_64 14541.0.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 3.15.2
		Author: Elementor.com


== Expériences d’Elementor ==
	Sortie DOM optimisée: Actif
	Amélioration du chargement des ressources: Actif
	Optimisation du chargement du CSS: Inactif par défaut
	Polices d’icônes « inline »: Inactif par défaut
	Points d’arrêt personnalisés supplémentaires: Actif par défaut
	admin_menu_rearrangement: Inactif par défaut
	Conteneur Flexbox: Actif
	Mettre à niveau la bibliothèque Swiper: Inactif par défaut
	Conteneur grille: Inactif par défaut
	En-tête et pied de page du thème Hello: Inactif par défaut
	Barre supérieure de l’éditeur: Inactif par défaut
	Page d’atterrissage: Actif par défaut
	Éléments imbriqués: Inactif par défaut
	Chargement différé des images d’arrière-plan: Inactif par défaut
	Guide de style global: Inactif par défaut


== Journal ==

CONFIDENTIAL

== Elementor - Compatibility Tag ==

````

</details>

**Comment by nicholaszein** [comment] 2023-08-20 04:36
Hello @titibleh !

Thank you for your submission! 🙏 

### 🔗 🐞 This issue is a Duplicate of #22927

Which is on the same subject. 

For this reason, I'm closing this thread and 🔃 **Merging** it with the original, so we can have all the discussions in one location, and deal with it more efficiently.

Feel free to continue the conversation there. 😉 

### 🔍 Please, in the future, remember to check if there isn't any thread similar to yours already opened. 

Kind regards

**Closed by nicholaszein** 2023-08-20 04:36 UTC
Labels: bug, type/layout, mod*, component/control/url, component/image-carousel
