### ISSUE TITLE
🔗 🚀 Feature Request: Change upload location for Form file uploads (Duplicate of #9181 - Related to #4868)

### ISSUE THREAD

**Issue by tak1885** [elementor/elementor#11674] opened 2020-06-18 17:12 UTC
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
I have a form setup for customers to upload their files (we are a printing company). Currently, we only receive an email with links to the uploaded items. It does not seem possible at the moment to easily locate the uploaded files, other than within the email that is sent. We have multiple team members that all need to have access to the uploaded files in a quick and efficient manner. 

**Describe the solution you'd like**
I would like to be able to change where file uploads are sent to and stored. External cloud storage such as dropbox, google drive, etc. would be the most ideal.

**Describe alternatives you've considered**
I would also be satisfied with a server storage solution that has a clear, easy to get to tab on the main Wordpress menu, separate from the media library. Perhaps a tab in the elementor column for uploads. 

**Additional context**

**Comment by arielk** [comment] 2020-09-01 20:19
Duplicate of https://github.com/elementor/elementor/issues/9181

Thanks for your feedback!

**Closed by arielk** 2020-09-01 20:19 UTC
Labels: request/enhancement, type/developer-api, component/forms/actions, request/integration, type/privacy
