### ISSUE TITLE
✅ 🐞 Bug Report: Beta 3.13 : Can't paste widgets into the 'Drag widget here' area - [ED-10511]

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#22142] opened 2023-04-20 20:51 UTC
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

In the new version, it is mentioned that [this bug](https://github.com/elementor/elementor/issues/21652) has been fixed. We still have this bug in the beta version.

**In fact, if we just paste the widget without the "Drag widget here" area container, it works fine, but if we paste a widget with the container, it still has problems.**

### Steps to reproduce

https://user-images.githubusercontent.com/77163248/233484804-69e3d08e-bf0b-410f-a10c-bb2486f75b4f.mp4

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

<details>
<summary>System Info</summary>
					
== Server Environment ==
	Operating System: WINNT
	Software: Apache/2.4.38 (Win32) OpenSSL/1.1.1a PHP/7.3.2
	MySQL version: mariadb.org binary distribution v5.6.42-84.2
	PHP Version: 7.3.2
	PHP Memory Limit: 128M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 64M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.1.1
	Site URL: http://localhost:85/elementor-beta
	Home URL: http://localhost:85/elementor-beta
	WP Multisite: No
	Max Upload Size: 64 MB
	Memory limit: 40M
	Max Memory limit: 256M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: en-US
	Timezone: Asia/Tehran
	Admin Email: hosein.site.98@gmail.com
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.7.0
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 3.13.0-beta1
		Author: Elementor.com

== Elementor Experiments ==
	Optimized DOM Output: Inactive
	Improved Asset Loading: Inactive
	Improved CSS Loading: Inactive
	Inline Font Icons: Inactive
	Accessibility Improvements: Inactive
	Additional Custom Breakpoints: Inactive
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active
	Upgrade Swiper Library: Inactive
	Grid Container: Active
	Hello Theme Header & Footer: Inactive
	Editor Top Bar: Active
	Landing Pages: Inactive
	Nested Elements: Active
	Lazy Load Background Images: Inactive

== Log ==
	
Log: showing 20 of 332023-03-14 15:49:21 [info] elementor::elementor_updater Started 
2023-03-14 15:49:21 [info] Elementor/Upgrades - _on_each_version Start  
2023-03-14 15:49:21 [info] Elementor/Upgrades - _on_each_version Finished 
2023-03-14 15:49:21 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.12.0-beta1',
  'to' => '3.12.0-beta2',
)]
2023-03-14 15:49:21 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.12.0-beta1',
  'to' => '3.12.0-beta2',
)]
2023-03-26 15:56:40 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.12.0-beta2',
  'to' => '3.12.0-beta3',
)]
2023-03-26 15:56:40 [info] elementor::elementor_updater Started 
2023-03-26 15:56:40 [info] Elementor/Upgrades - _on_each_version Start  
2023-03-26 15:56:40 [info] Elementor/Upgrades - _on_each_version Finished 
2023-03-26 15:56:40 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.12.0-beta2',
  'to' => '3.12.0-beta3',
)]
2023-03-26 15:56:41 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.12.0-beta2',
  'to' => '3.12.0-beta3',
)]
2023-04-19 19:44:51 [info] elementor::elementor_updater Started 
2023-04-19 19:44:51 [info] Elementor/Upgrades - _on_each_version Start  
2023-04-19 19:44:51 [info] Elementor/Upgrades - _on_each_version Finished 
2023-04-19 19:44:51 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.12.0-beta3',
  'to' => '3.13.0-beta1',
)]

PHP: showing 5 of 5PHP: 2023-03-06 19:45:00 [warning X 1][C:\xampp\htdocs\elementor-beta\wp-content\plugins\elementor\app\modules\import-export\processes\export.php::286] Invalid argument supplied for foreach() [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-03-13 12:28:32 [notice X 3][C:\xampp\htdocs\elementor-beta\wp-content\plugins\elementor\app\modules\import-export\module.php::695] Trying to get property 'label' of non-object [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-03-22 00:12:43 [notice X 3][C:\xampp\htdocs\elementor-beta\wp-content\plugins\elementor\core\common\modules\ajax\module.php::175] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-03-24 12:36:52 [notice X 3][C:\xampp\htdocs\elementor-beta\wp-content\plugins\elementor\includes\managers\image.php::36] Undefined index: id [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-03-26 16:05:04 [error X 17][C:\xampp\htdocs\elementor-beta\wp-content\plugins\elementor\includes\widgets\star-rating.php::4] Maximum execution time of 30 seconds exceeded [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 4 of 4JS: 2023-03-08 12:52:29 [error X 1][http://localhost:85/elementor-beta/wp-content/plugins/elementor/assets/js/df16c9d56464dd4f0800.bundle.min.js:2:7826] Cannot read properties of null (reading 'dataset') 
JS: 2023-03-10 16:26:53 [error X 7][http://localhost:85/elementor-beta/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.12.0-beta1:3:901445] Cannot read properties of undefined (reading 'route') 
JS: 2023-03-23 10:08:29 [error X 2][http://localhost:85/elementor-beta/wp-content/plugins/elementor/assets/js/admin.min.js?ver=3.12.0-beta2:2:11095] Cannot set properties of undefined (setting 'value') 
JS: 2023-04-20 15:09:20 [error X 14][http://localhost:85/elementor-beta/wp-content/plugins/elementor/assets/js/container.8c5b7936aedea7c000ad.bundle.min.js:2:4571] Cannot read properties of undefined (reading 'style') 

== Elementor - Compatibility Tag ==

<details>

**Comment by 79ho3ein** [comment] 2023-04-26 10:24
Hi @nicholaszein, Are you aware of this?

**Comment by nicholaszein** [comment] 2023-04-27 14:09
Hello, @79ho3ein! 

Thank you for submitting your issue! 🙏 

We are investigating this further to ensure it is fixed! 💪 

Best regards

**Comment by nicholaszein** [comment] 2023-05-04 17:14
Hey @79ho3ein!

We just released Elementor and Elementor Pro version 3.13-beta4 with a fix for this issue! 🙌 

Please, if possible, test the new version so to see if the issue is fixed for you. The final release is estimated to be released on `May 9, 2023` (next week).

Kind regards

**Comment by nicholaszein** [comment] 2023-05-08 14:30
Hey, @79ho3ein!

We have great news! 🙌 

### 📢 We're happy to announce that the issue you raised was resolved in Elementor **v3.13.0**! 🥳 

✅ Feel free to check it out and update your plugin to the new version!

Cheers 🥂

**Closed by nicholaszein** 2023-05-08 14:30 UTC
Labels: bug, type/ui/ux, component/editor, status/merged, type/workflow, 🚀 shipped, mod*
