### ISSUE TITLE
[PRO] Elementor custom product template can't be set as Elementor full width page template

### ISSUE THREAD

**Issue by cristian-ungureanu** [elementor/elementor#8697] opened 2019-07-26 13:21 UTC
I'm using twentynineteen theme.

When using Elementor Pro, from the Dashboard > Templates add a new Product template and set the template to Elementor Full Width. The settings should be saved but it goes back to default.

**Comment by shilo-ey** [comment] 2019-07-28 07:04
Hi @cristian-ungureanu 

Can't reproduce your issue.

Please contact our support at support @elementor.com for guidance in resolving this issue and mention that you were directed by me and reference this issue.

thanks.

**Closed by shilo-ey** 2019-07-28 07:04 UTC
