### ISSUE TITLE
🔗 🐞 Bug Report: Toggle and Accordion invalid anchor tags without href affect SEO scores negatively on Lighthouse (not crawlable) (Duplicate of #14371)

### ISSUE THREAD

**Issue by Gabz1989** [elementor/elementor#20214] opened 2022-11-01 13:32 UTC
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

I reported this to elementor and it seems that the toggle and the accordion drop your SEO score when you run lighthouse. is there perhaps a workaround without having to install more plugins?

I checked a previous post from 11 months ago but I see no resolution to it.

### Steps to reproduce

add toggle or accordion 
run lighthouse

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: mariadb.org binary distribution v10.4.26
	PHP Version: 8.0.24
	PHP Memory Limit: 96M
	PHP Max Input Vars: 2500
	PHP Max Post Size: 64M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.0.3
	Site URL: https://fangioauto.co.za
	Home URL: https://fangioauto.co.za
	WP Multisite: No
	Max Upload Size: 64 MB
	Memory limit: 40M
	Max Memory limit: 256M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: en-ZA
	Timezone: Africa/Johannesburg
	Admin Email: info@fangioauto.co.za
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.6.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_ZA
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 3.8.0
		Author: Elementor.com

	Elementor Pro
		Version: 3.8.0
		Author: Elementor.com

	Really Simple SSL
		Version: 5.3.5
		Author: Really Simple Plugins

	Site Kit by Google
		Version: 1.86.0
		Author: Google

	Twenty20 Image Before-After
		Version: 1.5.8
		Author: Zayed Baloch

	Yoast SEO
		Version: 19.9
		Author: Team Yoast

	Yoast SEO Premium
		Version: 19.4
		Author: Team Yoast

== Elements Usage ==
	
	container : 2
		container : 5
		heading : 2
		icon-list : 13
	footer : 2
		container : 18
		facebook-page : 2
		heading : 9
		icon-list : 2
		image : 6
		nav-menu : 1
		social-icons : 1
		text-editor : 1
	header : 1
		container : 4
		image : 1
		nav-menu : 1
		search-form : 1
	widget : 0
		button : 1
		form : 1
	wp-post : 4
		container : 3
		divider : 3
		facebook-page : 2
		heading : 14
		image : 1
		post-comments : 1
		search-form : 3
		theme-post-excerpt : 1
	wp-page : 14
		button : 13
		call-to-action : 1
		container : 251
		divider : 7
		form : 10
		google_maps : 2
		heading : 131
		icon-list : 44
		image : 64
		image-box : 24
		image-carousel : 2
		menu-anchor : 9
		nav-menu : 1
		posts : 3
		price-list : 2
		reviews : 1
		search-form : 2
		social-icons : 3
		spacer : 2
		table-of-contents : 4
		text-editor : 78
		toggle : 5
		twenty20 : 1
		video : 1

== Elementor Experiments ==
	Optimised DOM Output: Active by default
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Active by default
	Additional Custom Breakpoints: Active by default
	Import Export Website Kit: Active by default
	Hide native WordPress widgets from search results: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active
	Default to New Theme Builder: Active by default
	Hello Theme Header & Footer: Active by default
	Landing Pages: Active by default
	Colour Sampler: Active by default
	Favorite Widgets: Active by default
	Admin Top Bar: Active by default
	Page Transitions: Active by default
	Notes: Active by default
	Loop: Inactive by default
	Form Submissions: Active by default
	Scroll Snap: Active by default

== Log ==
	
Log: showing 20 of 282022-09-21 13:04:32 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-09-21 13:04:32 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.6',
  'to' => '3.7.7',
)]
2022-09-21 13:04:32 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.6',
  'to' => '3.7.7',
)]
2022-10-03 01:09:37 [info] elementor::elementor_updater Started 
2022-10-03 01:09:37 [info] Elementor/Upgrades - _on_each_version Start  
2022-10-03 01:09:37 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.7',
  'to' => '3.7.8',
)]
2022-10-03 01:09:38 [info] Elementor/Upgrades - _on_each_version Finished 
2022-10-03 01:09:38 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.7',
  'to' => '3.7.8',
)]
2022-10-31 01:05:37 [info] elementor::elementor_updater Started 
2022-10-31 01:05:37 [info] Elementor/Upgrades - _on_each_version Start  
2022-10-31 01:05:38 [info] Elementor/Upgrades - _on_each_version Finished 
2022-10-31 01:05:38 [info] Elementor/Upgrades - _v_3_8_0_fix_php8_image_custom_size Start  
2022-10-31 01:05:38 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.8',
  'to' => '3.8.0',
)]
2022-10-31 01:05:38 [info] Elementor/Upgrades - _v_3_8_0_fix_php8_image_custom_size Finished 
2022-10-31 01:05:38 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.8',
  'to' => '3.8.0',
)]
2022-10-31 09:10:11 [info] elementor-pro::elementor_pro_updater Started 
2022-10-31 09:10:11 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-10-31 09:10:11 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-10-31 09:10:11 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.7',
  'to' => '3.8.0',
)]
2022-10-31 09:10:11 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.7',
  'to' => '3.8.0',
)]

PHP: showing 11 of 11PHP: 2022-09-21 13:04:32 [error X 3][/usr/www/users/fangiummdt/wp-content/plugins/elementor/core/wp-api.php::26] Uncaught Error: Call to undefined function Elementor\Core\get_plugins() in /usr/www/users/fangiummdt/wp-content/plugins/elementor/core/wp-api.php:26
Stack trace:
#0 /usr/www/users/fangiummdt/wp-content/plugins/elementor/modules/compatibility-tag/base-module.php(96): Elementor\Core\Wp_Api-&gt;get_plugins()
#1 /usr/www/users/fangiummdt/wp-content/plugins/elementor/modules/compatibility-tag/base-module.php(58): Elementor\Modules\CompatibilityTag\Base_Module-&gt;get_plugins_with_header()
#2 /usr/www/users/fangiummdt/wp-content/plugins/elementor/modules/compatibility-tag/module.php(57): Elementor\Modules\CompatibilityTag\Base_Module-&gt;get_plugins_to_check()
#3 /usr/www/users/fangiummdt/wp-content/plugins/elementor/modules/compatibility-tag/base-module.php(148): Elementor\Modules\CompatibilityTag\Module-&gt;get_plugins_to_check()
#4 /usr/www/users/fangiummdt/wp-includes/class-wp-hook.php(307): Elementor\Modules\CompatibilityTag\Base_Module-&gt;Elementor\Modules\CompatibilityTag\{closure}(&#039;&#039;)
#5 /usr/www/users/fangiummdt/wp-includes/class-wp-hook.php(331): WP_Hook-&gt;apply_filters(&#039;&#039;, Array)
#6 /usr/www/users/fangiummdt/wp-includes/plugin.php(476): WP_Hook-&gt;do_action(Array)
#7 /usr/www/users/fangiummdt/wp-content/plugins/elementor/modules/system-info/module.php(334): do_action(&#039;elementor/syste...&#039;)
#8 /usr/www/users/fangiummdt/wp-content/plugins/elementor/includes/tracker.php(241): Elementor\Modules\System_Info\Module::get_allowed_reports()
#9 /usr/www/users/fangiummdt/wp-content/plugins/elementor/includes/tracker.php(530): Elementor\Tracker::get_system_reports_data()
#10 /usr/www/users/fangiummdt/wp-content/plugins/elementor/includes/tracker.php(141): Elementor\Tracker::get_tracking_data(false)
#11 /usr/www/users/fangiummdt/wp-includes/class-wp-hook.php(307): Elementor\Tracker::send_tracking_data()
#12 /usr/www/users/fangiummdt/wp-includes/class-wp-hook.php(331): WP_Hook-&gt;apply_filters(&#039;&#039;, Array)
#13 /usr/www/users/fangiummdt/wp-includes/plugin.php(524): WP_Hook-&gt;do_action(Array)
#14 /usr/www/users/fangiummdt/wp-cron.php(138): do_action_ref_array(&#039;elementor/track...&#039;, Array)
#15 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-09-21 15:55:19 [warning X 14][/usr/www/users/fangiummdt/wp-content/plugins/elementor-pro/modules/nav-menu/widgets/nav-menu.php::1446] Trying to access array offset on value of type null [array (
  'trace' => '
#0: /usr/www/users/fangiummdt/wp-content/plugins/elementor-pro/modules/nav-menu/widgets/nav-menu.php(1446): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /usr/www/users/fangiummdt/wp-content/plugins/elementor/includes/base/controls-stack.php(2249): ElementorPro\Modules\NavMenu\Widgets\Nav_Menu -> render()
#2: /usr/www/users/fangiummdt/wp-content/plugins/elementor/includes/base/widget-base.php(609): Elementor\Controls_Stack -> render_by_mode()
#3: /usr/www/users/fangiummdt/wp-content/plugins/elementor/includes/base/widget-base.php(750): Elementor\Widget_Base -> render_content()
#4: /usr/www/users/fangiummdt/wp-content/plugins/elementor/includes/base/element-base.php(447): Elementor\Widget_Base -> print_content()
',
)]
PHP: 2022-09-21 15:55:19 [warning X 14][/usr/www/users/fangiummdt/wp-content/plugins/elementor-pro/modules/nav-menu/widgets/nav-menu.php::1459] Trying to access array offset on value of type null [array (
  'trace' => '
#0: /usr/www/users/fangiummdt/wp-content/plugins/elementor-pro/modules/nav-menu/widgets/nav-menu.php(1459): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /usr/www/users/fangiummdt/wp-content/plugins/elementor/includes/base/controls-stack.php(2249): ElementorPro\Modules\NavMenu\Widgets\Nav_Menu -> render()
#2: /usr/www/users/fangiummdt/wp-content/plugins/elementor/includes/base/widget-base.php(609): Elementor\Controls_Stack -> render_by_mode()
#3: /usr/www/users/fangiummdt/wp-content/plugins/elementor/includes/base/widget-base.php(750): Elementor\Widget_Base -> render_content()
#4: /usr/www/users/fangiummdt/wp-content/plugins/elementor/includes/base/element-base.php(447): Elementor\Widget_Base -> print_content()
',
)]
PHP: 2022-09-21 15:55:19 [warning X 14][/usr/www/users/fangiummdt/wp-content/plugins/elementor-pro/modules/nav-menu/widgets/nav-menu.php::1470] Trying to access array offset on value of type null [array (
  'trace' => '
#0: /usr/www/users/fangiummdt/wp-content/plugins/elementor-pro/modules/nav-menu/widgets/nav-menu.php(1470): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /usr/www/users/fangiummdt/wp-content/plugins/elementor/includes/base/controls-stack.php(2249): ElementorPro\Modules\NavMenu\Widgets\Nav_Menu -> render()
#2: /usr/www/users/fangiummdt/wp-content/plugins/elementor/includes/base/widget-base.php(609): Elementor\Controls_Stack -> render_by_mode()
#3: /usr/www/users/fangiummdt/wp-content/plugins/elementor/includes/base/widget-base.php(750): Elementor\Widget_Base -> render_content()
#4: /usr/www/users/fangiummdt/wp-content/plugins/elementor/includes/base/element-base.php(447): Elementor\Widget_Base -> print_content()
',
)]
PHP: 2022-09-21 15:55:19 [warning X 14][/usr/www/users/fangiummdt/wp-content/plugins/elementor-pro/modules/nav-menu/widgets/nav-menu.php::1483] Trying to access array offset on value of type null [array (
  'trace' => '
#0: /usr/www/users/fangiummdt/wp-content/plugins/elementor-pro/modules/nav-menu/widgets/nav-menu.php(1483): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /usr/www/users/fangiummdt/wp-content/plugins/elementor/includes/base/controls-stack.php(2249): ElementorPro\Modules\NavMenu\Widgets\Nav_Menu -> render()
#2: /usr/www/users/fangiummdt/wp-content/plugins/elementor/includes/base/widget-base.php(609): Elementor\Controls_Stack -> render_by_mode()
#3: /usr/www/users/fangiummdt/wp-content/plugins/elementor/includes/base/widget-base.php(750): Elementor\Widget_Base -> render_content()
#4: /usr/www/users/fangiummdt/wp-content/plugins/elementor/includes/base/element-base.php(447): Elementor\Widget_Base -> print_content()
',
)]
PHP: 2022-09-26 12:45:54 [warning X 6][/usr/www/users/fangiummdt/wp-content/plugins/elementor-pro/modules/nav-menu/widgets/nav-menu.php::1446] Trying to access array offset on value of type null [array (
  'trace' => '
#0: /usr/www/users/fangiummdt/wp-content/plugins/elementor-pro/modules/nav-menu/widgets/nav-menu.php(1446): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /usr/www/users/fangiummdt/wp-content/plugins/elementor/includes/base/controls-stack.php(2249): ElementorPro\Modules\NavMenu\Widgets\Nav_Menu -> render()
#2: /usr/www/users/fangiummdt/wp-content/plugins/elementor/includes/base/widget-base.php(609): Elementor\Controls_Stack -> render_by_mode()
#3: /usr/www/users/fangiummdt/wp-content/plugins/elementor/includes/base/widget-base.php(733): Elementor\Widget_Base -> render_content()
#4: /usr/www/users/fangiummdt/wp-content/plugins/elementor/includes/base/element-base.php(534): Elementor\Widget_Base -> get_raw_data()
',
)]
PHP: 2022-09-26 12:45:54 [warning X 6][/usr/www/users/fangiummdt/wp-content/plugins/elementor-pro/modules/nav-menu/widgets/nav-menu.php::1459] Trying to access array offset on value of type null [array (
  'trace' => '
#0: /usr/www/users/fangiummdt/wp-content/plugins/elementor-pro/modules/nav-menu/widgets/nav-menu.php(1459): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /usr/www/users/fangiummdt/wp-content/plugins/elementor/includes/base/controls-stack.php(2249): ElementorPro\Modules\NavMenu\Widgets\Nav_Menu -> render()
#2: /usr/www/users/fangiummdt/wp-content/plugins/elementor/includes/base/widget-base.php(609): Elementor\Controls_Stack -> render_by_mode()
#3: /usr/www/users/fangiummdt/wp-content/plugins/elementor/includes/base/widget-base.php(733): Elementor\Widget_Base -> render_content()
#4: /usr/www/users/fangiummdt/wp-content/plugins/elementor/includes/base/element-base.php(534): Elementor\Widget_Base -> get_raw_data()
',
)]
PHP: 2022-09-26 12:45:54 [warning X 6][/usr/www/users/fangiummdt/wp-content/plugins/elementor-pro/modules/nav-menu/widgets/nav-menu.php::1470] Trying to access array offset on value of type null [array (
  'trace' => '
#0: /usr/www/users/fangiummdt/wp-content/plugins/elementor-pro/modules/nav-menu/widgets/nav-menu.php(1470): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /usr/www/users/fangiummdt/wp-content/plugins/elementor/includes/base/controls-stack.php(2249): ElementorPro\Modules\NavMenu\Widgets\Nav_Menu -> render()
#2: /usr/www/users/fangiummdt/wp-content/plugins/elementor/includes/base/widget-base.php(609): Elementor\Controls_Stack -> render_by_mode()
#3: /usr/www/users/fangiummdt/wp-content/plugins/elementor/includes/base/widget-base.php(733): Elementor\Widget_Base -> render_content()
#4: /usr/www/users/fangiummdt/wp-content/plugins/elementor/includes/base/element-base.php(534): Elementor\Widget_Base -> get_raw_data()
',
)]
PHP: 2022-09-26 12:45:54 [warning X 6][/usr/www/users/fangiummdt/wp-content/plugins/elementor-pro/modules/nav-menu/widgets/nav-menu.php::1483] Trying to access array offset on value of type null [array (
  'trace' => '
#0: /usr/www/users/fangiummdt/wp-content/plugins/elementor-pro/modules/nav-menu/widgets/nav-menu.php(1483): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /usr/www/users/fangiummdt/wp-content/plugins/elementor/includes/base/controls-stack.php(2249): ElementorPro\Modules\NavMenu\Widgets\Nav_Menu -> render()
#2: /usr/www/users/fangiummdt/wp-content/plugins/elementor/includes/base/widget-base.php(609): Elementor\Controls_Stack -> render_by_mode()
#3: /usr/www/users/fangiummdt/wp-content/plugins/elementor/includes/base/widget-base.php(733): Elementor\Widget_Base -> render_content()
#4: /usr/www/users/fangiummdt/wp-content/plugins/elementor/includes/base/element-base.php(534): Elementor\Widget_Base -> get_raw_data()
',
)]
PHP: 2022-09-27 14:05:24 [warning X 2][/usr/www/users/fangiummdt/wp-content/plugins/elementor/core/editor/editor.php::121] Cannot modify header information - headers already sent by (output started at /usr/www/users/fangiummdt/wp-includes/functions.php:6633) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-10-07 08:04:23 [warning X 4][/usr/www/users/fangiummdt/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined array key &quot;data&quot; [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 3 of 3JS: 2022-09-23 11:32:28 [error X 1][https://fangioauto.co.za/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.7.7:3:767341] Cannot read properties of undefined (reading \&#039;toLowerCase\&#039;) 
JS: 2022-09-23 11:43:53 [error X 3][https://fangioauto.co.za/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.7.7:3:767848] Cannot read properties of undefined (reading \&#039;localized\&#039;) 
JS: 2022-09-23 11:56:47 [error X 15][https://fangioauto.co.za/wp-content/plugins/elementor/assets/lib/nouislider/nouislider.min.js?ver=13.0.0:2:4604] noUiSlider (13.0.0): \&#039;start\&#039; option is incorrect. 

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatibility not specified

== Elementor Pro - Compatibility Tag ==

**Comment by nicholaszein** [comment] 2022-11-01 18:37
Hello @Gabz1989! 

Thank you for submitting your issue! 🙏 

Please allow us some time to investigate it, and get back to you with our findings. 🧐 

Best regards

**Comment by nicholaszein** [comment] 2022-11-09 21:59
Hello @Gabz1989!

Thank you for your submission! 🙏 

### 🔗 This issue is a Duplicate of #14371

Which is on the same subject. 

For this reason, I'm closing this issue and 🔃 **Merging** it with the original, so we can have all the discussions in one location, and deal with it more efficiently.

Feel free to continue the conversation there. 😉 

### ✔️ Please, in the future, remember to check if there isn't an issue similar to yours already opened. 

Best regards,

Nick

**Closed by nicholaszein** 2022-11-09 21:59 UTC
Labels: bug, type/seo, component/accordion

**Comment by nicholaszein** [comment] 2023-06-19 15:32
Hello!

We have great news! 🙌 

### 📢 We're happy to announce that the issue you raised was resolved in Elementor v3.14.0! 🥳 

Now Accordions are completely a11y compatible! 💪 

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
