### ISSUE TITLE
No Sidebar for Archives Template (Categories)

### ISSUE THREAD

**Issue by Megadeth02** [elementor/elementor#10744] opened 2020-03-04 18:49 UTC
I've been struggling to add a Sidebar to my Categories Template.
I use GeneratePress with Elementor Pro, my theme's Sidebar is indeed showing on every pages, posts but not on my Archives. 
So I tried using Elementor Anywhere. It worked partially, only showing my theme's Sidebar on the template in the Builder but its still hidden on the Live website. I also used the Default template, Full-width template inside Elementor Builder, still not working.

I really don't know what to do as the issue seems to happen with all themes.
![2020-03-04_13h32_21](https://user-images.githubusercontent.com/45047163/75912207-d394de00-5e1e-11ea-97eb-e1527636c771.png)
![2020-03-04_13h34_27](https://user-images.githubusercontent.com/45047163/75912226-dabbec00-5e1e-11ea-873a-0b5c87dabbc3.png)

**Comment by zeinnicholas** [comment] 2020-03-06 17:21
This is a non issue. It's simple to fix. Elementor comes with a sidebar widget. Just choose a section with more than one column and add the sidebar widget to it. The sidebar needs to have active widgets inside. You can use the Elementor Fullwidth template to add your custom sidebar.

If the problem is with the Sidebar widget, then just drag and drop your desired widgets into a columns. Elementor also renders any native WP widgets. 

For more information please make sure you consult the documentation before posting questions here. The appropriate place ask for help is either the support service, or by asking for help in the Elementor Community in Facebook.

Documentation: https://docs.elementor.com
Sidebar Widget: https://docs.elementor.com/article/434-sidebar-widget
Native Widgets: https://docs.elementor.com/article/129-can-i-use-other-plugin-widgets-inside-elementor

Official Support: https://elementor.com/support/
Facebook Community: https://www.facebook.com/groups/Elementors/

Please close this thread if you found the solution to your issue.

**Comment by shilo-ey** [comment] 2020-07-26 12:53
Thanks,

Please create GitHub issues only for bugs reports and feature requests. 

- If you have questions or need general support, as @zeinnicholas mentioned please try:

* [Elementor Community](https://www.facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org 
* [Elementor Developers docs](https://developers.elementor.com/)

If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email for details.


thanks.

**Closed by shilo-ey** 2020-07-26 12:53 UTC
