### ISSUE TITLE
⛔ 🚀 Allow to select the Image Resolution for each device in responsive mode in the Media Carousel widget

### ISSUE THREAD

**Issue by vladarte** [elementor/elementor#11368] opened 2020-05-14 12:08 UTC
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

## Description

Image size in Media carousel is static for all devices. There is no point of serving full sized image on mobile devices. Can you please make this setting dynamic, should be pretty easy to implement ;)

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

[Moderation: Information is missing]

**Comment by nicholaszein** [comment] 2024-08-12 04:13
Hello @vladarte!

Thank you for submitting your issue, and apologies for the delay in the response! 🙏 

As we move to separate Feature Requests from Bug Reports, and organize our GitHub repository, we found out that the issue you're reporting is not a bug, and is more of a Feature Request. The widget in question was not created with the intent to allow to select different file sizes for each breakpoint. We consider a bug when an existing feature is not working as intended, or when there is an error in the code, as opposed to what is expected from said feature.

Therefore, if you think this should be an Elementor feature, please submit a new [🚀 Feature Request](https://github.com/orgs/elementor/discussions/new?category=feature-request), and we will consider it in the future if there is enough demand (votes) from other users.

Since you posted this a long time ago as a bug, we cannot migrate it to feature requests, since the required information is not present. For this reason, I'm closing this issue. I hope you can understand.

Kind regards

**Closed by nicholaszein** 2024-08-12 04:13 UTC
Labels: request/enhancement, type/responsive, product/pro, component/swiper, type/layout, solved-by/nested, mod*, widget/media-carousel*, widget/settings
