### ISSUE TITLE
Background Images Not Displayed in Elementor v3.21.0

### ISSUE THREAD

**Issue by airman5573** [elementor/elementor#25771] opened 2024-04-18 03:58 UTC
### Prerequisites

- [X] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [ ] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description
1. I upgraded to Elementor 3.21.0.
2. After the upgrade, background images were not displayed.
3. I downgraded to Elementor 3.20.4.
4. I activated the 'Lazy Load Background Images' option. (Note: If this option is inactive, background images will not be shown.)
5. After activating the 'Lazy Load Background Images' option, the background images are now visible.

Here is prove video (5m)
https://drive.google.com/file/d/1uIbS1b_FRkZSNxF6R0FxaRkdP7J8cm_i/view?usp=sharing

### Steps to reproduce
1. After upgrading from Elementor 3.20.4 to 3.21.0, background images were no longer displayed.
2. To resolve the issue, I downgraded to Elementor 3.20.4 and activated the 'Lazy Load Background Images' option. With this option active, the background images were visible again.

### Expected behavior
I hope that in future updates, Elementor will resolve the issue with background images not being displayed in the latest version. It would be great to have the background images working properly without the need to downgrade or rely on the 'Lazy Load Background Images' option.

### Isolating the problem

- [ ] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [X] This bug happens with the Hello Elementor theme active.
- [X] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

<details>
<summary>Click to reveal</summary>

````txt
== Server Environment ==
	Operating System: Linux
	Software: nginx/1.19.3
	MySQL version: Please upgrade to 8.0 or opt-in to the paid RDS Extended Support service before 5.7 reaches end of standard support on 29 February, 2024: https://a.co/hQqiIn0 v5.7.44
	PHP Version: 7.4.16
	PHP Memory Limit: 1024M
	PHP Max Input Vars: 3000
	PHP Max Post Size: 50M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.5.2
	Site URL: https://oico.shoplic.site
	Home URL: https://oico.shoplic.site
	WP Multisite: No
	Max Upload Size: 50 MB
	Memory limit: 512M
	Max Memory limit: 1024M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: en_US
	Timezone: Asia/Seoul
	Debug Mode: Active

== Theme ==
	Name: Hello Elementor Child
	Version: 2.0.0
	Author: Elementor Team
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 3.0.1
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: en-US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36

== Active Plugins ==
	Advanced Custom Fields PRO
		Version: 6.2.9
		Author: WP Engine

	Duplicate Page
		Version: 4.5.3
		Author: mndpsingh287

	Duplicator Pro
		Version: 4.5.16.4
		Author: Duplicator

	Elementor
		Version: 3.20.4
		Author: Elementor.com

	Elementor Pro
		Version: 3.20.2
		Author: Elementor.com

	Essential Addons for Elementor
		Version: 5.9.15
		Author: WPDeveloper

	Essential Addons for Elementor - Pro
		Version: 5.8.11
		Author: WPDeveloper

	Essential Blocks
		Version: 4.5.9
		Author: WPDeveloper

	KBoard : 게시판
		Version: 6.4
		Author: 코스모스팜 - Cosmosfarm

	KBoard : 댓글
		Version: 5.3
		Author: 코스모스팜 - Cosmosfarm

	User Menus
		Version: 1.3.2
		Author: Code Atlantic

	User Switching
		Version: 1.7.3
		Author: John Blackbourn & contributors

	Wordfence Security
		Version: 7.11.5
		Author: Wordfence

	WP STAGING WordPress Backup Plugin - Backup Duplicator &amp; Migration
		Version: 3.4.3
		Author: WP-STAGING, WPStagingBackup

	Yoast SEO
		Version: 22.5
		Author: Team Yoast

	옴부즈만 커스텀 플러그인
		Version: 0.0.0
		Author: 쇼플릭


== Must-Use Plugins ==
	WP STAGING Optimizer
		Version: 1.5.6
		Author: WP STAGING

	쇼플릭 코어
		Version: 0.1.13
		Author: 쇼플릭


== Elements Usage ==
	
	archive : 5
		breadcrumbs : 5
		container : 28
		heading : 13
		loop-grid : 5
		search-form : 5
		template : 5
	container : 9
		container : 25
		eael-advanced-menu : 5
		eael-logo-carousel : 1
		heading : 8
		icon : 3
		icon-list : 3
		shortcode : 2
		spacer : 6
		template : 5
		text-editor : 4
	footer : 1
		button : 3
		container : 3
		image : 1
		spacer : 1
		text-editor : 1
	header : 1
		container : 9
		icon : 1
		nav-menu : 2
		search-form : 1
		theme-site-logo : 2
	page : 5
		breadcrumbs : 4
		button : 1
		container : 62
		eael-advanced-menu : 6
		heading : 17
		icon : 12
		icon-list : 12
		image : 1
		image-box : 4
		posts : 1
		shortcode : 1
		spacer : 16
		text-editor : 9
	popup : 1
		container : 3
		heading : 1
		nav-menu : 2
	wp-page : 30
		breadcrumbs : 25
		button : 14
		container : 420
		divider : 7
		eael-adv-accordion : 1
		eael-advanced-menu : 12
		eael-logo-carousel : 4
		eael-post-carousel : 1
		google_maps : 1
		heading : 305
		icon : 48
		icon-box : 3
		icon-list : 38
		image : 38
		image-box : 14
		loop-carousel : 2
		loop-grid : 2
		nav-menu : 5
		nested-tabs : 2
		posts : 2
		shortcode : 18
		spacer : 98
		template : 12
		text-editor : 61
		video : 2
	single-post : 4
		breadcrumbs : 4
		button : 4
		container : 34
		heading : 20
		image : 1
		post-navigation : 4
		shortcode : 3
		template : 4
		theme-post-content : 4
		theme-post-title : 4
	search-results : 2
		container : 5
		eael-advanced-menu : 1
		heading : 1
		loop-grid : 1
		search-form : 1
		shortcode : 1
		spacer : 1
		template : 1
	loop-item : 9
		container : 15
		icon : 2
		image : 1
		post-info : 9
		theme-post-excerpt : 2
		theme-post-featured-image : 2
		theme-post-title : 9


== Settings ==
	
	cpt_support: post, page, notice, activity_result
	allow_tracking: yes
	unfiltered_files_upload: 1
	font_display: swap


== Features ==
	Custom Fonts: 0
	Custom Icons: 0

== Integrations ==
	


== Elementor Experiments ==
	Improved Asset Loading: Active
	Improved CSS Loading: Active
	Inline Font Icons: Active
	Additional Custom Breakpoints: Active
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active
	Upgrade Swiper Library: Active
	Grid Container: Active
	Default to New Theme Builder: Active
	Hello Theme Header &amp; Footer: Active
	Editor Top Bar: Active
	Optimized Gutenberg Loading: Active
	Build with AI: Active
	Landing Pages: Active
	Nested Elements: Active
	Lazy Load Background Images: Active
	Optimize Image Loading: Active
	Pages Panel: Inactive by default
	Notes: Active
	Display Conditions: Active
	Form Submissions: Active
	Menu: Active
	Taxonomy Filter: Active


== Log ==
	
Log: showing 20 of 322024-04-11 10:40:10 [info] Elementor data updater process has been queued. [array (
  'plugin' => '엘리멘터',
  'from' => '3.20.3',
  'to' => '3.20.4',
)]
2024-04-11 10:40:10 [info] elementor::elementor_updater Started 
2024-04-11 10:40:10 [info] 엘리멘터/Upgrades - _on_each_version Start  
2024-04-11 10:40:11 [info] 엘리멘터/Upgrades - _on_each_version Finished 
2024-04-11 10:40:11 [info] Elementor data updater process has been completed. [array (
  'plugin' => '엘리멘터',
  'from' => '3.20.3',
  'to' => '3.20.4',
)]
2024-04-14 11:45:34 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.20.2',
  'to' => '3.20.3',
)]
2024-04-14 11:45:34 [info] elementor-pro::elementor_pro_updater Started 
2024-04-14 11:45:34 [info] Elementor Pro/Upgrades - _on_each_version Start  
2024-04-14 11:45:34 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2024-04-14 11:45:34 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.20.2',
  'to' => '3.20.3',
)]
2024-04-14 11:45:35 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.20.2',
  'to' => '3.20.3',
)]
2024-04-16 11:06:57 [info] elementor::elementor_updater Started 
2024-04-16 11:06:58 [info] 엘리멘터/Upgrades - _on_each_version Start  
2024-04-16 11:06:58 [info] Elementor data updater process has been queued. [array (
  'plugin' => '엘리멘터',
  'from' => '3.20.4',
  'to' => '3.21.0',
)]
2024-04-16 11:06:59 [info] 엘리멘터/Upgrades - _on_each_version Finished 
2024-04-16 11:06:59 [info] Elementor data updater process has been completed. [array (
  'plugin' => '엘리멘터',
  'from' => '3.20.4',
  'to' => '3.21.0',
)]
2024-04-16 20:31:38 [info] elementor-pro::elementor_pro_updater Started 
2024-04-16 20:31:38 [info] Elementor Pro/Upgrades - _on_each_version Start  
2024-04-16 20:31:38 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2024-04-16 20:31:38 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.20.3',
  'to' => '3.21.0',
)]

JS: showing 5 of 5JS: 2024-03-28 04:47:12 [error X 30][../wp-content/plugins/elementor/assets/js/ai.min.js?ver=3.20.3:3:7564] ReactUtils is not defined 
JS: 2024-04-04 03:52:15 [error X 82][../wp-content/uploads/essential-addons-elementor/eael.js?ver=1711981307:28:486618] undefined is not an object (evaluating &#039;m.eael_particle_opacity.size&#039;) 
JS: 2024-04-04 03:52:27 [error X 1][../wp-content/plugins/elementor/assets/js/ai.min.js?ver=3.20.3:3:7574] Can&#039;t find variable: ReactUtils 
JS: 2024-04-09 05:54:37 [error X 122][../wp-content/uploads/essential-addons-elementor/eael.js?ver=1712235991:28:486585] m.eael_particle_opacity is undefined 
JS: 2024-04-11 05:30:45 [error X 918][../wp-content/uploads/essential-addons-elementor/eael.js?ver=1712234621:28:486765] Cannot read properties of undefined (reading &#039;size&#039;) 

PHP: showing 6 of 6PHP: 2024-04-16 20:28:46 [error X 1][../wp-content/plugins/elementor-pro/elementor-pro.php::68] require(): Failed opening required &#039;../wp-content/plugins/elementor-pro/plugin.php&#039; (include_path=&#039;../wp-content/plugins/kboard/htmlpurifier/standalone:.:/usr/local/lib/php&#039;) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-04-17 15:58:20 [notice X 7][../wp-content/plugins/elementor/includes/managers/image.php::113] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-04-17 16:05:29 [error X 1][../wp-content/plugins/elementor-pro/plugin.php::500] Uncaught Error: Class &#039;ElementorPro\Core\Preview\Preview&#039; not found in ../wp-content/plugins/elementor-pro/plugin.php:500
Stack trace:
#0 ../wp-content/plugins/elementor-pro/plugin.php(139): ElementorPro\Plugin-&gt;__construct()
#1 ../wp-content/plugins/elementor-pro/plugin.php(542): ElementorPro\Plugin::instance()
#2 ../wp-content/plugins/elementor-pro/elementor-pro.php(68): require(&#039;/data/sites/oic...&#039;)
#3 ../wp-includes/class-wp-hook.php(324): elementor_pro_load_plugin(&#039;&#039;)
#4 ../wp-includes/class-wp-hook.php(348): WP_Hook-&gt;apply_filters(NULL, Array)
#5 ../wp-includes/plugin.php(517): WP_Hook-&gt;do_action(Array)
#6 ../wp-settings.php(550): do_action(&#039;plugins_loaded&#039;)
#7 ../wp-config.php(106): require_once(&#039;/data/sites/oic...&#039;)
#8 ../wp-load.php(50): require_once(&#039;/data/sites/oic...&#039;)
#9 /data/sites/oico/pu [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-04-17 16:05:30 [error X 1][../wp-content/plugins/elementor/data/manager.php::88] Uncaught Error: Class &#039;ElementorPro\Core\App\Modules\SiteEditor\Data\Controller&#039; not found in ../wp-content/plugins/elementor/data/manager.php:88
Stack trace:
#0 ../wp-content/plugins/elementor-pro/core/app/modules/site-editor/module.php(194): Elementor\Data\Manager-&gt;register_controller(&#039;ElementorPro\\Co...&#039;)
#1 ../wp-content/plugins/elementor-pro/core/app/app.php(86): ElementorPro\Core\App\Modules\SiteEditor\Module-&gt;__construct()
#2 ../wp-content/plugins/elementor-pro/plugin.php(502): ElementorPro\Core\App\App-&gt;__construct()
#3 ../wp-content/plugins/elementor-pro/plugin.php(139): ElementorPro\Plugin-&gt;__construct()
#4 ../wp-content/plugins/elementor-pro/plugin.php(542): ElementorPro\Plugin::instance()
#5 ../wp-content/plugins/elementor-pro/elementor-pro.php(68): require(&#039;/data/sites/oic...&#039;)
#6 ../wp-includes/class-wp-hook.php(324): elementor_p [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-04-17 18:25:42 [notice X 9][../wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php::150] Undefined index: condition_type [array (
  'trace' => '
#0: ../wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(150): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_template_json_item()
#2: ../wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(120): class type array_map()
#3: ../wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(59): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_templates_json()
#4: ../wp-content/plugins/elementor/data/base/endpoint.php(158): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> get_items()
',
)]
PHP: 2024-04-18 11:42:18 [error X 1][../wp-content/plugins/elementor-pro/elementor-pro.php::45] Cannot redeclare elementor_pro_load_plugin() (previously declared in ../wp-content/plugins/_elementor-pro/elementor-pro.php:46) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]



== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatibility not specified
	Essential Addons for Elementor: Compatibility not specified
	Essential Addons for Elementor - Pro: Compatibility not specified

== Elementor Pro - Compatibility Tag ==

````

</details>

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by m1ga** [comment] 2024-04-18 08:05
I had the same afte the update. Since they've renamed the background variable name you have to click and run the "database updater" when you login after the update. That will fix the variable name and the background image will load again.

**Comment by airman5573** [comment] 2024-04-18 08:51
@m1ga Thanks for your advice.
But I cannot find the "database updater" at admin page.
Is there anything that I can in this situation ?

**Comment by m1ga** [comment] 2024-04-18 08:57
![elementor-data-error](https://github.com/elementor/elementor/assets/4334997/2ee2f244-1162-4633-a4c3-53b0f9e837eb)
this one. I think if it is only in some places you can remove the background image and assign it again. That should also then use the new (shorter) variable name.

In my case I got the button when I logged into the backend, clicked it and then it was visible again.

To verify if it is the same issue:
Inspect the element that has the background image in the frontend and check the styles where it assigns the background-image. For me it was using `var(---something---)` (didn't make a screenshot, sorry) and the variable with the image below that line was using `--somethingElse--` as a name.

**Comment by airman5573** [comment] 2024-04-18 09:20
<img width="1185" alt="image" src="https://github.com/elementor/elementor/assets/68623798/d9fb32b6-47dc-4f19-886f-894907c996fb">
<img width="1389" alt="image" src="https://github.com/elementor/elementor/assets/68623798/df0e7986-e93b-4ddb-9f54-f6e16da6e53b">
Thanks, I think it might be a slightly different issue because the images are showing up fine in the Elementor Builder, but they're not appearing on the front end. The DOM is even empty, haha.

**Comment by m1ga** [comment] 2024-04-18 09:32
Ah, you've made the container a link. I think does show a warning in the backend when you do that that it can cause issues. I think that is what you are seeing here. Then ignore my comments from before :)

**Comment by jonathansoltero** [comment] 2024-04-18 16:06
+1 

I noticed the same.

**Comment by nicholaszein** [comment] 2024-04-18 18:58
Hello @airman5573,

Thank you for reaching out! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
The **`Lazy Load Background Images`** experimental feature was, until this version (3.21) **<ins>Inactive by Default on all websites</ins>**, and it required to be activated to be used both in the old implementation and now in the new one. This is important to note, because the old version wouldn't appear on your website unless you had it active by default, and this plays a big role and identifying the root cause of your issue.

That being said, in this version (3.21), this experimental feature was optimized, and now is more reliable and lighter. It also was promoted to **`Beta`** status, and is now **active by default <ins>ONLY on new installations</ins>**. Your site does not fit this scenario.

We also did some testing to try to reproduce your issue, and created a page with different background images to check if they were not updating correctly as you reported. And in our investigation we concluded the issue you're experiencing is **<ins>NOT A BUG in Elementor</ins>** as you can see in the video below, the changes apply correctly after the update, and the images are loading just fine.


https://github.com/elementor/elementor/assets/113993460/ce564bb6-7e22-434b-865b-9892360946c3

_The video is sped-up to 1.5x its original playback speed_

Moreover, we see you have some additional plugins and Elementor Add-ons. One plugin in particular is the _**Kboard**_ plugin. In your **Elementor System Info** there is an error caused by that plugin related to some sort of html purifier. If this is some type of sanitization process, it might be the root of your issue.

But here is our final prognostic:

It is likely a problem with your server. Could be related to Cron Jobs not running properly, or Object Cache. This prevented the CSS files from being regenerated correctly after the update, which happens when you run the **Elementor Data Updater** like I did in my video example. This process is crucial to ensure the changes made to Elementor are reflected throughout your website. If a plugin conflict (_**Kboard**_), inefficient cron jobs, lack of server resources, or Object Cache prevent the process from regenerating the CSS, this could affect how your content is displayed in the front-end. By default, as you see in the video, it does regenerate the CSS and shows different properties for background images.

Finally, in the video shared with, the images load just fine after the update, and everything is working correctly with the new lazy load method.

### ✅ What you can do to solve your issue:
Luckily there is a really simple way of solving this issue. 

You just need to **<ins>Regenerate CSS & Data.</ins>**

Go to your WordPress **`Dashboard`** > **`Elementor`** > **`Tools`** > **`General`** page and click on the button to **`Regenerate CSS & Data`**. This should force your website to recreate the CSS files that are holding the old lazy load method.

Once you do that, you're good to go!

This applies to you @jonathansoltero as well! 😉 

### 👍 For now, that's all we can help with. 

### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for support.

# Before submitting a bug report, make sure you have troubleshooted your issue!

❔ If you have questions, or need guidance, help, or general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) The main Facebook group where all kinds of users come together to help each other.
- [Elementor Academy](https://elementor.com/academy) Learn everything you need to know about using Elementor.
- [Elementor Developers Documentation](https://developers.elementor.com/) Learn everything about our Developer-API.
- [Free Support Forum](https://wordpress.org/support/plugin/elementor) Get help on WordPress.org.

💎 If you have an active [Elementor Pro](https://elementor.com/pro) license you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Kind regards

**Closed by nicholaszein** 2024-04-18 18:58 UTC
Labels: type/styles, type/experiment, control/group/background, mod/e*
