### ISSUE TITLE
🚀 Feature Request: Make text solid and gradient color control

### ISSUE THREAD

**Issue by thejaydip** [elementor/elementor#18534] opened 2022-04-29 05:46 UTC
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

I can't set gradient color for the heading or some other text, it would be nice to have both solid and gradient in the heading or text related control.

### Describe the solution you'd like

It would be nice to have both solid and gradient color options in text color control where we can choose ( solid or gradient ) the color of the text.

![gradient-text](https://user-images.githubusercontent.com/46511743/165890707-802af1d5-9c81-4940-8161-3541acf31885.png)

**Comment by arielk** [comment] 2022-09-12 08:58
Duplicate of: https://github.com/elementor/elementor/issues/4676

**Closed by arielk** 2022-09-12 08:58 UTC
Labels: request/feature
