### ISSUE TITLE
✅ 🔗 🐞 Bug Report: Star Rating widget shows wrong value on the frontend if the value has decimal points (Duplicate of #18169)

### ISSUE THREAD

**Issue by bytepack** [elementor/elementor#23809] opened 2023-09-15 06:25 UTC
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Star Rating widget shows a wrong result on frontend (It's correct in element editor) when rating has 2 decimals.

### Steps to reproduce

1) In Star Rating widget type a number in Rating with 2 decimals or get it dynamically 
2) Go to frontend to see the wrong result

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

<details>
<summary>Click to reveal</summary>

````txt



== Server Environment ==
	Operating System: Linux
	Software: LiteSpeed
	MySQL version: MariaDB Server v10.5.21
	PHP Version: 8.1.21
	PHP Memory Limit: 512M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 128M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.3.1
	Site URL: https://webrock.ir/bookstore1
	Home URL: https://webrock.ir/bookstore1
	WP Multisite: No
	Max Upload Size: 128 MB
	Memory limit: 256M
	Max Memory limit: 512M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor Child
	Version: 2.0.0
	Author: Elementor Team
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.8.1
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: fa_IR
	User Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36

== Active Plugins ==
	Admin category search
		Version: 1.3
		Author: Atilla Ordog

	Classic Editor
		Version: 1.6.3
		Author: WordPress Contributors

	Elementor
		Version: 3.16.2
		Author: Elementor.com

	Elementor Pro
		Version: 3.16.0
		Author: Elementor.com

	JetEngine
		Version: 3.2.4
		Author: Crocoblock

	JetSearch
		Version: 3.1.1
		Author: Crocoblock

	JetSmartFilters
		Version: 3.2.0
		Author: Crocoblock

	Loco Translate
		Version: 2.6.6
		Author: Tim Whitlock

	WooCommerce
		Version: 8.1.0
		Author: Automattic

	WPvivid Backup Plugin
		Version: 0.9.90
		Author: WPvivid Team

	Yoast SEO
		Version: 21.0
		Author: Team Yoast


== Features ==
	Custom Fonts: 1
	Custom Icons: 0

== Integrations ==
	
	woocommerce: Active


== Elementor Experiments ==
	Optimized DOM Output: Active by default
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Inactive by default
	Additional Custom Breakpoints: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active
	Upgrade Swiper Library: Active by default
	Grid Container: Inactive by default
	Default to New Theme Builder: Active by default
	Hello Theme Header &amp; Footer: Active by default
	Editor Top Bar: Inactive by default
	Landing Pages: Active by default
	Nested Elements: Inactive by default
	Lazy Load Background Images: Inactive by default
	Global Style Guide: Active by default
	Page Transitions: Active by default
	Notes: Active by default
	Form Submissions: Active by default
	Scroll Snap: Active by default
	Menu: Inactive by default
	Taxonomy Filter: Inactive by default


== Log ==
	
PHP: showing 8 of 8PHP: 2023-08-26 10:53:25 [warning X 20][../wp-content/plugins/elementor/core/common/modules/ajax/module.php::175] Undefined array key &quot;data&quot; [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-08-26 19:59:24 [notice X 1735][../wp-content/plugins/elementor-pro/modules/custom-css/module.php::76] trim(): Passing null to parameter #1 ($string) of type string is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-08-27 16:45:04 [warning X 2][../wp-content/plugins/elementor-pro/modules/assets-manager/asset-types/fonts-manager.php::252] Undefined array key &quot;editor_post_id&quot; [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-08-29 16:50:01 [warning X 12][../wp-content/plugins/elementor/core/logger/items/js.php::17] Undefined array key &quot;url&quot; [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-08-30 10:44:47 [warning X 3][../wp-content/plugins/elementor-pro/modules/woocommerce/widgets/cart.php::2377] Undefined array key &quot;section_coupon_display&quot; [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-08-30 15:56:42 [notice X 1][../wp-content/plugins/elementor-pro/modules/woocommerce/module.php::607] parse_str(): Passing null to parameter #1 ($string) of type string is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-09-01 13:31:15 [warning X 1][../wp-content/plugins/elementor-pro/modules/woocommerce/tags/product-image.php::54] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-09-02 08:55:19 [warning X 2][../wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php::150] Undefined array key &quot;condition_type&quot; [array (
  'trace' => '
#0: ../wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(150): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_template_json_item()
#2: ../wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(120): class type array_map()
#3: ../wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(59): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_templates_json()
#4: ../wp-content/plugins/elementor/data/base/endpoint.php(158): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> get_items()
',
)]

JS: showing 17 of 17JS: 2023-08-26 10:54:55 [error X 5][https://webrock.ir/bookstore1/wp-includes/js/jquery/jquery.min.js?ver=3.7.0:2:28722] Cannot read properties of undefined (reading &#039;value&#039;) 
JS: 2023-08-27 18:06:22 [error X 4][https://webrock.ir/bookstore1/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.15.3:3:54034] Cannot read properties of undefined (reading &#039;activate&#039;) 
JS: 2023-08-27 19:00:28 [error X 1][https://webrock.ir/bookstore1/wp-includes/js/dist/vendor/react-dom.min.js?ver=18.2.0:10:23755] Cannot read properties of null (reading &#039;getOptions&#039;) 
JS: 2023-08-27 20:07:30 [error X 2][https://webrock.ir/bookstore1/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.15.3:3:604162] Cannot read properties of null (reading &#039;id&#039;) 
JS: 2023-08-28 21:31:08 [error X 18][https://webrock.ir/bookstore1/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.15.3:3:803140] Cannot read properties of undefined (reading &#039;localized&#039;) 
JS: 2023-08-29 16:43:29 [error X 1][https://webrock.ir/bookstore1/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: &quot;view4183&quot;) has already been destroyed and cannot be used. 
JS: 2023-08-29 16:49:15 [error X 7284][https://webrock.ir/bookstore1/wp-content/plugins/elementor/assets/lib/pickr/pickr.min.js?ver=1.5.0:2:14799] Cannot read properties of null (reading &#039;clone&#039;) 
JS: 2023-08-29 16:49:21 [error X 157][https://webrock.ir/bookstore1/wp-content/plugins/elementor/assets/lib/pickr/pickr.min.js?ver=1.5.0:2:19552] Cannot read properties of null (reading &#039;changestop&#039;) 
JS: 2023-08-29 17:22:55 [error X 3][https://webrock.ir/bookstore1/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.15.3:3:802633] Cannot read properties of undefined (reading &#039;toLowerCase&#039;) 
JS: 2023-09-02 08:48:33 [error X 1][https://webrock.ir/bookstore1/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: &quot;view2067&quot;) has already been destroyed and cannot be used. 
JS: 2023-09-02 17:28:44 [error X 1][https://webrock.ir/bookstore1/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: &quot;view41176&quot;) has already been destroyed and cannot be used. 
JS: 2023-09-02 17:29:39 [error X 1][https://webrock.ir/bookstore1/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: &quot;view1565&quot;) has already been destroyed and cannot be used. 
JS: 2023-09-03 12:01:38 [error X 1][https://webrock.ir/bookstore1/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: &quot;view7376&quot;) has already been destroyed and cannot be used. 
JS: 2023-09-03 17:45:47 [error X 1][https://webrock.ir/bookstore1/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: &quot;view13150&quot;) has already been destroyed and cannot be used. 
JS: 2023-09-10 03:19:01 [error X 1][https://webrock.ir/bookstore1/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: &quot;view2295&quot;) has already been destroyed and cannot be used. 
JS: 2023-09-14 04:31:27 [error X 2][https://webrock.ir/bookstore1/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.16.2:3:135194] this.getSettingsPopup is not a function 
JS: 2023-09-14 05:27:30 [error X 1][https://webrock.ir/bookstore1/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.16.2:3:617231] Cannot read properties of undefined (reading &#039;isEditable&#039;) 

Log: showing 15 of 152023-09-14 04:08:10 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'المنتور',
  'from' => '3.15.3',
  'to' => '3.16.2',
)]
2023-09-14 04:08:16 [info] elementor::elementor_updater Started 
2023-09-14 04:08:16 [info] المنتور/Upgrades - _on_each_version Start  
2023-09-14 04:08:16 [info] المنتور/Upgrades - _on_each_version Finished 
2023-09-14 04:08:16 [info] المنتور/Upgrades - _v_3_16_0_container_updates Start  
2023-09-14 04:08:17 [info] المنتور/Upgrades - _v_3_16_0_container_updates Finished 
2023-09-14 04:08:17 [info] المنتور/Upgrades - _v_3_17_0_site_settings_updates Start  
2023-09-14 04:08:17 [info] المنتور/Upgrades - _v_3_17_0_site_settings_updates Finished 
2023-09-14 04:08:17 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'المنتور',
  'from' => '3.15.3',
  'to' => '3.16.2',
)]
2023-09-14 04:16:36 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.15.1',
  'to' => '3.16.0',
)]
2023-09-14 04:16:38 [info] elementor-pro::elementor_pro_updater Started 
2023-09-14 04:16:38 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-09-14 04:16:38 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-09-14 04:16:38 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.15.1',
  'to' => '3.16.0',
)]
2023-09-14 04:16:38 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.15.1',
  'to' => '3.16.0',
)]



== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatibility not specified

== Elementor Pro - Compatibility Tag ==
	


````

</details>

**Comment by nicholaszein** [comment] 2023-09-17 14:01
Hello @bytepack! 

Thank you for submitting your issue! 🙏 

We are aware of this issue and our team is already working on a fix. We can’t say exactly when it'll be sorted out, but we kindly ask for your patience. Thanks for understanding! 😉

Best regards

**Comment by nicholaszein** [comment] 2023-09-17 14:06
### 🔗 🐞 This issue is a Duplicate of #18169

Which is on the same subject. 

For this reason, I'm closing this thread and 🔃 **Merging** it with the original, so we can have all the discussions in one location, and deal with it more efficiently.

Feel free to continue the conversation there. 😉 

### 🔍 Please, in the future, remember to check if there isn't any thread similar to yours already opened. 

Kind regards

**Closed by nicholaszein** 2023-09-17 14:06 UTC
Labels: status/merged, type/styles, type/layout, component/star-rating, ✅ solved, mod*, solved_by_rating

**Comment by nicholaszein** [comment] 2023-10-26 05:48
Hello, @bytepack!

Thank you so much for your patience! 🙏 

We have great news! 🙌 

### 📢 We're happy to announce that the issue you raised was resolved with the release of the new Rating widget in Elementor v3.17! 🥳 

With this new widget, you have more options to choose the number of rating points, custom icons, and styling options, and it is fully compatible with Google Rich snippets (updated) and fully accessible. This also solves the issue with the decimal points raised here.

Your current Start Rating widgets will remain as they were before this update. But moving forward, only the new Rating widget will be available to add to your layouts.

If you are using the old Star Rating widget, we would recommend that you replace it with the new Rating widget.

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
