### ISSUE TITLE
🚀 Feature Request: Improved Ui Ux in Elementor navigator

### ISSUE THREAD

**Issue by Michaelgimii** [elementor/elementor#19782] opened 2022-09-12 13:09 UTC
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

One of the most important features is placing an element inside another element, which is not possible in the Elementor navigator. I don't know, maybe it is possible, because the user interface of the navigator is not really good and it is very confusing.
Please improve it.

### Describe the solution you'd like

Ability to move elements into or out of a container or section. This is something that is not possible now in Elementor.

Dragging an element in the desired element navigator will tilt it, and it's not really an interesting idea. For example, a little indentation would be much better. I'm completing a ui for the navigator, hope it's useful. thanks

**Comment by Michaelgimii** [comment] 2022-09-12 13:44
![navigator](https://user-images.githubusercontent.com/88034902/189670006-aca8bb1b-98f3-4d2f-9aa9-8f0d823c6fe4.png)

**Comment by rami-elementor** [comment] 2022-09-13 07:05
The issue title mention "performance", but in the description you are talking about UX.

**Comment by Michaelgimii** [comment] 2022-09-13 10:11
@rami-elementor , I wrote wrong. I apologize.

**Comment by rami-elementor** [comment] 2022-11-03 15:23
Duplicate of #18747

**Closed by rami-elementor** 2022-11-03 15:23 UTC
Labels: request/enhancement, component/navigator, component/container
