### ISSUE TITLE
🐞 Bug report: 

### ISSUE THREAD

**Issue by macedvisioned** [elementor/elementor#19461] opened 2022-08-13 15:47 UTC
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

While updating Elementor Pro from Version 3.7.2 to 3.7.3 I received the following error.

Deprecated: Functie Elementor\DB::is_built_with_elementor is sinds versie 3.2.0 verouderd! Gebruik in plaats daarvan Plugin::$instance->documents->get( $post_id )->is_built_with_elementor(). in /home/<dbname/domains/houwelingtelecommuseum.nl/public_html/wp-includes/functions.php on line 5379

I added the code on line 5379 but I got another fatal error.

### Steps to reproduce

I added the code on line 5379 but I got another fatal error.

degrade to version 3.7.2 helps. Issues disappears.

I use theme Astra. 

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: Apache/2
	MySQL version: MariaDB Server v10.4.24
	PHP Version: 7.4.28
	PHP Memory Limit: 128M
	PHP Max Input Vars: 10000
	PHP Max Post Size: 128M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.0.1
	Site URL: https://houwelingtelecommuseum.nl
	Home URL: https://houwelingtelecommuseum.nl
	WP Multisite: No
	Max Upload Size: 128 MB
	Memory limit: 40M
	Max Memory limit: 256M
	Permalink Structure: /%category%/%postname%/
	Language: nl
	Timezone: 0
	Admin Email: info@ceesbout.nl
	Debug Mode: Inactive

== Theme ==
	Name: Astra
	Version: 3.9.1
	Author: Brainstorm Force
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: nl_NL
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36

== Active Plugins ==
	Akismet Anti-Spam
		Version: 5.0
		Author: Automattic

	Astra Widgets
		Version: 1.2.12
		Author: Brainstorm Force

	Broken Link Checker
		Version: 1.11.17
		Author: WPMU DEV

	Classic Editor
		Version: 1.6.2
		Author: WordPress Contributors

	Classic Widgets
		Version: 0.3
		Author: WordPress Contributors

	Disable Gutenberg
		Version: 2.7
		Author: Jeff Starr

	Disable XML-RPC Pingback
		Version: 1.2.2
		Author: Samuel Aguilera

	Duplicator Pro
		Version: 4.5.5.2
		Author: Snap Creek

	Ele Custom Skin
		Version: 3.1.6
		Author: Dudaster.com

	Elementor
		Version: 3.7.0
		Author: Elementor.com

	Elementor Pro
		Version: 3.7.3
		Author: Elementor.com

	Enhanced Media Library
		Version: 2.8.9
		Author: wpUXsolutions

	Form Vibes
		Version: 1.4.5
		Author: WPVibes

	Gwolle Guestbook
		Version: 4.2.2
		Author: Marcel Pol

	Limit Login Attempts Reloaded
		Version: 2.25.4
		Author: Limit Login Attempts Reloaded

	Loco Translate
		Version: 2.6.2
		Author: Tim Whitlock

	Polylang
		Version: 3.2.5
		Author: WP SYNTEX

	Polylang Connect for Elementor
		Version: 2.3.0
		Author: Creame

	Really Simple SSL
		Version: 5.3.3
		Author: Really Simple Plugins

	Regenerate Thumbnails
		Version: 3.1.5
		Author: Alex Mills (Viper007Bond)

	Smush
		Version: 3.10.3
		Author: WPMU DEV

	UpdraftPlus - Backup/Restore
		Version: 1.22.14
		Author: UpdraftPlus.Com, DavidAnderson

	User Switching
		Version: 1.7.0
		Author: John Blackbourn & contributors

	WP-Matomo Integration
		Version: 1.0.27
		Author: André Bräkling

	WP-Optimize - Clean, Compress, Cache
		Version: 3.2.6
		Author: David Anderson, Ruhani Rabin, Team Updraft

	WP 2FA - Two-factor authentication for WordPress
		Version: 2.2.1
		Author: WP White Security

	WPS Hide Login
		Version: 1.9.6
		Author: WPServeur, NicolasKulka, wpformation

== Must-Use Plugins ==
	WordPress automation by Installatron
		Version: 
		Author: 

== Gebruik van elementen ==
	
	page : 1
		alert : 1
		heading : 1
	section : 6
		heading : 12
		icon-box : 4
		icon-list : 2
		image : 4
		spacer : 7
		text-editor : 16
	wp-post : 1
		text-editor : 2
	wp-page : 32
		accordion : 2
		alert : 2
		button : 6
		google_maps : 2
		heading : 93
		html : 4
		icon : 6
		icon-box : 14
		icon-list : 6
		image : 26
		shortcode : 2
		spacer : 55
		tabs : 8
		text-editor : 62
		video : 6

== Elementor experimenten ==
	Geoptimaliseerde DOM-uitvoer: Standaard inactief
	Verbeterd laden van assets: Standaard inactief
	Verbeterd laden van CSS: Standaard inactief
	Pictogrammen inline lettertype: Standaard inactief
	Toegang verbeteringen: Standaard inactief
	Extra aangepaste onderbrekingspunten: Standaard inactief
	Importeren exporteren Template Kit: Standaard actief
	Verberg verouderde WordPress widgets voor zoekresultaten: Standaard actief
	admin_menu_rearrangement: Standaard inactief
	Flexbox container: Standaard inactief
	Default to New Theme Builder: Standaard actief
	Landingspagina's: Standaard actief
	Kleur sampler: Standaard actief
	Favoriete widgets: Standaard actief
	Beheerder bovenste balk: Standaard actief
	Page Transitions: Standaard actief
	Notes: Standaard actief
	Form Submissions: Standaard actief
	Scroll Snap: Standaard actief

== Log ==
	
Log: showing 20 of 412022-08-07 13:38:49 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.2',
  'to' => '3.7.3',
)]
2022-08-07 13:38:49 [info] elementor-pro::elementor_pro_updater Started 
2022-08-07 13:38:49 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-08-07 13:38:49 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-08-07 13:38:49 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.2',
  'to' => '3.7.3',
)]
2022-08-07 13:38:50 [info] elementor::elementor_updater Started 
2022-08-07 13:38:50 [info] Elementor/Upgrades - _on_each_version Start  
2022-08-07 13:38:51 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.2',
  'to' => '3.7.3',
)]
2022-08-07 13:38:51 [info] elementor-pro::elementor_pro_updater Started 
2022-08-07 13:38:51 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-08-07 13:38:51 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-08-07 13:38:51 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.2',
  'to' => '3.7.3',
)]
2022-08-07 13:38:51 [info] Elementor/Upgrades - _on_each_version Finished 
2022-08-07 13:38:51 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.7',
  'to' => '3.6.8',
)]
2022-08-07 13:38:53 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.7',
  'to' => '3.6.8',
)]
2022-08-07 13:38:53 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.2',
  'to' => '3.7.3',
)]
2022-08-13 09:03:06 [info] elementor::elementor_updater Started 
2022-08-13 09:03:06 [info] Elementor/Upgrades - _on_each_version Start  
2022-08-13 09:03:07 [info] Elementor/Upgrades - _on_each_version Finished 
2022-08-13 09:03:07 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.8',
  'to' => '3.7.0',
)]

PHP: showing 2 of 2PHP: 2022-06-15 11:37:50 [error X 1][/home/pnyv199456/domains/houwelingtelecommuseum.nl/public_html/wp-content/plugins/elementor-pro/modules/notes/usage.php::161] Uncaught Error: Call to a member function format() on null in /home/pnyv199456/domains/houwelingtelecommuseum.nl/public_html/wp-content/plugins/elementor-pro/modules/notes/usage.php:161
Stack trace:
#0 /home/pnyv199456/domains/houwelingtelecommuseum.nl/public_html/wp-content/plugins/elementor-pro/modules/notes/usage.php(43): ElementorPro\Modules\Notes\Usage->get_first_interaction()
#1 /home/pnyv199456/domains/houwelingtelecommuseum.nl/public_html/wp-content/plugins/elementor-pro/modules/notes/usage.php(27): ElementorPro\Modules\Notes\Usage->get_usage_data()
#2 /home/pnyv199456/domains/houwelingtelecommuseum.nl/public_html/wp-includes/class-wp-hook.php(307): ElementorPro\Modules\Notes\Usage->ElementorPro\Modules\Notes\{closure}(Array)
#3 /home/pnyv199456/domains/houwelingtelecommuseum.nl/public_html/wp-includes/plugin.php(191): WP_Hook->apply_filters(Array, Array)
#4 /home/pnyv199456/domains/houwelingtelecommuseum.nl/public_html/wp-content/plugins/elementor/includes/tracker.php(563): apply_filters('elementor/t [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-06-20 09:26:46 [notice X 1][/home/pnyv199456/domains/houwelingtelecommuseum.nl/public_html/wp-content/plugins/elementor-pro/license/updater.php::84] Undefined index: new_version [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

== Elementor - Compatibility Tag ==
	
	Ele Custom Skin: Compatibel
	Elementor Pro: Compatibel
	Polylang Connect for Elementor: Niet compatibel

== Elementor Pro - Compatibility Tag ==
	
	Ele Custom Skin: Compatibel
	Polylang Connect for Elementor: Compatibel

**Comment by m1ga** [comment] 2022-08-13 17:52
check https://github.com/elementor/elementor/issues/18884

**Comment by rami-elementor** [comment] 2022-08-14 07:31
Duplicate of #18884

**Closed by rami-elementor** 2022-08-14 07:31 UTC
Labels: bug
