### ISSUE TITLE
🔗 🚀 Feature Request: Allow to add repeater controls inside a repeater control (nested repeater controls) (Duplicate of #2955)

### ISSUE THREAD

**Issue by pulla** [elementor/elementor#19174] opened 2022-07-16 09:00 UTC
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### 1. First of all,
1 question, 
Is there any the 3rd party plugin to support nested repeater widgets?
It should be a repeater in a repeater. 

<hr>
### 2. How we are trying to make.
<img width="963" alt="image" src="https://user-images.githubusercontent.com/5612050/179347858-5fba86c9-9ac1-4978-ae65-c9336ce2bb03.png">

Created 2 repeaters.

#### (1) Repeater 1 : it's for tab labels ( and pass some value with the form. ex) strType='stay' or 'people' 
You create tabs here

#### (2) Fileds : Add fitlers and choose which tab it's belongs to.

By repeaters, you can add fields and choose which fields it's belong to.
As you see there are 2 submit buttons.
One of them has to be "stay"
The other one has to be "people"

But the problem is .. tabs values don't pass to fields section.

How can you pass the values to another section?
Our developer created this much. But it's not possible to get "1. tab values" to "2. Fields section".
Then we can see the values and select them.
 
FYI, we don't want to add & use each template for search forms.
I have found there are many tabs are using "adding each templates".
It's a little bit not good to manage them. ( go to templates and modify each search form)
<hr>

### Describe the solution you'd like

Not found yet.

**Comment by nicholaszein** [comment] 2022-12-06 15:55
Hello @pulla!

Thank you for your submission! 🙏 

### 🔗 This issue is a Duplicate of #2955

Which is on the same subject. 

For this reason, I'm closing this issue and 🔃 **Merging** it with the original, so we can have all the discussions in one location, and deal with it more efficiently.

Feel free to continue the conversation there. 😉 

### ✔️ Please, in the future, remember to check if there isn't an issue similar to yours already opened. 

Best regards,

Nick

**Closed by nicholaszein** 2022-12-06 15:55 UTC
Labels: request/enhancement, solved_by_nested, component/tabs
