### ISSUE TITLE
🔗 🐞 Bug Report: Dark Mode text hightlight color (Duplicate of #21935)

### ISSUE THREAD

**Issue by madancodewing** [elementor/elementor#21953] opened 2023-04-06 07:59 UTC
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

In the dark mode the text hightlight color is not so visible 
https://prnt.sc/I6gZeAOhD4G0

### Steps to reproduce

just need to check the text hightlight color in dark mode

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently following the steps above.

### System Info

<details>
<summary>Click to reveal</summary>

````txt


					
== Server Environment ==
	Operating System: WINNT
	Software: Apache/2.4.47 (Win64) OpenSSL/1.1.1k PHP/7.4.19
	MySQL version: MySQL Community Server (GPL) v5.7.33
	PHP Version: 7.4.19
	PHP Memory Limit: 512M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 2G
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.2
	Site URL: http://test.mega-element
	Home URL: http://test.mega-element
	WP Multisite: No
	Max Upload Size: 2 GB
	Memory limit: 40M
	Max Memory limit: 512M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: en-US
	Timezone: 0
	Debug Mode: Active

== Theme ==
	Name: Coachify
	Version: 1.0.0
	Author: Coachify
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36

== Active Plugins ==
	Breeze
		Version: 2.0.18
		Author: Cloudways

	Elementor
		Version: 3.12.1
		Author: Elementor.com

	LiteSpeed Cache
		Version: 5.3.3
		Author: LiteSpeed Technologies

	Mega Elements - Addons for Elementor
		Version: 1.1.5
		Author: kraftplugins

	Regenerate Thumbnails
		Version: 3.1.5
		Author: Alex Mills (Viper007Bond)

	WordPress Importer
		Version: 0.8
		Author: wordpressdotorg


== Elementor Experiments ==
	Optimized DOM Output: Active by default
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Active by default
	Additional Custom Breakpoints: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active
	Upgrade Swiper Library: Inactive
	Editor Top Bar: Active
	Landing Pages: Active by default
	Nested Elements: Inactive by default
	Lazy Load Background Images: Inactive by default


== Log ==
	
JS: showing 5 of 5JS: 2023-03-07 08:50:13 [error X 2][../wp-content/plugins/elementor/assets/js/editor.js?ver=3.11.2:39299:71] Cannot read properties of undefined (reading 'toLowerCase') 
JS: 2023-03-07 08:50:15 [error X 14][../wp-content/plugins/elementor/assets/js/editor.js?ver=3.11.2:39327:11] Cannot read properties of undefined (reading 'localized') 
JS: 2023-03-08 06:08:18 [error X 1][../wp-content/plugins/elementor/assets/js/notes.js?ver=3.11.2:208:25] Cannot read properties of undefined (reading 'addFilter') 
JS: 2023-03-30 11:39:33 [error X 1][../wp-content/plugins/mega-elements-addons-for-elementor/includes/widgets/meafe-timeline/timeline.js?ver=1.1.5:55:38] Cannot read properties of null (reading 'swiper') 
JS: 2023-03-31 10:03:31 [error X 1][../wp-content/plugins/elementor/assets/lib/inline-editor/js/inline-editor.js?ver=3.11.2:403:17] Cannot convert undefined or null to object 

Log: showing 5 of 52023-04-05 07:02:14 [info] elementor::elementor_updater Started 
2023-04-05 07:02:14 [info] Elementor/Upgrades - _on_each_version Start  
2023-04-05 07:02:14 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.11.2',
  'to' => '3.12.1',
)]
2023-04-05 07:02:14 [info] Elementor/Upgrades - _on_each_version Finished 
2023-04-05 07:02:14 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.11.2',
  'to' => '3.12.1',
)]



== Elementor - Compatibility Tag ==
	
	Mega Elements - Addons for Elementor: Compatible
				

````

</details>

**Comment by nicholaszein** [comment] 2024-01-24 14:36
Hello @madancodewing!

Thank you for your submission! 🙏 

### 🔗 🐞 This issue is a Duplicate of #21935

Which is on the same subject. 

For this reason, I'm closing this thread and 🔃 **Merging** it with the original, so we can have all the discussions in one location, and deal with it more efficiently.

Feel free to continue the conversation there. 😉 

### 🔍 Please, in the future, remember to check if there isn't any thread similar to yours already opened. 

Kind regards

**Closed by nicholaszein** 2024-01-24 14:36 UTC
Labels: type/ui-ux, type/dark-mode, mod*, duplicate
