### ISSUE TITLE
Media carousel doesn't open video

### ISSUE THREAD

**Issue by umarglobal** [elementor/elementor#10167] opened 2020-01-16 13:16 UTC
The ticket below is not resolved although it is closed. Please resolve this for the sanity of your users. This is not fixed!
https://github.com/elementor/elementor/issues/8047

**Comment by lior-sh** [comment] 2020-03-30 09:16
Hi @umarglobal,

Thanks for reporting, we couldn't reproduce the issue.
Can you please attach a record of the issue by video?
Thanks.

**Comment by ImpactMind** [comment] 2020-06-07 21:19
Here's a website I'm working on using the Hello Theme with a Custom Carousel widget calling up two Elementor templates. The video is in the 2nd one and it will not show up initally. One must resize the browser and then the video will appear.

https://wordpress-281560-1202188.cloudwaysapps.com/

The missing video slide happens in all of the different carousel widgets I've tried. It's maddening.

**Comment by johnholliday** [comment] 2020-08-28 23:32
Definitely not fixed.  Video does not load. Only images in lightbox.
Elementor v2.9.14. Elementor Pro v2.10.3

**Comment by siteworkscollab** [comment] 2020-08-29 17:53
Elementor v3.0.3
Elementor Pro v3.0.1

YouTube videos seem to load fine but cannot load Vimeo - lightbox just spins and spins.

**Comment by ashbryant** [comment] 2020-10-22 14:38
Yep still an issue here too

**Comment by fEll3** [comment] 2020-11-17 15:44
Same for me, video is not working

Version 3.0.13
Version 3.0.6 - Pro

**Comment by arturikoX** [comment] 2020-12-21 13:34
Hi,
I'm trying to see videos too on versions :
Elementor Pro - 3.0.8
Elementor - 3.0.14

( Self hosted videos, it opens the image only )

Any assistance will be appreciated,

Thanks

**Comment by simb01** [comment] 2021-01-15 17:06
Hi

Not working for me either.
Elementor v3.0.16
Elementor Pro v3.0.9

Trying with Vimeo links

Lightbox opens but video doesn't load - just get a spinning loading icon.  
All the links work with the standard video widget.

Please can someone from Elementor respond to this... I have only just purchased the pro version - not good saying this issue has been open for a year.

Thanks

**Comment by DorShahar** [comment] 2021-02-21 15:33
Hi 
We tried again to reproduce the issue without any success. 
Therefore, I'm closing the issue.

In case the problem still happens, please open a new ticket and include :
-  Steps to reproduce
-  System info
- A short video will be excellent for us to understand better. 

Thanks.

**Closed by DorShahar** 2021-02-21 15:33 UTC
Labels: status/needs feedback

**Comment by rdushaev** [comment] 2024-07-27 13:52
I solved the problem by replacing the transition effect. With the Cube effect, some videos did not open for me.
