### ISSUE TITLE
Elementor menu in language as set in user-profile

### ISSUE THREAD

**Issue by srpotman72** [elementor/elementor#9356] opened 2019-10-17 09:30 UTC
- [x ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x ] The feature is still missing in the latest stable version of Elementor Pro.

**What problem is your feature request going to solve?
WordPress is showing it's menu in the language as per following:
1) (WP Dashboard - Settings - General - ) Site language
2) (WP Dashboard - right up in screen hover over user-id - Edit my profile - ) Language
The second is dominant.

Elementor is showing its menu (and Widget names) in the "Site language". This way we get to administer the site in 2 languages, one we don't master (the "Site language" is for the visitors of the site).

**Describe the solution you'd like**
Request to follow the same logic as WordPress, so Elementor is showing their options also based on 1) the Site language  but if different  2) Language (in the user profile), with the second dominant

**Describe alternatives you've considered**
Learning each language my customers want to target :-)

**Additional context**
Thanks! I hope this is easy to implement. A happy PRO-user

**Comment by yratof** [comment] 2019-10-18 08:44
Ditto on this. 

Elementor doens't respect the user language. I have English editors working on Norwegian sites where the entire dashboard is english until editing via elementor.

**Comment by yratof** [comment] 2019-10-18 08:47
Looks like we need to just check the right function for language before firing up the editor:

`/elementor/core/editor/editor.php:550` => `'locale' => get_locale(),`

Should be `'locale' => get_user_locale(),`

**Comment by srpotman72** [comment] 2019-10-21 06:47
Excellent Yratof! It works. Hope Elementor can quickly apply this to the standard product

**Comment by srpotman72** [comment] 2019-11-06 19:46
Unfortunately, I did not get it to work. Hope Elementor can improve standard product soon.
Thanks!

**Comment by vojjin** [comment] 2020-02-10 15:14
I found a solution.. in file  /elementor/includes/compatibility.php ... at row 270
````
add_action( 'set_current_user', function() {
	global $current_user;
	$current_user->locale = get_locale();
} );
````
just put locale you need. "en_US" or maybe (haven't tried) get_user_locale().

**Comment by srpotman72** [comment] 2020-02-10 16:09
Excellent Vojjin, thanks. It works for me. So I will be able to deliver much easier for strange languages.
However, it would be great if Elementor can update the standard software, as your update will be overwritten by new versions.

**Comment by vojjin** [comment] 2020-02-10 19:55
I know, that should be request to developers to include in Elementor settings option to use custom language rather than WP chosen language.

**Comment by arielk** [comment] 2020-06-20 19:42
Duplicate of https://github.com/elementor/elementor/issues/5148

**Closed by arielk** 2020-06-20 19:42 UTC

**Comment by lirdis** [comment] 2020-10-13 10:28
If the source of the problem has been found and the actual problem has been defined and practically solved - why isn't Elementor doing anything about it and fixes the code so that it takes the User profile language as an argument rather than the site's language?! I can always make another user (with its own language) to work in the language that I require but I cannot make another website..! Why isn't this solved natively?!

**Comment by dsecareanu** [comment] 2021-01-06 10:31
+1 - this should be a basic functionality in Elementor.
