### ISSUE TITLE
🔗 🐞 Bug Report: After update to 3.7.6  the background image styles don't apply (Related to #19894)

### ISSUE THREAD

**Issue by petrovakatya** [elementor/elementor#19861] opened 2022-09-20 08:04 UTC
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

When I updated the elementor version to 3.7.6 the background image styles don't apply to mobile and tablet (x position, y position and width). it looks fine in the editor but not in the preview.

In editor:
<img width="1080" alt="Screenshot 2022-09-20 at 10 54 45" src="https://user-images.githubusercontent.com/84016981/191200224-c4810b11-b5f2-4bca-8195-7c1042130569.png">

In preview:
<img width="503" alt="Screenshot 2022-09-20 at 10 57 56" src="https://user-images.githubusercontent.com/84016981/191200985-3b291c26-e35f-4119-bc63-b41d61c301b6.png">

### Steps to reproduce

1) add background image to section
2) select responsive mode for mobile or tablet
3) select position "custom" and change x position, y position and width
4) styles are applied in the editor but not in the preview

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: nginx
	MySQL version: Percona Server (GPL), Release '42', Revision 'b0a7dc2da2e' v5.7.39-42
	PHP Version: 7.4.28
	PHP Memory Limit: 512M
	PHP Max Input Vars: 10000
	PHP Max Post Size: 100M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.9.4
	Site URL: https://lecturiocom.wpengine.com
	Home URL: https://lecturiocom.wpengine.com
	WP Multisite: No
	Max Upload Size: 50 MB
	Memory limit: 512M
	Max Memory limit: 512M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 0
	Admin Email: server-admin@lecturio.de
	Debug Mode: Inactive

== Theme ==
	Name: Lecturio Theme
	Version: 1.0.1
	Author: Elementor Team
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.2.2
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36

== Active Plugins ==
	Advanced Custom Fields Multilingual
		Version: 1.10.3
		Author: OnTheGoSystems

	Advanced Custom Fields PRO
		Version: 5.12.2
		Author: Delicious Brains

	C3 Cloudfront Cache Controller
		Version: 6.1.3
		Author: hideokamoto

	Custom Gutenberg Styles
		Version: 1.0
		Author: Till Vennemann

	Custom Post Type UI
		Version: 1.12.1
		Author: WebDevStudios

	Dynamic.ooo - Dynamic Content for Elementor
		Version: 2.5.8
		Author: Dynamic.ooo

	Elementor
		Version: 3.7.6
		Author: Elementor.com

	Elementor Pro
		Version: 3.7.6
		Author: Elementor.com

	EWWW Image Optimizer
		Version: 6.5.2
		Author: Exactly WWW

	Lecturio Access
		Version: 0.1
		Author: Veselin Dimitrov

	Lecturio ACF
		Version: 0.1.1
		Author: Lecturio.com

	Lecturio Add Custom Meta Fileds to Posts
		Version: 1.0
		Author: Veselin Dimitrov

	Lecturio Add WPML roles
		Version: 0.1.1
		Author: Lecturio.com

	Lecturio Change Blog URL Structure
		Version: 0.1.1
		Author: Lecturio.com

	Lecturio concept tests
		Version: 0.1.1
		Author: Lecturio.com

	Lecturio Custom Page Search
		Version: 0.1
		Author: Veselin Dimitrov

	Lecturio Export Concept Pages in CSV
		Version: 0.1.1
		Author: Lecturio.de

	Lecturio Export Concepts
		Version: 0.1.1
		Author: Lecturio.com

	Lecturio Export Concept URLs in CSV
		Version: 0.1.1
		Author: Lecturio.com

	Lecturio Export Studenr blog post
		Version: 0.1.1
		Author: Katya Petrova

	Lecturio Extend Elementor Search form
		Version: 0.1.1
		Author: Lecturio.com

	Lecturio Find Post Using Attachment
		Version: 0.1.1
		Author: Katya Petrova

	Lecturio Google Tag Manager Plugin
		Version: 
		Author: 

	Lecturio Interlinking Pro
		Version: 1
		Author: Veselin Dimitrov feat Katya Petrova

	Lecturio LightBox
		Version: 1.0
		Author: Veselin Dimitrov

	Lecturio Nursing Course data
		Version: 0.1.1
		Author: Lecturio.com

	Lecturio Nursing Courses archive
		Version: 0.1.1
		Author: Lecturio.com

	Lecturio Nursing Courses carousel
		Version: 0.1.1
		Author: Lecturio.com

	Lecturio Pricing Two
		Version: 0.1
		Author: Veselin Dimitrov

	Lecturio Rank Math
		Version: 0.1.1
		Author: Lecturio.de

	Lecturio Regwall
		Version: 0.1.1
		Author: Katya Petrova

	Lecturio Related Video
		Version: 0.1
		Author: Veselin Dimitrov

	Lecturio Relate Language Link
		Version: 1.0
		Author: Veselin Dimitrov

	Lecturio Relative links
		Version: 0.1.1
		Author: Lecturio.de

	Lecturio Replace urls
		Version: 0.1.1
		Author: Lecturio.com

	Lecturio Security
		Version: 0.1.1
		Author: Lecturio.de

	Lecturio show popup for ES
		Version: 0.1.1
		Author: Lecturio.com

	Lecturio WPML custom preview button
		Version: 0.1.1
		Author: Lecturio.com

	Popup Trigger URL for Elementor Pro
		Version: 1.0.5
		Author: Suki WordPress Theme

	Rank Math SEO
		Version: 1.0.97
		Author: Rank Math

	Rank Math SEO PRO
		Version: 3.0.20
		Author: Rank Math

	Redirection
		Version: 5.2.3
		Author: John Godley

	REST API Blocks / Lecturio
		Version: 0.5.0
		Author: Jonathan Harris / Lecturio WP Team

	Unlimited Elements for Elementor
		Version: 1.5.12
		Author: Unlimited Elements

	WP Crontrol
		Version: 1.12.1
		Author: John Blackbourn & crontributors

	WPML Multilingual CMS
		Version: 4.5.6
		Author: OnTheGoSystems

	WPML String Translation
		Version: 3.2.1
		Author: OnTheGoSystems

	WP Offload Media
		Version: 2.6.2
		Author: Delicious Brains

	WP Offload Media - Assets Pull Addon
		Version: 1.1.2
		Author: Delicious Brains

	WP Rocket
		Version: 3.11.2
		Author: WP Media

== Must-Use Plugins ==
	Elementor Safe Mode
		Version: 1.0.0
		Author: Elementor.com

	Force Strong Passwords - WPE Edition
		Version: 1.8.0
		Author: Jason Cosper

	WP Engine Cache Plugin
		Version: 1.0.10
		Author: WP Engine

	WP Engine Seamless Login Plugin
		Version: 1.6.0
		Author: WP Engine

	WP Engine Security Auditor
		Version: 1.0.10
		Author: wpengine

	WP Engine System
		Version: 5.0.1
		Author: WP Engine

== Elements Usage ==
	
	footer : 13
		heading : 19
		icon-list : 15
		image : 10
		social-icons : 4
		text-editor : 3
	header : 22
		button : 5
		heading : 2
		image : 7
		nav-menu : 7
		text-editor : 1
	page : 144
		accordion : 2
		button : 82
		divider : 20
		form : 4
		heading : 67
		html : 4
		icon-box : 19
		icon-list : 22
		image : 28
		image-box : 33
		media-carousel : 1
		menu-anchor : 9
		price-table : 10
		reviews : 1
		share-buttons : 1
		spacer : 5
		testimonial-carousel : 2
		text-editor : 89
		toggle : 1
	popup : 109
		button : 4
		divider : 1
		heading : 5
		html : 2
		image : 3
		text-editor : 4
		video : 5
	section : 194
		button : 56
		dce-acf-repeater-v2 : 4
		divider : 23
		dyncontel-acf : 22
		heading : 93
		html : 2
		icon-list : 3
		image : 56
		image-box : 27
		posts : 1
		price-table : 6
		share-buttons : 1
		slides : 2
		tabs : 1
		text-editor : 57
		toggle : 5
	single : 15
		heading : 1
		image : 1
		text-editor : 1
	wp-page : 275
		accordion : 3
		button : 121
		dce-acf-repeater-v2 : 2
		divider : 23
		form : 5
		heading : 177
		html : 6
		icon-box : 59
		icon-list : 29
		image : 30
		image-box : 6
		image-carousel : 2
		lottie : 1
		media-carousel : 3
		menu-anchor : 10
		posts : 3
		price-table : 12
		reviews : 2
		share-buttons : 1
		slides : 2
		spacer : 51
		tabs : 1
		testimonial : 3
		testimonial-carousel : 3
		text-editor : 118
		toggle : 5
		video : 9
	single-post : 9
		button : 5
		divider : 1
		form : 4
		heading : 15
		icon-box : 8
		icon-list : 6
		image : 2
		spacer : 1
		template : 2
		text-editor : 3
		theme-post-content : 1
		toggle : 2
		ucaddon_uc_card_post_carousel : 1
		video : 1

== Elementor Experiments ==
	Optimized DOM Output: Active
	Improved Asset Loading: Active
	Improved CSS Loading: Inactive
	Inline Font Icons: Inactive
	Accessibility Improvements: Inactive by default
	Additional Custom Breakpoints: Inactive by default
	Import Export Template Kit: Inactive
	Hide native WordPress widgets from search results: Inactive
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Inactive
	Default to New Theme Builder: Inactive
	Landing Pages: Inactive
	Color Sampler: Inactive
	Favorite Widgets: Inactive
	Admin Top Bar: Inactive
	Page Transitions: Inactive
	Notes: Inactive
	Form Submissions: Inactive
	Scroll Snap: Inactive

== Log ==
	
PHP: showing 18 of 18PHP: 2022-08-18 16:02:06 [warning X 1][/nas/content/live/lecturiocom/wp-content/plugins/elementor/core/files/file-types/svg.php::233] simplexml_load_file(): I/O warning : failed to load external entity "https://cdn.lecturio.com/assets/Respiratory-System-2.svg" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-08-18 16:02:11 [warning X 1][/nas/content/live/lecturiocom/wp-content/plugins/elementor/core/files/file-types/svg.php::233] simplexml_load_file(): I/O warning : failed to load external entity "https://cdn.lecturio.com/assets/Rheumatology.svg" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-08-18 16:02:15 [warning X 1][/nas/content/live/lecturiocom/wp-content/plugins/elementor/core/files/file-types/svg.php::233] simplexml_load_file(): I/O warning : failed to load external entity "https://cdn.lecturio.com/assets/Safe-and-Effective-Care-Environment-Nursing.svg" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-08-18 16:02:20 [warning X 1][/nas/content/live/lecturiocom/wp-content/plugins/elementor/core/files/file-types/svg.php::233] simplexml_load_file(): I/O warning : failed to load external entity "https://cdn.lecturio.com/assets/Skin-_-Subcutaneous-Tissue.svg" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-08-18 16:02:24 [warning X 1][/nas/content/live/lecturiocom/wp-content/plugins/elementor/core/files/file-types/svg.php::233] simplexml_load_file(): I/O warning : failed to load external entity "https://cdn.lecturio.com/assets/Social-Sciences-1.svg" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-08-18 16:02:29 [warning X 1][/nas/content/live/lecturiocom/wp-content/plugins/elementor/core/files/file-types/svg.php::233] simplexml_load_file(): I/O warning : failed to load external entity "https://cdn.lecturio.com/assets/Surgery-2.svg" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-08-18 16:02:34 [warning X 1][/nas/content/live/lecturiocom/wp-content/plugins/elementor/core/files/file-types/svg.php::233] simplexml_load_file(): I/O warning : failed to load external entity "https://cdn.lecturio.com/assets/Top-USMLE-Diseases.svg" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-08-18 16:46:24 [warning X 1][/nas/content/live/lecturiocom/wp-content/plugins/elementor/core/files/file-types/svg.php::233] simplexml_load_file(): I/O warning : failed to load external entity "https://cdn.lecturio.com/assets/pathology.svg" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-08-18 17:46:48 [notice X 12][/nas/content/live/lecturiocom/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-08-23 11:50:58 [notice X 25][/nas/content/live/lecturiocom/wp-content/plugins/elementor/includes/managers/image.php::87] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-08-23 13:59:49 [notice X 10][/nas/content/live/lecturiocom/wp-content/plugins/elementor/includes/widgets/video.php::1161] Trying to access array offset on value of type null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-08-29 08:22:23 [warning X 4][/nas/content/live/lecturiocom/wp-content/plugins/elementor/core/files/file-types/svg.php::190] SimpleXMLElement::__construct(): ^ [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-08-30 09:10:56 [notice X 1][/nas/content/live/lecturiocom/wp-content/plugins/elementor-pro/modules/dynamic-tags/acf/tags/acf-text.php::33] Undefined offset: 1 [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-09-07 07:24:46 [warning X 6][/nas/content/live/lecturiocom/wp-content/plugins/elementor/core/files/file-types/svg.php::190] SimpleXMLElement::__construct():  ^ [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-09-07 10:47:13 [warning X 1][/nas/content/live/lecturiocom/wp-content/plugins/elementor/core/files/file-types/svg.php::233] simplexml_load_file(): I/O warning : failed to load external entity "https://cdn.lecturio.com/assets/triangle-outline-7.svg" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-09-08 11:38:33 [notice X 4][/nas/content/live/lecturiocom/wp-content/plugins/elementor/core/experiments/experiments-reporter.php::89] Undefined index: title [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-09-16 12:15:51 [notice X 1][/nas/content/live/lecturiocom/wp-content/plugins/elementor-pro/modules/posts/skins/skin-content-base.php::264] Trying to get property 'ID' of non-object [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-09-19 07:25:22 [error X 1][/nas/content/live/lecturiocom/wp-content/plugins/elementor-pro/core/app/modules/site-editor/module.php::164] Uncaught Error: Undefined class constant 'ADMIN_MENU_PRIORITY' in /nas/content/live/lecturiocom/wp-content/plugins/elementor-pro/core/app/modules/site-editor/module.php:164
Stack trace:
#0 /nas/content/live/lecturiocom/wp-content/plugins/elementor-pro/core/app/app.php(85): ElementorPro\Core\App\Modules\SiteEditor\Module->__construct()
#1 /nas/content/live/lecturiocom/wp-content/plugins/elementor-pro/plugin.php(473): ElementorPro\Core\App\App->__construct()
#2 /nas/content/live/lecturiocom/wp-content/plugins/elementor-pro/plugin.php(121): ElementorPro\Plugin->__construct()
#3 /nas/content/live/lecturiocom/wp-content/plugins/elementor-pro/plugin.php(511): ElementorPro\Plugin::instance()
#4 /nas/content/live/lecturiocom/wp-content/plugins/elementor-pro/elementor-pro.php(57): require('/nas/content/li...')
#5 /nas/content/live/lecturiocom/wp-includes/class-wp-hook.php(307): elementor_pro_load_plugin('')
#6 /nas/content/live/lecturiocom/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters(NULL, Array)
#7 /nas [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 11 of 11JS: 2022-08-19 08:52:29 [error X 31][https://lecturiocom.wpengine.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.6.5:2:450542] T.getContainer is not a function 
JS: 2022-08-23 11:51:03 [error X 11][https://lecturiocom.wpengine.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view873\") has already been destroyed and cannot be used. 
JS: 2022-08-23 14:00:09 [error X 1][https://lecturiocom.wpengine.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view13156\") has already been destroyed and cannot be used. 
JS: 2022-08-23 14:02:00 [error X 1][https://lecturiocom.wpengine.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view21326\") has already been destroyed and cannot be used. 
JS: 2022-08-25 06:34:28 [error X 1][https://lecturiocom.wpengine.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view604\") has already been destroyed and cannot be used. 
JS: 2022-08-25 06:35:03 [error X 1][https://lecturiocom.wpengine.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view3817\") has already been destroyed and cannot be used. 
JS: 2022-08-30 09:21:20 [error X 1][https://lecturiocom.wpengine.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view7415\") has already been destroyed and cannot be used. 
JS: 2022-08-30 09:22:57 [error X 1][https://lecturiocom.wpengine.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view14399\") has already been destroyed and cannot be used. 
JS: 2022-09-01 09:00:55 [error X 1][https://lecturiocom.wpengine.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view631\") has already been destroyed and cannot be used. 
JS: 2022-09-07 07:00:14 [error X 3][https://lecturiocom.wpengine.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view867\") has already been destroyed and cannot be used. 
JS: 2022-09-16 14:49:12 [error X 1][https://lecturiocom.wpengine.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.6.5:2:218059] Cannot read properties of undefined (reading \'css\') 

Log: showing 14 of 142022-09-19 07:22:16 [info] elementor::elementor_updater Started 
2022-09-19 07:22:16 [info] Elementor/Upgrades - _on_each_version Start  
2022-09-19 07:22:16 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.5',
  'to' => '3.7.6',
)]
2022-09-19 07:22:18 [info] Elementor/Upgrades - _on_each_version Finished 
2022-09-19 07:22:18 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.5',
  'to' => '3.7.6',
)]
2022-09-19 07:22:19 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.5',
  'to' => '3.7.6',
)]
2022-09-19 07:25:26 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.1',
  'to' => '3.7.6',
)]
2022-09-19 07:25:26 [info] elementor-pro::elementor_pro_updater Started 
2022-09-19 07:25:26 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-09-19 07:25:26 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-09-19 07:25:26 [info] Elementor Pro/Upgrades - _v_3_7_2_woocommerce_rename_related_to_related_products Start  
2022-09-19 07:25:32 [info] Elementor Pro/Upgrades - _v_3_7_2_woocommerce_rename_related_to_related_products Finished 
2022-09-19 07:25:32 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.1',
  'to' => '3.7.6',
)]
2022-09-19 07:25:33 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.1',
  'to' => '3.7.6',
)]

== Elementor - Compatibility Tag ==
	
	Dynamic.ooo - Dynamic Content for Elementor: Compatibility not specified
	Elementor Pro: Compatibility not specified
	Lecturio Extend Elementor Search form: Compatibility not specified
	Popup Trigger URL for Elementor Pro: Compatibility not specified
	Unlimited Elements for Elementor: Compatibility not specified

== Elementor Pro - Compatibility Tag ==

**Comment by marian-kadanka** [comment] 2022-09-21 09:02
Confirming. It looks like it started happening when you fixed #19527

**Comment by steveindzine** [comment] 2022-09-21 12:21
I have a similar problem with Background Size. It's set to contain for mobile devices but the CSS for this isn't being created. This is with Elementor 3.7.7 and Elementor Pro 3.7.7.

**Comment by rally-lad** [comment] 2022-09-21 15:09
Same issue here across multiple sites upgraded to Elementor 3.7.7 and Elementor PRO 3.7.7

Cache Disabled, tried re-building the CSS and tried incognito.

Currently rolled back to previous Elementor Version 3.7.3 (Pro is still at 3.7.7).

**Comment by m1ga** [comment] 2022-09-21 21:07
can confirm this too (Elementor 3.7.7).

Looks like this https://github.com/elementor/elementor/pull/19677 broke it. There is a comment that a fix will come in the next patch version. So hopefully that is release quickly (at the moment there are very many updates)

**Comment by Deadlift79** [comment] 2022-09-21 22:58
Same here.
All is working fine only in the editor (custom positioning and size now appear also for tablet/mobile) but then CSS (positioning, size, repeat...) isn't applied on frontend.

**Comment by chasperlisimba** [comment] 2022-09-22 06:57
same here. in 3.7.7 it looks good in the editor but it‘s no correct in the frontend…

**Comment by m1ga** [comment] 2022-09-22 09:26
looks like the fix for it https://github.com/elementor/elementor/pull/19883

**Comment by MichaelDarko** [comment] 2022-09-23 00:45
Same problem here.

**Comment by mcrowell** [comment] 2022-09-27 20:48
@rami-elementor Any ETA on when this bug will be fixed??

**Comment by rally-lad** [comment] 2022-09-27 21:06
> @rami-elementor Any ETA on when this bug will be fixed??

Looking at the patch notes and pull requests it’ll be on release 3.8 which may possibly cause other issues. 😑

**Comment by KingGrizzly** [comment] 2022-09-28 14:39
We've paused upgrades while waiting for this patch as well.

**Comment by tfrank77** [comment] 2022-10-04 10:17
We still have this bug in v3.7.8
Mobile view > Section background >> Position
It doesn't work at all.

**Comment by m1ga** [comment] 2022-10-04 10:27
@tfrank77 please check link above https://github.com/elementor/elementor/issues/19861#issuecomment-1254764425 
The PR is not merged yet

**Comment by tfrank77** [comment] 2022-10-04 10:54
> @tfrank77 please check link above [#19861 (comment)](https://github.com/elementor/elementor/issues/19861#issuecomment-1254764425) The PR is not merged yet

Thanks for the info, looking forward to it.

**Comment by marian-kadanka** [comment] 2022-10-04 11:53
I have manually applied patches mentioned in #19883 to current 3.7.8 master branch and the problem isn't fixed.

**Comment by nicholaszein** [comment] 2022-10-12 19:54
Hello all!

Yes, I'm confirming this issue will be resolved when Elementor v3.8 is released.

Feel free to update to v3.8 when it gets released.

Cheers! 🥂

**Comment by arielk** [comment] 2022-11-05 18:58
This issue has been resolved in Elementor v3.8.0

Feel free to update

Thanks!

**Closed by arielk** 2022-11-05 18:58 UTC
Labels: bug, type/responsive, status/merged
