### ISSUE TITLE
Conditional forms for selling stuff

### ISSUE THREAD

**Issue by Netman82** [elementor/elementor#8374] opened 2019-06-22 08:58 UTC
Elementor lacks having a conditional form. it has a lot of use, for example, makes the website admin able to create a purchase flow based on buyer's selections (hiding fields/showing fields). I see a few premium plugins out there having conditional forms developed already.

Any chance to see this on Elementor?

**Comment by shilo-ey** [comment] 2019-06-23 16:04
Duplicate of #2638

**Closed by shilo-ey** 2019-06-23 16:04 UTC
