### ISSUE TITLE
❌ 🐞 WordPress widgets styling error after update

### ISSUE THREAD

**Issue by Jelena1** [elementor/elementor#24966] opened 2024-01-29 22:57 UTC
### Prerequisites

- [X] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [X] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

From version 3.18 pages created with Elementor cause styling errors to default WordPress widgets in widget areas like header and footer on those pages. Widgets affected include search and social icons widgets. For example, default social icons widget has no background color. 

Seems that “Optimized Gutenber Loading” was inactive by default in versions before 3.18 and in newest versions it is active by default and that breaks styling for default WordPress widgets.

I don’t think this should be active by default.

### Steps to reproduce

1. Add default social icons widget in footer or other widget area on the page where Elementor is used.
2. Icons will have no background color, will be black.
3. Switch "Optimized Gutenberg loading" to inactive and icons will get background color (that can be changed in icon settings)

### Expected behavior

Default WP icons widget should always have background color.

### Isolating the problem

- [X] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [X] This bug happens with the Hello Elementor theme active.
- [X] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

```txt
Operating System: 	Linux 	 
Software: 	Apache 	 
MySQL version: 	Percona Server (GPL), Release 84.1, Revision b308619 v5.6.41-84.1 	 
PHP Version: 	7.4.33 	 
PHP Max Input Vars: 	1000 	 
PHP Max Post Size: 	128M 	 
GD Installed: 	Yes 	 
ZIP Installed: 	Yes 	 
Write Permissions: 	All right 	 
Elementor Library: 	Connected
```

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by JoelLisenby** [comment] 2024-01-30 18:28
We are also seeing widget padding/styling issues after the update to 3.19.0.

We have noticed we do not have the option to disable "DOM Optimization" and several layouts across our website have broken. We had to revert to the previous version of Elementor. Do you have any suggestions?

I see it enabled here:

https://github.com/elementor/elementor/pull/24712
https://github.com/elementor/elementor/pull/24716

**Comment by nicholaszein** [comment] 2024-01-31 00:45
Hi @JoelLisenby.

As of version 3.19, the Optimized Output feature will be part of Elementor Core, and can't be reverted back. This feature was introduced a while ago, and it was time to merge it to core.

If you have really old websites using custom CSS with the old structure, you will need to edit your custom CSS. For older sites this change should only affect custom CSS. Make sure to Regenerate CSS & Data, and to clear/purge all levels of cache that apply to your site.

**Comment by nicholaszein** [comment] 2024-01-31 00:48
Hello @Jelena1,

the issue you're reporting is not a bug. This option is set to be active by default, this is the expected behavior. If you use the Block editor, or any native WordPress widget, you will need to deactivate this option manually.

Thank you for sharing your feedback.

Please, next time remember to include the FULL Elementor System Info as required and [instructed](https://github.com/elementor/elementor/blob/main/.github/CONTRIBUTING.md#how-to-report-a-bug) in the Bug Report form.

We cannot accept issues without this crucial information.

Kind regards

**Closed by nicholaszein** 2024-01-31 00:48 UTC
Labels: type/performance, type/styles, type/experiment, mod*, admin, widget/wordpress, settings
