### ISSUE TITLE
❌ 🐞 Bug Report: Dropdown arrows on checkout page are boxes instead of arrow. Should be an easy fix in the backend.

### ISSUE THREAD

**Issue by DeanE1** [elementor/elementor#21321] opened 2023-02-14 06:15 UTC
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

I found a bug where the dropdown arrows in the checkout element turn into boxes if you select a form field color but only if you use a global color. If you manually select a color (not a global color) the arrow display correctly.

This does not display in the elementor preview but does get applied to a live site.
It works fine as long as you do not use a global color. What appears to be happening is 3 transparent properties on the border are not being applied on a global color selection. When a non global color is used, 3 transparent properties are applied to the border. Below is an example of the CSS when a global color used vs a non global color used.

CSS of global color used:
```
.elementor-3376 .elementor-element.elementor-element-db1828d .select2-container--default .select2-selection--single .select2-selection__arrow b {
    border-color: var( --e-global-color-text );
}
```

CSS of non global color used:
```
.elementor-3376 .elementor-element.elementor-element-db1828d .select2-container--default .select2-selection--single .select2-selection__arrow b {
    border-color: #E3E3E3 transparent transparent transparent; 
```

It makes sense why the additional transparent properties are not applied to the form field attributes, but maybe the form field arrows need separate styling to correct this?

### Steps to reproduce

1) add the checkout widget
2) select style / forms
3) scroll to fields
4) select global colors
5) select any global color
6) update page
7) view on live/front end of site

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

NA

**Comment by mbaierl** [comment] 2023-02-14 09:24
Same here. But since you have to adjust the CSS on the checkout page manually anyhow, I always fix this by hand... 
Overall the creation and styling of the cart/checkout/thank you pages is still a pain in the ass and only works 80%... buttons often don't work and global defaults are not honored.

**Comment by DeanE1** [comment] 2023-02-14 14:17
Everything else appears to be working properly on my end, I have no additional CSS on my checkout page.

**Comment by nicholaszein** [comment] 2023-02-16 13:17
Hello @DeanE1, 

Thank you for submitting your report! 🙏 

### ❌ While reviewing your report, we noticed it was missing some key pieces of information:

- 💾 **System info:** Please include the System Info report as outlined in our [guidelines](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml). 
   - Get your System Info from your WordPress `Dashboard` > `Elementor` > `System info` [learn how to copy it here](https://elementor.com/help/hare-my-system-info/). We can't accept issues without it.

Without them, we simply can't help. 😕 

### 🧐 Please provide the missing information above so we can troubleshoot your issue faster and better.

Best regards,

Nick

**Comment by DeanE1** [comment] 2023-02-16 14:35
I've already fixed my problem and troubleshot the issue. This post is to simply inform elementor of missing code that I am sure has frustrated several of your users during their design process.

**Comment by nicholaszein** [comment] 2023-05-02 05:20
Hi @DeanE1, 

we can't continue the investigation without the proper information. After following your steps we were unable to reproduce your issue. For this reason, I am closing this issue as invalid.

Please follow the guidelines for opening a new [🐞 Bug Report](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml), so we can help you better.

Best regards,

Nick

**Closed by nicholaszein** 2023-05-02 05:20 UTC
Labels: bug, product/pro, component/woocommerce, type/design, mod*
