### ISSUE TITLE
Caption / Title / Description in image lightbox

### ISSUE THREAD

**Issue by DH-Martin** [elementor/elementor#10115] opened 2020-01-10 15:32 UTC
Would it be possible to have a caption when the lightbox is open? Would be great if we could have captions not only in the gallery grid. 

## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by shilo-ey** [comment] 2020-01-12 07:48
Duplicate of #2502

**Closed by shilo-ey** 2020-01-12 07:48 UTC
