### ISSUE TITLE
Popup opens first time on page click instead on button click

### ISSUE THREAD

**Issue by nemanjasipka** [elementor/elementor#7446] opened 2019-03-13 12:18 UTC
Popup opens first time on page click instead on button click. Try to click on page anywhere  and you will see that popup will open, and after that it will work fine on click here button. But before that it will open on any click on the page.  https://successive.no/landing-page/ Check the link

**Comment by shilo-ey** [comment] 2019-03-13 14:02
Thanks for reporting,

As mentioned earlier (#7434), we can't reproduce.

Please contact our support at support @elementor.com for guidance in resolving this issue and reference this thread.

Thanks.

**Closed by shilo-ey** 2019-03-13 14:02 UTC

**Comment by nemanjasipka** [comment] 2019-03-13 14:10
How you can`t reproduce bug. It is first thing when you open the link and click anywhere on the page. Clearly it is a bug , i have tested it on couple themes and newest wordpress  versions.

**Comment by touchestudio** [comment] 2019-04-11 22:57
> Popup opens first time on page click instead on button click. Try to click on page anywhere and you will see that popup will open, and after that it will work fine on click here button. But before that it will open on any click on the page. https://successive.no/landing-page/ Check the link

Having the same issue here...

**Comment by mariomax** [comment] 2019-04-30 17:52
I figured out the problem by watching a tutorial. DO NOT select any triggers or conditions in the Popup settings. Only set the dynamic action in the button itself. Boom!

**Comment by dafitime** [comment] 2020-04-28 17:24
> I figured out the problem by watching a tutorial. DO NOT select any triggers or conditions in the Popup settings. Only set the dynamic action in the button itself. Boom!

Thank you Mario. This is the exact fix needed for mine.

**Comment by yves-s** [comment] 2020-09-03 16:48
> I figured out the problem by watching a tutorial. DO NOT select any triggers or conditions in the Popup settings. Only set the dynamic action in the button itself. Boom!

Thanks @mariomax fortunately I found this thread by googling 🙏🏼

**Comment by mabotofu** [comment] 2020-10-12 07:30
Thank you, @mariomax.  I was having the exact same issue. Wherever I click on screen, the popup was showing. 
I hope they fix this bug.

**Comment by Rajesh-Royal** [comment] 2021-05-13 09:34
> I figured out the problem by watching a tutorial. DO NOT select any triggers or conditions in the Popup settings. Only set the dynamic action in the button itself. Boom!

Thanks dude. 🙏🙏

**Comment by jdev-d** [comment] 2022-07-13 12:08
But its not working on my side...

**Comment by nevertoday** [comment] 2023-03-16 14:49
two popups display after i click one button , so awful

**Comment by freemartian** [comment] 2024-01-05 12:10
> I figured out the problem by watching a tutorial. DO NOT select any triggers or conditions in the Popup settings. Only set the dynamic action in the button itself. Boom!

Hello Can you please mention where to disable these conditions, I couldn't find any in the modal setting. Or if you can mention the youtube video it would be helpful. 

Thank you

**Comment by mariomax** [comment] 2024-01-13 20:12
These settings are found in WP Admin > Templates (below Elementor) > Popups >  Edit with Elementor > hover on the up arrow to the right of the main "Update" button > Save Options (Dispaly Conditions, Triggers, etc.) in the E Pro editor.
<img width="1202" alt="triggers" src="https://github.com/elementor/elementor/assets/26990513/29ffc972-7c2b-4df8-be0d-33408a20732b">

**Comment by freemartian** [comment] 2024-01-13 20:35
> These settings are found in WP Admin > Templates (below Elementor) > Popups > Edit with Elementor > hover on the up arrow to the right of the main "Update" button > Save Options (Dispaly Conditions, Triggers, etc.) in the E Pro editor. <img alt="triggers" width="1202" src="https://private-user-images.githubusercontent.com/26990513/296513132-29ffc972-7c2b-4df8-be0d-33408a20732b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUxNzg0MDksIm5iZiI6MTcwNTE3ODEwOSwicGF0aCI6Ii8yNjk5MDUxMy8yOTY1MTMxMzItMjlmZmM5NzItN2MyYi00ZGY4LWJlMGQtMzM0MDhhMjA3MzJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEzVDIwMzUwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkyYTNkMWIxOTMxYjMyZmVhODczMzc4MzY2MjBhNThiYjcxYzU2NTVmYmY3NzU3MTc2MTY0NWE3YmU2OTRiNTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-uagxduywM9jGrElaECamZiMpkxU6_AsqdAvWfch3jA">

You are a life save, thank you very much for this help.

**Comment by ahyanamoworks** [comment] 2024-02-06 05:51
> These settings are found in WP Admin > Templates (below Elementor) > Popups > Edit with Elementor > hover on the up arrow to the right of the main "Update" button > Save Options (Dispaly Conditions, Triggers, etc.) in the E Pro editor.

Thank you for this, in my case, I toggled on the "On Click" option on the "Triggers" section because I expected I could set the trigger element in this setting. Turns out that it was in a separate setting.

**Comment by DarkAthena** [comment] 2024-05-23 03:16
2024 now and it still works! I can't believe that Elementor hasn't fixed this. Thank you @mariomax you're the best!

**Comment by zara-rafiq** [comment] 2024-05-23 20:51
Hi @mariomax i tried your fix but sadly 😞 it didn’t work out for me, any alternative anybody tried to fix this issue of popup triggering on page load first click? Thanks!

**Comment by DarkAthena** [comment] 2024-05-23 21:24
@zara-rafiq 

Could you tell us what conditions you have selected?

**Comment by beastoked** [comment] 2024-08-05 04:54
> I figured out the problem by watching a tutorial. DO NOT select any triggers or conditions in the Popup settings. Only set the dynamic action in the button itself. Boom!

YOU ARE A HERO MARIO THANK YOU!

**Comment by kyleclaydotcom** [comment] 2025-01-23 17:46
> I figured out the problem by watching a tutorial. DO NOT select any triggers or conditions in the Popup settings. Only set the dynamic action in the button itself. Boom!

I was having an issue with the popup showing when I tried navigating away from the page that my popup was on (even though it was only set to open on click of a button). So I removed all conditions and triggers as suggested here and it works like a dream.
