### ISSUE TITLE
Extra BR's on Icon List Widget + From Submit buttons Pro Version 2.8.1

### ISSUE THREAD

**Issue by reachdigitalaus** [elementor/elementor#9928] opened 2019-12-19 07:08 UTC
I am facing an issue with the latest update, Edit mode looks ok but Live extra br's and spans are added. This produces unwanted spaces and misalignment. 

I see this on Icon List Widget + From Submit buttons

`<li class="elementor-icon-list-item">
					<a href="#" target="_blank" rel="noopener">						<span class="elementor-icon-list-icon"><br>
							<i aria-hidden="true" class="fab fa-facebook"></i>						</span><br>
										<span class="elementor-icon-list-text"></span><br>
											</a>
									</li>`

`<button type="submit" class="elementor-button elementor-size-sm"><br> <span><br> <span class=" elementor-button-icon"><br> </span><br> <span class="elementor-button-text">SUBMIT</span><br> </span><br> </button>`

**Comment by shilo-ey** [comment] 2019-12-19 08:43
Duplicate of #9927

**Closed by shilo-ey** 2019-12-19 08:43 UTC
