### ISSUE TITLE
Elementor popup event handler not working

### ISSUE THREAD

**Issue by edwardk1234** [elementor/elementor#10690] opened 2020-02-27 13:45 UTC
## Prerequisites
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

## Description
According to this post: https://developers.elementor.com/elementor-pro-2-7-popup-events/

We can easily use this JavaScript to execute stuff when popup is opened or closed.

I just tried inserting the following code into a html widget on the page where the popup is supposed to load.

```
<Script>

document.addEventListener( 'elementor/popup/show', () => { alert('1') } );

</Script>
```

However the alert of 1 does not show when the popup is opened. I tried placing the html widget in the header or footer and still it doesn't work.

I don't think the event trigger is working.

## Steps to reproduce
1. Create a popup
2. On the page where the popup is supposed to appear, create a HTML widget. This widget can be placed in the body, the header or the footer. I tried them all.
3. In the HTML widget, insert this code:
```
<Script>

document.addEventListener( 'elementor/popup/show', () => { alert('1') } );

</Script>
```
4. After the popup appears, an alert of 1 should show. However, it does not.

## Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a default WordPress theme active.
- [X] I can reproduce this bug consistently using the steps above.

## Environment
Will publish system information if really necessary as this is a work computer.

**Comment by luiszg** [comment] 2020-03-22 07:09
Exactly. Do you found a temporal solution?

**Comment by jackslayer1234** [comment] 2020-03-23 03:33
Nope, I have not found a solution yet.

**Comment by uriklar** [comment] 2020-03-24 20:06
I can confirm I am also trying to implement this event listener and it is not firing.

**Comment by aporiadin** [comment] 2020-04-10 23:37
Vanilla JS can't catch jQuery added events, so there is a workaround:
`jQuery( document ).on( 'elementor/popup/show' , function () { ... } );`

**Comment by jackslayer1234** [comment] 2020-04-11 02:54
> Vanilla JS can't catch jQuery added events, so you should use jQuery version:
> `jQuery( document ).on( 'elementor/popup/show' , function () { ... } );`

@aporiadin Will try it out and revert. Based on the example code on the website, I believe the below code for jquery should be used:

```
jQuery( document ).on( 'elementor/popup/show', (**event**, **id**, **instance**) => {
	// do your tracking here
} );
```

I understand how to change the popup ID. But how do you go about finding the event / instance of the popup?

**Comment by uriklar** [comment] 2020-04-11 10:01
Thanks @aporiadin! I was indeed using the vanilla js version. 
For completion's sake, here's the code I have in my Insert headers and footers plugin:
```
<script>
function registerPopupEvent() {
  window.jQuery(document).on('elementor/popup/show',(event, id, instance) => {
	console.log(event, id, instance);
  });
}
if (!window.jQuery) {
  setTimeout(registerPopupEvent, 500);
}

</script>
```

The docs show the vanilla version as well, so they might be misleading

**Comment by jebuske** [comment] 2020-04-13 11:44
Anyone found a solution? I'm trying to show an element when the popup closes but the eventhandler on elementor/popup/show doesn't seem to work.

**Comment by uriklar** [comment] 2020-04-16 05:23
@jebuske did you see my comment above your's? It works only when registering to it using jquery

**Comment by jebuske** [comment] 2020-04-16 13:11
@uriklar Thanks but I cannot get it to work. I've added exactly your code in header footer code manager but nothing is logged in the console

**Comment by jackslayer1234** [comment] 2020-04-16 13:31
@jebuske @uriklar Can confirm. Have tried it and still nothing shows in console. I modified the code slightly to show this. Does not work.

```
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js">
function registerPopupEvent() {
  window.jQuery(document).on('elementor/popup/show',(event, id, instance) => {
	console.log(event, id, instance);
  });
}
if (!window.jQuery) {
  setTimeout(registerPopupEvent, 500);
}

</script>
```

**Comment by pwkip** [comment] 2020-04-22 09:03
I've created a page to illustrate this problem: http://experiments.bdwm.be/elementor/

**Comment by anybany** [comment] 2020-04-22 09:36
this is what works for me:
`
jQuery(document).on('elementor/popup/show', () => { 
//your function here
});
`

habe a look at: https://rooja.jkjkjk.de/home3-ch-2/
the green play button triggers a popup which then triggers a swiper init...

**Comment by jackslayer1234** [comment] 2020-04-22 12:08
> this is what works for me:
> `jQuery(document).on('elementor/popup/show', () => { //your function here });`
> 
> have a look at: https://rooja.jkjkjk.de/home3-ch-2/
> the green play button triggers a popup which then triggers a swiper init...

@anybany . Thanks. Can you let me know where exactly are you placing your code? Are you creating a html widget and then insert the script?

I tried your code like this and inserted it into a HTML widget. I do not see anything in console.log.
```
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js">
jQuery(document).on('elementor/popup/show', () => {
console.log(event, id, instance);
}
);
</script>
```

**Comment by anybany** [comment] 2020-04-22 12:15
i am using a plugin which puts the js to the footer but it also worked in an html widget in the past. make sure you put it on the page where your popup trigger (eg. button) is and not in the popup itself ;)

**Comment by pwkip** [comment] 2020-04-22 12:28
Oh right, thanks. I can confirm the jQuery solution works.

http://experiments.bdwm.be/elementor/work-around/

**Comment by anybany** [comment] 2020-04-22 13:14
just use a button widget or any link in elementor. where you put in the link you see a little three stripes icon. You can choose popup there and then on the left is a wrench icon where you can search for your popup template ;)

**Comment by jebuske** [comment] 2020-04-22 13:28
It still doesn't work.
http://u51246p48935.web0100.zxcs-klant.nl/home-3 on this page if you click the "quartier bleu" button on the slide it opens a popup and the button disappears. If you close the popup the button should reappear but that doesn't happen..

Here is the code I'm using:
`jQuery(document).on('elementor/popup/hide', () => {
$('.elementor-element.elementor-element-74bfa08f').show();
}
);`

**Comment by anybany** [comment] 2020-04-22 13:45
@jebuske 
please try the following:
`

jQuery(document).on('elementor/popup/hide', () => { $('.elementor-element.elementor-element-74bfa08f').hide(); } );

`

**Comment by jebuske** [comment] 2020-04-22 13:50
doesn't work either but I tried to console.log("test"); and that does work

**Comment by jebuske** [comment] 2020-04-22 13:54
also tried with css hidden and visible but isn't working either

**Comment by anybany** [comment] 2020-04-22 14:01
@jebuske just had a look at the page you provided above and it seems the button doesn’t trigger a popup at all? If so nothing can be hidden on closing a popup that doesn’t exist ;)

**Comment by jebuske** [comment] 2020-04-22 14:06
You tried on mobile or ipad ? Because then there is indeed no button that triggers a popup. On desktop it should work fine

**Comment by jebuske** [comment] 2020-04-22 14:17
Got it to work! Thanks a lot for your help!
`<script> 
var $=jQuery.noConflict();
jQuery(document).ready(function( $ ){

   $('.elementor-element.elementor-element-74bfa08f').click(function() {
   $('.elementor-element.elementor-element-74bfa08f').hide();
   
    jQuery(document).on('elementor/popup/hide', () => {   $('.elementor-element.elementor-element-74bfa08f').show(); } );
 });
 

});

</script>

`

**Comment by jackslayer1234** [comment] 2020-04-22 15:03
@anybany Hey anybany, could you help me out, please?

Link: https://rebrand.ly/anybany

I still can't get it to work. Yellow button would open a popup. And then I want there to be some items in the console.log as shown in the code below.

Thank you.

```
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js">
jQuery(document).on('elementor/popup/show', () => {
console.log(event, id, instance);
}
);
</script>
```

**Comment by jebuske** [comment] 2020-04-22 15:19
Hi Jack,

If i'm not mistaken you can't log eventm id and instance if you dont put them like this:

```
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js">
jQuery(document).on('elementor/popup/show', (event, id, instance) => {
console.log(event, id, instance);
}
);
</script>
```

**Comment by jackslayer1234** [comment] 2020-04-22 15:26
> Hi @jackslayer1234,
> 
> If i'm not mistaken you can't log eventm id and instance if you dont put them like this:
> 
> ```
> <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js">
> jQuery(document).on('elementor/popup/show', (event, id, instance) => {
> console.log(event, id, instance);
> }
> );
> </script>
> ```

Hey @jebuske thanks for the reply. I tried your code and it didn't work. I have switched to something simpler to show a 1 in console log when the popup appears. However, there is nothing that appears in the console log when the popup appears. Any idea what is going wrong? Thanks.

```
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js">
jQuery(document).on('elementor/popup/show', () => {
console.log('1');
}
);
</script>
```

**Comment by jebuske** [comment] 2020-04-22 15:31
I've tried this and it works:

```
<script> 
var $=jQuery.noConflict();
jQuery(document).ready(function( $ ){

    jQuery(document).on('elementor/popup/show', () => { console.log("test"); } );

 

});

</script>


```

**Comment by jackslayer1234** [comment] 2020-04-22 15:37
Wow @jebuske thanks alot! Yes it worked!

**Comment by Pikamander2** [comment] 2020-04-30 11:35
Here's what I used to get it working:

```
jQuery(document).ready(function()
{
	jQuery( document ).on( 'elementor/popup/show' , function (){ console.log("Elementor popup shown") } );
	jQuery( document ).on( 'elementor/popup/hide' , function (){ console.log("Elementor popup hidden") } );
});
```

I don't understand why the pure JS version from [the official blog post](https://developers.elementor.com/elementor-pro-2-7-popup-events/) isn't working though.

@bainternet - Any idea what's happening here? Is the documentation wrong?

**Comment by pryley** [comment] 2020-05-05 20:13
They broke the vanilla event trigger in one of the last updates. Only the jQuery event works now.

**Comment by parasshah195** [comment] 2020-05-26 11:28
If someone's still looking for an optimal solution for this (the Elementor way), you should add the event listener to `elementorFrontend.elements.$document` when the `elementor/frontend/init` event occurs.

Example code:

```
(function( $ ) {
	$( window ).on( 'elementor/frontend/init', function() {
		elementorFrontend.elements.$document.on( 'elementor/popup/show', ( event, id ) => {
			 // process the show event 
		});
	});
})( jQuery );
```

**Note:** The popup document instance will not be passed because to your function (will return `undefined`) [jQuery `.trigger()` docs](https://api.jquery.com/trigger/) state that extra parameters need to be in an array or plainObject as a single param, whereas E Pro sends it as 2 separate parameters which is not valid.

**Comment by pryley** [comment] 2020-06-06 22:24
This is how I ended up handling it: #11306

**Comment by udidol** [comment] 2021-02-23 07:58
Hi all,
We have updated the documentation (https://developers.elementor.com/elementor-pro-2-7-popup-events/).
The Vanilla JS example indeed does not work, and it has been removed.
The jQuery example has been tested and works.

**Closed by udidol** 2021-02-23 07:58 UTC

**Comment by shilo-ey** [comment] 2021-02-23 17:56
This issue has been resolved in Elementor Pro v3.1.1

Feel free to update

Thanks!

**Comment by davidmgrana** [comment] 2022-09-26 16:18
hello there, it is not clear to me how to retrieve the button that triggered the popup

**Comment by stasonua0** [comment] 2022-12-10 14:16
In version 3.9 it was broken again

**Comment by MogulChris** [comment] 2022-12-11 22:02
Yes this is broken again in 3.9. As a workaround:

`jQuery( window ).on( 'elementor/frontend/init', () => {
    elementorFrontend.elements.$window.on('elementor/popup/show', ( event ) => {
        if(event.originalEvent.detail.id == 840){ //popup's WordPress ID
            //do something
        }
    });    
});`

**Comment by Tibebu-ES** [comment] 2022-12-12 15:19
window.addEventListener( 'elementor/popup/show', ( event )=>{
	const id = event.detail.id;
	const instance = event.detail.instance;
	
	if( id === 123 ) {
		// do your magic here
		console.log( 'elementor/popup/show', id )
	}

})

This works. 
But now the event target is the window not the actual element that triggers the event. 
On the older version, I simply use the following to get data passed from the triggering element.  
jQuery(event.target.activeElement).data("user-id")
Now this is not working after v3.9.

**Comment by mnemotiv** [comment] 2022-12-14 06:30
temporary workaround (backwards compatibility):

```js
window.addEventListener( 'elementor/popup/show', function ( e ) {
	$( document ).trigger( 'elementor/popup/show', [ e.detail.id, e.detail.instance ] );
} );

window.addEventListener( 'elementor/popup/hide', function ( e ) {
	$( document ).trigger( 'elementor/popup/hide', [ e.detail.id, e.detail.instance ] );
} );
```

of course, there's "Elementor way" to work with events, but...

**Comment by aylonmelos1** [comment] 2024-09-12 00:04
Just reforcing, this yet works:

`jQuery(document).on('elementor/popup/show', () => {  //your function here });`

**Comment by eduardovillao** [comment] 2025-01-08 14:15
If you don't want to use `jQuery` you can use this "workaround" to use vanilla JS. Basically you will hear the changes in the body and when the Popup modal is inserted you can do whatever you want.

```
const body = document.body;

const observer = new MutationObserver((mutations) => {
    mutations.forEach((mutation) => {
        if (mutation.type === "childList") {
            mutation.addedNodes.forEach((node) => {
                if (node.classList && node.classList.contains("elementor-popup-modal")) {
                    console.log("Modal injetado no body:", node);
                   // add what you need to do here.
                }
            });
        }
    });
});

observer.observe(body, { childList: true });```
