### ISSUE TITLE
🔗 🚀 Feature Request: Accordion - setting for all closed at start (Duplicate of #2756)

### ISSUE THREAD

**Issue by medieskolenlyngby** [elementor/elementor#20393] opened 2022-11-14 11:47 UTC
### Prerequisites

- [ ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

We need a possibility to close all tabs at start on the accordion

I found a old closed request .... with a lot of work arounds .... we need at stable "out of the box" solution to this issue!!
(last comment on that was datet a week ago ... but still closed)

### Describe the solution you'd like

Just the possibility to have a choice (first tab open or closed)

### Describe alternatives you've considered

I'm not alone .... [https://www.google.com/search?q=elementor+accordion+how+to+close+first+tab](https://www.google.com/search?q=elementor+accordion+how+to+close+first+tab)

### Additional context

The best woraround I found was adding this script (Elementor > Custom Code)

`<script>
jQuery(document).ready(function($) {
var wait = 50; setTimeout(function() {
$('.elementor-tab-title').removeClass('elementor-active');
 $('.elementor-tab-content').css('display', 'none'); }, wait);
});
</script>`

**Comment by nicholaszein** [comment] 2022-11-15 14:25
Hello @medieskolenlyngby!

Thank you for your submission! 🙏 

### 🔗 This issue is a Duplicate of #2756

Which is on the same subject. 

For this reason, I'm closing this issue and 🔃 **Merging** it with the original, so we can have all the discussions in one location, and deal with it more efficiently.

Feel free to continue the conversation there. 😉 

### ✔️ Please, in the future, remember to check if there isn't an issue similar to yours already opened. 

Best regards,

Nick

**Closed by nicholaszein** 2022-11-15 14:25 UTC
Labels: request/enhancement, solved_by_nested, component/accordion
