### ISSUE TITLE
🔗 🐞 Bug Report: Containers inside Nested Tabs lose their style after switching tabs (Duplicate of #21639)

### ISSUE THREAD

**Issue by umairfarooquu** [elementor/elementor#21883] opened 2023-04-01 06:47 UTC
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

I found this bug while using the nested tab as I set the nested tab inner column horizontal but when I click the next tab the previous one goes into vertical.

### Steps to reproduce

[video-convert-1680283239900_xOvqWDqh.webm](https://user-images.githubusercontent.com/61369825/229270336-f38ddaa5-7488-4df2-a3e4-bf9637c24e2b.webm)

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

[system-info.txt](https://github.com/elementor/elementor/files/11128659/system-info.txt)

**Comment by nicholaszein** [comment] 2023-05-28 03:26
Hello @XXX!

Thank you for your submission! 🙏 

### 🔗 🐞 This issue is a Duplicate of #21639 

Which is on the same subject. 

For this reason, I'm closing this thread and 🔃 **Merging** it with the original, so we can have all the discussions in one location, and deal with it more efficiently.

Feel free to continue the conversation there. 😉 

### 🔍 Please, in the future, remember to check if there isn't any thread similar to yours already opened. 

Best regards,

Nick

**Closed by nicholaszein** 2023-05-28 03:26 UTC
Labels: type/layout, mod*, component/nested/tabs
