### ISSUE TITLE
🔗 ⛔ Smooth Scrolling Conflict (Duplicate of #29103) 

### ISSUE THREAD

**Issue by syart7** [elementor/elementor#29508] opened 2024-12-05 08:52 UTC
### Prerequisites

- [ ] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [ ] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

Hi,
I noticed that in Elementor version **3.24.8**, smooth scrolling worked perfectly in my theme. However, in newer versions, I’m experiencing an issue with the "Back to Top" button—it glitches slightly when scrolling back up. When I roll back to version 3.24.8, the issue is resolved.

Has anyone else encountered this problem or found a solution?

### Expected behavior

Adding the following CSS fixes the "Back to Top" button issue:

html {  
    scroll-behavior: auto !important;  
}  
However, this breaks anchor links by causing them to jump directly to the target instead of smooth scrolling.

Here’s a preview of the issue: [Watch Video](https://www.awesomescreenshot.com/video/34332655?key=77848d19ba6d8b4f06e4d9e9dc56f51c)

### Isolating the problem

- [ ] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [ ] This bug happens with the Hello Elementor theme active.
- [ ] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

<details>
<summary>Click to reveal</summary>

````txt


== Server Environment ==
	Operating System: FreeBSD
	Software: Apache
	MySQL version: FreeBSD Ports v10.6.19
	PHP Version: 8.1.31
	PHP Memory Limit: 256M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 64M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.7.1
	WP Multisite: No
	Max Upload Size: 64 MB
	Memory limit: 40M
	Max Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: de_DE
	Timezone: Europe/Zurich
	Debug Mode: Inactive

== Theme ==
	Name: REFIVE Child Theme
	Version: 1.1
	Author: REFIVE
	Child Theme: Yes
	Parent Theme Name: REFIVE
	Parent Theme Version: 1.1
	Parent Theme Author: REFIVE

== User ==
	Role: administrator
	WP Profile lang: de
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36

== Active Plugins ==
	All-in-One WP Migration
		Version: 7.87
		Author: ServMask

	All-in-One WP Migration Unlimited Extension
		Version: 2.63
		Author: ServMask

	Duplicate Page
		Version: 4.5.4
		Author: mndpsingh287

	Elementor
		Version: 3.24.8
		Author: Elementor.com

	Elfsight Cookie Consent CC
		Version: 1.1.1
		Author: Elfsight

	Elfsight Google Maps CC
		Version: 2.4.1
		Author: Elfsight

	Floatton by Phpbits
		Version: 2.0
		Author: Phpbits Creative Studio

	Gravity Forms
		Version: 2.9.0
		Author: Gravity Forms

	Imagify
		Version: 2.2.3.2
		Author: Imagify Image Optimizer – Optimize Images & Convert WebP & Avif

	Loco Translate
		Version: 2.6.14
		Author: Tim Whitlock

	Qi Addons for Elementor
		Version: 1.8.1
		Author: Qode Interactive

	Qode Essential Addons
		Version: 1.6.4
		Author: Qode Interactive

	String Locator
		Version: 2.6.6
		Author: InstaWP

	User Role Editor
		Version: 4.64.3
		Author: Vladimir Garagulya

	WP Activity Log
		Version: 5.2.2
		Author: Melapress

	WP Mail SMTP
		Version: 4.2.0
		Author: WP Mail SMTP

	WP Rollback
		Version: 2.0.7
		Author: WP Rollback

	Yoast SEO
		Version: 24.0
		Author: Team Yoast


== Elementor-Experimente ==
	Verbessertes Laden von CSS: Standardmäßig deaktiviert
	Inline-Schriftarten-Symbole: Standardmäßig deaktiviert
	Additional Custom Breakpoints: Standardmäßig aktiviert
	Flexbox Container: Standardmäßig deaktiviert
	Grid Container: Standardmäßig aktiviert
	Upgrade Swiper Library: Standardmäßig aktiviert
	Nested Elements Performance: Standardmäßig aktiviert
	Optimized Control Loading: Standardmäßig deaktiviert
	Optimized Markup: Standardmäßig deaktiviert
	Conditionally load Swiper CSS files: Standardmäßig deaktiviert
	Plugin Onboarding: Standardmäßig aktiviert
	Elementor Home Screen: Standardmäßig aktiviert
	Build with AI: Standardmäßig aktiviert
	Startseiten: Standardmäßig aktiviert
	Launchpad Checklist: Standardmäßig deaktiviert
	Nested Elements: Standardmäßig deaktiviert
	Editor Top Bar: Standardmäßig deaktiviert
	Element Caching: Standardmäßig deaktiviert
	Link In Bio: Standardmäßig aktiviert
	Floating Buttons: Standardmäßig aktiviert
	Elementor Editor Events: Standardmäßig deaktiviert
	Atomic Widgets: Standardmäßig deaktiviert



Log: showing 20 of 342024-11-18 13:38:52 [info] elementor::elementor_updater Started 
2024-11-18 13:38:52 [info] Elementor/Upgrades - _on_each_version Start  
2024-11-18 13:38:52 [info] Elementor/Upgrades - _on_each_version Finished 
2024-11-18 13:38:52 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.23.4',
  'to' => '3.25.7',
)]
2024-11-18 13:38:52 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.23.4',
  'to' => '3.25.7',
)]
2024-11-19 12:58:15 [info] elementor::elementor_updater Started 
2024-11-19 12:58:15 [info] Elementor/Upgrades - _on_each_version Start  
2024-11-19 12:58:15 [info] Elementor/Upgrades - _on_each_version Finished 
2024-11-19 12:58:15 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.25.7',
  'to' => '3.25.8',
)]
2024-11-19 12:58:15 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.25.7',
  'to' => '3.25.8',
)]
2024-11-22 08:34:08 [info] elementor::elementor_updater Started 
2024-11-22 08:34:08 [info] Elementor/Upgrades - _on_each_version Start  
2024-11-22 08:34:08 [info] Elementor/Upgrades - _on_each_version Finished 
2024-11-22 08:34:08 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.25.8',
  'to' => '3.25.9',
)]
2024-11-22 08:34:08 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.25.8',
  'to' => '3.25.9',
)]
2024-12-05 09:25:31 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.25.9',
  'to' => '3.25.10',
)]
2024-12-05 09:25:31 [info] elementor::elementor_updater Started 
2024-12-05 09:25:31 [info] Elementor/Upgrades - _on_each_version Start  
2024-12-05 09:25:31 [info] Elementor/Upgrades - _on_each_version Finished 
2024-12-05 09:25:31 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.25.9',
  'to' => '3.25.10',
)]



== Elementor - Compatibility Tag ==
	
	Qi Addons for Elementor: Die Kompatibilität ist nicht angegeben

````

</details>

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by hein-obox** [comment] 2024-12-08 05:51
Can you try to delete this styling: 

```
html {
scroll-behavior: auto !important;
}
```

Reason: previously Elementor used JavaScript to handle the scrolling on the page, but we have replace that with a CSS solution that also use `scroll-behavior`. Your code might break our new logic.

**Comment by nicholaszein** [comment] 2024-12-24 18:44
Hello @syart7!

Thank you for your submission! 🙏 

### 🔗 🐞 This issue is a Duplicate of [#29103](https://github.com/elementor/elementor/issues/29103#issuecomment-2444788808)

Which is on the same subject. 

Please refer to [this answer](https://github.com/elementor/elementor/issues/29103#issuecomment-2444788808) about 3rd-party plugins that affect smooth scrolling. Qi Addons seems to be using some type of smooth scrolling.

### 🔍 Please, in the future, remember to check if there isn't any thread similar to yours already opened. 

Kind regards

**Closed by nicholaszein** 2024-12-24 18:44 UTC
Labels: compatibility/3rd-party, mod*, duplicate, component/smooth-scroll
