### ISSUE TITLE
Global Colors disappears in live view

### ISSUE THREAD

**Issue by Iconicdigitalw** [elementor/elementor#12412] opened 2020-09-04 09:45 UTC
-->

## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Steps to reproduce
1. Install a fresh Wordpress 
2. Install elementor latest version and Elementor Pro
3. Activate coming soon/maintenance mode (seems this triggers the issue)
4. Design with Elementor and use global colors
5. View live page and the global colors will disappear. Only the custom colors you select will show. Any global color will not show. 
6. If coming soon is active and you view as administrator, the issue may not come up, but the moment you deactivate coming soon, global colors either grays out (before last Elementor update) or does not even show at all (after new Elementor update).
7. Presently, the screenshot shows how a page I designed for coming soon looks on live view.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
https://pastebin.com/1YybGzPt

**Comment by fabianenzensperger** [comment] 2020-09-04 14:58
Look here #12363

**Comment by worldoptimizer** [comment] 2020-09-05 00:23
+1

**Comment by arielk** [comment] 2020-09-06 08:05
Duplicate of #12363 

Thanks for your reporting!

**Closed by arielk** 2020-09-06 08:05 UTC
