### ISSUE TITLE
🔗 🚀 Feature Request: Editing Elementor from a mobile (from dashboard) (Duplicate of #482)

### ISSUE THREAD

**Issue by MaximeCulea** [elementor/elementor#6865] opened 2019-01-24 10:46 UTC
Following https://twitter.com/elemntor/status/1088378071290429440

I would like to suggest a new feature which consist in adding the Elementor editing (from dashboard) from a mobile support.

We some clients which need this feature.

**Comment by shilo-ey** [comment] 2019-01-24 11:36
Duplicate of #482

**Closed** 2019-01-24 11:36 UTC
Labels: request/enhancement, type/responsive, type/ui/ux, component/editor, type/workflow, mod*
