### ISSUE TITLE
bugs bugs bugs - social icon widget / forms... - bugs bugs bugs

### ISSUE THREAD

**Issue by dasigna** [elementor/elementor#13248] opened 2020-12-07 15:44 UTC
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and can find (of course) unresolved duplicates.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

currently completely baffled up to complete disappointment regarding the ongoing errors and bugs. e.g.:

social icons widget:
you cant get this thing done right. it behaves completely erratic.
different rendering logged in or out - what looks good while editing is going strange on frontend while logged out.
- no padding of icons
- alignment not at all where set
etc. etc.
impossible even to tweak it per custom code due to the completely erratic occurrances depending whether logged in or out, browser or viewport.

steps form:
totally going strange for weeks or even months.
steps are buggy up to not being useable; even while editing. what is the use of wysiwyg when the form always jumps to step one as soon as indending to edit a field on step 2, 3 or 4? ... and more of these.
currently not able to use this at all.

these are only two examples of a lot more, and they are up here since a long time e.g. #13178 or #13118 - not to mention several closed ones.
and remember: these are not even feature requests! these are simply bugs!

to be honest i dont even want to open support tickets via 'pro-support' any more. you wont get anywhere eighter way. waiting a week or more to have them asking back silly questions several times untill you're desperate enough to stop the conversation or they're demanding time consuming screencasts from customers (!) for things they might find out by themselves in seconds. even with credentials you'll likely always get a response like "we couldnt reproduce" etc. this is crazy.

so what is 'support' or this github place finally good for?

elementor always states the amount of third party plugins you can (better: might) ditch off whilst using elementor. currently we're needing third party things to get native things done that elementor doesnt repair.
is this supposed to be in the spirit of the inventor? 

honestly, by the time being i am deeply disappointed in every which way. this (elementor) is a great tool... essentially.
but what is even a good tool worth for if youre constantly struggling bugs everywhere?

no use for a mercedes if it wont take you from A to B or if it spends more time at the repair shop than on the road.
... and even the repair shop states "sorry we cant help" or "please be patient another while".
is this supposed to be the tool youre working with?
this is a tool i am paying for and is supposed to earn money with. really?

what the hell is going on at elementor? i am loosing my hopes this is going somewhere at all ...

## Steps to reproduce

already stated several times before ...
create a (step) form or social icons widget and inspect within elementor as well on frontend - logged in or not.
lots of surprises.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
no matter what environment
```
</details>

**Comment by Aviad-Herman** [comment] 2020-12-08 15:43
I hear you loud and clear.
You raise real issues. After version 3.0.0 was released we have started investing much needed effort into the prevention of these weird UI bugs and glitches.

Although I can't promise you when the specific bugs you raised will be resolved, I hope you don't give up and continue raising the alarm whenever we screw up. We appreciate your voice.

I'm going to pass this to QA and they will find and write the exact steps to reproduce. I am also going to close this issue, not because it's been solved but to acknowledge I heard you loud and clear. Message received.

Thanks for the feedback

**Closed by Aviad-Herman** 2020-12-08 15:43 UTC
Labels: bug
