### ISSUE TITLE
⛔ 🧩 jQuery compatibility issue with Gravity Forms

### ISSUE THREAD

**Issue by jscontentleaders** [elementor/elementor#10672] opened 2020-02-26 14:08 UTC
To whomever it may concern:

We've recently noticed with the build of a small website that there seems to be an issue with shortcodes in template areas:

Specifically, we've added a gravity form(3rd party plugin, not at fault as it works in regular WP) in a template area and loaded this template on another page. When you do this, it generates errors with jQuery in the console log if this element is loaded as the last element. Makes it so that the jQuery needed for the form is broken.

**Comment by nicholaszein** [comment] 2024-04-28 04:04
Hello!

Thank you for your contribution and your patience.

After reviewing your report we concluded this isn't a bug caused by Elementor in its latest version (v3.21). Therefore we are closing this issue.

Kind regards.

**Closed by nicholaszein** 2024-04-28 04:04 UTC
Labels: compatibility/3rd-party, mod*, widget/shortcode
