### ISSUE TITLE
Elementor 3.0 Issues 

### ISSUE THREAD

**Issue by EquilibriumTechx** [elementor/elementor#12224] opened 2020-08-25 14:12 UTC
## Prerequisites

- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [ ] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by shilo-ey** [comment] 2020-08-25 16:08
Hi @EquilibriumTechx 

Thanks for sharing this input,

Could you please elaborate on which error are you seeing?

Thanks

**Comment by Luxamman** [comment] 2020-08-25 16:36
Seems we have also problems: 

- Site is not well formatted anymore, seems the fonts are missing or not loading. 
- Dashboard is dead - /wp-admin/index.php is just a code side now (see below)
- Version rollback is not working, tells me "Your license has not been activated for this domain, please activate it first.". I have reactivated the licence, still the same problem...  

Not sure if everything is because of the 3.0 update, but I rolled back WordPress to 5.4.2 after jQuery Problems and still have the problems. Also deactivated most of the not necessary plugins. 

Site has Elementor, WooCommerce and WPML, WP Media Folder. Pods and Yoast. Essential Addons, Elementor Extras and Jet Elements. 

--

Dashboard starts like: 
<!DOCTYPE html>


<html xmlns="http://www.w3.org/1999/xhtml" class="wp-toolbar"
	lang="de-DE"	>

<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
`<!DOCTYPE html>


<html xmlns="http://www.w3.org/1999/xhtml" class="wp-toolbar"
	lang="de-DE"	>

<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />`

**Comment by ethandmiller** [comment] 2020-08-25 16:48
Updated to 3.0.0 and wp dashboard loaded fine. Thereafter everything else including my sit only showed code in Chrome. But for some reason, with about a 10 second lag in load, it worked in Safari. Other than the WP Dashboard, nothing else worked in in Chrome though. Even the Backup Plugins I had installed, so I pulled yesterdays BU from my server. Works fine now, but I'll wait til issues get ironed out before I update again.

**Comment by OSITOPARDO123** [comment] 2020-08-25 16:57
Hi everyone, I'm new in this topic (I'm student but not of programing or anything similar, so sorry if I make a mistake).
I'm creating my first site on wordpress and I'm using Elementor ( a wonder for all new people in wordpress).
But with the new actualization of Elementor , the plugin makes my admin-page not work correctly , It makes all pages not work in the main menu: I can not see any page, I can not edit pages or plugins, I can not hide the main menu, I can open the help or options screen.

I can deactivate the plugin: renaming it  in my archives in my cPanel and it disables it; but I really like it and I need it.

I have the latest version of Elementor and  Wordpress and PHP.
I will add my list of plugins (maybe it could be and incompatibility bug but I don't know how to fix it) and few images of the problem.

Thanks for your attention and sorry because of my disability

PTT: I found this error code (no idea if it could be useful):
 { "message" ; "Server error, see Elementor => System Info" } 

![My plugins](https://user-images.githubusercontent.com/70219827/91204692-1054da00-e6ca-11ea-8d72-9d93b226ff40.png)
<img width="1652" alt="Example two" src="https://user-images.githubusercontent.com/70219827/91204702-13e86100-e6ca-11ea-9330-f38ba596c150.png">
<img width="1652" alt="Example three" src="https://user-images.githubusercontent.com/70219827/91204704-1480f780-e6ca-11ea-811d-8f6d59942d0c.png">
<img width="1655" alt="Example one" src="https://user-images.githubusercontent.com/70219827/91204705-1480f780-e6ca-11ea-8ddd-f4acf7e233ad.png">
<img width="1652" alt="Error Code" src="https://user-images.githubusercontent.com/70219827/91204707-15198e00-e6ca-11ea-98ff-8dbe01732234.png">

**Comment by Luxamman** [comment] 2020-08-25 18:17
Dashboard is working after update to 3.0.1, Products are also back. Still problems with site appearance of fonts and some elements.

**Comment by zeinnicholas** [comment] 2020-08-26 00:51
> @Luxamman Luxamman commented 8 hours ago
> * Version rollback is not working, tells me "Your license has not been activated for this domain, please activate it first.". I have reactivated the license, still the same problem...

@shilo-ey It seems this issue is happening with all Pro rollbacks, no matter what version you're in, but most importantly, it doesn't allow to rollback from 3.0...

I made a Loom screencast to show you the issue live:

https://www.loom.com/share/2dd470012e294f448c05405bd397d64f

Please note that I purposefully concealed my credentials during the recording (using the Stylebot Chrome Extension).

<details>
<summary>System Info</summary>
```
					
== Server Environment ==
	Operating System: Linux
	Software: nginx/1.19.0
	MySQL version: mariadb.org binary distribution v10.4.13
	PHP Version: 7.4.7
	PHP Max Input Vars: 10000
	PHP Max Post Size: 2048M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.5
	Site URL: https://nzein.com
	Home URL: https://nzein.com
	WP Multisite: No
	Max Upload Size: 2 GB
	Memory limit: 512M
	Permalink Structure: /%category%/%postname%/
	Language: en-US
	Timezone: America/Sao_Paulo
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.3.0
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.135 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 3.0.1
		Author: Elementor.com

	Elementor Pro
		Version: 3.0.0
		Author: Elementor.com

	Wordfence Security
		Version: 7.4.10
		Author: Wordfence


== Elements Usage ==
	
	wp-post : 0
		heading : 2
		image : 1
		text-editor : 1
		theme-site-logo : 1


== Log ==
	

				
```
</details>

**Comment by BAtiyat** [comment] 2020-08-26 12:47
Hi guys, well here are my issues with the 3.0.1, even after i rolled back to 3.0.1, still having to fix each one by one again, many things didn't go back to original design

I found over 20 things got screwed up with this update (from 3.0.0 to 3.0.1), and i'm not gonna open over 20 tickets.
Many things went out of wack, i.e....
- Icon sizes got changed
- I con hover responses (Grow is now more of a Side-Stretch, not Grow)
- More than half of the colors got changed
- Alignment went totally insane
- The Menu got doubled (now my menu has 2 of each item/page)
- The color tray is not user friendly (saved colors now in a List, not a palette, so to find your saved color you have to scroll, and if you have many, like in my case, then it's not practical)
-  When you try to save/add a customized color, a pop comes up (are you sure you want to create a new global color?) come on guys, this is way too impractical, the older palette was much easier and quicker
- Another color palette issue, the "CLEAR" button is gone, so to clear you have to slide the overlay slider, if you delete the code from the bottom of the color palette pop-up, nothing happens, it goes back to the same color
- I have a slider on my home page (Smart Slider), got pushed down
- A big problem when you go to Responsive mode, some changes don't show in the editor, you have to go to the mobile device (phone or ipad) to see if it worked (so far the buttons' changes don't show when i go to mobile/ipad mode in the editor, so back and forth between devices)

I did rollback to 3.0.0, even with re-installing the backup file, still many things didn't go back to how i had before, so I'm editing all AGAIN manually

Maybe it's time for me to find another builder

**Comment by shannonreed** [comment] 2020-08-26 13:36
Chiming in to add that all of our sites which were updated to WP 5.5. and that use Elementor were also broken. In the middle of a build in an environment that loaded 5.5 from the outset - and - Elementor 2.9.14 - started out ok, then a whole new fun thing started to happen - nothing. Nothing happened. I'd make a style change - nothing; the program saved my design settings, but nothing actually happened to indicate a change. I updated to 3.0.1 and my entire site crashed. Reverted to the backup - just stuck until this gets resolved. 

It's baffling that this seems like such an obvious issue as javascript deprecation appears to be causing the breakdown (I also tried utilizing the JQuery Migrate Helper plugin which helped on some of our other sites in a sort of hit/miss way, so it's definitely not THE fix); where are the Authors in Elementor? Like, seriously - what's being done? Where's the communication on this nightmare.

**Comment by Soulfire909** [comment] 2020-08-26 19:02
Yes, guys this is a massive issue... releasing v3 before v3 of pro broke everything. Then today new version of pro causes elementor to become unlicensed... these updates are concerning.

**Comment by bellamystudio** [comment] 2020-08-27 10:53
V3 is not ready for production! How has it been released as a non-beta version? Duplicating sections doesn't work, deleting sections seems to dismantle them element by element rather than removing the whole block. I've had to fix every site that's been updated and I'm in a situation now where I can't reliably build pages with the editor on either Firefox or Safari.

This is the first update that's really broken a lot of fundamentals and doesn't seem to have gone through any sort of QA process. Frustrating and disappointing.

**Comment by drawcard** [comment] 2020-08-27 11:04
I have reported another issue elsewhere that I think is connected to this ongoing list of jQuery related issues: #12283

**Comment by BAtiyat** [comment] 2020-08-27 11:12
3.0.2 just got released, i'm afraid to try it...lol
When I upgraded from 3.0.0 to 3.0.1, and faced all that madness, I rolled back to 3.0.1, but all the problems stayed, so I had to re-fix all manually again.
Anyone tried the 3.0.2 yet?

**Comment by drawcard** [comment] 2020-08-27 11:15
@BAtiyat this happened to me as well after upgrading to WP 5.5 on another website running Elementor. 

It was like the CSS fragment files were completely nuked, as if there was no styling loading up on any of my pages at all. All of the JS and CSS that Elementor created was lost. Regenerating CSS did nothing, and it was too late to roll back the core update.

The workaround I had was to open up every affected page in the Elementor editor, and roll back to a previously edited version of the page, and then hit Apply > Update. That seemed to get rid of what ever corrupted fragment files that caused the page rendering problems.

I didn't take a screenshot of any of the broken stuff sadly, nor did I log a report here, as I was too damn busy putting out the massive bonfire this update created. However I thought I'd share this workaround here in case anyone else faces the same problem after upgrading WP to 5.5 while running Elementor.

Also to answer your other question, I'm currently running 3.0.2 on another affected website, but I am not game enough to update that site to 5.5 until we get some solid answers here about what exactly is going on...

**Comment by BAtiyat** [comment] 2020-08-27 11:26
@drawcard - GOOD GOD, you had it much worse than me.
Before i upgrade I did an XML back up, so when I rolled back I uploaded the XML file, it brought back several things that were still in shape, but many were thrown out of wack, colors, fonts, alignments, buttons...it was a mess, but WOW, yours is much worse.... and on multiple site??? yayks, mine is only one site

Thanks for answering the 3.0.2 Question, I'll try it

I'm not as versed into it as you are, still new, but i'm shocked how something like this gets released, and not even in Beta, seems like it was not tested well before releasing.

I'll see how the new one pans out.

**Comment by drawcard** [comment] 2020-08-27 11:33
@BAtiyat luckily I've only run updates on a couple of those sites so far, I'm definitely holding off until we have more news :) 

But what you're describing with the pages looking all messed up is pretty much what I was staring at the other day. Reverting to a previously saved version in the Revisions tab helped me out, hopefully it will do the same for anyone else.

**Comment by BAtiyat** [comment] 2020-08-27 12:13
@drawcard cool idea, i didn't even look into the revisions...lol
Yeah, hope this helps others

I appreciate it

**Comment by qwik3r** [comment] 2020-08-27 13:34
Multiple javascript errors reported after updating from 3.0 to 3.02 releating to frontend.min.js which also messed up things like the vertical scrolling animation etc. https://github.com/elementor/elementor/issues/12275. 

After downgrading via tools to 3.0 for both Elementor and Pro, when I would go to update a post, any post, even newly created ones, I would get a red bar at the top saying "error updating check elementor logs" (or something similar to that).

**Comment by portrayaloflife** [comment] 2020-08-29 18:54
@qwik3r Confirm I'm seeing a ton of Frontend.min.js errors too that affect all animations to not work or just hide elements outright. So frustrating. 

![image](https://user-images.githubusercontent.com/24360965/91644159-15ce5f00-e9ff-11ea-98db-79bb1b8c1555.png)

**Comment by Luxamman** [comment] 2020-09-02 12:40
Still problems with a new created site:  

- Global Colors are displayed correctly in the editor, but not on the actual page. So h2 for example is not blue, like it should be, but just black.
- Global Colors also wont work in backgrounds. Displayed correctly in the editor, but not on the actual page.  
- Global Font settings are displayed correctly in the editor, but not on the actual page. So h2 text is for example not uppercase.

When I give the h2 a color and a style - overwriting the global settings, everything works.
No cache, WP 5.5.1 and Elementor 3.0.5 and Pro 3.0.2. Renew CSS also not working here.

**Comment by qwik3r** [comment] 2020-09-02 13:23
> Still problems with a new created site:
> 
> * Global Colors are displayed correctly in the editor, but not on the actual page. So h2 for example is not blue, like it should be, but just black.
> * Global Colors also wont work in backgrounds. Displayed correctly in the editor, but not on the actual page.
> * Global Font settings are displayed correctly in the editor, but not on the actual page. So h2 text is for example not uppercase.
> 
> When I give the h2 a color and a style - overwriting the global settings, everything works.
> No cache, WP 5.5.1 and Elementor 3.0.5 and Pro 3.0.2. Renew CSS also not working here.

Have you followed the instructions for clearing local storage, regenerating the css under 'tool's etc?

**Comment by Luxamman** [comment] 2020-09-02 13:35
> > Still problems with a new created site:
> > 
> > * Global Colors are displayed correctly in the editor, but not on the actual page. So h2 for example is not blue, like it should be, but just black.
> > * Global Colors also wont work in backgrounds. Displayed correctly in the editor, but not on the actual page.
> > * Global Font settings are displayed correctly in the editor, but not on the actual page. So h2 text is for example not uppercase.
> > 
> > When I give the h2 a color and a style - overwriting the global settings, everything works.
> > No cache, WP 5.5.1 and Elementor 3.0.5 and Pro 3.0.2. Renew CSS also not working here.
> 
> Have you followed the instructions for clearing local storage, regenerating the css under 'tool's etc?

Yes, regenerate CSS couple times, changed how CSS is delivered (external to internal) and I'm always in incognito mode for displaying front end to avoid problems. Because of a hurry we coded some global CSS to bring fonts, styles and colors to the front end - but it is funny, that in the Elementor editor, everything is just fine.

**Comment by qwik3r** [comment] 2020-09-02 14:02
> > > Still problems with a new created site:
> > > 
> > > * Global Colors are displayed correctly in the editor, but not on the actual page. So h2 for example is not blue, like it should be, but just black.
> > > * Global Colors also wont work in backgrounds. Displayed correctly in the editor, but not on the actual page.
> > > * Global Font settings are displayed correctly in the editor, but not on the actual page. So h2 text is for example not uppercase.
> > > 
> > > When I give the h2 a color and a style - overwriting the global settings, everything works.
> > > No cache, WP 5.5.1 and Elementor 3.0.5 and Pro 3.0.2. Renew CSS also not working here.
> > 
> > 
> > Have you followed the instructions for clearing local storage, regenerating the css under 'tool's etc?
> 
> Yes, regenerate CSS couple times, changed how CSS is delivered (external to internal) and I'm always in incognito mode for displaying front end to avoid problems. Because of a hurry we coded some global CSS to bring fonts, styles and colors to the front end - but it is funny, that in the Elementor editor, everything is just fine.

Could be a caching issue with your server's host. Are you using any aggressive caching or plugins that combine the css files that could be interrupting css file delivery?

**Comment by Luxamman** [comment] 2020-09-02 14:26
No caching, were an agency with lots of experience and dozens of websites running, we use caching tools but of course not when developing new sites. Also, when changing global colors to fix colors for elements, everything is working like it should. We also had to "downdate" to Elementor 2.9 in some cases, because of same problems on running sites and we don't update any site now till everything is running smoothly. But we have at least 3 sites with the same problems...

**Comment by portrayaloflife** [comment] 2020-09-02 15:43
I'm experiencing the same issue, works in editor but not front end

**Comment by BAtiyat** [comment] 2020-09-08 20:02
I'm still experiencing more and more new issues everyday with this, even with these updates, anyone having any luck?
The latest issue is when I add a new page, the size of a new page/canvas is not the same, so when I copy some elements/sections from other pages, they're not the same fit, the sections are much smaller when I paste them on the newly created page, I'm guessing the canvas is bigger? even though everything is set the same size...???

**Comment by qwik3r** [comment] 2020-09-08 20:40
Experiencing the same thing now myself.

**Comment by BAtiyat** [comment] 2020-09-09 09:07
Sections/Columns in Mobile view are much tighter than originally designed.
Is there an end to this? I don't see anything from the Elementor guys, are they even concerned about any of this? is there a Support team?
Well, at least it makes for a great $h!t article about their product and support, i will be writing about this soon, and I think everyone should

**Comment by jonathansoltero** [comment] 2020-11-20 01:44
> > > Still problems with a new created site:
> > > 
> > > * Global Colors are displayed correctly in the editor, but not on the actual page. So h2 for example is not blue, like it should be, but just black.
> > > * Global Colors also wont work in backgrounds. Displayed correctly in the editor, but not on the actual page.
> > > * Global Font settings are displayed correctly in the editor, but not on the actual page. So h2 text is for example not uppercase.
> > > 
> > > When I give the h2 a color and a style - overwriting the global settings, everything works.
> > > No cache, WP 5.5.1 and Elementor 3.0.5 and Pro 3.0.2. Renew CSS also not working here.
> > 
> > 
> > Have you followed the instructions for clearing local storage, regenerating the css under 'tool's etc?
> 
> Yes, regenerate CSS couple times, changed how CSS is delivered (external to internal) and I'm always in incognito mode for displaying front end to avoid problems. Because of a hurry we coded some global CSS to bring fonts, styles and colors to the front end - but it is funny, that in the Elementor editor, everything is just fine.

Can you open an issue in regards to this? I am also experiencing this on my websites.

**Comment by Aviad-Herman** [comment] 2021-07-12 22:18
Hi everyone,
Since version 3.0 we have implemented several measures to prevent QA issues:

**Automated QA regression tests**
Every version is tested with an automated process that checks all widgets in many configurations. This includes visual regression testing to reduce risk of site UI being affected.

**Longer Beta phase and Developer Edition Plugin**
Each feature is tested longer before being released to the general public.

**Elementor Experiments**
Most new features are released as experiments so they can quickly be turned off by the user in Elementor --> Settings in case they cause bugs.

**Faster Patches**
We've improved our delivery process so we can release patches faster in case of a problem.


We tracked the number of bugs over the last few versions and we've seen a great improvement.
I'm going to close this issue but I want to thank everyone personally for the help, your support is greatly appreciated.

If any bugs still persist, feel free to open a new thread. Thanks everyone!

**Closed by Aviad-Herman** 2021-07-12 22:18 UTC
