### ISSUE TITLE
[bug] pro gallery single doesnt show lightbox navigation

### ISSUE THREAD

**Issue by dasigna** [elementor/elementor#9229] opened 2019-10-01 13:16 UTC
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

unless i am missing something basic this is an major issue:
when using pro gallery widget an setting the type to 'single' there are now arrows shown in lightbox to navigate through the images.
they are there when setting multiple galleries, but then you have one completely useless filter entry if only one gallery is needed...
that makes absolutely no sense.

if it is intended - it makes no sense to me at all.
if it is unintended ...

please change it either way :)

## Steps to reproduce

see before

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
not provided - unnecessary

```
</details>

**Comment by mediatreeindia** [comment] 2019-10-03 12:12
I can confirm this issue too.

**Comment by srcek** [comment] 2019-10-09 10:02
Same problem here!

**Comment by jus303** [comment] 2019-10-16 17:29
Almost two weeks without a fix? This quite a major one guys n gals!

**Comment by Hoffl-GitHub** [comment] 2019-10-19 13:43
Same problem, the single gallery is not usable if there is no slide navigation in the lightbox. So only the multiple gallery can be used and than you need a css hack or delete the gallery name

**Comment by srcek** [comment] 2019-10-20 16:43
I'd like to add that there's an old issue with lightbox display on mobile. When clicked/tapped images are displayed smaller on screen to make room for lightbox controls. It would probably be more intuitive to display zoomed in image instead, or maybe offer zoom in/out controls. Controls should be on the image on mobile view instead of outside.

But lightbox navigation is essential. Really hope you'll resolve this problem soon.

**Comment by samuelcerezo** [comment] 2019-10-23 10:38
Any update with this bug?

**Comment by jus303** [comment] 2019-10-24 14:49
> I think this is a mishap not a bug.

Sure but it was there now it is not - its been a long time...

**Comment by Psychopomp777** [comment] 2019-10-25 13:31
Please update. This bug/mishap is now up for 4 weeks! That's way too long!

**Comment by PPjev** [comment] 2019-10-27 11:32
Same problem here.

**Comment by Psychopomp777** [comment] 2019-10-28 21:20
Okay, with E-Pro 2.7.3 this problem is being fixed now. Thanks! But now you can skip through all the photos if they are on the same page, even if they are in different galleries (on the same page). Is there any way to prevent this? It is very irritating for the user, if he opens a gallery with dogs and suddenly ends up with the cat photos, just because they are on the same page, but in a separate gallery. In the basic gallery widget you can only skip through the photos of the respective gallery. That's how the Pro Gallery should work as well, no!?

**Closed** 2020-01-16 10:38 UTC

**Comment by FredBaros** [comment] 2020-03-25 17:55
I'm having an issue with Elementor Pro 2.9.2 Gallery Widget. The lightbox doesn't work with the single gallery. Any solution?

**Comment by kovacevicivan** [comment] 2020-04-17 20:06
Same problem with me. Here are hte settings, https://www.dropbox.com/s/073beey8sbkb7xh/Screenshot%202020-04-17%2022.05.29.png?dl=0

I cant navigate when photo is opened in a single-mode gallery.

**Comment by svranakis** [comment] 2025-03-14 14:30
Still this issue after 5 years... This doesn't look too good to say the least...
