### ISSUE TITLE
🐞 Bug report: Section background image URL is hardcoded with an absolute path preventing the ability to use CDN

### ISSUE THREAD

**Issue by dangub** [elementor/elementor#19529] opened 2022-08-18 15:22 UTC
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

When I use a background image for a section, the CSS contains the **_absolute image's URL_** (including the domain and the protocol scheme) in the resulting CSS `background-image:url(...)`. This causes a W3 Total Cache plugin (and others) to not being able to use a CDN for this URL, even if the CSS file itself is delivered via a CDN.

The expected result is for the CSS to contain a **_relative URL_**, e.g. `background-image:url("\wp-content\uploads\image.jpg)` - this should result in the image being retrieved from the same origin as the CSS.

### Steps to reproduce

1. Add a section
2. Add image background by selecting the image from the media library
3. Observe the generated CSS as containing an absolute URL
4. Use W3TC plugin (or another) to set up a CDN
5. Observe the the image is delivered from the non-CDN domain

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.54 () OpenSSL/1.0.2k-fips
	MySQL version: MariaDB Server v10.5.10
	PHP Version: 8.0.20
	PHP Memory Limit: 128M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 10M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.0.1
	Site URL: https://www.legallycanadian.com
	Home URL: https://www.legallycanadian.com
	WP Multisite: No
	Max Upload Size: 10 MB
	Memory limit: 256M
	Max Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: America/Toronto
	Admin Email: admin@legallycanadian.com
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.6.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 3.7.1
		Author: Elementor.com

	Elementor Blocks for Gutenberg
		Version: 1.0.1
		Author: Elementor.com

	Elementor Pro
		Version: 3.7.3
		Author: Elementor.com

	Google XML Sitemaps
		Version: 4.1.5
		Author: Auctollo

	GTM4WP
		Version: 1.16.1
		Author: Thomas Geiger

	Post SMTP
		Version: 2.1.4
		Author: Post SMTP

	Redirection
		Version: 5.3.2
		Author: John Godley

	W3 Total Cache
		Version: 2.2.4
		Author: BoldGrid

== Elementor Experiments ==
	Optimized DOM Output: Inactive by default
	Improved Asset Loading: Active
	Improved CSS Loading: Active
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Inactive by default
	Additional Custom Breakpoints: Inactive by default
	Import Export Template Kit: Active by default
	Hide native WordPress widgets from search results: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Inactive by default
	Default to New Theme Builder: Active by default
	Hello Theme Header & Footer: Inactive by default
	Landing Pages: Active by default
	Color Sampler: Active by default
	Favorite Widgets: Active by default
	Admin Top Bar: Active by default
	Page Transitions: Active by default
	Notes: Active by default
	Form Submissions: Active by default
	Scroll Snap: Active by default

== Log ==
	
Log: showing 20 of 292022-08-13 00:55:42 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.1.3',
  'to' => '3.7.0',
)]
2022-08-13 00:55:42 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.1.3',
  'to' => '3.7.0',
)]
2022-08-13 01:34:09 [info] elementor-pro::elementor_pro_updater Started 
2022-08-13 01:34:09 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-08-13 01:34:09 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-08-13 01:34:09 [info] Elementor Pro/Upgrades - _v_3_7_2_woocommerce_rename_related_to_related_products Start  
2022-08-13 01:34:09 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.1.1',
  'to' => '3.7.3',
)]
2022-08-13 01:34:09 [info] Elementor Pro/Upgrades - _v_3_7_2_woocommerce_rename_related_to_related_products Finished 
2022-08-13 01:34:09 [info] Elementor Pro/Upgrades - _v_3_3_0_nav_menu_icon Start  
2022-08-13 01:34:10 [info] Elementor Pro/Upgrades - _v_3_3_0_nav_menu_icon Finished 
2022-08-13 01:34:10 [info] Elementor Pro/Upgrades - _v_3_3_0_recalc_usage_data Start  
2022-08-13 01:34:10 [info] Elementor Pro/Upgrades - _v_3_3_0_recalc_usage_data Finished 
2022-08-13 01:34:10 [info] Elementor Pro/Upgrades - _v_3_5_0_price_list Start  
2022-08-13 01:34:10 [info] Elementor Pro/Upgrades - _v_3_5_0_price_list Finished 
2022-08-13 01:34:10 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.1.1',
  'to' => '3.7.3',
)]
2022-08-15 15:55:27 [info] elementor::elementor_updater Started 
2022-08-15 15:55:27 [info] Elementor/Upgrades - _on_each_version Start  
2022-08-15 15:55:27 [info] Elementor/Upgrades - _on_each_version Finished 
2022-08-15 15:55:27 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.0',
  'to' => '3.7.1',
)]
2022-08-15 15:55:27 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.0',
  'to' => '3.7.1',
)]

PHP: showing 8 of 8PHP: 2022-08-13 00:55:42 [notice X 49][/var/www/html/wordpress/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::304] The $control_id argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-08-13 01:05:32 [error X 2][/var/www/html/wordpress/wp-content/plugins/elementor-pro/modules/theme-builder/documents/theme-document.php::46] Uncaught ReflectionException: Method ElementorPro\Modules\ThemeBuilder\Documents\Section::get_site_editor_type() does not exist in /var/www/html/wordpress/wp-content/plugins/elementor-pro/modules/theme-builder/documents/theme-document.php:46
Stack trace:
#0 /var/www/html/wordpress/wp-content/plugins/elementor-pro/modules/theme-builder/documents/theme-document.php(46): ReflectionClass->getMethod('get_site_editor...')
#1 /var/www/html/wordpress/wp-content/plugins/elementor-pro/modules/theme-builder/documents/theme-document.php(127): ElementorPro\Modules\ThemeBuilder\Documents\Theme_Document::get_site_editor_type_bc()
#2 /var/www/html/wordpress/wp-content/plugins/elementor/core/common/modules/finder/categories/create.php(94): ElementorPro\Modules\ThemeBuilder\Documents\Theme_Document::get_create_url()
#3 /var/www/html/wordpress/wp-content/plugins/elementor/core/common/modules/finder/categories/create.php(67): Elementor\Core\Common\Modules\Finder\Categories\Create->create_item_url_by_document_class('ElementorPro\\Mo...')
#4 /var/www/html/wordpress/wp-content/plugins/elementor/core/common/modules/finder/base-category.php(92): Elementor\Core\Common\Modules\Finder\Categories\Create->get_category_items()
#5 /var/www/html/wordpress/wp-content/plugins/elementor/core/base/base-object.php(142): Elementor\Core\Common\Modules\Finder\Base_Category->get_init_settings()
#6 /var/www/html/wordpress/wp-content/plugins/elementor/core/base/base-object.php(40): Elementor\Core\Base\Base_Object->ensure_settings()
#7 /var/www/html/wordpress/wp-content/plugins/elementor/core/common/modules/finder/module.php(107): Elementor\Core\Base\Base_Object->get_settings()
#8 /var/www/html/wordpress/wp-content/plugins/elementor/core/base/base-object.php(142): Elementor\Core\Common\Modules\Finder\Module->get_init_settings()
#9 /var/www/html/wordpress/wp-content/plugins/elementor/core/base/base-object.php(40): Elementor\Core\Base\Base_Object->ensure_settings()
#10 /var/www/html/wordpress/wp-content/plugins/elementor/core/base/app.php(59): Elementor\Core\Base\Base_Object->get_settings()
#11 /var/www/html/wordpress/wp-content/plugins/elementor/core/base/app.php(36): Elementor\Core\Base\App->get_components_config()
#12 /var/www/html/wordpress/wp-content/plugins/elementor/core/common/app.php(153): Elementor\Core\Base\App->print_config()
#13 /var/www/html/wordpress/wp-includes/class-wp-hook.php(307): Elementor\Core\Common\App->register_scripts('index.php')
#14 /var/www/html/wordpress/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters(NULL, Array)
#15 /var/www/html/wordpress/wp-includes/plugin.php(476): WP_Hook->do_action(Array)
#16 /var/www/html/wordpress/wp-admin/admin-header.php(118): do_action('admin_enqueue_s...', 'index.php')
#17 /var/www/html/wordpress/wp-admin/index.php(137): require_once('/var/www/html/w...')
#18 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-08-13 01:05:39 [error X 6][/var/www/html/wordpress/wp-content/plugins/elementor-pro/modules/theme-builder/documents/theme-document.php::46] Uncaught ReflectionException: Method ElementorPro\Modules\ThemeBuilder\Documents\Section::get_site_editor_type() does not exist in /var/www/html/wordpress/wp-content/plugins/elementor-pro/modules/theme-builder/documents/theme-document.php:46
Stack trace:
#0 /var/www/html/wordpress/wp-content/plugins/elementor-pro/modules/theme-builder/documents/theme-document.php(46): ReflectionClass->getMethod('get_site_editor...')
#1 /var/www/html/wordpress/wp-content/plugins/elementor-pro/modules/theme-builder/documents/theme-document.php(127): ElementorPro\Modules\ThemeBuilder\Documents\Theme_Document::get_site_editor_type_bc()
#2 /var/www/html/wordpress/wp-content/plugins/elementor/core/common/modules/finder/categories/create.php(94): ElementorPro\Modules\ThemeBuilder\Documents\Theme_Document::get_create_url()
#3 /var/www/html/wordpress/wp-content/plugins/elementor/core/common/modules/finder/categories/create.php(67): Elementor\Core\Common\Modules\Finder\Categories\Create->create_item_url_by_document_class('ElementorPro\\Mo...')
#4 /var/www/html/wordpress/wp-content/plugins/elementor/core/common/modules/finder/base-category.php(92): Elementor\Core\Common\Modules\Finder\Categories\Create->get_category_items()
#5 /var/www/html/wordpress/wp-content/plugins/elementor/core/base/base-object.php(142): Elementor\Core\Common\Modules\Finder\Base_Category->get_init_settings()
#6 /var/www/html/wordpress/wp-content/plugins/elementor/core/base/base-object.php(40): Elementor\Core\Base\Base_Object->ensure_settings()
#7 /var/www/html/wordpress/wp-content/plugins/elementor/core/common/modules/finder/module.php(107): Elementor\Core\Base\Base_Object->get_settings()
#8 /var/www/html/wordpress/wp-content/plugins/elementor/core/base/base-object.php(142): Elementor\Core\Common\Modules\Finder\Module->get_init_settings()
#9 /var/www/html/wordpress/wp-content/plugins/elementor/core/base/base-object.php(40): Elementor\Core\Base\Base_Object->ensure_settings()
#10 /var/www/html/wordpress/wp-content/plugins/elementor/core/base/app.php(59): Elementor\Core\Base\Base_Object->get_settings()
#11 /var/www/html/wordpress/wp-content/plugins/elementor/core/base/app.php(36): Elementor\Core\Base\App->get_components_config()
#12 /var/www/html/wordpress/wp-content/plugins/elementor/core/common/app.php(153): Elementor\Core\Base\App->print_config()
#13 /var/www/html/wordpress/wp-includes/class-wp-hook.php(307): Elementor\Core\Common\App->register_scripts('')
#14 /var/www/html/wordpress/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters(NULL, Array)
#15 /var/www/html/wordpress/wp-includes/plugin.php(476): WP_Hook->do_action(Array)
#16 /var/www/html/wordpress/wp-includes/script-loader.php(2156): do_action('wp_enqueue_scri...')
#17 /var/www/html/wordpress/wp-includes/class-wp-hook.php(307): wp_enqueue_scripts('')
#18 /var/www/html/wordpress/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters(NULL, Array)
#19 /var/www/html/wordpress/wp-includes/plugin.php(476): WP_Hook->do_action(Array)
#20 /var/www/html/wordpress/wp-includes/general-template.php(3042): do_action('wp_head')
#21 /var/www/html/wordpress/wp-content/themes/hello-elementor/header.php(21): wp_head()
#22 /var/www/html/wordpress/wp-includes/template.php(770): require_once('/var/www/html/w...')
#23 /var/www/html/wordpress/wp-includes/template.php(716): load_template('/var/www/html/w...', true, Array)
#24 /var/www/html/wordpress/wp-includes/general-template.php(48): locate_template(Array, true, true, Array)
#25 /var/www/html/wordpress/wp-content/themes/hello-elementor/index.php(15): get_header()
#26 /var/www/html/wordpress/wp-includes/template-loader.php(106): include('/var/www/html/w...')
#27 /var/www/html/wordpress/wp-blog-header.php(19): require_once('/var/www/html/w...')
#28 /var/www/html/wordpress/index.php(17): require('/var/www/html/w...')
#29 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-08-13 01:13:09 [error X 2][/var/www/html/wordpress/wp-content/plugins/elementor-pro/modules/theme-builder/documents/theme-document.php::46] Uncaught ReflectionException: Method ElementorPro\Modules\ThemeBuilder\Documents\Section::get_site_editor_type() does not exist in /var/www/html/wordpress/wp-content/plugins/elementor-pro/modules/theme-builder/documents/theme-document.php:46
Stack trace:
#0 /var/www/html/wordpress/wp-content/plugins/elementor-pro/modules/theme-builder/documents/theme-document.php(46): ReflectionClass->getMethod('get_site_editor...')
#1 /var/www/html/wordpress/wp-content/plugins/elementor-pro/modules/theme-builder/documents/theme-document.php(127): ElementorPro\Modules\ThemeBuilder\Documents\Theme_Document::get_site_editor_type_bc()
#2 /var/www/html/wordpress/wp-content/plugins/elementor/core/common/modules/finder/categories/create.php(94): ElementorPro\Modules\ThemeBuilder\Documents\Theme_Document::get_create_url()
#3 /var/www/html/wordpress/wp-content/plugins/elementor/core/common/modules/finder/categories/create.php(67): Elementor\Core\Common\Modules\Finder\Categories\Create->create_item_url_by_document_class('ElementorPro\\Mo...')
#4 /var/www/html/wordpress/wp-content/plugins/elementor/core/common/modules/finder/base-category.php(92): Elementor\Core\Common\Modules\Finder\Categories\Create->get_category_items()
#5 /var/www/html/wordpress/wp-content/plugins/elementor/core/base/base-object.php(142): Elementor\Core\Common\Modules\Finder\Base_Category->get_init_settings()
#6 /var/www/html/wordpress/wp-content/plugins/elementor/core/base/base-object.php(40): Elementor\Core\Base\Base_Object->ensure_settings()
#7 /var/www/html/wordpress/wp-content/plugins/elementor/core/common/modules/finder/module.php(107): Elementor\Core\Base\Base_Object->get_settings()
#8 /var/www/html/wordpress/wp-content/plugins/elementor/core/base/base-object.php(142): Elementor\Core\Common\Modules\Finder\Module->get_init_settings()
#9 /var/www/html/wordpress/wp-content/plugins/elementor/core/base/base-object.php(40): Elementor\Core\Base\Base_Object->ensure_settings()
#10 /var/www/html/wordpress/wp-content/plugins/elementor/core/base/app.php(59): Elementor\Core\Base\Base_Object->get_settings()
#11 /var/www/html/wordpress/wp-content/plugins/elementor/core/base/app.php(36): Elementor\Core\Base\App->get_components_config()
#12 /var/www/html/wordpress/wp-content/plugins/elementor/core/common/app.php(153): Elementor\Core\Base\App->print_config()
#13 /var/www/html/wordpress/wp-includes/class-wp-hook.php(307): Elementor\Core\Common\App->register_scripts('plugins.php')
#14 /var/www/html/wordpress/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters(NULL, Array)
#15 /var/www/html/wordpress/wp-includes/plugin.php(476): WP_Hook->do_action(Array)
#16 /var/www/html/wordpress/wp-admin/admin-header.php(118): do_action('admin_enqueue_s...', 'plugins.php')
#17 /var/www/html/wordpress/wp-admin/plugins.php(605): require_once('/var/www/html/w...')
#18 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-08-13 02:25:12 [warning X 38][/var/www/html/wordpress/wp-content/plugins/elementor-pro/modules/forms/classes/form-record.php::179] Undefined array key "referrer" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-08-13 22:55:40 [warning X 7][/var/www/html/wordpress/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined array key "data" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-08-16 02:39:34 [warning X 1][/var/www/html/wordpress/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::167] Undefined array key "editor_post_id" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-08-16 02:55:12 [error X 1][/var/www/html/wordpress/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::294] Uncaught Error: Call to a member function update_meta() on bool in /var/www/html/wordpress/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:294
Stack trace:
#0 /var/www/html/wordpress/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(167): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions(NULL, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /var/www/html/wordpress/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /var/www/html/wordpress/wp-includes/class-wp-hook.php(307): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#4 /var/www/html/wordpress/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters('', Array)
#5 /var/www/html/wordpress/wp-includes/plugin.php(476): WP_Hook->do_action(Array)
#6 /var/www/html/wordpress/wp-admin/admin-ajax.php(187): do_action('wp_ajax_element...')
#7 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 5 of 5JS: 2022-08-13 16:30:50 [error X 1][https://www.legallycanadian.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.7.0:3:570480] Cannot read properties of null (reading \'id\') 
JS: 2022-08-13 20:40:07 [error X 14][https://www.legallycanadian.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.7.0:3:766552] Cannot read properties of undefined (reading \'localized\') 
JS: 2022-08-14 00:17:13 [error X 3][https://www.legallycanadian.com/wp-content/plugins/elementor/assets/js/common-modules.min.js?ver=3.7.0:2:51471] Model.isValidChild() should be implemented, please provide \'isValidChild\' functionality. 
JS: 2022-08-16 05:57:38 [error X 1][https://www.legallycanadian.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.7.1:3:766783] Cannot read properties of undefined (reading \'toLowerCase\') 
JS: 2022-08-16 17:34:38 [error X 1][https://www.legallycanadian.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.7.1:3:1060434] Cannot read properties of null (reading \'getBoundingClientRect\') 

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatible

== Elementor Pro - Compatibility Tag ==

**Comment by arielk** [comment] 2022-08-22 22:15
Duplicate of https://github.com/elementor/elementor/issues/10838

**Closed by arielk** 2022-08-22 22:15 UTC
Labels: bug
