### ISSUE TITLE
PHP warning on the Recalculate elements usage button click

### ISSUE THREAD

**Issue by obiPlabon** [elementor/elementor#10706] opened 2020-02-29 18:48 UTC
![Recalculate Button](https://user-images.githubusercontent.com/10244644/75613259-a8c43480-5b55-11ea-8c11-d886e77d6d7e.jpg)

_I'm getting the following PHP warning after clicking on the Recalculate button (above)_

![PHP Warning](https://user-images.githubusercontent.com/10244644/75613256-a3ff8080-5b55-11ea-8f7f-c6798dd1ab12.jpg)

**Environment details -**

== Server Environment ==
	Operating System: Linux
	Software: nginx/1.10.1
	MySQL version: (Debian) v5.5.60
	PHP Version: 7.0.3
	PHP Max Input Vars: 3000
	PHP Max Post Size: 1000M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.3.2
	Site URL: http://myground.local
	Home URL: http://myground.local
	WP Multisite: No
	Max Upload Size: 1,000 MB
	Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.2.2
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 2.9.3
		Author: Elementor.com

	Which Elementor Addon
		Version: 1.0.0
		Author: obiPlabon

== Elements Usage ==
	wp-page : 1
		heading : 1

**Comment by arielk** [comment] 2020-08-20 11:38
Thanks for reporting, we couldn't reproduce the issue so I'm closing this issue for now feel free to reopen if the issue persists.

**Closed by arielk** 2020-08-20 11:38 UTC
