### ISSUE TITLE
🔗 🐞 Bug Report: Regular issues with having to regenerate CSS Files on various websites all on the same server (Duplicate of #4464)

### ISSUE THREAD

**Issue by PurpleWebCreative** [elementor/elementor#23721] opened 2023-09-10 17:28 UTC
### Prerequisites

- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

We run a server with over 40 sites all ecommerce and all using Elementor with WordPress. The sites are all up to date with the latest version of WP and Elementor Pro. We are having to set a weekly routine task of checking all the sites in incognito as we are finding a handle each week where the CSS files are messed up. We have a mixture of sites that are using WP fastest cache and we have some we haven't cached and the same issue happens. 

We have to find a resolution to this because otherwise we will be forced to look at alternative page builders!!!

I would just like to add that the Server these sites are all on is the same server we hve had for nearly a year now but these issues have only been in the last 3/4 months. I do have a support ticket logged with them too so i am just hoping someone can give me answers.

### Steps to reproduce

The only way to fix the issue is to Regen CSS files which i get is a very easy task but sometimes these sites are going undetected for a while before we check them and this will be causing a lot of issues with my clients in terms of missed orders and customer confidence in the site. 

We have looked at this for weeks now and have started to keep a log of which sites it is affecting. We are noticing some sites are more likely to break than others. There is no relationship between the sites other than they are on the same web server with Krystal. 

We have tried the community on Facebook and was advised there are certain settings in the advanced area that we can disable. We were also led to believe that it could be linked to adding additional breakpoints. 

We have also established its not linked to a particular theme as we are seeing issues regardless which theme has been used. 

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently following the steps above.

### System Info

This information is from one affected site but we currently have 5 broken sites from my last routine check. 

<details>
<summary>Click to reveal</summary>

````txt

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MariaDB Server v10.3.39
	PHP Version: 7.4.33
	PHP Memory Limit: 128M
	PHP Max Input Vars: 8000
	PHP Max Post Size: 512M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.2.2
	Site URL: https://ringrosebutchers.co.uk
	Home URL: https://ringrosebutchers.co.uk
	WP Multisite: No
	Max Upload Size: 512 MB
	Memory limit: 40M
	Max Memory limit: 256M
	Permalink Structure: /%postname%
	Language: en-GB
	Timezone: Europe/London
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor Child
	Version: 1.0
	Author: PurpleWeb
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.7.1
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: en_GB
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36

== Active Plugins ==
	Ban Hammer
		Version: 3.1.2
		Author: Mika Epstein

	Booster for WooCommerce
		Version: 6.0.6
		Author: Pluggabl LLC

	Broken Link Checker
		Version: 2.2.2
		Author: WPMU DEV

	Checkout Field Editor for WooCommerce
		Version: 1.9.0
		Author: ThemeHigh

	Child Theme Wizard
		Version: 1.4
		Author: Jay Versluis

	Duplicate Menu
		Version: 0.2.2
		Author: Jonathan Christopher

	Elementor
		Version: 3.15.3
		Author: Elementor.com

	Elementor Pro
		Version: 3.15.1
		Author: Elementor.com

	Email Template Customizer for WooCommerce
		Version: 1.1.22
		Author: VillaTheme

	Envato Elements
		Version: 2.0.12
		Author: Envato

	Fake Pay For WooCommerce
		Version: 1.1.0
		Author: Anthony Graddy

	Google Listings and Ads
		Version: 2.4.11
		Author: WooCommerce

	Mailchimp for WooCommerce
		Version: 3.2
		Author: Mailchimp

	ManageWP - Worker
		Version: 4.9.17
		Author: GoDaddy

	Order Delivery Date Pro for WooCommerce
		Version: 10.4.0
		Author: Tyche Softwares

	PageSpeed Ninja
		Version: 0.9.45
		Author: PageSpeed Ninja

	Post SMTP
		Version: 2.5.8
		Author: Post SMTP

	Redirection
		Version: 5.3.10
		Author: John Godley

	Show User Registration Date
		Version: 1.0.0
		Author: Carlos Martínez Romero

	Velvet Blues Update URLs
		Version: 3.2.10
		Author: VelvetBlues.com

	WebP Express
		Version: 0.25.6
		Author: Bjørn Rosell

	WooCommerce
		Version: 8.0.3
		Author: Automattic

	WooCommerce Square
		Version: 4.2.0
		Author: WooCommerce

	Wordfence Security
		Version: 7.10.3
		Author: Wordfence


== Must-Use Plugins ==
	ManageWP - Worker Loader
		Version: 1.0.0
		Author: GoDaddy


== Elements Usage ==
	
	footer : 1
		heading : 5
		icon-list : 1
		nav-menu : 2
		social-icons : 1
		text-editor : 1
	header : 2
		heading : 3
		icon : 8
		icon-list : 2
		image : 4
		nav-menu : 4
		woocommerce-menu-cart : 4
	page : 5
		heading : 1
		image : 1
		woocommerce-cart : 1
		woocommerce-checkout-page : 1
		woocommerce-my-account : 1
	popup : 2
		heading : 1
		nav-menu : 1
		search-form : 1
	product : 1
		woocommerce-product-add-to-cart : 1
		woocommerce-product-data-tabs : 1
		woocommerce-product-images : 1
		woocommerce-product-meta : 1
		woocommerce-product-price : 1
		woocommerce-product-rating : 1
		woocommerce-product-short-description : 1
		woocommerce-product-title : 1
	section : 1
		button : 1
		nav-menu : 1
		social-icons : 1
		theme-site-logo : 1
	wp-page : 12
		call-to-action : 22
		divider : 1
		facebook-embed : 1
		form : 1
		google_maps : 1
		heading : 4
		icon-box : 3
		icon-list : 1
		image-gallery : 6
		slides : 1
		text-editor : 15
		woocommerce-cart : 1
		woocommerce-checkout-page : 1
		woocommerce-my-account : 1
	search-results : 1
		heading : 1
		icon-list : 1
		nav-menu : 1
		woocommerce-products : 1
	product-archive : 1
		heading : 1
		icon-list : 1
		nav-menu : 1
		woocommerce-products : 1
	error-404 : 1
		heading : 3


== Settings ==
	
	cpt_support: post, page
	disable_color_schemes: yes
	disable_typography_schemes: yes
	allow_tracking: yes
	css_print_method: internal
	unfiltered_files_upload: 1


== Features ==
	Custom Fonts: 0
	Custom Icons: 0

== Integrations ==
	
	recaptcha_v3: Active
	woocommerce: Active


== Elementor Experiments ==
	Optimised DOM Output: Inactive
	Improved asset loading: Inactive
	Improved CSS Loading: Inactive
	Inline Font Icons: Inactive by default
	Additional Custom Breakpoints: Active
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Inactive by default
	Upgrade Swiper Library: Inactive by default
	Grid Container: Inactive by default
	Default to New Theme Builder: Active by default
	Hello Theme Header & Footer: Inactive by default
	Editor Top Bar: Inactive by default
	Landing pages: Active by default
	Nested Elements: Inactive by default
	Lazy Load Background Images: Active
	Global Style Guide: Inactive by default
	Page Transitions: Active by default
	Notes: Active by default
	Loop: Active by default
	Form Submissions: Active by default
	Scroll Snap: Active by default
	Menu: Inactive by default
	Taxonomy Filter: Inactive by default


== Log ==
	
Log: showing 20 of 372023-04-02 21:57:22 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-04-02 21:57:22 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-04-02 21:57:22 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.12.0',
  'to' => '3.12.1',
)]
2023-04-02 21:57:22 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.12.0',
  'to' => '3.12.1',
)]
2023-04-23 09:56:30 [info] elementor::elementor_updater Started 
2023-04-23 09:56:30 [info] Elementor/Upgrades - _on_each_version Start  
2023-04-23 09:56:31 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.12.1',
  'to' => '3.12.2',
)]
2023-04-23 09:56:31 [info] Elementor/Upgrades - _on_each_version Finished 
2023-04-23 09:56:31 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.12.1',
  'to' => '3.12.2',
)]
2023-04-24 13:01:15 [info] elementor-pro::elementor_pro_updater Started 
2023-04-24 13:01:15 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-04-24 13:01:15 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-04-24 13:01:15 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.12.1',
  'to' => '3.12.3',
)]
2023-04-24 13:01:16 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.12.1',
  'to' => '3.12.3',
)]
2023-05-08 14:48:21 [info] elementor::elementor_updater Started 
2023-05-08 14:48:21 [info] Elementor/Upgrades - _on_each_version Start  
2023-05-08 14:48:21 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.12.2',
  'to' => '3.13.0',
)]
2023-05-08 14:48:21 [info] Elementor/Upgrades - _on_each_version Finished 
2023-05-08 14:48:21 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.12.2',
  'to' => '3.13.0',
)]
2023-05-08 14:48:22 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.12.2',
  'to' => '3.13.0',
)]

PHP: showing 5 of 5PHP: 2023-03-30 16:29:45 [notice X 4][../wp-content/plugins/elementor/includes/conditions.php::87] Undefined index: cart_layout [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-04-03 16:35:56 [notice X 561][../wp-content/plugins/elementor/includes/conditions.php::87] Undefined index: checkout_layout [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-04-23 15:11:56 [notice X 2939][../wp-content/plugins/elementor-pro/modules/woocommerce/module.php::381] Undefined offset: 1 [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-07-11 17:35:16 [notice X 1][../wp-content/plugins/elementor/core/common/modules/ajax/module.php::175] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-08-04 13:41:21 [notice X 3][../wp-content/plugins/elementor-pro/modules/forms/classes/recaptcha-v3-handler.php::124] Undefined index: score [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]



== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatible
	Envato Elements: Incompatible

== Elementor Pro - Compatibility Tag ==
	
	Envato Elements: Incompatible
				

````

</details>

**Comment by PurpleWebCreative** [comment] 2023-09-10 17:57
https://github.com/elementor/elementor/issues/4464#issuecomment-1631476032 @opticalresolution

Did your issues get resolved

**Comment by nicholaszein** [comment] 2023-09-12 21:04
Hello @PurpleWebCreative!

Thank you for your submission! 🙏 

### 🔗 🐞 This issue is a Duplicate of #4464

Which is on the same subject. 

For this reason, I'm closing this thread and 🔃 **Merging** it with the original, so we can have all the discussions in one location, and deal with it more efficiently.

Feel free to continue the conversation there. 😉 

### 🔍 Please, in the future, remember to check if there isn't any thread similar to yours already opened. 

Kind regards

**Closed by nicholaszein** 2023-09-12 21:04 UTC
Labels: type/responsive, component/document, type/experiment, mod*, component/document/page-assets
