### ISSUE TITLE
 Elementor canvas option doesn't work

### ISSUE THREAD

**Issue by darkstudio** [elementor/elementor#9745] opened 2019-12-02 14:27 UTC
ELEMENTOR CANVAS option not working.
The Header and Footer still showing when elementor canvas is selected on new created page with elementor. Normaly when elementor canvas is selected, we have a blank page.
Elementor V2.7.5
Wordpress 5.3

**Comment by shilo-ey** [comment] 2019-12-02 15:05
Hi @darkstudio 


Thanks for your feedback.

We can't reproduce your issue,
Please contact our support at support @elementor.com for guidance in resolving this issue and reference this issue.

thanks.

**Closed by shilo-ey** 2019-12-02 15:05 UTC

**Comment by darkstudio** [comment] 2019-12-02 15:21
Impossible, the elementor support work only with PRO version. here is a free version.
See this animated gif, i think that the issue is not hard to understand:
[https://ibb.co/k2X65rt](url)
thanks

**Comment by Alan-Senderovich** [comment] 2023-10-23 23:33
Hi there!
I'm having exactly the same problem as @darkstudio shows above. Is there any help or advice?

Thank you very much for your time!
