### ISSUE TITLE
Nav Menu widget chevron icon broken(invisible) in mobile hamburger menu with inline svg experiment until tapped

### ISSUE THREAD

**Issue by jazir5** [elementor/elementor#16136] opened 2021-08-24 22:13 UTC
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

Once I activate the inline svg experiment the mobile submenu indicator becomes invisible inside the hamburger menu unless tapped. This means users have no idea a submenu item is expandable unless they hit it accidentally or are trying to navigate to the top menu page. This is terrible for user experience and makes many of my pages very unlikely to be visited as users have no indicator an item is expandable.

## Steps to reproduce
1. Activate inline svg experiment
2. Open the hamburger menu on a mobile device
3. The chevron icon indicating that a submenu item is expandable will be invisible until that submenu item is tapped. It reappears after the menu item has been tapped.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

**Comment by avivu** [comment] 2021-08-28 08:46
Hello @jazir5,
I tried to reproduce the issue and failed (Tested on Elementor v3.4.2, Elementor Pro v3.3.8)

Can you provide more details so we can investigate it more?

Thanks.

**Comment by jazir5** [comment] 2021-08-28 09:11
@avivu 

![signal-2021-08-28-020749_001](https://user-images.githubusercontent.com/31750063/131212808-b652d042-0da4-4afb-8d84-7d1fa6be3d6b.png)

The menu item "shop" is supposed to have a chevron icon next to it. It appears when tapped. I'm on Elementor 3.4.2 and Pro 3.3.8

Steps to reproduce is simply to activate the font awesome inline svg experiment and open the already existing nav menu placed on the site. It reappears immediately upon disabling the experiment

**Comment by avivu** [comment] 2021-09-09 19:46
Hello @jazir5,

We tried to reproduce the issue with the latest versions, but with no luck.
If the issue is still occurring, please contact our support at support @elementor.com for guidance in resolving this issue and mention that you were directed by me and reference this issue.

Thanks.

**Closed by avivu** 2021-09-09 19:46 UTC
