### ISSUE TITLE
❌ Inconsistent :nth-child and :nth-of-type Selector Behavior Between Elementor Editor and Frontend

### ISSUE THREAD

**Issue by Vincent-eg** [elementor/elementor#29121] opened 2024-10-30 04:09 UTC
### Prerequisites

- [X] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [ ] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

When using the :nth-child series of CSS selectors (including `:nth-of-type`) in the editor’s Custom CSS section, the display between the editor and the frontend is inconsistent. The editor shows opposite or incorrect ordering, while the frontend displays correctly. 

For example, selecting a container with `:nth-child(2)` does not render correctly in the editor preview but appears correctly on the frontend(cache is not being used.).

－**Editor View**

![elementor-css-issue-1 2](https://github.com/user-attachments/assets/3eb1634b-02b6-467f-9290-ebb7552ede28)

－**Frontend View**

![elementor-css-issue-2](https://github.com/user-attachments/assets/7459a86b-486a-4325-9cd0-49080b878935)

Additionally, when the parent container is set to full width, the display of `:nth-child(odd)` and `:nth-child(even)` appears completely reversed between the editor and the frontend, while the boxes themselves do not display this issue.

－**Editor View**

![elementor-css-issue-3](https://github.com/user-attachments/assets/570bdf47-5861-4bba-9e64-d2f8a5414a41)

－**Frontend View**

![elementor-css-issue-4](https://github.com/user-attachments/assets/7a15655e-fe2a-4cdc-aed4-0d09e3e4ce41)

### Steps to reproduce

1. Create a parent container and apply a specific CSS class for identification, such as .bg-col-m.
2. Inside the parent container, create more than three child containers. Assign them a height or insert widgets, and apply a specific CSS class for identification, such as .bg-col.
3. Add the following CSS to the parent container. In the editor’s preview, the styles do not display correctly:

`.bg-col-m .bg-col:nth-child(2) {
    background-color: #E9D8A2;
}`

or

`.bg-col-m .bg-col:first-child {
    background-color: #E9D8A2;
}`

or even

`.bg-col-m .bg-col:nth-of-type(2) {
    background-color: #E9D8A2;
}`

4. When the parent container is set to full width, the display of :nth-child(odd) and :nth-child(even) in the editor appears entirely opposite to the frontend, while boxes themselves do not exhibit this discrepancy.
5. However, on the frontend, the styling displays correctly.

### Expected behavior

Within the editor, the order of results displayed by the CSS `:nth-child` and `:nth-of-type` selectors should match those on the frontend."

### Isolating the problem

- [ ] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [ ] This bug happens with the Hello Elementor theme active.
- [x] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

**[Moderation Edit: The contributor did not share the full and required Elementor System Info.]**

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by nicholaszein** [comment] 2024-10-30 15:19
Hi @Vincent-eg!

Thank you for reaching out! 🙏 

We want to inform you we have received your issue, and will answer you as soon as possible.

Kind regards

**Comment by jdpoccorie** [comment] 2024-10-31 19:45
Perhaps this solution will help you figure out the problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)

**Comment by Vincent-eg** [comment] 2024-11-04 03:41
I understand. Thank you for your kind response, and I look forward to any adjustments you may make.

Best regards.

**Comment by nicholaszein** [comment] 2024-11-05 16:34
Hi @Vincent-eg!

Thank you for your patience. 🙏 

After reviewing your issue, we concluded this is not a bug in Elementor.

When you are editing your content in Elementor, it injects UI elements, such as the editing handles in order to allow you to edit your content. These editing handles are added to each element internally. See an example below:

![image](https://github.com/user-attachments/assets/16f87b6e-28c5-4e98-a209-8300330c881c)


If you are going to use Custom CSS, you need to take these into account, or to better explained, you need to consider these won't be added to the final element on the frontend.

For Containers, you can expect the following additional elements to be added alongside the widgets inside them when editing a document:
1. **`<div class="elementor-element-overlay"></div>`**: responsible for showing the outlines of the container, as well as the editing handles.
2. **`<div class="elementor-shape elementor-shape-top"></div>`**: always present in the editor, only visible in the frontend if you add a **Top Shape Divider**.
3. **`<div class="elementor-shape elementor-shape-bottom"></div>`**: always present in the editor, only visible in the frontend if you add a **Bottom Shape Divider**.

These will be added **_before_** the widgets inside a container when editing the document. 

4. **`<div class="ui-resizable-handle ui-resizable-e" style="z-index: 90;"></div>`**: responsible for allowing to change the size of the elements inside the container.
5. **`<div class="ui-resizable-handle ui-resizable-w" style="z-index: 90;"></div>`**: responsible for allowing to change the width of the container.

These will be added **_after_** the widgets inside a container when editing the document with the Elementor Editor.

Your calculations for **`:nth-child(n)`** need to account for these. When in doubt, just inspect the code with the browser inspector.

I hope this helps.

I'm closing this issue as not a bug!

Kind regards

**Closed by nicholaszein** 2024-11-05 16:34 UTC
Labels: editor, type/styles, compatibility/assets, component/custom-css, mod*, compatibility/3rd-party-code, editor/canvas
