### ISSUE TITLE
🔗 🚀 Feature Request: Hover animation for Containers (Duplicate of #18881)

### ISSUE THREAD

**Issue by vgstef** [elementor/elementor#20454] opened 2022-11-19 21:31 UTC
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

I'm trying to create a stylish button using a container, and I realize that there are missing features for hover animation like "grow", "rotate", for the containers. 

### Describe the solution you'd like

I'd like to have the same hover animations for the containers as the one we find in the image widget. 

### Describe alternatives you've considered

I'm planning to use custom CSS.

**Comment by nicholaszein** [comment] 2022-11-20 02:51
Hello @vgstef!

Thank you for your submission! 🙏 

### 🔗 This issue is a Duplicate of #18881.

Which is on the same subject. 

For this reason, I'm closing this issue and 🔃 **Merging** it with the original, so we can have all the discussions in one location, and deal with it more efficiently.

Feel free to continue the conversation there. 😉 

## ✔️ Please, in the future, remember to check if there isn't an issue similar to yours already opened. 

Best regards,

Nick

**Closed by nicholaszein** 2022-11-20 02:51 UTC
Labels: request/enhancement, type/design, solved_by_container

**Comment by nicholaszein** [comment] 2022-12-07 08:31
Hello there!

We have great news! 🙌 

### 📢 We're happy to announce that the issue you raised was resolved in Elementor **v3.9.0**! 🥳 

✔️ Please feel free to check it out and update your plugin to the new version!

Cheers 🥂
