### ISSUE TITLE
[Feature Request] Additional breakpoints in responsive mode

### ISSUE THREAD

**Issue by ShaneLynam** [elementor/elementor#10650] opened 2020-02-24 15:57 UTC
I've often run into issues where I'd like to change styles for different sized devices not included in responsive mode at the moment. These are mainly devices above 1024px. I develop on a widescreen monitor however some designs I create need to be tweaked for smaller screens such as laptops and the likes. I usually just write media queries but it would be helpful if Elementor had some additional breakpoints.

**Comment by artifex-media** [comment] 2020-03-03 14:44
+1

**Comment by arielk** [comment] 2020-08-19 18:49
Duplicate of https://github.com/elementor/elementor/issues/2043

**Closed by arielk** 2020-08-19 18:49 UTC
