### ISSUE TITLE
🔗 🐞 Bug Reports: How to add Distance from content and problem with `:hover` state in tabs (Merged with #21849)

### ISSUE THREAD

**Issue by bnovak99** [elementor/elementor#21823] opened 2023-03-29 18:32 UTC
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

I was trying to add more spacing between the navigation and mega menu by adding a bottom margin to the menu. This had no effect so I tried adding a top margin to the first item in my mega menu also no effect. I ended up adding a container to the first item and set top padding there to create some space the add my tabs to this container.

With my tabs there is now an issue with the Active tab. For some reason, after this last beta update, my Active tab and link go to white when you hover over them.
![tab](https://user-images.githubusercontent.com/25965963/228633810-772a1a63-d5aa-4583-a0e9-4922d356706e.png)

### Steps to reproduce

1. Create a mega menu 
2. try to add a margin to the menu to create a vertical space between the nav and mega menu

Tabs
1. Add tabs
2. Assign styles to tabs
3. View Active tab on hover goes to white

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

[system-info-spectrastg.wpengine.com-29-03-2023.txt](https://github.com/elementor/elementor/files/11104293/system-info-spectrastg.wpengine.com-29-03-2023.txt)

**Comment by doronwolf** [comment] 2023-03-30 11:43
Hi @bnovak99 
about the first issue - you can simply use the 'distance from content' under the style tab (see attached screenshot)
![Screenshot 2023-03-30 at 14 37 30](https://user-images.githubusercontent.com/89334998/228825434-85f06555-5f42-47c7-82ab-216c19704075.png)

I failed to reproduce the 2nd issue - did you assign colors for the 'hover' and 'active' states for the tabs background and titles?

**Comment by bnovak99** [comment] 2023-03-30 14:50
Ok thank you for confirming this issue.

**Comment by bnovak99** [comment] 2023-03-30 17:17
My form elements are now having background color issues on the frontend. Inputs have black backgrounds.

**Comment by nicholaszein** [comment] 2023-03-31 14:21
Hello @bnovak99! 

Thank you for submitting your issue! 🙏

### When submitting issues, please remember to follow our guidelines so we can help you better and save time:

- ☝️ **One Issue Per Thread:** If you are experiencing more than one bug, submit only **<ins>ONE ISSUE PER THREAD</ins>**, so we can properly track them and reference them without any confusion.

Since your first issue was already answered, I am closing this one and **merging** it with issue #21849 so we can have all the discussions in one location, and deal with it more efficiently.

Feel free to continue the conversation there. 😉 

Kind regards

**Closed by nicholaszein** 2023-03-31 14:21 UTC
Labels: bug, product/pro, type/design, component/tabs, component/menu
