### ISSUE TITLE
🔗 Problem in "post info" (Duplicate of #28800)

### ISSUE THREAD

**Issue by thisisamin2** [elementor/elementor#28830] opened 2024-09-26 16:07 UTC
### Prerequisites

- [ ] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [ ] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

Hello,
I encountered with a problem after you updated Elementor.
When I use "post info" widget, the page breaks down!
look:
![Capture](https://github.com/user-attachments/assets/02aec129-d2a9-4b65-a24b-f07b8411bc84)

Please fix this problem...
Thanks a lot.

### Steps to reproduce

I illustrated the issue for you...

### Expected behavior

please fix this problem...

### Isolating the problem

- [ ] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [ ] This bug happens with the Hello Elementor theme active.
- [ ] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

<details>
<summary>Click to reveal</summary>

````txt


== Server Environment ==
	Operating System: Linux
	Software: LiteSpeed
	MySQL version: MariaDB Server v10.6.18
	PHP Version: 7.4.33
	PHP Memory Limit: 1024M
	PHP Max Input Vars: 10000
	PHP Max Post Size: 1024M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.6.2
	Site URL: 
	Home URL: 
	WP Multisite: No
	Max Upload Size: 1 گیگابایت
	Memory limit: 40M
	Max Memory limit: 1024M
	Permalink Structure: /%postname%/
	Language: fa_IR
	Timezone: 3.5
	Debug Mode: Active

== Theme ==
	Name: Hello Elementor
	Version: 3.1.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: fa-IR
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36

== Active Plugins ==
	Disable Emojis (GDPR friendly)
		Version: 1.7.6
		Author: Ryan Hellyer

	Disable Updates
		Version: 1.3.9
		Author: Johan van der Wijk

	Elementor
		Version: 3.24.4
		Author: Elementor.com

	Elementor Pro
		Version: 3.23.3
		Author: Elementor.com

	JetBlocks For Elementor
		Version: 1.3.14
		Author: Crocoblock

	JetEngine
		Version: 3.5.5
		Author: Crocoblock

	LiteSpeed Cache
		Version: 6.5.1
		Author: LiteSpeed Technologies

	ShayanWeb Admin FontChanger | افزونه‌ی تغییر فونت پیشخوان وردپرس شایان وب
		Version: 1.8.1
		Author: ShayanWeb

	WP-Parsidate
		Version: 4.0.2
		Author: WP-Parsi Team


== امکانات ==
	Custom Fonts: 10
	Custom Icons: 1

== ادغام ==
	


== آزمایشات عنصر ==
	بارگذاری CSS بهبود یافته: به صورت پیشفرض غیرفعال است
	نمادهای فونت درون خطی: به صورت پیشفرض فعال است
	نقاط قطع سفارشی اضافی (جهت رسپانسیو سایت به کار میره): به صورت پیشفرض فعال است
	کانتینر فلکس باکس: به صورت پیشفرض فعال است
	کانتینر شبکه: به صورت پیشفرض فعال است
	ارتقای کتابخانه Swiper: به صورت پیشفرض فعال است
	عملکرد عناصر تو در تو: به صورت پیشفرض فعال است
	بارگذاری بهینه کنترل: به صورت پیشفرض غیرفعال است
	نشانه‌گذاری بهینه شده: به صورت پیشفرض غیرفعال است
	بارگذاری مشروط فایل‌های Swiper CSS: به صورت پیشفرض غیرفعال است
	مراحل راه‌اندازی افزونه: به صورت پیشفرض فعال است
	قالب ساز جدید حالت پیشفرض باشد: به صورت پیشفرض فعال است
	سربرگ و پابرگ: به صورت پیشفرض فعال است
	صفحه اصلی المنتور: به صورت پیشفرض فعال است
	ساختن با هوش مصنوعی: به صورت پیشفرض فعال است
	صفحات فرود: به صورت پیشفرض فعال است
	چک لیست Launchpad: به صورت پیشفرض غیرفعال است
	عناصر تو در تو: به صورت پیشفرض غیرفعال است
	نوار بالا ویرایشگر: به صورت پیشفرض غیرفعال است
	حافظه پنهان عنصر: به صورت پیشفرض غیرفعال است
	لینک در بایو: به صورت پیشفرض فعال است
	دکمه‌های شناور: به صورت پیشفرض فعال است
	رویدادهای ویرایشگر المنتور: به صورت پیشفرض غیرفعال است
	ابزارک‌های اتمی: به صورت پیشفرض غیرفعال است
	شرایط نمایش: به صورت پیشفرض فعال است
	فرم های ثبت شده: به صورت پیشفرض فعال است
	منو: به صورت پیشفرض غیرفعال است
	فیلتر طبقه بندی: به صورت پیشفرض فعال است
	جستجو: به صورت پیشفرض غیرفعال است


== گزارش ==
	
Log: showing 20 of 412024-09-13 14:20:16 [info] elementor::elementor_updater Started 
2024-09-13 14:20:16 [info] المنتور/Upgrades - _on_each_version Start  
2024-09-13 14:20:16 [info] المنتور/Upgrades - _on_each_version Finished 
2024-09-13 14:20:16 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'المنتور',
  'from' => '3.24.1',
  'to' => '3.24.2',
)]
2024-09-13 18:25:55 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'المنتور پرو',
  'from' => '3.21.3',
  'to' => '3.23.3',
)]
2024-09-13 18:25:56 [info] elementor-pro::elementor_pro_updater Started 
2024-09-13 18:25:56 [info] المنتور پرو/Upgrades - _on_each_version Start  
2024-09-13 18:25:56 [info] المنتور پرو/Upgrades - _on_each_version Finished 
2024-09-13 18:25:56 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'المنتور پرو',
  'from' => '3.21.3',
  'to' => '3.23.3',
)]
2024-09-13 18:25:58 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'المنتور پرو',
  'from' => '3.21.3',
  'to' => '3.23.3',
)]
2024-09-18 12:59:39 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'المنتور',
  'from' => '3.24.2',
  'to' => '3.24.3',
)]
2024-09-18 13:05:43 [info] elementor::elementor_updater Started 
2024-09-18 13:05:43 [info] المنتور/Upgrades - _on_each_version Start  
2024-09-18 13:05:43 [info] المنتور/Upgrades - _on_each_version Finished 
2024-09-18 13:05:43 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'المنتور',
  'from' => '3.24.2',
  'to' => '3.24.3',
)]
2024-09-26 19:13:44 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'المنتور',
  'from' => '3.24.3',
  'to' => '3.24.4',
)]
2024-09-26 19:13:45 [info] elementor::elementor_updater Started 
2024-09-26 19:13:45 [info] المنتور/Upgrades - _on_each_version Start  
2024-09-26 19:13:45 [info] المنتور/Upgrades - _on_each_version Finished 
2024-09-26 19:13:45 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'المنتور',
  'from' => '3.24.3',
  'to' => '3.24.4',
)]

JS: showing 1 of 1JS: 2024-07-18 18:34:54 [error X 11][../wp-content/plugins/elementor/assets/js/ai-gutenberg.min.js?ver=3.23.1:3:618224] Failed to execute &#039;insertBefore&#039; on &#039;Node&#039;: The node before which the new node is to be inserted is not a child of this node. 

PHP: showing 1 of 1PHP: 2024-09-13 13:09:12 [notice X 1][../wp-content/plugins/elementor/core/common/modules/connect/apps/base-app.php::539] hash_hmac(): Passing null to parameter #3 ($key) of type string is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]



== المنتور - Compatibility Tag ==
	
	Elementor Pro: ناسازگار
	JetBlocks For Elementor: ناسازگار

== المنتور پرو - Compatibility Tag ==
	
	JetBlocks For Elementor: ناسازگار

````

</details>

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by nicholaszein** [comment] 2024-10-01 14:56
Hello @thisisamin2!

Thank you for your submission! 🙏 

### 🔗 🐞 This issue is a Duplicate of #28800

Which is on the same subject. 

For this reason, I'm closing this thread and 🔃 **Merging** it with the original, so we can have all the discussions in one location, and deal with it more efficiently.

Feel free to continue the conversation there. 😉 

### 🔍 Please, in the future, remember to check if there isn't any thread similar to yours already opened. 

Kind regards

**Closed by nicholaszein** 2024-10-01 14:56 UTC
Labels: product/pro, type/styles, type/experiment, mod*, document/assets, widget/post-info, duplicate, component/improved-css-loading
