### ISSUE TITLE
Problem with the new update 3.2.2 Editor doesnt load "gray screen''

### ISSUE THREAD

**Issue by jason5137715** [elementor/elementor#14709] opened 2021-04-26 11:30 UTC
After the last update 3.2.1 I cant edit any page anymore, it gives me gray page.
So I updated to the latest update 3.2.2 and the problem still exist.
Please note, I disabled all plugins and changed the theme and cleared the cache, the problem still exist from the version 3.2.1
This is the error:
```
Uncaught TypeError: document.getElementById(...) is null
    <anonymous> https://www.istiklalhomes.com/en/about-houzez/?elementor-preview=692&ver=1619437125:2651
```
and a lot of other errors
```
TypeError: can't convert undefined to object
    initStylesheet https://www.istiklalhomes.com/wp-content/plugins/elementor/assets/js/editor.min.js:2
    t https://www.istiklalhomes.com/wp-content/plugins/elementor/assets/js/common-modules.min.js:2
    onInit https://www.istiklalhomes.com/wp-content/plugins/elementor/assets/js/editor.min.js:2
    t https://www.istiklalhomes.com/wp-content/plugins/elementor/assets/js/common-modules.min.js:2
    trigger https://www.istiklalhomes.com/wp-content/plugins/elementor/assets/js/common-modules.min.js:2
    t https://www.istiklalhomes.com/wp-content/plugins/elementor/assets/js/common-modules.min.js:2
    init https://www.istiklalhomes.com/wp-content/plugins/elementor/assets/js/common-modules.min.js:2
    Module https://www.istiklalhomes.com/wp-content/plugins/elementor/assets/js/common-modules.min.js:2
    child https://www.istiklalhomes.com/wp-content/plugins/elementor/assets/js/common-modules.min.js:2
    child https://www.istiklalhomes.com/wp-content/plugins/elementor/assets/js/common-modules.min.js:2
    renderGlobalsDefaultCSS https://www.istiklalhomes.com/wp-content/plugins/elementor/assets/js/editor.min.js:2
    initialize https://www.istiklalhomes.com/wp-content/plugins/elementor/assets/js/editor.min.js:2
    d/t[e]< Backbone
    before Underscore
    Backbone 4
    apply https://www.istiklalhomes.com/wp-content/plugins/elementor/assets/js/editor.min.js:2
    promise callback*apply https://www.istiklalhomes.com/wp-content/plugins/elementor/assets/js/editor.min.js:2
    run https://www.istiklalhomes.com/wp-content/plugins/elementor/assets/js/editor.min.js:2
    c https://www.istiklalhomes.com/wp-content/plugins/elementor/assets/js/editor.min.js:2
    run https://www.istiklalhomes.com/wp-content/plugins/elementor/assets/js/common.min.js:2
    internal https://www.istiklalhomes.com/wp-content/plugins/elementor/assets/js/common.min.js:2
    onPreviewLoaded https://www.istiklalhomes.com/wp-content/plugins/elementor/assets/js/editor.min.js:2
    onPreviewLoaded https://www.istiklalhomes.com/wp-content/plugins/elementor/assets/js/editor.min.js:2
    jQuery 9
    initPreview https://www.istiklalhomes.com/wp-content/plugins/elementor/assets/js/editor.min.js:2
    onStart https://www.istiklalhomes.com/wp-content/plugins/elementor/assets/js/editor.min.js:2
    onStart https://www.istiklalhomes.com/wp-content/plugins/elementor/assets/js/editor.min.js:2
    Backbone 3
    13021 https://www.istiklalhomes.com/wp-content/plugins/elementor/assets/js/editor.min.js:2
    __webpack_require__ https://www.istiklalhomes.com/wp-content/plugins/elementor/assets/js/editor.min.js:2
    <anonymous> https://www.istiklalhomes.com/wp-content/plugins/elementor/assets/js/editor.min.js:2
    <anonymous> https://www.istiklalhomes.com/wp-content/plugins/elementor/assets/js/editor.min.js:2
common.min.js:2:116367
    consoleError https://www.istiklalhomes.com/wp-content/plugins/elementor/assets/js/common.min.js:2
    onCatchApply https://www.istiklalhomes.com/wp-content/plugins/elementor/assets/js/editor.min.js:2
    _callee2$ https://www.istiklalhomes.com/wp-content/plugins/elementor/assets/js/editor.min.js:2
    tryCatch https://www.istiklalhomes.com/wp-content/plugins/elementor/assets/js/editor.min.js:2
    invoke https://www.istiklalhomes.com/wp-content/plugins/elementor/assets/js/editor.min.js:2
    defineIteratorMethods https://www.istiklalhomes.com/wp-content/plugins/elementor/assets/js/editor.min.js:2
    asyncGeneratorStep https://www.istiklalhomes.com/wp-content/plugins/elementor/assets/js/editor.min.js:2
    _next https://www.istiklalhomes.com/wp-content/plugins/elementor/assets/js/editor.min.js:2
    _asyncToGenerator https://www.istiklalhomes.com/wp-content/plugins/elementor/assets/js/editor.min.js:2
    F https://www.istiklalhomes.com/wp-content/plugins/elementor/assets/js/editor.min.js:2
    _asyncToGenerator https://www.istiklalhomes.com/wp-content/plugins/elementor/assets/js/editor.min.js:2
    runAfter https://www.istiklalhomes.com/wp-content/plugins/elementor/assets/js/editor.min.js:2
    run https://www.istiklalhomes.com/wp-content/plugins/elementor/assets/js/editor.min.js:2
    c https://www.istiklalhomes.com/wp-content/plugins/elementor/assets/js/editor.min.js:2
    run https://www.istiklalhomes.com/wp-content/plugins/elementor/assets/js/common.min.js:2
    internal https://www.istiklalhomes.com/wp-content/plugins/elementor/assets/js/common.min.js:2
    onPreviewLoaded https://www.istiklalhomes.com/wp-content/plugins/elementor/assets/js/editor.min.js:2
    onPreviewLoaded https://www.istiklalhomes.com/wp-content/plugins/elementor/assets/js/editor.min.js:2
    jQuery 9
    initPreview https://www.istiklalhomes.com/wp-content/plugins/elementor/assets/js/editor.min.js:2
    onStart https://www.istiklalhomes.com/wp-content/plugins/elementor/assets/js/editor.min.js:2
    onStart https://www.istiklalhomes.com/wp-content/plugins/elementor/assets/js/editor.min.js:2
    Backbone 3
    13021 https://www.istiklalhomes.com/wp-content/plugins/elementor/assets/js/editor.min.js:2
    __webpack_require__ https://www.istiklalhomes.com/wp-content/plugins/elementor/assets/js/editor.min.js:2
    <anonymous> https://www.istiklalhomes.com/wp-content/plugins/elementor/assets/js/editor.min.js:2
    <anonymous> https://www.istiklalhomes.com/wp-content/plugins/elementor/assets/js/editor.min.js:2



```

**Comment by shilo-ey** [comment] 2021-04-26 12:13
you have JS conflict somewhere in your install.

Start by deactivating all other add-ons and plugins other than Elementor Core & Elementor Pro (if installed) - then proceed to edit and see if the issue has been resolved. You may need to switch to the default theme to rule out your theme as the cause of the conflict.

If the issue is resolved by following the above action the proceed to reactivate each plugin 1 at a time and checking the editor till you find the one causing the conflict.

From a brief inspection - it seems to be related to custom code you have in your page (something related to "date")


If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.


Thanks

**Closed by shilo-ey** 2021-04-26 12:13 UTC

**Comment by jason5137715** [comment] 2021-04-27 05:42
I found the problem, It's plugin called "Performance Cache" from one.com, This hosting company install the plugin by defult
