### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read property 'data' of undefined

### ISSUE THREAD

**Issue by PhunkyBob** [elementor/elementor#11035] opened 2020-04-01 22:18 UTC
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
Old issue found : 3926
- [x] The issue still exists against the latest stable version of Elementor.

## Description
When I create a page, I can edit it with Elementor.
When I go again on the same page, I can't edit it anymore and I have an error in the console : 
```
editor.min.js?ver=2.9.7:7 Uncaught (in promise) TypeError: Cannot read property 'data' of undefined
    at initSettings (editor.min.js?ver=2.9.7:7)
```

## Steps to reproduce
- Create a new page.
- Edit with Elementor.
- Save & publish.
- Edit the same page with Elementor.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
https://pastebin.com/f6SpnrJ1
</details>

I've found an old issue and I found a post that helped me to find a workaround: 
https://github.com/elementor/elementor/issues/3926#issuecomment-397355828
In the file "preview.php", the function "is_preview_mode" returns "false" and I don't understand why "$_GET['elementor-preview']" is not set.
If I hack this function to return "true", I can edit my page with Elementor.

**Comment by HW-MI** [comment] 2020-04-03 09:21
I have the same problem.

**Comment by lebnani** [comment] 2020-04-06 16:59
Having same issue with the last version of elementor and elementor pro

**Comment by HW-MI** [comment] 2020-04-07 07:34
When I change my permalinks to default, it works again!

In my current settings, the other permalink contain index.php in de address. If I try the other permalinks strings, which contain index.php, it does not work. Besides that, for me it is not desirable to add index.php within my permalink. But a custom permalink without index.php does not work.

**Comment by PhunkyBob** [comment] 2020-04-07 09:07
Indeed, with "Plain permalinks" it works again. 
Unfortunately other plugins don't work with "plain permalinks" (eg. Hide My WP).

**Comment by ekkode** [comment] 2020-04-14 07:38
I have the same problem

**Comment by benfavre** [comment] 2020-04-21 14:12
![image](https://user-images.githubusercontent.com/664679/79875886-909cc300-83ea-11ea-96db-8e318ec1ee84.png)
Seems related to permission checking, I'm gonna comment it out for now since I'm not payed to make a plugin used by thousand of people.
Why you can't just alert a warning message instead of just failing is mind boggling.

**Comment by AlexWebYourmind** [comment] 2020-04-22 09:25
If you are using a vhost (e.g. on Xampp), make sure to add "AllowOverride All" in your configuration, otherwise .htaccess writing will be forbidden.
that fixed the issue for me. hope that helps.

**Comment by 7PH** [comment] 2020-04-24 09:39
Same problem on nginx. By duplicating the site on an apache website, it works.

**Comment by 7PH** [comment] 2020-04-24 22:03
I investigated and found the issue. It seems to be a problem with the web server rewrite rule, not this plugin in particular. 

In case the permalink is set to simple, the ajax request that loads the preview is:
[http://{DOMAIN}/?header={HEADER}&elementor-preview={ELEMENT_PREVIEW_ID}&ver={V}](#)

Which is interpreted just fine by the is_preview_mode function that tests for $_GET['elementor-preview']

But when the permalink is set to a custom value (/%category%/%postname%/ in my case) the requests is sent to:
[http://{DOMAIN}/header/{HEADER}/?elementor-preview={ELEMENT_PREVIEW_ID}&ver={V}](#)

Which is rewritten by **my** nginx to:
[http://{DOMAIN}/index.php?q=/header/{HEADER}/elementor-preview=99&ver=1587763043](#)

Which builds
```php
$_GET = [
    "q"=>"/header/{HEADER}/elementor-preview=99",
    "ver" => "1587763043"
]
```

This is obviously wrong, 'elementor-preview' should be in a separate variable. When looking at my nginx config, the error was obvious:
```text
try_files $uri $uri/ /index.php?q=$uri$args;
```

We can see the first argument is lost and merged with q=, so I updated the rule:
```text
try_files $uri $uri/ /index.php?q=$uri&$args;
```

And it works just fine now.

Seeing all of you also having the same error, I'm guessing that I was not the only one with an invalid redirect rule. So I hope this can help you.

**Comment by PhunkyBob** [comment] 2020-04-25 12:19
> When looking at my nginx config, the error was obvious

Problem is, I'm not the hoster and I can't change the server config files.

Is there something I can do in the .htaccess file to do something similar?

**Comment by YIN-Renlong** [comment] 2020-04-30 17:04
@HW-MI @7PH  Thanks for the workaround provided. Whether changing the permalinks or modifying Nginx configuration will be a solution. Cheers!

@PhunkyBob Thank you for the question, I hope you can find a suitable way to solve the problem.

**Comment by alarstyle** [comment] 2020-05-13 08:24
Same error!

**Comment by mdaltaf-tech** [comment] 2020-05-16 10:06
> When I change my permalinks to default, it works again!
> 
> In my current settings, the other permalink contain index.php in de address. If I try the other permalinks strings, which contain index.php, it does not work. Besides that, for me it is not desirable to add index.php within my permalink. But a custom permalink without index.php does not work.

This trick worked. Thank you 👍

**Comment by Errabaany** [comment] 2020-05-20 11:19
I had the same issue everything was working fine till I woke up today and I found this error
all I did is **log out and log in** again and it's works,
try this it's could solve your problem

**Comment by harshilvora8** [comment] 2020-05-21 15:05
Seems like I'm facing the same issue - I am unable to get the editor to load on the Checkout Page, it loads for all other pages and templates in my Theme Builder. 

Changing to default permalinks doesn't work for me. I'm using Siteground for my hosting. Any workarounds for this?

Here is the error I see in my browser console.

editor.min.js?ver=2.9.8:7 Uncaught TypeError: Cannot read property 'data' of undefined
at initSettings (editor.min.js?ver=2.9.8:7)
at initialize (editor.min.js?ver=2.9.8:7)
at i.h.Model (load-scripts.php?c=0&load[chunk_0]=underscore,jquery-core,jquery-migrate,backbone,jquery-ui-core,jquery-ui-widget,jquery-ui-mouse,shortcode,utils,wp-util,wp-backbo&load[chunk_1]=ne,media-models,moxiejs,plupload,wp-plupload,jquery-ui-sortable&ver=5.4.1:12)
at new i (load-scripts.php?c=0&load[chunk_0]=underscore,jquery-core,jquery-migrate,backbone,jquery-ui-core,jquery-ui-widget,jquery-ui-mouse,shortcode,utils,wp-util,wp-backbo&load[chunk_1]=ne,media-models,moxiejs,plupload,wp-plupload,jquery-ui-sortable&ver=5.4.1:12)
at t.value (editor.min.js?ver=2.9.4:2)
at t.value (editor.min.js?ver=2.9.4:2)
at editor.min.js?ver=2.9.4:2
at Function.v.each.v.forEach (load-scripts.php?c=0&load[chunk_0]=underscore,jquery-core,jquery-migrate,backbone,jquery-ui-core,jquery-ui-widget,jquery-ui-mouse,shortcode,utils,wp-util,wp-backbo&load[chunk_1]=ne,media-models,moxiejs,plupload,wp-plupload,jquery-ui-sortable&ver=5.4.1:2)
at t.value (editor.min.js?ver=2.9.4:2)
at Editor.<anonymous> (editor.min.js?ver=2.9.4:2)

**Comment by netbbe** [comment] 2020-06-06 12:28
Same issue. The solution here was to reset the Posts page in Settings - Reading - Your homepage displays to "--- Select ---".

**Comment by gbrits** [comment] 2020-06-28 11:04
For me the problem was that the page was named the same as the custom post type I had.

**Comment by mubasheerck** [comment] 2020-07-03 14:59
> I investigated and found the issue (for me). It seems to be a problem with the web server rewrite rule, not this plugin in particular.
> 
> In case the permalink is set to simple, the ajax request that loads the preview is:
> [http://{DOMAIN}/?header={HEADER}&elementor-preview={ELEMENT_PREVIEW_ID}&ver={V}](#)
> 
> Which is interpreted just fine by the is_preview_mode function that tests for $_GET['elementor-preview']
> 
> But when the permalink is set to a custom value (/%category%/%postname%/ in my case) the requests is sent to:
> [http://{DOMAIN}/header/{HEADER}/?elementor-preview={ELEMENT_PREVIEW_ID}&ver={V}](#)
> 
> Which is rewritten by **my** nginx to:
> [http://{DOMAIN}/index.php?q=/header/{HEADER}/elementor-preview=99&ver=1587763043](#)
> 
> Which builds
> 
> ```
> $_GET = [
>     "q"=>"/header/{HEADER}/elementor-preview=99",
>     "ver" => "1587763043"
> ]
> ```
> 
> This is obviously wrong, 'elementor-preview' should be in a separate variable. When looking at my nginx config, the error was obvious:
> 
> ```
> try_files $uri $uri/ /index.php?q=$uri$args;
> ```
> 
> We can see the first argument is lost and merged with q=, so I updated the rule:
> 
> ```
> try_files $uri $uri/ /index.php?q=$uri&$args;
> ```
> 
> And it works just fine now.
> 
> Seeing all of you also having the same error, I'm guessing that I was not the only one with an invalid redirect rule. So I hope this can help you.

Thank you so much. Finally, I found this after months of searching. Really helpful.

**Comment by benrich** [comment] 2020-08-17 14:01
My solution was down to running on a WP Network (multisite).  I had to log out of the primary site's admin area before the error mentioned within this thread disappeared from my sub-site.

The sub-site is on a subdomain of the primary site.  Complete guess here... presumably if my sub-site wasn't a subdomain of the primary site it wouldn't have been a problem (Re. server rewrite rules).

**Comment by mihail-minkov** [comment] 2021-01-07 21:42
> 
> We can see the first argument is lost and merged with q=, so I updated the rule:
> 
> ```
> try_files $uri $uri/ /index.php?q=$uri&$args;
> ```
>

This worked perfectly. In my case instead of:
```
try_files $uri $uri/ /index.php?q=$uri&$args;
````

I had
```
try_files $uri $uri/ /index.php?q=$request_uri;
```

**Comment by camorive** [comment] 2021-01-15 17:54
> I investigated and found the issue (for me). It seems to be a problem with the web server rewrite rule, not this plugin in particular.
> 
> In case the permalink is set to simple, the ajax request that loads the preview is:
> [http://{DOMAIN}/?header={HEADER}&elementor-preview={ELEMENT_PREVIEW_ID}&ver={V}](#)
> 
> Which is interpreted just fine by the is_preview_mode function that tests for $_GET['elementor-preview']
> 
> But when the permalink is set to a custom value (/%category%/%postname%/ in my case) the requests is sent to:
> [http://{DOMAIN}/header/{HEADER}/?elementor-preview={ELEMENT_PREVIEW_ID}&ver={V}](#)
> 
> Which is rewritten by **my** nginx to:
> [http://{DOMAIN}/index.php?q=/header/{HEADER}/elementor-preview=99&ver=1587763043](#)
> 
> Which builds
> 
> ```
> $_GET = [
>     "q"=>"/header/{HEADER}/elementor-preview=99",
>     "ver" => "1587763043"
> ]
> ```
> 
> This is obviously wrong, 'elementor-preview' should be in a separate variable. When looking at my nginx config, the error was obvious:
> 
> ```
> try_files $uri $uri/ /index.php?q=$uri$args;
> ```
> 
> We can see the first argument is lost and merged with q=, so I updated the rule:
> 
> ```
> try_files $uri $uri/ /index.php?q=$uri&$args;
> ```
> 
> And it works just fine now.
> 
> Seeing all of you also having the same error, I'm guessing that I was not the only one with an invalid redirect rule. So I hope this can help you.

Many but many Thanks!! A plugin called WPRocket ruined my .htaccess file and looking into this response I figured out it was probably this and it was. Just registered to thank you man, God bless you.

**Comment by MGParisi** [comment] 2021-02-03 23:56
Found the issue with mine....  I had a field that somehow lost an id.  After going through and hitting the "advanced" tab when you click on the field in the form settings, you will find you can set the id and a note that it needs to be unique.  Try changing this and setting it to something unique.

**Comment by hirushacooray** [comment] 2021-02-04 11:56
saving the permalinks worked for me

**Comment by triangle-stream** [comment] 2021-02-09 14:20
> 
> 
> I investigated and found the issue (for me). It seems to be a problem with the web server rewrite rule, not this plugin in particular.
> 
> In case the permalink is set to simple, the ajax request that loads the preview is:
> [http://{DOMAIN}/?header={HEADER}&elementor-preview={ELEMENT_PREVIEW_ID}&ver={V}](#)
> 
> Which is interpreted just fine by the is_preview_mode function that tests for $_GET['elementor-preview']
> 
> But when the permalink is set to a custom value (/%category%/%postname%/ in my case) the requests is sent to:
> [http://{DOMAIN}/header/{HEADER}/?elementor-preview={ELEMENT_PREVIEW_ID}&ver={V}](#)
> 
> Which is rewritten by **my** nginx to:
> [http://{DOMAIN}/index.php?q=/header/{HEADER}/elementor-preview=99&ver=1587763043](#)
> 
> Which builds
> 
> ```
> $_GET = [
>     "q"=>"/header/{HEADER}/elementor-preview=99",
>     "ver" => "1587763043"
> ]
> ```
> 
> This is obviously wrong, 'elementor-preview' should be in a separate variable. When looking at my nginx config, the error was obvious:
> 
> ```
> try_files $uri $uri/ /index.php?q=$uri$args;
> ```
> 
> We can see the first argument is lost and merged with q=, so I updated the rule:
> 
> ```
> try_files $uri $uri/ /index.php?q=$uri&$args;
> ```
> 
> And it works just fine now.
> 
> Seeing all of you also having the same error, I'm guessing that I was not the only one with an invalid redirect rule. So I hope this can help you.

Thank you!
This also fixed same issue for me when using Nginx [1.18].

**Comment by bluantinoo** [comment] 2021-03-31 09:11
Just saving permalinks solves for me, saving with no changes.

**Comment by jesustorresg** [comment] 2021-05-14 03:24
So sad, the only way to solve this issue was by making a Rollback to my last known stable version of Elementor & Elementor Pro (Stable while editing my template) [3.0.5].

**Comment by ALPSIT** [comment] 2021-05-29 06:17
I just want to give my experience with this issue which cost me hours and I eventually worked out.

I'm annoyed I didn't realise this earlier.

I had the same issue with post name permalink pages not loading elementor in published view and only as drafts view or if i changed the permalinks to plain. so i tried every solution in here to no prevail.

The page I was working on had 'Adwords' in the title and Adblock Plus was blocking the elements in the page from loading due the this naming. Took me a while to figure it out grrrr.. just incase anyone else runs into the same issue haha.

Regards,

Alp

**Comment by nikosing21** [comment] 2021-06-13 09:05
same for me ,
the solution of the problem was with Permalink Settings that uses the post name setting and just choosing plain fix it.
The problem was with the ocean theme that wordpress has and after we have it at 2 installations at our server .
we did it with the module all in one migrate. I would chech for further informations

**Comment by nikosing21** [comment] 2021-06-13 09:19
others having the same problem please tell us if you use the ocean theme .

**Comment by dimkasta** [comment] 2021-06-16 20:06
This is the most annoying thing. No helpful messages for what the problem is, and of course it happens to the one site where we have no access to the server.

**Comment by AIf4** [comment] 2021-08-21 19:53
> 
> 
> Just saving permalinks solves for me, saving with no changes.

changing the permalinks to "simple" worked for me

**Comment by Zexler** [comment] 2021-09-10 08:38
I have the same problem after migration to another domain. Only Elementor, without other plugin, with Hello theme. Why?!

**Comment by Morganesly** [comment] 2022-01-04 05:42
> 

Hello, can you tell me where I can find this? I'm trying to do the same but I can't find it 

Thanks.

**Comment by Morganesly** [comment] 2022-01-04 05:44
> > I investigated and found the issue (for me). It seems to be a problem with the web server rewrite rule, not this plugin in particular.
> > In case the permalink is set to simple, the ajax request that loads the preview is:
> > [http://{DOMAIN}/?header={HEADER}&elementor-preview={ELEMENT_PREVIEW_ID}&ver={V}](#)
> > Which is interpreted just fine by the is_preview_mode function that tests for $_GET['elementor-preview']
> > But when the permalink is set to a custom value (/%category%/%postname%/ in my case) the requests is sent to:
> > [http://{DOMAIN}/header/{HEADER}/?elementor-preview={ELEMENT_PREVIEW_ID}&ver={V}](#)
> > Which is rewritten by **my** nginx to:
> > [http://{DOMAIN}/index.php?q=/header/{HEADER}/elementor-preview=99&ver=1587763043](#)
> > Which builds
> > ```
> > $_GET = [
> >     "q"=>"/header/{HEADER}/elementor-preview=99",
> >     "ver" => "1587763043"
> > ]
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > This is obviously wrong, 'elementor-preview' should be in a separate variable. When looking at my nginx config, the error was obvious:
> > ```
> > try_files $uri $uri/ /index.php?q=$uri$args;
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > We can see the first argument is lost and merged with q=, so I updated the rule:
> > ```
> > try_files $uri $uri/ /index.php?q=$uri&$args;
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > And it works just fine now.
> > Seeing all of you also having the same error, I'm guessing that I was not the only one with an invalid redirect rule. So I hope this can help you.
> 


Hello, can you tell me where I can find this? I'm trying to do the same but I can't find it in the files

Thanks.

**Comment by ngarafol** [comment] 2022-02-21 23:36
> > > I investigated and found the issue (for me). It seems to be a problem with the web server rewrite rule, not this plugin in particular.
> > > In case the permalink is set to simple, the ajax request that loads the preview is:
> > > [http://{DOMAIN}/?header={HEADER}&elementor-preview={ELEMENT_PREVIEW_ID}&ver={V}](#)
> > > Which is interpreted just fine by the is_preview_mode function that tests for $_GET['elementor-preview']
> > > But when the permalink is set to a custom value (/%category%/%postname%/ in my case) the requests is sent to:
> > > [http://{DOMAIN}/header/{HEADER}/?elementor-preview={ELEMENT_PREVIEW_ID}&ver={V}](#)
> > > Which is rewritten by **my** nginx to:
> > > [http://{DOMAIN}/index.php?q=/header/{HEADER}/elementor-preview=99&ver=1587763043](#)
> > > Which builds
> > > ```
> > > $_GET = [
> > >     "q"=>"/header/{HEADER}/elementor-preview=99",
> > >     "ver" => "1587763043"
> > > ]
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > This is obviously wrong, 'elementor-preview' should be in a separate variable. When looking at my nginx config, the error was obvious:
> > > ```
> > > try_files $uri $uri/ /index.php?q=$uri$args;
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > We can see the first argument is lost and merged with q=, so I updated the rule:
> > > ```
> > > try_files $uri $uri/ /index.php?q=$uri&$args;
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > And it works just fine now.
> > > Seeing all of you also having the same error, I'm guessing that I was not the only one with an invalid redirect rule. So I hope this can help you.
> 
> Hello, can you tell me where I can find this? I'm trying to do the same but I can't find it in the files
> 
> Thanks.

It is nginx syntax, so in case you are using nginx as webserver instead of apache/httpd, you would find it in /etc/nginx/conf.d/ or sites-enabled folder, depends on what structure do you use.

**Comment by AliMD** [comment] 2022-08-23 12:18
`try_files $uri $uri/ /index.php?q=$uri&$args;` 😮 

It's not the right way and it causes many problems!

For example, you can`t pass query `q` from the client anymore! Or if args is empty we have separate `&` at the end & many other issues!

It's my Nginx configuration at the enterprise-ready scale.

```
location / {
  try_files $uri $uri/ /index.php$is_args$args;
}

location @php-fpm {
  try_files     $uri =404;
  fastcgi_pass  php-fpm;
  include       /etc/nginx/conf.d/fastcgi.conf;
}

location ~ [^/]\.php(/|$) {
  try_files     $uri $uri/ /index.php$is_args$args @php-fpm;
  fastcgi_pass  php-fpm;
  include       /etc/nginx/conf.d/fastcgi.conf;
}
```

Remind to change the `/etc/nginx/conf.d/fastcgi.conf` to your `fastcgi.conf` file, It's includes `fastcgi_param ...` lines.

**Comment by karser** [comment] 2022-09-10 12:08
@AliMD your solution worked for me
I changed from
```
    location / {
                index  index.html index.htm index.php;
                try_files $uri $uri/ /index.php;
    }
```
to
```
    location / {
                index  index.html index.htm index.php;
                try_files $uri $uri/ /index.php$is_args$args;
    }
```

**Comment by AliMD** [comment] 2022-09-10 12:31
> @AliMD your solution worked for me
> I changed from
> ```
>     location / {
>                 index  index.html index.htm index.php;
>                 try_files $uri $uri/ /index.php;
>     }
> ```
> to
> ```
>     location / {
>                 index  index.html index.htm index.php;
>                 try_files $uri $uri/ /index.php$is_args$args;
>     }
> ```

You also need to add `location ~ [^/]\.php(/|$)` to optimise request and minimum disk iops

**Comment by rami-elementor** [comment] 2022-11-27 14:21
> saving the permalinks worked for me

Closing issue.

**Closed by rami-elementor** 2022-11-27 14:21 UTC
Labels: bug

**Comment by andykaufseo** [comment] 2022-12-11 19:15
> You also need to add `location ~ [^/]\.php(/|$)` to minimum disk iops and optimise performance

where to add `location ~ [^/]\.php(/|$)` ?

replace location / with it or somewhere else?
