### ISSUE TITLE
Add more breakpoints especially for laptop 

### ISSUE THREAD

**Issue by kathleenverhelle** [elementor/elementor#11680] opened 2020-06-19 06:00 UTC
## Prerequisites

- [ X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

Hello, i would like to suggest to add breakpoints for laptop devices also in a future update for Elementor? When working with complex designs, the layout on laptop is not okay... Anyone who wants to share how they solve this now?

I think this would be great in the next version of Elementor?

**Comment by shilo-ey** [comment] 2020-06-19 15:21
duplicate of #2043

**Closed by shilo-ey** 2020-06-19 15:21 UTC
