### ISSUE TITLE
🔗 ⛔ 🐞 Bug Report: Empty loop grid when selecting from Taxonomy Filter with Loop Grid set to Current Query (Duplicate of #23360)

### ISSUE THREAD

**Issue by Erudition** [elementor/elementor#23755] opened 2023-09-12 23:27 UTC
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Love the new Taxonomy Filter! However, it doesn't seem to be working for me.
I have a loop grid on my archive pages which shows educational courses. In Theme Builder -> Archive template, I added the taxonomy filter widget and connected it to the loop grid. Since this is an archive template page, the loop grid is set to "Current Query" which must be the case for the autogenerated category and tag pages to have the correct contents.

In the Elementor editor, and on the frontend, clicking any filter completely hides all the loop grid items. This is despite the fact that there are definitely items that meet the filter. Worse, even if I switch back to the "All" filter, they never come back. They are hidden for good.

I notice that if I set the loop grid to be a static filter (e.g. all Courses), the filter works as expected. However this is an archive page template, so it must be set to Current Query.

I reviewed [the documentation for the Taxonomy Filter](https://elementor.com/help/taxonomy-filter-widget/) and it lists two requirements:

- The Taxonomy widget is currently an experimental feature, therefore you must activate it. To activate it, see [Elementor experiments](https://elementor.com/help/elementor-experiments-2/). 
- The Taxonomy widget can only be used as part of a Loop Grid. Therefore, in order to use the Taxonomy widget, make sure the Loop Grid is active.

I have satisfied these requirements, and I note that "Loop Grid must not be set to Current Query" is not one of them. Therefore I can be sure that this is a bug report and not a feature request.

### Steps to reproduce

1. Add a Loop Grid to an archive page with the query set to Current Query.
2. Add a Taxonomy Filter and attach it to the Loop Grid.
3. Ensure there are items in the list, and choose a filter which would also leave some items in the list.
4. Observe that the grid is empty.
5. Try switching back to the "All" filter.
6. Observe that the items never reappeared.

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

<details>
<summary>Click to reveal</summary>

````txt


					
== Server Environment ==
	Operating System: Linux
	Software: h2o/2.2.6
	MySQL version: MySQL Community Server (GPL) v5.7.12
	PHP Version: 8.0.30
	PHP Memory Limit: 1024M
	PHP Max Input Vars: 5000
	PHP Max Post Size: 518M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.3.1
	Site URL: https://3215b04c-84e4-4a42-8132-902bb6d4b51e.static.getshifter.net
	Home URL: https://3215b04c-84e4-4a42-8132-902bb6d4b51e.static.getshifter.net
	WP Multisite: No
	Max Upload Size: 512 MB
	Memory limit: 256M
	Max Memory limit: 512M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: America/Chicago
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.7.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/115.0

== Active Plugins ==
	Activity Log
		Version: 2.8.8
		Author: Activity Log Team

	Code Snippets
		Version: 3.4.2
		Author: Code Snippets Pro

	DynamicConditions
		Version: 1.6.2
		Author: RTO GmbH

	Elementor
		Version: 3.16.1
		Author: Elementor.com

	Elementor Pro
		Version: 3.16.0
		Author: Elementor.com

	Enable Media Replace
		Version: 4.1.2
		Author: ShortPixel

	Pods - Custom Content Types and Fields
		Version: 2.9.19
		Author: Pods Framework Team

	Regenerate Thumbnails Advanced
		Version: 2.4.1
		Author: ShortPixel

	WP Import Export Lite
		Version: 3.9.24
		Author: VJInfotech


== Must-Use Plugins ==
	EVA
		Version: 1.6.4
		Author: DigitalCube


== Features ==
	Custom Fonts: 0
	Custom Icons: 0

== Integrations ==
	


== Elementor Experiments ==
	Optimized DOM Output: Active
	Improved Asset Loading: Active
	Improved CSS Loading: Active
	Inline Font Icons: Active
	Additional Custom Breakpoints: Active
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active
	Upgrade Swiper Library: Active
	Grid Container: Active
	Default to New Theme Builder: Active
	Hello Theme Header & Footer: Active
	Editor Top Bar: Active
	Landing Pages: Active
	Nested Elements: Active
	Lazy Load Background Images: Active
	Pages Panel: Inactive by default
	Global Style Guide: Active
	Page Transitions: Active
	Notes: Active
	Form Submissions: Active
	Scroll Snap: Active
	Menu: Active
	Taxonomy Filter: Active


== Log ==
	
JS: showing 3 of 3JS: 2023-07-12 06:58:08 [error X 11][https://3215b04c-84e4-4a42-8132-902bb6d4b51e.static.getshifter.net/wp-content/plugins/elementor/assets/js/admin.min.js?ver=3.14.1:3:48021] l[0] is undefined 
JS: 2023-07-12 15:14:05 [error X 1][https://3215b04c-84e4-4a42-8132-902bb6d4b51e.static.getshifter.net/wp-content/plugins/elementor/assets/js/frontend.min.js?ver=3.14.1:2:31128] elementor.settings.page is undefined 
JS: 2023-09-12 22:37:16 [error X 35][https://3215b04c-84e4-4a42-8132-902bb6d4b51e.static.getshifter.net/wp-content/plugins/elementor/assets/js/frontend-modules.min.js?ver=3.16.1:2:28369] this.elements.$container.position() is undefined 

PHP: showing 5 of 5PHP: 2023-07-20 23:15:21 [warning X 3][../wp-content/plugins/elementor-pro/modules/query-control/module.php::767] Attempt to read property "name" on null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-08-02 12:37:42 [warning X 16][../wp-content/plugins/elementor/core/common/modules/ajax/module.php::175] Undefined array key "data" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-08-02 13:52:15 [warning X 1][../wp-content/plugins/elementor-pro/modules/dynamic-tags/pods/tags/pods-text.php::20] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-08-02 15:16:21 [warning X 18][../wp-content/plugins/elementor-pro/modules/dynamic-tags/pods/tags/pods-url.php::56] Array to string conversion [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-09-12 17:30:36 [warning X 8][../wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php::150] Undefined array key "condition_type" [array (
  'trace' => '
#0: ../wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(150): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_template_json_item()
#2: ../wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(120): class type array_map()
#3: ../wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(59): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_templates_json()
#4: ../wp-content/plugins/elementor/data/base/endpoint.php(158): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> get_items()
',
)]

Log: showing 20 of 342023-08-02 13:48:44 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.14.1',
  'to' => '3.15.0',
)]
2023-08-18 18:43:36 [info] elementor::elementor_updater Started 
2023-08-18 18:43:36 [info] Elementor/Upgrades - _on_each_version Start  
2023-08-18 18:43:36 [info] Elementor/Upgrades - _on_each_version Finished 
2023-08-18 18:43:37 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.15.1',
  'to' => '3.15.2',
)]
2023-08-18 18:43:37 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.15.1',
  'to' => '3.15.2',
)]
2023-09-12 17:29:38 [info] elementor-pro::elementor_pro_updater Started 
2023-09-12 17:29:38 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-09-12 17:29:38 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-09-12 17:29:38 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.15.0',
  'to' => '3.16.0',
)]
2023-09-12 17:29:38 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.15.0',
  'to' => '3.16.0',
)]
2023-09-12 17:30:13 [info] elementor::elementor_updater Started 
2023-09-12 17:30:13 [info] Elementor/Upgrades - _on_each_version Start  
2023-09-12 17:30:13 [info] Elementor/Upgrades - _on_each_version Finished 
2023-09-12 17:30:13 [info] Elementor/Upgrades - _v_3_16_0_container_updates Start  
2023-09-12 17:30:13 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.15.2',
  'to' => '3.16.1',
)]
2023-09-12 17:30:13 [info] Elementor/Upgrades - _v_3_16_0_container_updates Finished 
2023-09-12 17:30:13 [info] Elementor/Upgrades - _v_3_17_0_site_settings_updates Start  
2023-09-12 17:30:13 [info] Elementor/Upgrades - _v_3_17_0_site_settings_updates Finished 
2023-09-12 17:30:13 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.15.2',
  'to' => '3.16.1',
)]



== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatible

== Elementor Pro - Compatibility Tag ==
	

				

````

</details>

**Comment by hein-obox** [comment] 2023-09-13 14:37
The Current Query hasn't been developed for this experiment yet.
I will require more work, also for the Loop Grid.

**Comment by Erudition** [comment] 2023-09-13 19:14
In that case it's a documentation bug.

**Comment by nicholaszein** [comment] 2023-09-17 05:25
Hi, @Erudition,

Thank you for reaching out! 🙏 

### ⛔ After reviewing your report we concluded this is not a bug caused by Elementor. The feature you're referring to is not yet supported.

If you think this should be an Elementor feature, please submit a new [🚀 Feature Request](https://github.com/orgs/elementor/discussions/new?category=feature-request), and we will consider it in the future if there is enough demand (votes) from other users.

----

Hello @XXX!

Thank you for your submission! 🙏 

### 🔗 🐞 This issue is a Duplicate of #23360

Which is on the same subject. 

For this reason, I'm closing this thread and 🔃 **Merging** it with the original, so we can have all the discussions in one location, and deal with it more efficiently.

Feel free to continue the conversation there. 😉 

### 🔍 Please, in the future, remember to check if there isn't any thread similar to yours already opened. 

Kind regards

**Closed by nicholaszein** 2023-09-17 05:25 UTC
Labels: product/pro, component/loop-builder, component/query, mod*, component/theme-builder/archive-template, component/filter/taxonomy
