### ISSUE TITLE
✅ 🔗 🚀 Feature Request: Enable Elementor Editor for custom post Archives (of a custom taxonomy) (Duplicate of #4440)

### ISSUE THREAD

**Issue by javiercriado** [elementor/elementor#8248] opened 2019-06-03 14:19 UTC
This feature is really important if you wan to customize your website by working with custom post types, custom taxonomies and custom fields (not only the default pages, posts and categories entities).

Topics on this matter were closed without addressing a solution or a valid explanation:
#5882
#605
@bainternet, @arielk

The only way to solve this issue is by (purchasing and) installing third party plugins like crocoblock for example.

**You should be able to design your own Archive Template for your custom post type.
Also configure visualization conditions by custom taxonomy terms for header, footer, archive, etc.**

@alexatoxy, @nspell, @remyrichard, @TheCrystalRose, @michelmarcondes, @barrychapman

I don't know about the other users position, but for me the fact that this important feature and the (paying) users requests are being ignored is going to force me not to continue with my Elementor Expert plan ($199 Yearly) (user: a@piedra.pe).

**Comment by TheCrystalRose** [comment] 2019-06-03 14:29
I agree @javiercriado! I’ve been a paying customer for Elementor Pro for nearly 3 years now and the only explanation I got for making an Archive template for CPTs is to edit the code, which doesn't make me comfortable as a non coder. I’ve also read how messing with code doesn’t exactly work, anyway, and I refuse to put my site at risk by doing something with the code.

This feature would also solve a lot of problems that my members have with my site. Right now, I’ve created a work around until the Archive issue gets taken care of, by creating a dozen or more pages for my clients to search through, but it’s just an extra step that isn’t necessary if this issue got addressed.

Majority people nowadays use CPTs, especially within new plugins as well, so I think it’s crucial that any feature with Elementor accommodates that.

**Comment by AlbanL74fr** [comment] 2019-06-04 06:42
I need this feature too. My use case :
- I create a custom post type
- I have hundreds of posts for this custom type
- I need to create a search field and dedicated search result page that filters out and display only the element of this specific custom post type in accordance with the search term or filters selected (also a missing feature)

If at least, there was the "Query" section in the "Posts Archives" like in the "Posts" widget, that would be a good start

**Comment by momo-fr** [comment] 2019-06-04 07:27
Hi, I do not understand where the problem is, I use custom CPT with Elementor PRO and I can create my template pages according to the desired category or categories. I make custom archive pages without problems. What are you talking about ?
![what-is-the-problem](https://user-images.githubusercontent.com/29410831/58859568-57604500-86aa-11e9-8013-6a06b69d0b53.jpg)
![display-conditions](https://user-images.githubusercontent.com/29410831/58859775-e4a39980-86aa-11e9-9d5a-5d36d3f0ff01.jpg)

**Comment by TheCrystalRose** [comment] 2019-06-04 10:38
@momo-fr We’re talking about Archive Templates, not a Single Page/Post template. Products is part of Woocommerce which they’ve integrated, but other CPTs are not included to create a Search Results page Archive template. That’s the problem.

**Comment by momo-fr** [comment] 2019-06-04 11:22
You whant to create a Search Results page Archive template? Ok sorry, I did not understand exactly that. Did you see that? https://www.youtube.com/watch?v=kPAUEShgdoo

**Comment by momo-fr** [comment] 2019-06-04 11:43
Ok, I tried to create page templates of different search results and you're right, it does not work. Sorry.

**Comment by javiercriado** [comment] 2019-06-04 13:19
> I need this feature too. My use case :
> 
>     * I create a custom post type
> 
>     * I have hundreds of posts for this custom type
> 
>     * I need to create a search field and dedicated search result page that filters out and display only the element of this specific custom post type in accordance with the search term or filters selected (also a missing feature)
> 
> 
> If at least, there was the "Query" section in the "Posts Archives" like in the "Posts" widget, that would be a good start

I'm sorry @AlbanL74fr but you're off topic (and sabotaging this issue solution)

I don't know if Elementor can handle your issue, but Crocoblock can with it's JetSmartFilters module.

**Comment by javiercriado** [comment] 2019-06-04 13:21
> Hi, I do not understand where the problem is, I use custom CPT with Elementor PRO and I can create my template pages according to the desired category or categories. I make custom archive pages without problems. What are you talking about ?
> ![what-is-the-problem](https://user-images.githubusercontent.com/29410831/58859568-57604500-86aa-11e9-8013-6a06b69d0b53.jpg)
> ![display-conditions](https://user-images.githubusercontent.com/29410831/58859775-e4a39980-86aa-11e9-9d5a-5d36d3f0ff01.jpg)

@momo-fr 
the user @AlbanL74fr is off topic. 
please read the posts from me and @TheCrystalRose

**Comment by momo-fr** [comment] 2019-06-04 13:34
Ok, I tried to create page templates of different search results and you're right, it does not work. Sorry for my confusion.

**Comment by MichaelDarko** [comment] 2019-06-04 13:40
I agree. A have no idea why are they ignoring and closing this issue. CPT and ACF integration is half-baked in general. Elementor is used by a lot of professionals and to build more complex websites you absolutely need features like this.

**Comment by javiercriado** [comment] 2019-06-04 14:06
Here's the (original) issue in a more graphical way.

with Elementor you can't do this for example: 
![imagen](https://user-images.githubusercontent.com/11529913/58884749-9db3a500-86a6-11e9-991a-bca9e8ec4769.png)
(credits to crocoblock)

you can't design / define a header or footer for a custom taxonomy or custom taxonomy term.
you can't design / define an archive template for a custom post type either.

this cuts the ability to work efficiently with custom post types and taxonomies, because if you want to de so you would have to manually create a page for each custom taxonomy term instead of just having a custom post type archive template.

let's imagine you have the custom post type "book" and the custom taxonomy "genre".
if you want to list your books you have to create a page for each taxonomy term and add a widget to display these custom posts.
if you could create archive templates for the custom post type (and taxonomy) every taxonomy term would have an automatically created archive page (just as the default "category" taxonomy has and you can see in every wordpress blog)

I hope I've explained this clear because all of these can be a bit confusing.

Thank you for reading.

**Comment by TheCrystalRose** [comment] 2019-06-27 05:23
I'm very curious if we'll ever hear from the team about this issue...? Elementor crew, do you have any updates, please?

**Comment by javiercriado** [comment] 2019-07-23 22:46
any updates?

**Comment by SALITEL** [comment] 2019-08-14 12:03
I need this!!!
any updates?

**Comment by tonipanacek** [comment] 2019-08-14 13:19
Also rather perplexed why this doesn't exist with Elementor -- it works to create single page templates for custom post types but not the archive template?? That doesn't make sense to me.

**Comment by MarcMurrayUpfront** [comment] 2019-08-20 14:56
@javiercriado javiercriado has explained the issue really clearly, this is something that I would consider barebones essential, we are working on a site now where we have to create 50+ individual archive pages for every category of a custom post type, and should the client add a new category they are going to have to come calling us. A response from the team on the priority level of this issue would be great.

**Comment by javiercriado** [comment] 2019-08-20 17:23
please add to the core! critical

**Comment by iamntz** [comment] 2019-08-24 09:43
Just FIY, this **_is_** posible by default. 

There is a very small detail that is not documented anywhere from what I've seen: when define custom post types, you MUST specify `'has_archive' => true`. The default is false. (it does make sense when you think about it).

Also, defined taxonomies MUST have these two options set to true:

```
'public' => true,
'show_in_nav_menus' => true,
```

**Comment by lightstylenz** [comment] 2019-08-27 06:00
@javiercriado, sorry to jump in but you might have a +1 here...Is the fact that I cannot see my CPT Taxonomy related to this missing feature?

This case is even simpler; I can't map the Taxonomy to display on my CPT Single Template :(
![Untitled-1](https://user-images.githubusercontent.com/42532747/63744804-8e827300-c8f4-11e9-9460-f85cd28d4664.gif)

**Comment by TheCrystalRose** [comment] 2019-09-02 20:21
> Just FIY, this **_is_** posible by default.
> 
> There is a very small detail that is not documented anywhere from what I've seen: when define custom post types, you MUST specify `'has_archive' => true`. The default is false. (it does make sense when you think about it).
> 
> Also, defined taxonomies MUST have these two options set to true:
> 
> ```
> 'public' => true,
> 'show_in_nav_menus' => true,
> ```

Thank you soooo much for clearing that up! It worked!!

**Comment by hannyramzy** [comment] 2019-09-17 03:25
> Just FIY, this **_is_** posible by default.
> 
> There is a very small detail that is not documented anywhere from what I've seen: when define custom post types, you MUST specify `'has_archive' => true`. The default is false. (it does make sense when you think about it).
> 
> Also, defined taxonomies MUST have these two options set to true:
> 
> ```
> 'public' => true,
> 'show_in_nav_menus' => true,
> ```

Yeah this work for me. Thanks!

**Comment by javiercriado** [comment] 2019-10-03 22:14
> Just FIY, this **_is_** posible by default.
> 
> There is a very small detail that is not documented anywhere from what I've seen: when define custom post types, you MUST specify `'has_archive' => true`. The default is false. (it does make sense when you think about it).
> 
> Also, defined taxonomies MUST have these two options set to true:
> 
> ```
> 'public' => true,
> 'show_in_nav_menus' => true,
> ```

Thanks a lot!

It worked.

And yes...it isn't documented anywhere.

I hope this thread will guide everyone who can find themselves stuck in the same issue

![imagen](https://user-images.githubusercontent.com/11529913/66167870-113bd380-e601-11e9-8a30-cd271b5b55e6.png)

**Comment by shibindinesh** [comment] 2019-12-02 03:40
> > Just FIY, this **_is_** posible by default.
> > There is a very small detail that is not documented anywhere from what I've seen: when define custom post types, you MUST specify `'has_archive' => true`. The default is false. (it does make sense when you think about it).
> > Also, defined taxonomies MUST have these two options set to true:
> > ```
> > 'public' => true,
> > 'show_in_nav_menus' => true,
> > ```
> 
> Thanks a lot!
> 
> It worked.
> 
> And yes...it isn't documented anywhere.
> 
> I hope this thread will guide everyone who can find themselves stuck in the same issue
> 
> ![imagen](https://user-images.githubusercontent.com/11529913/66167870-113bd380-e601-11e9-8a30-cd271b5b55e6.png)

@javiercriado Does this works for the Archive page as well? For me, the custom post type has "has Archive" set to True, taxonomies has  public' = true, and  'show_in_nav_menus' => true, but in the Elementor archive template, if I select "Archive Posts" widget, it still shows only "Posts" and no option to Query custom post type. Am I missing something here? Is there any other way to display content on the archive page other than "Archive posts"? Thanks in advance for the response.

**Comment by ykuzmycz** [comment] 2019-12-14 22:24
Is there a way, though, to order the custom post archive by a custom field?  Say you have events with a start date, you'd want to order the events by start date >= today.  This is easily done via custom query id via functions.php but not doable through archives.  Right?

**Comment by iamntz** [comment] 2019-12-16 11:49
@ykuzmycz I'm not sure if _Archive_ widget is the right tool though. For _posts_ widget you should be able to do this with a couple of hooks.

**Comment by javiercriado** [comment] 2019-12-16 14:56
@ykuzmycz you can do it with crocoblock jet engine. with it's posts widget ("jet listing") you can create and style your own posts loop and order it via custom field, taxonomy, and more complex query rules easily.

**Comment by ykuzmycz** [comment] 2019-12-16 15:43
@iamntz Thanks.  I shifted to using post and a custom query via functions.php.  Your plug-in does look interesting!

@javiercriado Thanks.  JetEngine does look interesting for sure!  I added "Ele Custom Skin" to allow for a custom loop which I then plugged into a post view with a custom query.  Same approach (sorta).  I'll have to explore JetEngine.  I did notice that their subscription model kills the plugin (not allowing creating new pages with it) after a year (if you cancel) versus just not providing support/updates.

**Comment by barrychapman** [comment] 2020-01-10 22:05
> @ykuzmycz you can do it with crocoblock jet engine. with it's posts widget ("jet listing") you can create and style your own posts loop and order it via custom field, taxonomy, and more complex query rules easily.

Except you cannot hook into custom queries you already have :(

**Comment by marcfon** [comment] 2020-03-15 13:06
I've setup a **custom taxonomy** using Pods but can't get this taxonomy to show up in the Archive template section. As a side note a custom post type using Pods does show up as an option.

When I browse to the taxonomy archive (eg. /jobs/remote/) it does render as an archive but just with the general archive template I've setup.

What could be going on here? How could I create a custom archive template in Elementor for this specific taxonomy?

**Comment by TomRaraAvis** [comment] 2020-08-13 05:40
#4440 [Feature request] Posts / Archive loop item template designer

**Comment by odditi** [comment] 2020-08-24 05:27
@barrychapman , I struggled with this for days, and eventually i manged to achieve the end result using Dynamic Content plugin and "dynamic posts" widget (or views widget).
I have to say, in my case I created a custom post type *and* set the _archive_ parameter to "true", but it still didn't show up when i would create an archive template in elementor. 
With the Dynamic Content plugin, you can set really complex queries  quite easily and it even works dynamically, so you don't have to create separate pages for each archive category.

**Comment by amberflynn** [comment] 2020-11-01 03:01
> Just FIY, this **_is_** posible by default.
> 
> There is a very small detail that is not documented anywhere from what I've seen: when define custom post types, you MUST specify `'has_archive' => true`. The default is false. (it does make sense when you think about it).
> 
> Also, defined taxonomies MUST have these two options set to true:
> 
> ```
> 'public' => true,
> 'show_in_nav_menus' => true,
> ```

Thanks for the tip! 
Could you kindly indicate in which files we can make these changes?

**Comment by webndesign** [comment] 2020-12-12 19:17
Hi everyone, 
The solution that is working for everyone here, unfortunately, does not work for me. 
I had already set the values to 'true' for both 'public' and 'show in nav menu', but I cannot get it to show my cpt when creating anything in Theme builder. 
Why is Elementor still not providing a straight-forward fix for that. 
I have also read CPT threads where admins there say that it's not an issue from their end!

Anyone come up with a different solution that may work please?
I'm also using Ele Custom Skin.

**Comment by valziyan** [comment] 2021-01-06 03:05
if you are using Custom Post Type UI. Edit the post type and scroll to settings. There you will find Has Archive which is set to default false, change that to true. And it will work.

**Comment by stashcat99** [comment] 2021-04-24 15:43
The way may work for Custom Post Types (I created my CPTs with Crocoblock and they don't show up).

But what it definitely doesn't work for are Custom Taxonomies. After all, each term has its own archive, so to speak, and I can't set a custom template for it in Theme Builder. It always takes the general template for archives.

Does anyone know a solution for this?

**Comment by stashcat99** [comment] 2021-04-24 16:03
Here you can see it: I create a template for an archive. Under settings of the page I find ALL archives for preview in Elementor. But in Display Conditions all archives for Custom Taxonomies, which I created with Crocobloc, are missing.

![themebuilder](https://user-images.githubusercontent.com/83130404/115964965-39628e80-a527-11eb-8a3c-1c25a69e7fd7.jpg)

**Comment by itsViney** [comment] 2022-01-25 16:40
+1 same here. I've created a custom taxonomy, set 'public' => true and show_in_nav_menus' => true but still doesn't appear in the list of template display conditions.

Also tried adding the custom taxonomy to the default 'Posts' post type but that didn't help either.

**Comment by Panagiotis-Kouvelis** [comment] 2022-03-13 13:39
Hi to all, pro tier user here.

I can confirm that there is no fix on that yet. I'm using Pods and there is no way to define Elementor templates that are used only in specific custom taxonomies or a specific custom taxonomy term.

My website uses custom post types to define products, knowledge base articles, courses, services, and more. But to create the information architecture proposed by web best-practices by NN/g I have to use parent pages of those custom post types in order to group them and provide landing pages for those groups for SEO and marketing promotions.

There is another hard-bug or hard-lock issue here that other peers are not mentioning, and for this to get solved, the issue in the thread should be solved.

The other issue that some will fall is that:

When you have that kind of a system like the one I'm describing, then the aforementioned landing pages have the same slug/permalink as the archive pages.

When you try to edit those landing pages, the Elementor Editor throws the error that the "the_content" code was not found in the page and it cannot open.

The solution from Elementor's official documentation states that we should create a template for that archive and define the condition to open on that archive to solve this problem.

But with the problem described in this issue here, not having the custom taxonomies available in the template conditions list, creates a locked situation that cannot get solved.

So, currently, I'm actually locked out of being able to edit my landing pages because Elementor Editor won't open, and unable to create the solution that Elementor officially gives, which is to create a template for that archive.

Elementor (the company) heavily advertised the integration of dynamic data in its solution and presents itself in the market as a professional page builder.

I know that I might sound a little hostile the way I close my reply, but I'm really not. I just believe that the people behind Elementor should adhere to their promises and solve this so we all can continue our business and earn our living.

I'm sure many people in other places are also affected greatly by this incomplete integration of dynamic data from custom entities in Elementor.

**Comment by nicholaszein** [comment] 2023-08-01 21:18
Hello there!

Thank you all for your feedback, and patience! 🙏 

I wanted to update you on this issue to clarify some confusion.

As @iamntz correctly pointed out [here](https://github.com/elementor/elementor/issues/8248#issuecomment-524536953), it is already completely possible to create archive templates for both Custom Post Types and Custom Taxonomy Terms. All you have to do is to ensure both are: 

1. Public => true
2. Publicly Queryable => true
3. Has Archive => true
4. Show in Menu => true
5. Show in Nav Menus => true
6. Exclude from Search => false

If you set them up correctly, they will appear everywhere in Elementor where you can select Post Types or Terms. 😉 

Additionally, if you wish to also edit Custom Posts Types with Elementor, make sure you have selected them in the Elementor **`Settings`** > **`General`** > **`Post Types`**. 

Now it's also possible to use the new **`Loop Grid`** widget and create your own **`Loop Item`** templates using native Elementor widgets to design your own listings. This feature was released with Elementor Pro 3.8.0, and was directly connected with issue #4440.

### ✅ After reading all the comments and considering what is being requested, we concluded that this issue has been already solved.

For this reason, I'm closing this issue and locking comments.

If you think there are still missing features, please submit a new [🚀 Feature Request](https://github.com/orgs/elementor/discussions/new?category=feature-request), and we will consider it in the future if there is enough demand (votes) from other users.

Kind regards

**Closed by nicholaszein** 2023-08-01 21:18 UTC
Labels: request/enhancement, product/pro, component/theme-builder, status/merged, solved_by_loop, 🚀 shipped, mod*, component/theme-builder/archive-template, component/archive-posts
