### ISSUE TITLE
New Elementor Pro menu cart has big CLS issues and flashes open on screen then collapses on page load

### ISSUE THREAD

**Issue by jazir5** [elementor/elementor#16204] opened 2021-08-31 04:09 UTC
## Description

The new menu cart widget has massive cls issues. My CLS score went from .03 to .223, which immediately makes it fail CWV. In addition to that the menu cart flashes open to display the contents of the menu cart, then collapses and jolts the screen around, which is the CLS effect

## Steps to reproduce

Place the new menu cart set to minicart in a header. 

Load a page on the frontend and visually see the CLS issue.

Perform a lighthouse test in chrome>inspect>lighthouse.

**Comment by jazir5** [comment] 2021-09-03 04:20
@avivu @shilo-ey

**Comment by avivu** [comment] 2021-09-05 15:18
Hello @jazir5,

We examined the issue and failed in reproducing it.
We didn't find a visible flash or increase in load time on Chrome lighthouse on our testings.
It may be a plugin that delays the load of a minified external CSS or a conflict with another plugin.


Please Please try:

- Deactivate all your plugins besides Elementor (and Elementor Pro). If this solves the problem, gradually activate your plugins one by one until you spot the problematic plugin.
 - Change your WordPress theme to [Hello Theme](https://wordpress.org/themes/hello-elementor/) (or other default WordPress theme).

And see if the issue persists. 
If the issue is still occurring, please contact our support at support @elementor.com for guidance in resolving this issue and mention that you were directed by me and reference this issue.

Thanks.

**Closed by avivu** 2021-09-05 15:18 UTC
