### ISSUE TITLE
🔗 🚀 Feature Request: Popup Trigger on Date/Time (Duplicate of #6899)

### ISSUE THREAD

**Issue by StacyWV** [elementor/elementor#12770] opened 2020-10-07 22:11 UTC
## Prerequisites

- [X ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
I have multiple customers that need the ability to have a popup open at a specific date/time. This could be either the timestamp on the server or the time setting via WordPress. 

**Describe the solution you'd like**
Since this would be dynamic / asynchronous, it would have to include maybe some form of ajax or similar? I'm not sure on that part, but how it would work is when a person is viewing the stream via my website (training videos), which are live, at a specific time during that presentation, I need a popup to display.  For example, if I am running a training event from 6pm - 7:30pm, at 7:15pm I want a popup that I've created via Elementor to display for everyone that's on that page.

**Describe alternatives you've considered**
I've tried doing the dynamic conditions and dynamic visibility plugins "hidden until date/time" addon, but the problem that exists is that it's not asynchronous and relies on a page refresh for it to work as I need it to.  I want this new information to display *automatically* without any action from the user that is currently viewing the page.

**Additional context**

**Comment by DorShahar** [comment] 2020-11-18 11:08
Merged issue

I merged this issue with  #6899, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.
Thanks for your feedback!

**Closed by DorShahar** 2020-11-18 11:08 UTC
Labels: request/enhancement, product/pro, component/popup, product/beta3.11

**Comment by nicholaszein** [comment] 2023-01-27 16:06
Hello @steve-manes!

Thank you for your submission! 🙏 

### 🔗 This issue is a Duplicate of #6899

Which is on the same subject. 

For this reason, I'm closing this issue and 🔃 **Merging** it with the original, so we can have all the discussions in one location, and deal with it more efficiently.

We are also beta-testing our new [Popup Advanced Rule for Date and Time range](https://github.com/elementor/elementor/discussions/21125), which covers part of what you're asking. Try the new beta version and let us know if it helps to manage popups better.

Feel free to continue the conversation there. 😉 

Best regards,

Nick
