### ISSUE TITLE
⛔ 🚀 Feature Request: Change swiper library to spline js in elementor

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#19228] opened 2022-07-21 14:45 UTC
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

hi elementor team!

As you know, elementor now uses the swiper library for carousels and sliders. But splide library can be much better than swiper.
This library is not much smaller than swiper and is very optimized. It is also much more advanced.

Please check this out and use it in elementor if possible.

https://splidejs.com/

### Describe the solution you'd like

Change swiper to splide js library

**Comment by m1ga** [comment] 2022-07-21 16:02
duplicate of https://github.com/elementor/elementor/issues/18871
but I wish the would do https://github.com/elementor/elementor/issues/18724 first :smile:

**Comment by 79ho3ein** [comment] 2022-07-22 16:59
> duplicate of #18871 but I wish the would do #18724 first 😄

thanks

**Closed** 2022-07-22 17:00 UTC
Labels: request/feature, component/carousel, dependencies, component/slides, component/loop-builder/carousel, mod*

**Comment by nicholaszein** [comment] 2023-02-13 14:25
Hi @79ho3ein,

we have no plans to replace Swiper.js with Splide.js. 

Thanks for the suggestion though.
