### ISSUE TITLE
🔗 🚀 Feature Request: The default direction of the container after drag and drop (Duplicate of #19708)

### ISSUE THREAD

**Issue by Joliamendi** [elementor/elementor#20597] opened 2022-12-03 17:20 UTC
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

Hello

As you know, in css, the default direction of the container is row. But in Elementor, when we drag and drop a container, the default direction is column.
Shouldn't the default direction be row?
It's also great if we add a container, the default direction is visible.

### Describe the solution you'd like

1- When we drag and drop a container, the default orientation of the container is row (now it is column)

2- After dragging and dropping the container, the default direction should be visible.

![container](https://user-images.githubusercontent.com/103376243/205453431-fe126f3b-0605-44ea-953b-11f2c1919db4.png)

**Comment by nicholaszein** [comment] 2022-12-06 11:25
Hello @Joliamendi!

Thank you for your submission! 🙏

Answering your first question, we set the default direction to be "column" because it is the familiar way with which elements were added to Sections/Columns in the past. We won't change this behavior for now because of this.

### 🔗 This issue is also a Duplicate of #19708

Which is on the same subject.

For this reason, I'm closing this issue and 🔃 **Merging** it with the original, so we can have all the discussions in one location, and deal with it more efficiently.

Feel free to continue the conversation there. 😉 

### ✔️ Please, in the future, remember to check if there isn't an issue similar to yours already opened. 

Best regards,

Nick

**Closed by nicholaszein** 2022-12-06 11:25 UTC
Labels: request/enhancement, type/ui/ux, component/container
