### ISSUE TITLE
🐞 Bug report: Error opning editor after upgrading to 3.6.0

### ISSUE THREAD

**Issue by jtdissing** [elementor/elementor#18235] opened 2022-03-23 12:32 UTC
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

When I try to open elementor editor after upgrading to 3.6.0 it hangs and when I disable elementor pro 3.6.4 there is no issue.

And when I do a roll back to elementor 3.5.6 it works again

You can see the error under logs in System info

### Steps to reproduce

Install lastest version of Elementor and Elementor Pro

Create a new page and edit the page ien Elementor.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: WINNT
	Software: nginx/1.16.0
	MySQL version: MySQL Community Server - GPL v8.0.16
	PHP Version: 7.4.1
	PHP Memory Limit: 256M
	PHP Max Input Vars: 4000
	PHP Max Post Size: 1000M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.9.2
	Site URL: https://dev-vejgaard.local
	Home URL: https://dev-vejgaard.local
	WP Multisite: No
	Max Upload Size: 300 MB
	Memory limit: 40M
	Max Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: da-DK
	Timezone: Europe/Copenhagen
	Admin Email: jdi-dev-email@flywheel.local
	Debug Mode: Inactive

== Theme ==
	Name: Astra
	Version: 3.7.9
	Author: Brainstorm Force
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: da_DK
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.74 Safari/537.36 Edg/99.0.1150.46

== Active Plugins ==
	Admin Columns Pro
		Version: 5.6.4
		Author: AdminColumns.com

	Admin Columns Pro - JetEngine
		Version: 1.0.1
		Author: AdminColumns.com

	Admin Menu Editor Pro
		Version: 2.16.1
		Author: Janis Elsts

	Astra Pro
		Version: 3.6.6
		Author: Brainstorm Force

	Dynamic.ooo - Dynamic Content for Elementor
		Version: 2.4.5
		Author: Dynamic.ooo

	Elementor
		Version: 3.6.0
		Author: Elementor.com

	Elementor Pro
		Version: 3.6.4
		Author: Elementor.com

	FakerPress
		Version: 0.5.3
		Author: Gustavo Bordoni

	Image Regenerate & Select Crop
		Version: 6.2.2
		Author: Iulia Cazan

	JetBlocks For Elementor
		Version: 1.3.0
		Author: Crocoblock

	JetEngine
		Version: 2.11.5
		Author: Crocoblock

	JetEngine - Custom visibility conditions
		Version: 1.1.0
		Author: Crocoblock

	JetEngine - dynamic tables builder
		Version: 1.0.2
		Author: Crocoblock

	JetEngine - Get attachment file link by ID
		Version: 1.1.2
		Author: Crocoblock

	JetEngine - Trim string callback
		Version: 1.0.0
		Author: Crocoblock

	JetFormBuilder
		Version: 1.5.5
		Author: Crocoblock

	JetSearch For Elementor
		Version: 2.1.15
		Author: Crocoblock

	JetSmartFilters
		Version: 2.3.10
		Author: Crocoblock

	JetTabs For Elementor
		Version: 2.1.15
		Author: Crocoblock

	WordPress Toolbar Editor
		Version: 1.4.1
		Author: Janis Elsts

	WP Reset PRO
		Version: 6.04
		Author: WebFactory Ltd

== Elementor Experiments ==
	Optimeret DOM-output: Aktiv
	Forbedret ressourceindlæsning : Inaktiv som standard
	Improved CSS Loading: Inaktiv som standard
	Inline Font Icons: Inaktiv som standard
	Accessibility Improvements: Inaktiv som standard
	Import Export Template Kit: Aktiv som standard
	Additional Custom Breakpoints: Aktiv
	Hide native WordPress widgets from search results: Aktiv som standard
	: Inaktiv som standard
	Flexbox Container: Aktiv
	Default to New Theme Builder: Aktiv som standard
	Landingsside: Aktiv som standard
	Color Sampler: Aktiv som standard
	Favorite Widgets: Aktiv
	Admin Top Bar: Aktiv som standard
	Page Transitions: Aktiv som standard
	Modtagne formularer: Inaktiv
	Scroll Snap: Aktiv som standard

== Log ==
	
PHP: showing 3 of 3PHP: 2022-03-23 13:14:30 [notice X 7][D:\sites\devvejgaard\app\public\wp-content\plugins\elementor\modules\dev-tools\deprecation.php::301] The $control_id argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-03-23 13:14:35 [notice X 2][D:\sites\devvejgaard\app\public\wp-content\plugins\elementor\modules\dev-tools\deprecation.php::301] The $control_id argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: D:\sites\devvejgaard\app\public\wp-content\plugins\elementor\modules\dev-tools\deprecation.php(301): class type trigger_error()
#2: D:\sites\devvejgaard\app\public\wp-content\plugins\elementor\includes\managers\controls.php(523): Elementor\Modules\DevTools\Deprecation -> deprecated_argument()
#3: D:\sites\devvejgaard\app\public\wp-content\plugins\elementor\includes\managers\controls.php(501): Elementor\Controls_Manager -> register()
#4: D:\sites\devvejgaard\app\public\wp-content\plugins\jet-blocks\includes\modules\jet-elementor-extension\jet-elementor-extension.php(95): Elementor\Controls_Manager -> register_control()
',
)]
PHP: 2022-03-23 13:15:01 [notice X 1][D:\sites\devvejgaard\app\public\wp-content\plugins\elementor\core\experiments\experiments-reporter.php::89] Undefined index: title [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

== Elementor - Compatibility Tag ==
	
	Dynamic.ooo - Dynamic Content for Elementor: Compatibility not specified
	Elementor Pro: Compatibility not specified
	JetBlocks For Elementor: Compatibility not specified
	JetSearch For Elementor: Compatibility not specified
	JetTabs For Elementor: Compatibility not specified

== Elementor Pro - Compatibility Tag ==

**Comment by 79ho3ein** [comment] 2022-03-23 13:21
Many users have reported this bug in elementor community ...

**Comment by jtdissing** [comment] 2022-03-23 14:18
I can see that, but the scary part is that they talk problems with different plugins and  upgrading memory. Buth none of this helps, and the plugin that gives me problems are elementor pro, so can you do something or at least tell what the problem are, etc.

**Comment by tkima** [comment] 2022-03-23 14:43
Same here. 

When elementor-mode=safe still not working.
When version=3.6 > wp-config.php > WP_DEBUG = true it wil load the editor. 
When reverting to version 3.5.6 it is working. 

Error log 3.6.0: 
PHP: 2022-03-23 15:35:30 [notice X 3][/var/www/html/wp-content/plugins/elementor/core/experiments/experiments-reporter.php::89] Undefined index: title [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

And after some scrolling:
PHP: 2022-03-23 15:35:30 [notice X 4][/var/www/html/wp-content/plugins/elementor/core/experiments/experiments-reporter.php::89] Undefined index: title [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-03-23 15:36:35 [notice X 4][/var/www/html/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] Het argument $control_id is verouderd sinds versie 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-03-23 15:36:40 [notice X 1][/var/www/html/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] Het argument $control_id is verouderd sinds versie 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /var/www/html/wp-content/plugins/elementor/modules/dev-tools/deprecation.php(301): class type trigger_error()
#2: /var/www/html/wp-content/plugins/elementor/includes/managers/controls.php(523): Elementor\Modules\DevTools\Deprecation -> deprecated_argument()
#3: /var/www/html/wp-content/plugins/elementor/includes/managers/controls.php(501): Elementor\Controls_Manager -> register()
#4: /var/www/html/wp-content/plugins/elementor-pro/modules/query-control/module.php(826): Elementor\Controls_Manager -> register_control()
',
)]

**Comment by 79ho3ein** [comment] 2022-03-23 15:12
Friends, what exactly is the problem?
I use hello elementor theme. elementor and e pro are up to date but I do not see any problem!
Most likely you use templates other than hello elementor, right? If yes, you have to wait for this compatibility to be created by the theme and other plugins. Now go back to the previous elementor version to get everything right.

**Comment by iqbalmauludy** [comment] 2022-03-23 15:48
> Friends, what exactly is the problem? I use hello elementor theme. elementor and e pro are up to date but I do not see any problem! Most likely you use templates other than hello elementor, right? If yes, you have to wait for this compatibility to be created by the theme and other plugins. Now go back to the previous elementor version to get everything right.

This one, I agree.

We should at least be patient waiting for other addon developers to work on this. 3.6 just came out, so other developers are doing updates too, at least users can be patient before updating.

**Comment by shilo-ey** [comment] 2022-03-23 15:50
Thanks,

This issue is caused by errors that are being thrown due to incompatibility with Elementor v3.6.0 and 3rd party plugins.

We contacted the plugin authors to adjust the methods being used and we are going to release a patch that will reduce the conflict error enforcement, for allowing the editor to be loaded properly.

Please follow this thread for additional updates.

**Comment by Tossko** [comment] 2022-03-23 17:07
I have the same error. According to the analysis of the logs of my website, the JetTabs plugin did not allow to complete the update of the data of Elementor, however for some reason it was forcefully updated. My solution was to go back to the previous version of Elementor and wait for crocoblock to release a patch to resolve this issue.

**Comment by shilo-ey** [comment] 2022-03-23 18:10
> Thanks,
> 
> This issue is caused by errors that are being thrown due to incompatibility with Elementor v3.6.0 and 3rd party plugins.
> 
> We contacted the plugin authors to adjust the methods being used and we are going to release a patch that will reduce the conflict error enforcement, for allowing the editor to be loaded properly.
> 
> Please follow this thread for additional updates.

Thank you all for reporting,

v3.6.1 was just released with a fix for the compatibility enforcement issue.

Cheers

**Closed by shilo-ey** 2022-03-23 18:10 UTC
Labels: bug, status/merged

**Comment by caguia** [comment] 2022-03-24 14:21
I have updated 3.6.1 and still not working with Essential theme.

**Comment by loorlab** [comment] 2022-03-24 20:39
+1

[24-Mar-2022 20:29:32 UTC] PHP Notice:  Undefined index: title in /path/wp-content/plugins/elementor/core/experiments/experiments-reporter.php on line 89

**Comment by Alhiane** [comment] 2022-03-25 10:43
this update crash the whole website

**Comment by alexrwlp** [comment] 2022-03-25 17:09
I wasn't having the issue everyone is describing in 3.6.0 but now when I update to 3.6.1 I have the issue. I'm sticking on 3.6.0 until a newer update is available.

**Comment by 79ho3ein** [comment] 2022-03-26 08:51
Friends, this bug has been completely fixed in the new version. Please note that elementor and elementor pro must be updated to the latest version.
If you continue to experience this bug, check your third-party plugins for troubleshooting.

**Comment by briandoakes** [comment] 2022-03-29 17:50
I have this same issue with 3.6.1 so i had to roll back to 3.5.6 for now as I can't edit anything. I even confirmed my memory limits and PHP version.

**Comment by briandoakes** [comment] 2022-03-29 18:22
> I've troubleshot through my plugins and found the issue on my end was The Plus Addons for Elementor. I've written to them hoping they'll get this figured out.

Thanks, when you say The Plus Addons, are you referring to PRO or something else? I am using the JetPlugins in addition to Elementor Pro

**Comment by alexrwlp** [comment] 2022-03-29 18:44
> 

So we use [**The Plus Addons for Elementor**](https://theplusaddons.com/), and **The Plus Addons for Elementor Page Builder**, both of which I believe are the free version. 

When I update to Elementor 3.6.1 on The Plus version 5.0.7 and with version 5.0.8, it makes it so I can't edit in Elementor. So keeping Elementor at 3.6.0 and The Plus at 5.0.7 has kept it so I can continue editing. I had tried removing The Plus Addons, but it's actually providing a lot of function to our site so I can't move on without it.

**Comment by datascientistgonzo** [comment] 2022-05-24 10:50
I have the same problem with Version 3.6.5
