### ISSUE TITLE
Javascript error - An "el" undefined must exist in DOM

### ISSUE THREAD

**Issue by liamfl** [elementor/elementor#13297] opened 2020-12-14 13:31 UTC
I get a js error when trying to click on Back to Library after getting a 404 when trying to preview a page template:

Error: An "el" undefined must exist in DOM
    at constructor._ensureElement (http://s853740707.websitehome.co.uk/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:13472)
    at constructor.show (http://s853740707.websitehome.co.uk/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:11800)
    at i.setHeaderDefaultParts (http://s853740707.websitehome.co.uk/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.0.14:2:421246)
    at TemplateLibraryManager.showTemplates (http://s853740707.websitehome.co.uk/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.0.14:2:413715)
    at TemplateLibraryManager.setScreen (http://s853740707.websitehome.co.uk/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.0.14:2:413484)
    at Component.renderTab (http://s853740707.websitehome.co.uk/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.0.14:2:416552)
    at Component.activateTab (http://s853740707.websitehome.co.uk/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.0.14:2:36383)
    at Component.activateTab (http://s853740707.websitehome.co.uk/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.0.14:2:416716)
    at Component.<anonymous> (http://s853740707.websitehome.co.uk/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.0.14:2:34661)
    at Routes.run (http://s853740707.websitehome.co.uk/wp-content/plugins/elementor/assets/js/common.min.js?ver=3.0.14:2:102532)

**Comment by TheFunkyBiskit** [comment] 2020-12-15 03:02
Also experiencing this issue.

**Comment by pjabol** [comment] 2020-12-15 09:54
this error at my site. 
trying to change php version from 7.4 to 7.2 and 7.1 but no change...

`JS: showing 2 of 2JS: 2020-12-14 17:43:25 [error X 5][http://xxxxx/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.0.14:2:312489] elementor.config.document is undefined 
JS: 2020-12-14 17:47:00 [error X 10][http://xxxxx/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:13466] An \&quot;el\&quot; undefined must exist in DOM 
`

`== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.25
	MySQL version: Debian 9.13 v5.6.49-89.0
	PHP Version: 7.4.13
	PHP Max Input Vars: 1000
	PHP Max Post Size: 8M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.6
	WP Multisite: No
	Max Upload Size: 2 MB
	Memory limit: 128M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/

== Theme ==
	Name: Hello Elementor
	Version: 2.3.0
	Author: Elementor Team
	Child Theme: No

== Active Plugins ==
	Elementor
		Version: 3.0.14
		Author: Elementor.com

	Elementor Pro
		Version: 3.0.8
		Author: Elementor.com
`

**Comment by AristidisKoutounidis** [comment] 2020-12-15 10:22
Same here. 
Error is thrown in Wordpress Administration when working with Ninja Forms.

**Comment by drosa88** [comment] 2020-12-15 11:49
Same error here. Fresh WordPress installation when I try to save a section as template.

**Comment by AristidisKoutounidis** [comment] 2020-12-15 12:53
Downgrading WP-Core to 5.5.3 solved it for me.
I used "WP Downgrade | Specific Core Version"
https://de.wordpress.org/plugins/wp-downgrade/

**Comment by TheFunkyBiskit** [comment] 2020-12-16 05:26
> Downgrading WP-Core to 5.5.3 solved it for me.
> I used "WP Downgrade | Specific Core Version"
> https://de.wordpress.org/plugins/wp-downgrade/

This workaround also worked for me.
Hopefully that narrows down the issue a bit more.

**Comment by wassim-sayerh** [comment] 2020-12-16 16:48
Exact same problem on my end. I will try downgrading WP

**Comment by wassim-sayerh** [comment] 2020-12-16 16:53
> Exact same problem on my end. I will try downgrading WP

Yupe it works now

**Comment by samueleastdev** [comment] 2020-12-18 09:55
The same issue had to downgrade via the command line

 wp core update --version=5.5.3 --force

**Comment by shilo-ey** [comment] 2020-12-21 16:57
This issue has been resolved in Elementor v3.0.15

Feel free to update

Thanks!

**Closed by shilo-ey** 2020-12-21 16:57 UTC
Labels: bug, compatibility

**Comment by slopeside-graham** [comment] 2021-01-20 18:55
This still seems to be an issue in a Popup for Elementor. See here: https://test.slopesidetechnology.com/

**Comment by LawrenceAsanka** [comment] 2021-05-25 08:41
{
    "name": "Error",
    "message": "An \"el\" undefined must exist in DOM"
}
Any Solution?

**Comment by nicholaszein** [comment] 2024-03-08 21:50
Hello,

this issue has been long solved. If you are experimenting something similar, it is most likely caused by something else. In this case, please submit a new bug report.

I'm locking comments here.
