### ISSUE TITLE
SVG handler

### ISSUE THREAD

**Issue by Rajat124** [elementor/elementor#9588] opened 2019-11-17 05:48 UTC
[16-Nov-2019 11:10:54 UTC] PHP Warning:  file_get_contents(): Filename cannot be empty in /home/alchescz/public_html/wp-content/plugins/elementor/core/files/assets/svg/svg-handler.php on line 120 
i am getting this error in my wordpress site.

**Comment by bainternet** [comment] 2019-11-18 10:05
Duplicate of #9481

**Closed by bainternet** 2019-11-18 10:05 UTC

**Comment by Rajat124** [comment] 2019-11-18 10:10
Please provide me with the solution.
