### ISSUE TITLE
Wrong html rendering (tag close wrong place)

### ISSUE THREAD

**Issue by YaakovHatam** [elementor/elementor#14935] opened 2021-05-13 12:59 UTC
elementor version:  3.2.3

I built a page in Elementor, the design of the page goes wrong after 2 sections, I checked the css selector of the design and saw that there must be a father with the css class ```elementor-651```.

I followed the html and saw that there is such a father, and he also has the attribute: ```data-elementor-type="wp-page"```.

And for some reason only the first 2 sections are inside this element (wp-page) and everything else is outside, I went to the source of the page and saw that because there is an incorrect closing. the browser takes the rest of the sections out of the father

Look at the end of this html output, the ```</section>``` are in the wrong place, it should be before the ```</div></div>```
```html
<div data-elementor-type="wp-page" data-elementor-id="651" class="elementor elementor-651">
      <div class="elementor-inner">
         <div class="elementor-section-wrap">
            <section
               class="elementor-section elementor-top-section elementor-element elementor-element-c5464b0 elementor-hidden-desktop elementor-hidden-tablet elementor-section-boxed elementor-section-height-default elementor-section-height-default"
               data-id="c5464b0" data-element_type="section"
               data-settings="{&quot;background_background&quot;:&quot;classic&quot;}">
                  ...
            </section>
            <section
               class="elementor-section elementor-top-section elementor-element elementor-element-282f6ab elementor-section-full_width elementor-section-height-full elementor-section-height-default elementor-section-items-middle"
               data-id="282f6ab" data-element_type="section"
               data-settings="{&quot;background_background&quot;:&quot;gradient&quot;}">
                  ...
         </div>
      </div>
      </section>
      <section
         class="elementor-section elementor-top-section elementor-element elementor-element-da88d71 elementor-hidden-desktop elementor-hidden-tablet elementor-section-boxed elementor-section-height-default elementor-section-height-default"
         data-id="da88d71" data-element_type="section">
```

This page has a lot of design, I do not know how to reproduce the problem, because I do not know what caused it. i can send a link to the page and access to back panel if you need.

**Comment by udidol** [comment] 2021-05-13 13:17
Hi @YaakovHatam,
Please copy and paste here your System Info report from the Admin Dashboard > Elementor > System Info
That can help us understand what's happening exactly.

**Comment by YaakovHatam** [comment] 2021-05-13 14:11
== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips PHP/7.4.15
	MySQL version: MySQL Community Server (GPL) v5.7.33
	PHP Version: 7.4.15
	PHP Max Input Vars: 10000
	PHP Max Post Size: 200M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.7.2
	Site URL: https://alma-israel.co.il/landings/harmony
	Home URL: https://alma-israel.co.il/landings/harmony
	WP Multisite: No
	Max Upload Size: 200 MB
	Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: he-IL
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: Soprano
	Version: 2.0
	Author: Andromedia
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: he_IL
	User Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 14_5 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/87.0.4280.163 Mobile/15E148 Safari/604.1

== Active Plugins ==
	Advanced Custom Fields PRO
		Version: 5.8.12
		Author: Elliot Condon

	Classic Editor
		Version: 1.6
		Author: WordPress Contributors

	Contact Form 7
		Version: 5.4.1
		Author: Takayuki Miyoshi

	Contact Form CFDB7
		Version: 1.2.5.9
		Author: Arshid

	Duplicate Page
		Version: 4.4
		Author: mndpsingh287

	Easy UTM tracking with contact form 7
		Version: 2.0.4
		Author: Basir Mukhtar

	Elementor
		Version: 3.2.3
		Author: Elementor.com

	Elementor Pro
		Version: 3.2.2
		Author: Elementor.com

	Facebook for WordPress
		Version: 3.0.5
		Author: Facebook

	LiteSpeed Cache
		Version: 3.6.4
		Author: LiteSpeed Technologies

	One Click Accessibility
		Version: 2.0.3
		Author: One Click Accessibility

	WebP Express
		Version: 0.19.1
		Author: Bjørn Rosell

	Yoast SEO
		Version: 16.2
		Author: Team Yoast


== אלמנטור - Compatibility Tag ==
	
	Elementor Pro: compatible

== Elementor Pro - Compatibility Tag ==
	


== Elements Usage ==
	
	page : 1
		divider : 1
		form : 2
		heading : 20
		icon : 1
		icon-list : 3
		image : 25
		lottie : 1
		social-icons : 1
		spacer : 3
		text-editor : 16
		video : 1
	wp-page : 2
		divider : 2
		form : 4
		heading : 41
		icon : 2
		icon-list : 6
		image : 50
		lottie : 2
		social-icons : 2
		spacer : 6
		text-editor : 32
		video : 2


== Log ==
	
Log: showing 11 of 112021-05-12 11:31:43 [info] elementor-pro::elementor_pro_updater Started 
2021-05-12 11:31:43 [info] Elementor Pro/Upgrades - _v_3_1_0_media_carousel Start  
2021-05-12 11:31:43 [info] Elementor Pro/Upgrades - _v_3_1_0_media_carousel Finished 
2021-05-12 11:31:43 [info] Elementor Pro/Upgrades - _v_3_1_0_reviews Start  
2021-05-12 11:31:43 [info] Elementor Pro/Upgrades - _v_3_1_0_reviews Finished 
2021-05-12 11:31:43 [info] Elementor Pro/Upgrades - _v_3_1_0_testimonial_carousel Start  
2021-05-12 11:31:43 [info] Elementor Pro/Upgrades - _v_3_1_0_testimonial_carousel Finished 
2021-05-12 11:31:43 [info] Elementor Pro/Upgrades - _v_3_1_0_slides Start  
2021-05-12 11:31:43 [info] Elementor Pro/Upgrades - _v_3_1_0_slides Finished 
2021-05-12 11:31:43 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.0.9',
  'to' => '3.2.2',
)]
2021-05-12 11:31:43 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.0.9',
  'to' => '3.2.2',
)]

PHP: showing 1 of 1PHP: 2021-05-12 14:24:57 [notice X 3][/var/www/html/medicalnova.co.il/landings/harmony/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

**Comment by YaakovHatam** [comment] 2021-05-13 14:44
> Hi @YaakovHatam,
> 
> Please copy and paste here your System Info report from the Admin Dashboard > Elementor > System Info
> 
> That can help us understand what's happening exactly.

I can send wp-admin details in email if you want

**Comment by udidol** [comment] 2021-05-13 15:09
Hi @YaakovHatam,
Did you try disabling all other plugins except for Elementor and Elementor Pro and seeing if the problem persists?

**Comment by YaakovHatam** [comment] 2021-05-18 06:10
> Hi @YaakovHatam,
> Did you try disabling all other plugins except for Elementor and Elementor Pro and seeing if the problem persists?

I disabled everything except elementor and elementor pr, switched to Twenty Nineteen theme. 
still the same issue.

**Comment by YaakovHatam** [comment] 2021-05-18 06:36
I also added the class `elementor-651` to the body, because the generated css by Elementor require `elementor-651` as a parent class to everything and the design looks ok.  

The sections renderer under the `body` tag instead of `<div data-elementor-type="wp-page" class="elementor elementor-651" >` tag. caused by what i wrote in bug opening.

**Comment by udidol** [comment] 2021-05-18 07:48
Could you please export your page, download it, and share the JSON via Pastebin or something similar?
I want to try and reproduce the issue.

You can export your page as a template by following these steps:
1. At the bottom of your page in the Editor there is this dotted line section. You click on the folder icon to open the template library
![image](https://user-images.githubusercontent.com/36724484/118612192-337a6900-b7c6-11eb-8570-591b69537e00.png)

2. In the template library, click on the save icon on the top right, and save your template.
![image](https://user-images.githubusercontent.com/36724484/118612444-71778d00-b7c6-11eb-909e-8be6570445eb.png)

3. You can then go to My Templates, click on the 3 dots icon on the right, and download your newly saved template
![image](https://user-images.githubusercontent.com/36724484/118612573-93710f80-b7c6-11eb-9820-912158388f15.png)

**Comment by YaakovHatam** [comment] 2021-05-18 09:45
> Could you please export your page, download it, and share the JSON via Pastebin or something similar?
> I want to try and reproduce the issue.
> 

done:
https://pastebin.com/kkZY09QU

(the link will be available for 1 week from now)

**Comment by shilo-ey** [comment] 2021-11-22 07:30
Hey, 

We couldn't reproduce this issue, therefore we are closing it for now.

If the issue persist, please create a new one and reference this issue.

Thanks

**Closed by shilo-ey** 2021-11-22 07:30 UTC
