### ISSUE TITLE
Stray formatting code inserted when pasting text into text editor from external source

### ISSUE THREAD

**Issue by llafata** [elementor/elementor#15520] opened 2021-06-30 18:20 UTC
## Description 

Unwanted formatting code inserted when pasting text into text editor widget. 

PASTE function into text editor inserts stray DIV code above and below text, and in some instances also inserts code for unwanted styles like "apple generated space" etc.

In this instance, its from Microsoft word, but assuming other programs will do the same.

this is a NEW issue after latest elementor updates

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Steps to reproduce

1. create styled text paragraph in microsoft word
2. open elementor editor and create a text editor widget, place into the builder
3. copy text from microsoft word (or another program that is external)
4. paste this into the elementor text editor using the VISUAL tab of the widget window pane
5. switch to TEXT view of widget window pane
6. observe stray code inserted (code like <div> or link/text styles for <span>

these formatting codes should not be carried over

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

Using Safari Version 14.1.1 (16611.2.7.1.4)
ELEMENTOR PRO VERSION 3.2.5 
ELEMENTOR PRO VERSION  3.3.1
Jupiter X Core Version 1.17.0

![Screen Shot 2021-06-30 at 2 17 12 PM](https://user-images.githubusercontent.com/67172161/124011635-3adc8700-d9ae-11eb-80d9-ca0743637075.png)
![Screen Shot 2021-06-30 at 2 17 19 PM](https://user-images.githubusercontent.com/67172161/124011636-3b751d80-d9ae-11eb-8e17-3fb7d24d61a1.png)

**Comment by Aviad-Herman** [comment] 2021-06-30 20:37
Hi @llafata Thanks for sharing.
I will open a discussion around this.

The problem is that different users have different needs. Some want the style to be pasted and some don't, Some want HTML tags like H1 to be pasted and some don't...

It will be hard to find a sweet spot but I will ask people in the company about the historic reasons for defining the current behavior.

FYI, if you paste straight into the text mode (your second image) that everything except text will be stripped away like you want.

**Comment by Aviad-Herman** [comment] 2021-06-30 20:38
I'm going to close this issue but rest assured It's raised the questions you wanted

**Closed by Aviad-Herman** 2021-06-30 20:38 UTC
