### ISSUE TITLE
Post widget terms categories not working

### ISSUE THREAD

**Issue by KiQdev** [elementor/elementor#7653] opened 2019-03-28 10:39 UTC
## Prerequisites

- [ x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x ] The issue still exists against the latest stable version of Elementor.

## Description
Using Posts widget and setting to terms, categories shows nothing

## Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [ x] I can reproduce this bug consistently using the steps above.

## Environment

<details>Elementor 2.5.10 Pro 2.5.2
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by shilo-ey** [comment] 2019-03-28 10:41
- Where? in which document type? Post? Page? Product?
- What is your system info?
- Can you provide a screenshot of the options provided in your autocomplete terms field?

Thanks!

**Comment by KiQdev** [comment] 2019-03-28 13:18
Sorry for not enough info, here it is:-)
Also tried with portfolio widget, same, it´s not working when set to Term, categories.
Used on a page.
------------------------------------------
System info
Operating System:	Linux	
Software:	Apache	
MySQL version:	MariaDB Server v5.6.42-84.2	
PHP Version:	7.3.3	
PHP Max Input Vars:	5000	
PHP Max Post Size:	521M	
GD Installed:	Yes	
ZIP Installed:	Yes	
Write Permissions:	All right	
Elementor Library:	Connected	
WordPress Environment		
Version:	5.1.1		
WP Multisite:	No	
Max Upload Size:	521 MB	
Memory limit:	1024M
![post and portfolio widget](https://user-images.githubusercontent.com/30444495/55160788-64b9fa00-5164-11e9-8f6c-9dc45357c9d7.jpg)

**Comment by shilo-ey** [comment] 2019-03-28 15:31
And the posts are not visible after you select your desired query?

**Comment by dknck** [comment] 2019-03-28 15:39
Same issue here after updating to 2.5 and still happening after updating to 2.5.2. Posts Widget doesn't seem to work when setting it to filter terms (categories or tags) and shows blank. 

I think it has to do with the functions build_terms_query and insert_tax_query and the use of term_id and taxonomy_term_id. I've tried it with new install where term_id and taxonomy_term_id are the same and it works ok, but with old installs where term_id and taxonomy_term_id differ it doesn't work. Maybe because old installs often have different values in these columns before taxonomy term splitting was introduced in WP 4.2.

**Comment by KiQdev** [comment] 2019-03-28 16:34
No completely empty, tried everything and same on another site too, there I
use pages, not posts

Den tors 28 mars 2019 kl 17:31 skrev shilo-ey <notifications@github.com>:

**Comment by s-e-privalov** [comment] 2019-03-29 06:49
Same problem. Fixed by changing  $term_data = get_term_by( 'term_taxonomy_id', $id); returns term_id, but expected - term_taxonomy_id  to $term_data = get_term_by( 'id', $id, 'category'); in elementor-post-query.php - start from line 218. 

But on my other sites all works well....

**Comment by dknck** [comment] 2019-03-29 08:20
Yes, but I think that is only going to work for categories, not for all terms as intended.

**Comment by s-e-privalov** [comment] 2019-03-29 10:09
> Yes, but I think that is only going to work for categories, not for all terms as intended.

I know! For me it is ok. I dont have any other term types. But i want to know what is the reason of this problem. Database structure? How to fix?

**Comment by thimfy** [comment] 2019-03-30 07:48
Do not purchase elementor or any item from creator of it, no support nothing just kind of shit only.

**Comment by shilo-ey** [comment] 2019-03-31 07:07
[**@s-e-privalov**](https://github.com/s-e-privalov) commented on [Mar 29, 2019, 1:09 PM GMT+3](https://github.com/elementor/elementor/issues/7653#issuecomment-477942516 "2019-03-29T10:09:26Z - Replied by Github Reply Comments"):
> > Yes, but I think that is only going to work for categories, not for all terms as intended.
> 
> I know! For me it is ok. I dont have any other term types. But i want to know what is the reason of this problem. Database structure? How to fix?

We are working on a solution for this issue, and will release a patch soon.

Thanks and sorry for your inconvenience.

**Comment by shilo-ey** [comment] 2019-03-31 14:38
This issue has been fixed in Elementor Pro v2.5.3

Feel free to update!

**Comment by KiQdev** [comment] 2019-03-31 14:46
Tried the new versions, stlll same problem, nothing shows:-/

Den sön 31 mars 2019 kl 16:38 skrev shilo-ey <notifications@github.com>:

**Comment by KiQdev** [comment] 2019-03-31 15:54
It seems that is the sites that is build earlier (1.5 years( that don´t
work, trying on a new install, there it works.
Everything in the old is the same as the new one.

Den sön 31 mars 2019 kl 16:46 skrev Torsten Nilsson <
torsten.b.nilsson@gmail.com>:

**Comment by s-e-privalov** [comment] 2019-03-31 19:51
Same problem too. Nothing changed!

**Comment by nash-ye** [comment] 2019-03-31 19:54
Tried the new version, the same problem, we are using post tags.

**Comment by cosmincret** [comment] 2019-04-01 06:26
Unfortunately the category inclusion or exclusion is not working on latest update. This messed up previous sorting on my websites. Hope you'll consider fixing this soon. Thanks.

**Comment by shilo-ey** [comment] 2019-04-01 06:37
[**@cosmincret**](https://github.com/cosmincret) commented on [Apr 1, 2019, 9:26 AM GMT+3](https://github.com/elementor/elementor/issues/7653#issuecomment-478451752 "2019-04-01T06:26:45Z - Replied by Github Reply Comments"):
> Unfortunately the category inclusion or exclusion is not working on latest update. This messed up previous sorting on my websites. Hope you'll consider fixing this soon. Thanks.


[**@nash-ye**](https://github.com/nash-ye) commented on [Mar 31, 2019, 10:54 PM GMT+3](https://github.com/elementor/elementor/issues/7653#issuecomment-478374927 "2019-03-31T19:54:43Z - Replied by Github Reply Comments"):
> Tried the new version, the same problem, we are using post tags.


[**@s-e-privalov**](https://github.com/s-e-privalov) commented on [Mar 31, 2019, 10:51 PM GMT+3](https://github.com/elementor/elementor/issues/7653#issuecomment-478374605 "2019-03-31T19:51:39Z - Replied by Github Reply Comments"):
> Same problem too. Nothing changed!


[**@KiQdev**](https://github.com/KiQdev) commented on [Mar 31, 2019, 6:54 PM GMT+3](https://github.com/elementor/elementor/issues/7653#issuecomment-478353719 "2019-03-31T15:54:31Z - Replied by Github Reply Comments"):
> It seems that is the sites that is build earlier (1.5 years( that don´t
> work, trying on a new install, there it works.
> Everything in the old is the same as the new one.

Please try to remove and re-add your selected term and see if that solved the issue for you.

Looking forward your reply.

thanks.

**Comment by KiQdev** [comment] 2019-04-01 06:42
I did several times and tried to create new, no change.
A little nightmare at the moment, 75 pages on one site, all with post
widgets with terms, so it´s a quite blank  site for now:-)

Den mån 1 apr. 2019 kl 08:37 skrev shilo-ey <notifications@github.com>:

**Comment by nash-ye** [comment] 2019-04-01 07:44
I have tried to remove the term and add it again, same problem.

**Comment by dknck** [comment] 2019-04-01 07:58
Still not working after update

**Comment by shilo-ey** [comment] 2019-04-01 09:27
@dknck @nash-ye @KiQdev  @s-e-privalov @cosmincret 

Please contact our support at support @elementor.com for guidance in resolving this issue and **mention that you were directed by me and reference this issue.**

When you contact the support please provide as many details as possible (including credentials for logging in to your environment, pages that are affected and description of the desired behavior)

Thanks.

**Comment by Virus45** [comment] 2019-04-01 15:22
I have the same problem since the last update (Elementor 2.5.11, Elementor Pro 2.5.3, WooCommerce 3.5.7). I can't choose a term. I try to add a product category but… Searching… Searching… Searching…
I can't adjust or modify the terms, the field is "grey"!
![Elementor-products-widget](https://user-images.githubusercontent.com/49160936/55339209-8a1b7080-54a2-11e9-95f0-7cd4d282c370.png)

**Comment by derweltbuerger** [comment] 2019-04-01 15:37
Same here... still not working after updating to 2.5.3. I can choose categories though but they simply do not show on the screen, neither in editor mode nor on the actual page after saving. The field where the products should show stays empty as soon as I select any product category. Selecting a product brand, for instance, works just fine though.

Please fix this soon as I cannot install any of the Elementor Pro updates after 2.4.8 otherwise. Thanks.

**Comment by shilo-ey** [comment] 2019-04-02 07:50
Thanks @KiQdev for your help figuring this issue better.
We will soon release a patch for this.

Thanks!

**Comment by shilo-ey** [comment] 2019-04-03 14:58
This issue has been resolved in Elementor Pro v2.5.3

Feel free to update!

**Closed by shilo-ey** 2019-04-03 14:58 UTC
Labels: pro, status/has_pr

**Comment by derweltbuerger** [comment] 2019-04-04 08:37
Im very sorry but even after updating to 2.5.4 the issue has not been resolved for me. You can see for yourself: https://1drv.ms/u/s!AkOeEEATPrN-ga1eHuDYpTVBDGqXdA

There are 6 products in the selected category, none of them are displayed. To the right there is another product archive with 5 products of which none are displayed.

I'm using WP 4.9.8 with most recent WooCommerce, Elementor and Elementor Pro.

I have to revert back to 2.4.8.

**Comment by vasjanovak** [comment] 2019-04-04 10:10
In my post widget, I am filtering posts by category and tag. After updating to 2.5.4 I can filter only by one of them. Any idea of how to fix this? Tnx

**Comment by pako69** [comment] 2019-04-04 11:08
Hi
Why is this closed?
It's totaly buggy
I was using version 2.4.8 and filtering my post based on CPT Ui taxo and all was working.
I update to the latest 2.5.4 and it's a nightmare!
**Please fix it ASAP**
Thanks

**Comment by Virus45** [comment] 2019-04-04 11:37
Hi,
The 2.5.4 update is not available in my dashboard!
But, reading the previous messages, the update does not seem to have solved the problem.
I can not change my online shop project anymore.
Include or exclude by term does not work properly, whether for product categories or otherwise.

**Comment by shilo-ey** [comment] 2019-04-04 12:23
Hi @Virus45 @derweltbuerger @vasjanovak @pako69 

Thanks for reporting.

This issue most likely origins from update script that didn't run.

We will release a patch for this issue soon.

As a workaround you can:
1. Update your Elementor Pro Plugin to v2.5.4 through WP admin dashboard
2. After the update process access `../wp-admin/options.php` manually and set the `elementor_pro_version` to `2.4.8`.
3. Refresh the WP admin dashboard and make sure you can see the update notice.

This should force the update script execution.

Note: make sure that in your `wp_config.php` file the constant `DISALLOW_FILE_MODS` is either not defined or set to `false`, and the update is executed from your WP dashboard and not from external interfaces.

Thanks!

**Comment by Virus45** [comment] 2019-04-04 12:43
@shilo-ey 

Thank you for your reply.
There have already been updates in the dashboard.
I just saw the update 2.5.4. The update took a while to come. :-)
I confirm, the update does not solve anything!

**Comment by pako69** [comment] 2019-04-04 13:49
Thank you @shilo-ey 
Sorry but I do not want to trick anything and do some risky workaround on a product live site...
Please, please fix it in a next and urgent Version 2.5.5 version... :)
Thanks

**Comment by shilo-ey** [comment] 2019-04-04 14:04
@Virus45 

Please contact our support at support @elementor.com for guidance in resolving this issue and mention that you were directed by me and reference this issue.


Please attach there your system info and your WP login credentials.

thanks.

**Comment by shilo-ey** [comment] 2019-04-04 14:38
A fix should be released on the following 3-4 days.

Please send us your system info here / to our support as mentioned above so we could verify the fix solves your issue.

Thanks!

**Comment by Virus45** [comment] 2019-04-04 15:33
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MySQL Celeonet Server v5.7.24
	PHP Version: 7.0.27
	PHP Max Input Vars: 10000
	PHP Max Post Size: 100M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.1.1
	Site URL: http://golias.sailing-up.com
	Home URL: http://golias.sailing-up.com
	WP Multisite: No
	Max Upload Size: 100 MB
	Memory limit: 256M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: fr-FR
	Timezone: Europe/Paris
	Debug Mode: Inactive

== Theme ==
	Name: golias
	Version: 1.0.0
	Author: Sailing
	Child Theme: Yes
	Parent Theme Name: Twenty Seventeen
	Parent Theme Version: 2.1
	Parent Theme Author: the WordPress team

== User ==
	Role: administrator
	WP Profile lang: fr_FR
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:66.0) Gecko/20100101 Firefox/66.0

== Active Plugins ==
	Elementor
		Version: 2.5.11
		Author: Elementor.com

	Elementor Pro
		Version: 2.5.4
		Author: Elementor.com

	FG SPIP to WordPress Premium
		Version: 2.35.1
		Author: Frédéric GILLES

	Folders
		Version: 2.0.4
		Author: Premio

	Mailchimp for WooCommerce
		Version: 2.1.15
		Author: Mailchimp

	WooCommerce
		Version: 3.5.7
		Author: Automattic

	WooCommerce Blocks
		Version: 1.4.0
		Author: Automattic

	WooCommerce PayPal Checkout Gateway
		Version: 1.6.10
		Author: WooCommerce

	WooCommerce Services
		Version: 1.19.0
		Author: Automattic

	WooCommerce Stripe Gateway
		Version: 4.1.15
		Author: WooCommerce


== Log ==
	: 
PHP: showing 5 of 5PHP: 2019-03-26 12:32:04 [notice X 112][/home/www/client/www/CPT023/wp-content/plugins/elementor-pro/modules/query-control/module.php::280] Undefined index: object_type [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2019-03-27 12:35:36 [notice X 133][/home/www/client/www/CPT023/wp-content/plugins/elementor-pro/modules/woocommerce/classes/products-renderer.php::152] Trying to get property of non-object [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2019-03-28 12:02:17 [notice X 6][/home/www/client/www/CPT023/wp-content/plugins/elementor-pro/modules/posts/widgets/posts.php::31] Undefined index: posts_post_type [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2019-04-01 13:26:46 [error X 30][/home/www/client/www/CPT023/wp-content/plugins/elementor-pro/modules/query-control/module.php::302] Allowed memory size of 134217728 bytes exhausted (tried to allocate 134217736 bytes) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2019-04-01 13:28:39 [error X 8][/home/www/client/www/CPT023/wp-content/plugins/elementor-pro/modules/query-control/module.php::302] Allowed memory size of 134217728 bytes exhausted (tried to allocate 67108872 bytes) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

Log: showing 20 of 342019-03-28 19:42:13 [info] Elementor Pro/Upgrades - _v_2_5_0_popup_border_radius Start  
2019-03-28 19:42:13 [info] Elementor Pro/Upgrades - _v_2_5_0_popup_border_radius Finished 
2019-03-28 19:42:13 [info] Elementor Pro/Upgrades - _v_2_5_0_products Start (2 of 2, 100%) 
2019-03-28 19:42:13 [info] Elementor Pro/Upgrades - _v_2_5_0_products Finished 
2019-03-28 19:42:13 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.5.0',
  'to' => '2.5.2',
)]
2019-04-01 12:12:03 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.5.10',
  'to' => '2.5.11',
)]
2019-04-01 12:24:18 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.5.2',
  'to' => '2.5.3',
)]
2019-04-04 14:28:19 [info] elementor-pro::elementor_pro_updater Started 
2019-04-04 14:28:19 [info] Elementor Pro/Upgrades - _v_2_5_4_posts Start  
2019-04-04 14:28:19 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.5.3',
  'to' => '2.5.4',
)]
2019-04-04 14:28:20 [info] Elementor Pro/Upgrades - _v_2_5_4_posts Finished 
2019-04-04 14:28:20 [info] Elementor Pro/Upgrades - _v_2_5_4_portfolio Start  
2019-04-04 14:28:20 [info] Elementor Pro/Upgrades - _v_2_5_4_portfolio Finished 
2019-04-04 14:28:20 [info] Elementor Pro/Upgrades - _v_2_5_4_products Start  
2019-04-04 14:28:20 [info] Elementor Pro/Upgrades - _v_2_5_4_products callback needs to run more 1 times 
2019-04-04 14:28:20 [info] Elementor Pro/Upgrades - _v_2_5_4_form Start  
2019-04-04 14:28:21 [info] Elementor Pro/Upgrades - _v_2_5_4_form Finished 
2019-04-04 14:28:21 [info] Elementor Pro/Upgrades - _v_2_5_4_products Start (2 of 2, 100%) 
2019-04-04 14:28:21 [info] Elementor Pro/Upgrades - _v_2_5_4_products Finished 
2019-04-04 14:28:21 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.5.3',
  'to' => '2.5.4',
)]

JS: showing 3 of 3JS: 2019-03-28 18:36:57 [error X 1][http://golias.sailing-up.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.5.10:2:83363] i is undefined 
JS: 2019-03-29 09:34:28 [error X 1][http://golias.sailing-up.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.5.10:2:75360] setting getter-only property \"type\" 
JS: 2019-04-01 11:56:04 [error X 1][http://golias.sailing-up.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.5.11:2:53410] this.ui.sliders.filter(...)[0] is undefined

**Comment by vasjanovak** [comment] 2019-04-04 21:41
== Server Environment ==
	Operating System: WINNT
	Software: Apache/2.4.35 (Win64) OpenSSL/1.1.0i PHP/7.2.11
	MySQL version: MySQL Community Server (GPL) v5.7.24
	PHP Version: 7.2.11
	PHP Max Input Vars: 1000
	PHP Max Post Size: 2G
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.1.1
	Site URL: http://localhost/e-learning
	Home URL: http://localhost/e-learning
	WP Multisite: No
	Max Upload Size: 2 GB
	Memory limit: 512M
	Permalink Structure: /%category%/%postname%/
	Language: en-US
	Timezone: 1
	Debug Mode: Inactive

== Theme ==
	Name: Hello Child
	Version: 
	Author: Vasko
	Child Theme: Yes
	Parent Theme Name: Elementor Hello Theme
	Parent Theme Version: 1.1.0
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36

== Active Plugins ==
	Advanced Custom Fields
		Version: 5.7.12
		Author: Elliot Condon

	Advanced Custom Fields: Star Rating Field
		Version: 1.0.2
		Author: Kevin Ruscoe

	Complianz | GDPR Cookie Consent
		Version: 2.1.8
		Author: RogierLankhorst, Complianz team

	Custom Post Type UI
		Version: 1.6.1
		Author: WebDevStudios

	Elementor
		Version: 2.5.11
		Author: Elementor.com

	Elementor Pro
		Version: 2.5.4
		Author: Elementor.com

	Rank Math SEO
		Version: 1.0.22
		Author: Rank Math


== Log ==
	: 
JS: showing 20 of 23JS: 2019-03-30 16:57:36 [error X 1][http://localhost/e-learning/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view6394\") has already been destroyed and cannot be used. 
JS: 2019-03-30 16:57:47 [error X 1][http://localhost/e-learning/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view6491\") has already been destroyed and cannot be used. 
JS: 2019-03-30 16:58:08 [error X 1][http://localhost/e-learning/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view6588\") has already been destroyed and cannot be used. 
JS: 2019-03-30 20:16:11 [error X 3][http://localhost/e-learning/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view422\") has already been destroyed and cannot be used. 
JS: 2019-04-02 07:09:18 [error X 1][http://localhost/e-learning/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view533\") has already been destroyed and cannot be used. 
JS: 2019-04-02 07:09:45 [error X 1][http://localhost/e-learning/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view512\") has already been destroyed and cannot be used. 
JS: 2019-04-02 07:09:51 [error X 1][http://localhost/e-learning/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view609\") has already been destroyed and cannot be used. 
JS: 2019-04-02 07:09:57 [error X 1][http://localhost/e-learning/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view706\") has already been destroyed and cannot be used. 
JS: 2019-04-02 07:10:05 [error X 1][http://localhost/e-learning/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view803\") has already been destroyed and cannot be used. 
JS: 2019-04-02 07:10:13 [error X 1][http://localhost/e-learning/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view900\") has already been destroyed and cannot be used. 
JS: 2019-04-02 07:10:21 [error X 1][http://localhost/e-learning/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view997\") has already been destroyed and cannot be used. 
JS: 2019-04-02 07:37:19 [error X 2][http://localhost/e-learning/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view584\") has already been destroyed and cannot be used. 
JS: 2019-04-02 08:58:29 [error X 4][http://localhost/e-learning/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view581\") has already been destroyed and cannot be used. 
JS: 2019-04-02 13:11:13 [error X 1][http://localhost/e-learning/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view497\") has already been destroyed and cannot be used. 
JS: 2019-04-03 08:33:01 [error X 1][http://localhost/e-learning/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view475\") has already been destroyed and cannot be used. 
JS: 2019-04-03 08:33:40 [error X 1][http://localhost/e-learning/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view586\") has already been destroyed and cannot be used. 
JS: 2019-04-03 08:34:12 [error X 1][http://localhost/e-learning/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view2764\") has already been destroyed and cannot be used. 
JS: 2019-04-04 12:11:55 [error X 1][http://localhost/e-learning/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view20256\") has already been destroyed and cannot be used. 
JS: 2019-04-04 12:11:55 [error X 1][http://localhost/e-learning/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view20269\") has already been destroyed and cannot be used. 
JS: 2019-04-04 12:11:55 [error X 1][http://localhost/e-learning/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view20318\") has already been destroyed and cannot be used. 

PHP: showing 4 of 4PHP: 2019-03-30 18:26:02 [notice X 1][C:\laragon\www\e-learning\wp-content\plugins\elementor-pro\modules\query-control\classes\elementor-post-query.php::218] Undefined property: WP_Error::$taxonomy [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2019-03-31 21:39:52 [notice X 2][C:\laragon\www\e-learning\wp-content\plugins\elementor\includes\elements\column.php::1070] Undefined index: _column_size [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2019-04-04 09:51:02 [notice X 18][C:\laragon\www\e-learning\wp-content\plugins\elementor-pro\modules\query-control\module.php::122] Trying to get property 'name' of non-object [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2019-04-04 11:27:40 [notice X 1][C:\laragon\www\e-learning\wp-content\plugins\elementor-pro\modules\query-control\module.php::280] Undefined index: object_type [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

Log: showing 16 of 162019-03-31 15:56:33 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.5.10',
  'to' => '2.5.11',
)]
2019-03-31 15:56:49 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.5.2',
  'to' => '2.5.3',
)]
2019-04-04 09:18:55 [info] elementor-pro::elementor_pro_updater Started 
2019-04-04 09:18:55 [info] Elementor Pro/Upgrades - _v_2_5_4_posts Start  
2019-04-04 09:18:56 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.5.3',
  'to' => '2.5.4',
)]
2019-04-04 09:18:57 [info] Elementor Pro/Upgrades - _v_2_5_4_posts Finished 
2019-04-04 09:18:57 [info] Elementor Pro/Upgrades - _v_2_5_4_portfolio Start  
2019-04-04 09:18:58 [info] Elementor Pro/Upgrades - _v_2_5_4_portfolio Finished 
2019-04-04 09:18:58 [info] Elementor Pro/Upgrades - _v_2_5_4_products Start  
2019-04-04 09:18:58 [info] Elementor Pro/Upgrades - _v_2_5_4_products Finished 
2019-04-04 09:18:58 [info] Elementor Pro/Upgrades - _v_2_5_4_form Start  
2019-04-04 09:18:59 [info] Elementor Pro/Upgrades - _v_2_5_4_form callback needs to run more 1 times 
2019-04-04 09:18:59 [info] Elementor Pro/Upgrades - _v_2_5_4_form Start (2 of 2, 100%) 
2019-04-04 09:19:01 [info] Elementor Pro/Upgrades - _v_2_5_4_form Finished 
2019-04-04 09:19:01 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.5.3',
  'to' => '2.5.4',
)]
2019-04-04 09:19:02 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.5.3',
  'to' => '2.5.4',
)]

**Comment by dotjuice** [comment] 2019-04-05 10:38
I've used this new function to show related posts on my single templates by linking posts with A custom Taxonomy called clients. It worked perfectly until I updated to Pro 2.5.4 this morning. I'm now getting the following error below

`Fatal error: Uncaught Error: Call to undefined method ElementorPro\Modules\QueryControl\Classes\Elementor_Related_Query::insert_tax_query() in /wp-content/plugins/elementor-pro/modules/query-control/classes/elementor-related-query.php:112 Stack trace: #0 /wp-content/plugins/elementor-pro/modules/query-control/classes/elementor-post-query.php(197): ElementorPro\Modules\QueryControl\Classes\Elementor_Related_Query->build_terms_query_include('include_term_id...') #1 /wp-content/plugins/elementor-pro/modules/query-control/classes/elementor-post-query.php(117): ElementorPro\Modules\QueryControl\Classes\Elementor_Post_Query->set_terms_args() #2 /wp-content/plugins/elementor-pro/modules/query-control/classes/elementor-post-query.php(49): ElementorPro\Modules\QueryControl\Classes\Elementor_Post_Query->get_query_args() #3 /wp-content/plugins/elementor-pro/modules/query-control/classes/elementor-related-query.php on line 112`

Any help would be massively appreciated. Thank you

**Comment by KiQdev** [comment] 2019-04-05 10:40
Same here.

Den fre 5 apr. 2019 kl 12:39 skrev dotjuice <notifications@github.com>:

**Comment by seidenfaden** [comment] 2019-04-07 20:30
This appear to still not be solved. Are we waiting for 2.5.5?

**Comment by pako69** [comment] 2019-04-12 10:04
Hi
Does the latest 2.5.5  solved this issue please?
Thanks

**Comment by Virus45** [comment] 2019-04-12 10:14
Hi,
@pako69 
I don't think so.
I have to revert back to 2.4.8.

**Comment by pako69** [comment] 2019-04-12 10:16
@Virus45 Did you tried?
Because I tried on a stagging website, and the issue is no longer present with:
elementor pro 2.5.5
elementor 2.5.13

**Comment by Virus45** [comment] 2019-04-12 10:30
@pako69 Yes, i tried to filtering products by category, but not result.
The search works, but only for a specific category.
If I look for another category of products, the Ajax script does not send any request!

**Comment by dotjuice** [comment] 2019-04-12 15:52
The latest version solved the problems I had so happy overall.

**Comment by vasjanovak** [comment] 2019-04-12 16:43
It works for me. Filtering by category and tag. Thank you 😀

**Comment by derweltbuerger** [comment] 2019-05-02 14:31
This has finally been fixed in Elementor Pro 2.5.6. (2.5.5. did not fix it for me and I reverted to 2.4.8). I just updated and the query control now works again as it is supposed to :)

So, I guess everyone who has still been facing this issue should update in a staging environment and test whether it works for them too.

Thanks!

**Comment by bellamystudio** [comment] 2019-07-24 13:14
This isn't working for me in 2.6.6 / Pro 2.6.0 (WP 5.2.2 / PHP 7.2) - I have four categories associated with this post type but when I select term in the query window, I get no results for anything that I type into the box. In the screenshot I'm looking for 'reporters' (one of my four categories)

![term-not-working](https://user-images.githubusercontent.com/457677/61796372-29cb8880-ae1d-11e9-82e3-42b6f808141e.png)

**Comment by the-gap-decaders** [comment] 2019-07-24 15:06
Same here...no categories showing as available in portfolio widget, query under 'term'...does not work in posts query either.  Stopped today after I updated to Elementor Pro 2.6.0, Elementor is 2.6.6

**Comment by mrksdiehl** [comment] 2019-07-24 19:22
Same here. Newest version of Elementor 2.6.6 and Elementor Pro 2.6.0. Can not select any category. Exactly the same as the two above.

**Comment by Brasil2004** [comment] 2019-07-25 00:03
Hello, I've had exactly the same problem to this day. After I rewrote some posts to other categories and created new categories it suddenly worked. Very, strange, but now something is working that didn't work 3 hours ago.
Maybe it helps! Sorry my english is bad, so I had the text translated with deepl. Peter
![2019-07-24](https://user-images.githubusercontent.com/53281361/61836402-ad996b00-ae45-11e9-8a87-2b71578b6ae6.png)

**Comment by bellamystudio** [comment] 2019-07-26 16:29
I tried adding some other categories and posts but it hasn't started working for me - still no results found and I really need it to work!

**Comment by Pevehouse** [comment] 2020-04-18 03:04
I am using Elementor Pro version 2.9.2. 

I can get some categories to show, but not all.  Also, the search field only allows me to add one letter, so it's always "C" to get categories to show.  (If I try use words, nothing shows up.) After typing "C" it also provides tags even though I didn't search for those.  Today I added a new category and page and cannot get it to show up with "Term."  Any help with this would be awesome.

**Comment by Hynek-O** [comment] 2020-05-02 10:50
This is not on the portfolio, but it also doesn't work for me (query) for porfolio (elementor module for). It just doesn't show all the posts. E.g. are 3 and shows 1 and the like. Nonsense. Can anyone solve this?

**Comment by Fiskou** [comment] 2023-02-20 17:15
Hello everyone, I don't know if the problem is considered solved, but I wanted to share my solution. 

I'm using Elementor v.3.11 / Elementor PRO v.3.11 and when I use the Products block with terms and categories some of them don't display and others don't display all products.

So I opted for shortcodes, unfortunately it's not as user-friendly as the elementor blocks but at least I can display my products!

To do this I followed the Elementor tutorial on Woocommerce shortcodes. Link: https://elementor.com/blog/woocommerce-shortcodes

Here is an example with the categories to display the eight newest products from either the "Hoodies" or "T-Shirts" categories.
[products limit="8" columns="4" category="hoodies, tshirts" orderby="id" order="DESC" visibility="visible"]

PS: make sure to put the slug of your category and not his name.

![](https://elementor.com/marketing/wp-content/uploads/sites/9/2021/05/woocommerce-shortcodes-6-product-category-example-2.jpg)

**Comment by tomherold** [comment] 2023-03-05 18:45
Seems this bug is still happening in the latest release. I have created a template and want to show posts from a certain category. But the navigation widget is not working at all.

**Comment by neeelz** [comment] 2023-03-09 21:21
had the same issue. switched from firefox to chrome solved the issue...

**Comment by cristovaov** [comment] 2023-08-04 11:46
Issue still here in Firefox, switching to a chrome-based browser indeed solves the issue.

**Comment by lchique** [comment] 2023-08-11 10:18
Issue still here - using Chrome and does not work

**Comment by onurkoseoglu1** [comment] 2023-08-15 22:21
We are experiencing the same issue. Safari, Chrome, Brave... Non of them working. Only shows uncategorized category and others doesn't appear.

**Comment by brunojlucarelli** [comment] 2023-09-02 18:31
Experiencing the same issue. I have Categories: Announcements, Events, etc. However, after typing in character "C" only half of these occur, and going further I can't draw on the "Events" category amongst certain others.

**Comment by theeasadali** [comment] 2024-11-14 12:37
I also had the same issue but it just worked fine with elementor's **_"Post Info"_** widget. 

Add **"Post Info"** widget. In the content tab, select type to **"terms"** then select **taxonomy native or custom(it shows all)** then you're good to go.
