### ISSUE TITLE
Big issue in multisite Please respond asap

### ISSUE THREAD

**Issue by edemir206** [elementor/elementor#13967] opened 2021-02-19 13:02 UTC
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

Please anyone who runs this repo, take a look at my older issue, we have a big network with more than 450 sites in the university I work for and we can't edit Elementor pages which url contains more than 64 chars long. Please reffer to the link below to the complete issue, we need this bug fixed 
https://github.com/elementor/elementor/issues/13789

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by shilo-ey** [comment] 2021-02-22 08:32
Duplicate of #13789

**Closed by shilo-ey** 2021-02-22 08:32 UTC

**Comment by TIIUNDER** [comment] 2021-04-01 15:08
Why are you closing this issue as duplicate when the issue itself was closed by this thread? How about a solution?
