### ISSUE TITLE
Image Box Radius

### ISSUE THREAD

**Issue by zachleighton** [elementor/elementor#9124] opened 2019-09-18 16:31 UTC
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
When creating an image box it would be nice to be able to add a radius to the image. I'm able to add a radius to the content box by creating a border and then putting a radius on that border, but I can't seem to find a way to match that radius on the image side.  

**Describe the solution you'd like**
Add the ability to create a radius for the entire column. 

**See the attached screenshot
![Screen Shot 2019-09-18 at 9 31 14 AM](https://user-images.githubusercontent.com/27440278/65167278-168d0180-d9f7-11e9-98ca-5a99b299be9c.png)
**

**Comment by arielk** [comment] 2020-08-19 20:09
Duplicate of https://github.com/elementor/elementor/issues/9301

**Closed by arielk** 2020-08-19 20:09 UTC
