### ISSUE TITLE
BUG/In the new version of elementor, the color of the title widget does not change if ...

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#16037] opened 2021-08-18 12:02 UTC
hello
After updating elementor to version 3.4.0, all title widgets that had links changed color. For example, in the editor, the color is white, but in the website, the color is different. This bug only exists in the title widget.
I checked this problem on several websites and even websites where only elementor was active and there was this problem.

**this problem occurs for the title widget when :**
1- The title widget has a link.
2- option Improved CSS Loading is enabled.

please check. thank you

**details**
theme : hello elementor
wordpress 5.8
elementor : 3.4.0
elementor pro : 3.3.7

**Comment by Camilo517** [comment] 2021-08-18 17:01
+1

**Comment by AmibeWebsites** [comment] 2021-08-19 01:38
I've experienced something similar that may be related to this and #16046 - what I'm observing is that global color styling is being applied to elements where no color is set.

As per the attached image... the green highlighted element is a section where the title color is set; the yellow highlighted element is a title element within that section where color IS NOT set, yet there is a color value incorrectly being generated (the global style) in the CSS.

This is not only affecting title elements - I've seen it happening on icon lists also.

![image](https://user-images.githubusercontent.com/15866807/129993816-cf0e2d3f-7d2b-46d4-8830-dadd8470b053.png)

**Comment by 79ho3ein** [comment] 2021-08-19 01:54
than you @AmibeWebsites
I checked this problem, for me only the title widget has a problem and the icon list widget works properly. I hope this problem is solved. I have to stay in the previous version.
hello @shilo-ey may you check these bug?

**Comment by stasonua0** [comment] 2021-08-19 08:10
+1

**Comment by puregraphx** [comment] 2021-08-19 09:35
@79ho3ein try to add a link to one of your list icon items, then you'll notice the text colour will also override the link colour.
![image](https://user-images.githubusercontent.com/10434048/130045905-05ad655c-0e19-40b4-844f-32494d9cb418.png)

**Comment by DeoThemes** [comment] 2021-08-19 11:11
Also background color appears on buttons, even if my button doesn't have any color assigned - 
![4f280-clip-129kb](https://user-images.githubusercontent.com/16485360/130058969-9c3d201a-7257-41c1-a3bc-d1fa0ded3440.png)

**Comment by 79ho3ein** [comment] 2021-08-19 12:26
@puregraphx 
I checked the icon list widget again, it was not a problem for me. Just before I paint the icon, it had a different color than before (the same color that appears in the title widget and prevents color)
thank you

**Comment by jrevillini** [comment] 2021-08-19 13:14
What is the workaround and timeline for this to be released to wordpress.org repo? I have production sites affected by this. @79ho3ein said staying with previous version worked, but I tried rolling back Elementor and E Pro and it didn't fix it. Can anyone give steps to roll-back and fix this in the short term? Thx!

**Comment by 79ho3ein** [comment] 2021-08-19 13:20
@jrevillini
Restore elementor to the previous version, Or disable the Improved CSS Loading option from the elementor settings.

**Comment by ianmcilwraith** [comment] 2021-08-19 14:02
@jrevillini These steps just worked for me:
Restore Elementor to 3.4.0/Pro to 3.3.4
Regenerate Files & Data
Clear site caches/CDN if applicable
Disable automatic updates of the Elementor and Elementor Pro plugins if applicable

**Comment by jrevillini** [comment] 2021-08-19 14:51
@79ho3ein @ianmcilwraith thanks guys!

**Comment by shilo-ey** [comment] 2021-08-19 15:55
This issue has been resolved in Elementor v3.4.2

Feel free to update

Thanks!

**Closed by shilo-ey** 2021-08-19 15:55 UTC
Labels: bug, status/merged

**Comment by 79ho3ein** [comment] 2021-08-19 17:27
@shilo-ey thank you, but This bug (title widget bug) is still in the new version!

**Comment by jrevillini** [comment] 2021-08-19 17:49
> @shilo-ey thank you, but This bug (title widget bug) is still in the new version!

I upgraded and it resolved it for me. Maybe clear server cache? local? cloudflare/etc?

**Comment by ianmcilwraith** [comment] 2021-08-19 17:50
@79ho3ein it's resolved for me as well. I did regenerate the css files in Elementor and clear my site cache just to be sure.

**Comment by 79ho3ein** [comment] 2021-08-19 18:08
Thanks guys, maybe I need to regenerate the css files in elementor.  Do not do this.  I will test ‌. 

Thank you

**Comment by jonathansoltero** [comment] 2021-08-20 03:58
Nope, not working still, already cleared everything.

**Comment by freddekvist** [comment] 2021-08-20 06:49
same here, global colors are still messed up

**Comment by 79ho3ein** [comment] 2021-08-20 11:40
I did everything I could, But this problem still exists in the new version ...
hi @shilo-ey ,Please watch the video below ... only elementor and elementor pro are active. But the title widget still has bugs.
https://drive.google.com/file/d/1agHM3TJfZh3QvT5XUybn_Wh_V2pDa8Ee/view?usp=sharing

Friends please check to see if this problem still exists for you?  thank you

**Comment by mcrowell** [comment] 2021-08-20 12:50
Global colors aren't updating correctly on the front end when Improved CSS Loading is active. This is happening on a normal header with a global link color.

**Comment by 79ho3ein** [comment] 2021-08-20 13:06
> Global colors aren't updating correctly on the front end when Improved CSS Loading is active. This is happening on a normal header with a global link color.

True, but if you watched the video above, I did not use the global color !

**Comment by jonathansoltero** [comment] 2021-08-20 17:53
It fixed after I disabled 

"Improved CSS Loading"

**Comment by 79ho3ein** [comment] 2021-08-20 18:06
> It fixed after I disabled "Improved CSS Loading"
> 
> It seems disabling that feature resolves a bunch of styling issues I was having.

Yes, it was clear from the beginning that the problem was with "Improved CSS Loading". In any case, I hope elementor solves this problem.

**Comment by MichaelDarko** [comment] 2021-08-24 14:23
Same here. When "Improved CSS Loading" is active, the title widget link color doesn't work.

**Comment by Michaelgimii** [comment] 2021-08-24 15:31
This bug is also present on my sites. @shilo-ey please consider it.

**Comment by jrevillini** [comment] 2021-08-24 15:56
How do you guys even have that enabled? For me it's greyed out and set to default. Does that mean "off?" This screen is confusing with the dots and the dropdows so I don't really know what the hell I'm looking at lol ... but in any case, the site I was working on is properly inheriting heading colors from Astra, not from Elementor.
![image](https://user-images.githubusercontent.com/216786/130649420-2eb6969c-09a1-4824-9f26-3b74177fed3b.png)

**Comment by 79ho3ein** [comment] 2021-08-24 16:46
Hi @jrevillini 
This bug occurs when the "improved css loading" option is enabled. My theme is hello elementor and it has this problem. Of course, it exists in all my sites that are made with elementor.

**Comment by IT-Mesteren** [comment] 2023-08-13 09:08
2 years later this still isn't fixed

**Comment by susanne99** [comment] 2024-05-21 04:59
hi,
i use elementor 3.21.6.
the heading widget still doesn't work.
i use the website typographie settigns from elementor - it works but not with the heading widget.
the problem is, i cannot reset the color and typografie in style tab.
when i reset the color or typografie it set alwas the global primary setting - therefore, the predefined H1, H2,.. does not work

by the way: when i use fpr instance the infobox widtget, and i want to use the in elementor predefined H1, H2, ... this does not work too, because the infobox sets the color of a default color and overwrites the predefined style

please resolve quickly, you can't work like that

**Comment by heikkiheer** [comment] 2024-10-27 16:08
I also have the issue (without elementor). I run Wordpress 6.6.2, Astra Pro 4.8.2.

**Expected behaviour**
HTML-Text in header changes color

**Instead**
HTML-Text without link changes color as expected.
HTML-Text with link (e.g. mail address) does not change color.

**Findings**
_HTML-Text without link has correct css styles in inspector_
color: var(--ast-global-color-3);

_HTML-Text with link does not have correct css styles in inspector_
element.style {
    font-size: 9pt;
    color: #ffffff;         -----> WRONG
}
color: var(--ast-global-color-2);   ---> CORRECT

<img width="803" alt="Astrabug" src="https://github.com/user-attachments/assets/a2b400fb-6653-4311-9a6b-07a2bd4d640e">
