### ISSUE TITLE
Bug with FontAwesome codes in Custom CSS

### ISSUE THREAD

**Issue by f3bruary** [elementor/elementor#7179] opened 2019-02-23 15:54 UTC
## Prerequisites

- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

I have some custom css to restyle radio buttons en checkboxes. And I use fontawesome icons for this. When I add the custom css to the page in Elementor (just ignore the syntax)

`class {
 content: "\f096";
}`

It won't apply. But when I use a double backslash \\\f096 it does work. Perhaps because I need to escape the first \ so the second one is parsed properly. This is not the issue however.

The issue is that when I refresh the page (elementor builder) The \\\ becomes a \ again and it breaks again. So each time I edit this specific page I have to remember to add \\\ to all the FA icons.

## Steps to reproduce

Add custom css containing backslashes, save page, refresh builder, see custom css section again.

## Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by bainternet** [comment] 2019-02-24 08:19
@f3bruary 	


We can't replicate the issue describe nor do you need to use a double backslash.

If it's not working for you, please contact our support at support @elementor.com for guidance in resolving this issue and mention that you were directed by me and reference this issue.

thanks.

**Closed by bainternet** 2019-02-24 08:19 UTC

**Comment by f3bruary** [comment] 2019-02-24 19:15
@bainternet 

This is an example of the custom css code:

`input[type=radio] + label:before { content: "\f10c"; }
input[type=radio] + label:hover:before { content: "\f192"; filter: alpha(opacity=30); opacity: 0.3; }
input[type=radio]:checked + label:before { content: "\f192"; }
input[type=radio]:checked + label:hover:before { filter: alpha(opacity=100); opacity: 1; }`

If I enter this in custom css, and save the page, then reload the page builder, then all the backslashes are gone and only "f10c" is left.

But if I use "\\f10c", and save, and reload the page builder, then "\f10c" is left. It works like that until I save it again. Then it removes the remaining backslash again.

**Comment by robert1112** [comment] 2021-01-20 14:28
@f3bruary Hi I got the same problem. How do you get over it? Thank you.

**Comment by mapsmarketing** [comment] 2021-09-14 23:41
I am experiencing this with the latest Elementor versions to get around it you just add an extra backslash e.g. content: "\\e87a"

**Comment by nebulousGirl** [comment] 2021-11-16 16:32
I have that problem, too. The slash is stripped on the frontend, but remains visible in the admin.

**Comment by MartvanderKruis** [comment] 2022-01-10 10:26
Never had this problem before in many Elementor sites but now I have this same problem. The only difference is that this time I use Font Awesome Pro. 

font-family: 'Font Awesome 5 Pro'; 
content: '\e020';

As said above... that backslash appears inside the Elementor editor but disappears on the published page. Adding an extra backslash solves the problem on published page (but not in editor, duh) but I don't like this solution.

**Comment by mapsmarketing** [comment] 2022-03-28 23:12
> Never had this problem before in many Elementor sites but now I have this same problem. The only difference is that this time I use Font Awesome Pro.
> 
> font-family: 'Font Awesome 5 Pro'; content: '\e020';
> 
> As said above... that backslash appears inside the Elementor editor but disappears on the published page. Adding an extra backslash solves the problem on published page (but not in editor, duh) but I don't like this solution.

Completely agree that it's ugly

**Comment by mapsmarketing** [comment] 2022-04-04 04:37
I've figured out the root cause of this issue.

When setting the **CSS Print Method** to `Internal Embedding`, it causes the slash in the CSS `content` attribute to be removed. Instead set the **CSS Print Method** to `External File` and the issue will be resolved.
