### ISSUE TITLE
🔗 🚀 Feature Request: File uploads made in forms should attach the file in the email too. (Duplicate of #4868)

### ISSUE THREAD

**Issue by asimcard** [elementor/elementor#11678] opened 2020-06-19 03:52 UTC
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
It will allow for easier reading and access of files uploaded to the file upload option in the forms widget.
**Describe the solution you'd like**
When a user submits a form and that form also has a file upload that file should be attached to the email that is sent when the form get submitted. It would make it easier to read files this way as opposed to the link directly into the wp content folder.
**Describe alternatives you've considered**
I am considering using contact form 7 or another contact form plugin for this function

**Comment by TigranSaakyan** [comment] 2020-06-19 22:13
That's a nice feature to have

**Comment by arielk** [comment] 2020-06-20 21:08
Duplicate of https://github.com/elementor/elementor/issues/4868

**Closed by arielk** 2020-06-20 21:08 UTC
Labels: request/enhancement, type/developer-api, product/pro, component/forms/actions, type/privacy

**Comment by nicholaszein** [comment] 2024-01-05 21:04
Hello there @asimcard!

We have great news! 🙌 

### 📢 We're happy to announce that this feature was released with Elementor Pro v3.17.0! 🥳 

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
