### ISSUE TITLE
✅ Elementor Pro Forms Spam Filtering with Akismet

### ISSUE THREAD

**Issue by parasshah195** [elementor/elementor#11401] opened 2020-05-19 04:26 UTC
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Forms receiving spam - Manual submissions by users, meaning Honeypot isn't working. We don't want users to fill out reCAPTCHA.

**Describe the solution you'd like**
Integration with Akismet when the plugin is activated. Like Contact Form 7.

**Describe alternatives you've considered**
Contact Form 7. But don't want to install an additional plugin just for a single form on a page.

**Additional context**
- https://contactform7.com/spam-filtering-with-akismet/

**Comment by jarle0db** [comment] 2020-05-24 23:05
You are aware that you can use Google invisible recaptcha with Elementor form?

**Comment by parasshah195** [comment] 2020-05-25 03:57
@jarle0db, no I wasn't. Thanks for bringing it to attention.

I thought that reCaptcha integration meant that the captcha solving would show up every time (which would of course be a bad UX for an e-com website.. hurts trust). Didn't even know that Google had something like Invisible reCaptcha.

But we already use Akismet on the site for comment spam filtering, so an integration with Elementor Forms would certainly help.

In the meantime, will switch to using that. Thanks a lot!

**Comment by dasignlady** [comment] 2020-08-04 14:05
Any luck? I have both Honeypot and ReCapcha V3 activated on the form and spam and malicious links continue to come through in message area.

**Comment by mbaierl** [comment] 2021-01-11 11:40
Ideally other options like AntispamBee (GDPR compliant!) would also be supported as spam filters.

**Comment by eSilverStrike** [comment] 2021-03-07 16:53
+1 for both integrations. Not sure why Elementor doesn't support other common anti spam solutions as honeypot and recaptcha are not fool proof.

**Comment by onaralili** [comment] 2021-03-11 09:48
> Ideally other options like AntispamBee (GDPR compliant!) would also be supported as spam filters.

Agree! There are alternatives like [OOPSpam](https://www.oopspam.com/) that is also GDPR compliant and does better job than Akismet.

**Comment by iMiek** [comment] 2021-04-13 14:14
+1 for me

**Comment by iMiek** [comment] 2021-04-13 14:17
+1 for akismet
antispambee: "we just prevent *comment* spam" not for forms"

**Comment by en-iln592** [comment] 2021-04-22 17:49
+1 for akismet integration on forms.

**Comment by plantoeat** [comment] 2021-07-06 23:05
+1 for akismet integration on forms.

**Comment by boospot** [comment] 2021-07-27 10:23
+1 Akismet is the standard for spam filtering

**Comment by harmsway14** [comment] 2021-08-17 12:03
+1 for akismet integration on forms.

**Comment by birquah** [comment] 2021-09-02 13:50
+1 for Akismet integration on forms.

**Comment by rafaramos** [comment] 2021-10-03 09:40
+1 for Akismet integration on forms.

**Comment by Alwaysin** [comment] 2022-01-25 10:44
We'd like to have the same possibility!

Let's face it: the honeypot included does not work correctly and we have good reasons to not want to use recaptcha, be it visible or invisible. Please give us the possibility to filter out spam.

**Comment by onaralili** [comment] 2022-01-25 18:28
> Please add native spam filters that work! Been asking for this for awhile. Add character count limits for message text. Sick of Eric Jones....

Add OOPSpam. It has character limit. A native support would be nice tho. We all sick of Eric Jones lol

**Comment by Boytobeaman** [comment] 2022-04-25 02:04
+1 Akismet is the standard for spam filtering

**Comment by mbaierl** [comment] 2022-04-25 09:32
> +1 Akismet is the standard for spam filtering

... but not compliant with the GDPR, so it can't be used in the European Union. 
So I'd prefer Antispam Bee, which is GDPR-compliant.

**Comment by romapad** [comment] 2022-05-08 06:07
+1 for Akismet

**Comment by kskonovalov** [comment] 2022-10-25 19:10
Any updates? +1 for this

**Comment by castelar** [comment] 2022-12-28 22:25
+1

**Comment by fonkey** [comment] 2023-01-10 09:59
+1

**Comment by philrp** [comment] 2023-03-10 03:44
+1

**Comment by bobmatyas** [comment] 2023-06-21 18:34
It would be nice to see this implemented.

**Comment by formosattic** [comment] 2023-09-12 02:17
+1, on behalf of an Elementor user who contacted the Akismet support.

**Comment by joexcm** [comment] 2023-09-19 10:45
+1 for Akismet here. Honeypot is an irrelevent feature nowadays

**Comment by MikeWhelan** [comment] 2023-09-28 18:05
+1 for more advanced spam filter, i.e. Akismet or Antispam Bee, etc.  

ReCaptcha kills page speed and does not filter enough spam

**Comment by taropaa** [comment] 2023-12-11 13:23
That's why I can't use Elementor's form system. It's a shame because it would be great otherwise. But as soon as your website ranks you get flooded with spam.

**Comment by yonifre** [comment] 2024-01-26 01:52
Maspik – Spam Blacklist, integrate well to elementor forms
https://wordpress.org/plugins/contact-forms-anti-spam/

**Comment by Alwaysin** [comment] 2024-01-30 14:48
> Maspik – Spam Blacklist, integrate well to elementor forms https://wordpress.org/plugins/contact-forms-anti-spam/

I can confirm that it works for us, thanks for pointing to it!

**Comment by nicholaszein** [comment] 2024-04-12 03:28
Hey everyone!

### This feature was released with Elementor Pro v3.19! 🥳 

You can now use Akismet to filter spam from Elementor forms! For more information please [read the article in the Help Center](https://elementor.com/help/block-spam-messages-from-forms/#add-an-anti-spam-filter-to-your-forms).

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂

**Closed by nicholaszein** 2024-04-12 03:28 UTC
Labels: product/pro, widget/forms, status/merged, request/integration, solved, mod*, product/3.19
