### ISSUE TITLE
Saving a new Global Font from Site Settings > Typography doesn't actually create a new saved font

### ISSUE THREAD

**Issue by d19dotca** [elementor/elementor#12344] opened 2020-08-31 03:20 UTC
## Prerequisites

- [ x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ x] The issue still exists against the latest stable version of Elementor.

## Description

When trying to create a new Global Font from editing the Site Settings Typography directly, it is not saved properly despite everything looking okay in the GUI until after a reload/refresh of the page when we find out that the new Global Font wasn't actually saved.

## Steps to reproduce

1. Using Elementor 3.0.4 and Elementor Pro 3.0.1, edit a page using Elementor, then go to Site Settings > Typography.
2. In Typography, go to H1 and select the pencil icon, then the plus icon while editing H1 to Create New Global Font, name it whatever you want.
3. Update button to save changes, and reload the page. Note that the new Global Font is nowhere to be found and the set back to "Default" global style.

## Isolating the problem

- [ x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ x] This bug happens with a default WordPress theme active.
- [ x] I can reproduce this bug consistently using the steps above.

## Environment
					
== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.29 (Ubuntu)
	MySQL version: (Ubuntu) v5.7.29
	PHP Version: 7.3.17-1+ubuntu18.04.1+deb.sury.org+1
	PHP Max Input Vars: 1800
	PHP Max Post Size: 512M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: There are some writing permissions issues with the following directories/files:
		 - WordPress root directory
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.5
	Site URL: https://<hostname.domain.tld>
	Home URL: https://<hostname.domain.tld>
	WP Multisite: No
	Max Upload Size: 512 MB
	Memory limit: 384M
	Permalink Structure: /%category%/%postname%/
	Language: en-CA
	Timezone: America/Vancouver
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.3.0
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_CA
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 11_0) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0 Safari/605.1.15

== Active Plugins ==
	AuthLDAP
		Version: 2.4.2
		Author: Andreas Heigl <andreas@heigl.org>

	Better Search Replace
		Version: 1.3.3
		Author: Delicious Brains

	Disable WordPress Core Updates
		Version: 1.5
		Author: John Blackbourn

	Elementor
		Version: 3.0.4
		Author: Elementor.com

	Elementor Pro
		Version: 3.0.1
		Author: Elementor.com

	MainWP Child
		Version: 4.0.7.2
		Author: MainWP

	Rank Math SEO
		Version: 1.0.47.1
		Author: Rank Math

	ShortPixel Image Optimizer
		Version: 4.20.2
		Author: ShortPixel

	WP-Matomo
		Version: 1.0.22
		Author: André Bräkling

	WP Mail SMTP
		Version: 2.3.1
		Author: WPForms

== Elements Usage ==
	
	archive : 1
		archive-posts : 1
		theme-archive-title : 1
	footer : 1
		divider : 1
		heading : 3
		nav-menu : 1
		search-form : 1
		social-icons : 1
		text-editor : 2
	header : 1
		icon-list : 1
		image : 1
		nav-menu : 1
	single : 2
		heading : 1
		image : 2
		post-info : 1
		post-navigation : 1
		share-buttons : 1
		theme-post-content : 2
		theme-post-title : 2
	wp-post : 12
		accordion : 1
		animated-headline : 1
		button : 7
		counter : 2
		divider : 1
		facebook-button : 1
		form : 3
		heading : 40
		icon-box : 7
		icon-list : 5
		image : 1
		lottie : 2
		portfolio : 1
		posts : 1
		social-icons : 3
		tabs : 3
		testimonial-carousel : 1
		text-editor : 35
		toggle : 1
	wp-page : 12
		accordion : 1
		alert : 1
		button : 18
		call-to-action : 1
		divider : 2
		facebook-page : 1
		form : 1
		heading : 13
		lottie : 1
		menu-anchor : 4
		posts : 1
		price-list : 2
		price-table : 10
		social-icons : 2
		text-editor : 18
	single-post : 1
		icon-list : 1
		post-info : 1
		post-navigation : 1
		theme-post-content : 1
		theme-post-excerpt : 1
		theme-post-title : 1
	search-results : 1
		archive-posts : 1
		theme-archive-title : 1
	error-404 : 1
		heading : 2
		nav-menu : 1
		search-form : 1

== Log ==
	
Log: showing 20 of 362020-08-27 20:14:51 [info] Elementor/Upgrades - _v_3_0_0_move_general_settings_to_kit Start  
2020-08-27 20:14:51 [info] Elementor/Upgrades - _v_3_0_0_move_general_settings_to_kit Finished 
2020-08-27 20:14:51 [info] Elementor/Upgrades - _v_3_0_0_move_default_colors_to_kit Start  
2020-08-27 20:14:51 [notice] System colors are disabled. nothing to do. 
2020-08-27 20:14:51 [info] Elementor/Upgrades - _v_3_0_0_move_default_colors_to_kit Finished 
2020-08-27 20:14:51 [info] Elementor/Upgrades - _v_3_0_0_move_saved_colors_to_kit Start  
2020-08-27 20:14:51 [info] Elementor/Upgrades - _v_3_0_0_move_saved_colors_to_kit Finished 
2020-08-27 20:14:51 [info] Elementor/Upgrades - _v_3_0_0_move_default_typography_to_kit Start  
2020-08-27 20:14:51 [notice] System typography is disabled. nothing to do. 
2020-08-27 20:14:51 [info] Elementor/Upgrades - _v_3_0_0_move_default_typography_to_kit Finished 
2020-08-27 20:14:51 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.0-beta6',
  'to' => '3.0.3',
)]
2020-08-27 20:14:51 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.0-beta6',
  'to' => '3.0.3',
)]
2020-08-27 20:15:15 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.0.0-beta3',
  'to' => '3.0.0',
)]
2020-08-27 20:15:28 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.0.0',
  'to' => '3.0.1',
)]
2020-08-29 22:42:29 [notice] Re-migrate 3.0.0 globals: Start 
2020-08-29 22:42:29 [notice] Re-migrate 3.0.0 globals: _v_3_0_0_move_default_typography_to_kit 
2020-08-29 22:42:29 [notice] Re-migrate 3.0.0 globals: _v_3_0_0_move_default_colors_to_kit 
2020-08-29 22:42:29 [notice] Re-migrate 3.0.0 globals: _v_3_0_0_move_saved_colors_to_kit 
2020-08-29 22:42:29 [notice] Re-migrate 3.0.0 globals: End 
2020-08-30 15:58:57 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.3',
  'to' => '3.0.4',
)]

PHP: showing 2 of 2PHP: 2020-08-10 19:29:05 [notice X 25][/app/data/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-08-29 22:25:56 [notice X 11][/app/data/wp-content/plugins/elementor-pro/modules/posts/skins/skin-content-base.php::248] Trying to get property 'ID' of non-object [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 4 of 4JS: 2020-08-15 00:04:04 [error X 8][https://<hostname.domain.tld>/wp-admin/js/editor.min.js?ver=5.5:2:725] Cannot read property \'style\' of undefined 
JS: 2020-08-16 04:16:37 [error X 6][https://<hostname.domain.tld>/wp-content/plugins/elementor-pro/assets/lib/lottie/lottie.min.js?ver=5.6.6:17:3455] null is not an object (evaluating \'this._cbs[t]\') 
JS: 2020-08-16 04:32:44 [error X 25][https://<hostname.domain.tld>/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.0.0-beta5:2:469505] undefined is not an object (evaluating \'this.container.document\') 
JS: 2020-08-16 05:25:00 [error X 43][https://<hostname.domain.tld>/wp-content/plugins/elementor/assets/js/editor-modules.min.js?ver=3.0.0-beta5:2:55851] undefined is not an object (evaluating \'e[o].global\')

**Comment by arielk** [comment] 2020-08-31 05:02
Duplicate of https://github.com/elementor/elementor/issues/12272

Thanks for your reporting!

**Closed by arielk** 2020-08-31 05:02 UTC

**Comment by d19dotca** [comment] 2020-08-31 05:31
Sorry about that. Not sure how I missed that other ticket - I searched for 'global typography site settings' but nothing came up for some reason. Thank you for linking this to the original ticket.
