### ISSUE TITLE
Responsive: Add mediaquery for 2k 4k?

### ISSUE THREAD

**Issue by exolon82** [elementor/elementor#11785] opened 2020-07-03 10:03 UTC
- [x]  I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

Why not add previews for 4k screens? or 2k, widescreen?

**Comment by shilo-ey** [comment] 2020-07-03 13:43
Duplicate of #2043

**Closed by shilo-ey** 2020-07-03 13:43 UTC
