### ISSUE TITLE
🔗 🐞 Bug Report: Custom unit bug - responsive (Duplicate of #20961)

### ISSUE THREAD

**Issue by Michaelgimii** [elementor/elementor#21683] opened 2023-03-18 13:30 UTC
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Hi

If we select the custom unit on the desktop and change it back to px or any other unit, if we enter the tablet or mobile mode, the custom unit will be displayed as the default unit.

### Steps to reproduce

1- Add a widget.
2- On the Advanced tab, select custom unit for its width.
3- Now again change the width from custom unit to pixels or other unit.
4- Now if you view the tablet or mobile mode, the custom unit will be displayed as the default unit. **While in the previous step, we had selected the px unit on the desktop.**

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

https://user-images.githubusercontent.com/88034902/226109186-848702d3-0927-4f32-87ee-632ed6b0fe57.mp4

**Comment by perks98** [comment] 2023-03-20 11:50
I had reported this here: #20961, but still no ETA unfortunately.

**Comment by nicholaszein** [comment] 2023-09-24 03:40
Hello @XXX!

Thank you for your submission! 🙏 

### 🔗 🐞 This issue is a Duplicate of #20961

Which is on the same subject. 

For this reason, I'm closing this thread and 🔃 **Merging** it with the original, so we can have all the discussions in one location, and deal with it more efficiently.

Feel free to continue the conversation there. 😉 

Kind regards

**Closed by nicholaszein** 2023-09-24 03:40 UTC
Labels: bug, type/responsive, type/ui/ux, component/editor
