### ISSUE TITLE
⛔ 🧩 📚 Elementor 3.26 beta - Fatal Error with custom widgets - Class not found

### ISSUE THREAD

**Issue by qantumthemes** [elementor/elementor#29425] opened 2024-11-26 22:10 UTC
### Prerequisites

- [X] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [X] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

Tons of default classes used for custom plugins are not found with Elementor Beta 3.26.0 

Example:
Fatal error: Uncaught Error: Class "Elementor\Core\Schemes\Typography" not found...

### Steps to reproduce

Just use standard classes in a custom widget, like
Elementor\Core\Files\CSS\Post
Elementor\Core\Schemes\Typography

they are not found.

Is nice that there is ZERO documentation on this change in the release notes.
https://github.com/orgs/elementor/discussions/29403

### Expected behavior

Not to break entirely a website. Removed classes should go through a soft deprecation first.

### Isolating the problem

- [ ] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [x] This bug happens with the Hello Elementor theme active.
- [X] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

```txt
PHP 8.3
Wp 6.7.1
```

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by toineenzo** [comment] 2024-11-26 23:55
Please post your full system info @qantumthemes ;)

**Comment by nicholaszein** [comment] 2024-11-27 04:04
Hi @enamul-hoque,

This class was finally removed after being deprecated since version 3.0. Please refer to the blog post below, and check the Documentation to learn how to replace it with Globals.

https://developers.elementor.com/elementor-3-26-developers-update/

**Comment by nicholaszein** [comment] 2024-11-27 04:05
Hi @qantumthemes ,

This class was finally removed after being deprecated since version 3.0. Please refer to the blog post below, and check the Documentation to learn how to replace it with Globals.

https://developers.elementor.com/elementor-3-26-developers-update/

**Comment by qantumthemes** [comment] 2024-11-27 08:26
Thanks, very appreciated.
A small suggestion for next site-breaking updates: maybe a little link at the very bottom of the notes is not so visible for such a disruptive change https://www.dropbox.com/s/2ljnrhfm7dnn8wm/scr%202024-11-27%20at%2009.24.09.jpg?dl=0

BTW the documentation is clear. All was fixed promptly.
Thanks!

**Comment by nicholaszein** [comment] 2024-11-27 13:08
@qantumthemes

When Elementor 3.0 came out, we did made it clear what needed to be changed.

I suggest subscribing to the developers newsletter to keep up to date with changes like this.

You can do it by switching the Beta Testing option off and on again in your WordPress Dashboard > Elementor > Tools.

Elementor 3.0 was released in October, 2020.

**Comment by nicholaszein** [comment] 2024-12-04 16:56
Hi @qantumthemes!

I assume that at this point you have already made the necessary changes to your code to make it compatible with the future release.

I'm closing this issue as it is not a bug.

Please, in the future make sure you share the **full Elementor System Info** as required in the Bug Report form. We will not accept issues without the required information.

Kind regards

**Closed by nicholaszein** 2024-12-04 16:56 UTC
Labels: compatibility/3rd-party, type/developer-api, component/code, mod*, compatibility/3rd-party-code
