### ISSUE TITLE
Loop feature for more custom dynamic content

### ISSUE THREAD

**Issue by mo-trueui** [elementor/elementor#15679] opened 2021-07-16 16:28 UTC
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
One of the primary reasons why I sometimes end up going the fully-custom theme path with my clients is the lack of true loops as a module. This makes it a bit difficult to create some simple repeatable formats like menus, comparison lists, custom blog pages, etc. I appreciate the posts module and all the other amazing dynamic tags, and I believe that adding a loop feature in the way I will describe (if possible) would be amazing.

**Describe the solution you'd like**
The loop that I have in mind would ideally allow any other module inside of it, so it would essentially act like a section, or even something that wraps outside a section. Within the loop, we set the parameters for the query we'd like to make, then we can proceed to build out a single section with any modules we like to represent the content that goes inside the loop to be repeated with the number of posts available and parameters given. To summarize, this would allow building a custom posts archive within the content of a normal page.

**Describe alternatives you've considered**
I usually either go with a custom Wordpress template whenever I need a custom loop and create a shortcode or something like that to use within Elementor, or I go the static path and repeat the same section over and over on the page.

A completely alternative way to make my suggestion would be to have a separate loop builder (like the theme builder), which generates a shortcode or some sort of insertable module.

**Additional context**

**Comment by Stimson** [comment] 2021-07-16 17:44
You may want to look into Toolset for this functionality.

**Comment by shilo-ey** [comment] 2021-07-18 07:06
Duplicate of #4440

**Comment by shilo-ey** [comment] 2021-07-18 07:06
I merged this issue with #4440, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!

**Closed by shilo-ey** 2021-07-18 07:06 UTC

**Comment by nicholaszein** [comment] 2023-08-01 22:26
Hello there!

We have great news! 🙌 

### 📢 We're happy to announce the new Loop Builder released with Elementor Pro v3.8.0! 🥳 

With the new Loop Grid widget, you can customize your post listings with custom templates! 💪 
Drag & Drop widgets to create complex designs, fine-tune your Loop Grid layout, add alternate templates, and much more!

This is just the first phase. More customization is coming!

Check out the article here: https://elementor.com/help/loop-grid/

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
