### ISSUE TITLE
⛔ 🐞 Bug Report: Styles dont update until manual Regenerate CSS - and then it reverts

### ISSUE THREAD

**Issue by JonathanCrossland** [elementor/elementor#21246] opened 2023-02-06 11:52 UTC
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

The CSS applied in templates etc do not get applied unless you click regenerate CSS is elementor settings.
However, unexpectedly the css reverts, and the old styles come back.

There is a big report here that lists similar problems. Could we please have a fix - or adequate work around.

### Steps to reproduce

Modify a template using html and applying CSS.

You do not see the change in the published preview, but only in the designer when editing.

Click regenerate CSS.

Refresh the preview, and the styles are updated.

logout. close session. edit other pages and content. (This part is unknown as to its cause)

Visit the original page and it has reverted to previous CSS, requiring you to Regenerate CSS again.

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently following the steps above.

### System Info

<details>
<summary>System Info</summary>

````txt


					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: (Ubuntu) v5.7.41
	PHP Version: 8.1.11
	PHP Memory Limit: 128M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 64M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: There are some writing permissions issues with the following directories/files:
		 - .htaccess file
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.1.1
	Site URL: domain
	Home URL: domain
	WP Multisite: No
	Max Upload Size: 62 MB
	Memory limit: 1024M
	Max Memory limit: 512M
	Permalink Structure: /%postname%/
	Language: en-GB
	Timezone: Europe/London
	Admin Email: admin@
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.6.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_GB
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36

== Active Plugins ==
	Advanced Custom Fields: Extended
		Version: 0.8.9
		Author: ACF Extended

	Advanced Custom Fields: Table Field
		Version: 1.3.18
		Author: Johann Heyne

	Advanced Custom Fields PRO
		Version: 6.0.7
		Author: WP Engine

	Backup For WP
		Version: 6.1
		Author: Backup for WP

	Code Snippets
		Version: 5.2.1
		Author: Code Snippets Pro

	Custom Post Type UI
		Version: 1.13.4
		Author: WebDevStudios

	Database Management tool - Adminer
		Version: 2.1.0
		Author: Pexle Chris

	DataWarehouse Connector
		Version: 1.0.12
		Author: Kamber Peka

	Download Manager
		Version: 6.2.9
		Author: W3 Eden, Inc.

	Duplicate Page
		Version: 4.5
		Author: mndpsingh287

	Dynamic.ooo - Dynamic Content for Elementor
		Version: 2.8.8
		Author: Dynamic.ooo

	Elementor
		Version: 3.10.2
		Author: Elementor.com

	Elementor Pro
		Version: 3.10.3
		Author: Elementor.com

	ElementsKit Lite
		Version: 2.8.1
		Author: Wpmet

	ElementsKit Pro
		Version: 3.1.0
		Author: Wpmet

	Faster Updates
		Version: 0.3.2
		Author: WP Core Contributors

	FileBird
		Version: 5.1.4
		Author: Ninja Team

	Health Check & Troubleshooting
		Version: 1.5.1
		Author: The WordPress.org community

	Print-O-Matic
		Version: 2.1.9
		Author: twinpictures

	Rollback Update Failure
		Version: 4.1.2
		Author: WP Core Contributors

	Site Kit by Google
		Version: 1.92.0
		Author: Google

	TranslatePress - Developer
		Version: 1.2.4
		Author: Cozmoslabs, Razvan Mocanu, Madalin Ungureanu

	TranslatePress - Multilingual
		Version: 2.4.6
		Author: Cozmoslabs, Razvan Mocanu, Madalin Ungureanu, Cristophor Hurduban

	UpdraftPlus - Backup/Restore
		Version: 1.22.24
		Author: UpdraftPlus.Com, DavidAnderson

	WP Crontrol
		Version: 1.15.1
		Author: John Blackbourn & crontributors

	WP File Manager
		Version: 7.1.7
		Author: mndpsingh287


== Must-Use Plugins ==
	BPS MU Tools
		Version: 9.0
		Author: AITpro

	Health Check Troubleshooting Mode
		Version: 1.8.1
		Author: 


== Elements Usage ==
	
	container : 2
		container : 1
		heading : 1
		text-editor : 1
	footer : 1
		container : 9
		heading : 9
		icon-list : 1
		image : 2
		nav-menu : 2
		social-icons : 1
		text-editor : 1
	header : 4
		button : 4
		container : 12
		ekit-nav-menu : 2
		hotspot : 2
		icon : 2
		image : 6
		shortcode : 2
	page : 1
		container : 1
		dyncontel-acf : 1
	popup : 2
		button : 7
		container : 14
		divider : 4
		image : 6
		nav-menu : 1
		shortcode : 1
		text-editor : 6
	section : 13
		container : 83
		divider : 1
		dyncontel-acf : 21
		dyncontel-featured-image : 4
		heading : 5
		icon : 7
		shortcode : 2
		text-editor : 8
	widget : 0
		form : 2
	wp-post : 0
		button : 6
		container : 39
		dce-dynamicposts-v2 : 1
		divider : 3
		elementskit-heading : 5
		elementskit-page-list : 5
		heading : 18
		image : 9
		image-box : 1
		loop-grid : 11
		menu-anchor : 1
		nav-menu : 5
		shortcode : 6
		text-editor : 34
		theme-site-logo : 2
	wp-page : 10
		button : 5
		container : 63
		dce-dynamicposts-v2 : 2
		form : 5
		google_maps : 8
		heading : 15
		icon-list : 8
		image : 16
		loop-grid : 5
		posts : 1
		text-editor : 51
	single-post : 4
		container : 54
		dce-acf-repeater-v2 : 2
		dce-dynamicposts-v2 : 2
		dce-flexible-content : 1
		divider : 8
		dyncontel-acf : 24
		dyncontel-acf-relation : 14
		dyncontel-acfgallery : 1
		dyncontel-acfslider : 2
		google_maps : 2
		heading : 28
		icon : 13
		icon-list : 2
		image : 8
		posts : 1
		shortcode : 3
		text-editor : 4
		theme-post-content : 2
		theme-post-title : 3
		video : 3
	loop-item : 4
		alert : 1
		button : 2
		container : 29
		dyncontel-acf : 12
		image : 8
		image-box : 2
		shortcode : 1
		text-editor : 1
		theme-post-title : 5
	error-404 : 1
		button : 1
		heading : 3
		image : 3


== Settings ==
	
	cpt_support: post, page, e-landing-page, property
	allow_tracking: yes
	unfiltered_files_upload: 1
	font_display: swap
	load_fa4_shim: yes


== Features ==
	Custom Fonts: 0
	Custom Icons: 0

== Integrations ==
	
	google_maps: Active
	recaptcha_v3: Active


== Elementor Experiments ==
	Optimised DOM Output: Inactive
	Improved asset loading: Inactive
	Improved CSS Loading: Inactive
	Inline Font Icons: Active
	Accessibility improvements: Active
	Additional Custom Breakpoints: Active
	Hide native WordPress widgets from search results: Active
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active
	Default to New Theme Builder: Active
	Hello Theme Header & Footer: Active
	Landing pages: Active
	Nested Elements: Inactive by default
	Lazy Load Background Images: Active
	Save as Default: Active
	Page Transitions: Active
	Notes: Active
	Loop: Active
	Loop Carousel: Inactive by default
	Form Submissions: Active
	Scroll Snap: Active


== Log ==
	
JS: showing 9 of 9JS: 2023-01-18 21:24:00 [error X 17][https://domain/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.9.1:3:294308] Cannot read properties of undefined (reading \'id\') 
JS: 2023-01-19 08:45:14 [error X 6][https://domain/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view120\") has already been destroyed and cannot be used. 
JS: 2023-01-22 19:54:14 [error X 1][https://domain/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.9.1:3:616499] Cannot read properties of undefined (reading \'isDesignable\') 
JS: 2023-01-25 14:20:01 [error X 1][https://domain/wp-content/plugins/dynamic-content-for-elementor/assets/js/icons-form.min.js?ver=2.8.4:1:594] Cannot read properties of undefined (reading \'size\') 
JS: 2023-01-26 23:52:58 [error X 11][https://domain/wp-admin/load-scripts.php?c=0&loadchunk_0=jquery-core,jquery-migrate,regenerator-runtime,wp-polyfill,underscore,backbone,jquery-ui-core,jquery-ui-mouse,wp-api-request,wp-&loadchunk_1=hooks&ver=6.1.1:2:51824] Cannot read properties of undefined (reading 'replace') 
JS: 2023-01-31 12:06:28 [error X 1][https://domain/wp-content/plugins/elementor/assets/js/common-modules.min.js?ver=3.10.2:2:52931] Model.isValidChild() should be implemented, please provide 'isValidChild' functionality. 
JS: 2023-01-31 12:49:32 [error X 4][https://domain/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: "view126") has already been destroyed and cannot be used. 
JS: 2023-01-31 18:00:54 [error X 1][https://domain/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: "view56485") has already been destroyed and cannot be used. 
JS: 2023-02-03 13:48:45 [error X 1][https://domain/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: "view3621") has already been destroyed and cannot be used. 

PHP: showing 13 of 13PHP: 2023-01-22 19:58:16 [notice X 1052][var/www/vhosts/website/public/wp-content/plugins/elementor-pro/core/database/model-base.php::135] Return type of ElementorPro\Core\Database\Model_Base::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice [array (
  'trace' => '
#0:<website>public/wp-content/plugins/elementor-pro/core/database/model-base.php(10): Elementor\Core\Logger\Manager -> rest_error_handler()
#1:<website>public/wp-content/plugins/elementor-pro/plugin.php(154): class type include()array (
  0 => 'var/www/vhosts/website/public/wp-content/plugins/elementor-pro/core/database/model-base.php',
)
#2:<website>public/wp-content/plugins/elementor-pro/modules/notes/database/models/note.php(18): ElementorPro\Plugin -> autoload()
#3:<website>public/wp-content/plugins/elementor-pro/plugin.php(154): class type include()array (
  0 => 'var/www/vhosts/website/public/wp-content/plugins/elementor-pro/modules/notes/database/models/note.php',
)
#4:<website>public/wp-content/plugins/elementor-pro/modules/notes/data/controller.php(243): ElementorPro\Plugin -> autoload()
',
)]
PHP: 2023-01-25 23:38:15 [warning X 69][var/www/vhosts/website/public/wp-content/plugins/elementor/includes/managers/image.php::108] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-01-26 23:39:01 [notice X 80][var/www/vhosts/website/public/wp-content/plugins/elementor/includes/controls/groups/base.php::497] str_replace(): Passing null to parameter #2 ($replace) of type array|string is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-01-26 23:54:04 [notice X 1008][var/www/vhosts/website/public/wp-content/plugins/elementor-pro/core/utils/collection.php::75] Return type of ElementorPro\Core\Utils\Collection::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-01-30 18:39:08 [notice X 429][var/www/vhosts/website/public/wp-content/plugins/elementor-pro/core/database/model-base.php::135] Return type of ElementorPro\Core\Database\Model_Base::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice [array (
  'trace' => '
#0:<website>public/wp-content/plugins/elementor-pro/core/database/model-base.php(10): Elementor\Core\Logger\Manager -> rest_error_handler()
#1:<website>public/wp-content/plugins/elementor-pro/plugin.php(159): class type include()array (
  0 => 'var/www/vhosts/website/public/wp-content/plugins/elementor-pro/core/database/model-base.php',
)
#2:<website>public/wp-content/plugins/elementor-pro/modules/notes/database/models/note.php(18): ElementorPro\Plugin -> autoload()
#3:<website>public/wp-content/plugins/elementor-pro/plugin.php(159): class type include()array (
  0 => 'var/www/vhosts/website/public/wp-content/plugins/elementor-pro/modules/notes/database/models/note.php',
)
#4:<website>public/wp-content/plugins/elementor-pro/modules/notes/data/controller.php(243): ElementorPro\Plugin -> autoload()
',
)]
PHP: 2023-01-31 12:44:43 [warning X 18][var/www/vhosts/website/public/wp-content/plugins/elementor/core/common/modules/ajax/module.php::172] Undefined array key "data" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-01-31 13:09:39 [notice X 40][var/www/vhosts/website/public/wp-content/plugins/elementor-pro/modules/custom-css/module.php::76] trim(): Passing null to parameter #1 ($string) of type string is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-01-31 17:57:56 [notice X 1][var/www/vhosts/website/public/wp-content/plugins/elementor-pro/core/utils/collection.php::75] Return type of ElementorPro\Core\Utils\Collection::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice [array (
  'trace' => '
#0:<website>public/wp-content/plugins/elementor-pro/core/utils/collection.php(11): Elementor\Core\Logger\Manager -> rest_error_handler()
#1:<website>public/wp-content/plugins/elementor-pro/plugin.php(159): class type include()array (
  0 => 'var/www/vhosts/website/public/wp-content/plugins/elementor-pro/core/utils/collection.php',
)
#2:<website>public/wp-content/plugins/elementor-pro/core/database/query-builder.php(1222): ElementorPro\Plugin -> autoload()
#3:<website>public/wp-content/plugins/elementor-pro/core/database/query-builder.php(1153): ElementorPro\Core\Database\Query_Builder -> get_bindings()
#4:<website>public/wp-content/plugins/elementor-pro/modules/notes/database/query/note-query-builder.php(520): ElementorPro\Core\Database\Query_Builder -> update()
',
)]
PHP: 2023-01-31 18:38:36 [warning X 5][var/www/vhosts/website/public/wp-content/plugins/elementor/includes/conditions.php::90] Trying to access array offset on value of type null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-01-31 19:43:05 [warning X 45][var/www/vhosts/website/public/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php::150] Undefined array key "condition_type" [array (
  'trace' => '
#0:<website>public/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(150): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_template_json_item()
#2:<website>public/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(120): class type array_map()
#3:<website>public/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(59): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_templates_json()
#4:<website>public/wp-content/plugins/elementor/data/base/endpoint.php(158): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> get_items()
',
)]
PHP: 2023-01-31 19:43:06 [warning X 10][var/www/vhosts/website/public/wp-content/plugins/elementor-pro/modules/loop-builder/module.php::84] Undefined array key "elementor-preview" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-02-03 16:02:15 [notice X 30][var/www/vhosts/website/public/wp-content/plugins/elementor-pro/core/database/model-base.php::135] Return type of ElementorPro\Core\Database\Model_Base::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-02-06 10:58:55 [notice X 2][var/www/vhosts/website/public/wp-content/plugins/elementor-pro/modules/custom-css/module.php::76] trim(): Passing null to parameter #1 ($string) of type string is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1:<website>public/wp-content/plugins/elementor-pro/modules/custom-css/module.php(76): class type trim()
#2:<website>public/wp-includes/class-wp-hook.php(308): ElementorPro\Modules\CustomCss\Module -> add_page_settings_css()
#3:<website>public/wp-includes/class-wp-hook.php(332): WP_Hook -> apply_filters()
#4:<website>public/wp-includes/plugin.php(517): WP_Hook -> do_action()
',
)]

Log: showing 20 of 202023-01-26 21:41:05 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Dynamic.ooo - Dynamic Content for Elementor',
  'from' => '2.8.4',
  'to' => '2.8.8',
)]
2023-01-26 21:44:54 [info] elementor::elementor_updater Started 
2023-01-26 21:44:54 [info] Elementor/Upgrades - _on_each_version Start  
2023-01-26 21:44:55 [info] Elementor/Upgrades - _on_each_version Finished 
2023-01-26 21:44:55 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.9.1',
  'to' => '3.10.1',
)]
2023-01-26 23:25:06 [info] elementor-pro::elementor_pro_updater Started 
2023-01-26 23:25:06 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-01-26 23:25:06 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-01-26 23:25:06 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.9.1',
  'to' => '3.10.2',
)]
2023-01-26 23:25:06 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.9.1',
  'to' => '3.10.2',
)]
2023-01-30 18:36:25 [info] elementor::elementor_updater Started 
2023-01-30 18:36:25 [info] Elementor/Upgrades - _on_each_version Start  
2023-01-30 18:36:26 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.10.1',
  'to' => '3.10.2',
)]
2023-01-30 18:36:27 [info] Elementor/Upgrades - _on_each_version Finished 
2023-01-30 18:36:27 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.10.1',
  'to' => '3.10.2',
)]
2023-01-30 18:36:57 [info] elementor-pro::elementor_pro_updater Started 
2023-01-30 18:36:57 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-01-30 18:36:57 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-01-30 18:36:57 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.10.2',
  'to' => '3.10.3',
)]
2023-01-30 18:36:57 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.10.2',
  'to' => '3.10.3',
)]



== Elementor - Compatibility Tag ==
	
	Dynamic.ooo - Dynamic Content for Elementor: Compatible
	Elementor Pro: Compatible

== Elementor Pro - Compatibility Tag ==
	
	Dynamic.ooo - Dynamic Content for Elementor: Compatible
				
````

</details>

**Comment by tahmidbintaslim** [comment] 2023-02-07 04:42
I also see this issue in the latest Elementor Version 3.10.2. After editing pages, CSS is not generated until manually go to Tool and Regenerate CSS

**Comment by AdamBedoui** [comment] 2023-02-07 09:59
I'm also facing the same issue on two websites running on Elementor Pro 3.10.3.
Not only we have to manually regenerate CSS & Data in order to apply the styles, but also they roll back to their previous state on  after a while.

**Comment by uroslj** [comment] 2023-02-07 19:46
I'm also experiencing the same issue for a couple of months now. For me, the issue occurs mostly on mobile view when displaying Elementor templates (both "Saved templates" and "Theme builder templates") on pages or custom posts. Even though the templates are styled perfectly inside the Elementor editor using the responsive mode - they often look completely broken on the front end (margins, paddings, fonts, flex-direction, etc. - everything looks all over the place). Regenerating the CSS in Elementor Tools helps get elements back to the defined shape and style, but only for a little while. I usually notice that the styles got broken again a day later. This is something that needs to be resolved with the highest priority because using Elementor becomes kind of pointless if it cannot ensure responsiveness.

**Comment by haydonchurchill** [comment] 2023-02-07 21:12
+1 seems to be getting worse IMO. Now Regenerate CSS is not even working on some single page templates

**Comment by jphansendk** [comment] 2023-02-08 13:20
+1 - Me too

**Comment by mcrowell** [comment] 2023-02-08 14:17
+1 This has been a problem for months.

**Comment by nicholaszein** [comment] 2023-02-08 19:38
Hey everyone, 

Thank you for the feedback! 🙏 

### ❌ While reviewing your report, we noticed it was missing some key pieces of information:

1. We can't reproduce this issue on our end. From the description, it seems like this is being caused by a cache conflict. Sometimes users might think it's not cache related, especially if they don't have a performance optimization plugin installed, but mostly, the server cache is the one responsible for not clearing the cache when a post, page, or template is updated.
2. We see there is a lot going on on your site. Multiple plugins and Elementor add-ons are installed and active. There is a chance of conflict between these plugins, especially Elementor add-ons if they have any integration with Elementor, but might be using deprecated methods. It's crucial to verify if these plugins are not causing any conflict with Elementor before submitting your bug report.

Please follow these steps below and report back so we can ensure this is not caused by 3rd-party software or cache conflict:

- 🔬 **Isolate the problem:** Deactivate all of your plugins (except Elementor/Pro), and temporarily change your WordPress theme to [Hello theme](https://wordpress.org/themes/hello-elementor/). If this solves the problem, gradually activate your plugins and theme one by one, until you spot the conflicting plugin or theme.

- 🕵️ **Validate Your Issue:** If the issue can't be recreated consistently or reproduced on other sites, it's likely not an Elementor bug. In that case, your issue is likely caused by a conflict with something else.

- 🗑️ **Clear / Purge the Cache:** You need to ensure your site, server, or CDN cache is not causing the issue. If you don't have any cache or performance optimization plugin installed, contact your Hosting Provider and ask them to purge/clear temporarily disable the server cache. Then test again.

Without them, we simply can't help. 😕 

### 🧐 Please provide the missing information above so we can troubleshoot your issue faster and better.

Best regards,

Nick

**Comment by JonathanCrossland** [comment] 2023-02-23 12:50
While I appreciate the difficulty in having bugs which only appear when in conjunction with other plugins etc, one would expect you to install the plugins listed in the system info in order to reproduce? The fact that another plugin may be at fault, or that your code may be at fault when executing in conjunction with another plugin, should be your concern?

**Comment by sinanisler** [comment] 2023-03-10 16:02
I am so frustrated for this long-lasting bug

I cant even remember how long ago how many versions already.

**Comment by nicholaszein** [comment] 2023-05-02 04:46
Hello there,

Thank you for the feedback! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
- We cannot guarantee the functionality of 3rd party plugins, only Elementor, and Elementor Pro.
- The issue you're describing is strictly cache related and does not happen if you clear the cache after updating or if you use a cache plugin like WP Rocket, which recognizes when an Elementor document was updated and clears the cache accordingly.

### ✅ What you can do to solve your issue:
- Use an alternative cache solution that clears the cache properly after an update.
- Switch the CSS Print Method to "Internal Embedding" in the Elementor > Settings > Advanced page.
- Follow the instructions in [this article](https://elementor.com/help/changes-dont-appear-online/).

### 👍 For now, that's all we can help with. 

### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for support.

❔ If you have questions, or need guidance, help, or general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) The main Facebook group where all kinds of users come together to help each other.
- [Elementor Academy](https://elementor.com/academy) Learn everything you need to know about using Elementor.
- [Elementor Developers Documentation](https://developers.elementor.com/) Learn everything about our Developer-API.
- [Free Support Forum](https://wordpress.org/support/plugin/elementor) Get help on WordPress.org.

💎 If you have an active [Elementor Pro](https://elementor.com/pro) license you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Kind regards

**Closed by nicholaszein** 2023-05-02 04:46 UTC
Labels: bug, type/design, compatibility/assets, mod*
