### ISSUE TITLE
Need to fix select2 control style.

### ISSUE THREAD

**Issue by mehedidb** [elementor/elementor#10624] opened 2020-02-21 16:42 UTC
Hi,

I am using latest version of Elementor but I am found the issue that the select 2 filed filed size only 30px without selecting any data form select field. please check the issue in select2 field.

Thanks!

**Comment by DeoThemes** [comment] 2020-02-25 04:18
I can confirm that. If no items selected the control is collapsed.

**Comment by mehedidb** [comment] 2020-02-25 04:41
Yes if no item selected it goes to only 30px width.
example:
![Screenshot_1](https://user-images.githubusercontent.com/12911054/75215471-099ce700-57bb-11ea-8d45-b8963f918549.png)

 but when selected some option then it's get width same as content width,
example:
![Screenshot_2](https://user-images.githubusercontent.com/12911054/75215491-18839980-57bb-11ea-80fb-50cc5f1b0296.png)

 and when make the code label_block: true it make full width.
example:
![Screenshot_3](https://user-images.githubusercontent.com/12911054/75215537-44068400-57bb-11ea-88eb-0ea0846782a0.png)

I think you understand the problem.

Thanks!

**Comment by notrealdev** [comment] 2020-03-05 02:09
Need to fix it

**Comment by datfit09** [comment] 2020-03-05 02:12
I also have an error and want to update as soon as possible

**Comment by DorShahar** [comment] 2020-11-08 09:19
Hi everyone, 
We couldn't reproduce this issue.
If the issue continues, please attach more info, prefered a short video. 

Since this issue is a few months old, I'm closing this.

Thanks

**Closed by DorShahar** 2020-11-08 09:19 UTC
Labels: bug
