### ISSUE TITLE
⛔ Email notifications are missing important HTML tags

### ISSUE THREAD

**Issue by finalwebsites** [elementor/elementor#28664] opened 2024-09-10 14:12 UTC
### Prerequisites

- [ ] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [ ] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

Whenever I create a form and use "Email" as form action. The default shortcode [all-fields] for the email message which I send for 99% to the site owner, the mail is not complete. Only the HTML code from the shortcode is included. Tags like <html> or <body> are missing. 

Because of the missing tags, the mail ends up in the spam box very often. Of course it's possible to add the missing tags around the shortcode, but I guess no one will do this :)

### Steps to reproduce

1. Create the form
2. Send the email
3. Check the source code in your mail box
![Screenshot 2024-09-10 om 16 06 29](https://github.com/user-attachments/assets/d3d5e74b-4da1-4e22-b726-289c55c5fd67)
![Screenshot 2024-09-10 om 16 09 04](https://github.com/user-attachments/assets/84e3aebf-4342-442a-bfd5-041fc4b8b69e)

### Expected behavior

The mail should have the missing HTML tags

### Isolating the problem

- [ ] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [ ] This bug happens with the Hello Elementor theme active.
- [ ] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

<details>
<summary>Click to reveal</summary>

````txt


== Server Environment ==
	Operating System: Linux
	Software: nginx/1.18.0
	MySQL version: mariadb.org binary distribution v10.11.8-MariaDB-ubu2004
	PHP Version: 8.1.29
	PHP Memory Limit: 256M
	PHP Max Input Vars: 5000
	PHP Max Post Size: 1024M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.6.1
	Site URL: https://.nl
	Home URL: https://.nl
	WP Multisite: No
	Max Upload Size: 512 MB
	Memory limit: 40M
	Max Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: nl_NL
	Timezone: Europe/Amsterdam
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor Child
	Version: 1.0.1
	Author: Elementor Team
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 3.1.0
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: nl-NL
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36

== Active Plugins ==
	Admin Columns
		Version: 4.7.7
		Author: AdminColumns.com

	Advanced Custom Fields PRO
		Version: 6.3.6
		Author: WP Engine

	Ajax Contact Form
		Version: 1.2.5.1
		Author: Olaf Lederer

	Cleavr Clear Cache
		Version: 1.0
		Author: Cleavr

	Configure SMTP
		Version: 3.5
		Author: Scott Reilly

	Elementor
		Version: 3.23.4
		Author: Elementor.com

	Elementor Blocks for Gutenberg
		Version: 1.1.4
		Author: Elementor.com

	Elementor Pro
		Version: 3.23.3
		Author: Elementor.com

	EO4WP: EmailOctopus for WordPress
		Version: 1.0.2
		Author: Olaf Lederer

	FakerPress
		Version: 0.6.6
		Author: Gustavo Bordoni

	FW iDEAL betalingen
		Version: 1.13.0
		Author: Olaf Lederer

	FW Structured Data
		Version: 1.0.0
		Author: Olaf Lederer

	NinjaFirewall (WP Edition)
		Version: 4.6.1
		Author: The Ninja Technologies Network

	Query Monitor
		Version: 3.16.4
		Author: John Blackbourn

	Redirection
		Version: 5.5.0
		Author: John Godley

	SEOPress
		Version: 8.1.1
		Author: The SEO Guys at SEOPress

	Site Kit by Google
		Version: 1.135.0
		Author: Google

	Smart Slider 3
		Version: 3.5.1.23
		Author: Nextend

	WordPress Importer
		Version: 0.8.2
		Author: wordpressdotorg


== Must-Use Plugins ==
	NinjaFirewall WP (mu-plugin)
		Version: 1.0
		Author: The Ninja Technologies Network


== Gebruik van elementen ==
	
	container : 1
		container : 1
		loop-carousel : 1
	page : 2
		image : 14
		text-editor : 1
	section : 2
		heading : 3
		text-editor : 1
	widget : 0
		heading : 1
	wp-page : 7
		container : 4
		form : 1
		icon-list : 1
		image : 35
		image-carousel : 1
		loop-carousel : 2
		text-editor : 1
	loop-item : 2
		button : 1
		container : 2
		theme-post-excerpt : 2
		theme-post-featured-image : 1
		theme-post-title : 2


== Instellingen ==
	
	cpt_support: post, page
	allow_tracking: yes


== Eigenschappen ==
	Custom Fonts: 0
	Custom Icons: 0

== Integraties ==
	


== Elementor experimenten ==
	Verbeterd laden van CSS: Actief
	Inline lettertype iconen: Actief
	Extra aangepaste breakpoints: Standaard actief
	Flexbox container: Actief
	Raster container: Standaard actief
	Upgrade Swiper bibliotheek: Standaard actief
	Geneste elementen prestaties: Standaard actief
	Geoptimaliseerde laden van besturing: Actief
	Geoptimaliseerde markup: Standaard inactief
	Plugin onboarding: Standaard actief
	Standaard naar nieuwe Thema bouwer: Standaard actief
	Header &amp; footer: Standaard inactief
	Elementor home scherm: Standaard actief
	Editor top balk: Standaard inactief
	Bouwen met AI: Standaard actief
	Landingspagina&#039;s: Inactief
	Geneste elementen: Actief
	Lazy-load achtergrondafbeeldingen: Standaard actief
	Element caching: Actief
	Link in bio: Standaard inactief
	Zwevende knoppen: Standaard inactief
	Elementor editor gebeurtenissen: Standaard inactief
	Weergave voorwaarden: Standaard actief
	Formulierinzendingen: Standaard actief
	Menu: Standaard inactief
	Taxonomiefilter: Standaard actief
	Zoeken: Standaard inactief


== Log ==
	


== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatibel

== Elementor Pro - Compatibility Tag ==

````

</details>

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by nicholaszein** [comment] 2024-09-11 23:41
Hi, @finalwebsites,

Thank you for reaching out! 🙏 

### ⛔ 🚀 This is more of a Feature Request, not a bug. The feature you're referring to is not yet supported.

Allow me to explain:

Elementor Form Email and Email2 Message fields only send text messages. This includes the field shortcodes. If you want to add HTML to your emails you can, but these will not be added by Elementor. This is the intended behavior.

This is more of a Missing feature, not a bug. Therefore I'm closing this issue.

If you think this should be an Elementor feature, please cast your ⬆️ **Upvote** in one of the Feature Requests [here](https://github.com/orgs/elementor/discussions?discussions_q=is%3Aopen+email+html+template) and we will consider it in the future if there is enough demand (votes) from other users.

Kind regards

**Closed by nicholaszein** 2024-09-11 23:41 UTC
Labels: product/pro, widget/forms, widget/form/actions, mod*, mod/r*, mod/i*
