### ISSUE TITLE
⛔ 🐞Bug Report: Elementor Pro Form - Content Type HTML - Blank Submission

### ISSUE THREAD

**Issue by Geenmen** [elementor/elementor#20629] opened 2022-12-06 17:30 UTC
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

I am on the latest version of elementor pro. The issue that I am having is that upon submission none of my inputs that I wrote appear in the submission section on wordpress or are forwarded to my email. Everything comes in blank.
I am using the Form element and the HTML Content type.

I did find a similar post on [wordpress's website](https://wordpress.org/support/topic/custom-html-field-form-not-being-sent/) however it looks like that was solved privately.

If you need I can provide the HTML I wrote up.

### Steps to reproduce

1.On a wordpresssite add the Form Element
2.Set content type to HTML
3. Write in an input
4. Submit a test of the form
5. In wordpress elementor submissions there should be a blank submission.
![Blank_Submission_Screenshot](https://user-images.githubusercontent.com/26076471/205979800-480ba0cc-1dda-4918-a522-e47a7cfc06d5.PNG)

### Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

[system-info-sbcccorp.com-06-12-2022.txt](https://github.com/elementor/elementor/files/10168816/system-info-sbcccorp.com-06-12-2022.txt)

**Comment by Geenmen** [comment] 2022-12-06 18:08
>

**Comment by Geenmen** [comment] 2022-12-06 18:08
I have gone through and deactivated all the plugins except elementor -> Unfortunately the issue persists.
![Blank_Submission_Screenshot2](https://user-images.githubusercontent.com/26076471/205987850-d30bee20-d331-43f2-a9d8-fc58d9bb9881.PNG)
As for the updates I am on the latest versions that the auto-update prompted me to do.
![No-Updates](https://user-images.githubusercontent.com/26076471/205988094-a34de29d-2cb6-4962-a82b-e425e75bfd97.PNG)
I had assumed this was a bug. My apologies in the future I will definitely reach out to the support sections.

**Comment by Geenmen** [comment] 2022-12-07 15:42
Thanks for the follow up, I will go and update the Elementor Versions today and see if the issue is fixed.
As for how I configured the form please see attached: 
Please excuse the messy HTML I have no formal training and am making due with what I have figured out and learned so far.
[Agreement Form.txt](https://github.com/elementor/elementor/files/10177507/Agreement.Form.txt)
![Form Information_1-1](https://user-images.githubusercontent.com/26076471/206223494-26eca3ef-1d3e-44b0-a1ca-f9544c013a7c.PNG)
![Form Information_1-2](https://user-images.githubusercontent.com/26076471/206223495-b35888f2-4f5d-4483-9954-1cc9e4ef4589.PNG)
Let me know if this is everything you were looking for.

**Comment by Geenmen** [comment] 2022-12-12 14:22
@nicholaszein Is there documentation that I can read up on for using the HTML content type in the Form? I dont want to waste your time if it is simply me misusing the element.
I did find this [page](https://developers.elementor.com/docs/form-fields/add-new-field/)
However it seems that is in php and not in the form...Please Advise.

**Comment by nicholaszein** [comment] 2022-12-31 05:22
Hello @Geenmen,

thank you for the feedback, and please apologies for taking so long to get back to you. I wasn't able to respond sooner. 🙏 

Your issue is that you're adding a form inside a form field, and it won't work as you intend because it's an invalid implementation (a form inside a form).

Unfortunately, what you're trying to do is not possible with the Elementor form, and we do not support this type of customization. The HTML field is meant to be used to add only textual content, not to add form fields. They can't be parsed or validated in this way. What you want to do would require CSS customization instead. For each field, you would add a proper field to the form, and then move them around to be placed where you want. Honestly, it's not recommended to do this anyway, since it's not accessible and would probably break the layout on different screens.

What you can try to find is a dedicated form plugin with an option to output the form as a PDF, where you can customize how the PDF would look, and place the fields exactly where you want. This goes way beyond what Elementor Forms were meant to be used for. You might find an addon that does what you want though. Check perhaps Dynamic.ooo.

I hope you can find a solution to your issue. For now, that's all I can help you with. I'm closing this issue as not reproducible.

Kind regards

**Closed by nicholaszein** 2022-12-31 05:22 UTC
Labels: component/forms/actions, component/submissions
