### ISSUE TITLE
⛔ 🔗 ♿ 🐞 Bug Report: Toggle PageSpeed Insights Marked as Completed, But Still Giving Error (Duplicate of #22826)

### ISSUE THREAD

**Issue by Kubot12** [elementor/elementor#22913] opened 2023-06-27 10:33 UTC
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

This is the issue > https://github.com/elementor/elementor/issues/14371
It is marked as closed because it is completed.

But, I have updated to the latest version of Elementor and Elementor Pro. I have cleared all cache. The issue still persists. 

The completed comment mentions the accordion widget. I am using the toggle widget. 

Was this fixed for toggle widget too?

### Steps to reproduce

1. Go here > https://pagespeed.web.dev/analysis/https-www-symetriarecovery-com-locations-illinois-rehabs-chicago-suboxone-clinic/gta5xd32oj?form_factor=mobile
2. Scroll down to SEO section > Error: Links are not crawlable 

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

<details>
<summary>System Info</summary>

````txt


					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Percona Server (GPL), Release '46', Revision 'e1995a8bb71' v5.7.42-46
	PHP Version: 8.0.28
	PHP Memory Limit: 512M
	PHP Max Input Vars: 10000
	PHP Max Post Size: 100M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.2.2
	Site URL: https://www.symetriarecovery.com
	Home URL: https://www.symetriarecovery.com
	WP Multisite: No
	Max Upload Size: 50 MB
	Memory limit: 40M
	Max Memory limit: 512M
	Permalink Structure: /blog/%postname%/
	Language: en-US
	Timezone: 0
	Admin Email: [REDACTED]
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.7.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36

== Active Plugins ==
	Advanced Custom Fields
		Version: 6.1.6
		Author: WP Engine

	Akismet Anti-Spam: Spam Protection
		Version: 5.2
		Author: Automattic - Anti Spam Team

	Code Snippets
		Version: 3.4.0
		Author: Code Snippets Pro

	Comment Form Inline Errors
		Version: 1.0.2
		Author: latorante

	Elementor
		Version: 3.14.1
		Author: Elementor.com

	Elementor Pro
		Version: 3.14.1
		Author: Elementor.com

	Force Refresh
		Version: 2.6.1
		Author: Jordan Leven

	If-So
		Version: 1.6.1.2
		Author: If So Plugin

	Lightweight Subscribe To Comments
		Version: 1.5.8
		Author: Isabel Castillo

	Link Whisper
		Version: 2.2.7
		Author: Link Whisper

	Perfmatters
		Version: 2.1.1
		Author: forgemedia

	QueryHunter
		Version: 3.7
		Author: Joe Davies

	Rank Math SEO
		Version: 1.0.117.1
		Author: Rank Math

	Rank Math SEO PRO
		Version: 3.0.31
		Author: Rank Math

	SVG Support
		Version: 2.5.5
		Author: Benbodhi

	WP Rocket
		Version: 3.14
		Author: WP Media

	WP Store Locator
		Version: 2.2.237
		Author: Tijmen Smit


== Must-Use Plugins ==
	Asset CleanUp Pro: Plugin Filtering
		Version: 1.0
		Author: Gabriel Livan

	Force Strong Passwords - WPE Edition
		Version: 1.8.0
		Author: Jason Cosper

	ManageWP - Worker Loader
		Version: 
		Author: GoDaddy

	WP Engine Cache Plugin
		Version: 1.1.3
		Author: WP Engine

	WP Engine Seamless Login Plugin
		Version: 1.6.1
		Author: WP Engine

	WP Engine Security Auditor
		Version: 1.0.10
		Author: wpengine

	WP Engine System
		Version: 5.0.1
		Author: WP Engine


== Features ==
	Custom Fonts: 0
	Custom Icons: 0

== Integrations ==
	


== Elementor Experiments ==
	Optimized DOM Output: Active
	Improved Asset Loading: Active
	Improved CSS Loading: Active by default
	Inline Font Icons: Active
	Accessibility Improvements: Active
	Additional Custom Breakpoints: Active
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Inactive
	Upgrade Swiper Library: Inactive by default
	Grid Container: Inactive
	Default to New Theme Builder: Active by default
	Hello Theme Header & Footer: Active by default
	Editor Top Bar: Inactive by default
	Landing Pages: Active
	Nested Elements: Inactive by default
	Nested Accordion: Inactive by default
	Lazy Load Background Images: Active
	Global Style Guide: Inactive by default
	Page Transitions: Active by default
	Notes: Active by default
	Loop: Active by default
	Form Submissions: Active by default
	Scroll Snap: Active by default
	Menu: Inactive by default


== Log ==
	
Log: showing 20 of 252023-06-07 12:36:43 [info] elementor::elementor_updater Started 
2023-06-07 12:36:43 [info] Elementor/Upgrades - _on_each_version Start  
2023-06-07 12:36:43 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.13.2',
  'to' => '3.13.4',
)]
2023-06-07 12:36:46 [info] Elementor/Upgrades - _on_each_version Finished 
2023-06-07 12:36:46 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.13.2',
  'to' => '3.13.4',
)]
2023-06-07 12:37:07 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.13.1',
  'to' => '3.13.2',
)]
2023-06-07 12:37:11 [info] elementor-pro::elementor_pro_updater Started 
2023-06-07 12:37:11 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-06-07 12:37:11 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-06-07 12:37:11 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.13.1',
  'to' => '3.13.2',
)]
2023-06-27 10:10:28 [info] elementor::elementor_updater Started 
2023-06-27 10:10:28 [info] Elementor/Upgrades - _on_each_version Start  
2023-06-27 10:10:28 [info] Elementor/Upgrades - _on_each_version Finished 
2023-06-27 10:10:28 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.13.4',
  'to' => '3.14.1',
)]
2023-06-27 10:10:28 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.13.4',
  'to' => '3.14.1',
)]
2023-06-27 10:10:40 [info] elementor-pro::elementor_pro_updater Started 
2023-06-27 10:10:40 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-06-27 10:10:40 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-06-27 10:10:40 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.13.2',
  'to' => '3.14.1',
)]
2023-06-27 10:10:40 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.13.2',
  'to' => '3.14.1',
)]

JS: showing 13 of 13JS: 2023-05-16 18:02:15 [error X 27][https://www.symetriarecovery.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.13.2:3:1097282] Cannot read properties of null (reading 'getBoundingClientRect') 
JS: 2023-05-16 18:37:04 [error X 55][https://www.symetriarecovery.com/wp-content/plugins/elementor/assets/js/common-modules.min.js?ver=3.13.2:2:55595] Model.isValidChild() should be implemented, please provide 'isValidChild' functionality. 
JS: 2023-05-17 12:27:40 [error X 203][https://www.symetriarecovery.com/wp-content/plugins/elementor/assets/js/frontend-modules.min.js?ver=3.13.2:2:8297] Cannot read properties of undefined (reading 'attributes') 
JS: 2023-05-18 13:26:03 [error X 1][https://temp123test.wpengine.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.13.2:3:208223] C.ui.sync.removeClass is not a function 
JS: 2023-05-18 19:29:39 [error X 26][https://temp123test.wpengine.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.13.2:3:795450] Cannot read properties of undefined (reading 'localized') 
JS: 2023-05-21 21:41:12 [error X 1][https://temp123test.wpengine.com/wp-content/plugins/elementor/assets/lib/pickr/pickr.min.js?ver=1.5.0:2:18455] Cannot read properties of null (reading 'inline') 
JS: 2023-05-22 18:18:10 [error X 2][https://temp123test.wpengine.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.13.2:3:681852] this.model.isValidChild is not a function 
JS: 2023-05-22 22:28:04 [error X 1][https://temp123test.wpengine.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.13.2:3:497512] B.tipsy is not a function 
JS: 2023-05-26 17:22:46 [error X 1][https://temp123test.wpengine.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.13.2:3:794943] Cannot read properties of undefined (reading 'toLowerCase') 
JS: 2023-06-01 18:17:44 [error X 49][https://temp123test.wpengine.com/wp-content/plugins/elementor/assets/js/web-cli.min.js?ver=3.13.2:3:82314] Data commands: `` not found. 
JS: 2023-06-14 19:05:33 [error X 281][https://www.symetriarecovery.com/wp-content/plugins/elementor-pro/assets/js/frontend.min.js?ver=3.13.2:2:22137] Cannot read properties of undefined (reading 'handlers') 
JS: 2023-06-25 11:01:12 [error X 1][https://www.symetriarecovery.com/wp-includes/js/jquery/jquery.min.js?ver=3.6.4:2:31823] ElementorScreenshotConfig is not defined 
JS: 2023-06-25 16:32:04 [error X 3][https://www.symetriarecovery.com/wp-content/plugins/elementor-pro/assets/js/frontend.min.js?ver=3.13.2:2:22111] elementorModules.frontend is undefined 

PHP: showing 5 of 5PHP: 2023-05-16 18:46:31 [warning X 38][/nas/content/live/symetriarecpro/wp-content/plugins/elementor/core/common/modules/ajax/module.php::175] Undefined array key "data" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-05-18 13:04:12 [warning X 2][/nas/content/live/temp123test/wp-content/plugins/elementor/core/kits/manager.php::280] Attempt to read property "post_status" on null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-05-18 13:13:16 [warning X 1][/nas/content/live/temp123test/wp-content/plugins/elementor/core/base/document.php::1602] Undefined array key "thumbnail" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-05-26 17:21:39 [warning X 18][/nas/content/live/temp123test/wp-content/plugins/elementor/core/page-assets/data-managers/font-icon-svg/font-awesome.php::50] Trying to access array offset on value of type null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-05-26 18:19:56 [warning X 1][/nas/content/live/temp123test/wp-content/plugins/elementor-pro/modules/query-control/module.php::386] Undefined array key "display" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]



== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatible

== Elementor Pro - Compatibility Tag ==
	

				

````

</details>

**Comment by nicholaszein** [comment] 2023-06-27 17:55
Hello @Kubot12!

Thank you for your submission! 🙏 

### 🔗 🐞 This issue is a Duplicate of #22826

Which is on the same subject. 

The changes were applied for both the toggle and the accordion widgets. Please see [this comment](https://github.com/elementor/elementor/issues/22826#issuecomment-1604736951) to understand our position on this issue.

For this reason, I'm closing this thread and 🔃 **Merging** it with the original, so we can have all the discussions in one location, and deal with it more efficiently.

Feel free to continue the conversation there. 😉 

### 🔍 Please, in the future, remember to check if there isn't any thread similar to yours already opened. 

Kind regards

**Closed by nicholaszein** 2023-06-27 17:55 UTC
Labels: type/accessibility, type/seo, component/code, component/accordion, mod*
