### ISSUE TITLE
New Template Display Condition - User Role

### ISSUE THREAD

**Issue by paullawleyjones** [elementor/elementor#11908] opened 2020-07-21 07:44 UTC
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
I would like to be able to display Theme Builder templates according to User Role.

**Describe the solution you'd like**
A new Template Display Condition of User Role.

**Describe alternatives you've considered**
Adding all Users in the User Role to the Display Conditions for a template.
Adding all Posts by Users in a User Role to a specific WP Category, and adding a Display Condition for that Category. **[This is the solution I'm currently using.]**

**Additional context**
For example, the Guest Author User Role would display a template with a Guest Author bio box, and a fundraising campaign from a Campaign Manager User Role (from wpcharitable.com) would display another template with an organization information box.

**Comment by arielk** [comment] 2020-07-22 16:34
Duplicate of #4404

**Closed** 2020-07-22 16:34 UTC
