### ISSUE TITLE
🚀 Feature Request: Conditional Logic for Elementor Form Steps

### ISSUE THREAD

**Issue by garteth** [elementor/elementor#18451] opened 2022-04-15 15:02 UTC
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

Currently there is no conditional logic for steps meaning that you have to set a finite number of steps, even if you don't need them all.

### Describe the solution you'd like

Conditional logic for steps would help if you do not need to show all of the steps.

An example is my own use case.

I have a membership site. I have a product which allows for up to 4 licensees.

I start with a number field asking how many licenses the user actually wants to register (between 1 and 4). 

Depending on this number, I want to show a step for each licensees details e.g.:

First name
Last name
Email

If the user enters 1 licensee, there will be one additional step. If they enter 2, there will be two additional steps. If all 4 are used, there will be five steps in total. The form will then be submitted.

### Describe alternatives you've considered

I have had to go with using the existing Elementor form mixes with Dynamic.ooo, and show fields depending on the number entered into the initial number field.

This does still achieve what I want but I feel as though having steps would be better for the user, and more easy to follow.

**Comment by rami-elementor** [comment] 2022-04-18 23:10
Duplicate of #2638

**Closed by rami-elementor** 2022-04-18 23:10 UTC
Labels: request/feature, product/pro, component/forms
