### ISSUE TITLE
All widgets become images

### ISSUE THREAD

**Issue by jimyaghi** [elementor/elementor#17304] opened 2021-12-27 12:21 UTC
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description
In recent versions of Elementor, when i drag new widgets into the page, they all turn into images and report errors in the backend. i have tried to disable all plugins except for Elementor and the issue persists. 

it appears to be an issue with the new "drag image from desktop" functionality where Elementor can't seem to distinguish between a widget or image being dragged in.  It also appears to be an issue ONLY in Chrome, because in Firefox, the issue is not present.

## Steps to reproduce
In a new Elementor page, drag a new Heading widget into the editor (for example). It automatically turns into an image widget.
 

## Isolating the problem

- [x] This bug happens with only Elementor plugin active.
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment
https://pastebin.com/6wUXBBxD

**Comment by Sebastiangperez** [comment] 2021-12-28 15:11
I have the same issue, this happened in the free version.

**Comment by jimyaghi** [comment] 2021-12-29 10:07
i have identified where in the code this happens:

It seems here event.originalEvent.dataTransfer.files is populated for some reason:

https://github.com/elementor/elementor/blob/77fb8437c16ce635ef4ad8b9c662e39e11efdf83/assets/dev/js/editor/utils/jquery-html5-dnd.js#L335

then the condition checks here to see if we're dragging a file:
https://github.com/elementor/elementor/blob/77fb8437c16ce635ef4ad8b9c662e39e11efdf83/assets/dev/js/editor/utils/jquery-html5-dnd.js#L345

and it thinks we are. but we're not.

**Comment by jimyaghi** [comment] 2021-12-29 10:54
Note, this issue does not exist in Firefox. It is only in Chrome that i am experiencing this.

**Comment by Sebastiangperez** [comment] 2021-12-30 15:21
They break the plugin, i wonder how many people had the same problem.

**Comment by jimyaghi** [comment] 2022-01-01 12:20
it's weird that no one else seems to be complaining although it's a major bug that makes the plugin unusable. i too had to downgrade to 3.4.8. i would submit a pull request but i couldn't figure out where the issue was. they did some recent changes to allow dragging images in from the desktop, but this seems to be clashing with dragging components from the element toolbar. 

> They broke the plugin, i wonder how many people had the same problem. Maybe they must ditch Jquery and change to vanilla.. The bug started in version 3.5 , i rollback to version 3.4.8 and everything works now.

**Comment by Sebastiangperez** [comment] 2022-01-01 13:55
> it's weird that no one else seems to be complaining although it's a major bug that makes the plugin unusable

Maybe everyone uses Firefox??? yes , its very strange that no one have the same bug , what version of Chrome do you have? are you running a Linux as your main OS ?

**Comment by jimyaghi** [comment] 2022-01-02 15:28
Version 96.0.4664.110 (Official Build) (64-bit) yes i use Ubuntu as my main OS.

oddly, today i can drag headings in without any issues. i didn't upgrade anything. i did mess with experiment settings turning on and off some settings but i don't know if that is the reason. it works though all of a sudden and I'm happy but very wary.

**Comment by Sebastiangperez** [comment] 2022-01-02 15:36
Same version until the last digits, and im using PopOs. 
Now works ? i will try .

**Comment by jimyaghi** [comment] 2022-01-02 15:51
Here's the experiment settings i've got. give these a try as well:

![image](https://user-images.githubusercontent.com/15869425/147881241-a7771969-7fbd-4d6a-9347-29b9b7a47ce9.png) 
![image](https://user-images.githubusercontent.com/15869425/147881251-141faddc-4323-40eb-9438-dc41378a79e3.png)
![image](https://user-images.githubusercontent.com/15869425/147881259-37b52b0f-3594-4e01-bd0e-9856847a8c74.png)

**Comment by Sebastiangperez** [comment] 2022-01-02 17:17
Are you using the pro version ??

**Comment by jimyaghi** [comment] 2022-01-02 17:26
yeah i am

**Comment by Sebastiangperez** [comment] 2022-01-02 17:31
Ahh , ok, because im using the free version and i'm still having the same issue . I installed the dev version, now if you drag a widget , besides the image, inserts the actual widget on top. 
I will try to do a clean install of wordpress. 
Did you try , maybe WP Adminfy ? i thought that was the problem but i don't think that was the issue.

**Comment by Sebastiangperez** [comment] 2022-01-02 17:40
I just make a clean install of wordpress, and i have only one plugin , elementor , and i have the same issue

**Comment by jimyaghi** [comment] 2022-01-02 18:35
i wish i knew what fixed it on my end. i also when i tried with all plugins off it still failed. even with PRO off. but now all of a sudden it just works and nothing was updated. I'm even using the previous release of Elementor which started the problems and I've not yet upgraded to the very latest.

**Comment by Sebastiangperez** [comment] 2022-01-03 13:28
Maybe they upgrade the pro version alongside with the free version. 
Do you have any plugin or extension enable in chrome ?

**Comment by jimyaghi** [comment] 2022-01-04 10:56
yeah i do, there's several. lastpass, vimeo screen record, loom, go full-page, google docs to name a few

**Comment by jimyaghi** [comment] 2022-01-04 10:57
> I just make a clean install of wordpress, and i have only one plugin , elementor , and i have the same issue Update : Works on incognito mode.
> 
> This is the error that im getting in the console common.min.js?ver=3.5.3:2 POST http://starter-wp.test/wp-json/wp/v2/media?uploadTypeCaller=elementor-wp-media-upload 400 (Bad Request)

this error is because it's trying to do an image upload for a non-existent image. it's not the cause of the issues. it's a symptom only. you might try clearing cache, fresh install of chrome, or even a new chrome profile. perhaps there's something there?

**Comment by Gabugbuster** [comment] 2022-01-05 10:24
@Sebastiangperez Are you using a premade template or building from scratch? Does it work fine when you disable all your browser extensions? I am trying to reproduce the issue.

**Comment by Sebastiangperez** [comment] 2022-01-05 12:49
> @Sebastiangperez Are you using a premade template or building from scratch? Does it work fine when you disable all your browser extensions? I am trying to reproduce the issue.

No , im just using Hello Theme from elementor , and i only have 3 extensions , uBlock Origin , Bitwarden and Wappalyzer, all 3 disabled , also i have Vue Dev tools , but if this website do not have vuejs , it wont be enabled. 
Chrome Version 96.0.4664.45 
Wordpress version , Latest. 
Elementor , Latest.
No other plugin installed.

**Comment by Sebastiangperez** [comment] 2022-01-05 22:55
Ok , i just upgrade Chrome to 97 and i do not have the error anymore , but maybe there is something with that version that causes the error.

**Comment by jimyaghi** [comment] 2022-01-06 06:14
It seems like something was cached to be honest. Your upgrade may have
cleared that cache. Perhaps that's what happened with me too.

**Comment by jimyaghi** [comment] 2022-01-07 08:07
this might be an issue with Chrome. i was using Gutenberg editor and dragged a widget into a group and it did the same thing where it appeared to be trying to upload an image. check out the screenshot

![image](https://user-images.githubusercontent.com/15869425/148512280-aa2be904-0dfe-4bd5-b680-3f0ef29f34f5.png)

**Comment by jimyaghi** [comment] 2022-01-07 08:20
and now the issue is back in my Elementor

**Comment by Sebastiangperez** [comment] 2022-01-07 12:49
What version of Chrome are you using ?

**Comment by jimyaghi** [comment] 2022-01-07 13:02
> What version of Chrome are you using ?

Version 96.0.4664.110 (Official Build) (64-bit)

**Comment by Sebastiangperez** [comment] 2022-01-07 13:03
Upgrade to 97 , i just did that and worked.

**Comment by rami-elementor** [comment] 2022-03-08 09:46
Closing issue. Looks like it's a browser bug, not Elementor bug.

**Closed by rami-elementor** 2022-03-08 09:46 UTC
Labels: bug
