### ISSUE TITLE
⛔ 🐞 Bug Report: 3.12 colors of Elementor user interface changed, poor contrast, confusing

### ISSUE THREAD

**Issue by dbfischer** [elementor/elementor#21840] opened 2023-03-30 10:36 UTC
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Hi, after updating to Elementor 3.12 Pro the colors in the backend (user interface) are different with poor contrast. Widgets are now white on white background which was grey before. I have noticed this on several installations. Buttons and the borders of the elements on the right side are all pink now. Before the borders were blue, the columns gray ... Now everything is pink, very confusing.

Please change back to the previous colors.

### Steps to reproduce

It happens on all Elementor (Pro) installations which I updated to 3.12.
It is on a new installation with only Elementor 3.12 with Hello Theme and no plugins.
So it's easy to reproduce.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

<details>
<summary>System Info</summary>

````txt


					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Percona Server (GPL), Release '15', Revision 'a558ec2' v8.0.25-15
	PHP Version: 8.1.13
	PHP Memory Limit: 256M
	PHP Max Input Vars: 1500
	PHP Max Post Size: 32M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.2
	Site URL: https://www.immoboerse-ak-ff.de
	Home URL: https://www.immoboerse-ak-ff.de
	WP Multisite: No
	Max Upload Size: 32 MB
	Memory limit: 40M
	Max Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: de-DE
	Timezone: Europe/Berlin
	Admin Email: p640046@wordpress.p640046.webspaceconfig.de
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.7.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: de_DE
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/111.0

== Active Plugins ==
	Elementor
		Version: 3.12.0
		Author: Elementor.com


== Must-Use Plugins ==
	Elementor Safe Mode
		Version: 1.0.0
		Author: Elementor.com


== Elementor-Experimente ==
	Optimierte DOM Ausgabe: Standardmäßig aktiviert
	Verbessertes Laden von Assets: Standardmäßig aktiviert
	Verbessertes Laden von CSS: Standardmäßig aktiviert
	Inline-Schriftarten-Symbole: Standardmäßig deaktiviert
	Verbesserungen der Zugänglichkeit: Standardmäßig aktiviert
	Zusätzliche benutzerdefinierte Breakpoints: Standardmäßig aktiviert
	admin_menu_rearrangement: Standardmäßig deaktiviert
	Flexbox Container: Standardmäßig deaktiviert
	Upgrade Swiper Library: Standardmäßig aktiviert
	Hello Theme Header & Footer: Standardmäßig aktiviert
	Editor Top Bar: Standardmäßig deaktiviert
	Startseiten: Standardmäßig aktiviert
	Nested Elements: Standardmäßig deaktiviert
	Lazy Load Background Images: Standardmäßig deaktiviert


== Protokoll ==
	
JS: showing 1 of 1JS: 2023-03-29 16:34:26 [error X 2][https://www.immoboerse-ak-ff.de/wp-content/plugins/elementor/assets/js/frontend.min.js?ver=3.12.0:2:30905] elementor.settings.page is undefined 



== Elementor - Compatibility Tag ==
	

				

````

</details>

**Comment by frm1001xplrr** [comment] 2023-03-31 08:25
+1 same problem here in Dark Mode.
I have cleared cache. 

Even if I tell you that I've highlighted "100" in the Margin section, you can't tell which "100" i'm talking about (were it not for the arrows in the input box): 
![image](https://user-images.githubusercontent.com/34400103/229065979-dc8cc440-20dc-43c4-a86c-fdadcaed6015.png)

But I have: 
![image](https://user-images.githubusercontent.com/34400103/229066327-56314bc8-52cd-4430-8610-9e630709f01b.png)

It is super frustrating and should be fixed asap.

**Comment by dbfischer** [comment] 2023-03-31 08:28
As you can see in screenshot, everything is pink now and the widget zone ist white with no gray background.
On your homepage https://elementor.com/ you can see in the demo how the perfect colors were until the new version. Sections blue, colums gray etc.
![Elementor-pink-colors](https://user-images.githubusercontent.com/15387379/229067675-2390f389-57b5-4fc0-81c7-05e3d31678e5.jpg)

**Comment by nicholaszein** [comment] 2023-03-31 11:47
Hi @dbfischer,

Thank you for reaching out! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
This is the new Colors Scheme of the Elementor editor, and the colors you are seeing are not a bug, they are part of our efforts to improve accessibility on our UI.

We are still gathering user feedback, and these colors might be tweaked.

### 👍 For now, that's all we can help with. 

If you think this is still an issue caused by Elementor, please feel free to open a new 🐞 [Bug Report](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml).

### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for support.

❔ If you have questions, or need guidance, help, or general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) The main Facebook group where all kinds of users come together to help each other.
- [Elementor Academy](https://elementor.com/academy) Learn everything you need to know about using Elementor.
- [Elementor Developers Documentation](https://developers.elementor.com/) Learn everything about our Developer-API.
- [Free Support Forum](https://wordpress.org/support/plugin/elementor) Get help on WordPress.org.

💎 If you have an active [Elementor Pro](https://elementor.com/pro) license you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Kind regards

**Closed by nicholaszein** 2023-03-31 11:47 UTC
Labels: bug, component/editor, type/design

**Comment by nicholaszein** [comment] 2023-03-31 11:49
Hello @frm1001xplrr,

> +1 same problem here in Dark Mode. I have cleared cache. (...)
> 
> It is super frustrating and should be fixed asap.

What you've reported has already been identified, and will be fixed in a future version. But it's not related to this issue.

Thanks
