### ISSUE TITLE
⛔ 🔗 🚀 Feature Request: Loop Grid - "No More Posts Message" Is not working (Related to #20390)

### ISSUE THREAD

**Issue by Michaelgimii** [elementor/elementor#20389] opened 2022-11-13 19:26 UTC
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Hi elementor team.

It seems that there are two very important bugs in the loop builder.

1- In the Loop builder, the Custom Messages section will not be accessible until pagination (infinit scroll) is enabled. In fact, in the Loop builder, the Custom Messages section is not added in the right place at all. Custom Messages is an essential feature and should not depend on pagination. **Rather, it should always be available, even if pagination is not enabled.**

2- In the loop widget, if Custom Messages is enabled, it doesn't work. In the following, I will explain the method of its reproduction.

### Steps to reproduce

**bug 1 reproduce**

- Add the loop builder widget.
- In the settings of this widget, you will not find the Custom Messages option.
- After activating infinite scroll, this section will be added.

**bug 2 reproduce**

- Add the loop widget in archive template.
- After activating infinite scroll, activate the Custom Messages option.
- View a post category that has no posts in it.
- Here, the desired custom message is not displayed. This is definitely a problem.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

[system-info-localhost-26-10-2022.txt](https://github.com/elementor/elementor/files/9998033/system-info-localhost-26-10-2022.txt)

**Comment by nicholaszein** [comment] 2022-11-14 09:45
Hey @Michaelgimii!

Thank you so much for bringing this to our attention! 🙏 

We will look into changing this option to make it always available since sometimes there might be situations where there won't be any posts to show.

I redacted your second report though. Sorry about that. We can't track two issues in a single thread. Please submit a new issue. 🙏 

Best regards

**Comment by nicholaszein** [comment] 2022-11-16 16:14
Hey @Michaelgimii!

I wanted to update you on this issue. This indeed is not a bug. We are talking about two different things here. The _"No more posts"_ message is an option tailored only for _Infinite Scroll_ and _Load on Click_ pagination options. It wasn't meant to be used to indicate that there are _"No Posts Found"_ in the query. This is a feature that has not been added yet and will be added in the future.

For now, we are focusing on making the Loop Builder compatible with WooCommerce. These features will be added in a future phase.

This was requested in your other issue #20390. And for this reason, I'm closing this one and 🔃 Merging it with the other one, which is a proper request for this feature.

Best regards,

Nick

**Closed by nicholaszein** 2022-11-16 16:14 UTC
Labels: request/enhancement, component/loop-builder
