### ISSUE TITLE
⛔ Carousel Infinite Scroll cannot be turned off

### ISSUE THREAD

**Issue by bnovak99** [elementor/elementor#25744] opened 2024-04-15 14:13 UTC
### Prerequisites

- [X] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [X] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

Using the Carousel widget, I created a carousel with three slides. I have the carousel set to autoplay with infinite scroll turned off. When I view this on the frontend the carousel plays continuously instead of stopping after the last slide. I tried this with the other carousel widgets Loop Carousel, Image Carousel, Media Carousel, Slide Carousel, Testimonial Carousel. Only the Slide Carousel could infinite scroll be turned off.

![carousel](https://github.com/elementor/elementor/assets/25965963/089cc5b3-579f-4009-b584-03a2cc68019f)

### Steps to reproduce

1. Add a carousel using the carousel widget
2. Add slides to the carousel
3. Set slides on display to 1
4. Set to autoplay
5. Turn off infinity Scroll

### Expected behavior

The carousel should play when the page loads and stop after showing the last slide.

### Isolating the problem

- [x] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [x] This bug happens with the Hello Elementor theme active.
- [x] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

<details>
<summary>Click to reveal</summary>

````txt

== Server Environment ==
	Operating System: Linux
	Software: nginx
	MySQL version: Percona Server (GPL), Release '28', Revision '47601f19'$ v8.0.36-28
	PHP Version: 8.2.14
	PHP Memory Limit: 512M
	PHP Max Input Vars: 10000
	PHP Max Post Size: 100M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.5.2
	Site URL: https://topfoxmarkedev.wpenginepowered.com
	Home URL: https://topfoxmarkedev.wpenginepowered.com
	WP Multisite: No
	Max Upload Size: 50 MB
	Memory limit: 40M
	Max Memory limit: 512M
	Permalink Structure: /%postname%/
	Language: en_US
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: Top Fox Marketing
	Version: 2.0.0
	Author: Top Fox Marketing
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 3.0.1
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: en-US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 3.20.4
		Author: Elementor.com

	Elementor Pro
		Version: 3.20.3
		Author: Elementor.com


== Must-Use Plugins ==
	Force Strong Passwords - WPE Edition
		Version: 1.8.0
		Author: Jason Cosper

	WP Engine Cache Plugin
		Version: 1.3.0
		Author: WP Engine

	WP Engine Seamless Login Plugin
		Version: 1.6.1
		Author: WP Engine

	WP Engine Security Auditor
		Version: 1.1.1
		Author: wpengine

	WP Engine System
		Version: 5.0.1
		Author: WP Engine


== Elements Usage ==
	
	footer : 1
		button : 1
		container : 6
		heading : 3
		image : 6
		nav-menu : 2
		text-editor : 1
	header : 1
		button : 1
		container : 4
		nav-menu : 1
		theme-site-logo : 1
	wp-page : 1
		container : 8
		heading : 4
		image-carousel : 1
		loop-carousel : 1
		media-carousel : 1
		nested-carousel : 1
		slides : 1
		testimonial-carousel : 1
		text-editor : 3
	loop-item : 1
		container : 1
		theme-post-content : 1
		theme-post-title : 1


== Settings ==
	
	cpt_support: post, page
	disable_color_schemes: yes
	disable_typography_schemes: yes
	allow_tracking: yes
	font_display: swap


== Features ==
	Custom Fonts: 1
	Custom Icons: 0

== Integrations ==
	


== Elementor Experiments ==
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Active by default
	Additional Custom Breakpoints: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active by default
	Upgrade Swiper Library: Active
	Grid Container: Inactive
	Default to New Theme Builder: Active by default
	Hello Theme Header &amp; Footer: Active by default
	Editor Top Bar: Active
	Optimized Gutenberg Loading: Active by default
	Build with AI: Inactive
	Landing Pages: Active by default
	Nested Elements: Active
	Lazy Load Background Images: Inactive by default
	Optimize Image Loading: Active by default
	Pages Panel: Inactive by default
	Notes: Inactive
	Display Conditions: Active by default
	Form Submissions: Active by default
	Menu: Active
	Taxonomy Filter: Active by default


== Log ==
	
PHP: showing 2 of 2PHP: 2024-04-12 14:07:52 [notice X 20][../wp-content/plugins/elementor/includes/base/controls-stack.php::228] hexdec(): Passing null to parameter #1 ($hex_string) of type string is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-04-12 15:55:21 [warning X 5][../wp-content/plugins/elementor/modules/history/revisions-manager.php::363] Undefined array key &quot;editor_post_id&quot; [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 4 of 4JS: 2024-04-12 16:03:08 [error X 3][../wp-admin/load-scripts.php?c=1&amp;loadchunk_0=jquery-core,jquery-migrate,jquery-ui-core,utils,moxiejs,plupload&amp;ver=6.5.2:2:28760] Cannot read properties of undefined (reading &#039;value&#039;) 
JS: 2024-04-12 16:51:29 [error X 11][../wp-content/plugins/elementor/assets/js/ai.min.js?ver=3.20.4:3:7564] ReactUtils is not defined 
JS: 2024-04-12 20:50:08 [error X 12][../wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.20.4:3:816057] Cannot read properties of undefined (reading &#039;localized&#039;) 
JS: 2024-04-12 20:58:00 [error X 4][../wp-content/plugins/elementor/assets/js/4fdaa70e951ad90db2f2.bundle.min.js:2:7786] Cannot read properties of null (reading &#039;dataset&#039;) 



== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatible

== Elementor Pro - Compatibility Tag ==

````

</details>

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by nicholaszein** [comment] 2024-05-16 13:30
Hello @bnovak99!

I'm finally here! 🙌 

Apologies for the delay, and thank you for your patience! 🙏 

As we discussed on Facebook, unfortunately this is not a bug, and it's the expected behavior of the **SwiperJS** library that we use on all our carousels. As an example, you can [see this demo](https://swiperjs.com/demos/280-autoplay/core) on their official website. When you enable Autoplay it will slide through all slides, and then start again when Infinite Scroll is not enabled.

We understand this might not be the expected behavior, and we see the value of including an option to pause the autoplay once it reaches the last slide. So we would like to ask you to submit a new [🚀 Feature Request](https://github.com/orgs/elementor/discussions/new?category=feature-request), and we will consider it in the future if there is enough demand (votes) from other users.

Thank you for taking the time to report this issue! 🙏 

I'm closing this issue because this isn't a bug, rather a feature we currently don't support.

Kind regards

**Closed by nicholaszein** 2024-05-16 13:30 UTC
Labels: type/ui-ux, product/pro, component/swiper, type/workflow, mod*, widget/nested/carousel, widget/settings
