### ISSUE TITLE
color picker not working with portfolio widget

### ISSUE THREAD

**Issue by yossab** [elementor/elementor#11655] opened 2020-06-17 01:39 UTC
## Prerequisites

- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
 (I might have missed it because I'm not good at English.)
- [x] The issue still exists against the latest stable version of Elementor.

## Description

The color picker was applied to the portfolio widget using Jet Engine and ACF Pro, but it is not implemented.

## Steps to reproduce
(I am not good at English, so I used a translator and my sentence may be awkward.)

1) Custom Post Type was created with Jet Engine. (Post Type is Post and Custom Field is enabled. For convenience, this Custom Post Type is referred to as Products.)

2) [In ACF Pro] Color Picker Meta was created in the Meta Box of Products.

3) [From Products] New text (ex. A, B, C, D... J) was created and Color Picker Meta was entered for each post.

4) [From Products] I connected to the Elementer in the new article (Z) and used Portfolio Widget and realized it through the process below.
- [Set to Content - Query - Source - Ports]
- [Style - Item Overlay - Background Color - Dynamic Tag - ACF Color Picker Field - Key - Custom (set by me)]

5) I expected A, B, C, D... in the Portfolio widget. For each post in J, the overlaying color should be applied to the individual colors entered in Color Picker Meta, only to the base color (light green).

(My theme is Hello World and child theme.)

**Comment by lior-sh** [comment] 2020-06-17 12:04
Hi @yossab,

Thanks for reporting, we couldn't reproduce the issue.
Please contact our support at support @elementor.com for guidance in resolving this issue and mention that you were directed by me and reference this issue.
Thanks.

**Closed by lior-sh** 2020-06-17 12:04 UTC
