### ISSUE TITLE
✅ 🔗 🐞 Bug Report: Responsive CSS is not loaded - CUSTOM POST TYPE (Duplicate of #19394, #22670)

### ISSUE THREAD

**Issue by stormit** [elementor/elementor#22920] opened 2023-06-28 03:49 UTC
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Hi,

I created an issue about this [#22670](https://github.com/elementor/elementor/issues/22670). But, your team marked it to be duplicated. But, it is not duplicated. In my case, issue comes with a CUSTOM POST TYPE, not a default post type/page. For example, I created a custom post type which allows user to add footer content and add it to a main page content. In this case, it does not work correctly. Please check it again.

Thank you!

### Steps to reproduce

1. Edit a custom post type with Elementor (create one if don't have https://developer.wordpress.org/reference/functions/register_post_type/)
2. Switch to tablet or mobile editor
3. Change some things which need to update CSS (Ex: margin/padding, ...)
4. Check frontend

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently following the steps above.

### System Info

<html>
<body>

Operating System: | Linux |  
-- | -- | --
Software: | Apache |  
MySQL version: | MariaDB Server v10.3.39 |  
PHP Version: | 8.0.29 |  
PHP Memory Limit: | 4G |  
PHP Max Input Vars: | 1000 |  
PHP Max Post Size: | 256M |  
GD Installed: | Yes |  
ZIP Installed: | Yes |  
Write Permissions: | All right |  
Elementor Library: | Connected

</body>
</html>

**Comment by nicholaszein** [comment] 2023-06-28 13:38
Hello @stormit!

Thank you for your submission! 🙏 

### 🔗 🐞 This issue is a Duplicate of #19394

Which is on the same subject. Emphasis on <ins>same subject</ins>. We are implementing the fix for all Single Templates, regardless of the Post Type.

For this reason, I'm closing this thread and 🔃 **Merging** it with the original, so we can have all the discussions in one location, and deal with it more efficiently.

Feel free to continue the conversation there. 😉 

### 🔍 Please, in the future, remember to check if there isn't any thread similar to yours already opened. 
Opening duplicate issues only further delays their resolution. Please, respect our guidelines. Thanks for understanding.

Kind regards

**Closed by nicholaszein** 2023-06-28 13:38 UTC
Labels: bug, type/responsive, product/pro, component/theme-builder, status/merged, component/document, type/templates, 🚀 shipped, type/experiment, mod*, component/theme-builder/single-template, component/document/page-assets

**Comment by nicholaszein** [comment] 2023-08-02 00:48
Hello there!

We have great news! 🙌 

### 📢 We're happy to announce that the issue you raised was resolved in Elementor Core v.3.15.0! 🥳 

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
