### ISSUE TITLE
✔️ 🔗 🚀 Feature Request: Create great multi-purpose Widgets(Sections). Make less single-purpose Widgets (Duplicate of #2533, #2587, #4440)

### ISSUE THREAD

**Issue by MichaelDarko** [elementor/elementor#13125] opened 2020-11-22 10:55 UTC
- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )
____

This is a general request relating to the way Elementor develops new widgets.

I've been thinking about this a lot so I thought I might as well write it here, maybe somebody will read it.

### Current strategy for widgets

- Usually single-purpose
- Limited and somewhat random/inconsistent styling options

### Better strategy for widgets

- Make great multi-purpose widgets
- All available styling options

### Examples of multi-purpose widgets

- Content carousel (#219)
- Content tabs (#2587)
- Loop item designer (#4440)

### Why it's a better (and more future-proof) strategy

1. Instead of developing many single-use widgets (Slides, Testimonial Carousel, Media Carousel, etc.), you would develop one versatile widget (Perfectly designed customizable Content Carousel).

2. If you create a lot of single-use widgets, it will end up being a nightmare to maintain all the widgets in the future. 

3. That's why we now have so many outdated widgets that seemingly haven't been updated in a long time.

4. Creating more multi-purpose widgets would allow you to maintain and update widgets more easily.

5. Adding new styling options would be easier. 

6. It would give us more freedom to create what we need.

7. I suggest you have look at Webflow elements. Their elements are designed in much smarter way. With just a few elements you can accomplish more than with 15 Elementor widgets. 

8. With Webflow, I feel like I'm designing the website. With Elementor, I feel like I'm assembling the website with pre-made widgets. 

### Summary

The fact Elementor is a design tool and yet doesn't have almost any multi-purpose widgets and mostly focuses on limited single-use widgets doesn't make much sense in my opinion. Surely, versatile widgets should be developed first.

Multi-purpose widgets mentioned above are also one of the most requested features since the beginning.

But this is not about specific widgets. **This is about shift in strategy that would allow Elementor to maintain, update and focus resources more easily and, most importantly, it would allow the users to create without restrictions.**

I know it's like shouting into the wind here on Github, but maybe somebody will read it and hopefully Elementor leadership is thinking about this.

**Comment by black-eye** [comment] 2020-11-22 13:28
+1, 100% agreement
Fun fact: I've created very similar suggestion more than 3 years ago: https://github.com/elementor/elementor/issues/2533 - of course it was closed right away...

In fact it was one of the first requests I've made here. This "widget overcrowedness" was obvious 3 years ago with much less widgets available.

After those 3 years I would add one more suggestion: something like widget patters should be created. It could work similar way like the loop designer, but instead of dynamic data it would be filled manually. Basically it would be a simple custom widget builder, where you could design your own layout from the simple core widgets. I would be saved as reusable ontent block/widget and the user would fill in just the texts and images. Typical exmaple for such structure would be a team member. Maybe it's the way how Webflow elements work, I'm not familiar with them.

On the other hand this would require much more efficient DOM structure, because with the current wrapper div overuse it would ended up as a total "divception". BTW, same as with the loop item designer.

**Comment by sf-steve** [comment] 2020-11-28 03:17
This all draws back to the section implementation (as a hardcoded element).
Unfortunately, there has never been any suggestions this is being considered. There was a pull request a year or so ago by a core member, that looked like it was working towards abstract widget containers (which would allow nested widgets, the key to solving this problem in other tools), but it never got merged.

**Comment by MichaelDarko** [comment] 2020-11-28 12:57
Maybe the solution could be to create more than one Section type. Right now, we have 1 Section type and a large number of of Widgets. Instead of only focusing on developing new Widgets, why not develop new Sections? 

The structure could look like this:

**Sections**

- Normal section
- Slider section
- Tabs section
- Etc.

**Widgets**

- Heading
- Image
- Button
- Etc.

**With every new Section, you would double Elementor's capabalites, because you could utilize all Widgets within the section type.**

Look at what you can do in Webflow:

[Slider Element](https://www.youtube.com/watch?v=VC9kXcDAmXU)
[Tabs Element](https://www.youtube.com/watch?v=qAmJthuJnm4)

They don't give you 5 predesigned sliders and hope it will cover your needs. They give you a tool to design any slider possible - simple, yet 100X more powerful than Elementor's multiple widget approach.

**Versatile basic building blocks are absolutely fundamental in any design tool. Prebuilt components are a nice bonus, but that's not what matters. Elementor focused on making tons of widgets, but they forgot about the basic building blocks.**

**Comment by voneff** [comment] 2021-01-22 14:30
> Look at what you can do in Webflow:
> 
> [Slider Element](https://www.youtube.com/watch?v=VC9kXcDAmXU)
> [Tabs Element](https://www.youtube.com/watch?v=qAmJthuJnm4)

@MichaelDarko These Webflow videos make me wanna cry right now. 

I'm adding my +1 to this feature request. It seems like a big overhaul of the overall strategy but it really seems worth considering. I'm growing more and more tired of hacking prebuilt Elementor widgets instead of just creating the stuff I need. Current pain point: Putting a button into an accordion element. Does not seem so far-fetched, is it?

**Comment by MichaelDarko** [comment] 2021-01-23 16:32
@voneff 

Elementor is targeting professional web creators but the interface is designed more like a tool for non-professionals - Squarespace, Wix (Pre-styled widgets with limited customizability and single-use functinality).

That's exactly the direction where Gutenberg is going, so I don't quite understand why Elementor isn't moving in the same direction as Webflow - interface for professional web creators and designers. That's where Gutenberg isn't going to go and that's where the money is.

While working with Elementor, I've become a CSS professional (against my will) because I need to write hundreds of lines of code per every project to customize Elementor's widgets. As a designer, I need to have perfect control over styling and Elementor doesn't provide that.

The only reason not to move to Webflow is the fact that Elementor is build for WordPress and most of my clients want WordPress.

I was hoping the rise of Gutenberg would push Elementor in the right direction, but I don't see any signs of that.

Yes, it would require an overhaul, but that's completely normal and neccessary part of a product's life cycle in the software world. Elementor is now 5 years old and things are changing - Gutenberg is working and here to stay, so it seems like the right time to overhaul the editor. Just incrementally improving the current editor will have very diminishing returns.

**Comment by perks98** [comment] 2021-01-23 20:35
+1

**Comment by fabianenzensperger** [comment] 2021-01-23 21:32
YES. YES. YES. Please do this Elementor!

+1000000000000000000000000000

**Comment by fxaviers** [comment] 2021-02-12 16:24
+1000000000000

**Comment by MichaelDarko** [comment] 2021-03-01 13:59
I was just testing many other WP and non WP page builders and Elementor is missing 3 fundamental things:

### **1. Performance** 
Elementor is pretty much the worst compared to other serious builders.

#13099, #8847, #8572, #6778, #10886
### **2. Nested widgets** (Tabs, Slides, etc.)
The single purpose widget approach is just a terrible design decision for a pro page builder. It's extremely limiting.

#219, #2587
### **3. Dynamic content interface** (Post item builder, Post types + Meta fields interface)
Exactly like JetEngine from Crocoblock. This thing can 10x the power of Elementor and needs to be there natively.

#4440, #11126, #4246, #5979

**Comment by fabianenzensperger** [comment] 2021-03-01 17:04
> I was just testing many other WP and non WP page builders and Elementor is missing 3 fundamental things:
> 
> ### **1. Performance**
> Elementor is pretty much the worst compared to other serious builders.
> 
> #13099, #8847, #8572, #6778, #10886
> 
> ### **2. Nested widgets / sections** (Tabs, Slides, Accordions etc.)
> The single purpose widget approach is just a terrible design decision for a pro page builder. It's extremely limiting.
> 
> #219, #2587
> 
> ### **3. Dynamic content interface** (Post item builder, Post types + Meta fields interface)
> Exactly like JetEngine from Crocoblock. This thing can 10x the power of Elementor and needs to be there natively.
> 
> #4440, #11126, #4246, #5979


+Infinite for what @MichaelDarko said …

**Comment by wwdes** [comment] 2021-03-18 11:24
+1000

**Comment by eastriverstudio** [comment] 2021-06-15 12:24
+1 

This approach is definitely needed for serious professional usage. Very similarly I've often found myself needing a simple multi purpose containing div style widget that could be nested with other widgets. 

Having these sorts of multi purpose widgets would provide so much more flexibility to be able lay out and style things how I need them without having to apply lots of custom css to hack the single use widgets. 

Having such fundamental building blocks seems a really overlooked feature for Elementor Pro users and makes me think they are more geared towards winning over novice users right now. 

For example the competitor Oxygen Builder has these basic building blocks which can be nested and styled in pretty much anyway you need making it much more flexible than Elementor when you need to do something not catered for by an existing widget.

**Comment by fabianenzensperger** [comment] 2021-06-15 12:26
> +1
> 
> This approach is definitely needed for serious professional usage. Very similarly I've often found myself needing a simple multi purpose containing div style widget that could be nested with other widgets.
> 
> Having these sorts of multi purpose widgets would provide so much more flexibility to be able lay out and style things how I need them without having to apply lots of custom css to hack the single use widgets.
> 
> Having such fundamental building blocks seems a really overlooked feature for Elementor Pro users and makes me think they are more geared towards winning over novice users right now.
> 
> For example the competitor Oxygen Builder has these basic building blocks which can be nested and styled in pretty much anyway you need making it much more flexible than Elementor when you need to do something not catered for by an existing widget.


Nested Elements coming in 2021. Look at this Video: https://youtu.be/zUBG27llWKQ

**Comment by eastriverstudio** [comment] 2021-06-15 13:03
> > +1
> > This approach is definitely needed for serious professional usage. Very similarly I've often found myself needing a simple multi purpose containing div style widget that could be nested with other widgets.
> > Having these sorts of multi purpose widgets would provide so much more flexibility to be able lay out and style things how I need them without having to apply lots of custom css to hack the single use widgets.
> > Having such fundamental building blocks seems a really overlooked feature for Elementor Pro users and makes me think they are more geared towards winning over novice users right now.
> > For example the competitor Oxygen Builder has these basic building blocks which can be nested and styled in pretty much anyway you need making it much more flexible than Elementor when you need to do something not catered for by an existing widget.
> 
> Nested Elements coming in 2021. Look at this Video: https://youtu.be/zUBG27llWKQ

Thanks, I actually hadn't seen this preview video so it will be interesting to see when this is implemented. It will definitely be a welcome first step to improving the flexibility and usage of existing widgets. However I still think some form of multi purpose widgets that can work as initial building blocks will be necessary to make the most of that ability and give ultimate flexibility to professional users who need to build more custom solutions as is being highlighted by this request.

**Comment by sf-steve** [comment] 2021-06-15 14:20
> Thanks, I actually hadn't seen this preview video so it will be interesting to see when this is implemented. It will definitely be a welcome first step to improving the flexibility and usage of existing widgets. However I still think some form of multi purpose widgets that can work as initial building blocks will be necessary to make the most of that ability and give ultimate flexibility to professional users who need to build more custom solutions as is being highlighted by this request.

Nested widgets (dropzones within widgets) is the key to this - once that is possible, creating general purpose widgets will be pretty straight forward. 
I'm sure there will be some issues around non visible drop areas (sliders, tabs etc), but this is an amazing, positive change (that i have been waiting for for about 2 years...)

**Comment by m1ga** [comment] 2021-09-20 22:55
this PR [Internal: Nested elements.](https://github.com/elementor/elementor/pull/16252) sounds promising :+1:

**Comment by nicholaszein** [comment] 2023-01-11 19:44
Hello everyone!

Thank you for your feedback! 🙏 

## I want to give an update on this issue

We are working on implementing the requests made here and will be introducing new features along with the ones we have already introduced.

### 1. Nested Slider/Carousel

This feature is in our roadmap, and we plan to introduce it in a future release.

### 2. Container (Nested Sections)

✔️ The Container widget was already introduced as an experiment with Elementor **v3.6**, and is now a very stable experiment as of Elementor **v3.8** and later versions. Feel free to update to the latest version and enable the Flexbox Container experiment in your Dashboard > Elementor > Settings > Experiments.

To learn more about Containers, check [this article](https://elementor.com/help/what-is-a-container/).

### 3. Nested Tabs

✔️ The Nested Tabs experiment was introduced in Elementor **v3.10** and can also be activated in your Dashboard > Elementor > Settings > Experiments. Feel free to update to the latest version and start using this new feature! 💪 

You can learn more about Nested Tabs [here](https://developers.elementor.com/elementor-3-10-beta/).

### 4. Nested Accordions/Toggles

The Nested Accordions feature will be introduced in a future release and is part of our roadmap.

### 5. Loop Grid / Loop Builder

✔️ Like the Container experiment, the Loop Builder experiment was already introduced with Elementor **v3.8** with an update to support WooCommerce in **v3.9**. Feel free to update to the latest version and enable the Loop experiment in your Dashboard > Elementor > Settings > Experiments.

You can learn more about the Loop Builder [here](https://elementor.com/help/loop-grid/).

## 🔗 This issue is a Duplicate of many other issues, such as #2533, #2587, and #4440.

Which are on the same subject. 

For this reason, I'm closing this issue and 🔃 **Merging** it with the originals, so we can have all the discussions in one location, and deal with them more efficiently.

Feel free to continue the conversation there. 😉 

### ✔️ Please, in the future, remember to check if there isn't an issue similar to yours already opened. 

Best regards,

Nick

**Closed by nicholaszein** 2023-01-11 19:44 UTC
Labels: request/enhancement, request/feature, component/carousel, solved_by_container, solved_by_loop, solved_by_nested, component/accordion, component/tabs

**Comment by nicholaszein** [comment] 2023-08-01 13:23
Hello there!

We have great news! 🙌 

### 📢 We're happy to announce that the new Nested Accordion widget was released with Elementor v3.15.0! 🥳 

With this release, we finally conclude this Feature Request! 🎉

Thank you very much for all the feedback shared here, and for helping shape the future of Elementor! 🙏 

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
