### ISSUE TITLE
🔗 🐞 Bug Report: extra line height in all icons (Duplicate of #16511)

### ISSUE THREAD

**Issue by Michaelgimii** [elementor/elementor#20487] opened 2022-11-22 11:20 UTC
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Hi elementor team.

I have informed many times here that there is an extra line height in the icons. But unfortunately, no one pays attention. Until I saw these annoying bugs in action in my daily work with Elementor.
Is it difficult for a big team like Elementor to solve such a simple problem?

### Steps to reproduce

To find out the existence of extra line height in Elementor icons, please follow the steps below.

1- Add an icon widget.
2- In this widget, place the View on the framed.
3- In the advanced tab of the widget, create a border.

After that, the presence of an extra and disturbing space in the icons will be quite evident.

![d](https://user-images.githubusercontent.com/88034902/203301285-70454e92-0a4d-4801-990e-c7e49c2a2ec3.png)

If the code **selector{ line height :0px; }** Add , this annoying space will disappear.

Please check this issue. thanks

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

-

**Comment by nicholaszein** [comment] 2022-11-22 20:52
Hello @Michaelgimii!

Thank you for your submission! 🙏 

### 🔗 This issue is a Duplicate of #16511

Which is on the same subject. 

Moreover, this issue was already submitted by you before as a duplicate (#17987).

We understand your frustration, and we want to make things right. but there are other issues that have priority over this one. Please avoid posting duplicates, this only makes it more difficult to solve the original issue.

For this reason, I'm closing this issue and 🔃 **Merging** it with the original, so we can have all the discussions in one location, and deal with it more efficiently.

Feel free to continue the conversation there. 😉 

Best regards,

Nick

**Closed by nicholaszein** 2022-11-22 20:52 UTC
Labels: bug, component/icons, type/design
