### ISSUE TITLE
⛔ Non-Searcheable, Non-Public Custom Post Type won't show in the Theme Builder Display Conditions for Archive Templates

### ISSUE THREAD

**Issue by mohammadzm** [elementor/elementor#25395] opened 2024-03-08 09:37 UTC
### Prerequisites

- [X] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [X] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

hi
i created multiple custom post type with ACF and i want to create different custom template for each post type archive but when i want to set condition for display, no custom post type showed in display condition list

### Steps to reproduce

1. create post type
2. create archive page with elementor and get engine
3. cant find post type to set the condition to display

### Expected behavior

create special archive template for each post type

### Isolating the problem

- [ ] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [X] This bug happens with the Hello Elementor theme active.
- [X] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

<details>
<summary>Click to reveal</summary>

````txt

== Server Environment ==
	Operating System: Linux
	Software: LiteSpeed
	MySQL version: MySQL Community Server - GPL v8.0.35
	PHP Version: 7.4.33
	PHP Memory Limit: 8000M
	PHP Max Input Vars: 10000
	PHP Max Post Size: 256M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.4.3
	Site URL: https://drkojast.com
	Home URL: https://drkojast.com
	WP Multisite: No
	Max Upload Size: 256 مگابایت
	Memory limit: 40M
	Max Memory limit: 8000M
	Permalink Structure: /%postname%/
	Language: fa-IR
	Timezone: Asia/Tehran
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 3.0.0
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: fa_IR
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:123.0) Gecko/20100101 Firefox/123.0

== Active Plugins ==
	Advanced Custom Fields PRO
		Version: 6.2.1.1
		Author: WP Engine

	AIKit
		Version: 4.12.2
		Author: 

	Asset CleanUp Pro: Page Speed Booster
		Version: 1.2.3.6
		Author: Gabe Livan

	Classic Editor
		Version: 1.6.3
		Author: WordPress Contributors

	Converter for Media
		Version: 5.12.1
		Author: matt plugins

	Disable Everything
		Version: 0.4.1
		Author: Dessky Team

	Easy Table of Contents
		Version: 2.0.63
		Author: Magazine3

	Elementor
		Version: 3.19.4
		Author: Elementor.com

	Elementor Pro
		Version: 3.19.2
		Author: Elementor.com

	IndexNow
		Version: 1.0.2
		Author: Microsoft Bing

	Index WP MySQL For Speed
		Version: 1.4.15
		Author: Oliver Jones, Rick James

	Instant Indexing
		Version: 1.1.17
		Author: Rank Math

	JetElements For Elementor
		Version: 2.6.15
		Author: iranelEmentor

	JetEngine
		Version: 3.3.6
		Author: IranElementor

	JetMenu
		Version: 2.4.3
		Author: IranElementor

	JetSearch
		Version: 3.2.3
		Author: IranElementor

	Leaflet Map
		Version: 3.4.1
		Author: bozdoz

	Post Views Counter
		Version: 1.4.4
		Author: dFactory

	Quick Featured Images Pro
		Version: 9.3.0
		Author: Martin Stehle

	Rank Math SEO
		Version: 1.0.214
		Author: Rank Math

	Rank Math SEO PRO
		Version: 3.0.34
		Author: Rank Math

	Really Simple SSL
		Version: 7.2.3
		Author: Really Simple Plugins

	Relevanssi Live Ajax Search
		Version: 2.4
		Author: Mikko Saari

	Relevanssi Premium
		Version: 2.24.2
		Author: Mikko Saari

	RTL license management
		Version: 1.7.7
		Author: RTL-Theme

	Schema Pro
		Version: 2.7.7
		Author: Brainstorm Force

	SEOWriting
		Version: 1.1.8
		Author: SEOWriting

	Site Kit by Google
		Version: 1.121.0
		Author: Google

	Ultimate Addons for Elementor
		Version: 1.36.28
		Author: IranElementor

	UpdraftPlus - Backup/Restore
		Version: 1.24.1
		Author: UpdraftPlus.Com, DavidAnderson

	Wordfence Security
		Version: 7.11.3
		Author: Wordfence

	WP-Parsidate
		Version: 4.0.2
		Author: WP-Parsi Team

	wpDiscuz
		Version: 7.6.15
		Author: gVectors Team

	WPForms
		Version: 1.8.1.2
		Author: WPForms

	WP Post Rating
		Version: 2.5
		Author: Shoaib Saleem

	WP Rocket
		Version: 3.13.0.2
		Author: WP Media

	WP Telegram
		Version: 4.1.2
		Author: WP Socio


== Must-Use Plugins ==
	Asset CleanUp Pro: Plugin Filtering
		Version: 1.0
		Author: Gabriel Livan

	Index WP MySQL For Speed Upgrade Filter for mu-plugins.
		Version: 1.4.14
		Author: 


== Features ==
	Custom Fonts: 1
	Custom Icons: 0

== Integrations ==
	


== آزمایشات عنصر ==
	بارگذاری دارایی بهبود یافته: به صورت پیشفرض فعال است
	بارگذاری CSS بهبود یافته: به صورت پیشفرض فعال است
	نمادهای فونت درون خطی: به صورت پیشفرض غیرفعال است
	نقاط قطع سفارشی اضافی (جهت رسپانسیو سایت به کار میره): به صورت پیشفرض فعال است
	admin_menu_rearrangement: به صورت پیشفرض غیرفعال است
	کانتینر فلکس باکس: فعال
	ارتقای کتابخانه Swiper: به صورت پیشفرض فعال است
	کانتینر شبکه: فعال
	Default to New Theme Builder: به صورت پیشفرض فعال است
	سربرگ و فوتر پوسته سلام: به صورت پیشفرض فعال است
	نوار بالا ویرایشگر: فعال
	بارگذاری بهینه گوتنبرگ: به صورت پیشفرض فعال است
	ساختن با هوش مصنوعی: غیرفعال
	صفحات فرود: به صورت پیشفرض فعال است
	عناصر تو در تو: به صورت پیشفرض غیرفعال است
	بارگذاری تنبل تصاویر پس‌زمینه: به صورت پیشفرض غیرفعال است
	بهینه‌سازی بارگذاری تصویر: فعال
	پنل صفحات: به صورت پیشفرض غیرفعال است
	راهنمای سبک جهانی: به صورت پیشفرض فعال است
	Page Transitions: به صورت پیشفرض فعال است
	Notes: به صورت پیشفرض فعال است
	Display Conditions: فعال
	Form Submissions: به صورت پیشفرض فعال است
	Scroll Snap: به صورت پیشفرض فعال است
	Menu: به صورت پیشفرض غیرفعال است
	Taxonomy Filter: فعال


== گزارش ==
	
PHP: showing 3 of 3PHP: 2024-02-02 12:09:15 [warning X 6][../wp-content/plugins/elementor/core/files/file-types/svg.php::118] SimpleXMLElement::__construct(): ^ [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-03-05 11:19:20 [notice X 2][../wp-content/plugins/elementor/includes/base/controls-stack.php::1459] Undefined index: image_height_tablet [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-03-08 12:51:00 [notice X 2][../wp-content/plugins/elementor-pro/modules/loop-filter/module.php::151] Undefined index: post_type [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

Log: showing 20 of 372024-02-10 21:51:55 [info] المنتور/Upgrades - _on_each_version Start  
2024-02-10 21:51:55 [info] المنتور/Upgrades - _on_each_version Finished 
2024-02-10 21:51:55 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'المنتور',
  'from' => '3.19.1',
  'to' => '3.19.2',
)]
2024-02-24 14:59:46 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.19.0',
  'to' => '3.19.2',
)]
2024-02-24 15:00:18 [info] elementor-pro::elementor_pro_updater Started 
2024-02-24 15:00:18 [info] Elementor Pro/Upgrades - _on_each_version Start  
2024-02-24 15:00:18 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2024-02-24 15:00:18 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.19.0',
  'to' => '3.19.2',
)]
2024-02-24 15:00:20 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.19.0',
  'to' => '3.19.2',
)]
2024-02-27 21:29:03 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'المنتور',
  'from' => '3.19.2',
  'to' => '3.19.3',
)]
2024-02-27 21:31:04 [info] elementor::elementor_updater Started 
2024-02-27 21:31:04 [info] المنتور/Upgrades - _on_each_version Start  
2024-02-27 21:31:04 [info] المنتور/Upgrades - _on_each_version Finished 
2024-02-27 21:31:04 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'المنتور',
  'from' => '3.19.2',
  'to' => '3.19.3',
)]
2024-02-27 21:31:06 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'المنتور',
  'from' => '3.19.2',
  'to' => '3.19.3',
)]
2024-02-28 20:17:20 [info] elementor::elementor_updater Started 
2024-02-28 20:17:20 [info] المنتور/Upgrades - _on_each_version Start  
2024-02-28 20:17:20 [info] المنتور/Upgrades - _on_each_version Finished 
2024-02-28 20:17:21 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'المنتور',
  'from' => '3.19.3',
  'to' => '3.19.4',
)]
2024-02-28 20:17:24 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'المنتور',
  'from' => '3.19.3',
  'to' => '3.19.4',
)]

JS: showing 2 of 2JS: 2024-03-08 07:32:57 [error X 3][../wp-content/plugins/elementor/assets/js/admin.min.js?ver=3.19.4:3:48039] c[0] is undefined 
JS: 2024-03-08 08:12:45 [error X 1][../wp-content/plugins/elementor-pro/assets/js/app.min.js?ver=3.19.2:2:29772] this.conditionsConfig is null 



== المنتور - Compatibility Tag ==
	
	Elementor Pro: هیچ سازگاری تعیین نشده
	JetElements For Elementor: هیچ سازگاری تعیین نشده
	Ultimate Addons for Elementor: هیچ سازگاری تعیین نشده

== Elementor Pro - Compatibility Tag ==

````

</details>

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by toineenzo** [comment] 2024-03-10 04:06
Dynamic tags from custom post types are not supported in 3.19.x. This phase will be released in the upcoming 3.20 update

**Comment by Obaitan** [comment] 2024-03-11 07:54
@toineenzo, do you know when 3.20 will be released?
We have a site in which the dynamic content from custom post types have disappeared.

**Comment by toineenzo** [comment] 2024-03-11 08:16
> @toineenzo, do you know when 3.20 will be released?

In the coming days

**Closed** 2024-03-12 08:50 UTC
Labels: product/pro, theme-builder, type/content-management, mod*, compatibility/cpt, document/display-conditions

**Comment by nicholaszein** [comment] 2024-03-25 19:52
Hello @mohammadzm,

Thank you for reaching out! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
Post Types will only appear as Display Conditions if they are public, can be queried publicly, can be found in searches, and have archives. Otherwise you won't be able to see them as an option in the list.

### ✅ What you can do to solve your issue:
Make sure when creating your Custom Post Types they have the following parameters properly configured:

1. **Is Public** === **`true`**
2. **Exclude from search** === **`false`**
3. **Publicly queriable** === **`true`**
4. **Has archive** === **`true`**

It is also recommended to go to your WordPress **`Dashboard`** > **`Elementor`** > **`Settings`** > **`General`** page and check the the Post Types you want to be editable by Elementor.

### 👍 For now, that's all we can help with. 

### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for support.

❔ If you have questions, or need guidance, help, or general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) The main Facebook group where all kinds of users come together to help each other.
- [Elementor Academy](https://elementor.com/academy) Learn everything you need to know about using Elementor.
- [Elementor Developers Documentation](https://developers.elementor.com/) Learn everything about our Developer-API.
- [Free Support Forum](https://wordpress.org/support/plugin/elementor) Get help on WordPress.org.

💎 If you have an active [Elementor Pro](https://elementor.com/pro) license you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Kind regards
