### ISSUE TITLE
🚀 Feature Request: Variable Google Fonts

### ISSUE THREAD

**Issue by perks98** [elementor/elementor#19277] opened 2022-07-27 11:02 UTC
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

With variable fonts you can have full control over weight, grade, optical and slant through pulling in only one set of font data, while currently Elementor pulls in multiple weights and italic options for a single font.

### Describe the solution you'd like

Like in the Mozilla link below have a slider for each adjustable option for all typography customisation options.
https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Fonts/Variable_Fonts_Guide

Not all Google fonts support variable options, so under the fonts list maybe group supported ones under another section.

### Describe alternatives you've considered

Only alternative with Elementor is to use the custom fonts area to pull in the variable font then use custom CSS in the theme options to make the adjustments.

**Comment by arielk** [comment] 2022-11-06 10:58
Duplicate of https://github.com/elementor/elementor/issues/11333

**Closed by arielk** 2022-11-06 10:58 UTC
Labels: request/feature, component/custom-fonts
