### ISSUE TITLE
.map file undefiened in Safari Browser Mac OS

### ISSUE THREAD

**Issue by sagarpatel124** [elementor/elementor#7661] opened 2019-03-29 06:40 UTC
Hello Elementor,

Please check .map undefined issue. 

Screenshot : https://ibb.co/wLM1gBz 

[Error] Failed to load resource: the server responded with a status of 404 () (frontend-modules.js.map, line 0)
[Error] Failed to load resource: the server responded with a status of 404 () (ResizeSensor.min.js.map, line 0)
[Error] Failed to load resource: the server responded with a status of 404 () (common-modules.js.map, line 0)
[Error] Failed to load resource: the server responded with a status of 404 () (swiper.min.js.map, line 0)

Let us know, If you need us to share URL with you. 

Wordpress : 5.1.1 Elementor : 2.5.10 Jupiter X Theme

**Comment by creakipik** [comment] 2019-03-29 18:43
Hello,
Same for me.

**Comment by hubertq** [comment] 2019-04-04 11:40
No news about it ? EP 2.5.4 is out and the issue is not fixed ;(

**Comment by backpackerstoday** [comment] 2019-04-10 09:17
Still not fixed in the latest E and E Pro versions... 
Please fix that Elementor Team. The Widgets in Safari looks so blurry and unsharp.

**Comment by hubertq** [comment] 2019-04-11 09:25
Fixed for me since yesterday

**Comment by lior-sh** [comment] 2020-01-14 12:24
Close, fixed.

**Closed by lior-sh** 2020-01-14 12:24 UTC
