### ISSUE TITLE
✔️ 🔗 🐞 Bug Report: Elementor Pro triggers the WooCommerce `added_to_cart` event upon clicking the "Update" button after editing a page (Duplicate of #18629)

### ISSUE THREAD

**Issue by colmtroy** [elementor/elementor#19822] opened 2022-09-15 14:24 UTC
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Elementor Pro triggers the WooCommerce `added_to_cart` event upon clicking the "Update" button after editing a page.

### Steps to reproduce

1.) Create a simple page on a WP install with WooCommerce, Elementor and Elementor Pro installed
2.) Add a simple text block with some simple text to it.
3.) Click "Publish" or "Update" (doesn't matter if its a new page or an update to existing one)
4.) Expected result: I expect the page to save without the WooCommerce `added_to_cart` event from being triggered.
5.) Actual result: The page is saved, but the WooCommerce `added_to_cart` event is also triggered.

Why is this a problem?
Hundreds of WooCommerce themes and plugins listen for the `added_to_cart` event to be fired to do things like display side carts, modals and so on. When a user is editing a page on a WooCommerce store with any theme or plugin which listens for this event, updating a page creates unexpected events to occur when saving/updating the page. (such as triggering a mini cart or side cart to appear).

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

== Server Environment ==
	Operating System: Linux
	Software: nginx/1.16.1
	MySQL version: Percona Server (GPL), Release '13', Revision '6f7822f' v8.0.22-13
	PHP Version: 7.4.16
	PHP Memory Limit: 256M
	PHP Max Input Vars: 5000
	PHP Max Post Size: 512M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 42
	WP Multisite: No
	Max Upload Size: 512 MB
	Memory limit: 4096M
	Max Memory limit: 2000M
	Permalink Structure: /%category%/%postname%/
	Language: en-US
	Timezone: Europe/Prague
	Debug Mode: Active

== Theme ==
	Name: redacted
	Version: 1.1.1
	Author: redacted
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 3.7.6
		Author: Elementor.com

	Elementor Pro
		Version: 3.7.6
		Author: Elementor.com

	WooCommerce
		Version: 6.9.1
		Author: Automattic

== Must-Use Plugins ==
	GridPane Disable XMLRPC
		Version: 0.1.0
		Author: Jeff Cleverley

	GridPane Disable XMLRPC
		Version: 0.1.0
		Author: Jeff Cleverley. Jan-Riekus Jansen

	GridPane Disable XMLRPC
		Version: 0.1.0
		Author: Jeff Cleverley

	GridPane Nginx Cache Purger
		Version: 1.0.0
		Author: Jeff Cleverley Jebat

	WP CLI Login Command Server
		Version: 1.2
		Author: Evan Mattson

== Elements Usage ==
	
	page : 79
		accordion : 1
		button : 145
		countdown : 3
		divider : 7
		flip-box : 6
		gallery : 8
		heading : 287
		html : 45
		icon : 2
		icon-box : 16
		icon-list : 4
		image : 161
		image-carousel : 61
		media-carousel : 1
		post-comments : 2
		posts : 4
		shortcode : 10
		spacer : 20
		text-editor : 367
		toggle : 2
		video : 46
		woocommerce-products : 3
	section : 8
		accordion : 1
		button : 37
		heading : 70
		image-carousel : 24
		spacer : 2
		text-editor : 8
	wp-post : 2
		text-editor : 1
	wp-page : 36
		accordion : 4
		button : 43
		countdown : 2
		divider : 9
		gallery : 7
		heading : 112
		html : 15
		icon : 2
		icon-box : 7
		icon-list : 2
		image : 38
		media-carousel : 1
		post-comments : 1
		shortcode : 11
		spacer : 25
		text-editor : 130
		theme-post-title : 1
		video : 15
		woocommerce-products : 1

== Elementor Experiments ==
	Optimized DOM Output: Active by default
	Improved Asset Loading: Inactive by default
	Improved CSS Loading: Inactive by default
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Active by default
	Additional Custom Breakpoints: Inactive by default
	Import Export Template Kit: Active by default
	Hide native WordPress widgets from search results: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Inactive by default
	Default to New Theme Builder: Active by default
	Landing Pages: Active by default
	Color Sampler: Active by default
	Favorite Widgets: Active by default
	Admin Top Bar: Active by default
	Page Transitions: Active by default
	Notes: Active by default
	Form Submissions: Active by default
	Scroll Snap: Active by default

== Log ==
	
Log: showing 20 of 362021-11-04 16:05:59 [info] Elementor Pro/Upgrades - _v_3_5_0_price_list Start  
2021-11-04 16:05:59 [info] Elementor Pro/Upgrades - _v_3_5_0_price_list Finished 
2021-11-04 16:05:59 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.4.2',
  'to' => '3.5.0',
)]
2021-11-04 16:05:59 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.4.2',
  'to' => '3.5.0',
)]
2022-07-08 16:55:05 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.5.0',
  'to' => '3.7.1',
)]
2022-07-08 17:05:03 [info] elementor-pro::elementor_pro_updater Started 
2022-07-08 17:05:03 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-07-08 17:05:03 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-07-08 17:05:03 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.5.0',
  'to' => '3.7.1',
)]
2022-07-08 17:14:46 [info] elementor::elementor_updater Started 
2022-07-08 17:14:46 [info] Elementor/Upgrades - _on_each_version Start  
2022-07-08 17:14:48 [info] Elementor/Upgrades - _on_each_version Finished 
2022-07-08 17:14:48 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.4.7',
  'to' => '3.6.6',
)]
2022-09-15 15:54:09 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.6',
  'to' => '3.7.5',
)]
2022-09-15 15:55:01 [info] elementor::elementor_updater Started 
2022-09-15 15:55:01 [info] Elementor/Upgrades - _on_each_version Start  
2022-09-15 15:55:03 [info] Elementor/Upgrades - _on_each_version Finished 
2022-09-15 15:55:03 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.6',
  'to' => '3.7.5',
)]
2022-09-15 16:10:11 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.1',
  'to' => '3.7.6',
)]
2022-09-15 16:11:25 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.5',
  'to' => '3.7.6',
)]

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatible

== Elementor Pro - Compatibility Tag ==

**Comment by nicholaszein** [comment] 2023-02-02 07:08
Hello there!

We have great news! 🙌 

### 📢 We're happy to announce that the issue you raised was resolved in Elementor Pro **v3.7.2**! 🥳 

Moreover, this issue is a duplicate of issue #18629, which is on the same subject.

For this reason, we are closing this issue!

✔️ Please feel free to check it out and update your plugin to the new version!

Cheers 🥂

**Closed by nicholaszein** 2023-02-02 07:08 UTC
Labels: bug, product/pro, component/woocommerce, component/menu_cart
