### ISSUE TITLE
E 3.3 and E Pro 3.3.2 +  Improved CSS Loading Experiment = Review Widget Broken Star Icons

### ISSUE THREAD

**Issue by wpturnedup** [elementor/elementor#15632] opened 2021-07-13 14:10 UTC
- E 3.3 and E Pro 3.3.2 
- Improved CSS Loading Experiment (Active)
- All other experiments are deactivated
- All plugins deactivated except E and E Pro
- Hello theme active

[This super short video shows the issue.](https://cloud.mylisting.club/qX1woY7)

Thank you!

**Comment by shilo-ey** [comment] 2021-07-13 14:16
If you go to Elementor > Tools > Regenerate CSS & Data - does it resolves the issue for you?

**Comment by wpturnedup** [comment] 2021-07-13 14:19
Unfortunately, no.

**Comment by djrwp** [comment] 2021-07-13 14:49
I have noticed the same issue. Only way to fix is to switch off the experiment.
<img width="465" alt="Screenshot 2021-07-13 at 10 54 25" src="https://user-images.githubusercontent.com/84224815/125473398-5202ded3-b662-4cba-9589-7e048661b43c.png">

**Comment by shilo-ey** [comment] 2021-07-13 14:54
Please share a live example so we could debug it. currently, we are not able to reproduce this issue.

**Comment by d19dotca** [comment] 2021-07-13 15:29
Same issue with the Tabs widget.

**Comment by wpturnedup** [comment] 2021-07-13 15:46
staging-zukupeho.kinsta.cloud

Bottom of the page.

**Comment by shilo-ey** [comment] 2021-07-13 16:43
Thanks for reporting.

We will address this issue soon and release a patch.

Please follow this thread for updates.

Thanks!

**Comment by Deadlift79** [comment] 2021-07-13 21:56
Similar issue here: problem is with gallery pro filter bar pointer. (Multiple galleries).
With elementor CSS loading experiment enabled (and also optimized DOM output enabled) the choosen pointer works only inside elementor editor. In page preview or in the front end it disappears. Regenerate CSS or clearing cache don't fix it and only solution is to disable CSS loading experiment or optimized DOM output.

**Comment by rotemee** [comment] 2021-07-15 09:21
Hi @d19dotca,

I was unable to reproduce the problem with the Tabs widget, can you please provide "steps to reproduce"?
Are you using custom-css?

Please provide any additional info that will help us to reproduce the problem with the Tabs widget.

Thanks.

**Comment by d19dotca** [comment] 2021-07-15 14:56
@rotemee, funny enough I can't reproduce it either now. I went to just re-enable that experiment and issue didn't reproduce this time. Very strange though because as you can see in the screenshots above it was definitely an issue and I fixed it by simply disabling the CSS experiment and could reproduce it at will at that time. I wonder... I hadn't updated Elementor Pro to 3.3.2 at that moment and only updated yesterday, I wonder if that fixed things there. Not too sure. I'll try enabling this experiment in other sites slowly then and see if I see that issue again.

**Comment by rotemee** [comment] 2021-07-15 15:05
@d19dotca great, thank you.

**Comment by djrwp** [comment] 2021-07-16 07:59
New issue with improved CSS loading activated - archive template 'archive posts widget' not displaying with correct formatting. See attached showing how it should look and how it looks with experiment activated. As you can see image is wrong size and text has centred and changed sizes.
<img width="662" alt="Screenshot 2021-07-16 at 08 56 43" src="https://user-images.githubusercontent.com/84224815/125913091-1867db53-4aa7-4b47-a7a0-7cd7256c6d8c.png">
<img width="752" alt="Screenshot 2021-07-16 at 08 52 11" src="https://user-images.githubusercontent.com/84224815/125913107-f6d09207-2720-4675-8728-69db862f40b7.png">

**Comment by shilo-ey** [comment] 2021-07-20 15:44
This issue has been resolved in Elementor v3.3.1

Feel free to update

Thanks!

**Closed by shilo-ey** 2021-07-20 15:44 UTC
Labels: bug, status/merged

**Comment by Elemenentorist** [comment] 2021-07-23 08:45
Hello Team

![Capture1](https://user-images.githubusercontent.com/87853203/126757891-650ed6ca-fa17-44ad-a233-8255c155b1e9.JPG)

![Capture2](https://user-images.githubusercontent.com/87853203/126757940-bddc53bc-e77a-4620-9e4a-c129c26c67df.JPG)

I'm on 3.3.4, yet this issue is showing on my [blog](https://comparing.ly/blog) page.

The issue doesn't show while i'm logged into admin mode. There is huge empty gray space added below my blog header images.

Any help is appreciated.

**Comment by Elemenentorist** [comment] 2021-07-23 08:57
Also facing this issue highlighted in #15658 merged with this thread #15632.
Version 3.3.4, post info widget is broken site-wide. You can check it live on one of my blog [post](https://comparing.ly/blog/benefits-of-unlimited-graphic-design-for-small-businesses/) or [page](https://comparing.ly/best-logo-design-contest-sites/).

![Capture3](https://user-images.githubusercontent.com/87853203/126759005-41ba4e3f-f1bf-4f50-ab31-ddee1dc9885a.JPG)
On this post, even the blog header is left aligned along with the post info. Haven't seen this on other blog posts.

![Capture4](https://user-images.githubusercontent.com/87853203/126759027-1acb700a-64d8-438b-8ad6-5417e8e64415.JPG)

Issues don't show while logged in to Admin mode.

Kindly release a bug fix update. Thanks for your help.

**Comment by shilo-ey** [comment] 2021-07-25 07:25
> Also facing this issue highlighted in #15658 merged with this thread #15632.
> Version 3.3.4, post info widget is broken site-wide. You can check it live on one of my blog [post](https://comparing.ly/blog/benefits-of-unlimited-graphic-design-for-small-businesses/) or [page](https://comparing.ly/best-unlimited-graphic-design-services/).
> 
> ![Capture3](https://user-images.githubusercontent.com/87853203/126759005-41ba4e3f-f1bf-4f50-ab31-ddee1dc9885a.JPG)
> On this post, even the blog header is left aligned along with the post info. Haven't seen this on other blog posts.
> 
> ![Capture4](https://user-images.githubusercontent.com/87853203/126759027-1acb700a-64d8-438b-8ad6-5417e8e64415.JPG)
> 
> Issues don't show while logged in to Admin mode.
> 
> Kindly release a bug fix update. Thanks for your help.
> 
> Edit: Just visited one of the pages I was editing last night. I see the issue is not present there. [Link](https://comparing.ly/best-logo-design-contest-sites/). Will try updating all the pages or blog templates i'm having trouble with, if this alone can fix the issue. Though it's a tedious process opening and saving all the custom templates I've up on my site.

Try to go to Elementor > Tools > Regenerate CSS & Data and see if the issue is resolved.

**Comment by ulrichson** [comment] 2021-08-12 12:57
@shilo-ey I experience the same issue as described in https://github.com/elementor/elementor/issues/15632#issuecomment-885498406 (with the post info widget), however, regenerating the CSS doesn't help in my case. 

The issue is present with a clean WordPress 5.8 installation, Elementor Version 3.3.1, Elementor Pro Version 3.3.6 and Hello theme.

Should https://github.com/elementor/elementor/issues/15658 be re-opened to track this issue?

**Comment by Elemenentorist** [comment] 2021-09-06 08:16
> > Also facing this issue highlighted in #15658 merged with this thread #15632.
> > Version 3.3.4, post info widget is broken site-wide. You can check it live on one of my blog [post](https://comparing.ly/blog/benefits-of-unlimited-graphic-design-for-small-businesses/) or [page](https://comparing.ly/best-unlimited-graphic-design-services/).
> > ![Capture3](https://user-images.githubusercontent.com/87853203/126759005-41ba4e3f-f1bf-4f50-ab31-ddee1dc9885a.JPG)
> > On this post, even the blog header is left aligned along with the post info. Haven't seen this on other blog posts.
> > ![Capture4](https://user-images.githubusercontent.com/87853203/126759027-1acb700a-64d8-438b-8ad6-5417e8e64415.JPG)
> > Issues don't show while logged in to Admin mode.
> > Kindly release a bug fix update. Thanks for your help.
> > Edit: Just visited one of the pages I was editing last night. I see the issue is not present there. [Link](https://comparing.ly/best-logo-design-contest-sites/). Will try updating all the pages or blog templates i'm having trouble with, if this alone can fix the issue. Though it's a tedious process opening and saving all the custom templates I've up on my site.
> 
> Try to go to Elementor > Tools > Regenerate CSS & Data and see if the issue is resolved.

Any fixes @shilo-ey, it's been quite long. Still waiting for the issue to get fixed. And it's happening on the Elementor POSTS widget throughout my site and giving a very bad user experience.

**Comment by Elemenentorist** [comment] 2021-09-06 08:17
> Hello Team
> 
> ![Capture1](https://user-images.githubusercontent.com/87853203/126757891-650ed6ca-fa17-44ad-a233-8255c155b1e9.JPG)
> 
> ![Capture2](https://user-images.githubusercontent.com/87853203/126757940-bddc53bc-e77a-4620-9e4a-c129c26c67df.JPG)
> 
> I'm on 3.3.4, yet this issue is showing on my [blog](https://comparing.ly/blog) page.
> 
> The issue doesn't show while i'm logged into admin mode. There is huge empty gray space added below my blog header images.
> 
> Any help is appreciated.

Any fixes @shilo-ey, it's been quite long. Still waiting for the issue to get fixed. And it's happening on the Elementor POSTS widget throughout my site and giving a very bad user experience.
