### ISSUE TITLE
🐞 Bug report: Custom Widget Width Not working on tablet unless desktop is set to Custom as well.

### ISSUE THREAD

**Issue by brian-brightfire** [elementor/elementor#19528] opened 2022-08-18 14:51 UTC
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

This was introduced when updating Elementor from v3.6.8 > v3.7.0. We have tested in the most recent release as well (3.7.1) and the problem still exists.

We have an instance where we have 3 widgets set to 'Default' (Setting to Full Width works as well) for their widget width on Desktop, then Set to 'Custom' (33.3%) on Tablet, then set to Full Width (100%) on Mobile. 

*All three widgets shown are duplicates width identical settings to illustrate the 33.3% width*

Desktop:
![desktop-editor](https://user-images.githubusercontent.com/45051494/185423850-7f806793-410f-48d6-9c2c-1cb67e54a53c.png)

Tablet:
![tablet-editor](https://user-images.githubusercontent.com/45051494/185423846-4aaff863-cfd2-4828-9b01-0a66bb49b83b.png)

Mobile:
![mobile-editor](https://user-images.githubusercontent.com/45051494/185423848-633bbc11-c260-40d2-ab14-e96fdfc8aa12.png)

The Elementor Editor displays everything exactly as it should, but when viewing in the tablet breakpoints on the frontend, the 33.3 width is not respected and we are given `width: initial; max-width: initial` instead, and the widgets are not displayed at the expected 33.3% width. If we change Desktop to 'Custom: 100%', then our tablet width is respected.

Frontend, displayed at 1024px (Tablet):
![tablet-frontend](https://user-images.githubusercontent.com/45051494/185424082-4a85351c-9ccf-4bb3-b349-3060be0c3eb7.png)

It appears that improper CSS is generated for the Tablet breakpoint. Generated CSS for this post and these widgets is:
`@media (max-width: 1024px) {
    .elementor-8 .elementor-element.elementor-element-ec0731c {
        text-align: center;
        width: initial;
        max-width: initial;
    }
    .elementor-8 .elementor-element.elementor-element-d0b81f5 {
        text-align: center;
        width: initial;
        max-width: initial;
    }
    .elementor-8 .elementor-element.elementor-element-8a370e2 {
        text-align: center;
        width: initial;
        max-width: initial;
    }
}

@media (max-width: 767px) {
    .elementor-8 .elementor-element.elementor-element-ec0731c {
        width: 100%;
        max-width: 100%;
    }
    .elementor-8 .elementor-element.elementor-element-d0b81f5 {
        width: 100%;
        max-width: 100%;
    }
    .elementor-8 .elementor-element.elementor-element-8a370e2 {
        width: 100%;
        max-width: 100%;
    }
}`

### Steps to reproduce

Create any type of widget and under Advanced > Width, select the following values for your responsive breakpoints:
1. Desktop: Default
2. Tablet: Custom (33.3%)
3. Mobile: Full Width (100%)

Once you have set that up, you can update and view on the frontend, and view as tablet size, and you will see the Custom 33.3% width is not respected and you, instead, are left with `width: initial; max-width: initial` for the element width.

If you go back into the editor and set Advanced > Width with the following values (changing Desktop to custom).
1. Desktop Custom (100%)
2. Tablet: Custom (33.3%)
3. Mobile: Full Width (100%)

You will then notice everything on the frontend is respected properly and when viewing in tablet mode, your widget will now have the expected `width: 33.3%; max-width: 33.3%`.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Darwin
	Software: nginx/1.16.0
	MySQL version: MySQL Community Server (GPL) v5.7.28
	PHP Version: 7.4.1
	PHP Memory Limit: 256M
	PHP Max Input Vars: 4000
	PHP Max Post Size: 1000M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.0.1
	Site URL: http://elementorcore.local/test-site
	Home URL: http://elementorcore.local/test-site
	WP Multisite: Yes
	Max Upload Size: 1 MB
	Memory limit: 64M
	Max Memory limit: 256M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: en-US
	Timezone: 0
	Admin Email: brian+test@brightfire.com
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.5.0
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36

== Active Plugins ==
	Custom Code Test Plugin
		Version: 2.4.0
		Author: BrightFire Development Team

== Network Plugins ==
	Elementor
		Version: 3.7.1
		Author: Elementor.com

	Elementor Pro
		Version: 3.7.3
		Author: Elementor.com

== Elementor Experiments ==
	Optimized DOM Output: Active by default
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Active by default
	Additional Custom Breakpoints: Active by default
	Import Export Template Kit: Active by default
	Hide native WordPress widgets from search results: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Inactive by default
	Default to New Theme Builder: Active by default
	Hello Theme Header & Footer: Active by default
	Landing Pages: Active by default
	Color Sampler: Active by default
	Favorite Widgets: Active by default
	Admin Top Bar: Active by default
	Page Transitions: Active by default
	Notes: Active by default
	Form Submissions: Active by default
	Scroll Snap: Active by default

== Log ==
	
PHP: showing 2 of 2PHP: 2022-07-01 19:18:02 [notice X 2][/Users/brianfleming/Sites/elementor-core/app/public/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-07-01 19:18:24 [notice X 2][/Users/brianfleming/Sites/elementor-core/app/public/wp-content/plugins/elementor/includes/managers/image.php::87] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

Log: showing 10 of 102022-08-18 14:24:33 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.6',
  'to' => '3.7.1',
)]
2022-08-18 14:24:33 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.2',
  'to' => '3.7.3',
)]
2022-08-18 14:24:33 [info] elementor::elementor_updater Started 
2022-08-18 14:24:33 [info] Elementor/Upgrades - _on_each_version Start  
2022-08-18 14:24:33 [info] Elementor/Upgrades - _on_each_version Finished 
2022-08-18 14:24:33 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.6',
  'to' => '3.7.1',
)]
2022-08-18 14:24:34 [info] elementor-pro::elementor_pro_updater Started 
2022-08-18 14:24:34 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-08-18 14:24:34 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-08-18 14:24:34 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.2',
  'to' => '3.7.3',
)]

== Elementor - Compatibility Tag ==
	

== Elementor Pro - Compatibility Tag ==

**Comment by hb81010** [comment] 2022-08-18 18:41
dito

it's just annoying. every update destroys my layouts

**Comment by mattmckenny** [comment] 2022-08-19 23:54
I've confirmed the same issue. Looks like a direct result of this removing `device_args` from the `_element_custom_width` control. Here's the recent change that caused this to break on the front end #19085

**Comment by mattmckenny** [comment] 2022-08-25 14:43
@rami-elementor @shilo-ey Any chance this will get some attention soon?

**Comment by mattmckenny** [comment] 2022-08-25 21:21
This appears to be the same issue reported here as well: #19542

**Comment by brian-brightfire** [comment] 2022-08-26 00:24
Can confirm 3.7.2 does not fix this issue either.

**Comment by brian-brightfire** [comment] 2022-08-26 00:25
Can confirm that 3.7.2 does not resolve the issue either.

**Comment by hb81010** [comment] 2022-08-29 15:45
3.7.3 is online and #19542 #19528 are not listed in the changelog. Just two fixes are in there

I still have to use 3.6.8.
It's getting ridiculous....

**Comment by mattmckenny** [comment] 2022-08-30 19:30
Here's another recent bug report with the exact same problem
https://github.com/elementor/elementor/issues/19643

**Comment by hb81010** [comment] 2022-08-31 19:12
If I wasn't partially dependent on Crocoblock, I would have switched to Bricks long ago.
It's just ridiculous that serious problems are ignored for months.
Even if it was a major problem, they could at least briefly write that they are currently working on a solution.

I bet everything that if this bug will be fixed at some point, then directly other serious problems will occur.

**Comment by mattmckenny** [comment] 2022-08-31 19:35
I chatted with Elementor support today and, while very helpful, this bug isn't in a priority. They have it logged as an internal issue but it needs more examples of affected sites to justify giving more attention to fixing the problem.

I suggest reaching out via chat support and providing them with examples of your broken sites.

**Comment by hb81010** [comment] 2022-08-31 19:59
A colleague of mine already did it about 2 weeks ago. Even gave Elementor support access to his website.
They have as a solution for a mobile 50% 50% view, just created another section with two columns and made that only visible for mobile devices. 

This is not a solution, just a bad wordkaround. Especially in some listings with 100 products causing unnecessary code and making Elementor slow. In general, this solution is anything but best practice.
On the question when a fix will come, came from the support that the error will be handled as soon as possible and more standard block answers.

I'll create a ticket later, but I don't have much hope.

The numeric scrubber and custom icons on the carousel slider, video & alert widgets are much more important in Elementor....

**Comment by steve231293** [comment] 2022-09-13 04:32
Hello @udidol @rami-elementor
Is there any updates on this? Could you please fix it asap? It is very important for us.

**Comment by chasperlisimba** [comment] 2022-09-13 08:32
> I chatted with Elementor support today and, while very helpful, this bug isn't a priority. They have it logged as an internal issue but it needs more examples of affected sites to justify giving more attention to fixing the problem.
> 
> I suggest reaching out via chat support and providing them with examples of your broken sites.

It's breaking tousands of live sites and they have no priority? :-/ I also created a ticket and they told me the same... They are aware of this bug but they don't know when it will be fixed yet... it's open since a long time and they released 3 new versions... but no fix. not cool!

**Comment by udidol** [comment] 2022-09-13 10:40
This fix will be released in the next patch, very soon.

**Comment by steve231293** [comment] 2022-09-13 10:43
Hope see that soon. Thank you!

**Comment by mattmckenny** [comment] 2022-09-14 18:05
@udidol Thanks for helping get this patched and in the 3.7.5 release

**Comment by udidol** [comment] 2022-09-14 18:18
No prob @mattmckenny.
There are MANY users (~12 Million) and just so many of us developers at Elementor.
It's sometimes difficult for us to keep up the pace of developing new features while addressing existing issues, but we do our best, and even if a bug could take more than a few days to fix, it doesn't mean we forget about it.
This specifically was a system-wide issue with the responsive controls' conditioning, which I've worked on personally, so it was important for me personally to release a fix as soon as I could manage it.

**Comment by udidol** [comment] 2022-09-14 18:18
Fixed in Elementor Core 3.7.5, closing.

**Closed by udidol** 2022-09-14 18:18 UTC
Labels: bug, type/responsive
