### ISSUE TITLE
Conflict Between Elementor theme styler and forced line-height:1 in frontend.min.css

### ISSUE THREAD

**Issue by amindiary** [elementor/elementor#10649] opened 2020-02-24 15:33 UTC
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

## Description

When I set line-height for headings, in theme styler, it's not apply because of this rule 
```
.elementor-widget-heading .elementor-heading-title {
    padding: 0;
    margin: 0;
    line-height: 1;
}
```
in **frontend.min.css**

thisis the rule that not apply:
```
body.elementor-kit-19 h2 {
    color: #0B214E;
    font-size: 30px;
    line-height: 1.25em;
}
```

![image](https://user-images.githubusercontent.com/2544046/75165714-d8c59f00-5733-11ea-929d-85cbb1d1438a.png)

![image](https://user-images.githubusercontent.com/2544046/75165854-132f3c00-5734-11ea-8954-804259fb84b8.png)

I see this issue is around . but nothing replied from elementor team.

https://wordpress.org/support/topic/line-heights-set-on-elementor-stylesheet-set-to-1/

## Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a default WordPress theme active.
- [X] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MySQL Community Server (GPL) v5.7.29
	PHP Version: 7.3.14
	PHP Max Input Vars: 1000
	PHP Max Post Size: 20M
	GD Installed: Yes
	ZIP Installed: No
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.3.2
	Site URL: https://testhosting.co.uk/efia
	Home URL: https://testhosting.co.uk/efia
	WP Multisite: No
	Max Upload Size: 20 MB
	Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: Efia
	Version: 1.0
	Author: 
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36 OPR/66.0.3515.72

== Active Plugins ==
	Advanced Custom Fields PRO
		Version: 5.8.7
		Author: Elliot Condon

	All-in-One WP Migration
		Version: 7.17
		Author: ServMask

	All-in-One WP Migration FTP Extension
		Version: 2.59
		Author: ServMask

	Contact Form 7
		Version: 5.1.6
		Author: Takayuki Miyoshi

	Contact Form 7 styler for Elementor
		Version: 1.0.0
		Author: Essential Addons

	Custom Post Type UI
		Version: 1.7.3
		Author: WebDevStudios

	DynamicConditions
		Version: 1.4.4
		Author: RTO GmbH

	Ele Custom Skin
		Version: 1.3.10
		Author: Dudaster.com

	Elementor
		Version: 2.9.2
		Author: Elementor.com

	Elementor Pro
		Version: 2.8.4
		Author: Elementor.com

	Lenix Elementor Leads addon
		Version: 1.8.0
		Author: Lenix

	Really Simple SSL
		Version: 3.2.9
		Author: Rogier Lankhorst, Mark Wolters

	reSmush.it Image Optimizer
		Version: 0.3.0
		Author: reSmush.it

	SVG Support
		Version: 2.3.17
		Author: Benbodhi

	Yoast SEO
		Version: 13.1
		Author: Team Yoast

== Elements Usage ==
	
	footer : 1
		heading : 7
		icon-list : 4
		image : 1
	header : 1
		icon : 1
		image : 1
	loop : 2
		button : 2
		heading : 5
	popup : 1
		nav-menu : 1
	section : 3
		button : 1
		heading : 2
		image-carousel : 1
		spacer : 1
		text-editor : 1
	wp-post : 0
		button : 3
		call-to-action : 9
		form : 1
		heading : 5
		image : 2
		posts : 1
		spacer : 13
		template : 3
		text-editor : 2
	wp-page : 7
		accordion : 1
		breadcrumbs : 1
		button : 12
		call-to-action : 18
		eael-contact-form : 1
		form : 1
		heading : 36
		icon-box : 3
		image : 12
		posts : 1
		spacer : 45
		template : 13
		text-editor : 3

== Log ==
	
Log: showing 10 of 102019-12-12 12:07:37 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.8.0',
  'to' => '2.8.1',
)]
2020-01-14 09:49:47 [info] elementor::elementor_updater Started 
2020-01-14 09:49:47 [info] Elementor/Upgrades - _v_2_8_3_recalc_usage_data Start  
2020-01-14 09:49:47 [info] Elementor/Upgrades - _v_2_8_3_recalc_usage_data Finished 
2020-01-14 09:49:47 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.8.1',
  'to' => '2.8.3',
)]
2020-01-14 09:49:47 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '2.8.1',
  'to' => '2.8.3',
)]
2020-01-14 09:50:18 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.7.3',
  'to' => '2.8.3',
)]
2020-02-13 13:12:33 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.8.3',
  'to' => '2.8.5',
)]
2020-02-17 10:59:02 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.8.5',
  'to' => '2.9.2',
)]
2020-02-17 11:00:17 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.8.3',
  'to' => '2.8.4',
)]

JS: showing 4 of 4JS: 2020-02-13 12:54:26 [error X 8][http://testhosting.co.uk/efia/wp-content/themes/efia/js/script.js?ver=5.3.2:144:30] $(...).magnificPopup is not a function 
JS: 2020-02-17 12:11:56 [error X 1][https://testhosting.co.uk/efia/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.9.2:31:167093] Cannot read property \'isDesignable\' of undefined 
JS: 2020-02-18 11:45:56 [error X 2][https://testhosting.co.uk/efia/wp-content/plugins/elementor/assets/lib/e-select2/js/e-select2.full.min.js?ver=4.0.6-rc.1:1:74235] Cannot read property \'destroy\' of undefined 
JS: 2020-02-24 13:45:15 [error X 19][https://testhosting.co.uk/efia/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.9.2:7:83366] Cannot read property \'elements\' of undefined 

PHP: showing 1 of 1PHP: 2020-02-18 11:04:57 [notice X 2][/home/hakunamatata/public_html/efia/wp-content/plugins/elementor-pro/modules/dynamic-tags/acf/tags/acf-image.php::44] Undefined offset: 1 [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

				
</details>

**Comment by black-eye** [comment] 2020-02-24 16:46
+1
Oh yes, this is looong time issue, which hasn't been addressed yet. See https://github.com/elementor/elementor/issues/3197 or https://github.com/elementor/elementor/issues/6761.

Both issues were closed with the promise they will be solved when the Theme Styler comes.

So pls, could you remove this 1em line-height nonsense, already? ;-) Not only there are conflicts with most of the themes, there's a conflict with your own Theme Styler now as well.

**Comment by amindiary** [comment] 2020-02-24 20:28
> +1
> Oh yes, this is looong time issue, which hasn't been addressed yet. See #3197 or #6761.
> 
> Both issues were closed with the promise they will be solved when the Theme Styler comes.
> 
> So pls, could you remove this 1em line-height nonsense, already? ;-) Not only there are conflicts with most of the themes, there's a conflict with your own Theme Styler now as well.

Yeah, not good, Elementor team can solve it in 1 second! :| Probably they think, we can solve it by adding custom CSS with !important. but this **line-height:1em;** is really nonsense

**Comment by kaspergram** [comment] 2020-02-25 21:12
+1

**Comment by teoeugene** [comment] 2020-02-26 01:44
Unfortunately, this long time issue has came back to bite them in this new feature. They previously dismissed it without even providing an alternative solution. Now I hope they finally fix this ridiculous "line-height: 1" backward compatibility "feature".

**Comment by maxwellhibbert** [comment] 2020-02-26 07:46
Please fix!

**Comment by bzle** [comment] 2020-02-26 17:33
+1
Just ran into this too. The selector generated by Theme Style isn't as specific as the selector from frontend.min.css ("body.elementor-kit-255 h3" vs ".elementor-widget-heading .elementor-heading-title")

**Comment by DeoThemes** [comment] 2020-02-27 07:20
Not only line-height: 1; is useless and conflict with theme styles, but also provides really bad user experience for the readers. It could've been something 1.3 at least.

**Comment by gzabrisk** [comment] 2020-02-28 00:08
+1
Please please please fix this! It's frustrating that I can't use the line-height settings in the new Theme Styler for headings. Doesn't make any sense. Thank you!

**Comment by veniko** [comment] 2020-02-28 08:39
+1

**Comment by robert-neacsu** [comment] 2020-03-03 18:51
+1
Please take this into consideration, It is really annoying if line-height doesn't work as expected.

**Comment by sholman** [comment] 2020-03-04 04:36
Yes i just ran into this as well. Please fix this ASAP.

The comment from a previous listing of this issue (https://github.com/elementor/elementor/issues/3197) is "We did have some brainstorming sessions here about this and some other issue that came up, and we will have to address this and more once we provide a "theme builder"..."

Seems this wans't addressed!

**Comment by JohnPixle** [comment] 2020-03-09 13:27
This is insane to be happening guys, especially now with Theme Style.

**Comment by omgitsisaias** [comment] 2020-03-16 10:51
+1 Please fix.
Overriding styles with !important isn't feasible.

**Comment by parfilov** [comment] 2020-03-21 18:58
+1

**Comment by ludekcerny** [comment] 2020-03-23 18:13
+1

btw, this workaround fix the issue for me:
`
.elementor-widget-heading .elementor-heading-title {
    line-height: initial!important;
}
`
Added to the child style.css

**Comment by twerkema** [comment] 2020-03-24 20:35
+1

**Comment by twerkema** [comment] 2020-03-24 20:39
+1
@ludekcerny 
It didn't work in my child style.css. It only works in the customizer css for me. Can you please explain what the "initial" setting is? When I inspect the element it just says normal. I'm wondering where the base calculation comes from. Thanks.

**Comment by zeinnicholas** [comment] 2020-03-25 00:12
This was added probably to avoid newbies complaining that they couldn't change the height of the heading title widget. Why it has so much more specificity than anything else goes beyond my comprehention. I'm glad I found this issue.

+1 for fixing this ASAP.

My workaround is that I end up changing my child theme style to load after all Elementor's base CSS in array().

**Comment by ludekcerny** [comment] 2020-03-25 09:58
> +1
> @ludekcerny
> It didn't work in my child style.css. It only works in the customizer css for me. Can you please explain what the "initial" setting is? When I inspect the element it just says normal. I'm wondering where the base calculation comes from. Thanks.

I did further inspection and my workaround is not working, sorry, it's just reset the style to browser's default.

**Comment by stevek28** [comment] 2020-03-25 21:44
Hi Elementor Team - Please FIX this! It is really annoying that line-heights  for headings set in theme customizer (e.g. GP) or even set in the new theme styles cannot tickle through because of this.. Thank you! s.

**Comment by twerkema** [comment] 2020-03-26 15:42
Suggested short term fix is to go into the actual Elementor plugin (not Pro) and remove "line-height: 1;" CSS snippet for the ".elementor-widget-heading .elementor-heading-title" in your Elementor "frontend.min.css" 

They said that they're looking into a way to allow their new feature to work without messing up older sites. Obviously this creates concern that if you update the plugin this code will be overwritten. I've asked how we're supposed to handle that.

**Comment by fippy** [comment] 2020-03-26 19:03
+1 Please fix asap...

**Comment by amindiary** [comment] 2020-03-26 20:37
@shilo-ey @joshmarom @arielk @KingYes 
opened this issue on 24 Feb · 21 comments
19 participants
Feature of **Paid** Version

**Comment by fippy** [comment] 2020-03-26 22:56
> @shilo-ey @joshmarom @arielk @KingYes
> opened this issue on 24 Feb · 21 comments
> 19 participants
> Feature of **Paid** Version

???? What does this mean?

**Comment by black-eye** [comment] 2020-03-26 23:03
> > @shilo-ey @joshmarom @arielk @KingYes
> > opened this issue on 24 Feb · 21 comments
> > 19 participants
> > Feature of **Paid** Version
> 
> ???? What does this mean?

@amindiary is suggesting that this issue has grown enough to deserve some attention and reaction from the devs. ;-) And he's not the only one, I feel the same.

**Comment by fippy** [comment] 2020-03-27 04:48
Ah ok. Yes I agree. Thanks.

Just in case it helps anyone, this was my temporary workaround (it's a bit crazy!):

I think the stylesheets are queued correctly: stylesheets generated by the new Global Theme Styling feature include frontend.min.css as a dependency when enqueued (so frontend.min.css will always be included prior any theme styling).

It would seem then the issue is one of CSS precedence, in that frontend.min.css provides a more specific rule for widget headings, etc in insisting on:

`.elementor-heading-title{padding:0;margin:0;line-height:1}`

So the solution I have is a adding a custom function (either to functions.php or via Code Snippets) 

`function change_elementor_frontend_css( $upgrader_object, $options ) {

	// Bail if Elementor is not available.
	if ( ! defined( 'ELEMENTOR_VERSION' ) ) {
		return;
	}
	
 	$plugins_root = WP_CONTENT_DIR . '/plugins/';

	if ($options['action'] == 'update' && $options['type'] == 'plugin' ) {
		foreach($options['plugins'] as $plugin) {
			
			if (dirname($plugin) === 'elementor') {
				$path = $plugins_root . dirname($plugin) . '/assets/css/frontend.min.css';
				$css = file_get_contents($path); 
				$css = str_replace(".elementor-widget-heading .elementor-heading-title{padding:0;margin:0;line-height:1}", '.elementor-widget-heading .elementor-heading-title{padding:0;margin:0;}', $css, $count);
				if ($count) {
					file_put_contents($path, $css);
				}
			}		   
		}
	}
}
add_action( 'upgrader_process_complete', 'change_elementor_frontend_css',10, 2);`

I personally use Code Snippets and have set this to run in Admin area only. I haven't fully tested it, but in theory it should run whenever you update Elementor and change the css file to remove line-height.

I originally looked to do it using wp_enqueue_scripts (below) but didn't want checks running that often.

`function change_elementor_frontend_css() {
	
	// Bail if Elementor is not available.
    if ( ! defined( 'ELEMENTOR_VERSION' ) ) {
        return;
    }

	global $wp_styles;
	$path = $_SERVER["DOCUMENT_ROOT"] . parse_url($wp_styles->registered[ 'elementor-frontend' ]->src)["path"];
	//echo '<pre>',$path,'</pre>';
	$css = file_get_contents($path); 
	//echo '<pre>',$css,'</pre>';
	$css = str_replace(".elementor-widget-heading .elementor-heading-title{padding:0;margin:0;line-height:1}", '.elementor-widget-heading .elementor-heading-title{padding:0;margin:0;}', $css, $count);
	//echo '<pre>',$count,'</pre>';
	if ($count) {
		file_put_contents($_SERVER["DOCUMENT_ROOT"] . $path, $css);
	}
}
add_action('wp_enqueue_scripts','change_elementor_frontend_css');`

**Comment by amyriounis** [comment] 2020-03-28 14:58
Hi @fippy, thanks for your fix:)

I believe this line:
`		file_put_contents($_SERVER["DOCUMENT_ROOT"] . $path, $css);
`

should be:
`
		file_put_contents( $path, $css );
`

since you already included `$_SERVER["DOCUMENT_ROOT"]` at:

`
	$path = $_SERVER["DOCUMENT_ROOT"] . parse_url($wp_styles->registered[ 'elementor-frontend' ]->src)["path"];
`

Final:
```
function change_elementor_frontend_css() {
		if ( ! defined( 'ELEMENTOR_VERSION' ) ) {
			return;
		}

		global $wp_styles;

		$path = $_SERVER["DOCUMENT_ROOT"] . parse_url( $wp_styles->registered[ 'elementor-frontend' ]->src )["path"];
		$css  = file_get_contents( $path );
		$css  = str_replace( ".elementor-widget-heading .elementor-heading-title{padding:0;margin:0;line-height:1}", '.elementor-widget-heading .elementor-heading-title{padding:0;margin:0;}', $css, $count );

		if ( $count ) {
			file_put_contents( $path, $css );
		}
	}
```

**Comment by shimsa** [comment] 2020-03-29 20:20
+1

**Comment by Alipio123** [comment] 2020-04-01 07:05
Thanks @amyriounis 

If the code above doesn't work in your end, please make sure you clear your cache.

**Comment by lior-sh** [comment] 2020-04-01 11:48
Hi @amindiary,

Thanks for reporting.
We need more info in order to reproduce this issue, can you please add steps to replicate?
Thanks.

**Comment by black-eye** [comment] 2020-04-01 12:04
> Hi @amindiary,
> 
> Thanks for reporting.
> We need more info in order to reproduce this issue, can you please add steps to reproduce?
> Thanks.

Hi, I'm not amindiary, but isn't the issue obvious? Elementor uses basic settings for every heading, which is:

```
.elementor-widget-heading .elementor-heading-title {
    padding: 0;
    margin: 0;
    line-height: 1;
}
```
The selector for this settings (namely line-height: 1) are too specific, so they override the settings for h1-h{x} defined in most of the themes and Elementor Themer.

Please, get rid of this  `line-height: 1;` (or make it optional) and everything is fine!

**Comment by amindiary** [comment] 2020-04-01 12:10
> Hi @amindiary,
> 
> Thanks for reporting.
> We need more info in order to reproduce this issue, can you please add steps to reproduce?
> Thanks.

as @black-eye  said, it's obvious: 

https://github.com/elementor/elementor/issues/10649#issuecomment-607208956

**Comment by teoeugene** [comment] 2020-04-02 01:54
@lior-sh This is a long time issue that is also related to #3197 or #6761. Your fellow colleagues dismissed and closed those cases without providing a solution or an optional workaround. Now with this Theme Styler feature released, that issue has came full circle.

**Comment by lior-sh** [comment] 2020-04-02 08:14
Hi @amindiary,

We are working on the fix, we will update you ASAP.
Thanks.

**Comment by goldenpony89** [comment] 2020-04-08 13:43
Is this supposed to be fixed in the next version? This issue been conflicting with other themes for years.

**Comment by dev-love** [comment] 2020-04-14 17:25
Hi @lior-sh,

Please give us a quick update on this VERY SERIOUS issue. Everyone using the new theme styler (and all other Elementor users as well, of course) shouldn't experience this bug. It needs to be fixed ASAP.

**Comment by lior-sh** [comment] 2020-04-22 09:24
Hi @dev-love,

Thanks for reporting.
We will address this issue soon and we will release it in the next Patch.
Please follow this thread for updates.
Thanks!

**Comment by black-eye** [comment] 2020-04-22 10:23
hi @lior-sh.

Looking at changes made here: https://github.com/elementor/elementor/pull/11036/files

It seems, that the line-height: 1 is still there, just applied to another element.
It probably addresses the issue with the Theme Styler, but not the conflict with the themes. Could you pls consider removing it completely? Or at least apply it optionaly?

Thanks

**Comment by goldenpony89** [comment] 2020-04-27 17:08
> hi @lior-sh.
> 
> Looking at changes made here: https://github.com/elementor/elementor/pull/11036/files
> 
> It seems, that the line-height: 1 is still there, just applied to another element.
> It probably addresses the issue with the Theme Styler, but not the conflict with the themes. Could you pls consider removing it completely? Or at least apply it optionaly?
> 
> Thanks

I don't think it has been fixed yet, has it? Just updated and tested again, the problem still shows...

**Comment by black-eye** [comment] 2020-04-27 17:46
@goldenpony89 
> I don't think it has been fixed yet, has it? Just updated and tested again, the problem still shows...

No It hasn't been fixed yet. But there is a commit with a fix for it in the dev version (see the link above). The dev version isn't live yet, but the commit seems to offer only a partial solution.

**Comment by pierrehansen** [comment] 2020-05-01 06:13
Was scratching my head for 1 hour because line-height couldn't be changed. Inexplicable that Elementor is on the one side so fancy but then let's one sit on these little faults. Very annoying!

+1

**Comment by 3rinyes** [comment] 2020-05-04 14:09
+1
This needs to be fixed, line-height in theme styles are basically useless now.

**Comment by danger-danj** [comment] 2020-05-22 19:27
+1
Fixy fix. Pleasy please.

**Comment by Nicoduweb** [comment] 2020-05-23 10:39
It's a painful problem ! Please fix it.
My actually workaround is to use "Custom Global CSS" with (here only H2 for example) : 

`.elementor-widget-heading h2.elementor-heading-title{
    line-height :60px;
}

@media (max-width: 1024px){
 .elementor-widget-heading h2.elementor-heading-title{
    line-height :40px;
}   

@media (max-width: 767px){
 .elementor-widget-heading h2.elementor-heading-title{
    line-height :20px;
}   
   
}`

A better workaround would be able to filter css rules when generating global CSS to add "!important" parameter  on body.elementor-kit-XXXXX h2 {
    line-height: 60px !important;
}

But i don't understand how fapply filter to this CSS file.

Please fix it. :)

**Comment by shilo-ey** [comment] 2020-05-24 15:55
This issue has been resolved in Elementor v2.9.9

Feel free to update

@black-eye as you mentioned, we changed the selector so it will be less intrusive. As for conflicting themes - do you have an example? I suggest creating new feature request for allowing this option to be optional.

Thanks!

**Closed by shilo-ey** 2020-05-24 15:55 UTC
Labels: bug, status/merged

**Comment by black-eye** [comment] 2020-05-24 17:07
@shilo-ey Of course the conflict with the themes persists. :(

I've created a new issue for it: https://github.com/elementor/elementor/issues/11453
It's like the 6th attempt to resolve this problem. Hopefully this one will be the last one.

**Comment by zeinnicholas** [comment] 2020-05-25 23:25
> It's a painful problem ! Please fix it.
> My actually workaround is to use "Custom Global CSS" with (here only H2 for example) :
> 
> `
> .elementor-widget-heading h2.elementor-heading-title{
> line-height :60px;
> }
> 
> @media (max-width: 1024px){
> .elementor-widget-heading h2.elementor-heading-title{
> line-height :40px;
> }
> 
> @media (max-width: 767px){
> .elementor-widget-heading h2.elementor-heading-title{
> line-height :20px;
> }
> 
> }
> `
> 
> A better workaround would be able to filter css rules when generating global CSS to add "!important" parameter on body.elementor-kit-XXXXX h2 {
> line-height: 60px !important;
> }
> 
> But i don't understand how to apply filter to this CSS file.
> 
> Please fix it. :)

No please, don't add any !important tag anywhere. I just want to be able to edit things without being forcely overrides. This is a simple fix. No need to fancy workarounds. 

@shilo-ey You need to stop being afraid of fixing legacy issues. It's a simple matter of making a public statement and letting people know that their website might lose some styling, and offer them to use the already available Theme Styles to fix it. If you start living in this legacy world you'll won't be able to move forwards anymore. See WooCommerce and their crappy templating system. It's a disaster! Please, pretty please, don't go that way.

**Comment by shilo-ey** [comment] 2020-05-26 09:20
[**@zeinnicholas**](https://github.com/zeinnicholas) commented on [May 26, 2020, 2:25 AM GMT+3](https://github.com/elementor/elementor/issues/10649#issuecomment-633741102 "2020-05-25T23:25:01Z - Replied by Github Reply Comments"):
> @shilo-ey You need to stop being afraid of fixing legacy issues. It's a simple matter of making a public statement and letting people know that their website might lose some styling, and offer them to use the already available Theme Styles to fix it. If you start living in this legacy world you'll won't be able to move forwards anymore. See WooCommerce and their crappy templating system. It's a disaster! Please, pretty please, don't go that way.

Thanks,

We usually not releasing any "breaking" changes in minor versions.

This issue will be dealt off soon in a Major version.

FYI - version 3.0 will remove some elements and make Elementor code more modern (speaking of legacy...)

**Comment by zeinnicholas** [comment] 2020-05-26 15:29
> Thanks,
> 
> We usually not releasing any "breaking" changes in minor versions.
> 
> This issue will be dealt off soon in a Major version.
> 
> FYI - version 3.0 will remove some elements and make Elementor code more modern (speaking of legacy...)

Now that is awesome to hear! Thank you very much for your reply. I know you are very popular here. So I appreciate your time spending answering me!

Thanks!
