### ISSUE TITLE
🔗 🐞 Bug Report: woocommerce cart widget not working (Duplicate of #21836)

### ISSUE THREAD

**Issue by Paky2002** [elementor/elementor#21860] opened 2023-03-30 15:48 UTC
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

After the last update the woocommerce minicart is always empty, it doesn't show anything. Widget content is not loaded. the container that should contain the products has nothing inside. I would also like to point out that trying to insert the Elementor minicart, there are some errors regarding the webpack.
<img width="227" alt="image" src="https://user-images.githubusercontent.com/58035146/228891628-2c6c090d-f490-44cc-a414-3f9e4235e878.png">
<img width="313" alt="image" src="https://user-images.githubusercontent.com/58035146/228891716-1e4fe95f-22b9-4f14-acca-7d399c006b66.png">

### Steps to reproduce

1) Add product to cart
2) Open minicart 

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently following the steps above.

### System Info

<details>
<summary>System Info</summary>

````txt



== Server Environment ==
	Operating System: Linux
	Software: LiteSpeed
	MySQL version: MariaDB Server v10.5.17
	PHP Version: 8.0.28
	PHP Memory Limit: 6144M
	PHP Max Input Vars: 5000
	PHP Max Post Size: 6144M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.2
	Site URL: https://revolution03.net
	Home URL: https://revolution03.net
	WP Multisite: No
	Max Upload Size: 6 GB
	Memory limit: 40M
	Max Memory limit: 6144M
	Permalink Structure: /%postname%/
	Language: it-IT
	Timezone: 0
	Admin Email: revolution03eu@gmail.com
	Debug Mode: Inactive

== Theme ==
	Name: Woodmart
	Version: 7.1.4
	Author: XTemos
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: it_IT
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36

== Active Plugins ==
	Asset CleanUp: Page Speed Booster
		Version: 1.3.9.1
		Author: Gabe Livan

	Back In Stock Notifier for WooCommerce | WooCommerce Waitlist Pro
		Version: 3.2
		Author: codewoogeek

	BRT Fermopoint
		Version: 1.2.7
		Author: BRT

	bunny.net
		Version: 1.0.8
		Author: bunny.net

	Code Snippets
		Version: 3.3.0
		Author: Code Snippets Pro

	Contact Form 7
		Version: 5.7.5.1
		Author: Takayuki Miyoshi

	CookieYes | GDPR Cookie Consent
		Version: 3.0.8
		Author: CookieYes

	CSS &amp; JavaScript Toolbox
		Version: 11.6
		Author: Wipeout Media

	Easy WP SMTP
		Version: 2.1.0
		Author: Easy WP SMTP

	Elementor
		Version: 3.12.0
		Author: Elementor.com

	Elementor Pro
		Version: 3.12.0
		Author: Elementor.com

	Flexible Shipping
		Version: 4.20.0
		Author: Octolize

	Hostinger
		Version: 1.0.2
		Author: Hostinger

	Icon Element
		Version: 2.0.0
		Author: Webangon

	Indeed Ultimate Affiliate Pro
		Version: 6.8
		Author: WPIndeed Development

	Index WP MySQL For Speed
		Version: 1.4.12
		Author: Oliver Jones, Rick James

	Invoices for WooCommerce
		Version: 3.1.9
		Author: Bas Elbers

	Lazy Load - Optimize Images
		Version: 2.3.6
		Author: WP Rocket

	Loco Translate
		Version: 2.6.4
		Author: Tim Whitlock

	Newsletter, SMTP, Email marketing and Subscribe forms by Sendinblue
		Version: 3.1.58
		Author: Sendinblue

	OneSignal Push Notifications
		Version: 2.4.0
		Author: OneSignal

	Product Variation Swatches for Woocommerce
		Version: 2.3.2
		Author: ThemeHigh

	Sendinblue - WooCommerce Email Marketing
		Version: 3.0.4
		Author: Sendinblue

	Simple Google reCAPTCHA
		Version: 4.0
		Author: Michal Novák

	Site Kit by Google
		Version: 1.96.0
		Author: Google

	Slider Revolution
		Version: 6.6.12
		Author: ThemePunch

	Slider Revolution Holiday Snow
		Version: 3.0.5
		Author: ThemePunch

	Slider Revolution Lottie AddOn
		Version: 3.0.8
		Author: ThemePunch

	Slider Revolution Paint-Brush Add-On
		Version: 3.0.4
		Author: ThemePunch

	Slider Revolution Particles Effect
		Version: 3.3.2
		Author: ThemePunch

	Slider Revolution Particle Wave Add-On
		Version: 1.1.0
		Author: ThemePunch

	Slider Revolution Scroll Video Add-On
		Version: 3.0.4
		Author: ThemePunch

	Slider Revolution Transitionpack Add-On
		Version: 1.0.6
		Author: ThemePunch

	Ultimate Affiliate Pro Addon - Manage Reset Password
		Version: 1.5
		Author: WPIndeed

	WooCommerce
		Version: 7.5.1
		Author: Automattic

	WooCommerce Cart Abandonment Recovery
		Version: 1.2.23
		Author: CartFlows Inc

	WooCommerce Payments
		Version: 5.6.2
		Author: Automattic

	WooCommerce Shipping &amp; Tax
		Version: 2.2.4
		Author: WooCommerce

	WooCommerce Stripe Gateway
		Version: 7.2.0
		Author: WooCommerce

	Woodmart Core
		Version: 1.0.36
		Author: 

	WPS Hide Login
		Version: 1.9.8
		Author: WPServeur, NicolasKulka, wpformation

	Yoast SEO
		Version: 20.4
		Author: Team Yoast


== Must-Use Plugins ==
	Index WP MySQL For Speed Upgrade Filter for mu-plugins.
		Version: 1.4.12
		Author: 


== Caratteristiche ==
	Custom Fonts: 1
	Custom Icons: 0

== Integrazioni ==
	
	woocommerce: Attiva


== Esperimenti Elementor ==
	Uscita DOM ottimizzata: Attiva
	Caricamento delle risorse migliorato: Attiva
	Caricamento CSS migliorato: Attiva
	Icone dei font in linea: Attiva
	Miglioramenti dell&#039;accessibilità: Inattivo
	Punti di interruzione aggiuntivi: Inattivo
	admin_menu_rearrangement: Inattivo per impostazione predefinita
	Contenitore Flexbox: Inattivo
	Upgrade Swiper Library: Inattivo per impostazione predefinita
	Predefinito per Nuovo generatore di temi: Inattivo
	Editor Top Bar: Inattivo per impostazione predefinita
	Landing Page: Inattivo
	Nested Elements: Inattivo per impostazione predefinita
	Lazy Load Background Images: Inattivo per impostazione predefinita
	Transizioni pagine: Inattivo
	Notes: Inattivo
	Ciclico: Attivo per impostazione predefinita
	Snap scroll: Inattivo
	Menu: Inattivo per impostazione predefinita


== Registro ==
	
Log: showing 20 of 242022-10-31 10:49:48 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.7',
  'to' => '3.8.0',
)]
2022-10-31 10:49:50 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.7',
  'to' => '3.8.0',
)]
2022-11-04 14:53:42 [info] elementor::elementor_updater Started 
2022-11-04 14:53:42 [info] Elementor/Upgrades - _on_each_version Start  
2022-11-04 14:53:42 [info] Elementor/Upgrades - _on_each_version Finished 
2022-11-04 14:53:42 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.8',
  'to' => '3.8.0',
)]
2022-11-13 22:48:28 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.8.0',
  'to' => '3.8.1',
)]
2022-11-13 22:48:32 [info] elementor::elementor_updater Started 
2022-11-13 22:48:32 [info] Elementor/Upgrades - _on_each_version Start  
2022-11-13 22:48:32 [info] Elementor/Upgrades - _on_each_version Finished 
2022-11-13 22:48:32 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.8.0',
  'to' => '3.8.1',
)]
2022-11-13 22:48:33 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.8.0',
  'to' => '3.8.1',
)]
2023-03-30 08:44:22 [info] elementor::elementor_updater Started 
2023-03-30 08:44:22 [info] Elementor/Upgrades - _on_each_version Start  
2023-03-30 08:44:22 [info] Elementor/Upgrades - _on_each_version Finished 
2023-03-30 08:44:22 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.8.1',
  'to' => '3.12.0',
)]
2023-03-30 08:44:26 [info] elementor-pro::elementor_pro_updater Started 
2023-03-30 08:44:26 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-03-30 08:44:26 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-03-30 08:44:26 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.8.0',
  'to' => '3.12.0',
)]

JS: showing 13 of 13JS: 2022-11-10 16:13:28 [error X 8][https://revolution03.net/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.8.0:3:649119] this.model.isValidChild is not a function 
JS: 2022-11-11 13:48:18 [error X 20][https://revolution03.net/wp-admin/load-scripts.php?c=0&loadchunk_0=underscore,jquery-core,jquery-migrate,backbone,jquery-ui-core,jquery-ui-mouse,jquery-ui-draggable,wp-api-request,regenerator-run&loadchunk_1=time,wp-polyfill,wp-hooks&ver=6.1:4:51824] Cannot read properties of undefined (reading \&#039;replace\&#039;) 
JS: 2022-11-19 21:40:16 [error X 6265][https://revolution03.net/wp-content/plugins/elementor/assets/lib/pickr/pickr.min.js?ver=1.5.0:2:16820] Cannot read properties of null (reading \&#039;clone\&#039;) 
JS: 2022-11-19 21:40:19 [error X 189][https://revolution03.net/wp-content/plugins/elementor/assets/lib/pickr/pickr.min.js?ver=1.5.0:2:21012] Cannot read properties of null (reading \&#039;changestop\&#039;) 
JS: 2022-11-20 21:30:16 [error X 4][https://revolution03.net/wp-content/plugins/elementor/assets/js/new-template.min.js?ver=3.8.1:2:2932] elementor_new_template_form_controls is not defined 
JS: 2022-11-22 14:03:43 [error X 3][https://revolution03.net/wp-content/plugins/elementor-pro/assets/js/admin.min.js?ver=3.8.1:2:7984] Cannot read properties of null (reading \&#039;url\&#039;) 
JS: 2022-11-22 16:25:02 [error X 3][https://revolution03.net/wp-includes/js/dist/vendor/react-dom.min.js?ver=17.0.1:9:82426] Cannot read properties of undefined (reading \&#039;name\&#039;) 
JS: 2022-12-21 12:09:59 [error X 3][https://revolution03.net/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.9.1:3:258478] Cannot read properties of undefined (reading \&#039;val\&#039;) 
JS: 2023-02-08 16:03:43 [error X 4][https://revolution03.net/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.10.2:3:782338] Cannot read properties of undefined (reading &#039;localized&#039;) 
JS: 2023-02-26 10:21:18 [error X 289][https://revolution03.net/wp-content/plugins/elementor/assets/lib/pickr/pickr.min.js?ver=1.5.0:2:16820] Cannot read properties of null (reading &#039;clone&#039;) 
JS: 2023-02-26 10:21:18 [error X 8][https://revolution03.net/wp-content/plugins/elementor/assets/lib/pickr/pickr.min.js?ver=1.5.0:2:21012] Cannot read properties of null (reading &#039;changestop&#039;) 
JS: 2023-02-26 10:43:28 [error X 2][https://revolution03.net/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.11.2:3:559769] Blocked a frame with origin &quot;https://revolution03.net&quot; from accessing a cross-origin frame. 
JS: 2023-03-29 19:03:06 [error X 2][https://revolution03.net/wp-content/plugins/elementor-pro/assets/js/editor.min.js?ver=3.11.7:2:61404] Cannot convert undefined or null to object 

PHP: showing 5 of 5PHP: 2022-11-22 14:03:52 [warning X 3][/var/www/wptbox/wp-content/plugins/elementor-pro/modules/assets-manager/asset-types/icons/custom-icons.php::127] Invalid argument supplied for foreach() [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-11-22 14:15:16 [warning X 1][/var/www/wptbox/wp-content/plugins/elementor-pro/modules/assets-manager/asset-types/icons/custom-icons.php::195] unlink(Untitled Project.json): No such file or directory [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-11-22 16:24:56 [notice X 1][/var/www/wptbox/wp-content/plugins/elementor-pro/modules/assets-manager/asset-types/icons/custom-icons.php::444] Undefined index: name [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-02-26 10:43:57 [warning X 1][/home/u800343276/domains/revolution03.net/public_html/wp-content/plugins/elementor/modules/safe-mode/module.php::125] rmdir(/home/u800343276/domains/revolution03.net/public_html/wp-content/mu-plugins): Directory not empty [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-03-29 18:59:09 [warning X 5][/home/u800343276/domains/revolution03.net/public_html/wp-content/plugins/elementor-pro/modules/forms/classes/ajax-handler.php::121] Undefined array key &quot;form_fields&quot; [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]



== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatibilità non specificata

== Elementor Pro - Compatibility Tag ==
	



````

</details>

**Comment by baraapro** [comment] 2023-03-30 22:28
same problem here on woodmart theme and Hello Theme. cart widget is displayed empty.

**Comment by GiovanniGoccia** [comment] 2023-03-31 09:06
same problem with php 8.2 and theme oceanwp
The cart widget becomes empty when opening the woocommerce cart page. It resets if a new item is added to the cart.
It works on all pages until the cart page is opened, from then on it stops working.

**Comment by nicholaszein** [comment] 2023-03-31 11:52
Hello @Paky2002!

Thank you for your submission! 🙏 

### 🔗 🐞 This issue is a Duplicate of #21836 

Which is on the same subject. 

For this reason, I'm closing this thread and 🔃 **Merging** it with the original, so we can have all the discussions in one location, and deal with it more efficiently.

Feel free to continue the conversation there. 😉 

### 🔍 Please, in the future, remember to check if there isn't any thread similar to yours already opened. 

Best regards,

Nick

**Closed by nicholaszein** 2023-03-31 11:52 UTC
Labels: bug, compatibility/3rd_party, product/pro, component/woocommerce, component/menu-cart

**Comment by nicholaszein** [comment] 2023-04-24 20:34
Hello, we have an update on this issue.

Please refer to [this comment](https://github.com/elementor/elementor/issues/21836#issuecomment-1520791070).

Kind regards
