### ISSUE TITLE
Mobile Responsive Settings do not apply for custom loop template

### ISSUE THREAD

**Issue by Lowrider0** [elementor/elementor#19906] opened 2022-09-24 22:47 UTC
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

When I want to change the Border Radius of the column in the Theme Builder Template "Loop" that I created using the Plugin Ele Custom Skin, the Border Radius is always applied from the Desktop Setting in Elementor, the mobile option is ignored. Means if I look at the page in mobile mode in the dev tools, the Desktop setting is shown, instead of the Mobile setting of Border Radius. 

Is this an Elementor or Ele Custom Skin issue?

Thanks.

### Steps to reproduce

1) Install Ele Custom Skin
2) Create a Loop template
3) Try to optimize the template for mobile, work with border radius on mobile and desktop settings.
4) Open dev tools, mobile version. The desktop settings always apply, the mobile settings are ignored.

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: WINNT
	Software: nginx/1.16.0
	MySQL version: MySQL Community Server - GPL v8.0.16
	PHP Version: 7.4.1
	PHP Memory Limit: 256M
	PHP Max Input Vars: 4000
	PHP Max Post Size: 1000M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.0.2
	Site URL: http://propertysite.local
	Home URL: http://propertysite.local
	WP Multisite: No
	Max Upload Size: 300 MB
	Memory limit: 40M
	Max Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 0
	Admin Email: dev-email@flywheel.local
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.6.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36

== Active Plugins ==
	Advanced Custom Fields PRO
		Version: 5.12.3
		Author: Delicious Brains

	Classic Editor
		Version: 1.6.2
		Author: WordPress Contributors

	Custom Post Type UI
		Version: 1.13.1
		Author: WebDevStudios

	DynamicConditions
		Version: 1.6.0
		Author: RTO GmbH

	Ele Custom Skin
		Version: 3.1.0 - beta 2
		Author: Dudaster.com

	Elementor
		Version: 3.7.7
		Author: Elementor.com

	Elementor Pro
		Version: 3.1.0
		Author: Elementor.com

	Font Awesome
		Version: 4.3.1
		Author: Font Awesome

	Simple Custom CSS and JS
		Version: 3.40
		Author: SilkyPress.com

	Solid Dynamics
		Version: 1.2.0
		Author: Solid Digital

== Elementor Experiments ==
	Optimized DOM Output: Active by default
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Active by default
	Additional Custom Breakpoints: Active by default
	Import Export Template Kit: Active by default
	Hide native WordPress widgets from search results: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Inactive by default
	Hello Theme Header & Footer: Active by default
	Landing Pages: Active by default
	Color Sampler: Active by default
	Favorite Widgets: Active by default
	Admin Top Bar: Active by default

== Log ==
	
PHP: showing 20 of 28PHP: 2022-08-28 18:31:03 [notice X 98][C:\Users\luca-\Local Sites\propertysite\app\public\wp-content\plugins\elementor\modules\dev-tools\deprecation.php::304] The $control_id argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: C:\Users\luca-\Local Sites\propertysite\app\public\wp-content\plugins\elementor\modules\dev-tools\deprecation.php(304): class type trigger_error()
#2: C:\Users\luca-\Local Sites\propertysite\app\public\wp-content\plugins\elementor\includes\managers\controls.php(523): Elementor\Modules\DevTools\Deprecation -> deprecated_argument()
#3: C:\Users\luca-\Local Sites\propertysite\app\public\wp-content\plugins\elementor\includes\managers\controls.php(501): Elementor\Controls_Manager -> register()
#4: C:\Users\luca-\Local Sites\propertysite\app\public\wp-content\plugins\elementor-pro\modules\theme-builder\module.php(162): Elementor\Controls_Manager -> register_control()
',
)]
PHP: 2022-08-28 18:31:03 [notice X 98][C:\Users\luca-\Local Sites\propertysite\app\public\wp-content\plugins\elementor\modules\dev-tools\deprecation.php::304] The $control_id argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: C:\Users\luca-\Local Sites\propertysite\app\public\wp-content\plugins\elementor\modules\dev-tools\deprecation.php(304): class type trigger_error()
#2: C:\Users\luca-\Local Sites\propertysite\app\public\wp-content\plugins\elementor\includes\managers\controls.php(523): Elementor\Modules\DevTools\Deprecation -> deprecated_argument()
#3: C:\Users\luca-\Local Sites\propertysite\app\public\wp-content\plugins\elementor\includes\managers\controls.php(501): Elementor\Controls_Manager -> register()
#4: C:\Users\luca-\Local Sites\propertysite\app\public\wp-content\plugins\elementor-pro\modules\forms\module.php(69): Elementor\Controls_Manager -> register_control()
',
)]
PHP: 2022-08-28 18:31:03 [notice X 98][C:\Users\luca-\Local Sites\propertysite\app\public\wp-content\plugins\elementor\modules\dev-tools\deprecation.php::304] The $control_id argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: C:\Users\luca-\Local Sites\propertysite\app\public\wp-content\plugins\elementor\modules\dev-tools\deprecation.php(304): class type trigger_error()
#2: C:\Users\luca-\Local Sites\propertysite\app\public\wp-content\plugins\elementor\includes\managers\controls.php(523): Elementor\Modules\DevTools\Deprecation -> deprecated_argument()
#3: C:\Users\luca-\Local Sites\propertysite\app\public\wp-content\plugins\elementor\includes\managers\controls.php(501): Elementor\Controls_Manager -> register()
#4: C:\Users\luca-\Local Sites\propertysite\app\public\wp-content\plugins\elementor-pro\modules\forms\module.php(70): Elementor\Controls_Manager -> register_control()
',
)]
PHP: 2022-08-28 18:51:33 [notice X 67][C:\Users\luca-\Local Sites\propertysite\app\public\wp-content\plugins\elementor-pro\modules\dynamic-tags\acf\tags\acf-text.php::33] Undefined offset: 1 [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-08-28 18:54:06 [error X 4][C:\Users\luca-\Local Sites\propertysite\app\public\wp-content\plugins\elementor-pro\modules\theme-builder\classes\conditions-manager.php::281] Uncaught Error: Call to a member function update_meta() on null in C:\Users\luca-\Local Sites\propertysite\app\public\wp-content\plugins\elementor-pro\modules\theme-builder\classes\conditions-manager.php:281
Stack trace:
#0 C:\Users\luca-\Local Sites\propertysite\app\public\wp-content\plugins\elementor-pro\modules\theme-builder\classes\conditions-manager.php(162): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions(5, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 C:\Users\luca-\Local Sites\propertysite\app\public\wp-content\plugins\elementor\core\common\modules\ajax\module.php(171): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 C:\Users\luca-\Local Sites\propertysite\app\public\wp-includes\class-wp-hook.php(307): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#4 C:\Users\luca-\Local Sit [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-08-29 19:01:14 [error X 2][C:\Users\luca-\Local Sites\propertysite\app\public\wp-content\plugins\elementor-pro\modules\theme-builder\classes\conditions-manager.php::281] Uncaught Error: Call to a member function update_meta() on bool in C:\Users\luca-\Local Sites\propertysite\app\public\wp-content\plugins\elementor-pro\modules\theme-builder\classes\conditions-manager.php:281
Stack trace:
#0 C:\Users\luca-\Local Sites\propertysite\app\public\wp-content\plugins\elementor-pro\modules\theme-builder\classes\conditions-manager.php(162): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions(NULL, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 C:\Users\luca-\Local Sites\propertysite\app\public\wp-content\plugins\elementor\core\common\modules\ajax\module.php(171): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 C:\Users\luca-\Local Sites\propertysite\app\public\wp-includes\class-wp-hook.php(307): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#4 C:\Users\luca-\Local  [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-09-01 19:55:26 [notice X 18][C:\Users\luca-\Local Sites\propertysite\app\public\wp-content\plugins\elementor-pro\modules\theme-builder\documents\theme-document.php::49] Undefined variable: method [array (
  'trace' => '
#0: C:\Users\luca-\Local Sites\propertysite\app\public\wp-content\plugins\elementor-pro\modules\theme-builder\documents\theme-document.php(49): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: C:\Users\luca-\Local Sites\propertysite\app\public\wp-content\plugins\elementor-pro\modules\theme-builder\documents\theme-document.php(85): ElementorPro\Modules\ThemeBuilder\Documents\Theme_Document :: get_site_editor_type_bc()
#2: C:\Users\luca-\Local Sites\propertysite\app\public\wp-content\plugins\elementor-pro\core\app\modules\site-editor\data\endpoints\templates.php(165): ElementorPro\Modules\ThemeBuilder\Documents\Theme_Document :: get_site_editor_config()
#3: ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_template_json_item()
#4: C:\Users\luca-\Local Sites\propertysite\app\public\wp-content\plugins\elementor-pro\core\app\modules\site-editor\data\endpoints\templates.php(120): class type array_map()
',
)]
PHP: 2022-09-01 19:55:26 [notice X 18][C:\Users\luca-\Local Sites\propertysite\app\public\wp-content\plugins\elementor-pro\modules\theme-builder\documents\theme-document.php::49] Trying to get property 'class' of non-object [array (
  'trace' => '
#0: C:\Users\luca-\Local Sites\propertysite\app\public\wp-content\plugins\elementor-pro\modules\theme-builder\documents\theme-document.php(49): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: C:\Users\luca-\Local Sites\propertysite\app\public\wp-content\plugins\elementor-pro\modules\theme-builder\documents\theme-document.php(85): ElementorPro\Modules\ThemeBuilder\Documents\Theme_Document :: get_site_editor_type_bc()
#2: C:\Users\luca-\Local Sites\propertysite\app\public\wp-content\plugins\elementor-pro\core\app\modules\site-editor\data\endpoints\templates.php(165): ElementorPro\Modules\ThemeBuilder\Documents\Theme_Document :: get_site_editor_config()
#3: ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_template_json_item()
#4: C:\Users\luca-\Local Sites\propertysite\app\public\wp-content\plugins\elementor-pro\core\app\modules\site-editor\data\endpoints\templates.php(120): class type array_map()
',
)]
PHP: 2022-09-01 19:55:26 [notice X 18][C:\Users\luca-\Local Sites\propertysite\app\public\wp-content\plugins\elementor-pro\modules\theme-builder\documents\theme-document.php::49] Undefined variable: method [array (
  'trace' => '
#0: C:\Users\luca-\Local Sites\propertysite\app\public\wp-content\plugins\elementor-pro\modules\theme-builder\documents\theme-document.php(49): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: C:\Users\luca-\Local Sites\propertysite\app\public\wp-content\plugins\elementor-pro\modules\theme-builder\documents\theme-document.php(68): ElementorPro\Modules\ThemeBuilder\Documents\Theme_Document :: get_site_editor_type_bc()
#2: C:\Users\luca-\Local Sites\propertysite\app\public\wp-content\plugins\elementor-pro\modules\theme-builder\documents\theme-document.php(92): ElementorPro\Modules\ThemeBuilder\Documents\Theme_Document :: get_site_editor_route()
#3: C:\Users\luca-\Local Sites\propertysite\app\public\wp-content\plugins\elementor-pro\core\app\modules\site-editor\data\endpoints\templates.php(165): ElementorPro\Modules\ThemeBuilder\Documents\Theme_Document :: get_site_editor_config()
#4: ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_template_json_item()
',
)]
PHP: 2022-09-01 19:55:26 [notice X 18][C:\Users\luca-\Local Sites\propertysite\app\public\wp-content\plugins\elementor-pro\modules\theme-builder\documents\theme-document.php::49] Trying to get property 'class' of non-object [array (
  'trace' => '
#0: C:\Users\luca-\Local Sites\propertysite\app\public\wp-content\plugins\elementor-pro\modules\theme-builder\documents\theme-document.php(49): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: C:\Users\luca-\Local Sites\propertysite\app\public\wp-content\plugins\elementor-pro\modules\theme-builder\documents\theme-document.php(68): ElementorPro\Modules\ThemeBuilder\Documents\Theme_Document :: get_site_editor_type_bc()
#2: C:\Users\luca-\Local Sites\propertysite\app\public\wp-content\plugins\elementor-pro\modules\theme-builder\documents\theme-document.php(92): ElementorPro\Modules\ThemeBuilder\Documents\Theme_Document :: get_site_editor_route()
#3: C:\Users\luca-\Local Sites\propertysite\app\public\wp-content\plugins\elementor-pro\core\app\modules\site-editor\data\endpoints\templates.php(165): ElementorPro\Modules\ThemeBuilder\Documents\Theme_Document :: get_site_editor_config()
#4: ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_template_json_item()
',
)]
PHP: 2022-09-01 19:55:26 [notice X 18][C:\Users\luca-\Local Sites\propertysite\app\public\wp-content\plugins\elementor-pro\modules\theme-builder\documents\theme-document.php::49] Undefined variable: method [array (
  'trace' => '
#0: C:\Users\luca-\Local Sites\propertysite\app\public\wp-content\plugins\elementor-pro\modules\theme-builder\documents\theme-document.php(49): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: C:\Users\luca-\Local Sites\propertysite\app\public\wp-content\plugins\elementor-pro\modules\theme-builder\documents\theme-document.php(68): ElementorPro\Modules\ThemeBuilder\Documents\Theme_Document :: get_site_editor_type_bc()
#2: C:\Users\luca-\Local Sites\propertysite\app\public\wp-content\plugins\elementor-pro\modules\theme-builder\documents\theme-document.php(95): ElementorPro\Modules\ThemeBuilder\Documents\Theme_Document :: get_site_editor_route()
#3: C:\Users\luca-\Local Sites\propertysite\app\public\wp-content\plugins\elementor-pro\core\app\modules\site-editor\data\endpoints\templates.php(165): ElementorPro\Modules\ThemeBuilder\Documents\Theme_Document :: get_site_editor_config()
#4: ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_template_json_item()
',
)]
PHP: 2022-09-01 19:55:26 [notice X 18][C:\Users\luca-\Local Sites\propertysite\app\public\wp-content\plugins\elementor-pro\modules\theme-builder\documents\theme-document.php::49] Trying to get property 'class' of non-object [array (
  'trace' => '
#0: C:\Users\luca-\Local Sites\propertysite\app\public\wp-content\plugins\elementor-pro\modules\theme-builder\documents\theme-document.php(49): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: C:\Users\luca-\Local Sites\propertysite\app\public\wp-content\plugins\elementor-pro\modules\theme-builder\documents\theme-document.php(68): ElementorPro\Modules\ThemeBuilder\Documents\Theme_Document :: get_site_editor_type_bc()
#2: C:\Users\luca-\Local Sites\propertysite\app\public\wp-content\plugins\elementor-pro\modules\theme-builder\documents\theme-document.php(95): ElementorPro\Modules\ThemeBuilder\Documents\Theme_Document :: get_site_editor_route()
#3: C:\Users\luca-\Local Sites\propertysite\app\public\wp-content\plugins\elementor-pro\core\app\modules\site-editor\data\endpoints\templates.php(165): ElementorPro\Modules\ThemeBuilder\Documents\Theme_Document :: get_site_editor_config()
#4: ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_template_json_item()
',
)]
PHP: 2022-09-01 19:55:26 [notice X 11][C:\Users\luca-\Local Sites\propertysite\app\public\wp-content\plugins\elementor-pro\modules\theme-builder\documents\theme-document.php::49] Undefined variable: method [array (
  'trace' => '
#0: C:\Users\luca-\Local Sites\propertysite\app\public\wp-content\plugins\elementor-pro\modules\theme-builder\documents\theme-document.php(49): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: C:\Users\luca-\Local Sites\propertysite\app\public\wp-content\plugins\elementor-pro\modules\theme-builder\documents\theme-document.php(127): ElementorPro\Modules\ThemeBuilder\Documents\Theme_Document :: get_site_editor_type_bc()
#2: C:\Users\luca-\Local Sites\propertysite\app\public\wp-content\plugins\elementor-pro\modules\theme-builder\documents\archive-single-base.php(22): ElementorPro\Modules\ThemeBuilder\Documents\Theme_Document :: get_create_url()
#3: C:\Users\luca-\Local Sites\propertysite\app\public\wp-content\plugins\elementor-pro\modules\theme-builder\documents\theme-document.php(96): ElementorPro\Modules\ThemeBuilder\Documents\Archive_Single_Base :: get_create_url()
#4: C:\Users\luca-\Local Sites\propertysite\app\public\wp-content\plugins\elementor-pro\core\app\modules\site-editor\data\endpoints\templates.php(165): ElementorPro\Modules\ThemeBuilder\Documents\Theme_Document :: get_site_editor_config()
',
)]
PHP: 2022-09-01 19:55:26 [notice X 11][C:\Users\luca-\Local Sites\propertysite\app\public\wp-content\plugins\elementor-pro\modules\theme-builder\documents\theme-document.php::49] Trying to get property 'class' of non-object [array (
  'trace' => '
#0: C:\Users\luca-\Local Sites\propertysite\app\public\wp-content\plugins\elementor-pro\modules\theme-builder\documents\theme-document.php(49): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: C:\Users\luca-\Local Sites\propertysite\app\public\wp-content\plugins\elementor-pro\modules\theme-builder\documents\theme-document.php(127): ElementorPro\Modules\ThemeBuilder\Documents\Theme_Document :: get_site_editor_type_bc()
#2: C:\Users\luca-\Local Sites\propertysite\app\public\wp-content\plugins\elementor-pro\modules\theme-builder\documents\archive-single-base.php(22): ElementorPro\Modules\ThemeBuilder\Documents\Theme_Document :: get_create_url()
#3: C:\Users\luca-\Local Sites\propertysite\app\public\wp-content\plugins\elementor-pro\modules\theme-builder\documents\theme-document.php(96): ElementorPro\Modules\ThemeBuilder\Documents\Archive_Single_Base :: get_create_url()
#4: C:\Users\luca-\Local Sites\propertysite\app\public\wp-content\plugins\elementor-pro\core\app\modules\site-editor\data\endpoints\templates.php(165): ElementorPro\Modules\ThemeBuilder\Documents\Theme_Document :: get_site_editor_config()
',
)]
PHP: 2022-09-01 19:55:26 [notice X 15][C:\Users\luca-\Local Sites\propertysite\app\public\wp-content\plugins\elementor-pro\modules\theme-builder\documents\theme-document.php::49] Undefined variable: method [array (
  'trace' => '
#0: C:\Users\luca-\Local Sites\propertysite\app\public\wp-content\plugins\elementor-pro\modules\theme-builder\documents\theme-document.php(49): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: C:\Users\luca-\Local Sites\propertysite\app\public\wp-content\plugins\elementor-pro\modules\theme-builder\documents\theme-document.php(80): ElementorPro\Modules\ThemeBuilder\Documents\Theme_Document :: get_site_editor_type_bc()
#2: C:\Users\luca-\Local Sites\propertysite\app\public\wp-content\plugins\elementor-pro\modules\theme-builder\documents\theme-document.php(97): ElementorPro\Modules\ThemeBuilder\Documents\Theme_Document :: get_site_editor_thumbnail_url()
#3: C:\Users\luca-\Local Sites\propertysite\app\public\wp-content\plugins\elementor-pro\core\app\modules\site-editor\data\endpoints\templates.php(165): ElementorPro\Modules\ThemeBuilder\Documents\Theme_Document :: get_site_editor_config()
#4: ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_template_json_item()
',
)]
PHP: 2022-09-01 19:55:26 [notice X 15][C:\Users\luca-\Local Sites\propertysite\app\public\wp-content\plugins\elementor-pro\modules\theme-builder\documents\theme-document.php::49] Trying to get property 'class' of non-object [array (
  'trace' => '
#0: C:\Users\luca-\Local Sites\propertysite\app\public\wp-content\plugins\elementor-pro\modules\theme-builder\documents\theme-document.php(49): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: C:\Users\luca-\Local Sites\propertysite\app\public\wp-content\plugins\elementor-pro\modules\theme-builder\documents\theme-document.php(80): ElementorPro\Modules\ThemeBuilder\Documents\Theme_Document :: get_site_editor_type_bc()
#2: C:\Users\luca-\Local Sites\propertysite\app\public\wp-content\plugins\elementor-pro\modules\theme-builder\documents\theme-document.php(97): ElementorPro\Modules\ThemeBuilder\Documents\Theme_Document :: get_site_editor_thumbnail_url()
#3: C:\Users\luca-\Local Sites\propertysite\app\public\wp-content\plugins\elementor-pro\core\app\modules\site-editor\data\endpoints\templates.php(165): ElementorPro\Modules\ThemeBuilder\Documents\Theme_Document :: get_site_editor_config()
#4: ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_template_json_item()
',
)]
PHP: 2022-09-01 20:46:25 [notice X 7][C:\Users\luca-\Local Sites\propertysite\app\public\wp-content\plugins\elementor-pro\modules\theme-builder\documents\theme-document.php::49] Undefined variable: method [array (
  'trace' => '
#0: C:\Users\luca-\Local Sites\propertysite\app\public\wp-content\plugins\elementor-pro\modules\theme-builder\documents\theme-document.php(49): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: C:\Users\luca-\Local Sites\propertysite\app\public\wp-content\plugins\elementor-pro\modules\theme-builder\documents\theme-document.php(127): ElementorPro\Modules\ThemeBuilder\Documents\Theme_Document :: get_site_editor_type_bc()
#2: C:\Users\luca-\Local Sites\propertysite\app\public\wp-content\plugins\elementor-pro\modules\theme-builder\documents\theme-document.php(96): ElementorPro\Modules\ThemeBuilder\Documents\Theme_Document :: get_create_url()
#3: C:\Users\luca-\Local Sites\propertysite\app\public\wp-content\plugins\elementor-pro\core\app\modules\site-editor\data\endpoints\templates.php(165): ElementorPro\Modules\ThemeBuilder\Documents\Theme_Document :: get_site_editor_config()
#4: ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_template_json_item()
',
)]
PHP: 2022-09-01 20:46:25 [notice X 7][C:\Users\luca-\Local Sites\propertysite\app\public\wp-content\plugins\elementor-pro\modules\theme-builder\documents\theme-document.php::49] Trying to get property 'class' of non-object [array (
  'trace' => '
#0: C:\Users\luca-\Local Sites\propertysite\app\public\wp-content\plugins\elementor-pro\modules\theme-builder\documents\theme-document.php(49): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: C:\Users\luca-\Local Sites\propertysite\app\public\wp-content\plugins\elementor-pro\modules\theme-builder\documents\theme-document.php(127): ElementorPro\Modules\ThemeBuilder\Documents\Theme_Document :: get_site_editor_type_bc()
#2: C:\Users\luca-\Local Sites\propertysite\app\public\wp-content\plugins\elementor-pro\modules\theme-builder\documents\theme-document.php(96): ElementorPro\Modules\ThemeBuilder\Documents\Theme_Document :: get_create_url()
#3: C:\Users\luca-\Local Sites\propertysite\app\public\wp-content\plugins\elementor-pro\core\app\modules\site-editor\data\endpoints\templates.php(165): ElementorPro\Modules\ThemeBuilder\Documents\Theme_Document :: get_site_editor_config()
#4: ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_template_json_item()
',
)]
PHP: 2022-09-01 21:01:11 [notice X 15][C:\Users\luca-\Local Sites\propertysite\app\public\wp-content\plugins\elementor\includes\managers\image.php::105] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-09-02 21:35:31 [notice X 2][C:\Users\luca-\Local Sites\propertysite\app\public\wp-content\plugins\elementor\core\common\modules\ajax\module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

Log: showing 10 of 102022-09-05 21:23:09 [info] elementor::elementor_updater Started 
2022-09-05 21:23:09 [info] Elementor/Upgrades - _on_each_version Start  
2022-09-05 21:23:09 [info] Elementor/Upgrades - _on_each_version Finished 
2022-09-05 21:23:09 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.2',
  'to' => '3.7.4',
)]
2022-09-05 21:23:09 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.2',
  'to' => '3.7.4',
)]
2022-09-21 22:30:10 [info] elementor::elementor_updater Started 
2022-09-21 22:30:10 [info] Elementor/Upgrades - _on_each_version Start  
2022-09-21 22:30:10 [info] Elementor/Upgrades - _on_each_version Finished 
2022-09-21 22:30:10 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.4',
  'to' => '3.7.7',
)]
2022-09-21 22:30:10 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.4',
  'to' => '3.7.7',
)]

JS: showing 2 of 2JS: 2022-09-07 21:40:14 [error X 2][http://propertysite.local/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.7.4:3:1060434] Cannot read properties of null (reading \'getBoundingClientRect\') 
JS: 2022-09-24 01:35:31 [error X 1][http://propertysite.local/wp-admin/post.php?post=501&action=elementor#:1:1] Identifier \'$dcWidgetIdInput\' has already been declared 

== Elementor - Compatibility Tag ==
	
	Ele Custom Skin: Incompatible
	Elementor Pro: Incompatible

== Elementor Pro - Compatibility Tag ==
	
	Ele Custom Skin: Compatible

**Comment by nicholaszein** [comment] 2022-09-28 09:53
Hello @Lowrider0,

Thank you for reaching out! 🙏 

While we do welcome bug reports, we can't provide support for 3rd party add-ons.

If your issue is specifically happening only when you're using a feature from a 3rd party add-on, or only when the 3rd party add-on is active, you'll need to contact the support for that add-on or its developers.

To make sure the issue is not being caused by Elementor and isolate this conflict please try these **Troubleshooting steps**:

⚠️  Backup your website before proceeding, and if possible do it in a staging environment! ⚠️ 

1. Disable/Deactivate all your plugins except **Elementor** (and **Elementor Pro**).
    - If this solves the problem, gradually re-activate plugin-by-plugin (and check if the problem returns) to identify the problematic or conflicting plugin. In this case, contact the plugin support as we don't provide support for 3rd party plugins.
    - If it doesn't solve your problem, try the next step:
2.  Change your WordPress theme to the [Hello Elementor](https://wordpress.org/themes/hello-elementor/) theme and check if the problem is solved.
3.  Clear all types of cache, including but not limited to **Server cache**, **WordPress (optimization plugin) cache**, **CDN cache**, and **Browser cache**. Also, try visiting the front page of your website in **incognito/private** mode.
4. Make sure the server resources allocated to your site and WordPress installation meet our [Requirements](https://elementor.com/help/requirements/). To check this information go to your _WordPress Dashboard > Elementor > System Info_, and check both your **Server Environment** and **WordPress Environment** tables. You can also scroll down to the end of the **System Info** page and click on the **Download System Info** button. Then submit another comment here and drop the `.txt` file inside the text box to upload your system information and share it with us.

If after following these steps the problem persists, you can submit a new issue with details to reproduce it so we can take a look. For now, I'll be closing this issue.

Regards

**Closed by nicholaszein** 2022-09-28 09:53 UTC
Labels: compatibility/3rd_party
