### ISSUE TITLE
🚀 Feature Request: Form/Action - Add User Registration Action After Submit (Duplicate of #5184)

### ISSUE THREAD

**Issue by mramirezklapp** [elementor/elementor#5886] opened 2018-10-09 15:55 UTC
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
I guess the form widget is the weakest part of Elementor pro, because it lacks miss some functionalities that could make this tool into a better one.

**Describe the solution you'd like**

1. Create a custom registration form. 
2. Form validations: 
     (a) with regular expressions; 
     (b) for dates, in order to allow that one be less o greater than other; 
     (c) for numbers: type (real or integer), range;
     (d) that allow the user to write a custom validation rule in JavaScript, among others.

**Describe alternatives you've considered**
Just for now, I've seeking for some plugins, but I hope you can implement those things in the short term.

**Additional context**
Nothing to add.

Thanks in advance.

**Comment by bainternet** [comment] 2018-10-10 13:08
@mramirezklapp 

1) Duplicate of #5184

2) What's stopping you form adding your custom validation?

**Comment by mramirezklapp** [comment] 2018-10-10 13:12
Hi.

I don't want to use a third party plugin. I'd like to work only with Elementor Pro.

And #5184 looks like my post, but mine includes more specific details :)

**Comment by tmhopper** [comment] 2018-10-16 22:16
@mramirezklapp  @bainternet 
Has there been a resolve to this yet? I would also love to figure out how to create registration forms with Elementor

The need of a third party plugin for this button is not ideal

Ive been searching how to do this and been coming up empty

@bainternet I see you created a code...would you be able to share it?

**Closed** 2018-10-18 07:21 UTC
Labels: request/enhancement, component/form/actions, mod*

**Comment by nicholaszein** [comment] 2022-10-07 17:57
Hello

Thank you for your submission! 🙏 

📋 This issue is a **Duplicate** of #5184, which is on the same subject. For this reason, I'm ↔️ **Merging** it with the original, so we can have all the discussion in one location, and deal with it more efficiently.

Please feel free to continue the conversation there. 😉 

In the future, remember to check if there isn't an issue similar to yours already opened. ✔️ 

Best regards,

Nick
