### ISSUE TITLE
Gallery widget doesn't show correct pictures with Post Image Attachment dynamic tag

### ISSUE THREAD

**Issue by Iti1980** [elementor/elementor#11471] opened 2020-05-25 18:01 UTC
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

Premix: the website is under construction so don't considera the content used

I added a new post and used the gallery block to attach 3 pictures from the media library.
![Add new post](https://user-images.githubusercontent.com/65508986/82834182-a2c5c180-9ec0-11ea-808f-fffd83963118.jpg)
![Adding gallery in the post](https://user-images.githubusercontent.com/65508986/82834183-a35e5800-9ec0-11ea-8f0d-f981c108af38.jpg)

I created a template applied to all the posts and I added a basic gallery widget with a dynamic tag that correspond to the Post Image Attachment.
![Gallery with dynamic tag](https://user-images.githubusercontent.com/65508986/82834238-ca1c8e80-9ec0-11ea-970a-b68159df00eb.jpg)

When I visualize the article I can't see the three pictures. In some articles instead I see pictures that I have never selected in the gallery block (pic1-2).
![Gallery not displayed](https://user-images.githubusercontent.com/65508986/82834247-d0ab0600-9ec0-11ea-93ba-7e6259466d8d.jpg)

I use Elementor Pro and Hello theme.
I tried to deactivate all the plugin and to change the theme with Twenty Sixteen but nothing.

## Steps to reproduce

The steps are the same at the point above.
1) Add new post
2) Add a native wordpress gallery block
3) Create a template for all the posts and use a gallery widget with Post Image Attachment as dynamic tag
3) Visualize the article

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Source distribution v5.7.25-28
	PHP Version: 7.3.18
	PHP Max Input Vars: 3000
	PHP Max Post Size: 128M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.4.1
	Site URL: https://www.itineriamo.com
	Home URL: https://www.itineriamo.com
	WP Multisite: No
	Max Upload Size: 128 MB
	Memory limit: 768M
	Permalink Structure: /%postname%/
	Language: it-IT
	Timezone: Europe/Rome
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.3.0
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: it_IT
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36

== Active Plugins ==
	Advanced Custom Fields
		Version: 5.8.11
		Author: Elliot Condon

	Custom Post Type UI
		Version: 1.7.4
		Author: WebDevStudios

	Elementor
		Version: 2.9.9
		Author: Elementor.com

	Elementor Addon Elements
		Version: 1.6.4
		Author: WebTechStreet

	Elementor Pro
		Version: 2.9.5
		Author: Elementor.com

	Relevanssi
		Version: 4.7.2.1
		Author: Mikko Saari

	Search & Filter
		Version: 1.2.12
		Author: Designs & Code

	Shortcoder
		Version: 5.3.1
		Author: Aakash Chakravarthy

	Ultimate Maps by Supsystic
		Version: 1.1.10
		Author: supsystic.com

	Under Construction
		Version: 3.75
		Author: WebFactory Ltd


== Elements Usage ==
	
	archive : 2
		archive-posts : 2
		heading : 2
		spacer : 4
	footer : 1
		form : 1
		heading : 1
		html : 1
		icon : 1
		image : 1
	header : 1
		image : 1
		nav-menu : 1
		search-form : 1
		social-icons : 1
	single : 4
		divider : 2
		heading : 2
		icon-list : 2
		image-gallery : 1
		post-comments : 1
		post-info : 1
		share-buttons : 1
		shortcode : 1
		spacer : 3
		text-editor : 2
	wp-post : 4
		text-editor : 2
	wp-page : 3
		author-box : 1
		call-to-action : 1
		counter : 4
		divider : 4
		form : 1
		heading : 12
		media-carousel : 1
		post-info : 1
		posts : 1
		shortcode : 2
		spacer : 7


== Log ==
	
PHP: showing 13 of 13PHP: 2020-05-06 15:41:24 [warning X 3][/home/customer/www/itineriamo.com/public_html/wp-content/plugins/elementor-pro/modules/assets-manager/asset-types/icons/icon-sets/icomoon.php::31] file_get_contents(/tmp/icomoon-1/selection.json): failed to open stream: No such file or directory [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-05-06 15:42:37 [warning X 1][/home/customer/www/itineriamo.com/public_html/wp-content/plugins/elementor-pro/modules/assets-manager/asset-types/icons/icon-sets/icomoon.php::31] file_get_contents(/tmp/icomoon-2/selection.json): failed to open stream: No such file or directory [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-05-06 15:44:26 [warning X 1][/home/customer/www/itineriamo.com/public_html/wp-content/plugins/elementor-pro/modules/assets-manager/asset-types/icons/icon-sets/icomoon.php::31] file_get_contents(/tmp/icomoon-3/selection.json): failed to open stream: No such file or directory [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-05-07 11:52:31 [notice X 1][/home/customer/www/itineriamo.com/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::180] Undefined index: editor_post_id [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-05-07 15:47:38 [warning X 1][/home/customer/www/itineriamo.com/public_html/wp-content/plugins/elementor-pro/modules/assets-manager/asset-types/icons/icon-sets/icomoon.php::31] file_get_contents(/tmp/icomoon-4/selection.json): failed to open stream: No such file or directory [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-05-08 23:39:59 [notice X 4][/home/customer/www/itineriamo.com/public_html/wp-content/plugins/elementor-pro/modules/posts/widgets/portfolio.php::49] Undefined index: posts_post_type [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-05-10 16:41:53 [notice X 65][/home/customer/www/itineriamo.com/public_html/wp-content/plugins/elementor-pro/modules/dynamic-tags/acf/tags/acf-url.php::35] Undefined offset: 1 [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-05-13 00:54:07 [error X 1][/home/customer/www/itineriamo.com/public_html/wp-content/plugins/elementor/includes/template-library/sources/local.php::1044] Uncaught TypeError: Argument 2 passed to Elementor\TemplateLibrary\Source_Local::on_save_post() must be an instance of WP_Post, instance of stdClass given, called in /home/customer/www/itineriamo.com/public_html/wp-includes/class-wp-hook.php on line 289 and defined in /home/customer/www/itineriamo.com/public_html/wp-content/plugins/elementor/includes/template-library/sources/local.php:1044
Stack trace:
#0 /home/customer/www/itineriamo.com/public_html/wp-includes/class-wp-hook.php(289): Elementor\TemplateLibrary\Source_Local->on_save_post(1219, Object(stdClass))
#1 /home/customer/www/itineriamo.com/public_html/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters(NULL, Array)
#2 /home/customer/www/itineriamo.com/public_html/wp-includes/plugin.php(478): WP_Hook->do_action(Array)
#3 /home/customer/www/itineriamo.com/public_html/wp-includes/post.php(4153): do_action('save_post', 1219, Object(stdClass), true)
#4 /home/customer/www/itineriamo.com/public_html/wp-includes/post.php(4244): wp_insert_post(Array, fa [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-05-16 21:54:01 [notice X 1][/home/customer/www/itineriamo.com/public_html/wp-content/plugins/elementor/includes/template-library/sources/local.php::771] ob_end_flush(): failed to delete and flush buffer. No buffer to delete or flush [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-05-16 21:54:24 [notice X 3][/home/customer/www/itineriamo.com/public_html/wp-content/plugins/elementor/includes/template-library/sources/local.php::692] ob_end_clean(): failed to delete buffer. No buffer to delete [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-05-17 15:39:07 [error X 1][/home/customer/www/itineriamo.com/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::259] Uncaught Error: Call to a member function update_meta() on bool in /home/customer/www/itineriamo.com/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:259
Stack trace:
#0 /home/customer/www/itineriamo.com/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(180): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions(NULL, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /home/customer/www/itineriamo.com/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /home/customer/www/itineriamo.com/public_html/wp-includes/class-wp-hook.php(287): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#4 /home/customer/www/itineriamo.com/public_ [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-05-19 11:57:35 [error X 1][/home/customer/www/itineriamo.com/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::259] Uncaught Error: Call to a member function update_meta() on null in /home/customer/www/itineriamo.com/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:259
Stack trace:
#0 /home/customer/www/itineriamo.com/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(180): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions(825, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /home/customer/www/itineriamo.com/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /home/customer/www/itineriamo.com/public_html/wp-includes/class-wp-hook.php(287): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#4 /home/customer/www/itineriamo.com/public_h [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-05-19 11:59:51 [notice X 1][/home/customer/www/itineriamo.com/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 20 of 26JS: 2020-05-13 16:36:39 [error X 1][https://www.itineriamo.com/wp-content/plugins/elementor/assets/js/editor-document.min.js?ver=2.9.8:2:187452] Cannot read property \'map\' of undefined 
JS: 2020-05-13 17:06:50 [error X 1][https://www.itineriamo.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view12364\") has already been destroyed and cannot be used. 
JS: 2020-05-13 17:13:39 [error X 1][https://www.itineriamo.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view3117\") has already been destroyed and cannot be used. 
JS: 2020-05-15 10:04:31 [error X 1][https://www.itineriamo.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view7471\") has already been destroyed and cannot be used. 
JS: 2020-05-15 12:46:33 [error X 1][https://www.itineriamo.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view65484\") has already been destroyed and cannot be used. 
JS: 2020-05-15 12:46:55 [error X 1][https://www.itineriamo.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view66207\") has already been destroyed and cannot be used. 
JS: 2020-05-15 13:40:59 [error X 1][https://www.itineriamo.com/wp-admin/post.php?post=825&action=elementor#:2:5] d is not defined 
JS: 2020-05-15 13:40:59 [error X 1][https://www.itineriamo.com/wp-admin/post.php?post=825&action=elementor#:2:5] docu is not defined 
JS: 2020-05-15 13:40:59 [error X 1][https://www.itineriamo.com/wp-admin/post.php?post=825&action=elementor#:2:5] docume is not defined 
JS: 2020-05-15 13:41:00 [error X 3][https://www.itineriamo.com/wp-admin/post.php?post=825&action=elementor#:3:1] Unexpected end of input 
JS: 2020-05-15 13:41:15 [error X 1][https://www.itineriamo.com/wp-admin/post.php?post=825&action=elementor#:2:4] dou is not defined 
JS: 2020-05-15 13:41:42 [error X 10][https://www.itineriamo.com/wp-admin/post.php?post=825&action=elementor#:2:13] document.getElementByID is not a function 
JS: 2020-05-15 13:42:36 [error X 67][https://www.itineriamo.com/wp-admin/post.php?post=825&action=elementor#:12:25] Invalid or unexpected token 
JS: 2020-05-15 14:08:44 [error X 6][https://www.itineriamo.com/wp-admin/post.php?post=825&action=elementor#:10:5] Unexpected token \'<\' 
JS: 2020-05-15 14:08:48 [error X 1][https://www.itineriamo.com/wp-admin/post.php?post=825&action=elementor#:10:1] Unexpected token \'>\' 
JS: 2020-05-15 14:08:53 [error X 2][https://www.itineriamo.com/wp-admin/post.php?post=825&action=elementor#:2:46] Cannot set property \'onclick\' of null 
JS: 2020-05-15 17:10:16 [error X 2][https://www.itineriamo.com/wp-content/plugins/addon-elements-for-elementor-page-builder/assets/js/eae.min.js?ver=1.0:1:311] google is not defined 
JS: 2020-05-16 15:07:00 [error X 1][https://www.itineriamo.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view35545\") has already been destroyed and cannot be used. 
JS: 2020-05-18 07:08:32 [error X 5][https://www.itineriamo.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.9.8:31:168588] elementorFrontend.elements.window.jQuery is not a function 
JS: 2020-05-20 12:41:24 [error X 2][https://www.itineriamo.com/wp-content/plugins/elementor/assets/lib/e-select2/js/e-select2.full.min.js?ver=4.0.6-rc.1:1:74235] Cannot read property \'destroy\' of undefined 

Log: showing 3 of 32020-05-07 17:34:09 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.9.3',
  'to' => '2.9.4',
)]
2020-05-24 17:55:45 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.9.8',
  'to' => '2.9.9',
)]
2020-05-24 17:55:47 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.9.4',
  'to' => '2.9.5',
)]


				
</details>

**Comment by lior-sh** [comment] 2020-05-26 08:37
Hi @Iti1980,

Thanks for reporting, we couldn't reproduce the issue.
Can you please add clear steps on how to replicate the issue? 
Thanks.

**Comment by lior-sh** [comment] 2020-05-26 09:36
Hi @Iti1980,

Thanks for reporting, we couldn't reproduce the issue.
Please contact our support at support @elementor.com for guidance in resolving this issue and mention that you were directed by me and reference this issue.
Thanks.

**Closed by lior-sh** 2020-05-26 09:36 UTC
