### ISSUE TITLE
Custom Width Background Not Working/Showing in `Section/Column/Inner Section`

### ISSUE THREAD

**Issue by FauzanEdris** [elementor/elementor#19730] opened 2022-09-07 09:19 UTC
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Custom Width Background Not Working/Showing in `Section/Column/Inner Section`, except Extra Breakpoints.

Please See The Screenshot.

#### Dekstop :
<img width="1504" alt="Screen Shot 2022-09-07 at 17 21 22" src="https://user-images.githubusercontent.com/30016486/188842344-95ba5881-c09b-49f7-8ac3-739ff40b2763.png">

#### Tablet/Mobile :
<img width="1508" alt="Screen Shot 2022-09-07 at 17 21 40" src="https://user-images.githubusercontent.com/30016486/188842377-ad57879a-6de8-415b-8eac-fcb72c2a2194.png">

#### Any Extra Breakpoints :
<img width="1497" alt="Screen Shot 2022-09-07 at 17 21 49" src="https://user-images.githubusercontent.com/30016486/188842422-67ce6fe0-9e5a-4e6b-9abe-7d46cbacd45c.png">

### Steps to reproduce

Just styling the background in the `Section/Column/Inner Section` like the screenshot above

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

Bugs Since Elementor v3.7.0

Elementor v3.6.8 is fine.

Please fix it ASAP.

Thank You 🙃

**Comment by arielk** [comment] 2022-09-18 06:45
Duplicate of: https://github.com/elementor/elementor/issues/19669, https://github.com/elementor/elementor/issues/19662, https://github.com/elementor/elementor/issues/19527, https://github.com/elementor/elementor/issues/19487

**Closed by arielk** 2022-09-18 06:45 UTC
Labels: status/awaiting_triage
