### ISSUE TITLE
How to connect Swiper.js when creating a widget?

### ISSUE THREAD

**Issue by Vladddosss** [elementor/elementor#9171] opened 2019-09-24 11:21 UTC
Prompt how to connect a script which is in your directory by default? And if you can add this information to the documentation, I think it will help many.

I have read your documentation and I have not found the answer to my question in it. 
https://developers.elementor.com/building-a-simple-custom-widget-with-javascript/
https://developers.elementor.com/creating-a-new-widget/adding-javascript-to-eleme

Why is the script that you connect to the carousel in the free version is not minified?

**Comment by black-eye** [comment] 2019-09-24 12:53
+1 I'd like to know that too.
For example, when I want to create my own slider or carousel widget, that will have the same level of customisation as the original one. Basicaly a duplicate of the native with a different name and design.

**Closed** 2019-09-24 13:48 UTC

**Comment by Vladddosss** [comment] 2019-09-24 14:14
@bainternet 

Thanks!

**Comment by mccicorp** [comment] 2021-12-08 15:51
@bainternet 

Trying to get this working with a custom slider widget per your recommendation but not having any luck. 

We tried adding 'swiper' to the get_script_depends return array but we're still getting a "Swiper Undefined" error. 

public function get_script_depends() {
	return [ 'swiper', 'emc-featured-content-slider-scripts' ];
}

We also tried adding 'swiper' as a dependency when we register the custom javascript file for our widget, but then the javascript file doesn't load. 

wp_register_script( 'emc-featured-content-slider-scripts', plugins_url( '/assets/js/emc-featured-content-slider-scripts.js', PLUGIN_NAME), array( 'jquery', 'elementor-frontend', 'swiper' ), '1.0', true );

**Comment by sgeray** [comment] 2023-04-21 18:12
> @bainternet
> 
> Trying to get this working with a custom slider widget per your recommendation but not having any luck.
> 
> We tried adding 'swiper' to the get_script_depends return array but we're still getting a "Swiper Undefined" error.
> 
> public function get_script_depends() { return [ 'swiper', 'emc-featured-content-slider-scripts' ]; }
> 
> We also tried adding 'swiper' as a dependency when we register the custom javascript file for our widget, but then the javascript file doesn't load.
> 
> wp_register_script( 'emc-featured-content-slider-scripts', plugins_url( '/assets/js/emc-featured-content-slider-scripts.js', PLUGIN_NAME), array( 'jquery', 'elementor-frontend', 'swiper' ), '1.0', true );

It will be a very late response, it doesn't work due to "Improved Asset Loading" (https://elementor.com/help/optimized-assets-loading/?utm_source=experiments&utm_medium=wp-dash&utm_campaign=learn)

`	private function is_improved_assets_loading() {
		return Plugin::$instance->experiments->is_feature_active( 'e_optimized_assets_loading' );
	}

	private function get_elementor_frontend_dependencies() {
		$dependencies = [
			'elementor-frontend-modules',
			'elementor-waypoints',
			'jquery-ui-position',
		];

		if ( ! $this->is_improved_assets_loading() ) {
			wp_register_script(
				'swiper',
				$this->get_js_assets_url( 'swiper', $this->e_swiper_asset_path ),
				[],
				$this->e_swiper_version,
				true
			);

			$dependencies[] = 'swiper';
			$dependencies[] = 'share-link';
			$dependencies[] = 'elementor-dialog';
		}

		return $dependencies;
	}`

**Comment by SEwebm** [comment] 2023-07-04 09:43
Still relevant, since improved asset loading registering the script handle via return value in get_script_depends() does not lead to the desired effect.

I have created a custom extended widget to add some slide specific repeater controls, so far so fine. Registering the handle is insufficient. Registering the script manually via wp_register_script in class constructor does not work. How can this be achieved?

**Comment by sgeray** [comment] 2023-07-04 11:03
> Still relevant, since improved asset loading registering the script handle via return value in get_script_depends() does not lead to the desired effect.
> 
> I have created a custom extended widget to add some slide specific repeater controls, so far so fine. Registering the handle is insufficient. Registering the script manually via wp_register_script in class constructor does not work. How can this be achieved?

hope I get you right, I do use;

```
	public function __construct() {
		add_action( 'init', [ $this, 'i18n' ] );
		add_action( 'plugins_loaded', [ $this, 'init' ] );
	}

	public function init() {
		add_action( 'elementor/frontend/before_register_scripts', [ $this, 'widget_scripts' ] );
		add_action( 'elementor/frontend/after_enqueue_styles', [ $this, 'widget_styles' ], 11 );			
	}

	public function widget_scripts() {
		if ( ! wp_script_is( 'swiper' ) ) {
			wp_register_script( 'swiper', plugins_url( 'assets/widget_js/ext/swiper-bundle.min.js', __FILE__ ), [ 'jquery' ], self::VERSION, true );		
		}
	}
	
	public function widget_styles() {
		wp_register_style( 'my-swiper', plugins_url( 'assets/vendor/css/swiper.css', __FILE__ ) );
	}
```

and then simply call it in my custom widget;

```
	public function get_script_depends() {
		return [ 'my-widgets-generic', 'swiper' ];
	}
```

I do use same SwiperJS library that I copied in my own widget from Elementor instead of looking from Elementor's directory, not the final product but its working as expected for me.

**Comment by SEwebm** [comment] 2023-07-04 15:41
> > Still relevant, since improved asset loading registering the script handle via return value in get_script_depends() does not lead to the desired effect.
> > I have created a custom extended widget to add some slide specific repeater controls, so far so fine. Registering the handle is insufficient. Registering the script manually via wp_register_script in class constructor does not work. How can this be achieved?
> 
> hope I get you right, I do use;
> 
> ```
> 	public function __construct() {
> 		add_action( 'init', [ $this, 'i18n' ] );
> 		add_action( 'plugins_loaded', [ $this, 'init' ] );
> 	}
> 
> 	public function init() {
> 		add_action( 'elementor/frontend/before_register_scripts', [ $this, 'widget_scripts' ] );
> 		add_action( 'elementor/frontend/after_enqueue_styles', [ $this, 'widget_styles' ], 11 );			
> 	}
> 
> 	public function widget_scripts() {
> 		if ( ! wp_script_is( 'swiper' ) ) {
> 			wp_register_script( 'swiper', plugins_url( 'assets/widget_js/ext/swiper-bundle.min.js', __FILE__ ), [ 'jquery' ], self::VERSION, true );		
> 		}
> 	}
> 	
> 	public function widget_styles() {
> 		wp_register_style( 'my-swiper', plugins_url( 'assets/vendor/css/swiper.css', __FILE__ ) );
> 	}
> ```
> 
> and then simply call it in my custom widget;
> 
> ```
> 	public function get_script_depends() {
> 		return [ 'my-widgets-generic', 'swiper' ];
> 	}
> ```
> 
> I do use same SwiperJS library that I copied in my own widget from Elementor instead of looking from Elementor's directory, not the final product but its working as expected for me.

Thanks for your answer! This would be my goto if I was developing a custom widget from scratch. I left out some details in my previous answer for brevity but what I did essentially was extending the class of the slides widget to add a few controls hoping I would save myself some work.

Only to find out that even if the dependency is included the swiper js is not applied on the widget. Maybe it is more of an issue of the implementation so to say. In my case slide.js not being applied to the custom widget (which is essentially a slides widget with a few extra controls but under a different name).

Another user on  reddit suggested deactivating the original widget and registering the custom extended widget under the same name and even that will not work.
