### ISSUE TITLE
Undefined array key "background_color_b" when creating custom field gradients

### ISSUE THREAD

**Issue by clearhost-cmd** [elementor/elementor#16956] opened 2021-11-16 18:41 UTC
## Description

When creating a header using theme builder, and using the header's page settings to create a gradient, then using custom fields to create two colours for a specific page results in error  Undefined array key "background_color_b". This issue isn't persistent when using custom fields for buttons, backgrounds, or anything other than gradients. 

## Steps to reproduce

1. Select header settings, select style dropdown, select gradient, and using dynamic colour post custom fields.
2. Select two custom fields, colour a, colour b, whatever colour it doesn't matter.
3. Create  two test pages, and set specific colour a and colour b for each.
4. Access the pages, and see error.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment
Issue persists across multiple environments.

## Context Photos

![image](https://user-images.githubusercontent.com/91465315/142045537-4314f1b1-f212-4208-8718-d4ea57071cbf.png)
![image](https://user-images.githubusercontent.com/91465315/142045627-4fab6baf-5edb-4a30-b11a-26bbac919118.png)
![image](https://user-images.githubusercontent.com/91465315/142045679-076b57ec-209e-4b07-b16e-9de1c8935ecb.png)
![image](https://user-images.githubusercontent.com/91465315/142045723-c2846947-d4e6-44f3-bf66-1762fab23d14.png)
![image](https://user-images.githubusercontent.com/91465315/142045740-4c8264dd-3324-4956-a36c-d5a7e47c624a.png)

**Comment by clearhost-cmd** [comment] 2021-12-14 21:48
Any updates to this?

**Comment by btxtiger** [comment] 2022-05-22 12:08
Getting similar messages:
![image](https://user-images.githubusercontent.com/15804690/169694413-cfb27d13-5e75-4309-bfc3-0eaeaef007f4.png)

**Comment by essentique** [comment] 2022-06-24 07:26
Getting a similar problem. Can't set a gradient background with dynamic colors. Just see the first color as background, ignoring the whole gradient thing, with the following message:

PHP Warning:  Undefined array key "background_color" in .../wp-content/plugins/elementor/core/files/css/base.php on line 697

**Comment by momo-fr** [comment] 2022-07-08 09:51
Same issue for me too. When I use dynamic data from ACF field for the two colors of gradient background I have the "elementor/core/files/css/base.php on line 697" error message and no colors are displayed. :-((
In the editor all seem Ok in my template page (custom product) but in live nothing.

**Comment by clearhost-cmd** [comment] 2022-08-07 22:13
Issue still occurring :(

**Comment by arielk** [comment] 2022-09-12 17:29
Duplicate of: https://github.com/elementor/elementor/issues/10885

**Closed by arielk** 2022-09-12 17:29 UTC

**Comment by shoaib12589** [comment] 2024-08-12 05:22
$value = isset($comparison[$parsed_name[1]]) ? $comparison[$parsed_name[1]] : '';

Replace Line no 87 with this code the problem has been fixed.

Thanks me letter

**Comment by Ahmed-Qotb** [comment] 2024-08-25 09:03
if (isset($comparison[ $parsed_name[1] ])) {
    $value = $comparison[ $parsed_name[1] ];
} else {
    $value = ''; 
}

this worked for me replace with line 87

original : $value = $comparison[ $parsed_name[1] ];

**Comment by Fabulez** [comment] 2024-09-01 12:29
> if (isset($comparison[ $parsed_name[1] ])) { $value = $comparison[ $parsed_name[1] ]; } else { $value = ''; }
> 
> this worked for me replace with line 87
> 
> original : $value = $comparison[ $parsed_name[1] ];

Thanks bra

**Comment by rqieee** [comment] 2024-09-03 14:41
> if (isset($comparison[ $parsed_name[1] ])) { $value = $comparison[ $parsed_name[1] ]; } else { $value = ''; }
> 
> this worked for me replace with line 87
> 
> original : $value = $comparison[ $parsed_name[1] ];

Thx its work for me :D
