### ISSUE TITLE
Widget bar doesn't load

### ISSUE THREAD

**Issue by shimsa** [elementor/elementor#7482] opened 2019-03-15 18:07 UTC
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

From Elementor v2.5.5, widget bar doesn't load. It happens only, while Elementor Pro is also activated.

See screen 
![Snímek z 2019-03-15 18-00-14](https://user-images.githubusercontent.com/7617350/54452203-d487b800-4754-11e9-8b77-dd7d4b6a30e7.png)

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>

== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MySQL Community Server - GPL v8.0.13
	PHP Version: 7.2.13
	PHP Max Input Vars: 1000
	PHP Max Post Size: 40M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.1.1
	Site URL: http://example.com
	Home URL: http://example.com
	WP Multisite: Yes
	Max Upload Size: 32 MB
	Memory limit: 128M
	Permalink Structure: /%postname%/
	Language: cs-CZ
	Timezone: 1
	Admin Email: user@example.com
	Debug Mode: Inactive

== Theme ==
	Name: Twenty Nineteen
	Version: 1.3
	Author: the WordPress team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: cs_CZ
	User Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.75 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 2.5.8
		Author: Elementor.com
	Elementor Pro
		Version: 2.4.8
		Author: Elementor.com

== Log ==

</details>

**Comment by Deralict** [comment] 2019-03-15 18:55
This happens to me when upgrading to any version of 2.5.x from 2.4.x. Video of it in action: https://www.dropbox.com/s/3lq6e67ag82kluy/elementor-broke.mov?dl=0

**Comment by JoeDarko** [comment] 2019-03-15 21:35
This is also happening to me from time to time after the recent updates. Also the loading of the Elementor editor itself has become really buggy. Before the update i never experienced the "blank white page" probelm. But now it's happening very often. 

After trying again a few times, it always evenually loads, but it can be frustrating. We are also not the only ones. After the 2.5 update the number of people experiencing loading issues has increased rapidly. You can see complaints everywhere on Elementor comunity Facebook page and Wordpress plugin support forum.

**Comment by shilo-ey** [comment] 2019-03-17 10:17
Hi @shimsa @Deralict @JoeDarko 

Please contact our support at support @elementor.com for guidance in resolving this issue and mention that you were directed by me and reference this issue.

This issue needs specific debugging and usually caused by a conflict with some other plugin/website configuration.

thanks.

**Closed by shilo-ey** 2019-03-17 10:17 UTC
