### ISSUE TITLE
Elementor v 3.4.5 caused absolutely positioned items to move slightly out of position

### ISSUE THREAD

**Issue by simonclay** [elementor/elementor#16572] opened 2021-10-13 16:18 UTC
I have absolutely positioned items on page. 

After updating to v3.4.5 the items have all moved by about 10px

Issue is fixed when I revert back to v3.4.4.

**Comment by thehervy** [comment] 2021-10-14 12:34
Same here. But the whole page was rendered totally without CSS etc.. had to go 1 day back with daily backup.

**Comment by simonclay** [comment] 2021-10-14 12:39
Ouch! Using 'Elementor > Tools > Version Control' didn't help?

**Comment by thehervy** [comment] 2021-10-14 12:41
I did not try it. I had to do it quickly and be 100% sure the website will work. No worries - I have managewp daily backup, so it is one-click solution :)

**Comment by jefferyto** [comment] 2021-10-31 15:21
This is not a bug in the strictest sense but it is still a problem:

* For almost everyone who has used absolute positioning in their existing sites, when they upgrade Elementor their absolutely positioned elements will become misaligned. This plugin upgrade broke existing layouts.
* This is not how absolute positioning works in CSS. Absolutely positioned elements do not inherit padding from their parents. This new behaviour is not intuitive for users who know how to use absolute positioning.
* There is no way to remove/undo this extra padding from within the Elementor interface. Yes you can add CSS (in the custom CSS panel if you are using the Pro version, or in the theme's stylesheet) to workaround this unwanted padding, but this is a workaround, not a solution.

I am very surprised the developers of Elementor have no concern about breaking their users' sites.

**Comment by azkalex** [comment] 2021-11-17 02:13
> This is not a bug in the strictest sense but it is still a problem:
> 
> * For almost everyone who has used absolute positioning in their existing sites, when they upgrade Elementor their absolutely positioned elements will become misaligned. This plugin upgrade broke existing layouts.
> * This is not how absolute positioning works in CSS. Absolutely positioned elements do not inherit padding from their parents. This new behaviour is not intuitive for users who know how to use absolute positioning.
> * There is no way to remove/undo this extra padding from within the Elementor interface. Yes you can add CSS (in the custom CSS panel if you are using the Pro version, or in the theme's stylesheet) to workaround this unwanted padding, but this is a workaround, not a solution.
> 
> I am very surprised the developers of Elementor have no concern about breaking their users' sites.
> 
> Edit: This change is also not mentioned in the Elementor changelog, so users will just be surprised that their sites are broken.

Came here to say the exact same thing. They did it again, like the Nav menu items' spacing inheritance they fixed after I posted about it, absolute elements now also inherit the parent's padding, whether it's section or column padding. I don't know who comes with these ideas, and how they get approved in the final build, but not thinking about the chaos a simple CSS property can create, it's just over me. Again, why break something that works just fine?

I created a section, added a few elements, and added one of them as an absolute element. Gave the column 20px padding, and added border to better visualise it. The absolute element inherits the parents' padding as shown in the image below. And I also don't know why the box-sizing property is set to content-box. Yes, this can be fixed with CSS, but the point is not to fix it with CSS, this should be fixed as soon as possible.

![image](https://user-images.githubusercontent.com/60075863/142096243-45a91d2b-1454-4358-bd4d-56ba303c9669.png)

**Comment by simonclay** [comment] 2021-11-17 09:57
Completely agree @jefferyto  and @azkalex 

It makes no sense at all to do this. Poor decisions and sadly no response from the team.

**Comment by DorShahar** [comment] 2021-12-14 15:40
This issue has been added to Elementor Core v3.5.0

Feel free to update

Thanks!

**Closed by DorShahar** 2021-12-14 15:40 UTC
Labels: status/merged

**Comment by hybridmuse** [comment] 2022-01-09 03:36
Please never do this again.
We had manually moved each absolute element to fix this issue, and now had to move everything back once again!
I beg you to be more careful with these changes.
