### ISSUE TITLE
🔗 🚀 Feature Request: Inerting Tables with Different Themes (Duplicate of #1342)

### ISSUE THREAD

**Issue by TopNatural** [elementor/elementor#6055] opened 2018-11-04 05:33 UTC
Hello, 

I love your page builder, but it doesn't have tables. It is very hard to add a simple table with different types of content such as a table that contains images, text, buttons, and more. Please add this to your page builder because when I use your page builder I cannot use any other plugin to solve the table issue. 

Thanks,

**Comment by bainternet** [comment] 2018-11-04 07:54
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.

**Comment by bainternet** [comment] 2018-11-04 07:54
Duplicate of #1342

**Closed by bainternet** 2018-11-04 07:54 UTC
Labels: request/feature, mod*

**Comment by TopNatural** [comment] 2018-11-05 05:40
Hi, 

You closed my request and gave me an option for a request that was made on February 2018 and you haven’t added this feature which is very basic to your page builder!
Unfortunately, your customer service is very bad. No help at all.
