### ISSUE TITLE
🔗 🐞 Bug Report: The icon list divider breaks in the loop carousel widget only in RTL (Related to #21326) - [ED-9844]

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#21338] opened 2023-02-14 16:56 UTC
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

If we use the icon list widget in the loop carousel widget, put it in inline mode, the divider in this widget will be broken. **Please pay attention to these two points when reproducing this bug :**

1- The website should be RTL.
2- The icon list should be inline (Enable the inline option in the list icon widget)

### Steps to reproduce

1- Make sure the website is RTL.
2- Add loop carousel widget.
3- Click the Create Template button and add the image and icon list widget.
4- In the icon list widget, enable the inline option.
5- After that, activate the divider option.

Obviously, the divider is not working as expected.

![v](https://user-images.githubusercontent.com/77163248/218803955-565f14b4-19d1-42fa-beaa-c0d0af354f68.png)

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

[system-info-localhost-14-02-2023.txt](https://github.com/elementor/elementor/files/10734894/system-info-localhost-14-02-2023.txt)

**Comment by nicholaszein** [comment] 2023-02-16 13:44
Hi @79ho3ein! 

Thank you for submitting your issue! 🙏 

Kind regards

**Comment by nicholaszein** [comment] 2023-02-21 21:16
Hi @79ho3ein,

I could not reproduce this issue, could it be related to something else? Since you're on localhost, could it be related to the localhost cache? Can you please verify if this happens after clearing the cache?

Here's the video:

https://user-images.githubusercontent.com/113993460/220460397-0e7d9988-6703-461e-a486-9c95792c27e4.mp4


Just for context, I am testing on a live server, without any cache, and with all Elementor Experiments active.

**Comment by 79ho3ein** [comment] 2023-02-22 00:49
Hi @nicholaszein, Thanks for the video and also for the time.

Let's get to the root of this problem. I think this bug occurs because of [this bug](https://github.com/elementor/elementor/issues/21326). But to my surprise, I see in your video that there is not even an RTL bug! Has this bug been fixed for you?
I just checked now this bug on a live website and it is there.
In general, I think if [this bug](https://github.com/elementor/elementor/issues/21326) is fixed, the icon list bug will be fixed along with it.

**Comment by nicholaszein** [comment] 2023-02-22 11:38
Hi @79ho3ein,

thank you for the feedback! 🙏 

You are correct, this issue is related to issue #21326. There is a partial workaround that I will be posting there. For now, I'm closing this one so we can continue the conversation there.

Thanks again!

**Closed by nicholaszein** 2023-02-22 11:38 UTC
Labels: bug, product/pro, component/design, type/internationalization, component/loop-carousel
