### ISSUE TITLE
3.0.8 All Site Setting get deleted. Revision not always possible.

### ISSUE THREAD

**Issue by SebastianB12** [elementor/elementor#12538] opened 2020-09-15 15:17 UTC
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

I updated Elementor to 3.0.8.1 from 3.0.7 this morning. After around 4 hours all site settings were deleted. A revision is visible in the site history revisions tab, however I can not go back due to another error:

![image](https://user-images.githubusercontent.com/15847414/93227899-2e67a480-f775-11ea-8f1c-d7501cbcef77.png)

User @TomRaraAvis also experienced this bug, as stated in another issue: https://github.com/elementor/elementor/issues/12363#issuecomment-692431939
However he was able to return to an older revision and therefore get his global site settings back.

I don't how to reproduce it consistently....

3.0.7 did not have this problem for me.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [ ] I can reproduce this bug consistently using the steps above.

## Environment

A Rollback to 3.0.7 did not help:

<details>
<summary>System Info</summary>
					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: (Ubuntu) v5.7.28
	PHP Version: 7.4.5
	PHP Max Input Vars: 3000
	PHP Max Post Size: 200M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.4.2
	Site URL: https://elementor-backup.svm-test.de
	Home URL: https://elementor-backup.svm-test.de
	WP Multisite: No
	Max Upload Size: 200 MB
	Memory limit: 256M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: de-DE
	Timezone: Europe/Berlin
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor Child
	Version: 1.0.1
	Author: Elementor Team
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.3.0
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: de_DE
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.87 Safari/537.36

== Active Plugins ==
	Better Search Replace
		Version: 1.3.3
		Author: Delicious Brains

	Elementor
		Version: 3.0.7
		Author: Elementor.com

	Elementor Pro
		Version: 3.0.4
		Author: Elementor.com

	UpdraftPlus - Backup/Restore
		Version: 1.16.29
		Author: UpdraftPlus.Com, DavidAnderson

	WordPress Importer
		Version: 0.7
		Author: wordpressdotorg

	Yoast Duplicate Post
		Version: 3.2.5
		Author: Enrico Battocchi & Team Yoast

== Elements Usage ==
	
	archive : 1
		archive-posts : 1
		divider : 1
		heading : 1
	footer : 1
		heading : 6
		icon-list : 4
		spacer : 1
		text-editor : 1
		theme-site-logo : 1
	header : 4
		image : 2
		nav-menu : 4
		text-editor : 2
		theme-site-title : 2
	popup : 2
		flip-box : 3
		html : 3
	section : 8
		divider : 8
		heading : 20
		icon : 9
		image : 10
		spacer : 2
		text-editor : 11
	wp-page : 19
		button : 4
		divider : 125
		form : 1
		heading : 167
		html : 20
		icon : 92
		image : 72
		spacer : 56
		text-editor : 91

== Log ==
	
PHP: showing 6 of 6PHP: 2020-09-11 07:29:56 [notice X 3][/www/htdocs/xxxxxxxx/xxxxxxxx/wp-content/plugins/elementor/includes/managers/image.php::86] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-09-11 07:53:15 [notice X 36][/www/htdocs/xxxxxxxx/xxxxxxxx/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-09-11 07:53:40 [error X 1][/www/htdocs/xxxxxxxx/xxxxxxxx/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::281] Uncaught Error: Call to a member function update_meta() on null in /www/htdocs/xxxxxxxx/xxxxxxxx/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:281
Stack trace:
#0 /www/htdocs/xxxxxxxx/xxxxxxxx/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(162): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions(7, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /www/htdocs/xxxxxxxx/xxxxxxxx/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /www/htdocs/xxxxxxxx/xxxxxxxx/wp-includes/class-wp-hook.php(287): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#4 /www/htdocs/xxxxxxxx/xxxxxxxx/wp-includes/c [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-09-11 12:39:49 [notice X 3][/www/htdocs/xxxxxxxx/xxxxxxxx/wp-content/plugins/elementor-pro/modules/posts/widgets/posts.php::31] Undefined index: posts_post_type [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-09-12 21:52:36 [error X 1][/www/htdocs/xxxxxxxx/xxxxxxxx/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::281] Uncaught Error: Call to a member function update_meta() on null in /www/htdocs/xxxxxxxx/xxxxxxxx/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:281
Stack trace:
#0 /www/htdocs/xxxxxxxx/xxxxxxxx/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(162): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions(20582, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /www/htdocs/xxxxxxxx/xxxxxxxx/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /www/htdocs/xxxxxxxx/xxxxxxxx/wp-includes/class-wp-hook.php(287): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#4 /www/htdocs/xxxxxxxx/xxxxxxxx/wp-includ [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-09-15 12:46:42 [notice X 3][/www/htdocs/xxxxxxxx/xxxxxxxx/wp-content/plugins/elementor/core/kits/documents/tabs/settings-layout.php::187] Undefined index: post_status [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 6 of 6JS: 2020-09-11 11:31:35 [error X 65][https://xxxxxxxx/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.0.7:2:473653] Cannot read property \'document\' of undefined 
JS: 2020-09-11 12:50:44 [error X 15][https://xxxxxxxx/wp-content/plugins/elementor-pro/assets/js/frontend.min.js?ver=3.0.4:2:52624] this.$element.sticky is not a function 
JS: 2020-09-15 07:40:40 [error X 4][https://xxxxxxxx/wp-content/plugins/elementor/assets/js/common.min.js?ver=3.0.8.1:2:157191] Routes: `theme-builder-publish/triggers` is already registered. 
JS: 2020-09-15 07:40:42 [error X 2][https://xxxxxxxx/wp-content/plugins/elementor/assets/js/frontend-modules.min.js?ver=3.0.8.1:2:60273] Cannot read property \'data\' of undefined 
JS: 2020-09-15 07:40:54 [error X 4][https://xxxxxxxx/wp-content/plugins/elementor/assets/js/frontend-modules.min.js?ver=3.0.8.1:2:60285] Cannot read property \'attributes\' of undefined 
JS: 2020-09-15 11:37:08 [error X 8][https://xxxxxxxx/wp-content/plugins/elementor/assets/js/editor-modules.min.js?ver=3.0.8.1:2:55970] n.attributes[o.name].each is not a function 

				
</details>

**Comment by oliveandlake** [comment] 2020-09-15 18:01
Exactly the same thing happened to me. After around 3 hours, site settings completely disappeared. I didn't have anything in the history.

The weird thing is that then all my global settings on widgets couldn't then be edited as there were console errors about the global setting not being found.

I tried to recreate the issue on my localhost but couldn't. Just randomly deleted for some unknown reason.

Everything was going well, I thought Elementor had resolved it in 3.0.8.1 and I started to feel confident. I was just finishing up work for the day and went to take a backup (just in case, never know with v.3!) and it was gone.

I hadn't opened site settings, I was just building a page like normal. Then suddenly it went.

**Comment by TomRaraAvis** [comment] 2020-09-15 22:06
**+1**

I updated from 3.0.7 to 3.0.8.1 on a live site & everything was going very well . . . cleared all the caches, regenerated CSS, checked some pages, made some updates, etc. — all was working well (compared to 3.0.7). I continued to work on my site making changes and saving some forms. I went back to clear all the caches and regenerate the CSS again (just for heck of it) & I went to check my site.

ALL CSS WAS LOST! — not just global styles, I mean ALL of it. Even the individual widget CSS. I was freaking out. I was very very close to restoring my site from a backup but thought to try one last thing. I went into Site Settings to look around. Everything was gone. All global styles, fonts, layout, background settings were in their **default states**, like it was a new site. I had not even accessed the Site Settings panel after updating to 3.0.8.1. I have no idea how all my styles were deleted & set back to defaults. Continuing on, I accessed the Site Settings History tab & found that there was an older version save from last week. I then selected that week-old Site Settings version & updated. Then cleared caches and regenerated CSS again. Refreshed some site pages & everything is now back in order.

I will be taking frequent backups like a maniac because I still don't trust the latest version. It we ain't outta the woods yet.

<details>
<summary>MY SYSTEM INFO</summary>
<br>
					
== Server Environment ==

	Operating System: Linux
	Software: Apache/2.4.25 (Debian)
	MySQL version: mariadb.org binary distribution v5.6.47-87.0
	PHP Version: 7.3.20-1+0~20200710.65+debian9~1.gbpc9cbeb
	PHP Max Input Vars: 2500
	PHP Max Post Size: 64M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==

	Version: 5.5.1
	Site URL: https://mydomain.com
	Home URL: https://mydomain.com
	WP Multisite: No
	Max Upload Size: 64 MB
	Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: America/New_York
	Debug Mode: Inactive

== Theme ==

	Name: Hello Elementor Child
	Version: 1.0.1
	Author: Elementor Team
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.3.0
	Parent Theme Author: Elementor Team

== User ==

	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.102 Safari/537.36

== Active Plugins ==

	Breeze
		Version: 1.1.7
		Author: Cloudways

	Elementor
		Version: 3.0.8.1
		Author: Elementor.com

	Elementor Pro
		Version: 3.0.4
		Author: Elementor.com

	WooCommerce
		Version: 4.5.2
		Author: Automattic

	WooCommerce Stripe Gateway
		Version: 4.5.2
		Author: WooCommerce

	Wordfence Security
		Version: 7.4.11
		Author: Wordfence

== Elements Usage ==
	
	footer : 2
		button : 2
		icon-box : 4
	header : 2
		button : 8
		menu-anchor : 2
		spacer : 2
		theme-site-logo : 2
		woocommerce-menu-cart : 2
	page : 5
		spacer : 1
		template : 95
	popup : 3
		button : 9
		heading : 12
		html : 2
		icon : 9
		icon-box : 4
		image : 3
		text-editor : 11
	product : 4
		countdown : 1
		global : 2
		heading : 5
		image : 1
		spacer : 2
		text-editor : 1
		woocommerce-breadcrumb : 5
		woocommerce-product-add-to-cart : 4
		woocommerce-product-content : 3
		woocommerce-product-images : 5
		woocommerce-product-meta : 4
		woocommerce-product-price : 2
		woocommerce-product-title : 4
	section : 149
		accordion : 1
		button : 117
		form : 3
		global : 79
		heading : 162
		icon : 15
		icon-box : 5
		icon-list : 138
		image : 252
		image-carousel : 12
		menu-anchor : 69
		spacer : 30
		tabs : 37
		text-editor : 599
		toggle : 14
		video : 1
	widget : 0
		spacer : 8
	wp-post : 0
		global : 2
		heading : 7
		icon : 1
		shortcode : 4
		spacer : 3
		template : 8
	wp-page : 9
		button : 4
		global : 1
		heading : 12
		shortcode : 1
		spacer : 2
		template : 35
		text-editor : 7
		video : 6
	product-post : 0
		heading : 2
		icon-list : 16
		spacer : 2
		template : 93
		text-editor : 1
		woocommerce-products : 4
	product-archive : 1
		wc-archive-products : 1


== Log ==
	
Log: showing 1 of 12020-09-14 18:33:18 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.7',
  'to' => '3.0.8.1',
)]

JS: showing 2 of 2JS: 2020-09-14 22:34:06 [error X 10][https://mydomain.com/wp-admin/load-scripts.php?c=1&loadchunk_0=jquery-core,utils&ver=5.5.1:2:12675] Syntax error, unrecognized expression: #breeze-msg=success-cleancache&file=0 
JS: 2020-09-15 02:12:47 [error X 1][https://mydomain.com/wp-content/plugins/elementor/assets/js/editor-modules.min.js?ver=3.0.8.1:2:55970] n.attributes[o.name].each is not a function 

PHP: showing 2 of 2PHP: 2020-09-14 21:59:42 [notice X 1][/mydomain/public_html/wp-content/plugins/elementor/core/kits/documents/tabs/settings-layout.php::187] Undefined index: post_status [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-09-15 00:12:07 [notice X 3][/mydomain/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
				
</details>

**Comment by shilo-ey** [comment] 2020-09-16 06:23
Hi @TomRaraAvis @SebastianB12 

Thanks for your report.

Please contact our support at support @elementor.com for guidance in resolving this issue and mention that you were directed by me and reference this issue. we will try to locate the issue.

Please share credentials for WP admin, and for the server/FTP access.

Thanks

**Comment by SebastianB12** [comment] 2020-09-16 06:55
> Hi @TomRaraAvis @SebastianB12
> 
> Thanks for your report.
> 
> Please contact our support at support @elementor.com for guidance in resolving this issue and mention that you were directed by me (@shilo-ey) and reference this issue. we will try to locate the issue.
> 
> Please share credentials for WP admin, and for the server/FTP access.
> 
> Thanks

**Comment by SebastianB12** [comment] 2020-09-16 06:57
> Hi @TomRaraAvis @SebastianB12
> 
> Thanks for your report.
> 
> Please contact our support at support @elementor.com for guidance in resolving this issue and mention that you were directed by me (@shilo-ey) and reference this issue. we will try to locate the issue.
> 
> Please share credentials for WP admin, and for the server/FTP access.
> 
> Thanks

Sorry I miss clicked and closed the issue.  I sent you all the login details to a wordpress website just created for you with this issue. Thanks for the help!

**Comment by oliveandlake** [comment] 2020-09-16 08:50
@shilo-ey - I've managed to recreate the issue. These are the steps I take to recreate it. 

1. Go to site settings and change a global colour. Save, exit. 
2. Go to general wordpress settings and change something here. For example, the site name. 
3. Go back to site settings - all reverted back to default.

Here's a video of me doing it. https://www.youtube.com/watch?v=dTiCZt_HVfU

**Comment by DuncanMcCNZ** [comment] 2020-09-16 09:16
Yup, me too.  Nice it can be reproduced.  Cheers.

> @shilo-ey - I've managed to recreate the issue. These are the steps I take to recreate it.
> 
>     1. Go to site settings and change a global colour. Save, exit.
> 
>     2. Go to general wordpress settings and change something here. For example, the site name.
> 
>     3. Go back to site settings - all reverted back to default.
> 
> 
> Here's a video of me doing it. https://www.youtube.com/watch?v=dTiCZt_HVfU

**Comment by SebastianB12** [comment] 2020-09-16 09:32
> @shilo-ey - I've managed to recreate the issue. These are the steps I take to recreate it.
> 
> 1. Go to site settings and change a global colour. Save, exit.
> 2. Go to general wordpress settings and change something here. For example, the site name.
> 3. Go back to site settings - all reverted back to default.
> 
> Here's a video of me doing it. https://www.youtube.com/watch?v=dTiCZt_HVfU

Yep, same here, my colleague just told me, that he changed the site name in the WP settings, just before the error happend!

**Comment by VonJot** [comment] 2020-09-16 10:59
Additional to the above: When i create a staging of my site ALL color and font settings are back to default. No way to restore...

**Comment by SebastianB12** [comment] 2020-09-16 11:58
Probably the same issue: #12540

**Comment by VonJot** [comment] 2020-09-16 12:03
Correct. Posted additional video footage there. Thanks!

**Comment by TomRaraAvis** [comment] 2020-09-16 12:04
Yep. That’s it. I haven’t tried it again, but I can confirm that I did change my site name yesterday before it broke.

**Comment by cbsa100** [comment] 2020-09-17 10:17
is there a prediction to when will this be fixed?
and will it bring back my old settings or will i need to redo them

**Comment by shilo-ey** [comment] 2020-09-17 14:33
This issue has been resolved in Elementor v3.0.9

Feel free to update

Thanks!

**Closed by shilo-ey** 2020-09-17 14:33 UTC
Labels: bug, status/merged

**Comment by cbsa100** [comment] 2020-09-17 16:03
is there a way to restore my old settings?

**Comment by VonJot** [comment] 2020-09-17 18:28
All solved now. Works like a charm, even after altering the title and site icon.

**Comment by oliveandlake** [comment] 2020-09-18 05:39
Yes, all working for me too.
