### ISSUE TITLE
⛔ 🔗 Hello Theme v. 3.2.1. creates conflict (Duplicate of hello-theme #430)

### ISSUE THREAD

**Issue by Invitinere** [elementor/elementor#29601] opened 2024-12-16 16:12 UTC
### Prerequisites

- [ ] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [ ] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

after updating Hello theme to the version 3.2.1 Gutember editor started not to work properly: text lose formating : a different font, no line lenght, no margins, wrong spaces between lines, no format for H* titles. I tried different solution - managing css files, deactivating plugin, but I could fix the issue only when I restored my site to a date before the update

### Steps to reproduce

update Hello theme to 3.2.1

### Expected behavior

to work as usual in Gutember editor

### Isolating the problem

- [ ] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [ ] This bug happens with the Hello Elementor theme active.
- [X] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

<details>
<summary>Click to reveal</summary>

````txt


== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Source distribution v8.0.39-30
	PHP Version: 8.2.26
	PHP Memory Limit: 768M
	PHP Max Input Vars: 3000
	PHP Max Post Size: 256M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.7.1
	Site URL: https://invitinere.it
	Home URL: https://invitinere.it
	WP Multisite: No
	Max Upload Size: 256 MB
	Memory limit: 256M
	Max Memory limit: 768M
	Permalink Structure: /%postname%/
	Language: it_IT
	Timezone: Europe/Rome
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 3.1.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: it-IT
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36 Edg/131.0.0.0

== Active Plugins ==
	Autoptimize
		Version: 3.1.12
		Author: Frank Goossens (futtta)

	Easy Table of Contents
		Version: 2.0.71
		Author: Magazine3

	Elementor
		Version: 3.25.11
		Author: Elementor.com

	Elementor Pro
		Version: 3.25.5
		Author: Elementor.com

	Header and Footer Scripts
		Version: 2.2.1
		Author: Digital Liberation

	iubenda | All-in-one Compliance for GDPR / CCPA Cookie Consent + more
		Version: 3.11.3
		Author: iubenda

	Link Whisper Free
		Version: 0.7.7
		Author: Link Whisper

	Rank Math SEO
		Version: 1.0.234
		Author: Rank Math SEO

	Security Optimizer
		Version: 1.5.7
		Author: SiteGround

	SiteGround Central
		Version: 3.3.1
		Author: SiteGround

	Speed Optimizer
		Version: 7.7.2
		Author: SiteGround

	WP-Sweep
		Version: 1.1.8
		Author: Lester 'GaMerZ' Chan

	wpDiscuz
		Version: 7.6.27
		Author: gVectors Team


== Utilizzo degli elementi ==
	
	archive : 1
		archive-posts : 1
		container : 9
		form : 1
		heading : 4
		image-box : 1
		nav-menu : 2
		search-form : 1
		social-icons : 1
		text-editor : 2
		theme-archive-title : 1
	container : 1
		container : 5
		heading : 3
		image-box : 1
		nav-menu : 2
		search-form : 1
		social-icons : 1
		text-editor : 1
	footer : 1
		container : 1
		heading : 1
		iub-elementor-legal-widget : 1
	header : 1
		container : 3
		nav-menu : 1
		theme-site-logo : 1
	widget : 0
		form : 1
	wp-post : 
		text-editor : 10
	wp-page : 3
		button : 5
		container : 59
		form : 3
		heading : 21
		image : 20
		image-box : 3
		nav-menu : 6
		posts : 1
		search-form : 3
		slides : 1
		social-icons : 3
		text-editor : 11
		theme-archive-title : 2
	single-post : 1
		author-box : 1
		button : 1
		container : 12
		form : 1
		heading : 6
		image-box : 1
		menu-anchor : 1
		nav-menu : 2
		post-info : 2
		posts : 1
		search-form : 1
		share-buttons : 1
		social-icons : 1
		text-editor : 2
		theme-post-content : 1
		theme-post-excerpt : 1
		theme-post-featured-image : 1
		theme-post-title : 1
		wpDiscuz : 1
	error-404 : 1
		button : 1
		container : 3
		heading : 2


== Impostazioni ==
	
	cpt_support: post, page
	disable_color_schemes: yes
	disable_typography_schemes: yes
	allow_tracking: yes
	unfiltered_files_upload: 1
	font_display: swap


== Caratteristiche ==
	Custom Fonts: 0
	Custom Icons: 0

== Integrazioni ==
	


== Esperimenti Elementor ==
	Caricamento CSS migliorato: Inattivo per impostazione predefinita
	Icone dei font in linea: Attivo per impostazione predefinita
	Punti di interruzione aggiuntivi: Attivo per impostazione predefinita
	Contenitore: Attivo per impostazione predefinita
	Aggiorna la libreria Swiper: Attivo per impostazione predefinita
	Nested Elements Performance: Attivo per impostazione predefinita
	Optimized Control Loading: Attivo per impostazione predefinita
	Markup ottimizzato: Inattivo per impostazione predefinita
	Conditionally load Swiper CSS files: Inattivo per impostazione predefinita
	Plugin Onboarding: Attivo per impostazione predefinita
	CSS Smooth Scroll: Attivo per impostazione predefinita
	Predefinito per Nuovo generatore di temi: Attivo per impostazione predefinita
	Header e Footer: Attivo per impostazione predefinita
	Schermata home di Elementor: Attivo per impostazione predefinita
	Landing Page: Attivo per impostazione predefinita
	Elementi annidati: Attivo per impostazione predefinita
	Barra unificata degli strumenti dell&#039;editor: Attivo per impostazione predefinita
	Pannello pagine: Inattivo per impostazione predefinita
	Cache degli elementi: Inattivo per impostazione predefinita
	Link In Bio: Attivo per impostazione predefinita
	Floating Buttons: Attivo per impostazione predefinita
	Elementor Editor Events: Inattivo per impostazione predefinita
	Atomic Widgets: Inattivo per impostazione predefinita
	Launchpad Checklist: Inattivo per impostazione predefinita
	Menu: Inattivo per impostazione predefinita


== Registro ==
	
Log: showing 20 of 422024-11-21 13:43:59 [info] elementor-pro::elementor_pro_updater Started 
2024-11-21 13:43:59 [info] Elementor Pro/Upgrades - _on_each_version Start  
2024-11-21 13:43:59 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2024-11-21 13:43:59 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.25.3',
  'to' => '3.25.4',
)]
2024-11-21 13:43:59 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.25.3',
  'to' => '3.25.4',
)]
2024-11-25 05:02:30 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.25.9',
  'to' => '3.25.10',
)]
2024-11-25 05:12:13 [info] elementor::elementor_updater Started 
2024-11-25 05:12:13 [info] Elementor/Upgrades - _on_each_version Start  
2024-11-25 05:12:13 [info] Elementor/Upgrades - _on_each_version Finished 
2024-11-25 05:12:13 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.25.9',
  'to' => '3.25.10',
)]
2024-12-10 16:12:34 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.25.10',
  'to' => '3.25.11',
)]
2024-12-10 16:17:22 [info] elementor::elementor_updater Started 
2024-12-10 16:17:22 [info] Elementor/Upgrades - _on_each_version Start  
2024-12-10 16:17:22 [info] Elementor/Upgrades - _on_each_version Finished 
2024-12-10 16:17:22 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.25.10',
  'to' => '3.25.11',
)]
2024-12-12 09:48:15 [info] elementor-pro::elementor_pro_updater Started 
2024-12-12 09:48:15 [info] Elementor Pro/Upgrades - _on_each_version Start  
2024-12-12 09:48:15 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2024-12-12 09:48:15 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.25.4',
  'to' => '3.25.5',
)]
2024-12-12 09:48:15 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.25.4',
  'to' => '3.25.5',
)]

PHP: showing 1 of 1PHP: 2024-12-16 17:11:07 [warning X 1][../wp-content/plugins/elementor/modules/usage/module.php::80] Undefined array key &quot;publish&quot; [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]



== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatibile

== Elementor Pro - Compatibility Tag ==

````

</details>

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by nicholaszein** [comment] 2024-12-16 17:23
Hello @Invitinere!

Thank you for reaching out! 🙏 

Please not this repository is exclusively reserved to report validated bugs in the Elementor Editor plugin (for both Core and Pro versions), and should not be used for other products. The issue you're reporting was already discussed and resolved in the hello-theme repository, issue [#430](https://github.com/elementor/hello-theme/issues/430).

I see in your Elementor System Info that you have at least 3 performance optimization plugins active, two of them related to cache, and you also host your site on SiteGround, which include server-side cache enabled by default. It is likely you are still experiencing problems due to your several levels of cache applied to your site.

Please make sure you purge, clear, and flush all levels of cache applied to your site, including but not limited to server cache, site cache (plugins), CDN cache (of any), and last but not least Browser cache.

While testing the latest version of the Hello Elementor theme, we cannot reproduce your issue, as it was already resolved as mentioned above. See the video below for proof:


https://github.com/user-attachments/assets/62e3e486-a593-49a5-aef7-41b232b5d397

Just for the sake of completion, we have the following Elementor Performance Settings in this test website:

![image](https://github.com/user-attachments/assets/723be347-31fa-4089-a81e-6a0843607539)



For the reasons above, we consider this is not a bug caused by the Hello Elementor anymore, nor by Elementor itself, therefore we are closing this issue.

Next time, please refer to the correct repository for a quicker resolution.

Kind regards

**Closed by nicholaszein** 2024-12-16 17:23 UTC
Labels: type/styles, mod*, duplicate, compatibility/wordpress-editor, mod/d*, mod/b*, product/hello-theme
