### ISSUE TITLE
🔗 ❌ 🐞 WordPress throws a warning about the missing options in the site-logo.php when using PHP 8+ (Duplicate of #24337)

### ISSUE THREAD

**Issue by tcchkhk** [elementor/elementor#24456] opened 2023-11-30 04:25 UTC
### Prerequisites

- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest stable version of Elementor.

### Description

Warning: Undefined array key "options" in /home1/childsz9/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/widgets/site-logo.php on line 192

### Steps to reproduce

I am not sure

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently following the steps above.

### System Info

Warning: Undefined array key "options" in /home1/childsz9/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/widgets/site-logo.php on line 192

**Comment by nicholaszein** [comment] 2023-11-30 12:52
Hello @tcchkhk!

Thank you for your submission! 🙏 

### 🔗 🐞 This issue is a Duplicate of #24337

Which is on the same subject. 

For this reason, I'm closing this thread and 🔃 **Merging** it with the original, so we can have all the discussions in one location, and deal with it more efficiently.

Feel free to continue the conversation there. 😉 

### 🔍 Please, in the future, remember to check if there isn't any thread similar to yours already opened. 

Kind regards

We appreciate your involvement in our community. For efficient troubleshooting, please remember to include the **<br /><ins>FULL, and essential</ins> [System Info](https://elementor.com/help/hare-my-system-info/)** with each issue reported. We'll need it to help you effectively. 

#### ⚠️ As a gentle reminder, issues without it may need to be closed without troubleshooting. Providing this information upfront aligns with our guidelines, saves time, and ensures swift resolution. Thank you for understanding.

**Closed by nicholaszein** 2023-11-30 12:52 UTC
Labels: product/pro, compatibility/php_8, mod*, component/site-logo
