### ISSUE TITLE
Feature Request:Adding Popup trigger support to Nav Menu Items

### ISSUE THREAD

**Issue by IvanIntern** [elementor/elementor#7378] opened 2019-03-08 08:16 UTC
**What problem is your feature request going to solve? Please describe.**

Better responsive web design and less workarounds.
 
**Describe the solution you'd like**

When clicking on a Nav Menu Widget Item, I want it to open a popup

- [X ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**Comment by bainternet** [comment] 2019-03-10 08:26
Duplicate of #6876

**Closed by bainternet** 2019-03-10 08:26 UTC
