### ISSUE TITLE
✅ 🐞 Bug Report: Star Rating icon size doesn't work inside Containers

### ISSUE THREAD

**Issue by perks98** [elementor/elementor#20651] opened 2022-12-07 12:29 UTC
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

On a client site I tried to use the star rating widget today and there seems to be an issue with the sizing. Video below will better explain:

https://user-images.githubusercontent.com/55829113/206177960-633a7a14-651a-47a5-b0c5-a37825eb3fcc.mp4

I believe this is since the 3.9 update as I hadn't had an issue in 3.8+.

### Steps to reproduce

See video in description.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

<details>
<summary>Click to reveal</summary>

````txt


					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MariaDB Server v10.4.26
	PHP Version: 7.4.33
	PHP Memory Limit: 128M
	PHP Max Input Vars: 2500
	PHP Max Post Size: 128M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.1.1
	Site URL: [private]
	Home URL: [private]
	WP Multisite: Yes
	Max Upload Size: 128 MB
	Memory limit: 2048M
	Max Memory limit: 512M
	Permalink Structure: /%postname%/
	Language: en-GB
	Timezone: Europe/London
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor Child
	Version: 1.0.1
	Author: Elementor Team
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.6.1
	Parent Theme Author: Elementor Team

== User ==
	Role: 
	WP Profile lang: en_GB
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36

== Active Plugins ==
	Elementor Pro
		Version: 3.9.0
		Author: Elementor.com


== Network Plugins ==
	Elementor
		Version: 3.9.0
		Author: Elementor.com

	WP Mail SMTP
		Version: 3.6.1
		Author: WPForms


== Elementor Experiments ==
	Optimised DOM Output: Active by default
	Improved asset loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Inactive by default
	Accessibility improvements: Active by default
	Additional Custom Breakpoints: Active by default
	Import Export Template Kit: Active by default
	Hide native WordPress widgets from search results: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active
	Default to New Theme Builder: Active by default
	Hello Theme Header & Footer: Active by default
	Landing pages: Active by default
	Colour Sampler: Active by default
	Favourite Widgets: Active by default
	Admin Top Bar: Active by default
	Lazy Load Background Images: Active
	Save as Default: Active
	Page Transitions: Active by default
	Notes: Active by default
	Loop: Active
	Form Submissions: Active by default
	Scroll Snap: Active by default


== Log ==
	
Log: showing 20 of 222022-11-29 17:25:11 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-11-29 17:25:11 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-11-29 17:25:11 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.9.0-beta2',
  'to' => '3.9.0-beta3',
)]
2022-11-29 17:26:22 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.9.0-beta2',
  'to' => '3.9.0-beta3',
)]
2022-11-29 17:26:22 [info] elementor::elementor_updater Started 
2022-11-29 17:26:22 [info] Elementor/Upgrades - _on_each_version Start  
2022-11-29 17:26:22 [info] Elementor/Upgrades - _on_each_version Finished 
2022-11-29 17:26:22 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.9.0-beta2',
  'to' => '3.9.0-beta3',
)]
2022-12-07 09:06:41 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.9.0-beta3',
  'to' => '3.9.0',
)]
2022-12-07 09:06:43 [info] elementor::elementor_updater Started 
2022-12-07 09:06:43 [info] Elementor/Upgrades - _on_each_version Start  
2022-12-07 09:06:43 [info] Elementor/Upgrades - _on_each_version Finished 
2022-12-07 09:06:43 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.9.0-beta3',
  'to' => '3.9.0',
)]
2022-12-07 09:06:45 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.9.0-beta3',
  'to' => '3.9.0',
)]
2022-12-07 09:09:20 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.9.0-beta3',
  'to' => '3.9.0',
)]
2022-12-07 09:09:21 [info] elementor-pro::elementor_pro_updater Started 
2022-12-07 09:09:21 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-12-07 09:09:21 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-12-07 09:09:21 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.9.0-beta3',
  'to' => '3.9.0',
)]
2022-12-07 09:09:22 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.9.0-beta3',
  'to' => '3.9.0',
)]
			

````

</details>

**Comment by nicholaszein** [comment] 2022-12-09 15:30
Hello @perks98,

I'm having trouble reproducing your issue, it's working as expected for me. Have you inspected the element to see what might be causing the issue? Or maybe you should share the settings you've chosen for your container?

https://user-images.githubusercontent.com/113993460/206736577-c5303879-16e9-4ba5-8a7d-d69e46232afc.mp4

**Comment by nicholaszein** [comment] 2022-12-15 21:02
Hello @perks98,

I've spoken to my manager and there seems to be an issue with the Star Rating widget in some edge cases. This is being investigated and a fix will be introduced when a solution is found.

Kind regards

**Comment by Lord-sstar** [comment] 2023-05-14 10:25
> Hello @perks98,
> 
> I've spoken to my manager and there seems to be an issue with the Star Rating widget in some edge cases. This is being investigated and a fix will be introduced when a solution is found.
> 
> Kind regards

I have the same issue, can you help me?

**Comment by TimSgr** [comment] 2023-09-03 12:02
Its sadly still an issue on chrome for me

**Comment by nicholaszein** [comment] 2023-10-26 05:49
Hello guys!

Thank you so much for your patience! 🙏 

We have great news! 🙌 

### 📢 We're happy to announce that the issue you raised was resolved with the release of the new Rating widget in Elementor v3.17! 🥳 

With this new widget, you have more options to choose the number of rating points, custom icons, and styling options, and it is fully compatible with Google Rich snippets (updated), fully accessible, and compatible with Containers.

Your current Start Rating widgets will remain as they were before this update. But moving forward, only the new Rating widget will be available to add to your layouts.

If you are using the old Star Rating widget, we would recommend that you replace it with the new Rating widget.

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂

**Closed by nicholaszein** 2023-10-26 05:49 UTC
Labels: bug, product/pro, type/styles, type/layout, component/container, component/star-rating, mod*, solved_by_rating
