### ISSUE TITLE
Elementor is blocking filester

### ISSUE THREAD

**Issue by Thumas1** [elementor/elementor#13345] opened 2020-12-17 18:30 UTC
Hey, for some reason elementor is blocking filester after i made a update to 5.6. 

If i deactivate elementor, filester works fine again, for some reason, when elementor is activated it makes the filester plugin, just a white screen, hope you guys can help.

**Comment by Thumas1** [comment] 2020-12-17 18:42
Just tried rolling back to version 5.5.3 WP, and now it works fine again.

**Comment by Aviad-Herman** [comment] 2020-12-21 15:48
Hey, 
I'm not sure but this is probably caused by WP 5.6 upgrading JQuery version from 1.x to 3.x.

As a quickfix until we get a patch up and running you can either:
- Downgrade to WP 5.5.3 (for example using https://de.wordpress.org/plugins/wp-downgrade/)
- Use https://wordpress.org/plugins/enable-jquery-migrate-helper/

We are currently working on a patch that might solve this (might be the same as #13297).

I really hope the next Elementor patch will solve this issue. I'm going to close this issue but please re-open it if the problem persists after the patch.

Thanks for reporting this issue @Thumas1 .

**Closed by Aviad-Herman** 2020-12-21 15:48 UTC
