### ISSUE TITLE
Widget inside a widget or custom Div-Block as custom Widget (more design freedom)

### ISSUE THREAD

**Issue by CaptainJakethe1st** [elementor/elementor#5175] opened 2018-07-23 12:55 UTC
- [x ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Elementor is pretty flexible when it comes to webdesign, however simply cannot compete to a visual editor like webflow. Don't get me wrong, I love you guys ;-) 

But whats missing for me is a function, that allows me to put a widget inside a widget or simply custom divblocks I can put inside divblocks. (dunno if thats possible in wordpress?!)

**Describe the solution you'd like**
Allow widgets inside of other widget -> e.g. icon-list widget inside tab widget 

**Describe alternatives you've considered**
Allow designing custom DIVs and save them as a "widget-template" 

**Additional context**
I think the best solution / USP long term is a widget styler plugin within elementor. I think the best competitor to see how they do it is webflow... 

Love
CaptainJake

**Comment by mylimoproject** [comment] 2018-09-06 20:31
+1

**Comment by shilo-ey** [comment] 2019-12-29 10:15
Duplicate of #2587

**Comment by shilo-ey** [comment] 2019-12-29 10:15
I merged this issue with  #2587, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!

**Closed by shilo-ey** 2019-12-29 10:15 UTC

**Comment by nicholaszein** [comment] 2023-01-11 17:16
Hello there!

We have great news! 🙌 

### 📢 We're happy to announce that this feature was introduced with Elementor **v3.6** and is now a stable experiment since v3.8 as the Flexbox Container! 🥳 

#### We also have the new Nested Tabs experiment, which allows you to add elements inside tabs as well.

You can learn more about the Flexbox Container [here](https://elementor.com/help/what-is-a-container/).

You can learn more about the new **Nested Tabs** experiment [here](https://developers.elementor.com/elementor-3-10-beta/).

✔️ Feel free to check it out and update your plugin to the new version!

Stay tuned for the next versions that will introduce more Nested elements. 😉  

🗨️ Please continue the conversation in issue #2587.

Cheers 🥂
