### ISSUE TITLE
⛔ 🗣️ Feedback: Offset Slides option in the Nested and Loop Carousel limitations

### ISSUE THREAD

**Issue by Michaelgimii** [elementor/elementor#23252] opened 2023-08-01 11:04 UTC
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Hi

Version 3.15 was released and I encountered two problems with the offset slides feature that I had not encountered in the beta version.

1- **Offset slides are not rendered in the editor. But it is only visible in the front end.**  Why really? Just like you, the jet woobuilder plugin uses swiper js. But they render offset slides in the editor, but not in Elementor.

2- **If we enable infinite loop, offset slides will be disabled.** Why are all new features always released incompletely and inefficiently? This is also available in Jet Woobuilder plugin, but not in Elementor. This is what I was shocked to see. Why is everything published incompletely? If offset slides depends on infinite scroll, then what's the point of using it?

### Steps to reproduce

To be honest, I'm really disappointed with the new Elementor updates. New features that are incomplete and have many bugs...

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

-

**Comment by nicholaszein** [comment] 2023-08-03 21:52
Hello @Michaelgimii! 

Thank you for your feedback! 🙏 

### ⛔ What you are reporting is actually not a bug, but simply the expected behavior of this feature. 

### 1. Offset slides are not rendered in the editor

> _**Offset slides are not rendered in the editor. But it is only visible in the front end. Why really? Just like you, the jet woobuilder plugin uses swiper js. But they render offset slides in the editor, but not in Elementor.**_

We discussed this during the Beta phase where you asked the [same question](https://github.com/orgs/elementor/discussions/23010#discussioncomment-6408422). In [my answer](https://github.com/orgs/elementor/discussions/23010#discussioncomment-6411331) I explained that this limitation is due to the fact that we can't load the `Infinite Scroll` inside the editor as this would cause problems with the contents inside each **Carousel Item**. This would essentially duplicate items inside the carousel and moving the widgets inside each item from one item to another would cause duplication problems. **Each Carousel Item** has a unique ID, and can't be duplicated. It needs to be unique, otherwise, this would cause issues with the rendering process and the editor in general. This is different than the JetWooBuilder plugin, here you have the ability to drag & drop widgets inside each item and to change their order. If we allow Infinite Scroll to be visible inside the editor, this would mean having duplicate copies of each item, which would cause rendering issues. To avoid these issues, you can only see the results on the front end.

2- **_If we [<del>enable</del>] disable infinite loop, offset slides will be disabled. Why are all new features always released incompletely and inefficiently? This is also available in Jet Woobuilder plugin, but not in Elementor. This is what I was shocked to see. Why is everything published incompletely? If offset slides depends on infinite scroll, then what's the point of using it?_**

We can't predict how many items will be inside each carousel, and calculating them can cause performance issues. For this reason, `Offset Slides` are only available if `Infinite Scroll` is enabled too. If we separated these options we would have the issue above, alongside a design issue that would cause the last item in the carousel to have an empty offset. Differently from other solutions, we are strictly using CSS for the `Offset Slides` feature, to improve performance and allow for customization. If you inspect the element you will see that the `Offset Slides` option will add padding to the edges of the carousel.

As you can see we put a lot of thought into enabling these features, and how they would impact the editing experience and flexibility of usage. We understand that these might not be ideal for everyone, but for most users, this should cover all usage cases well enough.

I hope you can understand why we made these choices.

Thank you for your feedback! We take it very seriously and we will keep investigating ways to improve the functionality and workflow of these features. If we find better ways to implement them, we will consider making those changes.

Kind regards

**Closed by nicholaszein** 2023-08-03 21:52 UTC
Labels: product/pro, component/loop-builder/carousel, mod*, component/nested/carousel
