### ISSUE TITLE
Swiper slidesPerView not working in 3.5.1

### ISSUE THREAD

**Issue by david-strejc** [elementor/elementor#17262] opened 2021-12-21 12:39 UTC
In Elementor 3.4.8 option:

`slidesPerView`
is working 

in 3.5.1 it is not.

Is this desired behaviour of swiper?

`  var swiperOptions = {
      slidesPerView: slidesToShow,
      loop: 'yes' === elementSettings[this.getSkinPrefix() + 'infinite'],
      speed: elementSettings[this.getSkinPrefix() + 'speed'],
      handleElementorBreakpoints: true
    };
`

**Comment by shilo-ey** [comment] 2021-12-22 14:32
please share your system info

**Comment by david-strejc** [comment] 2021-12-22 14:47
`
### wp-core ###

version: 5.8.2
site_language: en_US
user_language: en_US
timezone: Europe/Prague
permalink: /%postname%/
https_status: true
multisite: false
user_registration: 0
blog_public: 1
default_comment_status: open
environment_type: production
user_count: 10
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: /home/ecg-electro.eu/public_html
wordpress_size: 42.45 GB (45584444344 bytes)
uploads_path: /home/ecg-electro.eu/public_html/wp-content/uploads
uploads_size: 42.32 GB (45435833169 bytes)
themes_path: /home/ecg-electro.eu/public_html/wp-content/themes
themes_size: 2.82 MB (2959131 bytes)
plugins_path: /home/ecg-electro.eu/public_html/wp-content/plugins
plugins_size: 288.30 MB (302300428 bytes)
database_size: 1.77 GB (1898283008 bytes)
total_size: 86.82 GB (93223820080 bytes)

### wp-dropins (1) ###

advanced-cache.php: true

### wp-active-theme ###

name: HelloElementorChild (HelloElementorChild)
version: 1.0
author: jakub
author_website: (undefined)
parent_theme: Hello Elementor (hello-elementor)
theme_features: core-block-patterns, widgets-block-editor, post-thumbnails, menus, automatic-feed-links, title-tag, html5, custom-logo, editor-style, align-wide, woocommerce, wc-product-gallery-zoom, wc-product-gallery-lightbox, wc-product-gallery-slider
theme_path: /home/ecg-electro.eu/public_html/wp-content/themes/HelloElementorChild
auto_update: Disabled

### wp-parent-theme ###

name: Hello Elementor (hello-elementor)
version: 2.4.1 (latest version: 2.4.2)
author: Elementor Team
author_website: https://elementor.com/?utm_source=wp-themes&utm_campaign=author-uri&utm_medium=wp-dash
theme_path: /home/ecg-electro.eu/public_html/wp-content/themes/hello-elementor
auto_update: Disabled

### wp-mu-plugins (3) ###

ajax-disable-plugins.php: author: (undefined), version: (undefined)
Elementor Safe Mode: version: 1.0.0, author: Elementor.com
pdf-generator-disable-plugins.php: author: (undefined), version: (undefined)

### wp-plugins-active (60) ###

Admin Columns Pro: version: 5.5.3, author: AdminColumns.com, Auto-updates enabled
Admin Columns Pro - Advanced Custom Fields (ACF): version: 2.6.4, author: AdminColumns.com, Auto-updates enabled
Admin Columns Pro - WooCommerce: version: 3.5.10, author: AdminColumns.com, Auto-updates enabled
Advanced Custom Fields Multilingual: version: 1.9.3, author: OnTheGoSystems, Auto-updates enabled
Advanced Custom Fields PRO: version: 5.11.4, author: Delicious Brains, Auto-updates enabled
Category Order and Taxonomy Terms Order: version: 1.5.7.7, author: Nsp-Code, Auto-updates enabled
Classic Editor: version: 1.6.2, author: WordPress Contributors, Auto-updates enabled
Custom Post Type UI: version: 1.10.1, author: WebDevStudios, Auto-updates enabled
Disable Comments: version: 2.3.2, author: WPDeveloper, Auto-updates enabled
Dynamic.ooo - Dynamic Content for Elementor: version: 2.2.5, author: Dynamic.ooo (latest version: 2.2.6), Auto-updates enabled
Easy Updates Manager: version: 9.0.12, author: Easy Updates Manager Team, Auto-updates enabled
Ele Custom Skin: version: 3.1.4, author: Dudaster.com, Auto-updates enabled
Ele Custom Skin Pro: version: 3.1.0, author: Dudaster.com, Auto-updates enabled
Elementor: version: 3.4.8, author: Elementor.com, Auto-updates enabled
Elementor Contact Form DB: version: 1.7, author: Sean Barton - Tortoise IT, Auto-updates enabled
Elementor Pro: version: 3.5.2, author: Elementor.com, Auto-updates enabled
EWWW Image Optimizer: version: 6.3.0, author: Exactly WWW, Auto-updates enabled
FiboSearch - AJAX Search for WooCommerce (Pro): version: 1.13.0, author: FiboSearch Team, Auto-updates enabled
GDPR Cookie Consent: version: 2.0.6, author: WebToffee, Auto-updates enabled
Google Analytics for WordPress by MonsterInsights: version: 8.3.0, author: MonsterInsights, Auto-updates enabled
JC Submenu: version: 0.9.1, author: James Collings, Auto-updates enabled
JetBlocks For Elementor: version: 1.2.10, author: Crocoblock, Auto-updates enabled
JetCompareWishlist For Elementor: version: 1.3.5, author: Crocoblock, Auto-updates enabled
JetElements For Elementor: version: 2.6.1, author: Crocoblock, Auto-updates enabled
JetMenu: version: 2.1.4, author: Crocoblock, Auto-updates enabled
JetPopup: version: 1.5.5, author: Crocoblock, Auto-updates enabled
JetProductGallery For Elementor: version: 2.1.0, author: Crocoblock, Auto-updates enabled
JetSmartFilters: version: 2.3.7, author: Crocoblock, Auto-updates enabled
JetTabs For Elementor: version: 2.1.15, author: Crocoblock, Auto-updates enabled
JetTricks: version: 1.3.9, author: Crocoblock, Auto-updates enabled
JetWooBuilder For Elementor: version: 1.11.4, author: Crocoblock, Auto-updates enabled
jQuery Manager for WordPress: version: 1.10.6, author: Remzi Cavdar, Auto-updates enabled
Loco Translate: version: 2.5.5, author: Tim Whitlock, Auto-updates enabled
Permalink Manager Pro: version: 2.2.14, author: Maciej Bis, Auto-updates enabled
Product Data Sheet Generator: version: 1.0.0, author: WPDistro.cz, Auto-updates enabled
Rank Math SEO: version: 1.0.78, author: Rank Math, Auto-updates enabled
Real3D Flipbook: version: 3.17.1, author: creativeinteractivemedia, Auto-updates enabled
Webcraftic Clearfy – WordPress optimization plugin: version: 2.0.0, author: Creative Motion <info@cm-wp.com>, Auto-updates enabled
WooCommerce: version: 6.0.0, author: Automattic, Auto-updates enabled
WooCommerce Multilingual: version: 4.12.1, author: OnTheGoSystems, Auto-updates enabled
WP Activity Log: version: 4.3.3.1, author: WP White Security, Auto-updates enabled
WP Activity Log for WooCommerce: version: 1.3.1, author: WP White Security, Auto-updates enabled
WP All Export - ACF Export Add-On Pro: version: 1.0.3, author: Soflyy, Auto-updates enabled
WP All Export - WooCommerce Export Add-On Pro: version: 1.0.3, author: Soflyy, Auto-updates enabled
WP All Export Pro: version: 1.7.2, author: Soflyy, Auto-updates enabled
WP All Import - ACF Add-On: version: 3.3.5, author: Soflyy, Auto-updates enabled
WP All Import - User Import Add-On Pro: version: 1.1.6, author: Soflyy, Auto-updates enabled
WP All Import - WooCommerce Add-On Pro: version: 3.2.8, author: Soflyy, Auto-updates enabled
WP All Import Pro: version: 4.7.1, author: Soflyy, Auto-updates enabled
WPDistro Code Snippets: version: 1.2.0, author: WPDistro, Auto-updates enabled
WPDistro Elements: version: 1.5, author: mozko, Auto-updates enabled
WP Mail Logging: version: 1.10.2, author: Wysija, Auto-updates enabled
WP Mail SMTP: version: 3.2.1, author: WPForms, Auto-updates enabled
WPML All Import: version: 2.2.0, author: OnTheGoSystems, Auto-updates enabled
WPML Multilingual CMS: version: 4.4.12, author: OnTheGoSystems, Auto-updates enabled
WPML String Translation: version: 3.1.10, author: OnTheGoSystems, Auto-updates enabled
WPML Translation Management: version: 2.10.8, author: OnTheGoSystems, Auto-updates enabled
WP Rocket: version: 3.10.5.1, author: WP Media, Auto-updates enabled
WP Rollback: version: 1.7.1, author: Impress.org, Auto-updates enabled
Yoast Duplicate Post: version: 4.3, author: Enrico Battocchi & Team Yoast, Auto-updates enabled

### wp-plugins-inactive (3) ###

404page - your smart custom 404 error page: version: 11.3.0, author: Peter Raschendorfer, Auto-updates enabled
Admin Menu Editor: version: 1.10, author: Janis Elsts, Auto-updates enabled
PixelYourSite: version: 8.2.15, author: PixelYourSite, Auto-updates enabled

### wp-media ###

image_editor: EWWWIO_GD_Editor
imagick_module_version: Not available
imagemagick_version: Not available
imagick_version: Not available
file_uploads: File uploads is turned off
post_max_size: 1000M
upload_max_filesize: 1000M
max_effective_size: 1,000 MB
max_file_uploads: 200
gd_version: 2.2.5
gd_formats: GIF, JPEG, PNG, WebP, BMP, XPM
ghostscript_version: 9.27

### wp-server ###

server_architecture: Linux 4.19.0-16-amd64 x86_64
httpd_software: Apache/2.4.38
php_version: 7.4.26 64bit
php_sapi: fpm-fcgi
max_input_variables: 5000
time_limit: 1800
memory_limit: 8192M
max_input_time: 1800
upload_max_filesize: 1000M
php_post_max_size: 1000M
curl_version: 7.64.0 OpenSSL/1.1.1d
suhosin: false
imagick_availability: false
pretty_permalinks: true
htaccess_extra_rules: true

### wp-database ###

extension: mysqli
server_version: 10.3.31-MariaDB-0+deb10u1-log
client_version: mysqlnd 7.4.26

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: /home/ecg-electro.eu/public_html/wp-content
WP_PLUGIN_DIR: /home/ecg-electro.eu/public_html/wp-content/plugins
WP_MEMORY_LIMIT: 8192M
WP_MAX_MEMORY_LIMIT: 8192M
WP_DEBUG: false
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: false
SCRIPT_DEBUG: false
WP_CACHE: true
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_LOCAL_DEV: undefined
DB_CHARSET: utf8mb4
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable
mu-plugins: writable
0: Writable

### redux-framework ###

version: 4.3.3
installation: plugin
data directory: /home/ecg-electro.eu/public_html/wp-content/plugins/wp-mail-logging/lib/vendor/redux-framework/redux-core/
browser: 
	Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.93 Safari/537.36
	Browser: Chrome
	Version: 96.0.4664.93
	Platform: Linux

### redux-instance-wpml_settings ###

opt_name: wpml_settings
global_variable: wpml_settings
dev_mode: false
ajax_save: true
page_slug: wpml_plugin_settings
page_permissions: manage_options
menu_type: hidden
page_parent: wpml_plugin_log
compiler: true
output: true
output_tag: true
templates_path: undefined
extensions: 
	Customizer: 4.0.0
	Import Export: 4.0.0
	Metaboxes: 4.0.0
	Options Object: 4.0.0

### wp_mail_smtp ###

version: 3.2.1
license_key_type: lite
debug: No debug notices found.
db_tables: wp_wpmailsmtp_tasks_meta, wp_wpmailsmtp_debug_events
lite_install_date: Jan 6, 2021 @ 10:06am

`

**Comment by shilo-ey** [comment] 2022-01-23 15:47
This issue has been resolved in Elementor v3.5.4

Feel free to update

Thanks!

**Closed by shilo-ey** 2022-01-23 15:47 UTC
Labels: status/merged

**Comment by ivanverona1** [comment] 2022-01-24 14:53
THE ISSUE IS NOT SOLVED!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by tom-baboon-branding** [comment] 2022-01-27 10:00
It isn't solved..
