### ISSUE TITLE
🐞 Bug report: HTML 5 Semantic Tagging of <main> </main>

### ISSUE THREAD

**Issue by ceejayuk** [elementor/elementor#19018] opened 2022-06-27 17:26 UTC
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

As the out of the box functionality of Elementor only supports tagging per section, adding the main tag to a section means that only the content of that section can be placed within the <main> and </main> tags (with Elementor generating the </main> tag at the end of the section).

As most pages on my websites use multiple sections which need to go inside the main tags, I've tried to use the HTML widget to manually add the <main> and </main> tags - usually after the <header> tag and before the <footer> tag as the attached diagram from a SEMRush blog article suggests.

### Steps to reproduce

However, when I attempt to add the </main> tag I get the error:
- Unexpected end tag (main) after the (implied) root file element

Clearly just adding a <header> tag to one section is damaging to the site's SEO BUT if I try to resolve this as above, I'm worried that ignoring this Elementor error message may also cause problems.

Thank you.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

Operating System: | Linux |  
Software: | Apache |  
MySQL version: | Source distribution v5.7.32-35 |  
PHP Version: | 7.4.30 |  
PHP Memory Limit: | 768M |  
PHP Max Input Vars: | 3000 |  
PHP Max Post Size: | 256M |
GD Installed: | Yes |  
ZIP Installed: | Yes |  
Write Permissions: | All right |  
Elementor Library: | Connected
![semantic-html5-markup-related-aside](https://user-images.githubusercontent.com/97218201/175999790-24934f35-34a5-42ae-8867-b6f3c733c903.jpg)
![main closing tag issue](https://user-images.githubusercontent.com/97218201/175999797-f0a43ef5-ebe4-4ae5-a941-729b608d82e3.jpg)

**Comment by rami-elementor** [comment] 2022-07-03 12:16
If this is what you are doing:


![main closing tag issue](https://user-images.githubusercontent.com/97218201/175999797-f0a43ef5-ebe4-4ae5-a941-729b608d82e3.jpg)


You are using this tag the wrong ways.

**Comment by rami-elementor** [comment] 2022-07-03 12:19
The HTML widget should contain a tag with the stat-tag and the end-tag.

It's not a bug. I'm closing the ticket.

**Closed by rami-elementor** 2022-07-03 12:19 UTC
Labels: bug

**Comment by rami-elementor** [comment] 2022-07-03 12:36
To solve your issue, I would use an alternative solution. I would use the theme builder to create a post/page template and set the  wrapping HTML tag to `<main>`.


![Elementor-Elementor-Single-Page-100](https://user-images.githubusercontent.com/92088692/177039958-5b9e2d5f-16ce-4487-9b70-b2b7b2fa675b.png)

**Comment by ceejayuk** [comment] 2022-07-03 13:00
Hi Rami,

Thank you for getting back to me. The HTML widgets I've been inserting do use the start tag of: <main> and end tag of </main>. Is this what you mean? It's for this reason that Unexpected end tag error makes no sense.

Re your suggestion of using the theme builder. That's a great idea, thank you. Problem I have is that I've 100s of pages/posts to tag of exisitng pages that are not build with the theme builder, hence manually adding the tags using the HTML widget (since Elementor's in-built method only allows a single section to be tagged.

Thank you ,
Carl
