### ISSUE TITLE
🔗 Javascript Type Error: __webpack_require__.O is not a function (Duplicate of #24492)

### ISSUE THREAD

**Issue by jazir555** [elementor/elementor#29276] opened 2024-11-13 02:16 UTC
### Prerequisites

- [ ] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [ ] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

Javascript type error reported in the debug log:

```txt
TypeError: __webpack_require__.O is not a function. (In '__webpack_require__.O(0, ["frontend-modules"], () => (__webpack_exec__("../assets/dev/js/frontend/frontend.js")))', '__webpack_require__.O' is undefined) in ../wp-content/plugins/elementor/assets/js/frontend.js?ver=3.25.5 on line 2981 column 31 at https://example.com/?post_type=elementor_library&p=23138&elementor-preview=23138&ver=1731462866
```

### Steps to reproduce

Enable debug logging with debug log manager

### Expected behavior

No javascript type error

### Isolating the problem

- [ ] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [X] This bug happens with the Hello Elementor theme active.
- [X] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

<details>
<summary>Click to reveal</summary>

````txt

== Server Environment ==
	Operating System: Linux
	Software: nginx/1.26.2
	MySQL version: mariadb.org binary distribution v11.4.3-MariaDB-ubu2204-log
	PHP Version: 7.4.33
	PHP Memory Limit: 256M
	PHP Max Input Vars: 20000
	PHP Max Post Size: 100M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.6.2
	Site URL: https://motrati.com
	Home URL: https://motrati.com
	WP Multisite: No
	Max Upload Size: 100 MB
	Memory limit: 512M
	Max Memory limit: 256M
	Permalink Structure: /%postname%/%year%/
	Language: en_CA
	Timezone: America/Vancouver
	Debug Mode: Active

== Theme ==
	Name: Hello Elementor
	Version: 3.1.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en-CA
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36

== Active Plugins ==
	Advanced Database Cleaner PRO
		Version: 3.2.10
		Author: Younes JFR.

	Chaty
		Version: 3.3.1
		Author: Premio

	Cloudflare
		Version: 4.12.8
		Author: Cloudflare, Inc.

	Clover Payments for WooCommerce
		Version: 1.0.12
		Author: Clover eCommerce

	Debug Log Manager
		Version: 2.3.3
		Author: Bowo

	Docket Cache
		Version: 24.07.01
		Author: Nawawi Jamili

	Duplicator Pro
		Version: 4.5.19.2
		Author: Duplicator

	Elementor
		Version: 3.25.5
		Author: Elementor.com

	Elementor Pro
		Version: 3.25.2
		Author: Elementor.com

	Facebook for WooCommerce
		Version: 3.3.0
		Author: Facebook

	File Manager Advanced
		Version: 5.2.10
		Author: modalweb

	FluentCRM - Marketing Automation For WordPress
		Version: 2.9.25
		Author: WP Email Newsletter Team - FluentCRM

	FluentCRM Pro
		Version: 2.9.25
		Author: Fluent CRM

	Fluent Forms
		Version: 5.2.4
		Author: Contact Form - WPManageNinja LLC

	Fluent Forms PDF Generator
		Version: 1.1.8
		Author: WPManageNinja LLC

	FluentSMTP
		Version: 2.2.81
		Author: FluentSMTP & WPManageNinja Team

	Fluent Support
		Version: 1.8.4
		Author: WPManageNinja LLC

	Google for WooCommerce
		Version: 2.8.6
		Author: WooCommerce

	Header Footer Code Manager
		Version: 1.1.39
		Author: DraftPress

	iThemes Security Pro
		Version: 7.1.2
		Author: iThemes

	Lazy Load Clarity
		Version: 1.1.1
		Author: Jorcus

	Matomo Analytics - Ethical Stats. Powerful Insights.
		Version: 5.1.5
		Author: Matomo

	Microsoft Clarity
		Version: 0.10.2
		Author: Microsoft

	Patchstack Security
		Version: 2.2.13
		Author: Patchstack

	Perfmatters
		Version: 2.3.4
		Author: forgemedia

	Pinterest for WooCommerce
		Version: 1.4.12
		Author: WooCommerce

	Product Feed PRO for WooCommerce
		Version: 13.3.8.1
		Author: AdTribes.io

	Safe SVG
		Version: 2.2.6
		Author: 10up

	Simple Custom CSS and JS
		Version: 3.48
		Author: SilkyPress.com

	Squirrly SEO (Newton)
		Version: 12.3.24
		Author: Squirrly

	WooCommerce
		Version: 9.3.3
		Author: Automattic

	WooCommerce Legacy REST API
		Version: 1.0.4
		Author: WooCommerce

	Woocommerce netParcel Shipping Calculator
		Version: 3.0.0
		Author: Rizwan Merchant

	WooCommerce PayPal Payments
		Version: 2.9.4
		Author: WooCommerce

	WooCommerce PDF Invoices, Packing Slips, Delivery Notes and Shipping Labels
		Version: 4.7.1
		Author: WebToffee

	WooCommerce Shipping
		Version: 1.2.2
		Author: WooCommerce

	WooCommerce Shipping &amp; Tax
		Version: 2.8.3
		Author: WooCommerce

	WooPayments
		Version: 8.4.0
		Author: WooCommerce

	WP Google Review Slider
		Version: 15.5
		Author: LJ Apps

	WP Rocket
		Version: 3.17.2.1
		Author: WP Media


== Must-Use Plugins ==
	_patchstack.php
		Version: 
		Author: 


== Elements Usage ==
	
	wp-page : 24
		button : 3
		container : 192
		divider : 1
		form : 7
		heading : 8
		hotspot : 1
		html : 1
		icon-list : 1
		image : 19
		image-box : 6
		image-carousel : 1
		spacer : 6
		text-editor : 13
		woocommerce-products : 1
	wp-post : 24
		button : 2
		container : 240
		form : 1
		heading : 22
		image-box : 2
		image-carousel : 1
		media-carousel : 1
		spacer : 16
		tabs : 1
		theme-post-title : 2
	product-post : 0


== Settings ==
	
	cpt_support: post, page, e-landing-page, woodmart_layout, woodmart_woo_lv, woodmart_woo_fbt, cms_block, woodmart_size_guide, woodmart_slide, woodmart_sidebar, portfolio, product
	disable_color_schemes: yes
	disable_typography_schemes: yes
	allow_tracking: yes
	unfiltered_files_upload: 1


== Features ==
	Custom Fonts: 0
	Custom Icons: 0

== Integrations ==
	
	google_maps: Active
	woocommerce: Active


== Elementor Experiments ==
	Improved CSS Loading: Inactive by default
	Inline Font Icons: Active
	Additional Custom Breakpoints: Active
	Container: Active
	Upgrade Swiper Library: Active by default
	Nested Elements Performance: Active by default
	Optimized Control Loading: Active by default
	Optimized Markup: Inactive by default
	Conditionally load Swiper CSS files: Inactive by default
	Plugin Onboarding: Active by default
	CSS Smooth Scroll: Active by default
	Default to New Theme Builder: Active by default
	Header &amp; Footer: Active by default
	Elementor Home Screen: Active by default
	Landing Pages: Active by default
	Nested Elements: Active by default
	Editor Top Bar: Active by default
	Pages Panel: Inactive by default
	Element Caching: Active
	Link In Bio: Active by default
	Floating Buttons: Active by default
	Elementor Editor Events: Inactive by default
	Atomic Widgets: Inactive by default
	Launchpad Checklist: Inactive by default
	Menu: Active


== Log ==
	
Log: showing 20 of 292024-10-31 02:30:12 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.25.1',
  'to' => '3.25.3',
)]
2024-10-31 02:30:13 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.25.1',
  'to' => '3.25.3',
)]
2024-10-31 02:30:13 [info] elementor::elementor_updater Started 
2024-10-31 02:30:13 [info] Elementor/Upgrades - _on_each_version Start  
2024-10-31 02:30:57 [info] Elementor/Upgrades - _on_each_version Finished 
2024-11-01 17:00:27 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.25.0',
  'to' => '3.25.1',
)]
2024-11-07 22:28:54 [info] elementor::elementor_updater Started 
2024-11-07 22:28:55 [info] Elementor/Upgrades - _on_each_version Start  
2024-11-07 22:29:06 [info] Elementor/Upgrades - _on_each_version Finished 
2024-11-07 22:29:06 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.25.3',
  'to' => '3.25.4',
)]
2024-11-07 22:29:20 [info] elementor-pro::elementor_pro_updater Started 
2024-11-07 22:29:20 [info] Elementor Pro/Upgrades - _on_each_version Start  
2024-11-07 22:29:20 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2024-11-07 22:29:20 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.25.0',
  'to' => '3.25.2',
)]
2024-11-07 22:29:23 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.25.0',
  'to' => '3.25.2',
)]
2024-11-12 12:47:11 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.25.4',
  'to' => '3.25.5',
)]
2024-11-12 12:47:11 [info] elementor::elementor_updater Started 
2024-11-12 12:47:11 [info] Elementor/Upgrades - _on_each_version Start  
2024-11-12 12:47:41 [info] Elementor/Upgrades - _on_each_version Finished 
2024-11-12 12:47:41 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.25.4',
  'to' => '3.25.5',
)]

JS: showing 11 of 11JS: 2024-10-29 23:07:14 [error X 3][https://motrati.com/wp-admin/load-scripts.php?c=0&amp;loadchunk_0=jquery-core,jquery-migrate,utils,wp-hooks&amp;ver=6.6.2:2:28767] undefined is not an object (evaluating &#039;c[0].value&#039;) 
JS: 2024-11-01 00:46:23 [error X 1][https://motrati.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.25.3:3:837991] undefined is not an object (evaluating &#039;T.originalEvent.key.toLowerCase&#039;) 
JS: 2024-11-11 00:58:16 [error X 1][https://motrati.com/wp-content/plugins/elementor/assets/js/editor-loader-v2.js?ver=3.25.4:18:17] undefined is not an object (evaluating &#039;window.elementor.start&#039;) 
JS: 2024-11-11 00:58:16 [error X 2][https://motrati.com/wp-content/plugins/elementor/assets/js/container-converter.js?ver=3.25.4:266:16] Can&#039;t find variable: elementor 
JS: 2024-11-11 18:43:07 [error X 1][https://motrati.com/wp-content/plugins/elementor/assets/js/editor.js?ver=3.25.4:32603:30] undefined is not an object (evaluating &#039;this.view.container.isDesignable&#039;) 
JS: 2024-11-12 05:14:22 [error X 3][https://motrati.com/wp-content/plugins/elementor/assets/js/editor.js?ver=3.25.4:41242:70] undefined is not an object (evaluating &#039;event.originalEvent.key.toLowerCase&#039;) 
JS: 2024-11-12 05:23:45 [error X 11][https://motrati.com/wp-content/plugins/elementor/assets/js/editor.js?ver=3.25.4:41270:11] undefined is not an object (evaluating &#039;this.store.find(function (element) { return element.original === char; }).localized&#039;) 
JS: 2024-11-12 07:32:51 [error X 1][https://motrati.com/wp-content/plugins/elementor-pro/assets/lib/sticky/jquery.sticky.js:183:40] Argument 1 (&#039;element&#039;) to Window.getComputedStyle must be an instance of Element 
JS: 2024-11-12 08:18:08 [error X 4][https://motrati.com/wp-includes/js/jquery/jquery.js?ver=3.7.1:3793:14] undefined is not an object (evaluating &#039;$importNowButton[0].value&#039;) 
JS: 2024-11-13 01:13:20 [error X 7][https://motrati.com/wp-content/plugins/elementor/assets/js/bdd4030576f6a94a4f0d.bundle.js:286:97] null is not an object (evaluating &#039;e.target.closest(&#039;.elementor&#039;).dataset&#039;) 
JS: 2024-11-13 01:14:55 [error X 3][https://motrati.com/wp-content/plugins/elementor/assets/js/editor.js?ver=3.25.5:16224:58] undefined is not an object (evaluating &#039;event.params.args.data.id&#039;) 

PHP: showing 2 of 2PHP: 2024-11-11 23:10:06 [notice X 1][/var/www/motrati.com/htdocs/wp-content/plugins/elementor/includes/managers/image.php::113] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-11-11 23:10:15 [notice X 8][/var/www/motrati.com/htdocs/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::182] Undefined index: editor_post_id [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]



== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatible

== Elementor Pro - Compatibility Tag ==
````

</details>

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by jamieburchell** [comment] 2024-11-13 16:30
@jazir555 This has been [reported already](https://github.com/elementor/elementor/issues/24492).

**Comment by nicholaszein** [comment] 2024-11-18 18:36
Hello @jazir555!

Thank you for your submission! 🙏 

### 🔗 🐞 This issue is a Duplicate of #24492

Which is on the same subject. 

For this reason, I'm closing this thread and 🔃 **Merging** it with the original, so we can have all the discussions in one location, and deal with it more efficiently.

Feel free to continue the conversation there. 😉 

### 🔍 Please, in the future, remember to check if there isn't any thread similar to yours already opened. 

Kind regards

**Closed by nicholaszein** 2024-11-18 18:36 UTC
Labels: bug, editor/site-settings, component/code, compatibility/assets, type/experiment, mod*, site-settings/style-guide, duplicate
