### ISSUE TITLE
Unable to type in to the html element

### ISSUE THREAD

**Issue by jpknz** [elementor/elementor#7668] opened 2019-03-29 18:29 UTC
- [ x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x ] The issue still exists against the latest stable version of Elementor.

Add html widget to elementor page (either in it's own section or part of another section)
Click in to the Edit HTML box under content on the left
Try to type anything
Nothing at all happens

## Isolating the problem

- [ x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ x] This bug happens with a default WordPress theme active.
- [ x] I can reproduce this bug consistently using the steps above.
- [ x] I can reproduce this bug consistently on different sites using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MySQL Community Server - GPL v8.0.13
	PHP Version: 7.2.13
	PHP Max Input Vars: 1000
	PHP Max Post Size: 40M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.1.1
	Site URL: https://dev.***REMOVED***.co.uk
	Home URL: http://dev.***REMOVED***.co.uk
	WP Multisite: No
	Max Upload Size: 40 MB
	Memory limit: 256M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: en-US
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: Twenty Nineteen
	Version: 1.2
	Author: the WordPress team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 2.5.10
		Author: Elementor.com

	Elementor Pro
		Version: 2.5.2
		Author: Elementor.com


== Log ==
	: 
Log: showing 18 of 182019-03-29 11:00:51 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.5.9',
  'to' => '2.5.10',
)]
2019-03-29 11:00:51 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.4.8',
  'to' => '2.5.2',
)]
2019-03-29 11:01:14 [info] elementor-pro::elementor_pro_updater Started 
2019-03-29 11:01:14 [info] Elementor Pro/Upgrades - _v_2_5_0_form Start  
2019-03-29 11:01:14 [info] Elementor Pro/Upgrades - _v_2_5_0_form Finished 
2019-03-29 11:01:14 [info] Elementor Pro/Upgrades - _v_2_5_0_woocommerce_menu_cart Start  
2019-03-29 11:01:14 [info] Elementor Pro/Upgrades - _v_2_5_0_woocommerce_menu_cart Finished 
2019-03-29 11:01:14 [info] Elementor Pro/Upgrades - _v_2_5_0_posts Start  
2019-03-29 11:01:14 [info] Elementor Pro/Upgrades - _v_2_5_0_posts Finished 
2019-03-29 11:01:14 [info] Elementor Pro/Upgrades - _v_2_5_0_portfolio Start  
2019-03-29 11:01:14 [info] Elementor Pro/Upgrades - _v_2_5_0_portfolio Finished 
2019-03-29 11:01:14 [info] Elementor Pro/Upgrades - _v_2_5_0_products Start  
2019-03-29 11:01:14 [info] Elementor Pro/Upgrades - _v_2_5_0_products Finished 
2019-03-29 11:01:14 [info] Elementor Pro/Upgrades - _v_2_5_0_sitemap Start  
2019-03-29 11:01:14 [info] Elementor Pro/Upgrades - _v_2_5_0_sitemap Finished 
2019-03-29 11:01:14 [info] Elementor Pro/Upgrades - _v_2_5_0_popup_border_radius Start  
2019-03-29 11:01:14 [info] Elementor Pro/Upgrades - _v_2_5_0_popup_border_radius Finished 
2019-03-29 11:01:14 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.4.8',
  'to' => '2.5.2',
)]


				
```
</details>

**Comment by thimfy** [comment] 2019-03-30 07:47
Do not purchase elementor or any item from creator of it, no support nothing just kind of shit only.

**Comment by jpknz** [comment] 2019-03-30 09:07
I agree the support is lacking but it's a great product that works well and easily (most of the time)

**Comment by shilo-ey** [comment] 2019-03-31 07:16
Hi @jpknz 

Thanks for your feedback.

Unfortunately, we cannot reproduce this issue

Please contact our support at support @elementor.com for guidance in resolving this issue and mention that you were directed by me and reference this issue.

thanks.

**Closed by shilo-ey** 2019-03-31 07:16 UTC

**Comment by TheoOliveira** [comment] 2021-05-09 13:36
Bug is still occurring. I am on Windows 10

**Comment by electro-p** [comment] 2025-02-12 18:34
> Hi [@jpknz](https://github.com/jpknz)
> 
> Thanks for your feedback.
> 
> Unfortunately, we cannot reproduce this issue
> 
> Please contact our support at support @elementor.com for guidance in resolving this issue and mention that you were directed by me and reference this issue.
> 
> thanks.

I have this issue right now, and its so annoying

**Comment by electro-p** [comment] 2025-02-12 18:34
Imagine 4 years later
