### ISSUE TITLE
Tablet Preview on new M1 Macbook Air Safari Browser

### ISSUE THREAD

**Issue by Aebl8** [elementor/elementor#14320] opened 2021-03-22 10:40 UTC
- [ X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X ] The issue still exists against the latest stable version of Elementor.

## Description

When using the Tablet Responsive Modus in the Elementor Page Builder on my Macbook Air (M1) in the Safari Browser the Tablet Mode doesn't change anything.

The Tablet Preview looks exactly like the Mobile Preview in the Pagebuilder but nothing I set gets actually added to the "Tablet Class"

If i inspect the Site in Google Chrome it does show the Tablet Class betwen 768 and 1024 pixels but it doesn't have any styling.

I noticed very late because in the Pagebuilder everything looks normal. The Problem only shows when expecting the Site in the tablet pixel range.

## Steps to reproduce

Go in the Pagebuilder in the Safari Browser (maybe only M1 Mac?) and change Tablet setting and inspect the site. Tablet Changes won't show up.

## Solution

Use any Browser other than Safari, so not the most urgent problem.

## Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a default WordPress theme active.
- [X] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>Macbook Air M1</summary>
					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Source distribution v5.7.32-35
	PHP Version: 7.3.27
	PHP Max Input Vars: 3000
	PHP Max Post Size: 256M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.7
	Site URL: https://www.apotheke-am-weg.idesign.tirol
	Home URL: https://www.apotheke-am-weg.idesign.tirol
	WP Multisite: Yes
	Max Upload Size: 256 MB
	Memory limit: 768M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: en-US
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: Apotheke am Weg
	Version: 1.0.1
	Author: Marco Ströher
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.3.1
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: de_DE
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 11_0_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36

== Network Plugins ==
	Advanced Custom Fields
		Version: 5.9.5
		Author: Elliot Condon

	Advanced Custom Fields PRO
		Version: 5.9.5
		Author: Elliot Condon

	Elementor
		Version: 3.1.4
		Author: Elementor.com

	Elementor Pro
		Version: 3.2.0
		Author: Elementor.com

	SG Optimizer
		Version: 5.7.17
		Author: SiteGround

	Wordfence Security
		Version: 7.4.14
		Author: Wordfence

== Must-Use Plugins ==
	Elementor Safe Mode
		Version: 1.0.0
		Author: Elementor.com

== Elementor - Compatibility Tag ==
	

== Elementor Pro - Compatibility Tag ==
	

== Elements Usage ==
	
	footer : 1
		button : 4
		icon-list : 3
		nav-menu : 2
		social-icons : 1
		text-editor : 9
	header : 1
		button : 2
		icon-list : 4
		image : 3
	wp-page : 3
		divider : 2
		icon-list : 3
		image : 4
		text-editor : 28

== Log ==
	
PHP: showing 3 of 3PHP: 2021-03-20 11:29:12 [notice X 25][/home/customer/www/idesign.tirol/public_html/wp-content/plugins/elementor-pro/modules/dynamic-tags/acf/tags/acf-image.php::40] Undefined offset: 1 [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-03-20 11:54:12 [error X 3][/home/customer/www/idesign.tirol/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::281] Uncaught Error: Call to a member function update_meta() on null in /home/customer/www/idesign.tirol/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:281
Stack trace:
#0 /home/customer/www/idesign.tirol/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(162): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions(22, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /home/customer/www/idesign.tirol/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /home/customer/www/idesign.tirol/public_html/wp-includes/class-wp-hook.php(292): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#4 /home/customer/www/idesign.tirol/public_html/wp [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-03-20 13:11:15 [notice X 1][/home/customer/www/idesign.tirol/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

				
</details>

**Comment by d19dotca** [comment] 2021-03-29 03:18
I can confirm this issue too when editing in tablet mode in the Safari browser, but I am on an Intel Mac so pretty sure this is not related to the M1 processor at all. 

This is a very annoying bug.

Here are my environment details:

<details>
```
macOS 11.3 Beta (20E5217a)
Safari 14.1 (16611.1.21.1.12)

== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.41 (Ubuntu)
	MySQL version: (Ubuntu) v8.0.23
	PHP Version: 7.4.3
	PHP Max Input Vars: 3000
	PHP Max Post Size: 512M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.7
	Site URL: https://www.{domainName}.{tld}
	Home URL: https://www.{domainName}.{tld}
	WP Multisite: No
	Max Upload Size: 512 MB
	Memory limit: 512M
	Permalink Structure: /%category%/%postname%/
	Language: en-CA
	Timezone: America/Vancouver
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.3.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_CA
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1 Safari/605.1.15

== Active Plugins ==
	AuthLDAP
		Version: 2.4.10
		Author: Andreas Heigl <andreas@heigl.org>

	Better Search Replace
		Version: 1.3.4
		Author: Delicious Brains

	Elementor
		Version: 3.1.4
		Author: Elementor.com

	Elementor Pro
		Version: 3.2.1
		Author: Elementor.com

	Enable Media Replace
		Version: 3.5.0
		Author: ShortPixel

	MainWP Child
		Version: 4.1.5
		Author: MainWP

	Pods - Custom Content Types and Fields
		Version: 2.7.26
		Author: Pods Framework Team

	Rank Math SEO
		Version: 1.0.60.1
		Author: Rank Math

	Redis Object Cache
		Version: 2.0.17
		Author: Till Krüss

	ShortPixel Image Optimizer
		Version: 4.21.2
		Author: ShortPixel

	SMTP Mailer
		Version: 1.1.1
		Author: naa986

	WP-Matomo Integration
		Version: 1.0.24
		Author: André Bräkling

	WP Rocket
		Version: 3.8.7
		Author: WP Media


== Elementor - Compatibility Tag ==
	
	Elementor Pro: compatible

== Elementor Pro - Compatibility Tag ==
	


== Elements Usage ==
	
	archive : 1
		archive-posts : 1
		theme-archive-title : 1
	footer : 1
		divider : 1
		heading : 4
		nav-menu : 1
		search-form : 1
		social-icons : 1
		text-editor : 4
	header : 1
		icon-list : 1
		nav-menu : 1
		theme-site-logo : 1
	section : 1
		heading : 1
		posts : 1
	single : 2
		heading : 1
		image : 1
		post-info : 1
		post-navigation : 1
		share-buttons : 1
		theme-post-content : 2
		theme-post-title : 2
	widget : 0
		form : 48
	wp-post : 7
		accordion : 1
		alert : 4
		button : 17
		counter : 2
		divider : 2
		form : 2
		global : 4
		heading : 49
		icon-box : 7
		icon-list : 5
		image : 1
		lottie : 3
		portfolio : 1
		social-icons : 3
		tabs : 3
		template : 1
		testimonial-carousel : 1
		text-editor : 84
		toggle : 1
	wp-page : 13
		accordion : 1
		alert : 1
		button : 13
		call-to-action : 1
		divider : 2
		facebook-page : 1
		form : 1
		heading : 18
		lottie : 1
		menu-anchor : 4
		posts : 2
		price-list : 2
		price-table : 12
		social-icons : 2
		template : 1
		text-editor : 26
	single-post : 1
		button : 1
		divider : 1
		heading : 1
		image : 1
		portfolio : 1
		post-info : 1
		text-editor : 1
		theme-post-content : 1
		theme-post-title : 1
	single-page : 1
		shortcode : 1
		table-of-contents : 1
		text-editor : 1
		theme-post-content : 1
		theme-post-title : 1
	search-results : 1
		archive-posts : 1
		theme-archive-title : 1
	error-404 : 1
		heading : 2
		nav-menu : 1
		search-form : 1


== Log ==
	
Log: showing 20 of 282020-12-29 16:46:43 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.0.8',
  'to' => '3.0.9',
)]
2021-01-06 08:56:21 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.15',
  'to' => '3.0.16',
)]
2021-01-25 13:35:56 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.16',
  'to' => '3.1.0',
)]
2021-01-25 13:36:59 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.0.9',
  'to' => '3.0.10',
)]
2021-01-31 15:07:08 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.1.0',
  'to' => '3.1.1',
)]
2021-02-14 10:07:54 [info] elementor-pro::elementor_pro_updater Started 
2021-02-14 10:07:54 [info] Elementor Pro/Upgrades - _v_3_1_0_media_carousel Start  
2021-02-14 10:07:55 [info] Elementor Pro/Upgrades - _v_3_1_0_media_carousel Finished 
2021-02-14 10:07:55 [info] Elementor Pro/Upgrades - _v_3_1_0_reviews Start  
2021-02-14 10:07:55 [info] Elementor Pro/Upgrades - _v_3_1_0_reviews Finished 
2021-02-14 10:07:55 [info] Elementor Pro/Upgrades - _v_3_1_0_testimonial_carousel Start  
2021-02-14 10:07:55 [info] Elementor Pro/Upgrades - _v_3_1_0_testimonial_carousel Finished 
2021-02-14 10:07:55 [info] Elementor Pro/Upgrades - _v_3_1_0_slides Start  
2021-02-14 10:07:55 [info] Elementor Pro/Upgrades - _v_3_1_0_slides Finished 
2021-02-14 10:07:55 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.0.10',
  'to' => '3.1.0',
)]
2021-02-24 16:22:49 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.1.0',
  'to' => '3.1.1',
)]
2021-03-03 16:29:34 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.1.1',
  'to' => '3.1.3',
)]
2021-03-10 21:16:59 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.1.3',
  'to' => '3.1.4',
)]
2021-03-16 11:17:48 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.1.1',
  'to' => '3.2.0',
)]
2021-03-22 09:39:52 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.2.0',
  'to' => '3.2.1',
)]

JS: showing 10 of 10JS: 2020-09-28 05:18:37 [error X 1][https://www.{domainName}.{tld}/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.0.10:2:421617] t.ui.sync.removeClass is not a function. (In \'t.ui.sync.removeClass(\"eicon-animation-spin\")\', \'t.ui.sync.removeClass\' is undefined) 
JS: 2021-02-20 01:24:09 [error X 1][https://www.{domainName}.{tld}/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view832\") has already been destroyed and cannot be used. 
JS: 2021-02-22 22:01:48 [error X 2][https://www.{domainName}.{tld}/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:17421] Could not find template: \"#tmpl-elementor-templates-modal__header\" 
JS: 2021-02-23 01:14:58 [error X 1][https://www.{domainName}.{tld}/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view890\") has already been destroyed and cannot be used. 
JS: 2021-03-02 21:47:26 [error X 1][https://www.{domainName}.{tld}/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view1945\") has already been destroyed and cannot be used. 
JS: 2021-03-02 21:49:28 [error X 1][https://www.{domainName}.{tld}/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view735\") has already been destroyed and cannot be used. 
JS: 2021-03-02 23:18:26 [error X 6][https://www.{domainName}.{tld}/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view120\") has already been destroyed and cannot be used. 
JS: 2021-03-02 23:18:59 [error X 1][https://www.{domainName}.{tld}/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view912\") has already been destroyed and cannot be used. 
JS: 2021-03-02 23:20:50 [error X 1][https://www.{domainName}.{tld}/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view4246\") has already been destroyed and cannot be used. 
JS: 2021-03-03 00:01:10 [error X 1][https://www.{domainName}.{tld}/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view4774\") has already been destroyed and cannot be used. 

PHP: showing 4 of 4PHP: 2021-03-02 16:01:09 [error X 1][/app/data/public/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::281] Uncaught Error: Call to a member function update_meta() on bool in /app/data/public/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:281
Stack trace:
#0 /app/data/public/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(162): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions()
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions()
#2 /app/data/public/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func()
#3 /app/data/public/wp-includes/class-wp-hook.php(287): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request()
#4 /app/data/public/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters()
#5 /app/data/public/wp-includes/plugin.php(484): WP_Hook->do_action()
#6 /app/data/public/wp-admin/admin-ajax.php(184): do_action()
#7 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-03-09 11:54:39 [notice X 11][/app/data/public/wp-content/plugins/elementor-pro/license/updater.php::75] Undefined index: new_version [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-03-16 11:19:22 [notice X 3][/app/data/public/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-03-16 11:21:06 [notice X 1][/app/data/public/wp-content/plugins/elementor-pro/modules/forms/classes/ajax-handler.php::244] Undefined index: post_id [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
```
</details>

**Comment by d19dotca** [comment] 2021-04-30 20:51
@Aebl8 - Just wanted to confirm... was this fixed for you in 3.2.x?

**Comment by Aebl8** [comment] 2021-05-04 06:00
Hello Dustin,

Sorry for the late answer. Yes, everything is working perfectly thank you very much.

I know this is not the right place to ask but maybe you could help me really quick:

Is there a way to disable the function to directly click edit footer / header template? Maybe through the functions.php file?

Just hiding the functions would be good too.

Thank you very much.

Marco



Ströher Marco
***@***.******@***.***>
0512 931840

Informa GmbH
Klammstraße 46  6020 Innsbruck
FN:  441448p UID: ATU69996089

[cid:12E4A6CD376A415398481C6D0A69679A]

Am 30. Apr. 2021, 22:51 +0200 schrieb Dustin Dauncey ***@***.***>:

@Aebl8<https://github.com/Aebl8> - Just wanted to confirm... was this fixed for you in 3.2.x?

**Comment by d19dotca** [comment] 2021-05-04 15:22
>Yes, everything is working perfectly thank you very much.

Okay, wanted to make sure I wasn't crazy haha. I can confirm this seems fixed for me too. It must have been fixed in 3.2.x. I guess this issue can be marked closed.

>Is there a way to disable the function to directly click edit footer / header template? Maybe through the functions.php file?

I'm unaware of a way for it, but I suspect it's possible. That kind of question would be better suited for the Facebook group or the Elementor Support team.

**Comment by d19dotca** [comment] 2021-06-09 20:23
I suspect this issue can be marked closed at this time.

**Comment by arielk** [comment] 2022-09-12 19:47
I'm closing an issue due to inactivity. If the problem still exists, feel free to reopen the issue or contact our support through your account. 

Thanks!

**Closed by arielk** 2022-09-12 19:47 UTC
