### ISSUE TITLE
🔗 🚀 Feature Request: Loop builder compatibility with popup (quick view for post, post type and WooCommerce) (Duplicate of #7106)

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#20606] opened 2022-12-04 18:22 UTC
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

Hi elementor team.

I tried to put an icon in the loop item so that by clicking on it, more details of the post will be displayed as a pop-up (quick view).

![quick view](https://user-images.githubusercontent.com/77163248/205508113-981db834-3c01-4423-a00e-cd33a16fa420.png)

But after doing this, I noticed that loop builder is not compatible with popup. **The steps I did :**

1- I created a loop and placed an icon inside it so that a popup will be displayed by clicking on it.
2- On the other hand, I created a popup and placed an image widget and a heading widget inside it. I made these two widgets dynamic to the featured image and the title of the post.

At the end, I attached the icon widget to the popup, but in the frontend, after clicking on the icon, the popup is displayed, but none of the post content is displayed.

### Describe the solution you'd like

Compatibility of loop builder with popup **(Post, Post Type and WooCommerce)**

**Comment by black-eye** [comment] 2022-12-05 00:45
I'm afraid this issue is here with us all the way back to 2019: https://github.com/elementor/elementor/issues/7106
Hopefully it will get some more attention with the inroduction of the Loop Builder.

**Comment by nicholaszein** [comment] 2022-12-06 13:40
Hey @79ho3ein!

Thank you for your request! 🙏 

As @black-eye correctly mentioned (thanks 🙏)...

### 🔗 This issue is a Duplicate of #7106.

Which is on the same subject. 

For this reason, I'm closing this issue and 🔃 **Merging** it with the original, so we can have all the discussions in one location, and deal with it more efficiently.

Feel free to continue the conversation there. 😉

**Closed by nicholaszein** 2022-12-06 13:40 UTC
Labels: request/enhancement, product/pro, status/merged, popups, type/dynamic-content, solved-by/loop-builder, solved-by/nested, widget/loop-builder, mod*, duplicate, release/3.26

**Comment by nicholaszein** [comment] 2024-12-16 23:54
Hey guys!

We have great news! 🙌 

### 📢 We're happy to announce that this feature was released with Elementor Pro v3.26.0! 🥳 

You can now use the **Off-Canvas** widget inside your **Loop Item** templates to display additional Dynamic Content for each post in your **Loop Grid** widgets! 🎉 🥳 🙌 

You can learn more about the Off-Canvas widget (and how to use it) here: 
https://elementor.com/help/off-canvas-widget/
And about the Loop Grid here: 
https://elementor.com/help/loop-grid/

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
