### ISSUE TITLE
✔️ 🐞 Bug Report: Form Submissions page doesn't load - returns SyntaxError: Unexpected end of JSON input in console (ED-8550)

### ISSUE THREAD

**Issue by gorzkitomasz** [elementor/elementor#19973] opened 2022-10-03 11:21 UTC
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

 i have the latest version of Elementor but Submission loading issue still hasn't improved. I've tried all options I found in post history but nothing has worked properly. I also disabled plugins, and only see this error in the console. Maybe someone met with this?

`web-cli.min.js?ver=3.7.8:3 Object
error @ web-cli.min.js?ver=3.7.8:3
web-cli.min.js?ver=3.7.8:3 SyntaxError: Unexpected end of JSON input
    at _callee$ (web-cli.min.js?ver=3.7.8:3:75232)
    at tryCatch (web-cli.min.js?ver=3.7.8:3:163868)
    at Generator._invoke (web-cli.min.js?ver=3.7.8:3:163607)
    at Generator.next (web-cli.min.js?ver=3.7.8:3:164351)
    at asyncGeneratorStep (web-cli.min.js?ver=3.7.8:3:157801)
    at _next (web-cli.min.js?ver=3.7.8:3:158034)
    at web-cli.min.js?ver=3.7.8:3:158150
    at new Promise (<anonymous>)
    at web-cli.min.js?ver=3.7.8:3:157970
    at web-cli.min.js?ver=3.7.8:3:75317
error @ web-cli.min.js?ver=3.7.8:3
admin.php:1 Uncaught (in promise) SyntaxError: Unexpected end of JSON input
    at _callee$ (web-cli.min.js?ver=3.7.8:3:75232)
    at tryCatch (web-cli.min.js?ver=3.7.8:3:163868)
    at Generator._invoke (web-cli.min.js?ver=3.7.8:3:163607)
    at Generator.next (web-cli.min.js?ver=3.7.8:3:164351)
    at asyncGeneratorStep (web-cli.min.js?ver=3.7.8:3:157801)
    at _next (web-cli.min.js?ver=3.7.8:3:158034)
    at web-cli.min.js?ver=3.7.8:3:158150
    at new Promise (<anonymous>)
    at web-cli.min.js?ver=3.7.8:3:157970
    at web-cli.min.js?ver=3.7.8:3:75317`

### Steps to reproduce

Elementor / Submission

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: IdeaWebServer/5.0.0 (like Apache)
	MySQL version: MySQL Community Server (GPL) v5.7.33-36
	PHP Version: 7.4.19
	PHP Memory Limit: 256M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 64M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.0.2
	Site URL: https://dev.[hidden]
	Home URL: https://dev.[hidden]
	WP Multisite: No
	Max Upload Size: 64 MB
	Memory limit: 40M
	Max Memory limit: 512M
	Permalink Structure: /%postname%/
	Language: pl-PL
	Timezone: Europe/Warsaw
	Admin Email: web@[hidden]
	Debug Mode: Active

== Theme ==
	Name: Shoptimizer
	Version: 2.4.5
	Author: CommerceGurus
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: pl_PL
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36

== Active Plugins ==
	Better Search Replace
		Version: 1.4.1
		Author: Delicious Brains

	CommerceGurus Commercekit
		Version: 1.3.0
		Author: CommerceGurus

	Converter for Media
		Version: 5.2.4
		Author: Image Optimization Team by matt plugins

	Duplicator Pro
		Version: 4.5.6
		Author: Snap Creek

	Elementor
		Version: 3.7.8
		Author: Elementor.com

	Elementor Pro
		Version: 3.7.7
		Author: Elementor.com

	Loco Translate
		Version: 2.6.2
		Author: Tim Whitlock

	Orphans
		Version: 3.0.3
		Author: Marcin Pietrzak

	Redirection
		Version: 5.3.4
		Author: John Godley

	UpdraftPlus - Backup/Restore
		Version: 1.22.23
		Author: UpdraftPlus.Com, DavidAnderson

	WooCommerce
		Version: 6.9.4
		Author: Automattic

	WordPress Importer
		Version: 0.8
		Author: wordpressdotorg

	WP Extended Search
		Version: 2.1.1
		Author: 5um17

	WP Mail SMTP
		Version: 3.5.2
		Author: WPForms

	Yoast SEO
		Version: 19.7.1
		Author: Team Yoast

	Yoast SEO Premium
		Version: 18.2.1
		Author: Team Yoast

== Must-Use Plugins ==
	Elementor Safe Mode
		Version: 1.0.0
		Author: Elementor.com

== Wykorzystanie elementów ==
	
	archive : 28
		heading : 1
		posts : 1
		template : 1
	header : 6
		button : 1
		image : 1
		nav-menu : 1
		search-form : 2
		social-icons : 2
	page : 4
		form : 2
		heading : 1
		text-editor : 1
	popup : 49
		button : 2
		form : 1
		heading : 11
		icon-list : 8
		image : 5
		text-editor : 2
	section : 7
		button : 1
		form : 1
		heading : 2
		image : 1
		image-carousel : 1
		template : 1
		text-editor : 1
	widget : 0
		form : 1
		search-form : 1
	wp-post : 37
		heading : 35
		image : 959
		text-editor : 88
	wp-page : 19
		accordion : 2
		form : 1
		heading : 3
		template : 1
		text-editor : 3
	single-post : 31
		divider : 2
		heading : 2
		post-comments : 1
		post-navigation : 1
		posts : 1
		search-form : 1
		share-buttons : 1
		template : 1
		theme-post-content : 1
		theme-post-featured-image : 1
		theme-post-title : 1
		wp-widget-tag_cloud : 1
	error-404 : 1
		button : 1
		heading : 3
		image : 2
		text-editor : 2

== Eksperymenty z Elementorem ==
	Zoptymalizowany wynik DOM: Włączono
	Ulepszone ładowanie zasobów: Włączono
	Poprawione ładowanie CSS: Włączono
	Czcionka ikon: Domyślnie nieaktywne
	Ulepszenia w zakresie dostępności: Domyślnie nieaktywne
	Dodatkowe niestandardowe punkty zmiany: Domyślnie nieaktywne
	Import i eksport zestaw szablonów: Domyślnie aktywne
	Ukryj natywne widgety WordPressa w wynikach wyszukiwania: Domyślnie aktywne
	admin_menu_rearrangement: Domyślnie nieaktywne
	Flexbox Container: Domyślnie nieaktywne
	Default to New Theme Builder: Domyślnie aktywne
	Strony docelowe: Domyślnie aktywne
	Próbnik kolorów: Domyślnie aktywne
	Ulubione widgety: Domyślnie aktywne
	Górny pasek administratora: Domyślnie aktywne
	Page Transitions: Włączono
	Notes: Domyślnie aktywne
	Form Submissions: Włączono
	Scroll Snap: Domyślnie aktywne

== Dziennik ==
	
Log: showing 20 of 332022-07-06 09:38:56 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Dynamic.ooo - Dynamic Content for Elementor',
  'from' => '2.5.7',
  'to' => '2.6.3',
)]
2022-08-24 14:14:01 [info] elementor::elementor_updater Started 
2022-08-24 14:14:01 [info] Elementor/Upgrades - _on_each_version Start  
2022-08-24 14:14:01 [info] Elementor/Upgrades - _on_each_version Finished 
2022-08-24 14:14:01 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.7',
  'to' => '3.7.0',
)]
2022-09-20 17:23:48 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.0',
  'to' => '3.7.7',
)]
2022-09-20 17:23:49 [info] elementor::elementor_updater Started 
2022-09-20 17:23:49 [info] Elementor/Upgrades - _on_each_version Start  
2022-09-20 17:23:49 [info] Elementor/Upgrades - _on_each_version Finished 
2022-09-20 17:23:49 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.0',
  'to' => '3.7.7',
)]
2022-10-03 09:53:28 [info] elementor-pro::elementor_pro_updater Started 
2022-10-03 09:53:28 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-10-03 09:53:28 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-10-03 09:53:28 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.2',
  'to' => '3.7.7',
)]
2022-10-03 09:53:28 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.2',
  'to' => '3.7.7',
)]
2022-10-03 09:55:50 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.7',
  'to' => '3.7.8',
)]
2022-10-03 09:55:51 [info] elementor::elementor_updater Started 
2022-10-03 09:55:51 [info] Elementor/Upgrades - _on_each_version Start  
2022-10-03 09:55:53 [info] Elementor/Upgrades - _on_each_version Finished 
2022-10-03 09:55:53 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.7',
  'to' => '3.7.8',
)]

PHP: showing 8 of 8PHP: 2022-07-06 15:37:49 [notice X 116][/[hidden]/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] Argument $control_id jest przestarzały od wersji 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /[hidden]/wp-content/plugins/elementor/modules/dev-tools/deprecation.php(301): class type trigger_error()
#2: /[hidden]/wp-content/plugins/elementor/includes/managers/controls.php(523): Elementor\Modules\DevTools\Deprecation -> deprecated_argument()
#3: /[hidden]/wp-content/plugins/elementor/includes/managers/controls.php(501): Elementor\Controls_Manager -> register()
#4: /[hidden]/wp-content/plugins/elementor-extras/includes/plugin.php(856): Elementor\Controls_Manager -> register_control()
',
)]
PHP: 2022-07-06 15:37:49 [notice X 116][/[hidden]/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] Argument $control_id jest przestarzały od wersji 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /[hidden]/wp-content/plugins/elementor/modules/dev-tools/deprecation.php(301): class type trigger_error()
#2: /[hidden]/wp-content/plugins/elementor/includes/managers/controls.php(523): Elementor\Modules\DevTools\Deprecation -> deprecated_argument()
#3: /[hidden]/wp-content/plugins/elementor/includes/managers/controls.php(501): Elementor\Controls_Manager -> register()
#4: /[hidden]/wp-content/plugins/elementor-extras/includes/plugin.php(857): Elementor\Controls_Manager -> register_control()
',
)]
PHP: 2022-08-05 16:02:35 [notice X 2][/[hidden]/wp-content/plugins/elementor-pro/modules/forms/classes/recaptcha-v3-handler.php::124] Undefined index: score [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-08-10 12:02:13 [notice X 1][/[hidden]/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-08-10 17:56:18 [notice X 276][/[hidden]/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::304] Argument $control_id jest przestarzały od wersji 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /[hidden]/wp-content/plugins/elementor/modules/dev-tools/deprecation.php(304): class type trigger_error()
#2: /[hidden]/wp-content/plugins/elementor/includes/managers/controls.php(523): Elementor\Modules\DevTools\Deprecation -> deprecated_argument()
#3: /[hidden]/wp-content/plugins/elementor/includes/managers/controls.php(501): Elementor\Controls_Manager -> register()
#4: /[hidden]/wp-content/plugins/elementor-extras/includes/plugin.php(856): Elementor\Controls_Manager -> register_control()
',
)]
PHP: 2022-08-10 17:56:18 [notice X 276][/[hidden]/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::304] Argument $control_id jest przestarzały od wersji 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /[hidden]/wp-content/plugins/elementor/modules/dev-tools/deprecation.php(304): class type trigger_error()
#2: /[hidden]/wp-content/plugins/elementor/includes/managers/controls.php(523): Elementor\Modules\DevTools\Deprecation -> deprecated_argument()
#3: /[hidden]/wp-content/plugins/elementor/includes/managers/controls.php(501): Elementor\Controls_Manager -> register()
#4: /[hidden]/wp-content/plugins/elementor-extras/includes/plugin.php(857): Elementor\Controls_Manager -> register_control()
',
)]
PHP: 2022-10-03 09:54:06 [notice X 1][/[hidden]/wp-content/plugins/elementor/core/common/modules/connect/module.php::230] Trying to get property 'email' of non-object [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-10-03 09:55:53 [notice X 34][/[hidden]/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::304] Argument $control_id jest przestarzały od wersji 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 1 of 1JS: 2022-08-10 11:23:27 [error X 1][https://dev.[hidden]/wp-content/plugins/elementor/assets/js/frontend.min.js?ver=3.6.7:2:19300] Cannot read properties of undefined (reading \'top\') 

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Kompatybilność nieokreślona

== Elementor Pro - Compatibility Tag ==

**Comment by nicholaszein** [comment] 2022-10-03 15:59
Hey @gorzkitomasz , 

Thank you for the feedback. 🙏 

Can you please elaborate? What exactly is your issue, what is happening, and what are the steps to reproduce?

While reviewing your report, we noticed it was missing some key pieces of information.

👉 Please follow the guidelines for opening a [new issue report](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml), so we can help you better.

⚠️ This report is missing key information: 

* Detailed description
* Steps to replicate
* Isolating the problem

Without them, we simply can't help. 😕 

👍 Please feel free to open a new issue in accordance with these guidelines.

Best regards,

Nick

**Comment by gorzkitomasz** [comment] 2022-10-03 16:14
Hi Nick :)

Thank You for Your answer. I don't know how else to describe my problem.
Because I tried all possible ways to start "Submission" (Elementor /
Submission) but none of those work and I still see a blank page saying
"Loading". I will mention, that all plugins was uninstalled, but that
didn't help either. I see the following information in the console, maybe
it causes an error? Screen below. Thank You for Your help.

[image: image.png]

Best regards,
Tom

pon., 3 paź 2022 o 17:59 Nicholas Zein ***@***.***>
napisał(a):

**Comment by nicholaszein** [comment] 2022-10-03 18:56
Hello @gorzkitomasz,

thank you for clarifying your issue. I've marked it as a bug and the team will take a look and see if they can reproduce the issue.

Please if you have any other information, let us know.

Right now I can't reproduce your issue consistently, but I might be missing something here.

Best regards,

**Comment by CamelDesign10** [comment] 2022-10-05 08:03
just go in general => permalink and revalidate it and is good normaly is just a redirection problem

**Comment by gorzkitomasz** [comment] 2022-10-05 08:14
Hi @CamelDesign10 
What do you mean? Explain your answer. I think, this has nothing to do with permalinks. Believe me, permalink is working fine and I have refreshed it to be sure - but it didn't help.
all best :)

**Comment by CamelDesign10** [comment] 2022-10-05 08:20
> Hi @CamelDesign10 What do you mean? Explain your answer. I think, this has nothing to do with permalinks. Believe me, permalink is working fine and I have refreshed it to be sure - but it didn't help. all best :)

I had the bug yesterday too and I just revalidated my permalinks to fix it, there was a conflict in the web-cli which returned a javascript A tag that fontawesome was already sending

my error : Error: Uncaught SyntaxError: Identifier 'a' has already been declared (at instant-page.min.js?ver=3.7.1:formatted:1:1)

**Comment by gorzkitomasz** [comment] 2022-10-05 08:40
@CamelDesign10 
I have already tried this before, im disabled and removed Elementor plugin, added it again, installed and configured it. Permalinks refreshed, but this error persists. However, I need to run the Submission option, which is still inactive and I see "Loading" without any no effect.
Thanks for Your tip, but that doesn't solve my problem.

**Comment by computur** [comment] 2022-10-08 23:50
I too am having this issue, even with bypassing my cache and page optimizations, as well as revalidating permalinks; When I try to go to Elementor->Submissions I get a blank page that says "Loading..." which never actually loads. I stumbled upon this thread while troubleshooting and still have not found a solution.

<details>
<summary>Chrome Developer Console Error</summary>
web-cli.min.js?ver=3.7.8:3 <br/>
SyntaxError: Unexpected end of JSON input <br/>
at _callee$ (web-cli.min.js?ver=3.7.8:3:75232) <br/>
at tryCatch (web-cli.min.js?ver=3.7.8:3:163868) <br/>
at Generator._invoke (web-cli.min.js?ver=3.7.8:3:163607) <br/>
at Generator.next (web-cli.min.js?ver=3.7.8:3:164351) <br/>
at asyncGeneratorStep (web-cli.min.js?ver=3.7.8:3:157801) <br/>
at _next (web-cli.min.js?ver=3.7.8:3:158034) <br/>
at web-cli.min.js?ver=3.7.8:3:158150 <br/>
at new Promise (<anonymous>) <br/>
at web-cli.min.js?ver=3.7.8:3:157970 <br/>
at web-cli.min.js?ver=3.7.8:3:75317 <br/>
error @ web-cli.min.js?ver=3.7.8:3 <br/>
</details>

Wordpress 6.0.2
Elementor 3.7.8
Elementor Pro 3.7.7

**Comment by gorzkitomasz** [comment] 2022-10-10 05:27
Unfortunately, I also have this problem all the time. The error still has not been fixed, And I dont have any new response from  Elementor team.

**Comment by orth-zlecenia** [comment] 2022-10-17 10:53
I am facing same issue. It seems that the problem occurs because on IdeaWebServer/5.0.0 you can't fully make use of REST API. The only permitted HTTP request are GET and POST, Elementor uses OPTIONS in this case. Probably you will face similar issue if you try to save Custom Code...

Question is - can it be bypassed somehow? Or - for the sake of detection potencial problems in the future - where else Elementor happens to use HTTP other than GET & POST?

**Comment by gorzkitomasz** [comment] 2022-10-17 12:45
that's not this problem. I double check website on several hosts and same error occurs on all of them.

**Comment by nadavhury** [comment] 2022-10-23 11:43
still has this problem on windows server 2016, all running fine, only this error, kindly waiting for a resolve

**Comment by gorzkitomasz** [comment] 2022-10-24 14:31
I recommend you do a test on a clean Elementor / Wordpres installation, and do check few different types of forms and saving different data to Submission. I feel that, this error is related to saving data from forms with a large amount of data. This is my first conclusion after my own tests.

but, but - where is the Elementor team with support? :/

**Comment by Nevoss** [comment] 2022-11-10 15:03
Hey, Can you please share the network tab in chrome dev tools while visiting the "Submissions" page, and let us know if there is an error in one of the requests, if there is, can you show us the response and status code for the current request?

**Comment by gorzkitomasz** [comment] 2022-11-14 10:29
> Hey, Can you please share the network tab in chrome dev tools while visiting the "Submissions" page, and let us know if there is an error in one of the requests, if there is, can you show us the response and status code for the current request?
> 
> We will remove this `OPTIONS` request in the next release but I want to be sure this is the solution for the current issue.

Hi, everything you ask for can be found in the first thread of this post. :)

**Comment by nicholaszein** [comment] 2022-12-07 09:28
Hello there

We have great news! 🙌 

### 📢 We're happy to announce that this issue was resolved in Elementor Pro **v3.9.0**! 🥳 

✔️ Please feel free to check it out and update your plugin to the new version!

Cheers 🥂

**Closed by nicholaszein** 2022-12-07 09:28 UTC
Labels: bug, component/submissions, 🚀 shipped
