### ISSUE TITLE
Elementor depricated issue

### ISSUE THREAD

**Issue by shrishtisingh12345** [elementor/elementor#14671] opened 2021-04-23 12:04 UTC
yesterday every thing was good but today i dont why i am seeing this error on my page PLAEASE HELP
.
.
.
Deprecated: Elementor\Scheme_Color is deprecated since version 2.8.0! Use Elementor\Core\Schemes\Color instead. in /home4/grandnuy/public_html/wp-includes/functions.php on line 5051

**Comment by d19dotca** [comment] 2021-04-23 23:38
Do you have a third-party plugin that may be using the outdated "Elementor\Scheme_Color"? I suspect that may be the case. Might be worth disabling other plugins outside of Elementor to see if the issue is still present with only the Elementor plugin enabled. If it is, then it's an Elementor issue I guess, and if not then it's likely coming from another plugin that is using an old deprecated feature of Elementor.

**Comment by d19dotca** [comment] 2021-04-23 23:43
Also, this is a duplicate of https://github.com/elementor/elementor/issues/14656#issuecomment-825575126 filed just the other day and appears to be resolved by disabling the third-party plugin which was causing a compatibility issue.

**Comment by shilo-ey** [comment] 2021-04-25 06:25
duplicate of #14656

**Closed by shilo-ey** 2021-04-25 06:25 UTC
