### ISSUE TITLE
navigator change order by dragging doesn't work after update

### ISSUE THREAD

**Issue by anybany** [elementor/elementor#12258] opened 2020-08-26 11:23 UTC
i update to elementor 3.0.1 and elementor pro 3.0.0 and now i can't change the order of my widgets in the navigator anymore.
when i drag one it always gets "pushed" to the last place in order...

**Comment by kskonovalov** [comment] 2020-08-26 12:59
Confirm: faced same issue

**Comment by anybany** [comment] 2020-08-26 13:01
it's possible to correctly drag widgets in the editor itself, but navigator is a must-have for large pages with a lot widgets ;)

**Comment by simonclay** [comment] 2020-08-27 23:25
I have same issue

**Comment by anybany** [comment] 2020-08-28 08:15
seems to be fine now
i'm on elementor 3.0.3
and elementor pro 3.0.1

**Comment by sermalefico** [comment] 2020-09-07 08:44
whit the last update I can, t drag any widgtets from left panel to the design and i can´t drag widgets order in the navigator.

**Comment by nerdtech** [comment] 2020-10-20 12:06
i can confirm this, we can drag in the editor window but the navigator is buggy when you try and drag a widget etc... it just won't go into place, it's take a lot of fiddling to get it where you want it...

**Comment by sermalefico** [comment] 2020-11-19 00:12
30 Aug !!! is imposible reorder the widgets, is frustrating

**Comment by DorShahar** [comment] 2021-01-26 15:02
This issue has been resolved in Elementor v3.1.0
Feel free to update
Thanks!

**Closed by DorShahar** 2021-01-26 15:02 UTC
Labels: status/merged

**Comment by sermalefico** [comment] 2021-01-26 17:31
Not resolved. Sorry.

**Comment by sermalefico** [comment] 2021-01-26 17:43
Please @DorShahar reopen this issue. 
this affects important functionality in the elementor editor. Drag items in the navigator should work correctly and not randomly. It is impossible to reorder widgets currently with this latest update as well.

**Comment by Aviad-Herman** [comment] 2021-01-27 07:37
@sermalefico
For 99% of the people the fix worked. Please help us understand why it doesn't work for you.

1. Deactivate all plugins except elementor and elementor pro and see if the bug persists.
2. What Theme + version are you using?
3. What version of elementor do you use?
4. What version of elementor Pro do you use?
5. Please send us a video of the problem ("loom" is a great tool to share screen recordings)

Thanks

**Comment by sermalefico** [comment] 2021-01-27 12:28
@Aviad-Herman this is the video

[https://www.loom.com/share/d59fc089098c4870919e5c7b34f2af8c](url)

Fresh install latest updates. 
Elementor  Version: 3.1.0
Elementor Pro Version: 3.0.10
Wordpress Version: 5.6
Default wordpress theme: Twenty Nineteen	Version: 1.4
 
This also happens on all old websites.

You can see that for the widget to be positioned correctly in the navigator list, I have to drag it one position higher. If you only have 2 widgets this is not possible. Currently this is skipping one position in the order. for example:

When you have 3 widgets, you cannot drag the first to the second position, you have to drag the first to the third position so that it is ordered in the second position. So if you only have 2 widgets you can never order it in the navigator.

It is skipping positions in the order.

					
== Server Environment ==
	Operating System: WINNT
	Software: Apache/2.4.41 (Win64) OpenSSL/1.1.1d PHP/7.4.2
	MySQL version: MySQL Community Server (GPL) v5.7.24
	PHP Version: 7.4.2
	PHP Max Input Vars: 1000
	PHP Max Post Size: 2G
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.6
	Site URL: http://prueba2.test
	Home URL: http://prueba2.test
	WP Multisite: No
	Max Upload Size: 2 GB
	Memory limit: 512M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: en-US
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: Twenty Nineteen
	Version: 1.4
	Author: the WordPress team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 3.1.0
		Author: Elementor.com

	Elementor Pro
		Version: 3.0.10
		Author: Elementor.com


== Elementor - Compatibility Tag ==
	
	Elementor Pro: header_not_exists

== Elements Usage ==
	


== Log ==

**Comment by Aviad-Herman** [comment] 2021-01-27 14:31
@sermalefico great info thanks!
One last question, what browser are you using?

**Comment by sermalefico** [comment] 2021-01-27 14:35
> @sermalefico great info thanks!
> One last question, what browser are you using?

Versión 88.0.4324.104 (Build oficial) (64 bits)

**Comment by sermalefico** [comment] 2021-01-27 14:54
another video with warnings

[https://www.loom.com/share/724adbbdb5a84ae596896c3a4369f049](url)

**Comment by Aviad-Herman** [comment] 2021-01-27 16:47
@sermalefico 
Thanks for your videos and system info, it helped us pin point the issue.

I turns out the bug is caused by the "Optimized DOM Output" experiment.
Go to Elementor settings --> Experiments and switch the toggle to "Inactive". This will solve the navigator issue for now until we roll out a fix.

Thanks for your help!

![image](https://user-images.githubusercontent.com/73067562/106023802-fe61d380-607b-11eb-8860-2b7429761ebb.png)

**Comment by sermalefico** [comment] 2021-01-27 16:57
> @sermalefico
> Thanks for your videos and system info, it helped us pin point the issue.
> 
> I turns out the bug is caused by the "Optimized DOM Output" experiment.
> Go to Elementor settings --> Experiments and switch the toggle to "Inactive". This will solve the navigator issue for now until we roll out a fix.
> 
> Thanks for your help!
> 
> ![image](https://user-images.githubusercontent.com/73067562/106024400-9bbd0780-607c-11eb-8ba1-1806487f1570.png)

yes! with the option inactive works. with the default option dont.

**Comment by Aviad-Herman** [comment] 2021-01-27 17:10
Sorry for the inconvenience @sermalefico

**Comment by simonclay** [comment] 2021-01-27 17:27
Surely the 'Default' should be 'Inactive' for all the Experimental features?

**Comment by Aviad-Herman** [comment] 2021-01-27 20:09
Yes @simonclay we try to differentiate between alpha, beta and stable experiments. The former are turned off by default. Optemized DOM was running for a few weeks, unfortunately without this bug being discovered. 

You have to admit though it's better than 3.0.0 😉 with experiments you can quickly turn off problematic features until we release a fix - keeping casualties of unpredictable bugs to a minimum.

I would like to thank @sermalefico again for his help. We are working on a fix.
