### ISSUE TITLE
duplicate button in theme builder

### ISSUE THREAD

**Issue by webmasterbart** [elementor/elementor#12378] opened 2020-09-02 07:06 UTC
- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Quick way to make page variations

Add a duplicate button
See screenshot

![duplicate](https://user-images.githubusercontent.com/58780706/91942569-71e4fc00-ecfb-11ea-8342-fe4437be6157.png)

**Comment by arielk** [comment] 2020-09-02 21:00
Duplicate of https://github.com/elementor/elementor/issues/8582

**Closed by arielk** 2020-09-02 21:00 UTC
