### ISSUE TITLE
Contact page

### ISSUE THREAD

**Issue by calvinspires1** [elementor/elementor#17914] opened 2022-02-21 17:22 UTC
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

My last website page show 404 Not Found.

### Describe the solution you'd like

404 Not Found
Looks like you have taken a wrong turn. Dont worry it happens to the best of us.
[RETURN TO HOME PAGERETURN TO HOME PAGE](https://spirescourierllc.com/)
[Transport WordPress Theme](https://www.themescaliber.com/themes/free-logistics-wordpress-theme/) By ThemesCaliber

### Describe alternatives you've considered

404 Not Found
Looks like you have taken a wrong turn. Dont worry it happens to the best of us.
[RETURN TO HOME PAGERETURN TO HOME PAGE](https://spirescourierllc.com/)
[Transport WordPress Theme](https://www.themescaliber.com/themes/free-logistics-wordpress-theme/) By ThemesCaliber

### Additional context

404 Not Found
Looks like you have taken a wrong turn. Dont worry it happens to the best of us.
[RETURN TO HOME PAGERETURN TO HOME PAGE](https://spirescourierllc.com/)
[Transport WordPress Theme](https://www.themescaliber.com/themes/free-logistics-wordpress-theme/) By ThemesCaliber

**Comment by rami-elementor** [comment] 2022-02-21 22:49
Duplicate of #17915

**Closed by rami-elementor** 2022-02-21 22:49 UTC
Labels: request
