### ISSUE TITLE
🔗 ⛔ 🐞 Taxonomy Filter and Loop Grid for Archive page not properly working (Duplicate of #23360)

### ISSUE THREAD

**Issue by BenMi47** [elementor/elementor#23961] opened 2023-10-05 13:17 UTC
### Prerequisites

- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest stable version of Elementor.

### Description

Hello,

We have been testing the new beta features such as Taxonomy filter and Loop Grids and we truly think it is a nice step in the right direction. 
We had great success in speed compared to previous pages but we noticed few bugs when we tried implementing it to the archive template.
We had two methods to create an archive, both resulted in a bug.
### First Method ### 
Activate Archive on the CPT, create an Elementor archive template. 
**Bug:** Taxonomy Filter do not work, the outcome is we see all taxonomies but nothing happens when we click on one to filter.

### Second Method ### 
Deactivate Archive on the CPT, create a page that has the same slug as the CPT, set up the template with the grid and filter.
**Bug:** Pagination do not work, once the page has loaded it would not fetch new items. In our case, "Load More" do not work.

Current solution: We used the Second Method with Pagination set to none and display results set to 100 to make sure all each filtered taxonomy display all results.

Additional Bug to mention: For the second method if we set the slug not the same as the archive, the pagination would work but it will load also other taxonomy items.

I realize the features are still in beta but we are hoping for a quick fix soon

### Method 1 ### 
1) Activate Archive on CPT UI
2) Create Archive template and set display condition to that specific CPT Archive
3) Design the page to include Taxonomy filter + Loop Grid with Pagination

### Method 2 ### 
1) Deactivate Archive on CPT UI 
2) Create overview page with same slug as the CPT
3) Design the page to include Taxonomy filter + Loop Grid with Pagination

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

For security reasons, i am only willing to share the system info with Elementor agents and not have it publicly shown. If needed, please inform me on how to do so.

**Comment by nicholaszein** [comment] 2023-11-13 13:12
Hi, @BenMi47,

Thank you for reaching out! 🙏 

### ⛔ After reviewing your report we concluded this is not a bug caused by Elementor. The feature you're referring to is not yet supported.

### 🔗 🐞 This issue is a Duplicate of #23360

Which is on the same subject. 

For this reason, I'm closing this thread and 🔃 **Merging** it with the original, so we can have all the discussions in one location, and deal with it more efficiently.

Feel free to continue the conversation there. 😉 

### 🔍 Please, in the future, remember to check if there isn't any thread similar to yours already opened. 

Kind regards

**Closed by nicholaszein** 2023-11-13 13:12 UTC
Labels: product/pro, component/theme-builder, mod*, component/theme-builder/archive-template, component/filter/taxonomy

**Comment by nicholaszein** [comment] 2023-11-13 13:14
PS: We appreciate your involvement in our community. For efficient troubleshooting, please remember to include the **<br /><ins>FULL, and essential</ins> [System Info](https://elementor.com/help/hare-my-system-info/)** with each issue reported. We'll need it to help you effectively. 

#### ⚠️ As a gentle reminder, issues without it may need to be closed without troubleshooting. Providing this information upfront aligns with our guidelines, saves time, and ensures swift resolution. Thank you for understanding.
