### ISSUE TITLE
🔗 ⛔ Loop Grid "Equal height" not applying to inner container (Duplicate of #21164)

### ISSUE THREAD

**Issue by walkxcode** [elementor/elementor#25253] opened 2024-02-22 23:02 UTC
### Prerequisites

- [X] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [X] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

When I use a Loop Grid with Loop Grid Item inner container set to "space-between" and enable "Equal Height," the button doesn't move to the bottom as expected. Although the Loop Grid Item container stretches to full height, its inner container does not. Here are screenshots to illustrate the issue:

1. **Equal Height Disabled**
   ![image](https://github.com/elementor/elementor/assets/71191962/6725c7c3-29eb-4e99-959e-5ac027321ae5)

2. **Equal Height Enabled**
   ![image](https://github.com/elementor/elementor/assets/71191962/7d1214c4-569c-481c-82cc-f2b407dd8c31)

As you can see, there's no apparent difference.

Further investigation using Chrome Dev Tools reveals that the equal height property is applied to the Loop Item, but not to the inner Div/Container.

1. **Loop Item with Equal Height Enabled**
   ![image](https://github.com/elementor/elementor/assets/71191962/3e4dc0fe-5484-43dc-8623-18d58a3169a6)

2. **Div with the class `elementor-section-wrap` inside the Loop Item Container**
   ![image](https://github.com/elementor/elementor/assets/71191962/bdfe0715-74a8-45ba-80f6-b41a07116ff4)

Manually adjusting the height of the `elementor-section-wrap` class to `height: 100%` resolves the issue.

**Temporary Solution:**

Add the following custom CSS to the Loop Grid:

```css
selector .elementor-section-wrap {
    height: 100%;
}
```

### Steps to reproduce

1. Add a Loop Grid
2. Set "Equal height" to enabled
3. The inner container is not set to a full height

### Expected behavior

1. Add a Loop Grid
2. Set "Equal height" to enabled
3. The inner container is set to a full height

### Isolating the problem

- [X] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [X] This bug happens with the Hello Elementor theme active.
- [X] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

<details>
<summary>Click to reveal</summary>

````txt
== Server Environment ==
	Operating System: WINNT
	Software: nginx/1.16.0
	MySQL version: MySQL Community Server - GPL v8.0.16
	PHP Version: 8.1.23
	PHP Memory Limit: 256M
	PHP Max Input Vars: 4000
	PHP Max Post Size: 1000M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.4.3
	Site URL: redacted
	Home URL: redacted
	WP Multisite: No
	Max Upload Size: 300 MB
	Memory limit: 40M
	Max Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: Europe/Amsterdam
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor Child
	Version: 2.0.0
	Author: Elementor Team
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 3.0.1
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: nl_NL
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36

== Active Plugins ==
	Admin and Site Enhancements (ASE)
		Version: 6.8.3
		Author: wpase.com

	Advanced Custom Fields
		Version: 6.2.6.1
		Author: WP Engine

	Classic Editor
		Version: 1.6.3
		Author: WordPress Contributors

	Elementor
		Version: 3.19.2
		Author: Elementor.com

	EWWW Image Optimizer
		Version: 7.3.0
		Author: Exactly WWW

	FileBird Lite
		Version: 5.6.1
		Author: Ninja Team

	Post Types Order
		Version: 2.1.8
		Author: Nsp Code

	Site Kit by Google
		Version: 1.120.0
		Author: Google

	Solid Security Basic
		Version: 9.3.1
		Author: SolidWP


== Features ==
	Custom Fonts: 3
	Custom Icons: 0

== Integrations ==
	


== Elementor Experiments ==
	Improved Asset Loading: Active
	Improved CSS Loading: Active
	Inline Font Icons: Active
	Additional Custom Breakpoints: Active
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active
	Upgrade Swiper Library: Active
	Grid Container: Active
	Default to New Theme Builder: Active
	Hello Theme Header &amp; Footer: Active by default
	Editor Top Bar: Active
	Optimized Gutenberg Loading: Active
	Build with AI: Inactive
	Landing Pages: Active
	Nested Elements: Active
	Lazy Load Background Images: Inactive
	Optimize Image Loading: Active
	Pages Panel: Inactive by default
	Global Style Guide: Active
	Page Transitions: Active
	Notes: Active
	Form Submissions: Active
	Scroll Snap: Active
	Menu: Active
	Taxonomy Filter: Active


== Log ==	
== Elementor - Compatibility Tag ==
== Elementor Pro - Compatibility Tag ==

````

</details>

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by toineenzo** [comment] 2024-03-04 03:42
Maybe take a look at this @walkxcode https://youtu.be/PGR5U1_QG4s

**Comment by giannisgx89** [comment] 2024-03-04 11:22
Try to use Flex Grow 1 on the text element and that should resolve the misaligned button issue.

**Comment by walkxcode** [comment] 2024-03-04 11:25
Flex Grow 1 is already applied.

**Comment by mcrowell** [comment] 2024-03-04 13:28
I made a video on how to fix this issue here:
https://www.youtube.com/watch?v=bFvFVIYiLp4

**Comment by nicholaszein** [comment] 2024-03-20 13:22
Hello @walkxcode!

Thank you for your submission! 🙏 

### 🔗 🐞 This issue is a Duplicate of #21164

Which is on the same subject. 

In addition to what @toineenzo and @mcrowell shared, please refer to [this comment](https://github.com/elementor/elementor/issues/21164#issuecomment-1409816171) as well to understand how Equal Height works. Basically it will only work with the parent container of the Loop Item template. If you nest containers it won't work. This is the intended behavior and it works as expected.

### 🔍 Please, in the future, remember to check if there isn't any thread similar to yours already opened. 

Kind regards

**Closed by nicholaszein** 2024-03-20 13:22 UTC
Labels: product/pro, type/layout, widget/loop-builder, mod*, widget/settings, duplicate
