### ISSUE TITLE
shuttle

### ISSUE THREAD

**Issue by FabQuimbaya** [elementor/elementor#14221] opened 2021-03-13 21:29 UTC
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest development version of Elementor.

## Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro) with development versions.
- [ ] This bug happens with a vanilla WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by FabQuimbaya** [comment] 2021-03-13 21:39
Elementor cannot be used when my theme's (Shuttle by ShuttleThemes) editor is active because it freezes. I need each time to deactivate the plugin and reactivate it when I've finished working with Elementor.

In the screenshot, you can see how Elementor shows up with this issue.

No needs to explain the steps to reproduce the problem: I just click "edit with elementor" as usual, and that's it. It gets stuck, showing that weird line you see in this image.

![Screenshot 2021-03-13 at 21 30 24](https://user-images.githubusercontent.com/78088370/111044970-90af1280-8443-11eb-8ae4-62fef5ca9113.png)

**Comment by shilo-ey** [comment] 2021-03-14 10:52
you have a PLUGIN conflict somewhere in your install.

Start by deactivating all other add-ons and plugins other than Elementor Core & Elementor Pro (if installed) - then proceed to edit and see if the issue has been resolved. You may need to switch to the default theme to rule out your theme as the cause of the conflict.

If the issue is resolved by following the above action the proceed to reactivate each plugin 1 at a time and checking the editor till you find the one causing the conflict.

I suggest contacting your Theme author for further information.

Thanks

**Closed by shilo-ey** 2021-03-14 10:52 UTC

**Comment by FabQuimbaya** [comment] 2021-03-15 00:18
Hi thank you for your reply. But you didn’t read carefully what I posted. I already know which plug-in Elementor has the conflict with. It is the one that I told you: It’s the main editor of my theme named shuttle. You can easily find it. 
And it’s elementor that has the problem. Not the other editor, which keeps working fine.
That’s why I asked you to resolve the issue and not Shuttle theme developers. Obviously they don’t care Elementor doesn’t work as it should.
Kind regards.
Fabrizio Perotti
