### ISSUE TITLE
✔️ 🔗 🚀 Feature Request: Update Google Fonts library (Duplicate of #8996, #12172)

### ISSUE THREAD

**Issue by datverse** [elementor/elementor#20229] opened 2022-11-02 11:56 UTC
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Hi, 
When choice Fonts from Font select some Google Font are missing. Can you update Google Fonts library to the latest version?

Example missing Font: League Spartan

[https://fonts.google.com/specimen/League+Spartan](https://fonts.google.com/specimen/League+Spartan)

Thanks

### Steps to reproduce

1 - Choice Font from select font of Widget or Setting.
2. Type "League Spartan"

=> Not Found

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

PHP 8.0.x
WordPress 6.1
Elementor 3.8
Elementor Pro 3.8

**Comment by nicholaszein** [comment] 2022-11-02 17:45
Hello @datverse!

Thank you for your submission! 🙏 

We will look into the possibility to update the Google Fonts library in the next major versions.

🔗 This issue is a Duplicate of #8996, #12172.

Best regards,

Nick

**Comment by datverse** [comment] 2022-11-02 17:48
Thanks

**Comment by nicholaszein** [comment] 2023-02-13 14:26
Hello, there!

We have great news! 🙌 

### 📢 We're happy to announce that this feature was released with Elementor **v3.11**! 🥳 

✔️ Feel free to check it out and update your plugin to the new version!

Cheers 🥂

**Closed by nicholaszein** 2023-02-13 14:26 UTC
Labels: status/merged, request/integration, component/typography, 🚀 shipped
