### ISSUE TITLE
Elementor Pro 3.3.5

### ISSUE THREAD

**Issue by wurschmedia** [elementor/elementor#15874] opened 2021-08-03 08:48 UTC
Product Categories Widget broken since V 3.3.5

Only shows one column for categories.
Multiple columns does not work anymore.

One big column, also category image is blown up to full 1-column width.

**Comment by shilo-ey** [comment] 2021-08-03 08:59
Duplicate of #15857

**Comment by shilo-ey** [comment] 2021-08-03 09:00
I merged this issue with #15857, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!

**Closed by shilo-ey** 2021-08-03 08:59 UTC
