### ISSUE TITLE
Elementor Login Form - refresh current page after login

### ISSUE THREAD

**Issue by shemakeswebthings** [elementor/elementor#11343] opened 2020-05-11 22:33 UTC
## Prerequisites

- [X ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
For membership sites, it is useful to have membership login forms on any page. The problem with the current functionality is that it either redirects to:

- Dashboard for Administrator
- Front page for users
- A specified page

This doesn't work, for example, if you want to place the login form on a single post page, for example, so that users can login to see premium content. The form will redirect away to the home page, taking the user away from the current page. Or if you have an ecommerce site, this can navigate a user away from a product they were viewing - which is very bad for conversions.

The login form should not interfere with the users activity on the site. Refreshing an/or reloading the current page should be an option. An exception would be if users login from the default login page, then it could have a different rule, which can be determined using referring page parameters.

**Describe the solution you'd like**
I'd like a checkbox option or a toggle switch to say, redirect after login to 'current page'. The behavior would be that the login form becomes context sensitive (i.e. understanding which page it is currently being displayed on) so that it can return the user to that particular page after login.

NOTE: This was also mentioned in 2018 (https://github.com/elementor/elementor/issues/5266), was marked as closed but is still not resolved.

**Comment by arielk** [comment] 2020-06-20 19:33
Duplicate of https://github.com/elementor/elementor/issues/10335

**Closed by arielk** 2020-06-20 19:33 UTC

**Comment by DevHog** [comment] 2020-07-14 03:51
This is most definitely NOT a duplicate. 
[#10335](https://github.com/elementor/elementor/issues/10335) is about redirects based on user roles, this issue is about Redirect to referrer page, which is a very standard feature request. Redirecting to the home page rather than whatever page the user was viewing is actually important functionality for good user experience and website flow.

**Comment by arielk** [comment] 2020-07-14 18:21
>  I'd like a checkbox option or a toggle switch to say, redirect after login to 'current page'. The behavior would be that the login form becomes context sensitive (i.e. understanding which page it is currently being displayed on) so that it can return the user to that particular page after login.

The solution you mentioned is behavior that is happening today (stay in the current page after login), so I'm trying to figure out what exactly the problem is?

**Comment by DevHog** [comment] 2020-07-14 20:39
> The solution you mentioned is behavior that is happening today (stay in the current page after login), so I'm trying to figure out what exactly the problem is?
I've run into an issue that even though it's checked to return to the referring page, and inserting a hidden attribute in the form to handle it, it's not actually redirecting after login, just returning to the home page. 
In researching this, I'm coming across recent posts where this is happening to others - but I can't find a solution anywhere except "this has been implemented".

**Comment by arielk** [comment] 2020-07-15 09:17
Hi, 

I've added a dynamic option to this controls so you can select "Post URL" for this request (will be available in v3.0).

Thanks
<img width="315" alt="image" src="https://user-images.githubusercontent.com/1778512/87527504-e2c14d80-c694-11ea-88ce-0f68b3f2696b.png">

**Comment by shilo-ey** [comment] 2020-08-26 16:17
This issue has been resolved in Elementor Pro v3.0.0

Feel free to update

Thanks!
