### ISSUE TITLE
Duplicated Default Kit template after demo import

### ISSUE THREAD

**Issue by DeoThemes** [elementor/elementor#10765] opened 2020-03-06 00:00 UTC
- [ X ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ X ] The issue still exists against the latest stable version of Elementor.

## Description
I've created default kit with theme styles in my first website. After importing demo content to another website using WordPress importer, Elementor creates another default kit and assigns it as the default. As the result there are 2 default kits and the empty one is activated, theme styles are empty - https://clip2net.com/s/46k5rEk

## Steps to reproduce
1. Create default theme styles
2. Export using WordPress export tool
3. Import to another website using WordPress import tool.

## Isolating the problem
- [ X ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ X ] This bug happens with a default WordPress theme active.
- [ X ] I can reproduce this bug consistently using the steps above.

**Comment by shimsa** [comment] 2020-06-02 19:38
I confirm this problem. Please fix it.

**Comment by d19dotca** [comment] 2020-07-15 04:58
I can confirm this too. This is greatly impacting my project of migrating sites to a new default Wordpress "template" app install.

**Comment by BlackJack7878** [comment] 2020-09-17 16:54
Same problem

**Comment by BlackJack7878** [comment] 2020-09-18 16:02
Actually problem is not with elementor but with importing plugins. I was able to fix it (but not the best way I guess).
For "one click demo import" plugin there's hook after_import
```
function ocdi_after_import_setup() {
   update_option( 'elementor_active_kit', 9999 );
}
add_action( 'pt-ocdi/after_import', 'ocdi_after_import_setup' );
```

This way we're activating imported global settings with id equal to 9999 (post_id), at the same time I had to change it from default id to 9999 inside XML export file
`<wp:post_id>9999</wp:post_id>`
You can search it inside XML using "_elementor_page_settings" or "Default Kit" or "default-kit"

**Comment by rshelnutt** [comment] 2020-10-07 00:46
Confirmed as well. Creating a global footer and importing from one of the defaults completely disconnected the original styles. Just lost a ton of work for a client. **Note:** No plugins were imported. 

Will update if I'm able to find a temporary workaround.

**Comment by rshelnutt** [comment] 2020-10-07 02:15
This duplication issue also happens after creating a custom Header or Footer and selecting one of the pre-built options. Causes any previous global style settings to be reset. 

Likely wouldn't be a problem if these were the very first objects created before making any other additions to the global styles, but that isn't always the case.

Lost hours worth of work because of this.

**Comment by tmrwltd** [comment] 2020-10-07 03:33
I have a lot of these Kits - without create any other templates. Maybe happens while updating Elementor.

![grafik](https://user-images.githubusercontent.com/50417351/95284491-867f5b80-0888-11eb-9781-86233ed18679.png)

**Comment by NickChris33** [comment] 2020-10-07 12:32
Just deactivate any caching plugin and delete the templates! I have the wp rocket and when I tried to activate it again the templates are back! So probably is something in the settings of wp rocket!

**Comment by Aliasviejo** [comment] 2020-10-25 19:18
> 
> 
> Just deactivate any caching plugin and delete the templates! I have the wp rocket and when I tried to activate it again the templates are back! So probably is something in the settings of wp rocket!

I did this, deactivated WPRocket, Deleted all the Default Kit Templates (be sure to permanently delete them). And turned WPRocket back on. All the duplicated are gone finally (Like 80).

**Comment by igorchernenko92** [comment] 2020-12-21 09:45
the same issue after simple wordpress import

**Comment by d19dotca** [comment] 2021-01-14 20:29
Interestingly, I no longer saw this issue today when trying this once again. I could not duplicate the issue anymore. Not sure if fixed by WordPress or Elementor, but I suspect WordPress fixed it because there is a note about how Default Kit already exists when I do the import in WordPress' Import UI. 

Would anyone else like to make sure they're on the latest version of WordPress (I'm currently on 5.6), and try to see if the issue is still reproducible? I suspect it's been fixed now from my latest test.

**Comment by andretoldo** [comment] 2021-03-27 22:06
Something just like this just happened to me right now =(
But I don't know exactly what could have caused it.

**Comment by DeoThemes** [comment] 2021-04-21 07:23
For me the solution of @BlackJack7878 works, if Elementor kit has some large number like 1335, simply add update_option( 'elementor_active_kit', 1335 ); in after/import action. If the number of kit is smaller like 547, better to edit content xml and change it to 9999. Hope it helps someone.

**Comment by shilo-ey** [comment] 2021-05-23 05:49
You can use the new experiment added in Elementor v3.2 to Export and Import elementor content.

This will add your settings to your existing site settings, or update the `elementor_active_kit` option as @DeoThemes mentioned.

Thanks.

**Closed by shilo-ey** 2021-05-23 05:49 UTC

**Comment by alahdal262** [comment] 2021-06-22 12:05
I have same trouble, I did everything but not fix
<img width="547" alt="Screenshot 2021-06-22 at 11 16 28" src="https://user-images.githubusercontent.com/50142552/122921538-82359880-d35a-11eb-9f43-8baf5e3501a1.png">
