### ISSUE TITLE
🐞 Bug report: free Elementor SimpleMenu Widget Misbehaviour.

### ISSUE THREAD

**Issue by PowerUser1234** [elementor/elementor#18965] opened 2022-06-20 06:49 UTC
### Prerequisites

- [X] The issue still exists against the latest stable version of Elementor.

### Description

I am running **Windows 10 64 bit Home Edition**.  My defalt web browser is **Firefox 64 bit v 101.0.1**. I have been using the presently installed and updated **free Elementor version 3.6.5** page builder on a main page area for my website, to act as a hub page for the other pages that are part of my web page as a whole.  I have been working from the free initial Theme, 
**Twenty Twenty-One.**

I installed the Windows XAMPP framework from the following file name:

**xampp-windows-x64-7.4.27-2-VC15-installer.exe**

and installed and updated to **WordPress version 6** from the following file:

**wordpress-5.9.2.zip**

I installed and got started using WordPress using the following online tutorial:

[https://www.wpbeginner.com/wp-tutorials/how-to-create-a-local-wordpress-site-using-xampp/](https://www.wpbeginner.com/wp-tutorials/how-to-create-a-local-wordpress-site-using-xampp/)

From there I have added and upgraded WordPress itself and the plugins as asked, from which point I have had no problems.

I have included a screenshot of the problem that is occuring.  When the browser area is smaller, such as on a smart phone, or just plain resized and shrunk on a modern PC's wide screen, things go wrong for the free SimpleMenu.

The problem is not the inclusion of the Hamburger button and the auto conversion to a Vertical menu from a Horizontal one.
The problem is that I can't centre this new menu, by top, left and right outer borders on screen, or compact its width to the widest menu item link name, a text derived width, by default or setting.

Is there a simple, systematic solution I can use, or can this bug be updated in the plugin itself and the update broadcasted to everyone, so that I can click on 'update' and obtain the correction logic, and a correct working SimpleMenu, automatically and by default?

### Steps to reproduce

I have uploaded the image of my problem in the Elementor Facebook Group, which can be seen with another copy of this article, at

[https://www.facebook.com/groups/Elementors/permalink/4861465867312494/](https://www.facebook.com/groups/Elementors/permalink/4861465867312494/)

### System Info

== Server Environment ==
	Operating System: WINNT
	Software: Apache/2.4.52 (Win64) OpenSSL/1.1.1m PHP/7.4.27
	MySQL version: mariadb.org binary distribution v10.4.22
	PHP Version: 7.4.27
	PHP Memory Limit: 512M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 40M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.0
	Site URL: https://localhost:4443/wordpress
	Home URL: https://localhost:4443/wordpress
	WP Multisite: No
	Max Upload Size: 1 GB
	Memory limit: 40M
	Max Memory limit: 512M
	Permalink Structure: /%postname%/
	Language: en-AU
	Timezone: 9.5
	Admin Email: 
	Debug Mode: Inactive

== Theme ==
	Name: Twenty Twenty-One
	Version: 1.6
	Author: the WordPress team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_AU
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:101.0) Gecko/20100101 Firefox/101.0

== Active Plugins ==
	All-in-One WP Migration
		Version: 7.61
		Author: ServMask

	Big File Uploads
		Version: 2.0.2
		Author: Infinite Uploads

	Change Admin Email Setting Without Outbound Email
		Version: 3.1
		Author: John Dee

	Download Plugin
		Version: 2.0.4
		Author: metagauss

	Elementor
		Version: 3.6.6
		Author: Elementor.com

	ElementsKit Lite
		Version: 2.6.1
		Author: Wpmet

	EmbedPress
		Version: 3.4.1
		Author: WPDeveloper

	Essential Addons for Elementor
		Version: 5.1.6
		Author: WPDeveloper

	Exclusive Addons Elementor
		Version: 2.5.5
		Author: DevsCred.com

	FileBird Lite
		Version: 4.9.8
		Author: Ninja Team

	Happy Elementor Addons
		Version: 3.6.1
		Author: weDevs

	Master Addons for Elementor
		Version: 1.9.1
		Author: Jewel Theme

	Ninja Forms
		Version: 3.6.11
		Author: Saturday Drive

	Options for Twenty Twenty-One
		Version: 1.6.6
		Author: Webd Ltd

	Premium Addons for Elementor
		Version: 4.9.17
		Author: Leap13

	Remove "Powered by Wordpress"
		Version: 1.4.6
		Author: Webd Ltd

	Responsive Pagination
		Version: 1.4.1
		Author: Bagus Sasikirono

	Royal Elementor Addons
		Version: 1.3.44
		Author: WP Royal

	Shape Dividers Plus
		Version: 1.2.2
		Author: Marcus Burnette

	Unlimited Elements for Elementor
		Version: 1.5.17
		Author: Unlimited Elements

	Wicked Folders
		Version: 2.18.13
		Author: Wicked Plugins

	WPvivid Backup Plugin
		Version: 0.9.73
		Author: WPvivid Team

== Elementor Experiments ==
	Optimized DOM Output: Inactive
	Improved Asset Loading: Inactive
	Improved CSS Loading: Inactive
	Inline Font Icons: Inactive
	Accessibility Improvements: Inactive
	Import Export Template Kit: Inactive
	Additional Custom Breakpoints: Inactive
	Hide native WordPress widgets from search results: Inactive
	: Inactive by default
	Flexbox Container: Inactive
	Landing Pages: Inactive
	Color Sampler: Inactive
	Favorite Widgets: Inactive
	Admin Top Bar: Inactive

== Log ==
	
PHP: showing 4 of 4PHP: 2022-03-15 18:42:45 [notice X 1554][/Applications/AMPPS/www/beta/wp-content/plugins/elementor/modules/dev-tools/deprecation.php::301] The $finder_category_name argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-03-26 12:16:18 [notice X 6470][C:\xampp\htdocs\wordpress\wp-content\plugins\elementor\modules\dev-tools\deprecation.php::301] The $control_id argument is deprecated since version 3.5.0! [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-03-26 13:18:40 [notice X 6][C:\xampp\htdocs\wordpress\wp-content\plugins\elementor\includes\managers\image.php::87] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-05-25 15:09:35 [notice X 1][C:\xampp\htdocs\wordpress\wp-content\plugins\elementor\core\experiments\experiments-reporter.php::89] Undefined index: title [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

Log: showing 20 of 262022-04-05 16:39:25 [info] elementor::elementor_updater Started 
2022-04-05 16:39:26 [info] Elementor/Upgrades - _on_each_version Start  
2022-04-05 16:39:26 [info] Elementor/Upgrades - _on_each_version Finished 
2022-04-05 16:39:26 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.1',
  'to' => '3.6.2',
)]
2022-04-14 14:58:42 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.2',
  'to' => '3.6.4',
)]
2022-04-14 14:58:43 [info] elementor::elementor_updater Started 
2022-04-14 14:58:43 [info] Elementor/Upgrades - _on_each_version Start  
2022-04-14 14:58:43 [info] Elementor/Upgrades - _on_each_version Finished 
2022-04-14 14:58:43 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.2',
  'to' => '3.6.4',
)]
2022-04-30 14:46:17 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.4',
  'to' => '3.6.5',
)]
2022-04-30 14:46:18 [info] elementor::elementor_updater Started 
2022-04-30 14:46:18 [info] Elementor/Upgrades - _on_each_version Start  
2022-04-30 14:46:18 [info] Elementor/Upgrades - _on_each_version Finished 
2022-04-30 14:46:18 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.4',
  'to' => '3.6.5',
)]
2022-06-10 13:35:27 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.5',
  'to' => '3.6.6',
)]
2022-06-10 13:35:28 [info] elementor::elementor_updater Started 
2022-06-10 13:35:28 [info] Elementor/Upgrades - _on_each_version Start  
2022-06-10 13:35:28 [info] Elementor/Upgrades - _on_each_version Finished 
2022-06-10 13:35:28 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.5',
  'to' => '3.6.6',
)]
2022-06-10 13:35:30 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.5',
  'to' => '3.6.6',
)]

JS: showing 6 of 6JS: 2022-03-26 03:40:17 [error X 3][https://localhost:4443/wordpress/wp-content/plugins/elementor/assets/js/editor-modules.min.js?ver=3.6.1:2:20179] An invalid argument supplied as multiple control value [array (
  'category' => 'InvalidElementData',
  'tag' => 'Element `undefined` got as `ma_el_image_gallery_link_one_url` value. Expected array or object.',
)]
JS: 2022-03-26 03:40:17 [error X 3][https://localhost:4443/wordpress/wp-content/plugins/elementor/assets/js/editor-modules.min.js?ver=3.6.1:2:20179] An invalid argument supplied as multiple control value [array (
  'category' => 'InvalidElementData',
  'tag' => 'Element `undefined` got as `ma_el_image_gallery_link_two_url` value. Expected array or object.',
)]
JS: 2022-03-31 08:30:53 [error X 1][https://localhost:4443/wordpress/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.6.1:2:363181] this.container is undefined 
JS: 2022-04-05 07:08:06 [error X 1][https://localhost:4443/wordpress/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.6.1:2:338291] this.config.document is undefined 
JS: 2022-04-05 08:40:51 [error X 1][https://localhost:4443/wordpress/wp-content/plugins/premium-addons-for-elementor/assets/editor/js/premium-cross-cp.js?ver=4.9.4:13:21] b is null 
JS: 2022-04-07 05:42:15 [error X 6][https://localhost:4443/wordpress/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.6.2:2:0] Permission denied to access property \"elementorFrontend\" on cross-origin object 

== Elementor - Compatibility Tag ==
	
	Essential Addons for Elementor: Compatibility not specified
	Exclusive Addons Elementor: Compatibility not specified
	Happy Elementor Addons: Compatibility not specified
	Master Addons for Elementor: Compatibility not specified
	Premium Addons for Elementor: Compatibility not specified
	Royal Elementor Addons: Compatibility not specified
	Unlimited Elements for Elementor: Compatibility not specified

**Comment by rami-elementor** [comment] 2022-06-28 09:04
Duplicate of #18703

**Closed by rami-elementor** 2022-06-28 09:04 UTC
Labels: bug
