### ISSUE TITLE
⛔ 📚 Elementor code base does not appear to follow recommended coding standard

### ISSUE THREAD

**Issue by mwoodpatrick** [elementor/elementor#10676] opened 2020-02-26 15:50 UTC
When I look at the page: 

https://developers.elementor.com/getting-started/ 

The page recommends using phpcs using the wordpress coding standard but when I run phpcs on the elementor source a few problems are consistently reported:

Class file names should be based on the class name with “class-” prepended. Expected class-control-button.php, but found button.php.

Missing file doc comment

Short array syntax is not allowed

I’m using the current WordPress rules as far as I can see. Do you know where I can I find a phpcs rule set which matches what the elementor team are doing in practice and where that rule set is documented?

**Comment by nicholaszein** [comment] 2024-04-28 04:08
Hello there!

Thank you for your contribution and your patience.

After reviewing your report, and based on the latest version of Elementor, we concluded this is not a bug caused by Elementor. Elementor follows all the WPCS recommendations when applicable, however, it does have its differences in some key aspects. These differences do not affect the compatibility or functionality of WordPress.

We are closing this issue as it is not a bug.

Kind regards

**Closed by nicholaszein** 2024-04-28 04:08 UTC
Labels: compatibility/3rd-party, component/code, mod*
