### ISSUE TITLE
⛔ 🐞 Bug Report: Elementor Menu Cart - Displays Empty When Invoked Within an Elementor Popup

### ISSUE THREAD

**Issue by wpturnedup** [elementor/elementor#22058] opened 2023-04-15 14:03 UTC
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Hi. I've created a full-screen dashboard using an Elementor popup. Within that popup, I've added **Menu Cart** widget.

When the Menu Cart is invoked within the popup, the Side Cart and Mini Cart are blank.

As soon as I pull that same Menu Cart widget out of the popup and place it on a page, the contents of the  Menu Cart work perfectly.

[Screen Recording
](https://share.theonlinebusinessnetwork.com/v/ffr9NfBgQdZRccQWg4CE)

### Steps to reproduce

1. Create a popup
2. Add the Menu Cart widget to the popup
3. Add an item to Cart
4. Test the Menu Cart widget within the popup (it should display as blank)
5. Copy/paste the same Menu Cart widget to a test page (it should display perfectly)

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

<details>
<summary>System Info</summary>

````txt



== Server Environment ==
	Operating System: Linux
	Software: nginx/1.21.3
	MySQL version: mariadb.org binary distribution v10.5.12
	PHP Version: 8.1.3
	PHP Memory Limit: 256M
	PHP Max Input Vars: 10000
	PHP Max Post Size: 128M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.2
	Site URL: https://staging-metropops.kinsta.cloud
	Home URL: https://staging-metropops.kinsta.cloud
	WP Multisite: No
	Max Upload Size: 128 MB
	Memory limit: 40M
	Max Memory limit: 256M
	Permalink Structure: /blog/%postname%/
	Language: en-US
	Timezone: America/New_York
	Admin Email: team@metropops.com
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.7.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 3.12.1
		Author: Elementor.com

	Elementor Pro
		Version: 3.12.2
		Author: Elementor.com

	WooCommerce
		Version: 7.6.0
		Author: Automattic


== Must-Use Plugins ==
	Kinsta Must-use Plugins
		Version: 3.0.0
		Author: Kinsta Team

	Perfmatters MU
		Version: 2.0.9
		Author: forgemedia


== Features ==
	Custom Fonts: 0
	Custom Icons: 0

== Integrations ==
	
	woocommerce: Active


== Elementor Experiments ==
	Optimized DOM Output: Active
	Improved Asset Loading: Active
	Improved CSS Loading: Active
	Inline Font Icons: Inactive
	Accessibility Improvements: Active
	Additional Custom Breakpoints: Inactive
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Inactive by default
	Upgrade Swiper Library: Inactive by default
	Default to New Theme Builder: Inactive
	Hello Theme Header &amp; Footer: Inactive by default
	Editor Top Bar: Inactive by default
	Landing Pages: Inactive
	Nested Elements: Inactive by default
	Lazy Load Background Images: Inactive by default
	Page Transitions: Inactive
	Notes: Inactive
	Loop: Active by default
	Form Submissions: Inactive
	Scroll Snap: Inactive
	Menu: Inactive by default


== Log ==
	
Log: showing 20 of 372023-03-29 10:04:14 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.11.7',
  'to' => '3.12.0',
)]
2023-03-29 10:04:14 [info] elementor::elementor_updater Started 
2023-03-29 10:04:14 [info] Elementor/Upgrades - _on_each_version Start  
2023-03-29 10:04:14 [info] Elementor/Upgrades - _on_each_version Finished 
2023-03-29 10:04:14 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.11.5',
  'to' => '3.12.0',
)]
2023-03-29 10:04:15 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.11.7',
  'to' => '3.12.0',
)]
2023-04-05 15:15:48 [info] elementor::elementor_updater Started 
2023-04-05 15:15:48 [info] Elementor/Upgrades - _on_each_version Start  
2023-04-05 15:15:48 [info] Elementor/Upgrades - _on_each_version Finished 
2023-04-05 15:15:48 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.12.0',
  'to' => '3.12.1',
)]
2023-04-05 15:15:52 [info] elementor-pro::elementor_pro_updater Started 
2023-04-05 15:15:52 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-04-05 15:15:52 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-04-05 15:15:52 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.12.0',
  'to' => '3.12.1',
)]
2023-04-10 11:22:20 [info] elementor-pro::elementor_pro_updater Started 
2023-04-10 11:22:20 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-04-10 11:22:20 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-04-10 11:22:20 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.12.1',
  'to' => '3.12.2',
)]
2023-04-10 11:22:20 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.12.1',
  'to' => '3.12.2',
)]
2023-04-10 11:22:21 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.12.1',
  'to' => '3.12.2',
)]

JS: showing 4 of 4JS: 2023-03-17 14:11:58 [error X 1][https://metropops.com/wp-content/plugins/elementor-pro/assets/js/editor.min.js?ver=3.11.6:2:61411] Object.entries requires that input parameter not be null or undefined 
JS: 2023-03-17 16:11:34 [error X 2][https://metropops.com/wp-content/plugins/elementor/assets/js/frontend.min.js?ver=3.11.5:2:19891] undefined is not an object (evaluating &#039;e.offset().top&#039;) 
JS: 2023-03-27 18:56:14 [error X 69][https://metropops.com/wp-content/plugins/elementor/assets/js/editor-modules.min.js?ver=3.11.5:2:16011] Cannot read properties of undefined (reading &#039;global&#039;) 
JS: 2023-04-05 21:08:56 [error X 2][https://metropops.com/wp-content/plugins/elementor-pro/assets/js/editor.min.js?ver=3.12.1:2:63893] Cannot convert undefined or null to object 

PHP: showing 1 of 1PHP: 2023-04-15 08:38:04 [notice X 197][/www/metropops_165/public/wp-content/plugins/elementor-pro/modules/loop-builder/module.php::204] strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]



== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatibility not specified

== Elementor Pro - Compatibility Tag ==
	


````

</details>

**Comment by abbasdv** [comment] 2023-04-15 19:12
I had a similar issue but when the Mini Cart is used in the header. 
Popup when clicked on the cart icon was empty. Used Latest version of Elementor and Woocommerce.

Fixed it by rolling back Elementor to 3.11.5 and pro 3.11.7.

Elementor -> tools -> version control

**Comment by wpturnedup** [comment] 2023-04-15 22:44
Appreciate the info. However, the issue is specific to invoking via a popup. It works just fine outside of a popup, for the current version.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by doronwolf** [comment] 2023-04-16 14:17
hi @wpturnedup - did you use a custom 'remove icon' in your menu cart? if the answer is 'yes' can you revert to the default icon, save changes, clear the cache, and then check if the problem still happens?
![Screenshot 2023-04-16 at 17 15 08](https://user-images.githubusercontent.com/89334998/232319137-066b5fd5-33e9-44de-bdc9-00913f8541dd.png)

**Comment by wpturnedup** [comment] 2023-04-16 15:22
Hi. No custom icon used. Again, this only happens within a popup.

From: doronwolf ***@***.***>
Date: Sunday, April 16, 2023 at 10:17 AM
To: elementor/elementor ***@***.***>
Cc: Ryan Logan ***@***.***>, Mention ***@***.***>
Subject: Re: [elementor/elementor] Elementor Menu Cart - Displays Empty When Invoked Within an Elementor Popup (Issue #22058)

hi @wpturnedup<https://github.com/wpturnedup> - did you use a custom 'remove icon' in your menu cart? if the answer is 'yes' can you revert to the default icon, save changes, clear the cache, and then check if the problem still happens?
[Image removed by sender. Screenshot 2023-04-16 at 17 15 08]<https://user-images.githubusercontent.com/89334998/232319137-066b5fd5-33e9-44de-bdc9-00913f8541dd.png>

**Comment by doronwolf** [comment] 2023-04-17 07:49
Hi @wpturnedup we are planning on releasing pro v3.12.3 tomorrow with a new fix related to the menu cart - please let us know if it helped, if not we will try to look deeper into your issue

**Comment by wpturnedup** [comment] 2023-04-19 20:42
Hi. Is this patch still coming?

**Comment by doronwolf** [comment] 2023-04-20 07:19
Sorry for the delay 🙏 it takes longer than expected, hopefully, it will be released by the end of Sunday (23 April)

**Comment by wpturnedup** [comment] 2023-04-25 11:47
Hi. Yeah, this didn't solve the issue here. My client websites are also having the same issue. We've all been testing the beta in Staging and can still reproduce it.

**Comment by wpturnedup** [comment] 2023-04-27 13:12
One of my clients gave up on waiting because this impacted sales. We moved all the content from the Popup to a page, and everything works fine now. So, it's definitely an issue with Popups.

What's the word on getting this resolved for Popups?

**Comment by doronwolf** [comment] 2023-05-01 08:34
Hi @wpturnedup I've talked about it with our development team and initially, the menu cart was not built to work inside popups, however, you can file it as a [feature reques](https://github.com/orgs/elementor/discussions/new?category=feature-request)t and if users upvote it, it will get promoted 👍

**Comment by Frantooo** [comment] 2023-05-16 11:25
Hi, we have a same issue. We use the menu cart in the header of the site. Elementor pro version 3.13.1

**Comment by doronwolf** [comment] 2023-05-16 11:56
Hi @Frantooo please update to Elementor Pro 3.12.3 (or above) that contains the fix
please also refer to this comment 
https://github.com/elementor/elementor/issues/21836#issuecomment-1520791070

**Comment by Frantooo** [comment] 2023-05-16 14:22
Hi @doronwolf we have downgraded to 3.12.3 ver. but the issue was not solved!
[image](https://github.com/elementor/elementor/assets/85238496/6507a16e-4666-4930-a58c-4727b2397a3a)
![image](https://github.com/elementor/elementor/assets/85238496/2db29d57-8a9b-454f-9980-a627add437c6)

**Comment by Frantooo** [comment] 2023-05-16 14:34
We see that only on a cart page of woocommerce.
![image](https://github.com/elementor/elementor/assets/85238496/9d050a01-d1d0-4c96-9f95-26a1158dcfe1)

**Comment by doronwolf** [comment] 2023-05-16 14:43
earlier you wrote you used 3.12.1
so if I understand correctly you upgraded, not downgraded (?) 
also, did you read the instructions in the comment here https://github.com/elementor/elementor/issues/21836#issuecomment-1520791070
meaning: you need to clear the cache, and regenerate CSS & Data
and also Remember that if you are not using the Elementor Menu Cart widget, and you want to use the Mini Cart from your theme, you need to deactivate the WooCommerce Mini Cart Template in Elementor Settings.
Please read the last section at the end of this article: https://elementor.com/help/menu-cart-widget-pro/

if you are still experiencing a bug after all those steps please open a NEW bug with all the details (including steps to reproduce, system info, etc) and we will try to assist you

**Comment by doronwolf** [comment] 2023-05-23 12:35
are we talking about the menu cart inside a popup? maybe you missed my earlier answer https://github.com/elementor/elementor/issues/22058#issuecomment-1529484487

**Comment by doronwolf** [comment] 2023-05-23 13:18
@nicholaszein

**Comment by nicholaszein** [comment] 2023-05-24 15:45
Hello everyone,

Thank you for your feedback, and apologies for the delay!

### ⛔ After reviewing your report we concluded this is not a bug caused by Elementor. The feature you're referring to is not yet supported.

Popups are loaded dynamically (via Ajax). The Menu Cart widget utilizes the default WooCommerce Mini Cart, which requires cart fragments to be loaded. Since Popups load dynamically, they can't communicate with the cart fragments. Placing Menu Carts inside Popups is not supported yet because of this. I hope you can understand.

If you think this should be an Elementor feature, please submit a new [🚀 Feature Request](https://github.com/orgs/elementor/discussions/new?category=feature-request), and we will consider it in the future if there is enough demand (votes) from other users.

Kind regards

**Closed by nicholaszein** 2023-05-24 15:45 UTC
Labels: bug, compatibility/3rd_party, product/pro, component/woocommerce, component/menu-cart
