### ISSUE TITLE
🔗 🚀 Feature Request: Dynamic Tag: Lightbox - Add an option to include a Gallery (Duplicate of #8054)

### ISSUE THREAD

**Issue by ofmarconi** [elementor/elementor#20384] opened 2022-11-13 13:40 UTC
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

Need to display a sequence of photos as a gallery from a button.

### Describe the solution you'd like

Add gallery option here:
![image](https://user-images.githubusercontent.com/6594795/201524680-991116f4-f4bf-40bd-9d87-28d05e2654f7.png)

### Describe alternatives you've considered

It would create a popup requiring another click to open the gallery.

**Comment by nicholaszein** [comment] 2022-11-14 09:29
Hello @ofmarconi!

Thank you for your submission! 🙏 

### 🔗 This issue is a Duplicate of #8054.

Which is on the same subject. 

For this reason, I'm closing this issue and 🔃 **Merging** it with the original, so we can have all the discussions in one location, and deal with it more efficiently.

Feel free to continue the conversation there. 😉 

### ✔️ Please, in the future, remember to check if there isn't an issue similar to yours already opened. 

Best regards,

Nick

**Closed** 2022-11-14 09:30 UTC
Labels: request/enhancement, component/lightbox, component/dynamic-tag, component/gallery
