### ISSUE TITLE
🔗 🐞 Global Colors defined using Dynamic Data don't Reflect on the Frontend (Duplicate of #20368)

### ISSUE THREAD

**Issue by Daveden2** [elementor/elementor#25387] opened 2024-03-07 00:57 UTC
### Prerequisites

- [X] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [X] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

I have created an options page with color picker fields to define global colors. Clients should be able to edit these global colors from the backend.

![image](https://github.com/elementor/elementor/assets/105490669/8f7cddc9-dd3e-4c49-ac6f-c603634fdadb)

The global colors appear as expected in the editor.

![image](https://github.com/elementor/elementor/assets/105490669/198706d8-e953-4a3d-be26-ce3b9fd4214f)

However, the changes do not reflect on the frontend of the website.

![image](https://github.com/elementor/elementor/assets/105490669/d87131aa-3446-4018-8d1f-d347f1a6ea8c)

If I add the same colors directly to a widget (as standalone colors), they display correctly on the frontend.

![image](https://github.com/elementor/elementor/assets/105490669/9d843c69-1491-455c-83a0-008e71a7094b)

![image](https://github.com/elementor/elementor/assets/105490669/49e6bbc2-5b75-49a4-b2d5-6dd31674b21a)

### Steps to reproduce

1. Create a colour picker field in an options page using a custom fields plugin like ACF or JetEngine
2. Apply the colour picker field to a new global color in the Site Settings
3. Apply the global color to a heading widget
4. Test in the editor
5. Test on the frontend.
6. Add the same dynamic field from the options page directly to a widget
7. Test on both the front and backend.

### Expected behavior

The color should reflect both on the front and backend.

### Isolating the problem

- [ ] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [X] This bug happens with the Hello Elementor theme active.
- [X] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

<details>
<summary>Click to reveal</summary>

````txt

== Server Environment ==
	Operating System: Linux
	Software: LiteSpeed
	MySQL version: MariaDB Server v10.11.7-MariaDB-cll-lve
	PHP Version: 8.1.27
	PHP Memory Limit: 2048M
	PHP Max Input Vars: 5000
	PHP Max Post Size: 2048M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.4.3
	Site URL: https://staging24.daveden.co.uk
	Home URL: https://staging24.daveden.co.uk
	WP Multisite: No
	Max Upload Size: 2 GB
	Memory limit: 40M
	Max Memory limit: 2048M
	Permalink Structure: /%postname%/
	Language: en_US
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor Child
	Version: 2.0.0
	Author: Elementor Team
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 3.0.1
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: en-US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36

== Active Plugins ==
	Admin and Site Enhancements (ASE) Pro
		Version: 6.9.0.1
		Author: wpase.com

	Advanced Custom Fields
		Version: 6.2.7
		Author: WP Engine

	Core Framework
		Version: 1.3.9
		Author: Core Framework

	Crocoblock Wizard
		Version: 1.2.8
		Author: Crocoblock

	Dynamic.ooo - Dynamic Shortcodes
		Version: 1.1.7
		Author: Dynamic.ooo

	Elementor
		Version: 3.20.0-beta4
		Author: Elementor.com

	Elementor Pro
		Version: 3.20.0-beta4
		Author: Elementor.com

	FakerPress
		Version: 0.6.1
		Author: Gustavo Bordoni

	HappyFiles Pro
		Version: 1.8.3
		Author: Codeer

	Hostinger
		Version: 2.1.0
		Author: Hostinger

	Hostinger AI Assistant
		Version: 1.7.0
		Author: Hostinger

	JetEngine
		Version: 3.4.0
		Author: Crocoblock

	JetFormBuilder
		Version: 3.3.2
		Author: Crocoblock

	LiteSpeed Cache
		Version: 6.1
		Author: LiteSpeed Technologies

	Max Mega Menu
		Version: 3.3.1
		Author: megamenu.com

	WPCodeBox 2
		Version: 1.0.3
		Author: WPCodeBox


== Elements Usage ==
	
	footer : 1
		container : 5
		heading : 2
		icon-list : 1
		image : 1
		social-icons : 1
		text-editor : 3
	header : 4
		button : 2
		container : 20
		heading : 1
		html : 9
		icon : 1
		icon-list : 5
		image : 4
		image-box : 1
		mega-menu : 2
		search-form : 2
		text-editor : 1
		wp-widget-maxmegamenu : 2
	page : 1
		button : 1
		container : 10
		heading : 3
		html : 1
		image : 3
		text-editor : 3
	section : 1
		container : 1
		html : 1
	wp-post : 0
		accordion : 1
		blockquote : 3
		button : 27
		call-to-action : 10
		container : 155
		form : 1
		heading : 32
		html : 7
		icon-box : 9
		icon-list : 2
		image : 46
		image-box : 48
		image-carousel : 3
		image-gallery : 1
		loop-grid : 3
		mega-menu : 1
		nav-menu : 1
		nested-carousel : 1
		price-table : 3
		rating : 4
		social-icons : 1
		spacer : 2
		text-editor : 14
		wp-widget-maxmegamenu : 1
	wp-page : 2
		container : 1
		html : 2
	single-post : 2
		container : 7
		form : 1
		heading : 3
		html : 1
		icon-list : 1
		post-info : 1
		post-navigation : 1
		theme-post-content : 1
		theme-post-excerpt : 1
		theme-post-featured-image : 1
		theme-post-title : 1
	loop-item : 4
		container : 3
		heading : 3
		html : 1
		theme-post-excerpt : 2
		theme-post-featured-image : 1
		theme-post-title : 2


== Settings ==
	
	cpt_support: post, page, lab-pages, demo, tut-demo
	disable_color_schemes: yes
	disable_typography_schemes: yes
	allow_tracking: yes
	unfiltered_files_upload: 1
	font_display: swap


== Features ==
	Custom Fonts: 7
	Custom Icons: 0

== Integrations ==
	


== Elementor Experiments ==
	Improved Asset Loading: Active by default
	Improved CSS Loading: Inactive
	Inline Font Icons: Active by default
	Additional Custom Breakpoints: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active by default
	Upgrade Swiper Library: Active by default
	Grid Container: Active
	Default to New Theme Builder: Active by default
	Hello Theme Header & Footer: Active by default
	Editor Top Bar: Active
	Optimized Gutenberg Loading: Active by default
	Build with AI: Active by default
	Landing Pages: Active by default
	Nested Elements: Active
	Lazy Load Background Images: Inactive by default
	Optimize Image Loading: Active by default
	Pages Panel: Inactive by default
	Notes: Active by default
	Display Conditions: Active
	Form Submissions: Active by default
	Menu: Active
	Taxonomy Filter: Active


== Log ==
	
Log: showing 20 of 282024-02-26 18:25:41 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.20.0-beta1',
  'to' => '3.20.0-beta2',
)]
2024-02-29 21:25:09 [info] elementor-pro::elementor_pro_updater Started 
2024-02-29 21:25:09 [info] Elementor Pro/Upgrades - _on_each_version Start  
2024-02-29 21:25:09 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2024-02-29 21:25:09 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.20.0-beta2',
  'to' => '3.20.0-beta3',
)]
2024-03-04 19:09:28 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.20.0-beta1',
  'to' => '3.20.0-beta3',
)]
2024-03-04 19:09:28 [info] elementor::elementor_updater Started 
2024-03-04 19:09:28 [info] Elementor/Upgrades - _on_each_version Start  
2024-03-04 19:09:29 [info] Elementor/Upgrades - _on_each_version Finished 
2024-03-04 19:09:29 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.20.0-beta1',
  'to' => '3.20.0-beta3',
)]
2024-03-06 23:52:05 [info] elementor-pro::elementor_pro_updater Started 
2024-03-06 23:52:05 [info] Elementor Pro/Upgrades - _on_each_version Start  
2024-03-06 23:52:05 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2024-03-06 23:52:05 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.20.0-beta3',
  'to' => '3.20.0-beta4',
)]
2024-03-06 23:52:05 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.20.0-beta3',
  'to' => '3.20.0-beta4',
)]
2024-03-06 23:55:41 [info] elementor::elementor_updater Started 
2024-03-06 23:55:41 [info] Elementor/Upgrades - _on_each_version Start  
2024-03-06 23:55:41 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.20.0-beta3',
  'to' => '3.20.0-beta4',
)]
2024-03-06 23:55:41 [info] Elementor/Upgrades - _on_each_version Finished 
2024-03-06 23:55:41 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.20.0-beta3',
  'to' => '3.20.0-beta4',
)]

JS: showing 8 of 8JS: 2024-02-20 16:03:18 [error X 2][../wp-content/plugins/elementor/assets/js/4fdaa70e951ad90db2f2.bundle.min.js:2:7786] Cannot read properties of null (reading 'dataset') 
JS: 2024-02-20 16:42:18 [error X 10][../wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.20.0-beta1:3:815577] Cannot read properties of undefined (reading 'localized') 
JS: 2024-02-20 17:34:05 [error X 1][../wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.20.0-beta1:3:702990] Cannot read properties of undefined (reading 'get') 
JS: 2024-02-20 17:58:31 [error X 1][../wp-admin/load-scripts.php?c=1&loadchunk_0=jquery-core,jquery-migrate,utils,wp-polyfill-inert,regenerator-runtime,wp-polyfill,wp-hooks&ver=6.4.3:2:28760] Cannot read properties of undefined (reading 'value') 
JS: 2024-02-24 08:47:42 [error X 2][../wp-includes/js/mediaelement/mediaelement-and-player.min.js?ver=4.2.17:12:0]  
JS: 2024-02-24 09:30:22 [error X 1][../wp-content/plugins/elementor/assets/js/admin.min.js?ver=3.20.0-beta1:3:47978] c[0] is undefined 
JS: 2024-03-01 14:44:07 [error X 2][../wp-content/plugins/elementor/assets/js/frontend-modules.min.js?ver=3.20.0-beta1:2:35050] e is null 
JS: 2024-03-07 00:28:57 [error X 4][../wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.20.0-beta4:3:134966] C.getNamespaceArray is not a function 

PHP: showing 6 of 6PHP: 2024-02-20 16:33:09 [notice X 41][../wp-content/plugins/elementor/includes/base/controls-stack.php::228] hexdec(): Passing null to parameter #1 ($hex_string) of type string is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-03-02 17:08:55 [warning X 10][../wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php::150] Undefined array key "condition_type" [array (
  'trace' => '
#0: ../wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(150): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_template_json_item()
#2: ../wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(120): class type array_map()
#3: ../wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(59): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_templates_json()
#4: ../wp-content/plugins/elementor/data/base/endpoint.php(158): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> get_items()
',
)]
PHP: 2024-03-04 22:23:10 [warning X 8][../wp-content/plugins/elementor/modules/history/revisions-manager.php::363] Undefined array key "editor_post_id" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-03-04 22:32:58 [warning X 26][../wp-content/plugins/elementor/core/files/css/base.php::778] Undefined array key "background_overlay_color" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-03-04 22:35:45 [warning X 2][../wp-content/plugins/elementor/core/files/css/base.php::778] Undefined array key "background_overlay_color_b" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-03-04 22:37:00 [warning X 2][../wp-content/plugins/elementor-pro/modules/dynamic-tags/acf/tags/acf-color.php::34] Undefined array key 1 [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]



== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatible

== Elementor Pro - Compatibility Tag ==

````

</details>

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by nicholaszein** [comment] 2024-03-20 15:40
Hi @Daveden2!

Thank you for your submission! 🙏 

### 🔗 🐞 This issue is a Duplicate of #20368 

Which is on the same subject. 

We are aware of this problem, however, we don't have an ETA to when it will be solved.

For this reason, I'm closing this thread and 🔃 **Merging** it with the original, so we can have all the discussions in one location, and deal with it more efficiently.

Feel free to continue the conversation there. 😉 

Kind regards

**Closed by nicholaszein** 2024-03-20 15:40 UTC
Labels: bug, product/pro, component/dynamic-tag, type/global-styles, mod*, site-settings/global-colors, duplicate
