### ISSUE TITLE
Error while updating Elementor from Wordpress

### ISSUE THREAD

**Issue by sss9212** [elementor/elementor#11642] opened 2020-06-16 06:15 UTC
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description
I encouter the following error when updating to a new version of Elementor Pro:
**Download failed. cURL error 56: Recv failure: Connection reset by peer**

I tried deactivating all other plugins to see if they are causing a conflict but the issue still persists

## Steps to reproduce

Wordpress Dashboard > Updates > Update Elementor Pro.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Percona Server (GPL), Release 84.1, Revision b308619 v5.6.41-84.1
	PHP Version: 7.3.18
	PHP Max Input Vars: 1000
	PHP Max Post Size: 260M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.4.2
	Site URL: https://www.ssquaredit.com
	Home URL: https://www.ssquaredit.com
	WP Multisite: No
	Max Upload Size: 256 MB
	Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 5.5
	Debug Mode: Inactive

== Theme ==
	Name: Neve
	Version: 2.7.2
	Author: ThemeIsle
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.97 Safari/537.36

== Active Plugins ==
	Akismet Anti-Spam
		Version: 4.1.6
		Author: Automattic

	Code Snippets
		Version: 2.14.0
		Author: Code Snippets Pro

	Elementor
		Version: 2.9.12
		Author: Elementor.com

	Elementor Pro
		Version: 2.9.4
		Author: Elementor.com

	Really Simple SSL
		Version: 3.3.3
		Author: Rogier Lankhorst, Mark Wolters

	Sucuri Security - Auditing, Malware Scanner and Hardening
		Version: 1.8.24
		Author: Sucuri Inc.

	UpdraftPlus - Backup/Restore
		Version: 1.16.25
		Author: UpdraftPlus.Com, DavidAnderson

	WP AutoTerms
		Version: 2.4.1
		Author: WP AutoTerms

	WP Maintenance Mode
		Version: 2.2.4
		Author: Designmodo

	Yoast SEO
		Version: 14.3
		Author: Team Yoast

== Elements Usage ==
	
	footer : 1
		heading : 1
		nav-menu : 2
		text-editor : 3
	header : 2
		button : 1
		icon-list : 4
		image : 2
		nav-menu : 2
		search-form : 1
	wp-page : 13
		animated-headline : 1
		button : 7
		counter : 3
		form : 4
		heading : 2
		icon-box : 4
		image : -9
		price-list : 1
		price-table : 7
		star-rating : 2
		testimonial : 1
		text-editor : 2
		toggle : 1

== Log ==
	
Log: showing 14 of 142020-01-20 05:31:03 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.8.3',
  'to' => '2.8.4',
)]
2020-01-28 05:30:54 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.8.4',
  'to' => '2.8.5',
)]
2020-02-17 05:33:20 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.8.5',
  'to' => '2.9.2',
)]
2020-02-27 05:35:17 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.9.2',
  'to' => '2.9.3',
)]
2020-03-05 05:31:05 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.9.3',
  'to' => '2.9.4',
)]
2020-03-10 05:34:35 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.9.4',
  'to' => '2.9.5',
)]
2020-03-12 14:15:12 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.9.5',
  'to' => '2.9.6',
)]
2020-03-26 05:40:44 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.9.6',
  'to' => '2.9.7',
)]
2020-04-22 05:31:37 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.9.7',
  'to' => '2.9.8',
)]
2020-05-15 11:36:58 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.8.5',
  'to' => '2.9.4',
)]
2020-05-25 05:30:54 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.9.8',
  'to' => '2.9.9',
)]
2020-06-02 05:31:40 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.9.9',
  'to' => '2.9.10',
)]
2020-06-03 05:32:10 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.9.10',
  'to' => '2.9.11',
)]
2020-06-15 00:21:01 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.9.11',
  'to' => '2.9.12',
)]

JS: showing 7 of 7JS: 2020-02-14 13:23:08 [error X 6][https://www.ssquaredit.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.8.5:31:118229] Cannot read property \'toolbar1\' of undefined 
JS: 2020-02-14 13:23:08 [error X 6][https://www.ssquaredit.com/wp-admin/js/editor.min.js?ver=5.3.2:1:725] Cannot read property \'style\' of undefined 
JS: 2020-03-20 14:32:15 [error X 2][https://www.ssquaredit.com/wp-content/plugins/elementor/assets/js/common.min.js?ver=2.9.6:2:98603] Commands internal: `document/history/delete-transaction` not found. 
JS: 2020-05-08 17:47:42 [error X 7][https://www.ssquaredit.com/wp-content/plugins/elementor-pro/assets/js/editor.min.js?ver=2.8.5:2:54332] Cannot read property \'top\' of undefined 
JS: 2020-05-27 10:22:27 [error X 100][https://www.ssquaredit.com/wp-content/plugins/elementor/assets/js/editor-document.min.js?ver=2.9.9:2:8328] container or containers are required. 
JS: 2020-06-10 14:31:32 [error X 1][https://www.ssquaredit.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view8213\") has already been destroyed and cannot be used. 
JS: 2020-06-10 14:31:32 [error X 1][https://www.ssquaredit.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view9066\") has already been destroyed and cannot be used. 

PHP: showing 3 of 3PHP: 2020-05-30 12:59:35 [error X 2][/home1/ssquacgb/public_html/wp-content/plugins/elementor-pro/license/updater.php::150] Cannot use object of type WP_Error as array [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-06-07 18:30:42 [notice X 1][/home1/ssquacgb/public_html/wp-content/plugins/elementor-pro/modules/forms/classes/ajax-handler.php::218] Undefined index: post_id [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-06-12 11:32:13 [error X 1][/home1/ssquacgb/public_html/wp-content/plugins/elementor-pro/license/updater.php::150] Uncaught Error: Cannot use object of type WP_Error as array in /home1/ssquacgb/public_html/wp-content/plugins/elementor-pro/license/updater.php:150
Stack trace:
#0 /home1/ssquacgb/public_html/wp-includes/class-wp-hook.php(287): ElementorPro\License\Updater->plugins_api_filter(false, 'plugin_informat...', Object(stdClass))
#1 /home1/ssquacgb/public_html/wp-includes/plugin.php(206): WP_Hook->apply_filters(false, Array)
#2 /home1/ssquacgb/public_html/wp-admin/includes/plugin-install.php(150): apply_filters('plugins_api', false, 'plugin_informat...', Object(stdClass))
#3 /home1/ssquacgb/public_html/wp-admin/includes/plugin-install.php(525): plugins_api('plugin_informat...', Object(stdClass))
#4 /home1/ssquacgb/public_html/wp-includes/class-wp-hook.php(287): install_plugin_information('')
#5 /home1/ssquacgb/public_html/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters('', Array)
#6 /home1/ssquacgb/public_html/wp-includes/plugin.php(478): WP_Hook->do_action(Array)
#7 /home1/ssquacgb/public_html/wp-admin/pl [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)] -->
</details>

**Comment by lior-sh** [comment] 2020-06-16 08:09
Hi @sss9212,

Thanks for reporting, we couldn't reproduce the issue.
Please remove the plugin and download it again. Update us if you still got the same error message.
Thanks.

**Comment by sss9212** [comment] 2020-06-16 08:15
Thanks for the reply. Will removing the plugin break the website I have made using Elementor?

**Comment by bainternet** [comment] 2020-06-16 08:33
@sss9212 

Removing the plugin will remove its functionality.

If you are having issues upgrading Please contact our support at support @elementor.com for guidance in resolving this issue and mention that you were directed by me and reference this issue.

thanks.

**Closed by bainternet** 2020-06-16 08:33 UTC

**Comment by sss9212** [comment] 2020-09-18 05:56
Hello, this issue still persists when updating Elementor Pro. The hosting provider says it's a plugin issue and not server-side issue. I tried doing a fresh install through CPanel but the error comes back when trying to update. The problem doesn't occur with the Elementor Core version, only with Pro.
