### ISSUE TITLE
🐞 Bug report: Display Rules/Repeater in advanced tab with Global Color conditions

### ISSUE THREAD

**Issue by posimyth** [elementor/elementor#19673] opened 2022-09-01 08:16 UTC
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

Hello Team Elementor,

We are Developers behind The Plus Addons for Elementor.

We have observed one bug which is happening with our plugin and other popular 3rd party addons for elementor. All those who have repeater added in Advanced Tab, They are having this issue.

Check : https://posimyth.vmaker.com/record/i8YmdecEO7pbEg13 In the editor default color is coming even we have set dynamic color in backend. In front end it works fine. In backend error is related to js.

### Describe the solution you'd like

Check elementor/assets/js/editor-modules.min.js In this file we have updated below code and it's working fine.
Old : null===(o=r[a].global)
NEW : null===(o=r[a]?r[a].global:null)

https://share.cleanshot.com/uRokVA

### Additional context

We had submitted support ticket and support team have asked to raise this on Github.

**Comment by arielk** [comment] 2022-09-02 07:55
Hi @posimyth Thanks for your report!

I will forward it to the developers for testing, in the meantime you can send a PR with the fix, that way we can test it faster :)

**Comment by AnkushT-12** [comment] 2022-09-15 13:20
Hi @arielk 

Any update on this issue?

**Comment by anandau** [comment] 2022-09-19 10:48
Hi @arielk 

This issue is affecting multiple Third Party addons. Can you please take this on priority?

**Comment by TrojanProxy** [comment] 2022-09-20 07:02
I rely heavily on this feature for multiple websites so it would be great to see a fix for this as soon as humanly possible. I am happy to help test on my side.

**Comment by TroxNox09** [comment] 2022-09-23 18:12
Any update to this? This error has been preventing many elements from showing and working on our website. Elementor and third party application have been notified and know of the issue.

**Comment by swapnilde** [comment] 2022-09-27 05:17
Hello @arielk 
Any update on resolving this issue?

**Comment by chipweb** [comment] 2022-09-27 10:13
I have this same problem on 4 websites and no one is providing a solution. Please, fix the problem.

**Comment by rami-elementor** [comment] 2022-09-29 11:00
Hi,

We know that bugs like this one can be frustrating, but we are currently focusing on releasing Elementor 3.8.

From what we understand, this issue does not break sites, and does not affect the front-end.

Please be patient we will prioritize this issue soon.

**Comment by udidol** [comment] 2022-09-29 12:15
Hi @posimyth,
Do you have a website that you can share where this issue happens?
If you can set `WP_DEBUG` to `true` for that website share credentials, that will help us debug the issue and fix it properly. 

You can open a ticket in Elementor support and tell them that you are asking to pass the site credentials to Udi, they will pass it to me.

**Comment by posimyth** [comment] 2022-09-30 11:00
@udidol Sure. We have submitted ticket on Elementor Pro's Helpdesk.

**Comment by udidol** [comment] 2022-09-30 13:48
I've received it. I will look at it next week.

**Comment by TheSashX** [comment] 2022-09-30 18:10
I want to vote this bug up. We have many sites that are "broken" because we can not use the features, we used before. Our customers are not amused.

**Comment by chipweb** [comment] 2022-10-03 08:28
Please fix it. We are despairing

**Comment by danvy** [comment] 2022-10-07 09:51
I also affected by this bug.
Our checkout is broken.
This is critical.

**Comment by udidol** [comment] 2022-10-11 06:23
Thanks to @posimyth we have found the cause of the problem.
A fix should be released in the next version of Elementor Core.

**Comment by udidol** [comment] 2022-10-11 07:17
@posimyth 
Something didn't look right to me about this issue so I did some more digging.
The problem seems to stem from something you are doing wrong.

In your `plus-widget-conditions.php` file, when you add the `tp_display_rules` repeater, this repeater's `'fields'` array is passed like this:
```
'fields' 		=> array_values($repeater->get_controls()),
```

Why do you pass the controls through `array_values()`? That is not how repeaters work, and that is the source of your problems.

**Closed by udidol** 2022-10-11 07:17 UTC
Labels: bug, compatibility/3rd_party, component/site-settings

**Comment by posimyth** [comment] 2022-10-11 09:35
Hello @udidol 

We have added that array values there because, If we don't add it and if someone will use "copy style - Paste Style" feature in any widget, It will throw error and not let users to save page. 

Check : https://posimyth.vmaker.com/record/xrAyEqe8kaScgxIw 

We have seen similar issue in other plugins as well when they use repeater in "Advanced" tab of elementor editor.

**Comment by udidol** [comment] 2022-10-11 09:41
@posimyth That is a different problem, but the solution is bad. Our systems expect an associative array of repeater fields with the control names as the keys.

Did you open a ticket about the Copy-Paste Style problem?
Did you check if it happened to be fixed in any recent version? Because I believe some fixes were applied for Copy-Past Style some time in the last few weeks/months.

**Comment by DYevseyev** [comment] 2022-11-11 04:55
I had a problem using presets with ultimate addon for elementor. 
Support said that Elementor is working on a fix.
Is it true? Are we still waiting for a fix?

**Comment by hillepeter** [comment] 2022-12-04 12:32
@posimyth Any new regarding this bug? The workaround described in the first post did not work for me. The error still apears...

**Comment by posimyth** [comment] 2022-12-07 12:02
@udidol We have tested in 3.9.0 and the issue is still there. Do we need to open this ticket again as we need your help to resolve that as well?

**Comment by posimyth** [comment] 2022-12-07 12:04
@udidol 

We found only solution of this is : 
Check elementor/assets/js/editor-modules.min.js In this file we have updated below code and it's working fine.
Old : null===(o=r[a].global)
NEW : null===(o=r[a]?r[a].global:null)

https://share.cleanshot.com/uRokVA

You have mentioned going with your way, But That is not possible to manage from our end. Even you may check this with other addons, They will also keep having this same issue.
