### ISSUE TITLE
🔗 🚀 Feature Request: Nested Repeater Needed (Duplicate of #2955)

### ISSUE THREAD

**Issue by thecodude** [elementor/elementor#12092] opened 2020-08-11 04:33 UTC
I need to nested repeater feature for developing a custom widgets. You know many page builder have this feature. If anyone find this solution for this please help!

**Comment by DorShahar** [comment] 2020-11-30 08:05
Merged issue

I merged this issue with  #4440, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.
Thanks for your feedback!

**Closed by DorShahar** 2020-11-30 08:05 UTC
Labels: request/enhancement, type/developer-api, mod*

**Comment by nicholaszein** [comment] 2022-12-06 15:54
Hello @thecodude!

Thank you for your submission! 🙏 

I'm currently consolidating similar requests, and I came across your issue.

### 🔗 This issue is a Duplicate of #2955.

Which is on the same subject. 

For this reason, I'm closing this issue and 🔃 **Merging** it with the original, so we can have all the discussions in one location, and deal with it more efficiently.

Feel free to continue the conversation there. 😉 

Best regards,

Nick
