### ISSUE TITLE
✔️ 🐞 Bug report: Gallery widget broken after updating Elementor from 3.8.2 to 3.9.0 (ED-9020)

### ISSUE THREAD

**Issue by puregraphx** [elementor/elementor#20669] opened 2022-12-08 19:28 UTC
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

After updating to 3.9.0 the Gallery Widget is still visible in the DOM, but every div.e-gallery-image is 33554400x0 pixels.
--item-width and --item-height on a.e-gallery-item are set to NaN%;

### Steps to reproduce

Have a working Gallery Widget in 3.8.2.
Update Elementor Pro to 3.9.0.
Visit the page again

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

				
== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.54 (Debian)
	MySQL version: mariadb.org binary distribution v10.4.20
	PHP Version: 7.4.30
	PHP Memory Limit: 256M
	PHP Max Input Vars: 2500
	PHP Max Post Size: 10M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.1.1
	Site URL: https://new.decoratiehuren.be
	Home URL: https://new.decoratiehuren.be
	WP Multisite: No
	Max Upload Size: 10 MB
	Memory limit: 2048M
	Max Memory limit: 2048M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: Europe/Brussels
	Admin Email: info@puregraphx.be
	Debug Mode: Inactive

== Theme ==
	Name: Astra Child
	Version: 1.0.0
	Author: Brainstorm Force
	Child Theme: Yes
	Parent Theme Name: Astra
	Parent Theme Version: 3.9.4
	Parent Theme Author: Brainstorm Force

== User ==
	Role: administrator
	WP Profile lang: nl_NL
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36

== Active Plugins ==
	Astra Pro
		Version: 3.9.4
		Author: Brainstorm Force

	Breeze
		Version: 2.0.14
		Author: Cloudways

	Call for Price for WooCommerce Pro
		Version: 3.5.0
		Author: Tyche Softwares

	Checkout Field Editor for WooCommerce (Pro)
		Version: 3.4.0
		Author: ThemeHigh

	Code Snippets
		Version: 3.2.2
		Author: Code Snippets Pro

	Elementor
		Version: 3.9.0
		Author: Elementor.com

	Elementor Pro
		Version: 3.9.0
		Author: Elementor.com

	Enable Media Replace
		Version: 4.0.1
		Author: ShortPixel

	Import Export for WooCommerce
		Version: 1.0.2
		Author: Webtoffee

	Loco Translate
		Version: 2.6.3
		Author: Tim Whitlock

	MailPoet
		Version: 4.1.1
		Author: MailPoet

	MailPoet Premium
		Version: 4.1.0
		Author: MailPoet

	Order Import Export for WooCommerce
		Version: 1.0.1
		Author: Webtoffee

	Product Import Export for WooCommerce
		Version: 1.0.2
		Author: Webtoffee

	Regenerate Thumbnails Advanced
		Version: 2.4.0
		Author: ShortPixel

	Say What?
		Version: 2.1.2
		Author: Ademti Software

	Simple Custom CSS and JS
		Version: 3.41
		Author: SilkyPress.com

	Smart Manager - WooCommerce Advanced Bulk Edit, Inventory Management & more...
		Version: 7.2.0
		Author: StoreApps

	Toolset Types
		Version: 3.4.16
		Author: OnTheGoSystems

	UpdraftPlus - Backup/Restore
		Version: 1.22.23
		Author: UpdraftPlus.Com, DavidAnderson

	User Import Export for WooCommerce
		Version: 1.0.2
		Author: Webtoffee

	User Menus
		Version: 1.3.1
		Author: Code Atlantic

	WooCommerce
		Version: 7.1.1
		Author: Automattic

	Woocommerce delete product images
		Version: 1.0.2
		Author: Husain Ahmed

	WooCommerce Product Search
		Version: 4.7.0
		Author: itthinx

	WP Carousel
		Version: 2.5.1
		Author: ShapedPlugin

== Must-Use Plugins ==
	Health Check Troubleshooting Mode
		Version: 1.7.2
		Author: 

	Object Cache Pro (MU)
		Version: 1.16.4
		Author: Rhubarb Group

== Elementor Experiments ==
	Optimized DOM Output: Active by default
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active
	Inline Font Icons: Active
	Accessibility Improvements: Active by default
	Additional Custom Breakpoints: Active by default
	Import Export Website Kit: Active by default
	Hide native WordPress widgets from search results: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active
	Default to New Theme Builder: Inactive
	Landing Pages: Inactive
	Color Sampler: Inactive
	Favorite Widgets: Active by default
	Admin Top Bar: Inactive
	Lazy Load Background Images: Inactive by default
	Save as Default: Active by default
	Page Transitions: Inactive
	Notes: Inactive
	Loop: Active
	Form Submissions: Active by default
	Scroll Snap: Inactive

== Log ==
	
Log: showing 20 of 342022-11-17 15:15:30 [info] elementor::elementor_updater Started 
2022-11-17 15:15:30 [info] Elementor/Upgrades - _on_each_version Start  
2022-11-17 15:15:30 [info] Elementor/Upgrades - _on_each_version Finished 
2022-11-17 15:15:30 [info] Elementor/Upgrades - _v_3_8_0_fix_php8_image_custom_size Start  
2022-11-17 15:15:31 [info] Elementor/Upgrades - _v_3_8_0_fix_php8_image_custom_size Finished 
2022-11-17 15:15:31 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.8.0',
  'to' => '3.8.1',
)]
2022-11-30 15:22:46 [info] elementor-pro::elementor_pro_updater Started 
2022-11-30 15:22:46 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-11-30 15:22:46 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-11-30 15:22:46 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.8.1',
  'to' => '3.8.2',
)]
2022-12-07 14:41:38 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.8.1',
  'to' => '3.9.0',
)]
2022-12-07 14:41:39 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.8.2',
  'to' => '3.9.0',
)]
2022-12-07 14:41:40 [info] elementor::elementor_updater Started 
2022-12-07 14:41:40 [info] Elementor/Upgrades - _on_each_version Start  
2022-12-07 14:41:40 [info] Elementor/Upgrades - _on_each_version Finished 
2022-12-07 14:41:40 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.8.1',
  'to' => '3.9.0',
)]
2022-12-07 14:41:40 [info] elementor-pro::elementor_pro_updater Started 
2022-12-07 14:41:40 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-12-07 14:41:41 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-12-07 14:41:41 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.8.2',
  'to' => '3.9.0',
)]

JS: showing 5 of 5JS: 2022-11-15 10:20:14 [error X 19][https://new.decoratiehuren.be/wp-admin/post.php?post=5848&action=elementor:4:29911] Cannot read properties of undefined (reading \'replace\') 
JS: 2022-11-15 10:26:38 [error X 3][https://new.decoratiehuren.be/wp-admin/post.php?post=15749&action=elementor:4:29911] Failed to execute \'getComputedStyle\' on \'Window\': parameter 1 is not of type \'Element\'. 
JS: 2022-11-30 15:34:39 [error X 1][https://new.decoratiehuren.be/wp-admin/post.php?post=14377&action=elementor:4:29911] this.model.isValidChild is not a function 
JS: 2022-12-02 09:06:51 [error X 5][https://new.decoratiehuren.be/decoratieve-achtergronden/:4:29908] Cannot read properties of undefined (reading \'ratio\') 
JS: 2022-12-07 13:44:43 [error X 1][https://new.decoratiehuren.be/wp-admin/post.php?post=10&action=elementor:5:32885] Cannot read properties of null (reading \'getBoundingClientRect\') 

PHP: showing 3 of 3PHP: 2022-11-18 14:39:14 [notice X 4][/home/347263.cloudwaysapps.com/cdactapwnh/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-11-18 14:47:08 [notice X 1][/home/347263.cloudwaysapps.com/cdactapwnh/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::167] Undefined index: editor_post_id [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-11-30 16:02:47 [notice X 4][/home/347263.cloudwaysapps.com/cdactapwnh/public_html/wp-content/plugins/elementor/includes/embed.php::176] Trying to access array offset on value of type null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatibility not specified

== Elementor Pro - Compatibility Tag ==

**Comment by jlemonz** [comment] 2022-12-08 21:48
Do you use containers?

**Comment by jlemonz** [comment] 2022-12-08 22:12
I had the same issue also with tab and accourdion. You need to set direction and align i think and it is fixed. Its weird issue since 3.9

**Comment by puregraphx** [comment] 2022-12-09 08:45
> I had the same issue also with tab and accourdion. You need to set direction and align i think and it is fixed. Its weird issue since 3.9

 I know that was a fix in a previous 3.8.x version, but it doesn't seem to help now.
![Screenshot_3](https://user-images.githubusercontent.com/10434048/206661556-f408fca6-867e-421d-8ecb-c6521aed99e7.jpg)

**Comment by nicholaszein** [comment] 2022-12-09 13:06
Hello @puregraphx,

thanks for submitting your issue! 🙏 

Can you please confirm you had cleared your cache, and regenerated Elementor's CSS & Data after updating?

**Comment by puregraphx** [comment] 2022-12-09 13:10
@nicholaszein 

I can confirm I have indeed cleared cache and regenerated css/data. That did not resolve it. Only rollback to 3.8.x did.

**Comment by nicholaszein** [comment] 2022-12-09 15:21
Hi @puregraphx,

I'm having a hard time trying to reproduce your issue. When I update everything works fine. This might be something related to your installation. See:

https://user-images.githubusercontent.com/113993460/206734583-5f1131d4-87e6-45cf-8f17-0a839d226b97.mp4

Please try these troubleshooting steps:

⚠️  **Backup** your website before proceeding, and if possible do it in a staging environment!

1. Disable/Deactivate all your plugins except **Elementor** (and **Elementor Pro**).
    - If this solves the problem, gradually re-activate plugin-by-plugin (and check if the problem returns) to identify the problematic or conflicting plugin. In this case, contact the 3rd-party plugin support as we don't provide support for 3rd party plugins.
    - If it doesn't solve your problem, try the next step:
2. Change your WordPress theme to the [Hello Elementor](https://wordpress.org/themes/hello-elementor/) theme and check if the problem is solved.
3. Clear all cache types, including but not limited to **Server cache**, **WordPress (optimization plugin) cache**, **CDN cache**, and **Browser cache**. Also, try visiting the front page of your website in **incognito/private** mode.
4. Make sure the server resources allocated to your site and WordPress installation meet our [Requirements](https://elementor.com/help/requirements/). To check this information go to your _WordPress Dashboard > Elementor > System Info_, and check both your **Server Environment** and **WordPress Environment** tables. You can also scroll down to the end of the **System Info** page and click on the **Download System Info** button. Then submit another comment here and drop the `.txt` file inside the text box to upload your system information and share it with us.

#### 👎 If the issue persists, try contacting 💎 **Elementor Support** (for Pro Users). 
To open a ticket, go to your [Elementor Account page](https://my.elementor.com/) and click on the support icon.

For non-Elementor Pro users, check out these resources:
- [Elementor Global Community](https://facebook.com/groups/Elementors/) on Facebook
- [Elementor Help Center](https://docs.elementor.com)
- [Support Forum](https://wordpress.org/support/plugin/elementor) on WordPress.org 
- [Elementor Developers Documentation](https://developers.elementor.com/)

Regards

**Comment by nicholaszein** [comment] 2022-12-09 15:22
Hey @Jojo852,

please if you think you found a bug, make sure to open a new [🐞 Bug Report](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml), so we can help you better.

Thanks 🙏

**Comment by nicholaszein** [comment] 2022-12-19 15:33
Hello @puregraphx,

I have some news! It seems this issue was successfully reproduced by one of our team members, and a fix is underway! 🙌 

Thanks for being so patient! 🙏 

There is a workaround right now that you can use in case this happens with the latest version:

**Go to the Gallery Widget's Advanced tab and change the widget's width to 100%**

I'm reopening this issue until it's solved.

Please let me know if this works for you! 🙏 
Kind regards

**Comment by puregraphx** [comment] 2022-12-19 15:38
Hi @nicholaszein ,

I remembered this workaround from a previous 3.8.x version where this bug also appeared.

**Comment by jlemonz** [comment] 2022-12-19 20:34
I think this issue is also with the accordeon widget. The widget gets really narrow after the update i then have to check the containr ad click on a direction and it fixes itself. I do the same with the gallery and that also works. Just clicks the arrows of the container its in.

**Comment by 79ho3ein** [comment] 2023-01-03 16:40
Hi @leonbezza
Can you explain more? I don't see any problem with the divider widget. Do you have this problem in container?

**Comment by jlemonz** [comment] 2023-01-03 17:21
Yes divider also same problem just as accordions and gallery maybe more also have the issue but i dont use those. You just have to select a direction and it renders again correct. Maybe new sites dont have this issue.

**Comment by leonbezza** [comment] 2023-01-04 09:46
> Hi @leonbezza Can you explain more? I don't see any problem with the divider widget. Do you have this problem in container?

The Divider won't appear unless a direction is set on the container. Interestingly though, they all appear perfectly when "improved css loading" is switched off. Maybe that's actually where the problem lies?

**Comment by nicholaszein** [comment] 2023-02-13 18:06
Hello there @puregraphx!

We have great news! 🙌 

### 📢 We're happy to announce that the issue you raised was resolved in Elementor v.310.1! 🥳 

✔️ Feel free to check it out and update your plugin to the new version!

@leonbezza,

if you have a bug to report, please submit a new issue. Thanks 🙏 

Cheers 🥂

**Closed by nicholaszein** 2023-02-13 18:06 UTC
Labels: bug, status/merged, component/gallery
