### ISSUE TITLE
Please add Blur background to elementor

### ISSUE THREAD

**Issue by Michaelgimii** [elementor/elementor#16848] opened 2021-11-07 21:40 UTC
- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
In professional designs, the blur feature is widely used. Unfortunately, it has not been noticed in elementor so far.
For a professional designer, this is really essential. at the moment is the only way to meet this need is coding.
Please add this feature to elementor. This is a big limitation. Two examples of blur backgrounds :

![images](https://user-images.githubusercontent.com/88034902/140662957-5a3ad773-3d7e-4fd0-8104-f8b216ba2b8e.jpeg)

![Create-A-Frosted-Glass-Background-Effect-With-Elementor-Page-Builder-1](https://user-images.githubusercontent.com/88034902/140662962-f085ce7b-b791-4571-99b0-06146baa8f58.jpg)

**Comment by fabianenzensperger** [comment] 2021-11-07 23:29
"Backdrop filters" in general would be a great addition. Good idea!

**Comment by rami-elementor** [comment] 2022-02-21 19:52
Duplicate of #12035

**Closed by rami-elementor** 2022-02-21 19:52 UTC
