### ISSUE TITLE
Display conditions feature in elementor

### ISSUE THREAD

**Issue by Joliamendi** [elementor/elementor#18406] opened 2022-04-10 21:09 UTC
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

Please localize the display conditions property in elementor. This important feature is present in almost all elementor plugins, But not in elementor. Using third-party plugins to meet such a rudimentary need is torturous.

### Describe the solution you'd like

Display conditions feature

**Comment by rami-elementor** [comment] 2022-04-11 06:42
Hi @jrutheiser 

Are you talking about the **[Control Conditions](http://localhost:8080/controls/conditional-display/)** or **Theme Builder Conditions** ?

And when you ask to "localize", are you talking about i18n ?

**Comment by Joliamendi** [comment] 2022-04-11 07:49
Hi @rami-elementor 

No, I meant this feature : https://powerpackelements.com/display-conditions/

About localize , I just wanted to say please add it to elementor

**Comment by 79ho3ein** [comment] 2022-04-11 08:27
I know elementor is working on this great feature. But I would love to know when this feature will be released. At least approximately

**Comment by fabianenzensperger** [comment] 2022-04-11 12:24
We need this for sure! Go Elementor! :)

**Comment by 3l3mentor** [comment] 2022-04-12 16:08
+1

**Comment by 79ho3ein** [comment] 2022-04-24 12:29
Isn't this a similar request? #4246

**Comment by rami-elementor** [comment] 2022-04-24 15:00
Duplicate of #4246

**Closed by rami-elementor** 2022-04-24 15:00 UTC
Labels: request/feature, type/dynamic-content

**Comment by nicholaszein** [comment] 2024-04-12 07:16
Hello!

### 📢 We're happy to announce that the issue you raised was resolved in Elementor Pro v3.19.0, and improved with Elementor Pro 3.20.0! 🥳 

You can now use Display Conditions for widgets based on a variety of conditions, including date, time, user role, logged in/out, and others (more to come too). Check the [documentation for the new Display Conditions](https://elementor.com/help/show-and-hide-elements-on-a-page-display-conditions/) for widgets (Pro).

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
