### ISSUE TITLE
🐞 Bug Report: Fatal Error with Responsive Control used by 3rd party add-on (Duplicate of #19894)

### ISSUE THREAD

**Issue by mubardauda** [elementor/elementor#19922] opened 2022-09-27 04:33 UTC
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

I can't access my website, and I deactivated all plugins and re-activated, but when I activate elementor it shows **"There has been a critical error on this website**. I went to set WP_DEBUG to true to check the actual cause of the problem. Then I got this error info below

`Deprecated: Function _register_controls is deprecated since version 3.1.0! Use Elementor\Controls_Stack::register_controls() instead. in /home/u296760864/domains/fcmiddlewell.com/public_html/wp-includes/functions.php on line 5379`

`Deprecated: Function Elementor\Controls_Stack::_register_controls is deprecated since version 3.1.0! Use Elementor\Controls_Stack::register_controls() instead. in /home/u296760864/domains/fcmiddlewell.com/public_html/wp-includes/functions.php on line 5379`

`Notice: Undefined index: sina_transform_effects_translateX_tablet_tablet in /home/u296760864/domains/fcmiddlewell.com/public_html/wp-content/plugins/elementor/core/files/css/base.php on line 443`

`**Fatal error**: Uncaught TypeError: Argument 1 passed to Elementor\Core\Files\CSS\Base::get_style_control_value() must be of the type array, null given, called in /home/u296760864/domains/fcmiddlewell.com/public_html/wp-content/plugins/elementor/core/files/css/base.php on line 682 and defined in /home/u296760864/domains/fcmiddlewell.com/public_html/wp-content/plugins/elementor/core/files/css/base.php:738 Stack trace: #0 /home/u296760864/domains/fcmiddlewell.com/public_html/wp-content/plugins/elementor/core/files/css/base.php(682): Elementor\Core\Files\CSS\Base->get_style_control_value(NULL, Array) #1 [internal function]: Elementor\Core\Files\CSS\Base->Elementor\Core\Files\CSS\{closure}(NULL) #2 /home/u296760864/domains/fcmiddlewell.com/public_html/wp-content/plugins/elementor/core/files/css/base.php(448): call_user_func(Object(Closure), NULL) #3 /home/u296760864/domains/fcmiddlewell.com/public_html/wp-content/plugins/elementor/core/files/css/base.php(347): Elementor\Core\Files\CSS\Base->parse_property_placeholder(NULL, Array in /home/u296760864/domains/fcmiddlewell.com/public_html/wp-content/plugins/elementor/core/files/css/base.php on line 738`

### Steps to reproduce

I want to help fix this

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently using the steps above.

### System Info

/home/u296760864/domains/fcmiddlewell.com/public_html/wp-content/plugins/elementor/core/files/css/base.php on line 738

**Comment by w3b-beweb** [comment] 2022-09-27 14:34
Duplicate of https://github.com/elementor/elementor/issues/19894

As a temporary workaround see https://github.com/elementor/elementor/issues/19894#issuecomment-1256314016

**Comment by nicholaszein** [comment] 2022-09-28 14:49
Hello @mubardauda !

Thank you for contacting us.

You seem to have a conflict with a 3rd party add-on that is using an unsupported method, not included in our API.

We are already aware of this issue, and a fix will be released in the upcoming patch version. Meanwhile, please [Rollback](https://elementor.com/help/rolling-back-to-a-previous-version-of-elementor/) Elementor to version 3.7.6.
You can use the built-in rollback feature or simply [download this file](https://downloads.wordpress.org/plugin/elementor.3.7.6.zip) and upload it as a plugin to your website. It will ask you if you want to replace Elementor v3.7.7 with v3.7.6. Just click to replace it and everything should be back to normal.

📋 This issue is a Duplicate of https://github.com/elementor/elementor/issues/19894, which is on the same subject. For this reason, I'm closing this issue and ↔️ Merging it with the original, so we can have all the discussion in one location, and deal with it more efficiently.

Please feel free to continue the conversation there. 😉

Best regards,

Nick

**Closed** 2022-10-02 08:09 UTC
Labels: bug, compatibility/3rd_party, type/responsive, type/developer-api

**Comment by nicholaszein** [comment] 2022-10-03 18:39
Hello there @mubardauda!

📢 We have great news! 

### We're happy to announce that the issue you raised was resolved in Elementor v3.8-Beta 3! 🥳 

Please feel free to check it out and update your plugin to the new version! 💪 

https://github.com/orgs/elementor/discussions/19854#discussioncomment-3789526

Cheers 🥂
