### ISSUE TITLE
✔️ 🚀 Feature Request: Section columns gap - set values with css variables (custom properties) OR add parameters in "Site settings -> layout" section

### ISSUE THREAD

**Issue by gregamer** [elementor/elementor#13002] opened 2020-11-03 16:35 UTC
## Prerequisites

- [x ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Full control over columns gap widths

**Describe the solution you'd like**
Add option to set custom global columns gap values. Two options:
A better solution would be to add parameters to "Site settings -> layout" to set gap for each of the columns gap options: narrow, extended, wide, wider
Another option would also be to use css variables (custom properties) which can then be overridden in custom css:
--column-gap-narrow: 10px;
--column-gap-extended: 20px;
--column-gap-wide: 30px;
--column-gap-wider: 40px;

**Describe alternatives you've considered**
I'm currently using custom overrides in my scss, but the problem is it also overrides custom column padding (if set in column advanced tab). 
Elementor uses 4 selectors for the column gap setting:
.elementor-column-gap-default>.elementor-row>.elementor-column>.elementor-element-populated
It also uses 4 selector for custom column gap setting (in advanced tab):
.elementor-1558 .elementor-element.elementor-element-255b138 > .elementor-element-populated
My override also uses 4 selectors to override default Elementor settings but that also prevents custom elementor settings to apply. (see attached image)

**Additional context**
Add any other context or screenshots
![elementor-custom-columns-gap](https://user-images.githubusercontent.com/4144796/98013279-78c2e480-1dfa-11eb-845e-1dbcb5dde968.jpg)
 about the feature request here.

**Comment by DorShahar** [comment] 2020-12-03 06:41
Merged issue - comments down the thread are related to the same issue. 

I merged this issue with  #452, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.
Thanks for your feedback!

**Comment by black-eye** [comment] 2020-12-03 09:29
> Merged issue - comments down the thread are related to the same issue.
> 
> I merged this issue with #452, which is on the same subject so we could deal with it more efficiently.
> Please feel free to continue the conversation there.
> Thanks for your feedback!

@DorShahar Are you sure it is the same problem? The issue, you referenced, is about the column alignment caused by the (outer) column gap, this one is about making column gap a global variable. Or does it mean you are working on the solution for #452 and the solution is based on global variables?

**Comment by nicholaszein** [comment] 2022-11-16 03:56
Hello @gregamer!

We have great news! 💪 

### 📢 We're happy to announce that the request you made was resolved in Elementor **v3.8**! 🥳 

With the new (now stable) Flexbox Container experiment, you can define a global value for gaps in the Site Settings > Layout section, and leverage the power of CSS Flexbox to better control your gaps. In the future, you'll even be able to use different values for column and row gaps.

✔️ Please feel free to check it out and update your plugin to the new version!

Cheers 🥂

**Closed by nicholaszein** 2022-11-16 03:56 UTC
Labels: request/enhancement, component/site-settings, component/design, solved_by_container, 🚀 shipped
