### ISSUE TITLE
New stripe payment button widget

### ISSUE THREAD

**Issue by pauserratgutierrez** [elementor/elementor#14748] opened 2021-04-28 18:56 UTC
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
With elementor pro is not possible to accept payments using Stripe (only paypal for now and sometimes itsn't usefull because of its taxes and other things)

**Describe the solution you'd like**
A new widget like the paypal button to be able to accept payments using Stripe

**Describe alternatives you've considered**
Using premium addon such as "PionetAddon for Elementor"

**Comment by GBallzus** [comment] 2021-06-07 19:21
Duplicate of #14347

**Comment by paauserrat** [comment] 2021-06-07 20:09
Not duplicate, mine is for stripe

**Comment by avivu** [comment] 2022-05-10 19:20
Hello,
This issue has been resolved in Elementor Pro v3.7.0

Feel free to update

Thanks!

**Closed by avivu** 2022-05-10 19:20 UTC
Labels: request/enhancement
