### ISSUE TITLE
Custom loop item template

### ISSUE THREAD

**Issue by webmasterbart** [elementor/elementor#9844] opened 2019-12-11 15:06 UTC
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
- I can't find any solution to build an archive page with custom fields.
- I can't find any solution to have full control over the lay-out of an archive page.

**Describe the solution you'd like**
Please integrate this solution into the core : https://wordpress.org/plugins/ele-custom-skin/

**Describe alternatives you've considered**
JET, but thats too much. I would just like the **custom loop template** possibilty built in.

**Additional context**

**Comment by bainternet** [comment] 2019-12-11 19:49
Duplicate of #4440

**Closed by bainternet** 2019-12-11 19:49 UTC

**Comment by nicholaszein** [comment] 2023-08-01 20:47
Hello there!

We have great news! 🙌 

### 📢 We're happy to announce the new Loop Builder released with Elementor Pro v3.8.0! 🥳 

With the new Loop Grid widget, you can customize your post listings with custom templates! 💪 
Drag & Drop widgets to create complex designs, fine-tune your Loop Grid layout, add alternate templates, and much more!

This is just the first phase. More customization is coming!

Check out the article here: https://elementor.com/help/loop-grid/

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
