### ISSUE TITLE
Gradient background overlay doesn't handle dynamic field color correctly

### ISSUE THREAD

**Issue by Christopher-Hayes** [elementor/elementor#12588] opened 2020-09-18 22:40 UTC
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

I have a gradient background overlay setup using a dynamic field like in the screenshot of the Elementor editor below. As you can see on the right side the gradient linearly fades out as expected. The green tint is coming from the dynamic field.

![image](https://user-images.githubusercontent.com/6013871/93647878-70902080-f9d7-11ea-8b35-4126d19d37f0.png)

However, once I hit "Publish" and check the actual page, the background overlay loses its gradient and just turns into a uniform tint.

![image](https://user-images.githubusercontent.com/6013871/93647985-b3ea8f00-f9d7-11ea-8584-baaffcfd315f.png)

Looking at the CSS, the element that does the overlay is missing CSS properties. This is how `.elementor-background-overlay` looks in the Elementor editor (looking as it should):
![image](https://user-images.githubusercontent.com/6013871/93648231-44c16a80-f9d8-11ea-8309-3a00eec4917e.png)

This is the same CSS class on the actual page, as you can see the background gradient properties are now missing. Now only a `background-color` property is visible, suggesting some sort of fallback behavior, but this is reproducible on all modern browsers.
![image](https://user-images.githubusercontent.com/6013871/93648166-1d6a9d80-f9d8-11ea-8cd1-4cd8b461ff71.png)

## Steps to reproduce

1) Give a section a background overlay from in the elementor editor.
2) Set the overlay to be a `linear` or `radial` overlay.
3) Set one of the gradient colors to use a dynamic field to get the color.
4) The preview should now accurately show the color gradient.
5) Press "Publish" and check the actual published page. The resulting page will not show the gradient despite the elementor preview looking fine.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [ ] I can reproduce this bug consistently using the steps above.

## Environment

**Elementor Plugins:**

Elementor - 3.0.9
Elementor Pro - 3.0.4

<details>

<summary>System Info</summary>

**== Server Environment ==**

```
	Operating System: Linux
	Software: Apache
	MySQL version: MySQL Community Server (GPL) v5.6.47
	PHP Version: 7.4.10
	PHP Max Input Vars: 1000
	PHP Max Post Size: 8M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected
```

**== WordPress Environment ==**

```
	Version: 5.5.1
	Site URL: 
	Home URL: 
	WP Multisite: No
	Max Upload Size: 2 MB
	Memory limit: 128M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: America/New_York
	Admin Email:
	Debug Mode: Inactive
```

**== Theme ==**

```
	Name: GeneratePress Child
	Version: 0.1
	Author: Tom Usborne
	Child Theme: Yes
	Parent Theme Name: GeneratePress
	Parent Theme Version: 2.4.2
	Parent Theme Author: Tom Usborne
```
</details>

**Comment by SoundYeti** [comment] 2020-09-28 16:38
Hey, I am having same issues! 

Are there any thoughts on fixing this Bug?

**Comment by Christopher-Hayes** [comment] 2020-09-28 16:49
> Hey, I am having same issues!
> 
> Are there any thoughts on fixing this Bug?

What I ended up doing as a workaround was to recreate the gradient in HTML. Since I was using Pods.io, I was able to add a Pods.io block for a single item and in the template inject the dynamic field into the CSS background gradient on an HTML overlay element I added. Unfortunately, for other reasons we changed approaches and started adding the overlay directly to a background image, so I no longer have that workaround code to share.

**Comment by SoundYeti** [comment] 2020-09-28 17:19
yes that's almost the same thing I wanted to do, forcedly insert some extra styling server-side, parsing that 'linear-gradient...' into the correct place on the page from a field

it's just I initially wanted sleekier solutions, not inserting html mumbo jumbo

Thanks for the quick response!

**Comment by vleytman** [comment] 2020-09-29 12:02
Found a better solution:

Elementor allows to use attributes in Advanced>Attributes tab. Thing is, you can actually use "style" attribute and pass any styling data like that. So I made a shortcode, that generates a linear gradient styling from values of five fields I have to customize the gradient, like:

```
...
return 'style|background: linear-gradient(' . $angle . 'deg, ' . $color1 . ' ' . $color1loc . '%, ' . $color2 . ' ' . $color2loc . '%) !important';
...
```

Works flawlessly!

**Comment by mclendening** [comment] 2020-11-19 20:52
> @Christopher-Hayes @SoundYeti
> Found a better solution:
> 
> Elementor allows to use attributes in Advanced>Attributes tab. Thing is, you can actually use "style" attribute and pass any styling data like that. So I made a shortcode, that generates a linear gradient styling from values of five fields I have to customize the gradient. And Attributes allows to use dynamic tags, so I specified Site>Shortcode as a dynamic tag for Attributes field.
> 
> Then the shortcode returns a full attribute string like this:
> 
> ```
> ...
> return 'style|background: linear-gradient(' . $angle . 'deg, ' . $color1 . ' ' . $color1loc . '%, ' . $color2 . ' ' . $color2loc . '%) !important';
> ...
> ```
> 
> (_style|_ in the beginning is needed so that Elementor parse the attribute name)
> 
> Works flawlessly!

I’ve been looking for a cleaner work around, thank you!

**Comment by sbc640964** [comment] 2021-01-28 19:13
Elementor, what's up with this bug?

**Comment by oceandiveloper** [comment] 2022-01-11 02:45
More than a year later this is still not fixed. Come on Elementor Team!

**Comment by arielk** [comment] 2022-09-12 17:23
Duplicate of https://github.com/elementor/elementor/issues/10885

**Closed by arielk** 2022-09-12 17:23 UTC
