### ISSUE TITLE
Widget Manager (Ability to Turn ON/OFF the Widgets and Fuctionalities)

### ISSUE THREAD

**Issue by black-eye** [elementor/elementor#7530] opened 2019-03-18 20:10 UTC
## Prerequisites
- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
With the raising number of widgets and functions I'm starting to be worried about the bloat added to the page weight. Especially, when there are native Elementor capabilities I will rarely use (popups, motion effects, ...). 

There are also several third party widgets or functions, which I find better than the native ones or which can raise conflicts (or just make the widget list too crowded and duplicated).

Thus I propose this feature to make the widget list and Elementor uncluttered again. ;)

**Describe the solution you'd like**
Nothing new or never unseen here - most of the quality third party plugins have such a manager (Elementor Extras, UAEL, Premium Addons, PAFE, ...) so it's quite a pitty Elementor itself does't have it.

It would be nice, if there was a possibility to manage also 3rd party addons or make a Featured Widget group.

**Describe alternatives you've considered**
I know, there's a hook for unregistering the widgets (https://github.com/elementor/elementor/issues/3136), but this would be MUCH easier. Also I'm not sure if all the corresponding code is truly removed from the frontend (including CSS and JS) just by unregistering it.

**Additional context**
Example: Elementor Extras Wigets / Extensions Manager

![obrazek](https://user-images.githubusercontent.com/5634870/54560058-c2f71800-49c1-11e9-82fe-ae68a8e9f4a0.png)

**Comment by jasonb4u** [comment] 2019-03-19 08:17
Absolutely spot on.
This is a must have feature and I'm not surprised why this hasnt been implimented last year 2018 !!!
Its getting a bit to much having soooo many interferences from other 3rd party plugins that we may only need one feature from them but are stuck coz we have to allow their whole plugin work and some parts of them interfer & we cant turn them off.

**Comment by Manuel-SG** [comment] 2019-03-19 09:11
Yes please add this feature. With all the latest "shiny stuff" in Elementor (Animations, Popup etc.) we need to switch certain elements / widgets off if we don't want to use them. So we can increase the load time of Elementor Editor and reduce script bloat.

**Comment by sommarzan** [comment] 2019-03-19 15:03
Please, please, please!
We need this, or goodbye Elementor.

**Comment by ndstate** [comment] 2019-03-19 20:42
Yes please. I pay for pro and hope to see this soon.

**Comment by tristanleboss** [comment] 2019-03-19 21:56
When you install Elementor on customers website along with some packs of widgets, you clearly want this ability to unregister some of them.

**Comment by jasonb4u** [comment] 2019-03-20 00:48
These two 3rd party plugins who adapt to Elementor do it

Image Links below:
**Premium Addons for Elementor**:  https://prnt.sc/n08zh9
**Essential Addons**: https://prnt.sc/n08zwd

I'm pretty sure there's a MILLIONs people who want this for Elementor yet they know nothing about this Github thread.  Imagine if they did know about this thread & BOOOOOM this thread would go viral & be flooded with comments and to much reading and probably to many people making stupid silly comments that don't make sense.

This is a definite MUST happen for Elementor

If the Elementor team cant see whats going on here, somethings definitely wrong !!!

**Comment by tristanleboss** [comment] 2019-03-20 10:51
@jasonb4u Good luck. The Elementor team is following their own roadmap and they almost never implements features asked by developpers on this issues trackers A lot of them are rotting here for years :( They mostly develops features for designers...

**Comment by jasonb4u** [comment] 2019-03-20 20:37
@tristanleboss you didnt throw any possitive forward moving comments above instead was negative with nobody cares attitude. Are you Elementor making this claim, I think not! 

 Example cenario, people know the roadmap and when start driving but also people pull over to only get a bottle of water at the shop but randonly also get an apple as well for added benifits meaning theres always something different can happen anywhere at any time coz other things get added that are good.

Only positive comments required here thank you!!!

Dont bother asking whats water & apples got to do with it. Lets just hope you can read bewteen the lines of philosophy!

**Comment by thomasmalley** [comment] 2019-03-23 10:40
@arielk isn't this a case for the [component/role-manager](https://github.com/elementor/elementor/labels/component%2Frole-manager) tag? :) 

Keep up the great Work!

**Comment by mcinaz** [comment] 2019-04-03 22:29
YES! YES! YE! PLEASE!!!

**Comment by jasonb4u** [comment] 2019-04-03 23:07
Is there any of the Elementor Dev team looking and doing anything about this or is this Github a waste of time?

**Comment by tristanleboss** [comment] 2019-04-03 23:41
@jasonb4u Welcome to the Elementor GitHub where open feature requests rot for years (when they are not closed). Unfortunately, paying the Pro version doesn't give better support in term of feature requests. They said in january they would publish a roadmap but, as of today, nothing has been published. If your feature request is implemented, it's mostly because you're lucky they got the same idea as you at some point.

I would love to be proven wrong but, 99% of the time, they never reply on issue comments.

By subscribing to the FB group, I think they mostly do things for average WP users: they don't really care about people using Elementor everydays for professional use (web agency, ...).

**Comment by black-eye** [comment] 2019-04-04 00:06
@tristanleboss, @jasonb4u Well, this request seems to be surprisingly requested both from proffessional and average users. At least concluding from the recent FB poll here:

![obrazek](https://user-images.githubusercontent.com/5634870/55520549-26996a80-567d-11e9-8d1e-140ddd0fea50.png)

Widget Manager ended up (BY FAR) the most requested feature! Good to know, that even noobies are starting to be worried about the raising numbers of features and widgets and are afraid of the possible bloat added to their pages. Even Gutenberg is going to add some kind of manager, so why not Elementor. It would be very needed and handy feature. Hopefuly it will arrive sooner than later.

**Comment by vsimon51** [comment] 2019-04-13 14:26
Essential. Combat code bloat, interface bloat, and legacy crashes. Updating Elementor with new features previously provided by other plugins leads to a big checking problem on legacy sites. For example parallax installed with JetElements (turned off), and Elementor Extras (active on legacy sites); now along comes Pro and I have multiple locations for parallax and the potential for real conflicts - especially it seems on Safari if Pro fade in movement was previously activated.
Checking dozens of legacy sites for breakages caused by a new feature I cannot disable is beyond annoying.

**Comment by marceloaof** [comment] 2019-09-18 16:43
So necessary. Elementor is richer at every update. (it requires more resources)
Editor is loading forever on low-resource-servers... HTTP 500 error...
We definitely do not need all widgets loading at the same time.

**Comment by jasonb4u** [comment] 2019-09-18 18:05
Seems like the Dev team don't care pmsl. It's quite clear here this is a great attribute to have.
Come-on Elementor Team, get it together!!! How long does a discussion have to take place before something gets done about it, 1 year, 2 years.  Look how long it took for Font Awesome 5 to happen within EL from the other Github thread, wow!!!

**Comment by tristanleboss** [comment] 2019-09-18 19:49
@jasonb4u So now, you can clearly understand my first "negative with nobody cares attitude" reply to you ;)

**Comment by webstarspro** [comment] 2019-11-22 00:37
+1

**Comment by KoniKodes** [comment] 2019-11-27 19:20
+1
On the next update would be great!

**Comment by hansgcn** [comment] 2019-11-28 03:15
+1

**Comment by freelancesam** [comment] 2020-01-03 15:45
+1...

**Comment by chelseaoliviaxo** [comment] 2020-02-24 20:16
As more and more features are added to Elementor, this is becoming more and more necessary. Definite +1 from me.

**Comment by ianstudio** [comment] 2020-02-24 20:50
+1000 All addon suites I know can do it, why not Elementor itself ?

**Comment by maungthuu** [comment] 2020-02-25 03:03
+1

**Comment by jdgranja** [comment] 2020-03-09 22:10
+1

**Comment by Tvhawk** [comment] 2020-03-10 04:48
+1

**Comment by davidamarek** [comment] 2020-03-10 08:25
+1

**Comment by shilo-ey** [comment] 2020-03-18 13:16
I merged this issue with #1314, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!

**Closed by shilo-ey** 2020-03-18 13:16 UTC
Labels: component/role-manager, request/feature

**Comment by nicholaszein** [comment] 2024-01-05 21:20
Hello everyone!

We have great news! 🙌 

### 📢 We're happy to announce that this feature was released with Elementor Pro v3.18.0! 🥳 

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
