### ISSUE TITLE
upload attachment file inside the email message

### ISSUE THREAD

**Issue by sugarchrist** [elementor/elementor#5053] opened 2018-07-13 20:48 UTC
Hi, 
About Elementor Pro upload file in the form widget.

Is it possible to make the file uploaded, be in the email as a attachment and not just a link on my server.
Thank you

**Comment by bainternet** [comment] 2018-07-15 07:30
Duplicate of #4868 

https://github.com/pojome/elementor/issues/4868#issuecomment-400272455

**Closed by bainternet** 2018-07-15 07:30 UTC

**Comment by lauranunez** [comment] 2018-11-14 08:53
I want this feature too!!!!

**Comment by nicholaszein** [comment] 2024-01-05 21:03
Hello there @sugarchrist!

We have great news! 🙌 

### 📢 We're happy to announce that this feature was released with Elementor Pro v3.17.0! 🥳 

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
