### ISSUE TITLE
⛔ 🔗 Dynamic Tags in Element Display Conditions don't show all available fields (Duplicate of #25418)

### ISSUE THREAD

**Issue by kilianhln** [elementor/elementor#28353] opened 2024-08-11 21:09 UTC
### Prerequisites

- [ ] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [ ] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

The dynamic content feature supports only 50 custom fields in dynamic tags (hard coded limit?). As many plugins introduce their own custom fields, it can happen very fast that you have more than 50 custom fields.  In fact, this happens on most of our sites.

This has been the case in all versions of Elementor since the feature was introduced.

Here you can see that I can only see custom fields up to the letter P, because the limit of 50 tags has been reached.
![Screenshot_3](https://github.com/user-attachments/assets/0cd99f7a-17b4-4470-8d4d-8ac91f21dc45)

### Steps to reproduce

1. Create more than 50 custom fields with ACF or other plugins
2. Use the dynamic content feature with dynamic tags

### Expected behavior

1. Show all custom fields

### Isolating the problem

- [ ] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [X] This bug happens with the Hello Elementor theme active.
- [X] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

<details>
<summary>Click to reveal</summary>

````txt


== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Percona Server (GPL), Release '28', Revision '47601f19'$ v8.0.36-28
	PHP Version: 8.1.29-he.0
	PHP Memory Limit: 256M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 32M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.6.1
	WP Multisite: No
	Max Upload Size: 32 MB
	Memory limit: 40M
	Max Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: de_DE
	Timezone: Europe/Berlin
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor Child
	Version: 2.4.1.1636999482
	Author: Elementor Team
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 3.1.1
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: de-DE
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36

== Active Plugins ==
	Admin Columns
		Version: 4.7.7
		Author: AdminColumns.com

	Advanced Custom Fields PRO
		Version: 6.3.5
		Author: WP Engine

	Complianz | GDPR/CCPA Cookie Consent
		Version: 7.1.0
		Author: Really Simple Plugins

	Duplicator
		Version: 1.5.10.2
		Author: Duplicator

	Elementor
		Version: 3.23.4
		Author: Elementor.com

	Elementor Pro
		Version: 3.23.3
		Author: Elementor.com

	Password Protect WordPress Lite
		Version: 1.9.2
		Author: BWPS

	Rank Math SEO
		Version: 1.0.225
		Author: Rank Math

	Really Simple SSL
		Version: 8.1.6
		Author: Really Simple Plugins

	TablePress
		Version: 2.4
		Author: Tobias Bäthge

	User Role Editor
		Version: 4.64.2
		Author: Vladimir Garagulya

	WP Activity Log
		Version: 5.1.0
		Author: Melapress

	WP Crontrol
		Version: 1.17.0
		Author: John Blackbourn

	WP Fastest Cache
		Version: 1.2.9
		Author: Emre Vona

	WP Fastest Cache Premium
		Version: 1.7.1
		Author: Emre Vona


== Eigenschaften ==
	Custom Fonts: 2
	Custom Icons: 0

== Integrations ==
	
	recaptcha_v3: Aktiv


== Elementor-Experimente ==
	Verbessertes Laden von CSS: Aktiv
	Inline-Schriftarten-Symbole: Aktiv
	Additional Custom Breakpoints: Aktiv
	Flexbox Container: Aktiv
	Grid Container: Aktiv
	Upgrade Swiper Library: Aktiv
	Nested Elements Performance: Standardmäßig aktiviert
	Optimized Control Loading: Standardmäßig deaktiviert
	Optimized Markup: Standardmäßig deaktiviert
	Plugin Onboarding: Standardmäßig aktiviert
	Default to New Theme Builder: Standardmäßig aktiviert
	Header &amp; Footer: Standardmäßig deaktiviert
	Elementor Home Screen: Standardmäßig aktiviert
	Editor Top Bar: Aktiv
	Build with AI: Standardmäßig aktiviert
	Startseiten: Aktiv
	Nested Elements: Aktiv
	Hintergrundbilder nachladen: Aktiv
	Seiten Panel: Standardmäßig deaktiviert
	Element Caching: Standardmäßig deaktiviert
	Link In Bio: Standardmäßig deaktiviert
	Floating Buttons: Standardmäßig deaktiviert
	Elementor Editor Events: Standardmäßig deaktiviert
	Bedingungen anzeigen: Standardmäßig aktiviert
	Form Submissions: Standardmäßig aktiviert
	Menü: Aktiv
	Taxonomy Filter: Standardmäßig aktiviert
	Suche: Standardmäßig deaktiviert

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Kompatibel

== Elementor Pro - Compatibility Tag ==

````

</details>

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by creative-andrew** [comment] 2024-08-18 10:14
Any news on this?

**Comment by nicholaszein** [comment] 2024-09-10 02:54
Hello @kilianhln and @creative-andrew,

Thank you for reaching out! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
- There is a limitation of 50 items by default to prevent depleting server resources. You can follow the instructions in the [comment](https://github.com/elementor/elementor/issues/25418#issuecomment-2036567032) in the issue indicated below.

### 👍 For now, that's all we can help with. 

### 🔗 🐞 This issue is a Duplicate of #25418 

Which is on the same subject. 

For this reason, I'm closing this thread and 🔃 **Merging** it with the original, so we can have all the discussions in one location, and deal with it more efficiently.

Feel free to continue the conversation there. 😉 

### 🔍 Please, in the future, remember to check if there isn't any thread similar to yours already opened. 

Kind regards

**Closed by nicholaszein** 2024-09-10 02:54 UTC
Labels: component/dynamic-tag, type/dynamic-content, mod*, duplicate, widget/settings/display-conditions
