### ISSUE TITLE
🔗 🐞 Bug Report: Sticky Inner Section does not stay in column (Duplicate of #20203)

### ISSUE THREAD

**Issue by veniko** [elementor/elementor#20271] opened 2022-11-03 13:04 UTC
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

This issue is described here - https://github.com/elementor/elementor/issues/7956

### Steps to reproduce

https://github.com/elementor/elementor/issues/7956

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

Irrelevant

**Comment by nicholaszein** [comment] 2022-11-03 17:01
Hello @veniko!

Thank you for your submission! 🙏 

### 🔗 This issue is a Duplicate of #20203 

Which is on the same subject. 

For this reason, I'm closing this issue and 🔃 **Merging** it with the original, so we can have all the discussions in one location, and deal with it more efficiently.

Feel free to continue the conversation there. 😉 

### ✔️ Please, in the future, remember to check if there isn't an issue similar to yours already opened. 

Best regards,

Nick

**Closed by nicholaszein** 2022-11-03 17:01 UTC
Labels: bug, type/layout, component/sticky
