### ISSUE TITLE
Share Buttons -- Missing Social Media

### ISSUE THREAD

**Issue by jgajera** [elementor/elementor#7146] opened 2019-02-21 02:18 UTC
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
The Share Buttons module is lacking a few really popular platforms -- namely Instagram and YouTube 

**Describe the solution you'd like**
Please just add IG and YT; better would be to open up all social media icons for this module (if/when possible, depending on the social media platform)

**Describe alternatives you've considered**
Installing a third-party plugin :-(

**Comment by shilo-ey** [comment] 2019-02-21 07:44
You cannot share to Instagram or YouTube.

Duplicate of #6885.

**Closed by shilo-ey** 2019-02-21 07:44 UTC
