### ISSUE TITLE
Custom Post Loop Layout

### ISSUE THREAD

**Issue by nfspck** [elementor/elementor#11231] opened 2020-04-26 13:22 UTC
I'm a recent (as of March 2020) convert from Beaver Builder and I love Elementor but there are two features that I really miss and this is one of them. In BB I can create custom post loops and display any piece of information I want in the loop be it ACF, PODS, WP custom fields, etc, read their doc on the feature [HERE](https://kb.wpbeaverbuilder.com/article/577-create-a-card-layout-for-posts-themer). This is incredibly helpful when working with custom post types as again I can show any data in the post loop and it's part of BB Pro out of the box. It does take a bit of 'coding' to accomplish but it's 100x easier than actually coding it in a PHP template.

If Elementor could include this feature it would be a game-changer because for each project I still have to choose which page builder to use based on the requirements and I'd like to make that choice a little easier.

**Comment by bainternet** [comment] 2020-04-26 15:58
Thanks for the feedback,
Please follow guidelines for opening a new [feature request](https://github.com/pojome/elementor/issues/new?template=Feature_request.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Description and examples.

**Comment by bainternet** [comment] 2020-04-26 15:58
Duplicate of #4440

**Closed by bainternet** 2020-04-26 15:58 UTC

**Comment by nicholaszein** [comment] 2023-08-01 20:51
Hello there!

We have great news! 🙌 

### 📢 We're happy to announce the new Loop Builder released with Elementor Pro v3.8.0! 🥳 

With the new Loop Grid widget, you can customize your post listings with custom templates! 💪 
Drag & Drop widgets to create complex designs, fine-tune your Loop Grid layout, add alternate templates, and much more!

This is just the first phase. More customization is coming!

Check out the article here: https://elementor.com/help/loop-grid/

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
