### ISSUE TITLE
Bug with global typography

### ISSUE THREAD

**Issue by rodolphebertozzo** [elementor/elementor#12369] opened 2020-09-01 11:32 UTC
When I create a global typography and assign it to elements, it appears in editor mode, but it does not appear at the rendering level, my elements in question inherit Elementor's basic styles.

**Comment by thehervy** [comment] 2020-09-01 14:12
Hi, first you have to create a bug through specific guideline: https://github.com/elementor/elementor/issues/new?template=Bug_report.md

Second: this bug is known, really bad and a lot of duplicit issues has been created right now. Hopefully it will be solved really soon!

**Comment by arielk** [comment] 2020-09-01 16:57
Duplicate of https://github.com/elementor/elementor/issues/12363

**Closed by arielk** 2020-09-01 16:57 UTC
