### ISSUE TITLE
elementor deprecation issues bug 

### ISSUE THREAD

**Issue by JasonSahli** [elementor/elementor#7654] opened 2019-03-28 13:54 UTC
Deprecated: Non-static method ElementorPro\Modules\QueryControl\Module::get_query_args() should not be called statically in /home/b8w1h184x61u/public_html/wp-content/plugins/elementor-pro/modules/woocommerce/widgets/products-deprecated.php on line 161

what is causing this?

**Comment by shilo-ey** [comment] 2019-03-28 15:35
Hi @JasonSahli 

Thanks for reporting.

This is due to depreciation of the Query control method.

This will be fixed in the next Pro version.

Follow this thread for updates.

**Comment by JasonSahli** [comment] 2019-03-28 15:41
The elementor support team blamed it on woocommerce and asked me to chase
after them for a fix, why?

**Comment by thimfy** [comment] 2019-03-30 07:48
Do not purchase elementor or any item from creator of it, no support nothing just kind of shit only.

**Comment by shilo-ey** [comment] 2019-03-31 14:38
This issue has been fixed in Elementor Pro v2.5.3

Feel free to update!

**Comment by AlexdeBorba** [comment] 2021-02-24 13:15
It seems the issue is yet to be resolved, as this is from the latest version of Elementor, installed today.

`2021/02/24  12:24:48 [error] 25300#25300: *1977434 FastCGI sent in stderr: "PHP  message: PHP Deprecated:   ElementorPro\Modules\QueryControl\Module::add_exclude_controls is  <strong>deprecated</strong> since version 2.5.0! Use class  Group_Control_Query instead. in  /www/xxx/public/wp-includes/functions.php on line 4859" while  reading response header from upstream, client: 186.86.68.185, server:  www.domain.com, request: "POST  /wp-admin/admin-ajax.php HTTP/1.0", upstream:  "fastcgi://unix:/var/run/php7.4-fpm-aeon.sock:", host:  "www.domain.com", referrer:  "https://www.domain.com/wp-admin/post.php?post=134098&action=elementor"
--`

**Comment by triangle-stream** [comment] 2021-03-02 20:53
I can confirm updating Elementor and Elementor pro to latest cause this issue (with WP Debug on):
`Deprecated: ElementorPro\Modules\QueryControl\Module::add_exclude_controls è deprecata dalla versione 2.5.0! Al suo posto utilizza class Group_Control_Query. in /var/www/wordpress/wp-includes/functions.php on line 4859`

Also, after the update to the latest WP version [5.6.2], Nginx started to show some new errors. 

In Elementor's Log, now I can find this line:
`JS: 2021-03-02 20:01:24 [error X 1][https://**-------**/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.1.1:2:467421] $e.routes.getHistory(...).reverse()[0] is undefined `

**Comment by llgreg** [comment] 2021-04-15 23:06
I'm also getting this error 
Using  
Elementor v3.1.4  
Elementor Pro v3.2.1 

PHP 7.4.16
WordPress v5.7.1 
WooCommerce version 5.2.0

can the issue be re-looked at please?

`2021/04/15 16:37:28 [error] 3482#0: *4413550 FastCGI sent in stderr: "PHP message: PHP Deprecated:  ElementorPro\Modules\QueryControl\Module::add_exclude_controls is <strong>deprecated</strong> since version 2.5.0! Use class Group_Control_Query instead. in `

**Comment by lukboegit** [comment] 2021-05-24 22:55
Bump, same problem here

**Comment by dimoteca** [comment] 2021-05-31 15:01
+1

**Comment by RuanPienaarCode** [comment] 2021-06-17 07:58
Bump same issue. We have Latest Elementor and wordpress installed and getting this error message.

`[17-Jun-2021 07:37:14 UTC] PHP Deprecated:  ElementorPro\Modules\QueryControl\Module::add_exclude_controls is <strong>deprecated</strong> since version 2.5.0! Use class Group_Control_Query instead. in /usr/www/users/devfoubfer/wp-includes/functions.php on line`

**Comment by dibg** [comment] 2021-06-19 01:03
I fail to see how something that suposably has being fixed 2 years ago still throws the same error in the latest elementor pro version.

Deprecated: ElementorPro\Modules\QueryControl\Module::add_exclude_controls is deprecated since version 2.5.0!

**Comment by ofmarconi** [comment] 2021-06-21 22:05
> Não consigo ver como algo que supostamente foi consertado 2 anos atrás ainda gera o mesmo erro na última versão Pro do Elementor.
> 
> Obsoleto: ElementorPro \ Modules \ QueryControl \ Module :: add_exclude_controls está obsoleto desde a versão 2.5.0!

Too

**Comment by llgreg** [comment] 2021-06-22 07:54
@shilo-ey are you able to re-open this please, as this is still ongoing.

**Comment by realmofevil** [comment] 2021-07-20 23:49
> This issue has been fixed in Elementor Pro v2.5.3
> 
> Feel free to update!

Not fixed. Still printing it in ver. 3.3.0:
`Deprecated: ElementorPro\Modules\QueryControl\Module::add_exclude_controls is deprecated since version 2.5.0! Use class Group_Control_Query instead. in /home/public_html/wp-includes/functions.php on line 5083`

**Comment by AlinaDibrani** [comment] 2021-07-28 09:05
Are you ready to fix it!

**Comment by splaquet** [comment] 2021-08-04 22:10
ugh
`
elementor                                        | active-network | none      | 3.3.1     |
elementor-pro                                    | active-network | none      | 3.3.5     |
`

are we certain it's been fixed?
`[04-Aug-2021 22:04:14 UTC] PHP Deprecated:  ElementorPro\Modules\QueryControl\Module::add_exclude_controls is <strong>deprecated</strong> since version 2.5.0! Use class Group_Control_Query instead. in /home/domain.dev/public_html/wp-includes/functions.php on line 5083
[04-Aug-2021 22:04:14 UTC] PHP Stack trace:
[04-Aug-2021 22:04:14 UTC] PHP   1. {main}() /home/domain.dev/public_html/wp-admin/admin-ajax.php:0
[04-Aug-2021 22:04:14 UTC] PHP   2. do_action() /home/domain.dev/public_html/wp-admin/admin-ajax.php:187
[04-Aug-2021 22:04:14 UTC] PHP   3. WP_Hook->do_action() /home/domain.dev/public_html/wp-includes/plugin.php:470
[04-Aug-2021 22:04:14 UTC] PHP   4. WP_Hook->apply_filters() /home/domain.dev/public_html/wp-includes/class-wp-hook.php:327
[04-Aug-2021 22:04:14 UTC] PHP   5. Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request() /home/domain.dev/public_html/wp-includes/class-wp-hook.php:303
[04-Aug-2021 22:04:14 UTC] PHP   6. call_user_func:{/home/domain.dev/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php:171}() /home/domain.dev/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php:171
[04-Aug-2021 22:04:14 UTC] PHP   7. Elementor\Widgets_Manager->ajax_get_widget_types_controls_config() /home/domain.dev/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php:171
[04-Aug-2021 22:04:14 UTC] PHP   8. ElementorPro\Modules\Woocommerce\Widgets\Products_Deprecated->get_stack() /home/domain.dev/public_html/wp-content/plugins/elementor/includes/managers/widgets.php:274
[04-Aug-2021 22:04:14 UTC] PHP   9. ElementorPro\Modules\Woocommerce\Widgets\Products_Deprecated->get_stack() /home/domain.dev/public_html/wp-content/plugins/elementor/includes/base/widget-base.php:172
[04-Aug-2021 22:04:14 UTC] PHP  10. ElementorPro\Modules\Woocommerce\Widgets\Products_Deprecated->init_controls() /home/domain.dev/public_html/wp-content/plugins/elementor/includes/base/controls-stack.php:461
[04-Aug-2021 22:04:14 UTC] PHP  11. ElementorPro\Modules\Woocommerce\Widgets\Products_Deprecated->register_controls() /home/domain.dev/public_html/wp-content/plugins/elementor/includes/base/controls-stack.php:1953
[04-Aug-2021 22:04:14 UTC] PHP  12. ElementorPro\Modules\QueryControl\Module::add_exclude_controls() /home/domain.dev/public_html/wp-content/plugins/elementor-pro/modules/woocommerce/widgets/products-deprecated.php:155
[04-Aug-2021 22:04:14 UTC] PHP  13. Elementor\Modules\DevTools\Deprecation->deprecated_function() /home/domain.dev/public_html/wp-content/plugins/elementor-pro/modules/query-control/module.php:70
[04-Aug-2021 22:04:14 UTC] PHP  14. _deprecated_function() /home/domain.dev/public_html/wp-content/plugins/elementor/modules/dev-tools/deprecation.php:238
[04-Aug-2021 22:04:14 UTC] PHP  15. trigger_error() /home/domain.dev/public_html/wp-includes/functions.php:5083`

**Comment by chemalopezp** [comment] 2021-08-07 23:48
I'm afraid I'm also seeing the same bug here

```
Deprecated: ElementorPro\Modules\QueryControl\Module::add_exclude_controls ha quedado obsoleto desde la versión 2.5.0. Utiliza class Group_Control_Query en su lugar. in /home/customer/www/sitename.com/public_html/wp-includes/functions.php on line 5083
```

I'm mostly on the latest vesions
Wordpress (Spanish) v5.8
Elementor v3.3.1 
Elementor Pro v3.3.5
WooCommerce v5.5.2
WP Rocket 3.5.4

**Comment by omandaisy** [comment] 2021-08-16 18:04
I think the issue not resolved on elementor updates , i can see same error 

do u have any idea about how to fix this

**Comment by josett225** [comment] 2021-08-16 21:54
Same issue here with all the latest updates...

**Comment by tradesouthwest** [comment] 2021-08-21 19:31
Plus 1: Issue occurs Elementor Pro 3.3.7 - 2021-08-15; PHP 7.3 (ea-php73); 

"Deprecated: ElementorPro\Modules\QueryControl\Module::add_exclude_controls is deprecated since version 2.5.0! Use class Group_Control_Query instead. in /home/vacastays/public_html/wp-includes/functions.php on line 5083"

Is it possible that line 76 in ...elementor-pro/modules/query-control/module.php	`'type' => Controls_Manager::SELECT2,` is at fault; but not Elementor... maybe a SELECT2  control?

Only asking because I got this deprecation error only after I update a select/dropdown field in a (Listeo) plugin option select field; and not when there is any Elementor editing. At least this was the first time I saw the error... otherwise error never existed prior to updating a select2 field.

**Comment by udidol** [comment] 2021-11-22 13:20
@tradesouthwest @360Zach @llgreg @josett225 @omandaisy @chemalopezp @splaquet @realmofevil 

Can you upgrade to the latest Elementor and Elementor Pro versions and let me know if this problem persists or not?
I believe we resolved issues with this deprecation in one of the latest versions.

**Comment by DorShahar** [comment] 2021-12-05 09:10
Closing for lack of activity,
Feel free to reopen if the issue persists.

**Closed by DorShahar** 2021-12-05 09:10 UTC
Labels: compatibility, product/pro, status/merged
