### ISSUE TITLE
⛔ Slideshow images can't be indexed

### ISSUE THREAD

**Issue by Gencay2** [elementor/elementor#28123] opened 2024-07-18 12:53 UTC
### Prerequisites

- [X] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [X] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

Slideshow images aren't indexed because of JavaScript. There should be a way to disable JavaScript on the slideshow for people who have images with valuable EXIF data in their homepage slideshow images, like me.

### Steps to reproduce

1. Upload images in the Elementor slideshow.
2. Check if the number of images in the sitemap matches the actual number.
3. Check if crawlers can see the images in the slideshow by disabling JavaScript in the browser or running a live URL test in the Search Console.
4. Wait for them to be indexed (they will not be).

### Expected behavior

1. Upload images to the Elementor slideshow.
2. Disable JavaScript in the slideshow so it relies only on CSS and HTML.
3. The images are indexed.

### Isolating the problem

- [ ] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [ ] This bug happens with the Hello Elementor theme active.
- [X] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

<details>
<summary>Click to reveal</summary>

````txt

== Server Environment ==
	Operating System: Linux
	Software: LiteSpeed
	MySQL version: MariaDB Server v10.4.33
	PHP Version: 7.4.33
	PHP Memory Limit: 370M
	PHP Max Input Vars: 5000
	PHP Max Post Size: 370M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.6
	Site URL: https://akcakocaalfaokullari.k12.tr
	Home URL: https://akcakocaalfaokullari.k12.tr
	WP Multisite: No
	Max Upload Size: 370 MB
	Memory limit: 40M
	Max Memory limit: 370M
	Permalink Structure: /%postname%/
	Language: tr_TR
	Timezone: Europe/Istanbul
	Debug Mode: Inactive

== Theme ==
	Name: Astra
	Version: 4.6.16
	Author: Brainstorm Force
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: tr
	User Agent: Mozilla/5.0 (X11; CrOS x86_64 14541.0.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36

== Active Plugins ==
	All-in-One WP Migration
		Version: 6.77
		Author: ServMask

	Classic Editor
		Version: 1.6.3
		Author: WordPress Contributors

	Elementor
		Version: 3.23.1
		Author: Elementor.com

	LiteSpeed Cache
		Version: 6.0.0.1
		Author: LiteSpeed Technologies

	LuckyWP Table of Contents
		Version: 2.1.4
		Author: LuckyWP

	Rank Math SEO
		Version: 1.0.223
		Author: Rank Math

	Smart Custom 404 error page [404page]
		Version: 11.4.6
		Author: Peter Raschendorfer

	Spotlight - Social Media Feeds
		Version: 1.6.13
		Author: RebelCode

	Starter Templates
		Version: 4.2.6
		Author: Brainstorm Force

	Unlimited Elements for Elementor
		Version: 1.5.108
		Author: Unlimited Elements

	WP External Links
		Version: 2.61
		Author: WebFactory Ltd

	WPForms Lite
		Version: 1.8.8.3
		Author: WPForms


== Elementor Deneysel ==
	İyileştirilmiş varlık yükleme: Varsayılan olarak etkin
	Geliştirilmiş CSS Yükleme: Varsayılan olarak etkin
	Satır İçi Yazı Tipi Simgeleri: Varsayılan olarak etkin
	Ek Özel Kesme Noktaları: Varsayılan olarak etkin
	admin_menu_rearrangement: Varsayılan olarak etkin değil
	Esnekkutu Konteyner: Etkin
	Swiper Kütüphanesini Yükselt: Varsayılan olarak etkin
	Izgara Konteyner: Varsayılan olarak etkin
	İç İçe Elemanlar Performans: Varsayılan olarak etkin değil
	Optimize Edilmiş Kontrol Yüklemesi: Varsayılan olarak etkin değil
	Elementor Ana Ekran: Varsayılan olarak etkin
	Editör Üst Çubuğu: Varsayılan olarak etkin değil
	Yapay zeka ile inşa edin: Varsayılan olarak etkin
	Açılış Sayfaları: Varsayılan olarak etkin
	İç İçe Öğeler: Varsayılan olarak etkin değil
	Tembel Yük Arka Plan Resimleri: Varsayılan olarak etkin


== Kayıtlar ==
	
JS: showing 8 of 8JS: 2024-05-28 16:15:01 [error X 1][../wp-admin/load-scripts.php?c=1&loadchunk_0=jquery-core,jquery-migrate,utils,wp-polyfill-inert,regenerator-runtime,wp-polyfill,wp-hooks&ver=6.5.3:2:28760] Cannot read properties of undefined (reading 'value') 
JS: 2024-06-06 10:08:16 [error X 10][../wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.21.8:3:821594] Cannot read properties of undefined (reading 'localized') 
JS: 2024-06-10 12:44:38 [error X 3][../wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.21.8:3:654174] Cannot read properties of undefined (reading 'isDesignable') 
JS: 2024-06-11 15:57:15 [error X 1][../wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.21.8:3:335170] Cannot read properties of undefined (reading 'html') 
JS: 2024-06-13 10:35:16 [error X 3][../wp-content/plugins/unlimited-elements-for-elementor/provider/core/plugins/unlimited_elements/elementor/assets/uc_front_admin.js?ver=1.5.108:107:76] elementorFrontend is not defined 
JS: 2024-06-13 10:35:44 [error X 1][../wp-content/plugins/unlimited-elements-for-elementor/provider/core/plugins/unlimited_elements/elementor/assets/uc_front_admin.js?ver=1.5.108:107:44] Cannot read properties of undefined (reading 'initFrontEndInteraction') 
JS: 2024-06-21 16:36:24 [error X 6][../wp-content/plugins/elementor/assets/js/responsive-bar.min.js?ver=3.21.8:2:11756] elementor is not defined 
JS: 2024-06-21 16:36:24 [error X 1][../wp-content/plugins/elementor/assets/js/editor-loader-v1.min.js?ver=3.21.8:2:37] Cannot read properties of undefined (reading 'start') 

PHP: showing 1 of 1PHP: 2024-05-31 12:58:59 [notice X 2][../wp-content/plugins/elementor/includes/managers/image.php::113] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]



== Elementor. - Compatibility Tag ==
	
	Unlimited Elements for Elementor: Uyumluluk belirtilmedi

````

</details>

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by nicholaszein** [comment] 2024-07-19 15:37
Hello @Gencay2,

Thank you for reaching out! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
I believe you are referring to the Slides (Pro) widget. Elementor does not have a slideshow widget.

The Slides widget used background images (as indicated in the widget itself). Background images are usually not indexed by Search Engines. This is the expected behavior, and what you are reporting here is not a bug.

### ✅ What you can do to solve your issue:
First, if you wish to index images, you should avoid using slides. Slides are meant to showcase Call to Actions. However, if you still want to use something like a Carousel, you should use the Nested Carousel (Pro) widget, and insert actual Image widgets inside. These will be indexed correctly.

### 👍 For now, that's all we can help with. 

This is more of a question you should have submitted to Elementor Support. 

### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for personal support.

❔ If you have questions, or need guidance, help, or general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) The main Facebook group where all kinds of users come together to help each other.
- [Elementor Academy](https://elementor.com/academy) Learn everything you need to know about using Elementor.
- [Elementor Developers Documentation](https://developers.elementor.com/) Learn everything about our Developer-API.
- [Free Support Forum](https://wordpress.org/support/plugin/elementor) Get help on WordPress.org.

💎 If you have an active [Elementor Pro](https://elementor.com/pro) license you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Kind regards

**Closed by nicholaszein** 2024-07-19 15:37 UTC
Labels: product/pro, component/swiper, type/seo, widget/slides, mod*
