### ISSUE TITLE
🔗 Images from the Image Carousel don’t open in Lightbox when the slide Effect is set to Fade (Duplicate of #23039)

### ISSUE THREAD

**Issue by CecoSvidovski** [elementor/elementor#28313] opened 2024-08-07 11:53 UTC
### Prerequisites

- [X] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [X] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

I'm using the latest version of Elementor and Elementor Pro with Hello Elementor Theme. When I add the Image Slider and choose the option for a Lightbox the link(a tag) only works on the first image since it is not updating the attributes of every slide on change. All of the slides excluding the first one have an "inert" and an "aria-hidden=true" attributes on them that don't change on going to the next slide. I saw a similar issue here [https://github.com/elementor/elementor/issues/22994](url). The issue has been closed so I decided to post a new one.

### Steps to reproduce

1. Add an Image Slider to a page
2. Link>Media File
3. Lightbox>Yes
4. Slides to Show>1
5. Additional options>Effect>Fade
6. Link only works on first slide
7. Slide's aria-hidden and inert attributes don't update on slide change

### Expected behavior

1. Add an Image Slider to a page
2. Link>Media File
3. Lightbox>Yes
4.  Slides to Show>1
5. Additional options>Effect>Fade
5. Link works on all slides
6. Attributes aria-hidden and inert update on slide change

### Isolating the problem

- [X] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [X] This bug happens with the Hello Elementor theme active.
- [X] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

<details>
<summary>Click to reveal</summary>

````txt


== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MariaDB Server v10.6.18
	PHP Version: 7.4.33
	PHP Memory Limit: 128M
	PHP Max Input Vars: 5000
	PHP Max Post Size: 20M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.6.1
	Site URL: https://***.com/new2024
	Home URL: https://***.com/new2024
	WP Multisite: No
	Max Upload Size: 20 MB
	Memory limit: 40M
	Max Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: bg_BG
	Timezone: Europe/Sofia
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 3.1.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: bg-BG
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36

== Active Plugins ==
	Classic Editor
		Version: 1.6.4
		Author: WordPress Contributors

	Contact Form 7
		Version: 5.9.8
		Author: Takayuki Miyoshi

	Cyr-To-Lat
		Version: 6.1.0
		Author: Sergey Biryukov, Mikhail Kobzarev, Igor Gergel

	Elementor
		Version: 3.23.4
		Author: Elementor.com

	Elementor Pro
		Version: 3.23.3
		Author: Elementor.com

	WPForms Lite
		Version: 1.8.9.6
		Author: WPForms

	Yoast Duplicate Post
		Version: 4.5
		Author: Enrico Battocchi & Team Yoast


== Elements Usage ==
	
	footer : 1
		button : 1
		container : 7
		heading : 5
		icon-list : 1
		image : 1
		nav-menu : 2
		social-icons : 1
		text-editor : 4
	header : 2
		button : 2
		container : 7
		icon : 2
		nav-menu : 2
	page : 3
		heading : 12
		icon-box : 9
		image : 12
		shortcode : 3
		text-editor : 3
		video : 3
	wp-post : 0
		container : 35
		google_maps : 1
		heading : 28
		icon : 6
		icon-box : 9
		icon-list : 4
		image : 12
		shortcode : 3
		social-icons : 1
		spacer : 10
		text-editor : 10
		video : 3
	wp-page : 44
		accordion : 3
		button : 2
		container : 30
		google_maps : 3
		heading : 5
		icon : 3
		icon-box : 69
		image : 1
		image-carousel : 4
		image-gallery : 16
		shortcode : 3
		spacer : 1
		text-editor : 30
	single-post : 1
		button : 1
		container : 12
		heading : 7
		icon : 2
		image-carousel : 1
		theme-post-content : 1


== Настройки ==
	
	cpt_support: post, page
	disable_color_schemes: yes
	disable_typography_schemes: yes
	allow_tracking: yes
	unfiltered_files_upload: 1
	font_display: swap
	load_fa4_shim: yes


== Функции ==
	Custom Fonts: 1
	Custom Icons: 0

== Интеграции ==
	


== Elementor Experiments ==
	Improved CSS Loading: Активен
	Inline Font Icons: Активен
	Additional Custom Breakpoints: Активно по подразбиране
	Flexbox Container: Активен
	Grid Container: Активен
	Upgrade Swiper Library: Активно по подразбиране
	Nested Elements Performance: Активно по подразбиране
	Optimized Control Loading: Неактивно по подразбиране
	Optimized Markup: Неактивно по подразбиране
	Plugin Onboarding: Активно по подразбиране
	Default to New Theme Builder: Активно по подразбиране
	Header &amp; Footer: Неактивно по подразбиране
	Elementor Home Screen: Активно по подразбиране
	Editor Top Bar: Активен
	Build with AI: Неактивно
	Целеви страници: Активно по подразбиране
	Nested Elements: Активен
	Lazy Load Background Images: Активно по подразбиране
	Pages Panel: Неактивно по подразбиране
	Element Caching: Неактивно по подразбиране
	Link In Bio: Неактивно по подразбиране
	Floating Buttons: Неактивно по подразбиране
	Elementor Editor Events: Неактивно по подразбиране
	Условия за показване: Активно по подразбиране
	Form Submissions: Активно по подразбиране
	Меню: Неактивно по подразбиране
	Taxonomy Filter: Активно по подразбиране
	Търсене: Неактивно по подразбиране


== Log ==
	
Log: showing 20 of 302024-06-20 20:59:43 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.21.5',
  'to' => '3.22.1',
)]
2024-07-19 09:56:03 [info] elementor-pro::elementor_pro_updater Started 
2024-07-19 09:56:03 [info] Elementor Pro/Upgrades - _on_each_version Start  
2024-07-19 09:56:03 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2024-07-19 09:56:03 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.22.0',
  'to' => '3.23.0',
)]
2024-07-19 09:56:03 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.22.0',
  'to' => '3.23.0',
)]
2024-07-19 10:02:03 [info] elementor::elementor_updater Started 
2024-07-19 10:02:03 [info] Elementor/Upgrades - _on_each_version Start  
2024-07-19 10:02:03 [info] Elementor/Upgrades - _on_each_version Finished 
2024-07-19 10:02:03 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.22.1',
  'to' => '3.23.1',
)]
2024-08-07 14:03:46 [info] elementor-pro::elementor_pro_updater Started 
2024-08-07 14:03:46 [info] Elementor Pro/Upgrades - _on_each_version Start  
2024-08-07 14:03:46 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2024-08-07 14:03:46 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.23.0',
  'to' => '3.23.3',
)]
2024-08-07 14:03:46 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.23.0',
  'to' => '3.23.3',
)]
2024-08-07 14:03:55 [info] elementor::elementor_updater Started 
2024-08-07 14:03:55 [info] Elementor/Upgrades - _on_each_version Start  
2024-08-07 14:03:56 [info] Elementor/Upgrades - _on_each_version Finished 
2024-08-07 14:03:56 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.23.1',
  'to' => '3.23.4',
)]
2024-08-07 14:03:56 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.23.1',
  'to' => '3.23.4',
)]

PHP: showing 7 of 7PHP: 2024-05-18 02:20:15 [warning X 1][../wp-content/plugins/elementor/core/files/file-types/svg.php::161] simplexml_load_file(): I/O warning : failed to load external entity &quot;../wp-content/uploads/2024/05/logo-dream-apart-hotel.svg&quot; [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-05-18 02:21:54 [warning X 1][../wp-content/plugins/elementor/core/files/file-types/svg.php::161] simplexml_load_file(): I/O warning : failed to load external entity &quot;../wp-content/uploads/2024/05/logo-dream-apart-hotel-w.svg&quot; [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-05-18 02:22:42 [warning X 21][../wp-content/plugins/elementor/core/files/file-types/svg.php::161] simplexml_load_file(): I/O warning : failed to load external entity &quot;../wp-content/uploads/2024/05/logo-dream-apart-hotel-w-1.svg&quot; [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-06-20 20:54:59 [notice X 1][../wp-content/plugins/elementor/core/common/modules/connect/module.php::255] Trying to get property &#039;email&#039; of non-object [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-07-25 10:04:54 [notice X 1][../wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::182] Undefined index: editor_post_id [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-08-02 13:40:15 [notice X 1][../wp-content/plugins/elementor/includes/template-library/sources/local.php::779] ob_end_clean(): failed to delete buffer. No buffer to delete [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 6 of 6JS: 2024-06-21 10:33:16 [error X 5][../wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.22.1:3:634940] Cannot read properties of undefined (reading &#039;isEditable&#039;) 
JS: 2024-06-21 10:33:26 [error X 1][../wp-content/plugins/elementor/assets/js/editor-modules.min.js?ver=3.22.1:3:5491] r.get is not a function 
JS: 2024-06-21 13:12:32 [error X 7][../wp-includes/js/dist/vendor/react-dom.min.js?ver=18.2.0:10:91925] Cannot read properties of undefined (reading &#039;toString&#039;) 
JS: 2024-07-18 08:00:48 [error X 1][../wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.22.1:3:706805] this.model.isValidChild is not a function 
JS: 2024-07-24 13:40:40 [error X 2][../wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.23.1:3:831442] Cannot read properties of undefined (reading &#039;toLowerCase&#039;) 



== Elementor - Compatibility Tag ==
	
	Elementor Pro: Неуказана съвместимост

== Elementor Pro - Compatibility Tag ==

````

</details>

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by CecoSvidovski** [comment] 2024-08-07 12:03
I forgot to mention that Slides to Show is set to 1.

**Comment by nicholaszein** [comment] 2024-08-07 15:41
Hello @CecoSvidovski!

Thank you for your submission! 🙏 

### 🔗 🐞 This issue is a Duplicate of #23039 

Which is on the same subject. 

For this reason, I'm closing this thread and 🔃 **Merging** it with the original, so we can have all the discussions in one location, and deal with it more efficiently.

Feel free to continue the conversation there. 😉 

Kind regards

**Closed by nicholaszein** 2024-08-07 15:41 UTC
Labels: component/swiper, component/lightbox, duplicate
