### ISSUE TITLE
🔗 🚀 Feature Request: Multi location and styling of Google Map widget (Duplicate of #1319)

### ISSUE THREAD

**Issue by WebservAUS** [elementor/elementor#20506] opened 2022-11-24 02:12 UTC
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

Ability to add multiple locaitons/map markers.
Ability to style the map natively or by using Snazzy maps javascript

### Describe the solution you'd like

as above

### Describe alternatives you've considered

We now have to use a different plugin just for this one feature which I feel should not be necessary when using Elementor Pro

### Additional context

We are a web design company who have built over 100 sites with Elementor Pro over the last 9 years. It is surprising to see that this feature is not more developed by E or many other plugins.
Regards
Alberto Nilsson

**Comment by nicholaszein** [comment] 2022-11-24 16:31
Hello @WebservAUS,

thanks for submitting your feature request! 🙏 

Please understand that while we do welcome new feature requests, we can't promise they will be considered or added to our roadmap for the time being. Allow us to take some time to review your request. We will get back to you with feedback as soon as possible.

Best regards

**Comment by nicholaszein** [comment] 2022-11-27 07:05
Hey @WebservAUS!

Thank you for your submission! 🙏 

### 🔗 This issue is a Duplicate of #1319 

Which is on the same subject. 

For this reason, I'm closing this issue and 🔃 **Merging** it with the original, so we can have all the discussions in one location, and deal with it more efficiently.

Feel free to continue the conversation there. 😉 

### ✔️ Please, in the future, remember to check if there isn't an issue similar to yours already opened. 

Best regards,

Nick

**Closed by nicholaszein** 2022-11-27 07:05 UTC
Labels: request/enhancement, component/maps
