### ISSUE TITLE
Margin and Padding improvements

### ISSUE THREAD

**Issue by paauserrat** [elementor/elementor#14900] opened 2021-05-11 10:13 UTC
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Every new widget has a predefined default margin and padding option. It we try to change the padding, we won't be able to reset it to the default value as it's not 0, it's an internal value.

**Describe the solution you'd like**
My suggestion is to change the default visualization of the default value from a blank spot to something like "Default".

![image](https://user-images.githubusercontent.com/73240206/117799326-46cf8680-b252-11eb-95b0-210f52c5ebae.png)

**Comment by black-eye** [comment] 2021-05-11 21:31
Well, in fact there should be a placeholder showing a value in charge. At least for higher vieport settings (because they are totally in control of Elementor).

The problem is mentioned here: https://github.com/elementor/elementor/issues/3356 and somehow connected to https://github.com/elementor/elementor/issues/2219 and partially to https://github.com/elementor/elementor/issues/3319.

All the issues have in common the suggestions to make margin and padding control better. And, unfortunatelly, also the lack of interest from the developers (the oldest one is there since august 2017).

**Comment by avivu** [comment] 2021-05-19 05:25
I merged this issue with #3356, which is on the same subject, to deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!

**Closed by avivu** 2021-05-19 05:25 UTC
Labels: request/enhancement, type/ui/ux
