### ISSUE TITLE
Lightbox not working in Galeries

### ISSUE THREAD

**Issue by janfehlis** [elementor/elementor#7689] opened 2019-04-01 07:07 UTC
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

Lightbox is opening in single images in content, but not in galleries.
First, I thought it's a conflict with OcenWP lightbox, but after using the default WP theme and disabling all plugins not needed, the issue persists.

## Steps to reproduce

Here's a sample page:

https://www.veraenderungskraft.de/agile-coach-academy-berlin/

Click on location images undet the hero section.

This is the error I see inspecting the page:

`Uncaught ReferenceError: DialogsManager is not defined
    at t.getDialogsManager (frontend.min.js?ver=2.5.9:2)
    at child.initModal (frontend.min.js?ver=2.5.9:2)
    at child.self.(/agile-coach-academy-berlin/anonymous function) [as initModal] (https://www.veraenderungskraft.de/wp-content/plugins/elementor/assets/js/frontend-modules.js?ver=2.5.9:666:22)
    at child.getModal (frontend.min.js?ver=2.5.9:2)
    at child.self.(/agile-coach-academy-berlin/anonymous function) [as getModal] (https://www.veraenderungskraft.de/wp-content/plugins/elementor/assets/js/frontend-modules.js?ver=2.5.9:666:22)
    at child.showModal (frontend.min.js?ver=2.5.9:2)
    at child.self.(/agile-coach-academy-berlin/anonymous function) [as showModal] (https://www.veraenderungskraft.de/wp-content/plugins/elementor/assets/js/frontend-modules.js?ver=2.5.9:666:22)
    at child.openLink (frontend.min.js?ver=2.5.9:2)
    at HTMLAnchorElement.self.(/agile-coach-academy-berlin/anonymous function) (https://www.veraenderungskraft.de/wp-content/plugins/elementor/assets/js/frontend-modules.js?ver=2.5.9:666:22)
    at HTMLDocument.dispatch (jquery.js?ver=1.12.4:3)`

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

This is from the staging site, not the live site linked above. Error is the same though.
_I can share the login credentials for the staging site with you, if you contact me directly._

<details>
<summary>System Info</summary>
```
== Server Environment ==
	Operating System: Linux
	Software: nginx/1.15.6
	MySQL version: mariadb.org binary distribution v5.7.25
	PHP Version: 7.2.16-1+ubuntu16.04.1+deb.sury.org+1
	PHP Max Input Vars: 10000
	PHP Max Post Size: 2000M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.1.1
	Site URL: https://www.veraenderungskraft.de
	Home URL: https://www.veraenderungskraft.de
	WP Multisite: No
	Max Upload Size: 2 GB
	Memory limit: 512M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: de-DE
	Timezone: Europe/Berlin
	Debug Mode: Active

== Theme ==
	Name: Twenty Nineteen
	Version: 1.3
	Author: the WordPress team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: de_DE
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 2.5.11
		Author: Elementor.com

	Elementor Pro
		Version: 2.5.3
		Author: Elementor.com

	Temporary Login Without Password
		Version: 1.5.15
		Author: StoreApps


== Log ==
	: 
JS: showing 12 of 12JS: 2019-03-25 14:16:13 [error X 1][https://www.veraenderungskraft.de/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=STAGING-2.4.5:22:19954] View (cid: \"view913\") has already been destroyed and cannot be used. 
JS: 2019-03-25 14:31:45 [error X 1][https://www.veraenderungskraft.de/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=STAGING-2.4.5:22:19954] View (cid: \"view573\") has already been destroyed and cannot be used. 
JS: 2019-03-25 14:36:16 [error X 1][https://www.veraenderungskraft.de/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=STAGING-2.4.5:22:19954] View (cid: \"view834\") has already been destroyed and cannot be used. 
JS: 2019-03-25 14:58:31 [error X 1][https://www.veraenderungskraft.de/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=STAGING-2.4.5:22:19954] View (cid: \"view752\") has already been destroyed and cannot be used. 
JS: 2019-03-25 15:00:06 [error X 1][https://www.veraenderungskraft.de/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=STAGING-2.4.5:22:19954] View (cid: \"view745\") has already been destroyed and cannot be used. 
JS: 2019-03-25 15:06:50 [error X 1][https://www.veraenderungskraft.de/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=STAGING-2.4.5:22:19954] View (cid: \"view804\") has already been destroyed and cannot be used. 
JS: 2019-03-25 15:08:43 [error X 1][https://www.veraenderungskraft.de/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=STAGING-2.4.5:22:19954] View (cid: \"view631\") has already been destroyed and cannot be used. 
JS: 2019-03-25 15:11:02 [error X 1][https://www.veraenderungskraft.de/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=STAGING-2.4.5:22:19954] View (cid: \"view627\") has already been destroyed and cannot be used. 
JS: 2019-03-25 15:13:30 [error X 3][https://www.veraenderungskraft.de/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=STAGING-2.4.5:22:19954] View (cid: \"view634\") has already been destroyed and cannot be used. 
JS: 2019-03-25 15:16:15 [error X 1][https://www.veraenderungskraft.de/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=STAGING-2.4.5:22:19954] View (cid: \"view633\") has already been destroyed and cannot be used. 
JS: 2019-03-25 15:21:16 [error X 1][https://www.veraenderungskraft.de/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=STAGING-2.4.5:22:19954] View (cid: \"view656\") has already been destroyed and cannot be used. 
JS: 2019-04-01 04:57:09 [error X 1][https://www.veraenderungskraft.de/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=STAGING-2.4.5:22:19954] View (cid: \"view479\") has already been destroyed and cannot be used. 

Log: showing 20 of 312019-03-28 19:28:59 [info] Elementor Pro/Upgrades - _v_2_5_0_products Start  
2019-03-28 19:29:00 [info] Elementor Pro/Upgrades - _v_2_5_0_products Finished 
2019-03-28 19:29:00 [info] Elementor Pro/Upgrades - _v_2_5_0_sitemap Start  
2019-03-28 19:29:02 [info] Elementor Pro/Upgrades - _v_2_5_0_sitemap Finished 
2019-03-28 19:29:02 [info] Elementor Pro/Upgrades - _v_2_5_0_popup_border_radius Start  
2019-03-28 19:29:02 [info] Elementor Pro/Upgrades - _v_2_5_0_popup_border_radius Finished 
2019-03-28 19:29:02 [info] Elementor Pro/Upgrades - _v_2_5_0_form Start (2 of 8, 25%) 
2019-03-28 19:29:03 [info] Elementor Pro/Upgrades - _v_2_5_0_posts Start (2 of 2, 100%) 
2019-03-28 19:29:05 [info] Elementor Pro/Upgrades - _v_2_5_0_posts Finished 
2019-03-28 19:29:05 [info] Elementor Pro/Upgrades - _v_2_5_0_form Start (3 of 8, 38%) 
2019-03-28 19:29:07 [info] Elementor Pro/Upgrades - _v_2_5_0_form Start (4 of 8, 50%) 
2019-03-28 19:29:08 [info] Elementor Pro/Upgrades - _v_2_5_0_form Start (5 of 8, 63%) 
2019-03-28 19:29:09 [info] Elementor Pro/Upgrades - _v_2_5_0_form Start (6 of 8, 75%) 
2019-03-28 19:29:10 [info] Elementor Pro/Upgrades - _v_2_5_0_form Start (7 of 8, 88%) 
2019-04-01 08:54:47 [info] elementor-pro::elementor_pro_updater Started 
2019-04-01 08:54:47 [info] Elementor Pro/Upgrades - _v_2_5_0_form Start (8 of 8, 100%) 
2019-04-01 08:54:50 [info] Elementor Pro/Upgrades - _v_2_5_0_form Finished 
2019-04-01 08:54:50 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.4.8',
  'to' => '2.5.2',
)]
2019-04-01 08:55:28 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.5.10',
  'to' => '2.5.11',
)]
2019-04-01 08:55:53 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.5.2',
  'to' => '2.5.3',
)]
```
</details>

**Comment by shilo-ey** [comment] 2019-04-01 08:36
Hi @janfehlis 

Thanks for contacting us.

Unfortunately, we cannot reproduce your issue.
Please contact our support at support @elementor.com for guidance in resolving this issue and mention that you were directed by me and reference this issue.

Thanks.

**Closed by shilo-ey** 2019-04-01 08:36 UTC

**Comment by janfehlis** [comment] 2019-04-02 06:04
> Unfortunately, we cannot reproduce your issue.

At least any suggestions on what might causing this?

> Please contact our support at support @elementor.com for guidance in resolving this issue and mention that you were directed by me and reference this issue.

I've already contacted the support (ticket via my Elementor Pro account), before posting here. The support recommended posting the issue here. The support was not helpful at all. Not reading the details I provided, gave only basic feedback. _But I will try again..._

**Comment by brightappse** [comment] 2019-12-02 18:12
I have the same problem
