### ISSUE TITLE
Column background video option

### ISSUE THREAD

**Issue by nerussor** [elementor/elementor#9317] opened 2019-10-11 12:05 UTC
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
A 2 column, 50/50 section with a video widget on one side and a heading and text editor on the other. The video becomes too small and doesn't fill the entire column. Looks unprofessional.

**Describe the solution you'd like**
Having video backgrounds for columns would mean that the height of the section wouldn't cause the video to be too small if the content in other columns of the section increased the section height. It would also be nice to set the position and size, in terms of cover, auto and contain like with image backgrounds but I think I'm dreaming here.

**Describe alternatives you've considered**
In the end, I had to use a video widget and reduce the font size and amount of content in the other column to not cause the balance of the sections to appear broken. The alternative would be a classic (color or image), gradient or slideshow which isn't what I'm looking for.

**Additional context**
With video backgrounds being able to be added to sections, it doesn't seem that having the option for columns would be difficult to implement and more reliable for responsivity than using the video widget.

**Comment by shilo-ey** [comment] 2019-10-15 07:42
Duplicate of #5826

**Closed by shilo-ey** 2019-10-15 07:42 UTC

**Comment by get8bit** [comment] 2019-10-31 20:39
Need this feature also!

**Comment by marcelplanb** [comment] 2020-02-27 16:33
Me too. Would love to have the option to add a video background for a column.
