### ISSUE TITLE
🔗 Loop carousel width jumping and flickering (Duplicate of #23735)

### ISSUE THREAD

**Issue by spasauna** [elementor/elementor#28560] opened 2024-08-29 22:50 UTC
### Prerequisites

- [ ] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [X] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

The loop carousel has a strange loading behaviour, especially when loading the page for the first time or refreshing with clearing cache. It's some kind of flickering. 

The first loop item of the carousel seems to be getting 100% width in the beginning instead of the correct one immediately.

That results in some ugly jumping and flickering. 

I uploaded a video that shows it clearly while refreshing the page slowly but constantly: https://www.youtube.com/watch?v=NLgX8IsdDEI

Seems like I'm not the only one affected by this: https://www.reddit.com/r/elementor/comments/16y93ed/loop_carousel_issue

**This happens in the beginning...**

![1](https://github.com/user-attachments/assets/c725404b-33c8-47f7-8109-1ab2c0f84b31)

**And then results in this correctly.**

![2](https://github.com/user-attachments/assets/772e0883-f71a-46c0-a4ce-ba8f60c8c9d7)

### Steps to reproduce

1. Put a loop carousel on your site.
2. Create a loop template that only consists of an image inside a container. Width 100%.
3. Create a few posts with images or whatever you're using for your dynamic tag and save it.
4. Notice the width jump and flickering.

### Expected behavior

1. I expect it to not make a width jump and to not flicker.

### Isolating the problem

- [X] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [X] This bug happens with the Hello Elementor theme active.
- [X] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

<details>
<summary>Click to reveal</summary>

````txt


== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MySQL Community Server - GPL v8.0.37
	PHP Version: 8.3.10
	PHP Memory Limit: 512M
	PHP Max Input Vars: 4000
	PHP Max Post Size: 128M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.6.1
	Site URL: https://XXXXXXXXXXXXXXX.com
	Home URL: https://XXXXXXXXXXXXXXX.com
	WP Multisite: No
	Max Upload Size: 128 MB
	Memory limit: 40M
	Max Memory limit: 512M
	Permalink Structure: /%postname%/
	Language: en_US
	Timezone: Europe/Berlin
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 3.1.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en-US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36

== Active Plugins ==
	Advanced Custom Fields
		Version: 6.3.6
		Author: WP Engine

	Elementor
		Version: 3.23.4
		Author: Elementor.com

	Elementor Pro
		Version: 3.23.3
		Author: Elementor.com


== Features ==
	Custom Fonts: 5
	Custom Icons: 0

== Integrations ==
	


== Elementor Experiments ==
	Improved CSS Loading: Active
	Inline Font Icons: Active
	Additional Custom Breakpoints: Active
	Flexbox Container: Active
	Grid Container: Active
	Upgrade Swiper Library: Active
	Nested Elements Performance: Active by default
	Optimized Control Loading: Active
	Optimized Markup: Inactive by default
	Plugin Onboarding: Active by default
	Default to New Theme Builder: Active by default
	Header & Footer: Active by default
	Elementor Home Screen: Active by default
	Editor Top Bar: Inactive by default
	Build with AI: Inactive
	Landing Pages: Active
	Nested Elements: Active
	Lazy Load Background Images: Active
	Element Caching: Inactive by default
	Link In Bio: Inactive by default
	Floating Buttons: Active
	Elementor Editor Events: Inactive by default
	Display Conditions: Active by default
	Form Submissions: Active
	Menu: Active
	Taxonomy Filter: Active by default
	Search: Active


== Log ==
	


== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatible

== Elementor Pro - Compatibility Tag ==

````

</details>

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by dev12-byte** [comment] 2024-09-02 12:16
Yes that is sadly the way loop elements currently load with elementor. There are already multiple issues regarding this bug (Most merged into one):
[https://github.com/elementor/elementor/issues/23735#issue-1891263439]

This issue has not been resolved for over a year and it is quite a significant bug as it really affects UX. I don't know why elementor won't make this a priority. Especially as this is a "Pro" feature. 

But glad you reported it, maybe it just takes a few more people mentioning it ;)

**Comment by spasauna** [comment] 2024-09-02 18:25
> Yes that is sadly the way loop elements currently load with elementor. There are already multiple issues regarding this bug (Most merged into one): [https://github.com/[/issues/23735](https://github.com/elementor/elementor/issues/23735)#issue-1891263439]
> 
> This issue has not been resolved for over a year and it is quite a significant bug as it really affects UX. I don't know why elementor won't make this a priority. Especially as this is a "Pro" feature.
> 
> But glad you reported it, maybe it just takes a few more people mentioning it ;)

I agree, it looks extremely bad. It annoyed me so much that I bought an annual Unlimited Elements subscription to give their loop carousel a try. Guess what? It doesn't happen with their loop carousel.

By the way, the URL you provided seems to be wrong/broken.

I hope this gets fixed asap.

**Comment by nicholaszein** [comment] 2024-09-11 22:19
Hello @spasauna!

Thank you for your submission! 🙏 

### 🔗 🐞 This issue is a Duplicate of #23735 

Which is on the same subject. 

For this reason, I'm closing this thread and 🔃 **Merging** it with the original, so we can have all the discussions in one location, and deal with it more efficiently.

Feel free to continue the conversation there. 😉 

### 🔍 Please, in the future, remember to check if there isn't any thread similar to yours already opened. 

Kind regards

**Closed by nicholaszein** 2024-09-11 22:19 UTC
Labels: product/pro, component/swiper, type/performance, type/layout, widget/loop-builder/carousel, mod/e*, mod/c*, mod/d*, mod/b*
