### ISSUE TITLE
Add simple and quick way to duplicate a template

### ISSUE THREAD

**Issue by kneops** [elementor/elementor#8727] opened 2019-07-31 06:38 UTC
I had a section template and a page template. To copy them would mean to copy the contents of a template and paste it into a newly created template. I tried using the Duplicate Post plugin, but that gave me a page template after duplicating a section template, and a template under the My Templates tabs when duplicating a page template under my Theme Builder tab. So this is not the way to go.

I would very much like to see a button 'Create copy' under each template name that would create a duplicate and keep it where it is and also the kind or template that it is. So duplicating a section template would mean a new section template.

Ideal would be to get a popup or something where a user can immediately add the name for the new template, and choose what kind of template this should be, just like when creating a brand new template.

**Comment by shilo-ey** [comment] 2019-07-31 09:54
Duplicate of #8582

**Closed by shilo-ey** 2019-07-31 09:54 UTC
