### ISSUE TITLE
Cannot remove a specific section

### ISSUE THREAD

**Issue by vinterk** [elementor/elementor#13193] opened 2020-11-28 23:07 UTC
Hello,

I cannot remove a specific section on my site and it is getting frustrating. I am trying to remove this section: https://gyazo.com/f752cb78a98d1ae66358d46b260270bf

I cannot find anything that would allow me to remove it. This is the digital agency from Astra.

**Comment by Aviad-Herman** [comment] 2020-11-29 14:30
Hi,
This seems like a support ticket and not a bug or feature request so I'm going to close this issue.
But don't worry! I will still try to help you out, just make sure to tag me in your replies so I get an email about it.

There are a few possible causes for this:
1. If you are using Elementor Pro, this section might be a template of the site's footer. If this is the case, when you edit the site using Elementor you can hover over it and see a small yellow tab saying "edit footer" like in the picture I attached. If this is the case let me know and I'll help you solve the issue.
![Screen Shot 2020-11-29 at 16 19 29](https://user-images.githubusercontent.com/73067562/100544575-a3426a80-320b-11eb-9ac5-d6960f4134fc.png)

2. If you are using Astra, and this section is not an elementor widget, I'm sorry but I can't help you out.

3. Some more information that might help: are you editing the page using Elementor? Is this problem on all pages and posts or only some?

Keep me updated.

**Closed by Aviad-Herman** 2020-11-29 14:30 UTC
