### ISSUE TITLE
🔗 🚀 Feature Request: Add new Shape Dividers (Vertical/Horizontal) + More Controls (Duplicate of #2729, #9887) (Related to #19368)

### ISSUE THREAD

**Issue by Michaelgimii** [elementor/elementor#20522] opened 2022-11-24 19:28 UTC
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

Hi elementor developer.

The shape divider is one of the cool features in Elementor and I think it was abandoned after release. So it's great if you give it some attention and develop it. Please consider some suggestions to improve this feature.

### Describe the solution you'd like

**1- New shape divider :** square

2- Flip horizontal
3- Flip vertical
4- Overflow
5- Rotate
6- Horizontal align
7- Vertical align
8- position (top-right-Bottom-Left)

These items give us much better control over the shape divider. Bricks page builder has been very strong in this field. Please improve these if possible. Thanks

**Comment by nicholaszein** [comment] 2022-11-27 10:16
Hello @Michaelgimii!

Thank you for your submission! 🙏 

### 🔗 This issue is a Duplicate of #2729

Which is on the same subject. 

For this reason, I'm closing this issue and 🔃 **Merging** it with the original, so we can have all the discussions in one location, and deal with it more efficiently.

Feel free to continue the conversation there. 😉 

### ✔️ Please, in the future, remember to check if there isn't an issue similar to yours already opened. 

Best regards,

Nick

**Closed by nicholaszein** 2022-11-27 10:16 UTC
Labels: request/enhancement, type/design, type/layout, component/shape-divider
