### ISSUE TITLE
🔗 🚀 Feature Request: Some suggestions for developing google maps widget (Duplicate of #1319)

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#18718] opened 2022-05-23 16:45 UTC
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

hi elementor team!

If possible, please consider the following to develop this widget.

1- Add **Scrollwheel Zoom** feature > If this option is enabled, desktop users can use the mouse to zoom in or out on the map.
2- Ability to hide [+ - buttons](https://prnt.sc/sXjVJqzjhzle)
3- Add Fullscreen button https://prnt.sc/vOzsgFPkpi39
4- Ability to hide the full screen button
5- Ability to pin on the map : https://prnt.sc/n0flbWgCWUl2

The above items are implemented in the Jet elements plugin. It would be great if they were localized in elementor.
https://prnt.sc/5uCoPxuHyd5W
https://prnt.sc/NpaEvygVeyq4

### Describe the solution you'd like

Advanced Google Maps widget

**Comment by nicholaszein** [comment] 2022-11-27 07:04
Hello! 🙂

Thank you for your submission! 🙏 

### 🔗 This issue is a Duplicate of #1319.

Which is on the same subject. 

For this reason, I'm closing this issue and 🔃 **Merging** it with the original, so we can have all the discussions in one location, and deal with it more efficiently.

Feel free to continue the conversation there. 😉

**Closed by nicholaszein** 2022-11-27 07:04 UTC
Labels: request/enhancement, component/maps
