### ISSUE TITLE
🐞 Bug Report: Elementor 3.8.0 beta - Bug with displaying ACF meta fields on the Loop builder archive fronted (ED-8230)

### ISSUE THREAD

**Issue by strale73** [elementor/elementor#19898] opened 2022-09-23 14:27 UTC
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

The custom meta fields are not showing in Loop builder in the front end if they are added with ACF. I've tested with the JetEngine meta fields and they are displayed on the front end.

Here is the Loom video of the testing
https://www.loom.com/share/16bae13702b24d9eba7c00516a48f06d

### Steps to reproduce

1. Make a Loop template with the custom fields data with ACF
2. In the Archive add the Loop Grid widget
3. Check the Preview (working)
4. Check the front end (custom meta fields are not displaying).

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

[system-info-elementorbeta.iodicrain.com-23-09-2022.txt](https://github.com/elementor/elementor/files/9634503/system-info-elementorbeta.iodicrain.com-23-09-2022.txt)

**Comment by nicholaszein** [comment] 2022-09-23 19:36
Hello @strale73!

Thank you for reporting this issue! We will look into it! 🙏 

Best regards.

**Comment by mhason** [comment] 2022-09-29 12:35
I am having exactly the same issue, was trying to add an ACF image field to the loop. The image shows in the editor but not in the front.

**Comment by nicholaszein** [comment] 2022-10-03 18:35
Hey @strale73 and @mhason!

Here's great news! Support for this feature is now available in v3.8-Beta3.

Check it out! 👉 https://github.com/orgs/elementor/discussions/19854#discussioncomment-3789526

**Comment by strale73** [comment] 2022-10-05 06:57
@nicholaszein wow, this was fast. Thank you :)

**Comment by arielk** [comment] 2022-10-26 19:24
This issue has been resolved in Elementor v3.8.0-beta-3

Feel free to update

Thanks!

**Closed by arielk** 2022-10-26 19:24 UTC
Labels: bug, component/dynamic-tag, type/dynamic-content, component/acf, component/loop-builder, product/beta3.8

**Comment by DThBlom** [comment] 2022-11-02 12:56
I have the same problem with another post loop builder and Elementor Pro 3.8 version (non beta). I have the combination of elementor pro 3.8 +JetEngine 3.06 (Crocoblock) + ACF Pro 6.03. De ACF fields inside a postloop made with Jetengine are not shown since the Elementor Pro 3.8 update. When I reroll to 3.6 everything works fine again.

**Comment by hax1** [comment] 2022-11-03 16:32
same problem here. not working with 3.8 final version using ele custom loop.

**Comment by Iesmha** [comment] 2022-11-06 07:05
I have the same problem.

**Comment by acornavi** [comment] 2022-11-06 09:15
The problem is persistent even today. Loops do not show ACF meta data. Please publish a fix ASAP.

**Comment by nicholaszein** [comment] 2022-11-29 20:47
Hello @DThBlom, @hax1, @lesmha, and @acornavi!

We are aware that some users are having issues with ACF in some edge cases, and we are working on some additional fixes that might help.

In the meantime, your feedback is valuable. We would love to know your cases to make sure every particular case is accounted for.

Please submit a [Bug Report](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml) with your System Info and steps to reproduce so we can try to reproduce your issues individually.

Also, make sure this is only happening with Elementor features. If this is happening with features from 3rd party add-ons, like JetEngine's Listings, it is likely they haven't yet added compatibility with the latest version of Elementor and Elementor Pro.

Kind regards,

Nick

**Comment by opwolken** [comment] 2022-11-30 07:40
Hi Nick, with Elementor Pro 3.8.1 the problem was fixed for me.

**Comment by nicholaszein** [comment] 2022-11-30 11:33
Thanks for the feedback @opwolken / @DThBlom! 🙏

**Comment by hax1** [comment] 2022-11-30 13:14
@nicholaszein seems to be fixed in 3.8.1 for me as well.

**Comment by Bob2245** [comment] 2022-12-12 11:39
Am on 3.9.0 and custom color picker ACF fields are not working on any loop iterations past the first. See this page example: 
https://begradient.com/vacatures/
Posts have ACF color picker fields for text and background colors. Those values are applied to the background of the container and the text color of the Post Title and a Rich Text editor text. Works well on the first iteration in the loop, for any subsequent ones only the default value is loaded.
