### ISSUE TITLE
🔗 🚀 Feature Request: The ability to use multiple loop templates on a loop grid according to the post type (Duplicate of #20248)

### ISSUE THREAD

**Issue by heikkiwaan** [elementor/elementor#20465] opened 2022-11-20 18:42 UTC
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

I can't have more than one template in one loop grid

### Describe the solution you'd like

a code that allows me to do it as a custom functionality.

We have this already:
$query->set( 'post_type', [ 'custom-post-type1', 'custom-post-type2' ] );

But it does not allow me to select different loop template for different post types.
At least i don't know any way to do it.
![316174345_10160070802557319_5131206776931008529_n](https://user-images.githubusercontent.com/85135616/202919948-b10aebb8-29db-4d1b-aed5-2d8a0e49c2a0.jpg)

### Additional context

![316174345_10160070802557319_5131206776931008529_n](https://user-images.githubusercontent.com/85135616/202919977-9e68577c-c587-4c29-9433-89e6f8a73f97.jpg)

**Comment by nicholaszein** [comment] 2022-11-22 03:44
Hello @heikkiwaan!

Thank you for your submission! 🙏 

### 🔗 This issue is a Duplicate of #20248

Which is on the same subject. 

For this reason, I'm closing this issue and 🔃 **Merging** it with the original, so we can have all the discussions in one location, and deal with it more efficiently.

Feel free to continue the conversation there. 😉 

### 🔍 Please, in the future, remember to check if there isn't an issue similar to yours already opened. 

Best regards,

Nick

**Closed by nicholaszein** 2022-11-22 03:44 UTC
Labels: request/enhancement, component/loop-builder
