### ISSUE TITLE
✅ 🔗 🐘 🐞 Not PHP 8.2 compatible.  (Duplicate of #24246)

### ISSUE THREAD

**Issue by BackuPs** [elementor/elementor#24253] opened 2023-11-12 10:39 UTC
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Please fix php 8.2 compatibility issues in editor.php

Deprecated: Using ${var} in strings is deprecated, use {$var} on line 139

File core/editor/editor.php

Please use {$package} instead of ${package} 

![afbeelding](https://github.com/elementor/elementor/assets/6078370/cb7e15cf-097b-4120-badb-1fd0d3de32f4)

### Steps to reproduce

install php 8.2 and turn debug mode on.  You will see the warning messages in the admin area after login.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

Not needed. It is a php 8.2 bug which will be a fatal in php 9.0  

Please follow the php coding standards

**Comment by m1ga** [comment] 2023-11-12 14:10
duplicate of https://github.com/elementor/elementor/issues/24246

**Comment by bdthemes** [comment] 2023-11-13 09:42
More issues please fix them:

`Deprecated: Creation of dynamic property Elementor\Includes\Elements\Container::$logical_dimensions_inline_start is deprecated in \wp-content\plugins\elementor\includes\elements\container.php on line 42
Deprecated: Creation of dynamic property Elementor\Includes\Elements\Container::$logical_dimensions_inline_end is deprecated in \wp-content\plugins\elementor\includes\elements\container.php on line 43

`

**Closed** 2024-04-28 18:03 UTC
Labels: editor, status/merged, component/code, compatibility/php-8, solved, duplicate, mod/e*, mod/c*
