### ISSUE TITLE
🔗 🐞 Bug Report: Container Flex-grow not working in most cases (Duplicate of #1803)

### ISSUE THREAD

**Issue by perks98** [elementor/elementor#18358] opened 2022-04-05 10:00 UTC
### Description

As previously reported in #18303 that I don't think anyone picked up on, the flex-grow feature doesn't work. It only works on widgets with no set width, while if a width is added it adds a max-width also which makes the flex-grow not work. This also doesn't work on containers.

**Comment by s5t5n** [comment] 2022-04-06 19:41
+1

**Comment by nicholaszein** [comment] 2022-11-23 17:29
Hello @perks98!

Thank you for your submission! 🙏 

### 🔗 This issue is a Duplicate of #18303.

Which is on the same subject. 

I'm organizing the issues related to Containers, and to avoid confusion, I'm closing this issue and 🔃 **Merging** it with the original, so we can have all the discussions in one location, and deal with it more efficiently.

Feel free to continue the conversation there. 😉 

### ❌ Please, in the future, try to avoid creating duplicate issues. This actually makes it more complicated to track the issues. Continuing the conversation in one place saves you a lot of time.

Best regards,

Nick

**Closed by nicholaszein** 2022-11-23 17:29 UTC
Labels: bug, component/container
