### ISSUE TITLE
🔗 🚀 Feature Request: Touch Screen Support - such as Surface Pro (Duplicate of #482)

### ISSUE THREAD

**Issue by jaffa2** [elementor/elementor#4457] opened 2018-05-15 08:16 UTC
## Prerequisites

- [ ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
When using a machine like Surface Pro, often the keyboard is not attached , so relying purely on touch, yet in Elementor/Pro, it just does not support this way of working.  

**Describe the solution you'd like**
Ability to drag and drop using touch screen or pen control.

**Describe alternatives you've considered**
n/a

**Additional context**

**Comment by bainternet** [comment] 2018-05-15 09:34
Duplicate of #482

**Closed by bainternet** 2018-05-15 09:34 UTC
Labels: request/enhancement, type/responsive, type/ui/ux, component/editor, type/workflow, mod*
