### ISSUE TITLE
Search Custom Post Type Only

### ISSUE THREAD

**Issue by ex-avenger** [elementor/elementor#11844] opened 2020-07-12 07:28 UTC
Can you please add a feature where I can search only Custom Post Type?

Right now, wherever I add search icon on Elementor, it searches whole site. How do I make it to search only custom types?

**Comment by arielk** [comment] 2020-08-07 13:03
Duplicate of https://github.com/elementor/elementor/issues/9255

**Closed by arielk** 2020-08-07 13:03 UTC
