### ISSUE TITLE
Copy & Paste as well as dragging widgets Stopped Working since update

### ISSUE THREAD

**Issue by AndyMorley** [elementor/elementor#17274] opened 2021-12-22 09:39 UTC
Good morning, since updating to the latest versions of elementor & elementor pro on multiple sites i manage i can no longer copy and paste elements or drag items from the tool bar directly into the design view.

**Comment by shilo-ey** [comment] 2021-12-22 14:27
It seems like you have JS/PHP/PLUGIN/THEME conflict somewhere in your install.

Start by deactivating all other add-ons and plugins other than Elementor Core & Elementor Pro (if installed) - then proceed to edit and see if the issue has been resolved. You may need to switch to the default theme to rule out your theme as the cause of the conflict.

If the issue is resolved by following the above action the proceed to reactivate each plugin 1 at a time and check the editor till you find the one causing the conflict.

If plugin and theme deactivation didn't work - please try to deactivate all Experiments and activate them one by one until you identify the buggy experiment (Elementor > Settings > Experiments tab)

If the above process does not resolve the issue then check on Memory Limit set for your site together with PHP version - the easiest way to do that is by going to Elementor > System Info & scanning through it. Would also help if you post that info here for further assistance.

Thanks

**Closed by shilo-ey** 2021-12-22 14:27 UTC
