### ISSUE TITLE
✅ 🔗 ❌ Invalid Issue: Popup link fills the console  with Invalid selector warning (Duplicate of #29199)

### ISSUE THREAD

**Issue by Priyaqb** [elementor/elementor#29350] opened 2024-11-21 06:32 UTC
### Prerequisites

- [ ] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [X] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

Elementor Version : 3.25.9
Elementor Pro Version : 3.25.4
I am using EAE Popup. Console is filled with warning messages.
![popup-issue](https://github.com/user-attachments/assets/40de53e4-8b7e-4feb-aa17-693f7b149729)

### Steps to reproduce

1. Create a Popup Template and assign to page.
2. View browser console error.

### Expected behavior

Remove the warning from the console. 

### Isolating the problem

- [ ] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [X] This bug happens with the Hello Elementor theme active.
- [X] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

**[Moderation Edit: The contributor did not provide the Full Elementor System Info as required in the bug report form.]**

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by nicholaszein** [comment] 2024-11-25 03:52
Hello @Priyaqb!

Thank you for your submission! 🙏 

### 🔗 🐞 This issue is a Duplicate of #29199

Which is on the same subject. 

For this reason, I'm closing this thread and 🔃 **Merging** it with the original, so we can have all the discussions in one location, and deal with it more efficiently.

Feel free to continue the conversation there. 😉 

### 🔍 Please, in the future, remember to check if there isn't any thread similar to yours already opened. 

Kind regards

**Closed by nicholaszein** 2024-11-25 03:52 UTC
Labels: bug, product/pro, component/dynamic-tag, status/merged, popups, solved, compatibility/browser, mod*, duplicate, mod/i*, mod/v*, release/3.26

**Comment by nicholaszein** [comment] 2024-12-16 23:17
Hello there!

We have great news! 🙌 

### 📢 We're happy to announce that this issue was resolved with the release of Elementor and Elementor Pro v3.26.0! 🥳 

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
