### ISSUE TITLE
Button stylings are very buggy (3.0.5)

### ISSUE THREAD

**Issue by fabianenzensperger** [elementor/elementor#12354] opened 2020-08-31 13:57 UTC
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

Sometimes when I set a global font for a button, the background color resets itself. Every now and then it will destroy one or the other font on this page. Perhaps using the button in conjunction with global colors and fonts can fix the problems?

I use the latest version of elementor: Core 3.0.5 + Pro 3.0.2!
But: This has been the case since 3.0. I don't use any design plugins except Elementor!

Video about this: https://youtu.be/3ZGGfChCNtM

**Comment by rhino-corey** [comment] 2020-08-31 20:55
I'm having very similar issues and running the same versions of Elementor + Pro plugins that you stated.

I created a Global Font in Site Settings called `Button 1`, then applied it to the Typography property on the Global Buttons. It renders correctly in the Elementor Editor. If I then Update and View the front-end page, the CSS does not render a property for the typography change at all. It will only render the color, background-color, and padding values.

![image](https://user-images.githubusercontent.com/35272256/91767600-fd4a7a00-eba1-11ea-866d-a52b98183ecb.png)

I've regenerated the Elementor Css cache and flushed the site cache, but the font-family will not render on the front-end.

**Comment by d19dotca** [comment] 2020-09-01 02:55
Similar issues here too. One example of the behaviour for me... if my button already had a hover background colour, and I did a "reset style" on the button, the hover background colour would not clear. Seems the reset style option doesn't fully reset anymore, I've noticed this on buttons specifically.

**Comment by markc** [comment] 2020-09-02 05:00
Same latest versions for me and now 1/2 the page colors and button settings are completely messed up since updating to 3.0.5 + 3.0.2. Even on a new fresh rebuild of the site, I am seeing wild inconsistencies with global colors affecting, or not, various aspects of even newly built pages so it seems it's not just an upgrade from a previous version to the v3 series that causes problems for me. And it's not just the buttons either, body text color and font-family changed and also the nav font and color. Any fiddling with the global colors and fonts sometimes makes a temporary difference but then when reviewing the site in another browser it still all messed up, even after applying font/color settings per widget.

**Comment by tobias-sparks** [comment] 2020-09-02 06:58
+1

**Comment by fabianenzensperger** [comment] 2020-09-07 17:46
@shilo-ey @arielk Still a massive problem in 3.0.6!

**Comment by lucafagherazzi** [comment] 2020-09-10 09:42
Hi everyone, I upgraded to Elementor v3.0.7 and Elementor Pro v3.0.4 but the same global color issues remain: the text color remains the default while the button text color changes to white.

**Comment by arshish1612** [comment] 2020-09-11 14:19
- Theme Styles - Button - Very Buggy
- Elementor Pro 3.0.4
- Disable default colors and fonts is enabled.

Under Site Setting, Theme Styles, Button, if you change the typography settings, the button font changes however when you hover, the updated font does not reflect and resets back to a default font. Since the typography settings are independent of normal and hover, the expected behavior is that the changed typography should also affect the hover state.

**Comment by fabienlege** [comment] 2020-10-01 00:29
always an issue in elementor 3.0.11 + elementor pro 3.0.5 :(

**Comment by shilo-ey** [comment] 2020-10-01 06:55
Please contact our support at support @elementor.com for guidance in resolving this issue and mention that you were directed by me and reference this issue.

thanks.

**Comment by shilo-ey** [comment] 2020-10-01 06:58
Thanks for your inputs. 

Most of the related issues regarding misalignments in frontend/editor has been resolved. 

If you still see some issues, please contact our support at support @elementor.com and attach credentials for better troubleshooting in order to resolve this issue and mention that you were directed by me (@shilo-ey). Please reference this issue.

thanks.

**Comment by fabienlege** [comment] 2020-10-01 10:27
Thanks for your reply @shilo-ey.

Here a copy of mail I just send to support : 

My test was made with core, plugins and theme up to date. all plugins disabled (except Elementor & elementor pro) theme used is Helle Elementor.

The problem is the button doesn't use the background specified in global style. The default background color is always "accent color". you can't change it globally.If you want to use primary color as button background you need to set background color for all buttons one by one.

Here a video to explain the problem with core and extensions up to date : https://youtu.be/SUAG44JGeYM

The problem is the same with many widgets for colors or fonts. another exemple here with titles where global color and font is not applied :  https://youtu.be/GBJ8-UCW6uo

There is problems at least on this widgets : 
- Button (normal background) 
- Title ( text color, typography) 
- Text editor (text color, typography ) 
- Forms (Label color and typography, Field normal background color, field focus background color)

**Comment by shilo-ey** [comment] 2020-10-04 17:09
Thanks.

I'm marking this issue as closed.

Please follow the description [mentioned above](https://github.com/elementor/elementor/issues/12354#issuecomment-702041783) if you encounter this issue.

Feel free to reopen if the issue persists with proper steps to reproduce of course.

Thanks

**Closed by shilo-ey** 2020-10-04 17:09 UTC
