### ISSUE TITLE
Conditional form actions

### ISSUE THREAD

**Issue by Talco100** [elementor/elementor#9790] opened 2019-12-06 08:52 UTC
Today when a form is submitted - all actions run automatically.
BUT - many times we need only an action to run based on what the user did with the form.
i.e. 'subscribe to Getresponse' **ONLY IF** checkbox X was actually checked,
OR
Send a Webhook email only if field Y = Z.

**Comment by shilo-ey** [comment] 2019-12-08 07:53
Duplicate of #2638

**Closed by shilo-ey** 2019-12-08 07:53 UTC

**Comment by Talco100** [comment] 2019-12-08 08:33
Thanks Shilo
But as far as I understand - #2638 talk about the display of fields, and not about whether an action will be fired r not.
Did I get it right?

**Comment by dbjpanda** [comment] 2019-12-10 11:38
@shilo-ey I think you should read the original issue again and reopen it.
