### ISSUE TITLE
⛔ 🔗 🐞 Bug Report: Nav Menu Widget Typography settings are the same for Hover/Normal/Active (Duplicate of #3275)

### ISSUE THREAD

**Issue by tristanleboss** [elementor/elementor#7236] opened 2019-02-27 09:02 UTC
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

## Description

In the "Nav Menu Widget", the "Typography" settings are shared between the 3 modes: Hover/Normal/Active

The color of the text is not shared.

I think this is a bug because it's really usefull to be able to set "Text decoration" to "Underline" or to make the text appear bold for the "Hover" status, for example.

## Steps to reproduce

Add a "Nav Menu Widget" and change the typography in the "Style" tab. The change will apply for all hover/normal/active modes.

## Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a default WordPress theme active.
- [X] I can reproduce this bug consistently using the steps above.

## Environment

Elementor v2.4.7
Elementor Pro v2.4.5
WordPress 5.1

**Comment by bainternet** [comment] 2019-03-03 09:25
I merged this issue with  #3275 , which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!

**Closed by bainternet** 2019-03-03 09:25 UTC
Labels: product/pro, component/nav-menu, component/design, mod*

**Comment by uzimedia** [comment] 2020-04-17 22:00
It's Apr 2020 and still this simple change is not implemented - please update - it is a basic thing to do!

**Comment by nicholaszein** [comment] 2023-08-01 17:15
Hi, @tristanleboss,

Thank you for reaching out! 🙏 

### ⛔ After reviewing your report we concluded this is not a bug caused by Elementor. The feature you're referring to is not yet supported.

If you think this should be an Elementor feature, please submit a new [🚀 Feature Request](https://github.com/orgs/elementor/discussions/new?category=feature-request), and we will consider it in the future if there is enough demand (votes) from other users.

Kind regards
