### ISSUE TITLE
🔗 🐞 Bug Report: WooCommerce mini cart are empty after adding product to cart  (Duplicate of #21836)

### ISSUE THREAD

**Issue by meysam98** [elementor/elementor#21950] opened 2023-04-06 05:43 UTC
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

In Elementor Pro version 3.12, there is a problem that mini WooCommerce shopping cart is displayed as empty after adding a product by Ajax. Please check and fix this problem.

### Steps to reproduce

1- Install Elementor Pro version 3.12 or 3.12.1
2- Install and activate a template such as Storefront.
3- Add the WooCommerce shopping cart widget to the sidebar of the store page.
4- Add a product to the shopping cart on the same shop page, you will see that the shopping cart is empty and the page must be refreshed to display the content of the cart.
5- Even after refreshing the page, it is not possible to remove the product from the shopping cart.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

<details>
<summary>System Info</summary>

````txt


					
== Server Environment ==
	Operating System: WINNT
	Software: Apache/2.4.51 (Win64) OpenSSL/1.1.1l PHP/7.4.25
	MySQL version: mariadb.org binary distribution v10.4.21
	PHP Version: 7.4.25
	PHP Memory Limit: 512M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 40M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.2
	Site URL: http://127.0.0.1/dinad
	Home URL: http://127.0.0.1/dinad
	WP Multisite: No
	Max Upload Size: 40 مگابایت
	Memory limit: 40M
	Max Memory limit: 512M
	Permalink Structure: /blog/%postname%/
	Language: fa-IR
	Timezone: Asia/Tehran
	Admin Email: info@i-design.ir
	Debug Mode: Active

== Theme ==
	Name: DinaKala
	Version: 5.4.5
	Author: Meysam Hosseinkhani
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: fa_IR
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36

== Active Plugins ==
	AffiliateWP
		Version: 2.7.8
		Author: پرشین اسکریپت

	Awesome Support
		Version: 6.1.2
		Author: Awesome Support Team

	Checkout Field Editor for WooCommerce
		Version: 1.8.2
		Author: ThemeHigh

	Classic Editor
		Version: 1.6.3
		Author: WordPress Contributors

	Code Snippets
		Version: 3.3.0
		Author: Code Snippets Pro

	Contact Form 7
		Version: 5.7.5.1
		Author: Takayuki Miyoshi

	Dokan
		Version: 3.7.15
		Author: weDevs

	Duplicator
		Version: 1.5.3.1
		Author: Snap Creek

	Elementor
		Version: 3.12.1
		Author: Elementor.com

	Elementor Header & Footer Builder
		Version: 1.6.13
		Author: Brainstorm Force, Nikhil Chavan

	Elementor Pro
		Version: 3.12.1
		Author: پرشین اسکریپت

	One Click Demo Import
		Version: 3.1.2
		Author: OCDI

	Product Filter for WooCommerce
		Version: 8.3.0
		Author: XforWooCommerce

	Regenerate Thumbnails
		Version: 3.1.5
		Author: Alex Mills (Viper007Bond)

	TeraWallet
		Version: 1.4.7
		Author: StandaloneTech

	Variation Swatches for WooCommerce
		Version: 2.0.19
		Author: Emran Ahmed

	Widget Importer & Exporter
		Version: 1.6
		Author: ChurchThemes.com

	WooCommerce
		Version: 7.5.1
		Author: Automattic

	WooCommerce Compare List
		Version: 1.1.2
		Author: Themeisle

	YITH WooCommerce Compare
		Version: 2.24.1
		Author: YITH

	YITH WooCommerce Wishlist
		Version: 3.19.0
		Author: YITH

	دکان پرو|استارتر
		Version: 3.7.15
		Author: Redwp

	ووکامرس فارسی
		Version: 6.1.0
		Author: ووکامرس فارسی


== Features ==
	Custom Fonts: 0
	Custom Icons: 0

== Integrations ==
	
	woocommerce: Active


== آزمایشات عنصر ==
	بهینه سازی خروجی DOM: به صورت پیشفرض غیرفعال است
	بارگذاری دارایی بهبود یافته: به صورت پیشفرض غیرفعال است
	بارگذاری CSS بهبود یافته: به صورت پیشفرض غیرفعال است
	نمادهای فونت درون خطی: به صورت پیشفرض غیرفعال است
	بهبود دسترسی: به صورت پیشفرض فعال است
	نقاط قطع سفارشی اضافی (جهت رسپانسیو سایت به کار میره): به صورت پیشفرض فعال است
	admin_menu_rearrangement: به صورت پیشفرض غیرفعال است
	کانتینر فلکس باکس: به صورت پیشفرض غیرفعال است
	Upgrade Swiper Library: به صورت پیشفرض غیرفعال است
	Default to New Theme Builder: به صورت پیشفرض فعال است
	Editor Top Bar: به صورت پیشفرض غیرفعال است
	صفحات فرود: به صورت پیشفرض فعال است
	Nested Elements: به صورت پیشفرض غیرفعال است
	Lazy Load Background Images: به صورت پیشفرض غیرفعال است
	Page Transitions: به صورت پیشفرض فعال است
	Notes: به صورت پیشفرض فعال است
	Loop: به صورت پیشفرض فعال است
	Form Submissions: به صورت پیشفرض فعال است
	Scroll Snap: به صورت پیشفرض فعال است
	Menu: به صورت پیشفرض غیرفعال است


== گزارش ==
	
Log: showing 20 of 432023-04-03 20:14:46 [info] elementor-pro::elementor_pro_updater Started 
2023-04-03 20:14:46 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-04-03 20:14:46 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-04-03 20:14:46 [info] Elementor Pro/Upgrades - _v_3_7_2_woocommerce_rename_related_to_related_products Start  
2023-04-03 20:14:46 [info] Elementor Pro/Upgrades - _v_3_7_2_woocommerce_rename_related_to_related_products Finished 
2023-04-03 20:14:46 [info] Elementor Pro/Upgrades - _v_3_1_0_media_carousel Start  
2023-04-03 20:14:46 [info] Elementor Pro/Upgrades - _v_3_1_0_media_carousel Finished 
2023-04-03 20:14:46 [info] Elementor Pro/Upgrades - _v_3_1_0_reviews Start  
2023-04-03 20:14:46 [info] Elementor Pro/Upgrades - _v_3_1_0_reviews Finished 
2023-04-03 20:14:46 [info] Elementor Pro/Upgrades - _v_3_1_0_testimonial_carousel Start  
2023-04-03 20:14:46 [info] Elementor Pro/Upgrades - _v_3_1_0_testimonial_carousel Finished 
2023-04-03 20:14:46 [info] Elementor Pro/Upgrades - _v_3_1_0_slides Start  
2023-04-03 20:14:46 [info] Elementor Pro/Upgrades - _v_3_1_0_slides Finished 
2023-04-03 20:14:46 [info] Elementor Pro/Upgrades - _v_3_3_0_nav_menu_icon Start  
2023-04-03 20:14:46 [info] Elementor Pro/Upgrades - _v_3_3_0_nav_menu_icon Finished 
2023-04-03 20:14:46 [info] Elementor Pro/Upgrades - _v_3_3_0_recalc_usage_data Start  
2023-04-03 20:14:46 [info] Elementor Pro/Upgrades - _v_3_3_0_recalc_usage_data Finished 
2023-04-03 20:14:46 [info] Elementor Pro/Upgrades - _v_3_5_0_price_list Start  
2023-04-03 20:14:46 [info] Elementor Pro/Upgrades - _v_3_5_0_price_list Finished 
2023-04-03 20:14:46 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.0.6',
  'to' => '3.12.1',
)]



== المنتور - Compatibility Tag ==
	
	Elementor Header & Footer Builder: هیچ سازگاری تعیین نشده
	Elementor Pro: هیچ سازگاری تعیین نشده

== Elementor Pro - Compatibility Tag ==
	

				
````

</details>

**Comment by Squeezemind** [comment] 2023-04-07 09:13
Same of [https://github.com/elementor/elementor/issues/21836](https://github.com/elementor/elementor/issues/21836)

**Comment by Stas0238** [comment] 2023-04-07 09:38
@Squeezemind @meysam98 
"Don't worry" because Elementor has already answered that they will release an update "immediately" on next Sunday. 
https://github.com/elementor/elementor/issues/21836#issuecomment-1499120282 

Truly saying, the only solution for now is to revert back Elementor Pro version 3.11.7 or just disabled it.
"Thanks" them for thinking not about marketing aims first but about their "trusted" clients.

Sincerely to you guys and with really disappoint to Elementor devs,
One of us - @stas0238

**Comment by nicholaszein** [comment] 2023-04-07 19:45
Hello @meysam98 !

Thank you for your submission! 🙏 

### 🔗 🐞 This issue is a Duplicate of #21836

Which is on the same subject. 

For this reason, I'm closing this thread and 🔃 **Merging** it with the original, so we can have all the discussions in one location, and deal with it more efficiently.

Feel free to continue the conversation there. 😉 

### 🔍 Please, in the future, remember to check if there isn't any thread similar to yours already opened. 

Best regards,

Nick

**Closed by nicholaszein** 2023-04-07 19:45 UTC
Labels: bug, compatibility/3rd_party, product/pro, component/woocommerce, component/menu-cart

**Comment by nicholaszein** [comment] 2023-04-24 20:34
Hello, we have an update on this issue.

Please refer to [this comment](https://github.com/elementor/elementor/issues/21836#issuecomment-1520791070).

Kind regards
