### ISSUE TITLE
✅ 🔗 🚀 Feature Request: Allow to add widgets inside Slides (Duplicate of #2587)

### ISSUE THREAD

**Issue by gabrielserafim** [elementor/elementor#2445] opened 2017-09-20 14:56 UTC
I have a suggestion, of a new feature.
I do not know if I'm clear in my explanation, but you can do an element with the possibility of slide other elements, for example, slide text mixed with image, or slide an icon list, slide flip boxes, different content in each slide.

**Comment by lordloadalot** [comment] 2018-08-24 20:15
Wooo yeah! I've been missing this, too. Meanwhile U can use this: 
https://www.livemeshthemes.com/elementor-addons/generic-carousel/
It's included in the free version. It can contain shortodes ( means elementor tempolates )
Best Martin

**Comment by lordloadalot** [comment] 2018-08-24 20:42
@arielk  : does this feature have a chance to hit the screens ?


![slidercontent](https://user-images.githubusercontent.com/29510055/44606893-f1779080-a7ee-11e8-8e16-f20ad6862d06.jpg)

**Comment by gabrielserafim** [comment] 2018-09-14 13:40
This is exactly what i've looking for, you can simply slide a shortcode.

**Comment by Turanligil** [comment] 2018-11-29 11:19
+1

**Comment by lordloadalot** [comment] 2018-11-29 12:16
14 Months now. Hello Staff ? Anyone watching this ? Whre should I post feature requests ?

**Comment by Turanligil** [comment] 2018-12-14 06:52
+1

**Comment by pingram3541** [comment] 2019-01-08 08:13
Wrapped `$slide['description']` within `do_shortcode()` on line 1175 of /modules/slides/widgets/sides.php and works w/ exception of adding a pesky <p> tag around the shortcode.

`$slide_html .= '<div class="elementor-slide-description">' . do_shortcode( $slide['description'] ) . '</div>';`

**Comment by black-eye** [comment] 2019-01-25 00:07
+1

**Comment by gabrielserafim** [comment] 2019-01-31 12:34
> Wrapped `$slide['description']` within `do_shortcode()` on line 1175 of /modules/slides/widgets/sides.php and works w/ exception of adding a pesky "p" tag around the shortcode.
> 
> `$slide_html .= '<div class="elementor-slide-description">' . do_shortcode( $slide['description'] ) . '</div>';`

Thanks, it works very well!

**Comment by pingram3541** [comment] 2019-02-13 05:23
@gabrielserafim see #6874 for a non-invasive snippet that can be used in your theme's functions.php and never worry about updates to Elementor overwriting this modification

**Comment by simonclay** [comment] 2019-03-10 23:55
To have this would be as powerful, better in fact than a plugin like Revolution Slider.

+1!

**Comment by salvimateus** [comment] 2019-03-12 02:58
+1

**Comment by simonclay** [comment] 2019-03-12 14:20
There seems to be a free plugin to do this:

https://premiumaddons.com/carousel-widget-for-elementor-page-builder/

with a demo here: 

https://premiumaddons.com/docs/carousel-widget-tutorial/

I haven't checked it out yet.

**Comment by pgrafix** [comment] 2019-06-20 15:17
Whomever or however my post (#6349) was flagged as a duplicate of this post is wrong. What I was asking for in #6349 (and was also being detailed in #5504) is completely unrelated to this post and is a request to fix a glaring oversight by the devs in how the slides element handles responsive image sizing when a text overlay is present. Would like to see my post reopened and for a developer to address the issue - it's been 6 months already.

**Comment by pingram3541** [comment] 2019-07-06 15:08
@pgrafix yeah this has happened a few times with my tickets too, probably best just to create a new issue re-wording it, otherwise you can try reaching out to whoever closed the original and see if they will reopen it.

**Comment by nicholaszein** [comment] 2023-08-01 12:40
Hello there!

We have great news! 🙌 

### 📢 We're happy to announce that this feature was released with the new Nested Carousel introduced in Elementor Pro v3.14.0! 🥳 

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂

**Closed** 2023-08-01 12:41 UTC
Labels: request/enhancement, product/pro, status/merged, component/slides, solved_by_nested, 🚀 shipped, mod*
