### ISSUE TITLE
Font-performance with font-display

### ISSUE THREAD

**Issue by SweetSoul** [elementor/elementor#8925] opened 2019-08-28 15:06 UTC
I'm testing elementor in it's pro version.
I noticed that my website it's getting a low performance in some points, and one of them it's the fonts, so we need to leverage the font-display CSS feature to ensure text is user-visible while webfonts are loading.

There is an implementation of font-display in every font-face used in any website?

If it hasn't, i strongly suggest that you implement it. It would save some lives and improve SEO for customers...
It's a simple configuration, but better done by you guys directly in the template generator that you use...

Reference:
https://developers.google.com/web/updates/2016/02/font-display?utm_source=lighthouse&utm_medium=unknown

**Comment by bainternet** [comment] 2019-08-28 19:18
Thanks for the feedback,
Please follow guidelines for opening a new [feature request](https://github.com/pojome/elementor/issues/new?template=Feature_request.md), so we can help you better.
This report is missing key information: 

* Prerequisites.

**Comment by bainternet** [comment] 2019-08-28 19:19
Duplicate of #5993

**Closed by bainternet** 2019-08-28 19:19 UTC
