### ISSUE TITLE
🔗 🚀 Feature Request: The possibility of creating multiple shape dividers in one container (Duplicate of #19368) (Related to #2729)

### ISSUE THREAD

**Issue by Michaelgimii** [elementor/elementor#20524] opened 2022-11-24 19:37 UTC
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

Hi

It would be great if we could add multiple shape dividers in one container. This is a great feature that the bricks page builder currently offers. Please check this feature for plugin to Elementor if possible.

### Describe the solution you'd like

https://prnt.sc/lJEz-QCz94QA

**Comment by nicholaszein** [comment] 2022-11-27 10:22
### 🔗 This issue is a Duplicate of #19368.

Which is on the same subject. 

For this reason, I'm closing this issue and 🔃 **Merging** it with the original, so we can have all the discussions in one location, and deal with it more efficiently.

I'm also referencing issue #2729 here.

**Closed by nicholaszein** 2022-11-27 10:22 UTC
Labels: request/enhancement, type/design, component/shape-divider
