### ISSUE TITLE
remove_action( 'woocommerce_single_product_summary', 'woocommerce_template_single_add_to_cart', 30 );

### ISSUE THREAD

**Issue by xander-13** [elementor/elementor#9475] opened 2019-11-04 10:04 UTC
## Prerequisites

- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ x] The issue still exists against the latest stable version of Elementor.

## Description

I am trying to use a plugin to hide the woocommerce add to cart button however due to this function "remove_action( 'woocommerce_single_product_summary', 'woocommerce_template_single_add_to_cart', 30 );"

It is not working.

I need to know what function has been used in place of this.

I contact support as it feels like a support issue, however, I was told to post here.

Thank you for any help.

## Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [ ] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by bainternet** [comment] 2019-11-09 21:07
@xander-13 

can you please elaborate more,

`remove_action( 'woocommerce_single_product_summary', 'woocommerce_template_single_add_to_cart', 30 );` this seems like a hooked function removal and its hard to understand if you are trying to remove it or its interfering?

**Comment by xander-13** [comment] 2019-11-11 11:51
@bainternet 

Hi, thank you for looking.

Yes sorry if my post wasn't clear.

We are using a plug in to hide the woo-commerce checkout button. However, the plugin will not work as elementor has replaced this function with something else:
`remove_action( 'woocommerce_single_product_summary', 'woocommerce_template_single_add_to_cart', 30 ); t`

The plugin developer needs to know what it was replaced with.

Thank you so much for any help
Alex

**Comment by bainternet** [comment] 2019-11-16 22:18
@xander-13 

It's still not clear what function you are trying to remove, this hook `woocommerce_single_product_summary` runs on a single product page template and you say you want to remove the checkout button which is not on that page.

Elementor doesn't use the WC template hooks in order to place product elements on the product template, you simply Drag n` Drop the elements where you want.


Without clearly understanding what it is you want/need we can't really help here.
If you want you can contact your plugin developer and tell him to contact our support at support @elementor.com for guidance in resolving this issue and mention that you were directed by me and reference this issue.

thanks.

**Closed by bainternet** 2019-11-16 22:18 UTC
Labels: status/needs feedback

**Comment by nomadjimbob** [comment] 2020-01-12 12:57
I hit this issue as well with my own website with a plugin that I developed. Elementor uses its own code to write the single product page and therefore none of the WooCommerce hooks are called, such as "woocommerce_single_product_summary". Any plugins that use woocommerce hooks to replace/add content will not work with the Elementor single product template.

**Comment by jghaanstra** [comment] 2020-02-25 23:39
I just ran into the issue that Elementor removes the JSON-LD schema from WooCommerce on the single product page. This schema is very important for SEO purposes. This schema is added in WooCommerce through the hook `woocommerce_single_product_summary` which is removed by Elementor on the single product page. This is really really bad and I'd like to see a solution.

**Comment by gangesh** [comment] 2020-06-23 07:44
+1

**Comment by RashwanCodes** [comment] 2020-08-01 13:52
add the below code to your child theme function.php file and then add this shortcode to your template using elementor shortcode widget:
[do_hook hook='woocommerce_single_product_summary']

code at the end of you function.php file:
add_shortcode( 'do_hook', function( $atts = array(), $content = null, $tag = ''){
	if ( isset( $atts['hook'] ) ) {
		do_action( 'woocommerce_single_product_summary' );
	}
	return;
});

**Comment by wildmercury** [comment] 2020-09-14 10:31
I also have this issue on single product and similar on the product loop.

**Comment by pixelicous** [comment] 2020-09-23 19:49
@RashwanCodes that did the trick for me, where the shortcode is, i can see my functions.php changes like "remove_action" all of the sudden are working.
The problem is that now, none of my different changes in elementor show..

I couldn't understand why the issue was closed, i managed to understood what the author was trying to say.

without being able to manage those hooks, you cannot do more complex manipulation on some of the parts, reordering and styling is only a minor thing, i specifically tried to hide the price from variable products only, while showing them on shop page..
