### ISSUE TITLE
[Feature Request] - Post Widget / Image Position settings

### ISSUE THREAD

**Issue by cstibi** [elementor/elementor#3317] opened 2018-01-25 21:01 UTC
Post widget / Image position: it would be nice to set it separately for desktop/tablet/phone too.
When using 1 column, and image on the left / excerpt on the right on desktop. It will be nice to change image on top/excerpt below this on mobile.
![image](https://user-images.githubusercontent.com/17050000/35412041-34625422-021b-11e8-9b1c-0e2eb67ea1b6.png)

**Comment by ramiy** [comment] 2018-01-27 18:57
+1 for using a responsive control.

It could also be easier to use if will be a switcher control instead of select control.

![position](https://user-images.githubusercontent.com/576623/35475307-a92d9f84-03a4-11e8-90c4-fcdda9703d05.png)

**Comment by bainternet** [comment] 2018-01-28 15:40
@ramiy PR?

**Comment by ramiy** [comment] 2018-01-28 16:04
It's a Pro package...

**Comment by IDESIGNSTUDIO** [comment] 2018-02-07 10:22
+1

**Comment by cstibi** [comment] 2018-05-28 18:33
Hi Developers! Have you a solution idea to my problem? Image left and text right looks good on desktop but not on mobile.  On mobile we have to set image on top and text under it.

**Comment by JoeDarko** [comment] 2018-07-15 00:40
+1 Left position can't be used, because it goes crazy on mobile.

**Comment by messina614** [comment] 2018-08-16 15:32
I would love this as well!

**Comment by BogSow** [comment] 2018-10-04 06:54
+ 1

**Comment by andrewmaney** [comment] 2018-10-29 23:50
Big oversight not having an option for responsive control on post layouts with left aligned images :-(
Shall stick to using AnyWhere Elementor Pro to build themes.

**Comment by Turanligil** [comment] 2018-11-29 11:13
+1

**Comment by richward111** [comment] 2018-12-10 00:55
+1

**Comment by pelegred** [comment] 2019-01-09 14:34
(Bad) Workaround - Duplicate Post-List and use Advanced=>Responsive to change their display on different viewports

**Comment by simonclay** [comment] 2019-03-08 08:28
Hi all, my opinion is this is not a 'feature request', but a bug that needs fixing.

Posts Widget, Classic Skin, Image Left, breaks on mobile. 

It pushes the Excerpt container to a width of 0.

In mobile the image should switch to stack on top of the Excerpt.

**Comment by avitorio** [comment] 2019-03-11 17:07
Hi everyone,

Adding this css fixed it for me:

@media (max-width: 767px) {
    .elementor-posts article.elementor-post {
        display: block;
    }

    .elementor-post__thumbnail__link {
        margin-bottom: 20px;
    }
}

**Comment by simonclay** [comment] 2019-03-12 09:13
Thanks @avitorio that's a good fix for now.

**Comment by philrp** [comment] 2019-06-10 17:43
I can understand this might not be a priority, but the current situation goes very much against Elementor's basic design standards.

I'm with simonclay, this is a bug not a missing feature.

**Comment by SNowWoof** [comment] 2019-06-24 08:10
Thanks @avitorio that really helped me out!

**Comment by parfilov** [comment] 2019-09-03 15:25
+1 
Constantly encounter this issue ((

**Comment by voneff** [comment] 2019-10-25 12:29
Wow, this has been a known bug for almost two years? Because, as @simonclay said – this in a feature request to fix a bug, actually. The elements clearly should stack on smaller screens out of the box. Right now, if image is set to left, post title and teaser are pushed out of the mobile viewport creating this ridiculous amount of empty space below the thumbnail. Please fix this soon, @arielk!

**Comment by ashrafulkareem** [comment] 2019-11-22 03:23
> Hi everyone,
> 
> Adding this css fixed it for me:
> 
> ```
> @media (max-width: 767px) {
>     .elementor-posts article.elementor-post {
>         display: block;
>     }
> 
>     .elementor-post__thumbnail__link {
>         margin-bottom: 20px;
>     }
> }
> ```

worked for me, thanks a lot

**Comment by koiinteractive** [comment] 2019-11-26 18:36
Agree with everyone else -- this is certainly a bug, not a feature request. It's clearly a broken functionality, because it makes zero sense in practice. I'm surprised this has been unaddressed going on nearly two years...

In the same spirit, it would also be great if the toggles for desktop/tablet/mobile also applied to all the elements like excerpt, title, etc. Honestly -- it should just be an option for every element in the front-end.

**Comment by joshuamayo** [comment] 2020-01-19 05:10
Even the padding options don't offer responsive settings. Utterly ridiculous that this still isn't fixed after almost 2 years. Elementor, do you just assume that people will use 3rd party plugins and so it's not worth fixing such an insignificant oversight? Well, you're wrong. In an effort to keep my websites as lightweight as possible, I don't like using more plugins than I have to. Now, could I make this work with CSS and media queries? Yes. Should I have to resort to that? Definitely not.

**Comment by hengkies** [comment] 2020-01-30 06:50
I just encountered this issue, googled to find a solution and found this. 

Am surprised to see such a clear bug issue isn't fixed after 2 years. 

Thanks @avitorio for the workaround!

**Comment by jgajera** [comment] 2020-05-11 18:59
This bug needs to be fixed ASAP. How can the Elementor devs have missed this super simple CSS addition? Everyone's browsing on mobile these days, and the left/classic bug on mobile makes us all look extremely unprofessional. **Please include it in the next Pro update!!!**

**Comment by barkoig** [comment] 2020-06-07 18:59
I need it too.

**Comment by joehdevwp** [comment] 2020-07-15 21:59
+1
cant believe this isnt available yet. constantly an issue.

**Comment by ram108** [comment] 2020-09-30 17:35
The bug is not fixed for more then 2 years already.

**Comment by dwamgo** [comment] 2020-10-06 10:36
+1 It's absolutely neccesary

**Comment by ram108** [comment] 2020-10-06 11:44
@bainternet 
@arielk 
Please change the topic tag to #bug. Thus, maybe developers will pay attention to it.

**Comment by zunairah** [comment] 2020-11-17 02:37
@cstibi  it's 2020 and they still have this issue. I had a pretty tough time making my site look good on desktop, tablet, and mobile. What I did was to change my typography to the 'em' unit. Setting the width and ratio of my images separately on desktop, tablet, and mobile. It fixed the look on desktop and tablet but still had an ok look on mobile. Thankfully, I found this post and applied @avitorio code and it fixed the issue. But it needs to be fixed on elementor's side. They should look into their Posts widget and make the styling separate for each viewport.

**Comment by imsyedabdullah** [comment] 2020-11-25 23:53
+1

I don't know why they are delaying this. Its a crucial thing and this simple feature is requested for over 2 years.

**Comment by larzknoke** [comment] 2020-11-26 08:13
> Hi everyone,
> 
> Adding this css fixed it for me:
> 
> ```
> @media (max-width: 767px) {
>     .elementor-posts article.elementor-post {
>         display: block;
>     }
> 
>     .elementor-post__thumbnail__link {
>         margin-bottom: 20px;
>     }
> }
> ```

worked for me as well, but I can't understand why this bug is still in the code.

**Comment by ram108** [comment] 2020-11-29 20:11
I think new bug report should be opened to have this issue fixed, because the original title contains a feature request and not a bug report.

**Comment by Simpa77** [comment] 2021-02-16 14:51
+1 I can't understand why this bug is still exists. The mobile view should not break because of selected image position.

**Comment by potwal-5** [comment] 2021-03-05 21:16
I have the problem too. The additional CSS code from Avitorio works fine, but only in the editor. On the live site, it remains the same. Seems to be some kind of caching problem. But I do not use a caching tool. Any ideas?

**Comment by imsyedabdullah** [comment] 2021-03-06 09:14
@potwal-5 Probably Browser Caching. I can check if you provide URL :)

**Comment by potwal-5** [comment] 2021-03-06 09:45
It is not browser caching, but the sticky post. In the developer tools I can see that the class .sticky (position: relative) overrules the display: block in the class elementor-posts
The URL is www.textilgeschichte.ch

**Comment by potwal-5** [comment] 2021-03-06 12:32
To be more precise: there is another instruction for the class .elementor-posts: 
display: flex overrules display: block
![Screenshot 2021-03-06 at 13 32 04](https://user-images.githubusercontent.com/66249417/110206830-63c99100-7e80-11eb-8b88-d2119c6bb7eb.jpg)

**Comment by imsyedabdullah** [comment] 2021-03-06 17:33
@potwal-5 You can also use:
```
@media (max-width: 767px) {
    .elementor-posts .elementor-post {
        flex-direction: column;
    }
}
```
Though you can also add power to prevent it from being overwritten, but using flex column will probably be simpler.

**Comment by Toni-X** [comment] 2021-05-25 10:57
2 years later, a PRO widget fixable with 2 css lines is still broken

**Comment by XdarknidjaX** [comment] 2021-06-06 14:19
I used the CSS code from above but added the " !important " statement. If you want to add the CSS to ALL pages, you can click the 3 lines in the top left corner -> go to "site settings" -> "custom css". This can be done while editing a page in elementor. Paste the following CSS code:


/* CSS code to show text correctly on mobile in the "posts" widget in Elementor Pro */
@media (max-width: 767px) {
    .elementor-posts .elementor-post {
        display: block !important;
    }

    .elementor-post__thumbnail__link {
        margin-bottom: 20px;
    }
}

**Comment by XdarknidjaX** [comment] 2021-06-06 14:22
I used the CSS code from above but added the " !important " statement. If you want to add the CSS to ALL pages, you can click the 3 lines in the top left corner -> go to "site settings" -> "custom css". This can be done while editing a page in elementor. Paste the following CSS code:


```
/* CSS code to show text correctly on mobile in the "posts" widget in Elementor Pro */
@media (max-width: 767px) {
    .elementor-posts .elementor-post {
        display: block !important;
    }

    .elementor-post__thumbnail__link {
        margin-bottom: 20px;
    }
}
```

**Comment by inveress** [comment] 2021-06-10 08:30
Encountering this issue too. Why hasn't it been fixed after three years?

**Comment by simonclay** [comment] 2021-06-10 08:42
Unbelievable isn't it. This is a tiny issue, but I have fallen out of love, for this and many other reasons.

**Comment by wmsoftware-de** [comment] 2021-07-09 08:15
Did anyone at elementor look at the widget on a phone? I can not believe that the setting is not responsive and this is known for more than 3 years…

**Comment by imsyedabdullah** [comment] 2021-07-09 11:21
@bainternet can you please add "Bug" label to this? Its a bug not an enhancement request.

The fix is not much, just requires adding a few lines while people are waiting for soo long to see this resolved in Elementor.

**Comment by contrastxxx** [comment] 2021-07-14 08:54
I'm adding to this feature request, please

**Comment by ThorinEk** [comment] 2021-08-17 14:09
Just came across this long thread since I am having the same problem. How come only some of the elementor attributes can be set for each breakpoint?

**Comment by sermalefico** [comment] 2021-11-12 19:30
25 Jan 2018 ??? REally??!! OMFG

**Comment by welvisfernandes** [comment] 2021-12-01 04:55
> Hi everyone,
> 
> Adding this css fixed it for me:
> 
> ```
> @media (max-width: 767px) {
>     .elementor-posts article.elementor-post {
>         display: block;
>     }
> 
>     .elementor-post__thumbnail__link {
>         margin-bottom: 20px;
>     }
> }
> ```

Thanks!

**Comment by 79ho3ein** [comment] 2021-12-09 10:35
+1

**Comment by simonclay** [comment] 2022-05-12 10:23
4 years later, a hack is still needed to correct this #bug

**Comment by simonclay** [comment] 2022-05-12 10:25
@cstibi please change this post to a [bug] not a [Feature request] :)

**Comment by marketingspectrumNL** [comment] 2022-07-23 10:27
4 years and I still need to go here for a line of css...
I'm seriously curious how the Elementor meetings take place. 

Dev: "users say they want the pro post widget fixed, it takes about 20min to do so". 

DMU: "Who cares about our users? Let's put resources into additions nobody asks about, and make promises that we keep in alfa for how long we want. Ohw, and **do not** communicate or improve our product, especially not a widget which people pay for and nearly every website needs."

Something like that I imagine? I can't figure out why else this could still be unfixed in Elementor Pro 4 years later.

**Comment by 79ho3ein** [comment] 2022-07-23 10:44
@marketingspectrumNL 
Loop builder will be added soon and elementor will definitely take care of everything in it. I think nothing is left without a solution in the loop builder.

**Comment by ogio** [comment] 2022-08-14 10:44
Please, urgent need for this, so stupid feature to wait this much long

**Comment by parfilov** [comment] 2022-08-14 12:07
> Please, urgent need for this, so stupid feature to wait this much long

Bhaha. Urgent and Elementor are mutually exclusive concepts.

**Comment by nicholaszein** [comment] 2022-12-13 12:25
Hello everyone!

Thank you so much for your feedback and, most importantly, for being patient. 🙏 

At Elementor we do care about our user's feedback, but sometimes, even when it appears easy, introducing some features can have a negative impact on the Editor's performance and most importantly on backward compatibility. This is one of those cases.

But there is a silver lining. 🤓

We have finally released the Loop Builder, where you can now design your own Loop Item templates, and organize your elements with much more freedom using the FlexBox Container, in comparison with what you had before with the Posts widget.

For this reason, I'm closing this issue as solved. We are going to maintain the Posts widget for backward compatibility, but we have no plans to change how it works for the time being.

We encourage everyone to switch on the Loop Experiment that comes with Elementor 3.9 and start using the Loop Grid widget to build your own templates. You'll be able to define when your elements will be stacked on mobile without having to resource to custom CSS and use any element inside your Loop Grid as you please, including for example dynamic content. It's really powerful stuff!

We believe this is the best way forward, something that solves many of the pain points our users have been reporting to us over the years, and we are thrilled to see what you can achieve with the new flexibility of the Loop Grid widget. 💪

✔️ Feel free to check it out and update your plugin to the new version to take full advantage of this new feature.

Cheers 🥂

**Closed by nicholaszein** 2022-12-13 12:25 UTC
Labels: request/enhancement, type/responsive, product/pro, solved_by_loop
