### ISSUE TITLE
Please stop closing legit bug reports without fixes

### ISSUE THREAD

**Issue by danyj** [elementor/elementor#7574] opened 2019-03-21 12:33 UTC
I appreciate everything you do and know that is not easy to manage big community but brushing us off , closing issues without solutions and not waiting for developer replies  is not helping any of us. You got a product and we all have customers who will run in the same thing and we all have to come back here again.  We want to make your community bigger but please spend few more min and listen to what we are saying. 

This is legit report of a container issue 
https://github.com/elementor/elementor/issues/7484#issuecomment-474582768
and instead of labeled as bug it is closed and I am told not to use specific controls. 
None of it is in docs and cherry picking what control should or shouldn't be used is not how containers should work. 

This is also a valid bug  
https://github.com/elementor/elementor/issues/7566

setting control not to do anything on change makes the preview redundant and the element seems  nonfunctional. 

This has been closed since November https://github.com/elementor/elementor/issues/5914
and you have many of us showing you that it is a bug. 

There are many others but I am sure you understand what I mean. So can we please get in to actual dev talks instead brush off. Thnx.

**Comment by shilo-ey** [comment] 2019-03-24 16:33
Hi @danyj,
Whenever we are directed to bugs, we address them and fix them.

[**@danyj**](https://github.com/danyj) commented on [Mar 21, 2019, 2:33 PM GMT+2](https://github.com/elementor/elementor/issues/7574#issue-423706773 "2019-03-21T12:33:25Z - Replied by Github Reply Comments"):
> This is legit report of a container issue 
> https://github.com/elementor/elementor/issues/7484#issuecomment-474582768
> and instead of labeled as bug it is closed and I am told not to use specific controls. 
> None of it is in docs and cherry picking what control should or shouldn't be used is not how containers should work. 

This is not a bug. You are requesting a behavior that is not meant to be.
If you, however, decide to write a patch for it, we'll gladly include it after some code review.

> This is also a valid bug  
> https://github.com/elementor/elementor/issues/7566
> 
> setting control not to do anything on change makes the preview redundant and the element seems  nonfunctional. 

Again, not a bug, we took our time and efforts to explain a long and descriptive answer to your question, in this case - this is the behavior. 
If you have a question regarding this issue, please ask and we will do our best to provide an answer.

As for your issue, have you tried to change the render type to `ui`?

> This has been closed since November https://github.com/elementor/elementor/issues/5914
> and you have many of us showing you that it is a bug. 

This is actually a bug, as you can see in the new issue you've opened. 
This will be fixed soon. Thanks!
 
> There are many others but I am sure you understand what I mean. So can we please get in to actual dev talks instead brush off. Thnx.

As you can see, we check each report and give great weight to every bug/feature request. we sometimes prioritize bugs over feature requests, and sometimes we need to lay down the proper infrastructure before we develop new features.

We hope you see this eye to eye with us, hence we need to keep an organized repo. 

Thanks!

**Closed by shilo-ey** 2019-03-24 16:33 UTC
