### ISSUE TITLE
Custom posts widget for archive page - custom fields from PODS plugin

### ISSUE THREAD

**Issue by GertjanTanghe-KoomBanaBay** [elementor/elementor#8052] opened 2019-05-06 13:24 UTC
## Prerequisites

- [ ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
We would like to create custom post widget, that show custom fields from the PODS plugin. In this way you can create fully custom archive pages. The PODS plugin already works great with the single page templates, now only needs to work with the archive page

**Describe the solution you'd like**
Have to possibility to select custom fields created by the PODs plugin to be shown in the posts widget.

**Describe alternatives you've considered**
This option is available in the Toolset plugin, but this is yet another plugin to rely on.

**Additional context**
/

**Comment by bainternet** [comment] 2019-05-06 15:12
Duplicate of #4440

**Closed by bainternet** 2019-05-06 15:12 UTC

**Comment by nicholaszein** [comment] 2023-08-01 19:29
Hello there!

We have great news! 🙌 

### 📢 We're happy to announce the new Loop Builder released with Elementor Pro v3.8.0! 🥳 

With the new Loop Grid widget, you can customize your post listings with custom templates! 💪 
Drag & Drop widgets to create complex designs, fine-tune your Loop Grid layout, add alternate templates, and much more!

This is just the first phase. More customization is coming!

Check out the article here: https://elementor.com/help/loop-grid/

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
