### ISSUE TITLE
ACF Fields for Taxonomies

### ISSUE THREAD

**Issue by ludyamano** [elementor/elementor#5147] opened 2018-07-20 14:57 UTC
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

## Description

ACF Fields on Taxonomies Archives only works on Editor. On the front end the fields are not being displayed, only the fallback.

## Steps to reproduce
Create a template for a Taxonomy Archive and use an background image as Dynamic Field with an ACF field for that Term. On editor the image will be displayed, but on front-end it won't show up. This happens with all kinds of ACF Fields (URL, Image, Text, Gallery).

## Possible solution
I've added a few lines on ElementorPro\Modules\DynamicTags\ACF\Tags. On the get_value() method there is no validation for what king of page is that. 

If you change this:
```php
$field = get_field_object( $field_key );
```

for this:
```php
if(is_tax()){
	$term = get_queried_object();
	$field = get_field_object( $field_key, $term );
}else{
	$field = get_field_object( $field_key );
}
```

I'm not a developer, so i don't know if this is the best solution 🤷‍♂️ 

## Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a default WordPress theme active.
- [X] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by bentalgad** [comment] 2018-08-06 09:45
This is a major problem. please fix it.

**Comment by umarglobal** [comment] 2018-08-16 09:04
Hi I have replicated this bug too. But with me it does not show up on the editor and on the front end once saved. Can this be fixed asap?

**Comment by collindavis** [comment] 2018-08-24 06:44
+1 for this fix. I don't see an ACF key for Taxonomy fields. Using [acf] shortcode inside text editor for Taxonomy filed breaks Elementor altogether (e.g. [acf field="mycategory"] )

**Comment by Hauki75** [comment] 2018-10-01 16:30
+1 Works in editor but shows default text on the front end. Can you please fix this.

**Comment by Jaska** [comment] 2018-10-11 11:04
+1. Please fix this

**Comment by HQRaja** [comment] 2018-10-14 15:15
+1.
The OP even provided the code to fix this, so all that needs to be done is that code edit in the next release.

**Comment by AkhilAniyan** [comment] 2018-11-05 13:33
+1 I'm also facing the same issue! Please fix this asap.

**Comment by razvanwaterford** [comment] 2018-11-13 12:11
+2 for this (extra 1 for a buddy of mine)

**Comment by AkhilAniyan** [comment] 2018-11-14 12:57
Hi,

The provided fix from the OP is working fine for ACF Text, not for the image. Anyone knows a fix for image field?

Thanks!

**Comment by HQRaja** [comment] 2018-11-14 13:29
This should be prioritized...it has been open since July. ACF support isn't just for single posts or CPTs, but also for taxonomies. For several projects, we need to add and display custom fields in taxonomy archives, and without support for these fields when building taxonomy archives, the only option is to build a separate archive for each term of a taxonomy - not a scalable solution by any means.

**Comment by AkhilAniyan** [comment] 2018-11-14 13:36
> This should be prioritized...it has been open since July. ACF support isn't just for single posts or CPTs, but also for taxonomies. For several projects, we need to add and display custom fields (text and image fields, at the bare minimum) in taxonomy archives, and without support for these fields when building taxonomy archives, the only option is to build a separate archive for each term of a taxonomy - not a scalable solution by any means.

Correct. Me and my colleague still struggling to find a solution for this! Just because of this we are delaying on delivering a project. We have more than 50 archives. Creating 50 templates is the only solution. If we did like that, that will be the dumbest thing I ever did in WordPress!

And I still wonder why @bainternet  tagged this issue under "request/feature "...This is not a feature..This is a bug and Elementor Pro is claiming that it is working!

**Comment by razvanwaterford** [comment] 2018-11-14 13:42
Akhil, worked for me with image and ACF is set to return value "Image Array" instead of "Image URL". I've also had to replace is_tax() with is_category() in my case

**Comment by AkhilAniyan** [comment] 2018-11-14 13:59
> Akhil, worked for me with image and ACF is set to return value "Image Array" instead of "Image URL". I've also had to replace is_tax() with is_category() in my case

I'm already using Image Array. If I apply the fix recommended by OP, the image will display. The issue is, If I apply that fix, then ACF Image field used in the loop is disappearing.

For loop, I'm using https://wordpress.org/plugins/ele-custom-skin/

**Comment by AdeLijster** [comment] 2018-11-29 01:00
I'm testing out the JetEngine plugin and it seems to do the job...

**Comment by AkhilAniyan** [comment] 2018-11-29 05:19
> I'm testing out the JetEngine plugin and it seems to do the job...

@AdeLijster could you please explain how JetEngine resolves the issue?

**Comment by AkhilAniyan** [comment] 2018-11-29 07:01
Thanks a million, @AdeLijster That worked finally. JetEngine is super awesome!

**Comment by AdeLijster** [comment] 2018-11-29 11:03
Happy it works for you as well!

**Comment by AkhilAniyan** [comment] 2018-11-30 11:49
@AdeLijster Update: OP is suggesting a solution. That fixed the issue of "dynamic text". Dynamic Link is working without any issues (No need to apply any fix). The remaining issue was "dynamic image". The dynamic image is fixed since I'm using JetEngine to get the image instead of ACF. Hope this will help someone who is struggling like me.

Note: Still unable to use any third-party extras widgets to display dynamic fields due to this issue.

Hope elementor guys will fix in 2019 at least!

**Comment by sermalefico** [comment] 2018-12-14 14:40
this is important to fix please!!

**Comment by MPHood** [comment] 2018-12-18 22:36
+1

**Comment by prdsutte** [comment] 2018-12-21 16:09
the following fix works for me. 

in acf-text.php
`		if ( 'options' === $field_key ) {
			$field = get_field_object( $meta_key, $field_key );
		} else {
			/**
			* CHANGED 
			*/
						if(is_category()){
							$term = get_queried_object();
							$field = get_field_object( $field_key, $term );

						}
						elseif(is_tax()){
							$term = get_queried_object();
							$field = get_field_object( $field_key, $term );

						}
							else{
							$field = get_field_object( $field_key );
						}
						/**
						* END CHANGED 
						*/
		}`

and in acf-image.php
`if ( 'options' === $field_key ) {
				$field = get_field_object( $meta_key, $field_key );
			} else {

							/**
							* START CHANGED 
							*/
								if(is_category()){
									$term = get_queried_object();
									$field = get_field_object( $field_key, $term );

								}
								elseif(is_tax()){
									$term = get_queried_object();
									$field = get_field_object( $field_key, $term );

								}
									else{
									$field = get_field_object( $field_key );
								}
							}

							$switch_key = "";
							if(! empty( $field['save_format'])) {
									$switch_key = $field['save_format'];
							}
							if(! empty( $field['return_format'])) {
									$switch_key = $field['return_format'];
							}


							if ( $field && ! empty( $switch_key) ) {
								switch ($switch_key) {


											/**
											* END CHANGED 
											*/
					case 'object':`


maybe it will help you too;

**Comment by redpik** [comment] 2019-01-09 09:30
@ludyamano your solution works ! Thank you.

**Comment by sermalefico** [comment] 2019-01-09 14:32
Can put this merged in the new Elementor update?

**Comment by black-eye** [comment] 2019-01-30 19:15
+1

**Comment by peterkinvara** [comment] 2019-02-01 17:08
Still not fixed...ACF key doesn't show for taxonomy field

**Comment by peterhoffren** [comment] 2019-02-08 15:52
Same issue here, unable to pull dynamic content for Taxonomies :(

**Comment by peterkinvara** [comment] 2019-02-08 16:12
I've been on to Elementor, but their response is quite slow, and quite formal. I'm sure a lot of customers have had similar issues, so I would have thought they would have sorted this issue by now. 
if anyone has a workaround, it would be very welcome

**Comment by FairhopeCreative** [comment] 2019-02-14 17:32
Looks like the latest update removed this piece of code from the original post: 

````
$field = get_field_object( $field_key );
````

The function still doesn't work in a taxonomy no matter what you set the return value to. Anyone have any ideas on how to alter the code now?

**Comment by peterkinvara** [comment] 2019-02-14 17:47
Support at Elementor say "Taxonomy and Relationship fields are only supported as URL, as mentioned in the doc" -[https://imgur.com/uDfZAxd](url). [https://docs.elementor.com/article/381-elementor-integration-with-acf ](url) I can't even get that to work.

**Comment by sermalefico** [comment] 2019-02-14 18:32
the fix that publish @prdsutte  [on 21 Dec 2018](#issuecomment-449428833) is fine

**Comment by ucheng** [comment] 2019-02-27 09:57
I use beta testing version  2.5.0-beta3 , this problem is still not fixed.
I create an image field for post category, and use it as the page header background on the post category archive template. The image is not displayed both on the editor and the frontend.

**Comment by AkhilAniyan** [comment] 2019-03-09 06:48
> I use beta testing version 2.5.0-beta3 , this problem is still not fixed.
> I create an image field for post category, and use it as the page header background on the post category archive template. The image is not displayed both on the editor and the frontend.

Elementor won't spend the time to fix this bug. They only focus on normal users, so that they can make more money! I still wonder, why this issue is moved to "request/feature". This is not a feature request. This is something not working as expected! And the elementor support is one of the worst customer support I have ever seen!

**Comment by sermalefico** [comment] 2019-03-15 04:08
fixxxxxxxxx pleaseeeeee

**Comment by FairhopeCreative** [comment] 2019-03-15 14:19
It's weeks like this when swapping out the code above is a real pain in the ass. Why do they not just use the solution above to fix this issue?

**Comment by sermalefico** [comment] 2019-03-15 15:53
a solution has been proposed and they do not make anything of case to include this fix that is crucial at the time of making templates for taxonomies. opened this issue on 20 Jul 2018 and now we are at 15 March 2019.

**Comment by menathor** [comment] 2019-03-17 05:06
+1

**Comment by MPHood** [comment] 2019-03-17 12:18
++1

**Comment by sermalefico** [comment] 2019-03-18 19:31
Por favor añadir este parche a la nueva beta... estamos cansados de editar los archivos del core para que funcione en cada nueva actualización...  @bainternet

**Comment by Sim2K** [comment] 2019-04-08 01:59
This is not just an ACF problem, it's happening on PODS as well. Check issue #6937... I've explained it there as well.

**Comment by jgajera** [comment] 2019-04-12 23:26
+1 and Pro user - PLEASE fix this, Elementor!!!!

**Comment by Sim2K** [comment] 2019-04-22 10:50
Seriously Elementor, why is it taking so long to fix this issue!? What do we need to do to get this fixed, please. I am a paying customer, and I can't complete my project due to this. Can you please fix it.

**Comment by davidmanson** [comment] 2019-04-29 08:55
I've been having the same problem for some projets and here is my workaround : 

**Step 1 : I create a simple shortcode in the functions.php file :**
```
function get_taxonomy_field( $atts ) {
	$term = get_queried_object();
	return get_field( $atts['name'], $term );
}
add_shortcode( 'ele_get_field', 'get_taxonomy_field' );
```

**Step 2 : In elementor, instead of "ACF Field", I choose "Shortcode", and I use it like so :**
`[ele_get_field name="my_field_name"]`

Hope it helps !

**Comment by Os-Ha** [comment] 2019-05-04 06:08
@davidmanson thanks for this! I have tried your workaround but only a 2-digit number is displayed, not  the actual term name.. 

When I select a different taxonomy term, the 2 digits change accordingly. I feel like I am so close to finding a solution! 

Any idea what I might be doing wrong?

**Comment by davidmanson** [comment] 2019-05-04 08:21
> @davidmanson thanks for this! I have tried your workaround but only a 2-digit number is displayed, not the actual term name..
> 
> When I select a different taxonomy term, the 2 digits change accordingly. I feel like I am so close to finding a solution!
> 
> Any idea what I might be doing wrong?

I guess you just need to change the "Return Value" in the ACF configuration of the field.

**Comment by baymarketing** [comment] 2019-05-04 15:56
> I've been having the same problem for some projets and here is my workaround :
> 
> **Step 1 : I create a simple shortcode in the functions.php file :**
> 
> ```
> function get_taxonomy_field( $atts ) {
> 	$term = get_queried_object();
> 	return get_field( $atts['name'], $term );
> }
> add_shortcode( 'ele_get_field', 'get_taxonomy_field' );
> ```
> 
> **Step 2 : In elementor, instead of "ACF Field", I choose "Shortcode", and I use it like so :**
> `[ele_get_field name="my_field_name"]`
> 
> Hope it helps !

Hi @davidmanson 

I'm desperately trying to get this to work.

I've put the following inside a Code Snippet:

`function get_taxonomy_field( $atts ) {
	$term = get_queried_object();
	return get_field( $atts['name'], $term );
}
add_shortcode( 'ele_get_field', 'get_taxonomy_field' );`

Which is exactly how you've got it.

The name of one of the fields is preacher.

So I put this inside the Elementor shortcode:

`[ele_get_field name="preacher"]`

All it does is prints "Array".

Any ideas?

**Comment by davidmanson** [comment] 2019-05-05 06:50
@baymarketing same as @Os-Ha, I think you just need to change the "Return Value" in the ACF configuration of the field.

**Comment by javiercriado** [comment] 2019-05-11 00:49
Please add to core!

**Comment by wedodigital** [comment] 2019-05-17 07:34
Still no update? oh my gawd.  Please add it to the core! This is a major features in any custom website.

**Comment by peterkinvara** [comment] 2019-05-17 08:17
Why ignore all the requests from paying customers for a fix? Seems like a very poor response.

**Comment by maxjutras** [comment] 2019-05-17 15:27
+1000

**Comment by relima** [comment] 2019-05-28 13:42
I thought I was going crazy.. so the problem is with elementor... when is it going to be fixed?

**Comment by someguy9** [comment] 2019-05-28 13:43
@relima From what I can tell it looks like it'll be released in the next update

**Comment by MichaelDarko** [comment] 2019-05-29 01:35
Please fix this ASAP. It's a major problem for a lot of us.

**Comment by MichaelDarko** [comment] 2019-05-29 02:14
After Elementor announced extensive support of ACF i thought building complex websites with Elementor is now possible. After trying it, i immediately run into this crazy problem a i still can't build any reasonably complex website. 

How can such a major issue still not be fixed? Can't you see how many people's projects are stuck because of this? 

I understand that developers can sometimes miss somethig importnant, but why is it ignored for so long?

**Comment by barrychapman** [comment] 2019-06-03 03:35
This needs to be fixed ASAP

**Comment by relima** [comment] 2019-07-02 16:34
I have just installed 2.6.0 beta 2 and it is not there. Why did they say it had been merged?

**Comment by sermalefico** [comment] 2019-07-02 17:05
@relima the beta is not the pro version. The dynamic fields is for pro version.

**Comment by relima** [comment] 2019-07-02 17:10
@sermalefico thank you. I am also a pro user. Guess I will have to wait then.

**Comment by ayhanmalkoc** [comment] 2019-07-10 17:31
+1

**Comment by ktse312** [comment] 2019-07-16 07:29
Tested and problem solved in Elementor Pro 2.6.0 (Beta 3)

**Comment by shilo-ey** [comment] 2019-07-23 10:12
This feature has been added to Elementor Pro v2.6.0

Feel free to update

Thanks!

**Closed by shilo-ey** 2019-07-23 10:12 UTC
Labels: request/feature, status/merged

**Comment by redpik** [comment] 2019-07-23 10:15
1 year bug. never too late ;)
It's a good thing, thank you.

**Comment by dantnan** [comment] 2019-07-23 19:14
Just what I needed. Thanks!

**Comment by gpsathas** [comment] 2019-07-24 06:50
If I update the Elementor Pro to 2.6.0 it breaks my templates I created with JetEngine. It shows the ACF fields empty!

**Comment by dudaster** [comment] 2019-07-24 10:30
@gpsathas ask JetEngine to solve the problem.

**Comment by baymarketing** [comment] 2019-07-30 13:48
What am I missing? I still can't add an ACF tax field to an Elementor single template. It simply doesn't show as a Key when I choose ACF field.

**Comment by wedodigital** [comment] 2019-08-05 06:51
hi!

1 error not fix in this ACF Taxonomy problem. 

When you embed the template using shortcode that have ACF taxonomy background, the background wont show because the page where you embed the template is not consider as "Archive".

please fix this ASAP

**Comment by baymarketing** [comment] 2019-08-05 06:57
for what it's worth...

I asked someone from Elementor to take a look at a site where I wanted to implement ACF taxonomy functionality.

After checking, this is their reply:

The taxonomy field in ACF is classified as a relationship field, at the moment with Elementor these types of fields are only supported in URL's in Elementor, for reference see: Elementor Integration With ACF see "Custom ACF fields we support" section.

Relationship fields will be integrated in Elementor, however, there's no ETA at the moment. I believe you can create custom taxonomies in CPT UI which might be a good alternative for you.

**Comment by wedodigital** [comment] 2019-08-05 07:58
Hi Dev!

Heres how i fixed the taxonomy problem when its not embedded in archive page. 
Can you apply this on your next update?

`if ( 'options' === $field_key ) { $field = get_field_object( $meta_key, $field_key );
			} elseif( ! is_tax() || ! is_category() ) {
				$field = get_field_object( $field_key );
			} else {
				$field = get_field_object( $field_key, get_queried_object() );
			} `

**Comment by wedodigital** [comment] 2019-08-05 08:38
> What am I missing? I still can't add an ACF tax field to an Elementor single template. It simply doesn't show as a Key when I choose ACF field.

can you try my solution above? hope that helps

**Comment by marcofrasson** [comment] 2019-11-21 03:35
My God! Seriously this problem has not yet been solved?

Really can't catch a field of taxonomy on his single ???

@shilo-ey

**Comment by daniel-musteata** [comment] 2020-07-20 16:15
What is the point fo elementor if is not working ?

**Comment by reathh** [comment] 2020-12-10 21:38
Tried it with ACF and Elementor - does not work. Custom fields from taxonomies are not showed.

**Comment by EdwardBlack** [comment] 2021-01-31 22:38
> When you embed the template using shortcode that have ACF taxonomy background, the background wont show because the page where you embed the template is not consider as "Archive".

I've found this bug report in 2021... what @wedodigital is saying is true. I tried to create a Image field in the taxonomy "brand" to display a brand logo based on what brand an woocommerce product is tagged with. It does not work.

**Comment by HQRaja** [comment] 2021-06-15 14:34
@shilo-ey Why is this issue closed when it's still an issue and retrieving an ACF field of a taxonomy anywhere other than that taxonomy's archive page doesn't work?

**Comment by reathh** [comment] 2021-06-15 15:37
> @shilo-ey Why is this issue closed when it's still an issue and retrieving an ACF field of a taxonomy anywhere other than that taxonomy's archive page doesn't work?

I can confirm that retrieving ACF field doesn't work

**Comment by daxpd28** [comment] 2022-07-26 02:31
I'm using ACF and CPT UI currently with Elementor. Is this an Elementor issue or an issue with one of the plugins? Sounds like Elementor from the posts. Also sounded like switching to Jet Engine yielded better results. Is that the only fix?

**Comment by WDUK8** [comment] 2022-07-30 18:19
Hi, 

I have read this thread because I am also having the same problem.

I have an ACF field for a CPT that has categories.

I want to be able to show the categories that a particular post in the CPT is in.

In Elementor I try to add the ACF but cannot add the taxonomy as per the content of this thread.

I did try some suggested code above but that did not work.

I can create a 'Select' field, but then the category names show without links to the categories themselves.  Which is fairly pointless.

Does anyone know if there is a workaround for this?

Thanks in advance :-)

**Comment by daxpd28** [comment] 2022-07-31 01:03
Hi, see if this works for you. When you click the option for adding dynamic info, select "Post Terms" from there you should be able to select your taxonomy info.
![Screen Shot 2022-07-30 at 8 00 03 PM](https://user-images.githubusercontent.com/12687462/182005262-d6bf8546-d95e-434e-8fe4-733c9734ec69.png)

**Comment by WDUK8** [comment] 2022-07-31 16:22
Thank you @daxpd28 

I had already tried that but it did not work.  I shut everything down and tried again just now and it worked

Glad you reminded me :-)

**Comment by JohnPaquette** [comment] 2023-10-17 10:58
Not understanding why this is closed. It's still an issue, almost done with 2023 and it's still an issue. 

You simple cannot select custom post type taxonomies with the Post Terms dynamic field, well, actually you can, but only once. Once you save the template it breaks. That's the issue.

You can however select custom post type taxonomies using the Post Info widget. If you choose Terms, the taxonomies appear in the dropdown like they did in the Post Terms dynamic field before saving. This is clearly a bug.

**Comment by dorfkind** [comment] 2023-12-14 06:50
Will this ever be officially fixed? Having the same issue as everything else setup a taxonomy field in ACF and wan't to select it in the dynamic tags under ACF Field, however besides the textfield and textarea keys, taxnonomy fields are not showing up

**Comment by bentographics** [comment] 2024-02-17 01:00
+1 

We have the same issue. @Elementor please fix this asap, it's a standard feature to be able to associate fields with a taxonomy and output on the frontend!

Though, we were able to set it up with this work-around, at least for an [image] field for a taxonomy:
https://daveden.co.uk/tutorials/how-to-add-taxonomy-images-to-elementor-loop-grid/

Hope this helps someone!

**Comment by pitchpublications** [comment] 2024-04-27 13:24
I have the same issue why is this closed? :(
