### ISSUE TITLE
🔗 🚀 Feature Request: Improvements to Elementor's popup element (Duplicate of #6899)

### ISSUE THREAD

**Issue by steve-manes** [elementor/elementor#17178] opened 2021-12-14 04:47 UTC
## Prerequisites

- [x ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
One of the things I’ve loved about migrating a web site using an ancient theme to Elementor is that I can jettison a bunch of third-party plugins that are no longer needed because their core features are either part of Elementor or in a library of Elementor add-ons.

One plugin I would love to lose is Popup Maker. But there are two options we use in almost all of our call-to-action popups that’s missing in Elementor’s popup support. One is the ability to show a popup X times over Y days. For some things, like a popup for an upcoming fundraiser, we might show that popup once every five days but as the target date approaches we’ll change that to every two days, then at every login. Our sponsors actually pay for X popup impressions/day.

The second thing PM does that doesn’t appear to be in Elementor is that you can update an existing popup without having to create a new one.  You can do this by editing the popup and then changing the name of the control cookie.

**Describe the solution you'd like**
I'd like to see better temporal control of popup display, such as "display once to a user every X hours". The mechanics are simple: just set a timeout on a named cookie and it will regenerate itself after X hours. 

I'd also like to see it employ a cookie to make it easier for third parties without access to Elementor's Preview to test popups simply by deleting a named cookie in their browsers. This would also make it easier to update a popup without having create a new one: just have it write to a new named cookie. I haven't found a way to test a popup on a live site. This would be easy if the popup could be triggered by, for instance, deleting a named cookie.

I'd also like there to be a log of popup displays and, if possible, click-throughs. This is something that our sponsors request from us to make sure they're getting their money's worth.

I'd also like set a start time and expiry for the popup campaign so that we don't have a Christmas-themed popup still running on New Years. Even Popup Maker lacks this feature.

**Describe alternatives you've considered**
I don't really have any other than to continue using Popup Maker. But Popup Maker doesn't leverage Elementor's powerful editor so I find myself having to create a popup in Elementor then taking a screen shot for Popup Maker to display it as an image. Yuck.

**Additional context**

**Comment by nicholaszein** [comment] 2023-01-27 15:56
Hello @steve-manes!

Thank you for your submission! 🙏 

### 🔗 This issue is a Duplicate of #6899

Which is on the same subject. 

For this reason, I'm closing this issue and 🔃 **Merging** it with the original, so we can have all the discussions in one location, and deal with it more efficiently.

We are also beta-testing our new [Popup Advanced Rule for Date and Time range](https://github.com/elementor/elementor/discussions/21125), which covers part of what you're asking. Try the new beta version and let us know if it helps to manage popups better.

Feel free to continue the conversation there. 😉 

Best regards,

Nick

**Closed by nicholaszein** 2023-01-27 15:56 UTC
Labels: request/enhancement, component/popup, product/beta3.11
