### ISSUE TITLE
Bug  - Gradient colors are "invisible" V.3.5.4

### ISSUE THREAD

**Issue by AppsTotalSEOMarketing** [elementor/elementor#17616] opened 2022-01-28 18:28 UTC
Hello friends, wishing you well.

I believe i found a bug building a woocommerce site with elementor, i made some color adjustment to the site in elementor, save the page, the changes reflected in the frontend BUT when reload the editing page, the changes in the design like gradient colors are "invisible" until make some adjustment in elementor the changes magically reappear.

This only happen in the new version of elementor 3.5.4, i have two other sites with Version 3.2.5 and they don't have that problem.

I already uninstall the wordpress installation three times and change root directory, re install wordpress with new credentials, install only elementor from plugin wordpress repository, active and make a page test and i get again the error. Is there any way to fix this bug?

I appreciate a lot your help to solve this issue.
Kind regards.
3rnest  (Elementor PRO user, advanced web designer)

This is exactly the issue:

![01-make-changes](https://user-images.githubusercontent.com/80184829/151601488-c18a551d-cc4e-4794-9be2-18cf6451ffe0.jpg)

![02-after-reload](https://user-images.githubusercontent.com/80184829/151601503-f808c4b1-cbae-4921-ab07-9cc4ccb36c54.jpg)

![03-change-boxed](https://user-images.githubusercontent.com/80184829/151601523-08cff89b-f964-4b54-b63f-b2cd775b1e7a.jpg)

![04-changes-re-appear](https://user-images.githubusercontent.com/80184829/151601540-bb640410-a729-45c9-9df1-16ebf5d783a6.jpg)

![05-only-elementor-plugin](https://user-images.githubusercontent.com/80184829/151601564-653e7518-6151-4979-8a21-63abf66287bd.jpg)

**Comment by MichaelDarko** [comment] 2022-02-26 18:50
#16793

Almost 4 month old bug still not fixed.

**Comment by arielk** [comment] 2022-09-12 17:08
Duplicate of: https://github.com/elementor/elementor/issues/16793

**Closed by arielk** 2022-09-12 17:08 UTC
Labels: bug
