### ISSUE TITLE
🐞 Bug report: Column widgets space not working

### ISSUE THREAD

**Issue by DynWeb-John** [elementor/elementor#19393] opened 2022-08-09 00:17 UTC
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

I just updated to v3.7.0 and noticed that my header template had a spacing change with extra space occurring between widgets in a column. The spacing should have been 0. I did an inspect and the spacing between all widgets (excluding last) was set to 20px.
Checking the column widget showed the spacing should have been set to 0.
The fault occurs on the front end, but the backend appeared correctly.
Changing the value had no effect.
I eventually added custom css of selector .elementor-widgets {margin:0;} to correct the fault, but you should know this occurred as others will probably come across it soon too.

### Steps to reproduce

Use elementor v3.7.0
Have a website that has a Elementor pro header template with a column and 4 widgets in it.
Change the columns widgets space field to 0.
Check the front end and you will find the spacing set to 20px

NOTE: any value other than 0 works correctly.

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

[system-info-perfectcare.net.au-09-08-2022.txt](https://github.com/elementor/elementor/files/9285746/system-info-perfectcare.net.au-09-08-2022.txt)

**Comment by BSG-75** [comment] 2022-08-09 02:50
I am having a similar issues across all of my sites that upgraded to Elementor 3.7.0. The widget spacing under column settings is getting ignored if it's set to "0". If you set it to any other number like "1" the column reflects the changes. In the editor everything looks fine, but on the front end the default 20px of bottom margin is being applied:

This is what Elementor 3.7.0 is applying to the column spacing if the value is "0":

`.elementor-widget:not(:last-child) {
    margin-bottom: 20px;
}`

Rolling back to Elementor 3.6.8 removes the issue.

**Comment by vgstef** [comment] 2022-08-09 04:09
Same problem here with the new update. It breaks the front end widget spacing.

**Comment by stefanstromquist** [comment] 2022-08-09 14:31
Ditto. New update breaks previous implementation of front end widget spacing. It also seems different in editing mode (edit with elementor) and display mode.

**Comment by mbaierl** [comment] 2022-08-09 14:33
Same issue.

**Comment by motvey** [comment] 2022-08-09 19:24
Confirm. 

- 3.7.0. non Pro.
- You won't see the margin-bottom:20px in the Editor mode
- You will get margin-bottom:20px on the real page, despite the Advanced/Layout/Margin = 0,0,0,0 setting.

The only fix is cumbersome:
-  apply "no-margin-bot" class to all affected places.
`.no-margin-bot { margin-bottom: 0px !important }`

**Comment by portrayaloflife** [comment] 2022-08-09 23:24
Same issue here!

**Comment by minty-owen** [comment] 2022-08-11 10:12
Same problem here. This is really ugly right now. We have to launch a website tomorrow. I hope they wil fix this soon.

**Comment by univagwetzikon** [comment] 2022-08-11 13:02
Same problem... hope it will be fixed soon!

**Comment by ncasedk** [comment] 2022-08-12 06:46
Yep. Me too.
Changing it to 1px helps for the moment - at least most places that I've tested it.

**Comment by shilo-ey** [comment] 2022-08-14 08:33
This issue has been resolved in Elementor v3.7.1

Feel free to update

Thanks!

**Closed by shilo-ey** 2022-08-14 08:33 UTC
Labels: bug, component/editor

**Comment by NAROLLES** [comment] 2022-08-14 10:25
The same problem is not solved by the latest version for those who use the flex container

**Comment by mkiii333** [comment] 2022-08-15 12:16
> The same problem is not solved by the latest version for those who use the flex container

Following. Please fix it asap.

**Comment by mbaierl** [comment] 2022-08-16 10:21
The issue is not yet solved for Flexbox Containers. Still 10px padding.

**Comment by NAROLLES** [comment] 2022-08-16 11:04
> The same problem is not solved by the latest version for those who use the flex container

Hello
The solution concerning padding for flex containers like the rest is in the new function implemented in the site settings. Go to layout settings.

Perhaps it was necessary to inform the community of this new function; It would have avoided a lot of inconvenience
Thanks
