### ISSUE TITLE
🐞 Bug Report: Responsive Controls not working Perfectly from latest version (Duplicate of #19894)

### ISSUE THREAD

**Issue by bdkoder** [elementor/elementor#19938] opened 2022-09-28 11:27 UTC
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Here is the code that works well before the latest version. Basically, the problem comes from **selectors**. ( [https://prnt.sc/W_I9qzOo0N2Z](https://prnt.sc/W_I9qzOo0N2Z) )
The errors from here - {{badge_horizontal_offset_tablet.SIZE}}
It's not working now. Giving undefined and fatal errors - **badge_horizontal_offset_tablet_tablet**
The suffix comes with double **tablet_tablet**
**This should be single (tablet) badge_horizontal_offset_tablet**

```php
$this->add_responsive_control(
			'badge_rotate',
			[
				'label'   => esc_html__( 'Rotate', 'bdthemes-element-pack' ),
				'type'    => Controls_Manager::SLIDER,
				'default' => [
					'size' => 0,
				],
				'tablet_default' => [
					'size' => 0,
				],
				'mobile_default' => [
					'size' => 0,
				],
				'range' => [
					'px' => [
						'min'  => -360,
						'max'  => 360,
						'step' => 5,
					],
				],
				'selectors' => [
					'(desktop){{WRAPPER}} .bdt-ep-fancy-card-badge' => 'transform: translate({{badge_horizontal_offset.SIZE}}px, {{badge_vertical_offset.SIZE}}px) rotate({{SIZE}}deg);',
					'(tablet){{WRAPPER}} .bdt-ep-fancy-card-badge' => 'transform: translate({{badge_horizontal_offset_tablet.SIZE}}px, {{badge_vertical_offset_tablet.SIZE}}px) rotate({{SIZE}}deg);',
					'(mobile){{WRAPPER}} .bdt-ep-fancy-card-badge' => 'transform: translate({{badge_horizontal_offset_mobile.SIZE}}px, {{badge_vertical_offset_mobile.SIZE}}px) rotate({{SIZE}}deg);',
				],
			]
		);
```

### Steps to reproduce

The latest version gives these errors.
**Version 3.7.6 / 3.7.3/3.7.2 working well.**

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently using the steps above.

### System Info

Elementor latest version.

**Comment by nicholaszein** [comment] 2022-09-28 16:46
Hello @bdkoder!

Thank you for contacting us.

We are already aware of this issue, and a fix will be released in the upcoming patch version. Meanwhile, please [Rollback](https://elementor.com/help/rolling-back-to-a-previous-version-of-elementor/) Elementor to version 3.7.6.
You can use the built-in rollback feature or simply [download this file](https://downloads.wordpress.org/plugin/elementor.3.7.6.zip) and upload it as a plugin to your website. It will ask you if you want to replace Elementor v3.7.7 with v3.7.6. Just click to replace it and everything should be back to normal.

📋 This issue is a Duplicate of #19894, which is on the same subject. For this reason, I'm closing this issue and ↔️ Merging it with the original, so we can have all the discussion in one location, and deal with it more efficiently.

Please feel free to continue the conversation there. 😉

Best regards

**Closed by nicholaszein** 2022-09-28 16:46 UTC
Labels: bug, compatibility/3rd_party, type/responsive, type/developer-api

**Comment by udidol** [comment] 2022-09-29 06:42
Hi @bdkoder 
A very long-standing bug with responsive control selectors was fixed in the latest version. It did break something in existing implementations, which will be fixed in the next patch.

In the meantime, to fix your instance, you can just change:
```
'selectors' => [
	'(desktop){{WRAPPER}} .bdt-ep-fancy-card-badge' => 'transform: translate({{badge_horizontal_offset.SIZE}}px, {{badge_vertical_offset.SIZE}}px) rotate({{SIZE}}deg);',
	'(tablet){{WRAPPER}} .bdt-ep-fancy-card-badge' => 'transform: translate({{badge_horizontal_offset_tablet.SIZE}}px, {{badge_vertical_offset_tablet.SIZE}}px) rotate({{SIZE}}deg);',
	'(mobile){{WRAPPER}} .bdt-ep-fancy-card-badge' => 'transform: translate({{badge_horizontal_offset_mobile.SIZE}}px, {{badge_vertical_offset_mobile.SIZE}}px) rotate({{SIZE}}deg);',
],
```

To:
```
'selectors' => [
	'{{WRAPPER}} .bdt-ep-fancy-card-badge' => 'transform: translate({{badge_horizontal_offset.SIZE}}px, {{badge_vertical_offset.SIZE}}px) rotate({{SIZE}}deg);',
],
```

And it should work responsively out of the box now.
