### ISSUE TITLE
🔗 ❌ 🐞 Bug Report: Elementor Line Break Bug (Duplicate of #11560)

### ISSUE THREAD

**Issue by warioishere** [elementor/elementor#23440] opened 2023-08-16 13:53 UTC
https://github.com/elementor/elementor/issues/11560

### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

i would like to bring up this issue, its 2023 now and elementor BS ist still breaking all normally edited pages by skipping the line breaks

https://github.com/elementor/elementor/issues/11560

### Steps to reproduce

see old post

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

happens on almost any system

**Comment by nicholaszein** [comment] 2023-08-20 05:24
Hello @warioishere!

Thank you for your submission! 🙏 

### 🔗 🐞 This issue is a Duplicate of #11560 

Which is on the same subject. 

For this reason, I'm closing this thread and 🔃 **Merging** it with the original, so we can have all the discussions in one location, and deal with it more efficiently.

Feel free to continue the conversation there. 😉 

### 🔍 Please, in the future, remember to check if there isn't any thread similar to yours already opened. 

### ❌ While reviewing your report, we noticed it was missing some key pieces of information:

- 💾 **System info:** Please include the System Info report as outlined in our [guidelines](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml). 
   - Get your System Info from your WordPress `Dashboard` > `Elementor` > `System info` [learn how to copy it here](https://elementor.com/help/hare-my-system-info/). We can't accept issues without it.

#### ⚠️ As a gentle reminder, issues without it may need to be closed without troubleshooting. Providing this information upfront aligns with our guidelines, saves time, and ensures swift resolution. Thank you for understanding.

Kind regards

**Closed by nicholaszein** 2023-08-20 05:24 UTC
Labels: mod*, component/control/WYSIWYG, component/text-editor, compatibility/dependencies
