### ISSUE TITLE
🔗 🚀 Feature Request: Multiple or unlimited button themes

### ISSUE THREAD

**Issue by neps-in** [elementor/elementor#20301] opened 2022-11-07 07:52 UTC
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

It would be nice to have multiple button styles, let's say we have a button for light background and another button style for dark theme. So Currently there is only one button that can be styled, it would be nice if we have multiple button styles or buttons with multiple styles.

Thanks !
Napoleon

### Describe the solution you'd like

It would be nice to have multiple button styles, let's say we have a button for light background and another button style for dark theme. So Currently there is only one button that can be styled, it would be nice if we have multiple button styles or buttons with multiple styles.

Thanks !
Napoleon

### Describe alternatives you've considered

It would be nice to have multiple button styles, let's say we have a button for light background and another button style for dark theme. So Currently there is only one button that can be styled, it would be nice if we have multiple button styles or buttons with multiple styles.

Thanks !
Napoleon

### Additional context

It would be nice to have multiple button styles, let's say we have a button for light background and another button style for dark theme. So Currently there is only one button that can be styled, it would be nice if we have multiple button styles or buttons with multiple styles.

Thanks !
Napoleon

**Comment by nicholaszein** [comment] 2022-11-14 03:05
Hello @neps-in!

Thank you for your submission! 🙏 

### 🔗 This issue is a Duplicate of #19098

Which is on the same subject. 

For this reason, I'm closing this issue and 🔃 **Merging** it with the original, so we can have all the discussions in one location, and deal with it more efficiently.

Feel free to continue the conversation there. 😉 

### ✔️ Please, in the future, remember to check if there isn't an issue similar to yours already opened. 

Best regards,

Nick

**Closed by nicholaszein** 2022-11-14 03:05 UTC
Labels: request/enhancement, type/global-style, component/button
