### ISSUE TITLE
Make columns clickable

### ISSUE THREAD

**Issue by Grynn07** [elementor/elementor#10969] opened 2020-03-25 19:58 UTC
## Prerequisites

- [ x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Columns need to have the option to add links.

**Describe the solution you'd like**
There is a plugin "[Make Column Clickable Elementor](https://wordpress.org/plugins/make-column-clickable-elementor/)" that could easily be added to Elementor that would instantly solve this. 

**Describe alternatives you've considered**
I can keep installing this plugin, it just seems like functionality that could (and should) be easily added to the core of Elementor.

**Additional context**
Making it so columns are easily clickable would greatly improve user friendliness for Elementor web builders, and our site users.

[make-column-clickable-elementor.zip](https://github.com/elementor/elementor/files/4383209/make-column-clickable-elementor.zip)

**Comment by MichaelDarko** [comment] 2020-03-29 20:41
Being able to apply a link to whole section/column is absolutely essential in website building process.

This has been requested many times over the last 4 years. 

The only response from Elementor comes from 2017: _"We checked it recently again and unfortunately this option is not feasible using Elementor, so I close this issue for now."_

Since then there was no comment and every request gets closed and merged with the CLOSED(!) original request from 2016.

Your request will also be ingored and merged without any response. 

Elementor markets itself as the best page builder and then they tell us that adding a link to a section (first thing you learn in HTML) will not be possible.

Whatever the reason is, they should solve it. Other page builders have it, Webflow has it. It's not impossible. 

But I'm pretty sure something so essential like this will maybe come after 50 other "fancy" features that nobody was asking for.

**Comment by GBallzus** [comment] 2020-05-30 03:56
This suggestion/enhancement gets my vote.

**Comment by thomasch-easting** [comment] 2020-07-08 11:01
+1, quite surprised this is not possible

**Comment by bilal-najar** [comment] 2020-10-10 21:13
+1, there is a plugin that allows this but I believe it should be a native feature.

**Comment by koddajr** [comment] 2020-12-16 19:21
+1 why this isnt core yet??????

**Comment by Rayken** [comment] 2021-03-03 23:33
I posted a solution that doesn't involve CSS or javascript trickery here: https://github.com/elementor/elementor/issues/351#issuecomment-789732511

Please make sure you read the comment before using the code though.

**Comment by 79ho3ein** [comment] 2021-06-08 11:41
+1

**Comment by BrockwayProd** [comment] 2021-06-16 08:27
Why the f*** is this feature request only 2020 old ? i remember of one issue with the same title having way more comments and +1 that was way older than this one.

+1000 on this request, it is becoming a game a stupidly not listening to your users.

**Comment by GBallzus** [comment] 2021-07-06 04:59
Duplicate of #15423

**Comment by Rayken** [comment] 2021-08-17 08:28
As of right now, due to [a change in utils.php](https://github.com/elementor/elementor/commit/20c86435a22f0faa33548dd01840756455875c41#diff-a4c20b6d7391a224faf11e6161c80b408e2a0f5a71a92dc11b7eafe3cad83f94R26) made on the 9th of June 2021, this can be done without JavaScript trickery. [See this gist](https://gist.github.com/Rayken/468b9534c9d84a08efcbda5ac5e0e618) (please make sure you're not using any nested anchors within the column you want to make linkable).

If you want to know how and why this works, see https://github.com/elementor/elementor/issues/351#issuecomment-789732511 and https://github.com/elementor/elementor/issues/351#issuecomment-791418264 or read the notes in the gist.

**Comment by vgstef** [comment] 2021-08-20 19:48
I also come across this issue. I really need to set a link to a section. And it need to be a dynamic link.

**Comment by Camilo517** [comment] 2021-09-07 16:03
+1

**Comment by BrockwayProd** [comment] 2021-09-14 11:33
Holy f*** ! Years and years that we want this, and it's finally coming !
Maybe in 6 months, but it's coming ^^

**Comment by shilo-ey** [comment] 2021-10-31 11:11
Hi all,
I merged this issue with #351, which is earlier and on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!

**Closed by shilo-ey** 2021-10-31 11:11 UTC
Labels: request/feature, status/has_pr

**Comment by nicholaszein** [comment] 2022-11-16 05:09
Hello there!

We have great news! 🙌 

### 📢 We're happy to announce that you can now have clickable container with <ins>stable</ins> version of the Flexbox Container experiment released with Elementor **v3.8**! 🥳 

✔️ Please feel free to check it out and update your plugin to the new version!

Cheers 🥂
