### ISSUE TITLE
Unable to delete column's & sections

### ISSUE THREAD

**Issue by 0hmar** [elementor/elementor#12242] opened 2020-08-26 06:49 UTC
I've ran into an issue with Elementor builder.

When I create new pages or go to edit a page.
Adding new sections/columns result in not allowing me to fully delete or adjust widgets.

Issues i've experienced.

Moving a widget creates 1-2 duplicates of the widget and moves it to a completely random spot
Deleting widgets don't delete the widget until editor is refreshed and the column is still there along with another widget

For example in a column I had social icons & an image. Deleting the column would only remove the image but not the social icons and the column alone.

It'd still show in the navigation bar and couldn't delete through navigation bar as well.

I've tried rolling back to previous versions of elementor but still broken as well.

**Comment by 15101570** [comment] 2020-08-26 07:29
Same issue

**Comment by kskonovalov** [comment] 2020-08-26 08:07
Same issue.
Quick steps to reproduce:
1. add section
2. add inner section
3. click on 'delete' of inner section

Error in console 'common.min.js?ver=3.0.1:2 TypeError: Cannot set property children of #<Container> which has only a getter'

**Comment by HorstKaufmann** [comment] 2020-08-26 08:58
Using Elementor 3.0.1.

Many actions related to blocks do not work.

Delete-Command from right click menu of a text-element ...
- element remains still there and text style changes to default

Duplicate-Command from right click of a text-element ...
- creates duplicate, seams to be correct

moving text-element to an other column ...
- element is moved, but duplicates in target position

colums can not be deleted

**Comment by shilo-ey** [comment] 2020-08-26 09:45
Please try to go to Elementor > Settings > Advanced tab > Optimized DOM and change the value to "Disabled" and let us know if this resolved the issue.

Thanks

**Comment by aureliePrd** [comment] 2020-08-26 09:51
@shilo-ey, nop, the issue is still here

**Comment by HorstKaufmann** [comment] 2020-08-26 09:53
same issue:
the issue is still here after 
Elementor > Settings > Advanced tab > Optimized DOM and change the value to "Disabled"

**Comment by kskonovalov** [comment] 2020-08-26 10:06
Tried all: default, disabled, enabled,- same issue with columns removing

**Comment by HorstKaufmann** [comment] 2020-08-26 17:20
3.0.2 seems to work correct - if I create a new page.

Thanks

**Comment by 0hmar** [comment] 2020-08-26 17:32
Still having the issue even with 3.0.2 in terms of removing columns. Also changing a page from Default to Elementor Canvas no longer live updates. Instead it shows after updating & refreshing. Tried method of disabling Optimized DOM and still same outcomes. 

Running into a lot of the same issues @HorstKaufmann has in terms of

> Many actions related to blocks do not work.
> 
> Delete-Command from right click menu of a text-element ...
> 
> element remains still there and text style changes to default
> Duplicate-Command from right click of a text-element ...
> 
> creates duplicate, seams to be correct
> moving text-element to an other column ...
> 
> element is moved, but duplicates in target position
> colums can not be deleted

**Comment by HorstKaufmann** [comment] 2020-08-26 17:38
sorry, meantime I see same issues with 3.0.2:

- Block: paste and copy style does'nt work
- delete a block changes style but does not delete it

**Comment by 0hmar** [comment] 2020-08-26 17:41
> sorry, meantime I see same issues with 3.0.2:
> 
> * Block: paste and copy style does'nt work
> * delete a block changes style but does not delete it

Yeah, seems to be the same for me in 3.0.2. I'm glad I'm not the only one running into these issues because I honestly thought I broke my site haha

**Comment by sermalefico** [comment] 2020-08-26 22:04
Same issues. with 3.0.2

For delete section or colums takes 2 or 3 clicks and when drag columns all is messed.

On delete column or section

`
common.min.js?ver=3.0.2:2 TypeError: Cannot set property children of #<Container> which has only a getter
    at i.<anonymous> (editor.min.js?ver=3.0.2:2)
    at p (load-scripts.php?c=1&load[chunk_0]=jquery,underscore,backbone,jquery-ui-core,jquery-ui-widget,jquery-ui-mouse,jquery-ui-draggable,wp-api-request,shortcode,utils,wp&load[chunk_1]=-util,wp-backbone,media-models,moxiejs,plupload,wp-plupload,jquery-ui-sortable&ver=5.5:10)
    at f (load-scripts.php?c=1&load[chunk_0]=jquery,underscore,backbone,jquery-ui-core,jquery-ui-widget,jquery-ui-mouse,jquery-ui-draggable,wp-api-request,shortcode,utils,wp&load[chunk_1]=-util,wp-backbone,media-models,moxiejs,plupload,wp-plupload,jquery-ui-sortable&ver=5.5:10)
    at l (load-scripts.php?c=1&load[chunk_0]=jquery,underscore,backbone,jquery-ui-core,jquery-ui-widget,jquery-ui-mouse,jquery-ui-draggable,wp-api-request,shortcode,utils,wp&load[chunk_1]=-util,wp-backbone,media-models,moxiejs,plupload,wp-plupload,jquery-ui-sortable&ver=5.5:10)
    at i.n.trigger (load-scripts.php?c=1&load[chunk_0]=jquery,underscore,backbone,jquery-ui-core,jquery-ui-widget,jquery-ui-mouse,jquery-ui-draggable,wp-api-request,shortcode,utils,wp&load[chunk_1]=-util,wp-backbone,media-models,moxiejs,plupload,wp-plupload,jquery-ui-sortable&ver=5.5:10)
    at Object._triggerMethod (backbone.marionette.min.js?ver=2.4.5:22)
    at i.triggerMethod (backbone.marionette.min.js?ver=2.4.5:22)
    at i.destroy (backbone.marionette.min.js?ver=2.4.5:22)
    at i.destroy (backbone.marionette.min.js?ver=2.4.5:22)
    at i.removeChildView (backbone.marionette.min.js?ver=2.4.5:22)
consoleError @ common.min.js?ver=3.0.2:2
onCatchApply @ editor-document.min.js?ver=3.0.2:2
onCatchApply @ editor-document.min.js?ver=3.0.2:2
run @ editor-document.min.js?ver=3.0.2:2
forEach.n.<computed> @ editor-document.min.js?ver=3.0.2:2
run @ common.min.js?ver=3.0.2:2
run @ common.min.js?ver=3.0.2:2
callback @ editor.min.js?ver=3.0.2:2
runAction @ editor.min.js?ver=3.0.2:2
e.each.r.<computed> @ common-modules.min.js?ver=3.0.2:2
(anonymous) @ editor.min.js?ver=3.0.2:2
dispatch @ load-scripts.php?c=1&load[chunk_0]=jquery,underscore,backbone,jquery-ui-core,jquery-ui-widget,jquery-ui-mouse,jquery-ui-draggable,wp-api-request,shortcode,utils,wp&load[chunk_1]=-util,wp-backbone,media-models,moxiejs,plupload,wp-plupload,jquery-ui-sortable&ver=5.5:3
r.handle @ load-scripts.php?c=1&load[chunk_0]=jquery,underscore,backbone,jquery-ui-core,jquery-ui-widget,jquery-ui-mouse,jquery-ui-draggable,wp-api-request,shortcode,utils,wp&load[chunk_1]=-util,wp-backbone,media-models,moxiejs,plupload,wp-plupload,jquery-ui-sortable&ver=5.5:3
common.min.js?ver=3.0.2:2 TypeError: Cannot read property 'parent' of undefined
    at editor-document.min.js?ver=3.0.2:2
    at Array.forEach (<anonymous>)
    at SectionsColumns.apply (editor-document.min.js?ver=3.0.2:2)
    at SectionsColumns.run (editor-document.min.js?ver=3.0.2:2)
    at Data.runCallback (common.min.js?ver=3.0.2:2)
    at Data.runCallbacks (common.min.js?ver=3.0.2:2)
    at Data.run (common.min.js?ver=3.0.2:2)
    at Hooks.run (common.min.js?ver=3.0.2:2)
    at Hooks.runDataAfter (common.min.js?ver=3.0.2:2)
    at Delete.onAfterApply (editor-document.min.js?ver=3.0.2:2)
consoleError @ common.min.js?ver=3.0.2:2
runCallbacks @ common.min.js?ver=3.0.2:2
run @ common.min.js?ver=3.0.2:2
run @ common.min.js?ver=3.0.2:2
runDataAfter @ common.min.js?ver=3.0.2:2
onAfterApply @ editor-document.min.js?ver=3.0.2:2
onAfter @ editor-document.min.js?ver=3.0.2:2
runAfter @ editor-document.min.js?ver=3.0.2:2
run @ editor-document.min.js?ver=3.0.2:2
forEach.n.<computed> @ editor-document.min.js?ver=3.0.2:2
run @ common.min.js?ver=3.0.2:2
run @ common.min.js?ver=3.0.2:2
callback @ editor.min.js?ver=3.0.2:2
runAction @ editor.min.js?ver=3.0.2:2
e.each.r.<computed> @ common-modules.min.js?ver=3.0.2:2
(anonymous) @ editor.min.js?ver=3.0.2:2
dispatch @ load-scripts.php?c=1&load[chunk_0]=jquery,underscore,backbone,jquery-ui-core,jquery-ui-widget,jquery-ui-mouse,jquery-ui-draggable,wp-api-request,shortcode,utils,wp&load[chunk_1]=-util,wp-backbone,media-models,moxiejs,plupload,wp-plupload,jquery-ui-sortable&ver=5.5:3
r.handle @ load-scripts.php?c=1&load[chunk_0]=jquery,underscore,backbone,jquery-ui-core,jquery-ui-widget,jquery-ui-mouse,jquery-ui-draggable,wp-api-request,shortcode,utils,wp&load[chunk_1]=-util,wp-backbone,media-models,moxiejs,plupload,wp-plupload,jquery-ui-sortable&ver=5.5:3
load-scripts.php?c=1&load[chunk_0]=jquery,underscore,backbone,jquery-ui-core,jquery-ui-widget,jquery-ui-mouse,jquery-ui-draggable,wp-api-request,shortcode,utils,wp&load[chunk_1]=-util,wp-backbone,media-models,moxiejs,plupload,wp-plupload,jquery-ui-sortable&ver=5.5:3 [Violation] 'click' 
`

**Comment by sermalefico** [comment] 2020-08-27 00:38
i Think there is a Conflict with Power Pack Lite for Elementor. If i deactivate the Dispaly Conditions extension in options all works for me. Another conflic with this plugin if a Critical error if Elementor Pro is no active.

**Comment by sermalefico** [comment] 2020-08-27 00:59
uffff i don´t know.... In another site all is fine with the extension active... and in other site only works when deactive extension... WTF!!

**Comment by sermalefico** [comment] 2020-08-27 09:46
Ok. it's all because of the repeat selector controls...

**Comment by 319heads** [comment] 2020-08-27 20:01
Same Issues as op here: deleting, moving, adding sections and columns all broken. 
Elementor 3.03 / Pro 3.01

- Try to delete a column and it deletes an element inside of it instead.
- Rearranging columns by dragging adds new columns

**Comment by sermalefico** [comment] 2020-08-27 23:23
i think the problem is in repeater controls in columns or sections options, any tweak inside columns/sections options break all

**Comment by sermalefico** [comment] 2020-08-27 23:29
common.min.js?ver=3.0.3:2 TypeError: Cannot set property children of #<Container> which has only a getter
    at i.<anonymous> (editor.min.js?ver=3.0.3:2)
    at p (backbone.min.js?ver=1.4.0:2)
    at f (backbone.min.js?ver=1.4.0:2)
    at l (backbone.min.js?ver=1.4.0:2)
    at i.n.trigger (backbone.min.js?ver=1.4.0:2)
    at Object._triggerMethod (backbone.marionette.min.js?ver=2.4.5:22)
    at i.triggerMethod (backbone.marionette.min.js?ver=2.4.5:22)
    at i.destroy (backbone.marionette.min.js?ver=2.4.5:22)
    at i.destroy (backbone.marionette.min.js?ver=2.4.5:22)
    at i.removeChildView (backbone.marionette.min.js?ver=2.4.5:22)
consoleError @ common.min.js?ver=3.0.3:2
onCatchApply @ editor-document.min.js?ver=3.0.3:2
onCatchApply @ editor-document.min.js?ver=3.0.3:2
run @ editor-document.min.js?ver=3.0.3:2
forEach.n.<computed> @ editor-document.min.js?ver=3.0.3:2
run @ common.min.js?ver=3.0.3:2
run @ common.min.js?ver=3.0.3:2
callback @ editor.min.js?ver=3.0.3:2
runAction @ editor.min.js?ver=3.0.3:2
e.each.r.<computed> @ common-modules.min.js?ver=3.0.3:2
(anonymous) @ editor.min.js?ver=3.0.3:2
dispatch @ jquery.js?ver=1.12.4-wp:3
r.handle @ jquery.js?ver=1.12.4-wp:3
common.min.js?ver=3.0.3:2 TypeError: Cannot read property 'parent' of undefined
    at editor-document.min.js?ver=3.0.3:2
    at Array.forEach (<anonymous>)
    at SectionsColumns.apply (editor-document.min.js?ver=3.0.3:2)
    at SectionsColumns.run (editor-document.min.js?ver=3.0.3:2)
    at Data.runCallback (common.min.js?ver=3.0.3:2)
    at Data.runCallbacks (common.min.js?ver=3.0.3:2)
    at Data.run (common.min.js?ver=3.0.3:2)
    at Hooks.run (common.min.js?ver=3.0.3:2)
    at Hooks.runDataAfter (common.min.js?ver=3.0.3:2)
    at Delete.onAfterApply (editor-document.min.js?ver=3.0.3:2)

**Comment by sermalefico** [comment] 2020-08-27 23:30
and this is a new bug

editor.min.js?ver=3.0.3:2 Uncaught TypeError: Cannot read property 'urls' of undefined
    at Function.m.initGroups (editor.min.js?ver=3.0.3:2)
    at Function.m.getGroups (editor.min.js?ver=3.0.3:2)
    at Function.m.addItem (editor.min.js?ver=3.0.3:2)
    at editor.min.js?ver=2.13.3:1
    at editor.min.js?ver=2.13.3:1

**Comment by HorstKaufmann** [comment] 2020-08-28 06:55
Same issues  Elementor 3.0.3 / Pro 3.0.0

deleting anything doesn't work and throws js errors

common.min.js:2:127480

TypeError: setting getter-only property "children"
    getContainer https://www.aquasirius.eu/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.0.3:2
    Backbone 28
    onDestroy https://www.aquasirius.eu/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.0.3:2
    forEach Underscore
    onDestroy https://www.aquasirius.eu/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.0.3:2
    Backbone 6
.....


common.min.js:2:127480

TypeError: e is undefined
    apply https://www.aquasirius.eu/wp-content/plugins/elementor/assets/js/editor-document.min.js?ver=3.0.3:2
    apply https://www.aquasirius.eu/wp-content/plugins/elementor/assets/js/editor-document.min.js?ver=3.0.3:2
    
...

**Comment by VadymPogorelov** [comment] 2020-08-28 07:29
This problem may be related to the presence of a REPEATER type field in the column parameters - see my comment https://github.com/elementor/elementor/issues/12270#issuecomment-682366972

**Comment by kskonovalov** [comment] 2020-08-28 08:23
> This problem may be related to the presence of a REPEATER type field in the column parameters - see my comment [#12270 (comment)](https://github.com/elementor/elementor/issues/12270#issuecomment-682366972)

I tried on an new empty page with newly added empty inner section, same issue

**Comment by sschuchlenz** [comment] 2020-08-28 08:31
Same issues here with 3.0.3 without any REPEATER type field.

**Comment by shilo-ey** [comment] 2020-08-28 08:52
We think that this issue is due to custom repeater controls inside the column element.

Can you verify?

**Comment by GregorCodex** [comment] 2020-08-28 09:44
> [**@VadymPogorelov**](https://github.com/VadymPogorelov) commented on [Aug 28, 2020, 10:29 AM GMT+3](https://github.com/elementor/elementor/issues/12242#issuecomment-682374889):
> 
> > This problem may be related to the presence of a REPEATER type field in the column parameters - see my comment [#12270 (comment)](https://github.com/elementor/elementor/issues/12270#issuecomment-682366972)
> 
> As you mentioned, we think that this issue is due to custom repeater controls inside the column element.
> 
> Can you verify it?

Hi, 

yes, this issue is due to custom repeater controls inside the column element, I confirm.

**Comment by jjjeanbaptiste** [comment] 2020-08-28 10:03
Hi, in my case the problem seems to be solved when I desactivate the Extras for Elementor Add On plugin by Namogo.

**Comment by bobbyschultz** [comment] 2020-08-28 16:35
For me, the issue goes away when I deactivate Essential Addons for Elementor plugin.

**Comment by anandau** [comment] 2020-08-28 17:15
> [**@VadymPogorelov**](https://github.com/VadymPogorelov) commented on [Aug 28, 2020, 10:29 AM GMT+3](https://github.com/elementor/elementor/issues/12242#issuecomment-682374889):
> 
> > This problem may be related to the presence of a REPEATER type field in the column parameters - see my comment [#12270 (comment)](https://github.com/elementor/elementor/issues/12270#issuecomment-682366972)
> 
> As you mentioned, we think that this issue is due to custom repeater controls inside the column element.
> 
> Can you verify it?

I can confirm that this issue appears only if there is any third party addon installed that is adding Repeater Controls to Section or Column.

**Comment by HorstKaufmann** [comment] 2020-08-30 15:45
Same issues with 3.0.4

**Comment by GregorCodex** [comment] 2020-08-30 15:55
Yes, the issues are still there with 3.0.4

**Comment by anandau** [comment] 2020-08-31 01:07
Issue is still there with 3.0.4
I tested the develop branch with PR mentioned above (#12324) and found that issue is fixed. But it seems like that patch was not included in 3.0.4
I hope this can be included in 3.0.5

**Comment by simrandeep** [comment] 2020-08-31 04:23
I just updated to 3.0.4 and seems like the issue is fixed.

**Comment by VadymPogorelov** [comment] 2020-08-31 06:56
In update 3.0.4, the problem still remains. The behavior is the same as I described in comment https://github.com/elementor/elementor/issues/12270#issuecomment-682366972: if you add two fields of the REPEATER type, everything works, and if you comment on any of them, errors appear.

**Comment by sschuchlenz** [comment] 2020-08-31 07:03
Updated to 3.0.4 and disabled elementor addon plugins (e.g. "elementor addon elements", "powerups for elementor" and "pt elementor addons lite") - still using "essential addons for elementor" pro version though - and bugs are gone.

**Comment by shilo-ey** [comment] 2020-08-31 12:20
This issue has been resolved in Elementor v3.0.5

Feel free to update

Thanks!

**Closed by shilo-ey** 2020-08-31 12:20 UTC
Labels: bug, compatibility, status/merged

**Comment by HorstKaufmann** [comment] 2020-08-31 12:25
got v3.0.5
first impression: works quite good - Thanks

**Comment by VadymPogorelov** [comment] 2020-08-31 14:27
Thanks for v.3.0.5. Everything works well.

**Comment by GregorCodex** [comment] 2020-08-31 15:19
Thank you for this fix!

**Comment by askinne2** [comment] 2020-08-31 17:17
Thanks! worked for me too!

**Comment by sermalefico** [comment] 2020-08-31 19:38
Works!

**Comment by bh865** [comment] 2020-10-27 16:12
This is not fixed for me. Here are the versions I'm running:

Elementor 3.0.12
Elementor Pro 3.0.5

Anybody else still having this issue?

**Comment by corgalore** [comment] 2023-06-06 18:42
This is still a problem in Elementor 3.13. The editor is borderline unusable in this state because drag/dropping elements wreaks havoc on your layout.

It seems to happen only when a \Elementor\Controls_Manager::REPEATER control has been added to the page-level document controls using this hook:

`'elementor/documents/register_controls'`

Trying to move containers or delete them doesn't work properly. Is there any work-around?
