### ISSUE TITLE
display flex on elementor-widget-wrap breaks old position absolute design

### ISSUE THREAD

**Issue by tristanleboss** [elementor/elementor#7366] opened 2019-03-07 17:05 UTC
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

## Description

Before v2.5, the class `.elementor-widget-wrap` used `display: block`.
Starting from 2.5, this same class uses `display: flex`.

This create a problem with widgets created in version prior to v2.5. For example, if you created a column with a background color and wanted to position absolute a picture, it will break on 2.5.

With v2.4 :

![image](https://user-images.githubusercontent.com/1431508/53974525-09678f80-4103-11e9-818c-d68a47dc9e61.png)

With v2.5 : 

![image](https://user-images.githubusercontent.com/1431508/53974561-1c7a5f80-4103-11e9-9f2a-5d1991ca7ed7.png)

## Steps to reproduce

Create a colum, set a background color, add a text editor and an image right after, set `Custom CSS` to position absolute the image:

![image](https://user-images.githubusercontent.com/1431508/53974632-45025980-4103-11e9-9c8b-7fa879996de2.png)

## Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a default WordPress theme active.
- [X] I can reproduce this bug consistently using the steps above.

## Environment

Latest WP, Elementor + Elementor Pro

**Comment by shilo-ey** [comment] 2019-03-10 08:45
@tristanleboss 
Thanks for reporting!

We are aware of this and it should be patched soon.
This is caused by the implementation of flexbox to the columns. The patch will add flexbox properties only for pages edited/created since 2.5.0

Please follow this thread for updates.

**Comment by bainternet** [comment] 2019-03-10 14:59
Fixed in 2.5.4

thanks.

**Closed by bainternet** 2019-03-10 14:59 UTC
Labels: bug
