### ISSUE TITLE
🚀 Feature Request: Dynamic tag for the countdown widget (for due date field)

### ISSUE THREAD

**Issue by Joliamendi** [elementor/elementor#19721] opened 2022-09-06 11:05 UTC
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

Please add dynamic tag to this widget.

![Countdown](https://user-images.githubusercontent.com/103376243/188619015-53c139f7-414e-4435-b9b9-1041d8b64b04.png)

Using this tag, we can display [Sale price dates](https://prnt.sc/xzBlPGz6xZWL) for WooCommerce products and this is great.

### Describe the solution you'd like

Dynamic tag for the countdown widget + Ability to display Sale price dates (in single product)

**Comment by rami-elementor** [comment] 2022-09-07 07:45
Duplicate of #18701

**Closed by rami-elementor** 2022-09-07 07:45 UTC
Labels: status/awaiting_triage
