### ISSUE TITLE
Img CSS classes assigned to parent div instead of Img attribute (Fix would enable compatibility for Image in popups with Jetpack Lazy Loading)

### ISSUE THREAD

**Issue by caluwaek** [elementor/elementor#7316] opened 2019-03-05 10:54 UTC
## Prerequisites

- [X ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X ] The issue still exists against the latest stable version of Elementor.

## Description

Created a popup and added an image.
The image is shown in the builder and I can see how it's there in preview (or once published) in the code (in Chrome developer tools) but it shows as a blank space.

If I use the same image as a background for the popup it works.
If you disable jetpack lazy loading images it works.

Disabling lazy loading images for the whole site is not something I want to do but Jetpack provides an alternative solution where you can assign classes to images you want lazy load to skip:
https://developer.jetpack.com/hooks/jetpack_lazy_images_blacklisted_classes/

I added the code to functions.php and created such a class and assigned it to the image (Edit Image > Advanced > CSS classes) but noticed that these CSS classes are not assigned to the img attribute but instead to a div element that wraps the img attribute.  This means Jetpack Lazy Loading is not impacted.

Is it possible to assign the css classes to the img attribute instead of one of the parent divs.  Or to both the div as well as the css image.

## Steps to reproduce

1. Enable Jetpack
2. Create new Popup
3. Add image to popup
4. Add css class to the image
5. Publish or save draft and preview

## Isolating the problem

- [x ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x ] This bug happens with a default WordPress theme active.
- [ x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Percona Server (GPL), Release '18', Revision '7ce54a6deef' v5.7.20-18
	PHP Version: 7.2.15
	PHP Max Input Vars: 20000
	PHP Max Post Size: 256M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.0.3
	Site URL: https://www.wapititravel.com/blog
	Home URL: https://www.wapititravel.com/blog
	WP Multisite: No
	Max Upload Size: 256 MB
	Memory limit: 128M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: Europe/Brussels
	Debug Mode: Inactive

== Theme ==
	Name: Hestia Pro Child
	Version: 0.1
	Author: ThemeIsle
	Child Theme: Yes
	Parent Theme Name: Hestia Pro
	Parent Theme Version: 2.3.0
	Parent Theme Author: ThemeIsle

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.119 Safari/537.36

== Active Plugins ==
	Agoda Affiliate Partners Text Link Generator
		Version: 1.0
		Author: Agoda

	Akismet Anti-Spam
		Version: 4.1.1
		Author: Automattic

	Boxzilla
		Version: 3.2.10
		Author: ibericode

	Categories Images
		Version: 2.5.4
		Author: Muhammad Said El Zahlan

	Classic Editor
		Version: 1.4
		Author: WordPress Contributors

	Content Views
		Version: 2.1.3.2
		Author: ContentViews

	Content Views Pro
		Version: 5.4.1
		Author: CVSOFT LLC

	Custom Related Posts
		Version: 1.6.1
		Author: Bootstrapped Ventures

	Easy Digital Downloads
		Version: 2.9.11
		Author: Easy Digital Downloads

	Easy Digital Downloads Polylang
		Version: 0.0.1
		Author: Ulrich Pogson

	Easy Table of Contents
		Version: 1.7
		Author: Steven A. Zahm

	EDD Sale Price
		Version: 1.0.4
		Author: Jeroen Sormani

	Elementor
		Version: 2.4.7
		Author: Elementor.com

	Elementor Pro
		Version: 2.4.5
		Author: Elementor.com

	Free & Simple Contact Form Plugin - Pirateforms
		Version: 2.5.1
		Author: WPForms

	GDPR Cookie Consent Banner
		Version: 2.3.14
		Author: termly

	Google Analytics Dashboard for WP (GADWP)
		Version: 5.3.7
		Author: ExactMetrics

	Image Cleanup
		Version: 1.9.2
		Author: Robbert Langezaal, Simon Duduica

	Insert Headers and Footers
		Version: 1.4.3
		Author: WPBeginner

	Instagram Feed
		Version: 1.11.2
		Author: Smash Balloon

	Jetpack by WordPress.com
		Version: 7.0.1
		Author: Automattic

	Mailchimp for WordPress
		Version: 4.4
		Author: ibericode

	MailChimp for WordPress - Premium
		Version: 4.5.7
		Author: ibericode

	ManageWP - Worker
		Version: 4.7.5
		Author: GoDaddy

	MaxButtons
		Version: 7.9
		Author: Max Foundry

	Menu Icons
		Version: 0.11.4
		Author: ThemeIsle

	Orbit Fox Companion
		Version: 2.7.5
		Author: Themeisle

	Pirate Parrot
		Version: 1.3.0
		Author: Themeisle

	Polylang
		Version: 2.5.2
		Author: Frédéric Demarle

	Redirection
		Version: 3.7.3
		Author: John Godley

	Send Images to RSS
		Version: 3.2.2
		Author: Robin Cornett

	TablePress
		Version: 1.9.2
		Author: Tobias Bäthge

	ThirstyAffiliates
		Version: 3.7
		Author: Rymera Web Co

	Title and Nofollow For Links
		Version: 1.07
		Author: WPKube

	UpdraftPlus - Backup/Restore
		Version: 1.16.6
		Author: UpdraftPlus.Com, DavidAnderson

	W3 Total Cache
		Version: 0.9.7.2
		Author: Frederick Townes

	WP Add Custom CSS
		Version: 1.1.4
		Author: Daniele De Santis

	WP Migrate DB
		Version: 1.0.10
		Author: Delicious Brains

	Yoast SEO
		Version: 9.7
		Author: Team Yoast

	Yoast SEO: Search index purge
		Version: 1.1.0
		Author: Team Yoast

== Must-Use Plugins ==
	ManageWP - Worker Loader
		Version: 
		Author: ManageWP

	WP Migrate DB Compatibility
		Version: 1.1
		Author: Delicious Brains

	WP Staging Optimizer
		Version: 1.0
		Author: René Hermenau

== Log ==
	: 
JS: showing 5 of 5JS: 2019-02-27 13:23:14 [error X 1][https://www.wapititravel.com/blog/wp-content/plugins/elementor-pro/assets/js/editor.min.js?ver=2.4.5:2:15986] Cannot read property \'model\' of undefined 
JS: 2019-03-01 06:46:45 [error X 13][https://www.wapititravel.com/blog/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.4.7:2:6883] Cannot read property \'select2\' of undefined 
JS: 2019-03-04 18:12:18 [error X 1][https://www.wapititravel.com/blog/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view4554\") has already been destroyed and cannot be used. 
JS: 2019-03-05 08:31:06 [error X 1][https://www.wapititravel.com/blog/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view1106\") has already been destroyed and cannot be used. 
JS: 2019-03-05 10:05:43 [error X 42][:2:5] $ is not a function 

				
</details>

**Comment by caluwaek** [comment] 2019-03-05 11:00
Sorry, forgot to include these screenshots.

[Elementor lazy load images.pdf](https://github.com/elementor/elementor/files/2930637/Elementor.lazy.load.images.pdf)

**Comment by shilo-ey** [comment] 2019-03-07 16:05
Duplicate of #6942 & #7362

**Closed by shilo-ey** 2019-03-07 16:05 UTC

**Comment by shilo-ey** [comment] 2019-03-07 16:07
As for your request, currently we do not support adding CSS classes for the elements themselves only to their wrapper.

**Comment by caluwaek** [comment] 2019-03-07 17:07
Can you change this case into a feature request?  As I stated it would help solve the lazy loading compatibility problem with Jetpack.

**Comment by offthewallprints** [comment] 2019-12-03 03:59
Hi, I have been through the few articles that address this issue with images not appearing on elementor popups and i have not been able to fix it. i am having the same problem as everyone else with the same details. i have tried disabling jetpack changing themes reuploading, turning off all lazy loads etc and images just dont appear on elementor popups. 

can anyone help with this simple problem that seems to have no fix? see example of what happens on my site: https://offthewallprints.co/product/black-white-tiger/ any of the 2 links in product description should have images where there are just gaps.

thanks

**Comment by sarit026** [comment] 2025-03-06 07:51
+1
