### ISSUE TITLE
Responsivenes in tablet mode does not respond

### ISSUE THREAD

**Issue by mgustavs** [elementor/elementor#7509] opened 2019-03-17 14:20 UTC
Try No 2
Dear Elementor,

I am working on a page in Elementor Pro on Mac and I have problem with Responsiveness for Tablets - any change I make does not take place in live mode and seems also not in front end...
Desktop and Mobile views work fine. I have attached a photo where you can see that one of columns should be 80% but both are still 50%..

Amindiary mentioned this on September 10, 2018. One of you closed it because of too much rules and that hasn't solved the issue itself. Can this maybe come up on surface now for a resolve?

Thanks a million!

## Prerequisites

- [ x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x ] The issue still exists against the latest stable version of Elementor.

## Isolating the problem

- [ x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ x] This bug happens with a default WordPress theme active.
- [ x] I can reproduce this bug consistently using the steps above.

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MariaDB Server v5.7.24
	PHP Version: 7.2.13
	PHP Max Input Vars: 6200
	PHP Max Post Size: 512M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.1.1
	Site URL: http://kokacentrs.lv
	Home URL: http://kokacentrs.lv
	WP Multisite: No
	Max Upload Size: 512 MB
	Memory limit: 768M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: Twenty Sixteen
	Version: 1.8
	Author: the WordPress team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.1.2 Safari/605.1.15

== Active Plugins ==
	Elementor
		Version: 2.5.8
		Author: Elementor.com

	Elementor Pro
		Version: 2.4.8
		Author: Elementor.com

== Log ==
	: 
JS: showing 12 of 12JS: 2019-02-01 10:13:39 [error X 6][http://kokacentrs.lv/wp-content/plugins/auxin-elements/admin/assets/js/elementor/widgets.js?ver=2.3.7:23:151] $scope.find(\'video\').mediaelementplayer is not a function. (In \'$scope.find(\'video\').mediaelementplayer()\', \'$scope.find(\'video\').mediaelementplayer\' is undefined) 
JS: 2019-02-04 11:13:43 [error X 1][http://kokacentrs.lv/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.4.5:2:206586] undefined is not an object (evaluating \'e.ui.form.html\') 
JS: 2019-02-04 11:13:56 [error X 1][undefined:1:21] Can\'t find variable: auxinCreateNamespace 
JS: 2019-02-15 03:24:07 [error X 149][http://kokacentrs.lv/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.4.6:2:167468] undefined is not an object (evaluating \'this._parent.errors\') 
JS: 2019-02-20 17:20:32 [error X 3][http://kokacentrs.lv/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.4.7:2:6882] undefined is not an object (evaluating \'this.ui.select.select2\') 
JS: 2019-02-22 11:19:08 [error X 10][http://kokacentrs.lv/wp-content/plugins/elementor-pro/assets/js/editor.min.js?ver=2.4.5:2:15985] undefined is not an object (evaluating \'e.model\') 
JS: 2019-02-23 17:29:57 [error X 3][undefined:1:9] Can\'t find variable: Calendly 
JS: 2019-02-27 23:14:54 [error X 11][http://kokacentrs.lv/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.4.7:2:119829] n is undefined 
JS: 2019-02-27 23:15:06 [error X 9][http://kokacentrs.lv/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.4.7:2:99388] e is undefined 
JS: 2019-02-28 01:56:51 [error X 5][http://kokacentrs.lv/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.4.7:2:74603] setting getter-only property \"type\" 
JS: 2019-02-28 03:08:12 [error X 1][http://kokacentrs.lv/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.4.7:2:6868] this.ui.select is undefined 
JS: 2019-03-14 20:16:03 [error X 3][http://kokacentrs.lv/wp-content/plugins/elementor/assets/js/editor-modules.js?ver=2.4.7:733:39] self.attributes[control.name].each is not a function. (In \'self.attributes[control.name].each(function (item) {
					styleFields.push(self.getStyleControls(control.fields, item.attributes));
				})\', \'self.attributes[control.name].each\' is undefined) 

Log: showing 5 of 52019-02-13 17:03:03 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.4.5',
  'to' => '2.4.6',
)]
2019-02-19 10:18:35 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.4.6',
  'to' => '2.4.7',
)]
2019-03-14 20:36:14 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.4.7',
  'to' => '2.5.7',
)]
2019-03-15 20:10:55 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.5.7',
  'to' => '2.5.8',
)]
2019-03-15 20:10:55 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.4.5',
  'to' => '2.4.8',
)]

<img width="1195" alt="Screen Shot 2019-03-15 at 19 37 14" src="https://user-images.githubusercontent.com/47918624/54492569-6ff16800-48d0-11e9-8bdf-db985a74ac5b.png">

**Comment by shilo-ey** [comment] 2019-03-17 14:38
Hi @mgustavs 

Thanks for reporting.

As we mentioned earlier, we can't see this issue, 
therefore kindly add steps to reproduce.

Looking forward to your reply.
Thanks

**Comment by mgustavs** [comment] 2019-03-17 15:04
## Steps to reproduce
(I don't quite get what that supposed to be?...)

1. Edit any page/footer/menu with Elementor Pro
2. Take any column and set width to preferred (e.g from 50% to 80%) in desktop mode. Live changes take place on screen. Set it back to 50%
3. Change live mode to tablet view. Set same column width to preferred one (e.g from 50% to 80%). No live changes on screen. It says in the little box 80, but stays 50% on screen.

![Screen Shot 2019-03-15 at 19 37 14 copy](https://user-images.githubusercontent.com/47918624/54493272-86022700-48d6-11e9-984e-87006c06d697.jpg)

**Comment by mgustavs** [comment] 2019-03-17 15:11
## Steps to reproduce
(I don't quite get what that supposed to be?...)

1) Edit any page/footer/menu with Elementor Pro
2) Take any column and set width to preferred (e.g from 50% to 80%) in desktop mode. Live changes take place on screen. Set it back to 50%
3) Change live mode to tablet view. Set same column width to preferred one (e.g from 50% to 80%). No live changes on screen. It says in the little box 80, but stays 50% on screen.

![54492569-6ff16800-48d0-11e9-8bdf-db985a74ac5b](https://user-images.githubusercontent.com/47918624/54493349-a979a180-48d7-11e9-927d-92afc2d05a4b.jpg)

**Comment by shilo-ey** [comment] 2019-03-17 15:23
Hן @mgustavs 

I'm sorry but we cannot reproduce your issue.

[Here is a video](https://www.useloom.com/share/14ae0121fb9545a488bd477be11f2e62) of the behavior as described.
Please note that the Tablet mode and the Desktop mode has some differences.
In Desktop mode the total percentages of a section can be above 100%, that's because of the grid responsive layout (the columns break and placed one after each other), therefore the total amount is not calculated automatically to 100% but can be more than that.

If you are still encountering this issue and my explanation is not in accordance to what you've meant, please contact our support at support @elementor.com for guidance in resolving this issue and mention that you were directed by me and reference this issue.

thanks.

**Closed by shilo-ey** 2019-03-17 15:23 UTC
Labels: status/needs feedback

**Comment by mgustavs** [comment] 2019-03-17 15:37
Thanks @shilo-ey. Yep, works fine on your screen.. Not on mine..

**Comment by shilo-ey** [comment] 2019-03-17 15:45
[**@mgustavs**](https://github.com/mgustavs) commented on [Mar 17, 2019, 5:37 PM GMT+2](https://github.com/elementor/elementor/issues/7509#issuecomment-473677191 "2019-03-17T15:37:58Z - Replied by Github Reply Comments"):
> Thanks @shilo-ey. Yep, works fine on your screen.. Not on mine..

Therefore it is not a general issue and might be caused by compatibility issue we need to troubleshoot.

Please contact our support.

**Comment by mgustavs** [comment] 2019-03-26 22:01
@shilo-ey 

It actually might be bigger than that and I think I just found out what the damn problem is.

I  have set the breakpoints in Elementor settings for Tablet 900px and Phone 600px. When I looked into Elementor page editor, it clearly says preview is for Tablet 600px and Phone 360px. I thought ok - 600px and 360px must be “average” sizes Elementor picked so I have to go below 600 for phone breakpoint to actually see the tablet changes live and I set Phone breakpoint to 590. Guess what?! Now in editor it says Tablet 590px(!!!) and phone still 360px!

Tablet view actually IS phone view and not a tablet view as I already guessed before!!!

Feel like freaking Sherlock Holmes here. I've sent this off to support@elementor.com I just want to make this public, so that others having this issue can also have a clue.

Still hoping for a solution as I want to see how my page will look on tablet and phone before it goes live and I can test it on actual devices….

<img width="409" alt="Elementor breakpoint settings 1" src="https://user-images.githubusercontent.com/47918624/55036330-f91c4380-5022-11e9-9c13-2269214644ef.png">
<img width="447" alt="Elementor breakpoint settings 2" src="https://user-images.githubusercontent.com/47918624/55036331-f91c4380-5022-11e9-89a4-5a70f7e495ab.png">
<img width="324" alt="Elementor editor breakpoints 1" src="https://user-images.githubusercontent.com/47918624/55036332-f91c4380-5022-11e9-87f7-ea9d349b7007.png">
<img width="313" alt="Elementor editor breakpoints 2" src="https://user-images.githubusercontent.com/47918624/55036333-f9b4da00-5022-11e9-8e0a-f2ad0a3eadc8.png">

**Comment by mgustavs** [comment] 2019-04-04 20:30
I've come down to realise that problem lies within Safari - I went on working on Chrome for a check and yes! I see my changes for tablet in responsive mode.

**Comment by mgustavs** [comment] 2019-04-04 20:32
@shilo-ey,

I've come down to realise that problem lies within Safari - I went on working on Chrome for a check and yes! I see my changes for tablet in responsive mode.

**Comment by mgustavs** [comment] 2019-04-04 20:32
@shilo-ey ,

I've come down to realise that the problem lies within Safari - I went on working on Chrome for a check and yes! I see my changes for tablet in responsive mode.

**Comment by likeasimon** [comment] 2020-07-08 14:23
Issue is also occurring using the currently newest Edge Chromium Version 83.0.478.61/64 bit. 

Using Chrome works.
