### ISSUE TITLE
Loop builder for Posts Widget

### ISSUE THREAD

**Issue by borayeris** [elementor/elementor#12211] opened 2020-08-24 20:58 UTC
## Prerequisites

- [ x ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ x ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Posts Widget doesn't have design feature. I wish we can customize how posts look. 

**Describe the solution you'd like**
I wish we can use theme builder to create loop of a post.

**Describe alternatives you've considered**

**Additional context**

**Comment by bainternet** [comment] 2020-08-24 21:25
Duplicate of #4440

**Closed by bainternet** 2020-08-24 21:25 UTC

**Comment by nicholaszein** [comment] 2023-08-01 21:48
Hello there!

We have great news! 🙌 

### 📢 We're happy to announce the new Loop Builder released with Elementor Pro v3.8.0! 🥳 

With the new Loop Grid widget, you can customize your post listings with custom templates! 💪 
Drag & Drop widgets to create complex designs, fine-tune your Loop Grid layout, add alternate templates, and much more!

This is just the first phase. More customization is coming!

Check out the article here: https://elementor.com/help/loop-grid/

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
