### ISSUE TITLE
Enqueues unnecessary JS files on the frontend

### ISSUE THREAD

**Issue by parasshah195** [elementor/elementor#8572] opened 2019-07-15 04:09 UTC
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

The plugin adds extra JS files for functionalities which are not being used on the page.

For example, on my [site's homepage](https://pixify.net), the plugin enqueues the following scripts which are not used:

- lib/sticky/jquery.sticky.min.js (no sticky elements on the page; added by Elementor Pro)
- jquery/ui/position.min.js (this one's probably a dependency for one of the below Elementor scripts)
- lib/dialog/dialog.min.js (no dialog boxes either)
- lib/swiper/swiper.min.js (no sliders used)

This does not even include the `frontend-modules.min.js` by Elementor and `frontend.min.js` by Elementor Pro which I guess are files that define general functions. (...wondering what important task do they do which is supposed to be loaded on all the pages)

So in short, Elementor (even just the free version) adds a lot of unnecessary JS files to the frontend whose functionalities are not being used. Affects site performance by quite a margin.

I think you guys need to modularize asset enqueuing better so that you have a system in place to detect whether the particular features are being used or not and only then enqueue these.

I appreciate the Element specific enqueuing model that Elementor has adapted which only includes those assets when those specific elements are used. So similarly, if that type of modular loading would be applied to these general elements as well, that would significantly cut down the number of assets enqueued and would only load the required files.

Elementor has already become a very mature Page Builder and so, the modular asset enqueuing is something that is expected from it and should've been already implemented.

I hope this would be prioritized and fixed soon.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

**Comment by black-eye** [comment] 2019-08-27 20:28
+1

**Comment by PieterT2000** [comment] 2019-09-03 11:56
@Paras16699, @black-eye If you're looking for a quick solution, check out the script I wrote.
https://github.com/PieterT2000/elementor-hacks/blob/master/script.php

**Comment by Paras16699** [comment] 2019-09-03 12:31
@PieterT2000, thanks for sharing. What's the license for that code? Was hoping to use that in one of my GPL themes.

**Comment by PieterT2000** [comment] 2019-09-03 16:54
@Paras16699 I've just added a GPL license to the repository. Good luck!

**Comment by Jonathlee** [comment] 2019-09-11 07:40
Would it be possible to change the JQuery to load from CDN instead from plugin's folder directory?

**Comment by andcha** [comment] 2020-01-28 09:32
@PieterT2000 The solution posted does not work anymore, maybe there is some change in code from elementor.

**Comment by MichaelDarko** [comment] 2020-05-04 12:29
+1.

Loading assets for something that's not used on a page is just bad. Some future-proof system should be implemented for this, or Elementor will become more and more bloted.

**Comment by davidamarek** [comment] 2020-06-16 07:12
+1

**Comment by RichDavis1** [comment] 2020-06-23 00:53
For how simple this implementation is, I don't see why it doesn't exist. Cache or not, no developer wants to manage third-party js bundles on pages where they are not used. Managing in-house webpack bundles is annoying enough.

**Comment by eduardovillao** [comment] 2020-08-19 17:01
Hey @parasshah195 i made a little snippet for remove JS, CSS and others and improve Elementor performance. [https://github.com/eduardovillao/speed-up-elementor](https://github.com/eduardovillao/speed-up-elementor)

**Comment by blackge** [comment] 2020-09-11 09:56
+1

**Comment by pacifier007** [comment] 2020-11-02 14:30
It's so unfortunate that a project this popular and this well-funded can continue to ignore front-end performance, for so long - especially in times when performance is critical for SEO. But even forget SEO, it's important for UX. 

Just see this: https://oxygen4fun.supadezign.com/wp-charts-comparisons/

It's a shame when WPBakery is better! - which used to be the worst. Elementor has continuously gotten worse in front-end performance over time.

**Comment by mrbenjaminjo** [comment] 2020-11-04 13:07
@shilo-ey Thanks for merging, but this thread goes back to mid 2019 - so a merge is basically, "yeah we know, but well, we're going to add conditional forms instead.."

(if you're not from Elementor and just being helpful, then I apologise - but it's frustrating. Just a checkbox in a menu called "Tools > Developers > This might break your site > Don't do it > Seriously, don't > Secret hacks > Speed up Elementor > Turn cr@p off." would do.

**Comment by Jordidriesen** [comment] 2020-11-12 13:17
This really needs to be handled, since it will cause a negative effect for seo when google implements their new page experience in 2021. Many made it clear, but is just looks like lazyness from elementor's part...

**Comment by parasshah195** [comment] 2020-12-19 07:17
@DorShahar, I installed the `3.1.0-dev3` version, created a new landing page (using the newly introduced CPT), checked the source code, and compared the output to a page developed with 3.0.x

The number of JS files outputted is the same, with more additional Webpack files outputted in the `3.1.0-dev3` version. The new page uses no slider, yet we had the `swiper` lib outputted; no share buttons, yet outputting the `share-link` file; and also the `dialog` and `waypoints` JS files which are also something not used on the page.

The version `3.1.0-dev3` [claims to fix it by conditional loading of assets](https://github.com/elementor/elementor/blob/developer-edition/CHANGELOG.md#changelog) but I don't see any conditional loading happening here.. Can you shed some light on this, please?

**Comment by thisura1994** [comment] 2020-12-19 17:06
Hi, 

Does anyone know what's the use of these? 

1. jquery-ui-position
/wp-includes/js/jquery/ui/position.min.js

2. elementor-waypoints
/wp-content/plugins/elementor/assets/lib/waypoints/waypoints.min.js

**Comment by shilo-ey** [comment] 2020-12-29 17:27
> @DorShahar, I installed the `3.1.0-dev3` version, created a new landing page (using the newly introduced CPT), checked the source code, and compared the output to a page developed with 3.0.x
> 
> The number of JS files outputted is the same, with more additional Webpack files outputted in the `3.1.0-dev3` version. The new page uses no slider, yet we had the `swiper` lib outputted; no share buttons, yet outputting the `share-link` file; and also the `dialog` and `waypoints` JS files which are also something not used on the page.
> 
> The version `3.1.0-dev3` [claims to fix it by conditional loading of assets](https://github.com/elementor/elementor/blob/developer-edition/CHANGELOG.md?rgh-link-date=2020-12-19T07%3A17%3A53Z#changelog) but I don't see any conditional loading happening here.. Can you shed some light on this, please?

Please try out the new Beta version that is out there.
If you're using Elementor Pro please make sure to update to the latest version.
Note that the Pro modules will be handled in the Pro release.

Thanks for bringing this issue to our attention.

Some useful information:
- https://developers.elementor.com/experiment-optimized-asset-loading
- https://developers.elementor.com/a-new-method-for-attaching-a-js-handler-to-an-element/

**Comment by parasshah195** [comment] 2020-12-30 16:47
@shilo-ey, Yes, the swiper lib doesn't load unnecessarily anymore which is a big win (considering it is around 130kBs), but for some reason, I'm still seeing the `share-link.min.js` on a new blank canvas page with just a single heading element. Not a big deal for just a 2kB file, but better if as many unnecessary requests are slashed from the page load.

Another file to slash would be the `dialog` lib (10kB) if there's no lightbox or popup used on the page but I'd guess that would be difficult to implement because of the architecture.

Looking forward to seeing the complementary implementation in Elementor Pro.

**Comment by Slapbox** [comment] 2021-01-18 20:00
Until the Elementor team removes those other straggler files, WP Asset Cleanup has been a great help for this purpose. Dequeued `share-link.min.js` and some other stuff and cut out a substantial amount of size and load time for our site.

**Comment by pacifier007** [comment] 2021-01-27 23:01
Need to do the same with CSS IMHO. The elementor-frontend css file is unreasonably bloated. There's no need for swiper, dialog and much more of the CSS to be all dumped into one frontend file. It should be conditional too.

**Comment by shilo-ey** [comment] 2021-02-16 14:45
This issue has been resolved in Elementor Pro v3.1.0

Feel free to update

In the next versions we will keep on improving this vector.

Keeping this open for now.

Thanks!

**Comment by jazir5** [comment] 2021-02-24 12:17
> This issue has been resolved in Elementor Pro v3.1.0
> 
> Feel free to update
> 
> In the next versions we will keep on improving this vector.
> 
> Keeping this open for now.
> 
> Thanks!

Do you have plans to implement this for CSS files as well soon?

**Comment by MichaelDarko** [comment] 2021-03-01 13:18
Is there a plan to gradually get the performance on a similar level as Oxygen, Gutenberg, Webflow and other fast visual builders? Out of the serious page builders, Elementor has the worst performance. I was just building a project in Oxygen and it was so much better in many ways. It seems that Elementor is just badly designed from the start and now most of the developement effort has to go into overcoming technical debt and any change in the right direction takes ages.

**Comment by kasket091** [comment] 2021-03-02 21:02
/plugins/elementor/assets/js/common.min.js?ver=3.1.2
/plugins/elementor/assets/js/common-modules.min.js?ver=3.1.2
/plugins/elementor/assets/js/app-loader.min.js?ver=3.1.2
/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1
/plugins/elementor/assets/lib/dialog/dialog.min.js?ver=4.8.1
/plugins/elementor/assets/lib/backbone/backbone.radio.min.js?ver=1.0.4

This are the new JS files loaded on a non-elementor page can for now i used Asset Clean up plugin to dequeue this files in the frontend does the next patch clearly remove all the elementor assets on a non-elementor page?

**Comment by Slapbox** [comment] 2021-03-02 21:29
We also use Asset Cleanup, but this is extremely tedious and not scalable. Currently we're only doing it on our most important pages due to the time required and the risk of breaking things if you don't take your time.

I really hope this will be improved on in the next release or two.

**Comment by kasket091** [comment] 2021-03-02 22:26
> /plugins/elementor/assets/js/common.min.js?ver=3.1.2
> /plugins/elementor/assets/js/common-modules.min.js?ver=3.1.2
> /plugins/elementor/assets/js/app-loader.min.js?ver=3.1.2
> /plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1
> /plugins/elementor/assets/lib/dialog/dialog.min.js?ver=4.8.1
> /plugins/elementor/assets/lib/backbone/backbone.radio.min.js?ver=1.0.4
> 
> This are the new JS files loaded on a non-elementor page. For now i used Asset Clean up plugin to dequeue this files in the frontend does the next patch clearly remove all the elementor assets on a non-elementor page?

All Good @Slapbox, Already understand the following scripts its for THE FINDER ( ctrl+E/CMD + E)  function of Elementor it will just load on the backend and logged in users and this scripts will not be visible in global users.

**Comment by jazir5** [comment] 2021-03-04 07:47
@kasket091

Can I disable all of these files with asset cleanup globally, even on
Elementor pages if I don't need Finder?

**Comment by MichaelDarko** [comment] 2021-03-13 18:10
It might be useful to visualize how badly designed Elementor is when it comes to performance.

### Elementor

This is a list of JS and CSS files that Elementor is loading on the frontend and the red color indicates what portion is not used.

(And that's on top of all the other WordPress and plugin assets!)

![Elementor](https://user-images.githubusercontent.com/36289156/111038270-5edc8280-8428-11eb-9d61-c01c14af3c90.png)

### Webflow

And here is the same thing from website build on Webflow. 

(And Webflow is 10x more powerful page builder in terms of features!)

![Webflow](https://user-images.githubusercontent.com/36289156/111038272-5f751900-8428-11eb-805a-17de232ff854.png)

Performance demands from my clients are basically forcing me to switch to Gutenberg (simple websites) and Webflow (more complex websites). Elementor is no longer at the cutting-edge when it comes to features and the performance is not acceptable for a professional tool.

**Comment by Slapbox** [comment] 2021-03-13 19:03
Elementor was a first mover and is bound to have more technical debt. As long as they're planning to address it I plan to be patient; I just want assurances that they plan to address it.

**Comment by Jonathlee** [comment] 2021-03-14 06:16
** PERFORMANCE & RESOURCES**
![image](https://user-images.githubusercontent.com/696956/111059191-7e2deb00-84ce-11eb-8f05-d3668f282369.png)
![image](https://user-images.githubusercontent.com/696956/111059193-87b75300-84ce-11eb-8451-59296b4e535f.png)

Using the latest version of Development version (as in time of post)
Great to see Fontawesome has been linked to CDN.

Hope to see JQuery & JQ Migrate would be possible to load via CDN.
`
share-link.min.js 
jquery.sticky.min.js
`
The above item was still loaded despite not in used.

`
dialog.min.js
` Unsure about this one though.

Hope the team cold overall resource loading prior adding in more new features to bloat the entire pack.

**Comment by shilo-ey** [comment] 2021-03-15 11:16
Hi all,

As mentioned earlier in this thread and in our official blog posts - we take this matter very seriously, therefore the aspects that you raise here are being taken care of:
- Conditionally load libraries (only when used):
 - dialog
 - share-links
 - screenfull
 - lightbox
 - sticky

- Working on a concept for improved css loading
- Minimize e-icons library dramatically
- More improvements to come

@MichaelDarko As for the comparisons you shared - it seems like the Improved Asset Load experiment is inactive. it should resolve many of the scripts that are loaded when not used.
But as mentioned above - we are aware and as a mature product, we make changes carefully and gradually.

If you have any more suggestions on how to improve the loading of assets in Elementor feel free to share them here.

Thanks

**Comment by mrbenjaminjo** [comment] 2021-03-15 13:42
> Hi all,
> 
> As mentioned earlier in this thread and in our official blog posts - we take this matter very seriously, therefore the aspects that you raise here are being taken care of:
> 
> * Conditionally load libraries (only when used):
>   
>   * dialog
>   * share-links
>   * screenfull
>   * lightbox
>   * sticky
> * Working on a concept for improved css loading
> * Minimize e-icons library dramatically
> * More improvements to come
> 
> @MichaelDarko As for the comparisons you shared - it seems like the Improved Asset Load experiment is inactive. it should resolve many of the scripts that are loaded when not used.
> But as mentioned above - we are aware and as a mature product, we make changes carefully and gradually.
> 
> If you have any more suggestions on how to improve the loading of assets in Elementor feel free to share them here.
> 
> Thanks

I think it's great that you've engaged here in a discussional way - may I offer an anecdotal story about Elementor performance?

I've tuned many Elementor stacks, and it's always a challenge to get above 89 PSI for mobile, it's almost impossible without significant page caching. And the more caching we add, the more likely something is to break.

I recently moved an Elementor, E Pro, Hello site to a host with a good page caching solution, so decided to re-optimise the site using the hosts caching stack. It performed very well, but Elementor, even with the new asset loading option selected was still pulling in libraries that I wasn't using.

So I still needed to use Asset Clean Up to prevent them from being loaded.

At this stage, I still couldn't get mobile over 89 on PSI.

As usual, elementor was loading e-icons on the site, and as usual (for me) the only thing using e-icons was the mobile hamburger menu.

Since I was in the mood for experimentation, I replaced Hello with Kadence (but I'm sure GP or Blocksy would've been the same) and replaced the E Pro header with a theme header from Kadence. Kadence doesn't load an icon set for their hamburger icon.

This allowed me to de-queue e-icons, it also reduced the page size and DOM.

The change from Hello to a theme with headers took me to a PSI of 95. The removal of e-icons reduced my page size by 20%.

Last years Iconic release for Elementor should've included the ability to use single SVGs for Hamburger open and close in the Nav. That single change would be hugely impactful for many sites, especially ones that are tuned down to  <600k page sizes.

It also seems like it would be the simplest of all of the options when it comes to dev time and resource.

Keep pushing the advanced solutions, but don't lose track of the speed "hacks" that people on the sharp end are doing, some simple changes could produce significant gains for you, and win some kudos in the community.

**Comment by jazir5** [comment] 2021-03-15 19:30
+1 for being able to replace the hamburger menu icon with an svg, that
would be very helpful and allow disabling of eicons.

**Comment by Thisurajay** [comment] 2021-03-15 19:44
+1 from me too for being able to replace the hamburger menu icon with an svg. One would expect something like this to be done soon.

**Comment by Rushdiey** [comment] 2021-04-23 04:07
After updating to 3.2
I got problem eicons.
It say not found.
It means i need to upload eicon into the path?
How to disable so that i wont use this eicon

**Comment by d19dotca** [comment] 2021-05-10 04:05
For what it's worth, I enabled the "Improved CSS Loading" experiment today in the Dev edition, and it did a pretty decent job. I'm sure it's one of those "your mileage may vary" situations, but I didn't notice any negative impact yet (no broken views for example) and saw positive improvements which is nice. 

Some very basic testing by making no changes other than the experiment enabled or disabled...

With Improved CSS Loading experiment **disabled** (baseline):
Total Size | Requests | Load Time
----------------|-----------|-------------
1.76 MB | 52 | 1.87 s

With Improved CSS Loading experiment **enabled**:
Total Size | Requests | Load Time
----------------|-----------|-------------
1.61 MB | 51 | 1.62 s

As you can see, enabling the new "Improved CSS Loading" experiment (currently in the dev edition) made a positive improvement to my example website.

**Comment by GJKuz** [comment] 2021-05-29 22:23
> > Hi all,
> > As mentioned earlier in this thread and in our official blog posts - we take this matter very seriously, therefore the aspects that you raise here are being taken care of:
> > 
> > * Conditionally load libraries (only when used):
> >   
> >   * dialog
> >   * share-links
> >   * screenfull
> >   * lightbox
> >   * sticky
> > * Working on a concept for improved css loading
> > * Minimize e-icons library dramatically
> > * More improvements to come
> > 
> > @MichaelDarko As for the comparisons you shared - it seems like the Improved Asset Load experiment is inactive. it should resolve many of the scripts that are loaded when not used.
> > But as mentioned above - we are aware and as a mature product, we make changes carefully and gradually.
> > If you have any more suggestions on how to improve the loading of assets in Elementor feel free to share them here.
> > Thanks
> 
> I think it's great that you've engaged here in a discussional way - may I offer an anecdotal story about Elementor performance?
> 
> I've tuned many Elementor stacks, and it's always a challenge to get above 89 PSI for mobile, it's almost impossible without significant page caching. And the more caching we add, the more likely something is to break.
> 
> I recently moved an Elementor, E Pro, Hello site to a host with a good page caching solution, so decided to re-optimise the site using the hosts caching stack. It performed very well, but Elementor, even with the new asset loading option selected was still pulling in libraries that I wasn't using.
> 
> So I still needed to use Asset Clean Up to prevent them from being loaded.
> 
> At this stage, I still couldn't get mobile over 89 on PSI.
> 
> As usual, elementor was loading e-icons on the site, and as usual (for me) the only thing using e-icons was the mobile hamburger menu.
> 
> Since I was in the mood for experimentation, I replaced Hello with Kadence (but I'm sure GP or Blocksy would've been the same) and replaced the E Pro header with a theme header from Kadence. Kadence doesn't load an icon set for their hamburger icon.
> 
> This allowed me to de-queue e-icons, it also reduced the page size and DOM.
> 
> The change from Hello to a theme with headers took me to a PSI of 95. The removal of e-icons reduced my page size by 20%.
> 
> Last years Iconic release for Elementor should've included the ability to use single SVGs for Hamburger open and close in the Nav. That single change would be hugely impactful for many sites, especially ones that are tuned down to <600k page sizes.
> 
> It also seems like it would be the simplest of all of the options when it comes to dev time and resource.
> 
> Keep pushing the advanced solutions, but don't lose track of the speed "hacks" that people on the sharp end are doing, some simple changes could produce significant gains for you, and win some kudos in the community.



> > Hi all,
> > As mentioned earlier in this thread and in our official blog posts - we take this matter very seriously, therefore the aspects that you raise here are being taken care of:
> > 
> > * Conditionally load libraries (only when used):
> >   
> >   * dialog
> >   * share-links
> >   * screenfull
> >   * lightbox
> >   * sticky
> > * Working on a concept for improved css loading
> > * Minimize e-icons library dramatically
> > * More improvements to come
> > 
> > @MichaelDarko As for the comparisons you shared - it seems like the Improved Asset Load experiment is inactive. it should resolve many of the scripts that are loaded when not used.
> > But as mentioned above - we are aware and as a mature product, we make changes carefully and gradually.
> > If you have any more suggestions on how to improve the loading of assets in Elementor feel free to share them here.
> > Thanks
> 
> I think it's great that you've engaged here in a discussional way - may I offer an anecdotal story about Elementor performance?
> 
> I've tuned many Elementor stacks, and it's always a challenge to get above 89 PSI for mobile, it's almost impossible without significant page caching. And the more caching we add, the more likely something is to break.
> 
> I recently moved an Elementor, E Pro, Hello site to a host with a good page caching solution, so decided to re-optimise the site using the hosts caching stack. It performed very well, but Elementor, even with the new asset loading option selected was still pulling in libraries that I wasn't using.
> 
> So I still needed to use Asset Clean Up to prevent them from being loaded.
> 
> At this stage, I still couldn't get mobile over 89 on PSI.
> 
> As usual, elementor was loading e-icons on the site, and as usual (for me) the only thing using e-icons was the mobile hamburger menu.
> 
> Since I was in the mood for experimentation, I replaced Hello with Kadence (but I'm sure GP or Blocksy would've been the same) and replaced the E Pro header with a theme header from Kadence. Kadence doesn't load an icon set for their hamburger icon.
> 
> This allowed me to de-queue e-icons, it also reduced the page size and DOM.
> 
> The change from Hello to a theme with headers took me to a PSI of 95. The removal of e-icons reduced my page size by 20%.
> 
> Last years Iconic release for Elementor should've included the ability to use single SVGs for Hamburger open and close in the Nav. That single change would be hugely impactful for many sites, especially ones that are tuned down to <600k page sizes.
> 
> It also seems like it would be the simplest of all of the options when it comes to dev time and resource.
> 
> Keep pushing the advanced solutions, but don't lose track of the speed "hacks" that people on the sharp end are doing, some simple changes could produce significant gains for you, and win some kudos in the community.

@mrbenjaminjo I am in the same boat as you. I have been trying various optimizations & hacks to get the mobile PSI over 90. I feel like it is all most impossible for me to score over 90 consistently. I use PerfMatters to deque the unnecessary JS and CSS files. Now I am working on slimming down the CSS files using PurifyCSS online editor. Cut down the file sizes of Elementor Frontend CSS files by half. The frontend js files are still heavy, and I don't want to mess with them.

I also use Happy Addons for Elementor plugin. They use a modular approach which allows you to easily turn off the widgets and features you don't want to use, resulting in slimmer js and css file sizes. That's the way to go. The experimental features certainly help. But still, there is work to be done to be on par with other performant page builders out there.

**Comment by GJKuz** [comment] 2021-05-29 22:45
@shilo-ey Following Elementor's Performance optimization video series I was able to significantly cut down on DOM elements. I had reached out to Support regarding an issue with the Sticky option creating a copy of the DOM tree where sticky is set. Support confirmed that the secondary DOM tree is not at all needed and closed the ticket with a comment that they will pass the info to the Dev Team as an enhancement request. By implementing my own version of the sticky with simple js and CSS, I was able to eliminate the unnecessary section created by the Elementor sticky option. I am sorry to say the DOM tree created by Elementor is bloated to begin with, and issues like sticky creating unnecessary DOM elements doesn't help at all. I really hope, the DEV Team will review the sticky implementation.

**Comment by oguilleux** [comment] 2021-06-22 07:42
Hi ! I'm trying to dequeue scripts & styles on pages where Elementor is not used. I thought it could be activated with "Optimize assets loading" but it's not the case. Can anyone help me out on this one ?

**Comment by shilo-ey** [comment] 2021-07-13 13:57
Hey all,

Thank you for pushing us to improve and extend Elementor essential features such as the ones mentioned above.

Gladly I can share that modular and conditional CSS load has been added to **Elementor v3.3.0** (as an experiment, active by default in new sites, manual activation in existing sites)

We are not stopping here, but we are about to implement a massive reduction in our JS files, and allow font icons to be loaded as inline SVG's 

I'm closing this issue for now because since v3.0.0 we are releasing these improvements as you can see in the following blog post: https://developers.elementor.com/how-elementor-improved-asset-loading-and-made-your-website-run-faster/

Feel free to open a new issue if you encounter a new area that needs optimization.

Thanks!

**Closed by shilo-ey** 2021-07-13 13:57 UTC
Labels: status/merged, type/performance

**Comment by jabeztadesse** [comment] 2024-04-26 04:23
+1
