### ISSUE TITLE
✔️ 🚀 Feature Request: Improve numeric fields to allow individual units, keywords and CSS functions()

### ISSUE THREAD

**Issue by black-eye** [elementor/elementor#2219] opened 2017-08-20 13:25 UTC
Now, when starting to edit margin/padding values, all are set to 0. It would be more convenient to have a possibility to change only individual values and the rest leave as set by default (or as set on previous breakpoint).

E.g.: I have set the column gap to wide, but I need even more space on the top and bottom. So I move to Advanced panel  and unclick the "link values together" option to change the top to 60px. Unfortunalely, all the values are set to 0 and my gap settings are gone.

I know, I can write the values back or do the top-bottom-gap setting other way, this was just an examle. 

This feature would be also useful, when the section's padding/margin defaults are set in template and you want to override only some of the them (and actually not knowing, what the other values are).

Not sure If it is possible, but it would be definitelly a big timesaver.

**Comment by marriott79** [comment] 2017-09-22 06:15
I wholeheartedly second this request!!! The current behavior, where you enter a custom padding amount on one side and then Elementor automatically assumes you want 0s for the remaining sides, is extremely frustrating. I love Elementor, but it shouldn't assume I want 0s for the remaining sides. More often than not, we want the default values to remain intact.

I noticed that Beaver Builder allows you to override padding or margins for each side (top, left, bottom or right) while keeping the default values in place for the remaining sides that you didn't enter a value. 

So, instead of doing this: "padding: 40px 0 0 0;" (what Elementor is currently outputting), it would be preferable if Elementor did this: "padding-top: 40px".

I'm sure many Elementor users don't know what the default column padding values are so they won't know what to replace those 0s with to get the rest of the sides to line up with their other content on the page. I agree this would be a huge timesaver.

**Comment by drank** [comment] 2018-01-27 15:44
+1 on this request. It's been countless times that I try to guess the current paddings by entering them into the boxes just so that I can then switch off the synchronous edit and change only the one that I need.

Please consider making every side isolated.

**Comment by black-eye** [comment] 2018-01-27 15:58
And maybe consider the option to enter mixed units as well. As mentioned here: #2413

**Comment by twiginteractive** [comment] 2019-03-28 16:20
It's getting very frustrating to see so many updates (large and small) to Elementor yet this HUGE gaping hole (that Visual Composer supported from the outset) - still not addressed.

Any plugin rep reading this thread?

**Comment by Helmi** [comment] 2019-03-29 12:24
The whole responsive editing UX is somehow broken and in this case it's not only the UX.

Somehow also connects to #7575 but indeed the issue here makes it even worse.

**Comment by tristanleboss** [comment] 2019-03-31 21:14
Unortunaately, there is no JS API (except a few very basic filters) so its impossible to code something to really alter the editor... like a plugin.

**Comment by yankiara** [comment] 2019-07-03 15:38
Please fix this, this is silly.
So frustrating not to be able to simply and quickly add or remove a padding/margin without having to set every others again.
Even Divi could make it in its early days ;-)

**Comment by twiginteractive** [comment] 2019-07-03 18:48
It's crazy how many releases these guys put out fixing other (smaller) problems, when this is a gaping hole against their competitors. As we are all developers, I think we can guess at the LoE to implement this feature (i.e. not that high) :(

**Comment by black-eye** [comment] 2019-08-20 13:10
OK, today is 2 year anniversary of this issue - happy birthday! 😉 🎂 🎉 
So it's a good day to ask for some news - are there any?

I know, it's not such a crucial problem, but honestly: how difficult this request would be to implement? Just don't fill up zeros when unclicking the "link values together" option and output the values separately ("padding-top: 40px" instead of "padding: 40px 0 0 0;"). How much time this could take?

It seems the next free and pro version will be focused on better CSS editing - this would be a really nice opportunity to implement this feature too.

@bainternet @shilo-ey ?
Thanks

**Comment by twiginteractive** [comment] 2019-08-20 13:16
I'm not convinced anyone from the dev team actually reads these issues, but happy cakeday to this one nonetheless :D

**Comment by qantumthemes** [comment] 2020-01-09 15:11
1 year later, still same issue alive. It seems one of those small tricky bugs to force you go with the Pro support but nobody reported any fix yet. Please let us know clearly if to specify separate margins and paddings we need a pro version. It takes 10 minutes to add the control to our shortcodes, is just a waste of time if it's already done on the master branch.

**Comment by shilo-ey** [comment] 2020-01-09 15:18
We have some plans for this control in the near future. Stay tuned.

**Comment by twiginteractive** [comment] 2020-04-03 17:18
@shilo-ey This is great news - but do you have any more detail on it? I see 2.9.2 is the latest release but this issue still remains. How is this still an open issue when it's so basic? Or am I missing some bigger picture? Could you at least supply some tech info as to why this is hard to implement because it seems pretty straightfoward. Thanks!

**Comment by arwvisions** [comment] 2020-06-24 15:35
This is ridiculous! Should have been fixed A LONG TIME AGO!! ELEMENTOR are you listening?

**Comment by twiginteractive** [comment] 2020-06-24 16:08
@arwvisions Pretty sure they are not. Also pretty sure any dev on this thread could probably whip up a simple split-parameter UI to store these T|R|B|L values... there's either a bigger picture here, or Elem just don't care 🤷

**Comment by arwvisions** [comment] 2020-06-24 16:30
@twiginteractive Yup looks that way. Sucks tho, I love elementor, but I may get outvoted and we switch back to VC :(

**Comment by twiginteractive** [comment] 2020-06-24 18:26
@arwvisions Heh sadly, Elem still crushes VC even with this glaring omission. I was a deep VC dude for a long time (wrote a couple custom widgets etc.) but couldn't go back now just based on this. Ho hum.

**Comment by arwvisions** [comment] 2020-06-24 18:28
@twiginteractive I agree 100% but I'm just a gun for hire :) So not always up to me which plugin we use.

**Comment by gnowland** [comment] 2020-10-01 16:05
I really hope this functionality is added soon...

**Comment by JamieWalkerSTF** [comment] 2021-12-13 02:55
![image](https://user-images.githubusercontent.com/59001525/145744976-d275a25c-a83b-4809-8199-ef4d392c219c.png)

Another thread was merged with this one, even though their points were slightly different. 

I want to be able to add in custom unit types - vmin, vmax, var(--sm-pad);

To add variables to our CSS in the UI would be amazing. Oxygen and Bricks are crushing Elementor with this functionality.

**Comment by eastriverstudio** [comment] 2021-12-23 15:11
The fact the editor is still constrained to one type of margin/padding unit control in 2021/22 is really a bizarre one. 

For the most part I've managed to get by with the way it is, but this is probably one of those small UI/UX things using Elementor that crops up regularly for me and makes me so frustrated I'm stuck with a single unit option for all. 

I can only hope that with the new container layout engine coming this situation will be improved at the same. I shouldn't have to resort to custom code if I want to for example have fixed pixel padding top/bottom, but percentage values left/right, or even better have a manual option to use calc or var values etc. I think all other builders that are a serious competitiion to Elementor have this level of control now.

The last update on this from Elementor was back in early 2020 and this is still open without feedback or resolution, so @shilo-ey @bainternet @DorShahar come on, do you have any updates for us in relation to new container layouts and whether we can expect improved margin/padding controls any time soon?

Thanks

**Comment by twiginteractive** [comment] 2021-12-23 22:00
@eastriverstudio Sadly the Elementor devs don't watch these threads. This issue was reported almost FIVE YEARS AGO, and is such a trivial implementation it should have been taken care of by now. Visual Composer is a clunky dinosaur compared to Elementor, but they manged this "impossible task" before this ticket was even open :(

**Comment by Michaelgimii** [comment] 2022-11-23 13:47
Hi @arielk , Can we use calc values ​​in width fields using this feature that will be added in version 3.10?
Also, in the margin and padding fields, can we use auto values?

thank you in advance

**Comment by arielk** [comment] 2022-11-23 16:32
Hi @Michaelgimii,

> Can we use "calc" values ​​in width fields using this feature that will be added in version 3.10? 

Yes :)

> Also, in the margin and padding fields, can we use auto values?

Yes ;)

Basically we are working on it these days, I hope everything will go well for v3.10

**Comment by Michaelgimii** [comment] 2022-11-23 16:40
This is really great. thank you @arielk❤

**Comment by twiginteractive** [comment] 2022-11-23 19:48
We reported this issue over 4 years ago - can't wait to see a fix! 🤞🏻

**Comment by nerdtech** [comment] 2022-12-09 13:50
I'm glad to see this is being worked on it's even more vital now we have flexbox which doesn't take gap subtraction into account.

**Comment by arielk** [comment] 2022-12-11 13:31
Hi All,

We have just merged a new tweak that solve this issue for the next version 3.10 (beta soon), please see the screenshot

https://user-images.githubusercontent.com/1778512/206906497-fb879871-7db5-49c9-965b-b1cbcf502cb5.mov

**Comment by black-eye** [comment] 2022-12-11 14:31
@arielk OK, that§s nice, but please don§t forget, that the original purpose and title of this issue was "[Feature request] Individual margin/padding values". Will this issue be resolved as well?

**Comment by arielk** [comment] 2022-12-11 15:14
@black-eye Sure! see here:


https://user-images.githubusercontent.com/1778512/206911850-a07e2440-f025-47de-b3eb-e9c8bd0caddf.mp4

**Comment by black-eye** [comment] 2022-12-11 15:36
@arielk OK, good. And what about the situation, when I want to change only some of the paddings/margins, e.g. TOP? From the video it seems, that the moment you unlink the values (the chain icon) all the values are still reset to zeroes. This is very unfortunate solution... :-(

**Comment by arielk** [comment] 2022-12-11 17:11
@black-eye You must choose a value for each dimension, that's how CSS works. Course we can refactor the control from scratch, but we preferred to keep it as it is for backwards compatibility.

**Comment by arielk** [comment] 2022-12-11 17:49
@black-eye indeed. Now I see that this issue has changed a lot over the last 5 years!

But going back to the original request, unfortunately we can't do that at this point because we're parsing the data in a different way, but let me look into that again.

Thanks

**Comment by Soluna1989** [comment] 2022-12-11 19:05
I´m actually really happy about the possibility to use calc in different fields. The way you showed it in the videos above is already amazing imo and I´m really looking forward to having that feature in Elementor! To me this is a huge deal so I´m already really greatful for getting this soon!

And personally I don´t have a big problem with typing in the values again if you unlink them. Sure it´d be nice if they stayed but you can always check what´s in the fields before you unlink them and then re-add those values again quickly. 

So yea, already a huge thanks to the devs for implementing the calc-feature!! ❤

**Comment by 79ho3ein** [comment] 2022-12-11 19:09
Excellent updates. Thank you @arielk.

**Comment by Michaelgimii** [comment] 2022-12-11 19:12
Wow I'm so excited! @arielk 
Is it known when the beta version will be released? approx

**Comment by arielk** [comment] 2022-12-11 20:25
> Wow I'm so excited! @arielk Is it known when the beta version will be released? approx

Hopefully this week.

**Comment by Michaelgimii** [comment] 2022-12-12 15:46
Hi again @arielk.
I thought that the [slider](https://prnt.sc/erS4UqLcf9Z-) in the field of width, height and Gap between elements, etc. will be removed from Elementor forever. Because I don't think users will use it to determine the width. So, do you have any plans to remove it in future versions?
As a suggestion, it's great if you poll users sometimes, to reach a conclusion. For example, whether they use the slider in the width, height, etc. fields or not. thanks!

**Comment by otomasz** [comment] 2023-01-08 11:57
> > @black-eyerzeczywiście. Teraz widzę, że ta kwestia bardzo się zmieniła przez ostatnie 5 lat!
> > Ale wracając do pierwotnej prośby, niestety nie możemy tego zrobić w tym momencie, ponieważ analizujemy dane w inny sposób, ale pozwólcie, że przyjrzę się temu ponownie.
> > Dzięki
> 
> @arielk Czy byłoby możliwe **ustawienie wartości domyślnych na te, które już widzimy na szaro** ?
> 
> Na przykład, jeśli na pulpicie dodałem dopełnienie `10 15 10 15`px, to widzę to jako wyszarzone wartości, gdy przełączam się na inny punkt przerwania. Byłoby wspaniale, gdyby były to wartości domyślne, gdy rozpakowuję, zamiast po prostu nadpisywać wszystko za pomocą `0 0 0 0`px.

**this option was a real game changer**

**Comment by curlygirly1** [comment] 2023-01-10 06:16
upgrading elementor plugin to v3.10 is a nightmare of bugs. all these numeric fields have silly little pencils all over the place, no tine up/down arrows all gone and had to downgrade for sanity. shameful thing to release such an ugly
![2023-01-09_DUMB-ELEMENTOR-UPDATE-FUCKED-UP-EDITOR](https://user-images.githubusercontent.com/14815195/211475669-3e88d557-cbbc-4860-87da-7b76be3229ed.jpg)
 buggy interface.

**Comment by raabmar** [comment] 2023-01-10 06:43
@curlygirly1 just tested on a dev site .. yes there was a change, I remember a big discussion about this on github I think but it's not looking like it shows on your screenshot

<img width="297" alt="image" src="https://user-images.githubusercontent.com/15885290/211479693-d59c9d56-1493-4cf6-b785-5801a6c5ec5e.png">

**Comment by Soluna1989** [comment] 2023-01-10 06:44
@curlygirly1 I just checked on 3 of my sites and I don´t have these kinds of problems. On my sites everything looks great. I don´t even have these radio buttons that I can see in your pictures. I only have one unit that I can click on to change it (e.g. from "px" to "%" or to the pencil where I can set custom values). For me it looks just like the screenshot that @raabmar showed.

**Comment by curlygirly1** [comment] 2023-01-10 06:49
@raabmar @Soluna1989 hmm. Have you the pro plugin or just the free one? I had to revert back to free v3.9.2 and left pro at 3.10 and all is fine again as was before the latest features

**Comment by raabmar** [comment] 2023-01-10 06:54
> @raabmar @Soluna1989 hmm. Have you the pro plugin or just the free one? I had to revert back to free v3.9.2 and left pro at 3.10 and all is fine again as was before the latest features

Just updates pro as well as I didn't do that before - all still looking good
<img width="1201" alt="image" src="https://user-images.githubusercontent.com/15885290/211481881-0ef2fc36-6051-4995-984e-3ca062560df0.png">

Disabled Elementor Pro just for testing → also still looking good

**Comment by Soluna1989** [comment] 2023-01-10 06:58
@curlygirly1 I'm on Elementor 3.10.0 and Elementor Pro 3.10.1 now, so yea. I have the pro plugin installed on all of my sites.

**Comment by curlygirly1** [comment] 2023-01-10 07:21
@Soluna1989 @raabmar 
![image](https://user-images.githubusercontent.com/14815195/211486721-52da9f5a-4c01-46b0-aef8-2781625d2eef.png)

I checked another site and all is fine there. But as you see on this one, it thinks I have a different version then the pro installed! bizarre

**Comment by nicholaszein** [comment] 2023-01-11 15:46
> upgrading elementor plugin to v3.10 is a nightmare of bugs. all these numeric fields have silly little pencils all over the place, no tine up/down arrows all gone and had to downgrade for sanity. shameful thing to release such an ugly buggy interface.

Hello @curlygirly1,

please clear your server cache and also your browser cache. What you're seeing is not caused by Elementor.

**Comment by nicholaszein** [comment] 2023-01-11 15:50
> Would it be possible to **set the default values to the one we already see greyed out**?
> 
> For example if on desktop I added a padding of `10 15 10 15` px than I see that as greyed out values when I switch to a different breakpoint. It would be great if these would then be the default values when I unchain instead of just overwriting everything with `0 0 0 0` px.

Hello @brittaweller,

we have no plans to change this behavior for the time being.

**Comment by nicholaszein** [comment] 2023-01-11 15:51
Hello, everyone!

We have great news! 🙌 

### 📢 We're happy to announce that this feature was introduced with Elementor **v3.10**! 🥳 

✔️ Please feel free to check it out and update your plugin to the new version!

Cheers 🥂

**Closed by nicholaszein** 2023-01-11 15:51 UTC
Labels: request/enhancement, type/ui/ux, status/merged, type/design, type/layout, 🚀 shipped, solved_by_custom_units

**Comment by black-eye** [comment] 2023-01-11 16:15
> Hello, everyone!
> 
> We have great news! 🙌
> ### 📢 We're happy to announce that this feature was introduced with Elementor **v3.10**! 🥳
> 
> You can learn more about the new Custom Units [here](https://developers.elementor.com/elementor-3-10-beta/).
> 
> ✔️ Please feel free to check it out and update your plugin to the new version!
> 
> Cheers 🥂

Well again - the original reguest was to be able to fill in only one of the values and leave the rest untouched (meaning don't replace it by zeroes). Every other feature which was added here during the lifetime of this issue was added, except the original one...

**Comment by puregraphx** [comment] 2023-01-18 09:39
> > Hello, everyone!
> > We have great news! 🙌
> > ### 📢 We're happy to announce that this feature was introduced with Elementor **v3.10**! 🥳
> > You can learn more about the new Custom Units [here](https://developers.elementor.com/elementor-3-10-beta/).
> > ✔️ Please feel free to check it out and update your plugin to the new version!
> > Cheers 🥂
> 
> Well again - the original reguest was to be able to fill in only one of the values and leave the rest untouched (meaning don't replace them by zeroes). Every other feature which was added here during the lifetime of this issue was added, except the original one...

True, I thought I just missed something in Elementor, but the values of larger devices still gets reset to 0 when you unlink the values on smaller devices :(
