### ISSUE TITLE
Moving Yoast panel

### ISSUE THREAD

**Issue by Malco1** [elementor/elementor#10847] opened 2020-03-14 12:01 UTC
Hi guys

I wonder if you can help. I'm trying to move Yoast panel to the bottom of the page after various custom fields I've been creating. I've read that you can put something like this into the Theme's function.php file:

(// shove YOAST settings panel in editor to bottom
add_filter( 'wpseo_metabox_prio', function() { return 'low'; } );

Does this code look correct to you in order to achieve the desired effect? Also, where would I find Elementor's function.php file anyway? (Yes I'm a bit of a newbie to coding!)

Hoping someone can help.
Malco

**Comment by arielk** [comment] 2020-07-22 20:09
Duplicate of #7130

**Closed by arielk** 2020-07-22 20:09 UTC
