### ISSUE TITLE
Heading color issue after Elementor v3.4.1 update

### ISSUE THREAD

**Issue by abhishek-bsf** [elementor/elementor#16070] opened 2021-08-19 14:24 UTC
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description
An issue with Heading color after Elementor v3.4.1 update. Different color is applied to Heading in Editor and on Front-end.

**Heading Color in Editor:** 
![Screenshot from 2021-08-19 19-31-36](https://user-images.githubusercontent.com/57793460/130085335-0f3edfce-5db0-4fbe-9884-b648adb39803.png)

**Heading Color on Front-end:**
![Screenshot from 2021-08-19 19-31-59](https://user-images.githubusercontent.com/57793460/130085435-7db47076-5690-4463-a3a5-5eafd3985848.png)

## Steps to reproduce
1. Add the Heading widget on any page using Elementor editor.
2. Now compare the color of Heading in Editor and on Front-end. Different color is applied to Heading on Front-end.
3. It was working properly with Elementor v3.4.0

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by VadymPogorelov** [comment] 2021-08-19 14:47
The problem isn't just with the headings. SVG icons behave in a similar way - the Elementor paints them all in the global primary color: http://joxi.ru/v29zoxeHRwBY6A
And the color of the icon is not assigned in the editor: http://joxi.ru/KAxDNvRtvjxbQA

**Comment by saltymedic** [comment] 2021-08-19 17:02
I've found this happening to me as well. I went ahead and changed the text color back for the heading. The update had changed it to blue. Even after making this change, you can see in my screenshot that the color showing in the edit page doesn't reflect what the actual page looks like. Yes cookies and cache cleared.

![Screenshot_20210819_105700](https://user-images.githubusercontent.com/18824694/130111884-fa9bd702-334f-424a-983f-1d62044d43d1.png)
![Screenshot_20210819_105903](https://user-images.githubusercontent.com/18824694/130111905-4148c1f3-3e4f-44cf-8cca-ffdf928ee093.png)

**Comment by jonathansoltero** [comment] 2021-08-19 21:02
Same here! It is showing the incorrect color on the front end! This was an issue in the past and now it's back...

**Comment by TRADEREXDE** [comment] 2021-08-20 08:03
i still have this issue even with 3.4.2

**Comment by jonathansoltero** [comment] 2021-08-20 17:58
I disabled "Improved CSS Loading" and the issue is gone.

Disabling that experiment resolved a bunch of front-end styling issues I was having.

**Comment by iStuff0** [comment] 2021-08-21 06:45
Disabling improved CSS loading fix the problem for me as well. Thank you!

**Comment by saltymedic** [comment] 2021-08-21 17:04
The update fixed my problem

Thank you

**Comment by VadymPogorelov** [comment] 2021-08-23 08:15
The update 3.4.2 fixed the problem.

Thanks

**Comment by DorShahar** [comment] 2021-08-23 08:56
Thanks for reporting.
Closing the issue.

**Closed by DorShahar** 2021-08-23 08:56 UTC

**Comment by MichaelDarko** [comment] 2021-08-24 14:27
It's not resolved, why do you keep closing issues related to this bug? Same with #16037, where many people are telling you it's not fixed, but it's closed anyway.

**Comment by aligations** [comment] 2022-01-02 23:46
A.  I do not know how to disable "Improved CSS Loading". I do not see it in the Dashboard...where does one do this?!?
B.  I am using 3.5.2, so I have to disagree that it has been fixed, unless the issue was RE-introduced after 3.4.2?  I don't think this has been fixed.
