### ISSUE TITLE
🔗 🚀 Feature request: Elementor form integration with custom post type fields (Duplicate of #1686)

### ISSUE THREAD

**Issue by srcek** [elementor/elementor#4405] opened 2018-05-09 21:16 UTC
I'd like a feature that would connect Elementor form fields with custom post type fields.

The feature could work the similar way like MailChimp integration only locally. User would have to create the fields in Elementor form and then have capability to map those to custom post type fields he already created in ACF or Pods.

That way site users could submit data to custom post types from the website front end. It would offer interesting capabilities. For example, displaying that data in some sort of list or table on the front end. Like user comments or suggestion, but with more predefined fields.

Thank you.

**Comment by bainternet** [comment] 2018-05-10 06:30
Duplicate of #1686

**Closed by bainternet** 2018-05-10 06:30 UTC
