### ISSUE TITLE
Template Widget (Pro) does not find any template

### ISSUE THREAD

**Issue by lucafagherazzi** [elementor/elementor#8661] opened 2019-07-23 13:42 UTC
Hi, upgrading to Elementor Pro 2.6.0 didn't solve the problem with the Template Widget (Pro). I have the same problem on all the updated sites.
Thank you!

![Template-Widget](https://user-images.githubusercontent.com/40598133/61716825-3b028f80-ad60-11e9-8da6-b5c2d7908df8.jpg)

					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Percona Server (GPL), Release 86.0, Revision eba1b3f v5.6.44-86.0
	PHP Version: 7.2.17
	PHP Max Input Vars: 1000
	PHP Max Post Size: 30M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.2.2
	Site URL: https://www.lucafagherazzi.it
	Home URL: https://www.lucafagherazzi.it
	WP Multisite: No
	Max Upload Size: 30 MB
	Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: it-IT
	Timezone: Europe/Rome
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.2.0
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: it_IT
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 2.6.6
		Author: Elementor.com

	Elementor Pro
		Version: 2.6.0
		Author: Elementor.com

	Google Analytics for WordPress by MonsterInsights
		Version: 7.7.1
		Author: MonsterInsights

	Lazy Load by WP Rocket
		Version: 2.2.2
		Author: WP Rocket

	WP Fastest Cache
		Version: 0.8.9.6
		Author: Emre Vona

	Yoast SEO
		Version: 11.7
		Author: Team Yoast

**Comment by srdesigns** [comment] 2019-07-23 19:51
Can confirm - I'm experiencing the same issue, and only after updating to the latest version. If I find any fixes aside from downgrading, I'll post here.

**Comment by razvanwaterford** [comment] 2019-07-24 07:10
Confirm, same issue

**Comment by eladore** [comment] 2019-07-24 08:26
It is even worse. Is also doesn't find any terms in query fields. Seem that search fileds for templates, terms... are totally broken....

**Comment by shilo-ey** [comment] 2019-07-24 11:38
Thanks for reporting.

We will address this issue soon and release a patch.

Please follow this thread for updates.

Thanks!

**Comment by shilo-ey** [comment] 2019-07-24 14:45
This issue has been resolved in Elementor Pro v2.6.1

Feel free to update

Thanks!

**Closed by shilo-ey** 2019-07-24 14:45 UTC
Labels: status/has_pr

**Comment by eladore** [comment] 2019-07-25 06:45
Ok that would be great but the update crashed my whole server. Could not even login to Wordpress admin anymore. I updated elementar pro first and then wanted to update elementor but after the pro update it stopped working. 

The site is experiencing technical difficulties.

I also didn’t get a recovery link.
And now?

**Comment by shilo-ey** [comment] 2019-07-25 06:58
@eladore 

Please contact our support at support @elementor.com for guidance in resolving this issue and mention that you were directed by me and reference this issue.

thanks.

**Comment by eladore** [comment] 2019-07-25 08:35
@shilo-ey Thank you I did that. 
Hope we will get it to run again without loosing all my sites and templates... i've put weeks of work into that stuff.  really worried at the moment...

**Comment by Visiodot** [comment] 2019-07-25 16:12
The problem is complete resolved, i have the same problem white the template widget and whit extern elemntor plugins like elementor extras. and the finder not find in all of my sites the elements
<img width="1564" alt="Schermata 2019-07-25 alle 18 10 54" src="https://user-images.githubusercontent.com/53310373/61890374-a20e7880-af07-11e9-8644-608c633d8fa3.png">
<img width="978" alt="Schermata 2019-07-25 alle 18 10 44" src="https://user-images.githubusercontent.com/53310373/61890383-a76bc300-af07-11e9-840b-da4fd0f1a57c.png">
<img width="1650" alt="Schermata 2019-07-25 alle 18 10 24" src="https://user-images.githubusercontent.com/53310373/61890393-ac307700-af07-11e9-9deb-9268047b8c8a.png">
<img width="1439" alt="Schermata 2019-07-25 alle 18 09 06" src="https://user-images.githubusercontent.com/53310373/61890408-b0f52b00-af07-11e9-8233-c5b6d03fc565.png">
<img width="1175" alt="Schermata 2019-07-25 alle 18 07 27" src="https://user-images.githubusercontent.com/53310373/61890428-bb172980-af07-11e9-9d7b-f9cc5f7647c4.png">

**Comment by eladore** [comment] 2019-07-26 06:59
Visiodot is right. After getting my server to work again and updated posts extra still doesn't find the templates. Also a problem now it has proplems with advanced custom fields which don't work inside of the dynamic text options. You can select them but then on the page it becomes empty...

**Comment by laboiteare** [comment] 2019-07-29 08:20
Hi, I can confirm eladore, it breaks elementor extras post (template search + Acf).

Please make something.

**Comment by Visiodot** [comment] 2019-07-29 15:11
i have solve whit a downgrade for now

**Comment by ideasandpixels** [comment] 2020-08-31 20:01
This is still happening!
