### ISSUE TITLE
🚀 Feature Request: padding control for popup close button and one more

### ISSUE THREAD

**Issue by Michaelgimii** [elementor/elementor#18953] opened 2022-06-18 06:03 UTC
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

Please add padding control to the pop-up closure button : https://prnt.sc/8gbWp1LBfMlw
Also great if you can add a custom icon to the close popup button. 

### Describe the solution you'd like

1- padding control for popup close button
2- custom icon for close popup button

**Comment by rami-elementor** [comment] 2022-06-28 08:59
Duplicate of #18976

**Closed by rami-elementor** 2022-06-28 08:59 UTC
Labels: request/enhancement, component/popup
