### ISSUE TITLE
Custom Widget Category Order

### ISSUE THREAD

**Issue by Orrison** [elementor/elementor#9042] opened 2019-09-09 23:46 UTC
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
I am looking for a way to programmatically change the order of the Widget Categories in Elementor post/page editing.

I have added a custom category but there does not seem to be a documented way to change it's in the list of category sections.

**Describe the solution you'd like**
A parameter to set custom widgets order or weight in $elements_manager->add_category method. Or a JS hook for the panel when the widget category sections are loaded so they can be moved with JS.

**Describe alternatives you've considered**
Changing the order with CSS flex order but that is not accessible friendly and requires all categories be accounted for when ordering.

Move my categories DIV with JS but there is not a good JS hook to get into for when those are loaded.

**Additional context**
https://developers.elementor.com/widget-categories/

**Comment by bainternet** [comment] 2019-09-10 07:26
Duplicate of #7445

**Comment by bainternet** [comment] 2019-09-10 07:27
@Orrison 

Thanks for the feedback,
Please follow guidelines for opening a new [feature request](https://github.com/pojome/elementor/issues/new?template=Feature_request.md), so we can help you better.
This report is missing key information: 

* Prerequisites.


As for your request, see this: https://github.com/elementor/elementor/pull/7447#issuecomment-502439895

thanks.

**Closed by bainternet** 2019-09-10 07:27 UTC
