### ISSUE TITLE
Image Widget

### ISSUE THREAD

**Issue by stormit** [elementor/elementor#17884] opened 2022-02-19 06:09 UTC
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

Hello,

I have a request. Can you add the [loading](https://www.w3schools.com/tags/att_img_loading.asp) attribute (loading="lazy") to image html if we choose custom size (_Group_Control_Image_Size::get_attachment_image_html()_)?

Thank you!

### Describe the solution you'd like

Add loading attribute to img tag

**Comment by rami-elementor** [comment] 2022-02-21 20:10
Duplicate of #16753

**Closed by rami-elementor** 2022-02-21 20:10 UTC
Labels: request/enhancement, type/performance
