### ISSUE TITLE
[Feature Request] Conditions for displaying elements

### ISSUE THREAD

**Issue by lcswillems** [elementor/elementor#7271] opened 2019-03-02 12:06 UTC
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

I would like to display only the custom fields that are filled.

**Describe the solution you'd like**

I would like to have a condition in order to define when I want an element to be displayed.

**Describe alternatives you've considered**

I don't see any alternative.

**Comment by bainternet** [comment] 2019-03-03 08:22
Duplicate of #4246

**Closed by bainternet** 2019-03-03 08:22 UTC

**Comment by nicholaszein** [comment] 2024-04-12 06:34
Hello!

### 📢 We're happy to announce that the issue you raised was resolved in Elementor Pro v3.19.0, and improved with Elementor Pro 3.20.0! 🥳 

You can now use Display Conditions for widgets based on a variety of conditions, including date, time, user role, logged in/out, and others (more to come too). Check the [documentation for the new Display Conditions](https://elementor.com/help/show-and-hide-elements-on-a-page-display-conditions/) for widgets (Pro).

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
