### ISSUE TITLE
Add Posts Caroussel

### ISSUE THREAD

**Issue by moisesrox** [elementor/elementor#12017] opened 2020-08-03 13:06 UTC
Please add posts caroussel.

**Comment by arielk** [comment] 2020-08-05 15:30
Duplicate of https://github.com/elementor/elementor/issues/219

**Closed by arielk** 2020-08-05 15:30 UTC

**Comment by nicholaszein** [comment] 2023-02-13 17:23
Hello there!

We have great news! 🙌 

### 📢 We're happy to announce that this feature was released with Elementor Pro v3.11! 🥳 

✔️ Feel free to check it out and update your plugin to the new version!

Cheers 🥂
