### ISSUE TITLE
Get Label of selected option in label|value configuration

### ISSUE THREAD

**Issue by iffifan** [elementor/elementor#9127] opened 2019-09-19 04:37 UTC
## Prerequisites

- [x ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

**Describe the solution you'd like**

I am building a contact us form and have added department option and email will go to selected department.
for example: 

> technical -> technical@domain.com,general@domain.com
> commercial -> commercial@domain.com,general@domain.com
> administrative -> administrative@domain.com,general@domain.com
> info -> info@domain.com,general@domain.com

i wrote this as options:

```
technical|technical@domain.com,general@domain.com
commercial|commercial@domain.com,general@domain.com
administrative|administrative@domain.com,general@domain.com
info|info@domain.com,general@domain.com
```

I have added `[field id="department"]` as email to value.

This works fine. 

I just want to know which option user has selected. I mean the label of selected option. Ithink this feature is missing.

**Describe alternatives you've considered**

I tried to find this feature in docs, in issues here and on internet. I did not find this feature

**Additional context**

**Comment by bainternet** [comment] 2019-09-19 07:27
Duplicate of #5771

more specifically https://github.com/elementor/elementor/issues/5771#issuecomment-423168465

**Closed by bainternet** 2019-09-19 07:27 UTC

**Comment by iffifan** [comment] 2019-09-19 09:39
@bainternet I actually looked into that issue. 
Solution provided there returns label:value which cannot be useful in either mail to field or in mail content. 
I want `[field id="department"]` to work as it is doing right now. I mean returning value provided after pipe.
Can I also just get only the label somehow?

**Comment by iffifan** [comment] 2019-09-20 00:27
@bainternet  You were too eager to close this ticket but honestly I was asking for a feature like we have in contact form 7

https://contactform7.com/selectable-recipient-with-pipes/

In the end they mentioned:

> To get the value after pipe character, put the usual mail tag corresponding to the form tag ([your-recipient] in the case of the above example) in the Mail templates. To get value before pipe, you can use [_raw_{field name}] ([_raw_your-recipient] in the case of the above example).

**Comment by trackingview** [comment] 2023-06-09 09:46
I made solution : create an hidden field and insert javascript (thanks to HTML Widget) which update the value of hidden field every time that the user select a value in the "Select Field".

`<script>
document.addEventListener('DOMContentLoaded', function() {
  const selectField = document.querySelector('select[name="form_fields[department]"]');
  const hiddenField = document.querySelector('input[name="form_fields[hidden_field]"]');

  if (selectField && hiddenField) {
    selectField.addEventListener('change', function() {
      const selectedOption = this.options[this.selectedIndex];
      hiddenField.value = selectedOption.text;
    });
  }
});
</script>`
