### ISSUE TITLE
🔗 ❌  🐞 Loop Grid Masonry Pagination Problem (Duplicate of #23684) - [ED-12229]

### ISSUE THREAD

**Issue by CevdetE** [elementor/elementor#25244] opened 2024-02-22 12:10 UTC
### Prerequisites

- [X] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [X] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

Normally it shows as expected:
![image](https://github.com/elementor/elementor/assets/73752008/b6245631-100b-4b1e-960e-79556ebc0a1b)

When you click the Load more or set it to the Infinity Scroll loaded elements look like this:
![image](https://github.com/elementor/elementor/assets/73752008/0ab0218c-3934-469f-96c5-5e7d06cf3013)

### Steps to reproduce

1. Create a loop grid section with 2 taxonomy filters with more than 20 item
2. Set the Items Per Page to 10 in Layout
3. Select Load More or Infinite Scroll on Pagination

### Expected behavior

1. Masonry should be applied the loaded items

### Isolating the problem

- [X] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [ ] This bug happens with the Hello Elementor theme active.
- [X] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

```txt
Elementor Version 3.19.2
Theme: Borgholm
```

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by ofmarconi** [comment] 2024-03-05 22:36
I'm also facing this, is there any way to restart the script that calculates the negative margin? I can't find the documentation.

**Comment by nicholaszein** [comment] 2024-03-17 08:37
Hello @CevdetE!

Thank you for your submission! 🙏 

### 🔗 🐞 This issue is a Duplicate of #23684

Which is on the same subject. 

For this reason, I'm closing this thread and 🔃 **Merging** it with the original, so we can have all the discussions in one location, and deal with it more efficiently.

Feel free to continue the conversation there. 😉 

### 🔍 Please, in the future, remember to check if there isn't any thread similar to yours already opened. 

----

We appreciate your involvement in our community. For efficient troubleshooting, please remember to include the **<br /><ins>FULL, and essential</ins> [System Info](https://elementor.com/help/hare-my-system-info/)** with each issue reported. We'll need it to help you effectively. 

#### ⚠️ As a gentle reminder, issues without it may need to be closed without troubleshooting. Providing this information upfront aligns with our guidelines, saves time, and ensures swift resolution. Thank you for understanding.

Kind regards

**Closed by nicholaszein** 2024-03-17 08:37 UTC
Labels: product/pro, type/layout, widget/loop-builder, mod*, widget/loop-builder/pagination, duplicate
