### ISSUE TITLE
3.3.0 / 3.3.2 Uneditable widgets in some posts

### ISSUE THREAD

**Issue by iStuff0** [elementor/elementor#15648] opened 2021-07-14 14:14 UTC
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

The widgets in some posts (heading, image, text) are uneditable. As in, clicking on them does nothing and it's like i haven't clicked anything. 

Duplicating any of these non-functional widgets duplicates all widgets in the same column, which makes them editable, But on page reload they become uneditable again.

## Steps to reproduce

I don't know because many posts are working fine but many are not. I haven't noticed a pattern.

## Isolating the problem
- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [ ] I can reproduce this bug consistently using the steps above.

## Environment

https://pastebin.com/6WxKvgcU

**Comment by Aviad-Herman** [comment] 2021-07-14 14:28
Hi,
Of course we want to fix this ASAP but we need more information.

First of all, please:
- Deactivate all plugins
- Use elementor default theme
- Turn off all Elementor Experiments (WP dash > Elementor > Settings > Experiments)

Is the problem solved?

**Comment by Aviad-Herman** [comment] 2021-07-14 14:30
As a next step, please see if the bug occurs only on existing pages or also on brand new pages.

**Comment by iStuff0** [comment] 2021-07-14 16:29
Yes, i tried those 3 things before posting initially. It didn't help.

It hasn't happened on newly created pages (tried 3 times).

It looks like something to do with a global widget (which is an image i have scattered in various places throughout the site) found at the bottom of the affected posts, because deleting this widget, saving the page, then reloading the page allows all widgets to be editable. This has worked 3 times on 3 different posts.

**Comment by Aviad-Herman** [comment] 2021-07-14 18:41
Wow amazing investigative work!
I will pass this info to dev ASAP

**Comment by etorabi** [comment] 2021-07-15 22:04
I am having the same problem and believe I may have found the cause of the issue and how to reproduce the bug, which appears to have come up with the recent update.

This seems to happen when there is a Global Element within a section. After inserting a Global Element, and then saving and refreshing or reloading the Elementor Editor, additional elements within the section cannot be edited. In fact, they cannot even be selected, and trying to do so instead only selects the entire column.

Only by "un-linking" the global element, and saving and refreshing, can items within the section be selected and edited.

To recreate the error » 1) Create a section and insert elements, including a Global Element. 2) Save and refresh. 3) Try to edit elements within that section.

Please push this up and escalate, and let us know, as this bug is making Global Elements largely unusable at the moment.

Thanks and blessed regards!

**Comment by Mal027** [comment] 2021-07-17 00:11
I had also experienced this issue and have since reverted back to v3.2.5. due to the bug. I had mentioned in another thread, but when attempting to duplicate items, it would duplicate the entire section instead. Some widgets, particularly the global widgets, would not load their preview on some pages.

**Comment by iStuff0** [comment] 2021-07-17 08:00
I'm using the workaround of selecting an uneditable widget, deleting, then undoing. They become editable.

My global widgets don't show their preview either. Got grey bars all over the place. Kinda got used to it.

**Comment by dibeja** [comment] 2021-07-19 07:47
I confirm this problem. Please fix it cause the editor has become unusable when there are global widgets in a page

**Comment by Aviad-Herman** [comment] 2021-07-19 07:59
Hi everyone, 
Thanks for sharing. We will release a hotfix for this.
In case it only solves some of the bugs, we will release another one soon after.
Stay tuned on this thread.

Thanks again,

**Comment by shilo-ey** [comment] 2021-07-20 15:48
This issue has been resolved in Elementor v3.3.1

Feel free to update

Thanks!

**Closed by shilo-ey** 2021-07-20 15:48 UTC
Labels: status/has_pr
