### ISSUE TITLE
Bugged popup.

### ISSUE THREAD

**Issue by codeorlov** [elementor/elementor#11555] opened 2020-06-08 08:00 UTC
Hello everyone! I have a problem with off canvas menu (done with Elementor's popup). Almost everytime I close the popup it blinks at the end. How could I fix it? It blinks in Chrome on 3 of my mobile devices. On Firefox and Safari it's ok. My client wants me to fix it but I don't know how. Do you have any ideas?
And also, look what nonsense happens with pop-ups if you press them quickly.
Website: https://trade-secrets.com.ua
Video in .zip:
[video problem.zip](https://github.com/elementor/elementor/files/4744660/video.problem.zip)

**The site uses only the hello and elementor themes.**

**Comment by lior-sh** [comment] 2020-06-08 09:17
Hi @codeorlov,

Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information:
* Prerequisites.
* **Steps to replicate**.
* Isolating the problem.
* **System info**.
* One issue per thread
Without it, we simply can't help.
Thanks.

**Comment by codeorlov** [comment] 2020-06-08 10:09
@lior-sh :
**+** The issue still exists against the latest stable version of Elementor.
**+** I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
**+** This bug happens with only Elementor plugin active (and Elementor Pro).
**You can repeat this by adding a popup like mine, I use it as a menu, please watch the video.**

**Comment by lior-sh** [comment] 2020-06-08 11:26
Hi @codeorlov,

Thanks for reporting, we couldn't reproduce the issue. As I wrote above this report is missing key information:
Prerequisites.
**Steps to replicate.**
Isolating the problem.
**System info**.
One issue per thread
Without it, we simply can't help.
Thanks.

**Comment by codeorlov** [comment] 2020-06-08 11:35
@lior-sh this is a joke? I provided information about the system in the file above, to reproduce the problem, just create a new pop-up as if it were a mobile menu and try to quickly open and close it. What information do you still need?

**Comment by lukealexander93** [comment] 2020-06-17 13:33
I have also noticed this blinking issue and my pop up is shooting to the top of the webpage when triggered. Has anyone found a solution yet?

**Comment by lior-sh** [comment] 2020-06-18 09:44
Duplicate of #11667

**Closed by lior-sh** 2020-06-18 09:44 UTC
