### ISSUE TITLE
Feature Request: Add Link Field to Columns

### ISSUE THREAD

**Issue by mfrapp20** [elementor/elementor#9495] opened 2019-11-05 22:44 UTC
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

I have had to download a separate plugin to make it so I could apply a link to an entire column instead of just one element. This is a pain because it increases the amount of database requests on my website goenergylink.com.

**Describe the solution you'd like**

Add a link field to columns.

**Describe alternatives you've considered**

As mentioned above, the only alternative is to download a plugin for this purpose. It would be best to make it so this is not needed.

**Additional context**

No additional context is needed.

**Comment by shilo-ey** [comment] 2019-11-08 14:08
Duplicate of #351

**Closed by shilo-ey** 2019-11-08 14:08 UTC
