### ISSUE TITLE
nav pop up menu display issues on mobile on 3.3.5

### ISSUE THREAD

**Issue by okikiola12** [elementor/elementor#15870] opened 2021-08-03 04:46 UTC
after this recent update 3.3.5, 
nav menu display is at the base of the page when clicked.
page background color change to grey and some other css glitch.

**Comment by d19dotca** [comment] 2021-08-03 06:28
I don't experience this issue at all on any of my Elementor sites. It would be helpful to everyone (Elementor team in particular) if you included screenshots of the issue and your system info, etc.

**Comment by okikiola12** [comment] 2021-08-03 14:03
Hi dustin,
Attach is the screenshot requested..

That is on Mobile..


for authentication please follow this link   
https://www.autruo.com/

Sent from Mail for Windows 10

**Comment by okikiola12** [comment] 2021-08-03 14:34
Hi dustin,
Attach is the screenshot requested..

That is on Mobile..


for authentication please follow this link
https://www.autruo.com/
![Screenshot_20210803-142742_Opera](https://user-images.githubusercontent.com/88362706/128034087-8a09f87e-d046-493f-90e0-722899041430.jpg)
![Screenshot_20210803-142801_Opera](https://user-images.githubusercontent.com/88362706/128034101-d99ece80-e01f-4440-9dd7-3830a7d1f12c.jpg)
![Screenshot_20210803-142746_Opera](https://user-images.githubusercontent.com/88362706/128034105-9dfd3e19-aefe-4d27-a8e2-f9e8ac2c4453.jpg)
![Screenshot_14](https://user-images.githubusercontent.com/88362706/128034112-eb189cfc-a947-4ff9-9816-4ee17fc2e488.png)
![Screenshot_15](https://user-images.githubusercontent.com/88362706/128034127-7ac8b0d5-f742-4924-9a8a-fd21d5828b97.png)
![Screenshot_20210803-142739_Opera](https://user-images.githubusercontent.com/88362706/128034132-3db31b29-a031-4f8c-921f-f160543789f3.jpg)

**Comment by shilo-ey** [comment] 2021-08-04 11:15
It seems like you have JS/PLUGIN/THEME conflict somewhere in your install.

Start by deactivating all other add-ons and plugins other than Elementor Core & Elementor Pro (if installed) - then proceed to edit and see if the issue has been resolved. You may need to switch to the default theme to rule out your theme as the cause of the conflict.

If the issue is resolved by following the above action the proceed to reactivate each plugin 1 at a time and checking the editor till you find the one causing the conflict.

If plugin and theme deactivation didn't work - please try to deactivate all Experiments and activate them one by one until you identify the buggy experiment (Elementor > Settings > Experimetns tab)

If the above process does not resolve the issue then check on Memory Limit set for your site together with PHP version - the easiest way to do that is by going to Elementor > System Info & scanning through it. Would also help if you post that info here for further assistance.

Thanks

**Comment by okikiola12** [comment] 2021-08-04 20:45
I have rolled back to the previous version and the issues were solved.
this is Php memory details.
![Screenshot_11](https://user-images.githubusercontent.com/88362706/128252287-39fba9e1-f8e9-4401-84c4-902763d8388a.png)
![Screenshot_12](https://user-images.githubusercontent.com/88362706/128252293-4767fad1-aeb3-439b-832d-e904f3f473c5.png)

**Comment by rami-elementor** [comment] 2022-03-08 09:34
> I have rolled back to the previous version and the issues were solved.

Thanks for the update. Closing the issue.

**Closed by rami-elementor** 2022-03-08 09:34 UTC
Labels: status/needs feedback
