### ISSUE TITLE
ACF Repeater field

### ISSUE THREAD

**Issue by Alexis1377** [elementor/elementor#10831] opened 2020-03-12 08:54 UTC
We are using Elementor Pro and ACF Pro and for us, it's a must-have to be able to use repeater fields. Such a disappointment that this feature still hasn't been made available without paying for a third-party plugin. We will think about using Beaver Builder for future projects if Elementor can't get it right.

**Comment by aunumever** [comment] 2021-01-18 16:16
What is an update on this from Elementor? I have a Pro account and would like more detailed information for this feature that has literally been asked hundreds of times over various forums and GitHub.

**Comment by d19dotca** [comment] 2021-04-30 15:47
Isn't this a duplicate of https://github.com/elementor/elementor/issues/5979 ?

**Comment by Aviad-Herman** [comment] 2021-07-04 20:42
Hi, 
Merging with #5979.
Thanks for the suggestion

**Closed by Aviad-Herman** 2021-07-04 20:42 UTC

**Comment by umer310** [comment] 2021-09-21 07:53
add_shortcode('repeater', 'wporg_shortcode');
function wporg_shortcode( $atts = [], $content = null) {
    // do something to $content
    // always return
	
	if(!function_exists('the_repeater_field')){
		return null;
	}
    
	$repeater  = get_post_meta( get_the_ID() , 'what_we_do', true);
	 
	ob_start();
	if(!empty($repeater) ) {
		 
		echo '<ul class="as-what-we-do-ul">';
		while( the_repeater_field('what_we_do', get_the_ID()) ) {
			echo '<li>';
			echo '<h3 class="as-what-we-do-head"> ' . get_sub_field('service_name') . '</h3><div class="service-details">';
			
			$service_description = get_sub_field('service_descrpatoion');
			if($service_description){
				printf('<div class="service-description">%s</div>', $service_description);
			}
			
			$service_link = get_sub_field('service_link');
			if($service_link){
				printf('<div class="service-link"><a href="%s" target="_blank" class="elementor-button-link elementor-button elementor-size-sm" role="button">
					<span class="elementor-button-content-wrapper">
						<span class="elementor-button-icon elementor-align-icon-right"><i aria-hidden="true" class="fas fa-external-link-alt"></i></span>
						<span class="elementor-button-text">View</span>
					</span>
				</a></div>',
				$service_link
				);
			}
			echo '</div></li>';
				
		}
		echo '</li></ul>';
	}
	
	
	
    return ob_get_clean();
}

**Comment by ryanlabelle** [comment] 2021-09-30 16:22
@umer310 Thank you! One part that might be obvious but I don't see mentioned is that you can use Dynamic Shortcodes (epro) to output inside many Elementor fields. This opens up a lot of flexibility. 

https://elementor.com/help/dynamic-shortcode-pro/
