### ISSUE TITLE
🔗 🐞 Bug Report: Laptop breakpoint override by desktop breakpoint (Duplicate of #20234)

### ISSUE THREAD

**Issue by ismailcseku** [elementor/elementor#20259] opened 2022-11-03 06:28 UTC
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

![image](https://user-images.githubusercontent.com/1621384/199658693-4de4a6b6-dde6-41ba-a000-5aabe80283bb.png)

In the image, the laptop breakpoint override by laptop breakpoint.  As a result, the laptop media is not working.

//desktop
@media (min-width: 768px)
.elementor-18921 .elementor-element.elementor-element-08d6b3a {
    width: 49.747%;
}

//laptop
@media (max-width: 1366px) and (min-width: 768px)
.elementor-18921 .elementor-element.elementor-element-08d6b3a {
    width: 55%;
}

### Steps to reproduce

Please fix the issue. This happens due to the laptop media query comes before the desktop query. See screenshot below:
![image](https://user-images.githubusercontent.com/1621384/199658978-7b9868c2-dc48-47d9-abae-668e007db530.png)

So, please move laptop query after desktop query.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: LiteSpeed
	MySQL version: MySQL Community Server - GPL v8.0.31
	PHP Version: 7.4.32
	PHP Memory Limit: 512M
	PHP Max Input Vars: 3000
	PHP Max Post Size: 2000M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.1
	Site URL: https://kodesolution.com/2022/oitech
	Home URL: https://kodesolution.com/2022/oitech
	WP Multisite: Yes
	Max Upload Size: 1 MB
	Memory limit: 128M
	Max Memory limit: 6000M
	Permalink Structure: /blog/%year%/%monthnum%/%day%/%postname%/
	Language: en-US
	Timezone: 0
	Admin Email: ismailcseku@gmail.com
	Debug Mode: Inactive

== Theme ==
	Name: Oitech
	Version: 1.0
	Author: ThemeMascot Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36

== Active Plugins ==
	Classic Editor
		Version: 1.6.2
		Author: WordPress Contributors

	Contact Form 7
		Version: 5.6.4
		Author: Takayuki Miyoshi

	Cost Calculator Builder
		Version: 3.1.1
		Author: StylemixThemes

	Elementor
		Version: 3.8.0
		Author: Elementor.com

	Mascot Core
		Version: 1.0
		Author: ThemeMascot

	Mascot Core - Oitech
		Version: 1.0
		Author: ThemeMascot

	MC4WP: Mailchimp for WordPress
		Version: 4.8.11
		Author: ibericode

	Meta Box
		Version: 5.6.7
		Author: MetaBox.io

	Meta Box Bundle (Mascot)
		Version: 1.0
		Author: ThemeMascot

	One Click Demo Import
		Version: 3.1.2
		Author: OCDI

	Qi Addons For Elementor
		Version: 1.5.4
		Author: Qode Interactive

	Regenerate Thumbnails
		Version: 3.1.5
		Author: Alex Mills (Viper007Bond)

	Slider Revolution
		Version: 6.5.15
		Author: ThemePunch

	Smash Balloon Instagram Feed
		Version: 6.1
		Author: Smash Balloon

	Template Library and Redux Framework
		Version: 4.3.20
		Author: Extendify

	Variation Swatches for WooCommerce
		Version: 2.0.12
		Author: Emran Ahmed

	WooCommerce
		Version: 7.0.1
		Author: Automattic

	WPC Smart Compare for WooCommerce
		Version: 5.3.0
		Author: WPClever

	WPC Smart Quick View for WooCommerce
		Version: 3.2.1
		Author: WPClever

	WPC Smart Wishlist for WooCommerce
		Version: 4.4.3
		Author: WPClever

	Yoast Duplicate Post
		Version: 4.5
		Author: Enrico Battocchi & Team Yoast

== Network Plugins ==
	Better Search Replace
		Version: 1.4.1
		Author: Delicious Brains

	NS Cloner - Site Copier
		Version: 4.2.1
		Author: Never Settle

	Widget Importer & Exporter
		Version: 1.6
		Author: ChurchThemes.com

	WordPress Importer
		Version: 0.8
		Author: wordpressdotorg

	WP-Sweep
		Version: 1.1.5
		Author: Lester 'GaMerZ' Chan

== Elementor Experiments ==
	Optimized DOM Output: Active by default
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Active by default
	Additional Custom Breakpoints: Active by default
	Import Export Website Kit: Active by default
	Hide native WordPress widgets from search results: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Inactive by default
	Landing Pages: Active by default
	Color Sampler: Active by default
	Favorite Widgets: Active by default
	Admin Top Bar: Active by default

== Log ==
	
JS: showing 7 of 7JS: 2022-10-13 08:09:35 [error X 173][https://kodesolution.com/2022/oitech/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.7.8:3:692080] T.getContainer is not a function 
JS: 2022-10-13 11:18:20 [error X 8][https://kodesolution.com/2022/oitech/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.7.8:3:767848] Cannot read properties of undefined (reading \'localized\') 
JS: 2022-10-13 12:32:55 [error X 20][https://kodesolution.com/2022/oitech/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.7.8:3:1060992] Cannot read properties of null (reading \'getBoundingClientRect\') 
JS: 2022-10-22 05:35:54 [error X 1][https://kodesolution.com/2022/oitech/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.7.8:3:767341] Cannot read properties of undefined (reading \'toLowerCase\') 
JS: 2022-10-29 11:11:32 [error X 5][https://kodesolution.com/2022/oitech/wp-content/plugins/elementor/assets/js/editor-modules.min.js?ver=3.7.8:2:14029] An invalid argument supplied as multiple control value [array (
  'category' => 'InvalidElementData',
  'tag' => 'Element `undefined` got as `logo` value. Expected array or object.',
)]
JS: 2022-10-29 13:09:03 [error X 4][https://kodesolution.com/2022/oitech/wp-content/plugins/elementor/assets/js/editor-modules.min.js?ver=3.7.8:2:14029] An invalid argument supplied as multiple control value [array (
  'category' => 'InvalidElementData',
  'tag' => 'Element `undefined` got as `slide_image` value. Expected array or object.',
)]
JS: 2022-11-03 05:54:29 [error X 6][https://kodesolution.com/2022/oitech/wp-admin/load-scripts.php?c=1&loadchunk_0=jquery-core,jquery-migrate,underscore,shortcode,utils,backbone,wp-util,wp-backbone,media-models,moxiejs,plupload,wp-plupload,jqu&loadchunk_1=ery-ui-core,jquery-ui-mouse,jquery-ui-sortable&ver=6.1:2:51824] Cannot read properties of undefined (reading \'replace\') 

PHP: showing 2 of 2PHP: 2022-10-14 11:30:23 [notice X 46][/home/kodesolution/public_html/2022/oitech/wp-content/plugins/elementor/includes/managers/image.php::108] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-10-18 05:14:52 [notice X 48][/home/kodesolution/public_html/2022/oitech/wp-content/plugins/elementor/includes/controls/base-multiple.php::87] Undefined index: value [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

Log: showing 7 of 72022-11-03 04:27:18 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.8',
  'to' => '3.8.0',
)]
2022-11-03 04:27:20 [info] elementor::elementor_updater Started 
2022-11-03 04:27:20 [info] Elementor/Upgrades - _on_each_version Start  
2022-11-03 04:27:20 [info] Elementor/Upgrades - _on_each_version Finished 
2022-11-03 04:27:20 [info] Elementor/Upgrades - _v_3_8_0_fix_php8_image_custom_size Start  
2022-11-03 04:27:20 [info] Elementor/Upgrades - _v_3_8_0_fix_php8_image_custom_size Finished 
2022-11-03 04:27:20 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.8',
  'to' => '3.8.0',
)]

== Elementor - Compatibility Tag ==
	
	Qi Addons For Elementor: Compatibility not specified

**Comment by nicholaszein** [comment] 2022-11-03 16:29
Hello @ismailcseku!

Thank you for your submission! 🙏 

### 🔗 This issue is a Duplicate of #20234.

Which is on the same subject. 

For this reason, I'm closing this issue and 🔃 **Merging** it with the original, so we can have all the discussions in one location, and deal with it more efficiently.

Feel free to continue the conversation there. 😉 

### ✔️ Please, in the future, remember to check if there isn't an issue similar to yours already opened. 

Best regards,

Nick

**Closed by nicholaszein** 2022-11-03 16:29 UTC
Labels: type/responsive, compatibility/assets, type/global-style, type/experiment
