### ISSUE TITLE
Suggestions for improving the slider widget.please check

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#14791] opened 2021-05-02 19:07 UTC
Please add a feature to this widget so that we can replace the navigation flash icon with our own icon, such as loading the svg icon.
https://prnt.sc/12efvfk
It would also be great if you could add a hover effect to the slider flash icon.For example, if the mouse hovers over the arrow, the arrow moves slightly to the right or ... 

Please check, thank you

**Comment by 79ho3ein** [comment] 2021-05-03 23:05
@DorShahar Excuse me, what do these labels mean?

**Comment by d19dotca** [comment] 2021-05-07 21:30
@79ho3ein - Labels in GitHub are meant for categorization and organization. It lets them work more efficiently and use filters to look for just feature enhancements, for example. You can learn more about GitHub labels here: https://docs.github.com/en/github/managing-your-work-on-github/managing-labels

**Comment by rami-elementor** [comment] 2022-03-09 17:49
Labels are used internally, this way we can group similar tasks and assign to relevant developers.

**Comment by rami-elementor** [comment] 2022-03-09 17:55
Duplicate of #14976

**Closed by rami-elementor** 2022-03-09 17:55 UTC
Labels: request/enhancement, component/carousel, component/icons, component/slides
