### ISSUE TITLE
WordPress Gallery Block not working with Elementor Lightbox

### ISSUE THREAD

**Issue by tollube** [elementor/elementor#12038] opened 2020-08-05 10:30 UTC
The WordPress gallery Gutenberg block is not working with the Elementor Lightbox. The image opens in the Lightbox - when you select the link to be to the media file in the block settings - but you can't switch through the gallery.

**Comment by euene** [comment] 2020-08-05 12:49
This is a duplicate of #11942

**Comment by lior-sh** [comment] 2020-08-05 14:21
duplicate with #11942

**Closed by lior-sh** 2020-08-05 14:21 UTC
