### ISSUE TITLE
Custom message when Post widget query is empty

### ISSUE THREAD

**Issue by gzabrisk** [elementor/elementor#7624] opened 2019-03-26 16:21 UTC
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

## My Request

I would love a way to display a message of some kind when the Posts widget has nothing to show according the query in place. I am using the Post Widget to display a specific custom post type and have implemented a custom query in functions.pho that hides posts after a date set through an ACF field. Sometimes, depending on the dates, my query has nothing to show and so the posts widget is empty. I'm want to display a message when this is the case, such as "We're sorry, there are no openings at this time."

**Comment by tristanleboss** [comment] 2019-03-31 21:21
+1

**Comment by Makramgit** [comment] 2019-04-23 16:33
I have exactly the same requirement. Did you end up finding a workaround?

**Comment by knireis** [comment] 2019-05-09 08:06
+1 I would like to see this option as well

**Comment by ninawannado** [comment] 2019-06-16 17:27
Yes please! +1

**Comment by bellamystudio** [comment] 2019-07-29 11:15
Yes +1 for this, I really need to display something when no posts are available!

**Comment by Kakuk91** [comment] 2019-08-08 07:12
There is a very simple solution for this: 
 
 1. On your search result page make an inner section with your text ('There are no results that match your search.') with an id('no-result')
 
 2. Give an id for your search result posts widget ('available-posts')

 3. Use jquery to check the length of the posts, if there is available post set css display value of the 
     no-result message to none
   jQuery(document).ready(function($){
    if($('#available-posts').length){
        $('#no-result').css("display", "none");
    }
});

**Comment by deepwaterpixel** [comment] 2019-08-19 17:09
> There is a very simple solution for this:
> 
> 1. On your search result page make an inner section with your text ('There are no results that match your search.') with an id('no-result')
> 2. Give an id for your search result posts widget ('available-posts')
> 3. Use jquery to check the length of the posts, if there is available post set css display value of the
>    no-result message to none
>    jQuery(document).ready(function($){
>    if($('#available-posts').length){
>    $('#no-result').css("display", "none");
>    }
>    });

I can confirm that this approach "does the thing".  In this way, you can set pretty much any content to show up when a particular query is empty.  This is super-useful, especially given this feature is not built into E Pro.  I can see how implementation of this could get tricky from an interface perspective, but it's definitely possible.  Using JQuery isn't my favorite solution, but it does the job well.

Team, consider making this a known issue, as even 3rd party post widgets have this option.  The main reason I still use E Pro's post widget is the ability to implement custom query filters to filter and sort by post_meta.

**Comment by sarahdenise** [comment] 2019-08-26 01:49
+1

**Comment by SieBer15** [comment] 2019-09-24 09:45
+1 This feature is integrated in the Archive Posts widget but not in the Posts widget?

**Comment by anag0** [comment] 2020-03-04 13:59
+1

**Comment by graphicfixations** [comment] 2020-03-22 22:51
+1

**Comment by donwattz1459** [comment] 2020-04-07 04:28
This doesn't seem to be working anymore. Does anyone else have a solution for this?

**Comment by graphicfixations** [comment] 2020-04-07 04:42
I jimmy-rigged a solution that does the trick. I gave my post loop a solid background that matched the page, then I set the z-index to 1. Then I created a title box above it and wrote in the message "no results" (or whatever you want it to say if there's nothing to display), set the z-index to 0 and then go back to the post loop, give it a negative margin that equals that title box (-50px, say). That way, if there are posts, the solid background covers the text, which loads behind it thanks to the z-index. If there aren't any posts to show, the text is not covered by anything so it shows up instead.  Not perfect, but it works.  See my example here: http://britannia.britanniaquote.com/vacancies (every section actually has "no vacancies to display, you just can't see it when there are vacancies there to cover it up!)

**Comment by donwattz1459** [comment] 2020-04-07 04:45
Thank you @graphicfixations ! That actually would work. 
However, I dug down in the code, and a DIV with the class below appears when no posts are found, so I added some CSS>

`.elementor-posts-nothing-found:after{
    content: "No Results";
}`

Works Perfectly! Thank you for answering though!

**Comment by graphicfixations** [comment] 2020-04-07 05:03
Lol well that would have been easier! Wish I'd seen that! I do like being able to set  custom messages for different areas on the same page, though, so at least there's that!

**Comment by lennertdaniels** [comment] 2020-05-28 16:55
Sharing my solution for reference :)

In my case, an empty query would not generate any HTML at all (Elementor Pro v2.9.9), so no luck with the Javascript or CSS solutions.

I added the following hook in my `functions.php`:

```
add_action('elementor/query/query_results', function($query) {
	$total = $query->found_posts;
	if ($total == 0) {
		echo '<p class="text-align-center">No items found.</p>';
	}
});
```

You could even change the text depending on the post type or category the query is acting on:
```
if ( $query->get("post_type") == "some_other_post_type_slug" ) {
	echo "My customized message.";
}
```

Refer to the [WP_Query docs](https://developer.wordpress.org/reference/classes/wp_query/) to see which parameters are available.

**Comment by mystivan** [comment] 2020-06-17 03:45
> Sharing my solution for reference :)
> 
> In my case, an empty query would not generate any HTML at all (Elementor Pro v2.9.9), so no luck with the Javascript or CSS solutions.
> 
> I added the following hook in my `functions.php`:
> 
> ```
> add_action('elementor/query/query_results', function($query) {
> 	$total = $query->found_posts;
> 	if ($total == 0) {
> 		echo '<p class="text-align-center">No items found.</p>';
> 	}
> });
> ```
> 
> You could even change the text depending on the post type or category the query is acting on:
> 
> ```
> if ( $query->get("post_type") == "some_other_post_type_slug" ) {
> 	echo "My customized message.";
> }
> ```
> 
> Refer to the [WP_Query docs](https://developer.wordpress.org/reference/classes/wp_query/) to see which parameters are available.

@lennertdaniels hey this was exactly what I was looking for, thanks much!

**Comment by stephen-bloomforwomen** [comment] 2020-07-30 20:25
Another option so you can have more control over this is to have it execute a shortcode elementor template so you can customize what you want here.  I put in a filter here in case you want to filter the template_id by the query type as someone suggested up above.

```
add_action('elementor/query/query_results', function($query) {
        $template_id = apply_filter('elementor/query/query_results/not_found_template_id', false);
	$total = $query->found_posts;
	if ($total == 0) {
                if ( $template_id !== false) {
		    do_shortcode('[elementor-template id="' . $template_id . '"]');
                } else {
                     echo '<p class="text-align-center">No items found.</p>';
                }
	}
});
```

**Comment by johnkraczek** [comment] 2020-08-03 17:09
I wanted this functionality, so I wrote a class to include in your child theme functions.php. 
It will add an option to type some simple text or select an Elementor saved section to display only if there are no posts found for the query. 

I wrote a blog post explaining it here: https://funnelpress.com/elementor-post-not-found-content/

if you just want the code here's the gist https://gist.github.com/johnkraczek/730b06e6044f97701b372a8f787ef52c

![Post Not Found Content](https://user-images.githubusercontent.com/3604887/89207914-bce2e680-d578-11ea-89be-faaccf6c4b35.png)

![post not found - Saved Section](https://user-images.githubusercontent.com/3604887/89207893-b6546f00-d578-11ea-99d5-dd39a02a66f2.png)

You can find this option under:  Elementor Editor -> Posts Widget -> Content Tab -> Query
I'm curious if people like this, so let me know.

**Comment by lindabenefield** [comment] 2020-11-25 00:20
johnkraczek , 
         is there any way you can turn this into a plugin? I would LOVE to be able to add a custom message to my posts widgets. I am pretty new at php, and I know there are others who would love to just add it as a plugin. Thanks!

**Comment by acornavi** [comment] 2021-01-15 14:20
The dynamic option to place a shortcode works but the only text is displayed instead of a template. It is a bug. Essentially this can be a solution if the Elementor team debug this option so that the template can be shown, not just text. @johnkraczek your solution is very good. Thanks for sharing.

**Comment by plethoradesign** [comment] 2021-01-29 17:31
johnkraczek's solutions is fantastic and ought to be in Elementor by default. I was quite surprised this basic feature was missing from Elementor!

**Comment by shimsim** [comment] 2021-03-08 00:07
+1 for @johnkraczek solution, works perfectly. can't believe this is feature is not already baked into elementor.

**Comment by Ectropy** [comment] 2021-05-24 23:01
@johnkraczek's child theme solution appears to work really well for my purposes. I wish it was built into Elementor.

**Comment by makeshyft-tom-g** [comment] 2021-09-28 18:21
> if ( $query->get("post_type") == "some_other_post_type_slug" ) {
> 	echo "My customized message.";
> }

This is the one solution that works really easily, and is robust enough to handle different custom queries just by using the query variables as described.  Thank you.

**Comment by robtown** [comment] 2021-11-06 15:54
@johnkraczek Thank you for this. Works great.

I did add it as a class file a in a custom plugin I created for a project.

All I needed to do:
1. create a file in my plugin folder called "post_not_found_content.php", copy the contents of your class into the file and save it (adding a closing "?>" tag).
2. added "require plugin_dir_path( __FILE__ ) . 'post_not_found_content.php';"  at the top of my main plugin file.

It made sense in my case to do it this way because I am working with a child theme, AND I had already created a custom plugin in my project. So it was quicker to just merge it in my plugin than create a child theme.

It would be very simple to just make this a standalone plugin though.

**Comment by mportell2017** [comment] 2021-11-11 23:52
> @johnkraczek Thank you for this. Works great.
> 
> I did add it as a class file a in a custom plugin I created for a project.
> 
> All I needed to do:
> 
> 1. create a file in my plugin folder called "post_not_found_content.php", copy the contents of your class into the file and save it (adding a closing "?>" tag).
> 2. added "require plugin_dir_path( **FILE** ) . 'post_not_found_content.php';"  at the top of my main plugin file.
> 
> It made sense in my case to do it this way because I am not working with a child theme, AND I had already created a custom plugin in my project. So it was quicker to just merge it in my plugin than create a child theme.
> 
> It would be very simple to just make this a standalone plugin though.

Hello, would you be willing to upload this as a plugin? Thank you!

**Comment by johnkraczek** [comment] 2021-11-12 06:59
I have considered making it a plug-in. I will add it to the to-do list and post here when I have finished.

**Comment by carletonm** [comment] 2021-11-13 22:56
If you're using elementor you can create a template for your No results view and display it like this.

add_action('elementor/query/query_results', function($query) {
	$total = $query->found_posts;
	if ($total == 0) {
		$frontend = new \Elementor\Frontend();
		$template_id  = 257; //put your id for the elementor template here

		echo $frontend->get_builder_content_for_display( $template_id, true );
	}
});

**Comment by juuso-turunen** [comment] 2022-03-13 20:49
> Im adding that to functions, but i dont know why, it shows the message in every case, whether or not there is a post to show.. what whould i do? add_action('elementor/query/query_results', function($query) { $total = $query->found_posts; if ($total == 0) { echo '
> 
> No items found.
> 
> ';
> }
> });

I have the same issue. `found_posts` returns always 0.

**Comment by mcrowell** [comment] 2022-03-24 17:52
@shilo-ey  Any future plans to add this functionality to Elementor Pro?

**Comment by michaelearley1** [comment] 2022-04-13 14:00
Would love a nice solution to this as well

**Comment by HusseinKhafaji** [comment] 2022-05-10 21:22
> > Sharing my solution for reference :)
> > In my case, an empty query would not generate any HTML at all (Elementor Pro v2.9.9), so no luck with the Javascript or CSS solutions.
> > I added the following hook in my `functions.php`:
> > ```
> > add_action('elementor/query/query_results', function($query) {
> > 	$total = $query->found_posts;
> > 	if ($total == 0) {
> > 		echo '<p class="text-align-center">No items found.</p>';
> > 	}
> > });
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > You could even change the text depending on the post type or category the query is acting on:
> > ```
> > if ( $query->get("post_type") == "some_other_post_type_slug" ) {
> > 	echo "My customized message.";
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Refer to the [WP_Query docs](https://developer.wordpress.org/reference/classes/wp_query/) to see which parameters are available.
> 
> @lennertdaniels hey this was exactly what I was looking for, thanks much!

Thank you for sharing this solution, works like a charm. 
I would like to know if I can use it by adding a custom Query id in the Elementor post widget, I'm trying to add different messages for each language. I'm using the Polylang plugin for the translation. :)

**Comment by MuhammadTasleem** [comment] 2022-07-25 12:16
> If you're using elementor you can create a template for your No results view and display it like this.
> 
> ```
> add_action('elementor/query/query_results', function($query) {
> 	$total = $query->found_posts;
> 	if ($total == 0) {
> 		$frontend = new \Elementor\Frontend();
> 		$template_id  = 257; //put your id for the elementor template here
> 
> 		echo $frontend->get_builder_content_for_display( $template_id, true );
> 	}
> });
> ```
@carletonm , I used above solution. I put 'No Post found message' in template. When no post is found, message is appearing but Posts Widget is also showing all posts. Kindly advise solution.
Thanks

**Comment by aryan3650** [comment] 2022-08-09 02:44
> If you're using elementor you can create a template for your No results view and display it like this.
> 
> ```
> add_action('elementor/query/query_results', function($query) {
> 	$total = $query->found_posts;
> 	if ($total == 0) {
> 		$frontend = new \Elementor\Frontend();
> 		$template_id  = 257; //put your id for the elementor template here
> 
> 		echo $frontend->get_builder_content_for_display( $template_id, true );
> 	}
> });
> ```

@carletonm's solution worked well with 'Jet filters'

**Comment by ivanverona1** [comment] 2022-11-17 21:23
Hi everybody.
I'm trying to display a different template for each custom post type i have.
After used this code i can see the assigned template displayed correctly in the custom post type i wanted but i can even see the other posts contained  in the query when my target is to display it only when the the post list contains 0 posts.


//* the template code *//

add_action('elementor/query/query_results', function($query) {
    $total = $query->found_posts;
    if ($total == 0);
    if ( $query->get("post_type") == "my_custom_post_type" ) {
		$frontend = new \Elementor\Frontend();
        $template_id  = "my_template id_without_quotes";
        echo $frontend->get_builder_content_for_display( $template_id, true );
    }
});



I've tried this and it work perfectly but it display only the text and i'm looking to display a template

//* the text code *//

add_action('elementor/query/query_results', function($query) {
    $total = $query->found_posts;
    if ($total == 0);
    if ( $query->get("post_type") == "my_custom_post_type" ) {
        echo "My customized message.";
    }
}); 


This is the code i'm using.
Thanks in advance to everybody

**Comment by ivanverona1** [comment] 2022-11-17 21:41
Hi everybody.
I'm trying to display a different template for each custom post type i have.
After used this code i can see the assigned template displayed correctly in the custom post type i wanted but i can even see the other posts contained  in the query when my target is to display it only when the the post list contains 0 posts.

//* THE TEMPLATE CODE *//

add_action('elementor/query/query_results', function($query) {
    $total = $query->found_posts;
    if ($total == 0);
    if ( $query->get("post_type") == "my_custom_post_type" ) {
		$frontend = new \Elementor\Frontend();
        $template_id  = "my_template id_without_quotes";
        echo $frontend->get_builder_content_for_display( $template_id, true );
    }
});


I've tried this and it work perfectly but it display only the text and i'm looking to display a template

//* THE TEXT CODE *//

add_action('elementor/query/query_results', function($query) {
         $total = $query->found_posts;
         if ($total == 0);
         if ( $query->get("post_type") == "my_custom_post_type" ) {
        echo "My customized message.";
    }
}); 

This is the code i'm using.
Thanks in advance to everybody.

P.s: Sorry i don't know why i couldn't post the code correctly. It didn't correctly displayed formatted inside the code quotes.

**Comment by johnkraczek** [comment] 2023-01-12 17:44
@developernerds, @acornavi, @caspervoogt, @shimsim, @Ectropy, @robtown @mportell2017 
 
> @johnkraczek , is there any way you can turn this into a plugin? I would LOVE to be able to add a custom message to my posts widgets. I am pretty new at PHP, and I know there are others who would love to just add it as a plugin. Thanks!

I know that it took me a bit to get around to it, but here's a plugin to do this. 
https://github.com/johnkraczek/post-not-found-for-elementor

Hopefully, someday elementor pro will include this functionality natively, and my plugin won't be required. 

Try it out, and let me know if you have any issues with it.

**Comment by e1creative** [comment] 2023-01-31 06:34
@ivanverona1 your code is wrong. `if ($total == 0);` is a statement, not a conditional.

**Comment by formgarten** [comment] 2023-04-11 10:45
@johnkraczek Thanks dude for sharing 👏🏻 I wish we also had that option inside the loop grid widget. 

It's still unbelievable that the people at elementor never integrated such basic functions. Instead, 1000 new features that are in alpha and beta stages. That leave me speechless.

**Comment by black-eye** [comment] 2023-07-25 00:24
+1 Unbelievable this super basic function is still not added.

**Comment by theavic** [comment] 2023-07-26 23:05
Agreed - The easiest (and not great way) to do this is to have a div with an id "nothingfound" with a message saying "Nothing Found" and adding CSS to the loop builder to set the display:none property 

But you'll have to use the loop builder for this

> +1 Unbelievable this super basic function is still not added.

**Comment by moojnick** [comment] 2023-07-28 13:31
hey! that's awesome! thank you so much!
Can you please make it work on loop grid too?


> I wanted this functionality, so I wrote a class to include in your child theme functions.php. It will add an option to type some simple text or select an Elementor saved section to display only if there are no posts found for the query.
> 
> I wrote a blog post explaining it here: https://funnelpress.com/elementor-post-not-found-content/
> 
> if you just want the code here's the gist https://gist.github.com/johnkraczek/730b06e6044f97701b372a8f787ef52c
> 
> ![Post Not Found Content](https://user-images.githubusercontent.com/3604887/89207914-bce2e680-d578-11ea-89be-faaccf6c4b35.png)
> 
> ![post not found - Saved Section](https://user-images.githubusercontent.com/3604887/89207893-b6546f00-d578-11ea-99d5-dd39a02a66f2.png)
> 
> You can find this option under: Elementor Editor -> Posts Widget -> Content Tab -> Query I'm curious if people like this, so let me know.

י

**Comment by johnkraczek** [comment] 2023-07-31 14:33
@moojnick  I will look into adding the loop grid item not found to the plugin.

**Comment by moojnick** [comment] 2023-08-01 19:19
> @moojnick I will look into adding the loop grid item not found to the plugin. https://github.com/johnkraczek/post-not-found-for-elementor

Thank you so much! 'm looking forward for this :)

**Comment by formgarten** [comment] 2023-08-01 20:16
Me too 😍😍😍Am 01.08.2023 um 21:19 schrieb moojnick ***@***.***>:﻿

@moojnick I will look into adding the loop grid item not found to the plugin. https://github.com/johnkraczek/post-not-found-for-elementor

Thank you so much! 'm looking forward for this :)

**Comment by portrayaloflife** [comment] 2023-08-02 22:27
+1

**Comment by JennyPower** [comment] 2023-08-16 03:23
+1

**Comment by portrayaloflife** [comment] 2023-08-28 05:05
@nicholaszein This feature would be really useful with loops! Just pinging for awareness!

**Comment by askwpgirl** [comment] 2024-11-03 22:08
It is surprising that of all the post widgets I've ever worked with in my WordPress career, Elementor is the only one that doesn't have a not found message option.

**Comment by nicholaszein** [comment] 2024-11-05 15:56
Hello everyone!

As of version 3.18.0 of Elementor Pro, all of the following widgets have a field to write a "Nothing Found" message:

- ✅ Archive Posts
- ✅ Archive Products
- ✅ Loop Grid

All of these plugins allow you to write a customized "Nothing Found" message, usually located in the **`Content`** tab > **`Additional Options`** or **`Content`** tab > **`Advanced`** section. See the Loop Grid for an example:

![image](https://github.com/user-attachments/assets/d475d7cf-0ad5-4c1b-978f-8d56cc053376)

We recommend using the Loop Grid for optimal customization and more advanced features going forward.

Further customization such as the ability to add custom templates in the place of the "Nothing Found" message are still in the planning phase.

I'm closing this issue as solved.

Thank you all for your feedback!

Kind regards

**Closed by nicholaszein** 2024-11-05 15:56 UTC
Labels: request/enhancement, product/pro, widget/posts*, solved-by/loop-builder, widget/loop-builder, widget/loop-builder/empty-message, mod/c*, mod/m*, mod/d*, mod/r*
