### ISSUE TITLE
🚀 Feature Request: New dynamic tag for product badges (Suitable for product page and loop builder)

### ISSUE THREAD

**Issue by Michaelgimii** [elementor/elementor#19799] opened 2022-09-13 22:16 UTC
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

It would be great if you add this new dynamic tag for WooCommerce. Using this dynamic tag, we can display the amount of discount for WooCommerce products. **This dynamic tag needs two important features :**

1- Ability to display custom text. For example, **sale!**

2- Ability to display the amount of discount as a percentage

### Describe the solution you'd like

New dynamic tag for product badges. Please check this issue. This is especially critical for the loop builder. It is also very useful and practical for the product page.

**Comment by rami-elementor** [comment] 2022-09-18 12:03
Duplicate of #19205

**Closed by rami-elementor** 2022-09-18 12:03 UTC
Labels: request/feature, product/pro, component/dynamic-tag, component/woocommerce
