### ISSUE TITLE
Fatal Error after updating to 3.7.7

### ISSUE THREAD

**Issue by ciprianpentelescu** [elementor/elementor#19917] opened 2022-09-26 12:33 UTC
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

After updating today the site stops working, and i get this fatal error:

PHP Fatal error: Uncaught TypeError: Elementor\\Core\\Files\\CSS\\Base::get_style_control_value(): Argument #1 ($control) must be of type array, null given, called in /public_html/wp-content/plugins/elementor/core/files/css/base.php on line 682 and defined in /public_html/wp-content/plugins/elementor/core/files/css/base.php:738Stack trace:#0 /public_html/wp-content/plugins/elementor/core/files/css/base.php(682): Elementor\\Core\\Files\\CSS\\Base->get_style_control_value()#1 [internal function]: Elementor\\Core\\Files\\CSS\\Base->Elementor\\Core\\Files\\CSS\\{closure}()#2 /public_html/wp-content/plugins/elementor/core/files/css/base.php(448): call_user_func()#3 /public_html/wp-content/plugins/elementor/core/files/css/base.php(347): Elementor\\Core\\Files\\CSS\\Base->parse_property_placeholder()#4 [internal function]: Elementor\\Core\\Files\\CSS\\Base->Elementor\\Core\\Files\\CSS\\{closure}()#5 /public_html/wp-content/plugins/elementor...',

### Steps to reproduce

Updated from 3.7.7 to 3.7.6. In console there is a swiper error and the website is down.
Also i have JetPopup 1.5.6 installed
### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

Centos 7, PHP 8.1

**Comment by DanielRuf** [comment] 2022-09-26 23:32
Duplicate of https://github.com/elementor/elementor/issues/19894 which was unfortunately closed.

As a workaround see https://github.com/elementor/elementor/issues/19894#issuecomment-1256314016

**Comment by nicholaszein** [comment] 2022-09-28 14:09
Hello @ciprianpentelescu!

Thank you for contacting us.

You seem to have a conflict with a 3rd party add-on that is using an unsupported method, not included in our API.

We are already aware of this issue, and a fix will be released in the upcoming patch version. Meanwhile, please [Rollback](https://elementor.com/help/rolling-back-to-a-previous-version-of-elementor/)Elementor to version 3.7.6. 
You can use the built-in rollback feature or simply [download this file](https://downloads.wordpress.org/plugin/elementor.3.7.6.zip) and upload it as a plugin to your website. It will ask you if you want to replace Elementor v3.7.7 with v3.7.6. Just click to replace it and everything should be back to normal.

📋 This issue is a **Duplicate** of #19894, which is on the same subject. For this reason, I'm closing this issue and ↔️ **Merging** it with the original, so we can have all the discussion in one location, and deal with it more efficiently.

Please feel free to continue the conversation there. 😉

Best regards,

Nick

**Closed by nicholaszein** 2022-09-28 14:09 UTC
Labels: bug, compatibility/3rd_party, type/responsive, type/developer-api
