### ISSUE TITLE
🔗 🐞 Widget "Loop Grid" Products option  /// Browser errors have been logged in the console (Duplicate of #24959)

### ISSUE THREAD

**Issue by DanielCyran** [elementor/elementor#24993] opened 2024-01-31 18:16 UTC
### Prerequisites

- [X] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [X] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

Instead of the standard product widget, I used the "Loop Grid" widget. Unfortunately, an error appears after adding this widget:

Browser errors have been logged in the console
Failed to load resource: the server responded with a status of 404 (Not Found)
https://topsklepsportowy.pl/wp-content/uploads/elementor/css/post-1402.css?ver=1706723753

![image](https://github.com/elementor/elementor/assets/96839460/475cecbe-ff6a-40e8-92ad-5355adeb1af6)

### Steps to reproduce

I simply added a "Loop Grid" widget with products

The website is completely clean and from the beginning there is only Elementor PRO + Woocommerce

### Expected behavior

I expect the element to be updated to resolve the error and improve the pagespeed score :)

### Isolating the problem

- [X] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [X] This bug happens with the Hello Elementor theme active.
- [X] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

<details>
<summary>Click to reveal</summary>

````txt

					
== Server Environment ==
	Operating System: Linux
	Software: LiteSpeed
	MySQL version: MariaDB Server v10.5.23
	PHP Version: 8.1.21
	PHP Memory Limit: 1280M
	PHP Max Input Vars: 100000
	PHP Max Post Size: 800M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.4.3
	Site URL: https://topsklepsportowy.pl
	Home URL: https://topsklepsportowy.pl
	WP Multisite: No
	Max Upload Size: 800 MB
	Memory limit: 40M
	Max Memory limit: 1280M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: en-US
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 3.0.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36 Edg/121.0.0.0

== Active Plugins ==
	Elementor
		Version: 3.19.0
		Author: Elementor.com

	Elementor Pro
		Version: 3.19.0
		Author: Elementor.com

	WooCommerce
		Version: 8.5.2
		Author: Automattic


== Must-Use Plugins ==
	WordPress automation by Installatron
		Version: 
		Author: 


== Features ==
	Custom Fonts: 0
	Custom Icons: 0

== Integrations ==
	
	woocommerce: Active


== Elementor Experiments ==
	Improved Asset Loading: Active
	Improved CSS Loading: Active
	Inline Font Icons: Active by default
	Additional Custom Breakpoints: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active
	Upgrade Swiper Library: Active by default
	Grid Container: Active
	Default to New Theme Builder: Active by default
	Hello Theme Header & Footer: Active by default
	Editor Top Bar: Inactive by default
	Optimized Gutenberg Loading: Active
	Build with AI: Active by default
	Landing Pages: Active by default
	Nested Elements: Active
	Lazy Load Background Images: Active
	Optimize Image Loading: Active
	Global Style Guide: Active by default
	Page Transitions: Active by default
	Notes: Active by default
	Display Conditions: Inactive by default
	Form Submissions: Active by default
	Scroll Snap: Active by default
	Menu: Active
	Taxonomy Filter: Inactive by default


== Log ==
	
PHP: showing 7 of 7PHP: 2024-01-26 06:29:56 [warning X 2][../wp-content/plugins/elementor/includes/managers/image.php::113] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-01-26 10:28:10 [notice X 167][../wp-content/plugins/elementor/includes/base/controls-stack.php::228] hexdec(): Passing null to parameter #1 ($hex_string) of type string is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-01-26 10:29:11 [notice X 38][../wp-content/plugins/elementor-pro/modules/custom-css/module.php::96] trim(): Passing null to parameter #1 ($string) of type string is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-01-26 10:47:09 [warning X 266][../wp-content/plugins/elementor-pro/modules/posts/skins/skin-content-base.php::265] Attempt to read property "ID" on null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-01-26 13:04:13 [warning X 2][../wp-content/plugins/elementor-pro/modules/woocommerce/classes/products-renderer.php::173] Attempt to read property "taxonomy" on bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-01-26 19:41:45 [notice X 27][../wp-content/plugins/elementor-pro/modules/woocommerce/module.php::626] parse_str(): Passing null to parameter #1 ($string) of type string is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-01-29 14:09:12 [warning X 3][../wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::179] Undefined array key "editor_post_id" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 3 of 3JS: 2024-01-26 09:12:24 [error X 9][../wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.18.3:3:640700] Cannot read properties of undefined (reading 'isDesignable') 
JS: 2024-01-28 17:36:40 [error X 1][../wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.18.3:3:322372] Cannot read properties of undefined (reading 'html') 
JS: 2024-01-29 10:10:20 [error X 4][../wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.18.3:3:1116198] Cannot read properties of null (reading 'getBoundingClientRect') 

Log: showing 10 of 102024-01-29 18:18:59 [info] elementor::elementor_updater Started 
2024-01-29 18:18:59 [info] Elementor/Upgrades - _on_each_version Start  
2024-01-29 18:18:59 [info] Elementor/Upgrades - _on_each_version Finished 
2024-01-29 18:18:59 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.18.3',
  'to' => '3.19.0',
)]
2024-01-29 18:18:59 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.18.3',
  'to' => '3.19.0',
)]
2024-01-30 06:27:21 [info] elementor-pro::elementor_pro_updater Started 
2024-01-30 06:27:21 [info] Elementor Pro/Upgrades - _on_each_version Start  
2024-01-30 06:27:21 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2024-01-30 06:27:21 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.18.3',
  'to' => '3.19.0',
)]
2024-01-30 06:27:21 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.18.3',
  'to' => '3.19.0',
)]



== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatible

== Elementor Pro - Compatibility Tag ==

````

</details>

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by nicholaszein** [comment] 2024-01-31 20:40
Hello @DanielCyran!

Thank you for your submission! 🙏 

### 🔗 🐞 This issue is a Duplicate of #24959

Which is on the same subject. 

For this reason, I'm closing this thread and 🔃 **Merging** it with the original, so we can have all the discussions in one location, and deal with it more efficiently.

Feel free to continue the conversation there. 😉 

### 🔍 Please, in the future, remember to check if there isn't any thread similar to yours already opened. 

Kind regards

**Closed by nicholaszein** 2024-01-31 20:40 UTC
Labels: product/pro, type/styles, compatibility/assets, widget/loop-builder, mod*, widget/loop-builder/item-template, duplicate
