### ISSUE TITLE
Scroll bar customization

### ISSUE THREAD

**Issue by pauserratgutierrez** [elementor/elementor#17254] opened 2021-12-20 17:51 UTC
## Prerequisites

- [ x ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ x ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
It's not possible to change anything related to the Scroll Bar using Elementor. It would be cool to be able to match our designs making changes to the style and behavior of the scroll bar.

**Describe the solution you'd like**
A new tab inside Site Settings to customize the scroll bar, allowing us to;
- Activate / Deactivate
- Change color (background, pointer hover, pointer click), width, height
- Responsive options

**Describe alternatives you've considered**
Custom plugin
Custom code like;
`-webkit-scrollbar {
	width: 4px;
	background: none;
}
-webkit-scrollbar-thumb {
  background: #606060;
}
-webkit-scrollbar-thumb:hover {
  background: #888;
}`

**Additional context**
I don't but maybe add this in Site Settings. It could be an option to add this as a part of the theme builder or popup as well.

**Comment by rami-elementor** [comment] 2022-03-17 11:28
Duplicate of #16569

**Closed by rami-elementor** 2022-03-17 11:28 UTC
