### ISSUE TITLE
Extra quote in the widget "Divider"

### ISSUE THREAD

**Issue by VadymPogorelov** [elementor/elementor#9111] opened 2019-09-17 14:17 UTC
When you output the layout of the "Divider" widget, you left an extra quote: https://www.screencast.com/t/tBd1Ajh3f
As a result in html we have: https://www.screencast.com/t/MSMhjdEx

**Comment by shilo-ey** [comment] 2019-09-18 07:29
Duplicate of #9102

**Closed** 2019-09-18 07:29 UTC
