### ISSUE TITLE
Elementor not applying borders to columns at all

### ISSUE THREAD

**Issue by jazir5** [elementor/elementor#13082] opened 2020-11-16 21:36 UTC
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

I am trying to add a border to a column, i want to add a border to the right side 1px wide as a divider. However, none of the border settings get applied. Borders work on sections, but are completely bugged on columns, they are not applying to the page. I've created a small 5 second recording of the bug in question so you can see what i mean: http://www.mediafire.com/file/w9j47bn8voh7kmz/error2.mp4/file

## Steps to reproduce

Create a column. Try to apply a border to it.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## System info

https://pastebin.com/xPK6FZFZ

**Comment by odivius** [comment] 2020-11-18 14:38
+1

No borders, no border colors, no rounded borders, no box shadows for columns

**Comment by odivius** [comment] 2020-11-18 14:44
I think I found the solution.
First you have to insert another widget in your column. Then the ajustments start to work.

**Comment by DorShahar** [comment] 2020-11-22 12:25
Hi @jazir5 
I couldn't reproduce the issue.
Try to work with our Hello theme, and deactivate other plugins in order to isolate the problem.

I'm closing the issue. If the problem still happens, please tag me in this issue.

Thanks.

**Closed by DorShahar** 2020-11-22 12:25 UTC
