### ISSUE TITLE
 add the loading page to the elementor theme builder

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#14449] opened 2021-04-06 11:59 UTC
Please add the loading page to the elementor theme builder, such as the 404 page that exists.
The loading page with Lottie animation widget can be very attractive.
This feature is really needed.
please check it.

Thanks

**Comment by DorShahar** [comment] 2021-04-06 16:11
Hi @79ho3ein 
Thanks for your feedback. 
We are working on it, Stay tuned!

**Comment by 79ho3ein** [comment] 2021-04-06 19:17
Thanks

**Comment by 79ho3ein** [comment] 2021-06-21 22:17
Hi @DorShahar 
Will this feature be added to elementor in 2021?
Can you give me information about when this feature will be released?

Thank you for your efforts‌

**Comment by d19dotca** [comment] 2021-06-21 22:45
> Hi @DorShahar 
> 
> Will this feature be added to elementor in 2021?
> 
> Can you give me information about when this feature will be released?
> 
> 
> 
> Thank you for your efforts‌

I'm pretty sure I saw "loading animations" in the Elementor video they published a couple weeks back as a sneak preview to what features to expect in 2021.

**Comment by 79ho3ein** [comment] 2021-06-21 23:01
Thank you @d19dotca
Is that exactly what you mean?  Loading page?  https://youtu.be/hhXt_bcC-wo
If so, that's really great.

**Comment by 79ho3ein** [comment] 2021-06-21 23:05
Yes, I had seen it, but I had not paid attention to it.👍🏻👍🏻👍🏻👍🏻👍🏻
I am very happy about this.  Thanks for letting me know buddy🌹🌹🌹🌹

**Comment by d19dotca** [comment] 2021-06-21 23:05
> Thank you @d19dotca
> Is that exactly what you mean? Loading page? https://youtu.be/hhXt_bcC-wo
> If so, that's really great.

Check out the Elementor video at 14 seconds on here (link already jumps you to 14 seconds in) where it says "Page Transitions" which I believe is what you're really looking for and what the video you provided earlier seems to indicate too: https://youtu.be/zUBG27llWKQ?t=14

**Comment by 79ho3ein** [comment] 2021-06-21 23:12
Yes, it is.
Thank you for informing me, brother🌹

**Comment by 79ho3ein** [comment] 2021-06-30 17:14
Hello
Elementor developers say there is no download page in the 2021 video.
Rather, it is the page transition feature we saw in the 2021 video.

**Comment by d19dotca** [comment] 2021-06-30 18:08
> Hello
> Elementor developers say there is no download page in the 2021 video.
> Rather, it is the page transition feature we saw in the 2021 video.

Not sure what you mean there. A "download page" is very different than a "loading page". A loading page is known simply as a transition that appears upon load of each page to indicate to the user that it's still loading data from the backend. Where does "download page" fit in here?

**Comment by 79ho3ein** [comment] 2021-06-30 18:21
hi @d19dotca ,Thank you for your answer. I mistyped the download page. I meant the loading page. There was an error translating Google.
This plugin is exactly what I hope will be added to elementor : https://fa.wordpress.org/plugins/loading-page/
But the feature that elementor has decided to add in 2021 is page transition, which I do not know what.

**Comment by d19dotca** [comment] 2021-06-30 18:31
> This plugin is exactly what I hope will be added to elementor : https://fa.wordpress.org/plugins/loading-page/
> But the feature that elementor has decided to add in 2021 is page transition, which I do not know what.

I may be misunderstanding then but it seems that what you're looking for is what's coming. Per your original request, you noted the following:

> The loading page with Lottie animation widget can be very attractive.

That is basically what a page transition is in most cases. Unless that's not what they have in mind, but @DorShahar did say to "stay tuned" as they're "working on it", so I presume this is indeed coming at least in the way that they and I would understand the original request. I think "loading page" and "page transitions" are effectively the same thing... they serve the purpose of notifying the user through an animation of some sort that the page is still loading and will be ready for them in a moment. That's what's coming soon, at least as far as I'm aware.

**Comment by d19dotca** [comment] 2021-07-27 15:45
https://github.com/elementor/elementor/issues/10576#issuecomment-887623456

**Comment by d19dotca** [comment] 2021-07-27 15:45
I'm thinking this should be closed as a duplicate of https://github.com/elementor/elementor/issues/10576

**Comment by 79ho3ein** [comment] 2021-07-27 16:37
Yes, I will close it. thank you

**Closed** 2021-07-27 16:37 UTC
Labels: request/feature
