### ISSUE TITLE
🚀 Smart dynamic tag for Text Editor widget

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#18552] opened 2022-05-01 16:40 UTC
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

Currently, we have dynamic tag option in the Text Editor widget. But there is a problem ...

If we use dynamic tag in this widget, that dynamic tag will be applied to all the text in this widget : https://prnt.sc/WljSgmdWf7uE
But it would be great if you could develop dynamic tag option in this widget. So that we can apply the dynamic tag to part of the text typed in this widget.Just select the desired text, then click the Dynamic button to make it dynamic  : https://prnt.sc/b1k-_IsFp6Qn
**Therefore, according to the previous screenshot, using this option, we can aplly the dynamic tag only on "Lorem ipsum"**
This is really great as well as required. Rival page builder (bricks) now uses this feature.

Finally I had another suggestion for this widget ...

Please add the dynamic tag option to the link section of this widget. It can be very useful. https://prnt.sc/aw2LMM1b3MxS

thank you

### Describe the solution you'd like

1- Be able to dynamicize only part of the text in the Text Editor widget.
2- Dynamic tag option, for the link section in the Text Editor widget.

**Comment by arielk** [comment] 2022-08-24 11:33
Duplicate of https://github.com/elementor/elementor/issues/19402

**Closed by arielk** 2022-08-24 11:33 UTC
Labels: request/enhancement, component/dynamic-tag, type/dynamic-content
