### ISSUE TITLE
Icon font manager

### ISSUE THREAD

**Issue by luizbills** [elementor/elementor#110] opened 2016-06-20 17:07 UTC
Ability to add your own icon fonts. Just uploding a zip with the font files, the css file and a conf file with the list of icon classes (maybe a json). And to remove the default font awesome (if the user wants).

**Comment by About2git** [comment] 2016-10-04 13:55
Yeah, this would be great. We could use: http://fontello.com/ Where you even can upload own icons and json and co. is automatically generated…

**Comment by badcat** [comment] 2016-11-08 17:12
Yes!  Would love to have the ability to make a call to any of the existing Font Awesome library icons from within the Social Icon section.

**Comment by LDX1** [comment] 2016-11-15 08:41
Could be useful if we can simply insert an icon also in the standard Text Editor Widget as a span element.

**Comment by drawcard** [comment] 2016-12-28 22:39
[IcoMoon](www.icomoon.io) is one of the bigger generators out there, and creates very customisable and clean CSS / SCSS as well. Would be great to support that.

I like @badcat 's idea too, about choosing whatever icon you please in the Social Icon section, to take care of niche services like Slack or Discord.

**Comment by pingram3541** [comment] 2017-01-24 18:49
Yes please, it would so nice to allow for font-awesome icons in the social element so we can choose generic icons to link to services not listed?

**Comment by drawcard** [comment] 2017-03-08 23:21
> So far working with Elementor has been an awesome experience.

I second this :) My entire WP workflow has changed (for the better) thanks to this plugin 💪

**Comment by maxnaud** [comment] 2017-05-24 00:10
I second to that, other Page Builders have the feature to at least choose a custom file as icon. Thanks!

**Comment by nickdgreen** [comment] 2017-06-07 09:00
when choosing an icon it would be great to be able to have the option of adding the "fa fa-code" of a font awesome icon giving access to any new icons not currently included in the dropdown list.

**Comment by drawcard** [comment] 2017-06-07 09:09
That is a top notch idea, though probably something that only coders would understand. Still it could be toggled on or off as "advanced features" in the settings page.

Perhaps another idea is to simply have a checkbox toggle that hides the standard FA icon set, and then that activates the custom icon class refs option.

**Comment by albionselimaj** [comment] 2017-07-05 08:46
While probably not the best approach, a workaround to adding custom icons would be to override the Elementor Icon control class with a custom class, and adding the extra icons in the 'get_icons()' method.
 [See example.](https://gist.github.com/albionselimaj/3b569012a296cc27ecbe800e97e3a6e2)

**Comment by black-eye** [comment] 2017-09-11 22:15
+1

**Comment by ramonztro** [comment] 2017-09-13 22:55
+1

**Comment by GreenRidingHood** [comment] 2017-09-14 19:43
@albionselimaj thanks for sharing!!
I am usually try to not to edit PLUGIN file, Is there any suggestion without touching wp-content/plugins , because If I remember correctly they will gone with every update

thanks

**Comment by ianstudio** [comment] 2017-09-16 11:41
Pleeeeeaaaaase this is important.. btw the new https://visualcomposer.io/ has a decent Icon tool with several icon fonts, though they do not let you upload your own.. But still much better than "ours" :/ You cannot let the competition get the better of Elementor :0)

**Comment by fthiesen** [comment] 2017-09-16 21:19
+1

**Comment by albionselimaj** [comment] 2017-09-17 14:28
@GreenRidingHood you don't have to touch the wp-content/plugins directory, just put that code in your theme. It overrides the default Icon class through the `elementor/controls/controls_registered` action.

**Comment by GreenRidingHood** [comment] 2017-09-18 13:40
@albionselimaj  I will try , thanks :thumbsup:

**Comment by renathosiqueira** [comment] 2017-10-01 15:22
+1
Will be GREAT can add more icons to Elementor!

**Comment by zeinnicholas** [comment] 2017-10-15 23:00
@albionselimaj Hey, I liked your idea as a temporary solution. Can you elaborate more on that? Like what you need to do in each "path/to/font.php" file called in the array? Just declare the classes as what's already being done in the original control, or we need to do more than that? I'm almost figuring it out, but I think I'm missing something. Did you managed to make it work?

**Comment by albionselimaj** [comment] 2017-10-16 15:10
@zeinnicholas The font file should return an array of class names (e.g. for Font Awesome, `return ['fa-address-book', 'fa-adjust', ...];`.

Also, make sure to enqueue the font styles in the elementor preview using `elementor/editor/after_enqueue_scripts` action hook, e.g.
```
add_action( 'elementor/editor/after_enqueue_scripts', function() {
    wp_enqueue_style('font-awesome', get_template_directory_uri() . '/assets/styles/vendor/font-awesome.css');
});
```
Yes, I've managed to make it work, and am using it in a project.

**Comment by lizrosenshine** [comment] 2017-10-23 03:08
+1

**Comment by drawcard** [comment] 2017-10-24 23:27
What if there was the ability to upload your own SVG's (say in the General Settings page) and just have elementor treat them as custom icons that can be selected from the icon library? They could have the same classes applied to them so they work just like regular icon fonts, but you also have the advantage of using whatever you want without loading up extra fonts etc.

**Comment by ianstudio** [comment] 2017-10-25 07:27
@drawcard This extension does it fairly well, though I wish it had a coloring option for regular and hover states.. but they think that since some svg' cannot be colored correctly it would not be a good idea, I beg to differ, a lot of svg's are single-colored and would work perfectly that way (I do use it for icons and add my color states in css).
https://wordpress.org/plugins/inline-svg-elementor/

**Comment by mgpub** [comment] 2017-11-16 20:25
+1 - I've already been limited by the small selection of icons on multiple projects

**Comment by cbrcongit** [comment] 2018-01-19 05:47
@albionselimaj I'm having trouble 'connecting-the-dots' by recreating the solution in your comments;
Can you please

- [ ] Create a Repo with the full directory structure and modified + added files

- [ ] Include an IcoMoon set (and other IcoMoon files for context/reverse-engineering)



If I can try to summarise this issue, and offer solution to it still being open/unresolved:

## Description

- Iconbox has a "fixed list" of FontAwesome icons to choose from. The list is not exhaustive (quite limited).
- - @drawcard "IcoMoon is one of the bigger generators out there, and creates very customisable and clean CSS / SCSS as well."... further, for product strategy, imagine the amazing designs we could attribute to Elementor enabling TheNounProject+IcoMoon graphical elements! (Docs, docs, docs!)
- - @luizbills "And [add the ability] to remove the default font awesome (if the user wants)."
- There is no function for uploading custom icons.
- The docs on how to add custom icons (e.g. IcoMoon, Fontello, etc) are not available; There are some broken threads of an idea posted here: https://github.com/pojome/elementor/issues/110

## Steps to reproduce

1. Add an IconBox Widget and select it to '**Edit Icon Box**';
2. In the 'Edit Icon Box' sidebar, open the dropdown selector labelled '**Choose Icon**';
3. Reveal a very limited and uncustomisable list of icons;
4. Try to add custom icons; Fail, Waste Time, lose hope in the product;
5. Ask again for a resolution to the issue...

## Environment

All

## Keys to Issue-Resolution

- [ ] Create a Plugin enabling IcoMoon, Fontello, and other custom Icon services/soultions (likely based on concepts developed by @albionselimaj `https://gist.github.com/albionselimaj/3b569012a296cc27ecbe800e97e3a6e2`)

**Comment by davidmcc3** [comment] 2018-01-19 15:47
Not quite on the same tack, but similar. Or should I start a new thyread?

Could the Icon set (in Price Table) have a 'none' option, so the text renders in a nice block without any icon or first-line indent.

Thanks, David

**Comment by drawcard** [comment] 2018-01-20 06:34
You should probably start new issue @davidmcc3 or else it will probably get overlooked in the discussion of this one :wink:

**Comment by zeinnicholas** [comment] 2018-01-20 17:15
@cbrcongit I couldn't make this work either... My solution was to manually change the Icon.php file (poor solution) and add my icon font manually. But I have to redo this every time I update Elementor...

**Comment by ryanlabelle** [comment] 2018-01-20 19:03
Hey guys, we created a widget plugin that adds custom icons, feel free to use it as an example. 

https://github.com/ryanlabelle/th-widget-pack

**Comment by cbrcongit** [comment] 2018-01-23 02:45
Ok, so I've used the brilliant work of @ryanlabelle (who had too much extra stuff) and @albionselimaj (who was missing pieces), and created a [plugin in this repo: cbrcongit/elementor-select-icon](https://github.com/cbrcongit/elementor-select-icon) that should simplify our next steps to resolve.

- [x]  :+1: fixed the load hook problem that was making this difficult to implement as a plugin (e.g. `add_action( 'elementor/init', function() { "Deal with Elementor controllers here" });` )
↻ @zeinnicholas, @GreenRidingHood, 

- [x]  :+1: successfully **listed** all custom icons in the 'Choose Icon' dropdown

## Final fixes required

- [ ]  I'm still not seeing any of the IcoMoon icons that have been added though, they list, but they do not display on the page - @albionselimaj and others here, do you think you could [have a look](https://github.com/cbrcongit/elementor-select-icon) and see what we're missing? Please :1st_place_medal: 
↻ @drawcard

- [ ] Still no progress on an 'add your own custom icons' simple UI solution as part of the Choose Icon process; More urgently concerned with the third dot-point (above) though, resolving the use of icomoon fonts for **REAL CUSTOM ICONS**.
↻ @ianstudio @About2git

**Comment by drawcard** [comment] 2018-01-23 02:57
Nice one @ryanlabelle @albionselimaj @cbrcongit 👍 🆒 😎 

I will have a test and see if I can have a shot at resolving the fixes.

**Comment by zeinnicholas** [comment] 2018-01-24 01:26
@cbrcongit 

very nice! Thanks! I will take a look.

About not seeing any of the IcoMoon icons, what do you mean?

1. The plugin works, it lets us select custom icons, but it only shows on the front-end (not able to see them in the visual builder).
2. The plugin works, as we can see the files are loaded, but it does not let us to select any custom icon. We can only call it's CSS class, but we can still see the custom icons on the front-end.
3. Nothing happens at all for IcoMoon custom icons only. But other famous font icons (like Material and FA 5) work brilliantly.

**Comment by cbrcongit** [comment] 2018-01-24 14:19
The plugin is a compilation of the efforts commented by others (in this thread); It consolidates the progress of code offered on this issue.

It currently loads a list for IcoMoon fonts that are added, but it is not loading the icon "assets" in order to display them.

I can add a full documentation to it for how to add custom "fonts / icon assets", but would rather wait until the IcoMoon fix is found. I believe @drawcard and @aldionselimaj have the skills to produce the code fix; Then I will read it and document how-to :ok_hand:

**Comment by cbrcongit** [comment] 2018-01-24 14:19
The plugin is a compilation of the efforts commented by others (in this thread); It consolidates the progress of code offered on this issue.

It currently loads a list for IcoMoon fonts that are added, but it is not loading the icon "assets" in order to display them.

I can add a full documentation to it for how to add custom "fonts / icon assets", but would rather wait until the IcoMoon fix is found. I believe @drawcard and @aldionselimaj have the skills to produce the code fix; Then I will read it and document how-to :ok_hand:

**Comment by cbrcongit** [comment] 2018-01-24 14:27
@pojome is this something you can help close-out? And/Or are you looking at adding an "upload your own icon" noncoder feature to choosing icons?

I'm new to github public threads, but usually check in with the dev - are you still looking at this issue as prioirity?

**Comment by zeinnicholas** [comment] 2018-01-24 14:57
@cbrcongit This is what I was using to add custom icons:
https://gist.github.com/zeinnicholas/9829a0b32d74bc8aaccb16203d4a8047
Basically I opened the icon.php file directly in Elementor, and added the icon list (a custom icoMoon pack I made). at line 1329 I managed to call the icon font using as reference that I got somewhere on the Elementor docs.

Maybe this fixes the issue?

Surely if we want custom icons (as of now) we should add them manually to the plugin and make this call, right?

**Comment by drawcard** [comment] 2018-01-24 23:36
Just to clarify @cbrcongit's comment - I am not an expert PHP developer nor am I on the Elementor team (just a front end dev that's contributed a bit here and there to Elementor) but I am happy to have a poke around and see if I can figure out what's going on :smile: 

If FA5 is working, chances are it's because something is hardwired into Elementor that accepts the fa- naming system, but nothing else. That's my gut feeling anyway.

I've cloned the plugin and have set up a blank WP site to test things in, I was hoping to take a look but this week has been a bit crazy with Australia Day coming up on Friday. I'm pretty enthusiastic about finding a solution though so I will find a bit of time somewhere soon :)

**Comment by cbrcongit** [comment] 2018-02-01 04:29
**Solved** IcoMoon custom icons for Elementor:

1 . Create a plugin with the following 

```
add_action( 'elementor/init', function() {
if ( ! defined( 'ABSPATH' ) ) exit;

class Elementor_Control_Icon extends Elementor\Base_Control {
	
	public function get_type() {
		return 'icon';
	}

	public static function get_icons() {
				return [
		'icon-noun_977768' => 'noun professional',
	        'icon-noun_977793' => 'noun health safety',
	        'icon-noun_1245026' => 'noun bicycle',
	        'icon-noun_1248182' => 'noun engineer mechanical',
	        'icon-noun_1258170' => 'noun engineer solve',
	        'icon-noun_1267333' => 'noun human resources',
	        'icon-noun_1273446' => 'noun engineer fit',
	        'icon-noun_1273443' => 'noun manager',
	        'icon-noun_1278287' => 'noun weather cold',
	        'icon-noun_977698' => 'noun technician',
	    ];

	protected function get_default_settings() {
		return [
			'icons' => self::get_icons(),
		];
	}

	public function content_template() {
		?>
		<div class="elementor-control-field">
			<label class="elementor-control-title">{{{ data.label }}}</label>
			<div class="elementor-control-input-wrapper">
				<select class="elementor-control-icon" data-setting="{{ data.name }}" data-placeholder="<?php _e( 'Select Icon', 'elementor' ); ?>">
					<option value=""><?php _e( 'Select Icon', 'elementor' ); ?></option>
					<# _.each( data.icons, function( option_title, option_value ) { #>
					<option value="{{ option_value }}">{{{ option_title }}}</option>
					<# } ); #>
				</select>
			</div>
		</div>
		<# if ( data.description ) { #>
		<div class="elementor-control-field-description">{{ data.description }}</div>
		<# } #>
		<?php
	}
};
wp_enqueue_style('icomoon', plugin_dir_url( __FILE__ ) . 'style.css' );
});

?>
```
2. Use [your own svg's in the icomoon font generator](https://www.sitepoint.com/create-an-icon-font-illustrator-icomoon/). I usually find great SVG's from [awesome designer's work at The Noun Project](https://thenounproject.com/leremy/)

3. The array in the plugin above (e.g. `'**icon-noun_977768**' => 'noun professional',`) makes reference to the downloaded Icomoon stylesheet (style.css) ID's (e.g. `.**icon-noun_977768**:before {  content: "\e900";}`)

4. The original Elementor array can be found in `..plugins/elementor/includes/controls/icon.php`

**Comment by drawcard** [comment] 2018-02-01 04:54
This is legendary, well done :)

You should submit it as a PR and get it merged into the main project!

**Comment by zeinnicholas** [comment] 2018-02-07 11:15
Hey @cbrcongit is it working for you on Elementor 1.9.3?

I couldn't find to make it work with the files on your repo =/ It's like Elementor is ignoring the plugin...

**Comment by codeagencybe** [comment] 2018-04-16 08:57
Is this a way to load FA5 pro icons into Elementor? 
I'm one of the early adopters and backers on kickstarters and have my personal Pro license to use in my projects. 

So I have many more options available now, but I can't use it everywhere. 
I'm using the script to load FA5 into my project, but if I want to use e.g. iconbox, I still can not select any of the FA5 pro icons. 

@cbrcongit Does your plugin can solve this? Or does anybody know a way how to pull this one off?

**Comment by joffcrabtree** [comment] 2018-04-18 03:51
+!

**Comment by oinformatico** [comment] 2018-04-21 13:08
Hi
I took the tips that gave us back and improved the plugin. It has more than 1000 different icos. Hope you like it.

[elementor-iconbox.zip](https://github.com/pojome/elementor/files/1934524/elementor-iconbox.zip)

You can find more about our work in the https://www.informatico.pt/

**Comment by CarlosElPoulpo** [comment] 2018-05-09 19:53
+1 for custom support and the possibility to integrate Font Awesome Pro 5

**Comment by oshibobo** [comment] 2018-05-11 00:40
+1 for custom support and the possibility to add PNG Icons

**Comment by drawcard** [comment] 2018-05-11 01:53
> PNG Icons

& SVG icons too ;)

**Comment by drawcard** [comment] 2018-05-11 01:55
At this point in time I'd be happy with just some sort of primitive option to upload your own SVG's, give them a unique identifying name, and then pick them from the selection that sits on top of Elementor's default FA set. Not sure if anyone else agrees with that or not, but that could speed up the path to getting us custom icons in E.

**Comment by Raccroc** [comment] 2018-05-11 18:25
Thanks for the elementor-iconbox.zip oinformatico, that helped with a couple sites (although, as an fyi, it did create issues with editing the social icon widget).

What I would really like to know is, is there is a solution to adding in custom icons or a solution on the near horizon road-map? People have be requesting this for well over a year and was hoping that it would be addressed in 2.x.  Without an official way, you end up with a bunch of custom PHP/CSS files and edits...that makes it such a pain to make changes down the road and near impossible to hand of to anther user to support.

I am building a dog rescue site and need to use icons for things like bones, doghouses, collars, etc. and am about to be forced to scrap the entire site to rebuild in another builder if I cannot figure out a way around this limitation.

**Comment by parfilov** [comment] 2018-05-12 13:46
+1

**Comment by DeoThemes** [comment] 2018-05-22 04:07
I've implemented @cbrcongit code to create custom control with a list of my own icons. Now I'm struggling how to apply this control to my custom widget. Here is my code - https://gist.github.com/DeoThemes/af8a369b33dc8920118c82cae2af3078

It doesn't show controls in a custom widget, it's just empty. However this extension works fine with a default icon box widget.

**Comment by themedleb** [comment] 2018-05-26 18:01
+1

**Comment by kingfisher64** [comment] 2018-07-19 16:02
New to elementor, very much enjoying it.

One thing I keep thinking would be handy is from the icon drop down field on whatever element would be custom icons. Like now wanting to add an icon to a tab (without css background image hack). 

How do I hack/add custom choices to this dropdown list?

@Raccroc did you sort it for your dogs site? :)

**Comment by Raccroc** [comment] 2018-07-19 18:57
@kingfisher64 no, I didn't.  I pretty much ran into a lot of the same issues as @DeoThemes with most everything I tried either breaking Font Awesome, screwing up other widgets, or not working consistently.  I largely gave up since the dev teams seems way more interested in putting out features to facilitate the rapid cookie cutter deployment of web sites (templates, copy & paste elements, etc.).  

I decided to roll out with "good enough" for now so I can begin working our our Intranet site.  I am testing alternative builders to use so that once completed, I can come back and rewrite our web site using the different builder and implement custom icons (we are also having our logo designer create a full custom icon suite to match our logo/branding, and going this route removes a lot of the pressure to rush them).

There is a lot to like about Elementor (I especially like the move away from needing much from your theme, like custom headers/footers) and the Pro support is excellent.  But if custom icons are at all important to you, there are better builders out there (and I wish I had know that before I got as far along as I did).

**Comment by BrookeRaraAvis** [comment] 2018-07-21 05:42
+1 for any custom SVG on all elements that support icons

**Comment by earwolf** [comment] 2018-07-25 10:09
+1 for custom icons

**Comment by bodhi1970** [comment] 2018-07-28 20:04
+1

**Comment by twerkema** [comment] 2018-07-31 16:07
+1. Also a designer in need of being able to fully customize iconography.

**Comment by kaisuketrax** [comment] 2018-08-01 08:51
+1

**Comment by bentalgad** [comment] 2018-08-02 13:50
+1 for support of custom icon font management

**Comment by bentalgad** [comment] 2018-08-03 13:57
https://wordpress.org/plugins/custom-icons-for-elementor/

**Comment by kingfisher64** [comment] 2018-08-04 19:45
@bentalgad - you got there just ahead of me! https://wordpress.org/plugins/custom-icons-for-elementor/. Finally a solution.

**Comment by fxaviers** [comment] 2018-09-08 17:50
+1

**Comment by IamSiddharth** [comment] 2018-09-11 17:02
+1

**Comment by knightknight** [comment] 2018-09-22 19:35
+1

**Comment by amindiary** [comment] 2018-09-27 13:27
oprnrf in 2016, still nothing? 👎

**Comment by timsamuelsson** [comment] 2018-12-21 12:30
My work is going all in on Elementor, this would be a killer feature.

**Comment by Kpudlo** [comment] 2019-02-20 15:10
Really hoping to see this make it in Elementor!

**Comment by shilo-ey** [comment] 2019-07-23 10:09
This feature has been added to Elementor Pro v2.6.0

Feel free to update

Thanks!

**Closed by shilo-ey** 2019-07-23 10:09 UTC
Labels: pro, request/enhancement, request/feature
