### ISSUE TITLE
[🧐 Evaluating] 🐞 Bug Report: Menu widget styles are broken after updating Elementor Pro to version 3.16

### ISSUE THREAD

**Issue by ChrisASearles** [elementor/elementor#23753] opened 2023-09-12 20:56 UTC
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Had a couple of sites using the Menu widget with auto-updates enabled and everything broke as soon as the new version came out. Adding a new Menu to a page also does not work. Everything looks fine in the builder but it looks like the styles aren't being loaded on the page somehow. Rolling back to 3.15 fixed the problem.

### Steps to reproduce

Add menu to page, save, view it.

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

<details>
<summary>Click to reveal</summary>

````txt


					
== Server Environment ==
	Operating System: Linux
	Software: nginx/1.24.0
	MySQL version: mariadb.org binary distribution v10.11.5-MariaDB-1:10.11.5+maria~ubu2004
	PHP Version: 8.0.28
	PHP Memory Limit: 512M
	PHP Max Input Vars: 10000
	PHP Max Post Size: 128M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.3.1
	Site URL: https://djaimports.com
	Home URL: https://djaimports.com
	WP Multisite: No
	Max Upload Size: 128 MB
	Memory limit: 40M
	Max Memory limit: 512M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: America/New_York
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.8.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36

== Active Plugins ==
	Add More Shipping Fields (For Multi Part Product)
		Version: 1.1.2
		Author: PluginHive

	Advanced Custom Fields
		Version: 6.2.1
		Author: WP Engine

	Advanced Google reCAPTCHA
		Version: 1.0.15
		Author: WebFactory Ltd

	Advanced Woo Search
		Version: 2.87
		Author: ILLID

	Code Snippets
		Version: 3.4.2
		Author: Code Snippets Pro

	Constant Contact + WooCommerce
		Version: 2.1.2
		Author: Constant Contact

	Constant Contact Forms for WordPress
		Version: 2.2.0
		Author: Constant Contact

	Cookie Notice & Compliance for GDPR / CCPA
		Version: 2.4.10
		Author: Hu-manity.co

	Draw Attention Pro
		Version: 3.0.9
		Author: N Squared

	Elementor
		Version: 3.15.3
		Author: Elementor.com

	Elementor Pro
		Version: 3.15.1
		Author: Elementor.com

	Enhanced Media Library
		Version: 2.8.9
		Author: wpUXsolutions

	Essential Addons for Elementor
		Version: 5.8.8
		Author: WPDeveloper

	Facebook for WooCommerce
		Version: 3.0.33
		Author: Facebook

	Google Listings and Ads
		Version: 2.5.5
		Author: WooCommerce

	HubSpot All-In-One Marketing - Forms, Popups, Live Chat
		Version: 10.2.5
		Author: HubSpot

	Imagify
		Version: 2.1.1
		Author: Imagify – Optimize Images & Convert WebP

	JetMenu
		Version: 2.4.0
		Author: Crocoblock

	JetSmartFilters
		Version: 3.2.0
		Author: Crocoblock

	JetWooBuilder For Elementor
		Version: 2.1.7
		Author: Crocoblock

	Members
		Version: 3.2.7
		Author: MemberPress

	myCred
		Version: 2.5.3
		Author: myCred

	myCRED for Elementor
		Version: 1.2.2
		Author: myCRED

	Ninja Tables
		Version: 5.0.2
		Author: WPManageNinja LLC

	PH Hide WooCommerce Shipping Methods & Rate Adjustment
		Version: 1.0.3
		Author: PluginHive

	Product Recommendations - Custom Locations
		Version: 1.0.3
		Author: SomewhereWarm

	ReviewX
		Version: 1.6.22
		Author: WPDeveloper

	Site Kit by Google
		Version: 1.109.0
		Author: Google

	Smart Coupons For WooCommerce Coupons
		Version: 1.4.9
		Author: WebToffee

	Timeline Widget For Elementor
		Version: 1.5
		Author: Cool Plugins

	Visibility Logic for Elementor
		Version: 2.3.5.1
		Author: StaxWP

	WooCommerce
		Version: 8.0.3
		Author: Automattic

	WooCommerce Authorize.Net Gateway
		Version: 3.9.3
		Author: SkyVerge

	WooCommerce Blocks
		Version: 11.1.0
		Author: Automattic

	WooCommerce Conversion Tracking
		Version: 2.0.10
		Author: weDevs

	WooCommerce Enable Reviews - Bulk Edit
		Version: 1.0.0
		Author: Mário Valney

	WooCommerce Google Analytics Integration
		Version: 1.8.4
		Author: WooCommerce

	WooCommerce Product Recommendations
		Version: 2.4.2
		Author: WooCommerce

	WooCommerce Sync for QuickBooks Desktop - by MyWorks Software
		Version: 1.8.3
		Author: MyWorks Software

	WooCommerce Sync for QuickBooks Desktop - Custom Field Mapping
		Version: 1.1
		Author: MyWorks Software

	WooCommerce UPS Shipping Plugin with Print Label
		Version: 4.8.2
		Author: PluginHive

	Woo Discount Rules
		Version: 2.6.1
		Author: Flycart

	Woo Discount Rules PRO 2.0
		Version: 2.6.1
		Author: Flycart

	WP Rollback
		Version: 1.7.3
		Author: GiveWP.com

	Yoast SEO
		Version: 21.1
		Author: Team Yoast

	Yoast SEO Premium
		Version: 21.1
		Author: Team Yoast


== Must-Use Plugins ==
	Kinsta Must-use Plugins
		Version: 3.0.0
		Author: Kinsta Team


== Features ==
	Custom Fonts: 0
	Custom Icons: 0

== Integrations ==
	
	recaptcha_v3: Active
	woocommerce: Active


== Elementor Experiments ==
	Optimized DOM Output: Active
	Improved Asset Loading: Active
	Improved CSS Loading: Inactive by default
	Inline Font Icons: Active
	Additional Custom Breakpoints: Active
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active
	Upgrade Swiper Library: Inactive by default
	Grid Container: Active
	Default to New Theme Builder: Active by default
	Hello Theme Header & Footer: Inactive by default
	Editor Top Bar: Active
	Landing Pages: Active by default
	Nested Elements: Active
	Lazy Load Background Images: Inactive by default
	Global Style Guide: Active
	Page Transitions: Active by default
	Notes: Active by default
	Loop: Active by default
	Form Submissions: Active by default
	Scroll Snap: Active by default
	Menu: Active
	Taxonomy Filter: Active


== Log ==
	
Log: showing 20 of 322023-09-12 05:18:32 [info] elementor::elementor_updater Started 
2023-09-12 05:18:32 [info] Elementor/Upgrades - _on_each_version Start  
2023-09-12 05:18:32 [info] Elementor/Upgrades - _on_each_version Finished 
2023-09-12 05:18:32 [info] Elementor/Upgrades - _v_3_16_0_container_updates Start  
2023-09-12 05:18:35 [info] Elementor/Upgrades - _v_3_16_0_container_updates Finished 
2023-09-12 05:18:35 [info] Elementor/Upgrades - _v_3_17_0_site_settings_updates Start  
2023-09-12 05:18:35 [info] Elementor/Upgrades - _v_3_17_0_site_settings_updates Finished 
2023-09-12 05:18:35 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.15.3',
  'to' => '3.16.0',
)]
2023-09-12 14:54:40 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.16.0',
  'to' => '3.16.1',
)]
2023-09-12 14:54:46 [info] elementor::elementor_updater Started 
2023-09-12 14:54:46 [info] Elementor/Upgrades - _on_each_version Start  
2023-09-12 14:54:46 [info] Elementor/Upgrades - _on_each_version Finished 
2023-09-12 14:54:46 [info] Elementor/Upgrades - _v_3_17_0_site_settings_updates Start  
2023-09-12 14:54:46 [info] Elementor/Upgrades - _v_3_17_0_site_settings_updates Finished 
2023-09-12 14:54:46 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.16.0',
  'to' => '3.16.1',
)]
2023-09-12 14:56:57 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.15.1',
  'to' => '3.16.0',
)]
2023-09-12 14:57:04 [info] elementor-pro::elementor_pro_updater Started 
2023-09-12 14:57:04 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-09-12 14:57:04 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-09-12 14:57:04 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.15.1',
  'to' => '3.16.0',
)]

JS: showing 6 of 6JS: 2023-08-16 20:04:25 [error X 1][https://djaimports.com/wp-content/plugins/leadin/build/elementor.js?ver=10.2.1:6558:9] View (cid: "view15400") has already been destroyed and cannot be used. 
JS: 2023-08-23 11:48:42 [error X 4][https://djaimports.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.15.3:3:642692] Cannot read properties of undefined (reading 'isDesignable') 
JS: 2023-08-23 12:06:58 [error X 2][https://djaimports.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.15.3:3:838767] Cannot convert undefined or null to object 
JS: 2023-08-23 18:34:10 [error X 1][https://djaimports.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.15.3:3:54034] Cannot read properties of undefined (reading 'activate') 
JS: 2023-09-11 15:59:00 [error X 1][https://djaimports.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.15.3:3:802633] Cannot read properties of undefined (reading 'toLowerCase') 
JS: 2023-09-12 19:25:25 [error X 3][https://djaimports.com/wp-content/plugins/elementor-pro/assets/js/mega-menu.7a85dd5077e11520ec44.bundle.min.js:2:15283] Cannot read properties of null (reading '$headingContainer') 

PHP: showing 4 of 4PHP: 2023-08-17 17:30:10 [warning X 1][../wp-content/plugins/elementor-pro/modules/forms/classes/recaptcha-v3-handler.php::124] Undefined array key "score" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-08-23 09:53:26 [warning X 20][../wp-content/plugins/elementor/core/common/modules/ajax/module.php::175] Undefined array key "data" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-08-23 09:53:29 [warning X 108][../wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php::150] Undefined array key "condition_type" [array (
  'trace' => '
#0: ../wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(150): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_template_json_item()
#2: ../wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(120): class type array_map()
#3: ../wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(59): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_templates_json()
#4: ../wp-content/plugins/elementor/data/base/endpoint.php(158): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> get_items()
',
)]
PHP: 2023-08-31 18:21:31 [warning X 2][../wp-content/plugins/elementor-pro/modules/forms/classes/ajax-handler.php::76] Undefined array key "form_id" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]



== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatible
	Essential Addons for Elementor: Compatible
	JetWooBuilder For Elementor: Incompatible
	myCRED for Elementor: Compatibility not specified
	Timeline Widget For Elementor: Compatible
	Visibility Logic for Elementor: Incompatible

== Elementor Pro - Compatibility Tag ==
	
	Essential Addons for Elementor: Compatible
	JetWooBuilder For Elementor: Incompatible
	Timeline Widget For Elementor: Compatible
	Visibility Logic for Elementor: Incompatible
				

````

</details>

**Comment by betatester07** [comment] 2023-09-12 22:22
We had a similar issue. But the problem was that the mega menu CSS file is linked statically directly in generated HTML as `wp-content/plugins/elementor-pro/assets/css/widget-mega-menu.min.css`, which resulted in old version of the file being cached by browser (and server) - no version string is appended in this case.

To verify, check what file contents your browser really gets - there is a comment with Elementor version at the beginning of the CSS file

Clearing all caches helped in our case.

However, this should be fixed and the CSS file should be loaded the standard Wordpress way to prevent such issues!

**Comment by datverse** [comment] 2023-09-13 05:54
Hi, I hotfix by set "Improved CSS Loading" is "Inactive" in Elementor/Settings/Features.

**Comment by nmbrthirteen** [comment] 2023-09-13 10:27
Same issue for me.

**Comment by hein-obox** [comment] 2023-09-13 11:11
@nicholaszein Can you reproduce this issue?

Would the issue be fixed by using Regenerate Css as well?

And we need to check if there is an issue with 'Improved CSS Loading'.

**Comment by betatester07** [comment] 2023-09-13 13:10
@hein-obox Regenerate CSS did not fix the issue for me.

But once again - the problem is that the mega menu CSS file `wp-content/plugins/elementor-pro/assets/css/widget-mega-menu.min.css` is referenced to without version query string, e.g. `wp-content/plugins/elementor-pro/assets/css/widget-mega-menu.min.css?ver=3.16.0`

**Comment by hein-obox** [comment] 2023-09-13 13:54
@betatester07 For the moment emptying the cache should work, I believe.

I understand your comment about the query string. @nicholaszein I believe we should check that.

**Comment by jbuijs** [comment] 2023-09-13 14:37
After updating to Elementor 3.16, the dropdown for the Mega Menu no longer shows for me. It doesn't show in the editor or the front end.

- Regenerate files & data doesn't fix the problem
- Clearing all caches doesn't work either
- Disable 'improved CSS loading' also doesn't help

As long as I stick on Elementor 3.15, everything works fine.
When I roll back to 3.15 from 3.16, the menu also works again.

**Comment by hein-obox** [comment] 2023-09-13 14:40
@jbuijs Can you see any errors in the console? (https://developer.chrome.com/docs/devtools/open/)
Have you updated the core version to 3.16 as well?

**Comment by jbuijs** [comment] 2023-09-13 14:49
@hein-obox I updated the core version, but I didn't update the pro version. After the pro update, the menu dropdown works. Must have missed the pro update. Thanks :)

**Comment by alleninfotrust** [comment] 2023-09-13 15:25
I also cannot get the dropdown menu to work. On hover, the dropdowns show, but when I attempt to move my mouse to the dropdown, it disappears. It appears the element is losing focus during the transition. This was not present until 3.16.

**Comment by Zurieee** [comment] 2023-09-13 15:38
> I also cannot get the dropdown menu to work. On hover, the dropdowns show, but when I attempt to move my mouse to the dropdown, it disappears. It appears the element is losing focus during the transition. This was not present until 3.16.

Same here

**Comment by nmbrthirteen** [comment] 2023-09-13 15:40
Same here, too.

> I also cannot get the dropdown menu to work. On hover, the dropdowns show, but when I attempt to move my mouse to the dropdown, it disappears. It appears the element is losing focus during the transition. This was not present until 3.16.

**Comment by nicholaszein** [comment] 2023-09-13 16:23
Hello @alleninfotrust, @Zurieee, and @nmbrthirteen!

The issue you are reporting about the Menu Item Content prematurely closing is not caused by this update (v3.16). 

It's actually a matter of timing and spacing. In some edge cases, the mouse may hover outside the menu item when you are moving the cursor to the content. When this happens it can cause the content to hide.

There is a workaround solution for that, which is to set the **`Distance from content`** option in the **`Style`** tab of the **`Menu`** widget to **<ins>zero</ins>** or close to zero. This would help avoid the premature closing of the content.

We are aware of this issue, and we are working on adding some improvements to the mega **Menu** widget that will help solve this problem. This is part of a feature that will be added in a future release of Elementor Pro.

We apologize for the inconvenience this might be causing, and we appreciate your patience while we work to improve this widget. 🙏 

There are actually already an issue #23430, and a feature request #21353 that are related to this topic.

Please continue the conversation there. 👇 
- https://github.com/elementor/elementor/issues/23430
- https://github.com/orgs/elementor/discussions/21353

Kind regards

**Comment by betatester07** [comment] 2023-09-13 17:02
> @betatester07 For the moment emptying the cache should work, I believe.
> 

Unfortunately, it did not work for some of our users. Probably because if a web browser already has the old version of the CSS file cached locally and cache period for such file was set to a long period, the browser will not make a request for updated version of the file until the expiration period has passed (other factors might affect this as well).

**Comment by ChrisASearles** [comment] 2023-09-13 19:37
Can confirm clearing caches actually only makes the problem worse, goes from the dropdowns not working to all styles being removed. Deactivating "Improved CSS Loading" does fix the problem.

**Comment by nmbrthirteen** [comment] 2023-09-13 19:39
Improved CSS Loading doesn’t fix this problem for me. I am waiting for a
new release. I’ve rolled back to older version because of that.

**Comment by Daveden2** [comment] 2023-09-13 19:55
> @hein-obox Regenerate CSS did not fix the issue for me.
> 
> But once again - the problem is that the mega menu CSS file `wp-content/plugins/elementor-pro/assets/css/widget-mega-menu.min.css` is referenced to without version query string, e.g. `wp-content/plugins/elementor-pro/assets/css/widget-mega-menu.min.css?ver=3.16.0`

Now I understand why my mega menu was broken even after clearing server cache and regenerating css.

Thanks @betatester07  🙏

**Comment by ChrisASearles** [comment] 2023-09-13 20:47
I'm also seeing the same behavior on sites using the JetMenu plugin so this is not isolated to the Elementor Menu widget.

**Comment by nicholaszein** [comment] 2023-09-13 23:42
Hello, everyone!

Thank you for reaching out! 🙏 

### ⛔ While reviewing your report we concluded this is not a bug caused by Elementor. This is actually a cache problem. Here's what we found out:
In this version, the mega **Menu** and nested **Tabs** widgets received some important changes to their HTML markup. These changes were necessary to:
1. Improve the **Menu** and **Tab** widgets' overall **Performance**;
2. Improve the **Menu** and **Tab** widgets' **Accessibility**.
You can learn more about these changes **[here](https://github.com/orgs/elementor/discussions/23486#:~:text=Menu%20%26%20Tabs%20Widgets%20Update)**.

To quote from the text:

> _**Note:** This update will also apply to existing Menu and Tabs widgets, and may break designs of titles in this widget if custom CSS has been applied to them._

As you can see styles might break for existing instances of the Menu.

This is particularly true for any level of cache implemented on any website. **This is why it's important to always, no matter what you are actually updating, clear the cache after any WordPress, Plugin, or Theme update.**

A good indication of why this is cache-related is when you see the widget working correctly inside the Elementor Editor, but not on the live page (front end) of your website.

### ✅ What you can do to solve your issue:

First, just for the sake of completion, I will explain what to look for when troubleshooting to fix this issue. Then I'll give you a step-by-step of the most efficient way to do it.

#### 1. Cache Levels

There are several levels of cache that might apply to any website, and sometimes you are not even aware of them. 

- **Server Cache** - Most hosting services apply some sort of **cache** or **performance optimization** solution at the **Server** level. Even if you don't have any cache plugin on your site, your hosting provider might be serving a cached version of your pages and assets. It's recommended to check with your hosting provider if you have any sort of cache or performance optimization that might be serving the outdated styles of the Menu widget. But usually, there is an option to do that directly inside the Control Panel.
- **Website Cache** - This type of cache is usually managed directly inside the WordPress dashboard through a performance optimization plugin. This is the most common type of performance optimization and gives users more control over what to optimize. Usually, there is an option to purge the cache in the plugin settings.
- **CDN Cache** - CDNs or Content Delivery Networks are a geographically distributed group of servers that caches content close to end users. A CDN allows for the quick transfer of assets needed for loading Internet content, including HTML pages, JavaScript files, stylesheets, images, and videos. When you update your site, if you don't clear the CDN cache, visitors from all around the world (including yourself) will not be served with the most recent assets. Some hosting companies also use this type of service to complement their own.
- **Browser Cache** - This is the most important type of cache. Usually, any cache solution includes a set of rules to indicate to browsers that they need to download some assets to your local machine and keep them for a set period of time instead of always downloading these assets every time you visit a page. This reduces the time you need to visualize the page since the browser doesn't need to download everything again. However when there are changes, unless your browser is signaled to re-download these assets by the cache engine used, or if it sees something changed in the file version, it won't do it, causing you to see old content or old styles. This is especially true with mobile devices since they enforce a more persistent cache solution to reduce mobile data consumption.

**_Regardless of the level(s) of cache applied to your website, the changes made to both mega Menu and nested Tabs widgets would require a full purge of the cache, otherwise, the styles won't be applied correctly._**

#### 2. How to effectively clear all levels of the cache

First of all, make sure you know which levels of cache are applied to your site. It's important to verify if your hosting provider does apply cache at the server level (Kinsta does for example), and if they also use CDNs to distribute assets geographically. If you can't see those options in your Hosting Control Panel, you might want to reach out to the hosting support to ask for assistance or check their documentation. With that in mind, we are ready to start the cleanup.

1. Purge/clear all levels of cache, and just to be sure, temporarily disable them. In some cases, you might need to completely deactivate the performance optimization plugin.
2. Go to your WordPress **`Dashboard`** > **`Elementor`** > **`Tools`** > **`General`** and click to **`Regenerate CSS & Data`**. This action removes all generated CSS and schedules a task for Elementor to generate the CSS of each page upon the first visit.
3. Go to the settings of your cache solutions and make sure, that the options to generate static HTML files as well as to optimize CSS files are disabled. This includes any object cache solution and any CSS optimizations you might have applied, including but not limited to CSS minify, CSS concatenation (combine), critical CSS generation, mobile CSS generation, and removal of unused CSS.
4. Clear the browser cache and history. How to do it depends on each browser. Chrome has the option to do that by opening the Developer Tools (F12) or right-clicking anywhere on the page and selecting the option to **`Inspect the element`**. A new window will appear. Go to the **`Application`** tab (menu) at the top of the window, and under the **Application** section on the left-hand side of the window, select the **`Storage`** sub-item. Check all options except the one that says to "simulate custom storage quota", and click on **`Clear site data`**.
5. At this point you will need to log into your WordPress dashboard again, but it should also show both the Tabs and Menu widgets correctly on the front-end of your site.  
6. You can now safely reactivate all cache levels again.

#### 3. What if the problem still persists?

In this case, you can try the following procedures: 

1. Keep all cache levels deactivated.
2. Go to your WordPress **`Dashboard`** > **`Elementor`** > **`Settings`** > **`Advanced`** page, and change the **`CSS Print Method`** to **`Internal Embedding`**.
3. Next, go to your WordPress **`Dashboard`** > **`Elementor`** > **`Settings`** > **`Features`** and **deactivate** the **`Improved CSS Loading`** feature.
4. Finally go to your WordPress **`Dashboard`** > **`Elementor`** > **`Tools`** > **`General`** and click on **`Regenerate CSS & Data`** again, and visit the front of your site where the problem occurs.

What this method does is to change the HTML structure of your pages to add all the styles of all the elements on that page. This will force the browser to re-download the entire page and assets again because the styles will be added inline on the page.

**If after doing this the styles of the mega Menu or nested Tabs widget appear correctly, you can finally revert the **`CSS Print Method`** option, and reactivate your cache levels (remembering to purge everything again). Otherwise please reach out to Elementor Support for further assistance.**

It's important to note that all these steps are necessary to handle the cache levels applied to your site. They are not a requirement for using Elementor at all. In fact, if you don't apply any level of cache, these issues will not occur as you can see in the video below.


https://github.com/elementor/elementor/assets/113993460/aaa6db37-5d97-4b5a-bb74-c1f237772b46



Due to how cache solutions work, unfortunately, sometimes you have to go to extensive lengths to be able to troubleshoot them.

I hope this clarifies any doubts that this is not a bug caused by Elementor, but a problem caused by cache.

### 👍 For now, that's all we can help with. 

### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for support.

❔ If you have questions, or need guidance, help, or general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) The main Facebook group where all kinds of users come together to help each other.
- [Elementor Academy](https://elementor.com/academy) Learn everything you need to know about using Elementor.
- [Elementor Developers Documentation](https://developers.elementor.com/) Learn everything about our Developer-API.
- [Free Support Forum](https://wordpress.org/support/plugin/elementor) Get help on WordPress.org.

💎 If you have an active [Elementor Pro](https://elementor.com/pro) license you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Kind regards

**Closed by nicholaszein** 2023-09-13 23:42 UTC
Labels: product/pro, component/code, type/styles, compatibility/assets, component/nested/menu, mod*, compatibility/cache
