### ISSUE TITLE
🔗 🐞 Bug Report: Post navigation: icons not visible after activating icon inline in Elementor - settings - functions (Duplicate of #18343)

### ISSUE THREAD

**Issue by LydiaDA** [elementor/elementor#22556] opened 2023-05-26 14:08 UTC
### Prerequisites

- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Elementor - settings - icon inline -active

The icons that can be used in Post Navigation widget can be seen in the back end, but not in the front end. 

### Steps to reproduce

1. Activate icon inline in settings - functions
2. Select post navigation widget in a page, add an icon. For example, arrows type - chevron circle. Click on save, update, clear cache.
3. Check the front end: icon not visible.
4. Deactivate icon inline in settings - functions. Clear cache. Icon should now be visible in the front end. 

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently following the steps above.

### System Info

<details>
<summary>System Info</summary>

````txt


Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MariaDB Server v10.3.35
	PHP Version: 8.1.19
	PHP Memory Limit: 128M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 64M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.2.2
	Site URL: https://amorpha.nl
	Home URL: https://amorpha.nl
	WP Multisite: No
	Max Upload Size: 64 MB
	Memory limit: 40M
	Max Memory limit: 512M
	Permalink Structure: /%postname%/
	Language: nl
	Timezone: 1
	Admin Email: [REDACTED]
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.7.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: nl_NL
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/113.0

== Active Plugins ==
	Elementor
		Version: 3.13.3
		Author: Elementor.com

	Elementor Pro
		Version: 3.13.2
		Author: Elementor.com

	FlyingPress
		Version: 4.5.0
		Author: 

	MailerLite - Signup forms (official)
		Version: 1.6.7
		Author: MailerLite

	Rank Math SEO
		Version: 1.0.115
		Author: Rank Math

	WPvivid Backup Plugin
		Version: 0.9.86
		Author: WPvivid Team


== Must-Use Plugins ==
	Elementor Safe Mode
		Version: 1.0.0
		Author: Elementor.com


== Eigenschappen ==
	Custom Fonts: 0
	Custom Icons: 0

== Integrations ==
	


== Elementor experimenten ==
	Geoptimaliseerde DOM-uitvoer: Actief
	Verbeterd laden van assets: Actief
	Verbeterd laden van CSS: Actief
	Pictogrammen inline lettertype: Actief
	Toegang verbeteringen: Inactief
	Extra aangepaste onderbrekingspunten: Inactief
	admin_menu_rearrangement: Standaard inactief
	Flexbox container: Actief
	Upgrade Swiper bibliotheek: Actief
	Raster container: Standaard inactief
	Default to New Theme Builder: Standaard actief
	Hello Theme header &amp; footer: Standaard actief
	Editor top balk: Standaard inactief
	Landingspagina&#039;s: Standaard actief
	Geneste elementen: Actief
	Lazy-load achtergrondafbeeldingen: Inactief
	Page Transitions: Actief
	Notes: Standaard actief
	Loop: Actief
	Form Submissions: Standaard actief
	Scroll Snap: Standaard actief
	Menu: Standaard inactief


== Log ==
	


== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatibel

== Elementor Pro - Compatibility Tag ==

````

</details>

**Comment by nicholaszein** [comment] 2023-05-27 17:54
Hello @LydiaDA!

Thank you for your submission! 🙏 

### 🔗 🐞 This issue is a Duplicate of #18343

Which is on the same subject. 

For this reason, I'm closing this thread and 🔃 **Merging** it with the original, so we can have all the discussions in one location, and deal with it more efficiently.

Feel free to continue the conversation there. 😉 

### 🔍 Please, in the future, remember to check if there isn't any thread similar to yours already opened. 

Best regards,

Nick

**Closed by nicholaszein** 2023-05-27 17:54 UTC
Labels: bug, product/pro, component/icons, component/post-navigation
