### ISSUE TITLE
⛔ 🐞 Bug report: Manual query of POSTS widget doesn't work

### ISSUE THREAD

**Issue by skito** [elementor/elementor#18689] opened 2022-05-19 14:15 UTC
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest stable version of Elementor.

### Description

Manual querying on `POSTS` widget doesn't work on Elementor PRO `3.7.1`.

The workaround for now is to stick with `3.6.5`.

### Steps to reproduce

**To reproduce**
1. Go to any page or template
2. Add `POSTS` widget.
3. Go to `Content`  -> `Query`
4. Select `Manual Selection` as source.
5. Inside `Search & Select` textarea select 3 names of posts. In my case these are custom post types of type `product`.
6. Select order by `Date` and order `DESC`.
7. Update and preview

**Expected result**
You should see only the posts you specified inside the query. Instead you will see all posts.

![Screenshot_304](https://user-images.githubusercontent.com/26840279/169320421-d67b1890-6498-4822-8eef-5e50403ac914.png) ![Screenshot_305](https://user-images.githubusercontent.com/26840279/169320430-e22bc0b1-c303-4b03-8f35-528ba736d420.png)

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

N/A

**Comment by dineshlalvani** [comment] 2022-05-20 15:16
I can also confirm I am having the same exact issue. It seems to be specific to manual posts selection.

**Comment by Johnvrkmp** [comment] 2022-06-14 06:54
This bug happens as well with `Query` source `Related` Term `Categories`

![Screenshot 2022-06-14 at 08 48 27](https://user-images.githubusercontent.com/107460640/173512423-4c6e0765-6913-4b29-acb6-a0310e1c2fef.png)

**Comment by SEwebm** [comment] 2022-06-28 13:30
Same problem with related posts, the related feature works, but the fallback is broken.

Need fix asap

**Comment by LoganStrike** [comment] 2022-07-14 02:37
@rami-elementor I have reported this same issue to Elementor support and provided WP access to a staging site where the issue can be recreated.

**Comment by LoganStrike** [comment] 2022-07-18 03:58
I received a response from Elementor support and the confirmed a bug related to "sticky" posts. When using Manual Selection to choose specific posts, the front end query does not ignore sticky posts, so those are displayed before the manually selected posts. The Manual Selection UI does not include the ability to "Ignore Sticky Posts", so a workaround is to remove the "sticky" status from all posts. Then the "Manual Selection" post will display correctly. Elementor support was unable to tell me when the bug might be fixed.

**Comment by vgstef** [comment] 2022-10-15 05:12
I also have this problem. But that's bad, because I'm manually selecting Pages, not articles. And the featured posts appear. But the website design uses Featured posts. So where's the fix for this issue? 

Moreover, the custom query doesn't work! So I can't create a custom filter. Elementor just don't trigger the custom query.

**Comment by vgstef** [comment] 2022-11-24 07:16
Any news about this issue? Its pretty bad. I'm manually querying pages, and sticky posts show up there! That's really problematic.

**Comment by skito** [comment] 2022-12-22 12:27
I found a strange solution which works for my specific case. Posting it here so anyone else can check if it will work for them.

In my case I needed to query specific post of type ``product``. However the filter didn't worked and I was shown other posts of regular type ``post``. So I did the following:

1. Move all posts of type ``post`` to the Trash.
2. Restored back the trashed posts. 
3. After restoration posts are with ``Draft`` status. Changed all statuses to ``Published``.

Now the bug disappear and the query is working as expected. I guess the problem is due to some kind of caching at WP core level.

**Comment by wpsupportconsulting** [comment] 2023-01-06 21:26
I've just discovered this problem after a client highlighted the issue on their site.

I rolled both Elementor & Elementor Pro back to v3.6.5 and the issue was solved.

So I assume that this is still an outstanding bug.

I've now locked both plugins at version 3.6.5 to stop the newer versions from being installed or updated until this bug is resolved.

**Comment by wpsupportconsulting** [comment] 2023-01-12 07:47
I just updated both free and pro version to the latest release today (3.10.0) and I continue to have this problem of manual selection in the Posts Widget Query not working properly.

This is still outstanding and no fix since first reported in May 2022 it would seem.

**Comment by Zach-Toth** [comment] 2023-01-16 19:12
Same issue here. Issue is not present in version 3.6.7 and earlier. Updated to version 3.10.0 and issue persists.... 

C'mon Elementor, this is a pretty major bug! My client wants sticky posts on her blog archive page, I can't tell her I have to turn them off just to fix another issue, that reflects poorly on me. Can you guys please focus on some of these lingering bugs rather than constantly trying to release new features? K thanks bye!

**Comment by bluantinoo** [comment] 2023-02-06 09:08
Error still persist in Elementor Pro v. 3.10.3 

both for manual post selection an related posts.
If you have sticky posts they will come up, no matter what post type you manually set.

very very very annoying issue.

**Comment by perezcarreno** [comment] 2023-02-13 21:22
I can confirm error persists for Manual selection and sticky posts in Elementor Pro 3.10.3 as well.

**Comment by lxiaoboo** [comment] 2023-05-17 16:01
Bad bug, I ran into it today, currently Elementor Pro version 3.13.1 is still not fixed.

Elementor Team What are you guys doing? Can such a serious bug be paid attention to?

**Comment by sixgunnar** [comment] 2023-08-11 12:22
This problem still occurs in Elementor 3.15 (Elementor Pro enabled as well).

Fixed it by setting CSS display: none on the sticky posts. This only worked because the sticky posts are another type than the ones that needed to be manually selected. The article tag had a different class for the sticky posts on our site.

Still a bit glitchy (short flashing because the css rule is applied on the fly) but hope it's not noticed too much by visitors.
Hope the ignore sticky posts functionality is added soon!

**Comment by zanz90** [comment] 2023-10-20 20:44
This problem still occurs in Elementor 3.16 (Elementor Pro enabled as well). 

Has anyone found a solutions?

**Comment by RJJuk** [comment] 2023-10-26 16:04
The problem still persists.
Elementor 3.17.1
Elementor PRO 3.17.0

Additionally, the same is true in the Woocommerce Products module.

**Comment by eknown** [comment] 2023-11-08 03:45
Confirming again that this issue is still active. Sticky posts are showing when using manual selection.

**Comment by samkenny** [comment] 2023-11-18 13:55
the problem still persists

**Comment by gervy28** [comment] 2024-05-26 02:03
The problem continues in Elementor Pro 3.21.3. This workaround worked for me:

Add `exp_remove_sticky_posts` to the Query ID in Elementor:

```
 function exp_remove_sticky_posts( $query ) {
    $query->set( 'ignore_sticky_posts', 1 );
    $query->set( 'post__not_in', get_option( 'sticky_posts' ) );
}

add_action( 'elementor/query/exp_remove_sticky_posts', 'exp_remove_sticky_posts' );```

**Comment by nicholaszein** [comment] 2024-07-25 14:44
Hello, everyone!

By default, Elementor doesn't have the option to remove Sticky/Featured posts from the query, because it doesn't modify the default WordPress query, allowing users to apply their changes using Query Filters if they need more control.

Before the query is rendered WordPress will prepend Sticky Posts at the beginning of the query by default. This may cause you to see Sticky Posts when you didn't want to see them. Because our goal is not to modify the query, and allow users to have the option to filter it the way they want, we cannot remove Sticky Posts from the query generated by WordPress.

We understand this might not be the preferable result, however, in general we don't see great demand to add an option to exclude Sticky Posts from the query inside any widget that has the query settings control.

But we do see the value of adding this feature!

For this reason I have a request for all those that are interested in having this option under the "Exclude" tab of the Query Settings:

If you think this should be an Elementor feature, please submit a new [🚀 Feature Request](https://github.com/orgs/elementor/discussions/new?category=feature-request), and we will consider it in the future if there is enough demand (votes) from other users.

### Workaround

For now, all I can suggest is that you use the following Code Snippet:

```php
/**
 * Modifies the query by excluding Sticky/Featured posts from appearing in the frontend.
 * on widgets that make use of this filter.
 * 
 * Use the 'exclude_sticky_posts' Query ID on the widgets you want to apply this filter.
 * 
 * @param \WP_Query $query The WordPress query instance.
 */
function custom_exclude_sticky_posts_query_callback( $query ) {
	$query->set( 'ignore_sticky_posts', true );
}
add_action( 'elementor/query/exclude_sticky_posts', 'custom_exclude_sticky_posts_query_callback' );
```

Add this PHP snippet to your Child Theme's `functions.php` file, or by using a Code Snippet plugin.

_**⚠️ Before modifying your theme files, please make sure you backup your site and theme files.**_

Thank you for sharing your feedback!

Kind regards

**Closed by nicholaszein** 2024-07-25 14:44 UTC
Labels: request/enhancement, product/pro, widget/posts*, component/query, mod*, control/group/query-group
