### ISSUE TITLE
⛔ 🔗 🐞 Bug Report: Custom CSS control does not support modern CSS properties (Related to #20607, #21752)

### ISSUE THREAD

**Issue by kulterryan** [elementor/elementor#22834] opened 2023-06-20 08:55 UTC
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Elementor shows a warning when adding some of the modern CSS properties:

![image](https://github.com/elementor/elementor/assets/36154235/6237259c-bb69-4507-b8a7-70894b04ec0d)
a 

### Steps to reproduce

In custom CSS, you can try adding the **text-underline-offset** property.

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

<details>
<summary>System Info</summary>

````txt


					
== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.57 (Debian)
	MySQL version: mariadb.org binary distribution v10.5.11
	PHP Version: 8.0.29
	PHP Memory Limit: 2047M
	PHP Max Input Vars: 10000
	PHP Max Post Size: 120M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.2.2
	Site URL: https://wordpress-694823-2427388.cloudwaysapps.com
	Home URL: https://wordpress-694823-2427388.cloudwaysapps.com
	WP Multisite: No
	Max Upload Size: 120 MB
	Memory limit: 40M
	Max Memory limit: 2047M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 5.5
	Admin Email: [REDACTED]
	Debug Mode: Inactive

== Theme ==
	Name: Astra Child
	Version: 1.0.0
	Author: Brainstorm Force
	Child Theme: Yes
	Parent Theme Name: Astra
	Parent Theme Version: 4.1.5
	Parent Theme Author: Brainstorm Force

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36 Edg/114.0.1823.51

== Active Plugins ==
	Advanced Order Export For WooCommerce
		Version: 3.4.0
		Author: AlgolPlus

	Antispam Bee
		Version: 2.11.3
		Author: pluginkollektiv

	Astra Pro
		Version: 4.1.5
		Author: Brainstorm Force

	BusinessOnBot
		Version: 19.13
		Author: BusinessOnBot

	Click to Chat
		Version: 3.29
		Author: HoliThemes

	CTX Feed
		Version: 5.4.19
		Author: WebAppick

	Elastic Email Sender
		Version: 1.2.6
		Author: Elastic Email Inc.

	Elementor
		Version: 3.13.4
		Author: Elementor.com

	Elementor Pro
		Version: 3.13.2
		Author: Elementor.com

	Extra Product Sorting Options for WooCommerce
		Version: 2.9.1
		Author: SkyVerge

	Facebook for WooCommerce
		Version: 3.0.24
		Author: Facebook

	Forminator
		Version: 1.24.1
		Author: WPMU DEV

	MailerLite - WooCommerce integration
		Version: 1.8.5
		Author: MailerLite

	MalCare WordPress Security Plugin - Malware Scanner, Cleaner, Security Firewall
		Version: 5.09
		Author: MalCare Security

	MC4WP: Mailchimp for WordPress
		Version: 4.9.5
		Author: ibericode

	Meta Box
		Version: 5.7.2
		Author: MetaBox.io

	Order Export & Order Import for WooCommerce
		Version: 2.3.5
		Author: WebToffee

	Pixel Caffeine
		Version: 2.3.3
		Author: AdEspresso

	Rank Math SEO
		Version: 1.0.116
		Author: Rank Math

	Razorpay for WooCommerce
		Version: 4.5.2
		Author: Team Razorpay

	Shiprocket
		Version: 2.0.1
		Author: Shiprocket

	Social Feed Gallery
		Version: 4.0.9
		Author: QuadLayers

	Table Rate Shipping for WooCommerce
		Version: 2.28
		Author: JEM Plugins

	Temporary Login Without Password
		Version: 1.8.2
		Author: StoreApps

	TI WooCommerce Wishlist
		Version: 2.6.0
		Author: TemplateInvaders

	WooCommerce
		Version: 7.7.2
		Author: Automattic

	WooCommerce AJAX Products Filter
		Version: 3.1.4.1
		Author: BeRocket

	WooCommerce Conditional Shipping and Payments
		Version: 1.14.5
		Author: WooCommerce

	WooCommerce Pixel Manager
		Version: 1.11.2
		Author: woopt

	WooCommerce Product Add-Ons Ultimate
		Version: 3.13.1
		Author: Plugin Republic

	WooCommerce Product Add-Ons Ultimate Text Preview
		Version: 1.1.8
		Author: Plugin Republic

	WP Rocket
		Version: 3.13.4
		Author: WP Media


== Features ==
	Custom Fonts: 0
	Custom Icons: 0

== Integrations ==
	
	woocommerce: Active


== Elementor Experiments ==
	Optimized DOM Output: Active
	Improved Asset Loading: Active
	Improved CSS Loading: Active
	Inline Font Icons: Active
	Accessibility Improvements: Active
	Additional Custom Breakpoints: Inactive
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active
	Upgrade Swiper Library: Inactive by default
	Grid Container: Active
	Default to New Theme Builder: Active by default
	Editor Top Bar: Inactive by default
	Landing Pages: Inactive
	Nested Elements: Active
	Lazy Load Background Images: Active
	Page Transitions: Active by default
	Notes: Active by default
	Loop: Active by default
	Form Submissions: Active by default
	Scroll Snap: Active by default
	Menu: Active


== Log ==
	
Log: showing 20 of 342023-04-26 21:37:55 [info] elementor-pro::elementor_pro_updater Started 
2023-04-26 21:37:55 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-04-26 21:37:55 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-04-26 21:37:55 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.11.3',
  'to' => '3.12.3',
)]
2023-04-26 21:37:55 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.11.3',
  'to' => '3.12.3',
)]
2023-05-11 14:57:00 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.12.2',
  'to' => '3.13.1',
)]
2023-05-11 14:57:01 [info] elementor::elementor_updater Started 
2023-05-11 14:57:01 [info] Elementor/Upgrades - _on_each_version Start  
2023-05-11 14:57:01 [info] Elementor/Upgrades - _on_each_version Finished 
2023-05-11 14:57:01 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.12.2',
  'to' => '3.13.1',
)]
2023-05-11 14:57:02 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.12.2',
  'to' => '3.13.1',
)]
2023-05-30 16:20:08 [info] elementor::elementor_updater Started 
2023-05-30 16:20:08 [info] Elementor/Upgrades - _on_each_version Start  
2023-05-30 16:20:08 [info] Elementor/Upgrades - _on_each_version Finished 
2023-05-30 16:20:08 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.13.1',
  'to' => '3.13.4',
)]
2023-06-01 00:54:58 [info] elementor-pro::elementor_pro_updater Started 
2023-06-01 00:54:58 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-06-01 00:54:58 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-06-01 00:54:58 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.12.3',
  'to' => '3.13.2',
)]
2023-06-01 00:54:58 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.12.3',
  'to' => '3.13.2',
)]

PHP: showing 5 of 5PHP: 2023-04-26 21:38:15 [warning X 12][/home/694823.cloudwaysapps.com/smhnevcpwu/public_html/wp-content/plugins/elementor/app/modules/import-export/module.php::695] Attempt to read property "label" on null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-04-26 21:38:18 [warning X 3][/home/694823.cloudwaysapps.com/smhnevcpwu/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php::175] Undefined array key "data" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-06-01 01:01:21 [warning X 9][/home/694823.cloudwaysapps.com/smhnevcpwu/public_html/wp-content/plugins/elementor/modules/history/revisions-manager.php::363] Trying to access array offset on value of type null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-06-01 01:04:36 [warning X 4][/home/694823.cloudwaysapps.com/smhnevcpwu/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::171] Undefined array key "editor_post_id" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-06-08 13:52:04 [warning X 2][/home/694823.cloudwaysapps.com/smhnevcpwu/public_html/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php::150] Undefined array key "condition_type" [array (
  'trace' => '
#0: /home/694823.cloudwaysapps.com/smhnevcpwu/public_html/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(150): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_template_json_item()
#2: /home/694823.cloudwaysapps.com/smhnevcpwu/public_html/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(120): class type array_map()
#3: /home/694823.cloudwaysapps.com/smhnevcpwu/public_html/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(59): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_templates_json()
#4: /home/694823.cloudwaysapps.com/smhnevcpwu/public_html/wp-content/plugins/elementor/data/base/endpoint.php(158): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> get_items()
',
)]

JS: showing 3 of 3JS: 2023-04-26 16:50:57 [error X 12][https://wordpress-694823-2427388.cloudwaysapps.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.12.2:3:785234] Cannot read properties of undefined (reading 'toLowerCase') 
JS: 2023-05-31 19:30:55 [error X 11][https://wordpress-694823-2427388.cloudwaysapps.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.13.4:3:795450] Cannot read properties of undefined (reading 'localized') 
JS: 2023-05-31 19:31:51 [error X 2][https://wordpress-694823-2427388.cloudwaysapps.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.13.4:3:1097282] Cannot read properties of null (reading 'getBoundingClientRect') 



== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatibility not specified

== Elementor Pro - Compatibility Tag ==
	

````

</details>

**Comment by nicholaszein** [comment] 2023-06-23 20:44
Hello @kulterryan,

Thank you for reaching out! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
For compatibility reasons, Elementor uses the built-in CodeMirror library from WordPress Core to handle CSS validation. It's the same dependency used in the Theme and Plugin editors. This version of CodeMirror is very outdated and there is no expectation that WordPress will update this library anytime soon. Elementor will not include its own version of the library to avoid conflicts with WordPress and other plugins.

### ✅ What you can do to solve your issue:
However, the validation does not affect the functionality of this component, and you should be able to use virtually any modern CSS property even if it shows a warning. They will still be parsed as long as they are valid CSS. In other words, for now, you can simply ignore the warnings.

### 👍 For now, that's all we can help with. 

#### 🔗 🐞 This issue is a Duplicate of #20607 

Which is on the same subject. 

### 🔍 Please, in the future, remember to check if there isn't any thread similar to yours already opened. 

Kind regards

**Closed by nicholaszein** 2023-06-23 20:44 UTC
Labels: dependencies, compatibility/assets, component/custom-css, mod*
