### ISSUE TITLE
SendinBlue

### ISSUE THREAD

**Issue by danna556** [elementor/elementor#9281] opened 2019-10-07 13:06 UTC
## Prerequisites

- [ ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by danna556** [comment] 2019-10-07 13:07
Hello, can u integrate elementor with [send in blue](www.sendinblue.com)

**Comment by bainternet** [comment] 2019-10-12 21:26
Duplicate of #6527 and https://github.com/elementor/elementor/issues/3315#issuecomment-361078878

**Closed by bainternet** 2019-10-12 21:26 UTC
