### ISSUE TITLE
Conditional Logic in Elementor Forms

### ISSUE THREAD

**Issue by pedrosromano** [elementor/elementor#10246] opened 2020-01-21 15:45 UTC
## Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
For most of my projects, i need to make complex forms that demand conditional logic (ex. show a field when i select a specific option on a dropdown of another field). It would be extremely usefull that i could do this with elementor forms.

**Describe the solution you'd like**
I would like that the elementor form widget had the possibility to define a conditional logic option for each of the form fields, for example only show / if / field_3 / is black

**Describe alternatives you've considered**
I usually end up having to use plugins like gravityforms to create more complex forms due to the lack of these options in elementor

**Comment by ZambraDesigner** [comment] 2020-02-27 01:32
I also look forward to this feature. I need to create dome forms the user first selects the country and then the city based on the selected country.
In this way I do not have to scroll an infinite list of cities to the user but only those present in the country chosen above.

**Comment by shilo-ey** [comment] 2020-03-02 17:34
Duplicate of #2638

**Closed by shilo-ey** 2020-03-02 17:34 UTC
