### ISSUE TITLE
Videos with the Lightbox mode ON stopped working.

### ISSUE THREAD

**Issue by Andy-Nobel** [elementor/elementor#17749] opened 2022-02-08 13:32 UTC
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Over 3 days now, elementor (youtube) videos with an image overlay, with the Lightbox mode ON stopped working.

### Steps to reproduce

if you follow this link and press play on any video you will find the problem: [https://www.whatastep.com/arts-and-design-occupations/]

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently using the steps above.

### System Info

`
### wp-core ###

version: 5.9
site_language: en_US
user_language: en_US
timezone: +00:00
permalink: /%postname%/
https_status: true
multisite: false
user_registration: 1
blog_public: 1
default_comment_status: closed
environment_type: production
user_count: 2
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: /home/whataste/public_html
wordpress_size: 149.38 MB (156639137 bytes)
uploads_path: /home/whataste/public_html/wp-content/uploads
uploads_size: 149.32 MB (156576227 bytes)
themes_path: /home/whataste/public_html/wp-content/themes
themes_size: 10.79 MB (11314241 bytes)
plugins_path: /home/whataste/public_html/wp-content/plugins
plugins_size: 140.87 MB (147717429 bytes)
database_size: 383.56 MB (402194432 bytes)
total_size: 833.93 MB (874441466 bytes)

### wp-active-theme ###

name: Kadence (kadence)
version: 1.1.14
author: Kadence WP
author_website: https://www.kadencewp.com/
parent_theme: none
theme_features: core-block-patterns, widgets-block-editor, menus, automatic-feed-links, title-tag, html5, custom-units, custom-line-height, customize-selective-refresh-widgets, responsive-embeds, post-thumbnails, editor-styles, align-wide, amp, custom-logo, editor-color-palette, editor-style, header-footer-elementor, widgets
theme_path: /home/whataste/public_html/wp-content/themes/kadence
auto_update: Disabled

### wp-themes-inactive (1) ###

Hello Elementor: version: 2.5.0, author: Elementor Team, Auto-updates disabled

### wp-plugins-active (10) ###

Elementor: version: 3.5.5, author: Elementor.com, Auto-updates disabled
Essential Addons for Elementor: version: 5.0.7, author: WPDeveloper, Auto-updates disabled
Fluent Forms: version: 4.3.0, author: Contact Form - WPManageNinja LLC, Auto-updates disabled
iThemes Security: version: 8.0.2, author: iThemes, Auto-updates disabled
Kadence Starter Templates: version: 1.2.12, author: Kadence WP, Auto-updates disabled
Paid Memberships Pro: version: 2.7.3, author: Stranger Studios, Auto-updates disabled
Rank Math SEO: version: 1.0.81.1, author: Rank Math, Auto-updates enabled
Really Simple SSL: version: 5.2.3, author: Really Simple Plugins, Auto-updates disabled
UpdraftPlus - Backup/Restore: version: 1.22.1, author: UpdraftPlus.Com, DavidAnderson, Auto-updates disabled
WP-Optimize - Clean, Compress, Cache: version: 3.2.2, author: David Anderson, Ruhani Rabin, Team Updraft, Auto-updates disabled

### wp-plugins-inactive (3) ###

Akismet Anti-Spam: version: 4.2.2, author: Automattic, Auto-updates disabled
CM Tooltip Glossary: version: 4.0.6, author: CreativeMindsSolutions, Auto-updates disabled
Hello Dolly: version: 1.7.2, author: Matt Mullenweg, Auto-updates disabled

### wp-media ###

image_editor: WP_Image_Editor_GD
imagick_module_version: Not available
imagemagick_version: Not available
imagick_version: Not available
file_uploads: File uploads is turned off
post_max_size: 128M
upload_max_filesize: 128M
max_effective_size: 128 MB
max_file_uploads: 20
gd_version: bundled (2.1.0 compatible)
gd_formats: GIF, JPEG, PNG, WebP, BMP, XPM
ghostscript_version: 9.25

### wp-server ###

server_architecture: Linux 3.10.0-962.3.2.lve1.5.61.el7.x86_64 x86_64
httpd_software: LiteSpeed
php_version: 7.3.33 64bit
php_sapi: litespeed
max_input_variables: 1000
time_limit: 30
memory_limit: 256M
max_input_time: -1
upload_max_filesize: 128M
php_post_max_size: 128M
curl_version: 7.71.0 OpenSSL/1.1.1d
suhosin: false
imagick_availability: false
pretty_permalinks: true
htaccess_extra_rules: true

### wp-database ###

extension: mysqli
server_version: 10.3.32-MariaDB-cll-lve
client_version: mysqlnd 5.0.12-dev - 20150407 - $Id: 7cc7cc96e675f6d72e5cf0f267f48e167c2abb23 $
max_allowed_packet: 268435456
max_connections: 500

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: /home/whataste/public_html/wp-content
WP_PLUGIN_DIR: /home/whataste/public_html/wp-content/plugins
WP_MEMORY_LIMIT: 40M
WP_MAX_MEMORY_LIMIT: 256M
WP_DEBUG: false
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: false
SCRIPT_DEBUG: false
WP_CACHE: false
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_ENVIRONMENT_TYPE: Undefined
DB_CHARSET: utf8
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable

### pmpro ###

pmpro-cron-jobs: pmpro_cron_expire_memberships (2022-02-09 08:52:53) | 
pmpro_cron_expiration_warnings (2022-02-09 08:52:54) | 
pmpro_cron_admin_activity_email (2022-02-09 10:30:00) | 
pmpro_cron_credit_card_expiring_warnings (2022-02-27 08:52:53)
pmpro-gateway: Default
pmpro-gateway-env: Sandbox/Testing
pmpro-orders: 1 order
pmpro-discount-codes: 0 discount codes
pmpro-membership-levels: {
    "1": {
        "id": "1",
        "name": "Whatastep Free Member",
        "description": "Get the Whatastep Free Membership to unlock additional features. Unlock the motivation section in the menu, and gain access to motivational videos and literature recommendations.",
        "confirmation": "Success! You got a Whatastep Free Membership. You can access additional features.",
        "initial_payment": 0,
        "billing_amount": 0,
        "cycle_number": "0",
        "cycle_period": "",
        "billing_limit": "0",
        "trial_amount": 0,
        "trial_limit": "0",
        "allow_signups": "1",
        "expiration_number": "0",
        "expiration_period": ""
    }
}
pmpro-custom-templates: No template overrides
pmpro-getfile-usage: PMPRO_GETFILE_ENABLED is not set
pmpro-htaccess-cache-usage: Off
pmpro-pages: 
	account: https://www.whatastep.com/membership-account/
	billing: https://www.whatastep.com/membership-account/membership-billing/
	cancel: https://www.whatastep.com/membership-account/membership-cancel/
	checkout: https://www.whatastep.com/membership-account/membership-checkout/
	confirmation: https://www.whatastep.com/membership-account/membership-confirmation/
	invoice: https://www.whatastep.com/membership-account/membership-invoice/
	levels: https://www.whatastep.com/membership-account/membership-levels/
	login: https://www.whatastep.com/login/
	member_profile_edit: https://www.whatastep.com/membership-account/your-profile/

`

**Comment by numeroish** [comment] 2022-02-08 15:57
Can confirm I've noticed that on our sites too.
Lightbox no longer working for videos.
No video is displayed.

**Comment by Nazrinn** [comment] 2022-02-09 01:48
Yeah that's Elementor 3.5.5 "video lightbox" hardening that's doing that. It doesn't allow you to have anything else other than YouTube or Vimeo videos now. That sucks (I have a client with 3D houses in lightboxes and in 3.5.5 it no longer works). =(

I opened a similar issue (17708) that might give you more details on why this doesn't work.

Best to do is rollback your Elementor version and wait and see.

**Comment by Andy-Nobel** [comment] 2022-02-11 04:27
Yes, just tested it. With privacy mode off it works. Thank you!

**Comment by marowi85** [comment] 2022-02-14 13:25
+1
Just updated to Elementor 3.5.5 / Pro 3.6.1 and see the same issue. Video lightbox not working when privacy mode is enabled.

**Comment by EZChris** [comment] 2022-02-14 13:29
I too have the same issue with privacy mode enabled youtube videos do not play any update on fixing this?

**Comment by shilo-ey** [comment] 2022-02-28 13:46
This issue has been resolved in Elementor v3.5.6

Feel free to update

Thanks!

**Closed by shilo-ey** 2022-02-28 13:46 UTC
Labels: bug, component/lightbox

**Comment by KingGrizzly** [comment] 2022-03-01 00:04
Well done @shilo-ey . Thank you!

**Comment by CamelDesign10** [comment] 2023-02-20 11:26
the bug is not resolved at all for me ! if i add a youtube video with a image overlay all is great.

But if i activate lightbox => at the first clic on the video that launch the lightbox and the video show error "This video is not available" and if i close lightbox and open again is fine that work, they are a bug at the first launch of lightbox who don't charge the video and need a second trigger for work

**Comment by CamelDesign10** [comment] 2023-02-20 13:36
i have make all test and the problem is only on browser who are fork of chromium (brave, edge, chrome) firefox is not impacted

**Comment by AmyKrizanWang** [comment] 2023-03-16 16:51
lightbox.php
Line#113
fixed the error ;-)

return [
			'type' => 'video',
			'videoType' => $video_type,
			//'url' => $video_url, //original code
			
			//fixed - fixer for video players	
			'url' => str_replace('#t=','?#t=',$video_url),

		];
