### ISSUE TITLE
Failed logins redirect to wp-login instead of to the same page

### ISSUE THREAD

**Issue by davidwolfpaw** [elementor/elementor#9144] opened 2019-09-20 11:14 UTC
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
When a user of the login popup leaves the credentials blank or enters an incorrect password it redirects to `wp-login.php`, as opposed to showing an error via the popup itself. This isn't ideal for users, as it doesn't look the same as the rest of the site and may be confusing.

I received the following from Elementor Pro support:

At the moment, the login widget was built to integrate with WordPress native login feature. If the credentials are incorrect or left blank (in this case) a redirect to the WordPress login screen will occur as this is regarded as a failed login attempt.

The Login Widget is still a very basic widget and is planned to be improved in the future. 

**Describe the solution you'd like**
I would like failed or incorrect logins to stay on the same page as the popup with an error notice, as opposed to redirecting to the login page.

**Comment by PawanjitAhluwalia** [comment] 2020-01-29 14:32
I would like to support this request. This seems a funadmental requirement of the login widget. It seems pointless having a widget that can't handle errors and then reverts the user to the default WordPress login.

**Comment by arielk** [comment] 2020-06-19 15:56
Duplicate of https://github.com/elementor/elementor/issues/8410

**Closed by arielk** 2020-06-19 15:56 UTC

**Comment by d12ilham** [comment] 2024-10-01 12:20
I have created this plugin for a specific requirement, you can get it and make changes if anyone wants it from [here](https://github.com/d12ilham/Custom-AJAX-Login-for-Elementor-Popup)
