### ISSUE TITLE
🔗 🐘 🐞 Bug Report: Deprecated warning while trying to edit with Elementor when using PHP 8.1 (Duplicate of #21655)

### ISSUE THREAD

**Issue by ciprianpentelescu** [elementor/elementor#21890] opened 2023-04-01 18:40 UTC
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Deprecated: strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in /.../wp-content/plugins/elementor-pro/modules/loop-builder/module.php on line 204

### Steps to reproduce

Enable WP_DEBUG in php 8.1+

### Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [x] I can reproduce this bug consistently following the steps above.

### System Info

Elementor 1.12 & PRO 1.12, PHP 8.1.17, WP 6.2

**Comment by jeffgoh** [comment] 2023-04-02 01:39
Deprecated means it will one day become a problem, but if you're anything like me - it's just annoying. It shows up in wp-cli even without WP_DEBUG on.  I tried php8.0 same problem.
```
diff -r1.1 ./module.php
204c204,208
< 		return strpos( $elementor_library, 'elementor-' . static::TEMPLATE_LIBRARY_TYPE_SLUG ) !== false;
---
> 		if ( $elementor_library ) {
> 			return strpos( $elementor_library, 'elementor-' . static::TEMPLATE_LIBRARY_TYPE_SLUG ) !== false;
> 		} else {
> 			return false;
> 		}
```

**Comment by Yadley** [comment] 2023-04-06 09:48
For anyone else experiencing this same problem or this:

'Warning: Cannot modify header information - headers already sent by (output started at elementor-pro/modules/loop-builder/module.php:204) in /wp-admin/includes/misc.php on line 1431'

I was able to resolve those errors by ensuring that the $elementor_library variable being passed to the strpos() function is not null. To do that successfully, I added a null check before calling the strpos() function. Here's the code:

```
private function is_editing_existing_loop_item() {
    //phpcs:ignore WordPress.Security.NonceVerification.Recommended -- Nonce verification is not required.
    $elementor_library = Utils::_unstable_get_super_global_value( $_GET, 'elementor_library' );
    if ( $elementor_library === null ) {
        return false;
    }
    return strpos( $elementor_library, 'elementor-' . static::TEMPLATE_LIBRARY_TYPE_SLUG ) !== false;
}

```

Hope a more permanent fix will come soon from the E team, but this works perfectly for now.

**Comment by marcinfigiel** [comment] 2023-04-12 20:52
It seems to be a duplicate of https://github.com/elementor/elementor/issues/21655

**Closed** 2024-02-14 16:01 UTC
Labels: bug, product/pro, component/library, status/needs-feedback, compatibility/php-8, mod*, mod/e*
