### ISSUE TITLE
Elementor Search Results template overriding all 'search result templates' from plugins. 

### ISSUE THREAD

**Issue by bluecoredev** [elementor/elementor#8223] opened 2019-05-29 07:40 UTC
Steps to reproduce: 
1. Download an unrelated plugin, such as WP Jobs or GeoDirectory. They have their search templates, because when you're searching on WP Jobs you're looking for jobs/candidates, and GeoDirectory businesses. 
2. Create an Archive Template on elementor and set Display Conditions to "Search Results". 

Now every search form on the site is overwritten by this new template, the ability to customize search results is completely lost, and all search results (website, jobs, business directory) will look exactly the same.

**Comment by bainternet** [comment] 2019-05-29 09:44
Duplicate of #6226

**Comment by bainternet** [comment] 2019-05-29 09:44
Thanks for the feedback,
Please follow guidelines for opening a new [feature request](https://github.com/pojome/elementor/issues/new?template=Feature_request.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Description and examples.

**Closed by bainternet** 2019-05-29 09:44 UTC
