### ISSUE TITLE
✔️ 🐞 Bug Report: Basic widgets are not displayed when editing the loop item.

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#20347] opened 2022-11-09 16:44 UTC
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Hi @nicholaszein , In the continuation of [this issue](https://github.com/elementor/elementor/issues/20198).

As mentioned in the title, Basic widgets are not displayed when editing the loop item. But if you search for them, they will be accessible.

### Steps to reproduce

https://user-images.githubusercontent.com/77163248/200887327-012bb8cb-3f37-42db-8d77-73d0f563ffdc.mp4

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

[system-info-localhost-09-11-2022.txt](https://github.com/elementor/elementor/files/9973135/system-info-localhost-09-11-2022.txt)

**Comment by nicholaszein** [comment] 2022-11-14 07:08
Hello @79ho3ein!

I see you submitted this issue again, but I still can't reproduce it. See the video below:

https://user-images.githubusercontent.com/113993460/201595791-066af203-bb63-4243-bbeb-a9cbe9846d5e.mp4

Tested in these scenarios:

- Frontpage
- Archive Template
- Single Template
- Loop Item Template

They all show the Basic section correctly.

The only difference between my website to yours is the version of PHP, which on yours is 7.3+. But I did test with PHP 7.3 and could not reproduce the issue.

Since you're on a localhost, most likely your issue is related to the local server cache.

Can you check on a live website if possible? Try using https://instawp.com/.

I'll wait for your feedback before closing this issue.

**Comment by nicholaszein** [comment] 2022-11-29 21:00
Hey @79ho3ein,

please let me know if the issue still persists. I couldn't reproduce this one yet.

Kind regards

**Comment by 79ho3ein** [comment] 2022-11-29 21:48
Hi @nicholaszein , I apologize for the delay. I forgot to answer you...
I am still experiencing this bug. But let me check this again with the official release of version 3.9 and I'll be sure to report back to you.

**Comment by nicholaszein** [comment] 2022-11-30 00:26
Awesome @79ho3ein!

Thanks! 🙏

**Comment by 79ho3ein** [comment] 2022-12-07 11:11
Hi @nicholaszein 

I'm still experiencing this bug in version 3.9. It's really strange. I even asked several people to check this out and they had the same problem.

![4](https://user-images.githubusercontent.com/77163248/206163710-7c391447-30a7-402b-ab8d-de2932f14983.png)

But everything works fine for you in the above video you posted. I will continue to look for the cause of this bug.

**Comment by nicholaszein** [comment] 2022-12-14 20:13
Hey @79ho3ein, does this issue still persist with beta 3.10?

I tried to reproduce it again today, in various different scenarios, and I still can't reproduce it. I think this could be related to your specific configuration. Here's a full 5 min video:


https://user-images.githubusercontent.com/113993460/207704454-2d885df3-e101-4a61-a45b-6ab1d6d2e060.mp4



Please try the following if possible:

1. Update your PHP to version 7.4 or 8.0. Test to see if the issue still happens.
2. Increase the PHP's max_input_vars to 10000 (ten thousand) in your php.ini file.

Please check these and let me know.

**Comment by 79ho3ein** [comment] 2022-12-17 09:36
Hi @nicholaszein , I did but the problem still exists.

**Comment by nicholaszein** [comment] 2022-12-28 05:58
Ok @79ho3ein,

last try. Can you please share a backup of your website with us? Try using the All-In-One WP Migration plugin, zip the file and paste it here for us to download it. I will try to use it and see if I can reproduce it this way.

Thanks 🙏

**Comment by 79ho3ein** [comment] 2022-12-29 08:29
Hi @nicholaszein

I don't know why, but in 3.10 beta 3 this problem was fixed.

![basic widget](https://user-images.githubusercontent.com/77163248/209924731-1c2418a9-969d-470a-9be9-35cd5bb38069.png)

thanks again 🥂

**Comment by nicholaszein** [comment] 2022-12-31 04:18
Hey @79ho3ein!

That's great news! 🙌 

Thank you for letting me know. 🙏 

I'm closing this issue as solved! Thanks

**Closed by nicholaszein** 2022-12-31 04:18 UTC
Labels: bug, type/ui/ux, component/editor, component/loop-builder, 🚀 shipped
