### ISSUE TITLE
🔗 🚀 Feature Request: Repeater control within another repeater control (Nested) (Duplicate of #2955)

### ISSUE THREAD

**Issue by tom-cwa** [elementor/elementor#19513] opened 2022-08-17 10:09 UTC
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

When creating my own widget, whenever I'm trying to use a repeater control within another repeater control, I get the following fatal error: 
```
Fatal error: Uncaught TypeError: Argument 3 passed to Elementor\Core\Files\CSS\Post::add_controls_stack_style_rules() must be of the type array, null given, called in /wp-content/plugins/elementor/core/files/css/base.php on line 793 and defined in /wp-content/plugins/elementor/core/files/css/post.php on line 221
```

### Describe the solution you'd like

I would like to be able to use a repeater control within another one without getting this error.

### Describe alternatives you've considered

The solution I came up with which resolve this issue is to replace one line of code in the following method:

In *wp-content/plugins/elementor/core/files/css/base.php* at line 784

Replace
```php
protected function add_repeater_control_style_rules( Controls_Stack $controls_stack, array $repeater_control, array $repeater_values, array $placeholders, array $replacements ) {
		$placeholders = array_merge( $placeholders, [ '{{CURRENT_ITEM}}' ] );

		foreach ( $repeater_control['style_fields'] as $index => $item ) {
			$this->add_controls_stack_style_rules(
				$controls_stack,
				$item,
				$repeater_values[ $index ], // change this line...
				$placeholders,
				array_merge( $replacements, [ '.elementor-repeater-item-' . $repeater_values[ $index ]['_id'] ] ),
				$repeater_control['fields']
			);
		}
	}
```
By
```php
protected function add_repeater_control_style_rules( Controls_Stack $controls_stack, array $repeater_control, array $repeater_values, array $placeholders, array $replacements ) {
		$placeholders = array_merge( $placeholders, [ '{{CURRENT_ITEM}}' ] );

		foreach ( $repeater_control['style_fields'] as $index => $item ) {
			$this->add_controls_stack_style_rules(
				$controls_stack,
				$item,
				$repeater_values[ $index ] ?: [], // ...to this line
				$placeholders,
				array_merge( $replacements, [ '.elementor-repeater-item-' . $repeater_values[ $index ]['_id'] ] ),
				$repeater_control['fields']
			);
		}
	}
```

### Additional context

See below how I proceed to register repeater controls in my widget:

```php
protected function register_controls()
    {
        $this->start_controls_section(
            'content_section',
            [
                'label' => 'Contenu',
                'tab'   => Controls_Manager::TAB_CONTENT
            ]
        );

        $tabs = new Repeater();

        $tabs->add_control(
            'title',
            [
                'label'         => 'Titre',
                'type'          => Controls_Manager::TEXT,
                'label_block'   => true,
                'default'       => "# Titre onglet"
            ]
        );

        $items = new Repeater();

        $items->add_control(
            'profil',
            [
                'label'     => 'Image',
                'type'      => Controls_Manager::MEDIA,
                'default'   => [
                    'url'       => Utils::get_placeholder_image_src(),
                ],
            ]
        );

        $items->start_controls_tabs('content_tabs');

        $items->start_controls_tab(
            'front_tab',
            [
                'label' => 'Prévisualisation'
            ]
        );

        $items->add_control(
            'name',
            [
                'label'         => 'Nom',
                'type'          => Controls_Manager::TEXT,
                'label_block'   => true
            ]
        );

        $items->add_control(
            'job',
            [
                'label' => 'Poste(s)',
                'type'  => Controls_Manager::WYSIWYG,
            ]
        );

        $items->end_controls_tab();

        $items->start_controls_tab(
            'back_tab',
            [
                'label' => 'Contenu'
            ]
        );

        $items->add_control(
            'logo',
            [
                'label'     => 'Logo',
                'type'      => Controls_Manager::MEDIA
            ]
        );

        $items->add_control(
            'content',
            [
                'label' => 'Contenu',
                'type'  => Controls_Manager::WYSIWYG,
            ]
        );

        $items->add_control(
            'phone',
            [
                'label' => 'Téléphone',
                'type'  => Controls_Manager::TEXT,
                'label_block'   => true
            ]
        );

        $items->end_controls_tab();

        $items->end_controls_tabs();

        $tabs->add_control(
            'persons',
            [
                'label'         => 'Personnes',
                'type'          => Controls_Manager::REPEATER,
                'fields'        => $items->get_controls(),
                'title_field'   => '{{{ name }}}',
                'default'       => [
                    [
                        'name'      => 'John Smith',
                        'profil'    => [
                            'url'       => Utils::get_placeholder_image_src(),
                        ]
                    ]
                ]
            ]
        );

        $this->add_control(
            'tabs',
            [
                'label'         => 'Sliders',
                'type'          => Controls_Manager::REPEATER,
                'fields'        => $tabs->get_controls(),
                'title_field'   => '{{{ title }}}',
                'default'       => [
                    [ 'title' => '# Titre 1' ],
                    [ 'title' => '# Titre 2' ],
                ],
                'prevent_empty' => false
            ]
        );

        $this->end_controls_section();
```

**Comment by nicholaszein** [comment] 2022-12-06 18:59
Hello @tom-cwa!

Thank you for your submission! 🙏 

### 🔗 This issue is a Duplicate of #2599.

Which is on the same subject. 

For this reason, I'm closing this issue and 🔃 **Merging** it with the original, so we can have all the discussions in one location, and deal with it more efficiently.

Feel free to continue the conversation there. 😉 

### ✔️ Please, in the future, remember to check if there isn't an issue similar to yours already opened. 

Best regards,

Nick

**Closed by nicholaszein** 2022-12-06 18:59 UTC
Labels: request/enhancement, type/developer-api
