### ISSUE TITLE
css Grid layout in elementor

### ISSUE THREAD

**Issue by Joliamendi** [elementor/elementor#19791] opened 2022-09-13 11:00 UTC
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

Hi elementor team!

css Grid is one of the most important features that competing page builders are now adding to their plugins. I wanted to ask you dear developers, will we see css grid in elementor? Are there any plans for that?

Thank you in advance

### Describe the solution you'd like

![CSS-GRID-3](https://user-images.githubusercontent.com/103376243/189879283-fd4cd0ab-3704-42c2-b26e-32428ba5a25d.png)

**Comment by m1ga** [comment] 2022-09-13 11:32
duplicate of https://github.com/elementor/elementor/issues/18839

**Comment by rami-elementor** [comment] 2022-09-15 07:09
Duplicate of #18839

**Closed by rami-elementor** 2022-09-15 07:09 UTC
Labels: status/awaiting_triage

**Comment by nicholaszein** [comment] 2023-05-08 14:10
Hello, there everyone!

We have great news! 🙌 

### 📢 We're happy to announce that the first phase of this feature was released with Elementor **v3.13.0**! 🥳 

✅ Feel free to check it out and update your plugin to the new version!

Cheers 🥂
