### ISSUE TITLE
UI improvement

### ISSUE THREAD

**Issue by LogoLogics2** [elementor/elementor#11955] opened 2020-07-26 22:30 UTC
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

I love Elementor, but stumbled upon a video about Divi Theme builder. 
There is the option to for example just drag to add more spacing, instead of having to go to the advanced tab and adjust the margins or add a spacer in between or even just drag a column to overlap another, while in Elementor that needs to be done in multiple steps in advanced tab and play with Z index etc.

**Describe the solution you'd like**
Improve the UI to enable these actions like Divi:
like this: https://youtu.be/fwQ0IXiqGYU

**Comment by arielk** [comment] 2020-07-28 07:40
Duplicate of https://github.com/elementor/elementor/issues/5018

**Closed by arielk** 2020-07-28 07:40 UTC
