### ISSUE TITLE
Edit with Elementor button is missing

### ISSUE THREAD

**Issue by DaNTaF** [elementor/elementor#11830] opened 2020-07-09 20:46 UTC
Hey
If I enabled Gutenberg v8.5.1 it makes  Elementor button missing.
![2020-07-09_23-34-03](https://user-images.githubusercontent.com/9018485/87088918-459e8900-c23e-11ea-91bc-f4ef08c33808.jpg)
![2020-07-09_23-33-17](https://user-images.githubusercontent.com/9018485/87088921-46cfb600-c23e-11ea-831f-8d90b8e8efca.jpg)

**Comment by zoliszabo** [comment] 2020-07-14 09:09
I can second this issue. After upgrading Gutenberg from 8.3.0 to 8.5.1, I've observed this behaviour.

In my case it is a "default" LTR / english installation.

I did not test with in-between Gutenberg versions, but a quick debugging shows that the parent element Elementor appends the button (`#edit-post-header-toolbar`) is re-rendered afterwards (using react).

**Comment by Worldwebscapes** [comment] 2020-07-16 18:09
I can replicate this. If the new Gutenberg plugin is enabled, there is no edit with Elementor button.
![image](https://user-images.githubusercontent.com/7572038/87706722-f8567600-c76d-11ea-81eb-8076c7f90052.png)

**Comment by liewcf** [comment] 2020-07-17 01:53
I can confirm that the "Edit with Elementor" button is not found in **WordPress 5.5-beta2-48501**
"Edit with Elementor" link is not found in post/page list too.

**Comment by chaselifetech** [comment] 2020-07-17 07:56
I can also confirm if it helps that the brizy button does not appear either.

**Comment by parasshah195** [comment] 2020-07-19 11:53
It's discussed in detail in this issue present in the Gutenberg's repo - https://github.com/WordPress/gutenberg/issues/23645

Highlights the cause and also hints towards a potential fix (which seems to be making the button "tabbable" for accessibility purposes).

Hoping that this is patched before 5.5 release

**Comment by chaselifetech** [comment] 2020-07-19 13:40
I'm guessing this is something elementor will have to fix

**Comment by shilo-ey** [comment] 2020-07-26 12:50
This issue has been resolved in Elementor v2.9.14

Feel free to update

Thanks!

**Comment by shilo-ey** [comment] 2020-07-26 12:50
This issue has been resolved in Elementor v2.9.14

Feel free to update

Thanks!

**Closed by shilo-ey** 2020-07-26 12:50 UTC
Labels: compatibility, status/merged

**Comment by ElisaBajcic** [comment] 2021-04-24 14:43
Hi there! I'm having the same issue after updating Elementor plugin right now.
Any idea about how to troubleshoot it?

thanks in advance to all the Community
