### ISSUE TITLE
Having problem with pages on Elementor - sidebar items disappear

### ISSUE THREAD

**Issue by Sara7887** [elementor/elementor#14689] opened 2021-04-25 08:48 UTC
Since 2 days I cannot style some elements in Elementor pages, more specifically images and sometimes other elements too. When I click on an image, the items on the left sidebar menu disappear and I can't modify neither the contents, nor the style nor advanced settings. Neither can I ask for support, just a blank grey sidebar. I'm working on a website with other 2 people, who don't have this problem. I'm pretty new to CMS world and I have no coding skills, just basic HTML and CSS. Hope this infos can help you: PHP version 7.3.25, Wordpress (Altervista) version 5.6.2, Theme Storefront version 3.5.1
![Schermata 2021-04-25 alle 10 46 11](https://user-images.githubusercontent.com/83159077/115987007-7e340700-a5b3-11eb-800c-cb3c22182a71.png)
That's the way the sidebar looks when I click on "modify the image".
Thank you all in advance!

**Comment by shilo-ey** [comment] 2021-04-25 09:10
Duplicate of #14642

**Closed by shilo-ey** 2021-04-25 09:10 UTC
