### ISSUE TITLE
Post Carousel

### ISSUE THREAD

**Issue by sheli21** [elementor/elementor#7536] opened 2019-03-19 08:08 UTC
I have been using the post carousel from the suggested elementor add-ons you have on your website. but it conflicts with the elementor code and it doesn't work. It repeats the name of the post in the excerpt and in sometimes it doesn't even pull the excerpt text through at all. Please make a post carousel widget because then yours will work and I won't have conflict problems coming in from the add-ons! Also its really expensive to have to buy add-ons when I also paid for elementor! 
<img width="1228" alt="Screen Shot 2019-03-18 at 10 35 26" src="https://user-images.githubusercontent.com/20577455/54589626-cffe2080-4a2e-11e9-89d6-d34a149d32c0.png">

**Comment by shilo-ey** [comment] 2019-03-19 09:17
Duplicate of #219

**Closed by shilo-ey** 2019-03-19 09:17 UTC
