### ISSUE TITLE
⛔ 🧩 Error: Class "Elementor\Core\Schemes\Typography"

### ISSUE THREAD

**Issue by AlexPBrin** [elementor/elementor#29606] opened 2024-12-17 03:58 UTC
### Prerequisites

- [ ] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [ ] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

my theme uses a custom plugin that taps into elementor for 

```
Error: Class "Elementor\Core\Schemes\Typography", which seams to have disappeard in the new version

$this->add_group_control(
            Group_Control_Typography::get_type(),
            [
                'name' => 'field_typography',
                'label' => esc_html__( 'Typography', 'rsaddon' ),
                'selector' => '{{WRAPPER}} .wpcf7-form-control:not(.wpcf7-submit)',
                **'scheme' => Typography::TYPOGRAPHY_3**
            ]
        );
```

### Steps to reproduce

plugin activated with new version, i looked in the new doc on whats the new way to how to access Typography found nothing

### Expected behavior

i would expect proper documentation or backwards compatibility

### Isolating the problem

- [ ] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [ ] This bug happens with the Hello Elementor theme active.
- [X] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

<details>
<summary>Click to reveal</summary>

````txt


== Server Environment ==
	Operating System: Linux
	Software: LiteSpeed
	MySQL version: MariaDB Server v10.5.25
	PHP Version: 8.0.30
	PHP Memory Limit: 768M
	PHP Max Input Vars: 10000
	PHP Max Post Size: 128M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.7.1
	Site URL: https://festivaljoyeux.ca/mont-laurier
	Home URL: https://festivaljoyeux.ca/mont-laurier
	WP Multisite: Yes
	Max Upload Size: 1 Mo
	Memory limit: 64M
	Max Memory limit: 768M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: fr_FR
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: Evenio Child Mont-Tremblant
	Version: 1.0
	Author: RS Theme
	Child Theme: Yes
	Parent Theme Name: Evenio
	Parent Theme Version: 2.0.1
	Parent Theme Author: RS Theme

== User ==
	Role: administrator
	WP Profile lang: fr-FR
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36

== Active Plugins ==
	Complianz | GDPR/CCPA Cookie Consent
		Version: 7.1.5
		Author: Really Simple Plugins

	conceptc-mods-joyt
		Version: 1.0.0
		Author: Alexandre Poirier-Brin

	Contact Form 7
		Version: 6.0.1
		Author: Takayuki Miyoshi

	Elementor
		Version: 3.25.11
		Author: Elementor.com

	MC4WP: Mailchimp for WordPress
		Version: 4.9.19
		Author: ibericode

	Redux Framework
		Version: 4.5.4
		Author: Team Redux

	RSElements
		Version: 1.0.3
		Author: rs-theme

	RS Framework
		Version: 1.0.1
		Author: RS Theme

	Yoast SEO
		Version: 24.0
		Author: Team Yoast


== Network Plugins ==
	Wordfence Security
		Version: 8.0.1
		Author: Wordfence

	WPBakery Page Builder
		Version: 8.1
		Author: Michael M - WPBakery.com

	WP Rollback
		Version: 2.0.7
		Author: WP Rollback

	WP Umbrella
		Version: 2.17.1
		Author: WP Umbrella - Backup & Manage WordPress


== Must-Use Plugins ==
	WP Umbrella
		Version: 1.0.0
		Author: WP Umbrella

	_WPHealthHandlerMU.php
		Version: 
		Author: 


== Expériences d’Elementor ==
	Improved CSS Loading: Inactif par défaut
	Polices d’icônes « inline »: Inactif par défaut
	Points d’arrêt personnalisés supplémentaires: Actif par défaut
	Conteneur: Inactif par défaut
	Mettre à niveau la bibliothèque Swiper: Actif par défaut
	Performances des éléments imbriqués: Actif par défaut
	Optimized Control Loading: Actif par défaut
	Balisage optimisé: Inactif par défaut
	Conditionally load Swiper CSS files: Inactif par défaut
	Intégration d’extension: Actif par défaut
	CSS Smooth Scroll: Actif par défaut
	Écran d’accueil Elementor: Actif par défaut
	Page d’atterrissage: Actif par défaut
	Éléments imbriqués: Actif par défaut
	Barre supérieure de l’éditeur: Actif par défaut
	Panneau des pages: Inactif par défaut
	Mise en cache d’éléments: Inactif par défaut
	Lien en bio: Actif par défaut
	Boutons flottants: Actif par défaut
	Évènements de l’éditeur Elementor: Inactif par défaut
	Atomic Widgets: Inactif par défaut
	Launchpad Checklist: Inactif par défaut


== Journal ==
	
Log: showing 20 of 432024-04-30 15:22:15 [info] Elementor/Upgrades - _on_each_version Finished 
2024-04-30 15:22:15 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.21.3',
  'to' => '3.21.4',
)]
2024-05-08 12:59:28 [info] elementor::elementor_updater Started 
2024-05-08 12:59:28 [info] Elementor/Upgrades - _on_each_version Start  
2024-05-08 12:59:28 [info] Elementor/Upgrades - _on_each_version Finished 
2024-05-08 12:59:28 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.21.4',
  'to' => '3.21.5',
)]
2024-05-08 12:59:29 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.21.4',
  'to' => '3.21.5',
)]
2024-05-29 12:59:40 [info] elementor::elementor_updater Started 
2024-05-29 12:59:40 [info] Elementor/Upgrades - _on_each_version Start  
2024-05-29 12:59:40 [info] Elementor/Upgrades - _on_each_version Finished 
2024-05-29 12:59:40 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.21.5',
  'to' => '3.21.8',
)]
2024-06-16 15:52:08 [info] elementor::elementor_updater Started 
2024-06-16 15:52:08 [info] Elementor/Upgrades - _on_each_version Start  
2024-06-16 15:52:08 [info] Elementor/Upgrades - _on_each_version Finished 
2024-06-16 15:52:08 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.21.8',
  'to' => '3.22.0',
)]
2024-06-16 15:52:09 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.21.8',
  'to' => '3.22.0',
)]
2024-12-17 03:00:34 [info] elementor::elementor_updater Started 
2024-12-17 03:00:34 [info] Elementor/Upgrades - _on_each_version Start  
2024-12-17 03:00:34 [info] Elementor/Upgrades - _on_each_version Finished 
2024-12-17 03:00:34 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.22.0',
  'to' => '3.26.0',
)]



== Elementor - Compatibility Tag ==

````

</details>

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by nicholaszein** [comment] 2024-12-17 04:36
Hello @AlexPBrin,

Thank you for reaching out! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
- This method was deprecated since version 3.0.0, released in 2020, more than 4 years ago. 
- Elementor has consistently given developers enough time to update their code.
- There were multiple notifications in multiple places, including pinned at the top of this repository, and sent in the official Developers Newsletter:
   - https://github.com/elementor/elementor/issues/29436
   - https://github.com/orgs/elementor/discussions/29437
   - https://github.com/orgs/elementor/discussions/28960
   - https://developers.elementor.com/elementor-3-26-beta/
   - https://developers.elementor.com/elementor-3-26-developers-update/
   - https://www.facebook.com/groups/Elementors/permalink/8193755707416810/
   - https://www.facebook.com/groups/Elementors/permalink/8211471138978600/
   - https://www.facebook.com/groups/Elementors/permalink/8485623218230056/
   - https://www.facebook.com/groups/Elementors/permalink/8527891794003198/
   - https://discord.com/channels/1164474724626206720/1196718453751562311/1310615448068558848
   - https://discord.com/channels/1164474724626206720/1196718453751562311/1311248027960344607
   - https://discord.com/channels/1164474724626206720/1196718453751562311/1316768076334628925
   - https://developers.elementor.com/docs/getting-started/best-practices/
   - https://developers.elementor.com/recent-deprecations/
   - https://developers.elementor.com/docs/deprecations/
   - https://elementor.com/pages/addon-developers-corner/

The documentation is publicly accessible, and easy to follow. We postponed the removal of this feature multiple times, including one more than a year ago on July/September 2023.

We are unable to continue to add backward compatibility to this method anymore.

### ✅ What you can do to solve your issue:
- Rollback Elementor to the previous version: https://elementor.com/help/rolling-back-to-a-previous-version-of-elementor/
- Contact your theme developer and share these resources with them. They are responsible for maintaining their code up-to-date. Elementor even offers an easy to use tool called Elementor [Deprecated Code Detector](https://github.com/matipojo/elementor-deprecated-code-detector), to help them maintain their code up-to-date.

### ⚠️ Note that GitHub issues are reserved for Elementor specific 🐞 Bug Reports only, and should not be used for 3rd-party theme or plugin support.

❔ If you have questions, or need guidance, help, or general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) The main Facebook group where all kinds of users come together to help each other.
- [Elementor Academy](https://elementor.com/academy) Learn everything you need to know about using Elementor.
- [Elementor Developers Documentation](https://developers.elementor.com/) Learn everything about our Developer-API.
- [Free Support Forum](https://wordpress.org/support/plugin/elementor) Get help on WordPress.org.

💎 If you have an active [Elementor Pro](https://elementor.com/pro) license you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

### 👍 For now, that's all we can help with. 

Kind regards

**Closed by nicholaszein** 2024-12-17 04:36 UTC
Labels: compatibility/3rd-party, component/code, compatibility/backwards, mod*, controls, mod/b*
