### ISSUE TITLE
Dynamic color not working on gradient

### ISSUE THREAD

**Issue by elasticeye** [elementor/elementor#10890] opened 2020-03-18 21:59 UTC
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

When using dynamic color with ACF color picker in gradient color option, it only selects the first gradient, and use that as color on the whole screen (the "bottom" gradient is not used)

## Steps to reproduce

I recorded a video: [https://hei.vegardbell.no/v/xS1YQH](https://hei.vegardbell.no/v/xS1YQH)

## Isolating the problem
- [] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

**Comment by rodolphebertozzo** [comment] 2020-03-18 22:35
#10885

**Comment by rodolphebertozzo** [comment] 2020-03-18 22:35
+1

**Comment by shilo-ey** [comment] 2020-03-19 08:44
Duplicate of #10885

**Closed by shilo-ey** 2020-03-19 08:44 UTC

**Comment by vovkasolovev** [comment] 2020-04-24 23:17
Same thing with JetEngine Custom Fields. Gradient first Dynamic color sets as background color.

**Comment by dkalive2017** [comment] 2020-06-04 09:17
Any update on this?

**Comment by richcoy** [comment] 2021-03-30 13:37
This issue still exists in March of 2021.

**Comment by sivabvarghese** [comment] 2022-11-01 13:50
The issue still exists in November of 2022.

**Comment by cazper57** [comment] 2023-04-23 19:55
The issue still exists in April of 2023.
why is the post closed?

**Comment by natequreshi** [comment] 2024-09-14 15:52
You know guys this still not fixed by JetEngine because its their fault not solving or fixing this particular nonsense problem that people just left for discussion.
