### ISSUE TITLE
Add GLOBAL padding and margin settings

### ISSUE THREAD

**Issue by erwinmoojen** [elementor/elementor#9721] opened 2019-11-29 09:34 UTC
Currently it is possible to set standard colors and fonts across all pages. It would be nice if we could also set the padding and margin for sections, as wel as the font size for H1 up to H6 tags.

**Comment by bainternet** [comment] 2019-11-29 11:22
Thanks for the feedback,
Please follow guidelines for opening a new [feature request](https://github.com/pojome/elementor/issues/new?template=Feature_request.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Description and examples.

**Comment by bainternet** [comment] 2019-11-29 11:23
Duplicate of #5252

**Closed by bainternet** 2019-11-29 11:23 UTC
