### ISSUE TITLE
[Bug] Adding colors to the color picker

### ISSUE THREAD

**Issue by avermat** [elementor/elementor#10452] opened 2020-02-07 20:59 UTC
Adding column background colors to the color picker doesn't work. All colors get added as black (#000000) instead of the color shown. Here's a video of the issue:
https://www.dropbox.com/s/f6k9egitwmx9mf7/color-picker-bug.mp4?dl=0

I'm using the latest Elementor, Elementor Pro, and Astra (no plugins).

**Comment by jazir5** [comment] 2020-02-11 22:05
Can confirm i am getting the same error on multiple sites that i maintain

**Comment by bitojoe** [comment] 2020-02-18 20:47
I get this bug from time to time too - My fix is to pick a random color within the color picker, paste in the hex over again, and then press the plug button.

**Comment by lior-sh** [comment] 2020-03-08 11:49
Hi @avermat,

This bug is not reproducible. Can you please recheck it?

Thanks.

**Comment by avermat** [comment] 2020-03-09 02:35
> Hi @avermat,
> 
> This bug is not reproducible. Can you please recheck it?
> 
> Thanks.

I can still produce it on my end on multiple sites. I even just spun up a brand new local flywheel install and could reproduce it again there as well (base TwentyTwenty theme and Elementor). Here's another screencast of it: https://www.dropbox.com/s/wkt4tbn8agl5lie/column-color.mp4?dl=0

**Comment by nullmem** [comment] 2020-03-18 15:02
I am able to reproduce this bug. 

https://imagebin.ca/v/5G3CWFMX0DJV

While I am at it, why is there no way to delete these added colors from pallet??

**Comment by nullmem** [comment] 2020-03-18 15:56
In order to provide some context into what exactly is going wrong and provide better clarity on how to reproduce this bug, I have did some testing to confirm my theory.

In order to reproduce you need to:

1. Assign a color to any object/widget/background/text (doesn't seem to matter what gets changed or where)
2. Save the page and exit to dashboard.
3. Again edit this page/template/popup (again it doesn't matter where) in Elementor
4. Pick click the color you assigned earlier using color picker and click the "+" sign to add it.

What seems to be happening here is when the page loads the color value is not loaded into the color picker add function.

**Comment by lior-sh** [comment] 2020-03-26 14:01
Hi @avermat,

Currently, this issue is known and already been reported on,
We are working on a solution that will resolve this issue.
For the meanwhile, you can make a slight change in the picker to avoid saving the black color.

Thanks.

**Comment by MichaelDarko** [comment] 2020-03-30 16:11
There is also a different but related bug to this.

When you save a black color (#000000) into your saved colors, applying it to an element doesn't work on a first try - you have to switch to a different color and then select the black color again.

**Steps to reproduce:**

1. Save #000000 color into your saved colors
2. Now select some widget with color options
3. Try selecting the saved black color
4. The color doesn't change

Any time you switch between widgets and try selecting the saved black color, it doesn't do anything.

I've tested it many times and it's only happening with #000000 color. Other colors work ok.

**Comment by shilo-ey** [comment] 2020-08-26 16:22
This issue has been resolved in Elementor v3.0.0

Feel free to update

Thanks!

**Closed by shilo-ey** 2020-08-26 16:22 UTC
Labels: bug
