### ISSUE TITLE
🚀 Ajax Add to cart in elementor

### ISSUE THREAD

**Issue by Michaelgimii** [elementor/elementor#18627] opened 2022-05-11 19:37 UTC
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

Please add the possibility of adding to the cart as Ajax to the Add to cart widget. This feature is much needed.

### Describe the solution you'd like

 Ajax Add to cart for Add to cart widget

**Comment by 79ho3ein** [comment] 2022-05-11 19:51
+1

**Comment by rami-elementor** [comment] 2022-05-15 07:06
Duplicate of #18628

**Closed by rami-elementor** 2022-05-15 07:06 UTC
Labels: request/feature, product/pro, component/woocommerce
