### ISSUE TITLE
Elementor Column padding not working....? 

### ISSUE THREAD

**Issue by monparaashvin** [elementor/elementor#15126] opened 2021-05-28 04:08 UTC
Elementor padding not working i have add padding in column bellow screenshot..

[screnshot](https://tinyurl.com/yzznvjwf)

**Comment by Nazrinn** [comment] 2021-05-28 05:13
Something looks like it's overriding your column padding somewhere. Most likely an issue with your theme.

**Comment by Aviad-Herman** [comment] 2021-05-30 15:24
Hey, thanks for the input.
This is not a bug so I'll be closing this issue but I am interested in seeing why this happens.
If you have the time, feel free to schedule with me using https://calendly.com/aviadh/feedback-session-with-elementor
Thanks @monparaashvin

**Closed by Aviad-Herman** 2021-05-30 15:24 UTC
