### ISSUE TITLE
Discord icon on the Social icons

### ISSUE THREAD

**Issue by SlavaIskov** [elementor/elementor#7213] opened 2019-02-26 06:25 UTC
Good morning to this support group,
I want to know how I add this icon to my Elementor?
I found a plugin that could help me but I do not know what to do next to add it to the Social Icons?
Should I program the plugin for this? And if so, where it is to program it, or there is a simpler and simpler solution.
Thank you very much for your support

**Comment by shilo-ey** [comment] 2019-02-26 08:37
Duplicate of #5513 #3106 #4430

**Comment by shilo-ey** [comment] 2019-02-26 08:37
Thanks for the feedback,
Please follow guidelines for opening a new [feature request](https://github.com/pojome/elementor/issues/new?template=Feature_request.md), so we can help you better.
This report is missing key information: 

* Prerequisites.

**Closed by shilo-ey** 2019-02-26 08:37 UTC
