### ISSUE TITLE
⛔ 🐞 Bug Report: Call to undefined method Elementor\Core\DocumentTypes\Post::print_content()

### ISSUE THREAD

**Issue by jamieburchell** [elementor/elementor#22202] opened 2023-04-26 09:59 UTC
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

```
PHP Fatal error:  Uncaught Error: Call to undefined method Elementor\Core\DocumentTypes\Post::print_content() in ../plugins/elementor-pro/modules/loop-builder/skins/skin-loop-base.php:250
Stack trace:
#0 ../plugins/elementor-pro/modules/posts/skins/skin-base.php(873): ElementorPro\Modules\LoopBuilder\Skins\Skin_Loop_Base->render_post()
#1 ../plugins/elementor-pro/modules/loop-builder/skins/skin-loop-base.php(87): ElementorPro\Modules\Posts\Skins\Skin_Base->render()
#2 ../plugins/elementor/includes/base/skin-base.php(66): ElementorPro\Modules\LoopBuilder\Skins\Skin_Loop_Base->render()
#3 ../plugins/elementor/includes/base/skin-base.php(74): Elementor\Skin_Base->render_static()
#4 ../plugins/elementor/includes/base/widget-base.php(607): Elementor\Skin_Base->render_by_mode()
#5 ../plugins/elementor/includes/base/widget-base.php(750): Elementor\Widget_Base->render_content()
#6 ../plugins/elementor/includes/base/element-base.php(449): Elementor\Widget_Base->print_content()
#7 ../plugins/elementor/includes/base/element-base.php(1354): Elementor\Element_Base->print_element()
#8 ../plugins/elementor/includes/base/element-base.php(449): Elementor\Element_Base->print_content()
#9 ../plugins/elementor/core/base/document.php(1680): Elementor\Element_Base->print_element()
#10 ../plugins/elementor-pro/modules/theme-builder/documents/theme-document.php(418): Elementor\Core\Base\Document->print_elements(Array)
#11 ../plugins/elementor/includes/frontend.php(1179): ElementorPro\Modules\ThemeBuilder\Documents\Theme_Document->print_elements_with_wrapper(Array)
#12 ../plugins/elementor/includes/frontend.php(1074): Elementor\Frontend->get_builder_content(2672)
#13 /var/www/web/wp/wp-includes/class-wp-hook.php(308): Elementor\Frontend->apply_builder_in_content('')
#14 /var/www/web/wp/wp-includes/plugin.php(205): WP_Hook->apply_filters('', Array)
#15 /var/www/web/wp/wp-includes/post-template.php(255): apply_filters('the_content', '')
#16 ../plugins/elementor/modules/page-templates/module.php(190): the_content()
#17 [internal function]: Elementor\Modules\PageTemplates\Module->print_callback()
#18 ../plugins/elementor/modules/page-templates/module.php(207): call_user_func(Array)
#19 ../plugins/elementor/modules/page-templates/templates/canvas.php(38): Elementor\Modules\PageTemplates\Module->print_content()
#20 /var/www/web/wp/wp-includes/template-loader.php(106): include('/var/www/vhosts...')
#21 /var/www/web/wp/wp-blog-header.php(19): require_once('/var/www/vhosts...')
#22 /var/www/web/index.php(6): require('/var/www/vhosts...')
#23 {main}
  thrown in ../plugins/elementor-pro/modules/loop-builder/skins/skin-loop-base.php on line 250
```

### Steps to reproduce

This error happened when I tried to edit a template I had just imported (JSON) from a working version of the same template on another website. The template contained two loop grids and both loop item templates existed at the destination. The only way I was able to resolve this was to edit the loop grids on the source template, remove the loop item templates, export, re-import and put them back in at the destination.

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently following the steps above.

### System Info

<details>
<summary>Click to reveal</summary>

````txt



					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MariaDB Server v10.5.16
	PHP Version: 8.0.28
	PHP Memory Limit: 256M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 50M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: There are some writing permissions issues with the following directories/files:
		 - WordPress root directory
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.2
	Site URL: https://www.example.com/wp
	Home URL: https://www.example.com
	WP Multisite: No
	Max Upload Size: 40 MB
	Memory limit: 40M
	Max Memory limit: 256M
	Permalink Structure: /%category%/%year%/%monthnum%/%day%/%postname%/
	Language: en-GB
	Timezone: Europe/London
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.7.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_GB
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36

== Active Plugins ==
	Code Snippets
		Version: 3.3.0
		Author: Code Snippets Pro

	DCO Comment Attachment
		Version: 2.4.0
		Author: Denis Yanchevskiy

	Ele Custom Skin
		Version: 3.1.7
		Author: Dudaster.com

	Elementor
		Version: 3.12.2
		Author: Elementor.com

	Elementor Pro
		Version: 3.12.3
		Author: Elementor.com

	Pods - Custom Content Types and Fields
		Version: 2.9.13
		Author: Pods Framework Team

	Post Types Order
		Version: 2.0.5
		Author: Nsp Code

	Rank Math SEO
		Version: 1.0.112
		Author: Rank Math

	reCaptcha by BestWebSoft
		Version: 1.70
		Author: BestWebSoft

	Spreaker Shortcode
		Version: 1.8.1
		Author: Spreaker

	W3 Total Cache
		Version: 2.3.1
		Author: BoldGrid

	Wordfence Security
		Version: 7.9.2
		Author: Wordfence


== Must-Use Plugins ==
	Bedrock Autoloader
		Version: 1.0.3
		Author: Roots

	Disable status tests
		Version: 1.0.0
		Author: Roots

	Register Theme Directory
		Version: 1.0.0
		Author: Roots


== Features ==
	Custom Fonts: 0
	Custom Icons: 0

== Integrations ==
	


== Elementor Experiments ==
	Optimised DOM Output: Active by default
	Improved asset loading: Active
	Improved CSS Loading: Active
	Inline Font Icons: Inactive
	Accessibility improvements: Active by default
	Additional Custom Breakpoints: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active
	Upgrade Swiper Library: Inactive by default
	Default to New Theme Builder: Active by default
	Hello Theme Header & Footer: Inactive by default
	Editor Top Bar: Inactive by default
	Landing pages: Active by default
	Nested Elements: Inactive by default
	Lazy Load Background Images: Inactive by default
	Page Transitions: Active by default
	Notes: Active by default
	Loop: Active by default
	Form Submissions: Active by default
	Scroll Snap: Active by default
	Menu: Inactive by default


== Log ==
	
Log: showing 20 of 362023-04-03 14:50:36 [info] Update DB has been started [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.11.7',
  'to' => '3.12.1',
)]
2023-04-03 14:50:36 [info] elementor-pro::elementor_pro_updater Started 
2023-04-03 14:50:36 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-04-03 14:50:36 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-04-03 14:50:36 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.11.7',
  'to' => '3.12.1',
)]
2023-04-12 12:10:16 [info] Update DB has been started [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.12.1',
  'to' => '3.12.2',
)]
2023-04-12 12:10:16 [info] elementor-pro::elementor_pro_updater Started 
2023-04-12 12:10:16 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-04-12 12:10:16 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-04-12 12:10:16 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.12.1',
  'to' => '3.12.2',
)]
2023-04-24 10:20:18 [info] Update DB has been started [array (
  'plugin' => 'Elementor',
  'from' => '3.12.1',
  'to' => '3.12.2',
)]
2023-04-24 10:20:18 [info] elementor::elementor_updater Started 
2023-04-24 10:20:18 [info] Elementor/Upgrades - _on_each_version Start  
2023-04-24 10:20:18 [info] Elementor/Upgrades - _on_each_version Finished 
2023-04-24 10:20:18 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.12.1',
  'to' => '3.12.2',
)]
2023-04-24 11:17:55 [info] Update DB has been started [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.12.2',
  'to' => '3.12.3',
)]
2023-04-24 11:17:55 [info] elementor-pro::elementor_pro_updater Started 
2023-04-24 11:17:55 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-04-24 11:17:55 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-04-24 11:17:55 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.12.2',
  'to' => '3.12.3',
)]

PHP: showing 6 of 6PHP: 2023-04-12 13:11:16 [warning X 10][../plugins/elementor/core/common/modules/ajax/module.php::175] Undefined array key "data" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-04-26 10:42:10 [warning X 2][../plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php::150] Undefined array key "condition_type" [array (
  'trace' => '
#0: ../plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(150): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_template_json_item()
#2: ../plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(120): class type array_map()
#3: ../plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(69): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_templates_json()
#4: ../plugins/elementor/data/base/endpoint.php(162): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> create_items()
',
)]
PHP: 2023-04-26 10:47:19 [warning X 6][../plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php::150] Undefined array key "condition_type" [array (
  'trace' => '
#0: ../plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(150): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_template_json_item()
#2: ../plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(120): class type array_map()
#3: ../plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(59): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_templates_json()
#4: ../plugins/elementor/data/base/endpoint.php(158): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> get_items()
',
)]
PHP: 2023-04-26 10:47:35 [error X 2][../plugins/elementor-pro/modules/loop-builder/skins/skin-loop-base.php::250] Uncaught Error: Call to undefined method Elementor\Core\DocumentTypes\Post::print_content() in ../plugins/elementor-pro/modules/loop-builder/skins/skin-loop-base.php:250
Stack trace:
#0 ../plugins/elementor-pro/modules/posts/skins/skin-base.php(873): ElementorPro\Modules\LoopBuilder\Skins\Skin_Loop_Base->render_post()
#1 ../plugins/elementor-pro/modules/loop-builder/skins/skin-loop-base.php(87): ElementorPro\Modules\Posts\Skins\Skin_Base->render()
#2 ../plugins/elementor/includes/base/skin-base.php(66): ElementorPro\Modules\LoopBuilder\Skins\Skin_Loop_Base->render()
#3 ../plugins/elementor/includes/base/skin-base.php(74): Elementor\Skin_Base->render_static()
#4 ../plugins/elementor/includes/base/widget-base.php(607): Elementor\Skin_Base->render_by_mode()
#5 ../plugins/elementor/includes/base/widget-base.php(750): Elementor\Widget_Base->render_content()
#6 ../plugins/elementor/includes/base/element-base.php(449): Elementor\Widget_Base->print_content()
#7 ../plugins/elementor/includes/base/element-base.php(1354): Elementor\Element_Base->print_element()
#8 ../plugins/elementor/includes/base/element-base.php(449): Elementor\Element_Base->print_content()
#9 ../plugins/elementor/core/base/document.php(1680): Elementor\Element_Base->print_element()
#10 ../plugins/elementor-pro/modules/theme-builder/documents/theme-document.php(418): Elementor\Core\Base\Document->print_elements(Array)
#11 ../plugins/elementor/includes/frontend.php(1179): ElementorPro\Modules\ThemeBuilder\Documents\Theme_Document->print_elements_with_wrapper(Array)
#12 ../plugins/elementor/includes/frontend.php(1074): Elementor\Frontend->get_builder_content(2638)
#13 /var/www/web/wp/wp-includes/class-wp-hook.php(308): Elementor\Frontend->apply_builder_in_content('')
#14 /var/www/web/wp/wp-includes/plugin.php(205): WP_Hook->apply_filters('', Array)
#15 /var/www/web/wp/wp-includes/post-template.php(255): apply_filters('the_content', '')
#16 ../plugins/elementor/modules/page-templates/module.php(190): the_content()
#17 [internal function]: Elementor\Modules\PageTemplates\Module->print_callback()
#18 ../plugins/elementor/modules/page-templates/module.php(207): call_user_func(Array)
#19 ../plugins/elementor/modules/page-templates/templates/canvas.php(38): Elementor\Modules\PageTemplates\Module->print_content()
#20 /var/www/web/wp/wp-includes/template-loader.php(106): include('/var/www/vhosts...')
#21 /var/www/web/wp/wp-blog-header.php(19): require_once('/var/www/vhosts...')
#22 /var/www/web/index.php(6): require('/var/www/vhosts...')
#23 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-04-26 10:47:45 [error X 1][../plugins/elementor-pro/modules/loop-builder/skins/skin-loop-base.php::250] Uncaught Error: Call to undefined method Elementor\Core\DocumentTypes\Post::print_content() in ../plugins/elementor-pro/modules/loop-builder/skins/skin-loop-base.php:250
Stack trace:
#0 ../plugins/elementor-pro/modules/posts/skins/skin-base.php(873): ElementorPro\Modules\LoopBuilder\Skins\Skin_Loop_Base->render_post()
#1 ../plugins/elementor-pro/modules/loop-builder/skins/skin-loop-base.php(87): ElementorPro\Modules\Posts\Skins\Skin_Base->render()
#2 ../plugins/elementor/includes/base/skin-base.php(79): ElementorPro\Modules\LoopBuilder\Skins\Skin_Loop_Base->render()
#3 ../plugins/elementor/includes/base/widget-base.php(607): Elementor\Skin_Base->render_by_mode()
#4 ../plugins/elementor/includes/base/widget-base.php(733): Elementor\Widget_Base->render_content()
#5 ../plugins/elementor/includes/base/element-base.php(536): Elementor\Widget_Base->get_raw_data(true)
#6 ../plugins/elementor/core/base/document.php(977): Elementor\Element_Base->get_raw_data(true)
#7 ../plugins/elementor-pro/modules/theme-builder/documents/theme-document.php(444): Elementor\Core\Base\Document->get_elements_raw_data(Array, true)
#8 ../plugins/elementor/core/base/document.php(643): ElementorPro\Modules\ThemeBuilder\Documents\Theme_Document->get_elements_raw_data(NULL, true)
#9 ../plugins/elementor/modules/library/documents/library-document.php(66): Elementor\Core\Base\Document->get_initial_config()
#10 ../plugins/elementor-pro/modules/theme-builder/documents/theme-document.php(666): Elementor\Modules\Library\Documents\Library_Document->get_initial_config()
#11 ../plugins/elementor/includes/base/controls-stack.php(1021): ElementorPro\Modules\ThemeBuilder\Documents\Theme_Document->get_initial_config()
#12 ../plugins/elementor/core/editor/config-providers/editor-common-client-settings.php(36): Elementor\Controls_Stack->get_config()
#13 ../plugins/elementor/core/editor/config-providers/editor-common-configs.php(169): Elementor\Core\Editor\Config_Providers\Editor_Common_Client_Settings::get_client_settings()
#14 ../plugins/elementor/core/editor/config-providers/editor-v1-config-provider.php(41): Elementor\Core\Editor\Config_Providers\Editor_Common_Configs::get_client_settings()
#15 ../plugins/elementor/core/editor/editor-loader.php(57): Elementor\Core\Editor\Config_Providers\Editor_V1_Config_Provider->get_client_settings()
#16 ../plugins/elementor/core/editor/editor.php(357): Elementor\Core\Editor\Editor_Loader->print_client_settings()
#17 /var/www/web/wp/wp-includes/class-wp-hook.php(308): Elementor\Core\Editor\Editor->enqueue_scripts('')
#18 /var/www/web/wp/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters('', Array)
#19 /var/www/web/wp/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#20 /var/www/web/wp/wp-includes/script-loader.php(2194): do_action('wp_enqueue_scri...')
#21 /var/www/web/wp/wp-includes/class-wp-hook.php(308): wp_enqueue_scripts('')
#22 /var/www/web/wp/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters('', Array)
#23 /var/www/web/wp/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#24 /var/www/web/wp/wp-includes/general-template.php(3049): do_action('wp_head')
#25 ../plugins/elementor/includes/editor-templates/editor-wrapper.php(31): wp_head()
#26 ../plugins/elementor/core/editor/editor-loader.php(135): include('/var/www/vhosts...')
#27 ../plugins/elementor/core/editor/editor.php(162): Elementor\Core\Editor\Editor_Loader->print_root_template()
#28 /var/www/web/wp/wp-includes/class-wp-hook.php(308): Elementor\Core\Editor\Editor->init('')
#29 /var/www/web/wp/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters('', Array)
#30 /var/www/web/wp/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#31 /var/www/web/wp/wp-admin/admin.php(419): do_action('admin_action_el...')
#32 /var/www/web/wp/wp-admin/post.php(12): require_once('/var/www/vhosts...')
#33 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-04-26 10:48:56 [error X 1][../plugins/elementor-pro/modules/loop-builder/skins/skin-loop-base.php::250] Uncaught Error: Call to undefined method Elementor\Core\DocumentTypes\Post::print_content() in ../plugins/elementor-pro/modules/loop-builder/skins/skin-loop-base.php:250
Stack trace:
#0 ../plugins/elementor-pro/modules/posts/skins/skin-base.php(873): ElementorPro\Modules\LoopBuilder\Skins\Skin_Loop_Base->render_post()
#1 ../plugins/elementor-pro/modules/loop-builder/skins/skin-loop-base.php(87): ElementorPro\Modules\Posts\Skins\Skin_Base->render()
#2 ../plugins/elementor/includes/base/skin-base.php(66): ElementorPro\Modules\LoopBuilder\Skins\Skin_Loop_Base->render()
#3 ../plugins/elementor/includes/base/skin-base.php(74): Elementor\Skin_Base->render_static()
#4 ../plugins/elementor/includes/base/widget-base.php(607): Elementor\Skin_Base->render_by_mode()
#5 ../plugins/elementor/includes/base/widget-base.php(750): Elementor\Widget_Base->render_content()
#6 ../plugins/elementor/includes/base/element-base.php(449): Elementor\Widget_Base->print_content()
#7 ../plugins/elementor/includes/base/element-base.php(1354): Elementor\Element_Base->print_element()
#8 ../plugins/elementor/includes/base/element-base.php(449): Elementor\Element_Base->print_content()
#9 ../plugins/elementor/core/base/document.php(1680): Elementor\Element_Base->print_element()
#10 ../plugins/elementor-pro/modules/theme-builder/documents/theme-document.php(418): Elementor\Core\Base\Document->print_elements(Array)
#11 ../plugins/elementor/includes/frontend.php(1179): ElementorPro\Modules\ThemeBuilder\Documents\Theme_Document->print_elements_with_wrapper(Array)
#12 ../plugins/elementor/includes/frontend.php(1074): Elementor\Frontend->get_builder_content(2672)
#13 /var/www/web/wp/wp-includes/class-wp-hook.php(308): Elementor\Frontend->apply_builder_in_content('')
#14 /var/www/web/wp/wp-includes/plugin.php(205): WP_Hook->apply_filters('', Array)
#15 /var/www/web/wp/wp-includes/post-template.php(255): apply_filters('the_content', '')
#16 ../plugins/elementor/modules/page-templates/module.php(190): the_content()
#17 [internal function]: Elementor\Modules\PageTemplates\Module->print_callback()
#18 ../plugins/elementor/modules/page-templates/module.php(207): call_user_func(Array)
#19 ../plugins/elementor/modules/page-templates/templates/canvas.php(38): Elementor\Modules\PageTemplates\Module->print_content()
#20 /var/www/web/wp/wp-includes/template-loader.php(106): include('/var/www/vhosts...')
#21 /var/www/web/wp/wp-blog-header.php(19): require_once('/var/www/vhosts...')
#22 /var/www/web/index.php(6): require('/var/www/vhosts...')
#23 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]



== Elementor - Compatibility Tag ==
	
	Ele Custom Skin: Incompatible
	Elementor Pro: Incompatible

== Elementor Pro - Compatibility Tag ==
	
	Ele Custom Skin: Incompatible
				
````

</details>

**Comment by joaodath** [comment] 2023-05-01 19:16
@nicholaszein could you give us an idea of when this will be fixed? I'm having the same issue as I mentioned in https://github.com/elementor/elementor/issues/21655#issuecomment-1513615416 
I opened a support ticket as well to see if they could find a fix.

**Comment by joaodath** [comment] 2023-05-03 17:09
@jamieburchell While the Elementor team is working on a patch for this issue, you can try following these steps to fix the page having the issue (it worked for me): 

1. Disable Loop feature;
2. Open the page with the error and export it as a template;
3. Create a new page and import the previously exported template;
4. Save it;
5. Enable Loop;
6. Edit the new page to add the missing loop again.

Hope this can help you as a workaround while the issue isn't patched.

**Comment by riteshtailor2002** [comment] 2023-08-04 13:48
I am also getting the same issue :\

**Comment by nicholaszein** [comment] 2023-09-14 17:52
Hello, everyone.

Thank you for reaching out, and apologize for not answering sooner! 🙏 

### ⛔ After reviewing your report we concluded this is not a bug caused by Elementor. The feature you're referring to is not yet supported.

As @joaodath correctly pointed out, the template system uses template IDs to reference Loop Grid Item templates. When Exporting/importing those templates the ID of each item will remain the same, and since two different sites have different IDs, the Loop Item templates will be missing.

While we do understand this is not the expected behavior, we are still working on a solution for this mechanism. However, we don't have an ETA of when we will be releasing this solution yet.

If you think this should be an Elementor feature, please submit a new [🚀 Feature Request](https://github.com/orgs/elementor/discussions/new?category=feature-request), and we will consider it in the future if there is enough demand (votes) from other users.

Kind regards

**Closed by nicholaszein** 2023-09-14 17:52 UTC
Labels: product/pro, component/theme-builder, component/export/import, type/templates, component/loop-builder, mod*
