### ISSUE TITLE
🐞 Bug report: Deprecated : _register_controls is deprecated since version 3.1.0! Use Elementor\Controls_Stack::register_controls() instead. in /var/www/html/wp-includes/functions.php on line 5323

### ISSUE THREAD

**Issue by phongvu1108** [elementor/elementor#18515] opened 2022-04-27 08:54 UTC
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Our site this prolem: **Deprecated: _register_controls**

Deprecated: _register_controls is deprecatedsince version 3.1.0! Use Elementor\Controls_Stack::register_controls() instead. in/var/www/html/wp-includes/functions.phpon line5323

our site: [https://app.appsheet.vn/](https://app.appsheet.vn)

**i finish step by step. But not fix.**

Go to WP dashboard > Elementor > Tools > Version Control.
In the Beta Tester field, change the value to Disabled.
Click Save Changes.
Go to WP dashboard > Elementor > Settings > Experiments.
Change all of the experiments to Inactive.
Click Save Changes.
Refresh the user’s website.
Is the issue still appearing?
YES – The issue is not related to an unstable Elementor version.
NO – The issue is related to an unstable Elementor version.
Please make sure that all of your Plug-ins and Theme are updated.
Sometimes it isn’t obvious that there is a plugin update available. Go to WordPress Dashboard > Updates and click the Check Again button to be sure.
Please also regenerate the CSS via Elementor > Tools > Regenerate CSS on your WordPress Dashboard,
then make sure that you are clear:
your WordPress cache (your WordPress plugin if you have one), your server cache (if
you have one. In this case, you can contact your hosting provider).
Please deactivate all your plugins besides Elementor and see if it helps. If it solves the issue, reactivate them one by one to find the culprit. If it didn’t help, switch your theme (temporarily) and see if it makes any difference.

Can you help me pro! 🙂

### Steps to reproduce

Go to WP dashboard > Elementor > Tools > Version Control.
In the Beta Tester field, change the value to Disabled.
Click Save Changes.
Go to WP dashboard > Elementor > Settings > Experiments.
Change all of the experiments to Inactive.
Click Save Changes.
Refresh the user’s website.
Is the issue still appearing?
YES – The issue is not related to an unstable Elementor version.
NO – The issue is related to an unstable Elementor version.
Please make sure that all of your Plug-ins and Theme are updated.
Sometimes it isn’t obvious that there is a plugin update available. Go to WordPress Dashboard > Updates and click the Check Again button to be sure.
Please also regenerate the CSS via Elementor > Tools > Regenerate CSS on your WordPress Dashboard,
then make sure that you are clear:
your WordPress cache (your WordPress plugin if you have one), your server cache (if
you have one. In this case, you can contact your hosting provider).
Please deactivate all your plugins besides Elementor and see if it helps. If it solves the issue, reactivate them one by one to find the culprit. If it didn’t help, switch your theme (temporarily) and see if it makes any difference.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently using the steps above.

### System Info

Our site this prolem: **Deprecated: _register_controls**

Deprecated: _register_controls is deprecatedsince version 3.1.0! Use Elementor\Controls_Stack::register_controls() instead. in/var/www/html/wp-includes/functions.phpon line5323

our site: [https://app.appsheet.vn/](https://app.appsheet.vn)

**Comment by rami-elementor** [comment] 2022-05-01 11:25
Duplicate of #18234

**Closed by rami-elementor** 2022-05-01 11:25 UTC
Labels: bug
